### ISSUE TITLE
Review InvokeAllExceptAsync API

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#1008]
We should look at most common ways to pass connections to InvokeAllExceptAsync and decide what is the most useful argument type. See https://github.com/aspnet/SignalR/pull/1007

**Comment by muratg** [comment]
@davidfowl thoughts?

**Comment by anurse** [comment]
I think we can be good with the `IReadOnlyList` API for preview 1. It's the base on which any overloads would be built anyway.
