### ISSUE TITLE
Confused regarding the correct packages and dependencies again.

### ISSUE THREAD

**Issue by simonpbond** [aspnet/SignalR#1011]
I've just updated my .NET project to:

Signalr's v1.0.0-alpha2-final , however I can't seem to find an alpha2 for SignalR.Http , is this on the way? or has it been deprecated for something else?

When using the old SignalR.Http my IHubConnection now requires an IHubProtocol parameter, and I'm unsure what I should be doing there.

As always, thanks for the help.

**Comment by BrennanConroy** [comment]
It got renamed to just `Microsoft.AspNetCore.SignalR`.
For `HubConnection` you can use the new `HubConnectionBuilder` to make it easier on yourself.
https://github.com/aspnet/SignalR-samples/blob/0b81c259e704a3b46079bdcf0e625907c7c409c0/StockTickR/CsharpClient/Program.cs#L19

**Comment by simonpbond** [comment]
Thank you so much Brennan. 👍
