### ISSUE TITLE
Specify our pattern for JWT bearer auth. Write a sample at minimum and explore the API.

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#1018]

**Comment by Havret** [comment]
It would be very nice to have an opinionated approach. I was googling for a while to find out that the only way to pass JWT bearer is through qs.

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR/issues/1039

**Comment by moozzyk** [comment]
0bafb304c2707739578e635bc9e00d0cd36420a7..4394b57143ad0517333ffbe88848fbb68264a614
