### ISSUE TITLE
Discover hubs regargless of its visibility

### ISSUE THREAD

**Issue by xperiandri** [aspnet/SignalR#102]
What is the purpose to expose hubs from my app as public?

**Comment by moozzyk** [comment]
What would be the purpose to expose hubs that are not to be public?

**Comment by xperiandri** [comment]
If I have some services which my hub depends on and I don't want them, to be public.
The need of making hubs public forces me to make all the hierarchy of their dependencies public.

**Comment by moozzyk** [comment]
How would you handle this if this wouldn't be RPC but just regular library? Because from a regular library you would not be able to "export" non-public methods. 
Why don't you inject your services - composition is oftentimes better than inheritance. Or create a Hub that wraps what you currently have and expose only what you need.

**Comment by xperiandri** [comment]
Imagine I have `HubX` which depends on `Service1` which depends on `Service2`.
If you do not write unit tests or has some trivial functionality you don't need interfaces for this services.
Now when `HubX` must be public, then Service1 and Service2 must be public!

**Comment by moozzyk** [comment]
One way of doing this would be:

```C#
internal class Service1
{
    public string GetValue() { return "test"; }
}

public class Chat : Hub
{
    private readonly Service1 _service;

    public Chat(IServiceProvider sp)
    {
        _service = sp.GetRequiredService<Service1>();
    }

   public async Task Send(string message)
    {
        await Clients.All.InvokeAsync("Send", $"{ _service.GetValue() }");
    }
}
```
Where the service is registered like this: 

```C#
services.AddSingleton<Service1>();
```

**Comment by xperiandri** [comment]
It is a workaround.
I can't just understand an intent of additional check for visibility if it does not produce any value
