### ISSUE TITLE
 Error during WebSocket handshake: Unexpected response code: 204

### ISSUE THREAD

**Issue by KeithGarry** [aspnet/SignalR#1028]
I'm attempting to use SignalR on my local machine, but it appears that IIS/Express on Windows 7 isn't supported.  What are my options for local machine developing?  

> The WebSockets transport will not work if the server hosting SignalR is running behind IIS on Windows 7 or Windows Server 2008 R2, due to limitations in IIS

In case I'm missing something and Express *is* supported here is the error I'm getting:

> VM46:164 WebSocket connection to 'ws://localhost:60609/chat?id=9d69e64f-eed1-4b28-af25-a34b8a963ec9' failed: Error during WebSocket handshake: Unexpected response code: 204
WrappedWebSocket @ VM46:164
(anonymous) @ signalr-clientES5-1.0.0-alpha2-final.min.js:1
t @ signalr-clientES5-1.0.0-alpha2-final.min.js:1
value @ signalr-clientES5-1.0.0-alpha2-final.min.js:1
(anonymous) @ signalr-clientES5-1.0.0-alpha2-final.min.js:1
r @ signalr-clientES5-1.0.0-alpha2-final.min.js:1
(anonymous) @ signalr-clientES5-1.0.0-alpha2-final.min.js:1
e.(anonymous function) @ signalr-clientES5-1.0.0-alpha2-final.min.js:1
a @ signalr-clientES5-1.0.0-alpha2-final.min.js:1
signalr-clientES5-1.0.0-alpha2-final.min.js:1 Error: Failed to start the connection. undefined
home:1 Uncaught (in promise) undefined

I have deployed to azure and the code works fine.  What are my options to get this running locally?

**Comment by moozzyk** [comment]
Only WebSockets transport is not supported *if* you use IIS. You can either use other transports (ServerSentEvents, LongPolling) or skip IIS and use Kestrel directly in which case WebSockets should work.

**Comment by KeithGarry** [comment]
I apologize for editing the title but I believe there is a bigger problem going on.  Even though web sockets are not supported with IIS Express, Signal R does not fall back to a different transport.  Even specifying the transport such as : 

> connection.start({ transport: ['longPolling', 'foreverFrame', 'serverSentEvents'] })
				.then(() => connection.invoke('send', 'Hello'));

still causes the error to occur.  The code works fine in azure but I cannot get it working on the local machine.  I've tried this on 3 different machines (using windows 7) reproducing the same error.

**Comment by BrennanConroy** [comment]
There is no transport fallback in SignalR Core although @moozzyk has a sample making fallback work https://github.com/aspnet/SignalR-samples/pull/8
Also `connection.start` doesn't take any parameters. If you want to pass a transport to use it needs to be in the constructor:
```
let connection = new HubConnection("someurl", { transport: 'longPolling' });
connection.start().then(() => {});
```

And lastly, `foreverFrame` isn't a thing anymore.

**Comment by KeithGarry** [comment]
Thank you!

**Comment by og1sha** [comment]
thank you so much, it was driving me crazy :)
