### ISSUE TITLE
[Question] Solicit-Response Example 

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/SignalR#1029]
One of the thing I like about SignalR is I can move to a solicit-response model and not a request-response model. I'm just starting with this and I'm looking for some approaches to try out. The case I'm working with is a tree view. The user connects through MVC and once the page is loaded I use SignalR to interact with a tree (ol). I only sent the nodes that are active as the user clicks around, based on some user preferences.

Sometimes I need to get info from the user without their interaction. When they click a node, I start processing. At some point I need to look into their browser and get information to continue. For example, there is a value in the browser that tells me how many levels of nodes to show and if I show form the root or trim to the start node. The way I have this working is I await the building of the tree while I solicit the values from the browser. Right now, I do this in two pieces. I send the solicit, which activates a JavaScript function, and this function sends the response. The problem I'm having is with getting back to the awaited task. Is there a clean way to tie the two together? Or is this something I need an RPC library for?

**Comment by moozzyk** [comment]
Seems like you want client side results. It's discussed a bit [here](https://github.com/aspnet/SignalR/issues/903#issuecomment-332718656) (and in comments that follow) - this functionality is currently not implemented internally - you would have to handle this yourself.

**Comment by RandyBuchholz** [comment]
Thanks. That thread helped a little. I'm actually doing the inverse of that. Liked that 2-part article you did on SignalR recently BTW.

**Comment by moozzyk** [comment]
Thanks!
