### ISSUE TITLE
Ability to change query parameters on reconnect

### ISSUE THREAD

**Issue by xperiandri** [aspnet/SignalR#103]
In my scenario I connect to a hub with location of client within a query parameters.
If my client app disconnected not because of its intent and reconnected back it can be located in another place.
How can I reconnect with another data then if I cannot change query string?

**Comment by moozzyk** [comment]
In the new version of SignalR the client does not handle reconnects. If a connection is closed and you want to "reconnect" you just start a new connection with a new query string. In the old version of SignalR I would do one of two things:
- don't rely (only) on query string parameters. You can create a method in which you can update the location. You would invoke this method each time the location changes (no reconnect required)
- if the location changes you can stop and start connection with new url parameters
I think you already have to have some kind of a client id which you use to identified the client even if it uses multiple signalr connections.

**Comment by xperiandri** [comment]
So in new implementation I will never know if client was disconnected without user intent and that it connected again, will I?

**Comment by moozzyk** [comment]
You would - in case of unclean disconnect the exception parameter in the [OnDisconnectedAsync](https://github.com/aspnet/SignalR/blob/8022afd3a2644237d597b6664f553871c69a1666/src/Microsoft.AspNetCore.SignalR/Hub.cs#L69) would be not null.

**Comment by xperiandri** [comment]
That's good.
However when client connects again it will receive new connection ID. And the only way of identification will be client's authentication. Right?

**Comment by moozzyk** [comment]
As I said before: 
_I think you already have to have some kind of a client id which you use to identified the client even if it uses multiple signalr connections._
I believe that even with reconnects you have to have a kind of client id to correlate connections since reconnects are not guaranteed to succeed. The client currently closes the connection if it can't reconnect within the reconnect timeout.

**Comment by los93sol** [comment]
@moozzyk When a client doesn't disconnect cleanly i understand that the exception in ondisconnectasync will not be null but will the context or the connectionid be null in this case?

I'm having random crashes that seem to be related to OnDisconnectAsync but have not been able to reproduce it reliably.  Inside OnDisconnectAsync i am doing Console.WriteLine with Context.ConnectionId, just guessing that's likely why i haven't caught it if it's already null when the method hits.

**Comment by davidfowl** [comment]
> @moozzyk When a client doesn't disconnect cleanly i understand that the exception in ondisconnectasync will not be null but will the context or the connectionid be null in this case?

No. It shouldn't be null.
