### ISSUE TITLE
Exceptions from the ChannelObserver's OnNext method

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/SignalR#1032]
In alpha2, the `ChannelObserver.OnNext` method can throw an `OperationCanceledException` and this currently hits my application in places I didn't expect. Former SignalR didn't let these connection specific exceptions enter my application. The [guidelines](https://docs.microsoft.com/en-us/dotnet/standard/events/observer-design-pattern-best-practices#the-observer----implementing-the-onerror-method) for implementing `OnNext` suggest to not throw in the interface implementations.

The code for `OnNext` has changed since to not throw OCE, but there's still an IOE that some day might pop up (when TryWrite might start to fail).

Are SignalR specific exceptions in a stream something I have to deal with on the stream level?

**Comment by davidfowl** [comment]
@Tragetaschen do you want to send a PR for this one?

**Comment by Tragetaschen** [comment]
[There](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs#L101)'s quite some explanation about how channels work and could work that lower my confidence in any change I could make—especially since I haven't looked into channels yet.

Given my time budget right now and to my dismay: Pass :-/

**Comment by anurse** [comment]
We should prevent exceptions from escaping [`ChannelObserver.OnNext`](https://github.com/aspnet/SignalR/blob/d23f2beafc64336918e240ff670c8c71a39ed013/src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs#L50).

**Comment by mikaelm12** [comment]
Hmm, yeah. We should be letting that exception propagate into the Observable. Should we just no-op then if the channel is already closed?

**Comment by mikaelm12** [comment]
Done: 4ddf8664c0a8da3b14f147c46b971b73a39538e9
