### ISSUE TITLE
Response to HTTP OPTIONS request returns wrong "availableTransports"

### ISSUE THREAD

**Issue by 3breadt** [aspnet/SignalR#1033]
Hosting on Windows 7 with HTTP.SYS, WebSockets are not supported. Nevertheless, the server indicates that it supports WebSockets. This is the response to the OPTIONS request:
`{"connectionId":"6e3edfdd-015f-4c6b-afa2-b3ad968d0a66","availableTransports":["WebSockets","ServerSentEvents","LongPolling"]}`

Thus the JS client cannot connect to the hub unless we explicitely specify long polling for the connection (i.e. 
`new signalR.HubConnection(new signalR.HttpConnection(url, { transport: signalR.TransportType.LongPolling }))`).

Is there a way to configure the "availableTransports" that are returned by the server, or is this a limitation of SignalR not recognizing the missing support for WebSockets?

I use SignalR 1.0.0-alpha2-final.

**Comment by BrennanConroy** [comment]
When you use `MapHub` you can configure some options, one of which is the transports available for that route. As far as not showing WebSockets on unsupported servers that could probably be fixed.
We do a similar thing for the C# client
https://github.com/aspnet/SignalR/blob/0e70c7950b4077f82a73c563b1681abd8f22a50c/src/Microsoft.AspNetCore.Sockets.Client.Http/DefaultTransportFactory.cs#L38-L45

**Comment by moozzyk** [comment]
I don't think we can easily fix detecting if the WebSockets transport is available on the server side. The problem is that it is not only that you have to detect if you are running on Win7 but also that you are running behind IIS. My understanding is that if you run Kestrel on Win7 WebSockets transport will just work fine. I think we may need to leave to the user to disable the WebSockets transport if they are running behind IIS on Win7/Win2008R2.

**Comment by davidfowl** [comment]
We just need to expose a sever feature to detect this.

**Comment by moozzyk** [comment]
Not sure how this works... Who is going to set this feature? IISIntegration?

For completeness we also have http sys server so it would have to be handled for this case as well.

**Comment by davidfowl** [comment]
> Not sure how this works... Who is going to set this feature? IISIntegration?

Sure. We just need to code against the feature and the server will do whatever is appropriate (just like it did in katana).

**Comment by 3breadt** [comment]
@BrennanConroy: Thanks for the hint regarding the possibility to specify options in the `MapHub` function. This helps us for now to deactivate WebSockets based on what OS the server is running on.

**Comment by moozzyk** [comment]
@davidfowl - sounds good. If we can code against the feature than yes, it becomes easy.

**Comment by davidfowl** [comment]
Filed https://github.com/aspnet/Hosting/issues/1241

**Comment by muratg** [comment]
Dup of #1317
