### ISSUE TITLE
Cannot ng build --prod 

### ISSUE THREAD

**Issue by Duanthse03268** [aspnet/SignalR#1038]
I'm trying to build with product environment but currently i cannot do it
when i build it will show this error it relate to this [issue](https://github.com/angular/angular-cli/issues/8044) of angular/cli

>  **ERROR in vendor.f899808992005b6aee0f.bundle.js from UglifyJs**

> **Unexpected token: name (Subject) [vendor.f899808992005b6aee0f.bundle.js:21840,6]**

how can i solve this problem.

**Comment by Duanthse03268** [comment]
Sorry i found the solution

**Comment by remeezp** [comment]
What was your solution?

**Comment by michaeldaw** [comment]
I'd like to know as well.

**Comment by Duanthse03268** [comment]
You can check here https://github.com/aspnet/SignalR/issues/983

**Comment by michaeldaw** [comment]
Thanks for posting it. Helped a lot.

**Comment by Duanthse03268** [comment]
No problem. Can i have

**Comment by Duanthse03268** [comment]
Can i have your skype ? Because i have some question which do not related to this issue.  Something like JWT

**Comment by remeezp** [comment]
Thanks very much, helped me too.

**Comment by michaeldaw** [comment]
@Duanthse03268 I don't use Skype but feel free to send an email and I'll help if I can.

**Comment by Duanthse03268** [comment]
Your email on github right ?

**Comment by michaeldaw** [comment]
Yes, that's fine.
