### ISSUE TITLE
Authorization with SignalR

### ISSUE THREAD

**Issue by jpmnteiro** [aspnet/SignalR#104]
Hey,

I'm playing around with SignalR looking to port an existing application that has authentication/authorization. Been experimenting on a test project but so far only managed to authenticate a client by deriving `AuthorizeAttribute` and overriding `AuthorizeHubMethodInvocation` (which is not a viable approach I dare say).

I've also noticed on the Chat sample that there's a `// TODO: Make this work` next to the `[Authorize]` header and that there's no JS client code yet. Does this mean it's not possible to add authorization at this moment to SignalR?

**Comment by moozzyk** [comment]
You need to take care of the authorization yourself currently. In the ChatSample users are Authorized in the [OnConnectedAsync](https://github.com/aspnet/SignalR/blob/901d9604b577c7940703ce06b3257899f3868207/samples/ChatSample/Hubs/Chat.cs#L19-L22) method

The Chat sample does use the Typescript/JS client. It is being compiled and copied to the project as a pre-compile step: https://github.com/aspnet/SignalR/blob/901d9604b577c7940703ce06b3257899f3868207/samples/ChatSample/project.json#L87-L89 and then used here: https://github.com/aspnet/SignalR/blob/901d9604b577c7940703ce06b3257899f3868207/samples/ChatSample/Views/Home/Index.cshtml#L17
