### ISSUE TITLE
Client does not get Closed event when Transport protocol is Server Sent Events

### ISSUE THREAD

**Issue by alexiordan** [aspnet/SignalR#1044]
Setup: internet source is a 3G dongle via a router.
After connection is established this is what happens if unplug 3G dongle:

If transport protocol is **WebSockets**:  Connection Slow, Reconnecting and in the end Closed events are fired.
If transport protocol is **Server Sent Events**(*): Connection Slow event is fired and nothing else.

Is there a technical reason why for SSE Reconnecting and Closed event are never fired ?

(*) This happened in my case due to lack of any more websocket connections available in Azure plan, but I don't think it is necessary relevant.

**Comment by BrennanConroy** [comment]
Looks like you are using SignalR 2.2
Belongs here https://github.com/SignalR/SignalR/issues
