### ISSUE TITLE
Reconnection

### ISSUE THREAD

**Issue by aminebizid** [aspnet/SignalR#1047]
Any sample how to manage re connection from TS client side?
Do I have to poll myself?

**Comment by AustinFelipe** [comment]
Check this out #1057 and tell me your thoughts

**Comment by moozzyk** [comment]
I played with C# client [here](https://github.com/aspnet/SignalR-samples/commit/4b9451595668ce829c501872bf1c0e479e59afea). I want to do something similar for JS

**Comment by muratg** [comment]
See #1057
