### ISSUE TITLE
Registering Client for Page Specific data events

### ISSUE THREAD

**Issue by willthiswork89** [aspnet/SignalR#1050]
Not so much an issue but more a question of how to handle something

I'm building a SignalR microservice that will use Redis as a backplane and all the front end clients will connect to us for page specific events. 

-Private messages
-Group messages on a live chat
-New video feeds coming online. 

Basically depending on what page they are on we will want to send them different events. I wouldnt want to send group message events from Group A when they moved over to Group B or send them messages about new video feeds when they are not on the home page browsing video feeds. 

I guess im mainly confused about the front end implementation of a person moving from page to page and constantly reconnecting on how to handle that. Do we have a sample somewhere that emulated similar behavior?

**Comment by moozzyk** [comment]
I guess you will need to authenticate your users. This way if a user disconnects and then connects again you will be able to tell this is the same user. What you could do is to add the user to a specific group depending on what page they are connecting from (e.g. if they connect from a Page A they are added to Group A  etc.). To know what group the user should be added to you could either add some parameters to the url you will use to connect to the server or send a message after the client has connected successfully.

**Comment by willthiswork89** [comment]
Our users do authenticate via a JWT Token so we should have that. So you are saying when they connect that in the params i should pass a page or some other information that identifies what group they should be apart of? I was not aware you could pass query params through the hub i will research this,

**Comment by moozzyk** [comment]
Yes, one of the options is to pass additional parameters in query string (you will actually have to pass the JWT token in the query string as well because WebSocket API in the browser does not allow setting headers - more details [here](https://github.com/aspnet/SignalR/issues/888)). You can then access it in the OnConnected, read the group to add the client to and add the client to a group.

**Comment by bigswede74** [comment]
In the OnConnectedAsync method when you add a client to a group, what is the behavior when the client is dosconnected, i.e. - OnDisconnectedAsync. Does the Group assignment get cleaned up with the connection or do we need to manually clean it up.

**Comment by BrennanConroy** [comment]
The client should be removed from all groups it is in automatically.
