### ISSUE TITLE
Exceptions thrown in Redis events should be caught and logged

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#1054]
If an exception is thrown in a Redis event handler it will just disappear without a trace. E.g. if deserializing [a message throws](https://github.com/aspnet/SignalR/blob/30e7422407760d0d56361f76b73c5930875a03d3/src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs#L123) no one will be able to tell what happened.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/aspnet/SignalR/commit/2419867dfcda3b11a83a30de6559f1c44b3da38c
