### ISSUE TITLE
Consume newer CoreFX/CoreFXLab packages

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#1060]
It's been a while since we took some of the dependencies.

@ahsonkhan is working on getting a new signed build of the packages that we use.

**Comment by ahsonkhan** [comment]
The packages are available for consumption.

**CoreFx:**
[System.Memory.4.5.0-preview1-25902-08](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory/4.5.0-preview1-25902-08)
[System.Runtime.CompilerServices.Unsafe.4.5.0-preview1-25902-08](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Runtime.CompilerServices.Unsafe/4.5.0-preview1-25902-08)
[System.Numerics.Vectors.4.5.0-preview1-25902-08](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Numerics.Vectors/4.5.0-preview1-25902-08)

**CoreFxLab:**
[System.Buffers.Experimental.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Buffers.Experimental/0.1.0-alpha-002)
[System.Buffers.Primitives.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Buffers.Primitives/0.1.0-alpha-002)
[System.Collections.Sequences.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Collections.Sequences/0.1.0-alpha-002)
[System.IO.Pipelines.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.IO.Pipelines/0.1.0-alpha-002)
[System.IO.Pipelines.Extensions.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.IO.Pipelines.Extensions/0.1.0-alpha-002)
[System.IO.Pipelines.Testing.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.IO.Pipelines.Testing/0.1.0-alpha-002)
[System.IO.Pipelines.Text.Primitives.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.IO.Pipelines.Text.Primitives/0.1.0-alpha-002)
[System.Text.Encodings.Web.Utf8.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Text.Encodings.Web.Utf8/0.1.0-alpha-002)
[System.Text.Formatting.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Text.Formatting/0.1.0-alpha-002)
[System.Text.Primitives.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Text.Primitives/0.1.0-alpha-002)
[System.Text.Utf8String.0.1.0-alpha-002](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Text.Utf8String/0.1.0-alpha-002)

cc @pakrym, @joshfree, @KrzysztofCwalina

**Comment by muratg** [comment]
Thanks @ahsonkhan! 

@moozzyk @BrennanConroy FYI

**Comment by joshfree** [comment]
@ahsonkhan what about System.Threading.Channels?

**Comment by ahsonkhan** [comment]
> what about System.Threading.Channels?

Good catch. That package is available on myget as well. Updated the list.

**Comment by BrennanConroy** [comment]
Done https://github.com/aspnet/SignalR/pull/998
