### ISSUE TITLE
Production Ready Roadmap

### ISSUE THREAD

**Issue by MattHartz** [aspnet/SignalR#1061]
Hi everyone,

Small question for the SignalR team.  Is there a roadmap posted anywhere for the features coming in future releases along with a best case scenario of when SignalR core may be production ready?

Thanks!

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Home/wiki/Roadmap

https://github.com/aspnet/SignalR/issues/394

**Comment by MattHartz** [comment]
#394 Looks great.  Unfortunately the first link is just an ASP.net roadmap that makes a slight mention of SignalR integration. :)
