### ISSUE TITLE
AspNetCore SignalR

### ISSUE THREAD

**Issue by bleekbless** [aspnet/SignalR#1062]
How can I use GlobalHost in SignalR AspNetCore, I need to call a Hub method from the server. Like I receive a message then send back a waiting message. Then process the requested message and after the process is complete I send back another message of completed to the client.

**Comment by moozzyk** [comment]
Just inject `IHubContext<T>` - here is an example: https://github.com/aspnet/SignalR/issues/182#issuecomment-278421834

**Comment by bleekbless** [comment]
I didnt understand, but what will I instantiate the class withou the context ?
