### ISSUE TITLE
SignalR not disposing of TCP connections?

### ISSUE THREAD

**Issue by simonpbond** [aspnet/SignalR#1064]
Hi team, I am experiencing some odd behavior.

I have 40 or so .NET clients running nationwide, and a single server (hub based), all running latest release of SignalR.

From time to time the network experiences issues, and when this happens I've made the client's attempt a reconnect. For the most part, they seem to reconnect fine. On the server side I am logging all connects and disconnects using OnConnectedAsync and OnDisconnectedAsync.

I noticed in my logs (server side) there were many client's that had multiple connections apparently open in the logs (no disconnects). When investigating further I could see there were established connections on the server side, yet no connections showing client side when using netstat or viewing the resource monitor. These connections remain open for hours.

I'm confused as to how this is possible? 

Both the client and server are under development/testing and both sides experience the odd crash (client side software) or exception (server side hosted on iis), this is not related to SignalR, however it presents situations where SignalR may not be cleanly disposed.

However, I still assumed the connections would disappear within minutes, yet they are showing for many hours (today we are at 6 hours and continuing to show).

(For reference I'm using port 5053 under IIS on server side if you look at these images).

![gt3](https://user-images.githubusercontent.com/10304668/32165516-2a56dac2-bd8b-11e7-9a33-77a1a686a30a.jpg)
![gt2](https://user-images.githubusercontent.com/10304668/32165534-334a1ce8-bd8b-11e7-9b22-3fd5796b5924.jpg)
![gt1](https://user-images.githubusercontent.com/10304668/32165540-36233ea4-bd8b-11e7-90d8-20307d913680.jpg)

Any idea of the reason for this? Thanks as always.

**Comment by BrennanConroy** [comment]
Is your server running under a debugger? We currently don't clean up connections when a debugger is attached to help with debugging scenarios.

Assuming there is no debugger attached, this is most likely because we don't have any keep alives yet, so until the server sends a message to the disconnected connection it has no idea that the connection is gone.

We have an issue tracking keep-alives https://github.com/aspnet/SignalR/issues/282

**Comment by simonpbond** [comment]
Hi Brennan, 

No debugger is attached on either side.
Will keep an eye on the keep-alives issue and see if it resolves the problem after implemented.

This is obviously causing issue's keeping track of legitimately connected clients on the server side.
Thanks again.

**Comment by moozzyk** [comment]
@simonpbond - Can you confirm that for these connections the OnDisconnected method was never called?

**Comment by davidfowl** [comment]
Yes that does seem strange. @simonpbond Do you have an idea of what transports are being used?

**Comment by simonpbond** [comment]
@moozzyk Yes, it was never called on those connections. I have a summary table of each connect and disconnect per remote i.p, that's how I first realized something was wrong, then confirmed by checking netstat / resource monitor on both server & client.

@davidfowl The client's all have transport set to websockets.

All client's are running at branch offices across the country and connected via site to site vpn (ipsec I believe) to head office where the server is located. 

If you would like me to test anything, please let me know, I can cut it down to a basic client/server if required and leave it running. So far today the network is stable and there are no reconnects, but I'm sure it will occur again if I leave a test up and running for a few days.

**Comment by simonpbond** [comment]
It was also not contained to just one client, I focused the screenshots on the one with the most connections still established.

**Comment by moozzyk** [comment]
I guess the next step is to turn on logging on the server side at the Trace level. Also, it would be interesting to see if the same happens when running just Kestrel (i.e. no IIS).

**Comment by davidfowl** [comment]
Sounds like it’s a proxy issue (might be at the IIS layer)

**Comment by simonpbond** [comment]
Ok, will set up logging at the trace level on the server and get back once I have some more info.
Thanks!

**Comment by simonpbond** [comment]
@moozzyk @davidfowl 

I've ran only Kestrel for the week and do not see the same issue occurring. 
Will run only Kestrel for another week, to confirm, then head back to IIS to also confirm the problem re-appears.

Thanks.

**Comment by simonpbond** [comment]
Because it was running live I couldn't swap back to IIS and potentially disrupt things, so I left it running with Kestrel. Now that the keep alives have been added I will upgrade and test under IIS. Please give me another couple of weeks to report back and close this off, I haven't forgotten about it. Thanks.

**Comment by simonpbond** [comment]
Will have to wait until release of 2.1. Closing until then.
