### ISSUE TITLE
Multiple boradcasts to different clients

### ISSUE THREAD

**Issue by bagzli** [aspnet/SignalR#1067]
I'm trying to use SignalR. However, I am not sure if it can do what I need it to do.

When setting up SignalR in Startup we have to call the following:

`app.UseSignalR(routes =>
{
    routes.MapHub<Chat>("chat");
});`

Now please think of this scenario, I tried to simplify the scenario as much as I could.

Let's say I go to my website and I open my profile page. That page lists all sort of chat messages that have my name in it. Then I open another tab and go to home page. There I type in the chat my name and send a message. This message will show on my profile page, but then I enter another user and send a message. This second message should not show up on my homepage, it should be on the homepage of that user.

To achieve this, from what I can tell, I have to map 2 hubs. However, I need this for every user and they will register to the site after startup runs. The other part to consider is if let us say this was Twitter. TONS of users. I thought about just filtering the message through javascript and only displaying if it has my name in it on the profile page, but if this is a very heavy hitting website, that is far too much data being sent to every client.

Is limiting what is sent to which client possible? The only way I thought of it was having multiple chat hubs and registering them on startup. More than likely the answer is yes and I did not fully understand the proper use of SignalR. If you could, please point me in the right direction.

**Comment by beatsm** [comment]
Sounds like you want something like this.

https://github.com/<https://github.com/PeteGoo/Pushqa>PeteGoo<https://github.com/PeteGoo/Pushqa>/<https://github.com/PeteGoo/Pushqa>Pushqa<https://github.com/PeteGoo/Pushqa>

Unfortunately this was not built for Signalr core.

________________________________

**Comment by BrennanConroy** [comment]
So you just want the ability to send messages to individual users?

In your hub you can do
```
// for connectionIds
Clients.Client(connectionId).InvokeAsync("clientmethod", args);
// or for user names
Clients.User("userName").InvokeAsync("clientMethod", args);
```

**Comment by moozzyk** [comment]
or use groups...

**Comment by bagzli** [comment]
@beatsm your link doesn't work for me.

@BrennanConroy Where would I run that code, not on startup I'm sure?

@moozzyk could you please elaborate?

**Comment by bagzli** [comment]
@BrennanConroy To answer your question. Not so much to an individual user, but more to an individual URL. The user example I came up with above is not exactly what I am trying to do, but it is very close to it in design.

So, for example, I will have 2 pages. Page one has controls. Page 2 has actions that happen when controls are sent. However, Every user has their own page one and page 2. Furthermore, Each user may have numerous sets of page 1 and page 2. So I'm looking for a way to target a specific URL. All clients that have a specific page opened.

**Comment by beatsm** [comment]
https://github.com/PeteGoo/Pushqa

Sorry sent it via email and somehow got garbled.

The idea is that the client is able to filter the messages it receives on the server. I was thinking that each page would advise the server what messages it was interested in. But as I said this is quite old code now that does not work on Signalr core.

**Comment by moozzyk** [comment]
The simplest way to make it work is as @BrennanConroy said to use `Client.User`. Whenever you have an update for the user you invoke a client side method with the data. Now, you either pass the name of the page you want to show the notification on as a parameter or you use a different client side method for each page. In the first page you would ignore messages that are not targeting the page that is open. In the second case the client will receive a client side invocation message but since there will be no handler registered for the method the message will be ignored. The disadvantage of this approach is that you will be sending messages to a user even if the page the message is meant for is not open. 
To fix this disadvantage you can use groups. Whenever a user opens a page they want to receive notifications for they add themselves to a group called for instance "UserName_PageName". Now, whenever you have a message for a given user for a given page you send this message to the "UserName_PageName" group. If the user has multiple instances of a page open they all should receive the message.

**Comment by mhosman** [comment]
Hey @BrennanConroy, you just wrote:

-----------------------------------------------------------------------------------

So you just want the ability to send messages to individual users?

In your hub you can do

```
// for connectionIds
Clients.Client(connectionId).InvokeAsync("clientmethod", args);
// or for user names
Clients.User("userName").InvokeAsync("clientMethod", args);
```

------------------------------------------------------------------------------------

Now the question is... using the client-ts, if this is a simple broadcast you can use this:

```
let connection = new signalR.HubConnection('/chat');

connection.on('send', data => {
    console.log(data);
});

connection.start()
    .then(() => connection.invoke('send', 'Hello'));
```

But.... how can i apply this connection to a specific user???

**Comment by BrennanConroy** [comment]
All the client does is invoke hub methods on the server. It is up to the hub methods to decide if you respond by broadcasting to everyone or a specific user.

Take a look at our sample chat hub here https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/Hubs/Chat.cs
