### ISSUE TITLE
Testing with Net Core TestServer

### ISSUE THREAD

**Issue by savpek** [aspnet/SignalR#1068]
Is it possible to use SignalR with Microsoft.AspNetCore.TestHost.TestServer Web/Socketclient? I tried several solutions but cannot figure way, only way i managed to run SignalR tests was to start real server during tests (just like you do in Microsoft.AspNetCore.SignalR.Client.FunctionalTests). However i'd like to use TestServer since i have other test utilities using it already.

**Comment by savpek** [comment]
Error is System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established. Basically what i need is to replace signalR standard communication against TestServer clients. Another way for me is to use testhost with its uri, but i dont think it exposes real http access outside?

**Comment by davidfowl** [comment]
It would be possible to make it work with server sent events and long polling but we don't have a way for you to give us the client websocket. We'd need to do some more thinking here but you should be able to do this for now:

```C#
var builder = new WebHostBuilder()
                .ConfigureServices(services =>
                {
                    services.AddSignalR();
                })
                .Configure(app =>
                {
                    app.UseSignalR(routes =>
                    {
                        routes.MapHub<Chat>("chat");
                    });
                });

var server = new TestServer(builder);

var connection = new HubConnectionBuilder()
                .WithUrl("http://localhost/chat")
                .WithMessageHandler(server.CreateHandler())
                .WithTransport(TransportType.ServerSentEvents)
                .WithConsoleLogger()
                .Build();
```

**Comment by savpek** [comment]
Nice! Tested that solution and it works.
