### ISSUE TITLE
Way to get connection state

### ISSUE THREAD

**Issue by potterdev** [aspnet/SignalR#1082]
Is there a way to get connection state on the client?

I am using xamarin and sometimes the connection is closed while the application is in background without calling the event .onClosed (because of the OS) so I need another way to check if the connection is still alive or I need to restart it. 

Thanks

**Comment by moozzyk** [comment]
It is not possible at the moment. You should be able to use the Closed task once [this PR](https://github.com/aspnet/SignalR/pull/1080) is merged.
