### ISSUE TITLE
Trying to understand the Hub's lifecycle.

### ISSUE THREAD

**Issue by nrhoffmann** [aspnet/SignalR#1086]
In this example, after clients have first invoked `FirstLetter`, they will then be able to invoke `NextLetter` to get the next letter. Every client can have a different next letter.
 
Will this work?

``` C#
    public class Example : Hub
    {
        private static Dictionary<string, char> ConnectionIdToLetterMappings = new Dictionary<string, char>();

        public Task FirstLetter()
        {
            ConnectionIdToLetterMappings[Context.ConnectionId] = 'A';

            return Clients.Client(Context.ConnectionId).InvokeAsync("nextLetter", 'A');
        }

        public Task NextLetter()
        {
            var nextLetter = (char) (ConnectionIdToLetterMappings[Context.ConnectionId] + 1);
            ConnectionIdToLetterMappings[Context.ConnectionId] = nextLetter;

            return Clients.Client(Context.ConnectionId).InvokeAsync("nextLetter", nextLetter);
        }
    }
```

**Comment by BrennanConroy** [comment]
Probably want to use a `ConcurrentDictionary`, but looks fine. What are you trying to understand?

**Comment by nrhoffmann** [comment]
If an external key value store like Redis is required.

**Comment by nrhoffmann** [comment]
Also what would happen if the dictionary wasn't `static`? Does the framework instantiate an new Hub for each connection?

**Comment by BrennanConroy** [comment]
In memory stores are fine, as long as you understand that the Hub gets created and destroyed after every method call. (Which you probably do since you used `static`)

And I know this is just an example, but you could resolve your store via DI in the Hubs constructor and the store could be a singleton service.

**Comment by nrhoffmann** [comment]
Exactly was I was wondering. Since the .net core version of signalr is quite new, I couldn't find much documentation on it. Thanks!
