### ISSUE TITLE
signalr not working in project created with "dotnet new angular" cli using VSCode

### ISSUE THREAD

**Issue by avijassra** [aspnet/SignalR#1088]
when i am trying to start the connection, i am getting this  .... at this line

File -> https://github.com/avijassra/signalrDi/blob/v1-reboot/ClientApp/app/services/pubsub.service.ts#L16

> this.connection = new HubConnection('chat');
> //this.startedConnection = this.connection.start();

File -> https://github.com/avijassra/signalrDi/blob/v1-reboot/Startup.cs#L47

> app.UseSignalR(routes =>
> routes.MapHub<signalrDi.Hubs.ChatHub>("chat"));

Project Repo https://github.com/avijassra/signalrDi/tree/v1-reboot

**Comment by moozzyk** [comment]
What is the error again?

**Comment by avijassra** [comment]
> An unhandled exception occurred while processing the request.
> 
> NodeInvocationException: Uncaught (in promise): Error: Cannot resolve '/chat'.
> Error: Cannot resolve '/chat'.
> at HttpConnection.resolveUrl (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/main-server.js:3534:19)
> at new HttpConnection (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/main-server.js:3424:25)
> at new HubConnection (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/main-server.js:19846:31)
> at new PubSubService (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/main-server.js:11730:27)
> at _createClass (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:20466:26)
> at _createProviderInstance$1 (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:20441:26)
> at resolveNgModuleDep (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:20426:17)
> at NgModuleRef_.module.exports.NgModuleRef_.get (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:21512:16)
> at resolveDep (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:22015:45)
> at createClass (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:21868:35)
> Error: Uncaught (in promise): Error: Cannot resolve '/chat'.
> Error: Cannot resolve '/chat'.
> at HttpConnection.resolveUrl (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/main-server.js:3534:19)
> at new HttpConnection (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/main-server.js:3424:25)
> at new HubConnection (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/main-server.js:19846:31)
> at new PubSubService (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/main-server.js:11730:27)
> at _createClass (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:20466:26)
> at _createProviderInstance$1 (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:20441:26)
> at resolveNgModuleDep (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:20426:17)
> at NgModuleRef_.module.exports.NgModuleRef_.get (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:21512:16)
> at resolveDep (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:22015:45)
> at createClass (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:21868:35)
> at resolvePromise (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:86165:31)
> at resolvePromise (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:86136:17)
> at /Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:86213:17
> at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:85819:31)
> at Object.onInvokeTask (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:14821:37)
> at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:85818:36)
> at Zone.module.exports.Zone.runTask (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:85586:47)
> at drainMicroTaskQueue (/Users/avijassra/Projects/GitHub/signalrDi/ClientApp/dist/vendor.js:85979:35)
> at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by moozzyk** [comment]
Looks like you need to use the full url. If the `window.document` [cannot be accessed](https://github.com/aspnet/SignalR/blob/caff492cdc8eccc42254ec7d584ab48b1fb019fe/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpConnection.ts#L172) there is no good way to resolve the full url from a relative url. Maybe the error message should be clearer about this.

**Comment by davidfowl** [comment]
This looks like the same problem described here https://github.com/aspnet/SignalR/issues/973

**Comment by avijassra** [comment]
@moozzyk @davidfowl , this [code](https://github.com/avijassra/signalrDi/blob/v1-reboot/ClientApp/app/services/pubsub.service.ts#L13) seems have solved the issue



```
constructor() {
        if(typeof window !== 'undefined') {
            this.connection = new HubConnection('/chat');
            this.startedConnection = this.connection.start();
    
            //chat
            this.connection.on('NewMessageReceived', (chatMsg: ChatMsgModel) => {
                this.onIncomingMessage(chatMsg);
            });
        }
    }
```

Questions: 
1) Is there any better solution for this than checking for window object? Or i am missing the actual solution. This looks more like of a patch than solution.
2) Why it [works](https://github.com/avijassra/Games/blob/Tic-Tac-Toe-w/SignalR/app/services/pubsub.service.ts#L14) when i am just creating a **dotnet new mvc** (not **dont new angular**) app and transpile code to js using [npm tsc](https://github.com/avijassra/Games/blob/Tic-Tac-Toe-w/SignalR/package.json) ... (**note**: I am not using webpack in this project)

Thanks for the help
- Avi

**Comment by moozzyk** [comment]
The issue is that `PubSubService` code runs on the server side. Is it supposed to run on the server? You workaround basically disables this functionality when the code does not run in the browser but I think running this code on the server side is not correct.

**Comment by avijassra** [comment]
@moozzyk @davidfowl,  i ended up removing **asp-prerender-module="ClientApp/dist/main-server"** from the Index.cshtml page and application just works as expected. 

Thanks for all your time and help. 
Avi
