### ISSUE TITLE
Unable to force longpolling in ASP.NET Core SignalR

### ISSUE THREAD

**Issue by zdeneksejcek** [aspnet/SignalR#1089]
Hi,

I tried everything possible, but cannot force longpolling (on either server or client side). The problem is that we have newest Chrome, but on server side we use linkerd without support for websockets. The only chance is to force is from beginning. Is there a way?

Thanks.

**Comment by davidfowl** [comment]
You can do it both on the client side and on the server side. What exactly did you try?

**Comment by zdeneksejcek** [comment]
I found some tutorials suggesting following:

```
var connection = $.hubConnection();
connection.start({ transport: 'longPolling' });
```

But it doesn't seem to work at all. Is there another way?

**Comment by davidfowl** [comment]
The ASP.NET Core version of SignalR has a completely different API. There are no docs for this version yet.

There are samples here https://github.com/aspnet/SignalR-samples/blob/f3b1a71eac5614fde9749a0d8d24a7c10e18bfde/ChatSample/ChatSample/wwwroot/index.html#L78

**Comment by zdeneksejcek** [comment]
**Works like a charm, thanks.**

For future reference:
`
let connection = new signalR.HubConnection(url, {transport: signalR.TransportType.LongPolling});
`

**Comment by anurse** [comment]
Thanks for the doc link @sebastianbk ! Actually, the API for the final client is this:

```javascript
let connection = new signalR.HubConnectionBuilder()
    .withUrl("/myhub", { transport: signalR.HttpTransportType.LongPolling })
    .build();
```

The `HubConnection` constructor is not recommended, as it is marked `private` in the TypeScript. It can be called from JavaScript (since JavaScript has no concept of `private`) but should be avoided as it is considered an internal API.
