### ISSUE TITLE
JS client: move HttpConnection to a separate package

### ISSUE THREAD

**Issue by BalassaMarton** [aspnet/SignalR#1090]
On the server, we can use `Microsoft.AspNetCore.Sockets.Http` to create endpoints without hubs, but we don't have the same elegant separation in the JS client. Could you move `HttpConnection` and its dependencies to a separate package ( `@aspnet/sockets-client` or something)? Loading `HubConnection` and other hub-related code is just a waste of resources when there are no hubs involved.

**Comment by davidfowl** [comment]
I don't mean to be that guy but can you quantify this statement:

>  Loading HubConnection and other hub-related code is just a waste of resources when there are no hubs involved.

How much waste?

**Comment by BalassaMarton** [comment]
You mean, in LoC? :D I didn't count, it may be just a few, but still, since the socket is in a lower layer than the hub, my over-abstracting inner demon wants it in another package.

**Comment by moozzyk** [comment]
I don't think we should do it - at least not now. We could reconsider if we get more feedback the reality is that the vast majority of people want just hubs. Btw. if you want to be very lean and you support webSockets on the server you don't need the client at all - you can connect to the server with just pure webSocket.

**Comment by BalassaMarton** [comment]
I use `HttpConnection` because of the long polling fallback option, and because the endpoint API on the server is more convenient for me than WebSockets. In my use case it is just the thing I was looking for.

**Comment by moozzyk** [comment]
When you have situations where you would like to use non-webSockets transports using the client is the way to go indeed.

**Comment by davidfowl** [comment]
Agreed closing as a result. Thanks for the suggestion @BalassaMarton
