### ISSUE TITLE
Clients.User IRequest equivalent

### ISSUE THREAD

**Issue by cfrets** [aspnet/SignalR#1092]
I'm using alpha2 and needs to use Clients.User, but i'm looking for the IRequest equivalent.
I need to get the users claims. How to get these in alpha2?

**Comment by jkljajic** [comment]
You can use Feature
Context.Connection.Features.Get<IHttpContextFeature>()?.HttpContext
Now you have Context and from there you pull User

**Comment by cfrets** [comment]
Thank you. Just what I needed.
