### ISSUE TITLE
How to use injected HubContext out of Controllers?

### ISSUE THREAD

**Issue by SNival** [aspnet/SignalR#1098]
Hi everyone,

I have a Web API server, hosting the SignalR hub, and I have to invoke methods on clients connected to this hub from an IHostedService running "inside" the server.
The problem is that the client's list of the HubContext injected in the hosted service is always empty.
It works perfectly when used inside a simple Controller, the hub injected in the controller constructor having a populated clients list.
I found that the VS debugger object IDs of both Hubs are different.

How can I get the actual hub in my hosted service ?

I will try to make a small sample of the code.

Best regards

**Comment by davidfowl** [comment]
There is  no clients list. What exactly do you mean by "it's empty". Can you put a sample that shows the problem in a github repository?
