### ISSUE TITLE
SignalR .net Client HubConnection memory leak

### ISSUE THREAD

**Issue by MarkOMeara123** [aspnet/SignalR#1099]
Hello

There appears a memory leak in the HubConnection.cs. Review line 35 : 
`private readonly CancellationTokenSource _connectionActive = new CancellationTokenSource();`

This is not disposed in the DisposeAsyncCore() method (line 126).

To replicate, the below code in a loop and review the accumulation of CancellationTokenSource objects in memory.

```
 var connection = new HubConnectionBuilder()
               .WithUrl(URL)
               .WithConsoleLogger()
               .Build();

var connection.DisposeAsync().Wait(1000); 
```
Can this be corrected please, or a workaround offered?

**Comment by moozzyk** [comment]
This needs to be fixed. Would you like to send a PR?

**Comment by MarkOMeara123** [comment]
Sorry, I have never done a pull request before. Perhaps I can leave that to others.

**Comment by MarkOMeara123** [comment]
Having a quick look through the code I can see there is not too much thought about disposing objects correctly. Why are the classes not implementing IDisposable?

Here are some more issues:

CancellationTokenSource not disposed
-----------------------------------------
HubConnectionContext
HttpConnectionDispatcher : (three undisposed references in ExecuteEndpointAsync)
LongPollingTransport
WebSocketsTransport
ServerSentEventsTransport

ClientWebSocket not disposed
--------------------------------------
WebSocketsTransport : ClientWebSocket is disposable

**Comment by moozzyk** [comment]
We also don't dispose most of the `HttpRequestMessage` and `HttpResponseMessage` instances.

**Comment by davidfowl** [comment]
The ones in ExecuteEndpointAsync are disposed:

https://github.com/aspnet/SignalR/blob/65cd41dbf542a5ad5a2fbc2c9e2bb96f2f5aa2bf/src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs#L194-L195

https://github.com/aspnet/SignalR/blob/65cd41dbf542a5ad5a2fbc2c9e2bb96f2f5aa2bf/src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs#L158

https://github.com/aspnet/SignalR/blob/65cd41dbf542a5ad5a2fbc2c9e2bb96f2f5aa2bf/src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs#L256

I'm assuming for the transports, you mean the client side ones. There are cases where disposing the  token is *super* important:

- If you create a token source with a timer
- If you create a linked token source
- If you access the wait handle then it allocates a kernel object (which has a finalizer)

We pretty much always cancel the tokens once allocated and I'm not sure we need to dispose them. If you're not cancelling then there's a bigger problem.

Maybe it's something else causing the leak?

**Comment by MarkOMeara123** [comment]
Ok, did not notice the Dispose registration in HttpConnectionDispatcher.cs.
However the others remain. Canceling the token does not dispose the object, you need to call the dispose method of the object or placing it in a 'using' section.

Consider the below code, it generates a heap of CancellationTokenSource object (amongst others). The snapshot (see attached images) was take about one minute apart. An out of memory error will eventually occur. (Obviously the code snippet is not something that will every see light in a production environment, but it should prove the point ).

![diagnostic tool window](https://user-images.githubusercontent.com/31123120/32678584-0eec6eca-c6b7-11e7-9ac8-7cdee4cebec2.png)
![managed memory](https://user-images.githubusercontent.com/31123120/32678586-12823074-c6b7-11e7-9cfb-ba5bc267f88f.png)



```
int i = 0;

            while (true)
            {
                var connection = new HubConnectionBuilder()
                                    .WithUrl("http://localhost:1202/NotificationHub")
                                    .WithConsoleLogger(LogLevel.Trace)
                                    .Build();

                connection.DisposeAsync().Wait();

                System.Threading.Thread.Sleep(100);

                i++;

                if (i >= 100)
                {
                    Console.WriteLine("Forcing GC");
                    GC.Collect();
                    GC.WaitForPendingFinalizers();
                    System.Threading.Thread.Sleep(2000);
                    i = 0;
                }
            }

```

**Comment by MarkOMeara123** [comment]
Note that the Cancel method does not dispose : https://referencesource.microsoft.com/mscorlib/R/9ead3f5d677e10b8.html

**Comment by davidfowl** [comment]
Who is rooting those objects? It seems odd that they are sticking around when nobody is rooting the HubConnection objects.

> Note that the Cancel method does not dispose : https://referencesource.microsoft.com/mscorlib/R/9ead3f5d677e10b8.html

Sure, I never said it disposes, I called out the things that would leak if dispose wasn't called (and none of those happen in your test AFAIK)

**Comment by MarkOMeara123** [comment]
I see David, apologies for the misunderstanding.

The memory leak appears due to the line:

`.WithConsoleLogger(LogLevel.Trace)`

It appears the CancellationTockenSource objects are from BlockingCollection<Microsoft.Extensions.Logging.Console.Internal.LogMessageEntry>    and Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor . Removing the above results in no memory leaks for the test code I posted above. I do not have access to the Microsoft logging source code so will not bother to debug that further. Simple solution for me is to not use the console logger.

Thanks



I

**Comment by MarkOMeara123** [comment]
Looking in to it a little more, ILoggerFactory interface implements IDisposable. It therefore needs to be disposed. With the below modification to HubConnection.cs the memory leak is resolved:

```
private async Task DisposeAsyncCore()
        {
            _loggerFactory.Dispose();
            _connectionActive.Dispose();
            await _connection.DisposeAsync();
        }
```

**Comment by davidfowl** [comment]
@MarkOMeara123 thanks for the awesome investigation, are you going to close it out and send a pull request 😄 ?

**Comment by MarkOMeara123** [comment]
David
I do not currently know how to do a pull request (never done it before). Not certain exactly what to do, I will start looking at the available documentation on PRs, but if it takes me too long I will leave it for someone else to do.

I will close the issue though. Thanks.

**Comment by davidfowl** [comment]
@MarkOMeara123 if you an diagnose a memory leak you can send a pull request 😉 . I can  help if you need guidance.

**Comment by MarkOMeara123** [comment]
Yes it seems I need help, creating a pull request is harder than diagnosing a memory leak it seems. I get a 403 error message, presumably I need to be authorised to submit requests?

![pullreq](https://user-images.githubusercontent.com/31123120/32692764-31ae71c2-c772-11e7-8df4-ffbcdc88073e.png)

**Comment by BrennanConroy** [comment]
You have to make a fork of the repo and push to a branch on your fork, then you can make a PR from there.

Also, I don't think we can blindly dispose the `ILoggerFactory` in `HubConnection`. We only own the `ILoggerFactory` when the `HubConnectionBuilder` creates a default one.

**Comment by MarkOMeara123** [comment]
Thanks @BrennanConroy  I think I have worked it out. You are correct about the loggerfactory, there needs to be a way to determine whether HubConnectionBuilder has created a default one. Perhaps I will create the pull request and the conversation can continue there?
