### ISSUE TITLE
XML parsing error: Hub reply does not define a root element

### ISSUE THREAD

**Issue by Externaluse** [aspnet/SignalR#1106]
This doesn't present a problem of the function, it is just not pretty; when invoking a method on the server my FF Developer tab reports:
XML Parsing Error: no root element found
Location: https://localhost:44311/signalr?id=ff8ff481-439a-4bcc-8f1f-67941a5ca331
Line Number 1, Column 1:

Again, not a bug per se but it does clutter the dev window. Not sure if it can be changed or if the browser is wrong.

**Comment by moozzyk** [comment]
I think I saw this - we don't set the `Content-Type` header for the response to the `OPTIONS` request and therefore FF treats it as Xml. The response to the `OPTIONS` request should have `Content-Type` set to `application-json`

**Comment by BrennanConroy** [comment]
Should be fixed via https://github.com/aspnet/SignalR/commit/d4b44de4b9b66cc9ee2aafa562417e4cb5653b41

**Comment by eugirdor** [comment]
@BrennanConroy Has this change been published to npm, or how do we get the fix if not?

**Comment by BrennanConroy** [comment]
You can use the nightly builds if you want the fix, located here https://dotnet.myget.org/gallery/aspnetcore-dev

**Comment by kblok** [comment]
@barrytang are we going to have a fix for the non-Core version?

**Comment by barrytang** [comment]
@kblok, what's the ask here?

**Comment by kblok** [comment]
@barrytang I'm having the same issue on SignalR 2.2.2, the .NET Framework one. I don't know whether the same team is maintaining both projects or not.

**Comment by barrytang** [comment]
@DamianEdwards ?

**Comment by anurse** [comment]
You should file an issue on https://github.com/SignalR/SignalR for that.
