### ISSUE TITLE
Works on browser not on android device

### ISSUE THREAD

**Issue by jasmin92** [aspnet/SignalR#1108]
I am working on mobile app using Ionic 3 framework and aspnet core as server. 
SignalR works fine when runs in browser, but when it runs on native android device it crush with white screen. I inspected app with chrome://inspect and got errors:

![image](https://user-images.githubusercontent.com/28627630/32721662-8488fc6e-c867-11e7-9368-f5c0271825b2.png)

Is this due the CORS policy setup?

**Comment by jasmin92** [comment]
Logs on browser:
![image](https://user-images.githubusercontent.com/28627630/32736566-098e4696-c898-11e7-9978-a78d78327d46.png)

**Comment by anurse** [comment]
The fact that it's working in the browser but not on a device does indicate a CORS or other browser policy difference though. I don't believe we have plans to officially support the SignalR JavaScript client outside of NodeJS and standard browsers right now, so there definitely could be issues in other environments.

It's difficult to diagnose just from those errors unfortunately. Are you able to isolate your vendored scripts and determine that SignalR is the one causing that syntax error?

**Comment by jasmin92** [comment]
It's definitly by SignalR. I commented a code where is implentation of SignalR and app worked well.
` this._hubConnection = new HubConnection('http://192.168.1.80:50225/carHub');

    this._hubConnection.start()
      .then(() => {
        console.log('Hub connection started')
      })
      .catch(err => {
        console.log('Error while establishing connection')
      });
    this._hubConnection.on('SendClick', (vehicle:any) => {
     var click =  {"vehicleID": vehicle.vehicleID, "ipAddress": vehicle.ipAddress};
     this.clickInfoList.unshift(click);
    });`
And then uncommented it once again and run in browser. Android version is without signalR and in browser version is included. I send message to hub in controller. 
So, when i click on some vehicle a information about vehicle id and ip Addres of device is added in page that runs in browser. 
It is possible to change something about CORS  like this https://stackoverflow.com/questions/30828558/signalr-working-in-browser-not-in-app

**Comment by anurse** [comment]
How are you importing the SignalR script into your WebPack configuration? The default SignalR script requires ECMAScript 6 support, which may be why you're getting a syntax error (because perhaps the native Android environment doesn't support ES6). There is an ECMAScript 5 version in the package as well, which may work in your environment.

**Comment by jasmin92** [comment]
`import { HubConnection } from '@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha2-final.js';`
instead `import { HubConnection } from '@aspnet/signalr-client'` fixed the issue.
Thank you verry much, you made my day :)
