### ISSUE TITLE
Can't build, need .net core 1.2.0

### ISSUE THREAD

**Issue by harisbotic** [aspnet/SignalR#111]
I know this isn't an issue related directly to singlaR but it can help those who want to run and test it.
I can't find a place to download .Net Core framework 1.2.0-beta-* and it is essential to run project which uses last version of singlaR.
I am using .net core cli version 1.0.0-preview2-1-003182.

**Comment by BrennanConroy** [comment]
If you clone the repo, delete the `.build` folder and run `build.cmd` or `build.sh` it will get the version of .NET we are currently using

**Comment by harisbotic** [comment]
I tried it, and saw that he was downloading thing but when I went to my project which has singlaR as dependency and is supposed to run on .net core 1.2.0 I am still getting this error

<img width="585" alt="screen shot 2017-01-11 at 17 54 25" src="https://cloud.githubusercontent.com/assets/6454831/21858034/dae4c114-d827-11e6-9d48-1786a303c635.png">

**Comment by BrennanConroy** [comment]
The build script installs dotnet in ~/.dotnet and it looks like you are using the globally installed one, if you switch to the local one it should be updated

**Comment by harisbotic** [comment]
Thanks a lot, I just copied it from ~/.dotnet and replaced it with global one and it worked.

Again, Thank you all

**Comment by moozzyk** [comment]
@harisbotic - you can also avoid copying (since the runtimes/sdks used during development change frequently) just by running `~/.dotnet/dotnet` instead of `dotnet`
