### ISSUE TITLE
Change negotiate from OPTIONS to use a "normal" HTTP method

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1111]
We've seen a few issues (#1107 for example) with using `OPTIONS` requests for connection negotiation. As a result, we should just switch to a "normal" HTTP method (like `POST` or `PUT`) and a URL endpoint

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/93cbf4dbef003b5101064978e954fed83095121e
