### ISSUE TITLE
SignalR AspNetCore Set Name

### ISSUE THREAD

**Issue by bleekbless** [aspnet/SignalR#1113]
How can I set a connection Identity name with signalr beacause when I try to get the Context.User.Idententity.Name its always null.

**Comment by davidfowl** [comment]
Where do you want to set it?

**Comment by bleekbless** [comment]
@davidfowl I want to set a querystring like Username or userId so I can identify the user.

**Comment by grahamehorner** [comment]
IMHO id never send the user details in a query string, could cookie or jwt  claims token be a better option for yoir needs?

Sent from my Windows 10 phone

**Comment by bleekbless** [comment]
Yes could be. I just want to know how can I pass a param to a hub request like a header...

**Comment by LilanMadusankaSilva** [comment]
@davidfowl : I also tried to authenticate signalR hub using [Authorize] tag. but it didn't work ? can we do like that ?

**Comment by BrennanConroy** [comment]
Yes that should work, have you actually set up authorization in your startup?
See the ChatSample for an example https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/Startup.cs

**Comment by LilanMadusankaSilva** [comment]
Thanks
