### ISSUE TITLE
Getting the URL and IP address of the client connection

### ISSUE THREAD

**Issue by nrhoffmann** [aspnet/SignalR#1114]
How you get the URL and IP address of the client connection?

Also, is there any form of documentation on the new core version of SignalR? That I could consult instead of opening issues on your Github?

**Comment by anurse** [comment]
For the IP address, you can use the `GetHttpContext` extension method on `ConnectionContext` to get an `HttpContext` and then use the `Connection` property on there to find the client information.

For URL, do you mean the URL on the server that the client requested? The Client doesn't have a "URL" associated with it because it initiated the connection.

As for docs, there's nothing right now. The code and GitHub issues are the documentation :).

**Comment by anurse** [comment]
https://github.com/aspnet/SignalR/issues/944 added better support for getting Client IP data, and the rest is all available off the `HttpContext` via the `ConnectionContext.GetHttpContext` method. Closing this as I think that's covered the cases you asked about. Feel free to comment/reopen if I missed something!

**Comment by lblima** [comment]
Hi guys, I still don't know how to get the url client called the hub. Is there any way to get this information? All I have is the hub path or client IP.

**Comment by anurse** [comment]
You want to know the URL of the Hub from within the hub? This isn't something we expose since there are numerous HTTP requests to different URLs.

**Comment by lblima** [comment]
Not really, I would like to know the caller URL.

Outlook<https://aka.ms/qtex0l> para iOS

________________________________

**Comment by anurse** [comment]
> I would like to know the caller URL.

What do you mean by "caller URL"? There is no URL for the caller, only an IP address.

**Comment by lblima** [comment]
If you're using signalr client JavaScript in a page for example. It works in signalr but don't in signalr core.

Ex.:
var url = System.Web.HttpContext.Current.Request.UrlReferrer.AbsoluteUri

Regards,

Outlook<https://aka.ms/qtex0l> para iOS

________________________________

**Comment by anurse** [comment]
I see. That's not something we plan to support directly in ASP.NET Core SignalR since there's no guarantee the client is on a page at all.

You should be able to access the HttpContext through `Context.GetHttpContext()` though, and that should have the Referrer if you want to get that.
