### ISSUE TITLE
Sample codes not work

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [aspnet/SignalR#1115]
@aspnet/signalr-client javascript does not work as expected. look like this issue come with latest code

**Comment by davidfowl** [comment]
This sample code? https://github.com/aspnet/SignalR-samples

**Comment by moozzyk** [comment]
@LilanMadusankaSilva - can you be more specfic? What is the error?

**Comment by LilanMadusankaSilva** [comment]
issue come with internet explorer. sorry for the inconvenience. it's work with chrome and edge

**Comment by Extentsoftware** [comment]
I have the same issue. Works in Chrome but not in IE

SCRIPT1002: Syntax Error
signalr-client-1.0.0-alpha2-final.js (6,1)

**Comment by BrennanConroy** [comment]
Take a look at our samples
https://github.com/aspnet/SignalR/blob/945710907b9f848231e3dbb70d0467a581e083ce/samples/SocketsSample/wwwroot/streaming.html#L27-L38
They show how to make IE work.

**Comment by Extentsoftware** [comment]
Yes that fixed it, many thanks!
FYI I was using the Chat sample, and it doesn't have that check in it..

Thanks again,

**Comment by Extentsoftware** [comment]
Yes that fixed it, many thanks!
FYI I was using the Chat sample, and it doesn't have that check in it..

Thanks again,

**Comment by BrennanConroy** [comment]
Ah, that would be nice to add :D
