### ISSUE TITLE
Add protocol regression tests to MsgPack

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1117]
Because MsgPack is a binary protocol, it's really important to have some tests that ensure that we know when the binary format changes. We should build some tests that serialize messages using MsgPack and then assert the exact bytes that are generated. Once we have them, they will fail when we change the protocol format and we'll know if and how clients are affected.

We currently only have round-tripping tests which can hide issues if we update all the C# code simultaneously.

JSON has similar tests already, so this is mostly just catching MsgPack up with that.

(Happy to write these myself, just filing this so I don't forget)

**Comment by moozzyk** [comment]
We do have some tests to this effect here: https://github.com/aspnet/SignalR/blob/ff12b9b20ce28fa409110cd33b1f19356f534764/test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/MessagePackHubProtocolTests.cs#L199-L268

**Comment by anurse** [comment]
Yeah, but they need expansion to cover cases like Error completion message, stream items with and without exceptions, etc.

**Comment by anurse** [comment]
Also could use a rename because I thought that test wasn't for this purpose when I looked at it originally :).

**Comment by anurse** [comment]
Done in https://github.com/aspnet/SignalR/commit/0435b6dc6e0ecae6920d1aca6cd7117dfe7cd307
