### ISSUE TITLE
Flaky test: Microsoft.AspNetCore.SignalR.Client.Tests.HubConnectionTests.CannotCallInvokeOnClosedHubConnection

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1121]
This test is flaky and it's because we don't cancel the `_connectionActive` CancellationTokenSource until the underlying connection's Closed Task is triggered. This means `DisposeAsync` can complete but the connection hasn't been fully closed.

Two ways to fix this:

* `await hubConnection.Closed` in the test, this solves the race in the test code but customers may still encounter it.
* Remove the race entirely by either triggering the CTS in `DisposeAsync` or having `DisposeAsync` await `Closed` itself.

What can happen here is that even if I `await DisposeAsync()`, calls to `InvokeAsync` after that await ends can proceed all the way to the underlying Connection. They'll fail there, but the exception won't be as clear.

**Comment by BrennanConroy** [comment]
You mean https://github.com/aspnet/SignalR/pull/1116 :D

**Comment by anurse** [comment]
Brennan... are you watching me code?
