### ISSUE TITLE
Is sticky sessions truly required for scaleout?  Or only for Redis version of scaleout?

### ISSUE THREAD

**Issue by DevCodex** [aspnet/SignalR#1123]
Is sticky sessions truly required for SignalR scaleout?  Or only for Redis version of scaleout?  

If it is required, it is likely a major new impediment to SignalR adoption in production.  Not all production environments (including ours) even have sticky session capability without networking/hardware configuration changes.

Also, is there any update on SQL Server scale out?  I have been reading that there were some tricky challenges to overcome.  Is SQL Server still on the table?

**Comment by davidfowl** [comment]
It’s required for all non websocket transports.

**Comment by DevCodex** [comment]
@davidfowl thanks for your response.  Can you please comment on SQL Server scaleout's status?

**Comment by davidfowl** [comment]
> Also, is there any update on SQL Server scale out? I have been reading that there were some tricky challenges to overcome. Is SQL Server still on the table?

As of this moment, there's no plan to add SQL Server scaleout. With .NET Core lacking SQLDependency it would be extremely slow to poll the database. It was never really a great fit to begin with.

**Comment by DevCodex** [comment]
@davidfowl thanks for the note.  Do you expect that Redis will be the primary recommendation for scaleout then?  Please let me know what we should be tinkering with to be ready.

**Comment by davidfowl** [comment]
Yes redis will be the primary recommendation.
