### ISSUE TITLE
Where can I find the C#/.NET client?

### ISSUE THREAD

**Issue by snarlynarwhal** [aspnet/SignalR#1124]
Where can I find the C#/.NET client for SignalR ASP.NET Core? Or does the [Microsoft.AspNet.SignalR.Client](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/) work with Core versions too?

**Comment by BrennanConroy** [comment]
We have released two alphas, both of which are located https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/1.0.0-alpha2-final

**Comment by snarlynarwhal** [comment]
Wow, that was quick - thank you!

**Comment by BrennanConroy** [comment]
I don't think we run on .NET 4.5, .NET 4.6.1 is the oldest version we support running.

**Comment by snarlynarwhal** [comment]
Ok - thanks!
