### ISSUE TITLE
Consider the following optimization to TryParseMessage

### ISSUE THREAD

**Issue by ahsonkhan** [aspnet/SignalR#1129]
1) Only set `payload = default` when necessary.
2) Do not use _numBitsToShift and just use numBytes * 7.

![image](https://user-images.githubusercontent.com/6527137/32870291-11d52984-ca30-11e7-8dda-f8e8c4d8c572.png)

https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Common/Internal/Formatters/BinaryMessageParser.cs#L13
```C#
public static bool TryParseMessage(ref ReadOnlySpan<byte> buffer, out ReadOnlySpan<byte> payload)
{
    var index = buffer.IndexOf(TextMessageFormatter.RecordSeparator);
    if (index == -1)
    {
        payload = default;
        return false;
    }

    payload = buffer.Slice(0, index);

    // Skip record separator
    buffer = buffer.Slice(index + 1);

    return true;
}
```

https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Common/Internal/Formatters/BinaryMessageParser.cs#L13
```C#
public static bool TryParseMessage(ref ReadOnlySpan<byte> buffer, out ReadOnlySpan<byte> payload)
{
    if (buffer.IsEmpty) goto FalseExit;
...
    do
    {
        byteRead = lengthPrefixBuffer[numBytes];
        length = length | (((uint)(byteRead & 0x7f)) << (numBytes * 7) );
        numBytes++;
    }
    while (numBytes < lengthPrefixBuffer.Length && ((byteRead & 0x80) != 0));
    // size bytes are missing
    if ((byteRead & 0x80) != 0 && (numBytes < MaxLengthPrefixSize)) goto FalseExit;
...
    // We don't have enough data
    if (buffer.Length < length + numBytes) goto FalseExit;

    // Get the payload
    payload = buffer.Slice(numBytes, (int)length);

    // Skip the payload
    buffer = buffer.Slice(numBytes + (int)length);
    return true;

    FalseExit:
    payload = default;
    return false;
}
```

cc @moozzyk, @KrzysztofCwalina

**Comment by moozzyk** [comment]
@davidfowl https://github.com/aspnet/SignalR/pull/948#discussion_r141091410  LOL

**Comment by davidfowl** [comment]
LOL, lookup table for the fail 😄 . I bet the shift is faster 😄

**Comment by ahsonkhan** [comment]
> I bet the shift is faster

Doesn't look like it (it is slower by around 20-30%):
```C#
    public void M(int[] n) {
        for (int i = 0; i < n.Length; i++)
                n[i] = n[i] * 7;
    }
    public void N(int[] n) {
        for (int i = 0; i < n.Length; i++)
                n[i] = (n[i] << 3) - n[i];
    }
```

M - runtime - 3.2081712
N - runtime - 4.270495

400000000 iterations, n.Length = 10

![image](https://user-images.githubusercontent.com/6527137/32914778-9825906e-cacb-11e7-9158-9bc056f29575.png)

**Comment by davidfowl** [comment]
OK so as it turns out l33t code is just slower 😄

**Comment by ahsonkhan** [comment]
@muratg, is there a PR out with the proposed optimization or is it being rejected?

**Comment by muratg** [comment]
@ahsonkhan I guess I misunderstood the comment above so reopening.  I'll check with @davidfowl when he's back.

**Comment by moozzyk** [comment]
@muratg: The comment means that the current version which uses byte shifting instead of just multiplying is slower than multiplying. Multiplying was also more readable.
