### ISSUE TITLE
Any sample code for authenticate siganlr hub using asp.net core 2

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [aspnet/SignalR#1130]
I tried to authenticate siganlr hub using [Authorize] in asp.net core 2. but it didn't work. Any suggestion or idea ....
cookie base authentication or any other working project example

**Comment by LilanMadusankaSilva** [comment]
I wrote asp.net core 2 web application
```
public override Task OnConnectedAsync()
        {
            var id = Context.ConnectionId;
            var name = Context.User.Identity.Name;
        }
```
But Context.User become null, but it works on controller class

**Comment by elestedt** [comment]
I'm trying to do this as well, how did you try to do it and in what way didn't it work?

**Comment by davidfowl** [comment]
Authenticate using what type of authentication? Did you wire it up? Did you follow the asp.net docs?

**Comment by jbdk** [comment]
Im using a middleware that transfers the token from the QS to the Authorization header. Insert it before the UseAuthentication()
````c#
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;

namespace Something.Middleware
{
    public class SignalRQueryStringAuthMiddleware
    {
        private readonly RequestDelegate _next;

        public SignalRQueryStringAuthMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        // Convert incomming qs auth key to a Authorization header so the rest of the chain can authorize the request correctly
        public async Task Invoke(HttpContext context)
        {
            if (context.Request.Headers["Connection"] == "Upgrade" && 
                context.Request.Query.TryGetValue("token", out var token))
            {
                context.Request.Headers.Add("Authorization", "Bearer " + token.First());
            }
            await _next.Invoke(context);
        }
    }

    public static class SignalRQueryStringAuthExtensions
    {
        public static IApplicationBuilder UseSignalRQueryStringAuth(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<SignalRQueryStringAuthMiddleware>();
        }
    }
}
````

**Comment by LilanMadusankaSilva** [comment]
@davidfowl : Its works with asp.net 4.6 framework but it didn't work asp.net core 2.

**Comment by davidfowl** [comment]
@LilanMadusankaSilva not sure what you mean. If you use a proper authentication mechanism like cookies or JWT, or any authentication scheme you implement in your ASP.NET Core application works fine.

**Comment by LilanMadusankaSilva** [comment]
If you can, share ASP.NET core 2 sample code with authentication

**Comment by moozzyk** [comment]
I merged a change (0bafb304c2707739578e635bc9e00d0cd36420a7 18a65496b7adab684a9af2ac255c7128699c96ee) today that adds an API that allows to pass a JWT token when starting a connection. When using the C# client the JWT token will be passed in the header. When using the TS client the token will be passed in the header when sending an HTTP request with XmlHttpRequest (i.e. for negotiate, long polling - send/poll request, server sent events - send request) or in the query string if the underlying API does not allow setting headers (webSockets, eventSource used for the server-to-client channel in the ServerSentEvents transport) as the `signalRTokenHeader` queryString parameter. When using the TS client it is required to copy the token to the MessageReceivedContext.Token as shown in the [sample](https://github.com/aspnet/SignalR/blob/dev/samples/JwtSample/Startup.cs#L49-L62).

**Comment by LilanMadusankaSilva** [comment]
HttpContext.User.Identity.Name can read from controller (home) but Context.User.Identity.Name become null when read inside SignalR hub in asp.net core signalR (This work fine in .net 4.6)

**Comment by davidfowl** [comment]
> HttpContext.User.Identity.Name can read from controller (home) but Context.User.Identity.Name become null when read inside SignalR hub in asp.net core signalR (This work fine in asp.net 4.6)

Can you make a sample that reproduces the issue?

**Comment by LilanMadusankaSilva** [comment]
@davidfowl : I added sample code. Please check this : https://github.com/LilanMadusankaSilva/signalrhubauthentication

**Comment by BrennanConroy** [comment]
Put UseAuth before UseSignalR
https://github.com/LilanMadusankaSilva/signalrhubauthentication/blob/9e5311f7dc0ac52aa664ae90ec97648a59028ccf/Src/AspNetCoreSignalr/Startup.cs#L50-L55

**Comment by LilanMadusankaSilva** [comment]
It is work. Thanks @BrennanConroy

**Comment by chenchen1987** [comment]
> Put UseAuth before UseSignalR

@BrennanConroy Thanks for the solution. I have done the exact same thing - it's great, works fine. But does this not bypass the authentication instead? Not entirely sure on the impact of it.

**Comment by davidfowl** [comment]
No it makes authentication work.
