### ISSUE TITLE
Change tests to target win7-x64 when https://github.com/aspnet/BuildTools/issues/471 is resolved

### ISSUE THREAD

**Issue by pranavkm** [aspnet/SignalR#1133]
See https://github.com/aspnet/SignalR/pull/1132#discussion_r151502108

**Comment by davidfowl** [comment]
@pakrym is this relevant?

**Comment by pakrym** [comment]
Relevant to what?

**Comment by davidfowl** [comment]
OOps, meant @pranavkm

**Comment by pranavkm** [comment]
People seemed passionate about it running on win7-x64 in the past. Let me have a another look, maybe we don't need rids at all.

**Comment by pranavkm** [comment]
Nope, still required. Not entirely sure if there were any specific consequences to targeting one rid over the other.

**Comment by anurse** [comment]
Is this going to happen in time for RC? Should we just punt to 2.2.0-mq?
