### ISSUE TITLE
502 error while handshake 

### ISSUE THREAD

**Issue by kirexp** [aspnet/SignalR#1134]
Hello. I created mvc project with signalR hub. Mapped it to 'chat' and created a angular4 application with angular cli installed npm packages and when i trying to make hub connection 

`
  let connection = new HubConnection('http://localhost:51837/chat');
  connection.start();
`
it makes a http error 502 
**WebSocket connection failed: Error during WebSocket handshake: Unexpected response code: 502**
_Alhtougt if i create connection with that lib in javascript like signalR.HubConnection.... it works._
+ it work if angular app and mvc project with signalR hub run on same port. 

> I think it maybe many headers that sended in angular http to hub for hadshake...

**Comment by BrennanConroy** [comment]
Can we get more info. Or even better, put your repro app on github

**Comment by kirexp** [comment]
It's Simple default project with chathub like in tutorials. and the same connection

![image](https://user-images.githubusercontent.com/20295858/33109205-72e62d06-cf6a-11e7-9915-5bda45554c22.png)

![image](https://user-images.githubusercontent.com/20295858/33109230-8ec14718-cf6a-11e7-8c24-b0fdb238b3cb.png)

**Comment by BrennanConroy** [comment]
How are you running the server? Is it behind a proxy? What OS are you on?

**Comment by kirexp** [comment]
OS - windows 10 fall creators Update(local machine). backend running in vs2017 15.4 debug mode and angular app on vs code (ng serve)   
![image](https://user-images.githubusercontent.com/20295858/33157739-737c2fe4-d02e-11e7-9e02-694c6b8a6f50.png)
also tried with angular4 and angular2

**Comment by muratg** [comment]
@kirexp Are you running behind IIS Express on VS or full IIS?   Also, is there a chance you can create a simple repro app and share on GitHub?

**Comment by anurse** [comment]
Also, are there any logs on the server when this error occurs? You can view the logs in Visual Studio in the Output Window under "ASP.NET Core Web Server", while the app is running:

![image](https://user-images.githubusercontent.com/7574/33466264-8bb89d30-d601-11e7-8d66-e7cd107754db.png)

**Comment by muratg** [comment]
This bug got stale so closing it. Please reactivate or file a new bug if you're still having issues.
