### ISSUE TITLE
@aspnet/signalr-client dont work with angular cli when run build prod mode

### ISSUE THREAD

**Issue by ngohungphuc** [aspnet/SignalR#1136]
I got this error when running ng build --prod. The source map lead me to the signalR file in node_modules

![image](https://user-images.githubusercontent.com/13591213/32976230-a8bb723e-cc44-11e7-8409-922d02d5252a.png)

**Comment by moozzyk** [comment]
Look at https://github.com/aspnet/SignalR/issues/765 and https://github.com/aspnet/SignalR/issues/729

**Comment by ngohungphuc** [comment]
temporary fix using 

`declare var signalR: any;`

**Comment by moozzyk** [comment]
Looks like this issue can be closed.
