### ISSUE TITLE
Anyway to set available time of a signalR connection

### ISSUE THREAD

**Issue by Duanthse03268** [aspnet/SignalR#1141]
I want to set my signalR connection just available in 30 min. How can i do this ? Does anyone has example ?

**Comment by davidfowl** [comment]
That's not a feature, what are you trying to do?

**Comment by Duanthse03268** [comment]
I want to handler unauthorize signalr connection when token expired

**Comment by KPixel** [comment]
When the connection is opened on the server-side, you can register a timer to manually close it when the token expires.
You can also do more complex things as long as you keep track of the opened connections on the server.

**Comment by Duanthse03268** [comment]
i added a token in query string for signalR connection.  As you wrote 

> you can register a timer to manually close it when the token expires.
can you give me an example ?

**Comment by moozzyk** [comment]
You may want to take a look at this: https://github.com/aspnet/SignalR/pull/1101

**Comment by Duanthse03268** [comment]
In my case. While token expired client still receive message from server but client cannot send to server because token handler that why i want to set life time of a connection.

**Comment by BrennanConroy** [comment]
Setup a timer on the client that calls connection.stop when the time is up

**Comment by Duanthse03268** [comment]
Thank you. I will try it
