### ISSUE TITLE
binary protocol example

### ISSUE THREAD

**Issue by chadAtGA** [aspnet/SignalR#1142]
Can you give an example of using the binary protocol?

**Comment by moozzyk** [comment]
With the C# client use `.WithMessagePack`. In case of JS client you need to include the `signalr-msgpackprotocol.js` and set the [`protocol` in the options to `new signalRMsgPack.MessagePackHubProtocol()`] (https://github.com/aspnet/SignalR/blob/93cbf4dbef003b5101064978e954fed83095121e/client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js#L16) when creating the connection.

**Comment by chadAtGA** [comment]
Thanks. I got it up and running.
