### ISSUE TITLE
How can, Manually push messages into to azure Service Bus backplane topic

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [aspnet/SignalR#1143]
is there any way to manually push message to service bus backplane?
what is that topic message body type ? (I able to read message from topic but cannot convert it to readable manner)

**Comment by davidfowl** [comment]
There is no service bus backplane for the ASP.NET Core version of signalr yet, see https://github.com/aspnet/SignalR/issues/501 for more details.

If you're just talking about manually using service bus, then I'm not exactly sure what the question is.

**Comment by LilanMadusankaSilva** [comment]
This one not related to asp.net core. I used .net 4.6 frameworks. Everything work as expected but thing is queue message cannot convert to C# object

```
var client = SubscriptionClient.CreateFromConnectionString(ConnectionString, topicName, subscriptionName);

                client.OnMessage(message =>
                {
                        var  msg =  message.GetBody<String>();
                });
```
That topic message cannot convert to a string. Can you guys give me that class <T> which use in message

**Comment by davidfowl** [comment]
So this is a service bus question, not a signalr question right? What's the question?

**Comment by LilanMadusankaSilva** [comment]
I read topic message from azure service bus backplane. everything good but I can not convert it to the readable manner? I need to deserialize that message

**Comment by davidfowl** [comment]
@LilanMadusankaSilva what does that have to do with SignalR?

**Comment by LilanMadusankaSilva** [comment]
I am currently using signalr with azure service bus backplane. I used worker role to manage long running process. Now I need to communicate with siganlR hub from worker role using service bus backplane

**Comment by davidfowl** [comment]
@LilanMadusankaSilva This repository is for the ASP.NET Core version of SignalR. The non ASP.NET Core version of SignalR sits here https://github.com/SignalR/SignalR.

**Comment by LilanMadusankaSilva** [comment]
ok. sorry for the inconvenience

**Comment by davidfowl** [comment]
I can help you on that repository

**Comment by LilanMadusankaSilva** [comment]
Nice (Y)

**Comment by LilanMadusankaSilva** [comment]
@davidfowl : Doesn't ASP.NET Core SignalR support azure service bus backplane?

**Comment by davidfowl** [comment]
See https://github.com/aspnet/SignalR/issues/501
