### ISSUE TITLE
Preserving SessionId in long-polling mode

### ISSUE THREAD

**Issue by zdeneksejcek** [aspnet/SignalR#1144]
Hi,

I observed weird behavior that we are sometimes loosing session data on server side when connecting reconnects. We have to use pong-polling and there is only one server instance.

My question is: **do I understand it right that session ID should stay same across multiple long-polling connections (one HubConnection of course, one tab in browser)?**

Thanks!

**Comment by BrennanConroy** [comment]
There are no automatic reconnects on SignalR Core, does this issue belong on http://github.com/signalr/signalr

**Comment by davidfowl** [comment]
> My question is: do I understand it right that session ID should stay same across multiple long-polling connections (one HubConnection of course, one tab in browser)?

No, when you disconnect, you get a new connection. There is no concept of "session" in ASP.NET Core SignalR.

**Comment by zdeneksejcek** [comment]
Sorry, I mean ConnectionId, SessionId is concept I created. So, when long-polling connection disconnects, what happens next? **There is really no auto-reconnect in SignalR Core?**

**Comment by davidfowl** [comment]
> There is really no auto-reconnect in SignalR Core?

Correct. We're discussing supporting automatic reconnect but it will not be stateful. There are other longer term discussions about making it more extensible so that you can preserve and restore state across a "session" concept which would be up to the user.
