### ISSUE TITLE
Promise rejection inside HubConnection.js when closing "early"

### ISSUE THREAD

**Issue by ZoolWay** [aspnet/SignalR#1145]
I am using **alpha 2** at the moment and there is a situation in my app where shortly after being connected I close the connection. If this happens, I get an unhandled rejection of a promise with the errror `Error: Invocation cancelled due to connection being closed`. The stack trace is:

```
    at callbacks.set (HubConnection.js:157)
    at callbacks.forEach.callback (HubConnection.js:93)
    at Map.forEach (<anonymous>)
    at HubConnection.connectionClosed (HubConnection.js:92)
    at HttpConnection.HubConnection.connection.onclose (HubConnection.js:43)
    at HttpConnection.stopConnection (HttpConnection.js:122)
    at HttpConnection.eval (HttpConnection.js:112)
    at Generator.next (<anonymous>)
    at fulfilled (HttpConnection.js:6)
    at <anonymous>
```

**Comment by moozzyk** [comment]
When a hub connection is closed either by the server or by the user all pending invocations are terminated with the error you posted. The promise cannot be fulfilled without the result and there will never be a result because the connection is closed, so it is rejected. What is your expectation here?

**Comment by ZoolWay** [comment]
My expectation is that either the rejection is catched or I as a consumer of the library get the possibility to catch it. Throwing an exception which cannot be caught should not be the behaviour when normal operations occur.

**Comment by moozzyk** [comment]
When you invoke a hub method the Promise is [returned](https://github.com/aspnet/SignalR/blob/dev/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts#L175) to you. You can then use `.catch` on this promise to handle the exception.

**Comment by ZoolWay** [comment]
Ah, you mean `invoke` of `signalR.HubConnection` returns that promise which is rejected here? I did not recognize that and it are those promises which are rejected here.

So I am now totally able to catch the situation, thank you!

Hoping for docs and typings soon :)

**Comment by moozzyk** [comment]
This is correct. You also use this promise to get the result of non-void hub methods.
