### ISSUE TITLE
Npm install issue, no dist/browser files

### ISSUE THREAD

**Issue by pixelhandler** [aspnet/SignalR#1148]
When I `npm install @aspnet/signalr-client` I do not see any dist files

<img width="148" alt="signalr-wat" src="https://user-images.githubusercontent.com/17178/33147896-8b2aaa9a-cf7e-11e7-8780-5630a33b71f3.PNG">

Only a README and package.json. Is there a build step needed?

Looking at https://github.com/aspnet/SignalR/blob/dev/client-ts/README.md

> To use the client in a browser, copy *.js files from the dist/browser folder to your script folder include on your page using the <script> tag.

The package.json file has `"version": "1.0.0-alpha2-final"` but no `dist` directory.

**Comment by moozzyk** [comment]
Check using a different tool (file explorer, command line etc.). I saw VS code sometimes not showing files.

**Comment by pixelhandler** [comment]
ops yeah `dist` directory is hidden
