### ISSUE TITLE
signalr-client.js hub connection dataReceived - data object is not in JSON format

### ISSUE THREAD

**Issue by kenty30** [aspnet/SignalR#115]
var descriptor = JSON.parse(data);

**Comment by moozzyk** [comment]
please show what it is then

**Comment by BrennanConroy** [comment]
Right now clients don't support the Binary format, I changed it this morning to return from the server whatever format the client requests on connect, so if you pass binary in the query string you will get binary back. So use json in the query string if you want it to work.

**Comment by kenty30** [comment]
I'm passing "formatType=json&format=text", but on "dataReceived" I'm getting back blob. I'm using 1.0.0-preview1-23107

**Comment by BrennanConroy** [comment]
Need to use a newer build :P

**Comment by kenty30** [comment]
Ah make sense :) I've just got the latest and all working as expected. Thanks
