### ISSUE TITLE
Singlar Core Apache port forwarding issue

### ISSUE THREAD

**Issue by JinsPeter** [aspnet/SignalR#1150]
I'm working on a .net core web api app where I use signalr core. I used apache to redirect the web request to www.myserver.com to http://127.0.0.1:5000 which is where my kestral runs.
```
<VirtualHost *:80>
  ServerName www.myserver.com
  ProxyPreserveHost On
  ProxyPass / http://127.0.0.1:5000/
  ProxyPassReverse / http://127.0.0.1:5000/
  ErrorLog <errorLogLocation>/<errorLogFilename>.log
  CustomLog <errorLogLocation>/<customErrorLogFilename>.log common
</VirtualHost>
```
The issue is the http request works fine, signalr handshake works fine, gets me the connection id, but the  websocket connection fails with a message, error establishing connection with 
ws://www.myserver.com/SignalR?id='some-guid-here'.

I'm using RHEL and Apache.
Is there a way to give domain name to  Kestral in linux without apache.?

**Comment by ralsu091** [comment]
You can host asp.net core with nginx on linux:https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction?tabs=aspnetcore2x

**Comment by BrennanConroy** [comment]
You need to add some websockets proxy settings or use a different transport from your client

**Comment by JinsPeter** [comment]
Writing a rewrite condition on my website.conf file solved this issue for me using apache.

```
<VirtualHost *:80>
  ServerName www.myserver.com
  ProxyPreserveHost On
  ProxyPass / http://127.0.0.1:5000/
  ProxyPassReverse / http://127.0.0.1:5000/

   RewriteEngine on 
  RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC] 
  RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC] 
  RewriteRule /(.*) ws://127.0.0.1:5000/$1 [P]

  ErrorLog <errorLogLocation>/<errorLogFilename>.log
  CustomLog <errorLogLocation>/<customErrorLogFilename>.log common
</VirtualHost>
```

**Comment by BrennanConroy** [comment]
Glad you got it working!
I'm not too familiar with Apache config, but I think I saw someone have multiple `ProxyPass` settings, one for http and one for ws

**Comment by JinsPeter** [comment]
Yeah In that case, you will need different pathbase for each.
like we have `http;//example.com/api`  for http connection and `ws://example.com/hubname` for signalR connection.
But in our case of signalR core, the handshake request to singnalR that establishes the connection and bring the connection id is an http request. which will be `https://example.com/hubname`. 
So we need to forward http request to `example.com/hubname` as http and ws request to `example.com/hubname` as ws.

**Comment by JinsPeter** [comment]
I have the exact same issue now with nginx. Any solution??

**Comment by BrennanConroy** [comment]
https://www.nginx.com/blog/websocket-nginx/

**Comment by JinsPeter** [comment]
[https://github.com/aspnet/KestrelHttpServer/issues/1263](this) issue here give the answer
