### ISSUE TITLE
How to create mock objects?

### ISSUE THREAD

**Issue by ValdemarSharp** [aspnet/SignalR#1152]
I can't see IHubCallerConnectionContext interface now which was used in old SignalR versions. So, how can I create mock objects now? For example, mock groups and clients?

**Comment by BrennanConroy** [comment]
Try IHubContext

**Comment by ValdemarSharp** [comment]
But how can I setup a method for mock clients in this case? I tried:

`public interface IClientContract
{Task TestMethodClient();}`

`var chatHub = new ChatHub();`
`var mockContext = new Mock<IHubContext<ChatHub>>();`
`var all = new Mock<IClientContract>();`
`all.Setup(x => x.TestMethodClient()).Verifiable();`
`chatHub.Clients = mockContext.Object.Clients;`            
`mockContext.Setup(m => m.Clients.All).Returns(all.Object);`

However, it doesn not work, because the last line (.Returns(all.Object)) generates an error:

> cannot convert from 'IClientContract' to 'Microsoft.AspNetCore.SignalR.IClientProxy'

**Comment by davidfowl** [comment]
ChatHub would need to need to be a `Hub<IClientContract>` for that to work.
