### ISSUE TITLE
Rejecting connections

### ISSUE THREAD

**Issue by jawetzel** [aspnet/SignalR#1153]
after reading several docs for signalR, I cannot find a way to simply reject a connection request. 

The case is I can have a front end connect to my hub, and I can pass a token into the hub using a query string, and i can check my database to verify which user is connection and if they have permission, I am trying to find some way to respond refusing the connection.

My best guess is that i am needing to override the OnConnectedAsync method, and instead of returning base.OnConnectedAsync(); returning something else, what that other thing is, is where i am stuck.

**Comment by BrennanConroy** [comment]
In `OnConnectedAsync`: `Context.Connection.Abort();`

**Comment by jawetzel** [comment]
Thank you, I was digging through https://docs.microsoft.com/en-us/aspnet/signalr/overview/  Is that the wrong place to be looking for docs on this project?

**Comment by BrennanConroy** [comment]
Yes, we don't have docs for this project yet
