### ISSUE TITLE
Clients don't receive message (after upgrading to 1.0.0-alpha2-final)

### ISSUE THREAD

**Issue by pellea** [aspnet/SignalR#1154]
Hello,

After upgrading SignalR to 1.0.0-alpha2-final, clients don't receive messages anymore while it's working the other way (a client can send a message to the server).

Here is the call to InvokeAsync from the Hub (server-side):
```
            await this.Clients.All.InvokeAsync("test");
            await this.Clients.All.InvokeAsync("testNumber", 99);
```

Here is how I set up handlers on the clients:
```
            this._connection.On("test", () => { ... });
            this._connection.On<object>("testNumber", _ => { ... });
            this._connection.On<int>("testNumber", _ => { ... });
```

The connection on the client is build with "the new way":
```
this._connection = 
                new HubConnectionBuilder()
                    .WithConsoleLogger(LogLevel.Trace)
                    .WithUrl(this.BaseUrl)
                    .WithJsonProtocol()
                    .WithTransport(TransportType.WebSockets)
                    .Build();
```
Using `WithJsonProtocol` and/or `WithTransport ` has no impact. It doesn't work either way.

What have changed since the old preview ?

BTW, there is no logs, crashes.

**Comment by radu-matei** [comment]
Hi!
Do you have a repo of that code we can take a look at?

Thanks!

**Comment by BrennanConroy** [comment]
Can't repro.
Is there a stack trace when it crashes?

Also, setting up multiple handlers for the same name just overwrites and only uses the last one registered.

**Comment by pellea** [comment]
It doesn't crash at all.

I made a quick repro. You can find it here : https://github.com/pellea/signalr-debug.

Please delete, in the server project, the Properties/launchSetting.json file that is automatically created by VS2017. It's a pain to delete it every times VS starts ...

Steps to reproduce:
- start both projects
- click on the start button in the WPF app to connect to the server
- it will send a 'join' message 2 seconds in the connected callback
- the WPF app should reveice messages from the server and it doesn't.

I have probably missed something there ...

**Comment by BrennanConroy** [comment]
I think you deadlocked your client. Use `SendAsync` here https://github.com/pellea/signalr-debug/blob/master/TestApp/MainWindow.xaml.cs#L111
`InvokeAsync` waits for a response from the server but because you're waiting inside the `Connected` callback the client isn't executing any code to receive and complete the `InvokeAsync`. `SendAsync` is a fire and forget so it should unblock the client code.

After alpha2 we removed the `Connected` callback in favor of using the `Task` returned from `StartAsync`

**Comment by pellea** [comment]
Using the `SendAsync` method on the client solved the issue.

As I understand it, the `InvokeAsync` on the server should be renamed to `SendAsync`.

**Comment by muratg** [comment]
👍
