### ISSUE TITLE
Review ServerSentEvents transport for raw binary data

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#116]
The ServerSentEvents transport is currently only able to send simple text messages with no new lines (why? details below). We need to make some changes to support multi-line messages and binary messages

1. Split text messages on newlines and write them as individual `data: [line]` lines, in order to ensure they are properly reconstructed (see https://html.spec.whatwg.org/multipage/comms.html#event-stream-interpretation)

1. Base64-encode binary messages

In general we just need to review how we are intending to encode messages on transports. We can't just blindly write binary, or even text (if it has newlines), data to the transport because if the data includes bytes `0x0A` (`\n`) or `0x0D` (`\r`) it will break the protocol. Something to consider as we build the protocol for Long Polling to batch messages.

/cc @davidfowl

**Comment by anurse** [comment]
See #125

**Comment by muratg** [comment]
@anurse is this good to close?

**Comment by anurse** [comment]
Yes.
