### ISSUE TITLE
Flaky Docker Redis tests

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1160]
Expanding this somewhat: I now have consistent failures on my desktop at home due to the docker container not starting properly. We should add some better diagnostics to these tests to report issues if the container fails to start properly so we can track down why they are failing on some (read: my) machines.

When your Docker for Windows instance is configured either for "Windows Container" or "Linux Containers on Windows" (LCOW), the Redis tests fail to run. In the first case, because Redis is a linux container and in the second case because of some bug in LCOW (it's experimental) that causes it to fail.

We should detect those cases and skip running the tests. You can detect this by the following command:

With Windows Containers or LCOW on (what we don't want):

```
› docker system info -f "{{.OSType}}"
windows
```

With it off (what we want):

```
› docker system info -f "{{.OSType}}"
linux
```

**Comment by muratg** [comment]
These are running now. @ryanbrandenburg let us know if you hit this again.
