### ISSUE TITLE
Performance Investigation

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#1164]
Interesting data points:
- [ ] Memory per connection/transport
- [ ] Scaleout overhead
- [ ] Serialization/Deserialization
- [ ] Idle connection limit (this is super arbitrary, because a lot of different factors affect this, but semi-useful to have a rough number)
- [ ] Invocations per second (again a little arbitrary)
- [ ] Broadcast to many connections vs. send to individual (with same connection counts)

**Comment by BrennanConroy** [comment]
### Memory per connection/transport and Idle connection limit

Found issue with Kestrel that causes connections to allocate a lot https://github.com/aspnet/KestrelHttpServer/issues/2178
Will investigate memory after the issue has been fixed.

Another side-effect is that "idle connection limit" is limited by RAM because of the above issue, so will also revisit that once fixed.

**Comment by BrennanConroy** [comment]
### Serialization/Deserialization

Initial investigations show that a large portion of runtime time is spent here during an active application.

![perf](https://user-images.githubusercontent.com/7574801/33341759-d3e1aa76-d434-11e7-9974-b1caeb66d36f.PNG)

When broadcasting to multiple clients we send the plain `HubMessage` to every connection and each connection has to serialize the message individually. This destroys perf, a quick test where we deserialize once per type shows major improvement
https://github.com/aspnet/SignalR/blob/887e22ec075bce3c4645125675ee6fbbd69c4533/src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs#L75

Relevant: Micro-benchmarks show that MessagePack is faster than Json https://github.com/aspnet/SignalR/pull/1158#issue-277126274

**Comment by davidfowl** [comment]
@BrennanConroy Can you call out what the big remaining allocations are for idle connections?

**Comment by davidfowl** [comment]
@BrennanConroy can you do another performance round when this gets merged https://github.com/aspnet/SignalR/pull/1470

**Comment by davidfowl** [comment]
@BrennanConroy can you update this issue?

**Comment by anurse** [comment]
We're done with this issue now, we have more granular ones and we know what our perf process is.
