### ISSUE TITLE
Nuget Restore Fails when adding SignalR to .NET CORE APP (v2.0.3) 

### ISSUE THREAD

**Issue by Sabdeth** [aspnet/SignalR#1166]
Hello,

I upgraded my dotnet core app to version 2.0.3 and added the latest SignalR package but Im getting the following error! 

![image](https://user-images.githubusercontent.com/13154166/33392257-2d3e2668-d501-11e7-9f72-0fe2a8052ccd.png)

My .csproj file looks like this.
![image](https://user-images.githubusercontent.com/13154166/33392321-5bd3d72a-d501-11e7-9f76-46dd9da70659.png)

**Comment by muratg** [comment]
Could you share your full .csproj file, or even ideally a repro app on github?

cc @anurse

**Comment by anurse** [comment]
Hey @Sabdeth, I took an MVC app and updated `Microsoft.AspNetCore.All` to `2.0.3` and added a reference to `Microsoft.AspNetCore.SignalR` as you indicated, but I'm not seeing this error. It would be really helpful to see more of your csproj, to see if there are any other things that could be causing this error. If you'd rather not share it on GitHub, you can also email me directly at [my github user name]@microsoft.com

**Comment by Sabdeth** [comment]
@anurse I have sent an email to anurse@microsoft.com with my .csproj attached. Please let me know if you need anything else.

**Comment by Sabdeth** [comment]
Attaching a

**Comment by anurse** [comment]
To update this thread. I'm working with @Sabdeth to try and work out the problem. At this point, it appears to be a problem with the machine configuration (NuGet caches, or versions or something), and not directly related to SignalR. I'd like to keep this issue open until we confirm that though.

**Comment by Sabdeth** [comment]
Thanks to @anurse now I am able to restore my project. The problem was with my Nuget Cache. I ran **dotnet nuget locals all --clear** and it worked.
