### ISSUE TITLE
Stop using EventId of 0 for named events and tidy up logger extension methods.

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1169]
The EventID "0" tends to be reserved in our system for "unnamed" events. Note that other Logging Extension methods in other repos don't use it: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/MvcViewFeaturesLoggerExtensions.cs#L39

We should avoid using it and start known events from `1`. The Event ID `0` should remain reserved for unnamed events. We should definitely do this before preview 1, but it's a simple quick pass over our extension methods. We should also look at ways to ensure they don't get mixed up between categories. There are a couple ways to do this:

1. @rynowak has used this pattern: Add a static nested class called `Log` to the component itself that has these "extension" methods on them (they can't be true extension methods because of that). Then each of these classes has only the log messages relevant to that logger category. See https://github.com/aspnet/HttpClientFactory/blob/9a393fa4ce189fee3eaefe12ba2ad8a3dc06c752/src/Microsoft.Extensions.Http/Logging/LoggingHttpMessageHandler.cs#L47
2. Hang the extension methods off of `ILogger<T>` instead of `ILogger`. This doesn't stop you from mixing up event IDs though since the static field is "global".

**Comment by anurse** [comment]
One other crazy idea:

```csharp
public class SomeComponent
{
    private SomeComponentLogger _logger;
    public SomeComponent(ILogger<SomeComponent> logger) {
        _logger = new SomeComponentLogger(logger);
    }

    public void DoSomething() {
        _logger.SomeEvent(...);
    }

    private struct SomeComponentLogger {
        private static readonly Action<ILogger, ...> _someEvent = LoggerMessage.Define<...>(...);

        private ILogger _logger;
        public SomeComponentLogger(ILogger logger) {
            _logger = logger;
        }

        public void SomeEvent(...) {
            _someEvent(_logger, ...);
        }
    }
}
```

**Comment by muratg** [comment]
Moving to preview2, but if you feel like this can (and should) be done quickly in preview1, feel free to bring it back!

**Comment by BrennanConroy** [comment]
Prototype PR for when we do the actual change across the board: https://github.com/aspnet/SignalR/pull/1342

**Comment by davidfowl** [comment]
We did this AFAIK
