### ISSUE TITLE
Client not receiving messages

### ISSUE THREAD

**Issue by evenflow58** [aspnet/SignalR#117]
I've set up a SignalR test similar to that of the ChatSample but my client does not receive any messages. I can see it connecting and I can invoke a call from the client but whenever I attempt to send anything to the client my hub disconnects.

I don't have anything special in my StartUp, just AddSignalR in ConfigureServices and this in the Configure method:
```
app.UseSignalR(routes =>
{
   routes.MapHub<SlotHub>("/slot");
});
```
My hub is also pretty simplistic with just one method
```
public async Task Send(string message)
{
  await Clients.All.InvokeAsync("GetMessage", message);
}
```
Client code:
```
let connection = new signalR.HubConnection(url.concat('slot'), 'formatType=json&format=text');
connection.logging = true;

connection.start().then(() => {
    debugger;
    connection.on('GetMessage', (result) => {
      debugger;
      alert('Found something');
    });
            
  connection.invoke('Send', 'a message', 'json');
});
```
Is there anything I'm missing? It seems when InvokeAsync is called the connection is dropped but there is no error message in the OnConnectedAsync method. I've also noticed that the dataReceived method in signalr-client.js is never called.

**Comment by mikaelm12** [comment]
Can you send a link to a github repository of this project so I can repro this issue and investigate it further? Thanks!

**Comment by moozzyk** [comment]
Also, check what you see in the browser log/network - this might give you a hint.

**Comment by evenflow58** [comment]
Example [here](https://github.com/evenflow58/SignalRExample). (Run SignalRExample and open TestPage.html. Messages are spit out to the console log.)

This example with throw an error message:

> info: Microsoft.AspNetCore.Server.Kestrel[14]
>       Connection id "0HL1QS599DJPA" communication error
> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
> 

It doesn't look like the client is ever hit at all as the last thing I see in the network tab is the invoke. I also tried putting debuggers in the dataReceived function in signalr-client.js but they were never hit.

**Comment by mikaelm12** [comment]
@evenflow58  So to get the sample that you sent me to work I had to first add the StaticFiles Middleware  in your Startup.cs. Otherwise the TestPage can't be served. I also had to add a wwwroot folder and move the TestPage.html there so that the static file handler could find it. I then added the  signalr-client.js file that you referenced inTestPage but wasn't anywhere in the project to the wwwroot folder as well.
After that sample seemed to work with no issues.
Not exactly sure which or if any of these issues exist in your original project but that was enough to get this one working. 
Hope this helps

**Comment by evenflow58** [comment]
Sorry about the signalr-client.js file not being included. For some reason git decided to ignore it on check in.

I was just opening the page with just a web browser as if were a completely seperate application and not serving it through IIS. Did you run the project as IIS or just run the project as a service?

**Comment by mikaelm12** [comment]
I'm just running it locally with Kestrel.

**Comment by evenflow58** [comment]
Got it working with Kestrel so it would seem to be an environment issue. I do think it's weird that you can run it as a service and seemingly do everything except recieving messages from the client.
