### ISSUE TITLE
javascript client file for .net core2

### ISSUE THREAD

**Issue by wpitallo** [aspnet/SignalR#1175]
Hey how would I get the the client file to work without using node?

I tried using a raw copy of the file: 

https://rawgit.com/wpitallo/scripts/master/signalr-client-1.0.0-alpha2-final.js

But when it runs it does not resolve the HubConnection

I have created an example here:

https://codepen.io/Wpitallo/pen/zPyjVv?editors=1010

Thanks for the help,

Regards Warren

**Comment by BrennanConroy** [comment]
We have multiple samples
Take a look here:
https://github.com/aspnet/SignalR/tree/dev/samples
https://github.com/aspnet/SignalR-samples

**Comment by wpitallo** [comment]
Thanks so much, you a legend!
