### ISSUE TITLE
WebSocket 1006 errors on "some" machines

### ISSUE THREAD

**Issue by cannehag** [aspnet/SignalR#1179]
Hi, we are trying out the alpha2 version in an internal surveillance system.
Each browser calls a 'Subscribe' method on the hub and then receives messages on those subscriptions. This is just a simple group functionality.
It works very well for our developer machines. But when accessing the application from the surveillance machines, the connection is ok, the 'Subscribe' call looks ok, but then we get a WebSocket 1006 error:

Error: Websocket closed with status code: 1006 ()
    at WebSocket.o.onclose.t [as __zone_symbol__ON_PROPERTYclose] (vendor.597a23d9830566ab0b3e.bundle.js:1)
    at WebSocket.j (polyfills.7583531957896711067d.bundle.js:1)
    at e.invokeTask (polyfills.7583531957896711067d.bundle.js:1)
    at Object.onInvokeTask (vendor.597a23d9830566ab0b3e.bundle.js:1)
    at e.invokeTask (polyfills.7583531957896711067d.bundle.js:1)
    at r.runTask (polyfills.7583531957896711067d.bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.7583531957896711067d.bundle.js:1)
    at v (polyfills.7583531957896711067d.bundle.js:1)
    at WebSocket.d (polyfills.7583531957896711067d.bundle.js:1)

I'm really trying to figure out the reason for this, but the 1006 error seems kind of reserved and hidden since there is no reason given.

**Comment by cannehag** [comment]
Further investigation shows that it works using my own domain account. But not when using the accounts specific for surveillance. Is there some special permissions required on the accounts ?

**Comment by cannehag** [comment]
SOLVED!
For others having the same problem This issues was caused by Kaspersky Antivirus killing the connection for some reason that is unknown...

**Comment by imsam67** [comment]
I'm having the same issue. My ASP.NET Core 2.1 app w/ SignalR runs on Azure App service. I'm seeing the error on my Windows 10 machine with latest updates and no antivirus software other than what's built into Win10. Not sure if this is something I need to fix in my app or something caused by client computer in which case I worry that other users will have similar issues and not much I can do about it.

This seems to be happening after a long time of inactivity i.e. user is not sending/receiving messages from my chat app.

**Comment by anurse** [comment]
The `1006` error is given when the underlying TCP connection is terminated without a proper close handshake. It usually means some intermediate proxy or server along the path terminated the connection. In the original post, it was an anti-virus system, but it could also be a proxy on the server-side.

How many concurrent connections are you getting in your App Service app? There are known limitations on the number of concurrent connections. Also, I presume you have WebSockets enabled in the App Settings?

**Comment by imsam67** [comment]
The app is currently being tested so it's definitely not the number of concurrent connections at this point. At best, there would be 2-3 connections.

And yes, the WebSockets settings is enabled.

The app runs on Azure App service so everything is pretty much vanilla settings. Therefore, I'm not aware of any proxy settings. Is there particular place I can check on Azure portal for such a proxy setting?

Including the settings from the Azure portal below:
![capture](https://user-images.githubusercontent.com/15844030/44117914-3d29407c-9fda-11e8-9a36-96175f4b5720.JPG)

**Comment by anurse** [comment]
In Azure App Service the only proxies involved are IIS and the Azure App Service front-end. Can you post a new issue and describe the full situation there? Most importantly, we'll need to know what kind of behavior causes the error to occur (i.e. does it spontaneously happen after a certain amount of time, or do you have to do something to trigger it). Also, we'll need as much of the diagnostics described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) as you can give us.
