### ISSUE TITLE
Adding client certificate for mutual SSL in ASP.NET Core SignalR client

### ISSUE THREAD

**Issue by mcilis** [aspnet/SignalR#1184]
Hello, 

I'm trying to find a way of using a X509Certificate2 as a client certificate in a 
 Microsoft.AspNetCore.SignalR.Client application. Is it possible? 

The server was written using Microsoft.AspNet.SignalR and can be called by a Microsoft.AspNet.SignalR.Client like this:

`_hubConnection.AddClientCertificate(_clientCertificate);`

However, in Microsoft.AspNetCore.SignalR.Client there is no "AddClientCertificate" method.

How can I connect to this server?

Thanks,

**Comment by anurse** [comment]
You can use the `.WithMessageHandler` API on `HubConnectionBuilder` in the Alpha2 client to configure the HTTP Message Handler used for the ServerSentEvents and LongPolling transport. You can set that to your own custom instance of [`HttpClientHandler`](https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler(v=vs.118).aspx) and configure Client Certificates there. However, **this will not work with WebSockets**

For WebSockets, in Alpha2, we do not support client certificate authentication. However, in the nightly Preview1 builds you can use the `.WithWebSocketOptions` API on `HubConnectionBuilder` to configure the [`ClientWebSocketOptions`](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocketoptions(v=vs.110).aspx) object, which has Client Certificate configuration on it as well.

We should look at unifying some of the concepts between these transports though so I'm going to leave this issue open to cover that.

**Comment by anurse** [comment]
I actually decided to file https://github.com/aspnet/SignalR/issues/1210 to make the new work clearer. Closing this one now since the original question has been answered (feel free to comment and/or reopen if you still have an issue!)
