### ISSUE TITLE
Send introductory message on Connected

### ISSUE THREAD

**Issue by paultobey** [aspnet/SignalR#1185]
I'm using v1.0.0-alpha2-final against a .NET Core 2.0/ASP.NET Core 2.0 local server. The scenario I have is to "join" a group as soon as my client connects (basically a "hello" message immediately after connection is established). Messages from the server are all sent by group, so this is central to getting the client working. However, I was always getting a NullReferenceException in my call to InvokeAsync() from the Connected handler. 

I've built a simpler TestHub (more or less like Chat), for debugging. I've changed my Connected task to use SendAsync(), expecting the hello message to make a round-trip to my client, but the debug trace still seems to show a problem with this Connected send:

dbug: Microsoft.AspNetCore.Sockets.Client.HttpConnection[0]
      12/06/2017 08:33:29: Starting connection.
dbug: Microsoft.AspNetCore.Sockets.Client.HttpConnection[7]
      12/06/2017 08:33:29: Establishing Connection at: http://localhost:5000/signalr/hub/testHub.
dbug: Microsoft.AspNetCore.Sockets.Client.HttpConnection[2]
      12/06/2017 08:33:29: Connection Id c33ba0d7-3289-43f8-b882-16434f8f7937: Starting transport 'ServerSentEventsTransport' with Url: http://localhost:5000/signalr/hub/testHub?id=c33ba0d7-3289-43f8-b882-16434f8f7937.
info: Microsoft.AspNetCore.Sockets.Client.ServerSentEventsTransport[0]
      12/06/2017 08:33:29: Connection Id c33ba0d7-3289-43f8-b882-16434f8f7937: Starting transport. Transfer mode: Text.
dbug: Microsoft.AspNetCore.Sockets.Client.ServerSentEventsTransport[6]
      12/06/2017 08:33:29: Connection Id c33ba0d7-3289-43f8-b882-16434f8f7937: Starting the send loop.
dbug: Microsoft.AspNetCore.Sockets.Client.ServerSentEventsTransport[2]
      12/06/2017 08:33:29: Connection Id c33ba0d7-3289-43f8-b882-16434f8f7937: Starting receive loop.
dbug: Microsoft.AspNetCore.Sockets.Client.HttpConnection[3]
      12/06/2017 08:33:29: Connection Id c33ba0d7-3289-43f8-b882-16434f8f7937: Raising Connected event.
TestHubConnection_Connected. -- **This is my Task for Connection handling**
Sending hello message -- **This is sent just before calling SendAsync()**
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[6]
      Sending Invocation '1' failed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<SendInvocation>d__31.MoveNext()
Hello message sent -- **This is sent on return from SendAsync()**
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[22]
      Using HubProtocol 'json'.
dbug: Microsoft.AspNetCore.Sockets.Client.HttpConnection[17]
      12/06/2017 08:33:29: Connection Id c33ba0d7-3289-43f8-b882-16434f8f7937: Sending message.
dbug: Microsoft.AspNetCore.Sockets.Client.ServerSentEventsTransport[9]
      12/06/2017 08:33:29: Connection Id c33ba0d7-3289-43f8-b882-16434f8f7937: Sending 1 message(s) to the server using url: http://localhost:5000/signalr/hub/testHub?id=c33ba0d7-3289-43f8-b882-16434f8f7937.
dbug: Microsoft.AspNetCore.Sockets.Client.ServerSentEventsTransport[10]
      12/06/2017 08:33:29: Connection Id c33ba0d7-3289-43f8-b882-16434f8f7937: Message(s) sent successfully.

The hello message never makes the round-trip. However, if I send a similar message some time after Connected, that message makes the correct round trip. The repo for this would be huge, as it's a working, very large Web API, but I hope that you'll see something in the debug messages that suggest an explanation and action.

The client-side code is copied below for reference:

        private async Task<bool> SubscribeAllEvents(string path)
        {
            // Make sure that the path has a trailing /.
            if (!path.EndsWith("/"))
                path += "/";
            Uri pathUri = new Uri(path);

            if (testHubConnection == null)
            {
                Uri statusUri = new Uri(pathUri, testHubName);

                testHubConnection = new HubConnectionBuilder()
                    .WithUrl(statusUri)
                    .WithConsoleLogger(Microsoft.Extensions.Logging.LogLevel.Debug)
                    .WithJsonProtocol()
                    .Build();

                testHubConnected = false;

                // Get connect notifications.
                testHubConnection.Connected += TestHubConnection_Connected;
                testHubConnection.Closed += TestHubConnection_Closed;

                testHubConnection.On<string, string>("SendMessage", (reference, msg) =>
                {
                    // Take care not to use Invoke. We don't want to block handling of the On operation
                    // while the UI thread is awaited.
                    this.BeginInvoke((Action)(() => { StatusUpdatesEdit.Text += $"{reference}: {msg}\r\n"; }));
                });
            }

            if (!testHubConnected)
            {
                await testHubConnection.StartAsync().ConfigureAwait(false);
            }

            return true;
        }

        private async Task TestHubConnection_Connected()
        {
            System.Diagnostics.Debug.WriteLine("TestHubConnection_Connected.");

            testHubConnected = true;

            // Send a hello message.
            await SendHelloMessage().ConfigureAwait(true);

            return;
        }

        private async Task SendHelloMessage()
        {
            System.Diagnostics.Debug.WriteLine($"Sending hello message");

            await testHubConnection.SendAsync("SendMessage", "New User", "Hello, I'm a new client");

            System.Diagnostics.Debug.WriteLine($"Hello message sent");

        }

**Comment by BrennanConroy** [comment]
Unfortunately looks like a bug where we don't setup the underlying parser until after the Connected event is called, so if you send from the Connected event you can hit a null ref. We changed the API in the dev branch to no longer have a Connected event and instead you wait for StartAsync to finish and that is your "Connected" event. You should be able to change your logic here to workaround the issue

**Comment by anurse** [comment]
I'm closing this because in Preview 1 we've got a different approach to this that shouldn't cause this issue. If you still encounter this issue when preview 1 is released, please feel free to re-open. You can try nightly builds of preview 1 using the MyGet feed `https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json` and see if that new approach is going to work for your scenario.
