### ISSUE TITLE
Make MapHub and MapEndpoint consistent with other ASP.NET Core APIs (use PathString)

### ISSUE THREAD

**Issue by vany0114** [aspnet/SignalR#1188]
Hi guys,

Just to get know, recently I update the package to the alpha2-final (previously I had the preview2) and I noticed a lot of cool changes, so I just want to know one of them...why the `MapHub`and `MapEndPoint` methods can't receive a relative path now, for example "/chat" or "~/chat". Is there a special reason for that?

Thanks.

**Comment by anurse** [comment]
I'm not sure I understand what you mean. The path you provide is an application-relative path, so `.MapHub("/foo/bar")` would map to `http://localhost:1234/foo/bar` (assuming your site is hosted at `http://localhost:1234` and so on. Previous versions of SignalR didn't support mapping hubs to specific paths at all anyway :)

**Comment by vany0114** [comment]
Hi @anurse I mean, when I configure the Endpoint or Hub's map just like this:
```
routes.MapHub<Inventory>("/inventory");
routes.MapEndPoint<MessagesEndPoint>("/message");
```
I get this error:
> The route template cannot start with a '/' or '~' character. Parameter name: routeTemplate

But if I remove the `/` it works ok, so that's my question, in the previous version it worked with the  `/`
I just want to know if you all found out an issue about that.

**Comment by anurse** [comment]
Ah, that's just an incorrect API then. We should actually be using the `PathString` type anyway. The path is automatically prefixed with `/`, but in most of our other systems we expect the user to provide that, so we should fix these APIs to be the same.

**Comment by vany0114** [comment]
I see, thanks for your answer, if you want I could help with that, just let me know a bit about that APIs.

**Comment by anurse** [comment]
We'd definitely take a PR changing `MapHub` and `MapEndpoint` to take `PathString` instead of `string` ;). It would be very helpful!

I'm going to change the title of the issue, to reflect that change.

**Comment by vany0114** [comment]
Thanks @anurse, sure, I'm going to create the PR then!

**Comment by anurse** [comment]
Merged to dev in 31ef3c49df90731169b9c8ea5a6a707964a8001c

**Comment by anurse** [comment]
Thanks for the contribution @vany0114 !

**Comment by vany0114** [comment]
My pleasure @anurse!
