### ISSUE TITLE
Does not support self-host

### ISSUE THREAD

**Issue by AndrewLang** [aspnet/SignalR#1189]
SignalR supports self-host, here is the document [https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host](https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host). 

I need host SignalR Core in a process and I do it with following code, it runs and listen request from port 8787 correctly, but it is running in the main thread even I start it with a background thread, and it blocks other logic. 

**Is there a document of how to do self-host with SignalR Core?**

  var url = "http://localhost:8787";
            var mServer = 
                WebHost.CreateDefaultBuilder(args)
               .ConfigureServices(services =>
               {
                   services.AddSignalR();
                   services.AddSingleton<Chat>();
               })
               .Configure(builder =>
               {
                   builder.UseSignalR(routes =>
                   {
                       routes.MapHub<Chat>("Chat");
                   });
               })
               .UseUrls(url)
               .Build();

            mServer.Run();

            Console.ReadLine();

**Comment by anurse** [comment]
The `.Run` method on WebHost blocks the thread until the app shuts down. You can use `.StartAsync` to start the host without blocking the thread.

**Comment by AndrewLang** [comment]
Actually, I tried RunAsync(). Anyway StartAsync() works. 

Thanks.

**Comment by anurse** [comment]
Glad you got it worked out!
