### ISSUE TITLE
Transport Protocols

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#119]
We need to build some small protocols for transports in order to make them consistent with each other. This issue tracks the requirements and the proposed solutions. I'll start some PRs for simple "specs" for the necessary protocols to discuss those. Then I'll open issues for the actual work to get these implemented.

Requirements:

1. Text/Binary frame distinction
2. Binary-safe protocol (able to transmit arbitrary binary data)
3. Efficient round-trip time for sending messages to clients
4. Duplex (server can send to client and vice versa)

## WebSockets

Nothing, it's perfect :) (For our purposes). It has Text/Binary frame distinction, it's Binary-safe, and messages can be sent directly from server to client

## Server Sent Events

This is almost good enough, but has a few limitations.

It has no built in way to distinguish between binary and text messages, but it does have a `type` field, which we can use to transmit this.

It is not binary-safe because the payload is stored in a single line, with the line-terminator is the delimiter, and there is no way to escape it in a stable way. You can write multi-line messages, but `\r\n` terminators are converted to `\n`, which would break binary data. To solve this, we base64-encode binary messages, and properly escape line breaks in text messages.

It has an efficient round-trip time for sending to clients because the server can send unsolicited messages and the connection stays open.

Finally, it's not duplex, it's server-to-client only, so we need the `/send` endpoint to send from client to server

So, some sample encodings:

### Example 1

Text Message: `FooBar`
Encoding:

```
type: text\r\n
data: FooBar\r\n
\r\n
```

Reconstruction: `FooBar`

### Example 2

Text Message: `Foo\nBar`
Encoding:

```
type: text\r\n
data: Foo\r\n
data: Bar\r\n
\r\n
```

Reconstruction: `Foo\nBar`

### Example 3

Text Message: `Foo\r\nBar`
Encoding:

```
type: text\r\n
data: Foo\r\n
data: Bar\r\n
\r\n
```

Reconstruction: `Foo\nBar` * Note, loss of `\r\n`, but for text frames we allow that.

### Example 4

Binary Message: UTF-8 encoding of `A\r\nB`
Encoding:

```
type: binary\r\n
data: QQ0KQg==\r\n
\r\n
```

Reconstruction: UTF-8 encoding of `A\r\nB`

## Long Polling

The first major problem is that the round-trip time is bad since the client needs to start a new poll for each individual message from server to client. So to solve this, we batch messages and send multiple messages in a single HTTP response.

Also, it's not duplex, it's server-to-client only, so we need the `/send` endpoint to send from client to server

It also doesn't have a Text/Binary frame distinction, so we'll need to encode that in our batching protocol.

It is binary-safe, since the HTTP headers provide the framing. Since we are batching, our batching protocol needs to be binary-safe as well. However, browser APIs are limited to returning strings unless XHR2 and Blobs are supported on the browser, so base-64 encoding may be needed.

The specifics of the protocol need to be hashed-out as part of this issue.

/cc @mikaelm12 @moozzyk @davidfowl @DamianEdwards @BrennanConroy

**Comment by moozzyk** [comment]
I thought that for sse we will use different events for binary vs. text or embed type in the message. Otherwise we will have to correlate events.

**Comment by moozzyk** [comment]
I think you're right. I read it as a separate event but now I realized that there is no new line between type and data so it is one and not two separate events.

**Comment by anurse** [comment]
They're designed. Filing a new issue to implement.
