### ISSUE TITLE
Sockets Sample OnDisconnected method isn't called

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#1190]
When clicking disconnect after connecting a client in the sockets sample the OnDisconnectedAsync hub method doesn't get called.

**Comment by davidfowl** [comment]
Is this really a sample bug?

**Comment by anurse** [comment]
Yeah, the sample shouldn't be the one responsible for this. There might be a product bug here.

**Comment by mikaelm12** [comment]
I just saw it in the sample and didn't have a chance to investigate further yesterday. Wanted to make sure to log it

**Comment by BrennanConroy** [comment]
I reproed this on LongPolling only

**Comment by BrennanConroy** [comment]
Only happens when the debugger is attached FYI

**Comment by anurse** [comment]
Is that because ConnectionManager.Scan is disabled when the debugger is attached?

**Comment by davidfowl** [comment]
That must be it...

**Comment by anurse** [comment]
I go back and forth with that. Sometimes you want to debug disconnection logic and so you need it to be enabled, but often it just interferes with debugging by terminating connections while you're paused at a breakpoint.

**Comment by davidfowl** [comment]
So can we close this issue?

**Comment by anurse** [comment]
I think so. We can always reopen it :)
