### ISSUE TITLE
Event for all "incoming" messages

### ISSUE THREAD

**Issue by windischb** [aspnet/SignalR#1193]
Hi!

I'm searching for a way to get every message which is sent from a client to the server.

Maybe there is a better way for solving my problem...
The thing is, that we use IdentityServer for Authentication with Reference Tokens instead of JWT Tokens...
The Idea is now, to wrap every message between client and server in a simple object
```csharp
public class SignalRMessage
{
    public string Method { get; set; }
    public object[] Args { get; set; }
    public string Token { get; set; }
}
```
On every message from the client, the token can be checked against the Identityserver or a short cache.
If the token is valid, i can than call the correct Method. If not, an error message will be sent back.

So for me it would be perfect, if there is a way to get all messages which are receivied, and handle all things next by myself.
Exists anything like this?

Many thanks for your help!

**Comment by anurse** [comment]
Yeah, we've talked about adding this before. There are a number of good use-cases for being able to intercept and override the handling of `HubMessage`s flowing through the system. Haven't got a clear plan for it yet, but it's on the list to take a look at this after preview1 (our schedule for preview1 is pretty full unfortunately)

**Comment by anurse** [comment]
We've got https://github.com/aspnet/SignalR/issues/924 tracking that work so I'm going to close this issue in lieu of that one (to reduce duplication). Feel free to continue posting your comments on the subject here (we'll still be notified and respond) or on that issue. Thanks!
