### ISSUE TITLE
Flaky test: ObservableHubRemovesSubscriptionWhenCanceledFromClient

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#1196]
As seen [here](http://aspnetci/viewLog.html?buildId=364452&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe#testNameId-8838225944578153692).

It seems strange that this would be flaky considering that the exception message:
```
System.InvalidCastException : Unable to cast object of type 'Microsoft.AspNetCore.SignalR.Internal.Protocol.CompletionMessage' to type 'Microsoft.AspNetCore.SignalR.Internal.Protocol.StreamItemMessage'.
```
is an `InvalidCastException`. Possibly a failure path that doesn't usually get exercised?

**Comment by ryanbrandenburg** [comment]
CC @BrennanConroy.

**Comment by anurse** [comment]
Probably an ordering bug.

**Comment by davidfowl** [comment]
This was fixed a while ago
