### ISSUE TITLE
The Hub protocol needs framing

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#12]
Right now we're getting lucky that `JSON.Parse` works client side. In fact, it can break easily if you send enough data. This happens with long polling more often than not because it falls behind when data is sent between polls.

**Comment by moozzyk** [comment]
Shouldn't it be up to the formatter to be able to handle this? If the formatter does not consume all the data - should not next ReadAsync() return the unconsumed data?

**Comment by davidfowl** [comment]
This bug doesn't say what component should or shouldn't handle it. Just that we need a hub specific protocol.

**Comment by moozzyk** [comment]
Isn't it up to the protocol implementer to guarantee this (e.g. you use coded stream when using protobuf, json is self delimited etc.)? Even below hubs you need to know how to separate messages but it's not on the SignalR 'core' to deal with that - it just asks the formatter to read a value of the given type and the formatter needs to know how much data to read.

**Comment by davidfowl** [comment]
Followed up with  @moozzyk offline. We're on the same page. We need to implement client side invocation formatters and we'll be 90% there. Then we need to come up with "the format" for hubs.

**Comment by anurse** [comment]
Should we turn this into the "Hub Protocol" tracking issue? Do you want me to take this on after the transport protocols @davidfowl ? You said you'd work on it but that was like... year(s) ago.

**Comment by davidfowl** [comment]
Yes.

**Comment by anurse** [comment]
Duplicating to #20.
