### ISSUE TITLE
Don't use FormatException for negotiate response errors

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1203]
If the negotiate response from the server is invalid, the client throws `FormatException`. This is not an appropriate use of that exception, as it's supposed to be used when arguments that the caller provides are invalid. We should use either a custom exception type or something like `InvalidOperationException`.

**Comment by anurse** [comment]
The fix for this will lie in https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/NegotiationProtocol.cs, and corresponding tests in https://github.com/aspnet/SignalR/blob/dev/test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.cs

We need to discuss what exception to use, or if we should create a custom one. That should happen in this issue before starting on a PR :)

**NOTE**: In #1208, the HttpConnectionTests are being significantly rewritten and reordered. It would be worth waiting for that PR to finish before writing tests.

**Comment by jackjwilliams** [comment]
This looks like an easy one. I see no reason for a custom exception type for one class if InvalidOperationException fits the bill. Thoughts?

**Comment by anurse** [comment]
I'm not sure `InvalidOperationException` fits the bill though. The error cases we want to express here are when the server sends a malformed Negotiate response. I see `InvalidOperationException` as kinda like an HTTP 400 error, it indicates the caller of the method did something wrong. But the caller didn't do anything wrong, the server did something wrong. I think maybe [`InvalidDataException`](https://msdn.microsoft.com/en-us/library/system.io.invaliddataexception(v=vs.110).aspx) fits better.

If you'd like to send a PR for this, please feel free! Let me know if you have any questions or concerns (you can reach me directly at `anurse@microsoft.com` if you'd like some 1:1 assistance, I'm very happy to help a new contributor out)

**Comment by jackjwilliams** [comment]
Thanks! I've sent an introductory email. Yes, InvalidDataException does seem to fit better. It looks like we TryParseMessage the data, resulting in a payload (or a FormatException). Then attempt to read the Token, throwing a FormatException again if not valid.

Shouldn't be too difficult to change the exception type to InvalidDataException, keeping the error messages the same and update the test expectations.

**Comment by ankitvijay** [comment]
This looks to be an easy fix and good start for my first PR. I can take this up.

**Comment by jackjwilliams** [comment]
@ankitvijay, I already created a PR for this at https://github.com/aspnet/SignalR/issues/1246

**Comment by ankitvijay** [comment]
Hi, @jackjwilliams thanks for the info. I will try and pick something else.

**Comment by muratg** [comment]
Thanks @jackjwilliams for the contribution!
