### ISSUE TITLE
Allow Pipes used in SignalR to be bounded

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1207]
Server-side Unbounded Channels are a Bad Idea(TM). We should make sure to expose the ability to configure Bounded Channels for all of our channels.

**Comment by davidfowl** [comment]
This is an implementation detail. We need to figure out the implications of what we're doing right now and see if we need to expose anything or just pick a default (though, when has that ever worked without making it configurable).

**Comment by anurse** [comment]
Agreed, just want this tracked. Exposing it seems pretty much necessary for properly adapting to client load.

**Comment by anurse** [comment]
This should be done in Preview 2. I'm nervous it'll get missed. We'll need to look at how many Channels go away with the pipelines change, but if any are left they should be bounded.

**Comment by davidfowl** [comment]
So there are several things here:
- So we need to expose the thresholds.
- `PipeOptions` needs a size for  PauseWriterThreshold and ResumeWriterThresold  here https://github.com/aspnet/SignalR/blob/1bd37cabf0675dd24689e03c8724fd8277a8a9c3/src/Microsoft.AspNetCore.Sockets/ConnectionManager.cs#L59
- We need to pass the options in so we don't hardcode them.

**Comment by mikaelm12** [comment]
Done: 0e4731e480ba2d44963d43dfb99451ee468f5b77
