### ISSUE TITLE
Accessing a Scoped DBContext from the Hub (WebApi)

### ISSUE THREAD

**Issue by willthiswork89** [aspnet/SignalR#1209]
Hey guys, 

My Hub is trying to access a SQL Server through a DBContext and when i attempt to inject my repository pattern into my hub, it tells me that i cannot inject a scoped type into a singleton class. Since the hub HAS to be a singleton to save state, what is the best method for grabbing a scoped service to access the sql server repository ?

Thanks!

**Comment by willthiswork89** [comment]
Just to add, i tried manually grabbing the scoped service by requesting a copy through IServiceProvider.GetService<IChatroomRepository> and it says that there is no current scope  so it cannot find an instance of that.

**Comment by davidfowl** [comment]
This should work fine. The hub is transient by default. Did you manually add it to the container as a singleton? If you can provide us with a running sample pushed to a GitHub repository then we can take a look

**Comment by willthiswork89** [comment]
Alright so when i add the hub as transient to the web API instead of singleton, there is something happening with the persistence. I can connect but then when i send a message events never show up on the connected clients. 

In startup i have

`            app.UseWebSockets();
            app.UseSignalR(routes =>
            {
                routes.MapHub<ChatroomHub>("chatroom/messages");
            });`

and i added 

`services.AddTransient<ChatroomHub>();`


So it solved one problem but created another. When its added as a singleton the events work fine, i can connect a client, and when another client(or REST api call) hits, the clinet updates as expected but then the hub can't access the repository. When i add it as transient, the client connects fine but then becomes disconnected like the hub is being disposed or something. 

Ill Post a sample project up to look at in a minute.

**Comment by willthiswork89** [comment]
Yep just confirmed, clients is null when the chathub is manually added as transient. When scoped the clients list persists

**Comment by anurse** [comment]
The Hub is created when a message is received and destroyed when the message has been processed. If you want to persist state across multiple invocations, you need to store that state in a separate service with Singleton or Scoped lifetime.

Why are you adding the Hub to the DI container at all? If you just need dependencies to be injected into your Hub, that happens already for free, you don't need to add it to the container to get that.

**Comment by willthiswork89** [comment]
This is inside a WebApi, so calls can be inserted into the repository layer from standard Rest calls. Because of this, i need to be able to tell the hub about those changes as they come in. 

If what you are saying is true, how do Groups work at all? If i add a client to a group and then that hub gets destroyed how am i supposed to maintain those groups?

**Comment by anurse** [comment]
> If what you are saying is true, how do Groups work at all?

Just because the "Hub" class is destroyed after an invocation doesn't mean we throw all the other state away. That state is stored in other internal SignalR services that have a longer lifetime.

> Which means my service layer of my REST Api needs to have an instance of the hub, so that i can alert all associated chat members in a particular room about a new message

This is what `HubContext<T>` is for. You can inject `HubContext<MyHub>` into your Web API controller and get access to all the SignalR connections currently active for that Hub. You get a `.Clients` property there that you can use to invoke methods.

**Comment by davidfowl** [comment]
nit: IHubContext\<THub\> not HubContext\<THub\>.
