### ISSUE TITLE
Unify HTTP Configuration options in the client

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1210]
Right now, we have [`HttpOptions`](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpOptions.cs) on the client. It provides a single `Headers` property, but HTTPS Client Certificates have to be specified separately on the `HttpMessageHandler` and `WebSocketOptions` in order to support all transports. We should look at all the options available on  [`HttpClientHandler`](https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler(v=vs.118).aspx) and [`WebSocketOptions`](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocketoptions(v=vs.110).aspx) and provide a single place to configure those, so that customers don't have to configure things twice just to support all transports.

Note that we would only be able to use those unified values if the user doesn't replace the `HttpMessageHandler`. We don't want to start trying to configure custom `HttpMessageHandler` instances.

**Comment by JamesNK** [comment]
Fixed https://github.com/aspnet/SignalR/commit/d816c6ef6085976a880387d37f651d0cb1205c0e

**Comment by MderM** [comment]
It is not clear to me how the WebsocketOptions object correspond to the custom validator solution in the HttpClientHandler when dealing with self signed certificates.
A complete example for self signed certificate configuration would be very nice.

**Comment by anurse** [comment]
See my answer in the other thread in which you posted this question: https://github.com/aspnet/SignalR/issues/1389#issuecomment-381631416

**Comment by MderM** [comment]
Ok, thank you. Now I understand I just have an outdated package. Using the 2.1 preview for now which does not have this property.

**Comment by anurse** [comment]
The property will only be available if your **TargetFramework** is `netcoreapp2.1`. That's because this property only exists in .NET Core 2.1, not .NET Standard 2.0. The 2.1 preview should have this property if you are targeting the correct framework.

**Comment by MderM** [comment]
Ok, now it gets strange. I have VS Preview, 2.1-Preview SDK. Added a .net Core Console app. Retargeted to core 2.1.
...
.WithWebsocketOptions (opt => opt.-> does not give me the property...

where can I doublecheck, if the right packages are referenced? Sorry, new to the core world...

**Comment by anurse** [comment]
Can you post your project on GitHub and share a link?

**Comment by MderM** [comment]
[ConsoleApp2.zip](https://github.com/aspnet/SignalR/files/1918455/ConsoleApp2.zip)

These are the project file and Program.cs. Just open the project file and no callback property is there. I assume me using the wrong references, but I don't really know how to fix them.

**Comment by MderM** [comment]
Nevermind. Got it. I think I got too many different SDKs installed. Removed all and installed latest Preview2. Now the property is there. Hooray! Thanks for the help anyway.
