### ISSUE TITLE
TS Client clean-up

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1212]
* [x] Review the public API
* [x] Use `IHttpClient` abstraction in LongPollingTransport
* [ ] Add "abstraction" for `EventSource`. This could be as easy as allowing the Options to take a constructor to use instead of `new EventSource`, because JavaScript!
* [ ] Add "abstraction" for `WebSocket`, same as `EventSource`
* [ ] Write tests for these transports
* [x] Make functional tests consistent with unit tests: use TypeScript, build them in the same project?
* [x] Get source maps working in some form (stretch goal)

There are also some changes I want to consider to the actual way we build the TS client, but this issue is for tracking the changes that don't require build system changes.

**Comment by davidfowl** [comment]
Moving to preview2

**Comment by anurse** [comment]
Updated with what's been done already.

**Comment by anurse** [comment]
Closing this issue. It's not useful any more.
