### ISSUE TITLE
[Question] ASP.NET Core SignalR native iOS and Android clients?

### ISSUE THREAD

**Issue by adincebic** [aspnet/SignalR#1213]
I was wondering is there any hope that we will get native iOS (Swift) and Android (Java) clients? Currently we have it through the Xamarin, but it would be very convenient to have it for native development.

**Comment by anurse** [comment]
They are on the backlog, but right now the priority is getting the .NET and JavaScript clients ready. I don't believe we are going to get them in to the first release, but they are high up on the priority list for things to look at after the first release.

**Comment by kyschouv** [comment]
Adding to this: is there a C++ client that will work with this version of SignalR? We're currently dependent upon the old SignalR-Server version, and would love to upgrade, but won't be able to do so without a native client.

**Comment by anurse** [comment]
Also on the backlog. Unfortunately it's also not likely to arrive in the first release.

**Comment by kyschouv** [comment]
Is there a more detailed roadmap we could view somewhere? We're anxious to upgrade, but won't be able to do so without a client library. We're also discussing using SignalR for upcoming projects, but it may not be an appropriate choice depending on the timeline.

**Comment by anurse** [comment]
I'm not aware of any roadmap beyond what we've planned for 2.1, which is mostly about getting the server, C# client and JS client up and running. We're aware that this first release isn't going to be sufficient for some users to upgrade from SignalR 2.x, but we've got to focus on the core scenarios to get 2.1 out the door :).

**Comment by moozzyk** [comment]
@adincebic - you can find a functioning Swift client here: https://github.com/moozzyk/SignalR-Client-Swift. If you are running against alpha-2 sync use the release/1.0.0-alpha-2 branch. master branch works against latest SignalR. Currently the only supported transport is webSockets.

**Comment by Gurgen** [comment]
This is android lib for SignalR .net core version
[https://github.com/Gurgen/SignalR-.net-core-android-client](https://github.com/Gurgen/SignalR-.net-core-android-client)

**Comment by karthik55** [comment]
Hello, can any one share a functioning Swift client code link which supports .net _core_swift_client

**Comment by moozzyk** [comment]
@karthik55 - https://github.com/moozzyk/SignalR-Client-Swift. It has been updated to work with the recently released preview.

**Comment by karthik55** [comment]
Thanks @moozzyk

**Comment by moozzyk** [comment]
@karthik55 - the link I provided is for the SignalR Swift client that works with SignalR for ASP.NET Core. It supports secure connections (https and wss).

**Comment by adincebic** [comment]
@anurse  is there any update regarding native iOS and Android (Swift or Java / Kotlin) SignalR clients?

**Comment by anurse** [comment]
We are working on a native Java client for the ASP.NET Core 2.2 release, but we have not yet planned on a Swift client. Swift is still in our plans, it just didn't make the plans for the next release.

**Comment by smartStmobile** [comment]
@adincebic   I'm using this for Android client -> https://github.com/Gurgen/SignalR-.net-core-android-client.
It works fine for now. ;)

**Comment by Ktirumalsetty** [comment]
JsonElement availableTransportsElements = jsonElement.getAsJsonObject().get("availableTransports");
I dont see availableTransports in result json .did you face same issue?

**Comment by kietnguyenn** [comment]
@moozzyk sorry can't you show me the doc for your lib please :(
I read and understand nothing

**Comment by bradygaster** [comment]
@kiethandsome the doc page for our Java client is [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-2.2). We also have an up-to-date example using the new ASP.NET Core SignalR Client for Java with a sample Android project [here](https://github.com/aspnet/SignalR-samples/blob/master/PullRequestR/android/app/src/main/java/com/example/pullrequestr/MainActivity.java). 

Let us know if this isn't enough (or too much) and we'll try to accommodate.

**Comment by datwelk** [comment]
Any timeline on the official Swift client? @bradygaster

**Comment by bradygaster** [comment]
@datwelk apologies for the delay, we've been busy. 👍 

ATM, we have a lot of priorities and feature requests, as well as continuing to improve the serverless stories and working with the Azure SignalR Service. One question we ask ourselves during each milestone is "which client do we want to build this time." A full end-to-end client is a huge amount of work, and our next milestone (3.0.0) is when we'd like to bring C++ support. That could, in turn, mitigate some of the complexities we have going to a few other native languages. 

That said, **iOS native support is our absolute next big feature**. Supporting the SignalR Hub protocol specification (there's a doc on this, BTW) is a major engineering undertaking so we need to make sure we carve out these big items *and* support the community's awesome feedback, too. In addition, Swift seems to be a language that is still evolving rapidly; we're a little concerned that if we start supporting iOS developers with Swift today, that the next language version might change drastically. As such, we're contemplating building the client with Objective C, and exploring all the other options. 

Our timeline today puts the iOS support in late fall. I'd be interested in the community feedback on this.  Would it be a good idea for me to create a new issue we'd use for discussing the idea of a native iOS client? I'd love to get community input.

**Comment by moozzyk** [comment]
@kiethandsome - [this sample](https://github.com/moozzyk/SignalR-Client-Swift/blob/master/HubSample/AppDelegate.swift) should get you started. I am planning to write a blog post with better explanation soon.

**Comment by datwelk** [comment]
@bradygaster thank you for the extensive reply. Totally agreed regarding Swift, the language has been evolving rapidly, which isn't necessarily a bad thing but it becomes troublesome when trying to maintain a library. I think the fastest path towards an iOS client would be an Objective-C wrapper around the C++ client.
