### ISSUE TITLE
Can't find .WithWebSocketOptions()

### ISSUE THREAD

**Issue by siberianguy** [aspnet/SignalR#1215]
I'm trying to initialise connection but .WithWebSocketOptions could not be found:

```
                var hubConnection = new HubConnectionBuilder()
                        .WithUrl(feedUrl)
                        .WithTransport(TransportType.WebSockets)
                        .WithConsoleLogger(LogLevel.Trace)
                        .WithWebSocketOptions() //this line doesn't compile
                    .Build();
```
In the source code WithWebSocketOptions lies next to WithUrl, so I'm confused what could be a problem here.

**Comment by BrennanConroy** [comment]
You probably aren't referencing the latest version of SignalR packages. What version is your Microsoft.AspNetCore.SignalR.Client reference?

**Comment by anurse** [comment]
Are you using the Nightly feed? (https://github.com/aspnet/Home#builds)

That method was added after alpha 2 so it won't be in a public release until preview 1 is release.

**Comment by siberianguy** [comment]
Thanks! It does work with the latest nightly build.
