### ISSUE TITLE
Error: Failed to start the connection. Error: Method Not Allowed

### ISSUE THREAD

**Issue by hanxinimm** [aspnet/SignalR#1217]
when package version config
```
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" />
```
 is run better;

update to 

```
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
 <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="2.1.0-preview1-27815" />
```
![image](https://user-images.githubusercontent.com/13499426/33986947-28b98a06-e0fa-11e7-8db1-07db037f00d6.png)

![image](https://user-images.githubusercontent.com/13499426/33986783-9bd24812-e0f9-11e7-8dc1-92db04eb39b6.png)

**Comment by BrennanConroy** [comment]
Update your client first, since the product isn't released yet lots of breaking changes can happen between versions so you need to keep your client and server versions the same otherwise they might now work.

**Comment by kevingermain** [comment]
@hanxinimm I had the same problem and you have to try to update your client. Have a look here: https://dotnet.myget.org/feed/aspnetcore-dev/package/npm/@aspnet/signalr-client/1.0.0-preview1-27891 You have a list of packages and you can get the one compatible with your .net package and install it manually in node_modules.

**Comment by NeelBhatt** [comment]
As more people should be aware of this, I have written a post on this error which you can find here - https://neelbhatt.com/2018/03/09/solution-for-the-signalr-error-failed-to-start-the-connection-error-method-not-allowed-net-core-errors-part-iii/
