### ISSUE TITLE
@aspnet/signalr-client not found in dev registry

### ISSUE THREAD

**Issue by MattJeanes** [aspnet/SignalR#1221]
Hello, I'm trying to use your CI/dev version of the SignalR TypeScript client but both yarn and npm are having trouble both using adding `@aspnet:registry=https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/` to my .npmrc and also by calling `yarn install` / `npm install` with the `--registry @aspnet:registry=https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/` option

npm output:
```
npm install  @aspnet/signalr-client@latest
npm ERR! code E404
npm ERR! 404 Not Found: @aspnet/signalr-client@latest
```

yarn output:
```
yarn add @aspnet/signalr-client
yarn add v1.3.2
[1/4] Resolving packages...
error Couldn't find package "@aspnet/signalr-client" on the "npm" registry.
```

Removing the line from `.npmrc` or the `--registry` option from the cmd line both result in successful installs but from the npm registry rather than your dev one.

**Comment by acjh** [comment]
Try `@aspnet:registry=https://dotnet.myget.org/f/aspnetcore-dev/npm/`

**Comment by MattJeanes** [comment]
Yep that works great thanks 😄 - looks like the `README.md` needs updating then.. Will leave this open until that is updated because other people will likely hit the same issue
