### ISSUE TITLE
Problem restoring nuget 2.1.0-preview1-27838

### ISSUE THREAD

**Issue by JanEggers** [aspnet/SignalR#1227]
when trying to update to 

2.1.0-preview1-27838

i get an some errors saying (all aspnetcoredependencies): 

Microsoft.AspNetCore.Authorization >= 2.1.0-preview1-27838 can not be found 

best match:
https://dotnet.myget.org/f/aspnetcore-dev/api/v3/index.json 2.1.0-preview1-27819

do i need to include another feed or is the dependency version incorrect?

**Comment by BrennanConroy** [comment]
For now you can reference 2.1.0-preview1-27819 of our packages.

@ryanbrandenburg Why is Microsoft.AspNetCore.Authorization not updated on our feed?

**Comment by JanEggers** [comment]
as build/deps.prop points to version preview1-27776 i guess there is something wrong with your packaging

> For now you can reference 2.1.0-preview1-27819 of our packages.

no i cannot visual studio does a rollback when trying to update

**Comment by BrennanConroy** [comment]
You can open the csproj and change the version to 27819

**Comment by JanEggers** [comment]
ahh oki that worked, thx.

didnt know that there is a difference in behavior depending on where I change the version.

is there some option to make the ui behave like editing the file?

Here is the complete error output of the package manager btw. had to switch language so its all in english:

Unable to find package Microsoft.AspNetCore.Authorization with version (>= 2.1.0-preview1-27838)
  - Found 125 version(s) in aspnetcore-dev [ Nearest version: 2.1.0-preview1-27819 ]
  - Found 17 version(s) in nuget.org [ Nearest version: 2.0.1 ]
  - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.0.0-rc2-final ]
  - Found 0 version(s) in dotnet-core
  - Found 0 version(s) in aspnet-contrib
Unable to find package Microsoft.Extensions.DependencyInjection.Abstractions with version (>= 2.1.0-preview1-27838)
  - Found 125 version(s) in aspnetcore-dev [ Nearest version: 2.1.0-preview1-27819 ]
  - Found 11 version(s) in nuget.org [ Nearest version: 2.0.0 ]
  - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.0.0-rc2-final ]
  - Found 0 version(s) in dotnet-core
  - Found 0 version(s) in aspnet-contrib
Unable to find package Microsoft.Extensions.Logging.Abstractions with version (>= 2.1.0-preview1-27838)
  - Found 125 version(s) in aspnetcore-dev [ Nearest version: 2.1.0-preview1-27819 ]
  - Found 12 version(s) in nuget.org [ Nearest version: 2.0.0 ]
  - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.0.0-rc2-final ]
  - Found 0 version(s) in dotnet-core
  - Found 0 version(s) in aspnet-contrib
Unable to find package Microsoft.AspNetCore.Hosting.Abstractions with version (>= 2.1.0-preview1-27838)
  - Found 125 version(s) in aspnetcore-dev [ Nearest version: 2.1.0-preview1-27819 ]
  - Found 17 version(s) in nuget.org [ Nearest version: 2.0.1 ]
  - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.0.0-rc2-final ]
  - Found 0 version(s) in dotnet-core
  - Found 0 version(s) in aspnet-contrib
Unable to find package Microsoft.AspNetCore.Authorization.Policy with version (>= 2.1.0-preview1-27838)
  - Found 124 version(s) in aspnetcore-dev [ Nearest version: 2.1.0-preview1-27819 ]
  - Found 4 version(s) in nuget.org [ Nearest version: 2.0.1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in dotnet-core
  - Found 0 version(s) in aspnet-contrib
Unable to find package Microsoft.AspNetCore.WebSockets with version (>= 2.1.0-preview1-27838)
  - Found 125 version(s) in aspnetcore-dev [ Nearest version: 2.1.0-preview1-27819 ]
  - Found 9 version(s) in nuget.org [ Nearest version: 2.0.1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in dotnet-core
  - Found 0 version(s) in aspnet-contrib
Unable to find package Microsoft.AspNetCore.Routing with version (>= 2.1.0-preview1-27838)
  - Found 125 version(s) in aspnetcore-dev [ Nearest version: 2.1.0-preview1-27819 ]
  - Found 16 version(s) in nuget.org [ Nearest version: 2.0.1 ]
  - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.0.0-rc2-final ]
  - Found 0 version(s) in dotnet-core
  - Found 0 version(s) in aspnet-contrib
Unable to find package Microsoft.AspNetCore.Http.Features with version (>= 2.1.0-preview1-27838)
  - Found 125 version(s) in aspnetcore-dev [ Nearest version: 2.1.0-preview1-27819 ]
  - Found 15 version(s) in nuget.org [ Nearest version: 2.0.1 ]
  - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.0.0-rc2-final ]
  - Found 0 version(s) in dotnet-core
  - Found 0 version(s) in aspnet-contrib

**Comment by JanEggers** [comment]
narf just restore worked but when i try to build i get the same error :(

**Comment by BrennanConroy** [comment]
The NuGet UI should allow you to choose a version when updating or installing a package

**Comment by JanEggers** [comment]
yup but if i pick the latest version it does a silent rollback and if i open package manager output i get the output from above. 

anyway now its build that doesnt work.

can you please ping me when you figured out why your dependencies arent pushed to the feed.

**Comment by jbb352** [comment]
I had a similar problem when adding signalr 27838.  I worked around the issue by updating some of the dependent projects such as logging to 27819.  If you don't add them specifically it seems signalr will try to load 27838 version which doesn't exist.

**Comment by JanEggers** [comment]
with 27854 restore works
