### ISSUE TITLE
Want to run a .net framework 4.x or 3.x client against a asp.net core 2.0 signalr service. possible?

### ISSUE THREAD

**Issue by fogbridgegit** [aspnet/SignalR#1228]
Want to run a .net framework 4.x or 3.x client against a asp.net core 2.0 signalr service. possible?

for now my client is a .net framework 4.x or 3.x console app.
eventually it will be a DLL i drop into unity3d plugins directory.

Then i can call my methods like so  MyNet4ClientClass.MakeSignalrCoreCall(data).

Is this possible?   Can .NET 3.x or 4.x talk to asp.net core 2.0 signalr service?

I tried to add the nuget package for Microsoft.AspNetCore.SignalR 1.0.0-alpha2-final but....

"Could not install package 'Microsoft.AspNetCore.SignalR 1.0.0-alpha2-final'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	"

i thought this post was hopeful
https://www.rizamarhaban.com/2016/09/13/asp-net-core-signalr-for-windows-10-uwp-app/

in the post the guy talks to signalr code 2.0 from a UWP app 
the client UWP app uses  "Microsoft.AspNet.SignalR.Client": "2.2.1" from nuget

and service which uses Microsoft.AspNetCore.SignalR.Server: 0.2.0-alpha1-22118
obtained from https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json repository

this works its seems because these older SignalR.Server packages still exposes themselves the old signalr way.  you can see from the url it exposes at /signalr/hubs

but the new new signalr core changed its protocol sometime so now incompatible.

how can i talk to the new new signalr core from .net framework 4.x or 3.x client ?

**Comment by BrennanConroy** [comment]
You can't.
See other issues for explanations
https://github.com/aspnet/SignalR/issues/985
https://github.com/aspnet/SignalR/issues/883
https://github.com/aspnet/SignalR/issues/713

**Comment by fogbridgegit** [comment]
So my Hololens is dead in the water when it comes to signalr core :( :(

**Comment by fogbridgegit** [comment]
Couldnt i download the source code for signalr and then cut and paste every class in the client into a .NET 4.x library called MySignalr.Client.Core all the way down the dependency chain?

**Comment by BrennanConroy** [comment]
You can try to upgrade to .net 4.6.1 or higher and use the ASP.NET Core version

**Comment by fogbridgegit** [comment]
wait are you saying a .net 4.6.1 classic .net framework console app could use the ASP.Net core 2 signalr client library Microsoft.AspNetCore.SignalR.Client ?   sorry im new to .NET.

**Comment by BrennanConroy** [comment]
We target `netstandard2.0`, here is some details about that https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md

In short you can run .NET 4.6.1 apps with packages that target `netstandard2.0`. For SignalR you'll need both the server and client to be AspNetCore versions

**Comment by fogbridgegit** [comment]
wow that built!  ok going to toss the dll into unity 3d  and see if it barks at me

**Comment by fogbridgegit** [comment]
ok so i was able to build a DLL in .net 4.61 referring to Microsoft.AspNetCore.SignalR.Client from nuget.
i dropped that dll into the "assets/plugins" directory and i could call a basic GetSomeText function and display on the Unity3d game.   Then i went back and added the Broadcast sample code from signalr examples .. e.g.

        public void StartListening()
        { 
            _connection = new HubConnectionBuilder().WithUrl("http://192.168.1.2:5005/chat").WithConsoleLogger().Build();
            _connection.StartAsync();
            _connection.On<string, string>("broadcastMessage", (name, msg) =>

            {
                message = msg;

            });
        }

i then dropped the new DLL back in unity3d.   when i run from unity i get a 
TypeLoadException: Could not find method due to a type load error

Then when i build from unity to deploy to hololens i get 3 errors with long outputs.
UnityException: Failed to run reference rewriter with command --target="Temp\StagingArea\Tutorial.dll" --additionalreferences="Temp\StagingArea","Temp\StagingArea\Plugins\X64  .............................................................................

So i will go back and drop all the DLLs that came when i added Microsoft.AspNetCore.SignalR.Client to the .NET 4.6 app and see what happens.

**Comment by fogbridgegit** [comment]
so now im getting a couple errors like so..
Asssets/HoloToolkit/Utilities/Scripts/GLTF/Scripts/GLTFJsonExtensions.cs(10,50): error CS0433: The imported type `Newtonsoft.Json.JsonReader' is defined multiple times

so assuming the Holotoolit is bringing in stuff with its C# scripts that is already coming with the DLLs i imported.  Ill delete what i can from the holotoolkit and see what happens next.

**Comment by fogbridgegit** [comment]
its this line of code here in the inline C# scripts that unity 3d lets you program in.

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;

namespace GLTF.JsonExtensions
{
	public static class JsonReaderExtensions
	{
		public static List<string> ReadStringList(this JsonReader reader)

...

**Comment by fogbridgegit** [comment]
ok so removing those files causes more errors.   ill strip down my app to just the bare bones no holotoolkit

**Comment by fogbridgegit** [comment]
It works!!!!

**Comment by fogbridgegit** [comment]
Thanks for the help i guess my followup question now is how do i keep the Holotoolkit stuff which is written with inline unity 3D C# from bumping into the signalr core client / .NET 4.6 imported DLLs.  ?

**Comment by fogbridgegit** [comment]
o o.  i spoke too soon.   it works when i run it in the unity editor... but when i go to build to deploy on the hololens i get..

Microsoft (R) Visual C# Compiler version 42.42.42.42424
Copyright (C) Microsoft Corporation. All rights reserved.

error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\fogbr\.nuget\packages\System.Xml.XmlSerializer\4.0.10\ref\dotnet\System.Xml.XmlSerializer.dll' and 'C:\org\projects\MRTraining\src\srunity\Assets\Plugins\System.Xml.XmlSerializer.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\fogbr\.nuget\packages\System.Xml.XDocument\4.0.10\ref\dotnet\System.Xml.XDocument.dll' and 'C:\org\projects\MRTraining\src\srunity\Assets\Plugins\System.Xml.XDocument.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\fogbr\.nuget\packages\System.Threading.Timer\4.0.0\ref\netcore50\System.Threading.Timer.dll' and 'C:\org\projects\MRTraining\src\srunity\Assets\Plugins\System.Threading.Timer.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\fogbr\.nuget\packages\System.Threading.Tasks.Parallel\4.0.0\ref\netcore50\System.Threading.Tasks.Parallel.dll' and 'C:\org\projects\MRTraining\src\srunity\Assets\Plugins\System.Threading.Tasks.Parallel.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\fogbr\.nuget\packages\System.Threading.Tasks\4.0.10\ref\dotnet\System.Threading.Tasks.dll' and 'C:\org\projects\MRTraining\src\srunity\Assets\Plugins\System.Threading.Tasks.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\fogbr\.nuget\packages\System.Threading\4.0.10\ref\dotnet\System.Threading.dll' and 'C:\org\projects\MRTraining\src\srunity\Assets\Plugins\System.Threading.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\fogbr\.nuget\packages\System.Text.Encoding.Extensions\4.0.10\ref\dotnet\System.Text.Encoding.Extensions.dll' and 'C:\org\projects\MRTraining\src\srunity\Assets\Plugins\System.Text.Encoding.Extensions.dll'. Remove one of the duplicate references.

**Comment by fogbridgegit** [comment]
would it be possible to cut and paste all the Signalr Core Client code into inline classes inside unity?

**Comment by fogbridgegit** [comment]
ok so i got further into the build process by marking all the "duplicates" to "exclude platforms: WSAPlayer: whatever that means.   that eliminated all the "duplicates"  now im getting an error for 1?  of my dlls specifically MsgPack.dll

UnityException: Failed to run serialization weaver with command "Temp\StagingArea\Data\Managed\MsgPack.dll" "-pdb" "-verbose" "-unity-engine=Temp\StagingArea\Data\Managed\UnityEngine.CoreModule.dll" "Temp\StagingArea\TempSerializationWeaver" "-lock=UWP\project.lock.json"

**Comment by fogbridgegit** [comment]
i got a bit further into the build by doing the same trick of exclude platforms: WSAPlayer
on the  msgpack  dll.  now im getting:


UnityException: Failed to run assembly converter with command -metadata=0 -platform=uap -lock="UWP\project.lock.json" -uwpsdk=10.0.16299.0 Temp\StagingArea\System.Memory.dll -path="Temp\StagingArea".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Unity.FixReferencesStep.Visit(ICustomAttributeProvider provider, GenericContext context)
   at Unity.FixReferencesStep.ProcessModule()
   at Unity.ModuleStep.Execute()
   at Unity.FixReferencesStep.Execute()
   at Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
   at Unity.Operation.Execute()
   at Unity.Program.Main(String[] args)

PostProcessUAPDotNet.RunAssemblyConverterNoMetadata (System.String assembly) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessUAPDotNet.cs:127)
PostProcessWinRT.RunReferenceRewriter () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:718)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:202)
UnityEditor.WSA.BuildPostprocessor.DoPostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:142)
UnityEditor.WSA.BuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:149)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by fogbridgegit** [comment]
Error: type `System.Diagnostics.StackFrame` doesn't exist in target framework. It is referenced from System.Diagnostics.StackTrace.dll at System.Boolean System.Diagnostics.StackFrameExtensions::HasNativeImage(System.Diagnostics.StackFrame).
Error: type `Syst<message truncated>

**Comment by fogbridgegit** [comment]
Error: type `System.Diagnostics.Tracing.EventDataAttribute` doesn't exist in target framework. It is referenced from System.Diagnostics.Tracing.dll at System.Diagnostics.Tracing.EventCounterPayload.
Error: method `System.Void System.Diagnostics.Tracing.EventDataA<message truncated>

**Comment by fogbridgegit** [comment]
so took WSA player off all my DLLs that do signalr and just left it on the top level dll.  my "business logic" and now im getting a Error: type `Microsoft.AspNetCore.SignalR.Client.HubConnection` doesn't exist in target framework. It is referenced from Tutorial3.dll at Tutorial3.tutsr3.

Error: type `Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder` doesn't exist in target framework. It is referenced f<message truncated>



Im not getting whats going on here.  Can someone help me understand even if they dont have a solution?

I got a basic plugin hello world working without adding the signalr libraries.  the hellow world had 3 dlls referencing each other and that worked fine.



Signalr then works in the editor.  So why doesnt it build.



You cannot add it after the project is generated either.

**Comment by fogbridgegit** [comment]
when i try to add the signalr libraries to the generated project i get the following....

Restoring packages for C:\org\projects\MRTraining\src\srunity2\App\GeneratedProjects\UWP\Assembly-CSharp\project.json...
Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240). Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-arm. Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-arm-aot. Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-x64. Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-x64-aot. Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-x86. Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-x86-aot. Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package restore failed. Rolling back package changes for 'Assembly-CSharp'.
Time Elapsed: 00:00:02.3801569

**Comment by fogbridgegit** [comment]
i then saw the following https://developercommunity.visualstudio.com/content/problem/93522/uwp-uap10015063-not-compatible-with-net-standard-2.html

which explains to Choose the Windows 10 Fall Creators Update for both Target and Min version for my UWP app .  so i did that  in 2 ways...

tried to create a separate project in .net 4.6.1 and grabbing the nugets.
this let me create a class library that uses signalr core 2.0 client.
but the UWP app generated from unity3d wont let me add this as a project reference.

next i tried to directly add the signalr core 2.0 client. nugets to the generated UWP project from unity3d

but got the following errors


Detected package version outside of dependency constraint: Microsoft.NETCore.Runtime.Native 1.0.0 requires System.Diagnostics.Contracts (= 4.0.0) but version System.Diagnostics.Contracts 4.3.0 was resolved. Detected package version outside of dependency constraint: Microsoft.NETCore.Runtime.CoreCLR-x64 1.0.0 requires System.Diagnostics.Contracts (= 4.0.0) but version System.Diagnostics.Contracts 4.3.0 was resolved. Detected package version outside of dependency constraint: Microsoft.NETCore.Runtime.CoreCLR-x86 1.0.0 requires System.Diagnostics.Contracts (= 4.0.0) but version System.Diagnostics.Contracts 4.3.0 was resolved. Version conflict detected for System.Collections. Reference the package directly from the project to resolve this issue. Assembly-CSharp -> Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final -> Microsoft.AspNetCore.SignalR.Client.Core 1.0.0-alpha2-final -> Microsoft.AspNetCore.Sockets.Abstractions 1.0.0-alpha2-final -> System.Threading.Tasks.Channels 0.1.0-alpha-001 -> NETStandard.Library 1.6.1 -> System.Collections (>= 4.3.0) Assembly-CSharp -> Microsoft.NETCore.UniversalWindowsPlatform 5.0.0 -> Microsoft.NETCore.Runtime 1.0.0 -> Microsoft.NETCore.Runtime.CoreCLR-arm 1.0.0 -> System.Collections (= 4.0.10). System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.16299, but there is no run-time assembly compatible with win10-arm-aot. System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.16299, but there is no run-time assembly compatible with win10-x64-aot. System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.16299, but there is no run-time assembly compatible with win10-x86-aot. Package restore failed. Rolling back package changes for 'Assembly-CSharp'.

**Comment by fogbridgegit** [comment]
here are some updates concerning my issue:
still struggling...

long story short 
1. unity allows .net 4.6 dlls.
2. visual studio lets me create a .net 4.6 dlls with the new .net core 2.0 signalr client nugets because the new .net core 2.0 signalr client nugets target .netstandard2.0.
3. bringing in the 30+ DLLs into the unity plugins directory hasnt worked because even though i get signalr core connectivity from the editor. When i build to UWP there are like 10 different issues no matter what i try. Excluding WSA Player, If Defs. etc. all reach dead ends
4. Bringing in the new .net core 2.0 signalr client nugets into the generated UWP project also fails.

Here are the links.
https://developercommunity.visualstudio.com/content/problem/93522/uwp-uap10015063-not-compatible-with-net-standard-2.html

https://holodevelopers.slack.com/

https://www.rizamarhaban.com/2016/09/13/asp-net-core-signalr-for-windows-10-uwp-app/

https://github.com/aspnet/SignalR/issues/1228

http://www.harrysmemo.com/post/148213236737/developing-unity3d-apps-for-uwp-and-hololens

**Comment by fogbridgegit** [comment]
Fyi ... the BestHttp Unity Asset from Asset Store doesnt connect to Signalr Core  https://www.assetstore.unity3d.com/en/#!/content/10872
I got beat for $60 hoping it would work.  Here is the difference....

Here is what regular Signalr package references look like.  (BestHttp Unity Asset)
Server:  PackageReference Include="Microsoft.AspNet.SignalR" Version="2.2.2" 
Client:  PackageReference Include="Microsoft.AspNet.SignalR.Client" Version="2.2.2" 


Here is what Core SignalR package references look like.
Server:  PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" 
Client:  PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="1.0.0-alpha2-final" 


Here is what regular Signalr client sends: (BestHttp Unity Asset)
HTTP/1.1 GET http://192.168.1.4:5005/chat/negotiate?tid=0&_=2566636909&clientProtocol=1.5&connectionData=[%7B%22Name%22:%22ChatHub%22%7D]


Here is what  Core SignalR  sends:
HTTP/1.1 GET http://192.168.1.4:5005/chat?id=f78745aa-d21d-4773-9cba-5e27b1fe7b60

more detail at: https://forums.hololens.com/discussion/comment/19635#Comment_19635

**Comment by fogbridgegit** [comment]
im currently stuck at the following errors after i edit the min and max versions in the generated UWP project to target Fall Creators Update. as advised here:
https://developercommunity.visualstudio.com/content/problem/93522/uwp-uap10015063-not-compatible-with-net-standard-2.html



Restoring packages for C:\org\projects\MRTraining\src\srunity2\App\GeneratedProjects\UWP\Assembly-CSharp\project.json...
Detected package version outside of dependency constraint: Microsoft.NETCore.Runtime.CoreCLR-arm 1.0.0 requires System.Diagnostics.Contracts (= 4.0.0) but version System.Diagnostics.Contracts 4.3.0 was resolved.
Detected package version outside of dependency constraint: Microsoft.NETCore.Runtime.Native 1.0.0 requires System.Diagnostics.Contracts (= 4.0.0) but version System.Diagnostics.Contracts 4.3.0 was resolved.
Detected package version outside of dependency constraint: Microsoft.NETCore.Runtime.CoreCLR-x64 1.0.0 requires System.Diagnostics.Contracts (= 4.0.0) but version System.Diagnostics.Contracts 4.3.0 was resolved.
Detected package version outside of dependency constraint: Microsoft.NETCore.Runtime.CoreCLR-x86 1.0.0 requires System.Diagnostics.Contracts (= 4.0.0) but version System.Diagnostics.Contracts 4.3.0 was resolved.
Version conflict detected for System.Collections. Reference the package directly from the project to resolve this issue. 
 Assembly-CSharp -> Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final -> Microsoft.AspNetCore.SignalR.Client.Core 1.0.0-alpha2-final -> Microsoft.AspNetCore.Sockets.Abstractions 1.0.0-alpha2-final -> System.Threading.Tasks.Channels 0.1.0-alpha-001 -> NETStandard.Library 1.6.1 -> System.Collections (>= 4.3.0) 
 Assembly-CSharp -> Microsoft.NETCore.UniversalWindowsPlatform 5.0.0 -> Microsoft.NETCore.Runtime 1.0.0 -> Microsoft.NETCore.Runtime.CoreCLR-arm 1.0.0 -> System.Collections (= 4.0.10).
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.16299, but there is no run-time assembly compatible with win10-arm-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.16299, but there is no run-time assembly compatible with win10-x64-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.16299, but there is no run-time assembly compatible with win10-x86-aot.
Package restore failed. Rolling back package changes for 'Assembly-CSharp'.
Time Elapsed: 00:00:02.0802231
========== Finished ==========

**Comment by anurse** [comment]
What version of Unity are you using? My understanding is that .NET Standard 2.0 support requires 2018.1, which has not yet been released. See https://forum.unity.com/threads/net-standard.451314/ for some more context.

**Comment by scarffy** [comment]
Sorry if I overtake your thread but I'm wondering if you run into this error when you build?
Because it seems like our problem is quite similar. 

> 
> ArgumentException: The Assembly System.Reflection.Emit is referenced by Microsoft.AspNetCore.SignalR.Core ('Assets/Plugins/Microsoft.AspNetCore.SignalR.Core.dll'). But the dll is not allowed to be included or could not be found.
> UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:152)
> UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:192)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Ryujose** [comment]
For what I understand @scarffy 2018.1 should run .NET standard 2.0 version but it's a beta so you will experiment a lot of Instability. Remember that .NET 4.6 is on an experimental phase too inside of the releases.

I assume that you're running this version. If not, you'll have to download or wait for the final release to minimize the trouble on your final release of the think that you want to develop.

Take a look to the URL that @anurse shared with us, there's a good information about it.

Regards.
