### ISSUE TITLE
ignore this issue reposting cleaner thread....  ( dont know how to delete )

### ISSUE THREAD

**Issue by fogbridgegit** [aspnet/SignalR#1232]
Ive been going 1 by one and adding the packages the error output advises to manually.
but keeps asking for more and more.   here is the current conflict.

Version conflict detected for System.Collections. Reference the package directly from the project to resolve this issue.
Assembly-CSharp -> Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final -> Microsoft.AspNetCore.SignalR.Client.Core 1.0.0-alpha2-final -> Microsoft.AspNetCore.Sockets.Abstractions 1.0.0-alpha2-final -> System.Threading.Tasks.Channels 0.1.0-alpha-001 -> NETStandard.Library 1.6.1 -> System.Collections (>= 4.3.0)
Assembly-CSharp -> Microsoft.NETCore.UniversalWindowsPlatform 5.0.0 -> Microsoft.NETCore.Runtime 1.0.0 -> Microsoft.NETCore.Runtime.CoreCLR-arm 1.0.0 -> System.Collections (= 4.0.10).

**Comment by fogbridgegit** [comment]
wow this is hard work.  so only 1 conflict exposes itself at a time.  So im sitting here doing the following
1.  right click on "Assembly-CSharp" universal project 
2.  manage nuget.
3.  select Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final
4.  Look in the Output window for the conflict.
5.  manually add the lower one that universal wants  ( hoping that doesnt eventually break signalr )
6.  repeat for all Signalr dependency chain which in a seperate project i see brings 70 Dlls

:( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :( :(

**Comment by ColbyBurke** [comment]
I cant even get useSIgnalR() or addSignalR() to work correctly.... wtf is wrong with it?

**Comment by fogbridgegit** [comment]
i had that problem back in august bro.   ended up being something about getting ASP.net core from one place (nuget) and Signalr Core was coming from another (myget).  and something was missing but you would only get the error at runtime not at build time.  :( :(

**Comment by ColbyBurke** [comment]
I dont even know how to use myget or what that is lol. I wish theyd just update it.

**Comment by fogbridgegit** [comment]
dude i just got beat cause some guy in the hololens forum told me he was running .net core client from a package he downloaded from unity assets store.   hes like "I just checked a Unity project I used it, and the server it is talking to is running SignalR.Core v2.2.2. You should be good to go"

So i download the package and as i suspected it has nothing to do with Core.  :( :( :(

**Comment by ColbyBurke** [comment]
Damn, I might as well start scamming and quit coding

**Comment by fogbridgegit** [comment]
you would think the worlds "First Holographic Device" would get more love.  Im gonna have to not send Satya Nadella a xmas card this year ;)   i tried everything.  I even downloaded the source for signalr thinking .. you know its just a simple messaging app right?   cant be that much code.  Dude all the dependencies is like 5 different githubs and like 50 projects LOL

**Comment by ColbyBurke** [comment]
can you pleeeassseee help me with my issues since you fixed them

**Comment by fogbridgegit** [comment]
whats your issue?

**Comment by ColbyBurke** [comment]
the useSignalR and addSignalR and basically the using of aspnetcor.signalr.xxx being messed up

**Comment by fogbridgegit** [comment]
open powershell and type dotnet --info

**Comment by fogbridgegit** [comment]
not inside your project directory.. somewhere nuetral

**Comment by fogbridgegit** [comment]
we can use the phone too if you want 646 962 1110 ( google voice )

**Comment by ColbyBurke** [comment]
so i just downloaded it and typed it in... it tells me the versions and stuff?

**Comment by fogbridgegit** [comment]
call me and cut and paste the info here

**Comment by ColbyBurke** [comment]
i tried your number but I guess I need google voice, i cant really talk right now

**Comment by ColbyBurke** [comment]
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by fogbridgegit** [comment]
ive got this 
PS C:\Users\fogbr> dotnet --info
.NET Command Line Tools (2.2.0-preview1-007814)

Product Information:
 Version:            2.2.0-preview1-007814
 Commit SHA-1 hash:  d833eaa657

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-preview1-007814\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26016-07
  Build    : b61508038835f31a099ce44f1b1c970878211fcd

**Comment by ColbyBurke** [comment]
damn how do you update those?

**Comment by fogbridgegit** [comment]
you can reach my levels by the following links

.NET Core Runtime & Host Setup Repo
repo contains the code to build the .NET Core runtime, libraries and shared host (dotnet) installers for all supported platforms.
https://github.com/dotnet/core-setup#daily-builds


Installers and Binaries
 .NET Core SDK as either an installer (MSI, PKG) or a zip (zip, tar.gz).
https://github.com/dotnet/cli#installers-and-binaries

**Comment by fogbridgegit** [comment]
get the windows 64 installer master branch and install that for both the dotnet cli (link2) and the sdk (link1 )
then also use the visual studio installer to get to version 15.5.2 of visual studio 2017

**Comment by fogbridgegit** [comment]
once you got all that working create a fresh .NET Core MVC project and just run it to see if it works without signalr

**Comment by fogbridgegit** [comment]
then download the latest node.js from https://nodejs.org/en/  im using v9.2.1

**Comment by fogbridgegit** [comment]
your gonna use nodes package manager tool to download the signalr javascript . by using the command from powershell inside the root of your project folder.
type npm install @aspnet/signalr-client

**Comment by fogbridgegit** [comment]
this will put the javascript file signalr-client inside a directory called node_modules

**Comment by fogbridgegit** [comment]
copy the whole signalr folder from the node-modules directory into the lib folder under your wwwroot

create an HTML file and put it inside the WWW directory and add the line
<script type="text/javascript" src="lib/signalr-client/dist/browser/signalr-client-1.0.0-alpha2-final.js"></script>

**Comment by fogbridgegit** [comment]
heres my hello world HTML file.

<!DOCTYPE html>
<html>
<head> <title>Simple Chat</title> </head>


<body>
    <div class="container">

        <input type="text" id="message" />
        <input type="button" id="sendMessage" value="Send" />
        <ul id="discussion"></ul>
    </div>

    <script type="text/javascript" src="lib/signalr-client/dist/browser/signalr-client-1.0.0-alpha2-final.js"></script>

    <script type="text/javascript">

        var transport = signalR.TransportType.WebSockets;

        var connection = new signalR.HubConnection(`http://${document.location.host}/chat`, { transport: transport });



        var messageInput = document.getElementById('message');

        var name = prompt('Enter your name:', '');

        var button = document.getElementById("sendMessage");


     
        connection.on('broadcastMessage', (name, message) => {


            var liElement = document.createElement('li');

            liElement.innerHTML = '<strong>' + name + '</strong>:&nbsp;&nbsp;' + message;

            document.getElementById('discussion').appendChild(liElement);

        });



        button.addEventListener("click", event => {

            connection.invoke('send', name, messageInput.value);

            messageInput.value = '';

            messageInput.focus();

        });
 
        connection.start();

    </script>

</body>
</html>

**Comment by fogbridgegit** [comment]
some of the tags were stripped off of my html file but you get the picture.

now go to your Startup.cs

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            services.AddSignalR();
 

        }



     public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseFileServer();

            app.UseSignalR(routes =>

            {

                routes.MapHub<ChatHub>("chat");
 
            });

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }

**Comment by ColbyBurke** [comment]
ok i cant get the .net core runtime to download because of avast but ill try everything else

**Comment by fogbridgegit** [comment]
you need everything.

**Comment by ColbyBurke** [comment]
.NET Command Line Tools (2.2.0-preview1-007835)

Product Information:
 Version:            2.2.0-preview1-007835
 Commit SHA-1 hash:  6894eb0e6e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-preview1-007835\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26015-04
  Build    : 8485f1ee2416d900d57074e2ae21f287b0c2c3b2

**Comment by fogbridgegit** [comment]
maybe you can download it to your phone then email yourself from your phone or something crazy like that

**Comment by fogbridgegit** [comment]
your program.cs should look like this...

        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseUrls("http://*:5005")
                .Build();

**Comment by ColbyBurke** [comment]
no i got it

**Comment by ColbyBurke** [comment]
i literally just updates nodejs so do i need to download?

**Comment by fogbridgegit** [comment]
ok you good with node.

your chat hub should look like this...

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.SignalR;

namespace IoTDemo2.Web1.Hubs
{
    public class ChatHub : Hub
    {
        public async Task Send(string name, string message)

        {

            // Call the broadcastMessage method to update clients.

            for (int i = 0; i < 20; i++)

            {

                //observer.OnNext($"sending...{i}");
                await Clients.All.InvokeAsync("broadcastMessage", name, message);

                await Task.Delay(1000);

            }


        }


        public override Task OnConnectedAsync()
        {
            Clients.All.InvokeAsync("broadcastMessage", "system", $"{Context.ConnectionId} joined the conversation");
            return base.OnConnectedAsync();
        }

        public override Task OnDisconnectedAsync(System.Exception exception)
        {
            Clients.All.InvokeAsync("broadcastMessage", "system", $"{Context.ConnectionId} left the conversation");
            return base.OnDisconnectedAsync(exception);
        }
    }
}

**Comment by fogbridgegit** [comment]
your csproj file should look similar to this..

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>
  
  <ItemGroup>

    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="1.0.0-alpha2-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>



</Project>

**Comment by fogbridgegit** [comment]
<TargetFramework>netcoreapp2.0</TargetFramework>

**Comment by fogbridgegit** [comment]
let me know if you have any problems

**Comment by fogbridgegit** [comment]
open 2 browsers to http://192.168.1.10:5005/  and test    ( whatever your local lan ip is )

**Comment by ColbyBurke** [comment]
omg this might work

**Comment by ColbyBurke** [comment]
so I just build from here?

**Comment by fogbridgegit** [comment]
just run the project and hit your local ip.

**Comment by fogbridgegit** [comment]
use chrome browser is the best cause it has the dev tools you can watch for any signalr errors with ctrl-shift-i

**Comment by ColbyBurke** [comment]
what do you mean hit my local ip?

**Comment by fogbridgegit** [comment]
when you run your project its going to host the kestrel webserver at http://192.168.1.10:5005/   or whatever the ip address was given to your computer by DHCP   you can find this address by typing ipconfig at the cmd prompt   mine is http://192.168.1.10:5005/

**Comment by ColbyBurke** [comment]
ok

**Comment by fogbridgegit** [comment]
put that into the web browser and it will hit your signalr hub.  open up another browser and the real test is wether browser 1 receives data from browser 2

**Comment by ColbyBurke** [comment]
it does localhost do ii change it?

**Comment by ColbyBurke** [comment]
okok

**Comment by fogbridgegit** [comment]
i dunno bro just try different things

**Comment by ColbyBurke** [comment]
lol gotcha thanks

**Comment by fogbridgegit** [comment]
np let me know if you score a touchdown :)

**Comment by ColbyBurke** [comment]
which ip do you use though?
sorry im dumb

**Comment by fogbridgegit** [comment]
ok youre pulling my leg now bro.   lol  gnite.

**Comment by fogbridgegit** [comment]
tell your buddies to stop playing tricks and help a brother out over here.

**Comment by ColbyBurke** [comment]
im not haha you said goodnight

**Comment by fogbridgegit** [comment]
im goign to delete this post and repost my original problem.   this message will self destruct soon.
