### ISSUE TITLE
Cant use addSignalR() or useSignalR() or "Clients" or IHubContext in ASP.NET Core + Swagger

### ISSUE THREAD

**Issue by ColbyBurke** [aspnet/SignalR#1233]
Im wondering why I'm not able t complete my proram using the given methods... is it a NuGet thing on a recent update or  what? And how do I use myget?

**Comment by acjh** [comment]
NuGet package: `https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json`
- Add to NuGet Package Manager in VS 2017

JavaScript client: `https://dotnet.myget.org/f/aspnetcore-dev/npm/`
- Instruction in the [README](https://github.com/aspnet/SignalR#readme) right on the repo's front page

**Comment by ColbyBurke** [comment]
How do I add the nuget package?

**Comment by fogbridgegit** [comment]
.NET Core Runtime & Host Setup Repo
repo contains the code to build the .NET Core runtime, libraries and shared host (dotnet) installers for all supported platforms.
https://github.com/dotnet/core-setup#daily-builds

Installers and Binaries
.NET Core SDK as either an installer (MSI, PKG) or a zip (zip, tar.gz).
https://github.com/dotnet/cli#installers-and-binaries

     

get the windows 64 installer master branch and install that for both the dotnet cli (link2) and the sdk (link1 )
then also use the visual studio installer to get to version 15.5.2 of visual studio 2017


     

once you got all that working create a fresh .NET Core MVC project and just run it to see if it works without signalr


then download and install the latest node.js from https://nodejs.org/en/ im using v9.2.1


your gonna use nodes package manager tool to download the signalr javascript . by using the command from powershell inside the root of your project folder.
type npm install @aspnet/signalr-client


this will put the javascript file signalr-client inside a directory called node_modules

copy the whole signalr folder from the node-modules directory into the lib folder under your wwwroot

create an HTML file and put it inside the WWW directory and add the line

<script type="text/javascript" src="lib/signalr-client/dist/browser/signalr-client-1.0.0-alpha2-final.js"></script>

     

heres my hello world HTML file.

`

<title>Simple Chat</title>
    <input type="text" id="message" />
    <input type="button" id="sendMessage" value="Send" />
    <ul id="discussion"></ul>
</div>

<script type="text/javascript" src="lib/signalr-client/dist/browser/signalr-client-1.0.0-alpha2-final.js"></script>

<script type="text/javascript">

    var transport = signalR.TransportType.WebSockets;

    var connection = new signalR.HubConnection(`http://${document.location.host}/chat`, { transport: transport });



    var messageInput = document.getElementById('message');

    var name = prompt('Enter your name:', '');

    var button = document.getElementById("sendMessage");


 
    connection.on('broadcastMessage', (name, message) => {


        var liElement = document.createElement('li');

        liElement.innerHTML = '<strong>' + name + '</strong>:&nbsp;&nbsp;' + message;

        document.getElementById('discussion').appendChild(liElement);

    });



    button.addEventListener("click", event => {

        connection.invoke('send', name, messageInput.value);

        messageInput.value = '';

        messageInput.focus();

    });



    connection.start();

</script>
`

     


now go to your Startup.cs

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();

        services.AddSignalR();


    }



 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
            app.UseBrowserLink();
        }
        else
        {
            app.UseExceptionHandler("/Home/Error");
        }

        app.UseStaticFiles();

        app.UseFileServer();

        app.UseSignalR(routes =>

        {

            routes.MapHub<ChatHub>("chat");

        });

        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");
        });
    }
}

     




your program.cs should look like this...

    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .UseUrls("http://*:5005")
            .Build();



your chat hub should look like this...

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.SignalR;

namespace IoTDemo2.Web1.Hubs
{
public class ChatHub : Hub
{
public async Task Send(string name, string message)

    {

        // Call the broadcastMessage method to update clients.

        for (int i = 0; i < 20; i++)

        {

            //observer.OnNext($"sending...{i}");
            await Clients.All.InvokeAsync("broadcastMessage", name, message);

            await Task.Delay(1000);

        }


    }


    public override Task OnConnectedAsync()
    {
        Clients.All.InvokeAsync("broadcastMessage", "system", $"{Context.ConnectionId} joined the conversation");
        return base.OnConnectedAsync();
    }

    public override Task OnDisconnectedAsync(System.Exception exception)
    {
        Clients.All.InvokeAsync("broadcastMessage", "system", $"{Context.ConnectionId} left the conversation");
        return base.OnDisconnectedAsync(exception);
    }
}
}


your csproj file should look similar to this..

netcoreapp2.0
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" />
<PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="1.0.0-alpha2-final" />

     

open 2 browsers to http://192.168.1.10:5005/ and test ( whatever your local lan ip is )


use chrome browser is the best cause it has the dev tools you can watch for any signalr errors with ctrl-shift-i


when you run your project its going to host the kestrel webserver at http://192.168.1.10:5005/ or whatever the ip address was given to your computer by DHCP you can find this address by typing ipconfig at the cmd prompt mine is http://192.168.1.10:5005/


put that into the web browser and it will hit your signalr hub. open up another browser and the real test is wether browser 1 receives data from browser 2

**Comment by ColbyBurke** [comment]
ive tried my ip it doesnt work

**Comment by ColbyBurke** [comment]
what is supposed to come up when you IIS express?

**Comment by ColbyBurke** [comment]
192.168.0.8 is all im  getting

**Comment by ColbyBurke** [comment]
@acjh I tried your method but what packages do i need? nothing looks valuable

**Comment by acjh** [comment]
`Microsoft.AspNetCore.SignalR`

**Comment by ColbyBurke** [comment]
fuck thanks so much @acjh ... but do you know what I need for "Clients"?

**Comment by acjh** [comment]
It's a property in Hub:
https://github.com/aspnet/SignalR/blob/75e102f97aa9ea999d5890d8067c12e981bbd864/src/Microsoft.AspNetCore.SignalR.Core/Hub.cs#L16

**Comment by ColbyBurke** [comment]
nevermind i got it. thanks anyways. thanks a ton
