### ISSUE TITLE
Does Chatsample work with core 2.0?

### ISSUE THREAD

**Issue by mortenbirkelund** [aspnet/SignalR#1236]
I have tried to implement the example in order to get the presence part working in my core 2.0 project. But after implementation I get an error in PresenceHubLifetimeManager.cs on line 114

`hub.Clients = new HubCallerClients(_hubContext.Clients, connection.ConnectionId);`

> The type or namespace name 'HubCallerClients' could not be found (are you missing a using directive or an assembly reference?)

Will the sample only work in asp.net core 2.1 where signalr core is also released?

Thanks in advance for your help.

**Comment by mikaelm12** [comment]
Are you using alpha 2 packages? HubCallerClients was added very recently so you'd need to be using the our most recent stuff. We are planning to release a preview1 soon which will have these changes and more.

You can go to the `rel/1.0.0-alpha2` branch to see how the ChatSample worked before if you're interested.

**Comment by anurse** [comment]
If you want to try out the latest code in `dev` you can use the MyGet nightly feed, but beware that these bits have not received any verification aside from automated tests and can often have major bugs. See https://github.com/aspnet/Home#builds for some information on how to do that.

**Comment by mortenbirkelund** [comment]
@mikaelm12  I was by mistake using the `dev`. I will try with the correct branch, `rel/1.0.0-alpha2`. Thanks

 @anurse Thanks, but it was by a mistake i used dev. I will try again with the correct branch. `

**Comment by mortenbirkelund** [comment]
I works fine when using the correct branch. Silly me. 
However, whenever the function `UsersLeft` or `UsersJoined` are invoked, I get an error in firebug, stating that `TypeError: users.forEach is not a function`. 
However, when `SetUsersOnline` is invoked, it works fine, without any error, even though it also uses forEach to iterate. I cant seem to find any difference in the `users` object and the `usersOnline` object. 

`    // User online/offline
    connection.on('SetUsersOnline', usersOnline => {
        usersOnline.forEach(user => addUserOnline(user));
        
    });

    connection.on('UsersJoined', users => {
        users.forEach(user => {
            appendLine(user.name + " ankom til chatten");
            
            if (user.userId != myId) { addUserOnline(user) }
        });
    });


    connection.on('UsersLeft', users => {
        users.forEach(user => {           
            appendLine(user.name + " forlod chatten");
            removeUserOnline(user);
        });
    });`

**Comment by mortenbirkelund** [comment]
@mikaelm12 @anurse ?

**Comment by acjh** [comment]
What does `console.log(users)` give?

**Comment by mortenbirkelund** [comment]
The `SetUsersOnline` runs perfectly fine, but on the `UsersJoined` i get an error as you can see. 
```
usersOnline = [object Object]
users = [object Object]
TypeError: users.forEach is not a function
```

**Comment by acjh** [comment]
What does `console.dir(users)` give?

**Comment by mortenbirkelund** [comment]
Gives me the same

**Comment by mortenbirkelund** [comment]
But the error message is more elaborated in chrome than in firefox

```
Uncaught TypeError: users.forEach is not a function
    at HubConnection.connection.on.users (Live:331)
    at methods.forEach.m (signalr-client-1.0.0-alpha2-final.js:414)
    at Array.forEach (<anonymous>)
    at HubConnection.invokeClientMethod (signalr-client-1.0.0-alpha2-final.js:414)
    at HubConnection.processIncomingData (signalr-client-1.0.0-alpha2-final.js:393)
    at WebSocketTransport.HubConnection.connection.onreceive (signalr-client-1.0.0-alpha2-final.js:379)
    at WebSocket.webSocket.onmessage (signalr-client-1.0.0-alpha2-final.js:711)
connection.on.users @ Live:331
methods.forEach.m @ signalr-client-1.0.0-alpha2-final.js:414
invokeClientMethod @ signalr-client-1.0.0-alpha2-final.js:414
processIncomingData @ signalr-client-1.0.0-alpha2-final.js:393
HubConnection.connection.onreceive @ signalr-client-1.0.0-alpha2-final.js:379
webSocket.onmessage @ signalr-client-1.0.0-alpha2-final.js:711
```

**Comment by mortenbirkelund** [comment]
I think i have fixed it. The problem was that on the server, the `await GetUsersOnline()` returned the users as en IEnumerable, and this was passed to the client function `SetUsersOnline`.. 
But when the hub passes the users to `UsersJoined` and `UsersLeft` they are passed on as array's. 

If i changed to methods in the hub, so that they users was past within a list, then the error goes away. 

```
        public override Task OnUsersJoined(UserDetails[] users)
        {
            var lst = new List<UserDetails>();
            lst.AddRange(users);

            return Clients.Client(Context.ConnectionId).InvokeAsync("UsersJoined", lst);
        }

        public override Task OnUsersLeft(UserDetails[] users)
        {
            var lst = new List<UserDetails>();
            lst.AddRange(users);
            return Clients.Client(Context.ConnectionId).InvokeAsync("UsersLeft", lst);
        }
```
Am I the only one who are experiencing this issue?

**Comment by BrennanConroy** [comment]
The ChatSample needs to be fixed, making a PR shortly

**Comment by BrennanConroy** [comment]
Updated the sample https://github.com/aspnet/SignalR/commit/0eca36ed2679713aae67b32a1b5c22b56b5c8ef3
