### ISSUE TITLE
holenens app requires Signalr Core Client but Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final is not compatible with uap10.0.14393 

### ISSUE THREAD

**Issue by fogbridgegit** [aspnet/SignalR#1237]
I need to use Signalr Core from the Hololens.  This is a hard requirement since i need to run Signalr Core on the server side from Linux.

In order to add Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final nuget i need to target universal 16299 Fall Creators Update in the project settings.

 I can build my solution and begin a deployment during the deployment process the  hololens says i need to target uap10.0.14393.

When i get back to my solution and downgrade the universal target to 14393 on both my projects i get the following error

NU1202: Package Microsoft.AspNetCore.SignalR.Client 1.0.0-alpha2-final is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393).

**Comment by anurse** [comment]
SignalR Core requires the Windows 10 Fall Creators Update because only the Fall Creators Update supports .NET Standard 2.0. We don't support versions of the .NET Standard below 2.0. I don't know when or if the Hololens plans to update to the latest version of Windows, but until then, SignalR cannot be compatible with it, as the underlying runtime simply doesn't support it.

**Comment by fogbridgegit** [comment]
well im finally able to build and deploy  to the hololens with signalr core 2.0 client  and it starts to run but then
https://drive.google.com/open?id=1Tbd92o_gyqnVgyR445qpcf9YYeG2KKwC

throws System.TypeLoadException: 'Could not load type 'System.Collections.Concurrent.ConcurrentDictionary`2' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.'

couldnt i put an IF DEF around this code and target multiple frameworks from my project.json?

**Comment by anurse** [comment]
This is exactly what I was saying in the other issue. Even if you work around the compilation errors, there are features missing from the runtime on older UWP platforms (like Hololens currently) that SignalR requires.

**Comment by fogbridgegit** [comment]
you were right ( bowing down ).  I have problems from childhood with wild goose chases.
that being said couldnt i do an HTTP call to download .netstandard 2.0 before i run that line of code ? :) :)
or download .net core 2.0 or something crazy like that.
ok dont answer that.. that was just rhetorical.
