### ISSUE TITLE
Need Xamarin Client

### ISSUE THREAD

**Issue by MhAllan** [aspnet/SignalR#1238]
I am having errors (Android crashes) when adding Microsoft.AspNetCore.SignalR.Client reference.
The error is : "Could not load assembly 'System.Memory' during startup registration"

I don't know if monodroid needs to update or your client should be Standard than Core?

**Comment by VladimirAkopyan** [comment]
Can;t seem to find source for that package on gitub. Am I being dumb? Can someone point me to it?

**Comment by MhAllan** [comment]
@VladimirAkopyan  it is still preview, tick the preview, check the "Include Prerelease" checkbox of your VS NuGet manager

**Comment by VladimirAkopyan** [comment]
I meant that I could not find the source code of this package on github - I want to take a look at the source. Is it in a folder in this repo?

**Comment by nikolayDemirev** [comment]
I have the same issue with SignalR on Xamarin.Android:

> 12-27 19:16:50.510 D/Mono    (10799): Assembly Loader probing location: 'System.Memory'.
12-27 19:16:50.510 F/monodroid-assembly(10799): Could not load assembly 'System.Memory' during startup registration.
12-27 19:16:50.510 F/monodroid-assembly(10799): This might be due to an invalid debug installation.
12-27 19:16:50.510 F/monodroid-assembly(10799): A common cause is to 'adb install' the app directly instead of doing from the IDE.

It runs on Xamarin.iOS and Xamarin.UWP, but Xamarin.Android gives that error and the app crashes just after showing the SplashScreen.

**Comment by VishalMadhvani** [comment]
https://github.com/dotnet/corefx/tree/master/src/System.Memory

**Comment by nikolayDemirev** [comment]
I was able to fix the error related to System.Memory, by installing manually System.Memory 4.4.0-preview2-25405-01 nuget from a local source, because I could not find it in nuget.org source. After that I got a new error:
>12-28 12:44:39.016 F/monodroid-assembly( 6004): Could not load assembly 'System.Runtime.CompilerServices.Unsafe' during startup registration.
12-28 12:44:39.016 F/monodroid-assembly( 6004): This might be due to an invalid debug installation.
12-28 12:44:39.016 F/monodroid-assembly( 6004): A common cause is to 'adb install' the app directly instead of doing from the IDE.

I have tried to install that nuget from a local source the same way as System.Memory but that did not help.

**Comment by nikolayDemirev** [comment]
> I was able to fix the error related to System.Memory, by installing manually System.Memory 4.4.0-preview2-25405-01 nuget from a local source, because I could not find it in nuget.org source. I have the "Include prerelease" option enabled. After that I got a new error:
> 
> 12-28 12:44:39.016 F/monodroid-assembly( 6004): Could not load assembly 'System.Runtime.CompilerServices.Unsafe' during startup registration.
> 12-28 12:44:39.016 F/monodroid-assembly( 6004): This might be due to an invalid debug installation.
> 12-28 12:44:39.016 F/monodroid-assembly( 6004): A common cause is to 'adb install' the app directly instead of doing from the IDE.
> 
> I have tried to install that nuget from a local source the same way as System.Memory but that did not help.

I was able to fix this by manually copying the System.Runtime.CompilerServices.Unsafe.dll from the nuget package to obj\Debug\android\assets folder. But this is not very good.

Can anyone help how to make it work without hacks?

**Comment by MhAllan** [comment]
@nikolayDemirev  Thanks, copying the "System.Memory" and "System.Runtime.CompilerServices.Unsafe" to" \obj\Debug\android\assets" worked

any help?

**Comment by anurse** [comment]
What version of SignalR are you using? The current version of SignalR may depend on some pre-release bits of the .NET MyGet feeds, so you may need to add those as NuGet sources to get the right packages.

**Comment by MhAllan** [comment]
@anurse I am using Microsoft.AspNetCore.SignalR version 1.0.0-alpha2-final

**Comment by Piteryo** [comment]
@MhAllan So what exactly we should copy? Dll or what? If Dll where do i get it?

**Comment by MhAllan** [comment]
@Piteryo You can get them by Nuget having "Include prerelease" checkbox checked. then you will find them in folder C:\Users\[Your User]\.nuget

Or these I attached

[Signalr-Xam-Droid.zip](https://github.com/aspnet/SignalR/files/1609729/Signalr-Xam-Droid.zip)

**Comment by mikaelm12** [comment]
Is anyone still seeing this issue with 1.0.0-alpha2-final version of `Microsoft.AspNetCore.SignalR.Client` ? I was able to install and use it in a Xamarin Android project without any issues.

**Comment by W2K** [comment]
Yes I have exactly the same issue. This is a blocker for my project right now.

**Comment by mikaelm12** [comment]
@W2K  Are you using 1.0.0-alpha2-final version of the client? What version of the runtime are you using?

**Comment by MhAllan** [comment]
@mikaelm12 , yes the issue is in 1.0.0-alpha2-final .. could you upload your android solution so I can see the difference. for me if I don't manually include "System.Memory" and "System.Runtime.CompilerServices.Unsafe" in " \obj\Debug\android\assets" it doesn't work. I came back to it today updated whatever needs to update today and tried again, same issue without that manually copy of dlls

**Comment by davidfowl** [comment]
@MhAllan are you using the latest Xamarin Android version?

**Comment by mikaelm12** [comment]
https://github.com/aspnet/SignalR-samples/tree/master/XamarinAndroidChatClient

**Comment by MhAllan** [comment]
Hi @mikaelm12 , Thanks for the example. The problem is in Xamarin Forms Android, the difference is that your project is using packages.config while Xamarin form is using packagereference. I don't know why this packagereference is skipping dependencies. You just start a xamarin forms solution, add the signalr client to the android and that android won't be able to load the dependencies i mentioned

**Comment by davidfowl** [comment]
@MhAllan What version of Xamarin Android are you using?

**Comment by MhAllan** [comment]
@davidfowl , it is Android 8.0, but those Mono.Android dlls are all versioned 0.

![image](https://user-images.githubusercontent.com/13087546/35762107-90b83284-08e5-11e8-9098-67c848ba6921.png)

**Comment by MhAllan** [comment]
Here is the solution, connect to android and launch it, it will crash. I am connecting to Android 6 Samsung device

[SignalrTest.zip](https://github.com/aspnet/SignalR/files/1691339/SignalrTest.zip)

**Comment by nikolayDemirev** [comment]
Hi, do we still have to copy the binaries manually in order to make it work?

**Comment by MhAllan** [comment]
@nikolayDemirev I believe we still have to do so until these binaries are out with .net core 2.1 and get included in mono

**Comment by Hazzamanic** [comment]
Any news on when we might see support for signalr in android forms projects?

**Comment by davidfowl** [comment]
Closing see https://github.com/aspnet/SignalR/issues/1886
