### ISSUE TITLE
Client 1.0.0 Alpha2 Supported Browsers

### ISSUE THREAD

**Issue by mattchidley** [aspnet/SignalR#1241]
We are currently trying to build an app that uses SignalR on aspnet core. In a perfect world, our app would work all the way back to IE7. We have the app working on IE9 and above with the ES5 client.

Is the current 1.0.0 alpha2 client supposed to be able to run on IE8 or IE7? I have been having issues getting it to run on these versions.

On the aspnet signalr docs in the Supported Platforms article, it states that SignalR will work using the Long Polling transport on IE 8+.

We are curious if any other developers have been trying to come up with a solution for this problem. We have tried ES5 shim with no success. We would like to avoid writing any custom client code if possible.

Which browsers & versions should the provided 1.0.0 Alpha2 client support?

**Comment by anurse** [comment]
SignalR for ASP.NET Core will require IE 9 or higher, as it requires ECMAScript 5 support and a number of other browser APIs that are not present on older versions of IE.
