### ISSUE TITLE
Unable to use SignalR with the latest SDK

### ISSUE THREAD

**Issue by ssougnez** [aspnet/SignalR#1248]
Hello,

a while ago, I posted https://github.com/aspnet/SignalR/issues/690 and davidfowl explained me how to get SignalR Core running. Since then, from time to time, I used to update the version of SignalR client & server and .NET runtime. I was doing so by using "ci-dev" feed and it used to work pretty well.

Few weeks, the "ci-dev" feed started to ask me credentials (I don't know why), so I switched to "dev" feed and then, issues have started... 

I created an issue in the cli repo (https://github.com/dotnet/cli/issues/8280) and after a short discussion, they adviced me to create an issue here.

Basically, the issue is that the latest bits don't allow me to run an aspnet core 2.1 web app on my machine because of a new feature they are implementing. However, I need aspnet core 2.1 for SignalR to work as it does not on aspnet-core 2.0. 

Therefore, I was hoping that someone could point out the correct version to use to be able to use SignalR in my aspnet core web app.

My ".csproj" references theses versions:

```
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-preview1-27884" />
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="2.1.0-preview1-27884" />
```

While my "packages.json" references this one:

`"@aspnet/signalr-client": "^1.0.0-preview1-27884",`

I think the issue is also in the version of the SDK/runtime I have on my machine, and I have no idea which one I have to use to make it work.

Maybe it would be interesting to put all of this in the readme of this project because all this versionning stuff are really complex to deal with and it would be easier for people if they had note about this.

Thanks

**Comment by anurse** [comment]
What error are you getting? Or are you just wondering how to get the latest version of the JavaScript client? We have some documentation on how to run nightly builds of the JavaScript client on the README: https://github.com/aspnet/SignalR#packages

**Comment by MHamburg** [comment]
@anurse,

I am running in to a similar issue, which is not signalr related but more related to kestrel (I think?), it is blocking me from checking out SignalR and testing some implementations (if you could point me in the right direction that would be great!):

using branch: dev

My environment:
dotnet --version 
2.2.0-preview1-007860

dotnet --info
  Version  : 2.1.0-preview1-26103-03
  Build    : 1d51767c35cb879c2388adf3d76722c6ad658c72

Error message on running ChatSample:

Microsoft.AspNetCore.Server.Kestrel:Warning: Connection processing ended abnormally.

System.MethodAccessException: Attempt by method 'System.IO.Pipelines.WritableBufferWriter.Write(Byte[])' to access method 'System.Span`1<System.Byte>.DangerousGetPinnableReference()' failed.
   at System.IO.Pipelines.WritableBufferWriter.Write(Byte[] source)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.WriteResponseHeaders(Int32 statusCode, String reasonPhrase, HttpResponseHeaders responseHeaders)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CreateResponseHeader(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProduceEndAwaited>d__209.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__185`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__185`1.MoveNext()
Microsoft.AspNetCore.Server.Kestrel:Warning: Connection shutdown abnormally.

**Comment by anurse** [comment]
Hmm, I've seen this reported elsewhere. I wonder if it's an issue of an incompatible runtime. The Pipelines code is somewhat sensitive to the .NET Core runtime version (i.e. during the previews, the versions have to line up well). @pakrym have you seen this at all before?

**Comment by pakrym** [comment]
Yes, there are breaking changes in the latest runtime that we are currently in the process of reacting to. 

@MHamburg  this should be fixed in a day or two, you can track https://github.com/aspnet/SignalR/pull/1250

**Comment by BrennanConroy** [comment]
Closing since this should have been fixed a couple weeks ago, reopen if you're still having the same issue
