### ISSUE TITLE
HubName or option for DI routes

### ISSUE THREAD

**Issue by LORDofDOOM** [aspnet/SignalR#1252]
I'm sorry if this "problem" is already solved and I did not recognize. 

I've waited for the resolve of this issue: #625 

But it seems that HubName attribute will not come back. I use old SignalR-Server with HubName attribute in optional modules and load them at runtime - All signalr routes from modules are correctly set without any manual injection. 

@anurse wrote that the HubName attribute is no longer relevant but IMHO there are many cases where this attribute makes sense... The best option would be if HubName is auto discovered like the route attribute for MVC. 

If anything like this planed or is there any other useful option for auto discovery/setup routes ?

**Comment by anurse** [comment]
There are no plans for auto-discovery and routing of Hubs. We're generally very cautious with enabling functionality like that in the main product (even behind a feature flag or extension method) because once it's in, it needs to be fully supported for the life of the product. Auto-discovery in particular is a tricky situation with lots of edge cases, so we have no plans to do it in the next version. It may be something we can look at in the future. Attribute routing took a few versions to come to MVC and that wasn't because it was a hard technical problem to solve ;).

In the meantime, it would certainly be possible to do it in a separate library and might be something the community could find useful!

**Comment by LORDofDOOM** [comment]
Thank you for your answer. 

Do you see other option to create a route in MVC ? 

I've try to connect SignalR JS client to a MVC route, in this route I return Signalr Hub and check if it's a WebSocket connection... The JS client will connect and is able to send data but I try to "upgrade" the websocket connection to a real signalr connection. 

Do you see any way to do this in a proper way ?

Here is my code (simply add to HomeController.cs in Chat Sample and drop app.UseSignalR in startup.cs)

`    [Route("default")]
    public class MvcChatHubTest : Controller
    {
        private readonly IHubContext<Chat> _IHubContext;

        public MvcChatHubTest(IHubContext<Chat> hubContext)
        {
            _IHubContext = hubContext;
        }

        [HttpGet]
        public async Task<IHubContext<Chat>> Get(string funcName, string data)
        {
            if (HttpContext.WebSockets.IsWebSocketRequest)
            {
                WebSocket socket = HttpContext.WebSockets.AcceptWebSocketAsync().Result;

                if (socket != null && socket.State == WebSocketState.Open)
                {
                    while (!HttpContext.RequestAborted.IsCancellationRequested)
                    {
                        var buffer = new byte[2048];

                        while (true)
                        {
                            var result = await socket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);

                            if (result.MessageType == WebSocketMessageType.Text)
                            {
                                string signalrMsg = Encoding.UTF8.GetString(buffer, 0, result.Count);
                                Console.WriteLine(signalrMsg);
                            }
                            else if (result.MessageType == WebSocketMessageType.Binary)
                            {
                            }
                            else if (result.MessageType == WebSocketMessageType.Close)
                            {
                                await socket.CloseOutputAsync(WebSocketCloseStatus.NormalClosure, "", CancellationToken.None);
                                break;
                            }
                        }
                        Thread.Sleep(3000);
                    }
                }
            }
            return _IHubContext;
        }
    }`

I hope I could explain what I'm trying to do :)

Thank you very much

**Comment by anurse** [comment]
Couldn't you just do this by mapping the Hub to the URL you're looking for? Why do you need the MVC controller? When you map the hub in the `Startup` class (in the call to `.UseSignalR`) you can specify the URL for the Hub.

**Comment by LORDofDOOM** [comment]
Thank you for your answer, unfortunately I can't use the Startup Class because I use plugins for my program - These plugins are fully optional and at compile time the system dont about them. 

MVC routes are discovered at runtime and I think this could be also a option for signalr.

Do you see any option to inject signalr or upgrade existing HttpGet to a signalr connection ? As you see in my sample this works with websockets but these are no real signalr connections...

**Comment by anurse** [comment]
You could scan the plugin assemblies for Hub classes yourself and register them in your Startup class (and use your own attribute to specify the route).

We are thinking about adding some Hub discovery logic after Preview 1, so we'll look at this scenario as part of doing that.

**Comment by LORDofDOOM** [comment]
Great to hear that discovery logic is in discussion :)

I try with this code:

```
        public static HubRouteBuilder MapSignalrRoutes(this HubRouteBuilder hubRouteBuilder)
        {
            IEnumerable<Assembly> assembliesPlugins = Directory.EnumerateFiles(AppDomain.CurrentDomain.BaseDirectory, "Plugin*.dll", SearchOption.TopDirectoryOnly)
                .Select(Assembly.LoadFrom);

            foreach (var assembly in assembliesPlugins)
            {
                //Get SignalR Hubs
                IEnumerable<Hub> pluginHubs = assembly.GetTypes()
                    .Where(t => t.IsSubclassOf(typeof(Hub)) && !t.IsAbstract)
                    .Select(t => (Hub)Activator.CreateInstance(t));

                foreach (var pluginHub in pluginHubs)
                {
                    Console.WriteLine("Assembly Name: " + assembly.GetName());
                    Console.WriteLine("HubName: " + pluginHub.GetType());
                    // Testing to get new Hub
                    Hub currentHub = (Hub)Convert.ChangeType(pluginHub.GetType(), typeof(Hub));
                    // This fails because currentHub is a variable
                    hubRouteBuilder.MapHub<currentHub> ("/" + assembly.GetName());
                }
            }
            return hubRouteBuilder;
        }
```

and init the route in startup:

```
app.UseSignalR(r => r.MapSignalrRoutes()); 
```

Can't get this working because currentHub is a variable... Can you please give me some advice how to use the type (Chat) ?

**Comment by anurse** [comment]
You can make it work via reflection using [`MakeGenericMethod`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo.makegenericmethod?view=netframework-4.7.1#System_Reflection_MethodInfo_MakeGenericMethod_System_Type___). I'm not able to provide a specific example right now, but I can add some details later if you get stuck.

We might be able to do something in Preview 1 to make this easier by allowing `MapHub` to be called with a `System.Type` instance instead of only using generics.

**Comment by LORDofDOOM** [comment]
Thank you for your fast answer. I try to reflect and create the hub with MakeGenericMethod but I still get same compiler error ("currentHub" is a variable).

I think I'm doing this wrong ;)

If you find a little time please provide a sample to do this in a correct way.

**Comment by anurse** [comment]
When using reflection you shouldn't be getting any compiler errors, there are no compile-time generics involved. It would be something like this:

```csharp
    public static class ConfigurationExtensions
    {
        // The MethodInfo for MapHub, this can be stored statically because it's just a pointer to the function.
        private static readonly MethodInfo _mapHubMethod = typeof(HubRouteBuilder).GetMethod("MapHub", new [] { typeof(string) });

        public static HubRouteBuilder MapSignalrRoutes(this HubRouteBuilder hubRouteBuilder)
        {
            IEnumerable<Assembly> assembliesPlugins = Directory.EnumerateFiles(AppDomain.CurrentDomain.BaseDirectory, "Plugin*.dll", SearchOption.TopDirectoryOnly)
                .Select(Assembly.LoadFrom);

            foreach (var assembly in assembliesPlugins)
            {
                //Get SignalR Hubs
                IEnumerable<Type> pluginHubTypes = assembly.GetTypes()
                    .Where(t => t.IsSubclassOf(typeof(Hub)) && !t.IsAbstract)

                foreach (var pluginHubType in pluginHubTypes)
                {
                    Console.WriteLine("Assembly Name: " + assembly.GetName());
                    Console.WriteLine("HubName: " + pluginHubType.GetType());
                    
                    // Create a generic version of MapHub using the plugin type, then invoke it using hubRouteBuilder as this and the assembly name as the parameter.
                    _mapHubMethod.MakeGenericMethod(pluginHubType).Invoke(hubRouteBuilder, "/" + assembly.GetName())
                }
            }
            return hubRouteBuilder;
        }
    }
```

**Comment by LORDofDOOM** [comment]
Now I see whats wrong in my code :)

Works really great - Thank you very much for for time and help
