### ISSUE TITLE
[HUB - ERROR] AES 256 bits rinjdael crypto security with binnary formatter fails on authorization attribute override - Class level

### ISSUE THREAD

**Issue by Ryujose** [aspnet/SignalR#1253]
Hello community.

I'm having an issue when I protect hub methods on class level with "AuthorizeAttribute" with an override of the methods.

I'm using AES 256 bits with rinjdael and binnary formatter to make data secure on connection token and other data that's travel from client to server. The first time that's doing the decryption there isn't any problem, but when it's going to decrypt the second time and more times after it, the error of "Padding is invalid and cannot be removed" starts to showing up without stopping.

I've done unit tests passing with several tests of this behaviour to see if it fails but it doesn't.

I'm attaching the log file that's logging the errors at Application_Error of global.asax under "AppDomain.CurrentDomain.FirstChanceException" and "AppDomain.CurrentDomain.UnhandledException".

[SignalRLog.txt](https://github.com/aspnet/SignalR/files/1589020/SignalRLog.txt)

Regards,

Jose Luis Guerra Infante.

**Comment by Ryujose** [comment]
I'm a bit confusing here. For what I see, this is the repository that's active, but it's related for asp.net core it seems. I've the same issue here "https://github.com/SignalR/SignalR" but it isn't have so much commits. That's mean that signalR for .NET framework versión is discontinued? This issue is for ASP.NET and not for ASP.NET Core.

Sorry for the confusion.

**Comment by davidfowl** [comment]
It's not discontinued but this is the new version of SignalR based on ASP.NET Core. The existing version won't see any major feature work but will continue to get bug fixes. This issue looks like it should be reported to the other repository.

**Comment by Ryujose** [comment]
Thanks for the information. The issue is already open on the other repository under URL https://github.com/SignalR/SignalR/issues/4057

**Comment by Ryujose** [comment]
I'll close the issue as this is not the right place for it.
