### ISSUE TITLE
Signalr SyntaxError in Google Chrome

### ISSUE THREAD

**Issue by Nickname863** [aspnet/SignalR#1255]
It could just be me using the js Client wrong. But when i am adding the client to HTML like this:

![image](https://user-images.githubusercontent.com/33596703/34428641-5b77a044-ec4f-11e7-86da-13025b89963a.png)

I get 

![image](https://user-images.githubusercontent.com/33596703/34428672-a312eaee-ec4f-11e7-9483-b1525caca6d1.png)

However when i load the Site in Firefox i don't get this Error and the client seems to work just fine.

**Comment by acjh** [comment]
Line 194:
```js
constructor(url, options = {}) {
```

- [Default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility) are supported in Chrome 49+.
- If you want to support ES5, use *signalr-client**ES5**-1.0.0-alpha2-final.js*.

**Comment by Nickname863** [comment]
Yes that worked.
Thank you very much.
