### ISSUE TITLE
On rejoin group, first message not broadcasting

### ISSUE THREAD

**Issue by kgrvr** [aspnet/SignalR#1259]
### Title
On rejoin group, first message not getting broadcasted

### Functional impact
*If I join again any group after leaving it, the first message which I send does not broadcast to any joined connection. All other messages after that message gets broadcasted easily. Sometimes even second or third message is also lost.*  

### Minimal repro steps
1. Join a group and send a message
2. Leave a group and join it again
3. Sends a message again

### Expected result
*It should broadcast the message to every connected connection.*

### Actual result
*Message is getting lost*

### Further technical details
I've invoked hub's method from client (Typescript) as :

    this._hubConnection.invoke('SendMessage', { 
	    message: 'Hello, World!',
	    groupId: '{{ Some-GUID }}'
    });

In my message hub:

    public async Task SendMessage(Message message) {
            try {
	            //...
                // Send message to all users in group
                await Clients.Group(message.GroupId).InvokeAsync("ReceiveMessage", message);

                // ...
            }
            catch (Exception ex) {
                throw ex;
            }
    }

And on my client:

    this._hubConnection.on('ReceiveMessage', (data: any) => {
            console.log(data);
    });

The problem is no error is thrown, but the message gets lost somewhere. Am I doing anything wrong?

I'm using `Microsoft.AspNetCore.SignalR Version=1.0.0-alpha2-final` and in client `@aspnet/signalr-client Version=1.0.0-alpha2-final`

**Comment by anurse** [comment]
I'm not able to repro this using our SocketsSample in the repo. Are you able to provide a repro project somewhere?

Some clarifying questions:

> It should broadcast the message to every connected connection.

You mean to every connection in the group right? That's the behavior I'm seeing in my attempt to repro this issue, just want to make sure we're understanding things the same way :).



> The problem is no error is thrown, but the message gets lost somewhere. Am I doing anything wrong?

Is anything interesting being logged to the Console? If not, can you set your logging level to Trace and collect the logs from that? In the default templates, this can be done by setting the `Logging:LogLevel:Microsoft` setting to `Trace`. Like so:

```js
{
  ...
  "Logging": {
    ...
    "LogLevel": {
      ...
      "Microsoft": "Trace"
    }
  }
}
```

**Comment by kgrvr** [comment]
I'm not following any templates..
Which default templates are you taking about?

**Comment by anurse** [comment]
I'm just referring to the default ASP.NET Core template, to describe how to configure logging. SignalR provides fairly detailed logging, but it has to be manually enabled by configuring the ASP.NET Core Logging system appropriately.

Are you able to provide a project that reproduces the issue? I'm not able to reproduce it, which makes it difficult to diagnose any issue.
