### ISSUE TITLE
Figure out buffer pooling when writing and reading to channels

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#126]
Right now we're allocating a new memory stream per write/read and that's very inefficient. We need a way to flow pooled buffers from producer to consumer and have them be disposed at the right time. Right now, the `Message` object stores a preserved buffer and is disposable but I'm not sure that's the right thing to do.

**Comment by muratg** [comment]
@davidfowl FYI keeping this in 1.0.0 (as opposed to 1.0.0-preview1)

**Comment by anurse** [comment]
Making some notes about related things in here:

* We need a strategy for using pooled memory for Hub message decoding/encoding. See IHubProtocol for example.

**Comment by davidfowl** [comment]
This might disappear when we use pipelines
