### ISSUE TITLE
Get SignalR into the Metapackage

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1267]
We need SignalR to be in the Microsoft.AspNetCore.All metapackage.

**Comment by muratg** [comment]
cc @JunTaoLuo @natemcmaster FYI

**Comment by anurse** [comment]
A prereq for this is splitting MsgPack into a separate assembly. Filing a bug for that. I think I can get that done this week.

**Comment by natemcmaster** [comment]
Besides MsgPack and NodeJS, are there any other 3rd party tools or dependencies? i.e. newtonsoft.json? any testing tools?

**Comment by anurse** [comment]
In the .NET side, Newtonsoft.Json is the only other 3rd-party dependency. For the NPM package there are some additional dependencies, but I don't think that's relevant to our source build

**Comment by natemcmaster** [comment]
Ok. This should be fine.

**Comment by davidfowl** [comment]
Dupe of https://github.com/aspnet/MetaPackages/issues/235
