### ISSUE TITLE
Consider better ways to send array in InvokeAsync

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#1268]
A very easy mistake to make is passing an array to `InvokeAsync` which will treat the array as a list of arguments instead of a single argument that is an array.

```
public async Task Send(byte[] data)
{
    await Clients.All.InvokeAsync("Send", data); // wrong
    await Clients.All.InvokeAsync("Send", new [] { data }); // correct
}
```

We should consider ways of either making this more obvious or changing APIs to prevent this issue.

**Comment by anurse** [comment]
Unfortunately, the only thing I can think of right now is to rename the one that takes the array to something obnoxious like `SendInvocationAsync` or something. We can't justify making it `internal` because it's a useful API.

**Comment by davidfowl** [comment]
On the client we did this with overloads.

**Comment by anurse** [comment]
The client was protected by the fact that it had an additional parameter in the argument array (the return type). The `SendAsync` helpers on the client have the same issue.

**Comment by anurse** [comment]
Overloads don't help, because an `object[]` binds to the overload that takes an array, not the one that takes `object`

**Comment by davidfowl** [comment]
That's true, I guess the only thing we could do is rename the array overload, hmmmmm.

**Comment by simeyla** [comment]
This is especially confusing (new user from SignalR 2 > 3) because when you hit F12 on `InvokeAsync` it takes you to the list of extension method signatures for `IClientProxy` and you don't even see that a signature with `[]` exists!

**Comment by cvanem** [comment]
I ran into this as well.  Using new [] { data } is acceptable, but won't that cause some performance concerns for large arrays as it is making a copy of the data with the new operator?  I am using this solution instead:

public async Task Send(byte[] data)
{
    await Clients.All.InvokeAsync("Send", data as object); 
}

Renaming the overload that takes the arguments array seems acceptable to me.  I don't think it is necessary, but it would prevent others from encountering this issue.

**Comment by anurse** [comment]
The array is being created no matter what. `params object[]` will always allocate an array. If you are sending a message with a single argument that is a large array though, no copy of the large array occurs. The array that is allocated will contain a **reference** to the large array, not a copy of it (since only `struct`s are copied by value)

**Comment by muratg** [comment]
Current POR: Rename the method which takes in an Array. (No good candidates yet.)

**Comment by BrennanConroy** [comment]
Correct me if I'm wrong, but can't we just remove `params` from our proxies https://github.com/aspnet/SignalR/blob/9786e28f52a870aa2ecd15d092d393c9de150442/src/Microsoft.AspNetCore.SignalR.Core/Proxies.cs#L20
and rely on the extension methods we have for multiple arguments?
https://github.com/aspnet/SignalR/blob/9786e28f52a870aa2ecd15d092d393c9de150442/src/Microsoft.AspNetCore.SignalR.Core/IClientProxyExtensions.cs#L192

And then 
```
public async Task Send(byte[] data)
{
    await Clients.All.SendAsync("send", data);
}
```
should just work

**Comment by jsakamoto** [comment]
I think, `byte[]` is never projected `(object[] args)`,  with or without `params`, because byte is value type.

Therefore, your sample code just work.

If you use array of reference type such as `string[]`, you will run into unexpected behavior, I think.

This is my sample code here: https://gist.github.com/jsakamoto/32b1e95f818a34ec74507039f3fa3cb6

**Comment by jsakamoto** [comment]
I guess, many developers will be satisfied to use `InvokeAsync(object args1, object args2, ..., argsN)` extension method version in almost cases.

So, In my idea, could you change the method name of `IClientProxy.InvokeAsync(string method, object[] args)`, like "Invoke**WithVariableArgs**Async(string method, object[] args)" ?

This method name idea may be no good, anyway, the important point of my idea is changing the method name live on `IClientProxy` side.
