### ISSUE TITLE
Don't use application/x-www-form-urlencoded POST requests for http polling

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#127]
CSRF is a concern here. We should just post raw data to the body.

**Comment by anurse** [comment]
See #125 

How does not using `application/x-www-form-urlencoded` prevent CSRF? We need an anti-forgery token no matter how we encode the data if we want to prevent CSRF.

**Comment by anurse** [comment]
Wait, never mind, this is for the poll request. Just got it ;). Never mind!

**Comment by davidfowl** [comment]
@anurse sends and poll. This is a long standing issue https://github.com/SignalR/SignalR/issues/1886.

**Comment by davidfowl** [comment]
@anurse we can close this right?

**Comment by moozzyk** [comment]
No - https://github.com/aspnet/SignalR/blob/a00ec445ef040395faed0b564f098258b8239e60/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpClient.ts#L21 - I could just remove it but I wanted to understand first how this can be a CSRF and I keep forgetting to ask you.

**Comment by davidfowl** [comment]
Here's the original issue - https://github.com/SignalR/SignalR/issues/1413

https://github.com/SignalR/SignalR/commit/f41abf4a17c91e3f18b5fc8cbdff9c0d3297645a

**Comment by moozzyk** [comment]
Fixed in e691e1c
