### ISSUE TITLE
[Question] Creating Hub instance from IHostedService

### ISSUE THREAD

**Issue by Antaris** [aspnet/SignalR#1272]
Hi Team,

In my application design, I can have multiple instances of an ASP.NET Core application communicating with each other and backend services over RabbitMQ (via EasyNetQ). I have both publisher and consumer `IHostedServices` that send notification messages to perform actions. Once an action is completed, a notification is then broadcast over RabbitMQ, picked up by a consumer declared by an `IHostedService`. 

My front-end is an Angular application that has a SignalR integration with the backend. Is it possible to access a `Hub` instance from an `IHostedService` so I can push notifications received from RabbitMQ down to connected clients?

**Comment by BrennanConroy** [comment]
This? https://github.com/aspnet/SignalR/issues/182
