### ISSUE TITLE
Inject a UserId into the OnConnect function?

### ISSUE THREAD

**Issue by MouthOfMadness** [aspnet/SignalR#1273]
Is there a way to inject a userId into the OnConnect function to associate with the ConnectionId?  I cannot use the Authorize attribute for Identity.

[Authorize] <-- I need to remove this.
public class MyHub : Hub
{

Current:
public override Task OnConnectedAsync()
      {
            var name = Context.User.Identity.Name;

Suggested:
public override Task OnConnectedAsync(string id)
      {
            var name = id;

**Comment by BrennanConroy** [comment]
What's wrong with
```
public override Task OnConnectedAsync()
{
    var name = Context.User.Identity.Name;
}
```
?

**Comment by cristian-eriomenco** [comment]
@MouthOfMadness I think I know what he means.... The `Context.User` is not hydrated unless there is an [Authorize] attribute on top of the hub.

If you remove the attribute then `.User` property would be empty.

Regarding passing it inside the OnConnectAsync IMHO this would be a bad design decision as we already have context for that. Its more the need of programatically make an auth challange and obtain the User data rather than changing the OnConnectedAsync signature.

**Comment by BrennanConroy** [comment]
> If you remove the attribute then .User property would be empty.

That's just not true. We still try to populate the fields, `[Authorize]` is used internally to do authorization checks, you can still have an identity even if you don't authorize it.

**Comment by MouthOfMadness** [comment]
In my case, removing the [Authorize] attribute does yield an empty field.

This statement:

Regarding passing it inside the OnConnectAsync IMHO this would be a bad design decision as we already have context for that. Its more the need of programatically make an auth challange and obtain the User data rather than changing the OnConnectedAsync signature.
This is a great design if you’re using an auth challenge; however, if you’re using a Gateway Offloading Pattern (with a product like NGinX), there’s no clear path to creating a server to callback on webclients by a User Id.  Maybe there’s some resolver dependency technique that can be used, but I haven’t been able to figure it out.

**Comment by MouthOfMadness** [comment]
It's empty when there is no [Authorize] attribute.

**Comment by MouthOfMadness** [comment]
As I get further in my design, I realize that it's possible the User (consultant) could have two or more browsers open and each browser could point to different customer cloud data.  In this use case, I only want to callback on one of the browsers, not both.  Even though the customer has the exact same login credentials, I need to abstract an interface that let's me layer and differentiate the user based upon my applications business logic.

**This technique assumes a single user/browser from the business logic of my application**
public override Task OnConnectedAsync()
{
    var name = Context.User.Identity.Name;
}

**What I really need is something that looks like this:**
public override Task OnConnectedAsync(object obj)
{
    MyBusinessLogic mbl = (MyBusinessLogic) obj;
    mbl.ConnectionId = Context.ConnectionId;
    MyCache[mbl.key] = mbl;

    return base.OnConnectedAsync();
}

**Or this:**
public override Task OnConnectedAsync(string jsonObject)
{
    MyBusinessLogic mbl =  JsonConvert.DeserializeObject<MyBusinessLogic>(jsonObject);
    mbl.ConnectionId = Context.ConnectionId;
    MyCache[mbl.key] = mbl;

    return base.OnConnectedAsync();
}

**Comment by MouthOfMadness** [comment]
Is there anyway to inject business logic into the OnConnectAsync function?  Is it possible for the typescript/javascript to return the ConnectionId through a separate api, this isn't an ideal solution but a working solution is a working solution.

**Comment by BrennanConroy** [comment]
You can inject your `MyBusinessLogic` object into the hubs constructor then assign values in the `OnConnectedAsync` function

**Comment by MouthOfMadness** [comment]
I’ve taken an approach similar to your suggestion, but I still don’t have a mechanism that allows me to inject and replace the Context.User.Identity.Name with my business logic identifiers.

// injection of my business logic
public NotificationHub(NotificationMgr m)
{
mgr = m;
}

private NotificationMgr mgr;

public override Task OnConnectedAsync()
{
// zzz hardcoded value
       RegistrationClient rc = mgr.GetUser(Context.User.Identity.Name ?? "jim", false);
       rc.ConnectionIds.Add(Context.ConnectionId);

       mgr.RegisterUser(rc);

       return base.OnConnectedAsync();
}

Is there a way to replace this class HubCallerContext with DerivedHubCallerContext where the MBL can be populated from an angular/javascript application?

public class DerivedHubCallerContext : HubCallerContext
    {
        public HubCallerContext(HubConnectionContext connection);

        public HubConnectionContext Connection { get; }
        public ClaimsPrincipal User { get; }
        public string ConnectionId { get; }
       public MyBusinessLogic MBL {get;}
    }

**Comment by MouthOfMadness** [comment]
If it helps, the RegistrationClient looks a little like this, it allows me to notify a specific application or browser based on a job that has been processed on some service bus queue.

public class RegistrationClient
    {
        public string TenantId { get; set; }
        public string UserId { get; set; }
        public string ApplicationId { get; set; }
        public string JobRequestId { get; set; }
        public List<string> ConnectionIds { get; set; } = new List<string>();

        #region Job Specifications
        #endregion

        #region SLA
        #endregion

    }

**Comment by MouthOfMadness** [comment]
I've done some exploratory work (without much success), how do pull the ConnectionId out of this javascript class.

var **connection** = new signalR.HubConnection(url, { transport: transport });

**Comment by MouthOfMadness** [comment]
I did eventually figure this out; the simplest way to solve this problem is to provide a socket function to Register (mylogic) with the context's connectionId.  After the java script makes the hub connection, it must call the Register function.
