### ISSUE TITLE
Where is observer.complete() ?

### ISSUE THREAD

**Issue by harveytriana** [aspnet/SignalR#1277]
Hello -

Running the example about Streaming, published in "Announcing SignalR (alpha) for ASP.NET Core 2.0", StockTicker sample (https://github.com/aspnet/SignalR-samples), I suppose there is a bug. When invoking close, an error is generated in the scripts. There is no observer.complete () in signalr-client-1.0.0-alpha2-final or ES5. I publish a image here: http://www.visionary-saas.com/docs/observer-complete-issue.png

When I disable the line (*) the error disappears, but I suppose there must be a correction to the issue. Detail:     
(*)
signalr-client-1.0.0-alpha2-final.js
...
complete() {
        for (let observer of this.observers) {
            //* observer.complete();
        }
    }
…

Regards

**Comment by BrennanConroy** [comment]
Looks like the same issue as https://github.com/aspnet/SignalR/issues/813
Although the StockTickR sample shouldn't be hitting this since it registers a complete function
https://github.com/aspnet/SignalR-samples/blob/master/StockTickR/NodeClient/src/main.ts#L35

**Comment by harveytriana** [comment]
Thanks Brennan. Elegant solution.
