### ISSUE TITLE
check [ConnectClientId] connection status 

### ISSUE THREAD

**Issue by wangboshun** [aspnet/SignalR#1278]
Do you hava a function ,use check  [ConnectClientId]  connect  status ,is connect or disconnect?
And have a funtion ,show all connect infomation ,for example connect status ,group,clientid........?

**Comment by anurse** [comment]
If you want to track information about all the connections, you'll need to do it yourself by capturing the connection object during the `OnConnectedAsync` virtual method and storing it somewhere you can track, then remove it it `OnDisconnectedAsync`. We don't expose any of our internal lists or collections for tracking.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
