### ISSUE TITLE
Consider Adding Graceful Termination of LongPolling Transport

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#1281]
Depending on the timeout for the termination of the LongPolling transport causes a delay in the OnDisconnected method being called. For example I was seeing this in the SocketsSample. When refreshing a client and connecting again you eventually get the disconnect message from your previous session which is odd.

**Comment by davidfowl** [comment]
This will require another request. Original SignalR supports an /abort request.

**Comment by mikaelm12** [comment]
Yeah, @anurse and I discussed  this briefly with @halter73. Will come back to it after preview 1

**Comment by anurse** [comment]
> closing the browser window wouldn't trigger it

To be honest, I'm fine doing the minimal thing here of providing a method to do it. Let the app developer decide when they want to do it :)

**Comment by davidfowl** [comment]
@anurse We can close this now that we have the close message right?

**Comment by anurse** [comment]
No, the server doesn't actually do anything when it receives a Close frame currently. This can track tidying that up though. We should formalize the Close process as well (is a response expected to the Close frame? I'd suggest no, and we keep it simple)

**Comment by anurse** [comment]
So the way to handle this with the close frame is to have the HubConnectionHandler actively shut down the connection when a Close frame is received (treat it like the client disconnecting). Then the poll would be shut down properly. I can get that implemented if that's what we want to do.

**Comment by anurse** [comment]
Ok, that should be fairly straightforward.
