### ISSUE TITLE
Xamarin.Forms Can't run with Microsoft.AspNetCore.SignalR.Client

### ISSUE THREAD

**Issue by atefboujday** [aspnet/SignalR#1283]
Hi,

I created a Xamarin Forms solution (Blank App, .Net Standard for Code sharing Strategy)

ProjectMobile (the UI and VM for the Xamarin Forms)
ProjectMobile.Android (application Android)
ProjectMobile.UWP (application universal Windows Plateform)

After that i added a Class Library (Net Standard 2.0) to my project: ProjectMobile.Hub, 
I install the package "Microsoft.AspNetCore.SignalR.Client" version "1.0.0-alpha2-final" to my ProjectMobile.Hub
ProjectMobile have ProjectMobile.Hub has reference
ProjectMobile .Android have ProjectMobile has reference
ProjectMobile .UWP have ProjectMobile has reference

The Android version crash when i start to run it
I have the following error:

01-10 08:50:32.299 F/monodroid-assembly(16655): Could not load assembly 'System.Memory' during startup registration.
F/monodroid-assembly(16655): This might be due to an invalid debug installation.
F/monodroid-assembly(16655): A common cause is to 'adb install' the app directly instead of doing from the IDE.
referenceTable GDEF length=814 1
referenceTable GSUB length=11364 1
referenceTable GPOS length=47302 1

Can you help please

**Comment by MhAllan** [comment]
Similar to [1238](https://github.com/aspnet/SignalR/issues/1238)

**Comment by davidfowl** [comment]
Closing see https://github.com/aspnet/SignalR/issues/1886
