### ISSUE TITLE
Exception: "Invalid negotiation response received."

### ISSUE THREAD

**Issue by pellea** [aspnet/SignalR#1284]
Hello,

A perfectly working code crashed later with a random exception "Invalid negotiation response received.".

What does that mean? Why sometimes I can connect to the signalR server and sometimes I got this exception?

The code is the same as posted here https://github.com/aspnet/SignalR/issues/1154 (https://github.com/pellea/signalr-debug). The code that worked just fine cannot connect to the SignalR server now.

Thanks.

**Comment by anurse** [comment]
Can you provide some additional information about your situation? Are you running behind IIS or self-hosted? Are there any server logs/console messages indicating an error? What does the HTTP traffic between the client and server look like (use your browser dev-tools or a tool like [Fiddler](https://www.telerik.com/fiddler) to find out)

**Comment by pellea** [comment]
Thanks for the tip about Fiddler, I always forgot about it ...

This is the line of Fiddler:
```
# | Result | Protocol | Host | URL | Body | Caching | Content-Type | Process | Comments | Custom
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 200 | HTTP | laptop-ap:5004 | /mgmt | 48,938 |   | text/html; charset=utf-8 | signalr-test:16236 |   |  
```

That is obviously not what I should expect. The server returns the "Welcome Page".

I misplaced the `app.UseWelcomePage()` line, it should come after the `app.UseSignalR(routes =>...)`. I assume that is the expected behavior for the aspnetcore pipeline.

**Comment by anurse** [comment]
Yeah, if you don't put a path parameter in to `.UseWelcomePage`, it takes over all requests. The Welcome page isn't designed to be used in any real app though, so do you need to have it at all?

**Comment by anurse** [comment]
Closing this as the direct issue seems to have been resolved. Feel free to continue discussion or reopen if an issue does arise.

**Comment by pellea** [comment]
>  so do you need to have it at all?
I was using it only in development mode. I removed it, I don't need it as you stated.
