### ISSUE TITLE
Client exception: Server requested a response, which is not supported in this version of the client

### ISSUE THREAD

**Issue by FSou1** [aspnet/SignalR#1286]
Here is my browser stack trace:

```
Information: Normalizing '/tickers' to 'https://localhost:44323/tickers'
signalr-client.min.js:1 Information: WebSocket connected to wss://localhost:44323/tickers
signalr-client.min.js:1 Information: Using HubProtocol 'json'.
Login?ReturnUrl=%2F:143 data
signalr-client.min.js:1 Error: Server requested a response, which is not supported in this version of the client.
log @ signalr-client.min.js:1
invokeClientMethod @ signalr-client.min.js:1
processIncomingData @ signalr-client.min.js:1
connection.onreceive @ signalr-client.min.js:1
e.onmessage @ signalr-client.min.js:1
Login?ReturnUrl=%2F:134 Connection closed with error: Error: Server requested a response, which is not supported in this version of the client. red
```

There are frames that I received at client-side from `wss://localhost:44323/tickers`:

```
{"protocol":"json"}
{"invocationId":"4","type":1,"target":"UpdateTickersClient","nonBlocking":true,"arguments":["data"]}
```

I've reviewed the code base of signalr and figured out that the root cause of this exception is hidden here: https://github.com/aspnet/SignalR/blob/1bd99f6b67c3825151428a4048a5acd63425ef9a/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts#L115-L121

If invocationId is not null, than this exception will be thrown.

My service configuration contains next lines:
```
services.AddAuthentication().AddCookie();
services.AddSignalR();
```

```
app.UseAuthentication();

app.UseSignalR(routes =>
{
    routes.MapHub<TickersHub>("tickers");
});

app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}/{id?}");
});
```

I also use this singleton `TickersManager` to broadcast a message for all connected clients:

```
public class TickersManager
{
    private readonly HubLifetimeManager<TickersHub> _hubManager;

    private readonly Timer _timer;
    private readonly TimeSpan _delayStartBy = TimeSpan.FromSeconds(1);
    private readonly TimeSpan _repeatEvery = TimeSpan.FromSeconds(5);

    public TickersManager(HubLifetimeManager<TickersHub> hubManager)
    {
        _hubManager = hubManager;
        _timer = new Timer(UpdateTickers, null, _delayStartBy, _repeatEvery);            
    }

    private void UpdateTickers(object state)
    {
        Debug.WriteLine("Updated!");

        Task.Run(async () => await BroadcastTickers());
    }

    private async Task BroadcastTickers()
    {
        await _hubManager.InvokeAllAsync("UpdateTickersClient", new object[] { "data" });
    }
}
```

As I could see the method `InvokeAllAsync` creates `InvocationMessage`: 

https://github.com/aspnet/SignalR/blob/89b532c985999047da51b580ff79365b265dccc8/src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs#L77

But the value of `invocationId` is null and shouldn't be assigned:

https://github.com/aspnet/SignalR/blob/00a6dc983ac1df1ddc51c968c060bff8f45e5b2e/src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/HubMethodInvocationMessage.cs#L61

Have you got any ideas what goes wrong? Should I continue try to use WebSockets?

**Comment by FSou1** [comment]
If I won't use sockets and leave my connection initialization like this:

```
<script>
    var logger = new signalR.ConsoleLogger(signalR.LogLevel.Information);
    var connection = new signalR.HubConnection('/tickers', { logger: logger });

    connection.onclose(e => {
        if (e) {
            console.log('Connection closed with error: ' + e, 'red');
        }
        else {
            console.log('Disconnected', 'green');
        }
    });

    connection.on('updateTickersClient',
        data => {
            console.log(data);
        });

    connection.start();
</script>
```
Then there are an output with 404 error on /tickers/negotiate:
```
Information: Normalizing '/tickers' to 'https://localhost:44323/tickers'
signalr-client.min.js:1 POST https://localhost:44323/tickers/negotiate 404 ()
Promise @ signalr-client.min.js:1
send @ signalr-client.min.js:1
post @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
d @ signalr-client.min.js:1
startInternal @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
d @ signalr-client.min.js:1
start @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
d @ signalr-client.min.js:1
start @ signalr-client.min.js:1
(anonymous) @ (index):87
signalr-client.min.js:1 Error: Failed to start the connection. Error
log @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
h @ signalr-client.min.js:1
Promise rejected (async)
i @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
d @ signalr-client.min.js:1
startInternal @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
d @ signalr-client.min.js:1
start @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
(anonymous) @ signalr-client.min.js:1
d @ signalr-client.min.js:1
start @ signalr-client.min.js:1
(anonymous) @ (index):87
signalr-client.min.js:1 Uncaught (in promise) d
    at XMLHttpRequest.f.onload (https://localhost:44323/lib/signalr-client.min.js:1:4091)
```

**Comment by FSou1** [comment]
The problem was with the difference between frontend npm module and backend nuget package. Sorry for that.

**Comment by pain0486** [comment]
@FSou1 How did you solve it?
Are you using the @aspnet/signalr or the -client one?
I have the @aspnet/signalr: 1.0.0-preview1-30006 client side with the nuget of 1.0.0-alpha2-final

**Comment by anurse** [comment]
@pain0486 During the preview releases, the version of your `@aspnet/signalr` package should match your NuGet package exactly.

**Comment by FSou1** [comment]
@pain0486 Yes, I've cloned the latest version of npm and built it myself.

**Comment by pain0486** [comment]
@FSou1 you couldn't just do 
`npm install @aspnet/signalr --registry https://dotnet.myget.org/f/aspnetcore-dev/npm/`?

You downloaded master and built it yourself? Or did you find a nuget that matched the preview version?
The only way I have been able to get client and server on the same version is to use the @aspnet/signalr-client npm

**Comment by anurse** [comment]
> The only way I have been able to get client and server on the same version is to use the @aspnet/signalr-client npm

For `alpha2` and earlier `preview1` nightly builds, this is the case. Just to clarify the situation with the package name: In the first alpha releases, the name was `@aspnet/signalr-client`. **After** `alpha2` was release, but **before** we branched for the upcoming `preview1` release, we renamed the package to `@aspnet/signalr`. 

If you are using a build of SignalR server that is **before** `1.0.0-preview1-28129`, then you use `@aspnet/signalr-client`. If your build is **equal to or above** `1.0.0-preview1-28129`, then you use `@aspnet/signalr`.

**Comment by Hashemalrifai** [comment]
Hi, sorry, but I spent many hours trying to fix the same issue, right now I have this package: 
`<PackageReference Include="Microsoft.AspNetCore.Sockets" Version="1.0.0-alpha2-final" />`
And when I ran `npm install @aspnet/signalr` which gave me: 
`"@aspnet/signalr": "^1.0.0-preview2-30143"`
-> No success, 
Then I tried to clone this repos with tag 1.0.0-alpha2 and run build.cmd, but the command fails directly.
I want the simplest way to get SignalR running, thanks :)

**Comment by anurse** [comment]
If you're using the `1.0.0-alpha2-final` build on the server, use the `@aspnet/signalr-client` package, version `1.0.0-alpha2-final` on NPM (it's on the public NPM registry, so you don't need the `--registry` flag when installing it.
