### ISSUE TITLE
OnDisconnectedAsync doesn't call in Microsoft.AspNetCore.SignalR.Hub

### ISSUE THREAD

**Issue by pravinpatil83** [aspnet/SignalR#1290]
Hi, I am developing a chat application using Xamarin and SignalR. I am using the "1.0.0-alpha2-final" package both in client and on the server (ASP.Net Core 2).

The problem is OnDisconnectedAsync doesn't call. I test it by running solution in release mode on the local machine, on ubuntu server with Nginx.  

**Server Configuration:**
```
public void ConfigureServices(IServiceCollection services) {
        services.AddSignalR();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
            app.UseSignalR(routes =>
            {
                routes.MapHub<ChatHub>("chat", (options) => {
                    options.Transports = Microsoft.AspNetCore.Sockets.TransportType.WebSockets;
                });
            });
}
```
Client Connect Method

   ```
_connection = new HubConnectionBuilder()
                        .WithUrl($"{Configuration.CHAT_URL}?token={tokenInfo.AuthenticationToken}")
                        .WithMessagePackProtocol()
                        .WithConsoleLogger(LogLevel.Error)
                        .WithTransport(Microsoft.AspNetCore.Sockets.TransportType.WebSockets)
                        .Build();

                    await _connection.StartAsync();
```

When I disconnect internet connection of a mobile, I guess, OnDisconnectedAsync should call but it is not. Everything works except this OnDisconnectedAsync method. 
Can someone please take a look at this and give me a hint what to check? 
Thanks in advance.

**Comment by BrennanConroy** [comment]
Where is your `OnDisconnectedAsync` method? If you can provide a sample app on github that would be ideal

**Comment by pravinpatil83** [comment]
Here is the OnDisconnectedAsync method. I just noticed now that, it called once. But not all the times.

```
public override async Task OnDisconnectedAsync(Exception exception)
        {
            await base.OnDisconnectedAsync(exception);

            if (this.CurrentUser == null)
                return;

            try
            {
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, null, null);
                throw ex;
            }
        }

```

I will provide the sample app.

**Comment by pravinpatil83** [comment]
Hi, Created android sample app and asp.net core server consuming Microsoft.AspNetCore.SignalR packages. I am able to reproduce the issue in this new code base also.

https://github.com/pravinpatil83/aspnetcore_signalr

Please have a look.

**Comment by anurse** [comment]
> I'm guessing this is because we don't have keep-alive implemented in alpha2. So the server still thinks the client is around.

Even keep-alive doesn't guarantee that the server will know that the client has disconnected. If the client loses network connection, it has no way of signaling to the server that is has disconnected. The only way to guarantee that you'll detect disconnected clients is with a timeout.

**Comment by pravinpatil83** [comment]
Hi, Thankyou guys. Got it. Will try to add timeout.

**Comment by anurse** [comment]
We'll also continue to think about this before RTM. Right now we do have a timeout for Long Polling since it has no graceful disconnection logic (so if we didn't have a timeout, we'd **never** be able to call `OnDisconnectedAsync`). However, the other transports have graceful disconnection logic which triggers `OnDisconnectedAsync`, but if they disconnect disgracefully, we don't have any timeout logic for that. The Operating System will eventually consider the TCP connection broken and signal us, but the timeouts for that vary greatly from OS to OS (Linux for example is something like 10 minutes by default). (cc @davidfowl this is why we may want to consider client-to-server keep-alive)

**Comment by isaac873** [comment]
@pravinpatil83 how did you go with adding a timeout? I'm experiencing the same issue with network connection loss not triggering the `OnDisconnectedAsync `event.

**Comment by anurse** [comment]
This somewhat depends on your network configuration. Linux, for example, has a very high timeout before it considers a TCP connection closed. If the network disconnects, `OnDisconnectedAsync` only fires when the Operating System reports the connection as closed to us. If you want something more granular and application-specific, you can build logic into your Hub by storing the time the last message was received in the `Context.Connection.Metadata` property bag and have a handler attached to the `IConnectionHeartbeat` (use `Context.Connection.Features.Get<IConnectionHeartbeatFeature>().OnHeartbeat(...)` to register a heartbeat handler) that checks if any connections have been idle for too long.

I'm closing this for now as we aren't planning to add further logic here, but feel free to comment further and we can revisit this. We had a lot of problems with this in SignalR for ASP.NET and eventually app developers ended up having to build their own logic, so we don't want to add something that doesn't really work well until we understand all the scenarios.

**Comment by arishlabroo** [comment]
@anurse can you provide some more direction on how to reliably handle network disconnect? I am facing the similar issue where the `OnDisconnectedAsync` event is not firing in the hub. For testing, everytime I turn WI-FI off on my laptop, the client gets notified within 20-30 secs, but the server event doesnt fire. 

In our app, there can be an extended period of time where we don't send any actual message on the connection, so not sure what/when I would add in the Context.Connection.Metadata bag as suggested above. 

Can I do a ping-pong with the client on the OnHeartbeat event to make sure it is still there? Is that ideal?  Issues?.... Curious, what are the reasons it doesn't do it by default for websocket protocol.

Also, How do I get to "Context.Connection" .... where/when do I register the heartbeat handler

**Comment by arishlabroo** [comment]
```
public override async Task OnConnectedAsync()
        {
            var feature = Context.Features.Get<IConnectionHeartbeatFeature>();
            feature.OnHeartbeat(context => { 
                
            }, Context);
        }
```

for ping pong I was thinking send a message to the client and await til it replies back, similar to this
https://github.com/SignalR/SignalR/issues/1149#issuecomment-302611992.

but it is not async :( ...

Any ideas?

**Comment by davidfowl** [comment]
> @anurse can you provide some more direction on how to reliably handle network disconnect? I am facing the similar issue where the OnDisconnectedAsync event is not firing in the hub. For testing, everytime I turn WI-FI off on my laptop, the client gets notified within 20-30 secs, but the server event doesnt fire.

Doesn't fire ever? We did a few tests and it we've seen it take up to 30 minutes in some cases and that all depends on how the client disconnected.

> Can I do a ping-pong with the client on the OnHeartbeat event to make sure it is still there? Is that ideal? Issues?.... Curious, what are the reasons it doesn't do it by default for websocket protocol.

Sure.

Websockets *does* send ping pongs https://github.com/dotnet/corefx/blob/5da1070c7264594de50aff1a8b059c480c43a315/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L201. It doesn't however kill the connection if it fails to send the ping or failed to receive the pong. It also doesn't kill the connection if it fails to receive a ping on some interval. The keep alive here is just to avoid proxies killing the connection.

> for ping pong I was thinking send a message to the client and await til it replies back, similar to this
SignalR/SignalR#1149 (comment).

No, definitely don't do that. You would do something similar to what we do for heartbeats, just send on an interval if you you don't see a message within that interval you abort the connection.

> but heartbeat handler is not async :( ...

Yes, we should consider changing this. We'll see if we can get this in for RTM but the bar is pretty high at this point.

Given the nature of this problem it seems as though we should start sending pings from client to server (the protocol already supports it and the server also supports it today but doesn't do anything if those messages don't show up).

**Comment by arishlabroo** [comment]
Thank you for your response @davidfowl 

> Doesn't fire ever? We did a few tests and it we've seen it take up to 30 minutes in some cases and that all depends on how the client disconnected.

Yes it did fire eventually. If client gets disconnected by closing browser, event is fired pretty quickly. For network disconnects, not so much 😢<sup>unfortunately for our on the road users, that happens way too often</sup>

> You would do something similar to what we do for heartbeats, just send on an interval if you you don't see a message within that interval you abort the connection.

To make sure I understand, I could do something like: send a ping every few seconds from the Client and save the received time in `Context.Connection.Metadata`. And in the heartbeat event just check if the metadata value is recent enough.

**Comment by davidfowl** [comment]
> To make sure I understand, I could do something like: send a ping every few seconds from the Client and save the received time in Context.Connection.Metadata. And in the heartbeat event just check if the metadata value is recent enough.

Yes, I've filed https://github.com/aspnet/SignalR/issues/2175 to do this in the next release.
