### ISSUE TITLE
Spurious calls of OnDisconnectedAsync?

### ISSUE THREAD

**Issue by rhegner** [aspnet/SignalR#1292]
I'm trying to keep track of the online-state of my users (note that in theory there can be more than one signalr connection per user). So I basically count the number of signalr connections per user-id (increment in OnConnectedAsync, decrement in OnDisconnectedAsync) and if that number is >0 I consider that user to be online.

Now what happens is that these counters sometimes go below zero, which should be impossible.
Do I have a guarantee that for every OnConnectedAsync() I get one (and only one) OnDisconnectedAsync()? Or can there be spurious OnDisconnectedAsync()?

Maybe a related question: Am I supposed to remove clients from groups in OnDisconnectedAsync()?

**Comment by rhegner** [comment]
Thanks for your reply. Yes I do all the reference counting within a lock block, so I don't think it's a threading issue...

**Comment by BrennanConroy** [comment]
Can you share your hub or even better a sample app on github?
