### ISSUE TITLE
AspNetCore.SignalR not register HttpConnectionDispatcher

### ISSUE THREAD

**Issue by Deggger** [aspnet/SignalR#1293]
I use visual studio 2017 and .Net Core version: 2.0.3 whern i launch the project i have an exeption:

System.InvalidOperationException
HResult=0x80131509
Message = No service for type 'Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher' has been registered.
 
Packages in my csproj:

    PackageReference Include="AutoMapper" Version="6.2.2" />
    PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="3.2.0" />
    PackageReference Include="DotNetCore.NPOI" Version="1.0.2" />
    PackageReference Include="EntityFramework" Version="6.2.0" />
    PackageReference Include="FastMember.Signed" Version="1.1.0" />
    PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    PackageReference Include="Microsoft.AspNetCore.Antiforgery" Version="2.0.1" />
    PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" />
    PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.0.0-alpha2-final" />
    PackageReference Include="Microsoft.AspNetCore.Sockets" Version="1.0.0-alpha2-final" />
    PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.0.1" />
    PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
    PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.2" PrivateAssets="All" />
    PackageReference Include="Newtonsoft.Json" Version="11.0.1-beta3" />
    PackageReference Include="Npgsql" Version="3.2.6" />
    PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.1" />
    PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="2.0.0-preview1" />
    PackageReference Include="popper.js" Version="1.13.0-next" />
    PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0-preview1-25914-04" />

Thanks

**Comment by BrennanConroy** [comment]
Call `AddSignalR` instead of `AddSignalRCore`

**Comment by Deggger** [comment]
@BrennanConroy , it works) Thank you.
