### ISSUE TITLE
Dynamically Add On Event

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/SignalR#1295]
I'm experimenting with using SignalR to dynamically inject html and Typescript generated ES into pages. Getting the info into the pages works fine, but "registering" the content is hanging me up. For example, I am injecting fragments of html (a set of form fields) into a page, and I want to interact with the elements in the partial, including invoking SignalR. 

## Background

With a page and section,
```
<div id="container">
    ...
    <div id="formFields" ></div>
    ...
</div>
```
when the page loads, it requests some default fields. Other field sets are requested when running.
```
    connection.start().then(() => {connection.invoke("GetFields", "default")}
```
The hub event handler sends the content.
```
public class PageHub : Hub {
    public async void GetFields(string fieldset) {
        // fieldset == "default"
        string content = $@"
       <input type="text" id="name" />
       <input type="text" id="age" />
        ";
        
        await Clients.Client(Context.ConnectionId).InvokeAsync("FillFields", content );
    }
}
```
On the client, SR adds the fields to the page.
```
// Typescript
const find = (id: string): Node => document.getElementById(id);
connection.on("FillFields", content: string ): void {
        const section = find("formFields") as HTMLDivElement;
        section.innerHTML = content;
```
As long as the page is anticipating/expecting specific content, I can prepare/declare, and access the info in Typescript/ES. In a TS class I can expose the fields as properties, and use them in my client code. This code is in a TS class in the page from the beginning. 
```
const findInput = (id: string): HTMLInputElement => document.getElementById(id) as HTMLInputElement;
const reader = (formField: HTMLInputElement) => formField.value; // ...null handlers not shown
const writer = (formField: HTMLInputElement, value: string) => formField.value = value;

    private readonly Name_ = findInput("name");
    get name(): string { return reader(this.Name_); }
    set name(value: string) { writer(this.Name_, value); }

    private readonly Age_ = findInput("age");
    get name(): string { return reader(this.Age_); }
    set name(value: string) { writer(this.Age_, value); }
```
The reader/writer handle cases where the items aren't present.

## Problem
The example is not much more than a very complex show/hide, since the page must know what fields might be present, and have code for them. A problem is that inserted code doesn't get "registered" with the page. For example, if I insert a button and button handler, they don't get bound. Here I inject a fragment with a button and handler. 
```
<button id="submit">Press Me</button>
<script>  
    const submit_ = document.getElementById("submit");

    function register() {
        submit_.addEventListener("click", (e) => submitHandler(e), true);
    }
</script>
```
I need to run the `register` function to bind the handler. An approach I considered was using SR to run a "binding function". In the code I inject, I could also inject a `connection.on`, and call that.
```
<button id="submit">Press Me</button>
<script>  
    const submit_ = document.getElementById("submit");

    function register() {
        submit_.addEventListener("click", (e) => submitHandler(e), true);
    }

    connection.on("bindEvents", () => { register();  });
</script>
```
Sending the `connection.on("bindEvents")` has the same problem - it wouldn't be registered. I'll get a `Not Found`  if I try:
```
    Clients.Client(Context.ConnectionId).InvokeAsync("bindEvents");
```  
## Solution
It would be nice to be able to add "on events" from server-side. Using something like an `AddEvent` method. This would have an overload that would create and map the event.
```
Clients.Client(Context.ConnectionId).AddEvent("bindEvents");
Clients.Client(Context.ConnectionId).AddEvent("bindEvents", ()=>{ } );

```
With this capability we can create some very dynamic pages.
```
// My Page
<html>
<head>
    <script src="~/signalr/hubs"></script>
</head>
<body>
    <div id="dynamicBody" ></div>
</body>
<script>
    var connection = new signalR.HubConnection("/pageHub");
    connection.start().then(()=>{
        connection.invoke("Startup");
    });
    
    connection.on("InitPage", content: string ) {
       const body= document.getElementById("dynamicBody");
       body.innerHTML = content;
   }

</script>

// Server
public class PageHub : Hub {
   void Startup(){
      string content = $@"
         connection.on("initialize", () => { "init" }
         function init () {
         // All of the script and html for the page, generate dynamically
         // ...
      }";
      Clients.Client(Context.ConnectionId).InvokeAsync("InitPage", content);
      Clients.Client(Context.ConnectionId).AddEvent("initialize");
      Clients.Client(Context.ConnectionId).InvokeAsync("initialize");
   }
}
```

**Comment by anurse** [comment]
You can't use `innerHtml` to load script tags: https://stackoverflow.com/questions/1197575/can-scripts-be-inserted-with-innerhtml

If you're using `innerHtml` to inject, `<script>` tags won't be run. If you want to run arbitrary script from the server you'll need to use [`eval`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval), or inject a script file using [`document.createElement('script')`](https://stackoverflow.com/questions/7557868/document-head-document-body-to-attach-scripts)

> It would be nice to be able to add "on events" from server-side. Using something like an AddEvent method. This would have an overload that would create and map the event.

I'm confused by what this would do. You want to register a handler for the event on the client using code on the server? What client code would run when `Clients.Client(Context.ConnectionId).InvokeAsync("initialize");` is called?

**Comment by RandyBuchholz** [comment]
Maybe this makes sense. A simple example would be a four directional arrow controlled by right and left buttons. The arrow can point N,E,S, or W, and changes color (red or blue) based on time of day (AM/PM). If we pretend changing direction and color are distinct and complex processes, we might have eight client functions, called (northRed, northBlue, eastRed, etc). When the page loads at 2 PM, the arrow points N. There are only two valid actions when turning left or right - face East or face West. The hub only needs `connection.on` calls for E and W registered, mapped to `eastBlue` and `westBlue`. Invoking any other would be a business error. Say the user clicks "right".  SR invokes the "Right" method/handler on the server, passing the current direction (N). The server does its thing and then calls `connection.on("E")`, which is currently mapped to the `eastBlue` method. The client points a blue arrow east. Conditions have now changed. With the arrow pointing East, the valid actions are `connection.on("N")` and `connection.on("S")`. The time will have also changed, and it could now be AM. The server is able to control the behavior of the client and the conditions. If the time hasn't changed, the server can call something like 

```
connection.removeEvent("E");
connection,removeEvent("W");
--or
connection.clear()
```
 that would remove  the events. Then it could add only the newly valid methods:
```
connection.addEvent("N", (()=>{ northBlue() });
connection.addEvent("S", (()=>{ southBlue() });
```
Or, if now AM
```
connection.addEvent("N", (()=>{ northRed() });
connection.addEvent("S", (()=>{ southRed() });
```
The system can only call valid events - the others are gone. A nice side effect of this is that it automatically implements guard conditions. If all eight options were always exposed, the client would need to check conditions, and optionally send back some invalid condition notice. By only exposing valid conditions, a `not found` is automatically returned.

Taking it a step further is the injection of code. This may be a little more abstract. Suppose there is an additional, "unforeseen" and transient situation that makes the `northBlue` method inappropriate for one user. SignalR can inject a new ES function into the code, and map that function for that user.
```
connection.on("InjectCode", (northSpecialCode)=> injector(northSpecialCode));
connection.removeEvent("N");
connection.addEvent("N", (()=>{ northSpecialCode() }); 
-- then call it.
Clients.Client(Context.ConnectionId).InvokeAsync("N")
```
Calling syntax hasn't changed, but behavior has. This would replace the method until the page reloads. The way I was exploring this was for things like small sub-forms or pop-ups. I could push a pop-up to the client, register it as a SR `on`, and call it when I needed it. I wouldn't need to know/code all the possible pop-ups into the application client.

The general idea behind this is just-in-time and dynamic pages using SignalR. Something between mostly-client or mostly-server frameworks. I'm building a dynamic workflow system that is like a typical business application with several cells/controls on the page, that interact. These are complex controls (micro-pages). The controls are basically partial views, a SignalR hub, and some Typescript. They are bundled under a Typescript class and module, and they expose events. A Master Hub handles interactions between them. Only base code is sent on the initial load and then the modules are loaded on-demand, but pushed through SignalR, not pulled by the client. Experimental. The possible number of commands I send to client is high and conditional based on the current state of the different controls. The idea was that I could generate conditional code on the server (from a rules engine), send it to the client, and then only expose valid options.  

The "initialize" was maybe an over-extreme example trying to show that SignalR could take full control of the page content dynamically. Not meant to be a practical example. But basically, I was thinking of it as as `onloaded` type of thing - anything you wanted to run as soon as the page loaded. Thanks for the link.

**Comment by anurse** [comment]
I'm still not clear on what you're asking for from SignalR. It sounds like you just want the ability unbind and rebind client handlers, which we have via `off` and `on`.

Also, I think it might be more appropriate to simply put your various commands into a dispatch layer that sits outside of SignalR. Just have SignalR send `invokeCommand` methods which specify the command and arguments as parameters. Then your business logic is completely under your control and you aren't having to bend the framework to your goal.

If I'm misunderstanding, I think I need a simpler description of exactly what features you want added to SignalR in order to achieve your goal. Client handlers should already by dynamically bindable (using `on`) and removable (using `off`) so I need to understand better what specific changes you're looking for.

**Comment by RandyBuchholz** [comment]
OK, I think I see what's going on. I was looking at it wrong. I was looking at `on` sort of as invoking the event, not enabling the event. Thanks.
