### ISSUE TITLE
SignalR 1.0.0-preview1 verification areas

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#1297]
## SignalR Preview1 Verification

- Connect to server/Disconnect
- Client calls server methods
  - Read a return value 
  - Serialization of arguments (try different argument types, primitives, complex types, ...)
- Server broadcast to multiple clients 
  - Serialization ("ditto")
- Groups
  - Add to/Remove from group
  - Send to group 
  - Others in group
- Users
  - Authentication
  - Send to user
- Clients
  - TS/JS client
  - C# client
- Browsers (JS clients)
  - Chrome, Firefox, IE, Edge, Safari
  - Mobile browsers
- Connection lifetime
  - Disconnects (with all the supported transports)
    - Graceful disconnect
    - Network interruption
- Transports
  - WebSockets
  - Serverside events
  - Longpolling
- Protocols
  - Json
  - MsgPack
- Binary
  - use MsgPack for binary serilazation 
-  Scaleout
  - Redis
- Streaming
- Bare websockets

**Comment by muratg** [comment]
cc @anurse @BrennanConroy @mikaelm12 @davidfowl @DamianEdwards

**Comment by muratg** [comment]
cc @anurse

**Comment by anurse** [comment]
https://github.com/aspnet/Release/issues/237

**Comment by leak** [comment]
Any ETA for common folks? 

*...reaching for the party hat*

**Comment by muratg** [comment]
@leak soon! :)

**Comment by leak** [comment]
Hope Microsoft is paying proper royalties to Blizzard Entertainment for the use of "soon".  😉 

https://wow.gamepedia.com/Soon

**Comment by muratg** [comment]
@leak https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-now-available/ :)

**Comment by anurse** [comment]
SignalR post: https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-getting-started-with-signalr/
