### ISSUE TITLE
Fresh Checkout Doesn't Build

### ISSUE THREAD

**Issue by antoinne85** [aspnet/SignalR#1298]
### Fresh Checkout Doesn't Build
A fresh checkout doesn't seem to build correctly from the command line, even when following the directions from the [Building From Source](https://github.com/aspnet/Home/wiki/Building-from-source) page.

### Functional impact
I am unable to build and contribute to the project, as well as build and run the sample projects.

### Minimal repro steps
1. Clone the repository.
1. Navigate to the repository folder in a terminal.
1. Run build.cmd.
1. Wait for the build process to exit.

### Expected result
I expected a successful build.

### Actual result
The build failed with several errors.

### Further technical details
I'm just getting started with this project, so I'm unfamiliar with what is expected from the build and I'm not yet attempting to build from Visual Studio. 

I've logged the build output and created [this gist](https://gist.githubusercontent.com/antoinne85/800af997d077ae3fa80e5f3ad422134d/raw/b183f27393ea951de00729a49b605bdb8666ac4a/build-output.log) (link to the raw content--because of its size, the pretty view truncates it).

Any input or advice you might have on how to get up-and-running would be greatly appreciated.

**Comment by anurse** [comment]
We use `docker` for some of our tests and it looks like there are some errors in there relating to docker:

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint redisTestContainer (bbafe9e2b9e88b14e1d231eae755ae33755292e1399a278a846cab5fdc6ae955): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:6379:tcp:172.17.0.2:6379: input/output error.
```

Do you have Docker for Windows installed and working properly? We try to detect docker and skip those tests if it's not present but it looks like you have `docker` but it is broken somehow.

Can you try `docker ps` and if that works `docker run --rm -it redis` (The redis image should be pulled and start up, you can Ctrl-C out of it when it starts and it will be removed)

**Comment by antoinne85** [comment]
I think I was a little premature in closing this out.

I got the command line build working, but then when you open the solution in VS 2017 several of the sample projects don't load anymore, citing the following error.

![image](https://user-images.githubusercontent.com/182187/34910049-850e08b6-f87b-11e7-8565-a1bef911c2d2.png)

After seeing this, I figured I must have done something wrong, so I nuked the repo, cloned it fresh again, opened it in VS 2017, and saw that the projects loaded okay. But, after running the command line build again, it hoses the projects in VS 2017.

Is the command-line build script materially altering the projects in some way?

For reference, I'm on VS 2017 15.5.3.

Any more insights?

When this is over I'll do what I can to update documentation for others who may be trying to get started.

**Comment by antoinne85** [comment]
I should add that after the command line build, Git doesn't show any files changed--so I have to assume something is changing that `.gitignore` is explicitly ignoring.

**Comment by antoinne85** [comment]
Seems to be that the creation of `global.json` in the solution folder is what's causing the sample projects not to load.

```
{ "sdk": { "version": "2.2.0-preview1-007866" } }
```

Dropping that down to `2.1.0` allows me to load the projects again, so it appears that my issue is related to VS not being able to locate the `2.2.0-preview1-007866` version of the SDK.

If I go peruse `%USERPROFILE%/.dotnet/x64` it seems to have the `2.2.0-preview1-007866` content in it (presumably stashed there by the command-line build). That directory is also the only `dotnet`-related directory listed in my PATH (as per the build instructions).

**Comment by BrennanConroy** [comment]
At the very top of the build log it says
```
WARNING: dotnet found on the system PATH is 'C:\Program Files\dotnet\dotnet.exe' but KoreBuild will use 'C:\Users\tonyc\.dotnet\x64\dotnet.exe'.
WARNING: Adding 'C:\Users\tonyc\.dotnet\x64' to system PATH permanently may be required for applications like Visual Studio or VS Code to work correctly.
```

**Comment by antoinne85** [comment]
Hey @BrennanConroy. The gist is from before I made that change to my PATH variable.

**Comment by anurse** [comment]
Did you launch VS from the command prompt you ran `build.cmd` from? Generally you should do that since the build command modifies the `PATH` to put the `dotnet` SDK it downloaded in place.

(We really should get a clear contributing doc together with these steps, but unfortunately other things have been a higher priority 😦 )

**Comment by antoinne85** [comment]
No, I hadn't been launching VS from the command prompt.

I'm not sure what would cause this, but I moved the `%USERPROFILE%/.dotnet/x64` entry into the System PATH instead of my User PATH and suddenly everything seems to work. I can get a successful build both from the command line and from within VS.

**Comment by antoinne85** [comment]
When you folks develop, do you typically launch VS from the command prompt after doing a command-line build?

It did seem a little strange to me to be adding this special directory to my PATH. Given that I use this machine for lots of things besides trying to build SignalR, it would be a shame if things started going all blinky because VS was picking up a strange version of the SDK.

But I'm guessing that it really only pulls in the preview versions of the SDK and VS will find the major/minor SDK versions in the typical location (if they're being targeted)?

**Comment by antoinne85** [comment]
Here's are some more things I've been able to piece together. 

As indicated before, running `build.cmd` produces the following output.
```
WARNING: dotnet found on the system PATH is 'C:\Program Files\dotnet\dotnet.exe' but KoreBuild will use
'C:\Users\tonyc\.dotnet\x64\dotnet.exe'.
WARNING: Adding 'C:\Users\tonyc\.dotnet\x64' to system PATH permanently may be required for applications like Visual Studio or VS Code to
 work correctly.
Adding C:\Users\tonyc\.dotnet\x64 to PATH
```

Despite this, though, after execution completes, if I dump the contents of the PATH variable, `C:\Users\tonyc\.dotnet\x64` is not in there.

If I manually add it within the terminal session and then launch VS, everything works correctly.

I think that for now I'll just draft a small script to set that variable and launch VS for me.

**Comment by antoinne85** [comment]
Here's what I've been able to sort out now.

Despite saying it's adding the `%USERPROFILE%/.dotnet/x64` directory to the PATH, after a command-line build, `echo`ing the PATH shows that the directory isn't actually _in_ the PATH.

I think for now I'll just drop a script in the folder that sets the PATH variable and launches VS on my behalf, unless someone else has a better solution.

**Comment by natemcmaster** [comment]
Re: the Visual Studio experience. I've opened https://developercommunity.visualstudio.com/content/problem/183188/unhelpful-error-message-when-globaljson-points-to.html to track improve the error message when the .NET Core SDK required via global.json cannot be loaded.

**Comment by anurse** [comment]
> It did seem a little strange to me to be adding this special directory to my PATH.

Yeah, I'm not a fan of having to do that either but we need our builds to run against specific versions of .NET Core (since we release in sync with them, we need to use nightly and preview builds) and our scripts can't write to Program Files (because we don't want to require Admin access to build). VS needs to have the .NET SDK on the PATH though, in order to use it to provide IDE services. It's unfortunate but it's what we're limited to right now :)

**Comment by antoinne85** [comment]
@anurse Totally understandable--it takes what it takes, you know. 

Doesn't this mean, though, that the daily builds aren't very useful for external folks? For instance, suppose I wanted to take a web application that's using whatever the current stable version of SignalR (presumably built against the latest stable version of the SDK) is and try out the latest dev build (maybe it contains a bug fix I'm interested in testing in my application or something)--if SignalR is building against the latest-and-greatest SDK, in order to run that in an existing application, I'd have to go get my application set up to build against that pre-release SDK as well, wouldn't I? That may not be an intended workflow for consuming applications, and that's an okay answer as well. I'm just curious about the way that you would like to see consuming applications interact with this project.

I'm interested in building an application around SignalR, so I'm trying to get a handle on what it looks like to contribute and how a development flow would look when working against a library that's so close to the SDK movement. (Typically, most libraries are built at a level that's much further away from underlying technology, whereas SignalR seems to be pretty close to the ASP.NET/.NET Core foundations.)

Continuing on, though, given that I've managed to sift through some of this locally--would the team be open to a PR that includes some documentation around getting up and running locally for this specific project (including some explanations about why things are they way they are). Perhaps include a tiny script that assists a first-timer in getting things working in VS as well as running the command-line build.

**Comment by Benedicht** [comment]
@anurse Thanks for the explanation.

**Comment by anurse** [comment]
> I'd have to go get my application set up to build against that pre-release SDK as well

Yeah, when running nightlies, you do generally have to use nightly builds of the .NET SDK. That's not always true and they don't have to be exactly the same version, but things have been a little rough right now as we've been getting new runtime builds for the `Span<T>`-related features we use.

> would the team be open to a PR that includes some documentation around getting up and running locally for this specific project

YES! Very open! What would be best right now is to stick with documentation. Our build scripts are shared across all aspnet repos so we generally want to avoid introducing new scripts in just one repo. We can look at where the documentation is awkward and add some scripts to support those scenarios though.

**Comment by lnaie** [comment]
Git this myself, right now.
![image](https://user-images.githubusercontent.com/1276077/36305702-e797e69c-1314-11e8-8949-e23ed272255f.png)

**Comment by lnaie** [comment]
Made some progress after I fixed the dotnet env path also the msbuild path. Now I've reached this point:
![image](https://user-images.githubusercontent.com/1276077/36323875-bd2de47c-1352-11e8-9e02-b1e4635768ac.png)

**Comment by anurse** [comment]
Your second post has references to `Microsoft.AspNet.SignalR` which is github.com/SignalR/SignalR (a different repo). Which repo are you trying to build? This issue tracker is for issues with the aspnet/SignalR repo, not SignalR/SignalR

**Comment by lnaie** [comment]
indeed, sorry, the second screen is from other machine that seems to have the old SignalR. switched to the new one.
