### ISSUE TITLE
Project doesn't build locally without TypeScript Compiler on path

### ISSUE THREAD

**Issue by MisterJames** [aspnet/SignalR#13]
After cloning the repo, a local build causes two errors (in ChatSample and SocketsSample) when you don't have tsc on your path.

**Comment by gencebay** [comment]
You can install it with:
` npm install -g typescript` as globally so if you dont have npm (node package manager) you can install it from [this url](https://nodejs.org/en/) with below configurations then IDE or Editor restart may required!
![nodejs_install_npm_globally](https://cloud.githubusercontent.com/assets/879469/20111497/35229de0-a5f1-11e6-89eb-127929366c4e.PNG)

**Comment by MisterJames** [comment]
You bet @gencebay, already PR'd to the readme.  @anurse asked me to file this so they can determine if they want to fix the error at a project level or via docs.
