### ISSUE TITLE
How use the SignalR with token based authentication?

### ISSUE THREAD

**Issue by Jenan** [aspnet/SignalR#130]
I want to use the token based authentication and I've been wondering how insert the token to the SignalR connection.

I've found some example where is token insert in the query string but I can't use it because the url could be find in some logs.

How can I send the JWT token to the HUB and validate it?

Thank you.

**Comment by davidfowl** [comment]
> I've found some example where is token insert in the query string but I can't use it because the url could be find in some logs.

You have to use the query string. The WebSockets javascript client doesn't support custom headers.

**Comment by Jenan** [comment]
I am wondering to add the JWT add the parameter of the client side function and validate it on the server for example:

What do you think about it instead of use the querystring? Is this way more secure than querystring?

```js
$(function () {

    var chat = $.connection.chatHub;
   
    $.connection.hub.start().done(function () {
                    chat.server.send(JWT);
        });
});
```

```cs
 public class ChatHub : Hub
    {
        public void Send(string jwt)
        {
            var validate = ValidateJwt(jwt);

            if(validate){
                    //DO SOMETHING
            }
        }
    }
```
Thank you.

**Comment by anurse** [comment]
That wouldn't be any more secure that using the querystring, but it would work fine if you wanted to do it that way. In either case, unless you're using HTTPS, a man-in-the-middle attack could see the token. So if it's simpler to use the querystring, go ahead.

I do strongly encourage you to use HTTPS though, to prevent man-in-the-middle attacks.

**Comment by bromanko** [comment]
@anurse Can you be more specific about how one might use querystring to pass the token? Is there an existing ASP.NET authentication mechanism that reads auth tokens from querystring? 

I've been exploring the ChatSample and it appears to use cookie authentication to covert the hub endpoints.

**Comment by mikebridge** [comment]
@bromanko I don't know if there's a more elegant way, but I read the token from the query string in middleware and pass it on as though it were a regular Authentication header, e.g.:

https://github.com/mikebridge/IdentityServer4SignalR/blob/master/src/ChatAPI/Auth/JWTSignalRExtensions.cs

Then you can use the regular `UseJwtBearerAuthentication` call:

https://github.com/mikebridge/IdentityServer4SignalR/blob/master/src/ChatAPI/Auth/JWTInitialization.cs#L80-L87

**Comment by fuocor** [comment]
I use the following

`      private Task OnMessageReceived(MessageReceivedContext context)
        {
            //DumpHeaders(context.Request.Headers);
            var headers = context.Request.Headers;
            var header = headers.Any(kp => string.Compare(kp.Key, CONNECTION_UPGRADE, StringComparison.InvariantCultureIgnoreCase) == 0 && kp.Value.Any(h => string.Compare(h, UPGRADE_WEB_SOCKET, StringComparison.InvariantCultureIgnoreCase) == 0));
            if (header && context.Request.Query.ContainsKey(AUTHORIZATION))
            {
                // pull the bearer token out of the QueryString for WebSocket connections
                _logger.LogInformation($"{nameof(OnMessageReceived)} processing websocket querystring authentication");
                context.Token = context.Request.Query[AUTHORIZATION];
            }

            return Task.FromResult(0);
        }
`
rich

**Comment by davidfowl** [comment]
@fuocor you don't need to manually look at headers to determine if the current request is a websocket request. There's a first class property on the `HttpContext`:

```C#
private Task OnMessageReceived(MessageReceivedContext context)
{
    if (context.HttpContext.WebSockets.IsWebSocketRequest && context.Request.Query.ContainsKey(AUTHORIZATION))
    {
        // pull the bearer token out of the QueryString for WebSocket connections
        _logger.LogInformation($"{nameof(OnMessageReceived)} processing websocket querystring authentication");
        context.Token = context.Request.Query[AUTHORIZATION];
    }

    return Task.CompletedTask;
}
```

**Comment by Jenan** [comment]
@mikebridge Is it possible set the authorization header for SignalR connection from Javascript? How do you set it if you have used the authrozitation headers in middleware? The reason why I have used the jwt token in query string, because It was'nt able pass jwt as an authorization header from javascript side.

Thank you.

**Comment by davidfowl** [comment]
@Jenan no, the javascript websocket client doesn't allow it.

**Comment by Jenan** [comment]
@davidfowl Thanks, I have removed my question because I don't read correctly, thank you.

**Comment by SGStino** [comment]
i was looking into getting the jwt token in the header when creating the initial connection, and this seems to work. However, I can't find anything server-side that contains that token.

```http
OPTIONS http://192.168.1.10:5000/hubs/events HTTP/1.1
User-Agent: Microsoft.AspNetCore.Sockets.Client.Http/1.0.0-alpha
Authorization: Bearer eyJ0e...
Host: 192.168.1.171:56419
Content-Length: 0
```
```http
HTTP/1.1 200 OK
Date: Fri, 06 Oct 2017 17:16:08 GMT
Content-Type: application/json
Server: Kestrel
Content-Length: 125
Allow: GET,POST,OPTIONS
Request-Context: appId=cid-v1:b91b490a-68aa-4451-829d-55b1076112c2
{"connectionId":"63284d81-88fa-4200-95e9-8171213cacc3","availableTransports":["WebSockets","ServerSentEvents","LongPolling"]}
```
```http
GET http://192.168.1.10:5000/hubs/events?id=63284d81-88fa-4200-95e9-8171213cacc3 HTTP/1.1
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Key: Xsl/8XU4BT4NXsV3+MVDPA==
Sec-WebSocket-Version: 13
Host: 192.168.1.171:56419
```
```http
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Date: Fri, 06 Oct 2017 17:16:08 GMT
Server: Kestrel
Upgrade: websocket
Request-Context: appId=cid-v1:b91b490a-68aa-4451-829d-55b1076112c2
Sec-WebSocket-Accept: dlqwfi6JHEQZJsRq8xbDTcFv9kg=
```

The initial `OPTIONS` call is authenticated, and it creates the connection id, which can only be used once if I'm not mistaken. This means, that at this point, the server knows the mapping from the connection id to the ClaimsPrincipal of the user. Without the JWT token ever appearing in any logs. So the token is basically swapped out for a one-time use password (the connection id).

So in theory, if this could work, this should be more secure than the query parameter unless I'm missing something vital?

The first OPTIONS call and the GET with the connection upgrade need to be handled by the same server instance? Because another node won't know the connection id?

And for the long-polling transport it could just fall back to providing the Authorize header in each request.

**Comment by moozzyk** [comment]
I merged a change (0bafb304c2707739578e635bc9e00d0cd36420a7 18a65496b7adab684a9af2ac255c7128699c96ee) today that adds an API that allows to pass a JWT token when starting a connection. When using the C# client the JWT token will be passed in the header. When using the TS client the token will be passed in the header when sending an HTTP request with XmlHttpRequest (i.e. for negotiate, long polling - send/poll request, server sent events - send request) or in the query string if the underlying API does not allow setting headers (webSockets, eventSource used for the server-to-client channel in the ServerSentEvents transport) as the `signalRTokenHeader` queryString parameter. When using the TS client it is required to copy the token to the MessageReceivedContext.Token as shown in the [sample](https://github.com/aspnet/SignalR/blob/dev/samples/JwtSample/Startup.cs#L49-L62).

**Comment by rexxmagnus** [comment]
I just wanted to point out that I've got headers to work with SignalR.

Has support for headers must been added recently? I can access the headers in the context when connecting.

I have been passing an "Authorization: Bearer xxxx"  header with an authentication token for my api, and resolved to use the method of copying the bearer token into a cookie to pass to SignalR. However, I didn't like having to clean up the cookies on my setup (it's quite complicated), so after a little experimentation I implemented the same OAuthBearerAuthenticationOptions as in my api and it appears to work (even though the Authorization is a header!)

This code is inside the Configuration(IAppBuilder app) section of my Startup class.

```
app.Map("/signalr", map =>
            {
                var hubConfiguration = new Microsoft.AspNet.SignalR.HubConfiguration();
                hubConfiguration.EnableDetailedErrors = true;
                map.UseOAuthAuthorizationServer(WebApiConfig.OAuthServerOptions);
                
                // Use the same bearer token authentication method as the general api.
                map.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions());

                map.RunSignalR(hubConfiguration);
            });
```

**Comment by mictian** [comment]
Hi @rexxmagnus ,

I am trying to also authenticate using a header token.
What I am not sure, is if your use case is to authenticate the entire SignalR endpoint to not "expose it" to everyone, or by the contrary you want to have the identity of the current user in the context of SignalR itself (which is my case).

In other words, I have the following code:

```
public class NotificationHub : Hub
{
	public async override Task OnConnectedAsync()
	{
		var identity = Context.User.Identity;

		if (identity.IsAuthenticated)
		{
			await Groups.AddAsync(Context.ConnectionId, GetGroupName(identity.Id)).ConfigureAwait(false);
		}

		await base.OnConnectedAsync();
	}
}
```

and I wonder how your code can be used in conjunction with mine to provide an Identity to SignalR. (assuming that is your aim)

Thanks in advance,
Mictian

**Comment by rexxmagnus** [comment]
@mictian, I use it for internal authentication and for obtaining the claims that are set by my api. Because it's using the oauth methods that the API uses to encode/decode them, the shouldn't be readable off-system anyway.

In my OnConnected method, I call another method that takes the Context.User and returns my own internal identity object (bear in mind this is only the constructor for the class, and that the strings must match whatever claims you set in your authentication setup):

```
public ApiAuthObject(System.Security.Principal.IPrincipal user)
{
    _Identity = user.Identity as ClaimsIdentity;
    if (_Identity != null)
    {
       if (_identity.FindFirst("AuthID") != null)
       {
           _ID = new Guid(_identity.FindFirst("AuthID").Value);
       }

       if (_identity.FindFirst("AuthUserName") != null)
       {
           _Username = _identity.FindFirst("AuthUserName").Value;
       }
    }
}
```

**Comment by elhamsarikhani** [comment]
@rexxmagnus  how did you pass the oauth token to the connection in javascript?
`$.connection`  doesn't have headers

**Comment by anurse** [comment]
SignalR for ASP.NET (non-Core) doesn't support headers in the JavaScript client because browser WebSockets and Server-Sent Events APIs don't provide any way to send headers. We recommend using the query string (via `$.connection.qs`) to send authentication tokens.

FYI: The ASP.NET SignalR repo is at http://github.com/signalr/signalr. This repo is for ASP.NET **Core** SignalR, which is a new version of SignalR for ASP.NET Core.

**Comment by elhamsarikhani** [comment]
@anurse  so in Core version, we can send the headers?

**Comment by rexxmagnus** [comment]
Ordinarily, there's no way to directly send the headers in that api, but I'm using an angular wrapper for the hub, and a custom http interceptor to add headers to any requests sent by angular's $http module. I'll try to post a minimum working example soon.

**Comment by elhamsarikhani** [comment]
Thanks @rexxmagnus  looking forward to the code snippet :grin:

**Comment by rexxmagnus** [comment]
Here is my minimum example. I have an app that expands angular's http provider by adding an interceptor that injects the headers with the authorization and refreshtoken. The refresh tokens are handled by oauth in an api, so they're not entirely necessary for the context of signalr. You have to use the same oauth configuration as for your authorization if you are sharing the auth ticket between api and signalr.

The app provides a signalrFactory, to which the angular controllers can subscribe for events from signalr. Whether there's a way of injecting the headers into signalr without using the angular wrapper is something other devs will know about (and seems unlikely to be possible).

Hope this helps.

```

var app;
if (typeof (angular) !== 'undefined') {

    app = angular.module('myApp', ['SignalR']);//includes the signalr module mentioned below

    app.factory('authInterceptorService', ['$q', '$injector', function ($q, $injector) { //mirror this functionality in global.js $.ajaxSetup for non-angular calls
        var _handleRequest = function (config) {
            //Retrieve auth token from storage (or wherever you put it) and append to the transmission as a header.
            // The angular signalr wrapper will also contain these headers that can be read during the onConnect of the hub.
            var _authData = getFromStorage('auth') || {};
            if (_authData) {
                if (_authData.access_token && _authData.access_token.length) {
                    config.headers["Authorization"] = 'Bearer ' + _authData.access_token;
                }
                //Also including the refreshtoken if necessary
                if (_authData.refresh_token && _authData.refresh_token.length) {
                    config.headers["RefreshToken"] = _authData.refresh_token;
                }
            }
            return config;
        };

        var _handleResponse = function (response) {
            if (response) {
                if (response && response.data && response.data.Error) {
                    // Here I handle my custom (intentionally returned) error data
                } else return response;
            }
        };

        var _handleResponseError = function (rejection) {
            var deferred = $q.defer();
            if (rejection.status === 401) {
                //On auth failure, try to get the refresh token then re-send the original request
            } else {
                // Handle your error
                deferred.reject(rejection);
            }
            return deferred.promise;
        };

        return {
            request: _handleRequest,
            response: _handleResponse,
            responseError: _handleResponseError,
        };
    }]);


    app.config(["$httpProvider", function ($httpProvider) {

        // Bind the authinterceptor
        $httpProvider.interceptors.push('authInterceptorService');

        $httpProvider.defaults.transformResponse.push(function (responseData) {
            // Here I also run a method that transforms date strings into real dates to be returned to the methods that call $http in my controllers
            return responseData;
        });

        $httpProvider.useApplyAsync(true);//make data that returns at roughly the same time cause only one digest
    }]);


    //Signalr factory - https://github.com/JustMaier/angular-signalr-hub used for easy mapping
    app.factory('signalFactory', ['$rootScope', 'Hub',
        function ($rootScope, Hub) {
            var _broadcastEventName = 'signalr-service-event';
            //declaring the hub connection
            var hub = new Hub('myHub', {
                
                //client side methods called by the service
                listeners: {
                    broadcastMessage: function (message) {
                        $rootScope.$emit(_broadcastEventName, {message: message });
                    },
                },

                //server side methods for injection - call these with hub.xxx
                methods: ['send'],

                //query params sent on initial connection
                queryParams: {
                    // You can use the following to add querystrings
                    //    'token': 'exampletoken'
                },

                //handle connection error
                errorHandler: function (error) {
                    
                    if (!!error.message && error.message == 'WebSocket closed.') {
                        // Fire disconnected event
                        // Handle the disconnection
                    } else {
                        console.error(error);
                    }

                },

                //specify a non default root (I have modified this, since the default is /signalr which omits the initial path when running locally
                rootPath: 'signalr',

                stateChanged: function (state) {
                    //console.log('state changed', state);
                    switch (state.newState) {
                        case $.signalR.connectionState.connecting:
                            //your code here
                            break;
                        case $.signalR.connectionState.connected:
                            //your code here
                            break;
                        case $.signalR.connectionState.reconnecting:
                            //your code here
                            break;
                        case $.signalR.connectionState.disconnected:
                            //your code here
                            break;
                    }
                }
            });

            //Exported object
            var signalFactory = {};

            // Allow controllers to subscribe to broadcast events
            signalFactory.subscribe = function (scope, callback) {
                if (typeof callback === 'function') {
                    var handler = $rootScope.$on(_broadcastEventName, function (event, args) {
                        callback(args);
                    });//Returns the destructor for the handler

                    //Unbind the event handler if the scope of a controller has been passed. Factories have no scope and thus are assumed to only exist once and therefore require no unbinding
                    if (scope) {
                        scope.$on('$destroy', handler);//unbind when the scope is destroyed
                    }
                }
            };

            // Client sending methods

            signalFactory.send = function (type, message) {
                hub.send(type, message); //Calling a server method
            };

            return signalFactory;
        }
    ]);

}
```

**Comment by hkosmidi** [comment]
is there a sample on how to send the Bearer token in asp.net core from an angular 5 application?

**Comment by anurse** [comment]
There is no specific sample as far as I'm aware. There are some examples using Angular above as well as the [JwtSample](https://github.com/aspnet/SignalR/tree/dev/samples/JwtSample) in this repo that shows the client and server (in Startup.cs) code necessary to flow a JWT token through WebSockets/Server-Sent Events

**Comment by imsam67** [comment]
I'm trying to use the approach @davidfowl  suggested by doing a `context.WebSockets.IsWebSocketRequest` test but I'm always getting `false` on that. Any idea why that would be? That approach seems to be the cleanest so I'd like to use that as opposed to checking headers or comparing path value to see if the request is going to my hub. For some reason though, `IsWebSocketRequest` is always `false`.

**Comment by BrennanConroy** [comment]
You'll need to add `app.UseWebSockets()` above your `app.UseAuthentication()` call.

**Comment by imsam67** [comment]
Just to be clear, the `app.UseWebSockets()` middleware is for me to have the ability to determine the nature of incoming request, correct? It's not really required for `SignalR` to work. I'm already using `app.UseSignalR()` and it's working fine.

**Comment by BrennanConroy** [comment]
Thats because `UseSignalR()` calls `UseWebSockets()`. However because you're using auth before SignalR you need to add WebSockets yourself before auth.

Although, now that I'm thinking about it, you might be able to move the auth after SignalR because we already run auth internally in SignalR, unless you have other things running before SignalR that need auth.

**Comment by davidfowl** [comment]
No that’s not recommended. Other things will fail
