### ISSUE TITLE
Consider renaming `InvokeAsync` on server to `SendAsync`

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1300]
The client has `SendAsync` which is fire-and-forget and `InvokeAsync` which waits for a completion message from the server.

The server has `InvokeAsync`, which is fire-and-forget and thus out of sync with the client APIs.

I propose renaming the server's `InvokeAsync` to `SendAsync` to match the client. It is a break from the SignalR 2.x API, but a) it's a simple rename and b) most people were using the `dynamic` API which isn't present by default anyway so it's not like porting relied on this API being the same name.

It also allows us to open the door to Client Results by using the `InvokeAsync` name on the server.

I think we should do this in Preview 1 if we're going to do it.

cc @davidfowl @DamianEdwards @muratg

**Comment by muratg** [comment]
@anurse makes sense to me, let's do it unless @davidfowl or @DamianEdwards reacts in the meantime.

**Comment by davidfowl** [comment]
Ugh, I was hoping we would fudge this but the purist in me says its right

**Comment by anurse** [comment]
![https://media1.tenor.com/images/ee9682d61532ff2b111775f22e4d7077/tenor.gif?itemid=5340126](https://media1.tenor.com/images/ee9682d61532ff2b111775f22e4d7077/tenor.gif?itemid=5340126)

**Comment by DamianEdwards** [comment]
Agreed

**Comment by grahamehorner** [comment]
@anurse @DamianEdwards @davidfowl IMHO InvokeAsync seems correct as SignalR is in essence doing a RPC (just my two pennies worth) but whichever I'm look forward to SignalR got some interesting ideas for a SignalR mesh 👯‍♂️

**Comment by anurse** [comment]
@grahamehorner You're correct, which is why the Client has `InvokeAsync`. RPC implies that the call doesn't return until the method invocation has completed (which is how the Client's version of `InvokeAsync` behaves). However, the server does not currently support receiving a result from the client. All server-to-client invocations are fire-and-forget (as it was in SignalR 2.x), so it's more appropriate to use `SendAsync` to match the behavior of the client's version of `SendAsync`. We do have some thoughts about enabling results from server-to-client invocations as well, so we'll want to reserve `InvokeAsync` for that purpose.

**Comment by anurse** [comment]
It sounded like @BrennanConroy was looking for Preview 1 work at stand-up this morning ;) /cc @muratg

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/d38764a8f0a9cc189e84c28113a5a7aa5b5535d7
