### ISSUE TITLE
signalr alpha 2: how to deserialize from camel to pascal with messagepack

### ISSUE THREAD

**Issue by Erikvdv** [aspnet/SignalR#1301]
I am having the following problem:
I have a typescript FE and a .net core backend.
my typescript objects are camelcase and my .net core objects are pascal case (the standard way for both languages).
When I use the JsonHubProtocol the ts/js object is deserialized properly to my POCO object in .net and also nicely serialized to camelcase when sending from .net to my ts frontend.
However, when I am using MessagePack this is not happening. 
with 
```C#
services.AddSignalR(o =>
{
    o.MessagePackSerializationContext.DictionarySerlaizationOptions.KeyTransformer = DictionaryKeyTransformers.LowerCamel;
});
```
I can make sure the POCO object is transformed into camel case. However, I can't find any way to do it the other way around. So having a camelcase ts object that will be mapped to a pascal case POCO object automatically.

Any thoughts on how to achieve this?

**Comment by Erikvdv** [comment]
After digging a bit more I guess the only way is to use the "workaround" of defining datamembers like: `[DataContract]
    public class Example
    {
        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "surname")]
        public string Surname { get; set; }
    }`

**Comment by muratg** [comment]
@anurse will take a look.

**Comment by anurse** [comment]
Looks like this was an issue in an older version of MsgPack-Cli that we were using. I'm updating to 1.0.0-rc and it seems to have resolved the issue. PR pending
