### ISSUE TITLE
Question: Is it now required to make a fork and publish it to personal package server if I need to get latest builds 

### ISSUE THREAD

**Issue by ivankarpey** [aspnet/SignalR#1304]
Hello. I'm as a vendor using SignalR for the building the early project version for my client. Yes, I know that signalr still in an early version and not suitable for production use, the same as a platform I currently build. However, I rely on signalr in this project and prefer to have latest available build for client/server version of the code. Some time ago I used myget server with CI builds, but currently, it's gone, and aspnecore-dev don't get server component updates for nearly a month already. Is the currently any alternatives for a user like me to have up-to-date code version without creating a fork and publishing/tracking it myself?

**Comment by acjh** [comment]
[`1.0.0-preview1-28086`](https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR/1.0.0-preview1-28086) was published 5 hours ago.

**Comment by ivankarpey** [comment]
@acjh thanks

**Comment by ivankarpey** [comment]
@acjh Interesting that link is correct, however, when trying to find this package in [myget gallery](https://dotnet.myget.org/gallery/aspnetcore-dev), it's failed to do that.

**Comment by acjh** [comment]
Type "SignalR" in the search box, and then click on "[Microsoft.AspNetCore.SignalR](https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR)".

**Comment by ivankarpey** [comment]
@acjh Yes, but the version you link in your last comment is 2.1-preview and it's month old.

**Comment by acjh** [comment]
Scroll down. MyGet sorts it by Semantic Versioning names.

**Comment by ivankarpey** [comment]
@acjh Thanks, got it now.

**Comment by BrennanConroy** [comment]
2.1.0-* packages have now been removed from the dev feed, should make nightly builds more discoverable :)
