### ISSUE TITLE
Hub connection filter

### ISSUE THREAD

**Issue by AndreiGorlov** [aspnet/SignalR#1305]
Is it possible to block/allow connections to the hub only from specific remote addresses?

**Comment by anurse** [comment]
You could probably do this with custom Authorization policies: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies

Once you have a custom policy that only allows access based on IP address, you should be able to specify the name of that policy in the `Authorize` attribute.

Note that when behind a proxy (including IIS/ANCM) the remote address will likely be the address of the proxy.

**Comment by AndreiGorlov** [comment]
Can't figure out how to retrieve remote address inside AuthorizationHandler<>.HandleRequirementAsync(...), AuthorizationHandlerContext.Resource field == null :confused:

>Note that when behind a proxy (including IIS/ANCM) the remote address will likely be the address of the proxy.

Already solved with
```
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor
});
```

**Comment by anurse** [comment]
> Can't figure out how to retrieve remote address inside AuthorizationHandler<>.HandleRequirementAsync(...), AuthorizationHandlerContext.Resource field == null 😕

Hrm, unfortunately I'm not super familiar with the policy handler APIs. Maybe @Tratcher or @blowdart have some advice on how to use the Remote IP Address in the policy.

> Already solved

Cool, glad to hear that :)

**Comment by blowdart** [comment]
MVC passes through an MVC specific Context which gives you access to the HttpContext which contains the client address. Presumably SignalR does/could/should do the same thing

**Comment by blowdart** [comment]
MVC passes through an MVC specific Context which gives you access to the HttpContext which contains the client address. Presumably SignalR does/could/should do the same thing

**Comment by anurse** [comment]
Ah, gotcha. Ok. Let's leave this open to track doing something there. @BrennanConroy do you have some idea of where we'd put this context? We'd probably just use the existing `ConnectionContext`

@AndreiGorlov as a workaround, until we get that figured out and merged (which isn't likely to happen for Preview 1 at this point, unfortunately), you can always put a middleware in front of SignalR that checks the remote IP Address and the Path and sends a 401 if the Path matches the Hub and the IP Address is not in the allowed set.

**Comment by BrennanConroy** [comment]
We have the `GetHttpContext()` method on `ConnectionContext`

**Comment by anurse** [comment]
Right, but is the `ConnectionContext` provided to Authorization policies when we invoke them?

**Comment by BrennanConroy** [comment]
Oh I see, so this issue https://github.com/aspnet/SignalR/issues/676?

**Comment by anurse** [comment]
Yep. Closing this in lieu of that.
