### ISSUE TITLE
Inject service into Hub

### ISSUE THREAD

**Issue by AlexBokhankovich** [aspnet/SignalR#1306]
Is there a way to inject service into hub? I need to provide my Hub access to one of my services instantiated by Autofac container. How can I inject that service into hub? I've found no examples for this..

**Comment by davidfowl** [comment]
Yes, you just need to take the dependency in the constructor. If you're not familiar with ASP.NET dependency injection I suggest you start here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection.

**Comment by AlexBokhankovich** [comment]
@davidfowl thank you, this works like a charm. I was a little bit confused by MapHub<T>() method, so I thought just adding a constructor will not be enough.

**Comment by anurse** [comment]
@AlexBokhankovich Yeah, even though you use MapHub, we use DI to activate the Hub.
