### ISSUE TITLE
Move SignalR distribution to Bower instead of NPM to better integrate with ASP.NET Core

### ISSUE THREAD

**Issue by jonathanperis** [aspnet/SignalR#1307]
Hi!,

I was following the SignalR tutorial to implement it in ASP.NET Core, and I came across as ASP.NET Core does not have a good integration with NPM, the practically manual process, of installing the package at the root of the project, paste the .min.js file from SignalR and put it inside the wwwroot so I can reference it on my pages. Why not distribute ASP.NET Core SignalR through Bower, which already has a good integration with ASP.NET Core projects, including the package targeting file into wwwroot by default? Sounds like a great idea to me.

**Comment by iboshkov** [comment]
Probably because bower is deprecated and could stop being maintained at any point, no point in adding bower integration when bower itself warns users using it that it's deprecated.

**Comment by anurse** [comment]
As noted by @iboshkov , Bower itself has been deprecated, so we'll be using NPM (with support for Yarn) moving forward, as [recommended by the Bower developers](https://bower.io/blog/2017/how-to-migrate-away-from-bower/)
