### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by samcov** [aspnet/SignalR#1309]
I've looked everywhere and can't seem to find a roadmap for the release of SignalR.

To be frank, I don't care what it looks like, however, we need this information for product planning purposes, mostly related to getting off of the full framework and moving everything to core.

**Comment by anurse** [comment]
SignalR is coming in the 2.1 release of ASP.NET Core, which is targeted at Q1/Q2 2018 (see the ASP.NET Roadmap here: https://github.com/aspnet/Home/wiki/Roadmap)

**Comment by samcov** [comment]
Thanks, I see it's quite a ways off, but that clears up the decision making for us.

**Comment by samcov** [comment]
Just wanted to say that we re-evaluated our decision and decided to start our project using core.

Conversion wasn't difficult, but tedious because of the changes, but it was well worth it, this version makes a LOT more sense, IMO.

**Comment by anurse** [comment]
Glad to hear it! Please let us know if you run in to issues! We want to get the core SignalR scenarios up and running ASAP.
