### ISSUE TITLE
SignalR social weather sample is giving 1006 websocket error for both C# and json client

### ISSUE THREAD

**Issue by yackmurali** [aspnet/SignalR#1310]
Both C# and json client were not able to connect to a server in same machine. It is giving the error 1006

Status: WebSocket closed. Reason: 1006
WebSocket connection to 'ws://localhost:59619/weather/ws?formatType=json' failed: Error during WebSocket handshake: Unexpected response code: 404
document.addEventListener @ (index):71
:59619/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

But the same client got connected to socialweather server in azure site and getting response.

what we need to do to correct the problem.

**Comment by BrennanConroy** [comment]
What OS are you running the server on? Is it behind a proxy like IIS?

**Comment by yackmurali** [comment]
I am running on windows 10.
How can i make sure it is not running behind the proxy.

**Comment by yackmurali** [comment]
Also socket sample is working without any problem

**Comment by BrennanConroy** [comment]
Looked into it, and the sample is out of date, it no longer works.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/aspnet/SignalR/commit/4203540cb07d446ff7a32d0973846b32e2ce450b
