### ISSUE TITLE
npm aspnet/signalr-client has broken dependency

### ISSUE THREAD

**Issue by rrogahn** [aspnet/SignalR#1314]
Getting an error on aspnet/signalr-client in VS 2017.  It requires msgpack5 version 3.6.0 that is no longer available.

**Comment by moozzyk** [comment]
```
npm install msgpack5@3.6.0
npm WARN tmp@1.0.0 No description
npm WARN tmp@1.0.0 No repository field.

+ msgpack5@3.6.0
updated 1 package in 1.202s
```

**Comment by rrogahn** [comment]
derp. thanks.

**Comment by rrogahn** [comment]
![image](https://user-images.githubusercontent.com/14827593/35080571-45d33072-fbc3-11e7-9b3f-697ecce5f30a.png)

Must be a VS error.  Builds fine.
