### ISSUE TITLE
Detect availability of transport dependencies on client and server and disable them automatically

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1317]
We should consider how to detect WebSocket availability on the server and automatically disable the transport when the server can't support WebSockets.

This would depend on aspnet/Hosting#1241 since we can't tell if the server will support it from the application without detecting the specific name of the server (and OS version, etc.)

We should also do similar detection on the TS client, detecting `WebSocket` and `EventSource` types. In the .NET client we should detect Windows 7 (non-`netcoreapp2.1`) where `ClientWebSocket` will fail.

**Comment by muratg** [comment]
We need to check IHttpWebSocketFeature when generating negotiate response.

**Comment by anurse** [comment]
I'm expanding this issue to cover the client too. Editing the description and renaming. The necessary changes for the server are starting to land

**Comment by anurse** [comment]
* On JS Client this is just about checking for `typeof WebSocket !== "undefined"` (and the same for `EventSource`) to determine if the transports are available and skip them if they aren't
* On the .NET Server side we just need to look for `IHttpWebSocketFeature` when generating the `/negotiate` response, if it's not there, just don't include WebSockets.
