### ISSUE TITLE
add Authroization header in request

### ISSUE THREAD

**Issue by mutasemhidmi1133** [aspnet/SignalR#1320]
please how can i add authorization header in request when calling it from front end i mean how to add it for the hub connection ?

**Comment by mutasemhidmi1133** [comment]
please note than i'm using alpha 2

**Comment by BrennanConroy** [comment]
I'm assuming you're using the TS/JS client.

You can create your own HttpClient and set headers inside there. Then pass the HttpClient to the HubConnection via the options. One thing to note is that websockets don't support headers in the TS/JS client, so you'll have to use the query string instead.

In the newer nightly builds the client now has an accessToken option which will set the "Authorization" header for ServerSentEvents and LongPolling, and set the query string "signalRTokenHeader" in WebSockets

**Comment by mutasemhidmi1133** [comment]
thanks for your reply, regarding the above i have concern if it would be secure to pass the Authorization like this ?

**Comment by anurse** [comment]
> i have concern if it would be secure to pass the Authorization like this ?

You mean via the query string? The query string and the Authorization headers are both equivalently secure. The only security issue with query string is that it appears in the address bar, which is not a concern for WebSockets since the URL never appears in the address bar. Otherwise, the query string and headers and both sent the same way (in the HTTP header).

Do remember that the **only secure way** to transmit Authorization data is over HTTPS.

**Comment by mutasemhidmi1133** [comment]
@anurse so the query string is passed through IHubConnectionOptions ? sorry but i'm new to SignalR i would be grateful if you have an example regarding this.

**Comment by mutasemhidmi1133** [comment]
@anurse i'm using Typescript by they way

**Comment by anurse** [comment]
You pass the query string in when specifying the URL of the hub, it just goes on the end: `new signalR.HubConnection('/myhub?signalRTokenHeader=[...]')`

**Comment by mutasemhidmi1133** [comment]
i'm getting unauthorized when i did the below connection, note that i have the Authorize attribute on the hub class in the backend code and i'm using identityserver4
let connection = new HubConnection(HubUrl.PATIENT_URL+
      "?signalRTokenHeader=eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ2M2FlNWZiMTExNjlhMTMwMDI2YWFiNGVhOGVkZDNjIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MTYzNzQzNDIsImV4cCI6MTUxNjQ2MDc0MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMS9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6ImNsaWVudCIsInN1YiI6ImRhM2RlMTJiLTZjYzgtNGZlZC1iOWU3LTI3ZmYyY2Y3NDVjYSIsImF1dGhfdGltZSI6MTUxNjM3NDM0MiwiaWRwIjoibG9jYWwiLCJzY29wZSI6WyJhcGkxIl0sImFtciI6WyJwd2QiXX0.cigQxww7Q8AeovTF0fDflZQ0uiLUBRVPZcfLU9-ZFx8lWw5vK9UiPDWCa_d8a_kp7UjlhvzPIJnm3gsqWJ9fCiz-u-8wfzsMXpFK_6nlyvtYAH0k3tlYKBXBgYZwlX2RrjMGEnefLaQMQZdU8ERVCWnh94l4R5wJJ5heeeMAvTQIJQmGYyBNN5XMH8HotHSMrNXJVCo4rCehi16LyHnq-o3zI9aRm-wvmqRfVLRDXCWcT4aoDUhNTsm0kWdSSpEnmsYjsBSVA4iIucxOuEG5GI3xcmFf3qp9plFYJ7BgVMTos00TShOo-0qRtcWFaeUWYpE_pnF7WQhTWRKski4BFg");
    connection.start()

**Comment by anurse** [comment]
Ah, you actually need to handle the querystring parameter yourself. Fortunately, you can plug in to the existing JwtBearer component and just change where it reads the token, rather than having to do the authentication yourself. You just need to handle the `OnMessageReceived` event in the JwtBearer authentication provider and have it read the token from the query string. See the [JwtSample](https://github.com/aspnet/SignalR/blob/dev/samples/JwtSample/Startup.cs#L36) sample in this repo for some information.

We'll be looking at improving this before RTM, or at least having a clearly-documented sample.

**Comment by mutasemhidmi1133** [comment]
@anurse i did the above and i'm still getting unauthorized services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options => {
                //signalr
                options.Events = new JwtBearerEvents {
                    OnMessageReceived = context => {
                        var signalRTokenHeader = context.Request.Query["signalRTokenHeader"];
                        if (!string.IsNullOrEmpty(signalRTokenHeader)) {
                            Console.WriteLine(signalRTokenHeader);
                            context.Token = signalRTokenHeader.FirstOrDefault();
                        }
                        return Task.CompletedTask;
                    }
                };
                // signlar
                options.Authority = "http://localhost:5001/";
                options.Audience = "api1";
                options.RequireHttpsMetadata = false;
            });
            services.AddSignalR(options => {
                options.JsonSerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            });

**Comment by mutasemhidmi1133** [comment]
@anurse a stupid mistake in Configure method in startup class i was using authentication after using signalr it's fixed now thanks, appreciated.

**Comment by anurse** [comment]
No problem! Glad you got the issue resolved. I'm going to close this now, feel free to re-open if the issue reoccurs.

**Comment by embryologist** [comment]
I am having the same issue even with providing the token in the query string,
I am using JWT for my app and it is working properly with all my API controllers using the auth attribute `[Authorize]`, however, it’s not working with SignalR hub

```typescript
(this.hubConnection = new HubConnectionBuilder()
          .withUrl(
            BackEndConfig.baseUrls.hub +
              hubEndPoit +
              '?signalRTokenHeader=' +
              this.authService.getToken(),
          )
          .configureLogging(signalR.LogLevel.Critical)
          .build())
```

server-side,

```c#
            services.AddAuthentication(options => {
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddJwtBearer(jwtBearerOptions => {
                    jwtBearerOptions.RequireHttpsMetadata = false;
                    jwtBearerOptions.SaveToken = true;
                    jwtBearerOptions.TokenValidationParameters = new TokenValidationParameters() {
                        LifetimeValidator = (before, expires, token, param) => {
                                return expires > DateTime.UtcNow;
                            },
                            ValidateAudience = false,
                            ValidateIssuer = false,
                            ValidateActor = false,
                            ValidateLifetime = true,
                            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["BearerTokens:Key"]))
                    };
                    jwtBearerOptions.Events = new JwtBearerEvents {
                        OnAuthenticationFailed = context => {
                                var logger = context.HttpContext.RequestServices.GetRequiredService<ILoggerFactory>().CreateLogger(nameof(JwtBearerEvents));
                                logger.LogError("Authentication failed.", context.Exception);
                                Console.WriteLine("Authentication failed.");
                                return Task.CompletedTask;
                            },
                            OnTokenValidated = context => {
                                var tokenValidatorService = context.HttpContext.RequestServices.GetRequiredService<ITokenValidatorService>();
                                return tokenValidatorService.ValidateAsync(context);
                            },
                            OnMessageReceived = context => {
                                var accessToken = context.Request.Query["signalRTokenHeader"];
                                // If the request is for our hub...
                                var path = context.HttpContext.Request.Path;
                                if (!string.IsNullOrEmpty(accessToken)) {
                                    // Read the token out of the query string
                                    context.Token = accessToken;
                                }
                                return Task.CompletedTask;
                            },
                           OnChallenge = context => {
                                var logger = context.HttpContext.RequestServices.GetRequiredService<ILoggerFactory>().CreateLogger(nameof(JwtBearerEvents));
                                logger.LogError("OnChallenge error", context.Error, context.ErrorDescription);
                                Console.WriteLine("Authentication failed. {0}, {1}", context.Error, context.ErrorDescription);
                                context.Response.StatusCode = 401;
                                return Task.CompletedTask;
                            }
                    };
                });
```
