### ISSUE TITLE
Visual Studio does not always shut down IIS worker process when stopping debug 

### ISSUE THREAD

**Issue by wpitallo** [aspnet/SignalR#1323]
Visual Studio does not always shut down IIS worker process when stopping debug. Even though debugging has detached the worker process stays running in the background. Using VS 2017.5 .Net Core 2

**Comment by anurse** [comment]
Is this an issue you're seeing when using SignalR specifically? This repo is for SignalR issues. To report Visual Studio issues use https://developercommunity.visualstudio.com/

**Comment by wpitallo** [comment]
Ok cool thanks, at the moment it seems specific to SignalR

**Comment by anurse** [comment]
Are you using full IIS or IIS Express? (cc @davidfowl)

**Comment by wpitallo** [comment]
IIS Express
