### ISSUE TITLE
Which set of samples are best to use?

### ISSUE THREAD

**Issue by samcov** [aspnet/SignalR#1326]
There are samples in this repo, and there are samples in SignalR-samples repo(https://github.com/aspnet/SignalR-samples).

Which samples are the suggested ones to use?

**Comment by BrennanConroy** [comment]
Both. The ones in this repo are more up to date with the latest dev version, but they are also generally simpler samples. The SignalR-samples repo has slightly more complicated samples that are built on top of alpha2

**Comment by samcov** [comment]
Thanks!!!
