### ISSUE TITLE
return data from a connection.invoke

### ISSUE THREAD

**Issue by willthiswork89** [aspnet/SignalR#1327]
I've googled and tried to search issues as well as look at documentation but i'm at a loss... 

If i want to send back data from a connection.invoke("send", data) how do i do that?

Basically i need a way to ensure that the data sent was accepted and was not "bad". Something like

connection.invoke("send", badData).finally((result) => { if(!result.success) { alert(result.message); } });

**Comment by BrennanConroy** [comment]
Something like the below should work
```
connection.invoke("send", badData)
    .then((result) => {})
    .catch((reason) => {});
```

**Comment by muratg** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
