### ISSUE TITLE
IConnectionManager.GetHubContext<T>

### ISSUE THREAD

**Issue by CarlosLanderas** [aspnet/SignalR#133]
Hello. On the previous asp.net signalr core deprecated repository, I could use **IConnectionManager** registered by services.AddSignalr(), to recover the Hub Context inside a controller. 

source: [IConnectionManager.cs](https://github.com/aspnet/SignalR-Server/blob/dev/src/Microsoft.AspNetCore.SignalR.Server/Infrastructure/IConnectionManager.cs)

For example:

` connectionManager.GetHubContext<MyHub>().Clients.All.notify(data);`

I have been looking at the repository and I have not found anything related with this. Maybe I am not looking in the right place or maybe it is not implemented yet. Do you plan on having this feature in this new repository?.

Thanks you very much.

**Comment by moozzyk** [comment]
Have you tried resolving `HubContext` from the DI container (either by calling GetRequiredServices or by taking it as the ctor parameter similarly to how [HubEndpoint](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs#L20) does it)?

**Comment by CarlosLanderas** [comment]
I was going to answer right now because I found it some minutes ago:

```
 public RealtimeController(IHubContext<Chat> chatHub)
        {
            this.chatHub = chatHub;
        }
     
        [HttpPost, Route("[action]/{message}")]
        public void Send(string message)
        {
            chatHub.Clients.All.InvokeAsync("Send", message);
  }
```


It is working perfect!. Thankyou @moozzyk
