### ISSUE TITLE
RedisHubLifetimeManager Self Referencing Loop

### ISSUE THREAD

**Issue by los93sol** [aspnet/SignalR#1332]
I am trying to use redis scaleout with SignalR and having some issues.  I have a few models that I return to the clients that have self referencing loops in them.

With just SignalR I simply did this in my startup and it resolved the issue....
  services.AddSignalR(options => { options.JsonSerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore; });

I have now added Redis into the mix and my serialization settings are no longer being obeyed.  I took a look at the RedisHubLifetimeManager and it appears that when I call Clients.All.InvokeAsync..... from my hub it is being proxied through to RedisHubLifetimeManager.PublishAsync where the private readonly serializer is taking over from there which sort of explains the issue, however, I was under the impression that the RedisHubLifetimeManager shouldn't actually be calling the clients, rather it should be gathering all of the connections and dispatching them back....not totally sure on this though.

Any suggestions or pointers are appreciated as I'm currently at a standstill with no real idea how to properly resolve this issue.

**Comment by los93sol** [comment]
I was able to get things to serialize by tagging the model with JsonIgnore, but this is far from ideal and doesn't feel like the correct way to handle it for my specific scenario

**Comment by anurse** [comment]
Yeah, that's a tricky one. We use JSON to serialize between two nodes over Redis but we don't expose those serializer settings. We should look at doing that. Glad you were able to get past the immediate issue. We'll look at making this better.

**Comment by anurse** [comment]
What kind of payload are you sending through SignalR? You should generally avoid sending anything other than plain data-transfer objects (with no reference loops) via SignalR.

**Comment by los93sol** [comment]
In my case they are EF models.  I know it’s best to use view models but my payload does not contain any sensitive data so no reason to add the overhead to convert it

**Comment by davidfowl** [comment]
This is going to be solved by https://github.com/aspnet/SignalR/issues/1800
