### ISSUE TITLE
HubConnectionContext User.Identity Empty

### ISSUE THREAD

**Issue by AESTechnology** [aspnet/SignalR#1335]
Hello, first i would like to say sorry for posting a question here i know its not proper form and id hate to be guilty of offending any of the contributors that i have followed and respected for several years now. but other issues in this repo have come very very close to solving my issue and i feel it may be the place where the right people are around to answer (if i am wrong id be happy to post somewhere else per suggestion)
Preface over tldr

I am implementing the chatsample in my dot net core 2 webapi application and am using JWT for authentication. and using aspnet identity. i cant seem to figure out why hubconnection.user.identity does not contain any of my claims as my controller retrieve them without any issues. It seems that when others have come across this they simply register IHttpContextAccessor and inject it into the hub, however i can't seem to accomplish this either. 

is there something obvious i am missing? where exactly can i give my claims to the hubconnection.user.identity?

hopefully this makes sense im very new to actually posting questions.
Thank You

edit: here is a stack question i posted if that ends up being of any help https://stackoverflow.com/questions/48408148/unable-to-inject-ihttpcontextaccessor

**Comment by anurse** [comment]
I see you closed the issue, did you resolve the problem?

Are you able to provide a link to your Startup code and the Hub? My first thought is that you don't have authentication properly registered or you didn't put the `[Authorize]` attribute on your hub.

**Comment by AESTechnology** [comment]
Hi @anurse thanks for the reply. I closed the issue because I don't want to clog up your open issues and I think my question was actually just incorrect.

if you are still interested, you are correct, I was missing the [authorize] attribute.
currently my application is in angular and I am authenticating using JWT. however I am still using identity. i'm having a hard time understanding how i can authenticate a user from the client-ts
i see that @moozzyk checked in a sample for how to handle this on the bearer configuration (https://github.com/aspnet/SignalR/blob/dev/samples/JwtSample/Startup.cs#L49-L62)
but I'm confused on how I'm actually supposed to send the auth token from the client in typescript.

sorry if this is something obvious.
also I opened a new one after closing this one because it seemed more relevant to my issue
https://github.com/aspnet/SignalR/issues/1336
I can close that if this discussion belongs here instead?

**Comment by BrennanConroy** [comment]
In the same sample you can look at the JS client usage https://github.com/aspnet/SignalR/blob/dev/samples/JwtSample/wwwroot/index.html#L71

**Comment by AESTechnology** [comment]
thank you so much for your help! I've closed the issues as they are answered. my solution still isn't working.
here is a stack question I've created in case anyone finds it useful
https://stackoverflow.com/questions/48429656/authenticating-signalr-hub-with-jwt
