### ISSUE TITLE
Client doesn't receive messages when sent to specific connection ID.

### ISSUE THREAD

**Issue by antoinne85** [aspnet/SignalR#1341]
### Title
Client doesn't receive messages when sent to specific connection ID.

### Functional impact
I am unable to send messages to a specific client through an `IHubContext<T>`, even if I am in possession of their `connectionId`. 

More specifically, the following C# code will result in JavaScript clients both receiving and executing code:
```
await _hub.Clients.All.SendAsync("receiveMessage", "This is a test message to everyone.");
```

However, the following C# code will not result in messages being received by JavaScript clients:
```
var possibleMultipleUsers = _hub.Clients.Users(new List<string> {connectionId});
await possibleMultipleUsers.SendAsync("receiveMessage", "This is a test message to specific clients.");

var singleUser = _hub.Clients.User(connectionId);
await singleUser.SendAsync("receiveMessage", "This is a test message to exactly one client.");
```

### Minimal repro steps
Getting everything set up can be a touch time consuming, so I've created a sample repository that includes a minimum setup.
1. Clone the repository at [antoinne85/SignalRConnectionIdIssue](https://www.github.com/antoinne85/SignalRConnectionIdIssue).
1. Open a terminal and navigate to the `/SignalRConnectionIdIssue` folder.
1. Execute `npm install` to install the `signalr-client` package.
1. Open the solution and run the project.
1. In your browser, navigate to `/home/index`.
1. Open the developer tools and monitor the console output. 
1. Click the 'Test' button.

If you're uncomfortable with this approach, you can:
1. Override the `OnConnectedAsync` method in a hub to track connection IDs.
1. Connect a client, keeping track of their assigned connection ID.
1. With the client still connected, attempt to send them a message using each of the three techniques listed in the *Functional Impact* section.

##### Explanation
The `IssueHub` has an override for `OnConnectedAsync` that passes back the `connectionId` by calling a `setId` method on the client.

Clicking the 'Test' button makes a GET request that is received by the `TestController.Get` method. This request includes the `connectionId` that was passed back when the client first connected.

`TestController.Get` then attempts to send the three messages using different techniques. The first is sent to all connected clients, the  second two attempt to send a message to the single client that made the request.

### Expected result
The console should contain all three messages:
* `"This is a test message to everyone."`
* `"This is a test message to specific clients."`.
* `"This is a test message to exactly one client."`

### Actual result
The console only contains `"This is a test message to everyone."`

### Further technical details
The web application is using `Microsoft.AspNetCore.SignalR` version `1.0.0-preview1-28153` from `https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json`.

The JavaScript client is using `signalr-client` version `1.0.0-preview1-28127` from `https://dotnet.myget.org/f/aspnetcore-dev/npm`.

**Comment by BrennanConroy** [comment]
You are wanting `_hub.Clients.Client(connectionId)` and `_hub.Clients.Clients(new List<string> {connectionId})`.

User is for the username associated with the connection if they have one.

**Comment by antoinne85** [comment]
Thanks. I'll give that a try this evening. I'll close this out afterwards. 

For my future self, is there already documentation in the works that I should have referenced for this kind of thing or is that on hold until the code finalizes some more?

**Comment by BrennanConroy** [comment]
There are no docs for this version, however you can take a look at the old docs and often times there is the exact same thing or something similar in this project. https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#callfromhub

**Comment by antoinne85** [comment]
Thanks, @BrennanConroy. You 100% nailed it.
