### ISSUE TITLE
AddSignalR failing in .NET Core 2.0.

### ISSUE THREAD

**Issue by jceddy** [aspnet/SignalR#1348]
I'm getting the following exception when I call service.AddSignalR() in my ConfigureServices method:

> System.TypeLoadException: 'Method 'StartAsync' in type 'Microsoft.AspNetCore.Sockets.SocketsApplicationLifetimeService' from assembly 'Microsoft.AspNetCore.Sockets, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'

Is this due to a bug, or due to me doing it wrong?

**Comment by BrennanConroy** [comment]
Very unlikely a bug. I'm guessing its a mismatch of assemblies/runtime.

What version of dotnet are you running? What SignalR assembly version are you using?

**Comment by jceddy** [comment]
.NET Core 2.0 with SignalR 1.0.0-preview1-24937

**Comment by BrennanConroy** [comment]
SignalR 1.0.0-preview1-* will only work with .NET Core 2.1, if you want to use .NET Core 2.0 you can use the 1.0.0-alpha2 SignalR package, or upgrade to .NET Core 2.1 and use the preview1 builds of SignalR

**Comment by jceddy** [comment]
Makes sense, sorry to bug y'all!
