### ISSUE TITLE
Consider allowing arbitrary metadata/extensions to be added to protocol messages

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1350]
A number of features we're thinking of adding in the future would benefit from having arbitrary metadata/extensions be allowed in protocol messages. We should update the spec (and the code) to accept these metadata. Most importantly, we should also define the behavior of clients/servers that do not understand particular metadata and set an expectation on how this would be treated.

**Comment by anurse** [comment]
We're going to do simple `string -> string` "headers" for now, in both JSON and MsgPack.

**Comment by davidfowl** [comment]
We can close this right?
