### ISSUE TITLE
Allow extension of Hub invocation pipeline

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1351]
Currently `HubEndpoint<THub>` is soley responsible for discovering and invoking Hub methods. We should consider adding an abstraction to allow users to customize the discovering/invocation behavior without having to replace the whole endpoint.

**Comment by muratg** [comment]
@anurse will be designing this.

**Comment by muratg** [comment]
Tracking the work in: https://github.com/aspnet/SignalR/issues/924
