### ISSUE TITLE
Suggestion - Change default PollTimeout for LongPolling

### ISSUE THREAD

**Issue by gary-holland** [aspnet/SignalR#1357]
For the LongPolling transport I've noticed the default timeout is set to 110 seconds.  

The issue I had is that CloudFlare have a default timeout of ~100 seconds ([details](https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524-A-timeout-occurred)) which was causing my client to error intermittently due to CloudFlares timeout.  

I am aware that this can be overridden in the configure section using the following (which has resolved issue for me).

```
app.UseSignalR(routes =>
	{
		routes.MapHub<RemoteAgentHub>("remoteagent", options =>
		{
			options.LongPolling.PollTimeout = TimeSpan.FromSeconds(60);
		});
	});
```

My suggestion is that you drop the default from 110 seconds to something below 100 seconds, as the current configuration means that everyone hosting a site behind Cloudflare will encounter this issue with the default configuration.

**Comment by anurse** [comment]
I'm not sure what drove the decision to use 120 seconds, it may have been what we used for the previous versions of SignalR, so we'll need to look in to the reasons behind that, but I agree, it would be good if we can pick a default that doesn't cause CloudFlare to timeout, since it is so common. Thanks for the report!

**Comment by mikaelm12** [comment]
> I'm not sure what drove the decision to use 110 seconds

Wasn't it because of the default timeout in IIS being like 120 seconds? I remember something like that

**Comment by anurse** [comment]
Ah, ok, that makes sense. I think 90 or 100 seconds would be reasonable based on CloudFlare's limit. CloudFlare is a fairly common proxy to use.

**Comment by davidfowl** [comment]
Sounds fine.

**Comment by mikaelm12** [comment]
Done: e214d5cdfac12475f0d5c7a1b6a5e063a61870e1
Thanks for the suggestion @gary-holland
