### ISSUE TITLE
@aspnet/signalr-client Microsoft Edge and IE bug

### ISSUE THREAD

**Issue by SkeletonSkelettron** [aspnet/SignalR#1358]
Hi
I have **@aspnet/signalr-client** in Angular5 application. webpack version is 3.10.0
The app fails to run in **Edge** and **IE**, problem in both of them is same: 

(console log)
SCRIPT1006: Expected    ')'
signalr-client-1.0.0-alpha2-final.min.js (1,3798)

There is no problem in Chrome and FF

**Comment by BrennanConroy** [comment]
Edge/IE use a client that was complied for ES5
Here is an example of what you can do in the alpha builds
https://github.com/aspnet/SignalR-samples/blob/master/StockTickR/StockTickRApp/wwwroot/index.html#L33-L40

Note: In the latest dev bits this is no longer required

**Comment by SkeletonSkelettron** [comment]
Thanks Brennan
