### ISSUE TITLE
Will new SignalR use a new AspNetSynchronizationContext per call?

### ISSUE THREAD

**Issue by xperiandri** [aspnet/SignalR#136]
In a port of legacy SignalR there is an issue when HttpContext is not synchronized between SignalR and ASP.NET. And worse is that secvice scopes preserved per connection and not per hub instance which led to issues.

Is it fixed in this version?

**Comment by moozzyk** [comment]
SignalR now creates a new scope for each hub method call: https://github.com/aspnet/SignalR/blob/3d5fc9493aa418ac299250dcd52c8bf942de3ee3/src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs#L242

**Comment by davidfowl** [comment]
Also there is no sync context in asp.net core.

**Comment by xperiandri** [comment]
Does this mean that method calls occur sequentially within a single connection?
I mean I can't realize how scope works. Is there any article that explains this topic?

**Comment by davidfowl** [comment]
@xperiandri I'm not sure what you're asking. Are you wanting to know if 2 hub methods can be called in parallel?

**Comment by xperiandri** [comment]
I mean what happens when 2 methods calls comes one right after the other?
Imagine that first call comes and takes 1 second. The scope is created for it.
While first call didn't finished the second call comes. The second scope is created for the second call.
Are this scopes intersect somehow?
What is the isolation boundary between this scopes?
I understand that by default scope is created per HTTP request and middleware saves scope services into HttpContext.
But how does this scope works in SignalR within the same HttpRequest?

**Comment by xperiandri** [comment]
From my experiment with `SignalR-Server` sources just wrapping a hub method call into a scope didn't help me to fix multi-threading issue in EF.
`The connection was not closed. The connection's current state is connecting.`

``` C#
protected override async Task OnReceived(HttpRequest request, string connectionId, string data)
{
...
    MethodDescriptor methodDescriptor = _manager.GetHubMethod(descriptor.Name, hubRequest.Method, parameterValues);

    if (methodDescriptor == null)
    {
        // Empty (noop) method descriptor
        // Use: Forces the hub pipeline module to throw an error.  This error is encapsulated in the HubDispatcher.
        //      Encapsulating it in the HubDispatcher prevents the error from bubbling up to the transport level.
        //      Specifically this allows us to return a faulted task (call .fail on client) and to not cause the
        //      transport to unintentionally fail.
        IEnumerable<MethodDescriptor> availableMethods = _manager.GetHubMethods(descriptor.Name, m => m.Name == hubRequest.Method);
        methodDescriptor = new NullMethodDescriptor(descriptor, hubRequest.Method, availableMethods);
    }

    using (var scope = _serviceScopeFactory.CreateScope())
    {
        var hub = CreateHub(request, descriptor, connectionId, throwIfFailedToCreate: true);

        await InvokeHubPipeline(hub, parameterValues, methodDescriptor, hubRequest)
            .ContinueWithPreservedCulture(task => hub.Dispose(), TaskContinuationOptions.ExecuteSynchronously);
    }
}
```

**Comment by davidfowl** [comment]
The scopes are completely independent. What's the multithreadimg issue? There's no guarantee that hub methods can't overlap. What assumptions are you making in your code.

**Comment by moozzyk** [comment]
SignalR-Server (which indeed [have issues with scopes](https://github.com/aspnet/SignalR-Server/issues?q=is%3Aissue+scope+is%3Aclosed))  is a different code base which was not used to create this version so it's not relevant how it worked.

**Comment by xperiandri** [comment]
I got it. I was not attentive enough.
@moozzyk, you should have pointed me to this line https://github.com/aspnet/SignalR/blob/3d5fc9493aa418ac299250dcd52c8bf942de3ee3/src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs#L244
