### ISSUE TITLE
MsgPack Protocol Tidy-up

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1366]
There are some things in the MsgPack Protocol I want to revisit:

1. It uses Protobuf's [`varint`](https://developers.google.com/protocol-buffers/docs/encoding#varints) for framing the protocol. This does save some bytes (only generally 1-2 bytes though), but it seems simpler to just use MsgPack's own [`bin`](https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family) type. This would allow clients to use the existing MsgPack decoding libraries they are using and would not require an additional decoder layer. It may also be possible to avoid the outer framing entirely, but it would require the parser to be able to pause and resume parsing when more data is available. The end of a message is clearly defined in MsgPack (unlike ProtoBuf) but the exact byte length of a message isn't known until the end of parsing.

2. MsgPack-CLI encodes DateTime as a `uint 64` but MsgPack has a spec-provided type for DateTime (the `Timestamp` extension type). This appears to be a limitation of the library: https://github.com/msgpack/msgpack-cli/issues/246

3. I'm not sure I like how CompletionMessages are encoded using a "result type" enum. Not sure what I like better yet though. It's not bad, I just feel like introducing a new enumeration shouldn't be necessary.

4. In adding headers (#1350), I'm wondering if it might be better to use two nested arrays. Currently the entire message is a single array, where each array has the same first two items `[headers, type, ...`. I wonder if a better pattern would be for all messages to have the same high-level format: `[headers, type, payload]` where `payload` is an array specific to the type.

Sure I'll find more as I go though implementing #1350 :)

**Comment by anurse** [comment]
> Did you look at the existing implementation?

That's what I'm working with right now.

> Seems like this introduces more problems than it solves.

Why? `varint` requires custom parsing, using MsgPack itself wouldn't.

**Comment by davidfowl** [comment]
Don’t we need to know the size of the payload separately from the payload Itself. Initially we just read a long, but we switched a varint to save space. So we have a proof that there are parsers that would work if we made the change to be all message pack?

**Comment by anurse** [comment]
> It may also be possible to avoid the outer framing entirely

If you're talking about this part, I don't really disagree. But my initial plan was to use the `bin` type, which is fixed size and length-prefixed.

**Comment by anurse** [comment]
> Don’t we need to know the size of the payload separately from the payload Itself

Depends on how the parser works, but as I said, there are two parts to this: 1) Use MsgPack types for fixed-length parsing and 2) Consider removing fixed-length parsing altogether. (1) makes a lot of sense to me, since you only need a MsgPack parser (and just call it once recursively on the payload of the outer frame). (2) is more difficult, since it requires a stateful parser, and might not be worth it.

**Comment by davidfowl** [comment]
@anurse I wouldn't change anything for the sake of it until we find a benefit (like other clients are easier to write as a result)

**Comment by moozzyk** [comment]
> MsgPack-CLI encodes DateTime as a uint 64 but MsgPack has a spec-provided type for DateTime (the Timestamp extension type). This appears to be a limitation of the library: msgpack/msgpack-cli#246

See: https://github.com/aspnet/SignalR/issues/1058#issuecomment-341272873
