### ISSUE TITLE
@aspnet/signalr negotiation 404 (not found)

### ISSUE THREAD

**Issue by jacopozzo** [aspnet/SignalR#1370]
Hi,
Now, installing @aspnet/signalr from your registry, it cannot call negotiation correctly and i have the following message:
![image](https://user-images.githubusercontent.com/19947058/35558852-62978bf0-05a9-11e8-9629-3f78740f73eb.png)

my Startup.cs:

` public class Startup
    {
        public IConfigurationRoot Configuration { get; }

        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();

            Configuration = builder.Build();
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services
                         .AddMvc()
                         .AddJsonOptions(options => options.SerializerSettings.ContractResolver =
                             new DefaultContractResolver());

            services.AddSignalR();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseCors(
                builder => builder.AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials())
                    .UseDefaultFiles()
                .UseStaticFiles();
            #region old
            //app.UseMvc(routes =>
            //{
            //    routes.MapRoute(
            //        name: "default",
            //        template: "{controller=Home}/{action=Index}/{id?}");
            //});
            #endregion

            app.Use(async (context, next) =>
        {
            await next();

            if (context.Response.StatusCode == 404
                && !Path.HasExtension(context.Request.Path.Value))
            {
                context.Request.Path = "/index.html";
                await next();
            }
        });

            app.UseMvc();

            app.UseSignalR(cfg =>
            {
                cfg.MapHub<TestHub>("chat");
            });
        }`

my component.ts
`ngOnInit() {
        this.nick = window.prompt("What's your nickname:", "J4C0X92");

        this.hubConnection = new HubConnection("/chat");

        this.hubConnection.on('sendToAll', (nick: string, receivedMessage: string) => {
            const text = `${nick}: ${receivedMessage}`;
            this.messages.push(text);
        });
        
        
        this.hubConnection
            .start()
            .then(() => console.log('Connection started!'))
            .catch(err => console.log('Error while establishing connection :(',err));
        
    }`
Seems to be everything ok, but i don't know why client fails calling negotation.
Everything ran correctly before with @aspnet/signalr-client package, i only had the problem with ES5 in IE 11.

I'm using the following "backend" libraries:
` <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" />
  </ItemGroup>`

**Comment by jacopozzo** [comment]
I'm using the following "backend" libraries:
` <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" />
  </ItemGroup>`

**Comment by acjh** [comment]
`@aspnet/signalr` is the `preview1` build. You should use the same build for client and server.

You can add a [NuGet.Config](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/5e8d3336bb27d747036d8b66e6b82afe88037ad1/NuGet.Config) file to the same folder as your **.sln** file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="aspnetcore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by anurse** [comment]
I'll update the README to clarify this. The build/version numbers for the NPM module and the Server NuGet package should be aligned so you should always use the same build numbers. After the RTM 2.1 release, compatibility guarantees will be a little more flexible, but while we're developing things we make significant changes that require the client and server to be aligned.

Closing the issue on the assumption that updating the version will fix the issue. Please feel free to re-open or comment further if updating doesn't solve the issue!
