### ISSUE TITLE
Can't use SignalR Client for UWP App

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#1372]
When using the Nuget Package manager to try and bring in the alpha2 SignalR Client into a UWP app I get this error.

`Package restore failed. Rolling back package changes for 'UWPTest'`

**Comment by muratg** [comment]
@mikaelm12 for future reference: 
https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/

**Comment by mikaelm12** [comment]
![win10version](https://user-images.githubusercontent.com/4809660/36636577-2246b86c-197e-11e8-9b80-685bba9b5ae7.png)

Works if you set the min version to Win10 Fall Creators Update Build 16299
