### ISSUE TITLE
Deploying on IIS

### ISSUE THREAD

**Issue by msmolka** [aspnet/SignalR#1377]
Hello
I'm facing problem when deploying SignalR on IIS. (All is working with IIS Express and VS debug)
However when deployed on IIS the first connection is rejected. Server is even not hit.

I believe it can be related to OPTIONS verb which is somehow consumed on IIS.
I don't need CORS for this project. 
I wonder if it is any possibility to change that verb, to use GET/POST instead of OPTIONS  for initial connection.

**Comment by msmolka** [comment]
Sorry... I found the solution issue was wrong url resolution not options

**Comment by anurse** [comment]
We've also switched to using a `POST` request in Preview 1 anyway :)
