### ISSUE TITLE
@aspnet\signalR typescript - HttpConnection.ts

### ISSUE THREAD

**Issue by nickkhan** [aspnet/SignalR#1378]
I am trying to run the typescript client for signalR and connect to a Hub server running as a console app using .Net framework 4.6.1.

The code below is parsing content to a string and then tries to create an object of type INegotiateResponse. Problem is the case for the ConnectionId property as declared in the interface INegotiateResponse has an upper case 'C', while the one contained in the negotiateResponse object has a lower case 'C'. Therefore the connectionId is set to undefined.

Below is the interface definition from HttpConnection.ts
`interface INegotiateResponse {
    ConnectionId: string
    availableTransports: string[]
}`
https://github.com/aspnet/SignalR/blob/9482b4976e071207ba3fcc53027346404033afbb/client-ts/signalr/src/HttpConnection.ts#L86

Also createTransport method blows up,  because the  negotiateResponse.availableTransports array is undefined! also i do not see it in the unparsed negotiatePayload.content.

https://github.com/aspnet/SignalR/blob/9482b4976e071207ba3fcc53027346404033afbb/client-ts/signalr/src/HttpConnection.ts#L95

Package.json
    "@aspnet/signalr": "^1.0.0-preview1-28189",
    "@aspnet/signalr-protocol-msgpack": "^1.0.0-preview1-28189",

To reproduce,
1) Grab the repo from https://github.com/aspnet/SignalR/
2) Build everything in VS2017
3) create a hubconnection to a signalr hub 
` let hubConnection = new HubConnection("http://localhost/signalr");
  hubConnection.start().then(() => {
console.log("connected to hub");
 }).catch((error) => {
console.log(error);
});`

**Comment by nickkhan** [comment]
@PinpointTownes, @anurse please take a look at this issue.
#1378

**Comment by BrennanConroy** [comment]
How did you configure your Hub Endpoint on the server? Unless you mapped it to "/signalr" it wont work. "/signalr" was the old ASP.NET method for connecting to signalr hubs, but now you need to configure your hubs path via `MapHub<Hub>("/endpoint")`

**Comment by nickkhan** [comment]
here's my startup.cs for the signalR server
`        public void Configuration(IAppBuilder app)
        {
            GlobalHost.HubPipeline.AddModule(new ErrorHandlingPipelineModule());

            app.UseCors(CorsOptions.AllowAll);
            var hubConfiguration = new HubConfiguration();
            app.MapSignalR("/signalr", hubConfiguration);
        }`

**Comment by PinpointTownes** [comment]
Are you trying to use the SignalR Core client with a SignalR "non-Core" server? :neutral_face:

**Comment by nickkhan** [comment]
@PinpointTownes I was using signalr javascript client in a asp.net core angular web application. All was working well. I wanted to see if I could use the signalR typescript client instead. Shouldn't the core javascript/typescript be backwards compatible with non-core server?

**Comment by BrennanConroy** [comment]
No
https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/
>One of the consequences of this is that SignalR for ASP.NET Core is not compatible with previous versions of SignalR.

**Comment by PinpointTownes** [comment]
I'm not really familiar with the SignalR Core internals, but the changes in the hub protocol are so massive that I doubt mixing Core and non-Core SignalR clients/servers will ever work.

**Comment by nickkhan** [comment]
Oh geez, thanks @BrennanConroy  and @PinpointTownes  
the only other thing is, the signalR core clients/servers are still in alpha stages,  would you recommend using it in a production application?

**Comment by BrennanConroy** [comment]
Definitely not, we will only recommend it for production when the 2.1.0 release is out

**Comment by nickkhan** [comment]
ok thanks both @BrennanConroy  and @PinpointTownes.

**Comment by nickkhan** [comment]
FYI, for those trying to use signalR typescript client with a .net signalR server. you can use typed libraries for signalR(@types/signalr) and Jquery(@types/jquery)
Then create your client interfaces for your HubProxy and then you should be able to reference the client/hub methods from angular components.

**Comment by nahdarp** [comment]
> FYI, for those trying to use signalR typescript client with a .net signalR server. you can use typed libraries for signalR(@types/signalr) and Jquery(@types/jquery)
> Then create your client interfaces for your HubProxy and then you should be able to reference the client/hub methods from angular components.

Do you have any samples how this can be done? I am using Angular and wanted to connect SignalR hub running on .net framework 4.6.2.
