### ISSUE TITLE
react-scripts fails to package client

### ISSUE THREAD

**Issue by georgiosd** [aspnet/SignalR#1380]
I'm using the new React SPA rc1 and I get an error when trying to publish the project. The error references here: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Any ideas how to fix this?

**Comment by acjh** [comment]
Duplicate of #1299

**Comment by georgiosd** [comment]
Thanks @acjh - would be nice if this was fixed for good.

**Comment by anurse** [comment]
In the upcoming preview build, we compile the CommonJS format of the module (used by NPM) to ES5, so it should be compatible with these tools. I suggest trying with the latest preview package (which, by the way, has been **renamed**) using instructions here: https://github.com/aspnet/SignalR#packages

**Comment by georgiosd** [comment]
Fantastic, thanks!

**Comment by georgiosd** [comment]
@anurse Hm.... if I add the dev npm source and use the @aspnet/signalr package, SignalR doesnt work at all (404 to POST /hub/negotiate).

Am I doing something wrong?

At the same time, there's no @aspnet/signalr package listed here: https://dotnet.myget.org/gallery/signalr-preview

**Comment by moozzyk** [comment]
@georgiosd - you need to update the server packages to the latest as well.

**Comment by BrennanConroy** [comment]
@georgiosd The package feed you should be using for the dev bits is https://dotnet.myget.org/gallery/aspnetcore-dev/

**Comment by georgiosd** [comment]
Ah! Thank you gents
