### ISSUE TITLE
Web site hangs

### ISSUE THREAD

**Issue by squalsoft** [aspnet/SignalR#139]
Hi i created project on Asp.Net Core 1.1.0 with 
"Microsoft.AspNetCore.SignalR.Server": "0.2.0-*",
"Microsoft.AspNetCore.WebSockets": "0.2.0-*".
I host it on IIS. 
I have .Net 4.0 clients for that SignalR.
Everything works great some time. But after several connections website starts to hangs for several seconds, then it can totally hang and unavailabe with web browser.
But when all SignalR clients disconnects website starts to work. 
What can it be and how to find error's place?

**Comment by davidfowl** [comment]
Those versions of SignalR aren't supported and don't come from this repository.

**Comment by squalsoft** [comment]
Which version this repository have? And how to install?

**Comment by squalsoft** [comment]
Thank you very much! So i can't use standard SignalR client?

**Comment by moozzyk** [comment]
No, the old client does not work with the new server.
