### ISSUE TITLE
Ensure we are tracing connection/request URLs on the client

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1391]
While investigating #1389 I noticed that we don't really trace the URLs that we are connecting to or the HTTP requests going out. So when an error occurs, we can't easily trace it back to the request that triggered it. We should ensure our transports trace out useful data about the outbound requests, and consider attaching a logging handler to the `HttpClient` we use

**Comment by davidfowl** [comment]
We may need to scrub querystrings

**Comment by anurse** [comment]
We should **definitely** scrub querystrings.

**Comment by BrennanConroy** [comment]
?

**Comment by anurse** [comment]
Just confirming that we should scrub querystrings, and moving this to the appropriate milestone :)

**Comment by JamesNK** [comment]
What do we mean by scrub querystrings? URL only with no query string at all?

**Comment by BrennanConroy** [comment]
`https://localhost:5000?id=1234&secret_token=super-secret` will become `https://localhost:5000?id=1234`

**Comment by davidfowl** [comment]
That's a good question, are we stripping all query strings from logs as user data?

**Comment by BrennanConroy** [comment]
I think everything except `id` should be stripped

**Comment by anurse** [comment]
> That's a good question, are we stripping all query strings from logs as user data?

Yeah, I kinda dodged that because I'm not sure the best way to approach it. Generally, query strings should be loggable (as you're not supposed to put authentication in there). We're forced to put auth tokens in the query string in one place: WebSockets on the **JavaScript** Client. I think we can log query strings everywhere **except** in the WebSocket transport.

**Comment by davidfowl** [comment]
It's a bit messy. People will be using these logs to look at what gets sent and filtering that out feels wrong.

**Comment by JamesNK** [comment]
FYI the entire URL is already logged in the TS client

https://github.com/aspnet/SignalR/blob/d367bdc9aa7856be4c9b22c2fe97532f16d6641a/clients/ts/signalr/src/Transports.ts#L64

**Comment by davidfowl** [comment]
I actually think this is fine.
