### ISSUE TITLE
Detect connection state changes?

### ISSUE THREAD

**Issue by jceddy** [aspnet/SignalR#1396]
In the previous SignalR client, I could subscribe to connection state changes using:

$.connection.hub.stateChanged

Is there something similar in the new (preview2) client? Or do I have to do some kind of polling to get that information?

**Comment by anurse** [comment]
The state diagram for the client right now is much simpler. The `start` Promise lets you know when the connection starts and the `closed` event lets you know it's stopped. We don't have automatic reconnects, so those are the only state transitions.

**Comment by jceddy** [comment]
Thanks for that. Been testing with preview2 in a .NET Core 2.0 application and am very pleased with the performance. Looking forward to the real-deal release. :)

**Comment by LucasArgate** [comment]
How can i get close connection event?

```
var connection = new signalR.HubConnection('/chat', { logging: signalR.LogLevel.Trace });
connection.onclose = function(){
   console.log('connecition closed');
}
connection.start().then(function(){
   console.log('connection started');
})
```

im having difficult to understand it.

**Comment by anurse** [comment]
You actually **call** `onclose` passing it the callback you want to register. This is so that you can register multiple callbacks. So this modification to your code should work:

```javascript
var connection = new signalR.HubConnection('/chat', { logging: signalR.LogLevel.Trace });
connection.onclose(function(){
   console.log('connecition closed');
});
connection.start().then(function(){
   console.log('connection started');
})
```
