### ISSUE TITLE
Turn of keep alive messages logging

### ISSUE THREAD

**Issue by xperiandri** [aspnet/SignalR#140]
Can keep alive messages logging be disabled?
Was it possible in `SignalR-Server`?

**Comment by davidfowl** [comment]
We don't have keep alive messages as yet and no it wasn't possible to turn it off in SignalR-Server.

**Comment by xperiandri** [comment]
They occured because of `Application Insights`
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/328
