### ISSUE TITLE
SingalR connection.start() seems to succeed when it's failing

### ISSUE THREAD

**Issue by jceddy** [aspnet/SignalR#1401]
I've been testing some logic to re-establish a SignalR connection from a JavaScript client when it gets broken. (Using preview2).

I added on onclose handler to my connection by doing something like this:

`signalRHub.onclose(reconnect)`

Where the reconnect function looks like this:

```
function reconnect(error) {
  log(identifier, "Reconnect", error == null ? error : "Retry");
  showConnectionStatus('reconnecting', 'Re-connecting...');

  signalRHub = new signalR.HubConnection(signalRHubURL, signalRHubOptions);
  signalRHub.on("doStuff", (jsonData) => { /* do stuff */ });
  signalRHub.onclose(reconnect);
  signalRHub.start().then(() => {
    /* do some stuff to register connection information */
    showConnectionStatus('connected', 'Data connection is normal.');
    reconnectTime = 1000;
    log(identifier, "Reconnect Successful");
  }).catch((error) => {
    log(identifier, "Reconnect Failed", error == null ? error : "Unknown", "Retrying in Msecs", reconnectTime);
    setTimeout(reconnect, reconnectTime);
    reconnectTime = Math.min(60000, reconnectTime * 2);
  });
}
```

Basically, if the connection closes unexpectedly, it will try to create a new connection in a second, then keep retrying with the retry interval time doubled, up to a minute (at which points it just retries every minute).

The way I'm testing it is by shutting down the server completely after the initial connection is established, and I've verified that 2-way communication is working correctly over the connection.

The strange thing I'm seeing is that after I shut down the server, the onclose handler triggers and it tries to reconnect. At this point a new HubConnection is created and start() is called. I expect in this case for .catch() to happen and for the reconnect to be rescheduled, but instead it's going into the then() block, with a connectionStatus of 2 (Connected). This seems incorrect, since the server side is completely down and there's no way a connection is successfully being established.

In fact, I can see connection attempts failing with a 502 error in my JavaScript console.

Can anyone explain this behavior? Is it a bug? Is it a known bug? Or am I just misunderstanding something?

**Comment by anurse** [comment]
That doesn't sound like expected behavior. Can you provide additional information on your scenario:

* What server are you using (Kestrel/IIS/IISExpress/HttpSys)?
* Is everything running on localhost? 
* What transport(s) are you using?
* What does the network trace in your browser devtools show during the connection attempts?

**Comment by jceddy** [comment]
Okay, I think I figured out what is happening...

I think IISExpress is restarting my Kestrel server (which is what I was manually stopping) behind the scenes, so it's actually successfully reconnecting at this point.

When I kill the IISExpress server manually before killing the Kestrel server, I see the expected behavior.
