### ISSUE TITLE
Hub unexpectedly disposed

### ISSUE THREAD

**Issue by samcov** [aspnet/SignalR#1404]
I have a login method on a hub and if I don't await a function the hub remains active, but if I do, the hub is disposed.

The hub method is an async function, could that be the issue?
![presentation1](https://user-images.githubusercontent.com/1551314/35751723-6021d4ea-080e-11e8-9c4d-4802b1968b1b.jpg)

**Comment by anurse** [comment]
You should not use `async void` for Hub methods, as it create a race condition. Without a `Task` return from the Hub method we don't know when the actual async operation completes. Change the function to be `async Task` and the issue should be resolved.

In general, you should never use `async void` unless writing handlers for .NET Events (using `EventHandler` specifically)

**Comment by samcov** [comment]
Great, I'll modify the code. This worked fine in the full framework, but no issue, your answer makes sense, because async void is bad in other situations as well.

Thanks for the quick response!

**Comment by anurse** [comment]
> full framework

Do you mean ASP.NET Core on .NET Framework, or ASP.NET 4.x (System.Web and friends)? System.Web did some weird hacky magic to make async void kinda work in places so I'm not too surprised that it used to work. That was back when async was new though, now `async Task` is the way to go everywhere.

**Comment by anurse** [comment]
Closing this under the assumption that it will fix your issue. Please feel free to continue to comment or reopen if you still have issues!

**Comment by samcov** [comment]
Asp.net 4.x using SignalR 2.x. and Orleans 1.5

**Comment by samcov** [comment]
Just to let you know, your suggestion worked a treat. Returning a Task fixed everything!

**Comment by anurse** [comment]
> Asp.net 4.x using SignalR 2.x. and Orleans 1.5

Ah yeah, so this would have worked in SignalR 2.x because we did a lot of hacky things to try and make it work, but those hacks were problematic and we didn't bring them forward to ASP.NET Core. You should always try to use `async Task` (having `async void` anywhere in your code is always a bit suspicious ;))

> Just to let you know, your suggestion worked a treat. Returning a Task fixed everything!

Excellent! Glad to hear it!

**Comment by davidfowl** [comment]
It’s likely you just got lucky in SignalR 2.x. Async void isn’t supported anywhere but event handlers in Winforms and webforms apps

**Comment by samcov** [comment]
I'm just happy to get the right solution, thanks guys!
