### ISSUE TITLE
Provide some kind of "guard rail" to prevent `async void` Hub methods

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1405]
Issues like this: https://github.com/aspnet/SignalR/issues/1404 can arise when `async void` is used in a Hub method. We should look at some kind of "guard rail" for this:

1. We could use reflection to scan for `AsyncStateMachineAttribute` and `void` return type and throw. We can "cache" that so that it only happens once per hub method per app, or do it only when a config setting is provided (and default that to "on" in the Development environment)
2. We could provide a Roslyn Analyzer to detect this.

**Comment by davidfowl** [comment]
This isn't a SignalR issue, file this at the ASP.NET Home repository. This is the same for MVC/Middleware, anything really.

**Comment by davidfowl** [comment]
BTW you can detect this with a sync context
