### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by mual1133** [aspnet/SignalR#1407]
when i try to connect from another pc or phone i'm getting this error 
Transports.js:28 WebSocket connection to 'ws://10.0.0.52:3000/patient?signalRTokenHeader=eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ2M2FlNWZiMTExNjlhMTMwMDI2YWFiNGVhOGVkZDNjIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MTc2NjAwNTQsImV4cCI6MTUxNzc0NjQ1NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMS9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6ImNsaWVudCIsInN1YiI6IjU3ZDNiOTQ1LTQwZWItNGM4My05MGYyLTIwMDU2YmJmNzAwNyIsImF1dGhfdGltZSI6MTUxNzY2MDA1NCwiaWRwIjoibG9jYWwiLCJzY29wZSI6WyJhcGkxIl0sImFtciI6WyJwd2QiXX0.S6DHS24o60lsFewsvbcyV7j0wxo_vAf4N3ixg4fG_S3rWRMXmrkkHEdHjokVTkXNT1_07zzcehmmWyZdvDCpEsxwhX1mKbZdsZUFT0S8y8IJYsDXJlxw7exZOZOPW3Xp9HeHkfVOGKhDfwzKbHLgBzRpclb8AvMWe-4lAm0snjQTvroRJPSu5ifE8Aqv2qZr5ze_V4tSWX70Ly9ziZyGRGRMDzfyY4mr9Z2yDIYnHOHhBOqlrI4xCp340dZnSaCBLjC7jtI1wSu5nNuQEgQZtC0y5pH5NMi1Sxu7AMaAq4qNY-ivkHiIqVtu7IZrmeJD9HEWEjywVQh62T-Xe3wt2g&id=b1842c02-a9e4-40e7-91de-cdd8f2b244e6' failed: Error during WebSocket handshake: Unexpected response code: 504
Promise @ Transports.js:28
t @ polyfills.js:3
connect @ Transports.js:26
(anonymous) @ HttpConnection.js:54
fulfilled @ HttpConnection.js:6
t.invoke @ polyfills.js:3
onInvoke @ core.js:4629
t.invoke @ polyfills.js:3
r.run @ polyfills.js:3
(anonymous) @ polyfills.js:3
t.invokeTask @ polyfills.js:3
onInvokeTask @ core.js:4620
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
o @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2
Loggers.js:17 Error: Failed to start the connection. undefined

**Comment by anurse** [comment]
Can you provide some more information about your environment? What operating systems are you using (Windows versions/Linux distros/etc.)? What server is running (Kestrel/IIS/IIS Express)? Are there any logs on the server (from either the Console Window or the Debug Pane in Visual Studio) that indicate exceptions throw on the server? What browser are you testing from (including version)?

The error code '504' indicates a "Gateway Timeout", which means a proxy may be blocking your connection.

**Comment by anurse** [comment]
> from another pc or phone

Just saw this. If you try to connect over localhost on the server, does it work? Could you provide the startup log messages from your server?

**Comment by mutasemhidmi1133** [comment]
yes when i use localhost it works normally however i'm using iisexpressproxy to test it remotely from a phone, note that iisexpressproxy works normally with webApi controllers but with signalr i'm receiving the above error

**Comment by mutasemhidmi1133** [comment]
i was not able to get the logs for it because the connection is not being established however here is what i get from fiddler (
HTTP/1.1 504 Fiddler - Receive Failure
Date: Sat, 03 Feb 2018 19:38:02 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: no-cache, must-revalidate
Timestamp: 21:38:02.311

[Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 0 bytes.                                                                                                                                                                                                                                                                                                                                                                                                       
)

**Comment by BrennanConroy** [comment]
Try a different transport, I'm guessing your proxy is blocking websocket requests.

**Comment by anurse** [comment]
@mual1133 What operating system is the server running on? WebSockets in IIS Express require Windows 8/Windows Server 2012 or higher.

**Comment by mual1133** [comment]
i have windows 10

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/en-us/iis/configuration/system.webserver/websocket

**Comment by anurse** [comment]
To be clear, when you say you are using "iisexpressproxy" are you referring to this: https://github.com/icflorescu/iisexpress-proxy ?

If so, and it only fails when using that proxy, you'd have to ask them if WebSockets are properly supported and how to configure them.

**Comment by mual1133** [comment]
@anurse yes i was using this and im using typescript too.

**Comment by anurse** [comment]
Ok, then if it works fine outside `iisexpressproxy` you'll have to get further assistance from the `iisexpressproxy` devs. Closing this here as there doesn't appear to be a SignalR issue yet, feel free to reopen if one does arise!
