### ISSUE TITLE
Does SignalR change the case of class members in returned json?

### ISSUE THREAD

**Issue by samcov** [aspnet/SignalR#1415]
I have a class that is being sent to the client(html). 

One of the members of that class is **ConnectionID**, however, when it arrives at the client, the member is now **connectionID**.

Is this the expected behavior?

**Comment by moozzyk** [comment]
Yes: https://github.com/aspnet/SignalR/blob/0311f9b41570715293e82b793d22aee9e1a60b57/src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonHubProtocol.cs#L338
but can be configured.

**Comment by anurse** [comment]
We use camelCase for names in JSON as it fits JavaScript patterns better. However, as @moozzyk mentioned, it is configurable if you'd prefer to use PascalCasing. On the server you can edit your `.AddSignalR` call to something like this:

```csharp
services.AddSignalR()
    .AddJsonProtocol(options => {
        options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver();
    });
```

Closing this, as the question has been answered. Feel free to comment if you have additional questions!

**Comment by samcov** [comment]
I'd prefer to use camelCase if I was starting fresh. Unfortunately porting an existing application that used the previous version of SignalR, we must use the classes as designed or we'll face a lot of breaking changes too hard to track down.

Good to know we have that option in the future... Thanks

**Comment by samcov** [comment]
BTW, the example didn't work, but this does.

` services.AddSignalR(options => options.JsonSerializerSettings.ContractResolver = new DefaultContractResolver());`

**Comment by anurse** [comment]
Ah, sorry. I was referring to the API in the Preview 1 nightly builds. If you're using Alpha2, your code snippet is correct. When you update to Preview1, you'll need to use the snippet I provided :)

**Comment by samcov** [comment]
Good to know, you were one step ahead :)
