### ISSUE TITLE
ISignalRBuilder does not contain a definition for AddRedis

### ISSUE THREAD

**Issue by isaac873** [aspnet/SignalR#1417]
This feels like it might be a silly question but I'm trying to implement Redis as a backplane for a prototype I'm building and all the samples I've seen, quote something along the lines of: 

```
public void ConfigureServices(IServiceCollection services)
        {
             services.AddSignalR()
                .AddRedis(options => options.Factory = writer =>
                {
                    return ConnectionMultiplexer.Connect("localhost", writer);
                });
}
```
but apparently there is no definition for AddRedis() in the package I'm using (which for reference is Microsoft.AspNetCore.SignalR -version 1.0.0-alpha2-final).

Any ideas?

**Comment by BrennanConroy** [comment]
You need to add the redis package, `Microsoft.AspNetCore.SignalR.Redis`

**Comment by isaac873** [comment]
Perfect, that's what I was missing, thanks!
