### ISSUE TITLE
Add new APIs to get group counts

### ISSUE THREAD

**Issue by niemyjski** [aspnet/SignalR#1418]
I was looking at the HubLifeTimeManager and respected unit tests for both reds and in memory and there is a real good use case for exposing an api for getting the number of current subscribers to a specific group (e.g., connections via user id. connections to an organization).

In Exceptionless, we added the ability to not send any change notifications over our message bus (which flowed down to clients over web sockets and saved a ton of work and over head) by checking connection counts ([GetConnectionCountAsync](https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Insulation/Redis/RedisConnectionMap.cs#L35) and https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Services/MessageService.cs#L40

Having this would allow us to migrate to SignalR and save a lot of work and overhead :) I think this would also simplify some tests as we well as you could assert number of listeners.

**Comment by davidfowl** [comment]
We don't want to expose connection counts via the HubLifetimeManager. That would require state to be stored in the implementation. Things pub sub systems like service bus and rabbit MQ would now need an additional state storing mechanism.

**Comment by niemyjski** [comment]
Couldn't it query the current subscription/connection count by a group? Surely there is api / stats end points to do this in various vendors.

**Comment by davidfowl** [comment]
I think it's too limiting to require on the implementation.

**Comment by niemyjski** [comment]
Could it be an additional interface and I can type check for it? It would be a huge win for us.

**Comment by BrennanConroy** [comment]
It's very simple to store group count information yourself via a static collection in your hub. Granted you have to store the same information on every server, or you could put it in an external DB.

Is that not what you want?

**Comment by niemyjski** [comment]
No, because I need to see whose actually listening to a group (how many
subscribers does this redis key have is a super cheap lookup). If I'm going
to manage that myself then I'm not going to use as it's just as much work
to keep my current implementation which is pretty dead simple :\.

Thanks
-Blake Niemyjski

**Comment by davidfowl** [comment]
> No, because I need to see whose actually listening to a group (how many
subscribers does this redis key have is a super cheap lookup). If I'm going
to manage that myself then I'm not going to use as it's just as much work
to keep my current implementation which is pretty dead simple :\.

@niemyjski They keyword is "implementation" not abstraction. The more requirements we have on the abstraction the harder it is to implement. The other thing is requiring state on the HubLifetimeManager implementation, I *really* *really* don't want us to go there. 

If we consider doing a feature like this, it will be separate from the HubLifetimeManager.

**Comment by ejsmith** [comment]
I saw in a different issue (#1292) that someone was just overriding the OnConnectedAsync and OnDisconnectedAsync methods in their hub to keep an up to date count of connections, but they were running into issues with the disconnected method being called too many times. @davidfowl should that work to be able to keep an accurate count?

**Comment by davidfowl** [comment]
It will only ever be called once per connection. Unlike the existing version of SignalR, connections need to be persistent in this version so there's no crazy state tracking going on across multiple servers.

**Comment by ejsmith** [comment]
So I think you are saying that keeping track of connection counts like that issue was trying to do should work? Is OnDisconnectedAsync guaranteed to be called even if the connection isn't closed properly and eventually times out?

Also, is there currently any documentation on how the scale out works in the new SignalR?  I see RedisHubLifetimeManager, but not sure exactly what it's doing yet.

**Comment by davidfowl** [comment]
> So I think you are saying that keeping track of connection counts like that issue was trying to do should work?

Yes.

>  Is OnDisconnectedAsync guaranteed to be called even if the connection isn't closed properly and eventually times out?

Yes, if the socket dies this will be called. The tricky part is that in some scenarios, the socket can take very long to die (that's OS dependent). But the guarantees are that each event will fire once for the lifetime of the connection.

> Also, is there currently any documentation on how the scale out works in the new SignalR? I see RedisHubLifetimeManager, but not sure exactly what it's doing yet.

We don't write that level of docs until the implementation is done. It's pretty much the same as it was before at a high level. It's responsible for delivering messages to various groups of connections.

**Comment by niemyjski** [comment]
Only thing is the connection can live a really long time and you don't really know if the process just died. So how do you handle that unless you use some kind of expires and update it on successful idle check

**Comment by davidfowl** [comment]
> Only thing is the connection can live a really long time and you don't really know if the process just died. So how do you handle that unless you use some kind of expires and update it on successful idle check

With keep alives.

**Comment by niemyjski** [comment]
@davidfowl yes, but that's a lot harder than just extending OnDisconnectedAsync and OnConnectedAsync to ensure counts are accurate. If I had a hook for keep alives, I'd still have to maintain a list of connection ids and some kind of last timestamp so I'd know which ones to expire for an accurate count (and do this for every group). Which is why I was thinking adding support for this would be nice. I totally get that it adds complexity and may not be supported in every implementation but it's a really nice to have. At least in redis (https://redis.io/commands/pubsub#codepubsub-numsub-channel-1--channel-ncode), in memory it (return dictionary count), and rabbitmq (https://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2013-May/026932.html) would be super easy

**Comment by davidfowl** [comment]
We're not going to be adding support to get a list of a count of connections in a group. At least not in this version.
