### ISSUE TITLE
RedisHubLifetimeManager should support multiple serialization formats via an abstraction

### ISSUE THREAD

**Issue by niemyjski** [aspnet/SignalR#1419]
I noticed that the library is hard coded to use JSON.NET (https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs#L36). I've been trying to work towards using only MessagePack or https://github.com/neuecc/Utf8Json Would it be possible to use a serializer abstraction for all implementations so we can reduce some dependencies here.

**Comment by anurse** [comment]
We could consider that but given that the backlog for 2.1 is pretty deep, and the HubLifetimeManager is itself an abstraction that can be replaced, I don't think we'll be able to get this done in 2.1.

The serialization used there is intended to be an implementation detail. Can you provide more context on why you are trying to reduce dependencies? Even if we add the abstraction, JSON.NET will still be in your dependency graph.

**Comment by niemyjski** [comment]
For one, using MessagePack is much smaller and faster payloads for this scenario. It would be nice to change out how messages are serialized. For instance Utf8Json is much much faster than JSON.NET and I'd rather use that then JSON.NET if I'm just dealing with JSON / readable data.

**Comment by davidfowl** [comment]
We're not going to be doing this, we're actually going to use a custom binary format https://github.com/aspnet/SignalR/issues/1800

**Comment by niemyjski** [comment]
@davidfowl what are you going with? Be nice to use some standard that already has a community and is proven..

**Comment by davidfowl** [comment]
> Be nice to use some standard that already has a community and is proven..

Why? Currently we plan to use a custom binary format but it could be msgpack as well, it really doesn't matter as it's invisible and not configurable.

**Comment by niemyjski** [comment]
Why maintain a custom format when there area already proven formats out there and also make it much harder for people to use this on different stacks where msgpack / web sockets are already supported?

**Comment by davidfowl** [comment]
> Why maintain a custom format when there area already proven formats out there and also make it much harder for people to use this on different stacks where msgpack / web sockets are already supported?

1. It's simpler and specific to our needs. It's not extensible, doesn't need to support anything fancy.
2. We don't need a dependency on a 3rd party library other than the redis client.

It doesn't make it harder for people to use, maybe I wasn't clear earlier when I said this is transparent to the user experience of SignalR. The protocol is specifically for redis to communicate to other servers running signalr with redis.

**Comment by anurse** [comment]
> The protocol is specifically for redis

To be even clearer this protocol is for a SignalR server to communicate with another SignalR server **running the exact sample application** _via_ Redis. This protocol has nothing to do with how the client communicates with the server.

**Comment by niemyjski** [comment]
Makes sense. Was just thinking others might want to push something onto the backplane in a different language

**Comment by anurse** [comment]
That's not something we're looking to enable right now. We may end up using something like MsgPack (after all, the serialization format for that is simple and we wouldn't need a full serializer here, we're just serializing a list of `(protocolName, serializedMessageBlob)` pairs). If we do that, we could document it later if we want to open that extensibility up.

**Comment by davidfowl** [comment]
Yea I think we document it later as we look to enable more scenarios

**Comment by anurse** [comment]
In my initial work, I'm using the MsgPack format anyway so I don't see why we couldn't document it. I do think we're not quite there yet though. We can probably have it as a "pubternal" feature (i.e. technically doable but we reserve the right to break it after 2.1). I use quotes because it's the format that would be "pubternal", not any particular type (those would still be `internal` for now)
