### ISSUE TITLE
RedisHubLifetimeManager memory leak with disconnected clients?

### ISSUE THREAD

**Issue by niemyjski** [aspnet/SignalR#1420]
I ran into this issue myself with our own hard coded implementation with exceptionless that I'm investigating how to resolve. The issue is that if the app dies the redis keys exist and never get cleaned up on app restart. We were using redis sets instead of subscribing to the bus. I was looking over the source code here to see what you all were doing and came across this: https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs#L35 

And I was curious what happens if a redis hiccup happens or app restarts, are groups properly unsubscribed / subscribed after a disconnect? I just see log messages in the respected handlers.  I also wasn't sure how subscriptions work after a redis disconnect.

**Comment by davidfowl** [comment]
I believe redis subscriptions are tied to a specific connection. AFAIK redis  has no persistent state (which is precisely why we use them) for pub sub. All of the state is stored per connection on the redis instance and nothing is written to disk. If redis dies, all of the subscriptions and data are lost.

**Comment by niemyjski** [comment]
So then, won't we need to re subscribe when on disconnect / reconnect occurs ?

**Comment by BrennanConroy** [comment]
If it's just the redis connection that dies and not the server then StackExchange.Redis automatically sets the subscriptions back up when it reconnects

**Comment by niemyjski** [comment]
I know that in our code, when a reconnect occurs we have to reload any Lua scripts. I wasn't sure the extent of what needs to be done for redis pub / sub. Be good to test this scenario :)
