### ISSUE TITLE
Allow Rx streams from client to be observered by backend

### ISSUE THREAD

**Issue by pardahlman** [aspnet/SignalR#1421]
Hello gang - great job with the new SignalR framework 👍 . I really like the `IObservable<T>` support for the hub methods, it makes tons of sense to let data streams propagate out to the client. I don't know if what I'm asking for is technical doable or even makes sense, but... here goes :bowtie: 

I'm currently building an application in which the client initiates queries that are handled by various backend services. These services, in turn, produces responses to an (aggregated) `IObservable<QueryResponse>` that the client subscribe to. Easy 😉 

The only thing that doesn't feel 100% right is that I have to use a subject in the hub when receiving a new query to notify the backend services about the new query. Ideally, I would like the have an observable in the frontend that registers changes in the input field and that I could have a registered observer in the backend/hub that is invoked (`OnNext`) when input is changed. Basically, I would like streams initiated in the frontend to be observed in the backend.

Looking forward hearing your thought, and keep up the good work!

**Comment by anurse** [comment]
We've talked about returning values from Client calls, and this would be part of the same basic idea. There are unfortunately a lot of things on our queue for 2.1 so I don't think it will happen in this first release, but we're keeping it in mind!

**Comment by pardahlman** [comment]
That sounds very interesting! Is there a Github issue for that that I can keep track of?

**Comment by anurse** [comment]
https://github.com/aspnet/SignalR/issues/335

I'm going to close this issue in lieu of that one so we don't have duplicates hanging around. Thanks for the suggestion!
