### ISSUE TITLE
Unable to connect to SignalR hub from using "signalr-client-1.0.0-alpha2-final.js" with "https" self-signed certificate

### ISSUE THREAD

**Issue by thepranay14** [aspnet/SignalR#1423]
I am facing a problem while connecting to SignalRHub from signalr-client-1.0.0-alpha2-final.js,
I am able to connect it when connecting to "http:" but with "https:" I am unable to connect.

I am using a self-signed certificate here. Following is my code, do let me know if I am missing something.
```
<script type="text/javascript">
        var transport = signalR.TransportType.WebSockets;
        var connection = new signalR.HubConnection(`https://${document.location.host}/chat`, { transport: transport });
        var messageInput = document.getElementById('message');
        var name = prompt('Enter your name:', '');
        var button = document.getElementById("sendMessage");
        connection.on('broadcastMessage', (name, message) => {
            var liElement = document.createElement('li');
            liElement.innerHTML = '<strong>' + name + '</strong>:&nbsp;&nbsp;' + message;
            document.getElementById('discussion').appendChild(liElement);
        });
        button.addEventListener("click", event => {
            connection.invoke('send', name, messageInput.value);
            messageInput.value = '';
            messageInput.focus();
        });
        connection.start();
    </script>
```

![untitled](https://user-images.githubusercontent.com/12296363/35975788-f26b7d8e-0d03-11e8-95ec-384b00e5d440.png)

I have implemented a custom retry policy here. You can ignore this as of now.
I have also tried changing TransportType.WebSockets; to TransportType.Longpooling but had no luck.
Is there any workaround to bypass the self-signed certificate for the development environment?

**Comment by anurse** [comment]
Can you confirm the URL you are using in your `HubConnection` constructor? The code snippet shows `http` but the DevTools log shows `wss` (which indicates `https` was used). Also, I presume you've verified that the port number is correct as well?

Is there anything in the Network tab for the WebSocket request? We can see the 404 response there. Also, do you have any server logs indicating an error?

**Comment by thepranay14** [comment]
Ah my bad, I have updated my question. Yes i am using "Https".
I have checked the port number.
I am able to connect with "https" in the c# client by ignoring certificate. But doing the same with java script client it is throwing errors.

I don't have any server logs.

I can easly ignore the certificate and in c#, is there any way to ignore the same in javascript(XmlHttpsRequest)?

**Comment by anurse** [comment]
It's not possible to do this programmatically (it would be a security risk, because JavaScript code is often untrusted and has to be sandboxed). If you navigate to the page normally and add the certificate as a trusted certificate in your browser, it should be treated as trusted by XHR as well.
