### ISSUE TITLE
Angular App connects inconsistently

### ISSUE THREAD

**Issue by bparkerhsd** [aspnet/SignalR#1438]
I am using version 1.0.0-alpha2-final. My hub is hosted in Azure App Services. When I attempt to connect from the Angular App using the SignalR client I get the following error message:

Error during WebSocket handshake: Unexpected response code: 404.

I can finally connect after trying to connect one or more additional times. I am able to then send messages to the hub and receive them back.

My typescript code for connecting:
```
public connect() {
        
        try {
            this._hubConnection = new HubConnection(this.connectionString);
            this._hubConnection.on('Send', (data: any) => {
                const received = `Received: ${data}`;
                this.messages.push(received);
                console.log(received);
            });

            this._hubConnection.start()
                .then(() => {
                    console.log('Hub connection started')
                    this.connectionStatus = "Connected.";
                })
                .catch(err => {
                    console.log('Error while establishing connection')
                    this.connectionStatus = `Error while establishing connection: ${err}`;
                });
        }
        catch (ex) {
            console.log(`Exception connecting: ${ex}`);
        }
    }
```

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR/issues/1022#issuecomment-336935501

**Comment by bparkerhsd** [comment]
I reviewed #1022. In my case this is a single ASP.NET Core 2 Angular client connecting to a single ASP.NET Core 2 Hub. I cannot consistently connect to the Hub. It takes multiple retries before it does. 

In addition, once I get a connection and I perform a chatHub.Clients.All.InvokeAsync("Send", data); from the Hub, the Angular client sometimes gets the message. It is not consistent. Sending messages from the    Angular clients always works.

**Comment by anurse** [comment]
Can you use the Network tab of your Browser Dev Tools to gather some more information about the network traffic? Does this issue only occur on Azure App Service or does it also occur locally? Finally, do you have multiple instances configured in your Azure App Service Scale Out tab?

**Comment by bparkerhsd** [comment]
[networklog.zip](https://github.com/aspnet/SignalR/files/1732177/networklog.zip)

I am running the client through a debug session of Visual Studio.

The hub is running on an App Service plan with an override instance count of 10.

**Comment by anurse** [comment]
It looks like each request is getting a different ARRAfinity cookie value, which means it may be going to a different server. Do you have ARR Affinity enabled in your App Service? Also, since you have multiple servers, have you configured the Redis backplane in order to allow connections from multiple servers to communicate with each other?

**Comment by bparkerhsd** [comment]
I changed the hub to a new App Service plan with one instance. This works consistently for my current use cases! I will add to my work log adding a Redis backplane. Thanks for the guidance!
