### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by NVentimiglia** [aspnet/SignalR#1440]
I am looking for SignalR benchmarks. Would like to know the limitations of SignalR Core before I dive too deep. 

I would like to know operations per second for simple echo and broadcast type events. Number of maximum of concurrent connections I can expect to serve.

Has anyone gone ahead and done some performance testing yet ? I can find benchmarks for kestrel in a adjoined repository, but nothing specific to SignalR.

**Comment by davidfowl** [comment]
No, we haven't done this work yet. @BrennanConroy is up benchmarks right now. We've also done no performance work so it'll likely be extremely inefficient right now.

**Comment by muratg** [comment]
See #1164
