### ISSUE TITLE
@aspnet/signalr package is not found

### ISSUE THREAD

**Issue by HassanHashemi** [aspnet/SignalR#1442]
the command `npm install @aspnet/signalr` results into 404.
and the docs in first page state that `@aspnet/signalr-client` is deprecated.

**Comment by BrennanConroy** [comment]
Because there has been no pre-release with the new name it's still only on our MyGet feed.
So the actual command is `npm install @aspnet/signalr --registry https://dotnet.myget.org/f/aspnetcore-dev/npm/`

**Comment by HassanHashemi** [comment]
sorry, my bad.

**Comment by HassanHashemi** [comment]
however this version seems to be using the URL "/hub/negotiate" which is deprecated according to [this](https://stackoverflow.com/questions/46264982/asp-net-core-2-signalr-1-0-0-alpha2-27025-signalr-negotiate-404-error).

**Comment by BrennanConroy** [comment]
That info is old. We changed it from alpha2 to preview1

**Comment by HassanHashemi** [comment]
sorry i do`nt get it, this package. is using wrong URL to negotiate!
(this package:  `npm install @aspnet/signalr --registry https://dotnet.myget.org/f/aspnetcore-dev/npm/`)

the server config is:
`app.UseSignalR(r => r.MapHub<HubBase>("b"));`
and the negotiation is done like this:
`/b/negotiate`.

**Comment by BrennanConroy** [comment]
That is correct. Make sure you have the same client and server package versions otherwise you can hit issues

**Comment by HassanHashemi** [comment]
server version:  Microsoft.AspNetCore.SignalR 1.0.0-alpha2-final
client version: npm install @aspnet/signalr --registry https://dotnet.myget.org/f/aspnetcore-dev/npm/

**Comment by BrennanConroy** [comment]
Those aren't compatible, either upgrade the server or use `@aspnet/signalr-client`
