### ISSUE TITLE
InvokeAsync with Queue<T> sends empty data

### ISSUE THREAD

**Issue by benaadams** [aspnet/SignalR#1444]
```csharp
Queue<MyStruct> _queue;
```
```csharp
await _hub
    .Clients
    .Group("global")
    .InvokeAsync("global", _queue);
```
```
{"invocationId":"1","type":1,"target":"global","nonBlocking":true,"arguments":[[]]}
```

However converting to array first works
```csharp
await _hub
    .Clients
    .Group("global")
    .InvokeAsync("global", _queue.ToArray());
```
```
{"invocationId":"1","type":1,"target":"global","nonBlocking":true,"arguments":[[{...},{...},{...},{...},{...}]]}
```

**Comment by anurse** [comment]
Hrm, this should be getting all the way down to JSON.NET. Do you know if JSON.NET properly serializes Queues?

**Comment by JamesNK** [comment]
Json.NET does serialize queues. A test with `Queue<T>` outputs the expected JSON at the protocol level: `{"type":1,"target":"Target","arguments":[["first","second"]]}`

https://github.com/aspnet/SignalR/commit/0d4e9fb5b9fb662058d340975f4e4d33df3c67ba

Exactly what overload of `InvokeAsync` does your code call? There are a lot of overloads of that method and knowing which one you're using might help lead to the issue.

**Comment by JamesNK** [comment]
More complete end to end test also works https://github.com/aspnet/SignalR/commit/6716fc402a2644091a1cf2e1993db03ded31271f

I'm not able to repo this.

**Comment by anurse** [comment]
Closing this for now given that it can't be reproduced. Please reopen and/or comment further if the issue reoccurs.
