### ISSUE TITLE
Make IConnection single-use and move restart/reuse behavior to HubConnection

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1450]
It makes things a little cleaner and after all, the main reason we want restartable/reusable connections are to keep HubConnection bindings in place, so making HttpConnection/IConnection restartable is less important.

**Comment by davidfowl** [comment]
So thinking about this more in the context of my existing change, we might be able to just unify things like this:

ConnectionContext is the root of the universe, its used on both the client and the server as the connection abstraction. We remove `IConnection` completely and introduce a factory of some sort that looks something like this:

```C#
public interface IConnectionFactory
{
    public ValueTask<ConnectionContext> ConnectAsync();
}
```

We then turn the HttpConnection into the `HttpConnectionFactory` whose solve purpose is to provide the ConnectionContext implementation over the various http transports.

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/aspnet/SignalR/issues/1450

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/aspnet/SignalR/issues/1475
