### ISSUE TITLE
Websocket response code: 204 (IIS8)

### ISSUE THREAD

**Issue by jceddy** [aspnet/SignalR#1457]
I have a .NET Core 2.0 application running with the preview SignalR. I'm running on Windows Server 2012 R2 behind IIS 8.5.

Websockets are enabled in the server roles, and are also configured in IIS.

When I attempt to initiate a SignalR connection over Websocket, I get this response:

> Error during WebSocket handshake: Unexpected response code: 204

Everything I've read says that this should work, and as far as I can tell I have all of the configurations set up correctly. Can anyone guide me on debugging this issue?

**Comment by anurse** [comment]
It would be most helpful if you can provide a simple repro project so we can see the code you're using to host the server and to connect the client. At a minimum, can you provide a snippet of your client connection code?

Are you using full IIS? If so, WebSockets is supported but **must be manually enabled** (see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets#iisiis-express-support)

It would also help if you could check the Network tab of your browser Dev Tools (assuming you're using the browser client) and get an idea of what requests the client is making.

**Comment by jceddy** [comment]
My application has two extension methods for adding SignalR to the application and to the services:

```
/// <summary>
/// .NET Core 2.0-specific extensions for Signal-R.
/// </summary>
public static class SignalRExtensions
{
	/// <summary>
	/// Use Signal-R and set up the base hub in the application.
	/// </summary>
	/// <param name="app">The Builder for the .NET Core 2.0 application.</param>
	/// <param name="serviceProvider">The application's service provider.</param>
	/// <returns>A reference to the application builder object.</returns>
	public static IApplicationBuilder UseSignalR_NETCORE20(this IApplicationBuilder app, IServiceProvider serviceProvider)
	{
		app.UseSignalR(routes =>
		{
			routes.MapHub<BaseHub>("baseHub");
		});
		OATISignalRHelper.BaseHubContext = serviceProvider.GetService<IHubContext<BaseHub>>();
		return app;
	}

	/// <summary>
	/// Add Signal-R servies to a .NET Core 20 application.
	/// </summary>
	/// <param name="services">The service collection.</param>
	/// <returns>The Signal-R builder object.</returns>
	public static ISignalRBuilder AddSignalR_NETCORE20(this IServiceCollection services)
	{
		var settings = new JsonSerializerSettings();
		settings.ContractResolver = new SignalRContractResolver();

		var serializer = JsonSerializer.Create(settings);
		services.Add(new ServiceDescriptor(typeof(JsonSerializer), provider => serializer, ServiceLifetime.Transient));

		services.AddSingleton<IMessageSender, MessageSender>();
		services.AddSingleton<IContractResolver, SignalRContractResolver>();
		return services.AddSignalR();
	}
}
```

It has code to use web Sockets if we're running on Windows Server 2012 R2 or higher (I needed this code in .NET Core 1.1, I might not need the check in 2.0 but haven't verified yet):

```
// Don't enable web sockets if we're running on a Windows version lower than 6.2 (Windows 8/Windows Server 2012 R2)
Regex windowsRex = new Regex(@"Microsoft Windows ([0-9]*\.[0-9*]).*");
Match match = windowsRex.Match(RuntimeInformation.OSDescription);
if (!match.Success || double.Parse(match.Groups[1].Value) > 6.1)
{
	app.UseWebSockets();
}
```

The client connection code looks something like this (sanitized a bit):

```
Publisher.signalRHubURL = /* set URL */
Publisher.options = { logging: false };
Publisher.signalRHub = new signalR.HubConnection(Publisher.signalRHubURL, Publisher.options);
Publisher.showConnectionStatus('disconnected', 'Disconnected. Real-Time updates offline.');
Publisher.signalRHub.start().then(function() {
	Publisher.isInitialized = true;
	Publisher.signalRHub.on("updateSubscribedDisplay", function(jsonData) {
		Publisher.startMessageQueueThread(jsonData);
	});
	Publisher.signalRHub.onclose(Publisher.reconnect);
	if (Publisher.subscriberQueue.length > 0) {
		/* send some data to the server */
	}
	Publisher.showConnectionStatus('connected', 'Data connection is normal.');
}).catch(function(error) {
	// WebSockets not supported, fall back to LongPolling
	Publisher.logError(error, 1);

	Publisher.options.transport = signalR.TransportType.LongPolling;
	Publisher.signalRHub = new signalR.HubConnection(Publisher.signalRHubURL, Publisher.options);
		Publisher.signalRHub.start().then(function() {
		Publisher.isInitialized = true;
		Publisher.signalRHub.on("updateSubscribedDisplay", function(jsonData) {
			Publisher.startMessageQueueThread(jsonData);
		});
		Publisher.signalRHub.onclose(Publisher.reconnect);
		if (Publisher.subscriberQueue.length > 0) {
			/* send some data to the server */
		}
		Publisher.showConnectionStatus('connected', 'Data connection is normal.');
	});
});
```

I am using full IIS, and webSockets are enabled:

![image](https://user-images.githubusercontent.com/1302263/36319958-2475e3f8-130a-11e8-896c-675a88d4928c.png)

In the network tab, I see the webSocket request fail and then the longPolling request take over:

![image](https://user-images.githubusercontent.com/1302263/36320230-1aa16c52-130b-11e8-9942-ba2274666c63.png)

I notice that once the connection is made, signalR is reporting WebSockets as an available transport:

![image](https://user-images.githubusercontent.com/1302263/36320336-7bc900e4-130b-11e8-8157-cd6c3674863e.png)

**Comment by anurse** [comment]
Getting a `204` from the WebSocket request seems very suspicious. That would indicate the request came through SignalR marked as **not** a WebSocket request, which indicates a problem with how the WebSockets middleware is configured.

> It has code to use web Sockets if we're running on Windows Server 2012 R2 or higher (I needed this code in .NET Core 1.1, I might not need the check in 2.0 but haven't verified yet):

This code will not affect SignalR's usage of WebSockets. [SignalR puts the WebSocket middleware in automatically](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Http/SocketsAppBuilderExtensions.cs), you need to use the `Transports` option on `HttpSocketOptions` in your `MapHub` call: `routes.MapHub<Foo>("/foo", options => options.Transports = TransportType.LongPolling | TransportType.ServerSentEvents)`.

WebSockets work on all platforms when using Kestrel directly, but behind IIS they only work on Windows 8 or higher. We are working on doing this check automatically for you in ASP.NET Core 2.1: https://github.com/aspnet/IISIntegration/issues/584. When that change is made and we've updated SignalR to use that, you shouldn't need that code. Until now, it looks like it should functional properly, you just need to change what you do when the OS doesn't support WebSockets (use `Transports` instead of removing `.UseWebSockets`).

Your IIS configuration looks right, so I'm not sure what's going on there.

> I notice that once the connection is made, signalR is reporting WebSockets as an available transport

That's where the bug I mentioned above comes in. We need to add logic to our negotiate process that detects if WebSockets are supported and remove it. Right now we don't have that logic built-in, but you can use the `Transports` option to add it yourself.

**Comment by jceddy** [comment]
Should my code just not have UseWebSockets() at all, if it's already inserted by SignalR?

**Comment by anurse** [comment]
> Should my code just not have UseWebSockets() at all, if it's already inserted by SignalR?

Correct.

**Comment by anurse** [comment]
Having said that, it shouldn't matter that you're adding it to the pipeline. If it's in the pipeline twice, the second one should simply no-op

**Comment by jceddy** [comment]
Yeah, removing that hasn't changed the behavior.

What you said about the request coming through as not a WebSocket request sounds like something for me to look into...off the top of my head I don't know why that would happen, though.

**Comment by jceddy** [comment]
I added this at the very top of my Startup class's Configure method:

```
app.Use(async (context, next) =>
{
	ServerFactory.GetLogManager().Log(string.Format("Request Scheme: {0}", context.Request.Scheme));

	await next();
});
```

This is always logging "http" as the scheme (I expect at least one "ws" for the webSocket request). Is this a valid test? Does it indicate that IIS is somehow mangling the webSocket request before passing it off to Kestrel?

**Comment by anurse** [comment]
Do you have logging enabled on the server? You should be able to see log entries for the incoming WebSocket request (it will show as an `http` request, but the `id` and `access_token` query string values should make it stand out) and see what additional log messages are coming after the initial "Request starting" message and the final "Request finished" message.

**Comment by anurse** [comment]
Ah, now that I read the linked issue, it certainly is possible. Would you be able to hack out the rewrite rule and test to see if that fixes the WebSocket just to isolate the issue?

**Comment by jceddy** [comment]
As soon as I commented out the rewrite section, it looked like it started connecting, but then it looked like it was reconnecting over and over again...might be an issue with my client-side code that handles re-establishing a broken connection.

Looks like I might be out of luck for webSockets on IIS until they have a fix for that rewrite issue.

![image](https://user-images.githubusercontent.com/1302263/36332934-e1b57fee-1339-11e8-8205-d1bbababe017.png)

**Comment by muratg** [comment]
Keeping this open to track aspnet/AspNetCoreModule#163
