### ISSUE TITLE
Cannot deploy ASP.NET Core 2 Angular 4 app to Azure App Services

### ISSUE THREAD

**Issue by bparkerhsd** [aspnet/SignalR#1458]
I create a base ASP.NET Core 2 Angular 4 app in Visual Studio 2017. I can deploy successfully to Azure App Services. 

I add "@aspnet/signalr-client": "1.0.0-alpha2-final" to package.json. I can run this in debug mode in Visual Studio 2017.

When I deploy to Azure App Services it fails:

1166 error path C:\Test Projects\DMTSignalRAngular\node_modules\fsevents\node_modules
1167 error code EPERM
1168 error errno -4048
1169 error syscall scandir
1170 error Error: EPERM: operation not permitted, scandir 'C:\Test Projects\DMTSignalRAngular\node_modules\fsevents\node_modules'
1170 error  { Error: EPERM: operation not permitted, scandir 'C:\Test Projects\DMTSignalRAngular\node_modules\fsevents\node_modules'
1170 error   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Test Projects\\DMTSignalRAngular\\node_modules\\fsevents\\node_modules\'',
1170 error   errno: -4048,
1170 error   code: 'EPERM',
1170 error   syscall: 'scandir',
1170 error   path: 'C:\\Test Projects\\DMTSignalRAngular\\node_modules\\fsevents\\node_modules' }
1171 error Please try running this command again as root/Administrator.
1172 verbose exit [ -4048, true ]

Trying to add "fsevents": "1.1.3" to package.json fails to install the package:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Test Projects\DMTSignalRAngular\npm-debug.log

**Comment by anurse** [comment]
Looks like https://github.com/npm/npm/issues/17671, which is an issue in NPM itself. How are you deploying to Azure App Service? Are you using Git deployment?

**Comment by bparkerhsd** [comment]
I am building locally and publishing to App Service through VS 2017. I updated to npm 5.6.0 and it works! Thanks.

**Comment by anurse** [comment]
Excellent! Glad to hear it! I'll update our README to note that.
