### ISSUE TITLE
Support attribute routes for ConnectionHandlers bound via HTTP

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#146]
/cc @rynowak

**Comment by rynowak** [comment]
Cool

**Comment by rynowak** [comment]
More practically, what does this actually mean?

**Comment by davidfowl** [comment]
EndPoints today are mapped via `MapEndPoint`:

https://github.com/aspnet/SignalR/blob/dev/samples/SocketsSample/Startup.cs#L48-L56

As an alternative you can imagine the code being:

```C#
[Route("/chat")]
public class MessagesEndPoint : EndPoint
{
   // ...
}
```

**Comment by davidfowl** [comment]
I'm not a fan of this anymore since ConnectionHandlers are completely separate from how they are bound.
