### ISSUE TITLE
.Net Core 2 Signalr core alpha2 Hub not working

### ISSUE THREAD

**Issue by racamp101** [aspnet/SignalR#1472]
I have a major issue I can not solve. I have a.net core 2 project with jwt auth and trying to get a basic signalr hub test to work. The connection from the client seems to work but the connection is promptly dropped with a 204 code.

My hub is running on another URL than my front end UI so CORS is involved.

**I removed real keys and my project name

this is what the client console outputs:

> Information: Using HubProtocol 'json'.
> SignalR Connected: Chat
> signalr-clientES5-1.0.0-alpha2-final.js:818 Uncaught (in promise) Error: Invocation cancelled due to connection being closed.
>     at signalr-clientES5-1.0.0-alpha2-final.js:818
>     at signalr-clientES5-1.0.0-alpha2-final.js:712
>     at Map.forEach (<anonymous>)
>     at Map.<anonymous> (signalr-clientES5-1.0.0-alpha2-final.js:2046)
>     at HubConnection.connectionClosed (signalr-clientES5-1.0.0-alpha2-final.js:711)
>     at HttpConnection.HubConnection.connection.onclose (signalr-clientES5-1.0.0-alpha2-final.js:649)
>     at HttpConnection.stopConnection (signalr-clientES5-1.0.0-alpha2-final.js:484)
>     at LongPollingTransport.transport.onclose (signalr-clientES5-1.0.0-alpha2-final.js:361)
>     at XMLHttpRequest.pollXhr.onload (signalr-clientES5-1.0.0-alpha2-final.js:1411)

Here is my startup code:

    public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.Configure<ConnectionStrings>(Configuration.GetSection("ConnectionStrings"));
            services.Configure<DiAssemblies>(Configuration.GetSection("DiAssemblies"));
            services.Configure<StripeSettings>(Configuration.GetSection("Stripe"));
            services.Configure<AzureStorageSettings>(Configuration.GetSection("AzureStorageSettings"));

            // Add framework services.
            services.AddApplicationInsightsTelemetry(Configuration);
            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    x => x.AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                        .AllowCredentials());
            });

            services.AddIdentity<testApp.Identity.ApplicationUser, IdentityRole>()
            .AddEntityFrameworkStores<testApp.Identity.Context>()
            .AddDefaultTokenProviders();

            services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                sharedOptions.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;

            })
                .AddJwtBearer(options =>
                {
                    options.RequireHttpsMetadata = false;
                    options.SaveToken = true;
                    
                    options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters()
                    {
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("authkeyasdfasdfasdfsadfasdfda")),
                        ValidIssuer = "https://testApp.com/",
                        ValidAudience = "https://testApp.com/",
                        
                    };
                    options.Events = new JwtBearerEvents
                    {

                        OnAuthenticationFailed = context =>
                        {
                            Debug.WriteLine("Auth issue");
                            Debug.WriteLine(context.Exception);
                            return Task.CompletedTask;
                        },

                        OnMessageReceived = context =>
                        {
                            if (!context.Request.Headers.ContainsKey("Authorization") && !string.IsNullOrEmpty(context.Request.Query["authToken"]))
                            {
                                context.Request.Headers.Add("Authorization", context.Request.Query["authToken"]);
                            }
                            return Task.CompletedTask;
                        },
                        OnChallenge = context =>
                        {
                            Debug.WriteLine("Auth issue");
                            Debug.WriteLine(context.Error);
                            Debug.WriteLine(context.ErrorDescription);
                            return Task.CompletedTask;
                        }
                    };
                });

            services.AddMemoryCache();

            services.AddMvc().AddJsonOptions(options =>
            {
                options.SerializerSettings.ContractResolver =
                    new CamelCasePropertyNamesContractResolver();
                options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
            });
            
            services.AddSockets();
            services.AddSignalRCore();

            var builder = new ContainerBuilder();

            // Register dependencies, populate the services from
            // the collection, and build the container. If you want
            // to dispose of the container at the end of the app,
            // be sure to keep a reference to it as a property or field.
            //builder.RegisterType<MyType>().As<IMyType>();
            builder.Populate(services);
            var diHelper = new DiHelper();
            var diAssemblies = Configuration.GetValue<string>("DiAssemblies:List");
            var assemblies = diHelper.GetAssemblies(diAssemblies.Split(',').ToList());
          //  Console.Write(diAssemblies);
            builder.RegisterAssemblyModules(assemblies);

            ApplicationContainer = builder.Build();

            //foreach(var assembly in assemblies)
            //    services.AddMvc().AddApplicationPart(assembly).AddControllersAsServices();

            // Create the IServiceProvider based on the container.
            return new AutofacServiceProvider(ApplicationContainer);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseCors("CorsPolicy");

            app.UseAuthentication();

            app.UseMvc();
            
            app.UseSignalR(routes =>
            {
                routes.MapHub<ChatHub>("chat");
            });
        }
    }

My Hub (a break point on any of the methods never gets hit)

    public class ChatHub : Hub
        {
            public ChatHub()
            {
                var t = 0;
            }
    
    
            public override async Task OnConnectedAsync()
            {
                await Clients.Client(Context.ConnectionId).InvokeAsync("send", "connection made");
    
                await base.OnConnectedAsync();
            }
    
            public Task Send(string message)
            { 
                return Clients.All.InvokeAsync("send", message); 
            }
        }

Client javascript:

 

    <script>
          window.connection;
          window.connection = new signalR.HubConnection("https://localhost:44367/chat?authToken=" + 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.yyJzdWIiOiJhYzNkMTU3OC05YjU5LTRmNzQtOWMxYi01MWZlYjk2YmQ4YzEiLCJqdGkiOiJidnRlc3QxIiwiZXhwIjoxTYI2NjY1OTM3LCJpc3MiOiJodHRwczovL2Jpc3ZpbmUuY29tLyIsImF1ZCI6Imh0dHBzOi1vYmlzdmluZS5jb20vIn0.GxycqmyVsdHkW3M5yRH7arGkR3K-jAE2zrPrgoJnh-M', 
    								{ transport: signalR.TransportType.LongPolling });
    
          window.connection.on('send', function(message) {
            alert(message);
          });
    
    
          window.connection.start().then(function() {
            console.log("SignalR Connected: Chat");
            window.connection.invoke('send',"hi").then(function (chats) {
              console.log(chats);
            });
          }, function () {
             
          });
        </script>

**Comment by anurse** [comment]
Are you using IIS URL Rewriting? There is a know issue with that affecting WebSockets in that scenario: https://github.com/aspnet/AspNetCoreModule/issues/163

**Comment by racamp101** [comment]
@anurse no not doing any rewriting and not even trying websockets yet just longpolling first

**Comment by anurse** [comment]
Just to check one more simple question off the list: Do you have an MVC action or Razor page at the URL `/chat` in your application? If so, MVC would be taking the request before SignalR gets to it.

Assuming that isn't the issue: Are you able to view the server-side logs (Console window if you're using Kestrel directly or in the VS Output Window if you're using IIS/IIS Express)? Also, it would be helpful to see what the Network tab in your browser DevTools shows.

**Comment by racamp101** [comment]
@anurse Well it was not the same controller name BUT it did get me close! after reading the logs i had read 200 times i noticed another file was being hit that i didn't see before. One of my controllers didnt have a [Route()] attribute set after I set it my signalr started working thanks!

**Comment by anurse** [comment]
Aha! Glad you found the issue :).
