### ISSUE TITLE
WebSocketTransport.connect rejects promise with "undefined" error.

### ISSUE THREAD

**Issue by halter73** [aspnet/SignalR#1474]
https://github.com/aspnet/SignalR/blob/b3a33efeaea9d99a0541be9b98104a2d72f87579/client-ts/signalr/src/Transports.ts#L60-L62

results in

![image](https://user-images.githubusercontent.com/54385/36466379-babba2bc-168e-11e8-9609-6a8a1a2e5e90.png)

I would look at all usages of `reject()`. I'm also curious about rejecting with a string vs. rejecting with an `Error` object. Is it really OK to mix and match in a library?

**Comment by davidfowl** [comment]
It depends on what layer is consuming this API. That error looks like crap though, we should decide to probably normalize the error

**Comment by davidfowl** [comment]
Putting this in preview2 and marking it up for grabs

**Comment by anurse** [comment]
Thanks for tracking this down @halter73 !

We should **always** be rejecting with `new Error("message")` or `new TypeExtendingError("message")` (as with .NET and `Exception`)

**Comment by mikaelm12** [comment]
Looks like this was mostly fixed in fb6121399c676208b12663e60d12f84b7e8020c1
