### ISSUE TITLE
SignalR may not work with iOS and webSockets

### ISSUE THREAD

**Issue by xlegalles** [aspnet/SignalR#1476]
We have just moved a web application to ASP.NET Core with SignalR alpha 2 final. It works fine with our test server using any kind of device (local network only). But using the production server (DMZ) we have discovered that notifications are no more received by any iOS devices (Chrome or Safari). But it still works fine with any Android. (using either our local network or the public IP)

There is also one difference between both environment: the test server is a windows 2012 as the production one is a 2016.

The workaround has been to change the js client source code to not use web sockets but we are not convinced at all.

It seems that the previous SignalR version had a fallback method in such a case and that it was used by iOS: I have understood that you removed such an ability but can we simply re-implement it by ourselves?

**Comment by davidfowl** [comment]
We actually have a work item to implement client fallback https://github.com/aspnet/SignalR/issues/1373. If you need to implement this yourself, you can look at this sample https://github.com/aspnet/SignalR-samples/blob/cd1e20844c47c5da5f51f74a5030c05a88152a8b/ChatSample/ChatSample/wwwroot/index.html#L75
