### ISSUE TITLE
How do I specify the subprotocol to use with ClientWebSocket

### ISSUE THREAD

**Issue by andylyonette** [aspnet/SignalR#1477]
Hi,

Sorry, this isn't strictly SignalR related but the WebSockets issues are closed.  I can't work out how to specify the sub protocol when creating a client connect to a websocket endpoint.  Is this possible like it is with this JavaScript client? (https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications)

Thanks,
Andy

**Comment by anurse** [comment]
> the WebSockets issues are closed

Issues with the WebSocket middleware should be posted in https://github.com/aspnet/Home, as described in the issue closing the WebSockets tracker: https://github.com/aspnet/WebSockets/issues/216

> I can't work out how to specify the sub protocol when creating a client connect to a websocket endpoint

If you're referring to setting the WebSockets subprotocol from the SignalR Client, no this is not possible. The SignalR client is not a general-purpose WebSockets client, it is specific to the SignalR server.

If you're referring to the .NET [`ClientWebSocket`](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocket(v=vs.110).aspx) type, you can use the [`AddSubProtocol`](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocketoptions.addsubprotocol(v=vs.110).aspx) method of the [`Options`](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocket.options(v=vs.110).aspx) property on the `ClientWebSocket`.

**Comment by LGinC** [comment]
ClientWebSocket client = new ClientWebSocket();
client.Options.AddSubProtocol("protocol1");
