### ISSUE TITLE
net45 support for Signalr C# client

### ISSUE THREAD

**Issue by oguimbal** [aspnet/SignalR#1484]
Hello,

Thanks for this wonderful library.

Any plan to support old .net versions for the Microsoft.AspNetCore.SignalR.Client ? (in my case: net452)

Its a bit early to publish desktop apps using newer versions (not everybody has the newest framework versions installed)... 

For what its worth, I only see two dependencies of SignalR.Client that would not support netstandard 1.2: 

- Microsoft.Extensions.Options  (referenced by Microsoft.AspNetCore.SignalR.Common.csproj)
- Microsoft.AspNetCore.Protocols.Abstractions  (referenced by Microsoft.AspNetCore.Sockets.Abstractions.csproj)

Thanks

**Comment by anurse** [comment]
We have no plans to support anything below .NET Standard 2.0 (which is .NET 4.6.1). The dependencies you reference that require .NET Standard 2.0 also happen to be extremely core dependencies :). In general, ASP.NET Core (including the SignalR Client library) requires a minimum of .NET Standard 2.0.

**Comment by davidfowl** [comment]
Feel free to fork and port it down level but we have no plans to support it.
