### ISSUE TITLE
Strategies for handling flaky connections?

### ISSUE THREAD

**Issue by pardahlman** [aspnet/SignalR#1488]
Based on code for `HubConnection`, [an error is thrown](https://github.com/aspnet/SignalR/blob/dev/client-ts/signalr/src/HttpConnection.ts#L154) if the connection does not have the correct `ConnectionState` when calling `send`.

My first thought was to check the connection state before making the call, but that property is private. This got me thinking: what is the strategy to handle flaky connections? Will the connection try to re-connect or is it up to the application to `stop` the connection and create a new one? If the connection reconnects, how can I get a notification that the connection is re-established again? Is there any documentation or discussions you can point me to? Thanks a bunch!

**Comment by davidfowl** [comment]
In the alpha the user has to do it manually, there's no concept of auto-reconnect, this will be coming later https://github.com/aspnet/SignalR/issues/1057. As of right now, when the disconnected event fires, you have to reconnect as connections aren't re-usable in the alpha.

**Comment by pardahlman** [comment]
Thanks, it makes a lot of sense. I think we can close this and I'll keep an eye on #1057 👍
