### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SabirHossain** [aspnet/SignalR#1490]
Object reference not set to an instance of an object. signalr-client-1.0.0-alpha2-final.js:494:32

**Comment by BrennanConroy** [comment]
Could you provide any other information?

**Comment by SabirHossain** [comment]
If anything fails on the Hub and if you forget to catch the fail then the
error will appear on the client side console.. Ex. I was trying to save
some data on the database using EF Core just for test I didn't use any
'try' and 'catch' and after complete the database action I was also calling
a client side method but when I was debugging I saw after the database
changes fail it don't execute the client side method as usual but then why
the client side error happened?  [aspnet/SignalR] Object reference not set
to an instance of an object (#1490)

**Comment by BrennanConroy** [comment]
The "Object reference not set to an instance of an object" is an error thrown from your Hub. We could probably clean up the client side log a little to make that more clear

**Comment by SabirHossain** [comment]
Yes you are right, I'm sorry for inconvenience, the problem was in database
updating in the Hub. We need a better reference for .net core 2.0 and
signalr-alpha2. the old documention have some deprecated coeds. Thank you.

**Comment by davidfowl** [comment]
We should fix how we expose errors on the client side.

**Comment by alexzaytsev-newsroomly** [comment]
@davidfowl the current way is not so bad, i actually liked being able to see server-side errors on the client while debugging; what would be nice if the console would indicate that this happened on the server; further, it would be great if we could elect to opt-out of this for prod builds.

**Comment by davidfowl** [comment]
That's what this bug is about, improving that error experience. It should be wrapped in a specific exception type. That might be enough to distinguish.

**Comment by JamesNK** [comment]
In the .NET client the error comes back as a string on `CompletionMessage`.

https://github.com/aspnet/SignalR/blob/1790d6bdf088bab120cd14912d6d625d983fb077/test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs#L452

What we could do is prepend some text to it to give it some more context, i.e. `An error occurred invoking method "MethodThatThrows" on the server: BOOM!`

**Comment by BrennanConroy** [comment]
Yeah, I think all we need is a little info wrapped around the error message. It's the same in the js client

**Comment by JamesNK** [comment]
Fixed https://github.com/aspnet/SignalR/commit/846432c9ac4599cbd24ceac6e756627d3f1859c7
