### ISSUE TITLE
Types with embedded references are not supported in this version of your compiler

### ISSUE THREAD

**Issue by racamp101** [aspnet/SignalR#1494]
Trying to compile I get this 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0619	'ReadOnlySpan<byte>' is obsolete: 'Types with embedded references are not supported in this version of your compiler.'	Microsoft.AspNetCore.SignalR.Common(netcoreapp2.1)	C:\Users\Downloads\SignalR-dev (2)\SignalR-dev\src\Microsoft.AspNetCore.SignalR.Common\Internal\Encoders\Base64Encoder.cs	13	Active

and I also see this:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.	Microsoft.AspNetCore.SignalR.Common	C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	135	

any ideas?

**Comment by anurse** [comment]
Make sure you run `build.cmd` and that `C:\Users\[username]\.dotnet\x64` is in your `PATH` variable. See https://github.com/aspnet/SignalR/blob/dev/docs/GettingStarted.md fore more.

**Comment by racamp101** [comment]
trying to run that I get this:

C:\Users\.dotnet\buildtools\korebuild\2.1.0-preview2-15707\modul
es\vstest\module.targets(119,5): error : Run exited with a non-zero exit code: C
:\Users\.dotnet\x64\dotnet.exe C:\Users\Download
s\SignalR-dev (2)\SignalR-dev\benchmarks\Microsoft.AspNetCore.SignalR.Microbench
marks\bin\Debug\netcoreapp2.0\Microsoft.AspNetCore.SignalR.Microbenchmarks.dll *
 --validate-fast [C:\Users\campbroe.TMGOLF\.dotnet\buildtools\korebuild\2.1.0-pr
eview2-15707\KoreBuild.proj]
    115 Warning(s)
    1 Error(s)

Time Elapsed 00:04:36.79
dotnet.exe failed with exit code: 1
At C:\Users\.dotnet\buildtools\korebuild\2.1.0-preview2-15707\s
cripts\common.psm1:11 char:9
+         throw "$cmdName failed with exit code: $exitCode"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit c
   ode: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1

**Comment by racamp101** [comment]
ran it and got this:

```
C:\Users\camp\.dotnet\buildtools\korebuild\2.1.0-preview2-15721\modul
es\vstest\module.targets(106,5): error : Test group UnitTests/netcoreapp2.1 fail
ed with exit code '1'. [C:\Users\campbroe.TMGOLF\.dotnet\buildtools\korebuild\2.
1.0-preview2-15721\KoreBuild.proj]
    115 Warning(s)
    1 Error(s)

Time Elapsed 00:05:12.37
dotnet.exe failed with exit code: 1
At C:\Users\camp\.dotnet\buildtools\korebuild\2.1.0-preview2-15721\s
cripts\common.psm1:11 char:9
+         throw "$cmdName failed with exit code: $exitCode"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit c
   ode: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1
```

**Comment by racamp101** [comment]
@davidfowl  why did you close this??

**Comment by anurse** [comment]
> Test group UnitTests/netcoreapp2.1 failed with exit code '1'

This means that one or more unit tests failed. The actual errors will be somewhere earlier in the log. Also, even though tests fail, you should be able to open the solution in Visual Studio now and build/run unit tests from there.

**Comment by racamp101** [comment]
I tried to do run in vs and I still get the errors I reported in original post

**Comment by anurse** [comment]
> I tried to do run in vs

To be clear, that's after you updated your `PATH` environment variable as described above (and in the Getting Started guide)? That should resolve the "The current .NET SDK does not support targeting .NET Core 2.1" error.

**Comment by racamp101** [comment]
yes ive updated my path variable

**Comment by anurse** [comment]
That's very odd that it would be updated and still causing this issue. Can you look at the `global.json` file in the repo root and ensure that there is a directory under `C:\Users\[your username]\.dotnet\x64\sdk` matching the version number listed in that file? Also, it might be useful to check the .NET SDK version Visual Studio sees by running `dotnet --info` in the Package Manager Console (View > Other Windows > Package Manager Console)

**Comment by aklette** [comment]
Project Properties, Build Advanced, Language Version: C# latest minor version (latest).
On VS2017 15.8.1 this gave me C# 7.3 and above problem solved.
