### ISSUE TITLE
How to know clients connectionstate?

### ISSUE THREAD

**Issue by olofd** [aspnet/SignalR#1496]
How do I with the js-client subscribe to changes in connectionState?

Previous version of SignalR did some reconnect-logic for the user.
But if now I need to implement this myself, that's fine, but how do I actually know when to reconnect?

Do I need to implement my own "heartbeat"-hub?

**Comment by anurse** [comment]
We're going to be adding automated reconnect in SignalR core. As part of that, we'll be looking at events to signal changes in connection state. However, note that we do not plan to do any server or client-side buffering, so you'll need to do that yourself.

See https://github.com/aspnet/SignalR/issues/1057 for more info.

Closing this so we can keep discussion on reconnection to one place :).
