### ISSUE TITLE
TS Compilation Errors in ServerSentEventsTransports.ts

### ISSUE THREAD

**Issue by MisterJames** [aspnet/SignalR#15]
There are multiple compilation errors project `TypeScript Virtual Projects`:

 - Cannot fine name `EventSource`
 - Type `Promise<{}>` is not assignable

These are referenced in via the sample apps (ChatSample, SocketsSample) and unloaded these projects allows you to build.

**Comment by moozzyk** [comment]
I believe this is fixed now.
