### ISSUE TITLE
Use custom authorization attribute on hub

### ISSUE THREAD

**Issue by mmikirtumov** [aspnet/SignalR#1500]
We are using custom authentification middleware and authorization action filter on controllers. 
Can we use any filter, custom authorization attribute or any other custom mechanism to authorize request to hub?

**Comment by anurse** [comment]
You can use [Authorization Policies](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies) for custom authorization between MVC and SignalR. Policies are preferred over custom filters as they are a first-class feature of `AuthorizeAttribute`

**Comment by mmikirtumov** [comment]
Thank you @anurse
 
We use our custome authentication mechanism and custom authorization filter. We would like to find the way to use filter instead of create new AuthorizeAttribute. 

When we set AuthorizeAttribute, system throws exception:
`No authenticationScheme was specified, and there was no DefaultChallengeScheme found.`

When we set Bearer schema in AuthorizeAttribute, we recieve
`No authentication handler is configured to authenticate for the scheme: Bearer`

**Comment by davidfowl** [comment]
You want to write an authentication policy. That way it can be shared across frameworks without using an MVC specific filter.  What exactly are you trying to do?

**Comment by mmikirtumov** [comment]
Thank you @davidfowl 

We do not have authetication policy and are using our own custom authentication middleware. We want to use Authorize attribute without using `app.UseAuthentication()` standard middleware, but we cannot implement due to reasons mentioned above.

May be we can use some other mechanisme (non AuthorizeAttribute), to authorize requests.

We have already built authentication and authorization mechanism (in controllers) with rich features and it will be very hard to change it.

**Comment by davidfowl** [comment]
Even if you have your own authentication system you need to hook into what SignalR understand if you want the attribute to work. Otherwise you're going to end up writing something custom in the hub itself. There is no filter equivalent.
