### ISSUE TITLE
How to access context outside of hub?

### ISSUE THREAD

**Issue by racamp101** [aspnet/SignalR#1503]
I need to access the user outside the hub. I can user Context inside the hub just fine but if I try to use IHttpContextAccessor from a class the user is no longer available. Is there another way to get the correct context?

I see posts about injecting IHubContext<hubname> but I cant access it this way I just need the context.user and using that would cause a circular ref.

**Comment by anurse** [comment]
Have you registered `IHttpContextAccessor` in the DI container? You have to register it manually: https://github.com/aspnet/Hosting/issues/793

**Comment by anurse** [comment]
The User property is populated by calling `HttpContext.Authentication.AuthenticateAsync`. SignalR will call this on your behalf for Hubs with the `[Authorize]` attribute, as will MVC actions/controllers with the `[Authorize]` attribute. If you want the user identity in other requests, you need to call it manually. The value is cached as well so it's safe to call it even if SignalR will run later in the middleware pipeline (SignalR will just use the cached value).

**Comment by davidfowl** [comment]
@racamp101 where are you trying to get access to the user and which user?

**Comment by racamp101** [comment]
that HttpContext.Authentication.AuthenticateAsync is async saying that sometimes I'm able to access the user is it possible its not finishing sometimes before the method I'm trying to access it in runs?

Im trying to access it in a class that is injected into my hubs constructor.

**Comment by davidfowl** [comment]
You would need to use the IHttpContextAccessor https://www.strathweb.com/2016/12/accessing-httpcontext-outside-of-framework-components-in-asp-net-core/

**Comment by racamp101** [comment]
I am using that but the user is only sometimes populated.

**Comment by davidfowl** [comment]
What transport are you using and how are you asking for the user?

**Comment by anurse** [comment]
> that HttpContext.Authentication.AuthenticateAsync is async

Yes, you would need to use it from an async method.

> Im trying to access it in a class that is injected into my hubs constructor.

Have you considered passing the data into the service that your hub uses? If the Hub is the one consuming this service, it's the one with access to the user data. The service should accept it as input rather than loading it automatically from an additional dependency. `IHttpContextAccessor` is only really there as a stop-gap solution when you aren't able to use DI and method parameters to flow the data you need.

**Comment by anurse** [comment]
Closing this as we haven't had any feedback since the last message. Please feel free to comment if you still have questions, we can always re-open or file a new issue if there's a problem to be resolved.

**Comment by liangshiw** [comment]
I also encountered this problem. When using LongPolling, injecting IHttpContextAccessor in the hub and get `user.Claims` in httpcontext.  sometimes loses information.

**Comment by davidfowl** [comment]
Don't do that, use the GetHttpContext on the HubConnectionContext.

**Comment by liangshiw** [comment]
I have defined a global shared session in my architecture. I need to set the value of the session when the request comes.I chose to use IHttpContextAccessor It works fine for mvc and webapi applications, 

https://github.com/aspnetboilerplate/aspnetboilerplate/blob/e0ded5d8702f389aa1f5947d3446f16aec845287/src/Abp.AspNetCore/AspNetCore/Runtime/Session/AspNetCorePrincipalAccessor.cs#L11

but the context state is lost in signalr long polling mode. This will result in the correct value not being obtained using a custom session. 
`var userId = AbpSession.UserId;`
![image](https://user-images.githubusercontent.com/16813853/48182200-527e2180-e365-11e8-93ef-d40baa48c6b5.png)


Do you have any good solutions?
