### ISSUE TITLE
Is it OK to use the new version 1.0.0-preview1-final release alongside 2.0 stable packages?

### ISSUE THREAD

**Issue by vladislav-karamfilov** [aspnet/SignalR#1504]
We are developing an application using the latest stable versions of all Microsoft packages except the SignalR package (we're currently using 1.0.0-alpha2-final). I'm thinking of migrating to the new version released today but I'm wondering if it's OK to have 2.1.0-preview1 (transitive) packages alongside 2.0 stable packages? Are there any known or expected issues that we might hit?

**Comment by DamianEdwards** [comment]
Not really. SignalR is part of the ASP.NET Core 2.1 release and is intended to be used with matching bits.

**Comment by vladislav-karamfilov** [comment]
I suspected that this will be the answer. :) We'll be sticking with 1.0.0-alpha2-final release.
Thanks for the quick answer!
