### ISSUE TITLE
How to disable SignalR logging?

### ISSUE THREAD

**Issue by mnmr** [aspnet/SignalR#1505]
We're using the latest dev CI build of SignalR (2.1.0-preview*) and are seeing massive amounts of useless logging from SignalR that interferes with our ability to debug.

Specifically, it appears to log a message every time it sends a message:
2018-02-27 21:56:24.695 [DBG] Sending payload: 233 bytes.
2018-02-27 21:56:24.708 [DBG] Sending payload: 251 bytes.
repeat ad nauseam

Looking at the code, the culprit seems to be this:
`_logger.SendPayload(buffer.Length);`
(located in [WebSocketsTransport.cs](https://github.com/aspnet/SignalR/blob/32baa655b93b8d64a8d25aa6ad2af288ed9abc54/src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/WebSocketsTransport.cs) around line 221)

Can we please add a mechanism to turn spammy logs like this off? And might I suggest to demote this spectacularly uninformative message to Verbose or lower?

**Comment by anurse** [comment]
It's controlled via the Logging configuration, just as with all other logging in the ASP.NET Core stack. The log message is already only logged at the `Debug` level. Have you turned up the verbosity of the Logging system?

**Comment by mnmr** [comment]
I'm using Serilog and log everything (Verbose and up). I have the following in Startup to pipe ASP.NET logging into Serilog:
`public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, ILogFactory logFactory)
        {
            loggerFactory.AddSerilog(logFactory.CreateLogSource("AspNetCore"));
            ...`
ILogFactory is our own thing; it creates and configures the default ILogger, and every call to CreateLogSource returns the same instance (enriched with the log source provided).

The above works great - I get a lot of insight into what is happening in the ASP.NET pipeline and what EF Core is doing. However, for a web application that pushes out price updates (think Nasdaq), having a log message every time you publish a bit of data is just not going to work.

I don't have any special ASP.NET Core logging configuration. We're reading a custom "logging.json" file and I'm using that in the ILogFactory implementation to configure Serilog and the sinks (targets) we use.

**Comment by davidfowl** [comment]
You need to turn off debug logs for SignalR. You have to filter if you aren’t then you will get spam and I assure your that’s not the only set of spam you’ll get.

**Comment by mnmr** [comment]
@davidfowl That sort of was my question/request - how do I turn off debug logs from SignalR? The key point here is that I'd like the freedom to keep debug logs from other sources. I'm also not keen on having to filter ALL my log messages in the Serilog pipeline, as that will incur unwanted overhead.

Mind you, I still think "debug logging" on every message sent is fundamentally bad.

**Comment by davidfowl** [comment]
We can change those logs to trace (but that's just the next level you'd have to filter) and they are useful when we want to help you diagnose issues in your signalr application.

As for how you filter, if you're not using the default logger factory (and it looks like you might be using it) then you'd need to go via serilog. Otherwise you can just use the standard ASP.NET configuration file to disable the logs for the Microsoft.AspNetCore.SignalR prefix or call the AddFilter method to do the equivalent but imperatively.

See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-filtering for more information.

**Comment by anurse** [comment]
> We can change those logs to trace

Those actually should be Trace level. They're rarely useful to anything other than automation, which is the bar between Debug and Trace IMO. I'll send a quick PR.

**Comment by mnmr** [comment]
Thank you all for some quick action on this!
