### ISSUE TITLE
Remove console logs when building for production (JS Client)

### ISSUE THREAD

**Issue by isaac873** [aspnet/SignalR#1509]
Hello,

I'm wondering if there's a way to stop signalr.js from outputting logging info to the console (e.g. "Information: Using HubProtocol 'json'." "Information: Connection disconnected." among a couple of others). 

I've tried building/serving my app in production mode but they're still showing up.

Cheers.

**Comment by moozzyk** [comment]
You can pass [LogLevel](https://github.com/aspnet/SignalR/blob/dev/client-ts/signalr/src/ILogger.ts#L4) in the [options](https://github.com/aspnet/SignalR/blob/dev/client-ts/signalr/src/HttpConnection.ts#L14)

**Comment by anurse** [comment]
Closing as the question has been answered. Feel free to comment further if you need clarification! We can always re-open it if there is an issue to fix.

**Comment by isaac873** [comment]
Perfect! That's exactly what I was looking for.

Cheers
