### ISSUE TITLE
404 in negotiate if useSpa is before signalr 

### ISSUE THREAD

**Issue by JanEggers** [aspnet/SignalR#1511]
i dont know if this is signalr issue or spa services so @SteveSandersonMS may also have a look.

i just tried out signalr preview1 final.

if I have this in startup everything works as expected:

```
            app.UseSignalR(routes =>
            {
                routes.MapHub<TestHub>("/hubs/test");
            });

            app.UseSpa((o) =>
            {
                if (env.IsDevelopment())
                {
                    o.UseProxyToSpaDevelopmentServer("http://localhost:4200");
                }
            });
```

but if I do this i get 404 in client:

```
            app.UseSpa((o) =>
            {
                if (env.IsDevelopment())
                {
                    o.UseProxyToSpaDevelopmentServer("http://localhost:4200");
                }
            });

            app.UseSignalR(routes =>
            {
                routes.MapHub<TestHub>("/hubs/test");
            });
```

**Comment by buvinghausen** [comment]
This is not an issue the spa middleware redirects *everything* to index.html if the previous middlewares do not handle the request.

**Comment by buvinghausen** [comment]
That is how deep linking to your SPA routes occurs....

**Comment by anurse** [comment]
As @buvinghausen indicates, it sounds like `UseSpa` is what we call a "terminal middleware" in that requests never pass beyond it. If it makes sense to make the Spa middleware non-terminal, that would be a discussion that would have to happen in the repo for that middleware.

I'm closing this issue as there isn't a SignalR issue here. Feel free to comment further if you need clarification, we can always re-open the issue if there is something for SignalR to fix :)

**Comment by buvinghausen** [comment]
@anurse I do think there should be some discussion on ways to configure the UseSpa middleware to ignore certain route prefixes (things like /api, /hubs, /swagger, etc.) but this is definitely not the place for that discussion :)
