### ISSUE TITLE
1.0.0-preview-1 CORS?

### ISSUE THREAD

**Issue by olofd** [aspnet/SignalR#1512]
Just upgraded to the latest bits, and I can't seem to get CORS working?
Any known issues about this?

**Comment by olofd** [comment]
Not CORS, but seem to get Method not allowed.

**Comment by olofd** [comment]
Yepp. The alpha 2 npm-package does not seem to work with the preview 1 server.
Running the client code form preview-1 here on github, and that works.

**Comment by fschlaef** [comment]
Warning, the client for preview1 is no longer named `@aspnet/signalr-client` but `@aspnet/signalr`
More info : https://github.com/aspnet/SignalR
