### ISSUE TITLE
Doesn't connect with xamarin forms

### ISSUE THREAD

**Issue by neville-nazerane** [aspnet/SignalR#1518]
When I try the following

1. Create a new Xamarin Forms project
2. Update all release packages
3. Run `Install-Package Microsoft.AspNetCore.SignalR.Client -Version 1.0.0-preview1-final` on the portable project
4. Run the android project

I find the following error:
> "Could not load assembly 'System.Threading.Tasks.Extensions' during startup registration". 

I have tried installing the latest pre-release of `System.Threading.Tasks.Extensions`. Still no change in the error.

**Update**
I have found the same error on xamarin versions "2.5.0.122203", "2.5.0.280555", "2.5.1.317207-pre1"

I get the same error with web socket client nuget as well for "2.5.0.280555" and "2.5.1.317207-pre1" but NOT on "2.5.0.122203".

**Comment by davidfowl** [comment]
Are you using the latest version of Xamarin?

**Comment by shao200** [comment]
I too

**Comment by UncleSamSwiss** [comment]
Same here.

**Comment by FrancoisM** [comment]
Wrt the AOT compilation error, I've put together a simple [repro](https://github.com/FrancoisM/AotTests/tree/master) on github and explained the issue on [stackoverflow](https://stackoverflow.com/questions/49646078/xamrin-ios-aot-compilation-fails-from-mac-but-builds-fine-from-pc).

**Comment by davidfowl** [comment]
Sweet!

**Comment by davidfowl** [comment]
Closing see https://github.com/aspnet/SignalR/issues/1886
