### ISSUE TITLE
'Parameter count mismatch' after invoking hub from typescript client

### ISSUE THREAD

**Issue by JonasMH** [aspnet/SignalR#152]
I'm reporting what i think is a bug, where after invoking a hub the server responds with 'Parameter count mismatch'.

The hub:

```
public class NotificationHub : Hub, INotificationHub
{
	private readonly IHubNotificationService _service;

	public NotificationHub(IHubNotificationService service)
	{
		_service = service;
	}

	public override Task OnConnectedAsync()
	{
		return Task.CompletedTask;
	}

	public override Task OnDisconnectedAsync(Exception exception)
	{
		_service.ClientDisconnected(Context.ConnectionId);
		return Task.CompletedTask;
	}

	public Task Subscribe(string topic)
	{
		string id = _service.ClientSubscribed(new SubscriptionUpdate(
			topic,
			Context.User.Identity.Name,
			Context.ConnectionId));

		return Task.CompletedTask;
	}
}
```

Client side (angular2, typescript): 

```
public subscribe(topic: string): void {
  this.hubConnection.invoke("subscribe", {topic: topic});
}
```

The hub's Constructor, OnConnectedAsync and OnDisconnectedAsync gets called as expected when a server connects and disconnects, but as soon as i try to invoke it, the following happens (websocket frames):
Request: `{"Id":"0","Method":"subscribe","Arguments":[{"topic":"/someTopic/"}]}`
Response: `{"Result":null,"Error":"Parameter count mismatch.","Id":"0"}`

The connection does not get shut down or anything, but i get the 'Parameter count mismatch' and the subscribe method on the hub is never called. Any suggestions?

**Comment by davidfowl** [comment]
Try changing the code to do:

```C#
this.hubConnection.invoke("subscribe", topic);
```

You're not passing an object on the server side, you're passing a string.

**Comment by moozzyk** [comment]
@JonasMH - can you provide a stack trace from the server. While what @davidfowl says is correct - you have a type mismatch - something else seems going on here. I tried to repro this and the server threw a different exception and close the connection. The exception I received was a parse error because the expected parameter type is String so SignalR tries to read the value as string but it encountered a json object.

**Comment by JonasMH** [comment]
@moozzyk On the server nothing gets thrown, it's just running as normal
@davidfowl Just tried and nothing changed, still the same response as before.

Here's some more information that may be helpful:"

Microsoft.AspNetCore.SignalR version 1.0.0-preview1-23180
netcoreapp1.0
win10-x64
Aspnet, entityframework and so on are on version 1.2.0-*

**Comment by davidfowl** [comment]
> @davidfowl Just tried and nothing changed, still the same response as before.

Can you provide a running example? We can't reproduce this locally. If you could narrow it down to remove all of the dependencies, that would be better as well.

**Comment by JonasMH** [comment]
@davidfowl Sure, just created a small web-server that re-creates it. I only included the server side, since it's what seems to be causing the issue
[WebApplication1.zip](https://github.com/aspnet/SignalR/files/731005/WebApplication1.zip)
Let me know if you want to have uploaded another way

**Comment by davidfowl** [comment]
@JonasMH a github repository would be ideal.

**Comment by JonasMH** [comment]
Of couse, haha, my bad :) Here you go https://github.com/JonasMH/Signalr-issue-152

**Comment by davidfowl** [comment]
I think we'd need the client code as well.

**Comment by JonasMH** [comment]
That gonna be a bit harder since it's seperate app, but i'll get right on it. But unless the protocol has been changed, it should be possible to use another client and get the same results

**Comment by JonasMH** [comment]
Just added a client to the repo

**Comment by BrennanConroy** [comment]
Try changing the invoke to `Subscribe` to match the casing of the function you want to call
https://github.com/JonasMH/Signalr-issue-152/blob/master/client/src/NotificationService.ts#L25

**Comment by davidfowl** [comment]
I see the bug:

https://github.com/aspnet/SignalR/blob/c997ea81650420ed42fca3d1bdedb03527ad711f/src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs#L32-L34

The parameter names dictionary is case sensitive and the method lookup isn't. 

https://github.com/aspnet/SignalR/blob/c997ea81650420ed42fca3d1bdedb03527ad711f/src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs#L358

This returns 0 args but the method name is found

We need to store a single dictionary with a method descriptor instead of having 2 dictionaries.

**Comment by JonasMH** [comment]
@BrennanConroy Yep that fixed it! Nicely spotted :)

@BrennanConroy and @davidfowl thanks for the help

**Comment by davidfowl** [comment]
Fixed
