### ISSUE TITLE
Type-constrain JSON parser in Redis scale-out

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1521]
The JSON parser we use for transferring messages between servers should be type-constrained.

**Comment by anurse** [comment]
The quickest/easiest way to deal with this is to just disable Type Name Handling by default and expose the options for users to configure if they need to have full-fidelity types.

**Comment by anurse** [comment]
We'll need this for preview2

**Comment by davidfowl** [comment]
Closing this in favor of https://github.com/aspnet/SignalR/issues/1800
