### ISSUE TITLE
Publish signalr.js on cdnjs.com

### ISSUE THREAD

**Issue by madskristensen** [aspnet/SignalR#1525]
This will enable LibMan to provide the script file so developers don't have to use npm

**Comment by Eilon** [comment]
cc @jbagga FYI because she's looked into this for some of our other scripts.

**Comment by anurse** [comment]
Ugh, I hope we don't get too bogged down publishing to a bunch of different CDNs. If cdnjs is the primary CDN the community uses now, then that's OK. I've just bee using unpkg.com to get files out of the package (though that doesn't really have a proper SLA, so recommending that to customers is probably not idea)

**Comment by Eilon** [comment]
We use NPM, CDNJS, and the ASP.NET CDN... for now 😄

**Comment by anurse** [comment]
> for now

That's my concern. I'd rather we just published to NPM and build tools to publish off of that. Anyway, however we implement it, I'm not too worried about where we publish as long as we can automate it.

**Comment by anurse** [comment]
Looks like we qualify for cdnjs based on GitHub stars: https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library

**Comment by Eilon** [comment]
Oh, and *some* packages need to go to NuGet.org as Content packages, but that applies to stuff that needs to go to old-style CSPROJ's, such as MVC 5.x, Web Forms, etc.

**Comment by anurse** [comment]
It would be nice to see if we can drive all that from the NPM packages somehow so we only have to produce one set of things out of the repos and then have a tool push those packages to all the places they need to go.

**Comment by Eilon** [comment]
Different packages release at a different cadence. E.g. the jQuery unobtrusive validation/ajax stuff ships completely separately from everything else. The SignalR stuff presumably sim-ships with SignalR (and ASP.NET Core and .NET Core).

I'm certainly open to suggestions on anything we can do to make the process easier.

**Comment by jbagga** [comment]
For cdnjs, adding an npm hook to package.json should allow auto-update. https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md
I don't think publishing to npm can be automated though https://docs.npmjs.com/getting-started/publishing-npm-packages#how-to-update-a-package
Microsoft CDN and NuGet will need to be manual too I am guessing. Package creation for NuGet can be automated with an MSBuild task but not publishing.
Here's the issue I am working on https://github.com/aspnet/jquery-validation-unobtrusive/issues/47

**Comment by anurse** [comment]
This is a release task, we should look at doing it in Preview 2.

**Comment by cecilphillip** [comment]
Just throwing in my 2c here. [jsDelivr](https://www.jsdelivr.com/package/npm/@aspnet/signalr) and [UnPkg](https://unpkg.com/@aspnet/signalr) are two NPM CDNs that I've been using for demos. They're also the recommended CDNs for the VueJS project

**Comment by Eilon** [comment]
@cecilphillip I think we'll need to limit the number of CDNs that we actively publish to in order to keep things manageable, but certainly others can go further with additional CDNs.

**Comment by anurse** [comment]
@Eilon Those are CDNs that just auto-host everything on NPM, so we're already there :). I've used UnPkg a few times.

**Comment by anurse** [comment]
@mikaelm12 can you find out what we have to do to host on cdnjs.org and report back with your findings? I'd imagine we need to get approval from them first. @jbagga may have already done some work here with our jQuery Unobtrusive Validation package.

**Comment by anurse** [comment]
(Of course, this is at a lower priority level than issues that involve code changes, but when you have downtime, etc. ;))

**Comment by jbagga** [comment]
You have to open an issue with cdnjs with a request to host your package and then send a PR to add it there https://github.com/cdnjs/cdnjs/issues/7176

**Comment by Eilon** [comment]
@muratg / @anurse / @mikaelm12 - any action today for this?

**Comment by mikaelm12** [comment]
Starting the process https://github.com/cdnjs/cdnjs/issues/12694

**Comment by anurse** [comment]
@davidfowl you mentioned that libman is going to support unpkg, so is this still relevant? If not, we should withdraw the request with cdnjs.

**Comment by anurse** [comment]
Even if we don't need it for LibMan, we've got a couple customers asking about it. I think we should just get this done.

**Comment by davidfowl** [comment]
Are we going to do it every release? If no then we shouldn’t bother

**Comment by anurse** [comment]
Once you add it to CDNjs they automatically update from your NPM module. But if we ever restructure our module we'd have to update that. So meh, maybe we'll just leave it out and wait and see what customers want :). Unpkg is fine for now.

**Comment by anurse** [comment]
@mikaelm12 can you close the issue on CDNjs, I don't have the power ;)

**Comment by mikaelm12** [comment]
https://github.com/cdnjs/cdnjs/issues/12694 Closed (For now)
