### ISSUE TITLE
Rename StreamAsync to StreamAsChannelAsync

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1526]
We don't want to burn the generic `StreamAsync` name on the Channel reader overload. Instead, we should make the StreamAsync overload exist when IAsyncEnumerable lands.

We could also consider adding StreamAsObservable with this approach.

/cc @anurse

**Comment by anurse** [comment]
Public API change, and super easy. Nominate for preview 2

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/62956530aee33c79878e161bc2972e0dd9ddc1de
