### ISSUE TITLE
await SendAsync does not wait for message to be sent

### ISSUE THREAD

**Issue by olofd** [aspnet/SignalR#1527]
I know this is not perfect code, but I had an old application that I upgraded to SignalRCore
and this application does this:

```csharp
            await _competitionHubContext.Clients.Group(HubEvent.CompetitionChanged + "::" + competitionChangedModel.Competition.CompetitionId)
                .SendAsync("competitionUpdated", competitionChangedModel.Competition);

            //Avoid sending all teams:
            competitionChangedModel.Competition.Teams = null;
//...send to other groups
```

The listeners in the group on line one receives teams == null, the nullifying I'm doing gets included.
That was not the case in old signalr, and the await, to me at least, implies that I'm awaiting the message to be dispatched? Or what am i awaiting?

Not saying this is wrong, the code here is not perfect, I see that. But from an API standpoint the awaiting is a bit confusing.

**Comment by BrennanConroy** [comment]
I think we accidentally fixed this a couple weeks ago. The dev builds should now serialize the data before returning from SendAsync.

We should add a test for this, keeping the issue open to track that

**Comment by BrennanConroy** [comment]
We would write the HubMessage to the channel then return, and another thread would read from the channel and serialize it which raced with whatever you did next in your hub, like setting a value on the object you passed to SendAsync

**Comment by davidfowl** [comment]
Ah!

**Comment by olofd** [comment]
Cool. Then I know it is not suppose to work like that. Felt wrong. Do you have nightlys? Point me to some docs about installing and running it?

Otherwise I’ll just serialize and deserialize to get new references for now.

PS. Tell the lang-guys to give me some better primitives for immutability! ☺️

**Comment by BrennanConroy** [comment]
This should be good https://github.com/aspnet/Home#builds
If you have any questions feel free to ask

**Comment by olofd** [comment]
Nooo. Installed https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-osx-x64.pkg. Added a NuGet.config pointing to VNext myget-feed. Changed my references to version 2.1.0-preview2-30230. Now I get `WebService.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.1.0-preview2-26227-01)`

`WebService.csproj : error NU1102:   - Found 39 version(s) in AspNetVNext [ Nearest version: 2.1.0-preview2-26225-03 ]
WebService.csproj : error NU1102:   - Found 24 version(s) in nuget.org [ Nearest version: 2.1.0-preview1-26216-03 ]`

for all my restores.

Would love to use some early bits. But I have to say that versioning I still a bit confusing to my.
Like, I got a couple of installed SDKs by now and I'm still unsure of the which one is older, like:
dotnet --list-sdks:
`2.1.4 [/usr/local/share/dotnet/sdk]
2.1.300-preview1-008174 [/usr/local/share/dotnet/sdk]`

Is 2.1.4 older? It seems to have been there longer than the other one, but it must be newer??

And how do I set default version on the CLI without adding some weird global.json?
Can't I just say like `dotnet set default 2.1.300-preview1-008174`?

DLL-hell is coming, so I'm backing of there.
Just wanted to give my feelings around the tooling here.

But otherwise. Great work. And I would not bother if I don't believe that this can turn out terrific!

**Comment by anurse** [comment]
> Is 2.1.4 older?

Yes, each version number segment should be treated as a separate integer, so `300` is greater than `4` and thus `2.1.300` is later than `2.1.4`

> And how do I set default version on the CLI without adding some weird global.json?

That would be a question for the github.com/dotnet/cli repo. `global.json` is the only way to do this right now.

It looks like there isn't an issue here any more, please feel free to comment if I'm misunderstanding. I'm closing this, we can always re-open it or file something new if there's an issue for SignalR to solve.
