### ISSUE TITLE
Plans to port PersistentConnection

### ISSUE THREAD

**Issue by JakenVeina** [aspnet/SignalR#1528]
I'm entirely new to SignalR, so feel free to tell me I'm crazy.

Are there any plans to port PersistentConnection from .NET over to Core? Or is there a newer alternative I should look into for implementing a custom protocol (not Hubs)?

Specifically, I'd like to have a protocol that's more of an "event subscription" model, and I'd like it to integrate a little more fluently into a Web API, where all the real work happens.

**Comment by davidfowl** [comment]
@JakenVeina there's a lower layer that hubs are built on top of that we're currently calling Sockets. There's an example here:

https://github.com/aspnet/SignalR/blob/9786e28f52a870aa2ecd15d092d393c9de150442/samples/SocketsSample/Startup.cs#L21

https://github.com/aspnet/SignalR/blob/9786e28f52a870aa2ecd15d092d393c9de150442/samples/SocketsSample/Startup.cs#L67-L70

https://github.com/aspnet/SignalR/blob/9786e28f52a870aa2ecd15d092d393c9de150442/samples/SocketsSample/Startup.cs#L44

https://github.com/aspnet/SignalR/blob/9786e28f52a870aa2ecd15d092d393c9de150442/samples/SocketsSample/EndPoints/MessagesEndPoint.cs

>  Or is there a newer alternative I should look into for implementing a custom protocol (not Hubs)?

Hubs are implemented as a https://github.com/aspnet/SignalR/blob/9786e28f52a870aa2ecd15d092d393c9de150442/src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs 

> Specifically, I'd like to have a protocol that's more of an "event subscription" model, and I'd like it to integrate a little more fluently into a Web API, where all the real work happens.

I'm not entirely sure what you mean by this but hopefully that helps. 

There's also a plan to provide something thin like this but there are some challenges https://github.com/aspnet/SignalR/issues/515

**Comment by JakenVeina** [comment]
From a high-level, I was thinking something like this:

`GET /api/newsposts`
`GET /api/newspost/{id}`
`PUT /api/newsposts`
`PUT/POST /api/newspost/{id}`
`DELETE /api/newspost/{id}`

This is the structure of an API I'm working on, to support an SPA frontend client. I started down the whole WebSockets/SignalR road because I wanted the ability to have clients notified when a new NewsPost is created, so it can immediately show up on a "News" tab in the app's menu. In my mind (coming from WPF/UWP land) the construct I want is an event, which clients can subscribe to or not. And if I wanted to put that in the context of a Web API, what makes sense to me is something like this:

`/api/events/` (WebSocket/SignalR connection endpoint)
`POST /api/newsposts/events/subscribe/{eventName}`
`POST /api/newsposts/events/unsubscribe/{eventName}`

I could implement a functional equivalent with a Hub...
`
public class EventsHub : Hub<IEventsClient>
{
    public Task Subscribe(string eventName)
        => Groups.AddAsync(Context.ConnectionId, eventName);

    public Task Subscribe(string eventName)
        => Groups.AddAsync(Context.ConnectionId, eventName);

    public void RaiseEvent(string eventName, object eventData)
        => Clients.Group(eventName).RaiseEvent(eventName, eventData);
}
`

But I'd rather not wrap a layer around the RPC model, if it doesn't conceptually represent what I'm doing, and I like the idea of having each API Controller be responsible for managing the events it creates.

Also, at this point, I need to satisfy my curiosity.

**Comment by davidfowl** [comment]
If you're looking for REST and not looking to use a custom client then SignalR isn't for you (or the layer underneath). That looks more like this https://github.com/aspnet/Mvc/issues/6224.

**Comment by davidfowl** [comment]
Actually, now that I think about it, you might just want a hybrid of an API and a Hub for outgoing. How were you planning on handling the outgoing channel? This is a pretty typical pattern today with SignalR. Using MVC for incoming posts and using SignalR for the outgoing channel.

**Comment by JakenVeina** [comment]
That's pretty much exactly it. In the above example, each client (if they want to receive events) must open a long-term connection at `/api/events` and then specify what events it wants to receive. Then, any regular API calls that modify resources will use a singleton service to instruct each active connection on `/api/events` to transmit the given event to anyone who has subscribed to it.

**Comment by davidfowl** [comment]
@JakenVeina what protocol do you want to use for outgoing data? What does the client look like? You need to establish a session id/connection id that the client needs to use to subscribe/unsubscribe and raise events right?

I have an idea kicking around in my head. You want to use SignalR to manage the hard things for you like the connection lifetime, groups,  scale out without exposing the hub protocol on the wire. It's doable but we'd need to think about the end to end with a few concrete examples.

You have a few options for your /api/events end point:
- Do raw websockets and write the thing from scratch
- Use the ASP.NET Core Sockets framework
- Use SignalR for outgoing (RPC) to the client

**Comment by JakenVeina** [comment]
In my mind, the outgoing data should be as close as possible to a regular API response, except it's server-initiated. Meaning, it's just a JSON data object, with an event name attached in some fashion. Maybe as part of the JSON, maybe in a header, maybe just by virtue of setting a source field to `/api/{controller}/events/{eventname}` or whatever matches the original subscription URL.

I figure SignalR is the way to go for the endpoint simply because it abstracts the transport layer, allowing the  app to work with browsers that don't support WebSockets. The `MessagesEndPoint` example in `SocketsSample` seems like it'll work great for this. I'll probably just put a `ConcurrentQueue` on a service that I can stick events into and have an `EventsEndPoint` instance that pulls them off and sends them out.

Unless you've got something else in mind?

**Comment by davidfowl** [comment]
Sounds good to me. As long as you know what you're getting into, sounds like a fine solution!

**Comment by JakenVeina** [comment]
Thanks for your time. :)

**Comment by JakenVeina** [comment]
Client-side, I'll want to wrap around the HttpConnection TS class, yes?

**Comment by davidfowl** [comment]
Yea, just follow what hubs does. You also don't need to use HttpConnection if you want to use pure websockets.

**Comment by JakenVeina** [comment]
Nah, the whole point of using SignalR here is to leverage the fallback behavior.

**Comment by davidfowl** [comment]
I'm super confused. So you want the fallback, but you don't want the JSON payload that signalr uses... 😄. When you finish writing your custom protocol, I'd love to see what it ends up looking like 😄.

**Comment by JakenVeina** [comment]
Not JSON entirely, just the JSON format that the Hubs Protocol uses. It looks like the protocol uses 6 different message types. If I end up making a custom protocol, it'll basically just have 2 message types, `Ping` and `Event`.

The more I look at it, the more I think I'm just being obsessive. I originally was scared to put too much complicated protocol junk in what's supposed to be a simple Web API, but looking at the source code, the protocol doesn't seem all that complicated. 

I'm gonna go ahead and implement this with some Hubs and see how it comes out. I can always rework it later.

**Comment by KPixel** [comment]
@JakenVeina What happens if an event is created while client is temporarily disconnected?

Does the client miss that event? Or do you have some kind of catch-up mechanism?

**Comment by JakenVeina** [comment]
The event system isn't really meant to provide data to the client, just notify the client of changes. Of course, it would be silly to have the client receive an event, then go off to poll the API for data, so each event should include a copy of the changed data, for reference. But, if the connection drops, the client should be able to respond to that and re-poll the API as needed.

**Comment by anurse** [comment]
The complexity of the protocol should scale based on what you do. If all you're doing is sending notifications from server to client, you'll only end up using `Ping` and `Invocation` messages, none of the streaming or completion messages will be used/needed, and using Hubs would give you access to any of the improvements we put into that layer but don't go into the Endpoint layer.

**Comment by JakenVeina** [comment]
I think I'm about to settle on this scheme for presenting WebApi + SignalR to the client.

```
/api/newsposts  GET
/api/newsposts/{id}  GET
/api/newsposts  PUT
/api/newsposts/{id}  PUT
/api/newsposts/{id}  DELETE
/api/newsposts/{eventname}/subscribe  POST
/api/newsposts/{eventname}/unsubscribe  POST
/api/events  SignalR CONNECT

IEventsClient
{
    void RaiseEvent(string eventName, object eventData);
}
```

Where `eventName` is `/api/newsposts/{eventname}`, I.E. the URL used to subscribe to the event.

The only real problem with this is that the connectionId of the SignalR connection would need to be sent to sent to each subscribe/unsubscribe request to the API, and the SignalR TS client doesn't make this value public. Would it be crazy for me to just extract the private `id` field from `HubConnection` and use it anyway? Or even just sub-class `HubConnection` to make it public?

**Comment by anurse** [comment]
I would avoid extracting a private field from our types. Connection IDs are an internal implementation detail and aren't generally designed to be relied upon outside of the server. You could generate your own IDs and have the SignalR Hub assign connections to Groups using those IDs, and send the IDs back to the client. That way you are insulated from us changing how connection IDs work.

> Also, would it be crazy to have an /events endpoint and Hub for each individual controller, instead of one master?

It would be possible, but I would caution you that each SignalR Hub would mean a separate HTTP connection. If you are using Server-Sent Events or Long Polling, browsers heavily limit the number of concurrent connections (to around 6 per "origin", i.e. domain name). So each hub would take one of those connections away for the duration of the SignalR connection. WebSockets are much more generous, as browsers generally allow on the order of 100 concurrent connections there.

In general, I wouldn't use Hubs to partition clients, that's what Groups are for. If you use groups, you could have the Client use SignalR to invoke a "Subscribe" method on the Hub, specifying the events it is interested in, and then the server can add the client to Groups matching the event names. Then when you want to dispatch an event, you simply use the Group to send to all the clients who subscribe.

**Comment by anurse** [comment]
> With all events firing through one Hub, there needs to be some kind of namespace mechanism to distinguish which Controller is generating them

Yes, this would need to be expressed in your payload, but it's just a matter of adding a property to an object or an argument to a method

> Each controller needs to somehow register a list of valid events with the Hub during application startup OR the Hub needs to be able to delegate the validation of an event name to controllers, as each request comes in.

Yeah, if you don't have auth, you'll want to restrict the set of events. These could be managed centrally though and injected into both the Controller and the Hub to ensure you don't have magic strings everywhere.

**Comment by KPixel** [comment]
@JakenVeina I too wanted the connection id to be made public. But after discussing it, I found that it is quite easy to create your own (no extra round-trip needed). I call it "connection key" to avoid confusion.

See #961 for more details.

**Comment by JakenVeina** [comment]
@anurse The actual mechanism for injecting event names into each controller (or, rather, letting them be defined by/within the controller, and extracting them into a service) has been a lot more challenging than I expected, At one point, I was hoping to use MVC's ApplicationModel API to allow controllers to define what events they support as part of their ControllerModel class, then have a service that extracts the info from the model. However, there doesn't appear to be any mechanisms for actually CONSUMING the model, only for adding info to it for MVC to consume.

@KPixel So, your solution was to attach a client-defined key to each connection request url, directly? That should work for me. I'll call it a "subscription token". You can only have one token per connection, so it doesn't present a flooding vulnerability (not any more than connections themselves).

**Comment by KPixel** [comment]
@JakenVeina Indeed.

**Comment by anurse** [comment]
It looks like we've got a solution to your issue here, so I'm closing this issue. Feel free to comment if you still have concerns, we can always re-open the issue :)

**Comment by JakenVeina** [comment]
Thanks for all the time, everyone.
