### ISSUE TITLE
method with return type Task<IObservable<T>> is not recogniced as Streaming method

### ISSUE THREAD

**Issue by JanEggers** [aspnet/SignalR#1534]
im having a gateway that analyses the request and based on the parameters forwards the request to some backend service.

im using the signalr client in my gateway to achive that proxy behavior. what i dont like is that i have to 

`hubConnection.StreamAsync<TResult>("Method").Result;`

because if i await the call and change my hubmethod to return a task then signalr does not recognice it as streaming method.

**Comment by BrennanConroy** [comment]
Just return `IObservable<T>` from your hub

**Comment by JanEggers** [comment]
how can i do that? if i use your signalr client to subscribe to a stream it is always async!

https://github.com/aspnet/SignalR/blob/00da533f109a0f82cf2d9d8af26d0f39666bf0a4/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs#L194

**Comment by davidfowl** [comment]
@JamesNK can you take a look?  

@JanEggers You're invoking StreamAsync from the client right?

**Comment by JanEggers** [comment]
@davidfowl i have a js client that uses this:

https://github.com/aspnet/SignalR/blob/846432c9ac4599cbd24ceac6e756627d3f1859c7/client-ts/signalr/src/HubConnection.ts#L163

that connects to a gateway server with a hub. that gateway hub uses 

https://github.com/aspnet/SignalR/blob/00da533f109a0f82cf2d9d8af26d0f39666bf0a4/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs#L194

to forward the request to the backend.

and that backend hub returns an `IObservable<T>`

**Comment by JanEggers** [comment]
I used signalr client in the server because i have to call different backends depending on parameters otherwise i would have used some websocket proxy

**Comment by davidfowl** [comment]
Great. We have a bug here that we need to fix. Does it throw when you have a `Task<IObservable<T>>` or `Task<ChannelReader<T>>` saying that the invocation isn't streaming?

As a workaround in the meantime you could do something like this (if using RX):

```
public IObservable<int> Proxy()
{
     var subject = new Subject<int>();
     _ =StreamAsync(hubConnection, subject);
     return subject;
}

private async Task StreamAsync(HubConnection conn, Subject<int> subject)
{
    var reader = await conn.StreamAsync("SomeBackendMethod");
    while (reader.WaitToReadAsync())
    {
        while(reader.TryRead(out var item))
        {  
              subject.OnNext(item);
        }
    }
    subject.OnCompleted();
}
```

This basically adapts the channel to the observable.

**Comment by JanEggers** [comment]
i get this:

The client attempted to invoke the non-streaming '{0}' method in a streaming fashion.

**Comment by JanEggers** [comment]
thx @JamesNK for fixing that up

**Comment by claylaut** [comment]
@davidfowl I am migrating my project which uses `Microsoft.AspNetCore.SignalR` version `1.0.0-preview2-final` to `1.0.0-rc1-final`.

And I run into this issue or similar issue, the exception is:
`A non-streaming method was invoked with a streaming invocation : StreamInvocation.`

backend (in the old version this used to work)
```
public class HeroHub : Hub<IHeroHub> {
        public IObservable<Hero> GetUpdates(string id) {
           //  returns an observable 
         }
}
```
And my second questions which relates to this, in the interface how shall I create the method signature for the stream method?

I've tried the following but i had no luck:
```
IObservable<Hero> GetUpdates(string id);
Task<IObservable<Hero>> GetUpdates(string id);
Task GetUpdates(string id);
Task<ChannelReader<Hero>> GetUpdates(string id);
```
For all the above it was throwing this error:
```
System.InvalidOperationException: Cannot generate proxy implementation for 'Heroes.Contracts.IHeroHub.GetUpdates'. All client proxy methods must return 'System.Threading.Tasks.Task'.
```

I m also using `System.Reactive` 3.1.1. and also tried to upgrade to the prelease v4.0.0-preview.2.build.379

**Comment by anurse** [comment]
@claylaut The error is indicating a failure in generating the implementation for `IHeroHub`. `IHeroHub` in your example should define what methods exist **on the client** and Streaming is not supported from the client to the server right now. Can you show the definition of `IHeroHub`?

**Comment by JanEggers** [comment]
@davidfowl  removed support for observables. have a look at the samples you have to use channelreader now.

https://github.com/aspnet/SignalR/blob/9cb683a41d759e45e3227ca4b2d57d819cc97380/samples/SignalRSamples/Hubs/Streaming.cs#L14-L20

**Comment by anurse** [comment]
It still isn't really clear to me. You defined `IHero` but I don't see that type used in the example.

When you use `Hub<T>`, the type you use for the `T` parameter defines the structure of the **Client** methods. Client methods can't return values or stream results in 2.1, only Server methods can. So, the interface you use in `Hub<T>` can only contain methods that return `Task`. This doesn't restrict the methods you can put on the Hub itself, those can be streaming. As @JanEggers mentioned, we dropped support for `IObservable` due to lack of support for back-pressure, so you need to use `ChannelReader<T>` or `Task<ChannelReader<T>>`.
