### ISSUE TITLE
Add better logic around deserializing headers

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#1545]
Currently when deserializing messages we grab the header value and check if there are any headers to write. This causes an allocation per send that we could easily avoid
https://github.com/aspnet/SignalR/blob/0eb2b96c45964be461394e73b960dd634fca405f/src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/HubInvocationMessage.cs#L16

![dict](https://user-images.githubusercontent.com/7574801/37066103-ab192ef4-2158-11e8-8218-3233d8cead80.PNG)

**Comment by davidfowl** [comment]
@anurse tsk 😄

**Comment by anurse** [comment]
I just wanted to leave some low-hanging performance fruit around ;). Boost morale and such XD
