### ISSUE TITLE
Improve JsonHubProtocol parsing of JSON message

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1549]
Today when parsing incoming messages `JsonHubProtocol` loads the whole JSON document into a `JObject` and then pulls data out of it as needed. This has the overhead of allocating many JObject/JArray/JValue instances and their own internal data structures (lists, dictionaries, box primitives, etc). Also arguments are parsed once into JTokens, and then those JTokens will be read again by the serializer.

Changing parse message to use `JsonTextReader` directly would be more efficient - both in allocations and amount of work done - but poses some challenges. The reader is forward only, and JSON objects are unordered.

Parse message will need to handle data coming in any order, e.g. arguments might be read before the method name, or the message type might come last. Ideally we would want arguments deserialized directly from the reader, but in cases where we don't know the method name yet - and therefor don't know the argument types - we'll need to temporarily cached them in a JArray as a fallback.

https://github.com/aspnet/SignalR/blob/0eb2b96c45964be461394e73b960dd634fca405f/src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonHubProtocol.cs#L69-L111

**Comment by anurse** [comment]
I think this should be fairly straightforward given that we already have a pretty good battery of tests for this.

**Comment by davidfowl** [comment]
I don't think this is a small work item. James would know better but I'm trying to determine how much stuff we need to re-implement when using the reader directly that we're getting for free today.

**Comment by davidfowl** [comment]
Ok I took a look and I think I have an approach (it may not be that difficult at all).
