### ISSUE TITLE
Presence over multiple pages

### ISSUE THREAD

**Issue by mortenbirkelund** [aspnet/SignalR#1552]
Hi

I am trying to use the presence functionality from the chatsample but instead of only applying it to a single page, I would like it to work on multiple pages. So that whenever a person arrives at the site he is shown as online, no mater what page he is viewing. I am thinking that it should be possible by simply adding the signalr client code to a seperat js file that is then included on all the relevant page. However, the problem is that the user should not be shown as leaving/entering a site, every time he visits another page on the site. 

Are there an easy solution to prevent that every page change is seen as leaving/joining?

**Comment by joshlrogers** [comment]
Essentially you technically can't but you can make it appear as if that is what is happening.  A page represents a collection, so this is possible in a SPA scenario as long as you have it high enough up the dependency stack.  However in an MVC scenario you have to do smoke and mirrors to give the appears of persisting connections across page reloads:

https://stackoverflow.com/questions/13383311/signalr-preserve-same-connection-across-multiple-pages-of-web-application

**Comment by KPixel** [comment]
One possible solution is to intercept when a person clicks to navigate to a different page, and update the current page's html + url... That way, the connection is not closed.

I think YouTube.com does something like that.

**Comment by anurse** [comment]
You could try establishing a session ID of some kind in your initial connection, store that in local storage on the browser and have new page loads send that session ID. Then you could modify the presence functionality to use the arrival of a new session ID as a "Connect". For disconnecting, you would ignore the Disconnected event and instead use a timeout and/or an explicit "End Session" message.

**Comment by KPixel** [comment]
I thought about that solution, but it would leave pocket of times where the user is disconnected while the browser navigates from one page to another, and that introduces a lot of unreliable behavior for you and for the other chat members.

BTW, I just tested the embedded chat feature on Facebook.com, and I think it also work like I described above.

**Comment by anurse** [comment]
> it would leave pocket of times where the user is disconnected while the browser navigates from one page to another

Well, that's somewhat inevitable with any connection. If pockets of lost messages are going to be a problem you'll want to build that reliability into your app because networks can be unreliable even if you aren't navigating between pages (consider when you change networks on a mobile device while a page is open).

**Comment by mortenbirkelund** [comment]
@KPixel Would there be any drawback/pitfalls to using your method? I found this tutorial for making a dynamic pagechange and still maintaining the correct url history. 
https://css-tricks.com/rethinking-dynamic-page-replacing-content/

**Comment by KPixel** [comment]
If you can implement it in such a way that is transparent to the rest of your code, I think it is a good solution.
But if you have to switch away from the MVC pattern (assuming that's what you are using), then it may not be worth the hassle.

**Comment by mortenbirkelund** [comment]
Awesome. The onepage approach seems to work, and it was possible incorporate without breaking the MVC pattern. 
Generally I used the guide from css-tricks to make the ajax code, and then I added the following to ViewStart.cshtml to ensure that the layout is not included. 
```
@{
    Layout = (Context.Request.Headers["x-requested-with"] == "XMLHttpRequest") ? null : "_Layout";
}
```

**Comment by mortenbirkelund** [comment]
Celebrated to early. The script section from the views is not included with this approach

**Comment by mortenbirkelund** [comment]
@anurse could you elaborate on how you would create the timeout functionality? I hoped that it could be done simple by the following, but even though the code is executed in the right order, then I can see that the user is not added to the disconnected list before the OndisconnectedAsync method is completed, and therefore the list is empty when OnConnectedAsync is executed. 


```
    [Authorize]
    public class ChatHub : HubWithPresence
    {

        private readonly HashSet<String> _disconnected = new HashSet<string>();

        public override async Task OnConnectedAsync()
        {
            var user = GetCurrentUserAsync().Result;

            if (!_disconnected.Contains(user.Id))
            {
                await base.OnConnectedAsync();
            }else
            {
                _disconnected.Remove(user.Id);
            }
            
        }
        
        public override async Task OnDisconnectedAsync(Exception exception)
        {
            var user = await GetCurrentUserAsync();

            _disconnected.Add(user.Id);
            Task.Delay(10000).Wait();
            if (_disconnected.Contains(user.Id))
            {
                _disconnected.Remove(user.Id);

                await base.OnDisconnectedAsync(exception);
            }

        }

        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(Context.User);
        }
    }
```

**Comment by anurse** [comment]
You want to create a system where users are marked online as long as they are browsing pages in your site, even when they move from page to page right? I'd suggest building some kind of user presence "service" in your site. The service would track the number of active connections each user holds. In `OnConnectedAsync`, you would add one to the counter for that user, and in `OnDisconnectedAsync` you would subtract one. When the counter reaches `0`, you **also** record the time that the last connection disconnected. Then you have a periodic timer in the background that scans this table and removes users where the connection count is `0` **and** the time of the last disconnect was more than `x` seconds ago (where `x` is whatever timeout you want to establish).

**Comment by mortenbirkelund** [comment]
It seems to be working as you explained. Only problem is that i am using hangfire to scan the connections, and it will only scan every minute. I think I will need to loop and wait in the scan method, as i would like to scan every 5 seconds.

**Comment by anurse** [comment]
If you need that kind of responsiveness that makes sense, but I would caution you that you will create a fairly significant load on your system by doing that. You need to make absolutely sure you can complete the scanning in less than 5 seconds when under the kind of traffic you expect to receive, otherwise the scans will start overlapping and you'll fall behind (which can reduce throughput significantly). If you're going to use such a low period, you should make sure you are tracking how long each iteration is taking so you can identify situations when it takes too long.

Do you need sub-minute responsiveness for this presence indicator? What kind of load (concurrent connection count, in particular) do you expect to receive on this service?

**Comment by mortenbirkelund** [comment]
Well it is not needed, but In a system where people can have conversation, I think it is problematic if users that logged of 60 seconds ago, is still shown as online, so that other people will try and initiate a new conversation with users who are actually offline. 

I understand the load that I put on the system, but as hangfire takes a trip to the database first, it seems best to use hangfire perhaps every fifth minute, and then instead just making the thread sleep for 5 or 10 seconds. 

I think I will just log the execution time as a warning if the execution time is above 50% of the max iteration time. 

 In the beginning i expect a max of 20 concurrent connections.

**Comment by mortenbirkelund** [comment]
Instead of making the job as a recurring in hangfire, I could just make it as an instant job, and then at the end of the method, add it again, as an instantly running job. This way, I will never experience 2 jobs overlapping. 

But perhaps it would be better to just make 1 job and then have that job running in an infinite loop? 
I know this is a bit outside the scope of SignalR, but which of these 2 solutions would you prefer, @anurse

**Comment by anurse** [comment]
The first method would be a little safer, having the job only be rescheduled **after** it has run.

**Comment by mortenbirkelund** [comment]
The approach I ended up with was using the IHostedService, and it works perfectly. Users are not logged out when changing pages, but first once they leave my website. 

Thank you for your help @anurse
