### ISSUE TITLE
SignalR map route in middleware for a Net 4.61 console app when service is started in Net  4.61 class lib

### ISSUE THREAD

**Issue by caseylobrien** [aspnet/SignalR#1553]
Context: We are using Net standard 2.0 to implement Miscrosoft.AspNetCore.SignalR (currently we are on version 1.0.0-alpha2-final). This library is used inside a Net Framework 4.61 console application typically (no issues here). For our integration tests we have a Net Core 2.0 console app that uses WebHostBuilder to spin up an instance of the service, this also works fine. 

We just started using Specflow, which currently does not support Net Core 2.0, so its a Net Framework 4.61 Class Library. We are also Using a WebHostBuilder (nearly identical to the Integrations Net Core 2.0 app's) to spin up an instance of the same Net Framework 4.61 service, but here we have an issue.

In the middleware we are using SignalRAppBuilderExtensions.UseSignalR to map the route like:
```
app.UseSignalR(routes =>
            {
                routes.MapHub<EventHub>("eventhub");
            });
```
This works great when running the 4.61 as a service, or even when starting the service from the Net Core 2.0 Integration Test console app. However when starting the Net Framework 4.61 service from a NetFramework 4.61 class library (for the Specflow tests) we receive the following error message:
>Message:
>The path in 'value' must start with '/'.
>Parameter name: value

>Source:
>"Microsoft.AspNetCore.Http.Abstractions"

>StackTrace:
>   at Microsoft.AspNetCore.Http.PathString..ctor(String value)
>   at Microsoft.AspNetCore.SignalR.HubRouteBuilder.MapHub[THub](String path)

I looked at the source code for the MapRouteBuilder.MapHub and saw that it is overloaded and can also take a PathString, so I tried that as well ( using new PathString("/eventhub") ), but still received the same error. 

Currently our work around is:
```
            app.UseSignalR(routes =>
            {
                try
                {
                    // for net core 2.0 / net standard 2.0
                    routes.MapHub<EventHub>("eventhub");
                }
                catch (ArgumentException)
                {
                    // for net 461
                    routes.MapHub<EventHub>("/eventhub");
                }
            });
```
This works in all three previously mentioned situations, but is obviously a tad ugly ;)

**Comment by anurse** [comment]
Are you sure both your .NET Framework and .NET Core builds are using the same version of the package? The change to require a `/` at the start of the path was made in the `1.0.0-preview1-final` build and should be the same in both .NET Framework and .NET Core.

**Comment by caseylobrien** [comment]
@anurse Yes that was the issue! Thanks for the help :)
