### ISSUE TITLE
Ensure `StartAsync` on transports waits for the transport to initialize and yields any errors

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1554]
Right now, the Server-Sent Events and Long Polling transports don't actually block `StartAsync` until they are initialized, they start up loops to handle polling and sending and then just immediately return. This means any failure in initialization won't trigger Transport Fallback (#1455).

For example, see Server-Sent Events (Long Polling is similar):

https://github.com/aspnet/SignalR/blob/1c44e8febfd57a1038715d6c74f030cebdcd14f2/src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs#L47-L72

The `Task.CompletedTask` on line 71 will be returned regardless of if the transport successfully initialized. Instead, we need to create a TaskCompletionSource, pass it in to the "OpenConnection" method and return the Task from that in `StartAsync`. Then, when the connection is properly established, we trigger the TCS, or if any error occurs, we fault the TCS.

* For Server-Sent Events, we want to trigger the TCS **after** the `SendAsync` here completes, and fault it if an exception occurs anywhere up to that point:

https://github.com/aspnet/SignalR/blob/1c44e8febfd57a1038715d6c74f030cebdcd14f2/src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs#L76-L81

* For Long Polling, things are slightly trickier. We want to trigger the TCS as soon as the first poll flushes headers. On the client, that simply means triggering it after the `SendAsync` for each poll (https://github.com/aspnet/SignalR/blob/1c44e8febfd57a1038715d6c74f030cebdcd14f2/src/Microsoft.AspNetCore.Sockets.Client.Http/LongPollingTransport.cs#L102) since only the first time you trigger it matters. Similarly we need to fault it if there's an exception with a poll. However, the server is trickier (see below)

We do have one tricky thing to deal with. Today, the Long Polling transport on the server does not flush the body until a message arrives, which means the headers won't be sent, and the `SendAsync` call on the client won't complete until a message arrives. We'll need to change our logic to flush the body immediately (to signal that the poll was received). That also means we can't set the Content Length and will have to use Chunking (the server will do this for us automatically) because we won't have a message at the time we're writing the headers.

@davidfowl Does this all sound reasonable to you? In particular, the Long Polling server-side change is a bit of a change in protocol.

**Comment by anurse** [comment]
We're also going to need this in the TS client.

**Comment by mikaelm12** [comment]
Yup, gonna add it with https://github.com/aspnet/SignalR/issues/1558

**Comment by mikaelm12** [comment]
Done: b5c46f35b3550936655c94c9ae8925d1fd4256be
