### ISSUE TITLE
If WriteAsync throws other connections might not be sent to

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#1555]
`WriteAsync` can throw, and if it throws before going async then other connections after the faulty one won't get the Send.
https://github.com/aspnet/SignalR/blob/1c44e8febfd57a1038715d6c74f030cebdcd14f2/src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs#L86

Also the Hub will get the error, and I think we decided it wasn't an interesting failure for the Hub to see

**Comment by anurse** [comment]
We should take this in preview2

**Comment by anurse** [comment]
In Redis as well
