### ISSUE TITLE
Connection getting disconnected when using MessagePackHubProtocol

### ISSUE THREAD

**Issue by learnersLicense** [aspnet/SignalR#1559]
Hi, 

I updated the the javascript libraries to signalr@1.0.0-preview1-update1 and @aspnet/signalr-protocol-msgpack@1.0.0-preview1-update1 on the frontend and backend Microsoft.AspNetCore.SignalR Nuget library to 1.0.0-preview1-final.

I use MessagePackHubProtocol as the connection protocol. 
First I got 
msgpack5 is not a function
so I included the msgpack5.js to the project. 

After that once the connection is made, on invoking a server method the connection disconnects
The error logs are given below:

![image](https://user-images.githubusercontent.com/33309159/37151115-49e6a1b8-22fa-11e8-8fc7-8f7bd77e5b3a.png)

The connection works if json protocol is used.(Information: Using HubProtocol 'json'.)

Please may I get some help.

**Comment by anurse** [comment]
Can you check for logs on the server? If you're running directly in Kestrel these are visible from the console window. If you're using IIS Express/IIS in Visual Studio, they show up in the "ASP.NET Core Web Server" section of the Output Window.

**Comment by learnersLicense** [comment]
Hi @anurse 
I checked the logs on the server.
I am using ServerSentEvents transport and messagepack protocol for the connection.
The following error was reported. 

System.NotSupportedException: The protocol 'messagepack' is not supported.

Is there any other package to be installed on the server side to support message pack?

**Comment by anurse** [comment]
Yes, you have to install the `Microsoft.AspNetCore.SignalR.MsgPack` package on the server and add `.AddMessagePackProtocol` after your `.AddSignalR` call in `ConfigureServices`. For example:

https://github.com/aspnet/SignalR/blob/4a4efe0f39477dff01bdff5006df477498e5e6f2/samples/SocketsSample/Startup.cs#L23-L31

We're looking at adding some logic to the protocol to make this error clearer, see #1548 

I'm going to close this as it looks like the issue has been resolved. Please feel free to comment further if you have questions, we can always re-open this if there are any issues.

**Comment by learnersLicense** [comment]
Thanks @anurse . 
This really helped :)

**Comment by anurse** [comment]
In RC1 we switched to https://github.com/neuecc/MessagePack-CSharp/ in order to get improved performance and stablility. See that repository for documentation on how to configure that library.

We expose an `options` delegate off `.AddMessagePack` on the server:

```csharp
services.AddSignalR()
  .AddMessagePackProtocol(options => { ... configure MsgPack options ... })
```

**Comment by guylando** [comment]
yes I checked the options but they have only single property: FormatterResolvers which is an array...
@anurse

**Comment by guylando** [comment]
couldnt find an example anywhere yet..still looking

**Comment by guylando** [comment]
I found in https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Protocols.MessagePack/Protocol/MessagePackHubProtocol.cs how to deal with it.

havent found solution for serializing enum as integer so opened an issue there https://github.com/neuecc/MessagePack-CSharp/issues/248

**Comment by anurse** [comment]
> but they have only single property: FormatterResolvers which is a list

Yes, the way MessagePack-CSharp does configuration is via managing a list of these FormatterResolvers. The MessagePack-CSharp repo has some documentation on this: https://github.com/neuecc/MessagePack-CSharp#extension-pointiformatterresolver

**Comment by guylando** [comment]
I dont see a way to serialize enum as int..this together with the other messagepack bug brings me to the conclusion that its not mature enough and I should stick to json for now.
