### ISSUE TITLE
MsgPack Hub protocol seems to use different casing in each direction from browser

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/SignalR#1565]
Repro at https://github.com/DamianEdwards/MoveShapeCore

See line https://github.com/DamianEdwards/MoveShapeCore/blob/master/MoveShape21/wwwroot/js/MoveShape.js#L49

I wrote the app using JSON protocol first, but when I changed it to MsgPack it seems the casing of the object being sent to the server from the browser had to be in PascalCase, e.g. `position.X`, whereas what's received from the server is in camelCase, e.g. `position.x`. This seems wrong.

**Comment by DamianEdwards** [comment]
@anurse

**Comment by anurse** [comment]
I bet I know the issue. I bet the MsgPack library we're using only does the camel-case transformation when serializing and not when deserializing.

**Comment by anurse** [comment]
Yep, I've confirmed this. There are two issues:

* Camel-Case behavior is inconsistent between MsgPack-Cli and JSON.NET. We can work around this by providing our own Key Transformer delegate that just copies the behavior of JSON.NET. Specifically: `GUID` camelCases to `gUID` in MsgPack-Cli but `guid` in JSON.NET (the latter is more correct IMO)
* Binding in MsgPack-Cli is case-sensitive, and there's no way to change this, so an incoming `name` will only bind to a property named `name`, and **not** to `Name`. We can't work around this, so the only fix is to fix it in MsgPack-Cli or to change libraries (and hope they have this behavior or are willing to make the fix)

**Comment by anurse** [comment]
This is a medium that we might luck out on and be able to do quickly.

**Comment by anurse** [comment]
Should we just let this be a limitation of the library and downgrade this to `cost: 0` tracking https://github.com/neuecc/MessagePack-CSharp/issues/220 ?

**Comment by anurse** [comment]
Triage: agreed with my earlier suggestion

**Comment by anurse** [comment]
You can use the [`Key` attribute ](https://github.com/neuecc/MessagePack-CSharp#object-serialization)to control the property names in the MessagePack library. It's not ideal, but it would allow you to work around the issue.

**Comment by anurse** [comment]
Closing this as it's a limitation of MessagePack-CSharp
