### ISSUE TITLE
Run WebSocket tests on netcoreapp2.1+Win7

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1568]
Right now we skip WebSocket-related tests on Windows 7. However, in .NET Core 2.1, `ClientWebSocket` uses the managed implementation on all OSes, which means it works on Windows 7. That was the only thing that didn't work about those tests so we should try to re-enable them. However, they can only be enabled on Windows 7 + `netcoreapp2.1`, not on other frameworks when running on Windows 7. We'll need a new [`ITestCondition`](https://github.com/aspnet/Testing/blob/dev/src/Microsoft.AspNetCore.Testing/xunit/ITestCondition.cs) attribute for that condition.

**Comment by moozzyk** [comment]
https://github.com/aspnet/Testing/issues/267
