### ISSUE TITLE
Invoke event on all clients has no effect

### ISSUE THREAD

**Issue by maximtarasov** [aspnet/SignalR#157]
Hi.

In my case, i try to invoke event on all clients connected to hub.
WebSockets used as transport.
Event are not called on client (checked this in development console, there is no frame with event data).

```
[AllowAnonymous]
    public class MyController : Controller
    {
        private readonly IConnectionManager _context;
        public ATSController(IConnectionManager context)
        {
            _context = context;
        }

        public async Task OnExternalTreatment()
        {
            await _context.GetHubContext<EventsHub, IEventHubClient>().Clients.All.OnExternalTreatment();
        }
   }
```

Package: Microsoft.AspNetCore.SignalR.Server
Version: 0.2.0-preview2-22683

**Comment by davidfowl** [comment]
See my last reply https://github.com/aspnet/SignalR/issues/156#issuecomment-275230701
