### ISSUE TITLE
transport is undef in HttpConnection

### ISSUE THREAD

**Issue by the-dansan** [aspnet/SignalR#1576]
Hi guys -- thanks for making all this public.

I'm trying to get a simple app working with update1. Server code is great, but the js is giving me issues (and I'm fairly new with modern javascript so still catching up):

```javascript
let connection = new HubConnection('some url');
connection.start().then((tr, opt) => {
            debugger;
        },
        (err) => {
             debugger;
        });
```

this results in the following error (and the promise's error callback being invoked):

> Error: Failed to start the connection. TypeError: Cannot set property 'onreceive' of undefined

calling /negotiate manually seems to work:

```json
{
  "Url": "\/signalr",
  "ConnectionToken": "Z3z1w03ekE9MTiVft7UzfvgxJIe6UjVngyb0SI21SE10QSifO6C\/h5XB1p6cosKGFBVI7F6HsdMVh8nswZOy3Dkl1fLol2U19y1Nw0ejlJgKJgNKmOaqhl9aVLXyJPWq",
  "ConnectionId": "edf55548-cc7f-4633-b9f7-3fd439f32641",
  "KeepAliveTimeout": 20,
  "DisconnectTimeout": 30,
  "ConnectionTimeout": 110,
  "TryWebSockets": true,
  "ProtocolVersion": "1.2",
  "TransportConnectTimeout": 5,
  "LongPollDelay": 0
}
```

**Comment by BrennanConroy** [comment]
Looks like you're trying to use the SignalR Core client with a 2.X Server, that is unsupported. The new client is not compatible with the old server, you have to use the new server.

**Comment by the-dansan** [comment]
Ok, thank you; I'll switch out the server and retry and update the thread shortly.

**Comment by the-dansan** [comment]
Wonderful, it starts! Thanks again.
