### ISSUE TITLE
Things to flesh out in the spec

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#158]
- Flowing errors to the client
- Describing how status codes affect the various transport (204, vs 200 for long polling etc)

/cc @anurse

**Comment by anurse** [comment]
I'm not sure the Sockets/Transport layer should do much in the way of flowing errors. Almost all the errors that can occur at that layer are things the client can't do anything about (exception for `4xx`-class HTTP errors, like authentication things).

SignalR certainly needs an RPC protocol that allows flowing errors.

**Comment by davidfowl** [comment]
> I'm not sure the Sockets/Transport layer should do much in the way of flowing errors. Almost all the errors that can occur at that layer are things the client can't do anything about (exception for 4xx-class HTTP errors, like authentication things).

Even if we don't flow exception text from the server we need to describe how each transport behaves when faced with a particular status code and how errors on the server map to those status codes. 

A few examples: 
- What happens when the endpoint can't be created on the server? Is that just a 500? 
- What happens when the `/send` request returns a non 2xx response?
- What happens when the transport fails in an unexpected way?
- What happens when the application throws an error? How is that communicated over the transport?

**Comment by anurse** [comment]
This was done in #171
