### ISSUE TITLE
The README of how to use signalr-protocol-msgpack has a bug

### ISSUE THREAD

**Issue by ccic** [aspnet/SignalR#1580]
@aspnet/dist/browser/signalr-protocol-msgpack.js defines "signalR.protocol**s**.msgpack", but the README asks developers to reference "signalR.protocol.msgpack", which caused error: msgpack is undefined.

let connection = new signalR.HubConnection('/chat', {
    protocol: new signalR.protocol.msgpack.MessagePackHubProtocol()
});

**Comment by anurse** [comment]
Thanks for the report! https://github.com/aspnet/SignalR/pull/1581 should fix this in preview2.
