### ISSUE TITLE
Terminating Long Polling connection by sending 204 response on iOS

### ISSUE THREAD

**Issue by Krakownication** [aspnet/SignalR#1584]
I would like to submit issue.

Backend return 204 response for Long Polling connection GET request, if iOS client is sender - both Safari and Chrome.
Work fine for PC (Chrome, Firefox, Edge) and Android (Chrome).

Backend:
```
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
<PackageReference Include="NLog.Web.AspNetCore" Version="4.4.1" />
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" />
```
Frontend:
```signalr-client-1.0.0-alpha2-final.js```

<br/>

Logs of issue:
```Microsoft.AspNetCore.Hosting.Internal.WebHost | url: http://url.domain/subdomain/signalR | msg: Request starting HTTP/1.1 OPTIONS http://url.domain/subdomain/signalR  0 
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler | url: https://url.domain/subdomain/signalR | msg: AuthenticationScheme: Cookies was successfully authenticated. 
Microsoft.AspNetCore.Hosting.Internal.WebHost | url: https://url.domain/subdomain/signalR | msg: Request finished in 7.7804ms 200 application/json 
Microsoft.AspNetCore.Hosting.Internal.WebHost | url: http://url.domain/subdomain/signalR | msg: Request starting HTTP/1.1 GET http://url.domain/subdomain/signalR?id=92096986-9e6c-4091-ab66-423af4705c18&_=1520938245989   
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler | url: https://url.domain/subdomain/signalR | msg: AuthenticationScheme: Cookies was successfully authenticated. 
Microsoft.AspNetCore.Sockets.Internal.Transports.LongPollingTransport | url: https://url.domain/subdomain/signalR | msg: 03/13/2018 11:50:51: Connection Id 92096986-9e6c-4091-ab66-423af4705c18, Request Id 0HLC8MERMSQJA:00000003: Terminating Long Polling connection by sending 204 response. 
Microsoft.AspNetCore.Hosting.Internal.WebHost | url: https://url.domain/subdomain/signalR | msg: Request finished in 4996.896ms 204
```

Logs of normal behaviour:
```Microsoft.AspNetCore.Hosting.Internal.WebHost | url: http://url.domain/subdomain/signalR | msg: Request starting HTTP/1.1 OPTIONS http://url.domain/subdomain/signalR   
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler | url: https://url.domain/subdomain/signalR | msg: AuthenticationScheme: Cookies was successfully authenticated. 
Microsoft.AspNetCore.Hosting.Internal.WebHost | url: https://url.domain/subdomain/signalR | msg: Request finished in 85.9912ms 200 application/json 
Microsoft.AspNetCore.Hosting.Internal.WebHost | url: http://url.domain/subdomain/signalR | msg: Request starting HTTP/1.1 GET http://url.domain/subdomain/signalR?id=2b287337-7f48-4a6d-b3f4-7271368c67c3&_=1520837051649   
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler | url: https://url.domain/subdomain/signalR | msg: AuthenticationScheme: Cookies was successfully authenticated. 
Microsoft.AspNetCore.Hosting.Internal.WebHost | url: http://url.domain/subdomain/signalR | msg: Request starting HTTP/1.1 POST http://url.domain/subdomain/signalR?id=2b287337-7f48-4a6d-b3f4-7271368c67c3 text/plain;charset=UTF-8 20 
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler | url: https://url.domain/subdomain/signalR | msg: AuthenticationScheme: Cookies was successfully authenticated. 
Microsoft.AspNetCore.Hosting.Internal.WebHost | url: https://url.domain/subdomain/signalR | msg: Request finished in 34.636ms 200
```
<br/>

Any hints?

**Comment by anurse** [comment]
Can you provide the code that reproduces the problem? Both server- and client-side code will be necessary to identify the issue.

Also, are you able to collect information about the network requests occurring? (i.e. the information you'd get from the Network tab of your Browser Dev Tools on a PC)

**Comment by Krakownication** [comment]
Sure:
ReproduceSolution: https://github.com/Krakownication/Issue1584ReproduceSolution
network.HAR: https://github.com/Krakownication/Issue1584ReproduceSolution/blob/master/network.HAR

**Comment by anurse** [comment]
@HaoK can you take a look and see if you can reproduce this issue on the latest builds?

@Krakownication are you still seeing this issue on the latest builds? Can you update to the preview 1 release and try to reproduce the issue again (and provide any logging and other diagnostics as described here: https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md)

**Comment by Krakownication** [comment]
Issue solved on the lastes build:
_backend - 1.0.0-preview2-final
frontend - @aspnet/signalr@1.0.0-preview3-32122_

Thanks

**Comment by HaoK** [comment]
Great to hear, closing this out then

**Comment by anurse** [comment]
> frontend - @aspnet/signalr@1.0.0-preview3-32122

FYI, you should use the `1.0.0-preview2-final` build of the client with the matching server build. You're getting lucky that the `preview3` client is working with the `preview2` server. The `preview2` client build was just published to npmjs.org

**Comment by Krakownication** [comment]
I was aware of that, but couldn't find proper version. Now I'll use `preview2`
BTW, as _VS2017_ got build-in _bower_ management, you sould publish client versions there also.

**Comment by Krakownication** [comment]
Just tried client `preview2` and with it issue is **not** solved.

I will check it later.

**Comment by Krakownication** [comment]
Versions of Server-Side NuGet Packages: `Microsoft.AspNetCore.SignalR 1.0.0-preview2-final`
Versions of Client-Side NuGet/NPM Packages: `@aspnet/signalr 1.0.0-preview2-final`
Are you using the C# client or the JavaScript client: `JavaScript`
The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): `IIS`
The Operating System on the Server (Windows/Linux/macOS):  `Windows Server 2016 Standard`
The Operating System on the Client (Windows/Linux/macOS):` iOS 11`
The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): `Safari and Chrome`

[Network Traces](https://github.com/Krakownication/Issue1584ReproduceSolution/blob/master/Logs/preview2-final/client-network.har)
[Logs from the client](https://github.com/Krakownication/Issue1584ReproduceSolution/blob/master/Logs/preview2-final/client-console.log)
[Logs from the server](https://github.com/Krakownication/Issue1584ReproduceSolution/blob/master/Logs/preview2-final/server.log)

**Comment by Krakownication** [comment]
On `@aspnet/signalr@1.0.0-preview3-32196` connection seems to be established, but errors occur while repooling. I guess its from mismatch client-server versions.

**Comment by anurse** [comment]
I see in your repro project that you are still using `Microsoft.AspNetCore.All` `2.0.3`. That combination is not supported. After alpha 2, SignalR became part of `Microsoft.AspNetCore.All` so you should remove the dependency on `Microsoft.AspNetCore.SignalR` and update `Microsoft.AspNetCore.All` to `2.1.0-preview2-final`. You will also need to update your application to `netcoreapp2.1` (and install .NET Core 2.1 preview2)

After updating to that, I ran your project, using the `signalr-client-preview2.min.js` file and connected from an iOS device. The connection seemed fine. Every time I hit the `/api/test/get/test1` URL, I got a pop-up on the iOS device. I'm afraid I can't repro the issue unless we can find more information about what's different between our scenarios.

**Comment by anurse** [comment]
I should note that the error you are seeing in your client log (`signalr-client-preview2.js:14 Warning: Error from HTTP request. 0: `) is often associated with the browser blocking a cross-origin request or some other error originating from the browser HTTP stack. Are you making cross-origin requests?
