### ISSUE TITLE
Need heelp: can't create an HubConnection client, targetting .net standart 2.0.

### ISSUE THREAD

**Issue by Bohirjon** [aspnet/SignalR#1593]
Hey dears I'm new at signalR ineed ur help, can't create an HubConnection couse of there no implementation of IConnection i've installed  "Microsoft.AspNetCore.SignalR.Client.Core version 1.0.0-preview1-final"  into my .net standart 2.0, or should I create my own implementation if yes how, is there anyone have using client side targetting net standart 2.0? can u share that ?

**Comment by mikaelm12** [comment]
You can either create an instance of HttpConnection and pass that into your HubConnection. Or you can use the HubConnectionBuilder class which will do it for you like so https://github.com/aspnet/SignalR/blob/dev/samples/ClientSample/HubSample.cs#L33

**Comment by Bohirjon** [comment]
@mikaelm12 thank u for ur quick answer I'll take a look.

**Comment by anurse** [comment]
> i've installed "Microsoft.AspNetCore.SignalR.Client.Core version 1.0.0-preview1-final"

You need to install `Microsoft.AspNetCore.SignalR.Client` to get all the correct dependencies. Then you will have access to `HubConnectionBuilder` which will create an `IConnection` on your behalf.

**Comment by anurse** [comment]
Closing this issue for now as the question has been answered and we want to make sure we're tracking issues that need to be fixed. Please feel free to comment further if you have questions! We can always re-open the issue if there's an issue to fix here!

**Comment by Bohirjon** [comment]
@anurse Thanks it it worked, I was installing a wrong version of it.
