### ISSUE TITLE
Sending AspNetCore.Identity.Application cookie to signalr 

### ISSUE THREAD

**Issue by KennethInfoEasy** [aspnet/SignalR#1602]
Hi, I'm trying to connect to an asp.net core 2 signalR hub from an .net core 2.0 console application. 
I'm trying to authenticate the application by sending a cookie with the signalR StartAsync method. The cookie is returned by using httpclient.

    var connection = new HubConnectionBuilder()
                .WithUrl("http://localhost:58215/testhub")
                .WithHeader("Set-Cookie", cookiestring)
                .WithConsoleLogger()
                .Build();

Test scenario 1: Without the Authorize attribute. I'm connected to the hub but the Context.User.Identity.Name is null. 
Test scenario 2. With the Authorize attribute i'm getting an exception from signalr. 

System.AggregateException: 'One or more errors occurred. (Invalid negotiation response received.)'
FormatException: Invalid negotiation response received.
JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0

I get this exception also if I don't send the cookie  //   .WithHeader("Set-Cookie", cookiestring)

I'm unsure if the second scenario is related to the first.  Or this is two separate issues.  

Is there another way to authenticate the users logging in remotely (console or windows service)?

 I want to keep the default authentication for the rest of the web application, so changing everything to JWT is not an option.

**Comment by BrennanConroy** [comment]
Check your server and client versions and make sure they are the same

**Comment by KennethInfoEasy** [comment]
![signalrdependencies](https://user-images.githubusercontent.com/37364761/37435394-707e47e8-27e3-11e8-8fe0-1af739335514.png)
I belive i'm good there. I checked that before submitting. @BrennanConroy Thanks for the quick reply though 👍

**Comment by BrennanConroy** [comment]
I'm not sure setting cookies via `.WithHeader("Set-Cookie", ...)` is a good idea. You could try using `.WithMessageHandler` and providing your own wrapper that adds cookies to the httprequest. In the latest dev bits we have `.WithCookie` FYI

**Comment by BrennanConroy** [comment]
Also, I was just made aware that on the request it's "Cookie" instead of "Set-Cookie"

**Comment by KennethInfoEasy** [comment]
@BrennanConroy  Nice news about the .WithCookie.. Will that be release to nuget any time soon ? 
Did I mix the cookies up? :) I thought you put Set-Cookie when sending back to server. I'll try :) 

What about the exception? Since I get then exception when not setting the withheader option.

**Comment by KennethInfoEasy** [comment]
@BrennanConroy Now it works. I'm now identified using Cookies. Seems like i only get the exception when not authenticated.

**Comment by anurse** [comment]
This is because we aren't setting the `X-Requested-With` header (that JavaScript sets on the browser) so the Authentication middleware does a redirect to the login page rather than sending us a `401`. Either we need to set that header to masquerade as XMLHttpRequest or the auth middleware should be a little more flexible here.
