### ISSUE TITLE
Typo: DictionarySerlaizationOptions property on SerializationContext (MsgPack)

### ISSUE THREAD

**Issue by sondreb** [aspnet/SignalR#1608]
Not sure if this has been corrected yet, but the DictionarySerlaizationOptions class in namespace "MsgPack.Serialization" and property "DictionarySerlaizationOptions" on SerializationContext in namespace "MsgPack.Serialization" is written incorrectly.

DictionarySerlaizationOptions should be DictionarySerializationOptions

Couldn't find classes in question within the repo (searched for both correct and incorrect spelling), appears perhaps that MsgPack was moved out of this repo? And I couldn't find a MsgPack repo under "aspnet" organization, so I reported the issue here.

**Comment by BrennanConroy** [comment]
Report it here: https://github.com/msgpack/msgpack-cli

**Comment by anurse** [comment]
We've actually already sent a PR to fix this (though there is an issue I'm resolving shortly): https://github.com/msgpack/msgpack-cli/pull/284
