### ISSUE TITLE
Use same Redis Cache instance for multiple SignalR hosts

### ISSUE THREAD

**Issue by sondreb** [aspnet/SignalR#1620]
Is it possible to reuse the same Redis Cache instance for multiple SignalR hosts, using ChannelPrefix or something else?

Would something like this do it?

Options.ChannelPrefix = new RedisChannel("App1", RedisChannel.PatternMode.Auto)

Reason for this is with many test environments, I want to re-use the Redis Cache, but avoid messages being distributed across environments.

Searched through the issues archive and couldn't find anything on  this.

**Comment by anurse** [comment]
That sounds like a reasonable idea. I think we'd be happy to take a PR for this, and it should be somewhat straightforward if you're interested in contributing it.

**Comment by BrennanConroy** [comment]
We expose the `ConfigurationOptions` via `AddRedis`

```
services.AddSignalR()
    .AddRedis(options =>
    {
        options.ChannelPrefix = new RedisChannel("App1", RedisChannel.PatternMode.Auto);
    });
```

Does this not work? Or were you not aware of the ability to add options?

**Comment by anurse** [comment]
We think we have this functionality already, as @BrennanConroy mentions. Feel free to comment further, we can always re-open this if there's work to do.
