### ISSUE TITLE
Sending messages to hub using websockets

### ISSUE THREAD

**Issue by davenewza** [aspnet/SignalR#1621]
We are trying to send messages to our SignalR hub without using a SignalR client, i.e. using websockets, since this is now supported.  This will allow us to use Java clients (although we are just testing in C# for now).

The connection opens fine, but I can't seem to find an example of how to construct a message that gets accepted correctly on our server.

    var websocket = new ClientWebSocket();
    await websocket.ConnectAsync(new Uri("ws://precariouswebsockets.azurewebsites.net/user"), CancellationToken.None);

    string data = "???";  // How do I call upon the Accept method on the hub?
    var encoded = Encoding.UTF8.GetBytes(data);
    var buffer = new ArraySegment<Byte>(encoded, 0, encoded.Length);
    await websocket.SendAsync(buffer, WebSocketMessageType.Text, true, CancellationToken.None);

The method on the hub is nothing more than:

    public void Accept(string message)
    {
        ...
    }

**Comment by davidfowl** [comment]
The spec is here:

https://github.com/aspnet/SignalR/blob/dev/specs/HubProtocol.md

**Comment by davenewza** [comment]
Great - thanks. Not sure how I missed this.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if there's anything in the spec you'd like clarified! We want the spec to be somewhat usable for exactly this scenario (building non-official clients) so that we can have clients on platforms that we don't currently support.
