### ISSUE TITLE
When a hub cannot be created longPolling transport returns 204 instead of an error.

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#163]
The hub could not be created and the server closed the connection. In case of longPolling the connection was closed with 204 even though there was an error. 
For SSE server returns 404: GET http://localhost:5000/notification/sse?id=2d19ab96-1679-485d-b8df-0bd9bcbed0fd 404 (Not Found) - does not seem to be correct.
For websockets transport the the webSocket is closed with 1011 (which is correct)

![image](https://cloud.githubusercontent.com/assets/1438884/22381896/4b49b840-e478-11e6-90f1-fc3a9deb7629.png)

```
fail: Microsoft.AspNetCore.SignalR.HubEndPoint[0]
      Error when invoking OnConnectedAsync on hub.
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'SignalRCoreTest.NotificationHub'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.AspNetCore.SignalR.DefaultHubActivator`2.Create()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<HubOnConnectedAsync>d__9.MoveNext()
info: Microsoft.AspNetCore.Sockets.Transports.LongPollingTransport[0]
      Terminating Long Polling connection by sending 204 response.
fail: Microsoft.AspNetCore.Sockets.ConnectionManager[0]
      Failed disposing connection e4eb6bf0-b08c-4899-a8ba-04648ec1f114
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'SignalRCoreTest.NotificationHub'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.AspNetCore.SignalR.DefaultHubActivator`2.Create()
```

Also each time it happens you will see:

```
fail: Microsoft.AspNetCore.Sockets.ConnectionManager[0]
      Failed disposing connection 828a02d2-ba1f-4a62-aaa1-6e8f45a43db0
```

**Comment by davidfowl** [comment]
That's part of this  https://github.com/aspnet/SignalR/issues/158. 

With respect to error handing we need to describe:

- What happens the end point throws for each transport
- What happens when the transport throws
- What happens if the end point doesn't exist (404 seems appropriate)
- Do we ever surface 500s to the client?

**Comment by moozzyk** [comment]
On the client in case of errors we close the connection passing an error as an argument.

**Comment by davidfowl** [comment]
The server is the same deal but that doesn't help the client connected to the server.

**Comment by moozzyk** [comment]
Are you talking about https://github.com/aspnet/SignalR/blob/8022afd3a2644237d597b6664f553871c69a1666/src/Microsoft.AspNetCore.SignalR/Hub.cs#L69? Because it is not the same - this is only for the user to know that the connection was not closed cleanly. Closing the connection itself should signal an error in a transport specific way (i.e. 500 for longPolling and serverSentEvents and non-1000 close status for webSockets (which already works).

**Comment by davidfowl** [comment]
I'm talking about this https://github.com/aspnet/SignalR/blob/eafbe741609981cdcf6b6f28d45cb2f50126750d/src/Microsoft.AspNetCore.Sockets/Internal/ConnectionState.cs#L54-L63

**Comment by davidfowl** [comment]
@moozzyk This is fixed right?

**Comment by moozzyk** [comment]
We need to verify/add tests for the scenarios you pointed in your [comment](https://github.com/aspnet/SignalR/issues/163#issuecomment-275740340).

**Comment by davidfowl** [comment]
Turns out we have a test for this https://github.com/aspnet/SignalR/blob/13ef35fa79f3e52453868ef7421e46d58b5c5242/test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs#L203

**Comment by pravinpatil83** [comment]
Hi, I am getting this error on ubuntu server with Nginx. The Same code is working in IIS Express. What can be the issue?

**Comment by pravinpatil83** [comment]
Hi, I am connecting from Xamarin Client.

**Comment by pravinpatil83** [comment]
Soled by adding proxy_set_header Connection "Upgrade" in nginx configuration.
