### ISSUE TITLE
Look at using ObjectPool for various per message allocations

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1634]
After we get in https://github.com/aspnet/SignalR/pull/1632 and https://github.com/aspnet/SignalR/pull/1630 we'll be in a much better place for the JsonHubProtocol implementation with respect to allocations per message. There are still a bunch of objects that end up getting allocated per message that we could reduce by using an object pool. Here's a snapshot of reading:

The code for this test is here https://gist.github.com/davidfowl/195beda5846360855faa17ab8b9856f5#file-sample-cs

![image](https://user-images.githubusercontent.com/95136/37561255-5ea50892-2a07-11e8-933d-d26bc0b1c426.png)

**Comment by ccic** [comment]
@davidfowl Which tool do you use to get the memory allocation? It is helpful to diagnose the memory issue.

**Comment by anurse** [comment]
We usually use [JetBrains dotMemory](https://www.jetbrains.com/dotmemory/), but you can also use [PerfView](https://github.com/Microsoft/perfview) (though PerfView is much harder to use in my experience)

**Comment by davidfowl** [comment]
Here are the objects we allocate on a per message basis for reading for JSON. The sample reads 1M messages:

![image](https://user-images.githubusercontent.com/95136/37873704-e33c24a8-2fd6-11e8-8641-1bfd3058c9b1.png)

**Comment by anurse** [comment]
We don't expect to be able to get to this in RC. But we'll always keep reviewing performance.
