### ISSUE TITLE
Null HttpContext with long polling

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1644]
A hub method that accesses the `HttpContext` can get null instead if the method was invoked while the poll request ended.

https://github.com/aspnet/SignalR/blob/0e38ee3e63f4fb7ed08b3626fa85ec5f33952e09/src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs#L279

This has shown up with `HubConnectionTests.ClientCanSendHeaders(transportType: LongPolling)` on OSX build.

https://travis-ci.org/aspnet/SignalR/jobs/355210173#L1309

```
[xUnit.net 00:00:06.1150930]     Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ClientCanSendHeaders(transportType: LongPolling) [FAIL]
Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ClientCanSendHeaders(transportType: LongPolling)
Error Message:
 Microsoft.AspNetCore.SignalR.Client.HubException : An unexpected error occurred invoking 'GetHeaderValues' on the server. InvalidOperationException: Unable to get HttpContext from request.
Stack Trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by anurse** [comment]
Yeah, this is a tricky one because the connection is long-living but the HttpContext is only associated with a single Send, Poll, EventSource stream or WebSocket request. Perhaps we need to just remove the HttpContext entirely and copy any relevant data into the ConnectionContext.

**Comment by davidfowl** [comment]
Since we are decoupled from the actual hub invocation process we're going to remove the HttpContext from the connection features. Instead, we're going to need to copy data from the HttpContext (Headers and QueryString).

**Comment by anurse** [comment]
Also Connection info (IP Addresses, ports)

**Comment by davidfowl** [comment]
@anurse  I had an evil idea. Still set an HttpContext but with the copied data. The benefit is that it just works with all of the APIs that take an http context (like the auth methods) but it's harmless since it isn't valid as write to or read from (the bodies), and it has the properties that people want.

**Comment by anurse** [comment]
It's not that crazy. We'd need to poison, or `null`-out things like the Body stream. It would take a lot of effort though, possibly more than just copying the things we know we want.

**Comment by davidfowl** [comment]
Yep, I'm going to do this.
