### ISSUE TITLE
How to get a .Net Framework SignalR client to connect to .Net Core Server?

### ISSUE THREAD

**Issue by keithn** [aspnet/SignalR#1645]
Currently it seems to be incompatible with the SignalR client in the .net framework?

If so, is there a way to connect with .net framework?

**Comment by davidfowl** [comment]
You can use this package https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/1.0.0-preview1-final which is netstandard 2.0 and runs on .NET Framework.

**Comment by keithn** [comment]
doesn't seem to work, have a pretty much identical core and .net framework test client, the .net framework client doesn't seem to connect

![image](https://user-images.githubusercontent.com/86080/37585195-22aaadbc-2bbd-11e8-8360-b0454bc161e1.png)

**Comment by keithn** [comment]
ok,  apparently it needed  ```      .WithTransport(TransportType.WebSockets)```

**Comment by davidfowl** [comment]
@keithn SignalR Core requires sticky sessions unless you use websockets.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
