### ISSUE TITLE
Non-serializable data

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#1649]
[These](http://aspnetci/viewLog.html?buildId=423407&buildTypeId=Lite_UniverseTest&tab=buildLog&_focus=17506#_state=486) warnings:
```
Microsoft.AspNetCore.SignalR.Client.FunctionalTests: Non-serializable data ('System.Object[]') found for 'Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanInvokeClientMethodFromServer'; falling back to single test case.
```
are appearing in builds of SignalR, they sound like they're preventing the full compliment of tests from running.

CC @jkotalik

**Comment by jkotalik** [comment]
I don't think I'm the appropriate person for this task. cc @anurse @BrennanConroy @mikaelm12

**Comment by anurse** [comment]
These issues don't cause any problem running the test. They simply stop Test Explorer from showing them as multiple tests.

**Comment by anurse** [comment]
Re-opening to track making these data serializable so that we get a clean Test Explorer experience. It's suuuuuuper puntable :)
