### ISSUE TITLE
signalr-client.js not found

### ISSUE THREAD

**Issue by sadersa** [aspnet/SignalR#165]
hi
i create new asp.net core project
add 
Microsoft.AspNetCore.SignalR            1-23269
Microsoft.AspNetCore.SignalR.Client  1-23269

no file **signalr-client.js** in folder http://localhost:59456/Home/lib/signalr-client/signalr-client.js
![screenshot_1](https://cloud.githubusercontent.com/assets/15789294/22395847/3b4c192c-e55b-11e6-8d6a-e0e2e7d4ab60.png)
tell me pls where get signalr-client.js and another files for signalr
thanks

**Comment by herecydev** [comment]
It looks like it'll be packaged [via npm](https://github.com/aspnet/SignalR/blob/dev/package.json). But I can't find it on there yet. You'll probably have to build your own from source.

**Comment by moozzyk** [comment]
For now you need to build and copy yourself. It is not being packaged and published anywhere yet. The easiest way is to clone the SignalR repo and run build.cmd and you will find it in the artifacts folder. The fastest way is to clone the SignalR repo, `npm install`, go to src/Microsoft.AspNetCore.SignalR.Client.TS folder and run `gulp`.

**Comment by moozzyk** [comment]
We are now publishing the client as npm module. The module contains a browserified version of the client. You can install it using the following command:

`npm install signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/`
