### ISSUE TITLE
Capturing "this" context

### ISSUE THREAD

**Issue by herecydev** [aspnet/SignalR#166]
In the transport and connection typescript classes, you are capturing "this" explicitly but only using lamdas which will capture this for you. See [LongPollingTransport](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts#L160). Is there any reason for that? I've [committed something](https://github.com/herecydev/SignalR/commit/98bc22aed75584fff7f41e2ea2d9c6640bdec6c1) if you would like a PR?

**Comment by davidfowl** [comment]
Ah yes,  that's what lambda's fix 😄.

/cc @moozzyk

**Comment by herecydev** [comment]
Yep, it's much cleaner now.
