### ISSUE TITLE
The TS client doesn't support IPv6 address URLs in Edge

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/SignalR#1662]
Here's an annoying mess:

In Edge (Fall Creators Update), I cannot use IPv6 URLs (`http://[2003:…:3b]/`) in the browser when I want to connect to the server with a relative URL. In [the relevant code](https://github.com/aspnet/SignalR/blob/3a3cebb884ac4164c5f773a4ab652e5a19fbe290/client-ts/signalr/src/HttpConnection.ts#L238), `parser.host` is just `2003:…:3b` (without the brackets), so the resulting URL is invalid. `window.document.location.host` contains the brackets, though.

In Chrome, both `host` properties contain the brackets, so it works.
In Firefox for relative URLs, the `a`-element's `host` property is the empty string and the location's property contains the brackets, so things work.

**Comment by Tragetaschen** [comment]
I've also created https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16476907/

**Comment by anurse** [comment]
Given that this is an issue in Edge, I think our preference would certainly be to get it fixed there. If necessary though, we could probably work around it with custom URL parsing.

**Comment by anurse** [comment]
We don't think we're going to be able to get to this in 2.1. It would mean building some URL parsing code and that's got a bunch of edge cases. We'd certainly consider a PR with lots of tests ;). There is a workaround in that you can resolve the absolute URL manually and pass it in. Hopefully Edge will have a fix for this.

**Comment by mikaelm12** [comment]
Fixed in: e51852d0fc91c10b8eac641d137d10c9348589ec as pointed out in @Tragetaschen's comment here https://github.com/aspnet/SignalR/pull/1828#issuecomment-378514495. Good find!

**Comment by Tragetaschen** [comment]
And for good measure: The issue has been marked fixed for Edge and should appear officially in the next (1809) release of Windows.
