### ISSUE TITLE
Bedrock API review

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1669]
## Connections layer rename

Microsoft.AspNetCore.Http.Connections
Microsoft.AspNetCore.Http.Connections.Common
Microsoft.AspNetCore.Http.Connections.Client

```C#
app.UseConnections(routes =>
{
    // Handle SignalR chat connections on the /chat path (multiple transports)
    routes.MapConnection("chat", connectionBuilder =>
    {
        connectionBuilder.UseSignalR<Chat>();
    });
});
```

## Cleanup

- Rename DefaultConnectionContext to something else
- Remove Microsoft.AspNetCore.Sockets.Abstractions

We need to delete Sockets.Abstractions but `IConnection` is the last remaining hold out once we do the renames.

**Comment by anurse** [comment]
Blocked on #1475

**Comment by davidfowl** [comment]
This is done
