### ISSUE TITLE
how to make the .net standard SignalR client robust to disconnections

### ISSUE THREAD

**Issue by keithn** [aspnet/SignalR#1675]
I'm not sure how to detect disconnection / failures.  I want a system which trys to keep a connection established.  But it can fail at that start, and can get fail during the connection

I'm not sure how to hook any of that.  The only thing that seems to get notifications is the Log?  

Is the idea to hook the log and translate what's going on?

or am I missing something?

**Comment by anurse** [comment]
> Is the idea to hook the log and translate what's going on?

Definitely not :). Logging is never expected to be used by the application itself, only for diagnostics tools and investigations after the fact.

`HubConnection.StartAsync` can fail, if an error occurs initializing the exception. If that completes successfully, any other connection errors will cause the `.Closed` event to be triggered, which has an optional exception parameter.

So you'd do something like this:

```csharp
public HubConnection ConnectAsync() 
{
    var connection = /* create a HubConnection */
    connection.Closed += HandleDisconnect;
    try 
    {
        await connection.StartAsync();
    }
    catch(Exception ex)
    {
        HandleDisconnect(ex);
    }
    
    return connection;
}

public void HandleDisconnect(Exception ex)
{
    if(ex == null)
    {
        // Server disconnected "gracefully" (with no error)
    }
    else
    {
        // An error occurred, which terminated the exception
        // Log it, and reconnect.
    }
}
```

**Comment by keithn** [comment]
ok, I'll have a bit more a play, I had the closed hooked, but it didn't seem to trigger when the server disappeared.  But might be something I'm doing

**Comment by Nickname863** [comment]
Same here
when i kick the Server while a connection is already build. SignalR will throw an error
![image](https://user-images.githubusercontent.com/33596703/38174076-fa126df8-35c7-11e8-823a-2429cefb093c.png)
however the code that should execute on Close didn't seem to execute

**Comment by los93sol** [comment]
I noticed similar, but opposite.  I was monitoring disconnects on the server and observed breaking the network connection between client and server that it took some time before the server fire OnDisconnected for that client, guessing it’s detected with a heartbeat method of some type and only fires after the timeout lapses for that connection to be heard from.  I would expect similar to happen on the client end as well.

**Comment by anurse** [comment]
> observed breaking the network connection between client and server that it took some time before the server fire OnDisconnected for that client

The only reliable way to detect any broken network connection is a timeout, since the connection could be lost before a "Close" message is sent. Today, the client times out when it hasn't heard from the server in 30 seconds, and the server sends "keep-alive" messages every 15 seconds so that the client doesn't time it out, even if there aren't any "real" messages being sent. However, we don't do the same **from** the client **to** the server, so the only way for the server to detect a timeout is when the underlying TCP connection times out. On Windows, we observed this happening quite quickly (~30 seconds). On Linux the default timeout is very long (5+ minutes). To help resolve this we're adding client-to-server pings in 2.2, so the server will be able to detect disconnected clients more quickly.

**Comment by anurse** [comment]
> when i kick the Server while a connection is already build. SignalR will throw an error
> 
> however the code that should execute on Close didn't seem to execute

@Nickname863 sorry for the delay in responding, I missed this one somehow. If you're still seeing this issue in the latest RTM builds, please file a new bug and include the code you are expecting to see execute.

**Comment by Nickname863** [comment]
Well it turns out i just used the wrong method. 
Sorry for that confusion :/
![image](https://user-images.githubusercontent.com/33596703/42134579-dd275f0a-7d3e-11e8-8913-0250befe658d.png)

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
