### ISSUE TITLE
Azure Service Bus backplane for Signalr core

### ISSUE THREAD

**Issue by DebolaA** [aspnet/SignalR#1676]
is Azure Service Bus backplane available for signalr core.

which backplane is available for a signalr core app that is hosted on Azure cloud.

thank you.

**Comment by davidfowl** [comment]
We have no plans to do a service bus backplane this release. I'd recommend using redis as it's more suited for volatile messaging. See https://github.com/aspnet/SignalR/issues/501.

**Comment by DebolaA** [comment]
@davidfowl thank you.
