### ISSUE TITLE
SignalR Client add the ability to unregister a handler without passing in the function handler

### ISSUE THREAD

**Issue by spudcud** [aspnet/SignalR#1677]
Right now the actual function handler has to be passed in to off in order to unregister it but keeping track of the handler is not desired. I want to unregister the event itself and don't care about what functions are registered to it. This used to be possible in the old SignalR version and would be nice to get added back in. I understand the desire to unregister a specific handler but unregistering all is useful too as we only ever have one per event.

`connection.off("myEvent", myHandler );`

Desired:
`connection.off("myEvent");`

**Comment by davidfowl** [comment]
Seems reasonable. Care to send a pull request?

**Comment by spudcud** [comment]
I'll test out some changes and then I'll look into figuring out how to submit the PR. Haven't done it yet so it will be a learning experience :)

**Comment by davidfowl** [comment]
@spudcud We're here for moral support as well as technical support 😄.

**Comment by spudcud** [comment]
Haha, thanks David!!

**Comment by spudcud** [comment]
Morning. So, I unfortunately can't create a pull request. I have not been able to test the changes using dev latest. You can see the changes in the fork and here is the main change that I would recommend to allow for this feature and I added a test for it as well. I am not sure how to run the test or compile the typescript at this point. If you have any questions please reach out to me privately.

```javascript
    public off(methodName: string, method?: (...args: any[]) => void) {
        if (!methodName) {
            return;
        }

        methodName = methodName.toLowerCase();
        const handlers = this.methods[methodName];
        if (!handlers) {
            return;
        }

        if (method) {
            const removeIdx = handlers.indexOf(method);
            if (removeIdx !== -1) {
                handlers.splice(removeIdx, 1);
                if (handlers.length === 0) {
                    delete this.methods[methodName];
                }
            }
        }
        else {
            delete this.methods[methodName];
        }
    }
```

**Comment by anurse** [comment]
Since you have a test already, feel free to just open a PR now and we can iterate on it there (the CI will automatically run the tests so you could luck out and everything could just work ;)). As I said above, feel free to reach out to me for assistance!

**Comment by mikaelm12** [comment]
Done here: 3952eacfaa03af3519cb0d5666d2952bfa5f3de3

**Comment by spudcud** [comment]
Thanks @mikaelm12 for getting it done. It will make my life a lot easier :)

**Comment by mikaelm12** [comment]
@spudcud Glad to hear it!
