### ISSUE TITLE
Authorization of signalr

### ISSUE THREAD

**Issue by KennethInfoEasy** [aspnet/SignalR#1687]
Hi, I have a hub that is decorated with [Authorize], when running in debug (IIS) everything works perfectly ,, but when running against the localhost site (IIS) I get:

401 (Unauthorized)
Uncaught (in promise) Error: Unauthorized
    at new HttpError (signalr.min.js:13)
    at XMLHttpRequest.xhr.onload (signalr.min.js:13)

Seems like a racing problem since working in debug, but i cannot find the issue.  So same host, same build, same browser. Running debug i'm authorized , running normally not authorized. Even when i''m logged into the site.  Any clues?

**Comment by KennethInfoEasy** [comment]
It turnes out that when i remove the authorize decorator I still get the user onconnect. when not debugging the user is null.

**Comment by anurse** [comment]
How are you authenticating users? Cookies? Are you able to isolate this and provide sample code that reproduces the problem?

**Comment by KennethInfoEasy** [comment]
Correct, with cookies. I will try to isolate and provide github sample

Sendt fra min iPhone

22. mar. 2018 kl. 17:26 skrev Andrew Stanton-Nurse <notifications@github.com<mailto:notifications@github.com>>:


How are you authenticating users? Cookies? Are you able to isolate this and provide sample code that reproduces the problem?

-

**Comment by KennethInfoEasy** [comment]
Hi, I wrote a simple project, and I cannot for the life of me reproduce this in the new project. I should mention that i use the HubWithPrencense classes which I now belive is the source of my issues. I will investigate later. In my original project I can still reproduce the issue.

**Comment by anurse** [comment]
Yeah, you could try introducing those classes into your simple repro. If you are able to share anything from your original project, that may help me investigate further.

**Comment by anurse** [comment]
Thanks. If you need to share it privately, you can contact me directly at `[my github username]@microsoft.com`

**Comment by KennethInfoEasy** [comment]
Hi, I have now added the classes and now how issues with the hub. You can see the test project here: https://github.com/KennethInfoEasy/test/tree/master/SignalRAuth 
Even though I havent reproduced the orginial issue. I still think this is the root of the issue.

**Comment by HaoK** [comment]
@KennethInfoEasy so can you clarify what's the issue I should look at in the new repro?  I cloned it and fixed it so login works, and it displays:

Hello, nothing more to see here!
You are logged in and should be connected to the TestHub
Connected to hub:

**Comment by HaoK** [comment]
@KennethInfoEasy without more info for how to reproduce the issue with your test project, there's not much we can do here

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
