### ISSUE TITLE
Rework HubConnectionBuilder

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#1688]
~~Specifically we want to log unknown message types~~

Also, we can consider adding a service collection as the backend for the `HubConnectionBuilder` to have DI on the client.

Some context: https://github.com/aspnet/SignalR/pull/1666#discussion_r176460811

**Comment by anurse** [comment]
If we do this right, we could end up with the same extension methods by having the new builder implement `ISignalRBuilder` (or something like that)
