### ISSUE TITLE
Change to MessagePack-CSharp

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1690]
https://github.com/neuecc/MessagePack-CSharp/

* Remove the structural MessagePack tests, they're nice but if they don't work easily let's just get this in
* Verify that case-insensitive binding works and if not, file an issue and try to get that moving.

**Comment by moozzyk** [comment]
Make sure this kinds of scenarios work https://github.com/neuecc/MessagePack-CSharp/issues/61. When I originally looked at MessagePack-CSharp it was not [mature enough](https://github.com/aspnet/SignalR/issues/543#issuecomment-313100131).

**Comment by BrennanConroy** [comment]
neuecc/MessagePack-CSharp#223 to track ContractlessReflectionObjectResolver
