### ISSUE TITLE
Problem with ASP.NET Core 2.1.0-preview1-final and SignalR 1.0.0-preview-final on .NetFramework 4.7.1

### ISSUE THREAD

**Issue by simonatecsa** [aspnet/SignalR#1699]
Hello, 

Are ASP.NET Core 2.1.0-preview1-final and SignalR 1.0.0-preview-final compatible with .NetFramework 4.7.1? I tried to make SignalR work and it passes the negotiate phase, but after, it says that "Error: Failed to start the connection: Error: Unable to initialize any of the available transports."
On the client I used the js that I got from here: npm install @aspnet/signalr --registry https://dotnet.myget.org/f/aspnetcore-dev/npm/
Are they compatible? Shall I continue to try to make it work? Is there a list where it says which server version goes with each client version?

Thank you,
Simona

**Comment by anurse** [comment]
Those versions should be compatible. Can you provide some more information about your scenario so we can investigate further and identify the issue?

* What server(s) are you using (Kestrel, IIS Express, etc.)?
* What operating system are you running on (Windows/Linux/macOS)?
* What browser are you using?
* Can you provide a snippet of the code in your `Startup.cs` file that configures SignalR so we can review that
* Can you enable logging on the client (pass `logger: LogLevel.Trace` to the `HubConnection` constructor, like this: `new signalR.HubConnection(url, { logger: LogLevel.Trace })`)
* Can you get logs from the server? (on the Console when using Kestrel, or to the "ASP.NET Core Web Server" section of the Output Window in VS when using IIS/IIS Express)
* Can you capture Browser Network traces using your Dev Tools? (See [these instructions](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) for generating a HAR file with network traces in Chrome. Please do not post the HAR file in this issue as it is quite large, use a [Gist](https://gist.github.com/) or other hosting service and link it here)

Providing as much data as you can will really help us to resolve your issue ASAP!

**Comment by simonatecsa** [comment]
I'm using Kestrel, running on Windows 10 x64, and using Chrome (Version 65.0.3325.181 (Official Build) (64-bit) - latest version)
The methods in Startup.cs :
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(cfg =>
                {
                    cfg.SaveToken = true;
                    cfg.TokenValidationParameters = new TokenValidationParameters
                    {
                        SaveSigninToken = true,
                        RequireExpirationTime = true,
                        ValidateIssuer = false,
                        ValidateAudience = false,
                        IssuerSigningKey = JwtSecurityKey.Create("fiver-secret-key")
                    };

                    cfg.Events = new JwtBearerEvents
                    {
                        OnAuthenticationFailed = context =>
                        {
                            Console.WriteLine("OnAuthenticationFailed: " + context.Exception.Message);
                            return Task.CompletedTask;
                        },
                        OnTokenValidated = context =>
                        {
                            Console.WriteLine("OnTokenValidated: " + context.SecurityToken);
                            return Task.CompletedTask;
                        }
                    };
                });

            services.AddAuthorization(options =>
            {
                options.AddPolicy("Member",
                    policy => policy.RequireClaim("MembershipId"));
            });          
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAll",
                    builder =>
                    {
                        builder
                            .AllowAnyOrigin()
                            .AllowAnyMethod()
                            .AllowAnyHeader()
                            .AllowCredentials();
                    });
            });
            Assembly webEcommerceAssembly = GetEcommerceWebAppAssembly();
            services.AddMvcCore()
                .AddAuthorization()
                .AddJsonFormatters().AddJsonOptions(j =>
                {
                    j.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.None;
                    j.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                    j.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                }).AddApplicationPart(webEcommerceAssembly).AddControllersAsServices();
            services.AddSignalR();
        }

The Configure Method:
 public void Configure(IApplicationBuilder app)
        {   app.UseAuthentication();
            app.UseCors("AllowAll");
            app.UseFileServer();          
            app.UseMvc(routes =>
            {
                routes.MapRoute("api", "api/{controller}/{action}/{id?}");
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action}/{id?}");
            });
//            app.UseWebSockets();
            app.UseSignalR(routes =>
            {
                routes.MapHub<ControlPanelHub>("/controlPanel");
            });
//adding other middlewares
}

The Hub on the server:
 public class ControlPanelHub : Hub
    {
        public void Send()
        {  ...
                Clients.All.SendAsync("scheduleStatuses", scheduledStatuses);
           ...
        }
     }
On the client side:
    var connection = new signalR.HubConnection('/controlPanel');
    connection.start()
        .then(() => {
            connection.invoke('send');
        }).catch(err => {
            console.log("Error");
        });

    connection.on.scheduleStatuses = onScheduleStatuses;

If I add the LogLevel part it says that LogLevel is not defined.
I'll come back with the HAR file as well
Thank you

**Comment by anurse** [comment]
A few things:

1. I got the log level instruction slightly wrong, you want `var connection = new signalR.HubConnection('/controlPanel', { logger: signalR.LogLevel.Trance })`. I've updated my comment. If you're still seeing issues with logging then, let me know
2. `connection.on.scheduleStatuses = onScheduleStatuses;` is not the correct way to define Client methods in SignalR for ASP.NET Core, you **call** the `on` method like so: `connection.on("scheduleStatues", onScheduleStatuses);` (this isn't causing your issue, just something you'll encounter once we fix this issue :)
3. Can you double-check that you don't have any MVC Controllers or Razor Pages that would match the route `/controlPanel`? If you do, they will take over the request before it hits SignalR.

The HAR file and additional client logging will help further diagnose the issue, update this thread when you've been able to collect them (or if you have any issues collecting them)!

**Comment by simonatecsa** [comment]
- Url to the HAR file - https://gist.github.com/simonatecsa/9ee30a844582e102dc102adb690e6c4f
- I've modified the "on" method call
- Double checked the Controllers, I don't have any pages that would match the route
- I have AngularJs 1.6.9 on the client side - can this be an issue?
- After logging, the error is 
'''
Loggers.ts:40 Information: Normalizing '/controlPanel' to 'http://localhost:8099/controlPanel'.
3Loggers.ts:44 Trace: Skipping transport 'undefined' because it is not supported by this client.
Loggers.ts:36 Error: Failed to start the connection: Error: Unable to initialize any of the available transports.
'''

**Comment by anurse** [comment]
> Loggers.ts:44 Trace: Skipping transport 'undefined' because it is not supported by this client.

This log message was added **after** preview1. Are you sure you're using the `1.0.0-preview1` build of the JavaScript client? If you are using a later build, you have to use the matching Server build, as the protocol is changing frequently during development.

**Comment by anurse** [comment]
> On the client I used the js that I got from here: npm install @aspnet/signalr --registry https://dotnet.myget.org/f/aspnetcore-dev/npm/

Ah, I see this now. No, the latest client from that registry is **not compatible** with SignalR 1.0.0-preview1-final. You should use the version on the main NPM registry.

**Comment by simonatecsa** [comment]
Ok, took the latest version, now it connects, gets the data, but after a few seconds disconnects and I have this error in console "Transports.ts:263 Error: Connection disconnected with error 'Error: Websocket closed with status code: 1006 ()". 
Also, on the server the Dispose on the Hub is called, even though I don't call it and when trying to put data on "Clients.All.SendAsync("scheduleStatuses", scheduledStatuses);" I receive this
"		Message	"Cannot access a disposed object.\r\nObject name: 'ControlPanelHub'.""
Do you know who is calling the dispose method and why? 
Also...is there a way to reconnect?

**Comment by anurse** [comment]
> Also, on the server the Dispose on the Hub ... Do you know who is calling the dispose method and why?

The Hub is disposed after each invocation, you can't store state on the Hub.


> Also, on the server the Dispose on the Hub is called, even though I don't call it and when trying to put data on
> Clients.All.SendAsync("scheduleStatuses", scheduledStatuses);
> 
> I receive this error
> "	Message	"Cannot access a disposed object.\r\nObject name: 'ControlPanelHub'.""

Are you seeing this exception thrown by `SendAsync`? The Hub should not be disposed while a method is executing, so as long as you aren't launching async code without `await`ing it, this shouldn't be happening.

Can you provide a more complete example of your Hub code and where it's throwing?

> Also...is there a way to reconnect like in the old SignalR?

There is no automatic reconnection, and we don't buffer messages to replay them when clients come back online. However, you can re-start a `HubConnection` by calling start again in the closed event handler.

**Comment by spudcud** [comment]
I also noticed there was no reconnect. What is the consequence of it not automatically reconnecting? We had to handle the reconnect special in old SignalR because it created a new connection ID and we needed to link the old ID with the new ID because of backend logic. Is there a recommended approach for reconnecting? I'm assuming there may be some gotchas or scenarios that cannot be reconnected etc? I do handle the closed event handler but is there any recommended way to do a reconnect there? Also is there a way to force a disconnect for testing purposes to make sure our code will handle it (hopefully the step isn't to recycle the app pool).

This is marginally off topic so if it needs to move let me know.

**Comment by anurse** [comment]
Reconnection is handled by your application. You can call `StartAsync` in the `HubConnection.Closed` event and restart the connection that way. A new connection ID will indeed be generated, so you'll want to use Groups, Users or your own mapping of IDs to connection IDs on the server to identify users in order to manage clients across reconnects.

**Comment by simonatecsa** [comment]
Hub code:
        public class ControlPanelHub : Hub
    {
...
        public void Send()
        {
  ...
            SetTimer(notificationInterval);
...
            NotifyClients();
        }

        private void SetTimer(int notificationInterval)
        {
            lock (SyncTimer)
            {
                if (timer == null)
                {
                    timer = new System.Threading.Timer(OnTimerCallback, null, 0, notificationInterval);
                }
            }

        }

        private void OnTimerCallback(object state)
        {
            NotifyClients();
        }

        private bool isNotifying;
        private void NotifyClients()
        {
            if (!ShouldSendNotifications)
            {
                return;
            }

            if (isNotifying)
            {
                return;
            }
            isNotifying = true;
            try
            {

                List<ScheduleStatus> scheduledStatuses = new List<ScheduleStatus>();

                foreach (var ceva in cevas)
                {
                    List<ScheduleStatus> schedules = Schedules.GetScheduleStatuses();
        
                    schedules.ForEach(
                        s =>
                        {
                            ...

                        });
                    scheduledStatuses.AddRange(schedules);
                }
                Clients.All.SendAsync("scheduleStatuses", scheduledStatuses);
            }
            finally
            {
                isNotifying = false;
            }

        }
    }

The exception is thrown by: 'Clients.All' threw an exception of type 'System.ObjectDisposedException'
We don't have any other asynchronous methods...shall we have?
Thank you

**Comment by spudcud** [comment]
You cannot do any timer/callback type logic in the Hub because it gets disposed after each call. What you need to do is setup another service that will manage this for you. You will need to use dependency injection and register your new service. This is all possible because of DI and the ability to inject IHubContext<yourhub> into another service. You can also inject a user tracker as well in the same way.

In Startup.cs ConfigureServices setup a new singleton
```services.AddSingleton(typeof(YourNewService), typeof(YourNewService));```

You can then create your service and inject the IHubContext so that you have access to the clients and in there you can have timers or whatever you want as it will be a singleton with state.

```
   public class YourNewService
   {
      private IHubContext<ControlPanelHub> _hubContext;
      public YourNewService(IHubContext<ControlPanelHub> hubContext)
      {
         _hubContext = hubContext;

         // Do any timer initialization/setup etc or do it via method call.
      }

      private void OnTimerCallback(object state)
      {
         NotifyClients();
      }

      private void NotifyClients()
      {
         _hubContext.Clients.All.SendAsync("Notification");
      }
   }
```

**Comment by anurse** [comment]
@spudcud 's got the right answer here! Hope that helps.

**Comment by simonatecsa** [comment]
Awesome, it works now. Thank you very much, I will close the issue

**Comment by bangonkali** [comment]
Hi Guys, I encounter the same error following the Chat example. I have uploaded the project [here](https://drive.google.com/file/d/1nC-5HsNNBpVhVF9pIE3irHZRkdS-6DG1/view?usp=sharing). 

![image](https://user-images.githubusercontent.com/539946/38913942-da8000a4-430f-11e8-9b52-73986e3fd47b.png)


- What server(s) are you using (Kestrel, IIS Express, etc.)? Kestrel
    ```
    ➜  Projects dotnet --version
    2.1.300-preview1-008174
    ```
- What operating system are you running on (Windows/Linux/macOS)? MacOS
    ```
    Software:

        System Software Overview:

        System Version: macOS 10.13.4 (17E199)
        Kernel Version: Darwin 17.5.0
        Boot Volume: Macintosh HD
        Boot Mode: Normal
        Computer Name: Mac
        User Name: Gil Michael Regalado (gilmichael)
        Secure Virtual Memory: Enabled
        System Integrity Protection: Enabled
        Time since boot: 2:28
    ```
- What browser are you using? Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- Can you provide a snippet of the code in your Startup.cs file that configures SignalR so we can review that: [Gist](https://gist.github.com/bangonkali/de37d3024f880d098eb2da5c86f35530)
- Can you enable logging on the client (pass logger: signalR.LogLevel.Trace to the HubConnection constructor, like this: new signalR.HubConnection(url, { logger: signalR.LogLevel.Trace })) **Yes**
- Can you get logs from the server? (on the Console when using Kestrel, or to the "ASP.NET Core Web Server" section of the Output Window in VS when using IIS/IIS Express) [Gist](https://gist.github.com/bangonkali/da39f8f76447ef4aad7d591df8160597)
- Can you capture Browser Network traces using your Dev Tools? (See these instructions for generating a HAR file with network traces in Chrome. Please do not post the HAR file in this issue as it is quite large, use a Gist or other hosting service and link it here) [Upload](https://drive.google.com/open?id=10iqeWWU_vWIObzsBy_jmF8i9hY9JaOGc)

**Comment by anurse** [comment]
I appreciate the details but would strongly recommend you file a new bug, otherwise we can easily lose track of this (potentially new) issue. We can't really track investigation into your issue if it's just attached to an existing closed bug.

**Comment by Kriegthor23** [comment]
@bangonkali (or @anurse)  if you have posted please  let me know about the solution for bangonkali's issue since im having the same issue on windows10  if you need more info about anything please tell me how to supply them to you since im a newbie for git stuff and i do not know much about it

thanks in advance

**Comment by anurse** [comment]
@bangonkali the project you uploaded shows the `preview2` build of the client but the `preview1` build of the server. You need to use the same versions on the client and server until RTM.

@Kriegthor23 Check your package versions as I suggested to @bangonkali , otherwise if you are still having this problem, please file a new issue.
