### ISSUE TITLE
How to create a JS client in Angular 2

### ISSUE THREAD

**Issue by AbrarJahin** [aspnet/SignalR#170]
Hi, I am new in [Angular2](http://www.angular2.com/).

I want to implement SignalR with Angular2, but there is no proper library for this as far as I have been searching.

So, can you please create an Angular2 compatible javascript library for that so that we can use signalR with latest Angular2?

Thanks

**Comment by moozzyk** [comment]
You might need to build the javascript client yourself (as described here https://github.com/aspnet/SignalR/issues/165#issuecomment-275930704). If you still can't make it work with Angular2 please reopen this issue and provide details about specific problems you hit.
