### ISSUE TITLE
Stress: Add a stress scenario for long-running connections with the client

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1700]
We should have a constantly-running test with a Client connected to a Server (using each transport) being utilized very infrequently to ensure we keep the connection alive as necessary. We've seen use cases for long-running low-traffic connections in IoT devices with SignalR for ASP.NET and we should ensure our logic allows for a long-running connection of this type.

cc @BrennanConroy @davidfowl 

@sebastienros Is this kind of scenario possible with our stress platform?

**Comment by sebastienros** [comment]
"easy peasy" would be an understatement

**Comment by anurse** [comment]
The thing about this, is that unlike Kestrel's stress scenarios, for this one, I want a client that almost never sends a message. The client sends VERY infrequently, but asserts that the connection is still established and working. We would run this scenario constantly (never stop it) and have it notify us if it ever fails (possibly also have something monitoring CPU/Memory usage on the client and server).

We'd have to allocate some permanently-running Azure resource to just this test, but honestly the server could just be an App Service or cheap VM. We're not interested in performance, just longevity and reliability.

**Comment by sebastienros** [comment]
We are already doing it for windows and linux, weekly and daily restarts (two different sets of environment running 24/7 on Azure). We define a custom load to reach 50% CPU (our choice) and get graphs to analyze long term latencies and memory usage. It's compatible with any benchmark client (oh and you have one already) and the setup takes 10 minutes.

**Comment by anurse** [comment]
@davidfowl what do you want to do here for 2.1? Should we just move this out to 2.2.0-mq?

**Comment by davidfowl** [comment]
@mikaelm12 can you look into this?

**Comment by anurse** [comment]
I think the way to do this is to build a server app that echos messages. Then client apps (C# and Browser) that connect and ping every 30mins or so (reconnecting on failures), then just log every successful or failed ping. Run it for a while and see how it goes. We should test all three transports this way too.

The scenario we're checking is that long-running, low-traffic connections are stable and stay open.

**Comment by sebastienros** [comment]
This is already handled by the driver, pass 30s as duration and 1 day as span, it will create new connections every 30s, log the results, and do it for one day. Or do you need something that keeps connections alive even longer than the stats log delay?

**Comment by BrennanConroy** [comment]
We don't want new connections

**Comment by anurse** [comment]
The goal here is to test a single long-running connection

**Comment by sebastienros** [comment]
Then maybe just create a new client that works this way (or a new option in the client) based on the duration arg, but still use spans of multiple days to keep the server alive as it might also show some issues.

**Comment by mikaelm12** [comment]
Done. Added here: https://github.com/aspnet/benchmarks/commit/6948a742444f0af977a78b36a2f3ba1abf748485
We now have long running stress jobs running and hooked up to a Power BI
