### ISSUE TITLE
Unit test receiving multiple messages and partial messages

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1704]
Need more unit tests for:
* Receiving multiple messages
* Receiving partial messages

Test in
* Server
* C# client
* ~TS client~

**Comment by davidfowl** [comment]
We currently don't send partial messages anywhere. Once @anurse finishes his change we can decide if we ever want to send partial messages to the client (I don't think we do), at least not in the short term.

**Comment by anurse** [comment]
> We currently don't send partial messages anywhere.

This is true currently, but we've talked about writing WebSocket messages to the pipeline even when `EndOfMessage` is `false`. This will cause partial messages to be written in the case of large messages, or messages that [straddle buffers](https://github.com/aspnet/SignalR/blob/dev/src/Common/WebSocketExtensions.cs#L39)

**Comment by davidfowl** [comment]
That will only affect the c# client for websockets and incoming messages on the server (we can do this for all transports for incoming data). JavaScript will never get partial messages.
