### ISSUE TITLE
How to download '2.1.0-preview2-26314-02'

### ISSUE THREAD

**Issue by kevin-jing** [aspnet/SignalR#1706]
PS C:\Users\xxx\Documents\SignalR\samples\ChatSample> dotnet run -f netcoreapp2.1
Using launch settings from C:\Users\xxx\Documents\SignalR\samples\ChatSample\Properties\launchSettings.json...
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview2-26314-02' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\

      https://aka.ms/dotnet-download-runtime
  - The .NET framework and SDK can be installed from:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The following versions are installed:
      1.1.0 at [C:\Program Files\dotnet\shared]
      2.0.6 at [C:\Program Files\dotnet\shared]
      2.1.0-preview1-26216-03 at [C:\Program Files\dotnet\shared]

**Comment by anurse** [comment]
Running `./build /t:Restore` in the root of the repository will download the appropriate runtime automatically and install it to `C:\Users\[Your User Name]\.dotnet\x64`. Run that script and make sure `C:\Users\[Your User Name]\.dotnet\x64` is in your `PATH` environment variable and Visual Studio and `dotnet run` should work.

**Comment by kevin-jing** [comment]
Not sure why it failed, but Thanks Andrew anyway for answering.

.NET Core SDK 2.1.300-preview2-008367 is already installed. Skipping installation.
>>> dotnet.exe msbuild @C:\Users\xxx\Documents\SignalR\artifacts\logs\msbuild.rsp @C:\Users\xxx\Documents\SignalR\artifacts\logs\msbuild.logger.rsp
C:\Users\xxx\.dotnet\buildtools\korebuild\2.1.0-preview3-15744\modules\KoreBuild.Tasks\module.targets(140,5): error : Could not find NodeJS on PATH. [C:\Users\xxx\.dotnet\buildtools\korebuild\2.1.0-preview3-15744\KoreBuild.proj]

Build FAILED.

C:\Users\xxx\.dotnet\buildtools\korebuild\2.1.0-preview3-15744\modules\KoreBuild.Tasks\module.targets(140,5): error : Could not find NodeJS on PATH. [C:\Users\xxx\.dotnet\buildtools\korebuild\2.1.0-preview3-15744\KoreBuild.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.38
dotnet.exe failed with exit code: 1
At C:\Users\xxx\.dotnet\buildtools\korebuild\2.1.0-preview3-15744\scripts\common.psm1:11 char:9
+         throw "$cmdName failed with exit code: $exitCode"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit code: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1

**Comment by anurse** [comment]
> error : Could not find NodeJS on PATH.

As it says, you need [NodeJS](https://nodejs.org/en/) installed to build SignalR

**Comment by kevin-jing** [comment]
The build was done, but dotnet run still failed. I used the following command to run:
>>> C:\Users\xxx\.dotnet\x64\dotnet.exe run -f netcoreapp2.1
Then it works!

**Comment by kevin-jing** [comment]
It works now as above.
