### ISSUE TITLE
How to Server broadcast means that communications sent to clients are initiated by the server

### ISSUE THREAD

**Issue by kevin-jing** [aspnet/SignalR#1707]
In dotnet framework, we can use GlobalHost.ConnectionManager.GetHubContext<StockTickerHub>().Clients), as in https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/tutorial-server-broadcast-with-signalr.

But in dotnet core, GlobalHost doesn't exist at all.

**Comment by anurse** [comment]
GlobalHost was needed because ASP.NET 4.x did not have dependency injection. In ASP.NET Core you can achieve the same thing by injecting `IHubContext<MyHub>` into the constructor of your MVC Controllers, DI Services, etc.

See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection for more information on dependency injection.

**Comment by kevin-jing** [comment]
Thanks Andrew for the answer. It will be better if a sample is provide. :)

**Comment by anurse** [comment]
Yep, we're tracking it here: https://github.com/aspnet/Docs/issues/5493

Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.

**Comment by kevin-jing** [comment]
It looks like MVC Controller can only be called by clients. Is that possible for the server app to run a thread when the server app starts? How to get IHubContext<MyHub> in a singleton class?

**Comment by anurse** [comment]
Any type in the DI container can have `IHubContext<T>` injected into it, even a singleton. If you need a "background thread", I suggest you create a type implementing [`IHostedService`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostedservice?view=aspnetcore-2.0). The `StartAsync` method will be called on server startup. You could do something like this to create a background process that can invoke methods on client hubs:

```csharp
public class MyBackgroundService : IHostedService
{
    private readonly CancellationTokenSource _cancellationTokenSource = new CancellationTokenSource();
    private readonly IHubContext<MyHub> _hubContext;

    public MyBackgroundService(IHubContext<MyHub> hubContext)
    {
        _hubContext = hubContext;
    }

    public Task StartAsync()
    {
        _ = BackgroundTask(_cancellationTokenSource.CancellationToken);
    }

    public Task StopAsync()
    {
        _cancellationTokenSource.Cancel();
    }

    private Task BackgroundTask(CancellationToken cancellationToken)
    {
        while(!cancellationToken.IsCancellationRequested)
        {
            // Do stuff with _hubContext!
        }
    }
}
```

Then just register `MyBackgroundService` with `services.AddSingleton<IHostedService, MyBackgroundService>()` in `ConfigureServices`

**Comment by davidfowl** [comment]
In 2.1 there's a first class BackgroundService type already @anurse https://github.com/aspnet/Hosting/blob/e93aa56b588bee1e9ef0d25fd0176545f91d0c40/src/Microsoft.Extensions.Hosting.Abstractions/BackgroundService.cs

**Comment by kevin-jing** [comment]
With the help of @anurse and @davidfowl , I did it finally in dotnet Core. Thank you both!

I'm sharing the 1st edition. Later, I will try to use BackgroundService class, proposed by @davidfowl to reduce the code length.

Startup \ ConfigureServices:
`services.AddSingleton<Microsoft.Extensions.Hosting.IHostedService, MyBackgroundService>();`

MyBackgroundService.cs:
`using ChatServer.Hubs;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ChatServer
{
    public class MyBackgroundService : IHostedService
    {
        private Task _executingTask;
        private readonly CancellationTokenSource _cancellationTokenSource = new CancellationTokenSource();
        private readonly IHubContext<ChatHub> _hubContext;

        public MyBackgroundService(IHubContext<ChatHub> hubContext)
        {
            _hubContext = hubContext;
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            _executingTask = BackgroundTask(_cancellationTokenSource.Token);

            // If the task is completed then return it, this will bubble cancellation and failure to the caller
            if (_executingTask.IsCompleted)
            {
                return _executingTask;
            }

            // Otherwise it's running
            return Task.CompletedTask;
        }

        public async Task StopAsync(CancellationToken cancellationToken)
        {
            // Stop called without start
            if (_executingTask == null)
            {
                return;
            }
            try
            {
                _cancellationTokenSource.Cancel();
            }
            finally
            {
                // Wait until the task completes or the stop token triggers
                await Task.WhenAny(_executingTask, Task.Delay(Timeout.Infinite, cancellationToken));
            }
        }

        private async Task BackgroundTask(CancellationToken cancellationToken)
        {
            Console.WriteLine("MyServiceA is starting.");

            cancellationToken.Register(() => Console.WriteLine("MyServiceA is stopping."));

            while (!cancellationToken.IsCancellationRequested)
            {
                Console.WriteLine("MyServiceA is doing background work.");

                await _hubContext.Clients.All.SendAsync("BroadcastMessage", "server", "123");

                await Task.Delay(TimeSpan.FromSeconds(5), cancellationToken);
            }

            Console.WriteLine("MyServiceA background task is stopping.");
        }

        public virtual void Dispose()
        {
            _cancellationTokenSource.Cancel();
        }
    }
}
`

**Comment by kevin-jing** [comment]
`using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Hosting;

namespace MyBackgroundService
{
    public class MyBackgroundService : BackgroundService
    {
        private readonly IHubContext<ChatHub> _hubContext;
        public MyBackgroundService(IHubContext<ChatHub> hubContext)
        {
            _hubContext = hubContext;
        }
        protected override async Task ExecuteAsync(CancellationToken cancellationToken)
        {
            while (!cancellationToken.IsCancellationRequested)
            {
                await _hubContext.Clients.All.SendAsync("BroadcastMessage", "server", "123");

                await Task.Delay(TimeSpan.FromSeconds(5), cancellationToken);
            }
        }
    }
}
`

**Comment by davidfowl** [comment]
👍
