### ISSUE TITLE
Handling slow consumers with batching

### ISSUE THREAD

**Issue by Kikimora** [aspnet/SignalR#1719]
I’m building typical stock app with charts and sending market updates with signalr over web sockets. Clients will be fine if instead all events they will get aggregated view. For example 100 trades might happen in a given second but clients will be fine if I aggregate them in a single bar. 
Ideally I’d like to batch updates on ubservable while signalr sending previous batch. This way I update clients at fastest possible rate. Please advise how can I achieve this with SignalR.

**Comment by davidfowl** [comment]
Think of SignalR as bidirectional RPC over a socket. It doesn't provide anything first class OOTB for the scenario you mention, you have to build this yourself. We provide a channel and programming pattern, you build the semantics you desire.

> Please advise how can I achieve this with SignalR.

One thing you could do is write a sample without a network, just write a console application with an IObservable and a bunch of subscribers (simulating clients). Once you get that working then you can expose the data over SignalR (streaming method or background thread doing client invocation).

**Comment by Kikimora** [comment]
@davidfowl Thanks, I think I figured this out. It looks like by the time SignalR observer returns from OnNext, bytes had been already sent to net. This means I can call OnNext in a loop while aggregating data in a separate thread.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
