### ISSUE TITLE
Clients in multiple Groups

### ISSUE THREAD

**Issue by novatiny** [aspnet/SignalR#1748]
Hi,

I have multiple users in multiple groups:

usr1  | usr2  | usr3
----- | ----- | -----
grp1  | grp1  | grp2
grp2  | grp3  | grp3
grp3  |

Is there a way to send data to every user that is in `grp2` and also in `grp3`.

Currently if I send a message to `{ "grp2", "grp3" }` `usr2` would also get the message because he is part of `grp3`.

v.1.0.0-preview1-final

**Comment by davidfowl** [comment]
No there's no way to do that. You need to make another group (grp2andgrp3) and send to that.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
