### ISSUE TITLE
SendAll SendGroup* of LifetimeManager do not have sender's context ID

### ISSUE THREAD

**Issue by ccic** [aspnet/SignalR#1767]
For the group sending, like SendAllAsync, SendGroupAsync, and SendGroupsAsync, there is no sender's connection ID which can be used to find connection context.

There is a requirement of my service: if there is a group sending, for example, SendAllAsync on SDK side, we'd like to reuse the same connection context to send this message back to service.

Currently, I implemented this by adding a connectionId for all group sending method of LifetimeManger, meanwhile, passing the connection Id to HubClients, and invoking new group sending method.

**Comment by anurse** [comment]
We can definitely include the connection ID. Should we include the sender's entire `HubConnectionContext`? We should have that information.

**Comment by davidfowl** [comment]
I was thinking we include the HubConnectionContext. There's a question as to what happens when you get an IHubContext out of thin air though, do we create one on the fly?

**Comment by anurse** [comment]
Or maybe the value is allowed to be null? There's no connection context associated with an invocation from an `IHubContext<T>`

**Comment by davidfowl** [comment]
The original Signalr created a synthetic sender but we'd need to think about it a little

**Comment by davidfowl** [comment]
Closing this as it isn't required after discussing with @ccic
