### ISSUE TITLE
Syntax errors in IE11

### ISSUE THREAD

**Issue by Blankinfinity** [aspnet/SignalR#177]
#Hi,

I have just built the project and i then ran the ChatSample project. I started it up and it launched in IE11. When clicking on any of the links from the main page I am getting syntax erros in the signalr-client.js and also the relating html files. Just to check whether it was an issue with the scripts or IE i opened the same links within ff, edge and chrome. These all worked without any issue.

Is this version of signalr supposed to work with IE? If you need more details on where the scripts and pages are throwing errors let me know and i'll add them here.

Update: Have been doing a bit of googling and came to the conclusion it's because IE11 doesn't support es6, is there any likelyhood that this will be available for es5? I have had a go at converting it myself but just running into a "Promise is undefined" error, which has something to do with polyfill but then it all starts to get a bit confusing. Any pointers in the right direction would be great.

regards

Keith

**Comment by moozzyk** [comment]
Yes, you need a polyfill for Promise.

**Comment by Blankinfinity** [comment]
So will IE11 be supported or not?

**Comment by moozzyk** [comment]
TS/JS client is browser agnostic. As opposed to the version of the client for SignalR 2.x which use jquery, hooked up to browser events and even had some browser version checks this version is not aware of the environment it is running on. Rather, if a required functionality (like Promise) is missing the user needs to ensure it is available. It will be Promise for IE11 but it also will be XmlHttpRequest when running in node.js.

**Comment by Blankinfinity** [comment]
Ok, thanks for the help. Have just this minute got it working in IE11 using commonjs, also had to convert a lot of the scripts on the html pages to es5 too (used the babeljs converter for that).
