### ISSUE TITLE
SignalR.Client 1.0.0-preview1-final - Could not AOT the assembly Microsoft.AspNetCore.Sockets.Abstractions.dll

### ISSUE THREAD

**Issue by FrancoisM** [aspnet/SignalR#1770]
I'm using Microsoft.AspNetCore.SignalR.Client 1.0.0-preview1-final on a mobile app with Xamarin Forms in .Net Standard 2.0. It works well in DEBUG however in Release I got the following build error on iOS.

> MTOUCH : error MT3001: Could not AOT the assembly '/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Microsoft.AspNetCore.Sockets.Abstractions.dll'

**Comment by jaykrell** [comment]
Is the file available? And the mono command line? (and surrounding files -- not sure is needed).

**Comment by FrancoisM** [comment]
> 2018-03-29T19:03:25.9038010Z   AOT Compilation exited with code 2, command:
> 2018-03-29T19:03:25.9066530Z   MONO_PATH=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Threading.Tasks.Extensions.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Msym,outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Threading.Tasks.Extensions.dll.s "/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Threading.Tasks.Extensions.dll"
> 2018-03-29T19:03:25.9116270Z   Cannot open assembly '/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Threading.Tasks.Extensions.dll': File does not contain a valid CIL image.
> 2018-03-29T19:03:25.9138050Z   
> 2018-03-29T19:03:25.9172590Z   AOT Compilation exited with code 134, command:
> 2018-03-29T19:03:25.9281410Z   MONO_PATH=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AspNetCore.Sockets.Abstractions.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Msym,outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AspNetCore.Sockets.Abstractions.dll.s "/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Microsoft.AspNetCore.Sockets.Abstractions.dll"
> 2018-03-29T19:03:25.9310940Z   Mono Ahead of Time compiler - compiling assembly /Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Microsoft.AspNetCore.Sockets.Abstractions.dll
> 2018-03-29T19:03:25.9334980Z   AOTID 4EE3496B-602D-49D2-676A-C3DEED97C005
> 2018-03-29T19:03:25.9360650Z   Could not load signature of Microsoft.AspNetCore.SignalR.Internal.ChannelReaderExtensions:ReadAsync due to: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:<none>
> 2018-03-29T19:03:25.9471880Z   * Assertion at /Users/builder/data/lanes/5808/1c6f300e/source/xamarin-macios/external/mono/mono/mini/mini-generic-sharing.c:3670, condition `mono_error_ok (&error)' not met
> 2018-03-29T19:03:25.9493780Z   
> 2018-03-29T19:03:25.9513240Z   
> 2018-03-29T19:03:25.9532410Z   AOT Compilation exited with code 134, command:
> 2018-03-29T19:03:25.9591740Z   MONO_PATH=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Threading.Channels.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Msym,outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Threading.Channels.dll.s "/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Threading.Channels.dll"
> 2018-03-29T19:03:25.9621430Z   Mono Ahead of Time compiler - compiling assembly /Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Threading.Channels.dll
> 2018-03-29T19:03:25.9646860Z   AOTID FB480F97-7EE0-A503-622D-D52F8B972C22
> 2018-03-29T19:03:25.9674330Z   Could not load signature of System.Threading.Channels.ChannelReader`1[T]:ReadAsync due to: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:<none>
> 2018-03-29T19:03:25.9720310Z   * Assertion at /Users/builder/data/lanes/5808/1c6f300e/source/xamarin-macios/external/mono/mono/mini/mini-generic-sharing.c:3670, condition `mono_error_ok (&error)' not met
> 2018-03-29T19:03:25.9743340Z   
> 2018-03-29T19:03:25.9763190Z   
> 2018-03-29T19:03:26.9259770Z   AOT Compilation exited with code 2, command:
> 2018-03-29T19:03:26.9287490Z   MONO_PATH=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Runtime.CompilerServices.Unsafe.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Msym,outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Runtime.CompilerServices.Unsafe.dll.s "/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Runtime.CompilerServices.Unsafe.dll"
> 2018-03-29T19:03:26.9317490Z   Cannot open assembly '/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Runtime.CompilerServices.Unsafe.dll': File does not contain a valid CIL image.
> 2018-03-29T19:03:26.9339580Z   
> 2018-03-29T19:03:29.2265700Z   AOT Compilation exited with code 2, command:
> 2018-03-29T19:03:29.2292090Z   MONO_PATH=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Memory.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Msym,outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Memory.dll.s "/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Memory.dll"
> 2018-03-29T19:03:29.2320820Z   Cannot open assembly '/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Memory.dll': File does not contain a valid CIL image.
> 2018-03-29T19:03:29.2342230Z   
> 2018-03-29T19:03:29.7759220Z   AOT Compilation exited with code 2, command:
> 2018-03-29T19:03:29.7786500Z   MONO_PATH=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Buffers.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Msym,outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Buffers.dll.s "/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Buffers.dll"
> 2018-03-29T19:03:29.7815730Z   Cannot open assembly '/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Buffers.dll': File does not contain a valid CIL image.
> 2018-03-29T19:03:29.7836820Z   
> 2018-03-29T19:03:31.6536790Z   AOT Compilation exited with code 134, command:
> 2018-03-29T19:03:31.6564110Z   MONO_PATH=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Buffers.Primitives.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Msym,outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Buffers.Primitives.dll.s "/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Buffers.Primitives.dll"
> 2018-03-29T19:03:31.6593170Z   Mono Ahead of Time compiler - compiling assembly /Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.Buffers.Primitives.dll
> 2018-03-29T19:03:31.6617290Z   AOTID 6DF4AA81-61D1-F709-7051-31DE5CFD6489
> 2018-03-29T19:03:31.6642520Z   Could not load signature of System.Buffers.IMemoryList`1[T]:get_Memory due to: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:<none>
> 2018-03-29T19:03:31.6668750Z   * Assertion at /Users/builder/data/lanes/5808/1c6f300e/source/xamarin-macios/external/mono/mono/mini/mini-generic-sharing.c:3670, condition `mono_error_ok (&error)' not met
> 2018-03-29T19:03:31.6690170Z   
> 2018-03-29T19:03:31.6708910Z   
> 2018-03-29T19:03:32.5053760Z   AOT Compilation exited with code 1, command:
> 2018-03-29T19:03:32.5082490Z   MONO_PATH=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.IO.Pipelines.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Msym,outfile=/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.IO.Pipelines.dll.s "/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.IO.Pipelines.dll"
> 2018-03-29T19:03:32.5111690Z   Mono Ahead of Time compiler - compiling assembly /Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.IO.Pipelines.dll
> 2018-03-29T19:03:32.5135980Z   AOTID 25225CBB-2A32-9763-0273-DA7CC954B213
> 2018-03-29T19:03:32.5162660Z   Failed to load method 0x60000d5 from '/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.IO.Pipelines.dll' due to Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:<none>.
> 2018-03-29T19:03:32.5190550Z   Run with MONO_LOG_LEVEL=debug for more information.
> 2018-03-29T19:03:32.5212350Z   AOT of image /Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/System.IO.Pipelines.dll failed.
> 2018-03-29T19:03:32.5233550Z   
> 2018-03-29T19:03:46.3955100Z MTOUCH : error MT3001: Could not AOT the assembly '/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Microsoft.AspNetCore.Sockets.Abstractions.dll' [/Users/vsts/agent/2.131.0/work/1/s/Platforms/MyApp.iOS/MyApp.iOS.csproj]
>

**Comment by davidfowl** [comment]
@jaykrell https://www.nuget.org/packages/Microsoft.AspNetCore.Sockets.Abstractions/1.0.0-preview1-final. I'm assuming i has something to do with System.Memory.

**Comment by FrancoisM** [comment]
Note that this on vsts. I can build DEBUG | iPhone on my machine and install the app on my iPhone. And as soon I use a device rather than the simulator it does AOT compilation normally. So I don't understand why it compiles on my machine and not on VSTS. I'll try to compile on release on my machine to see if any differences.

**Comment by FrancoisM** [comment]
It also builds fine on Release | iPhone on my machine.

**Comment by akoeplinger** [comment]
Do you know which Xamarin.iOS version is getting used VSTS?

**Comment by FrancoisM** [comment]
Actually on my pc the xamarin.ios version is 11.8.0.20 but on my mac it is 11.8.1.28. When I build from the pc connected to the mac I don't really know what is used.

**Comment by FrancoisM** [comment]
Also mono on vsts is 5.8.0 while I'm on 5.8.1

**Comment by FrancoisM** [comment]
I'm trying to make my mac a private agent of vsts and see if it works.

**Comment by FrancoisM** [comment]
I managed to run the vsts build defintion on my mac with a private agent.
And I got the same vsts error:

> MTOUCH : error MT3001: Could not AOT the assembly '/Users/francois/myagent/_work/2/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Microsoft.AspNetCore.Sockets.Abstractions.dll' 


So I'm lost. It works on my machine from (Visual Studio connected to my mac) nut not on vsts running on my mac :-(

**Comment by vargaz** [comment]
Could you upload the obj/iPhone/Release/mtouch-cache directory ?

**Comment by FrancoisM** [comment]
What do you mean by upload?
But it's true that my local build uses that cache folder whereas vsts doesn't.

**Comment by FrancoisM** [comment]
Are you looking for something specific in that directory? I can't upload it here unfortunately as this is client's code so I don't think I'd have the right to do so :-(
Unless I try to reproduce the behavior with a a sample app...

**Comment by FrancoisM** [comment]
The same directory but within the agent directory for vsts doesn't have `Microsoft.AspNetCore.Sockets.Abstractions.dll` 
It only has `Microsoft.AspNetCore.Sockets.Abstractions.aotdata.arm64`

**Comment by FrancoisM** [comment]
Trying to compare MTOUCH args:

When running with VS (same line twice):

```
-r=/Users/francois/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/b4a91b9a48ec7dd4bd9fdcbeb8a49e8c/bin/iPhone/Release/Microsoft.AspNetCore.Sockets.Abstractions.dll
-r=/Users/francois/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/b4a91b9a48ec7dd4bd9fdcbeb8a49e8c/bin/iPhone/Release/Microsoft.AspNetCore.Sockets.Abstractions.dll
```

When running with VSTS:

`-r=/Users/vsts/.nuget/packages/microsoft.aspnetcore.sockets.abstractions/1.0.0-preview1-final/lib/netstandard2.0/Microsoft.AspNetCore.Sockets.Abstractions.dll`

**Comment by anurse** [comment]
We're tracking Xamarin.Forms issues in #1518
