### ISSUE TITLE
HubConnection.StartAsync should timeout the handshake response

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1782]
We currently timeout the negotiate request on the server side but we don't timeout the handshake response on the client. This means if the server took long or never sent the handshake, the client would hang forever in StartAsync (which also means StopAsync would hang see https://github.com/aspnet/SignalR/issues/1781)

**Comment by anurse** [comment]
Ooooooor, we allow a CancellationToken to be passed in \*ducks\*

**Comment by anurse** [comment]
Just need to add a `CancellationToken` to `StartAsync`.

**Comment by BrennanConroy** [comment]
`HttpOptions` should not have a `HandshakeTimeout` as that is a Hub only feature

Currently the only "option" we have for `HubConnection` on the C# client is a public `ServerTimeout` property. Should we add another public property for the timeout?

And we are adding a cancellation token to `HubConnection.StartAsync` as part of this?

**Comment by anurse** [comment]
Good point. Sounds good. And yes, also add a cancellation token.
