### ISSUE TITLE
Browser functional tests begin failing after multiple runs

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1784]
1. Build signalr client and client functional tests
2. Launch functional test server
3. Open browser pointing to test server
4. Refresh browser to run tests multiple times. The tests all pass in the first run. Additional test runs are slower and tests begin timing out.

In the server console I see a lot of this error - https://github.com/aspnet/SignalR/issues/1638#issuecomment-377119918 - and in the client I see `Handshake was canceled.` error messages coming back from the server.

**Comment by JamesNK** [comment]
Tests are fast and pass again if you wait 5 minutes and run them again.

**Comment by davidfowl** [comment]
I don't see them fail...

**Comment by anurse** [comment]
Haven't been able to repro this. We're doing a bunch of work deflaking the tests a bit, @davidfowl has already found some issues. Closing this out unless we see this behavior returning.
