### ISSUE TITLE
Hub.Clients.User() and Hub.Clients.Group() compare string case-sensitivly

### ISSUE THREAD

**Issue by alexxie** [aspnet/SignalR#1797]
Hub.Clients.User() and Hub.Clients.Group() function search connection case sensitively, e.g.

Hub.Clients.Group("abc") does not find connections via Hub.Groups.AddAsync(Groups.AddAsync(Context.ConnectionId, "ABC")

* Versions of Server-Side NuGet Packages: 1.0.0-preview1-final

**Comment by davidfowl** [comment]
That's by design, the group names aren't case sensitive. You should normalize your group names before adding and sending to the group.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
