### ISSUE TITLE
MyGet Repo

### ISSUE THREAD

**Issue by jayrulez** [aspnet/SignalR#18]
Is the MyGet repo ready yet?

@davidfowl

**Comment by moozzyk** [comment]
getting there: https://github.com/aspnet/SignalR/pull/17#discussion_r87104082

**Comment by moozzyk** [comment]
https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.AspNetCore.SignalR

**Comment by jayrulez** [comment]
Awesome :)
