### ISSUE TITLE
Add benchmarks for group sending

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1801]
Basically mimic this benchmark but for groups

https://github.com/aspnet/SignalR/blob/90aa48c09f79fe7c0f3c0e8aeb420816ec15c7f0/benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/BroadcastBenchmark.cs

**Comment by davidfowl** [comment]
@JamesNK I think it makes sense to do this as part of the same benchmark. Add all of the clients to the same group and then do Clients.Group("groupName").SendAsync("Method")

**Comment by JamesNK** [comment]
I was thinking of moving a lot of the code in that class to a test helper and having a new benchmark class that had a param for number of groups
