### ISSUE TITLE
Add Redis broadcast and group micro benchmarks

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1803]
We need to write some micro benchmarks for broadcast scenarios similar to  https://github.com/aspnet/SignalR/blob/90aa48c09f79fe7c0f3c0e8aeb420816ec15c7f0/benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/BroadcastBenchmark.cs. It should be possible to do this with a local redis. This'll let use compare to the in memory benchmark.

**Comment by anurse** [comment]
Done with the fix for #1800
