### ISSUE TITLE
Consider updating DefaultUserIdProvider to support more claims

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/SignalR#1809]
The `DefaultUserIdProvider` class only supports the `ClaimTypes.NameIdentifier` claim. Yet, this (kinda legacy) claim is not always available, specially when using JWT authentication with claims mapping disabled (in this case, the user identifier is in the standard `sub` claim).

Please consider extending the default claims list to support `sub` (and optionally, more `ClaimTypes` like `Upn`).

**Comment by anurse** [comment]
Would you suggest this be configurable? It sounds like something we should throw on one of our options types. `UserIdClaimType` or something

**Comment by PinpointTownes** [comment]
> Would you suggest this be configurable?

That's certainly an option :+1: 
Maybe a list, instead of just a single claim name?

**Comment by anurse** [comment]
Ordered and we take the first one that has a value?

**Comment by davidfowl** [comment]
I actually think we kinda messed up with this interface last time around. User was originally meant for as a user controlled connection id surrogate but the default impl tried to use the current user. Maybe we need a “session” concept.

**Comment by anurse** [comment]
The JWT authentication already seems to load the `sub` claim in as `ClaimTypes.NameIdentifier` in the `ClaimsIdentity`, is this not working in some scenario?

**Comment by PinpointTownes** [comment]
> The JWT authentication already seems to load the sub claim in as ClaimTypes.NameIdentifier in the ClaimsIdentity, is this not working in some scenario?

> Yet, this (kinda legacy) claim is not always available, **specially when using JWT authentication with claims mapping disabled** (in this case, the user identifier is in the standard sub claim).

These days, disabling this mapping feature - specific to the JWT handler - is a very common practice (the IdSrv folks disable it in all their templates/demos).

There are also handlers - like the aspnet-contrib validation handler - that have full claims fidelity and don't use claims mapping. In this case, you can't use the `ClaimTypes.NameIdentifier` claim 'cause it's simply not there.

**Comment by bradygaster** [comment]
At the moment we believe IUserIDProvider already gives enough flexibility here.
