### ISSUE TITLE
Question : How to minimize DDos attack

### ISSUE THREAD

**Issue by AwsomeCode** [aspnet/SignalR#181]
I have created mobile app. Which is kind of chat application. Which talks to Asp.net Signalr backend server.
Now I am worried about DDos attack. Currently we are using ServerSentEvents as Transport protocol.
I want to know how to minimize the DDos attack in case of configuring in Asp.net Middleware? Or any hardware level firewall configuration? Or any other place where we should do some thing regarding DDos.  
What would be the difference if using Web socket instated of ServerSentEvents?
Any information on this would help. 
Thanks.

**Comment by moozzyk** [comment]
This question is too broad to give a comprehensive answer or there might not even be a good answer. It is also not a particular SignalR issue/bug. I would recommend researching DDos prevention strategies online and/or asking a question on forums like [stackoverflow](https://stackoverflow.com).

**Comment by davidfowl** [comment]
PS: You can't prevent a DDos if somebody wants you down. http://www.welivesecurity.com/2016/10/24/10-things-know-october-21-iot-ddos-attacks/

**Comment by Brain2000** [comment]
Actually, he's right.  We have over 10,000 clients and I'm calculating numbers right now as we could be in for self inflicted DDoS attack if I don't get my retries and disconnects just right.
