### ISSUE TITLE
SignalR Server Ready Event

### ISSUE THREAD

**Issue by samcov** [aspnet/SignalR#1813]
I notice that every call to the server creates a new instance of the hub.

What I'm looking for is something similar to a page ready event, i.e. one where the Clients and Context are initialized when a call is made. I've looked, but can't find anything like that except for a hub method, and I don't want to write something for each method if I don't have to.

Does this event exist?

**Comment by samcov** [comment]
Yeah, I know there is no concept of a page, it was just an analogy, likely a bad one. OnConnectedAsync is fired only once as far as I can determine, however, if I add a constructor, it is hit every time a request come in to the server.

Unfortunately, nothing is initialized at that point.

**Comment by davidfowl** [comment]
So why doesn't OnConnectedAsync work for you?

**Comment by samcov** [comment]
Because it fires only once, even though the hub is created every time any hub method is called. I wanted something that would fire any time a hub method is called, so that I can do something before the method exits.

The only other way is for me to place a call to a function to preprocess my task in every hub method, which is what I'll do if this event doesn't exist.

I'm doing some authentication of the user(a token with additional info), which is why I want this.

**Comment by davidfowl** [comment]
Oh I see that wasn't clear to me earlier, seems like you wanted a "page ready which would only happen once, not per hub invocation". Anyways we don't have anything fo cross cutting concerns yet but we do have something for auth. Why not write an authorization policy?

**Comment by samcov** [comment]
You're right, I just saw a thread on that, and it fits what I want exactly. Thanks for talking me down off the ledge, lol.

I'm closing this one.
