### ISSUE TITLE
Unable to install SignalR nuget package

### ISSUE THREAD

**Issue by chrisahardie** [aspnet/SignalR#1823]
I am attempting to run the following:

>Install-Package Microsoft.AspNetCore.SignalR -Version 1.0.0-preview3-32096 -Source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json

This error is thrown:

```
Install-Package : NU1102: Unable to find package System.Threading.Channels with version (>= 4.5.0-preview2-26326-04)
  - Found 13 version(s) in MyGet [ Nearest version: 4.5.0-preview2-26308-02 ]
  - Found 1 version(s) in nuget.org [ Nearest version: 4.5.0-preview1-26216-02 ]
```

Is there another Nuget feed with the required version of `System.Threading.Channels`? Thanks!

**Comment by davidfowl** [comment]
Yes, you need to add the dotnet-core feed (https://github.com/aspnet/SignalR/blob/5ce672dfe66584303d374d4a76077ea8cb73f785/build/sources.props#L8)
