### ISSUE TITLE
DI and System.ObjectDisposedException: 'Cannot access a disposed object.'

### ISSUE THREAD

**Issue by amccool** [aspnet/SignalR#1829]
* Versions of Server-Side NuGet Packages:
  microsoft.aspnetcore.signalr\1.0.0-preview1-final
* Versions of Client-Side NuGet/NPM Packages:
 "@aspnet/signalr": "^1.0.0-preview1-update1"
JavaScript client via TypeScript:
* The Server you are using
 Kestrel
* The Operating System on the Server
 Windows
* The Operating System on the Client
 Windows
* The Browser on the client, if using the JavaScript client
 Chrome

I have a dependency I inject into a Hub.   The dependency has a method in it which I supply with Action<T> lambda methods.

When the dependency calls my lambda Action<T> methods, it does jump into my hub code, However I always get

`System.ObjectDisposedException: Cannot access a disposed object. Object name: 'CallActivityHub'.`

`at Microsoft.AspNetCore.SignalR.Hub.CheckDisposed()    
at Microsoft.AspNetCore.SignalR.Hub.get_Context()    
at REWebApp.SignalR.Hubs.CallActivityHub.<ConnectToStream>b__5_2(PCConsoleSnapshot snapshot) in c:\xxx\SignalR\Hubs\CallActivityHub.cs:line 49    
at REWebApp.Startup.<>c.<<ConfigureServices>b__4_3>d.MoveNext() in c:\xxx\Startup.cs:line 81`

I have used, AddSingleton, AddScoped, Add Transient for the dependency, and all do the same thing.   I have also Moq'd the dependency, and it also does the same thing.

What is disposing of the Hub?
or do I need to be looking at this:   https://github.com/aspnet/SignalR/issues/1699#issuecomment-376956884

also -- help with this TypeScript setup, VS doesnt like LogLevel.  Do I need another import?
    this.hubConnection = new HubConnection("/CallActivity", { logger: LogLevel.Trace } );

**Comment by davidfowl** [comment]
The hub is disposed after the invocation.

**Comment by amccool** [comment]
is this the correct way to change the client side logging?

`import { HubConnection } from "@aspnet/signalr";`
`import { LogLevel } from "@aspnet/signalr";`
`this.hubConnection = new HubConnection("/CallActivity", { logger: LogLevel.Trace } );`

**Comment by anurse** [comment]
@amccool When using `import` syntax, yes, that's correct.

**Comment by amccool** [comment]
Things are working after creating a simple service class and injecting the IHubContext<CallActivityHub> into it, and firing its _context.Client.All.SendAsync.  @spudcud 's comment really saved my day.  Also points to ricardoperes 's blog post re:timers in https://weblogs.asp.net/ricardoperes/signalr-in-asp-net-core 

I'm going to close this issue.

However - I must say I never saw any Documentation surrounding the issue I had.   I hope this is forthcoming and not an oversight.

**Comment by davidfowl** [comment]
@amccool SignalR hasn't been released yet. The documentation will exist once it does
