### ISSUE TITLE
JavaScript HubConnection constructor should resolve URLs relative to the page

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1835]
Example: If you are on `http://localhost/foo/bar/baz`

* `new HubConnection('boz')` (Page-relative) should resolve to `http://localhost/foo/bar/boz`
* `new HubConnection('/boz')` (Absolute) should resolve to `http://localhost/boz`

**Comment by mikaelm12** [comment]
Fixed in e51852d0fc91c10b8eac641d137d10c9348589ec
