### ISSUE TITLE
TCP Socket Transport?

### ISSUE THREAD

**Issue by AwsomeCode** [aspnet/SignalR#184]
Currently Xamarin does not support WebSocket. And there is no timeline for it also. But Xamarin support TCP Socket. 
Is it OK to have TCP Socket support on .Net Client as well?

**Comment by moozzyk** [comment]
I think I saw ClientWebSocket available in a Xamarin Mac app the other day. It also is [documented](https://developer.xamarin.com/api/type/System.Net.WebSockets.ClientWebSocket/) on Xamarin API website. 
It's to early to comment on TCP support at this point. We have not finished implementing serverSentEvents and webSockets transports on the client and the server does not currently support TCP transport either.
