### ISSUE TITLE
Cannot send signalr message to specific clients using connection indexes

### ISSUE THREAD

**Issue by redplane** [aspnet/SignalR#1853]
Hi everyone,

Currently I'm using Signalr (ASP.Net Core 2.1) to develop my application.
In my application, I have one API that will send notification to specific clients in my system (for example: send notification to administrators when a product is registered)

I've run this code and worked fine:

`await myHubContext.Clients.All.SendAsync("myClientMethod", new {a: 1, b: 2});`

But if I change my code to :
`await myHubContext.Clients.Clients(aListOfConnectionIds).SendAsync("myClientMethod", new {a: 1, b: 2});
`
(`aListOfConnectionIds `is a list of connection id I saved to database)

My clients cannot receive notification.

Is it a bug of Signalr Core 2.1 ?

**Comment by anurse** [comment]
How are you tracking the connection IDs? Are the clients all still connected with the same ID (the connection ID changes when a client reconnects).

Using connection IDs for this purpose is not recommended, you should generally use Groups to achieve this. You can add the connections you want to receive notifications to a group using `Groups.AddAsync` in the `OnConnectedAsync` method of your Hub, then simply use `myHubContext.Groups("GroupName").SendAsync` to send messages to all the connections in the group.

**Comment by redplane** [comment]
My hub name is `NotificationHub`. I just want to use that hub to broadcast notifications to users (admin and user also).  

When I reload my browser, I see the connection id is still the same as the one I saved into database. But using that connection id to broadcast notification to is not possible. :(

**Comment by davidfowl** [comment]
> When I reload my browser, I see the connection id is still the same as the one I saved into database. But using that connection id to broadcast notification to is not possible. :(

When you refresh the connection id will change, it can't be the same.

**Comment by redplane** [comment]
I set a breakpoint in `OnConnectedAsync()` function, get the connection id there and save to my database.
Later I use the connection id in my database and send real-time notification to it, but my client cannot receive.

**Comment by davidfowl** [comment]
@redplane Which transport? Can you make a repro application and put it on github so we can investigate? Turning logging verbosity up might also help investigate issues.

**Comment by redplane** [comment]
Ok. Ill create a xemo project on angularjs and netcore asap :)

**Comment by redplane** [comment]
Oop. After doing my demo project.
I found out that in my main project. I used this query:

`var realTimeConnections = unitOfWork.SignalrConnections.Search();
 realTimeConnections = realTimeConnections.Where(x => x.UserId == user.Id);`

I didn't check whether new connection id is in my database or not, it should be:

`realTimeConnections = realTimeConnections.Where(x => x.Id.Equals(Context.ConnectionId));`

That's why new connection index wasn't added to database if user had 1 connection already.

This is not Signalr issue, I've changed my implementation and worked fine.

This can be closed :)

Thank you for your supports.

**Comment by anurse** [comment]
Please don't use Connection IDs like this. They are not designed to be stored in the database in this way, they should only ever be used on the server that created them. I strongly encourage you to consider using Groups instead. You can add a connection to a group using the `Groups.AddAsync` method on either `Hub` or `IHubContext<T>` and you can send to all the connections in a group using `Clients.Group("groupname").SendAsync` (also on `Hub` or `IHubContext<T>`)

**Comment by redplane** [comment]
@anurse , thank your for you tip.
I've followed the way you said :)
