### ISSUE TITLE
Does bearer token expiration still work?

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#1857]
The idea behind having accessTokenFactory was to call the factory before sending each HTTP request to obtain the current token. This way, if the user knows the current token is about to expire, they can get a new token from the server and return it from the factory to prevent from stopping the connection with an error due to an expired token. 
Today I found this:
https://github.com/aspnet/SignalR/blob/32b4d5cc6ce8a938d83d473a7e0030184b008e4a/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs#L427
which, if I read the code correctly, means that the access token value will be set once when starting the connection and SignalR will not ask the user for the token again.

**Comment by davidfowl** [comment]
Ah yes, I made this change. We'll take a look at this. We need to change this to be part of a message handler instead. 

Good catch! (we need a test 😉)
