### ISSUE TITLE
Connect to redis asynchronously

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1863]
Today we block a thread while trying to connect to redis, this would only be beneficial if we did it at startup and it caused startup to fail (or maybe that's a bad thing). In reality, we may end up blocking a thread pool thread sometime layer down the road which would lead to starvation. We should change this to be asynchronous.

See https://github.com/aspnet/SignalR/blob/61c3d0c4030033013d4ad155d0f284aba384070a/src/Microsoft.AspNetCore.SignalR.Redis/RedisOptions.cs#L21

**Comment by mikaelm12** [comment]
Done here: e2169ceda636797ebe76ba1a26abd0ae59a0802e
