### ISSUE TITLE
Flaky test: CorrectlyHandlesQueryStringWhenAppendingNegotiateToUrl

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1883]
@BrennanConroy 's change commit 307ed01051803607f4f58ca50509f7fc9aa39a1d here had a flaky test failure on appveyor https://ci.appveyor.com/project/aspnetci/signalr/build/1.0.3825.

It seems to have timed out trying to start the connection. There's no server in this picture. These are all mocks and that still timed out. 

https://github.com/aspnet/SignalR/blob/cb5ece8a24fbc3f53cc838996bd1d298c0049eb0/test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Negotiate.cs#L73

Either we have too low of a timeout because we have so many things running in parallel racing to be scheduled or something in the client took longer than 5 seconds.

**Comment by JamesNK** [comment]
I can repo it on my computer if I the code is executed 10000 times in parallel AND the timeout delay is lowered to 500ms.

```
[Theory]
[InlineData("http://fakeuri.org/", "http://fakeuri.org/negotiate")]
[InlineData("http://fakeuri.org/?q=1/0", "http://fakeuri.org/negotiate?q=1/0")]
[InlineData("http://fakeuri.org?q=1/0", "http://fakeuri.org/negotiate?q=1/0")]
[InlineData("http://fakeuri.org/endpoint", "http://fakeuri.org/endpoint/negotiate")]
[InlineData("http://fakeuri.org/endpoint/", "http://fakeuri.org/endpoint/negotiate")]
[InlineData("http://fakeuri.org/endpoint?q=1/0", "http://fakeuri.org/endpoint/negotiate?q=1/0")]
public async Task CorrectlyHandlesQueryStringWhenAppendingNegotiateToUrl(string requestedUrl, string expectedNegotiate)
{
    IList<Task> tasks = new List<Task>();
    for (int i = 0; i < 10000; i++)
    {
        var task = Task.Run(async () =>
        {
            var testHttpHandler = new TestHttpMessageHandler(autoNegotiate: false);

            var negotiateUrlTcs = new TaskCompletionSource<string>();
            testHttpHandler.OnLongPoll(cancellationToken => ResponseUtils.CreateResponse(HttpStatusCode.NoContent));
            testHttpHandler.OnNegotiate((request, cancellationToken) =>
            {
                negotiateUrlTcs.TrySetResult(request.RequestUri.ToString());
                return ResponseUtils.CreateResponse(HttpStatusCode.OK,
                    ResponseUtils.CreateNegotiationContent());
            });

            await WithConnectionAsync(
                CreateConnection(testHttpHandler, url: requestedUrl),
                async (connection) =>
                {
                    await connection.StartAsync(TransferFormat.Text).OrTimeout(500);
                });

            Assert.Equal(expectedNegotiate, await negotiateUrlTcs.Task.OrTimeout(500));
        });
        tasks.Add(task);
    }

    await Task.WhenAll(tasks);
}
```

Two options:
1. App veyor was incredibly slow at this point in time and just happened to exceed the 5 second time out.
2. This test is working with URLs. Is there any chance something in .NET is doing some kind of DNS lookup with them?

**Comment by anurse** [comment]
> This test is working with URLs. Is there any chance something in .NET is doing some kind of DNS lookup with them?

Extremely doubtful.

**Comment by JamesNK** [comment]
> An issue that this has uncovered is that the HttpConnection still thinks it has successfully started up even though the long poll transport has failed to make any successful web requests.

I guess this is by design? Thing that concerns me is that there is no way to tell if the transport has died.

Also concerning that unknown errors are being thrown inside the app without the test noticing. What about using an in-memory logger and asserting at the end of tests that no error level logs have been written?

**Comment by davidfowl** [comment]
> Also concerning that unknown errors are being thrown inside the app without the test noticing. What about using an in-memory logger and asserting at the end of tests that no error level logs have been written?

That sounds good. Kestrel does a similar thing.

**Comment by anurse** [comment]
> I guess this is by design?

Kinda. We had some logic at one point to fail `StartAsync` when the poll fails, but it turns out to be harder than we anticipated since by default we don't respond from the poll until there is data to send.

Still, the `Closed` event should be firing when the transport fails...

**Comment by JamesNK** [comment]
I think this is a one off oddity because the server was especially slow. Exceptions were also being thrown in the background (fixed) which might have contributed to the time it took to run.

Can reopen if the test fails again in the future.
