### ISSUE TITLE
Unify HttpConnectionOptions and HttpOptions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1896]
I'm not sure why we have 2 very similar types on the client side by regardless, we need to unify them. We might also want to consider adding Client to the name HttpClientOptions since it'll conflict with the server if you use them in the same app.

/cc @JamesNK do you know why we have both?

**Comment by JamesNK** [comment]
I'll remove HttpConnectionOptions, rename HttpOptions to HttpClientOptions, and have the factory use it.
