### ISSUE TITLE
Mobile native clients

### ISSUE THREAD

**Issue by llooz** [aspnet/SignalR#190]
We are considering to switch our backends to .NET Core when SignalR Core is ready.
Currently we are using the old SignalR with mobile apps (Android and iOS) using a third party obj-c library and the official java client but with an our implementation of the web socket protocol based on **okhttp-ws**

There are any plans for Java and Obj-C/Swift clients for the new SignalR?

**Comment by moozzyk** [comment]
https://twitter.com/davidfowl/status/826594554119741440
