### ISSUE TITLE
Send AccessToken via C# Client for [Authorize] protected hub

### ISSUE THREAD

**Issue by brettclutch** [aspnet/SignalR#1903]
This is I believe a duplicate of: https://github.com/aspnet/SignalR/issues/1039 but all of the information appears is no longer relevant in 1.0.0-alpha2-final release and almost feels like removed on purpose. I wanted to post to make sure this requirement is not missed as its very important to me. 

The question:
* How to send an AccessToken along with the c# client HubConnectionBuilder / HubConnection to authenticate a connection for accessing a [Authorize] protected hub. 

I so far can't figure it out. Thx.

**Comment by robrohan** [comment]
I am in the process of looking at using singalR core as well - my assumption is that since most systems I have worked on send a JWT via the Authorisation header, and a websocket connection starts out as an HTTP connection before it upgrades, sending the token "As normal" should "just work".

Keep in mind I have no idea about SignalR yet, but I'd like to follow this issue and thought maybe that might help you on your way :)

**Comment by anurse** [comment]
@brettclutch Support for JWT tokens was added in Preview 1. You need to upgrade both your client and server to the latest preview release. Please note that the alpha 2 version is no longer supported (since Preview 1 was released).

I'm closing this issue for now as the issue should be resolved in the latest released version. Feel free to comment further if you have issues, we can always re-open the issue if there's still a bug there.

**Comment by anurse** [comment]
> my assumption is that since most systems I have worked on send a JWT via the Authorisation header, and a websocket connection starts out as an HTTP connection before it upgrades, sending the token "As normal" should "just work".

@robrohan This is generally correct and how we operate. However, browser APIs do not allow headers to be added to WebSocket requests, so we also support encoding the token in the query string, though you need to modify the server to accept those tokens. See below (from the JwtSample in this repo) for an example:

https://github.com/aspnet/SignalR/blob/962ea25637a70c99ccbda2b47e3d682dd29da9ec/samples/JwtSample/Startup.cs#L35-L63

**Comment by brettclutch** [comment]
Dang, thought I was on latest. Sorry for the noise.

**Comment by robrohan** [comment]
@anurse Cool, thanks for the info. 

In the past (this was in node mind you), I've taken the JWT Authorisation header out of the initial websocket request (which is just a standard HTTP request) saved the JWT against whatever websocket ID type object was there.  Then we'd send back the upgrade response and start the web socket. 

This was for a much simpler system than signalr, and that was quite a while ago so my memory might be off, but something like that would save you from the HTTP query string size limitation - I've seen JWTs get nasty big.

Anyway, thanks for the info and  I'll dig into the JwtSample a bit more.

**Comment by anurse** [comment]
No worries, glad that resolved your issue!

**Comment by LGinC** [comment]
I use ClientWebSocket connect my server but can not trigger OnMessageReceived event.

**Comment by brettclutch** [comment]
Here is the code I used to get a JWT token working. No clue what your doing there with AddSubProtocol. 

https://gist.github.com/brettclutch/06bfa3fde17b15a2908a94090c2992f3

**Comment by anurse** [comment]
> I use ClientWebSocket connect my server but can not trigger OnMessageReceived event.
> ClientWebSocket code

Can you provide a repro project? Do you have `app.UseAuthentication()` above `app.UseSignalR()` in your `Startup.Configure` method?

**Comment by LGinC** [comment]
@brettclutch But I use ClientWebsocket instead of HubConnection.

and it will not generate a http request.

**Comment by LGinC** [comment]
@anurse AbpZero.
![image](https://user-images.githubusercontent.com/15363011/40755914-240460a2-64b3-11e8-86b5-9a7fea679be0.png)

![image](https://user-images.githubusercontent.com/15363011/40755897-07ba01ae-64b3-11e8-920c-db20b0ef1d41.png)

Jwt and querystring Configure
![image](https://user-images.githubusercontent.com/15363011/40755995-89aa50d8-64b3-11e8-95dc-ad5524d1aadd.png)

![image](https://user-images.githubusercontent.com/15363011/40756040-d2427eba-64b3-11e8-9bf4-7b83ce444043.png)

**Comment by brettclutch** [comment]
Sorry I'm no help with ClientWebSocket, never even used that. What might help though is to turn on the signalR debugging, that helped me in the past. 

I don't know if there is an equivalent for ClientWebSocket but try somehow to set this to see if it will help, here is setting ConsoleLogger for HubConnectionBuilder. 

 Connection = new HubConnectionBuilder()
                        .WithTransport(Microsoft.AspNetCore.Sockets.TransportType.WebSockets)
                        .WithUrl(ConnectPoint)
                        .WithAccessToken(() => { return token; })
                        .WithConsoleLogger(Microsoft.Extensions.Logging.LogLevel.Debug)
                        .Build();

Goodluck!

**Comment by LGinC** [comment]
@brettclutch actually，I want to know how signalr client change the http request to weboscket.
queryString is in http request, but ClientWebSocket don't need http request...

**Comment by davidfowl** [comment]
@LGinC the code is open source 😄 https://github.com/aspnet/SignalR/blob/30a59f6df79014942620a65fb7d65f32b6b1246b/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/WebSocketsTransport.cs#L46-L49

**Comment by davidfowl** [comment]
You don't need to do any of that. Raw websocket connections work without negotiation. There's no conversion from query string to header.
