### ISSUE TITLE
Cannot send message to specific user from server

### ISSUE THREAD

**Issue by SkeletonSkelettron** [aspnet/SignalR#1909]
Hi
after updating from alpha2-final to preview1-final version, I cannot send message to specific user by username

`myHub.Clients.User("c@c.com").SendAsync("onMessage",new { text : "some text" })`

"c@c.com" here is  AspNetCore.Identity user.

myHub.Clients.User("c@c.com") does return data, but after sending data client method is not invoked.
When I send by  myHub.Clients.All.SendAsync every user receives data, but targeted messages are not received.

I am using mongoDB as identity storage provider, if it helps. userId in this case is not GUID but something like 5a2acbf1e29aae12c0a94df7.

on client side I have angular App and I use "@aspnet/signalr": "1.0.0-preview1-update1" version.

Thanks

**Comment by SkeletonSkelettron** [comment]
Yes David 
I upgraded nuget package to preview1-final version and npm package to preview1-update1. 
after it, it stopped working.

**Comment by SkeletonSkelettron** [comment]
just to clarify, 
I had versions  `Nuget: 1.0.0-alpha2-final`, `npm: 1.0.0-alpha2-final`
now : `Nuget: 1.0.0-preview1-final`, `npm: 1.0.0-preview1-update1`

**Comment by davidfowl** [comment]
The only obvious thing would be if the user name SignalR expects, isn't the user name you're using to address the connection. By default, we use https://github.com/aspnet/SignalR/blob/27d18578d0bafcbc1da839197f9ecd29cf72097d/src/Microsoft.AspNetCore.SignalR.Core/DefaultUserIdProvider.cs#L12 the name claim. You can see if you have one of those and if not then it won't work. You can also replace this service and provider your own IUserIdProvider that resolves the correct user name for a connection.

**Comment by SkeletonSkelettron** [comment]
Thanks David
Now I used UserID instead of UserName and it worked

**Comment by SkeletonSkelettron** [comment]
And also, thanks for rapid responses, you saved my time <3
