### ISSUE TITLE
Consider using msgpack for Redis protocol

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1914]
Right now the protocol is completely internal and uses the BinaryWriter APIs in .NET (which don't interoperate with anything else). If we want to open this up for allowing others to publish to clients via redis we should use something more standard (and also document and version the protocol).

**Comment by anurse** [comment]
I figured out why this is problematic. `SerializedHubMessage`'s serialization logic lives in the core in order to allow it to be serialized by any lifetime manager. I think I can reasonably move it out.
