### ISSUE TITLE
Long polling connection terminates 30 minutes after logging out

### ISSUE THREAD

**Issue by imamy4** [aspnet/SignalR#1917]
I have problem with application that using SignalR (versions info below). 

I open the application in chrome, open DevTools and log out.
An hour later I log in. I see that Long Polling connections in the regular mode were completed and recreated, but after about half an hour connection is terminated and SignalR does not warn about it and the OnClose event was not fired.

Network snapshot below.

Problem in Chrome only. If i use Firefox, it close connection too, but after logging in connection is restored.

* Versions of Server-Side NuGet Packages: 1.0.0-preview1-final
* Versions of Client-Side NuGet/NPM Packages: 1.0.0-preview1-update1
* Are you using the C# client or the JavaScript client: JavaScript Client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): IIS 
* The Operating System on the Server (Windows/Linux/macOS): Windows Server 2012R2
* The Operating System on the Client (Windows/Linux/macOS): Windows 7 
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome 65.0.3325.181

[network snapshot.zip](https://github.com/aspnet/SignalR/files/1890154/network.snapshot.zip)

**Comment by JamesNK** [comment]
Hi

Unfortunately logs of the HTTP requests alone are not enough to diagnose what happened. Could you enable logging of the client and server and attach the logs? Instructions here:

> * If possible, please collect logs from the client:
>    * Set the `logger` option on your `HubConnection` to `LogLevel.Trace` and find the logs in the Console tab of your Browser Dev Tools
>    * Example: `new signalR.HubConnection(url, { logger: signalR.LogLevel.Trace })`
> * If possible, please collect logs from the server:
>    * When using Kestrel/HttpSysServer, these are available on the Console by default
>    * When using IIS/IIS Express, these are available in Visual Studio in the "ASP.NET Core Web Server" section of the Output Window
>    * See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x for more information

Also preview2 has just been released. Update the SignalR packages to preview2 in VS and retry this scenario. Your issue may have been resolved.

Let me know how you get on.

**Comment by imamy4** [comment]
I attached server, client and network logs.

P.S. I cannot fully configure preview2 in my app and collect logs, but this error occurs.
P.S.S. Error when invoking 'OnDisconnectedAsync' (which you can see in server logs) does not affect connection terminating problem. It's new problem, I made it recently, before original problem detection

[traces.zip](https://github.com/aspnet/SignalR/files/1915237/traces.zip)

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

Make sure to try the 1.0.0 rtm build! It may have the fix for your issue.
