### ISSUE TITLE
Microsoft.AspNetCore.Sockets dynamic EndPoint mapping based on HttpContext

### ISSUE THREAD

**Issue by fuocor** [aspnet/SignalR#194]
Currently SocketRouteBuilder supports static mapping to an EndPoint without considering headers or QueryString. It would be nice (because I need It) to support dynamic routing...

I have an implementation where I add a method MapEndpointResolver in SocketRouteBuilder that does the following

```C#
      public void MapEndpointResolver<TResolver>(string path) where TResolver : EndPointResolver
        {
            _routes.AddPrefixRoute(path, new RouteHandler(c => _dispatcher.ReolveAsync<TResolver>(path, c)));
        }
```

EndPointResolver simply takes the path and HttpContext and returns an appropriate EndPoint

```C#
    public abstract class EndPointResolver
    {
        public abstract EndPoint Resolve(string path, HttpContext context);
    }
```
To wire it all up HttpConnectionDispatcher needs a ResolveAsync async Task ReolveAsync<TResolver>(string path, HttpContext context) method that does the flowing

```C#
var endpointResolver = (EndPointResolver)context.RequestServices.GetRequiredService<TResolver>();
            var endpoint = endpointResolver.Resolve(path, context);

            if (context.Request.Path.StartsWithSegments(path + "/negotiate"))
            {
                await ProcessNegotiate(context);
            }
            else if (context.Request.Path.StartsWithSegments(path + "/send"))
            {
                await ProcessSend(context);
            }
            else
            {
                await ExecuteEndpointAsync(path, context, endpoint);
            }
````

These relatively minor modification provides the ability to contextualize messaging without having to interpret every messages flowing through an endpoint. (Think connection groups and rooms)..

rich

**Comment by davidfowl** [comment]
Can you expand on how you are using it?

**Comment by fuocor** [comment]
I have messaging application that processes IoT device telemetry information on one end, and the UI on the other. Each device has a virtual hub that manages the logic for that particular device. The UI can monitor several devices simultaneously and each user can choose which device to monitor. By assigning a socket endpoint to the virtual hub messages can flow without any outside dispatcher. From a load balancing perspective the virtual hubs are clustered onto server nodes and can be moved at will. The IOT device is completely decoupled from the virtual node through the use of queues. The UI uses a front-end discovery service to identify the cluster for a device and then connect... From a node management perspective the socket mappings come and go based on resource availability and managing that should be pushed into the middleware between the socket protocol and connection handling 

I Hope tis helps
rich

**Comment by davidfowl** [comment]
I see, so you just have some logic that selects a hub based on query string arguments in this case? Or do you select an endpoint dynamically based on some other criteria? This would allow you to change mappings at runtime but you still can't add an endpoint at runtime. Also the clients don't care about this right? In your architecture, do endpoints map to virtual hubs? What does that look like? Do you have your own idea of connection id ? (is that basically what the virtual hub is?)

**Comment by fuocor** [comment]
I see, so you just have some logic that selects a hub based on query string arguments in this case? YES

Or do you select an endpoint dynamically based on some other criteria? NO - The behavior of the EndPoint is dynamically managed, not the EndPoint itself.

In your architecture, do endpoints map to virtual hubs? YES Each IoT device has a unique virtual hub associated with it. So the connection Id is essentially the IoT device Id
