### ISSUE TITLE
Enhancements to negotiate response url

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1947]
We want to add 2 things to the negotiate response:

- A url that the client connects to for the actual SignalR end point. This is to support scenarios where the main application wants to direct the real time traffic to another server but doesn't want to hard code urls in the client. Negotiate would gain the ability to specify a URL that the client should connect to.

- An access token or access token end point. This would automagically get plugged into the client's access token provider when making a request to the above url.

**Comment by muratg** [comment]
Triage: We'll need to discuss this.

**Comment by davidfowl** [comment]
Today if websockets is chosen, we skip negotiate, we need to make this an explicit flag instead of using the transport type.

**Comment by anurse** [comment]
If this flag (SkipNegotiate) is set, we should throw if the Transports flags enum (on the client) is anything other than exactly WebSockets.

**Comment by davidfowl** [comment]
The response will look like:

```JSON
{
    "url": "https://myothersignalrapp.foo.net/chat",
    "accessToken": "accessToken"
}
```

**Comment by muratg** [comment]
@davidfowl how about `accessTokenEndpoint`?

**Comment by davidfowl** [comment]
Not required, we're going to be just using the access token specified here as is. If it expires, the connection will die and we'll get a new one from the same negotiate endpoint.
