### ISSUE TITLE
Consider providing an xunit test suite for HubLifetimeManager implementations

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1948]
DI and EF has used this technique to great success. Basically for any provider model, you provide a suite of tests that need to pass in order for to validate your behavior assumptions. We provide the harness, the user plugs in their HubLifetimeManager and we validate our expectations about their implementation.

**Comment by anurse** [comment]
Sounds great for 2.2.0-mq ;)

**Comment by davidfowl** [comment]
Moving to the backlog

**Comment by davidfowl** [comment]
We should do this in 2.2.0-mq: See

https://github.com/DarkCow/SignalR.Orleans/tree/ef5b9f3f8c2f9eb1f475a8285977b5fd5b8d9d9d/test/SignalR.Orleans.Tests

**Comment by anurse** [comment]
A lot of this would just be converting our existing tests for `DefaultHubLifetimeManager` and `RedisHubLifetimeManager` into an abstract base class and shipping it in an assembly.

**Comment by anurse** [comment]
@mikaelm12 you were mentioning you were ready for some new MQ work, want to take a look at this?

**Comment by davidfowl** [comment]
Yes, it'll also help the service.

**Comment by mikaelm12** [comment]
648705f6484ffc0ceefab7c571747af895a389d4

**Comment by anurse** [comment]
Reopening this as the packaging needs to be fixed. See @natemcmaster 's comments in the #2353

**Comment by mikaelm12** [comment]
Fixed: dd64e4d9a5b84c6e3a5ee850ab20336daf4faa14
