### ISSUE TITLE
Failing test on linux

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#195]
Travis keeps failing:

https://travis-ci.org/aspnet/SignalR/jobs/200553251

We should look into it to make sure it's not a bug.

/cc @moozzyk

**Comment by moozzyk** [comment]
I saw it once but since we decided to replace ReceiveAsync with the event I did not investigate -this code is gone in https://github.com/aspnet/SignalR/pull/191.

**Comment by moozzyk** [comment]
This code is no more. Closing.
