### ISSUE TITLE
preview2 cannot be minified by create-react-app

### ISSUE THREAD

**Issue by bloodcarter** [aspnet/SignalR#1951]
When trying to run `npm run build` using `create-react-app`? I got this error:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/@aspnet/signalr/dist/esm/Loggers.js:4

Read more here: http://bit.ly/2tRViJ9
```

With preview1 everything works fine.

**Comment by anurse** [comment]
As per https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify it looks like we have to transpile everything for ES5, even the "modern" ECMAScript Modules version. That's super unfortunate. We'll look at it for RC
