### ISSUE TITLE
Cannot run @aspnet/signalr on IE11

### ISSUE THREAD

**Issue by dangtathanh** [aspnet/SignalR#1954]
Hi all,

I download and run sample code of SignalR from this [document](https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio) but get below error when run the app on IE11:

SCRIPT1002: Syntax error
chat.js (3,61)

App works well on Chrome, FF or Edge. Could you please check it?

**Comment by davidfowl** [comment]
@HaoK can you take a look?

**Comment by anurse** [comment]
@dangtathanh That sample does not support IE 11, because it uses ECMAScript 6 features. I'll file a bug to make sure that is clear. You can use a tool like https://babeljs.io/repl/ to convert the scripts to ECMAScript 5.

Note that SignalR itself **is** compatible with IE 11, just not that sample code.

As an example, the `chat.js` script should be the following if you want compatibility with IE 11:

```javascript
"use strict";

var connection = new signalR.HubConnection("/chathub", { logger: signalR.LogLevel.Information });

connection.on("ReceiveMessage", function (user, message) {
    var encodedMsg = user + " says " + message;
    var li = document.createElement("li");
    li.textContent = encodedMsg;
    document.getElementById("messagesList").appendChild(li);
});

document.getElementById("sendButton").addEventListener("click", function (event) {
    var user = document.getElementById("userInput").value;
    var message = document.getElementById("messageInput").value;
    connection.invoke("SendMessage", user, message).catch(function (err) {
        return console.error;
    });
    event.preventDefault();
});

connection.start().catch(function (err) {
    return console.error;
});
```

**Comment by HaoK** [comment]
So sounds like this behavior is expected, any more to here @anurse or can we close this out?

**Comment by anurse** [comment]
Yep, closing this. We can track changes to the sample at aspnet/Docs#5945

@dangtathanh if there's still an issue after using the converted code above, feel free to post a comment and we can explore further.

**Comment by JanEggers** [comment]
using preview 2 and i get an error in ie: vendor.bundle.js (15,1) which is "../../../../@aspnet/signalr/dist/esm/Errors.js" so do i need to transpile or not?

**Comment by anurse** [comment]
If you are using a module bundler, there is an issue in Preview 2 that prevents it from working with IE: https://github.com/aspnet/SignalR/issues/1951

It has been fixed in RC1 by transpiling every build to ES5, for IE compatibility.

**Comment by riregi** [comment]
Hello, When i call  connection.invoke("SendMessage", user, message) recive error message: 
Information: WebSocket connected to wss://localhost:44356/chatHub?id=grOL3s0ibtuH7aZfnh3KUQ
**WebSocket is not in the OPEN state**

**Comment by BrennanConroy** [comment]
@riregi Please open a new issue and describe your environment as well as collect client/server logs as described in our [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)
