### ISSUE TITLE
Error: Failed to start the connection: TypeError: o is not iterable

### ISSUE THREAD

**Issue by BissacM** [aspnet/SignalR#1955]
**Chrome Browser:**
![image](https://user-images.githubusercontent.com/15155243/38613097-728665d4-3d91-11e8-9089-3cb9e4b34ebc.png)
**_This the angular 5 service that connecting to SignalR:_**
![image](https://user-images.githubusercontent.com/15155243/38613642-3d072522-3d93-11e8-91fa-8345f436b051.png)
**This is the Startup Class:** 
![image](https://user-images.githubusercontent.com/15155243/38613375-6b7cb6b6-3d92-11e8-80da-a058149a9dec.png)
**This is the HUB**
![image](https://user-images.githubusercontent.com/15155243/38613327-41ac68a4-3d92-11e8-9b80-48b86a2c092b.png)

**Comment by davidfowl** [comment]
Looks like old non core SignalR with the new SignalR client. That won’t work. You need to use SignalR Core in the server side.

**Comment by BissacM** [comment]
Thanks!
If I'm developing Dot Net Framework 4.6.1, Can use SignlR Core ?

**Comment by davidfowl** [comment]
Yes, see https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server for the bigger ASP.NET Core picture. SignalR is part of ASP.NET Core which also runs on .NET Framework.
