### ISSUE TITLE
Win2008 Browser Functional Test flakiness

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#1958]
https://gist.github.com/BrennanConroy/c6cb60c673d2d99813b9ad6fcc4ebdd7
Tests failing 100% of the time it looks like

**Comment by anurse** [comment]
Merged https://github.com/aspnet/SignalR/pull/1959 to provide a longer timeout and more logging. Reopen if the failures reoccur. cc @ryanbrandenburg
