### ISSUE TITLE
Expose an API for getting the connection based on connection id

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#196]
This allows sending to a connection via another server side entry point that isn't the EndPoint. It also  allows users to solve the the stickiness problem for non websockets transports by implementing another url that can push messages through a a message queue/bus to another machine to a specific connection.

/cc @DamianEdwards

**Comment by muratg** [comment]
One option is to put ConnectionManager inside the DI which would enable this.

**Comment by davidfowl** [comment]
Specifically this is for metadata, not for actually invoking methods.

**Comment by anurse** [comment]
We're closing this. If people want it, they can open issues :)
