### ISSUE TITLE
ChatSample no worky

### ISSUE THREAD

**Issue by HaoK** [aspnet/SignalR#1960]
The sample is not really functional right now, it runs but things like registering a user doesn't work.

If fixing everything is too much work, maybe we should just replace it with a simple Chat Hub like the one described here:  https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-getting-started-with-signalr/

I can submit a PR slimming it down to simple chat app like that if we want, since I just followed that walkthrough

**Comment by anurse** [comment]
Hrm, I was able to register and login just fine. The JavaScript code is a bit out of date, but I'm fixing that in #2050 . Can you clarify what errors you were seeing?

**Comment by HaoK** [comment]
Hrm, so when I tried, I was able to register, but login didn't work, it would just redirect back to the login page, and it would display all of the cookies under the external login page.  I can try again tomorrow to see if its still doing what I was seeing

**Comment by HaoK** [comment]
I could have been doing the flow wrong, I didn't actually try just directly going to the chat url after registering

**Comment by anurse** [comment]
It's possible that there is an issue with logging in. All I did was register and then was immediately logged in.
