### ISSUE TITLE
Allow multiple HttpTransportTypes to be specified in TS client

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1961]
https://github.com/aspnet/SignalR/pull/1925#discussion_r180876421

**Comment by mikaelm12** [comment]
Edited the title to reflect that you're talking about the TS client

**Comment by JamesNK** [comment]
TypeScript supports flags - https://basarat.gitbooks.io/typescript/docs/enums.html#enums-as-flags

**Comment by mikaelm12** [comment]
Going to wait on https://github.com/aspnet/SignalR/pull/1925 to avoid making @anurse  rage out 😄

**Comment by anurse** [comment]
https://github.com/aspnet/SignalR/commit/c009e15b0c811191dd481a04cfdd63fb9166be5f
