### ISSUE TITLE
Run build and tests on Spanish image

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1967]
Consider running SignalR build and tests on a Spanish image to catch culture related bugs.

Roslyn already does this - https://github.com/aspnet/SignalR/issues/1905#issuecomment-380648062

// @jaredpar @pranavkm

**Comment by anurse** [comment]
Per Jared, we should be able to use the Windows.10.Amd64.ClientRS3.ES.Open image. We may need to add our necessary prerequisites to that image (or create a new one) though. We need browsers and NodeJS (to test JavaScript in different cultures).

**Comment by pranavkm** [comment]
Filed https://github.com/dotnet/core-eng/issues/3407 to add a Spanish language OS with the same pre-reqs as the other Windows image. I'm guessing the one Roslyn uses doesn't have node \ npm installed.

**Comment by anurse** [comment]
@pranavkm it looks like you're trying to get this turned on, yes?

**Comment by anurse** [comment]
Blocked by #2448
