### ISSUE TITLE
Dependency issue with nuget package

### ISSUE THREAD

**Issue by abdelkader27** [aspnet/SignalR#197]
I'm trying to use Microsoft.AspNetCore.WebSockets on .net core library using NETStandard.Library 1.6.1
But I'm getting a dependency warning because Microsoft.AspNetCore.WebSockets is using NETStandard.Library 1.6.2-beta-24913-01.

The same issue with Microsoft.AspNetCore.Signalr.Client.

**Comment by davidfowl** [comment]
It's actually pretty difficult (or nearly impossible) to use these nuget packages at the moment. We're currently in the middle of updating the ASP.NET repositories to use the latest bits from myget.

**Comment by davidfowl** [comment]
@abdelkader27 This is fixed now. You should be able to consume SignalR in your projects!
