### ISSUE TITLE
How to debug authorization?

### ISSUE THREAD

**Issue by Externaluse** [aspnet/SignalR#1973]
* Versions of Server-Side NuGet Packages:
Microsoft.AspNetCore.{SignalR, SignalR.Client, SignalR.Core} at v.1.0.0.0-preview2-final
* Versions of Client-Side NuGet/NPM Packages:
v.1.0.0.0-preview2-final
* Are you using the C# client or the JavaScript client: Javascript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
IIS Express on localhost
* The Operating System on the Server (Windows/Linux/macOS):
Windows 7 x64
* The Operating System on the Client (Windows/Linux/macOS):
Windows 7 x64
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
Chrome

I can't seem to make the Authorize attribute work properly, and Context.User.Identities[0].IsAuthenticated is false; obviously Name etc are null then.

Creating new connection
Loggers.ts:28 Information: Normalizing '/signalr' to 'https://localhost:44329/signalr'.
Loggers.ts:31 Trace: Starting HubConnection.
Loggers.ts:31 Trace: Starting connection with transfer format 'Text'.
Loggers.ts:31 Trace: Sending negotiation request: https://localhost:44329/signalr/negotiate
Loggers.ts:31 Trace: Skipping transport 'WebSockets' because it was disabled by the client.
^^ Websockets aren't working on IIS Express localhost; I think this has been reported before but may be nice to point out in the samples...
Loggers.ts:31 Trace: Selecting transport 'ServerSentEvents'
Loggers.ts:31 Trace: (SSE transport) Connecting
Loggers.ts:28 Information: SSE connected to https://localhost:44329/signalr?id=Og16GRXWgPlT_uBYFDnL6w
Loggers.ts:31 Trace: Sending handshake request.
Loggers.ts:31 Trace: (SSE transport) sending data. String data of length 32.
Loggers.ts:31 Trace: (SSE transport) request complete. Response status: 200.
Loggers.ts:28 Information: Using HubProtocol 'json'.
My code: Registering registerHeartBeatTockTimer
Loggers.ts:31 Trace: (SSE transport) data received. String data of length 3.
signalr.js:1416 Trace: Server handshake complete.
My code: Standard attempt HeartBeatTock
Loggers.ts:31 Trace: (SSE transport) sending data. String data of length 70.
Loggers.ts:31 Trace: (SSE transport) request complete. Response status: 200.
Loggers.ts:31 Trace: (SSE transport) data received. String data of length 44.
My Code: HeartbeatTock worked.

Negotiate headers, Request:
Carries Cookie .AspNetCore.Antiforgery... and Identity.Application-=...
Origin: https://localhost:44329
Response:
Access-Control-Allow-Credentials: true << also tried without allow credentials
Access-Control-Allow-Origin: https://localhost:44329
Content-Length: 252
Content-Type: application/json
Date: Thu, 12 Apr 2018 08:53:18 GMT
Server: Kestrel

After negotiation however, there don't seem to be origin headers; might that be an issue? The cookies are still part of the request though.

Request URL: https://localhost:44329/signalr?id=HZd1KZ33CVPUYlsCTooeTA
Request Method: GET
Status Code: 200 OK
Remote Address: [::1]:44329
Referrer Policy: no-referrer-when-downgrade

Response (shortened)
Cache-Control: no-cache
Content-Encoding: identity
Content-Type: text/event-stream
Date: Thu, 12 Apr 2018 08:57:07 GMT
Server: Kestrel
Transfer-Encoding: chunked
X-Powered-By: ASP.NET
X-SourceFiles: =?UTF-8?B?RDpcUHJvamVrdGVcRG9ja1xEb2NrXHNpZ25hbHI=?=

The last version I had running was 1.0.0-alpha2-final in which this worked, however this was on default Core Identity whereas I'm using a Cloudscribe template for this one.

In the new one I've also tried CookiePolicyOptions with HttpOnly = HttpOnlyPolicy.None instead of Always; and Secure = CookieSecurePolicy.None instead of SameAsRequest without a difference in result.

I would be grateful if someone could point me in the correct direction to look further.

**Comment by davidfowl** [comment]
> I can't seem to make the Authorize attribute work properly, and Context.User.Identities[0].IsAuthenticated is false; obviously Name etc are null then.

What's the expectation. You added the attribute and what did you expect to happen as a result?

**Comment by Externaluse** [comment]
Oh sorry:
I'm on a particular website as an authenticated user. That website connects to the SignalR Hub. I was previously able to override OnConnectedAsync and create a group with the user's GUID. 
When the hub class is decorated with Authorize, I would receive a 401:
Request URL: https://localhost:44329/signalr
Request Method: OPTIONS
Status Code: 401 Unauthorized

To debug, I had removed the attribute to see that the Identity object in the hubs context isn't populated with the logged in user's Identity.

**Comment by davidfowl** [comment]
So you have an authorized user and the Hub is acting as if you aren't authorized? Is that correct? 

Are you running SignalR cross domain or on the same website?

**Comment by Externaluse** [comment]
That is correct. It is running on the same website. Say I'm browsing https://localhost:44329/Schedule which connects to SignalR on https://localhost:44329/signalr. 
Comparing the two samples, the working one on Default Core Identity, and the non-working one on Cloudscribe Core Identity, the requests look absolutely identical in every respect; Headers, Responses etc.
Now I'm stuck trying to figure out where the difference is...

**Comment by davidfowl** [comment]
I don't know what "Cloudscribe Core Identity" is or how it plugs into ASP.NET Core's authentication system. Is it a 3rd party oauth2 provider like google?

**Comment by Externaluse** [comment]
Cloudscribe is a kickstart template for .Net Core Projects. It essentially leaves most of the default middleware intact, but adds a few things. Having established that it is not, as I first suspected, a version issue, I suppose this is out of the scope of your help.
This probably has to do with how Context is mapped.
The working one (default Core identity) looks like this:
{Microsoft.AspNetCore.SignalR.DefaultHubCallerContext}
...
User: {System.Security.Claims.ClaimsPrincipal}
    UserIdentifier: "8850dae3-60ca-4901-abc2-8f69d3f21aa6"
Cloudscribe's in comparison:
 User: {System.Security.Claims.ClaimsPrincipal}
    UserIdentifier: null

Could you point me towards the location in the source on where User is populated and from what? I could then continue investigation.
Thank you very much for your time, your help is greatly appreciated.

**Comment by davidfowl** [comment]
UserIdentifier is only used for sending to that particular user, it isn't used to reject the request. 

https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Core/DefaultUserIdProvider.cs

**Comment by davidfowl** [comment]
This is the code that will reject based on the user itself (using the ASP.NET authentication system):

https://github.com/aspnet/SignalR/blob/d4773e831ccf1ca9c157e312028086ed6a12ec75/src/Microsoft.AspNetCore.Http.Connections/HttpConnectionDispatcher.cs#L95

https://github.com/aspnet/SignalR/blob/d4773e831ccf1ca9c157e312028086ed6a12ec75/src/Microsoft.AspNetCore.Http.Connections/Internal/AuthorizeHelper.cs

**Comment by Externaluse** [comment]
Thanks again, I'll have a look at those and will report back findings.

**Comment by Externaluse** [comment]
It was stupid, I didn't pay enough attention to the order of the middleware. SignalR needed to be wired after the (amended) authentication middleware of Cloudscribe.
Working fine now. Please accept my apologies for wasting your time!
