### ISSUE TITLE
Test runs aborted

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#1977]
SignalR [sometimes](http://aspnetci/viewLog.html?buildId=445725&tab=buildResultsDiv&buildTypeId=Lite_SignalR) has its test runs abort with the following errors:

```
The active test run was aborted. Reason: After parsing a value an unexpected character was encountered: V. Path 'Payload.NewTestResults[1].Messages[0].Text', line 1, position 16386.
[08:34:53]	Test Run Aborted.
```

Future instances of this failure will appear [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:TestAbortUnexpectedCharacter,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by davidfowl** [comment]
Seems like another bug in the test runner.

**Comment by davidfowl** [comment]
I filed this https://github.com/Microsoft/vstest/issues/1542

**Comment by anurse** [comment]
Closing this. It's an issue in VSTest (possibly due to something we're doing wrong, but we need the VSTest fix before we can know)

**Comment by ryanbrandenburg** [comment]
Why not just leave it open as a tracking issue for Microsoft/vstest#1542? That way it doesn't fall off our radar and get deprioritized.

**Comment by ryanbrandenburg** [comment]
This now seems to be consistently failing the SignalR project build.

**Comment by JamesNK** [comment]
We know what the vstest team has posted in the linked issue

**Comment by BrennanConroy** [comment]
This should be fixed now
https://github.com/aspnet/BuildTools/commit/4bd5cd656011fc2e278763918709c4259867752b
