### ISSUE TITLE
HubConnection.StopAsync never uses timeout

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1997]
`StopAsyncCore` never uses `timeout`.

https://github.com/aspnet/SignalR/blob/198013bfa3368bd2b3e17956722157098d03626c/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs#L962-L994

**Comment by anurse** [comment]
API review also concluded it should have a `CancellationToken` anyway.
