### ISSUE TITLE
signalr is not throwing any events or callbacks when internet is not available

### ISSUE THREAD

**Issue by sarvabowmen** [aspnet/SignalR#2001]
I am trying to detect the network failure event from signalR client javascript library, but signalr is not throwing any events or callbacks when internet is not available, is there are any callback which i can listen if there is any network failure?

i am using **webSockets** transport and is there any possible way to detect whether the connection is still active?

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages:
 "@aspnet/signalr-client": "1.0.0-alpha2-final",
* Are you using the C# client or the JavaScript client:
javascript client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
Node
* The Operating System on the Server (Windows/Linux/macOS):
Windows
* The Operating System on the Client (Windows/Linux/macOS):
Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
Chrome

**Comment by davidfowl** [comment]
Can you be more specific. What kind of failure? Are you on a normal network (no VPN etc, behind proxies). How did you "disconnect" exactly?

**Comment by sarvabowmen** [comment]
I just want to handle the scenario of network disconnected (i.e. Internet disconnected abruptly) and also i want to check whether the signalr is still connected to server, 

Sorry I hosted my signalr server application in local IIS, I am connecting it with javascript client.

**Comment by davidfowl** [comment]
> I just want to handle the scenario of network disconnected (i.e. Internet disconnected abruptly) and also i want to check whether the signalr is still connected to server,

Yes, it's extremely complicated unfortunately. How did you disconnect? Did you unplug the cable? Did your internet just drop? Did the server die? What happened exactly?

**Comment by sarvabowmen** [comment]
I want to handle all the scenarios you mentioned above..

**Comment by davidfowl** [comment]
> I want to handle all the scenarios you mentioned above.. Both the server die and the internet just drop, And also i want to check whether the connection is still alive..

We do too, if you could tell us which scenario you are specifically complaining about, that would be great. We can then setup tests with this in our infrastructure.

**Comment by sarvabowmen** [comment]
Currently i have requirement of notifying the users when i failure has in my application, I want to notify the users on these scenarios mentioned below
1. Server hosted the signalr Service Died. How can i identify it from the client end or how can i intimate that to a client?
2. internet just dropped (i.e. no internet), Is there any callback which gets called once the internet has dropped off
3. And also need to show a provision in UI to check whether the connection is still active, For that i want to check whether the hubConnection is still active or not?

**Comment by davidfowl** [comment]
@sarvabowmen you filed an issue with the title "signalr is not throwing any events or callbacks when internet is not available", can you just specify what exactly you did and what did and didnt' work in each *specific* case.

In all cases, the closed event should fire, if it's not firing then let us know which situation it didn't fire in so we can investigate further.

**Comment by sarvabowmen** [comment]
I opened by client javascript application in my browser, i just changed the chrome to offline mode (using the developer tools), it doesn't call the disconnected method.
For checking the connection alive, i couldn't find any method or property for it in the HubConnection class.

**Comment by davidfowl** [comment]
> i just changed the chrome to offline mode (using the developer tools), it doesn't call the disconnected method.

Thanks! That's what I was looking for.

**Comment by JamesNK** [comment]
Hi

I have tested using SignalR with web sockets and Chrome in offline mode and I ran into the same issue. The problem is not in SignalR but Chrome: web sockets are not effected by offline mode. A blog post with someone running into a similar problem here - https://medium.com/@ngzhian/chrome-offline-network-emulation-and-websocket-6ecc914e2308

I tested HubConnection.onclose being fired by killing the IIS server while the web page was still open and it worked successfully.

![image](https://user-images.githubusercontent.com/303201/38842921-c7fcfd80-4240-11e8-8232-3ac88f00d373.png)

**Comment by sarvabowmen** [comment]
Thanks James, 
It is calling the onclose callback in the client, if the server stops or iis stops, but if i switch off my system wifi, it is not calling the onclose callback.

**Comment by JamesNK** [comment]
Hi

How long are you waiting? A socket will not close immediately when the internet connection goes down.

**Comment by JamesNK** [comment]
The connection closed for me and raised the onclose event when I introduced a network issue.

![image](https://user-images.githubusercontent.com/303201/38904873-012a5146-4301-11e8-930b-5ebf07771ebf.png)
