### ISSUE TITLE
How to use Microsoft.AspNetCore.SignalR.Redis for scaleout of SignalR?

### ISSUE THREAD

**Issue by NorDroN** [aspnet/SignalR#2002]
Hi!

Where can I see sample how to use Microsoft.AspNetCore.SignalR.Redis for scaleout of SignalR?
I've created docker container with redis
```
docker run -d -p 6379:6379 redis
```
after that I added in my app
```
services.AddSignalR().AddRedis(options =>
{
    options.Options.EndPoints.Add(Configuration["Data:Redis:ConnectionString"]);
});
```
When I start my app I see
```
info: Microsoft.AspNetCore.SignalR.Redis.RedisHubLifetimeManager[2]
      Connected to Redis.
```
but I can't see content into redis. My redis storage is empty. And of course when I create many instances of my app they doesn't work.

I'm using Microsoft.AspNetCore.SignalR and Microsoft.AspNetCore.SignalR.Redis 1.0.0-preview2-final

**Comment by davidfowl** [comment]
> but I can't see content into redis. My redis storage is empty. And of course when I create many instances of my app they doesn't work.

We don't use redis storage, we use redis pubsub. Is the application getting messages? If yes then it's working.

**Comment by NorDroN** [comment]
Thanks, @davidfowl 
Unfortunately it doesn't work. I'd like to create project with this structure
<img width="560" alt="schema" src="https://user-images.githubusercontent.com/5458276/38798997-e688d9c0-416b-11e8-964e-146f9bb0262b.png">
I'm using SignalR for /chat

I've tried to use WebSocket and I've tried to use LongPooling also, but it doesn't work in this cases.

I can understand why it doesn't work when I use LongPooling (one request /chat/negotiate go to backend-1 and server return ID, second request go to backend-2 and second request know nothing about ID), but I thought that regis helps me.

PS: And of course I know about
```
public static ISignalRBuilder AddRedis(this ISignalRBuilder builder, string redisConnectionString);
``` 
I wrote full construction because I need to override some another parameters.

**Comment by davidfowl** [comment]
Try turning the logs onto the trace level. There's nothing more to it than specifying a redis connection string. If you have more info after turning on the logging them we can look deeper.

For non-websocket requests, you need to turn sticky sessions on so that requests go to the same server. Specifying WebSockets directly works around this.

**Comment by davidfowl** [comment]
I'd also recommend using the redis client and the MONITOR command to see all commands being sent to redis.

**Comment by NorDroN** [comment]
I've created example application https://github.com/NorDroN/SignalRChat

**Comment by NorDroN** [comment]
Thanks, @davidfowl 

I'm working with kubernates for deployment my app.

When I'm using one instance of backend
![image](https://user-images.githubusercontent.com/5458276/39060424-fbd96b58-44c9-11e8-934d-e55efa666a20.png)
it works perfectly (WebSocket and LongPooling)


but when I scale my backend
![image](https://user-images.githubusercontent.com/5458276/39060440-04241e2a-44ca-11e8-8bf0-ca37a8276798.png)
I get error
<img width="951" alt="screenshot_12" src="https://user-images.githubusercontent.com/5458276/39060845-20dd865e-44cb-11e8-9e40-d8720871e4de.png">

**Comment by davidfowl** [comment]
Oh that's simple, you need to use sticky sessions when you scale out.

**Comment by NorDroN** [comment]
It works perfectly! But I thought that redis helps me to scaleout without sticky session. I thought that redis save session id, which I got from /negotiate.

**Comment by anurse** [comment]
Redis **and** sticky sessions are required for any multi-server deployment. Redis helps ensure that Server A can send to clients on Server B, but sticky sessions are required because each individual client must remain connected to the same server. This is **different** from ASP.NET SignalR, which allows clients to roam between server (which was a major source of complexity and bugs)

**Comment by zdenan** [comment]
So if I use skipNegotiation and websocket protocol on client builder then I dont need sticky sessions. Is it correct? Thx.

**Comment by anurse** [comment]
Correct. If you have `skipNegotiation` set to `true`, you don't need sticky sessions. That setting is only allowed with WebSockets.

Also, you don't need sticky sessions on your application when using the newly-announced [Azure SignalR Service](https://azure.microsoft.com/en-us/services/signalr-service/)

**Comment by davidfowl** [comment]
Also `skipNegotiation` does not work with the azure service (negotiation is how the client get the right URL).

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
