### ISSUE TITLE
Connecting to SignalR with more than 5 clients in asp.net Core 2.0 makes this error "failed: Error during WebSocket handshake: Unexpected response code: 503"

### ISSUE THREAD

**Issue by mhmdtaherian** [aspnet/SignalR#2007]
I expected that SignalR supports lots of concurrent client connection to hub, I had no problem on local computer in development mode. But when I uploaded my project on Azure, I just can have about 5 concurrent clients and I will get the error which I put in subject.

* javascript client
* Server Azure Web App
* Server Windows
* Client Windows
* Browser (IE/Chrome/Edge/Firefox) 
* SignalR server side version: v1.0.0-alpha2-final
* SignalR client side version: v1.0.0-alpha2-final

**Comment by mikaelm12** [comment]
My first suggestion would be to upgrade to the preview 2 bits as we've done a lot of work to SignalR since the alpha2 release.

**Comment by anurse** [comment]
After you've updated, if the issue reoccurs, can you also gather the client and server logs as described here: https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md

**Comment by mhmdtaherian** [comment]
I've tried to update signalR to latest latest version, I updated by nuget package manager. Now I want to get signalR-client JS file but it gets only version 1.0.0-preview2-final and it doesn't work. how can I get signalR-client js file?

**Comment by anurse** [comment]
> Now I want to get signalR-client JS file but it gets only version 1.0.0-preview2-final and it doesn't work.

This is the latest version of the SignalR client. What error are you seeing? Can you provide as much of the details requested in https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md as possible?

**Comment by davidfowl** [comment]
@mhmdtaherian are you using the free tier of azure app service?

**Comment by anurse** [comment]
Good catch @davidfowl . @mhmdtaherian please note that the free tier of Azure App Service is limited to 5 concurrent WebSockets: https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#app-service-limits

**Comment by mhmdtaherian** [comment]
yes, I use free tier of Azure App Service. That is the point. Thank you guys. 
But another thing, I upgraded my SignalR to latest version and now using 1.0.0-preview2-final as client JS. I get this error "_Failed to load resource: the server responded with a status of 405 (Method Not Allowed)_" I took a look and I found this "[SignalR version compatability (StatusCode: 405 'Method Not Allowed')](https://stackoverflow.com/questions/49152486/signalr-version-compatability-statuscode-405-method-not-allowed)"

**Comment by anurse** [comment]
Have you updated **both** the server and the client to `1.0.0-preview2-final`?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
