### ISSUE TITLE
WinForms net461/471 with SignalR.Client throws on Connect

### ISSUE THREAD

**Issue by HaoK** [aspnet/SignalR#2008]
Using 2.1-preview2 fina lbits:
 
Setup SignalR server with /hub/chat via: https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-getting-started-with-signalr/
This is working via chrome at https://localhost:44343/hubs/chat

Setup WinForms client:
```
•	New WinForms project (net461) + Add preview2 SignalR.Client
•	  <package id="Microsoft.AspNetCore.Connections.Abstractions" version="2.1.0-preview2-final" targetFramework="net461" />
•	  <package id="Microsoft.AspNetCore.Http.Connections.Client" version="1.0.0-preview2-final" targetFramework="net461" />
•	  <package id="Microsoft.AspNetCore.Http.Connections.Common" version="1.0.0-preview2-final" targetFramework="net461" />
•	  <package id="Microsoft.AspNetCore.Http.Features" version="2.1.0-preview2-final" targetFramework="net461" />
•	  <package id="Microsoft.AspNetCore.SignalR.Client" version="1.0.0-preview2-final" targetFramework="net461" />
•	  <package id="Microsoft.AspNetCore.SignalR.Client.Core" version="1.0.0-preview2-final" targetFramework="net461" />
•	  <package id="Microsoft.AspNetCore.SignalR.Common" version="1.0.0-preview2-final" targetFramework="net461" />
•	  <package id="Microsoft.Extensions.Configuration" version="2.1.0-preview2-final" targetFramework="net461" />
```

Trying to connect via:

``` 
        const string ServerURI = "https://localhost:44343/hubs/chat";
            Console.WriteLine("Connecting to {0}", ServerURI);
 
            Connection = new HubConnectionBuilder().WithUrl(ServerURI).Build();
            Connection.Closed += Connection_Closed;
            Connection.On<string, string>("AddMessage", (name, message) =>
                this.Invoke((Action)(() =>
                    RichTextBoxConsole.AppendText(String.Format("{0}: {1}" + Environment.NewLine, name, message))
                ))
            );
            try
            {
                await Connection.StartAsync(); => Blows up with: 
 ```

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.SpanHelpers.IndexOf(Byte& searchSpace, Byte value, Int32 length)
   at System.MemoryExtensions.IndexOf[T](ReadOnlySpan`1 span, T value)
   at System.Buffers.BuffersExtensions.PositionOf[T](ReadOnlySequence`1& source, T value)
   at Microsoft.AspNetCore.SignalR.Internal.Formatters.TextMessageParser.TryParseMessage(ReadOnlySequence`1& buffer, ReadOnlySequence`1& payload)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HandshakeProtocol.TryParseResponseMessage(ReadOnlySequence`1& buffer, HandshakeResponseMessage& responseMessage)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<HandshakeAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by anurse** [comment]
I believe this is cause by the fact that System.Memory depends on the following for `net45` (see https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory). We are building for `net461` in the sample, but the `net45` dependencies are chosen over the `netstandard2.0` ones because NuGet finds an exact target framework name match (**unless this logic has changed since I last knew how this worked ;)**).

* System.Buffers (>= 4.4.0)
* System.Runtime.CompilerServices.Unsafe (>= 4.5.0-preview3-26416-06)

However, at runtime, it only provides a `netstandard2.0` binary, so it loads that binary, which references `System.Numerics.Vectors`, and thus blows up. System.Memory's references:

```
// netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
// System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```

**Comment by anurse** [comment]
https://github.com/dotnet/corefx/issues/29149

**Comment by anurse** [comment]
There is a workaround for the corefx bug, I'm going to try that and make sure there's nothing else blocking this scenario.

**Comment by anurse** [comment]
Confirmed that when dotnet/corefx#29149 is fixed, we should be good to go:

![image](https://user-images.githubusercontent.com/7574/39012670-ec1961f6-43c9-11e8-8984-6a2bf4ab5dce.png)

**Comment by anurse** [comment]
The corefx issue is closed. Will close this when we verify on a fixed build.

**Comment by anurse** [comment]
Confirmed fixed in the latest corefx build

**Comment by Masterside** [comment]
@anurse Sorry that I comment on a closed issue, but I still got this issue with .NET Core 2.1 rc1, but I got it with System.Buffers instead of System.Numerics.Vectors:

`"Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified."`

**Comment by davidfowl** [comment]
@Masterside make us a repro project. You can also see a working sample here https://github.com/aspnet/SignalR-samples/tree/master/WindowsFormsSample

**Comment by Masterside** [comment]
@davidfowl Created the requested repro here: https://github.com/Masterside/SignalRDependencyBugSample

**Comment by ericstj** [comment]
This is a case of a classic desktop project using a project-reference to a class library that has package dependencies.

The dependencies of the class library are not copied by default.

If you set the following in the net4x project it will fix it.
```
  <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
```
If you have any PackageReference in the net4x project this is not necessary.  If you are using packages.config you need to reference every package that your referenced project references.

@rrelyea do you know why NuGet doesn't give transitive behavior when a project has no packages.config nor packagereference?  Is it just being overly conservative?

**Comment by Masterside** [comment]
@ericstj It works now. Thanks you.
