### ISSUE TITLE
HubContext.Clients.AllExcept parameter unclear

### ISSUE THREAD

**Issue by Externaluse** [aspnet/SignalR#2009]
* Versions of Server-Side NuGet Packages:
1.0.0-preview2-final
* Versions of Client-Side NuGet/NPM Packages:
1.0.0-preview2-final

The parameters for IHubClients<T> could be slightly clearer.

In T Client or T Clients it is string or List<string> connectionId(s) - pretty clear.

In AllExcept and GroupExcept the parameter is "IReadOnlyList<string> excludedIds"; it could be slightly clearer if it was excludedUserIds or excludedConnectionIds.

I suppose we're dealing with connection Ids for those? 

And how difficult would it be to add AllExceptUser(string userId)? This is the last hurdle I'll still have to resolve from the client (save own identity and suppress messages to oneself) when injecting the HubContext into e.g. a controller.

Example:
Only to me (works):  
await _signalRHub.Clients.User(User.GetUserIdAsGuid().ToString()).SendAsync("Notify", ...)
All but me (doesn't work): await _signalRHub.Clients.UserExcept(new List<string>() { User.GetUserIdAsGuid().ToString() }).SendAsync("Notify", ...

I hope this makes sense and isn't too stupid a question. Thanks for the amazing work, quite a step from alpha2-final I had played around with!

**Comment by muratg** [comment]
Tracked in #1974

**Comment by anurse** [comment]
Just to expand on this, we reviewed this in our triage meeting and you're absolutely right @Externaluse , the parameter names could be clearer. We're doing a big bunch of API clean-ups, so we've added this to that list and will take care of it there.

I don't think we're going to be be able to do `AllExceptUser` in this release, but it's a good idea to consider in the future.
