### ISSUE TITLE
Use fixed length length for binary message format

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#2012]
Today we use varint and it can be 1-5 bytes, which means we have to buffer. If we use a fixed length, we can write directly to the pipe and come back and write the length back at the beginning. We'll use a fixed 4-byte length (max 2GB, which is the current max anyway)

cc @davidfowl @anurse

**Comment by davidfowl** [comment]
Preliminary results based on https://github.com/aspnet/SignalR/tree/davidfowl/remove-var-int.

## Before

```
              Method |          Input | HubProtocol |        Mean |     Error |      StdDev |      Median |        Op/s |  Gen 0 | Allocated |
------------------- |--------------- |------------ |------------:|----------:|------------:|------------:|------------:|-------:|----------:|
 WriteSingleMessage |   FewArguments |     MsgPack |    757.9 ns |  29.98 ns |    84.06 ns |    731.7 ns | 1,319,478.2 |      - |      48 B |
 WriteSingleMessage | LargeArguments |     MsgPack | 12,536.5 ns | 714.00 ns | 2,048.60 ns | 12,077.4 ns |    79,767.1 | 0.6561 |   20528 B |
 WriteSingleMessage |  ManyArguments |     MsgPack |  1,359.4 ns |  51.48 ns |   149.36 ns |  1,315.4 ns |   735,618.6 | 0.0019 |      72 B |
 WriteSingleMessage |    NoArguments |     MsgPack |    405.2 ns |  15.54 ns |    44.58 ns |    397.5 ns | 2,467,802.4 | 0.0010 |      40 B |
```

## After

```
              Method |          Input | HubProtocol |        Mean |     Error |      StdDev |      Median |        Op/s |  Gen 0 | Allocated |
------------------- |--------------- |------------ |------------:|----------:|------------:|------------:|------------:|-------:|----------:|
 WriteSingleMessage |   FewArguments |     MsgPack |    703.9 ns |  24.22 ns |    68.70 ns |    683.9 ns | 1,420,724.1 | 0.0010 |      56 B |
 WriteSingleMessage | LargeArguments |     MsgPack | 11,575.3 ns | 495.72 ns | 1,422.33 ns | 11,492.7 ns |    86,391.2 | 0.6561 |   20528 B |
 WriteSingleMessage |  ManyArguments |     MsgPack |  1,346.7 ns |  50.19 ns |   144.02 ns |  1,316.8 ns |   742,567.5 | 0.0019 |      72 B |
 WriteSingleMessage |    NoArguments |     MsgPack |    392.6 ns |  18.92 ns |    54.29 ns |    380.5 ns | 2,547,128.8 | 0.0010 |      40 B |
```

I'm not sure if the benefits justify the protocol change. There is a bunch of code simplification on the protocol implementation though (I didn't finish the javascript side yet).

**Comment by anurse** [comment]
That doesn't really seem to justify it to me either. Would the benefit be greater though if the protocol was writing directly to the buffer? Right now we're using the `Stream` API which means `MessagePack-CSharp` has to allocate buffers to provide to the Write method.

I guess if it looks simple enough we could just do it and hope we can realize some benefit later. It certainly doesn't seem to make performance **worse**.

**Comment by JanEggers** [comment]
> We can still "optimize" writing varint in almost the same way by just always pre-allocating 5 bytes and 0-padding the length if we end up needing fewer than 5 bytes.

is this a good way to handle this kind of problem? I have the same issue of first writing to temp buffer in my mqtt protocol because mqtt also has varint length header.

**Comment by davidfowl** [comment]
> is this a good way to handle this kind of problem? I have the same issue of first writing to temp buffer in my mqtt protocol because mqtt also has varint length header.

It's non trivial to avoid the buffering with a varint. The only thing I can think of would be a serializer that  had a "what-if" mode. That mode would do a fake serialize that counted the bytes but did nothing else.   So you'd run in that mode, get the length, the run again to get the actual data.

**Comment by davidfowl** [comment]
@anurse @muratg I'm going to close this based on the fact that the savings are so minimal (even the allocation savings are dubious).

**Comment by muratg** [comment]
@davidfowl sounds good. And the "what-if" mode would probably be too crazy anyway.
