### ISSUE TITLE
Migration from 1.0.0-alpha2 to Microsoft.AspNetCore.SignalR - 1.0.0-preview2-final broken the execution of the application in IE10

### ISSUE THREAD

**Issue by prasadmamidi7** [aspnet/SignalR#2028]
After migration of application from 1.0.0-alpha2 to Microsoft.AspNetCore.SignalR - 1.0.0-preview2-final broken the execution of the application in IE11 and IE10. And Error in the IE dev tools points to AbortController . As per Mozilla below class is not comparability for IE.   

class AbortController {
    constructor() {
        this.isAborted = false;
    }
    abort() {
        if (!this.isAborted) {
            this.isAborted = true;
            if (this.onabort) {
                this.onabort();
            }
        }
    }
    get signal() {
        return this;
    }
    get aborted() {
        return this.isAborted;
    }
}

SCRIPT1002: Syntax error
File: vendor.bundle.js, Line: 12, Column: 1

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages:"Microsoft.AspNetCore.SignalR - 1.0.0-preview2-final
* Versions of Client-Side NuGet/NPM Packages:aspnet/signalr": "^1.0.0-preview2-final
* Are you using the C# client or the JavaScript client: JavaScript Client : Angular:5.0.0
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Kestrel and IIS
* The Operating System on the Server (Windows/Linux/macOS):Windows
* The Operating System on the Client (Windows/Linux/macOS):Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):IE10
* If possible, please collect Network Traces and attach them (please do not post them inline, use a service like [Gist](https://gist.github.com) to upload them and link them in the issue)
   * For either client you can use a tool such as [Fiddler](https://www.telerik.com/fiddler) for this
   * Many browsers allow you to capture Network Traces from their Dev Tools. See sample instructions for Chrome: https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting
* If possible, please collect logs from the client:
   * Set the `logger` option on your `HubConnection` to `LogLevel.Trace` and find the logs in the Console tab of your Browser Dev Tools
   * Example: `new signalR.HubConnection(url, { logger: signalR.LogLevel.Trace })`
* If possible, please collect logs from the server:
   * When using Kestrel/HttpSysServer, these are available on the Console by default
   * When using IIS/IIS Express, these are available in Visual Studio in the "ASP.NET Core Web Server" section of the Output Window
   * See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x for more information

When in doubt, feel free to file the issue, we're happy to help answer questions. We also suggest using the `asp.net-core-signalr` tag on StackOverflow to ask questions.

**Comment by anurse** [comment]
How are you referencing the script in your application? IE does not support ES 2015 features, so you have to ensure you are using the script in `dist/browser` in order to get IE compatibility. Or, if you are using a bundler like WebPack, you need to ensure you transpile code to ES5 for IE.

**Comment by anurse** [comment]
Note this has been improved in the next release as we are ensuring that the version used by bundlers will be transpiled to ES5.

**Comment by prasadmamidi7** [comment]
Thank you for the prompt support. I am able resolve the problem by referring the java script as below
import { HubConnection, TransportType, HttpConnection, LogLevel, ILogger } from '@aspnet/signalr/dist/browser/signalr.js';

if this is the correct way of doing in the preview 2 release. you can close the issue.

**Comment by anurse** [comment]
Yep, that'll work for preview 2. In the next release you'll be able to switch back to using `@aspnet/signalr` directly.

Closing this now as the issue has been resolved.
