### ISSUE TITLE
HubConnection Off function requires exact same function reference

### ISSUE THREAD

**Issue by mattiLeBlanc** [aspnet/SignalR#2039]
Version: @aspnet/signalr@1.0.0-preview1-update1

In my Angular 5 app I have to do this to make sure the OFF function removes the callback from the queue:
```

ngOnInit() {
    this.handleDecisionFn = this.handleDecision.bind( this );
    this.notificationService.on( 'creditDecision', this.handleDecisionFn );
}

handleDecision() {
  // do some logic here
}
someOtherFunction() {
  this.notificationService.off( 'creditDecision', this.handleDecisionFn );
}


```
Before I just passed `this.handleDecision.bind( this )` in as the callback of the `on()`, but then I noticed that the indexOf function used in the source code of the Off function can't match because the reference is probably different.

In the `signalr.js` function Off, should the line 
```
   var removeIdx = handlers.indexOf(method);
```
use a string comparison of the function instead of an object comparison?

**Comment by davidfowl** [comment]
> use a string comparison of the function instead of an object comparison?

Why? Why can't you give it the same reference? AFAIK thats how most of the other javascript eventing systems work.

**Comment by mattiLeBlanc** [comment]
Well that is what I am doing, but it seems weird to store the reference in
an extra variable and then pass that into the on and off function.
It felt like I was working around the issue but if you think that is the
proper way of doing so, then I will accept that.

**Comment by davidfowl** [comment]
Yes this is by design.
