### ISSUE TITLE
Available Transport Fallback in SignalR client ?

### ISSUE THREAD

**Issue by mattchidley** [aspnet/SignalR#2044]
* Versions of Server-Side NuGet Packages: 1.0.0-preview1-final
* Versions of Client-Side NuGet/NPM Packages: signalr.js (@aspnet/signalr)
* Are you using the C# client or the JavaScript client: JavaScript client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): IIS Express
* The Operating System on the Server (Windows/Linux/macOS): Windows 10
* The Operating System on the Client (Windows/Linux/macOS): Windows 10 and Windows 7
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): IE 9, 10, 11

Is the SignalR client supposed to intelligently "fallback" to an available transport that the browser can also use?

**Expected behaviour:**
- A client in IE 9 negotiates a connection.
- The server responds including an array of available transports it supports - Websockets and Long Polling
- The client detects that it's browser is not capable of using Websockets, so it sets the HttpConnection transport to Long Polling and uses the Long Polling Transport type for all communication with the server.

**Actual behaviour:**
- A client in IE 9 negotiates a connection.
- The server responds including an array of available transports it supports - Websockets and Long Polling
- The client chooses the first option in the list of available transports (see around line 1915 of the signalr.js client):

        if ((transport === null || transport === undefined) && availableTransports.length > 0) {
            transport = Transports.TransportType[availableTransports[0]];
        }

**Question**
Is it up to the developer to build in logic to determine which transport to use when creating a HubConnection? The documentation led me to believe that this logic was handled by the SignalR client.. but the behaviour leads me to believe otherwise.

**Comment by BrennanConroy** [comment]
This should be handled correctly in preview2
See https://github.com/aspnet/SignalR/issues/1317

**Comment by anurse** [comment]
Closing this as this issue should be resolved in the latest release. Please update and see if your issue is resolved. If not, please feel free to comment here and we can consider reopening the issue.
