### ISSUE TITLE
JSDoc documentation

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2047]
Developers would find it easier to use SignalR TS client if they had JSDoc documentation to refer to in intelli-sense and on docs.microsoft.com

**Comment by anurse** [comment]
As part of this, we should also talk with the aspnet/Docs team about getting on https://docs.microsoft.com/en-us/javascript/api/

**Comment by anurse** [comment]
https://github.com/aspnet/SignalR/commit/c89cf1a12b2d61d0607e186e4687943473eea461
