### ISSUE TITLE
Chrome + offline + XMLHttpRequest = 0 status response

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2051]
Repo:
1. Load page with signalr TS client in browser
2. In Chrome developer tools network tab, check Offline
3. Attempt to connect with long polling

`XMLHttpRequest` calls `onreadystatechange` with a value of 4 which then comes here - https://github.com/aspnet/SignalR/blob/e15d1ec255fb3bf13c8ffa23f88a9b7b061e123b/clients/ts/signalr/src/HttpClient.ts#L103-L112

And returns a successful promise. I researched a little and 0 shouldn't be treated as successful - https://stackoverflow.com/a/14507670/11829

(a 0 status also raises `onerror` here that then attempts to reject the promise but I guess that happens after it has already been resolved).

https://github.com/aspnet/SignalR/blob/e15d1ec255fb3bf13c8ffa23f88a9b7b061e123b/clients/ts/signalr/src/HttpClient.ts#L116-L119

**Comment by anurse** [comment]
Yeah, we should reject on a `0` status. @davidfowl, do you remember why you put this in as `resolve` instead of `reject`? It seems more appropriate to `reject`

**Comment by JamesNK** [comment]
Comment in the code:

                     // Some browsers report xhr.status == 0 when the 
                     // response has been cut off or there's been a TCP FIN. 
                     // Treat it like a 200 with no response.

**Comment by anurse** [comment]
Yeah, I see that. I'm just not sure it's appropriate to `resolve` in that case.

**Comment by davidfowl** [comment]
Hmm let’s change back to onload that might have worked better here. Originally I changed that code thinking we had an issue in JavaScript but turns out it was a sever side race

**Comment by anurse** [comment]
Fixed in https://github.com/aspnet/SignalR/commit/d9272032d0042229976a8bed4b497dcff38da720
