### ISSUE TITLE
Is there a way to await a callback in the javascript client?

### ISSUE THREAD

**Issue by samcov** [aspnet/SignalR#2053]
I'm trying to find a way to wait for a callback to return before executing additional code.

I thought I heard them mention that there was a way in the video "Introducing ASP.NET Core SignalR"

**Comment by davidfowl** [comment]
Can you explain which callback you mean?

**Comment by samcov** [comment]
Good question, most times when I make a call to the server, I expect to get a returned value. To make this happen, I send a callback function to get the data.

The server calls the client with the data, and that is what I'm calling a callback function, which is probably my implementation.

I guess what I'm looking for is a way to call the server and await in JS for the server to respond.

**Comment by davidfowl** [comment]
Are you asking how to use es6 or how to use typescript? The SignalR client library returns promises and if you're using the appropriate typescript compiler or version of javascript, you can use async await.

**Comment by samcov** [comment]
I can see how to do it after reading this issue [#1145](https://github.com/aspnet/SignalR/issues/1145) 

**Bottom Line:** This is correct. You also use this promise to get the result of non-void hub methods.

Thanks, closing this issue.
