### ISSUE TITLE
SignalR 1.0.0-preview2-final server and client mismatch CORS

### ISSUE THREAD

**Issue by BastienVerschaete** [aspnet/SignalR#2054]
I know there have been a few issues created in this repo concerning the same problem and I read every one of them but haven't come to a solution, stackoverflow wasn't of any help either so I'm trying here as a final effort until a stable version is released.

I keep running into the CORS issue integrating the example project on https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-getting-started-with-signalr/  in my application.

Versions of all packages used are listed below, I have checked that those are indeed the ones installed.
On my AspNetCore app I have these packages, I have also tried using Microsoft.AspNetCore.App package instead of listing them all out but it gives the same problem.

    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OAuth" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0-preview2-final" />
    <PackageReference Include="Sendgrid" Version="9.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="2.4.0" />

In my angular 5 application in my npm-shrinkwrap I have the following signalR package:

    "@aspnet/signalr": {  
      "version": "1.0.0-preview2-final",  
      "resolved": "https://registry.npmjs.org/@aspnet/signalr/-/signalr-1.0.0-preview2-final.tgz",  
      "integrity": "xxx"  
    },

I have double checked my node modules and this is the version that is installed. The code used to create the connection is the one linked above, but I keep getting the following errors thrown into my browser console when starting the connection:

    zone.js:2969 OPTIONS https://localhost:44304/api/notification/negotiate 405 ()
    dashboard:1 Failed to load https://localhost:44304/api/notification/negotiate: Response to preflight 
    request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the 
    requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had 
    HTTP status code 405.
    signalr.js:1410 Warning: Error from HTTP request. 0: 

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: **1.0.0-preview2-final**
* Versions of Client-Side NuGet/NPM Packages: **1.0.0-preview2-final**
* Are you using the C# client or the JavaScript client: **JavaScript/Typescript**
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): **IIS Express**
* The Operating System on the Server (Windows/Linux/macOS): **Windows**
* The Operating System on the Client (Windows/Linux/macOS): **Windows**
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): **Chrome**
* If possible, please collect Network Traces and attach them **[Network traces](https://gist.github.com/BastienVerschaete/73554d92a79ab3d8b11d14dbed2a8a7f)**
* If possible, please collect logs from the client:
* If possible, please collect logs from the server:

Any help would be really appreciated

**Comment by BastienVerschaete** [comment]
In my Configuration method in startup.cs I have the following lines. The rest of my application hasn't given any CORS issues so far.

    // CORS
    services.AddCors(options =>
    {
       options.AddPolicy("AllowAnyOrigin",
           builder => builder.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());

       options.AddPolicy("AllowSpecificOrigin",
           builder => builder.WithOrigins("localhost:4200").AllowAnyMethod().AllowAnyHeader());
    });
    services.Configure<MvcOptions>(options =>
    {
        options.Filters.Add(new CorsAuthorizationFilterFactory("AllowAnyOrigin"));
    });

In my Configure method I have:

    app.UseAuthentication();
    app.UseCors();
    app.UseHttpsRedirection();
    app.UseSignalR(routes =>
    {
         routes.MapHub<NotificationHub>("/api/notification");
    });
    app.UseMvc();

Is there a specific order I have to follow here?

**Comment by BastienVerschaete** [comment]
Okay I will close the issue, it seems that configuring MVC with CORS doesn't seem to work here.
When I use

    app.UseCors(builder =>
      builder.WithOrigins("http://localhost:4200")
         .AllowAnyHeader().AllowAnyMethod().AllowCredentials()
      );

It's working, thank you for your time.

**Comment by anurse** [comment]
I think the problem is that you were creating named policies and not referencing them in the CORS middleware. In your most recent example, you are directly applying the policy to the middleware so it works. Though, I'm not an expert on how CORS works so I'd suggest asking on StackOverflow or in aspnet/Cors if you have more questions about CORS specifically
