### ISSUE TITLE
"Subject" not available in '@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha2-final'

### ISSUE THREAD

**Issue by thanga91** [aspnet/SignalR#2055]
When building i am getting below exception, since uglify doesn't support ES6. I am trying to get the ES5 version of subject from '@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha2-final',  but i am not able to import it even though it has been exported in signalr-clientES5-1.0.0-alpha2-final.js. I am able to import ES5 versions of HubConnection, TransportType but couldn't import Subject.

Exception: Unexpected token: name (Subject) UglifyJs 

Version: "@aspnet/signalr-client": "^1.0.0-alpha2-final

**Comment by anurse** [comment]
Please update to the latest builds: `1.0.0-preview2-final` on both the server and client and try again. The alpha versions are no longer supported. If you are still seeing the issue then, comment further and we can investigate and reopen the issue if there's a bug there.
