### ISSUE TITLE
Azure RedisCache Backplane Logging/Signalr logging

### ISSUE THREAD

**Issue by DebolaA** [aspnet/SignalR#2056]
I have a Single Page Azure Web App that uses Signalr(Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha1-final) to broadcast events(login, logout, department creation etc) to connected clients.

I also scale my application to several instances at peak times and i use Redis Cache Backplane (Microsoft.AspNetCore.SignalR.Redis" Version="1.0.0-alpha2-final) to distribute event broadcast messages to all connected clients

i use angular front end (@aspnet/signalr-client": "^1.0.0-alpha2-final)

on azure, i enabled diagnostic log to log information and error messages.

the above works fine but when i scale up the application, it is difficult to trace information or error messages as i have to look through up to 10 instance application logs to find information or error; 

**my question:** **How do i ensure redis cache logs error messages or information on all available instances rather than on instances where client is connected; how do i know if a client has missed out on event broadcast message? how do i ensure signalr sever/hub logs all messages on all application log instances?**

thank you in advance

**Comment by anurse** [comment]
There is no way built-in to SignalR to aggregate logs across multiple instances. If you want to aggregate logs, you need to look at something like [Application Insights](https://azure.microsoft.com/en-us/services/application-insights/) or use scripts/tools to aggregate the logs across all your instances.

Closing this as the question is not related to SignalR specifically. If you have questions about how to aggregate logs in ASP.NET Core applications, I suggest asking on [StackOverflow](https://stackoverflow.com/questions/tagged/asp.net-core)
