### ISSUE TITLE
1.0.0-preview2-final - looping out group messages multiple times

### ISSUE THREAD

**Issue by rr222cy** [aspnet/SignalR#2059]
Hi!

I'm running into some issues after updating from the alpha1 to preview2. Some information about the setup:

Microsoft.AspNetCore.SignalR: 1.0.0-preview2-final
Javascript js file: 1.0.0-preview2-final
Server: Kestrel / IIS
OS on server and client: Windows server 2016, Windows 10
Browser: Firefox (latest) and Chrome (latest)

In my Hub class I have the following method for registering a connecting user to a group

```
// name = username, role = moderator/user, roomId = chat room, GUID converted to string
        public async Task Notify(string name, string role, string roomId)
        {
            await Groups.AddAsync(Context.ConnectionId, roomId);
            
            await Clients.Group(roomId).SendAsync("online", name, role, roomId);
            if (role == "agent")
            {
                await Clients.Group(roomId).SendAsync("agentOnline", name, role, roomId);
            }
        }
```
On the front-end I have a chat with multiple rooms that users can jump between as they wish. Now this has been working as expected before the update where users could go to e.g. "room1" and write "hello", then go to e.g. "room2" and write "hello all", with "hello" and "hello all" showing up in the correct rooms.

Messages still shows up in the correct rooms, however after jumping between rooms, say i go "room1->room2->room1" and then write "hey", the method invoked for sending out the message loops out the message 3 times for the user sending it,

I'm at a complete loss as to what I could be doing wrong and would appreciate all input and pointers to how I can solve this.

**Comment by anurse** [comment]
This is occurring because you are adding the connection to the group each time the client calls `Notify`. We don't de-duplicate connection IDs in groups (at the moment) so each time you call it, a new copy of the connection is being added to the group.

@davidfowl do you remember if SignalR on ASP.NET de-duplicated connection IDs?

**Comment by rr222cy** [comment]
Thank you @anurse !

I did as you said and as far as I can tell from some initial testing it's working just as it should now. 👍

**Comment by anurse** [comment]
I confirmed we now have logic to ensure we don't add duplicate connections to the same group.
