### ISSUE TITLE
Edge - Unable to initialize any of the available transports

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#2074]
I'm seeing some odd behaviour in edge with a simple hub and connection; which working in chrome.
The browser console shows the following: -
Error: Failed to start the connection: Error: Unable to initialize any of the available transports.

Fiddler shows that the POST /echo/negotiate HTTP/1.1 results in a response of

`{"connectionId":"A2IhDR8ctXCxhDnjmKoc7w","availableTransports":[{"transport":"WebSockets","transferFormats":["Text","Binary"]},{"transport":"ServerSentEvents","transferFormats":["Text"]},{"transport":"LongPolling","transferFormats":["Text","Binary"]}]}`

**Comment by davidfowl** [comment]
Are you using the right client version?

**Comment by grahamehorner** [comment]
if these are the current/correct version then yes; the same code works fine when using chrome seem odd? 
```
    "@aspnet/signalr": "^1.0.0-preview2-final",
    "@aspnet/signalr-protocol-msgpack": "^1.0.0-preview2-final",
```

**Comment by davidfowl** [comment]
That is odd, are you sure something isn't cached? This specific issue ends up being a client and server version mismatch.

**Comment by grahamehorner** [comment]
CTRL+F5 shows all the resource coming from the server (localhost) and this results in the same error in Edge, wondering if Edge has some differences to Chrome with regards firewall settings and localhost?  I can also confirm that I'm using the Microsoft.AspNetcore.SignalR v1.0.0-preview2-final nugget package on the server.

**Comment by grahamehorner** [comment]
on the  server side I've noticed the following: -

**Chrome**
`Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:57146/echo/negotiate text/plain;charset=UTF-8 0`

**Edge**
`Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:57146/echo/negotiate  0
`
grasping at straws as it's an odd one; going to get network admin to disable firewall for localhost/private network to see if that helps; happy to upload a repo to that shows the issue

**Comment by grahamehorner** [comment]
update: disabled windows defender on all networks; no change Edge still errors, Chrome connects

**Comment by anurse** [comment]
Can you use the dev tools in Edge to capture a network trace? See https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/network for a guide.

Also, can you collect client logs, etc. as requested by the Issue Template? https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md

**Comment by grahamehorner** [comment]
Please find attached the network trace for both Edge & Chrome; Chrome is working as expected however Edge fails to connect


Versions of Server-Side NuGet Packages:
Microsoft.AspNetCore.SignalR 1.0.0-Preview2-final


Versions of Client-Side NuGet/NPM Packages:
@aspnet/signalr 1.0.0-Preview2-final

Are you using the C# client or the JavaScript client: typescript

The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):
Kestrel

The Operating System on the Server (Windows/Linux/macOS):
Windows 10

The Operating System on the Client (Windows/Linux/macOS):
Windows 10


[Edge-SignalR-Kestrel-Issue.zip](https://github.com/aspnet/SignalR/files/1927451/Edge-SignalR-Kestrel-Issue.zip)

**Comment by grahamehorner** [comment]
This was an issue with the transportType value; the masking was incorrect and resulted in chrome connecting with server side events, but egde not connecting. 

close as user (numpty) error

**Comment by grahamehorner** [comment]
close as user (numpty) error

**Comment by btcosta** [comment]
Total newb here, I am trying to use SignalR in .NET Core 2.1 Preview and I am getting this error. Can someone explain what "This was an issue with the transportType value; the masking was incorrect and resulted in chrome connecting with server side events, but egde not connecting," this means? How do I fix it?

**Comment by davidfowl** [comment]
Use the same version on the client and server.

**Comment by btcosta** [comment]
Thanks for the reply. So I must of screwed something up installing the preview packages because this is my dev machine running in debug on localhost. So....shouldn't they be one in the same by default?

**Comment by davidfowl** [comment]
During the preview there are braking changes every release until we get to 1.0.0. We can’t afford to be backwards compatible

**Comment by btcosta** [comment]
Gotcha. Any idea when SingalR will make it in to Core officially?

**Comment by davidfowl** [comment]
When 2.1 is officially released

**Comment by btcosta** [comment]
Lol. Thanks for that clarification. 😃
