### ISSUE TITLE
WebSocket sample not working for wss connections

### ISSUE THREAD

**Issue by MderM** [aspnet/SignalR#2075]
Got a hub hosted in IIS. It uses https. 

Connecting with a modified https://github.com/aspnet/SignalR/blob/dev/samples/ClientSample/HubSample.cs
everything works as expected.

Using the websocket sample
https://github.com/aspnet/SignalR/blob/dev/samples/WebSocketSample/Program.cs
to connect to wss://route/to/hub/ws
gives me an Exception stating it is unable to connect to the remote server. Am I missing something?

 var ws = new ClientWebSocket();
            ws.Options.RemoteCertificateValidationCallback = (sender, certificate, chain, errors) => true;
            await ws.ConnectAsync(new Uri("wss://route/to/hub/ws"), CancellationToken.None); --> Exception

**Comment by anurse** [comment]
Can you collect the information requested in the issue template? https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md

Most specifically, it would be helpful to have client and server logs.

Are you able to hit the server with plain `https`? (i.e. not using a WebSocket?)

**Comment by MderM** [comment]
`try
            {
                await ws.ConnectAsync(new Uri("wss://route/to/hub/ws"), CancellationToken.None);
            } catch (Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }`

gives me following output:

Unable to connect to the remote server
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at ConsoleApp3.Program.RunWebSockets() in C:\Dev\workspace\webonds\ConsoleApp3\Program.cs:line 22

There are no client logs, since it is a plain console app.
I dont' know where to find the logs of the server app from IIS.

I configured it using
` WebHost.CreateDefaultBuilder(args)
                .UseIISIntegration()
                .UseKestrel()
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                    logging.AddConsole();
                    logging.AddDebug();
                })
                .UseStartup<Startup>();`

**Comment by MderM** [comment]
I also tried to run the server app locally.

`Content root path: C:\Dev\workspace\webonds\WebApplication2\bin\Release\netcoreapp2.1\publish
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001`

Now, again, connecting via HubConnection works as expected, using the connection to the plain websocket with  
`await ws.ConnectAsync(new Uri("wss://localhost:5001/bonds/ws"), CancellationToken.None); ` or
`await ws.ConnectAsync(new Uri("wss://localhost:5000/bonds/ws"), CancellationToken.None); ` 
does not work where 'bonds' is the route to my hub.

I use the SDK Microsoft.NETCore.App (2.1.0-preview2-26406-04) dependency on both client console apps.

The HubConnection app uses SignalR.Client (1.0.0-preview2-final) dependency.

The server app uses the same SignalR and NETCore.App dependencies and additionally it uses AspNetCore.App (2.1.0-preview2-final).

I hope this helps a bit more.

**Comment by MderM** [comment]
It was `await ws.ConnectAsync(new Uri("ws://localhost:5000/bonds/ws"), CancellationToken.None);`

**Comment by BrennanConroy** [comment]
Remove /ws from the end of your `Uri`

**Comment by anurse** [comment]
Yeah, the endpoints were modified to not have `/ws` on the end, but the WebSocketSample is out of date. I'll send a PR to fix it.

**Comment by anurse** [comment]
Also, please note that if you are connecting to a SignalR hub, the WebSocketSample is not sufficient. You are responsible for reimplementing the entire [SignalR Hub Protocol](https://github.com/aspnet/SignalR/blob/dev/specs/HubProtocol.md). The WebSocketSample is for connecting to a `ConnectionHandler` such as the [`MessagesConnectionHandler` in the SignalRSamples project](https://github.com/aspnet/SignalR/blob/dev/samples/SignalRSamples/ConnectionHandlers/MessagesConnectionHandler.cs)

If you just want to connect to a Hub using WebSockets directly, you should use `HubConnection` from `Microsoft.AspNetCore.SignalR.Client` but set the transport option to `WebSockets` rather than using the default, which automatically negotiates a transport for you.

**Comment by MderM** [comment]
Ok. That seems to work now. Since the sample was reworked in the meantime, I think this issue can be closed.
I wanted to use the websocket connection to use my backend hub with frameworks that have no client library (speaking of Dart and Flutter). The previous sample code suggested this possibility without reimplementing the hub protocol.
