### ISSUE TITLE
1.0.0-preveiw2-final IE 9 long polling/connection issue

### ISSUE THREAD

**Issue by mattchidley** [aspnet/SignalR#2076]
* dotnet SDK:
2.1.300-preview2-008533
* Versions of Server-Side NuGet Packages: 
Microsoft.AspNetCore 2.1.0-preview2-final
Microsoft.AspNetCore.All 2.1.0-preview2-final
Microsoft.AspNetCore.SignalR 1.0.0-preview2-final
* Versions of Client-Side NuGet/NPM Packages:
@aspnet/signalr signalr.js
* Are you using the C# client or the JavaScript client: javascript client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Kestrel (IIS Express)
* The Operating System on the Server (Windows/Linux/macOS): Windows 10
* The Operating System on the Client (Windows/Linux/macOS): Windows 7
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): IE 9

**Issue summary:** 
An IE 9 client is unable to connect to the SignalR hub using the long polling transport type.

The sequence of events:
The IE 9 client successfully POST to /negotiate.
The IE 9 client attempts to connect to the SignalR hub, but the request does not make its way to the OnConnectedAsync method. My Connection hub does not appear to be constructed either.

The transport being attempted by the IE 9 client is Long Polling. I do not believe this is a transport type issue, as I am able to successfully connect IE 10+, Chrome, and Firefox clients (what I tested) to the hub using a forced Long Polling transport type.

I've been using BrowserStack to test IE 9, and I've tried it both by running it locally and also putting a tunneling agent (ngrok) infront of the app running on IIS Express, but I don't think this approach is creating issues because again - both work on IE 10+/other browsers.

Furthermore, I have noticed that the requests coming into the application are a bit different:
*both IE 9 and Chrome are being forced to use Long Polling:
IE 9:
Request starting HTTP/1.1 POST http://localhost:57641/chat/negotiate? 0
Request starting HTTP/1.1 GET http://localhost:57641/chat?id=2pbfc18OdAzlfuEdmz3Xaw&_=1524059965519 

Chrome: 
Request starting HTTP/1.1 POST http://localhost:57641/chat/negotiate? text/plain;charset=UTF-8 0
Request starting HTTP/1.1 POST http://localhost:57641/chat?id=lE3caCVhiujIRX5vmUDDAQ text/plain;charset=UTF-8 32
Request starting HTTP/1.1 GET http://localhost:57641/chat?id=lE3caCVhiujIRX5vmUDDAQ&_=1524059981615  

It may also be important to mention that I was able to connect the IE 9 client using long polling using the 1.0.0-preview1-final version. But I cannot confirm exactly which version of the client side javascript I was using.

**Comment by anurse** [comment]
Unfortunately we don't support IE 9, we require IE 11 (which is supported on all Windows versions currently supported by Microsoft).

I'm closing this as the issue only appears to occur in an unsupported browser and we have no plans to officially support IE 9.

Having said that, I'm happy to give you a bit of best-effort support to see if we can figure out what's wrong. What Hub Protocol are you using? One thing I notice from [Can I Use](https://caniuse.com/#search=xhr%20level) is that XHR Level 2 was added in IE 10, and we require that for the MessagePack protocol.

Are there any other errors in the console on IE 9? Can you collect the client side logs referenced here? https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md

**Comment by davidfowl** [comment]
@mattchidley we'll be sure to explicitly state our browser support matrix when we have more docs.

**Comment by anurse** [comment]
Filed: https://github.com/aspnet/Docs/issues/6015
