### ISSUE TITLE
A client can easily overwhelm the servers memory by constantly sending to a broadcast hub method

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2084]
We currently fire-and-forget hub invocations
https://github.com/aspnet/SignalR/blob/9a0c190f487b9f48eaaa83fb4f3c1675ee21bdc0/src/Microsoft.AspNetCore.SignalR.Core/HubConnectionHandler.cs#L187
This can cause high lock contention and quickly grow the servers memory when many invocations are trying to write to the same connection. A quick test where we await the invocations shows stable low memory without affecting RPS in the load test that found this.

**Server Hub**

```c#
public class BroadcastHub : Hub
{
    public Task Broadcast(string message)
    {
        return Clients.All.SendAsync(message);
    }
}
```

**Client**

```c#
while (true)
{
    hubConnection.SendAsync("Broadcast", "flood server");
}
```

**Comment by muratg** [comment]
Approved.
