### ISSUE TITLE
HubConnection is not available on HubCallerContext 1.0.0-preview2-final

### ISSUE THREAD

**Issue by popcatalin81** [aspnet/SignalR#2093]
The Connection property was available in preview1 but is private in preview2.

We are using the connection to retrieve the RemoteIpAddress (among others), so we need the connection object.
```csharp
var ipAdr = this.Context.Connection.RemoteIpAddress; // not available in preview2-final
```

Is there an alternative for preview2-final to retrieve the remote IpAddress?

Edit:
`var remoteIp = Context.Features.Get<IHttpContextFeature>().HttpContext.Connection.RemoteIpAddress;`
seems to work

**Comment by davidfowl** [comment]
You can simplify it by doing:

```C#
var remoteIp = Context.GetHttpContext()?.Connection.RemoteIpAddress;
```

HttpContext can be null but it isn't when you're running in ASP.NET Core. It'll be possible to run on transports that don't have an IP so you should make sure you're checking for null.
