### ISSUE TITLE
404 negotiate not found

### ISSUE THREAD

**Issue by pwfraley** [aspnet/SignalR#2094]
Hi,
I just upgraded to <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="1.0.0-preview2-final" /> and in my Angular app "@aspnet/signalr": "^1.0.0-preview2-final", from the 1.0.0-alpha

After the upgrade I get the HUBNAME/negotiate not found error.

It seems like I am using all the correct libs (dotnet core versions).

Please help.

**Comment by pwfraley** [comment]
Ok the Problem seems to have resolved itself.  I am not sure what it was, if it was chaching, or something else.

**Comment by anurse** [comment]
The alpha did use a different URL on the server, so it may have been some kind of caching bug. Glad it's resolved!

**Comment by LucasArgate** [comment]
Im having this same problem.

[Log]
Information: Normalizing '/chat' to 'http://localhost:57470/chat'.

[Version]
netcore 2.0

im following this tutorial:
https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/

**Comment by anurse** [comment]
Can you collect network traces and client logs as requested here? https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md

**Comment by LucasArgate** [comment]
Sure, sorry:

## Versions of Server-Side NuGet Packages:
GeoCoordinate" Version="2.0.1"
GeoCoordinate.NetCore" Version="1.0.0.1"
Microsoft.AspNetCore" Version="2.0.2"
Microsoft.AspNetCore.All" Version="2.0.0"
Microsoft.AspNetCore.Cors" Version="2.0.1"
Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0"
Swashbuckle.AspNetCore" Version="2.3.0"
**Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha1-final"**


## Client
@aspnet/signalr@1.0.0-preview2-final

looking the version of signarR are different i will try use the same..

OK?

**Comment by anurse** [comment]
> looking the version of signarR are different i will try use the same..

Yeah, the versions of the client and server have to match during the previews. After we release, we will work to maintain compatibility between different versions of the client and server, but things are changing quickly during the previews.

**Comment by LucasArgate** [comment]
@anurse  it working now!

thanks so mutch 👍

**Comment by leehung-net** [comment]
Im having this same problem.

im using @aspnet/signalr@1.1.0 with npm.

[Log]
Information: Normalizing '/recoverhub' to 'http://localhost:8899/recoverhub'.

[Version]
netcore 2.2.1
