### ISSUE TITLE
memory leak group expiration 

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#2103]
The current code that relates to groups causes a memory leak as group aren’t cleaned up when all users leave, groups should have a last activity date/time and expiry after a given amount of inactivity in a similar way to that of the redis user/server processes to prevent the memory leak and to allow the server to operate smoothly with high volumes of activity across many groups.

**Comment by anurse** [comment]
And, the fix ended up in 2.1,0 🎉
