### ISSUE TITLE
using npm @aspnet/signalr angular package. could not find any documentaion nor samples on the same. It would be nice if we can get some working samples .  we wan't to use this with asp.net core and angular 5 SPA

### ISSUE THREAD

**Issue by UdayaBhandaru** [aspnet/SignalR#2109]
using npm @aspnet/signalr angular package. could not find any documentaion on the same neither the sample. can you please privide any sample or documenation we wan't to use this with asp.net core and angular to using npm @aspnet/signalr angular package. could not find any documentaion nor samples on the same. It would be nice if we can get some working samples . we wan't to use this with asp.net core and angular 5 SPA

**Comment by anurse** [comment]
There is no documentation or samples for that exact scenario at this time. Our documentation can be found here: https://docs.microsoft.com/en-us/aspnet/core/signalr/?view=aspnetcore-2.1.
