### ISSUE TITLE
Simplified connection API

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#211]
The EndPoint API is a model where OnConnectedAsync is called for each connection. The end point represents a binding to which all connections "connect". In this model, storing per connection state needs to be done in connection metadata. Users also need to write the receive loop manually which can be non trivial (especially handling exceptions). The proposal is to offer a simplified API to solve the above problems:

1. Each ConnectionHandler has a 1:1 mapping to the connection itself. This means you can store per connection state in fields of that object.
2. The receive loop is implemented and it handles all of the cases (errors etc).

Here's an example of what it could look like:

```C#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSockets();
    }

    public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
    {
        loggerFactory.AddConsole(LogLevel.Debug);

        app.UseFileServer();

        app.UseSockets(routes =>
        {
            routes.MapConnectionHandler<EchoConnectionHandler>("/echo");
        });
    }
}

public class EchoConnectionHandler : ConnectionHandler
{
    public override Task OnMessageAsync(Message message)
    {
        return Connection.Transport.Output.WriteAsync(message);
    }
}

public abstract class ConnectionHandler
{
    public Connection Connection { get; internal set; }

    public virtual Task OnConnectedAsync() => Task.CompletedTask;
    public virtual Task OnDisconnectedAsync() => Task.CompletedTask;
    public abstract Task OnMessageAsync(Message message);
}
```

**Comment by DamianEdwards** [comment]
I like this as a layer above `Endpoint` and can see reasons for both.

**Comment by muratg** [comment]
@davidfowl will you do this in the next few weeks? (If not move it out)

**Comment by davidfowl** [comment]
No, this can be post preview
