### ISSUE TITLE
DefaultHubLifetimeManager private

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#2111]
Please consider making the DefaultHubLifetimeManager
        private readonly HubConnectionStore _connections = new HubConnectionStore();
        private readonly HubGroupList _groups = new HubGroupList();

internal, so that derived classes may access these and provide extra features such as evaluating if a group exists before adding a connection and if the group doesn't exists if the connection has the correct permissions to create a group

**Comment by davidfowl** [comment]
You mean protected right? You should be careful pushing too much knowledge into a custom lifetime manager. If you ever need to scale out, you'll need to re-implement that logic.

**Comment by grahamehorner** [comment]
Yeah, oops; if HubLifetimeManager is not the correct place, where would you suggest logic be placed for things like scheduled background tasks & monitoring of repository data that is used to trigger sending of message to clients?

**Comment by davidfowl** [comment]
@grahamehorner an IHostedService.

**Comment by grahamehorner** [comment]
and if the IHostedService also needs to receive messages from the clients how would one do this? sorry if these are questions already answered, been looking around but couldn’t find anything and want to do it correctly so to do justice to all the great work done thus far with performance etc.

**Comment by davidfowl** [comment]
The hub is the only thing that receives messages from clients.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
