### ISSUE TITLE
Ensure that interfaces used in Hub<T> always return Task for methods

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2116]
Today we support both void returning methods and Task returning methods, we should change this to always require a task returning method. Today we fire and forget if the method is void returning. This leads to unobserved Task exceptions in your code if for example you were using redis and it went down.

**Comment by anurse** [comment]
Is this API review or should we take it to ship room? cc @muratg 

PR coming very shortly.

**Comment by muratg** [comment]
This is a missing API review case. No ship room approval required if this goes in in the next few.
