### ISSUE TITLE
Need a way to check the connection state on the Client API

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#212]
I just started playing with the client API and there's no way to know if you are still able to send. Of course this is a built in race condition but we need to figure out what we think the right behavior is here.

**Comment by muratg** [comment]
@moozzyk @davidfowl will ping you on this. (This may not be needed anymore.)

**Comment by moozzyk** [comment]
Once the close event is fired you can't send. We track the state internally in connection so we could expose it if needed but I think the event should be enough

**Comment by davidfowl** [comment]
@moozzyk The event is a crappy solution because it requires the consumer to store the state when we already have it.

**Comment by davidfowl** [comment]
Superseded by #900
