### ISSUE TITLE
Performance leak

### ISSUE THREAD

**Issue by myrup** [aspnet/SignalR#2124]
We've been chasing a performance bug for the past week. While running a few hours the app cpu usage slowly creeps up to 100%. We've managed to isolate the culprit to our signalR client trying to connect/reconnect to an unreachable server (5 seconds between retries). The time between reconnects is constant, yet there seems to be some sort of performance leak (this might be a .Net core team issue).

This example is enough to exhibit the problem:
```c#
class Program {
    static HubConnection connection;
    static void Main(string[] args) {
        connection = new HubConnectionBuilder()
                        .WithUrl("http://127.0.0.1:5000/badhub") // connect to an offline server
                        .Build();
        Task.Run(ConnectAsync);
        System.Threading.Thread.Sleep(Int32.MaxValue);
    }

    public static async Task ConnectAsync() {
        while (true) {
            try {
                Console.WriteLine(DateTime.Now + " " + Thread.CurrentThread.ManagedThreadId + " Connect");
                await connection.StartAsync();
                break;
            } catch {
                await Task.Delay(0); // Set delay low to invoke leak faster
            }
        }
    }
}
```
We're running 2.1 preview 2 SCD'ed to linux-arm on raspian linux.

A linux perf snapshot reveals most processor time is spent at `PROCRemoveThread`

**Comment by myrup** [comment]
We're seeing the same behaviour on Darwin, but it takes a few days instead of hours to creep up. It effectively renders the SignalR C# client useless for long running processes.

**Comment by davidfowl** [comment]
@myrup and you're sure the problem isn't in your application? We actually haven't done any long running tests ourselves but we're getting that up and running soon. We'll see if we can reproduce the issue. It also might have fixed itself in the latest if you're willing to grab a ci build (look at the readme).

Does PROCRemoveThread method ring a bell @jkotas @stephentoub ?

**Comment by jkotas** [comment]
`PROCRemoveThread` is called when thread exits. It walks the linked list of all threads in the process. If you are spending a lot of time in it, it means that there are likely many thousands threads in the process (ie the process is leaking threads).

Should be able to confirm this theory by attaching the debugger to the process, and checking how many threads are there are and what they are doing.

**Comment by myrup** [comment]
@davidfowl we’ve created the minimal sample to show it’s not our app. @jkotas The ThreadId is included in stdout to confirm that just a few threads are being cycled. Cat /proc/pid/status when process is visiting crazytown shows only 14 threads.

**Comment by davidfowl** [comment]
> @davidfowl we’ve created the minimal sample to show it’s not our app. 

Can you share that sample application with us?

**Comment by stephentoub** [comment]
You're not fully consuming nor disposing of the http responses, this creating a very fast leak of open sockets.

**Comment by Jodacola** [comment]
In the naive example I added and in the SignalR code, the client.SendAsync call is throwing the System.Net.Http.HttpRequestException with a "Connection refused"  and not returning an HttpResponseMessage to be inspected and disposed.  I'll look into the HttpClient code in CoreFX to see where my own misunderstanding is.

**Comment by Jodacola** [comment]
@stephentoub I can take this over to CoreFX, but as I'm looking through HttpClient on master, https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L506, `FinishSendAsyncUnbuffered` isn't disposing of the response when it's throwing, whereas `FinishSendAsyncBuffered` *does* dispose.

My level of exposure to CoreFX code is pretty limited, so I'm not sure if there's a compelling reason for not disposing of the response in FinishSendAsyncUnbuffered without spending more time to dig in, but in the scenario I described above and your note about the response not being cleaned up, I think I can see where sockets are being left laying around when HttpClient is throwing.

**Comment by stephentoub** [comment]
> FinishSendAsyncUnbuffered isn't disposing of the response when it's throwing

I'm not following; what's not disposing of what?  If `await sendTask.ConfigureAwait(false)` throws, there's nothing to be disposed of.  If it returns null, there's nothing to be disposed of.  If it returns non-null, we're returning it and wouldn't want to dispose it.  What am I missing?  Thanks.

**Comment by Jodacola** [comment]
Compare `FinishSendAsyncBuffered`'s catch block (https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L479-L496) to `FinishSendAsyncUnbuffered`'s catch block (https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L511-L523).

If an exception is thrown in `FinishSendAsyncBuffered`, the response is disposed.  The same is not true in `FinishSendAsyncUnbuffered`.

When the connection is refused during the course of SignalR trying to connect, the exception is being thrown from within `FinishSendAsyncUnbuffered`, which, unless I'm missing something, leads me to the conclusion that the response, if it's not null, isn't being disposed, as you suggested it should be.

SignalR exception stack:
```
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/josh/projects/signalr/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/LoggingHttpMessageHandler.cs:line 31
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.Negotiate(Uri url, HttpClient httpClient, ILogger logger) in /Users/josh/projects/signalr/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs:line 302
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponse() in /Users/josh/projects/signalr/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs:line 438
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat) in /Users/josh/projects/signalr/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs:line 215
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat) in /Users/josh/projects/signalr/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs:line 142
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() in /Users/josh/projects/signalr/src/Common/ForceAsyncAwaiter.cs:line 39
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat) in /Users/josh/projects/signalr/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs:line 116
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore() in /Users/josh/projects/signalr/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 130
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() in /Users/josh/projects/signalr/src/Common/ForceAsyncAwaiter.cs:line 39
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync() in /Users/josh/projects/signalr/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 64
```

Should HttpClient be trying to dispose of the response in `FinishSendAsyncUnbuffered` like it does in `FinishSendAsyncBuffered`, or am I completely missing some other important piece of logic?

Having said all that, interestingly, I'm still running into the same issue when issuing a `SendAsync` with `HttpCompletionOption.ResponseHeadersRead` or without, meaning, I still get "too many open files" exceptions no matter if `SendAsync` is finishing with a call to `FinishSendAsyncBuffered` or `FinishSendAsyncUnbuffered`, but maybe that's a result of the tight while loop.

**Comment by stephentoub** [comment]
> Should HttpClient be trying to dispose of the response in FinishSendAsyncUnbuffered like it does in FinishSendAsyncBuffered, or am I completely missing some other important piece of logic?

The difference is that other stuff happens that can throw an exception in FinishSendAsyncBuffered after successfully getting the HttpResponseMessage.  That's not the case for FinishSendAsyncUnbuffered; if it successfully gets an HttpResponseMessage, it'll be returned and won't throw an exception (unless something catastrophic happens of course).

**Comment by myrup** [comment]
@davidfowl The sample code is included in the first post. Happy this is being looked into!

**Comment by stephentoub** [comment]
Are you only able to repro this leak when (a) you're using an IP address as the host name and (b) the connection fails?  I think there may be a leak (until a finalizer runs) in that situation in Socket itself; will investigate further.
cc: @geoffkizer

**Comment by Jodacola** [comment]
I'm currently running my naive HttpClient test I included in https://github.com/aspnet/SignalR/issues/2124#issuecomment-383618523 with http://localhost/badhub/ instead of http://127.0.0.1:5000/badhub/.  I don't have any http servers running locally at the moment.

I'm still getting the connection refused exception, but I'm not leaking file descriptors like crazy anymore.  I'm monitoring the process as it continues the tight loop, and it appears to be stable.  Looks like you're on to something, @stephentoub.

**Comment by stephentoub** [comment]
Thanks, Jodacola.  Could you also try using "127.0.0.1" but adding `GC.Collect(); GC.WaitForPendingFinalizers();` into your loop?  Just for additional confirmation... I expect/hope you'll see the issue similarly go away.

**Comment by stephentoub** [comment]
I opened https://github.com/dotnet/corefx/issues/29285 for the socket issue.  Assuming that's the only problem here, this SignalR issue can probably be closed.

**Comment by myrup** [comment]
@stephentoub does daily build 2.2.100-preview1-008633 include your [dotnet/corefx#29285](https://github.com/dotnet/corefx/issues/29285)  fix? 

I've changed the sample app to, instead of an ip, target a domain which refuses the connection. Testing SCD'ed to linux-arm on raspian linux (have not tried other systems) leaks are still occurring (possibly different issue?).

**Comment by stephentoub** [comment]
> does daily build 2.2.100-preview1-008633 include your dotnet/corefx#29286 fix?

No

**Comment by myrup** [comment]
@stephentoub OK. Assuming it's included tomorrow I will test and give feedback :)

**Comment by stephentoub** [comment]
It won't be; it's not in a release branch yet. If it's important to you, you can build the System.Net.Http library yourself from corefx's master branch and use that.

**Comment by stephentoub** [comment]
ps My fix addresses the socket leak, and I'm confident it does that. That's a very different manifestation than originally reported, so it's likely is not the same issue.

**Comment by davidfowl** [comment]
@myrup it could also be this https://github.com/aspnet/SignalR/commit/bd46d757ba008eac6196e0ecd8c6c9894ada831c. Try the latest SignalR builds from the dev branch (currently versioned at 1.1.0-*) https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR.Client.

**Comment by myrup** [comment]
@davidfowl Initial tests shows the heavy leak is gone with 1.1.0-preview1-34041! I'll leave it running and have a party tomorrow if nothing has spilled ;)

**Comment by myrup** [comment]
Ready to close this as fixed by #2137 (and not a bad side effect @Jodacola / @stephentoub uncovered two other issues on the way). 🎉

**Comment by stephentoub** [comment]
> uncovered two other issues on the way

Two?  I'm aware of one issue in sockets, which we haven't yet fixed but did work around in SocketsHttpHandler.  Just making sure I'm not missing something that needs to be addressed. :)

**Comment by myrup** [comment]
@stephentoub Ah ok, I mistook the socket workaround as a separate issue from the real socket issue. Regardless, Christmas has come early and signalR team has the honours of doing the closing of this matter ;)
