### ISSUE TITLE
Expose a connection state from HubConnection

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2127]
We should expose a ConnectionState enum from the HubConnection so that it's possible to avoid throwing from SendAsync if the HubConnection wasn't connected. Today it requires you storing your own bool and setting it in the Closed event.

**Comment by JamesNK** [comment]
Also need state on JS client.

**Comment by moozzyk** [comment]
Only that it can still throw if the connection gets disconnected after the check and before actually sending data...

**Comment by davidfowl** [comment]
Yep.

**Comment by MagicAndre1981** [comment]
when will this be released? Microsoft.AspNetCore.SignalR.Client Version 1.0.2 doesn't include this.

I assume the 2.2.0 means Asp.Net Core 2.2? Why not sync SignalR versions to match Asp.Net Core to easily see which version has the fix?

**Comment by davidfowl** [comment]
> when will this be released? Microsoft.AspNetCore.SignalR.Client Version 1.0.2 doesn't include this.

1.1, which will ship with ASP.NET Core 2.2

> I assume the 2.2.0 means Asp.Net Core 2.2? Why not sync SignalR versions to match Asp.Net Core to easily see which version has the fix?

We'll sync it in 3.0

**Comment by davidfowl** [comment]
That's correct. There are packages on the myget feed if you want to try them out right now but the final build will be with ASP.NET Core 2.2

**Comment by MagicAndre1981** [comment]
so I have to use [this version](https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR/1.1.0-preview1-34892)?

**Comment by MagicAndre1981** [comment]
the version works and I see the State property. How reliable are the 1.1 previews? Will we see radical API changes or only for 3 builds? 

btw, it would be better to have 2 feeds (1 feed for 3.0 and 1 for 2.2/1.1).

**Comment by MagicAndre1981** [comment]
I've tested the nightly versions a bit more, but it doesn't work the same like in the old SignalR. In my case 3 time the state is disconnected and I start 3 connections not only 1 like in old SignalR.

```
Application started. Press Ctrl+C to shut down.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HLG2H0UTOJ3O" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HLG2H0UTOJ3P" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLG2H0UTOJ3O" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
      Connection id "0HLG2H0UTOJ3P" received FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HLG2H0UTOJ3Q" started.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLG2H0UTOJ3P" sending FIN.
```

```
Connection = new HubConnectionBuilder()
            .WithUrl("https://foo:5001/barService")
            .Build();

if (Connection.State == HubConnectionState.Disconnected)
            {
                try
                {
                    await Connection.StartAsync();
                }
                catch (Exception e)
                {
                    Debug.WriteLine(e);
                }
            }
```

**Comment by davidfowl** [comment]
> I've tested the nightly versions a bit more, but it doesn't work the same like in the old SignalR

That's right, they work very differently.

> In my case 3 time the state is disconnected and I start 3 connections not only 1 like in old SignalR.

Can you clarify what you mean? There's no intermediate states, there's disconnected and connected. There's no automatic reconnect either so when disconnected, you need to manually reconnect.

**Comment by MagicAndre1981** [comment]
In each method I call a Connect method which checks the State to check if the connection is already connected and if not I start the connection. this works fine for old SignalR and I only have 1 connection. Now for the first 3 calls the state is always disconnected and I have 3 connections from 1 client.

**Comment by davidfowl** [comment]
Do you mean you have 3 different hubs?

**Comment by davidfowl** [comment]
Can you provide a sample project with repro steps?
