### ISSUE TITLE
 Embed version in the JavaScript client 

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2130]
We should log the version of the client (.NET/JS/whatever) and the version of the server to help diagnose issues when devs create issues with attached logs.

**Comment by JamesNK** [comment]
Can pull version in .NET from assembly version attribute. Is the version embedded anywhere in JS?

**Comment by JamesNK** [comment]
How do we embed the version number in the TS file? It is not something I've done before.

Lodash does it but I couldn't track down their build scripts.

Thoughts, ideas?

**Comment by anurse** [comment]
We'd basically do it the same way we do it in any other file. We'd have to just do a simple find-replace for a string in one of our build scripts, such as `build/repo.targets`

**Comment by muratg** [comment]
Updated the title to reflect how we approach this: https://github.com/aspnet/SignalR/pull/2229

**Comment by anurse** [comment]
https://github.com/aspnet/SignalR/commit/f005e80b14055a4ca629a17413c4c8647ccf70a5
