### ISSUE TITLE
HttpClient isn't disposed if transport fails to start when using HttpConnection and HubConnection

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2134]
We don't dispose the HttpClient if the transport fails to Start. This could cause resource leaks when using HubConnection in a retry loop since it can't call DisposeAsync because it doesn't even have a reference to the ConnectionContext if ConnectAsync fails to start.

**Comment by anurse** [comment]
Reopening to track porting the fix from `dev` into `release/2.1` in the next milestone (pending shiproom approval)

**Comment by muratg** [comment]
We'll bring this back to the shiproom.
