### ISSUE TITLE
Plan Java Client Work

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2138]
Should support Android. Make sure it has enough `Factory` types to pass Java Style Guidelines.

**Comment by rfrancisco** [comment]
When will this be available?

**Comment by JamesNK** [comment]
We're aiming to do a Java client in the next milestone (2.2) but right now there is no date on when 2.2 will be available.

**Comment by anurse** [comment]
Re-targetting this issue to preparing the plan and breaking it up into smaller chunks (each with it's own issue)

The work for this **includes** choosing the Java infrastructure we want to use (Maven, Gradle, etc.) and laying out the basic structure of the library

**Comment by mikaelm12** [comment]
Started an outline for this issue here https://github.com/aspnet/SignalR/issues/2482
