### ISSUE TITLE
NegotiateResponse with access token broken in .NET Client for WebSocket transport

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2140]
We're using the wrong access token provider for websockets. The DefaultTransportFactory stashes the AccessTokenProvider on the options which we never update directly https://github.com/aspnet/SignalR/blob/43fc0854c38bbde1cb495d1b5e4f3e594da79e50/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs#L110.

**Comment by JamesNK** [comment]
It is tougher to unit test web sockets but it is possible. Can ping back the Authorization httpheader like so https://github.com/aspnet/SignalR/blob/1c9607a1ed74e709bcb1b4983c1a6c13fea41e0e/test/Microsoft.AspNetCore.SignalR.Tests/WebSocketsTransportTests.cs#L71-L96

**Comment by JamesNK** [comment]
@davidfowl: Have you started on this at all? I recall you saying you had some local changes

**Comment by davidfowl** [comment]
Yea I’ll push it to a branch

**Comment by anurse** [comment]
Testing is even easier than we'd feared. There's already a test for JWT tokens. All I have to do is add an endpoint that does the negotiate redirect and make a copy of that test.
