### ISSUE TITLE
Marker Service isn't working

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2142]
Repro steps:

1. Create a new app
2. Add `.UseSignalR` to `Configure`, but **do not** add `.AddSignalR` to `ConfigureServices`
3. Run the app

Expected behavior: A clear error telling me to call `.AddSignalR`
Actual behavior: `InvalidOperationException: No service for type 'Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher' has been registered.`

The problem is that the marker service is checked in [`UseHub`](https://github.com/aspnet/SignalR/blob/a5d9930802ec9be37ed0a99f1dc043696a8a6720/src/Microsoft.AspNetCore.SignalR.Core/SignalRConnectionBuilderExtensions.cs#L15), but that's too late. `UseConnections` (called by `UseSignalR`) tries to get the connection dispatcher out first, and that's not present.

**Comment by davidfowl** [comment]
Ah, we should leave it in both places.

**Comment by anurse** [comment]
https://github.com/aspnet/SignalR/commit/555c1fd7208d6e64f0c93a42ff7d76fa234bb85e
