### ISSUE TITLE
Revisit warmup on SignalREchoAll scenario

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2144]
https://github.com/aspnet/SignalR/pull/2143

**Comment by JamesNK** [comment]
A way to finish processing all warm up messages is one option.

If that is difficult a warm up of a single message could be enough to eliminate startup times without impacting the actual benchmark.

**Comment by anurse** [comment]
We're just going to clean this up. Our perf testing is pretty good so far.
