### ISSUE TITLE
JavaScript client failing to connect to asp.net core 2.1 app implementing SignalR

### ISSUE THREAD

**Issue by stackt52** [aspnet/SignalR#2145]
I'm new to the dotnet platform. I've been trying to create a server app that implements signalR in order to push notifications to connected clients in real time (according to the blog: [https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-getting-started-with-signalr/](https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-getting-started-with-signalr)) but i've been having challenges having the client subscribe to push notifications services implemented on the server side using SignalR. I'm using .NET Core SDK 2.1.300-preview2, which ships with signalR, and for the client I'm using an `npm` module @aspnet/signalr@1.0.0-preview2-final.  

The client is a pure HTML5 app, and I'm adding the client signalR library using the `<script>` tag. When I run the client in order to connect I'm getting these errors in the browser console:
![console](https://user-images.githubusercontent.com/21298951/39275251-f517e3d4-48e4-11e8-8893-b457e7981f5a.png)
Snapshot of the code I'm using to establish connection:
![client_code](https://user-images.githubusercontent.com/21298951/39275341-398ca73e-48e5-11e8-8803-f05df48a9733.png)

At first I thought maybe it's the CORS issue, but I've enabled CORS in my backend app to allow all origins, headers, and methods, but still getting the same error.

I'm running both the client and server on macOs High Sierra.
How can I resolve this error?

**Comment by anurse** [comment]
You have to call `AllowCredentials` in your CORS configuration. SignalR sets the `withCredentials` flag on the XMLHTTPRequest object (so that cookies flow through), and you have to match that on the server.

It's not obvious though! Others have encountered this issue, so we filed https://github.com/aspnet/Docs/issues/6078 to track adding it to our documentation. Hope that helps!

**Comment by stackt52** [comment]
Awesome, after adding the the `AllowCredentials` everything starts working perfectly fine now. Thanks @anurse
