### ISSUE TITLE
Not reciving messages with Microsoft.AspNet.SignalR.Client in client .Net Core 2.0

### ISSUE THREAD

**Issue by georginacm** [aspnet/SignalR#2156]
Hi,

I have a SingalR server with .Net Framework 4.5.2, and a SignalR Client ( Console Application)  with .Net Framework 4.5.2 using:

Server:
![image](https://user-images.githubusercontent.com/29973878/39358193-a3139d44-4a15-11e8-8754-2e9afb01da87.png)

Client:
![image](https://user-images.githubusercontent.com/29973878/39358467-67452c8c-4a16-11e8-9e48-5a1e78eb1596.png)

All of them are working fine since months ago.

But currently I have another SignalR client in a .Net Core 2.0 Console Application using the same version of  Microsoft.AspNet.SignalR.Client. It is connecting fine, but is not reciving messages from the hub connection. Is there any issue with this nuget in .Net Core? 

This is the code:

            var hubProxy = hubConnection.CreateHubProxy("MyHub");

            hubProxy.On("created", data =>
            {
                Console.WriteLine("Incoming Created  data: {0}", data);
            });

            hubProxy.On("deleted", data =>
            {
                Console.WriteLine("Incoming Deleted data: {0}", data);
            });

            hubConnection.Start().ContinueWith(x =>
            {
                hubProxy.Invoke("subscribe", "firstFeature", "secontFeature");
            }).Wait();

            Console.WriteLine("Connected to {0}", hubConnection.Url.ToString());

Thanks!

**Comment by anurse** [comment]
Closing this as the issue belongs on github.com/SignalR/SignalR
