### ISSUE TITLE
''Microsoft.AspNetCore.SignalR.IHubClients' does not contain a definition for 'User''

### ISSUE THREAD

**Issue by SkeletonSkelettron** [aspnet/SignalR#2157]
Hi I have Signalr Hub and use it in controllers via injection this way

`private readonly IHubContext < ChatHub > chatHub;

        public SharedController( IHubContext<ChatHub> hubContext)
        {
            chatHub= hubContext;
        }

        public async void SendMessage([FromBody] JObject obj)
        {
            await chatHub.Clients.User(userId).SendAsync("ReceieveMessage", new { Message = message});
        }

program compiles, but on execution I get error: 

**''Microsoft.AspNetCore.SignalR.IHubClients' does not contain a definition for 'User''.**

but in other controllers everything works fine.
What's the problem?
I have signalr version 1.0.0-preview2-final

Thanks

**Comment by SkeletonSkelettron** [comment]
I've got the clue. I have following code before signalr line. 


    public async void SendMessage([FromBody] JObject obj)
    {
            dynamic room = null;

            if (origin == "pref")
            {
                room = await prefRepository.GetRoom(roomId);
            }
            else // origin == "king"
            {
                room = await kingRepository.GetRoom(roomId);
            }
             
             foreach (var item in room.Table)
             {
                  await chatHub.Clients.User(item.Player).SendAsync("ReceieveMessage", new { Message = message });
             }
        
    }

When I remove dynamic room = null; from program then signalr works as supposed to work. otherwise it does not 
Very strange, in any case 
P.S.
code above is incomplete

**Comment by anurse** [comment]
First off, I'd strongly recommend you avoid the `dynamic` keyword in C#. It causes large pieces of the code to be compiled at run-time instead of at compile-time.

What is the type of `item.Player` in your example? It has to be a `string` for this code to work.

**Comment by SkeletonSkelettron** [comment]
item.Player is string, id of the user.

**Comment by anurse** [comment]
It should be working then. I noticed you closed the issue, did you solve the problem?

What's the reason for using `dynamic room = null` rather than using static typing? Are you able to change to that? You'll get clearer errors at compile time if you are able to do that.
