### ISSUE TITLE
Maximum Payload size

### ISSUE THREAD

**Issue by ckoenig95** [aspnet/SignalR#2158]
Hi,

I tried to send larger amounts of data (> 100kb) over a SignalR connection from server (Kestrel) to client (Browser / JS) in a single methode invocation and got some unexpected results.

For example when sending a `byte[]` of size 50000 from server to client everything works as expected.
But when sending a `byte[]` of size somewhere between 100000 and 110000+ the server stops responding.
I got no errors/exceptions and tried the `JsonHubProtocol` and `MessagePackHubProtocol`.

I use AspNetCore v2.1.0-preview2-final on .NET Framework 4.6.1 with AspNetCore.SignalR v1.0.0-preview2-final.

I tested this on a Windows 10 Machine with Firefox 60.0b15 (64-bit) and Chrome 66.0.3359.117 (64-Bit).

A working example illustrating the issue can be found [here](https://github.com/ckoenig95/SignalRApplication).

#### TestHub.cs
```cs
public class TestHub : Hub
{
    public byte[] GetData(int size) => new byte[size];
}
```
#### Browser / JS:
```html
<script src="lib/signalr/signalr.js"></script>
<script src="lib/msgpack5/msgpack5.js"></script>
<script src="lib/signalr/signalr-protocol-msgpack.js"></script>

<script>
    (function () {
        let protocolSelect = document.getElementById("protocol");
        let connectButton = document.getElementById("connect");
        let startButton = document.getElementById("start");
        let startLengthInput = document.getElementById("startLength");
        let requestedLengthSpan = document.getElementById("requestedLength");
        let responseLengthSpan = document.getElementById("responseLength");

        let connection;

        connectButton.addEventListener("click", async () => {
            if (connection && connection.connection.connectionState === 1 /* Connected */)
                await connection.stop();

            let protocol;
            switch (protocolSelect.value) {
                case "json":
                    protocol = new signalR.JsonHubProtocol();
                    break;
                case "messagepack":
                    protocol = new signalR.protocols.msgpack.MessagePackHubProtocol();
                    break;
            }

            connection = new signalR.HubConnection("TestHub", { logger: signalR.LogLevel.Trace, protocol: protocol });
            await connection.start();
        });

        startButton.addEventListener("click", async () => {
            for (let i = startLengthInput.valueAsNumber; true; i += 100) {
                requestedLengthSpan.innerText = i;
                let data = await connection.invoke("GetData", i); // ISSUE: Stops responding when i is greater then ~100000 
                responseLengthSpan.innerText = data.length;
                await sleep(10);
            }
        });

        function sleep(ms) {
            return new Promise((resolve, reject) => setTimeout(resolve, ms));
        }
    })();
</script>
```

**Comment by davidfowl** [comment]
Just FYI that type of code will never be efficient. You can't send a 100KB byte array over the write and expect it to be fast 😄. It might just be taking an extremely long time because we use a moderately sized buffer (2K) by default.

Turn on logging to get more information.

**Comment by BrennanConroy** [comment]
I can't repro the issue with the latest bits, and I tried up to 1,000,000 byte array.
