### ISSUE TITLE
LongPollingTransport shutdown timer is configured incorrectly

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2169]
https://github.com/aspnet/SignalR/blob/c53514fa19bbb776ee3855a6cfaa1c4706b7f446/clients/ts/signalr/src/LongPollingTransport.ts#L182-L185

[`setTimeout`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) takes the callback as the **first** argument

**Comment by JamesNK** [comment]
Can we add a unit test the verifies that shutdown timeout works? 😸
