### ISSUE TITLE
Send client to server pings from C# client

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2175]
Depending on how connections die it can take an extremely long time for OnDisconnectedAsync to fire on the server. See the issue below for examples: 

https://github.com/aspnet/SignalR/issues/1290

The implementation would be the same as the client, we would abort the connection after some configured interval of inactivity.

**Comment by anurse** [comment]
For this work item, let's just get the client sending the pings. I opened #2289 to track using the Pings for marking clients as "disconnected".

Some notes:

* This change will mostly be done in `HubConnection` in `Microsoft.AspNetCore.SignalR.Client`. We'll need a timer (We can start with [`System.Threading.Timer`](https://msdn.microsoft.com/en-us/library/system.threading.timer(v=vs.110).aspx) but should consider using `TimerAwaitable` later on as a refactoring)
* When the timer fires, we send a ping message using `SendHubMessage`
* The interval of the timer should be configurable via a property on `HubConnection`. When the property is changed we need to update the timer.
* Tests: Use `HubConnectionTests.Protocol.cs` in `Microsoft.AspNetCore.SignalR.Client.Tests` as a guide.
