### ISSUE TITLE
solution compiles - samples do do not run  - can't find sdk

### ISSUE THREAD

**Issue by scharada** [aspnet/SignalR#2176]
trying to run the samples included in the repo ...

SignalRSamples> It was not possible to find any compatible framework version
SignalRSamples> The specified framework 'Microsoft.NETCore.App', version '2.2.0-preview1-26424-04' was not found.
SignalRSamples>   - Check application dependencies and target a framework version installed at:
SignalRSamples>       C:\Program Files\dotnet\
SignalRSamples>   - Installing .NET Core prerequisites might help resolve this problem:
SignalRSamples>       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
SignalRSamples>   - The .NET Core framework and SDK can be installed from:
SignalRSamples>       https://aka.ms/dotnet-download
SignalRSamples>   - The following versions are installed:
SignalRSamples>       1.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       1.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       1.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       1.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       1.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       1.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       1.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       1.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       2.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       2.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
SignalRSamples>       2.1.0-preview2-26406-04 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by anurse** [comment]
Have you added `C:\Users\[username]\.dotnet\x64` to your `PATH` and run `build.cmd`? See the Getting Started guide for more information: https://github.com/aspnet/SignalR/blob/dev/docs/GettingStarted.md

**Comment by scharada** [comment]
well. build went fine. completed all tasks. all unit tesst using stream failed.

then running one of the samples from command line or VS (preview) fails :

PS C:\Code\Microsoft\SignalR\samples\SignalRSamples> dotnet run --framework netcoreapp2.1
Using launch settings from C:\Code\Microsoft\SignalR\samples\SignalRSamples\Properties\launchSettings.json...
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.2.0-preview1-26424-04' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.0-preview2-26406-04 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
PS C:\Code\Microsoft\SignalR\samples\SignalRSamples>

**Comment by scharada** [comment]
running now perfectly. thank you. had to clean up few old setups and package cache... 
thx for your help.

**Comment by JamesNK** [comment]
Great. Closed as resolved.
