### ISSUE TITLE
tsc command error

### ISSUE THREAD

**Issue by bigswede74** [aspnet/SignalR#22]
I cant compile the sample projects for some reason MSBuild cant find the typescript compiler. I have the typescript compiler installed from the readme but I still get these errors when compiling.

No executable found matching command "tsc" - Microsoft.DotNet.Common.Targets

for both the ChatSample and SocketsSample

**Comment by AmitBhatnagar24** [comment]
Did you add it to your Path?

**Comment by moozzyk** [comment]
Is the tsc on the path? i.e. if you type tsc in the command line does it work?

**Comment by bigswede74** [comment]
The msbuild command prompt does not recognize tsc. Where do I add the path?

**Comment by moozzyk** [comment]
How did you install the compiler? If you are using node you can install it globally with `npm install -g typescript` and it will add tsc to the path.

**Comment by bigswede74** [comment]
I downloaded the installer in the readme file for the project and installed it from here.

https://www.microsoft.com/en-us/download/details.aspx?id=48593

**Comment by bigswede74** [comment]
I fixed the issue by adding "C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0" path to the PATH environment variable. You would think the Typescript installer would have added the path. Thanks for the help.
