### ISSUE TITLE
Android and IOS

### ISSUE THREAD

**Issue by FIVIL** [aspnet/SignalR#2206]
Hi, i was wondering if there will be any official clients provided by asp net core team for Java and Swift/ObjectiveC for using in Android or IOS??

**Comment by davidfowl** [comment]
We have plans to build an official java and android client, no plans for an official iOS client as yet. @moozzyk has been maintaining a Swift client for ASP.NET Core SignalR

**Comment by rfrancisco** [comment]
Does anyone know of any unofficial client i can use right now with Android? I looked at https://github.com/Gurgen/SignalR-.net-core-android-client but does not seem to work with RC1. Any pointers on what changed from Preview 2 to Rc1 that could break the client?

**Comment by anurse** [comment]
The ASP.NET Core 2.2 Roadmap was announced yesterday, see the Announcement repos for these kinds of updates: https://github.com/aspnet/Announcements/issues/307

A Java client (which will support Android) is on the roadmap for 2.2. A Swift client is not on the plans for 2.2, but is still in our queue.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
