### ISSUE TITLE
modifying property names when using message pack

### ISSUE THREAD

**Issue by guylando** [aspnet/SignalR#2211]
Is it possible and how can it be done?
In json it could be done using [JsonProperty(PropertyName = "T")] attribute

NOTE: The goal is to use shorter names in network while using long names in the code, to make messages sent shorter.

Tried to do as here: https://github.com/neuecc/MessagePack-CSharp/issues/2
using MessagePackObject attribute, but MessagePackObject attribute wasn't found in Microsoft.AspNetCore.SignalR.MsgPack nugget package.

**Comment by davidfowl** [comment]
The RTM version of the package was renamed to **Microsoft.AspNetCore.SignalR.Protocols.MessagePack** https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR.Protocols.MessagePack/1.0.0-rtm-30733

**Comment by guylando** [comment]
works, thanks
