### ISSUE TITLE
Returning named tuple results in item1, item2 etc.

### ISSUE THREAD

**Issue by AndrewNikolin** [aspnet/SignalR#2213]
### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: 1.0.0-preview2-final
* Versions of Client-Side NuGet/NPM Packages: 1.0.0-preview2-final
* Are you using the C# client or the JavaScript client: TypeScript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): IIS Express
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome

Trace said me that it is using WebSocket with JSON. The issue is that when returning a tuple from Hub method and invoking it like `this.hub.invoke(method, data).then(result => this.process(result.item1, result.item2));`
while I presume it should result in `result.MyValue1` in a case when hub's method return value is `(string MyValue1, Guid MyValue2)`

**Comment by anurse** [comment]
Named tuples aren't encoded as actual properties with names (see [this example](https://sharplab.io/#v2:D4AQDABCCMDcCwAoEBmK0BsUBM6DsEA3khKVGjFgBQCWAdgC4QBmA9qwDQQDKDATvQDmEAEYBDPgEp0ADirTiiMsogMAFn1YB3CHQCmOgHKsGASQC2ABwA2e83sZ6AJgFEAHgGM9lhjVZ15BCUyAF8kEKA==)), so the reflection APIs don't support it. We currently just look at the return type, and not any attributes. You'll have to either use `.item1`/etc. on the client or use a full `struct` or `class` for the return type on the client.

We'll consider adding support to this to a future version.

**Comment by davidfowl** [comment]
Well, TBH the serializer needs to add support for it, not SignalR.

**Comment by AndrewNikolin** [comment]
@davidfowl agree on that, but at the moment posting this I wasn't aware where the issue actually is.

**Comment by anurse** [comment]
Unfortunately we're limited by what the serializer can support. You can use JSON.NET custom converters to try and help here or use a custom struct.
