### ISSUE TITLE
Javascript client: The 'protocol' argument is required.

### ISSUE THREAD

**Issue by kortgat** [aspnet/SignalR#2218]
Versions of Server-Side NuGet Packages: 1.0.0-rc1-final
Versions of Client-Side NuGet/NPM Packages: installed from npm on 2018/05/07
Are you using the C# client or the JavaScript client: Javascript Client
The Server you are using: IIS Express/Azure Web App): 
The Operating System on the Server: Windows:
The Operating System on the Client: Windows
The Browser on the client, if using the JavaScript client: Chrome
IDE: Visual Studio 2017

I am struggling to get my client to connect, it was working fine and all of a sudden started throwing out the following in the console:
Utils.ts:12 Uncaught Error: The 'protocol' argument is required.
    at Function.Arg.isRequired (Utils.ts:12)
    at new HubConnection (HubConnection.ts:39)
    at (index):260

Any help will be appreciated.

**Comment by davidfowl** [comment]
Here's the new API:

```js
var connection = new signalR.HubConnectionBuilder()
    .withUrl("/chat")
    .build();
 
connection.on("send", data => {
    console.log(data);
});
 
connection.start()
    .then(() => connection.invoke("send", "Hello"));
```

**Comment by kortgat** [comment]
Thank you, I did not change the connection to the new HubConnectionBuilder after updating the client. it works now thank you.
