### ISSUE TITLE
WebRtc, sending MediaStream to .Net Core Api using signalR

### ISSUE THREAD

**Issue by ranouf** [aspnet/SignalR#2222]
Versions:
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-preview1-final" />
    "@aspnet/signalr": "1.0.0-preview1-final",
OS: Windows 10
Browser: Chrome v. Latest

TypeScript Code:

```
    navigator.mediaDevices.getUserMedia({ audio: true })
      .then(stream => {
        let _hubConnection = new HubConnection(this.apiUrl + '/webrtc');
        _hubConnection.send("SendStream", stream);
      })
      .catch(function (e) {
        console.error('getUserMedia() error: ' + e.message);
      });
```

C# Code:

```
public class WebRtcHub : Hub {
        public void SendStream(object o)
        {
               var stream = o as System.IO.Stream; // return null

        }
}
```

I put a debug point in SendStream in VisualStudio, I can see that I receive something, but I m not able to Cast it as a Stream.

From what I read on WebRtc documentation:
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling

In the situation where a client wants to stream to another client, they need ICE Server, STUN, RTCPeerConnection, concept that I dont really understant, but in my case, where I only want to stream from Client to Server, do I need that too? 

How Can I stream a MediaStream audio from WebRTC to a .net core API using signalR?

**Comment by anurse** [comment]
> In the situation where a client wants to stream to another client, they need ICE Server, STUN, RTCPeerConnection, concept that I dont really understant, but in my case, where I only want to stream from Client to Server, do I need that too?

You shouldn't need a STUN server if you're streaming from client to server.

> How Can I stream a MediaStream audio from WebRTC to a .net core API using signalR?

SignalR doesn't have anything built-in to support sending a WebRTC stream. You'd need to manually read the data out of the stream and send it up to a SignalR Hub Method as individual chunks. I don't know enough about the MediaStream API to know how to do that, so I'd suggest researching how to use those APIs to read audio/video data. It looks like you can use the [`AudioContext`](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext) API to read audio data from a MediaSource using JavaScript but as I said, we're not experts on that API.

**Comment by ranouf** [comment]
Thanks for this answer, I will take a look on how to do that.
