### ISSUE TITLE
UseHub is in the wrong namespace

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2225]
UseHub is in the Microsoft.AspNetCore.SignalR namespace and it should be in the Microsoft.AspNetCore.Connections namespace (matching the IConnectionBuilder namespace).

/cc @muratg @anurse

**Comment by muratg** [comment]
@davidfowl was this missed in the API review? Or was it contentious?

**Comment by muratg** [comment]
Please send the template

**Comment by davidfowl** [comment]
Missed in the API review

**Comment by anurse** [comment]
We should do this in RTM.

**Comment by anurse** [comment]
This would have to be an RTM fix, but it was declined by shiproom. Closing.

**Comment by davidfowl** [comment]
Lame... 😢
