### ISSUE TITLE
Can't transfer HttpMessageHandlerFactory to HubConnectionBuilder in new 1.0 RC

### ISSUE THREAD

**Issue by NektoDron** [aspnet/SignalR#2226]
I replaced the old code
``` C#
            m_hubConnection = new HubConnectionBuilder()
                              .WithUrl(uri).WithMessageHandler(h => handler).WithConsoleLogger()
                              .WithTransport(transportType).Build();
```

to this new one:
```C#
            m_hubConnection = new HubConnectionBuilder()
                              .WithUrl(uri, transportType, options =>
                                                               {
                                                                   options.HttpMessageHandlerFactory = h => handler;
                                                               }).Build();
```
When I try to call m_hubConnection.StartAsync() the Options.HttpMessageHandlerFactory  is null and connection to TestServer can't be established.

**Comment by mikaelm12** [comment]
This issue was fixed for RTM here: https://github.com/aspnet/SignalR/commit/6f6382799b00936521452cc6c5c516a5bb7f3ce8
So it has been fixed and will be available in the next release.

**Comment by mikaelm12** [comment]
A work around for now would be to pass in a string instead of a uri. That should work fine. There was just a small mistake in the API that took a Uri.

**Comment by anurse** [comment]
This has been fixed. Closing the bug.
