### ISSUE TITLE
Exception while loading assemblies: System.IO.FileNotFoundException => in Xamarin project

### ISSUE THREAD

**Issue by KaYLKann** [aspnet/SignalR#2227]
Hi! 
I got this error at compile time after adding microsoft.aspnetcore.signalr.core 1.0.0-rc1-final to my project.
The problem resolves after removing microsoft.aspnetcore.signalr.core 1.0.0-rc1-final but I was expecting to use it in the project.
```
> Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Perhaps it doesn't exist in the Mono for Android profile?
> Имя файла: 'System.Memory.dll'
>    в Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
>    в Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
>    в Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
>    в Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	MirtekConnection.Android	
```	
I am hope for your help.

![default](https://user-images.githubusercontent.com/10370241/39761773-a53d75b6-52e1-11e8-8ed1-633f0d21f9e4.png)
![default](https://user-images.githubusercontent.com/10370241/39761813-ba390a3e-52e1-11e8-9ec7-1b6a13f251af.png)

**Comment by anurse** [comment]
Xamarin does not yet support the `System.Memory` assembly that SignalR requires. The Xamarin team is actively working on fixing that though! We're tracking their work here: https://github.com/aspnet/SignalR/issues/1886

I'm going to close this issue so we can track this all in one place, but feel free to comment further here if you have questions!

**Comment by KaYLKann** [comment]
Thank you for your reply! I hope that this error will be corrected as soon as possible )))
