### ISSUE TITLE
Service Fabric-based backplanes

### ISSUE THREAD

**Issue by mkosieradzki** [aspnet/SignalR#223]
Please consider following use cases when designing pluggable backplane API:
- Stateful service-hosted hub with state backed by local Reliable Collections
- External generic stateful service designed to act as backplane (backed by Reliable Collections) + integration code
- optionally some actor based integration...

**Comment by muratg** [comment]
@DamianEdwards FYI.  Backlogging this.

**Comment by davidfowl** [comment]
We'll look at this after we do service bus and redis. We're very interested in doing this as it fits with the SF's stateful services.

**Comment by mkosieradzki** [comment]
I would like to elaborate on the first point:
It would be really nice to be able to span a hub across multiple replicas of the same single stateful service partition (between primary and multiple secondary replicas). In that case you can allow clients to connect to secondary replicas strongly improving scalability. It should be possible to use reliable collections API in that case.

**Comment by davidfowl** [comment]
Hubs themselves are stateless, so I'm assuming you mean usually scale out pluggability (in the new world it's a HubLifetimeManager see redis https://github.com/aspnet/SignalR/blob/ccf6cd415e7e79896ba6b47045ecc5a5f1474460/src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs). If not, can you elaborate on what you mean? The new model requires stickiness so you can't have connections bounce around between nodes and keep their connection state (if that's what you mean).

**Comment by mkosieradzki** [comment]
@davidfowl Yes, I mean the scale out pluggability.

Thanks for mentioning the stickiness requirement.

This stickiness requirement may or may not be difficult in terms of typical Service Fabric implementations:
- For websockets it should be trivial and out of the box.
- For other protocols it can be really challenging because it will put some strong requirements on the reverse proxy implementation. So basically there will be a requirement for stickiness here.

The architecture for that case is a follows
Client -> <internet> -> <L4 load balancer> -> Service Fabric Stateless Service (MyReverseProxy) (one of stateless instances) -> Service Fabric Stateful Service replica (MyService) (primary or one of secondaries)

1. Hubs in replicas can use reliable collections for scale out (those collections are accessible for all the replicas and even have notifications)
2. Now we need to make sure MyReverseProxy guarantees stickiness.

So there will be some requirements for service resolution logic in MyReverseProxy that as long specific replica is accessible all messages will be routed to the specific replica, that also means that stateless service will require to maintain some kind SHARED resolution cache (or use some kind of cookies).

My basic design plan for similar case was to limit protocols to web-sockets only. This establishes a quite-sticky channel from client to single replica (hub instance) with lifetime bounded by: web sockets connection stability, MyReverseProxy instance lifetime, MyService replica lifetime. What would be definitely good enough.

However when we can add some support in MyReverseProxy for cookies. For example we can store service resolution result in cookies (in a secure way). In that case we would be able to achieve even better lifetime because it would be bound to MyService replica lifetime only - what is an optimal lifetime - because it is exactly the same as hub lifetime.

**Comment by grahamehorner** [comment]
@davidfowl @mkosieradzki do you envision a Service Fabric back plan using the stateless reliable actor model for hubs/group/users/connections & events?

**Comment by Expecho** [comment]
It has been a while. Is this still on the backlog somewhere? Any news?

**Comment by davidfowl** [comment]
We have no plans on doing this. I'll close the issue.

**Comment by Expecho** [comment]
Ok. is due to too many complex factors in play using Service Fabric or is it a lack of time decision? Are there any docs on how to write a backplane?  Just wondering if it makes sense to try create it myself somehow.

**Comment by anurse** [comment]
A little of both, to be honest :). There aren't docs about writing backplanes, but all you need to do is provide an implementation of `HubLifetimeManager<T>` and put it in the DI container. So you'd create `ServiceFabricHubLifetimeManager<T>` which inherits from` HubLifetimeManager<T>` and implement the methods. You can use the existing [RedisHubLifetimeManager](https://github.com/aspnet/SignalR/blob/b86f31d58c5727d0d6f4c0a1c3ca6533ba9ec087/src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs) as a reference. We're also working on building a test suite for backplane implementations.

**Comment by anurse** [comment]
To be clear, at this time we're not looking to add more built-in backplanes, so I don't think we're prepared to take this as a PR to this repo. But it's certainly something that can live as a community-maintained extension package!

If you decide to start a project up, please feel free to reach out to us for help (feel free to tag me in GitHub issues/PRs on your repo to take a look at things). I can't guarantee we'll always be able to respond immediately but we'll do our best to help out!

**Comment by Expecho** [comment]
Ok, thanks for the heads up and the great info!

**Comment by jseekamp** [comment]
@Expecho Did you ever end up with a solution to this?

**Comment by Expecho** [comment]
@jseekamp  No, sorry. The project I was working on was cancelled so I did not need it anymore.
