### ISSUE TITLE
Can't use new Signalr 2.1.0 RC1 C# Client with Mono

### ISSUE THREAD

**Issue by metaduckling** [aspnet/SignalR#2232]
I am trying to use signalr 2.1.0-RC1 C# client on Mono (Unity 2018.1 especially). Unity uses Mono equivalent of .NET 4.6 with .NET Standard 2.0 api compatibility. When I call connection.StartAsync() following error occurs:

`System.NotImplementedException: The method or operation is not implemented.
  at System.Net.Http.HttpClientHandler.get_ClientCertificates () [0x00000] in <20a8f293e89843148f03a963627efba4>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.CreateHttpClient () [0x0005c] in <dd40c651eaf14486a531dbb173fa57e1>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection..ctor (Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions httpConnectionOptions, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory) [0x00080] in <dd40c651eaf14486a531dbb173fa57e1>:0 
  at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory+<ConnectAsync>d__3.MoveNext () [0x00011] in <2d5fd7ae71414f799c1b2fb768dded77>:0 
--- End of stack trace from previous location where exception was thrown ---  `

I guess this is a certificates issue. Can you fix this problem, or make the usage of certificates optional?

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages:
Microsoft.AspNetCore.SignalR 1.0.0-rc1-final

* Versions of Client-Side NuGet/NPM Packages:
Microsoft.AspNetCore.SignalR.Client 1.0.0-rc1-final

* Are you using the C# client or the JavaScript client:
C# client

* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
IIS Express

* The Operating System on the Server (Windows/Linux/macOS):
Windows 10 Pro

* The Operating System on the Client (Windows/Linux/macOS):
Windows 10 Pro

**Comment by davidfowl** [comment]
Wow that's super unfortunate.

> I guess this is a certificates issue. Can you fix this problem, or make the usage of certificates optional?

The issue should be fixed in mono. I suggest filing an issue on https://github.com/mono/mono and make sure you're using the latest mono version.

We'll see what we can do in the short term until then, this might just be the tip of the ice berg for issues to be found with mono.

**Comment by MiKom** [comment]
It seems that the issue here is mono's lacking conformance to netstandard. Does Microsoft keep eye on that somehow? It's unfortunate, that there's this kind of fragmentation.

**Comment by dasuma** [comment]
any solution ?

**Comment by anurse** [comment]
We've submitted https://github.com/aspnet/SignalR/pull/2270 to fix this issue.

**Comment by anurse** [comment]
This will be fixed in the upcoming release. https://github.com/aspnet/SignalR/commit/2388dd3a764b2000539c5984be817d76d8324a6e
