### ISSUE TITLE
messagepack is not supported

### ISSUE THREAD

**Issue by Jon-Murray** [aspnet/SignalR#2235]
Hi guys,

   First off, i'm sorry for opening an issue about this, but hopefully it will help people testing stuff out in the future. I've just upgraded to coreapp 2.1 RC1 for everything in a small project i use to test out SignalR every now and again. I've previously had messagepack working fine, with old code. However, updating the new libraries seem to give me the error "Trace: (WebSockets transport) data received: {"error":"The protocol 'messagepack' is not supported."}". This was also throwing a "version" error, until i went and hardcoded that as it did not seem to find/pass the version string. Building the connection with the hub connection builder gives "signalr-client.min.js:15 Error: Connection disconnected with error 'Error: Server returned handshake error: The protocol 'messagepack' is not supported.'.". Both work absolutely fine when in JSON.

Are there any examples of the server configuration in use for messagepack? I can't seem to find anything in startup/options where i can add support for messagepack to signalr, everything defaults down to JSON only.

Thanks!

**Comment by BrennanConroy** [comment]
>Are there any examples of the server configuration in use for messagepack?

https://github.com/aspnet/SignalR/blob/dev/samples/SignalRSamples/Startup.cs#L26

**Comment by Jon-Murray** [comment]
Wow. Now i feel silly. Was a reference error on my part, not including the messagepack SignalR project in my main app. Thanks Brennan for the quick reply!
