### ISSUE TITLE
Javascript client not compatible with Asp.Net Web API servers ? 

### ISSUE THREAD

**Issue by poppein** [aspnet/SignalR#2236]
Hi,

I'm using the js client package @aspnet/signalr (1.0.0-rc1-update1) in a react application in order to try to communicate with a SignalR server hosted in a Web API (using .Net Framework 4.5.2 and Microsoft.AspNet.SignalR 2.2.3 package). I managed to communicate with the server successfully with a C# client but had no luck so far with a JS client. 

This is the code i'm using on the client side :
```
componentDidMount() {
        var connection = new SignalR.HubConnectionBuilder().withUrl('https://localhost:44322/signalr').configureLogging(SignalR.LogLevel.Trace).build();
        connection.on('receiveTask', data => {
            console.log(data);
        });
        connection.start()
            .then(() => console.log('Started !'))
            .catch(err => console.error(err));
    }

```
And on the server side : 

```
public class TaskNotificationHub : Hub
    {
        public void Send(string message)
        {
            Clients.All.receiveTask(message);
        }
    }
```

I always receive the same error, thrown when connecting : 

> Root.jsx:38 TypeError: Cannot read property 'length' of undefined
>     at HttpConnection.<anonymous> (HttpConnection.js:261)
>     at step (HttpConnection.js:33)
>     at Object.next (HttpConnection.js:14)
>     at HttpConnection.js:8
>     at new Promise (<anonymous>)
>     at ./node_modules/@aspnet/signalr/dist/esm/HttpConnection.js.__awaiter (HttpConnection.js:4)
>     at HttpConnection../node_modules/@aspnet/signalr/dist/esm/HttpConnection.js.HttpConnection.createTransport (HttpConnection.js:240)
>     at HttpConnection.<anonymous> (HttpConnection.js:174)
>     at step (HttpConnection.js:33)
>     at Object.next (HttpConnection.js:14)

So i was actually wondering if this is due to the client library only being compatible with .Net Core servers or if this is coming from something else ?

Thanks !

**Comment by BrennanConroy** [comment]
ASP.NET SignalR is not compatible with ASP.NET Core SignalR

**Comment by anurse** [comment]
Closing this as per @BrennanConroy 's comment. The ASP.NET Core SignalR libraries are not compatible with ASP.NET SignalR.

**Comment by poppein** [comment]
@BrennanConroy Thanks for the input, that's what i thought. Do you know if there's a JS client package for ASP.NET SignalR like there's one for the .Net Core version ?

**Comment by anurse** [comment]
https://www.npmjs.com/package/signalr is compatible with ASP.NET SignalR. Note the lack of `@aspnet/` prefix.

**Comment by kotpal** [comment]
Why can't you people add @aspnetcore instead of @aspnet ?

**Comment by AChrsitensen70** [comment]
Is there any good example of implementing https://www.npmjs.com/package/signalr  in and angular 5 client? Struggling to find any documentation, everything seems to be outdated or going towards the core package.
