### ISSUE TITLE
Closing one tab/connection kills notifications to a user using user id when the user have multiple connections from different tabs/browsers. Redis backplane

### ISSUE THREAD

**Issue by Boychenko** [aspnet/SignalR#2243]
Hi
I've found an issue with `Microsoft.AspNetCore.SignalR.Redis` as backplane.

Environment:
Microsoft.AspNetCore.SignalR: 1.0.0-rc1-final
Microsoft.AspNetCore.SignalR.Redis: 1.0.0-rc1-final
Javascript js file: 1.0.0-rc1-update1
Server: Kestrel / IIS
OS on server and client: Windows 10
Browser: Firefox (latest) and Chrome (latest)

Step to reproduce:
1 Open two tabs with the same user logged in
2 Close one tab

Expected: The app in the existing tab should be able to get notifications using user id
Actual: No notifications sent using user id delivered to this user anymore.

I made some research. There are my finding
* Everything works fine if I don't use Redis as a backplane.
* According to my understanding [unsubscribe](https://github.com/aspnet/SignalR/blob/6f6382799b00936521452cc6c5c516a5bb7f3ce8/src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs#L87) causing the problem. While it works fine for connection subscriptions because i'st closed anyway. For user subscriptions this is wrong. A user can have more than one connection to the same server.

**Comment by Boychenko** [comment]
There is a [repository](https://github.com/Boychenko/SignalR.Redis_issue_sample/) with minimal app to reproduce.

**Comment by anurse** [comment]
I've verified that this occurs. I'm working on a fix. We'll post back here with more information on scheduling/private builds/etc.

One thing you could try as a workaround (I realize it's not ideal) is using Groups instead of Users here. You have to manually manage the group, but it should not have this issue. We're going to look at fixing this issue properly, but until we have the fix released you could use that as a temporary workaround.

**Comment by davidfowl** [comment]
The workaround would look like this:

```C#
public override Task OnConnectedAsync()
{
    Groups.AddToGroupAsync(Context.ConnectionId, "u-" + Context.UserIdentifier);
     return base.OnConnectedAsync();
}
```
Then you can use `Group("u" + userId)` to invoke instead of `User`. The u prefix is to avoid conflicting with group names.

**Comment by Boychenko** [comment]
@anurse @davidfowl Thanks!
@davidfowl, workaround works fine. But I've improved it a bit.
```
public override Task OnConnectedAsync()
{
     return base.OnConnectedAsync();
    Groups.AddToGroupAsync(Context.ConnectionId, "u-" + Context.UserIdentifier);
}
```
It should be a bit more efficient because of [this](https://github.com/aspnet/SignalR/blob/f005e80b14055a4ca629a17413c4c8647ccf70a5/src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs#L179). Is it correct?

**Comment by davidfowl** [comment]
Ah yes, doing it after is better. Nice catch

**Comment by anurse** [comment]
PR: #2273

**Comment by Boychenko** [comment]
It's not related to that issue itself. I can open another issue but I hope I just doing something silly.
I just checked sources and wanted to run tests. Visual Studio 15.7 Windows 10. Test don't run.
Steps I did
1 `build.cmd`
2 updated [path](https://github.com/aspnet/Home/wiki/Building-from-source)
3 I can open and build a solution in VS but test just don't run
```
[5/16/2018 12:07:47 AM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-rtm-26502-02' was not found.
  - Check application dependencies and target a framework version installed at:
      c:\Users\Alex\.dotnet\x64\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.0-rc2-3002702 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.5 at [c:\Users\Alex\.dotnet\x64\shared\Microsoft.NETCore.App]
      2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.0-rc1 at [c:\Users\Alex\.dotnet\x64\shared\Microsoft.NETCore.App]
      2.1.0-rc1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by anurse** [comment]
This isn't related to the issue. Please file a new issue.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/aspnet/SignalR/commit/95f543848ce04260fda1f97b06e4588bf79898f1
