### ISSUE TITLE
AzureSignalR + Disconnects  & No Messages

### ISSUE THREAD

**Issue by bsampica** [aspnet/SignalR#2244]
I recently implemented the Azure backplane support that was recently released for Microsoft.AspNetCore 2.0.  When connecting using the new HubConnectionBuilder() the connection creates and connects fine, but after some time, will disconnect.

I'm also not receiving any messages from the SignalR server side at all.

**Server ASP.NET Core WebAPI hosted in Visual Studio 2017**  
```
Microsoft.AspNetCore: 2.0
Microsoft.AspNetCore.SignalR : 1.0.0-rc1-final 
Microsoft.Azure.SignalR : 1.0.0-preview1-10009
```

Server side errors I'm seeing a lot of problems with Exceptions related to writing after the writer is closed, and reading after the reader is closed.  When I inspect the dashboard for the Azure SignalR service I do see traffic going through, though I only know their "message count" it shows on the graph, no other important information like delivery.

**Client - Angular 5 Web Application** 
`@aspnet/signalr typescript via NPM  : 1.0.0-rc1-update1 `

`System.InvalidOperationException: Can't advance past buffer size.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AdvancingPastBufferSize()
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.Advance(Int32 bytes)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.<StartReceiving>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnection.<ProcessIncomingAsync>d__27.MoveNext()`

`System.InvalidOperationException: No reading operation to complete.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadToComplete()
   at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at Microsoft.Azure.SignalR.ServiceConnection.<ProcessIncomingAsync>d__27.MoveNext()`

**On the client, here's the trace:**
`Debug: Starting HubConnection.
Utils.js:192 Debug: Starting connection with transfer format 'Text'.
Utils.js:192 Debug: Sending negotiation request: http://192.168.1.153:45455/signalr/livevalues/negotiate?token=removed
Debug: Sending negotiation request: https://removed.service.signalr.net:5001/client/negotiate?hub=livevalueshub
Debug: Selecting transport 'WebSockets'
Utils.js:192 Trace: (WebSockets transport) Connecting
Utils.js:188 Information: WebSocket connected to wss://controlcenter.service.signalr.net:5001/client/?hub=livevalueshub&id=l0NKkhlpJsAE6f8zxVc0hA&access_token=removed
Utils.js:192 Debug: Sending handshake request.
Utils.js:192 Trace: (WebSockets transport) sending data. String data of length 32.
Utils.js:188 Information: Using HubProtocol 'json'.
signalr.service.ts:84 ConnectionState For livevalues {status: 2}
Utils.js:192 Trace: (WebSockets transport) socket closed.
Utils.js:182 Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.`

**Comment by davidfowl** [comment]
Why are you using ASP.NET Core 2.0 instead of 2.1?

**Comment by bsampica** [comment]
Upgrading to the latest @aspnet/signalr package using the registry: 

@aspnet:registry=https://dotnet.myget.org/f/aspnetcore-dev/npm/

Did not solve the issue.  If I remove the AzureSignalR entries on my server, these messages go away.  Because I receive no messages during the time I'm supposedly "connected" which can be 40 to 12- seconds - I'm assuming that I'm not actually making a connection to the azure SignalR Hub, so it's bailing and dumping me...?

**Comment by bsampica** [comment]
I just updated the project to .NET Core 2.1

`<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-final" />`

Before I was using .NET core 2.0 - the result is the same either way.

**Comment by davidfowl** [comment]
So I should be a bit clearer here. SignalR depends on ASP.NET Core 2.1 (which is .NET standard 2.0). Then there’s .NET Core 2.1 which ships with ASP.NET Core 2.1. 

It seems like you’re trying to update an existing project to use .NET Core 2.0. Can you show your entire csproj?

All that said, it looks like there is a bug here and we think it only occurs when running on .NET Core 2.0 (which is why I’m asking).

**Comment by bsampica** [comment]
Just a little bit of background.  We've successfully been running the .NET Core Version of SignalR in this project for some time now:  this only started occurring when we included the AzureSignalR portions that were released a day or two ago:  

Here's my .csproj

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <StartupObject />
    <UserSecretsId>bce27350-244e-4b48-b7f1-64f17197977c</UserSecretsId>
    <ApplicationInsightsResourceId>/subscriptions/a8372c37-88f6-445f-b90e-3c9516c7a15a/resourcegroups/ControlTech-Resources/providers/microsoft.insights/components/webapp-metrics</ApplicationInsightsResourceId>
    <ApplicationInsightsAnnotationResourceId>/subscriptions/a8372c37-88f6-445f-b90e-3c9516c7a15a/resourcegroups/ControlTech-Resources/providers/microsoft.insights/components/webapp-metrics</ApplicationInsightsAnnotationResourceId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNet.Security.OAuth.Introspection" Version="2.0.0-rc3-0300" />
    <PackageReference Include="AspNet.Security.OAuth.Validation" Version="2.0.0-rc3-0300" />
    <PackageReference Include="AutoMapper" Version="7.0.0-alpha-0001" />
    <PackageReference Include="AutoMapper.Collection" Version="3.1.3" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="3.2.0" />
    <PackageReference Include="FluentValidation" Version="7.6.0-preview1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="7.6.0-preview1" />
    <PackageReference Include="HangFire" Version="1.7.0-beta1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.3.0-beta2" />
    <PackageReference Include="Microsoft.ApplicationInsights.SnapshotCollector" Version="1.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-rc1-final" />
    <PackageReference Include="Microsoft.Azure.NotificationHubs" Version="2.0.0-preview2" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.0.0-preview1-10009" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0-rc1-final" />
    <PackageReference Include="MQTTnet" Version="2.8.0-alpha1" />
    <PackageReference Include="MQTTnet.AspNetCore" Version="2.7.5" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <PackageReference Include="OpenIddict" Version="2.0.0-rc3-0958" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="2.0.0-rc3-0958" />
    <PackageReference Include="OpenIddict.Mvc" Version="2.0.0-rc3-0958" />
    <PackageReference Include="protobuf-net" Version="2.3.7" />
    <PackageReference Include="Sendgrid" Version="9.9.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-dev001285" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="2.4.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.1.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.1.0-preview1-final" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>
  
  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="FlightLine.pfx" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="FlightLine.pfx" />
  </ItemGroup>
  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JSONSchema="" /></VisualStudio></ProjectExtensions>
</Project>
`

**Comment by davidfowl** [comment]
Thanks! Can you reproduce this every time? We would love to debug your app.

**Comment by bsampica** [comment]
Yes, I absolutely can recreate this every single time...whats the best way to go about having you debug this?

**Comment by bsampica** [comment]
I’m game.  Can use Skype or slack, or teamviewer.

On May 10, 2018, at 6:21 PM, David Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm live share might be interesting

**Comment by davidfowl** [comment]
@bsampica ping me on https://gitter.im/aspnet/SignalR

**Comment by bsampica** [comment]
I'm receiving a completly different message this morning:  
```
System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
ControlCenterApi>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
ControlCenterApi>    --- End of inner exception stack trace ---
ControlCenterApi>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
ControlCenterApi>    at System.Threading.Tasks.ValueTask`1.get_Result()
ControlCenterApi>    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
ControlCenterApi>    at System.Threading.Tasks.ValueTask`1.get_Result()
ControlCenterApi>    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
ControlCenterApi>    at System.Threading.Tasks.ValueTask`1.get_Result()
ControlCenterApi>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
ControlCenterApi>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
ControlCenterApi>    at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
ControlCenterApi>    at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
ControlCenterApi>    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
ControlCenterApi>    at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat)
ControlCenterApi>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat)
ControlCenterApi>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat)
ControlCenterApi>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat)
ControlCenterApi>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
ControlCenterApi>    at Microsoft.Azure.SignalR.ServiceHubDispatcher`1.ConnectAsync(TransferFormat transferFormat, String connectionId, CancellationToken cancellationToken)
ControlCenterApi>    at Microsoft.Azure.SignalR.ServiceHubDispatcher`1.ConnectAsync(TransferFormat transferFormat, String connectionId, CancellationToken cancellationToken)
ControlCenterApi>    at Microsoft.Azure.SignalR.ServiceConnection.StartAsyncCore()
```

**Comment by bsampica** [comment]
Quick Update:  I removed the AspNetCore.SignalR package, the demo projects only include the Azure SignalR package - that got me back to where I can connect, but the client will disconnect after a certain amount of time.

The server errors are before:  Pipe / Reader / Writer exceptions.
The client error is:
```
Utils.js:182 Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.
```

**Comment by davidfowl** [comment]
> The server errors are before: Pipe / Reader / Writer exceptions.

Do you mean, you're getting the same errors you got before? Specifically I'm interested to know if you're still seeing this exception:

```
System.InvalidOperationException: Can't advance past buffer size. at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AdvancingPastBufferSize() at System.IO.Pipelines.Pipe.DefaultPipeWriter.Advance(Int32 bytes) at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.<StartReceiving>d__20.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.IO.Pipelines.PipeCompletion.ThrowLatchedException() at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result) at System.IO.Pipelines.Pipe.GetReadAsyncResult() at Microsoft.Azure.SignalR.ServiceConnection.<ProcessIncomingAsync>d__27.MoveNext()
```

Is your application hosted in Azure or can you reproduce the issue when running locally as well? 

Are those exception messages coming from logs or somewhere else?

**Comment by davidfowl** [comment]
Good, it means it should be simple to figure out. I'm in gitter right now

**Comment by davidfowl** [comment]
Confirmed this is a SignalR Azure SDK problem, moving the issue here https://github.com/Azure/azure-signalr/.
