### ISSUE TITLE
SignalR Demo Getting SignalR is not defined

### ISSUE THREAD

**Issue by Kriegthor23** [aspnet/SignalR#2248]
So I am trying to make SignalR Demo that Windows provided on its website (https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio)
and taking the EXACT steps in the guideline 
the only step that i differ from the guide is one line of npm code 
to be exact i will write down the line that i differ below 
(the npm line that guide uses 
  npm init -y
  npm install @aspnet/signalr)
(and what i used instead since V1.0 did not worked properly for me
npm init -y
npm i signalr)

I am using Visual Studio 2017 in Windows 10 with IIS Express 

<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview1-final" />
<PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.1.0-preview1-final" />
for package info 

For browser it is 
Chrome 66.0.3359.139 official  (64 bit) 

and for Error that i am getting 

![image](https://user-images.githubusercontent.com/39078682/39909356-1c2ebc6e-54fb-11e8-980c-68bb377224f6.png)

so this is my issue im a newbie in git hub so if i did anything wrong or posted this on wrong issue tracker i appologize in advance 
if you need any more info that i missed to give please say so i would be more than happyto give more details to you to find the solution 

thanks for your help and being patient to a newbie in advance

**Comment by davidfowl** [comment]
The best way to get help is to share the application that is failing.

**Comment by Kriegthor23** [comment]
@davidfowl ok so i am getting help from the author directy i will post the codes of the applicaion but the thing is the demo in the link is actually the application for now i will continue to develope on it and much more but for now the base

 is that SignalR demo that provided in the link 

So here i go

https://gist.github.com/Kriegthor23/17f06deeea4f5aa5a4dfb0d9190971c1

you can find all of the codes that i use in the gist link 
as i mentioned it is the exact copy paste of the demo in the link changed only name of the project 
and if i gave missing information i can complete it if you say what is missing.

ty for replying immediately 
and ty for further helps in advace

**Comment by davidfowl** [comment]
Ah the bug looks simple, you're using the wrong signalr javascript library. It's using the older jquery.SignalR when it should be using this one https://www.npmjs.com/package/@aspnet/signalr . You can use something like this:

https://github.com/davidfowl/build2018talk/blob/f528662f95dce79a979ee94e7b9bb4e6704685d6/demo1/wwwroot/index.html#L29

**Comment by Kriegthor23** [comment]
yeap you are right i got the wrong version thank a lot for the helping
now i have to find a way to get rid of the conectivity problem now 
![image](https://user-images.githubusercontent.com/39078682/39910780-74498c70-5501-11e8-93a3-6015bc3b862f.png)

in to the depths of searchig again but thanks for help @davidfowl

**Comment by davidfowl** [comment]
That error usually happens when you have different versions on the server and client. So now you're probably using rc1 on the client and a much older version on the server side.

**Comment by Kriegthor23** [comment]
thanks for the tip @davidfowl and by the way thanks for giving us SignalR i will contşnue to watch over your repository in git hub and your demos as well. have much to learn

**Comment by anurse** [comment]
@Kriegthor23 did aligning the versions fix your issue?
