### ISSUE TITLE
Native winforms client using core does not connect

### ISSUE THREAD

**Issue by ThisGaryOverHere** [aspnet/SignalR#2250]
When prototyping with the new release candidate SignalR for .net Core. 

Server  (core hub .NET Core 2.1)
Client (.Net Framework 4.6.1)

The native winforms client (based on the Winforms Chat example) does not connect. 

The error on connection is "The server disconnected before the handshake was completed"

**However** changing the client SignalR version to the older 1.0.0-preview2-final client version however seems to connect and work very well with the RC version on the server.

**Comment by davidfowl** [comment]
Can you share a repro project?

**Comment by ThisGaryOverHere** [comment]
Sorry it is not possible to provide the code.

The code is slight edits on the two chat examples.

The client code is mild edits based on this (just enough to get it compiling with the different versions)
SignalR-samples-master\SignalR-samples-master\WindowsFormsSample

And the hub code is from here
https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/

**Comment by davidfowl** [comment]
@ThisGaryOverHere I just updated the sample to the latest rc1 and it works. Take a look again to see if that fixes things.

**Comment by ThisGaryOverHere** [comment]
Could you send me your working client code please?

If I update the client example to the RC version then I get the Handshake error.
 "fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]      Failed connection handshake."

**Comment by mikaelm12** [comment]
Here's the sample client code using the rc1 bits https://github.com/aspnet/SignalR-samples/tree/master/WindowsFormsSample/WindowsFormsSample

**Comment by ThisGaryOverHere** [comment]
Thanks!   This works fine now.

Looking back at my version of the Winforms client, the code was much the same (additional parameter on the sends) as your working version but it still didn't work. Then I uninstalled the SignalR binary and re-added it and now it works.  So I am assuming that it is an issue updating from the 1.0.0-preview2-final up to the RC version without uninstalling?

However trying to recreate this I now get the handshake error with the Preview version but moving forward to the RC version I get working connection code.  So this is a NuGet oddity maybe? 

Thanks for your help with this.

**Comment by mikaelm12** [comment]
@ThisGaryOverHere Glad you got it working!
