### ISSUE TITLE
Best practices when deploying to production in AWS

### ISSUE THREAD

**Issue by rfrancisco** [aspnet/SignalR#2252]
Is there any documentation available with best practices when deploying to a production environment in AWS using Application Load Balancer in front of multiple signar (rc1) servers?

Also, our components have signalr hosted in kestrel. Is it still recommended that we put an nginx in front of them?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
