### ISSUE TITLE
Angular SignalR, constructor is private

### ISSUE THREAD

**Issue by ranouf** [aspnet/SignalR#2253]
Hi,

I m using an Asp.NetCore Api with
https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR/1.0.0-rc1-final

And Angular App with
https://www.npmjs.com/package/@aspnet/signalr/v/1.0.0-rc1-update1

When I try to Instance a new HubConnection as I did in the past, I Have a compilation error because the Constructor is now private.

It s important for me to configure to which url HubConnection need to connect.

How to instanciate it now?

**Comment by mikaelm12** [comment]
You can now use a HubConnectionBuilder to configure and instantiate your HubConnection in javascript like so
https://github.com/aspnet/SignalR/blob/023e61495f1ab2bd59efc6d3582f59d46f6fdcbf/samples/SignalRSamples/wwwroot/hubs.html#L148-L152

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.

**Comment by RezaRahmati** [comment]
How we should import signalR in Angular2+

this way doesn't work
`import { signalR } from '@aspnet/signalr';`
