### ISSUE TITLE
JSON.Parse issues in JsonHubProtocol.js that look like overlapping frames

### ISSUE THREAD

**Issue by codecadwallader** [aspnet/SignalR#2255]
We're seeing an issue where in the middle of a package payload, we see another package payload interrupting the JSON.  This surfaces in the JsonHubProtocol.js with the line `var parsedMessage = JSON.parse(message);` where is looks like malformed JSON because of the overlapping frames.

Strangely, the corruption seems to happen at the exact same location each time you repeat a specific operation.  It happens at a different location across different operations (sometimes after 100KB, sometimes after 900KB).  I do not believe it is related to special/unicode characters.  I have several example JSON payloads extracted via Chrome debugger by capturing the 'message' that threw the error and saving it to a JSON file.  Visual Studio Code formatted the files just to make it easier to see where the exception occurs.  Sometimes the interruption happens during a JSON key, sometimes the interruption happens during a JSON value.  Sometimes the interruption is by a "type 3" message and sometimes it is by a "type 1" message.

This system was using the .NET Framework version of SignalR for the last year and was recently upgraded to the .NET Core version which is when we began seeing these errors.

Thank you for your help and please let me know what other information I can provide!

* Versions of Server-Side NuGet Packages: Microsoft.AspNet.SignalR v1.0.0-rc1-final
* Versions of Client-Side NuGet/NPM Packages: @aspnet/signalr@1.0.0-rc1-update1
* Are you using the C# client or the JavaScript client: JavaScript client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Azure Web App, but also reproducible in IIS Express locally
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): FireFox, Chrome

Network Trace: https://gist.github.com/codecadwallader/e499e867e89fe405d942833a51946491

Client log: https://gist.github.com/codecadwallader/d2c90a8ac3daaa2109baadfd4fde310c
Server log: https://gist.github.com/codecadwallader/75e2d242332f46520bc19124a3df3f1d

JSON payloads: 
[SignalR_CorruptJSONPayloads.zip](https://github.com/aspnet/SignalR/files/1996034/SignalR_CorruptJSONPayloads.zip)

**Comment by BrennanConroy** [comment]
Looks like you're hitting https://github.com/aspnet/SignalR/issues/2187 which will be fixed in the RTM build.

Also, it looks like we have a bug where if the hub protocol throws while writing, it will leave partial messages in the pipe and the next successful write will send the partial and current message. We should clean up the pipe buffer if this happens.

**Comment by davidfowl** [comment]
@codecadwallader you can try out a build from here:

https://github.com/aspnet/SignalR/issues/2187#issuecomment-387465397

@BrennanConroy can you file an issue for that?

**Comment by codecadwallader** [comment]
Thanks both, experimenting now..

**Comment by codecadwallader** [comment]
Yes indeed, the latest rtm build (30769) seems to resolve this issue.  Thank you for the quick responses!
