### ISSUE TITLE
If the HubProtocol throws while writing it can leave partial messages in the transport pipe which will get sent on the next successful write

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2257]
See: https://github.com/aspnet/SignalR/issues/2255#issuecomment-388415398

Because we pass the pipe directly to the HubProtocol it will start writing a message and if an error occurs then the pipe will have the unfinished message. The next write that comes in will start writing where the failed message left off and send both the partial and new message, which the client wont understand.

**Comment by anurse** [comment]
From discussions with @BrennanConroy last week, we think there isn't really a way we can solve this. Even if we could, the connection is in a broken state. We failed to send a message that the client may be expecting (it could be the completion message that would unblock the client's `Task`, for example). We should just Abort the whole connection in this case.
