### ISSUE TITLE
Client certificate not available to Authentication Handler.

### ISSUE THREAD

**Issue by abubakar-khaliq-avalara** [aspnet/SignalR#2259]
### Please include as much of the following as you can in your bug report
Packages:
microsoft.aspnetcore\2.1.0-rc1-final
microsoft.aspnetcore.authentication\2.1.0-rc1-final
microsoft.aspnetcore.signalr\1.0.0-rc1-final
microsoft.aspnetcore.signalr.client\1.0.0-rc1-final

*Using the C# client
*Using IIS Express
* Windows 10 for both server and client with Chrome browser

I am able to pass in ClientCertificates when creating connection. I have verified that certificate is valid. This is what the code looks like.

```
X509Store store = new X509Store(StoreLocation.LocalMachine);
store.Open(OpenFlags.ReadOnly);
var cert = store.Certificates.Find(X509FindType.FindBySubjectName, "test.mycert", true);
store.Close();
return new HubConnectionBuilder().WithUrl(uri, options => { options.ClientCertificates = cert; }).Build();
```

I have an AuthenticationHandler on server side. My Auth handler gets invoked correctly but ClientCertificate is always null in `Request.HttpContext.Connection`

```
	public class CustomAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
	{
		public CustomAuthenticationHandler(
			IOptionsMonitor<AuthenticationSchemeOptions> options,
			ILoggerFactory logger,
			UrlEncoder encoder,
			ISystemClock clock)
			: base(options, logger, encoder, clock)
		{
		}

		protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
		{
			// validate cert here. Cert never reaches here.
			// For now, dummy success.
			var claims = new[] { new Claim(ClaimTypes.Name, "valid") };
			var identity = new ClaimsIdentity(claims, Scheme.Name);
			var principal = new ClaimsPrincipal(identity);
			var ticket = new AuthenticationTicket(principal, Scheme.Name);
			return AuthenticateResult.Success(ticket);
		}
	}
```

This is what I have in my ConfigureServices. 

```
			services.AddAuthentication("Custom")
				.AddScheme<AuthenticationSchemeOptions, CustomAuthenticationHandler>("Custom", null);
			services.AddSignalR();
			services.AddMvcCore();
```

**Comment by abubakar-khaliq-avalara** [comment]
- I am not specifying a specific transport so I assume that it uses websockets. I am testing on windows machine. 

- You are right, it is a C# client, not the chrome browser.

- I am not sure I understand what do you mean by "where are you applying auth". I was assuming that my auth handler (HandleAuthenticateAsync) would invoke whenever a client connects to hub. Handler gets invoked correctly, on any connection. But I could not get anything in `cer = await Request.HttpContext.Connection.GetClientCertificateAsync();` or `cert = Request.HttpContext.Connection.ClientCertificate`

**Comment by abubakar-khaliq-avalara** [comment]
Thanks a lot for responding. Couple of things.
When I follow instructions to configure IISExpress as mentioned in article, `SslNegotiateCert` is the only value that I can use for sslFlags. If I try to use Ssl and SslRequireCert, I cannot even start debugging. It throws 403 saying it cannot start dotnet.exe. With just negotiate cert in there, I still have the issue of client cert not reaching server.
Also, though I am debugging on Windows, our hubs are going to be hosted in unix environment, behind haproxy. However, for now, issue is that I cannot even get it working when everything is on same windows machine.

**Comment by Tratcher** [comment]
VS has some known issues debugging apps that require client certs. Can you start the app without debugging (CTL+F5)?

@BillHiebert

**Comment by JamesNK** [comment]
Random question: Are your client certs trusted?

**Comment by abubakar-khaliq-avalara** [comment]
@JamesNK yes, certs are trusted. 
@BillHiebert yes, it runs without debug. I need to figure out a better way to check if cert is getting to server (as I am not debugging).

**Comment by Tratcher** [comment]
You can attach the debugger to dotnet.exe after the site launches.

**Comment by abubakar-khaliq-avalara** [comment]
@Tratcher I'll try and report back on that.

**Comment by abubakar-khaliq-avalara** [comment]
@Tratcher I was wrong when I said that ctrl+F5 worked. In fact, if I have Ssl and SslRequireCert in config, it just doesn't work. There is no dotnet.exe in processes. So I am assuming that it fails to start the same way it fails while debugging. I have verified that if I remove both values from config (and leave SslNegotiateCert in) it starts and I can see dotnet.exe. In that case, however, it starts fine with debugger as well. Client certificate does not get to server though.

**Comment by Tratcher** [comment]
You need to launch the browser and access the site before dotnet.exe will be started. That's what VS is trying to do when it fails due to the client cert requirement.

**Comment by abubakar-khaliq-avalara** [comment]
@Tratcher I have verified that if I hit the website through browser, it asks for cert and if I secify correct cert it reaches server. However, when I run my C# client (as mentioned in OP) cert is still not reaching to server. Not sure if this is a SignalR issue or AspNetCore issue. 
At this point, we are thinking of abandoning this route (taking more than desired time) and move to some other way of authentication (possibly Jwt token). However, if there is any updates along the lines of certificates, please keep us posted.

**Comment by Tratcher** [comment]
If it works with IIS Express then it's not a AspNetCore or SignalR issue, it's a client issue. Is it the same certificate you're trying to use in both cases? The server will automatically advertise which cert issuers it will accept certs from and the client won't bother unless it has a match.

**Comment by anurse** [comment]
@abubakar-khaliq-avalara are you still having problems here? I want to make sure the status of this doesn't get lost in the backlog.

If you are still seeing the issue when using the C# client, could you try collecting client logs and a Fiddler network trace (from the Client) as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) ?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
