### ISSUE TITLE
.NET 4.5.x support

### ISSUE THREAD

**Issue by cruikshj** [aspnet/SignalR#226]
Is there a plan to support .NET 4.5.x with the SignalR ASP.NET Core packages?

I noticed the latest NuGet package (**1.0.0-preview1-23543**) available in the dev-ci feed targets .NET standard 1.3 only (which I am pretty sure means .NET 4.6 at a minimum).   I understand that this is under active development and expect things to be in flux (obviously, since I am pulling from a dev-ci feed).  But I am curious if this is the expectation going forward.  I would normally simply upgrade my application to 4.6.x and go on with my day, but doing so causes other problems (specifically around OIDC authentication).  

Thanks

**Comment by davidfowl** [comment]
> Is there a plan to support .NET 4.5.x with the SignalR ASP.NET Core packages?

No. Especially not on the server side. On the client, we might need to be a little more lenient but we're going to start with picking the lowest netstandard that matches the API we need and go from there.

.NET 4.6 will likely be the minimum going forward for ASP.NET Core as most of our server side components require at least netstandard 1.3. 

Also .NET <= 4.5.1 is out of support.

**Comment by cruikshj** [comment]
That is understandable.  I will focus on figuring out why OIDC breaks when I upgrade to 4.6.x.

Thanks for the quick response.

**Comment by MiKom** [comment]
I second adding version that supports .NET 4.6

With this version, we could use SignalR Core on Unity3D
