### ISSUE TITLE
Question: How to invoke hub method, from outside hub i.e. Service?

### ISSUE THREAD

**Issue by prom3theu5** [aspnet/SignalR#2265]
Using current prerelease.

I've a Background Service which subscribes to a Redis Channel, and performs actions based on an enum returned as part of a Class object.
A few of these actions I'd like to invoke server-side.

Currently the only way I have figured out how to do this is by passing IHubContext<MyHubType> through the constructor for the Redis Service. This allows me to call hub.Clients.All.SendAsync(method, args);

However, this seems to only invoke a Client-Side method, so I'd need an extra "Hop" in my execution, i.e. Send Event to Client -> Client Invokes Server Method -> Server Sends Result to Client.

Is it not possible to directly Invoke the Server method from my HubContext, cutting out the extra client processing, so the client simply Gets the Result from my Redis Service Invocation?

Would I have to create a client in my Redis Service?
I'm going to end up with quite a few of these services in the application.

**Comment by davidfowl** [comment]
> A few of these actions I'd like to invoke server-side.

What does that mean?

> Currently the only way I have figured out how to do this is by passing IHubContext through the constructor for the Redis Service. This allows me to call hub.Clients.All.SendAsync(method, args);

Right, that's the way to do it.

> However, this seems to only invoke a Client-Side method, so I'd need an extra "Hop" in my execution, i.e. Send Event to Client -> Client Invokes Server Method -> Server Sends Result to Client.

Are you trying to talk to clients? If yes then this is the way. If you're just trying to run some server side logic then put it somewhere outside of the hub.

> Is it not possible to directly Invoke the Server method from my HubContext, cutting out the extra client processing, so the client simply Gets the Result from my Redis Service Invocation?

I don't really understand what you're trying to cut out.

**Comment by prom3theu5** [comment]
I'm mainly trying to minimize code duplication. It's a few methods in the Hub that clients can invoke, which I wanted the Background Service to also be able to directly invoke as if a client had done so.

I guess I could move them to a third class containing shared methods and add that as a singleton.
Was just trying to make sure I hadn't overlooked something as I thought this could previously be done with `GlobalHost.ConnectionManager.GetHubContext<T>()`

**Comment by davidfowl** [comment]
> I'm mainly trying to minimize code duplication. It's a few methods in the Hub that clients can invoke, which I wanted the Background Service to also be able to directly invoke as if a client had done so.

Make a class that does that, the hub is something that a client calls, it's not a place to put shared logic as much as it feels like it could be. Hubs are also transient and exist for as long as a single invocation.

> I guess I could move them to a third class containing shared methods and add that as a singleton.

Yes, that's recommended.

> Was just trying to make sure I hadn't overlooked something as I thought this could previously be done with GlobalHost.ConnectionManager.GetHubContext<T>()

No, it was exactly the same thing as this with more statics.

**Comment by prom3theu5** [comment]
Ahh gotcha - thanks for the help / recommendation :)
