### ISSUE TITLE
How to SendAsync to Caller or Others on the IHubContext<>?

### ISSUE THREAD

**Issue by jadjare** [aspnet/SignalR#2274]
Is it at all possible to access the `Caller` and `Others` clients when working with the `IHubContext`?

I have read through various issues, including:
https://github.com/aspnet/SignalR/issues/734

Where it suggests using
`Clients.Client(Context.ConnectionId).InvokeAsync(...)`

I'm following the pattern here https://github.com/aspnet/SignalR/issues/182, that suggests using a separate "HubMethods" class to host / share hub logic between the actual Hub implementation and say a controller action method.  As such I'm working with the `IHubContext` interface rather than a `Hub` and thus don't have access to the `Context` property used in the above example.

_I just can't figure out how I can SendAsync to the `Caller`.  Is this possible when working with the `IHubContext`?_

Here is a snippet of the code I'm using,  It's in the commented out method that I want to make an explicit call to the Caller.
```
    public class AllocationHubCommands
    {
        
        private readonly IHubContext<AllocationHub> _hubContext;


        public AllocationHubCommands(IHubContext<AllocationHub> hubContext)
        {
            _hubContext = hubContext;
            
        }

        public Task SendAllocationCreatedMessage(AllocationCreated allocation)
        {

            return _hubContext.Clients.All.SendAsync("AllocationCreated", allocation);
        }

        //public Task SendAllocationSavedSuccesfullyMessageToCaller(AllocationCreated allocation)
        //{
            
        //}
    }
```

**Comment by anurse** [comment]
It's not possible to access those from `IHubContext`. `Caller` and `Others` both depend on knowing which client is the caller. When you're in `IHubContext`, we don't know and there may not even **be** a current caller since you could be in an MVC controller action, etc.

**Comment by jadjare** [comment]
Just on a side note, I did notice when trying to get things hooked up, that it is possible to see, in the private member variables, a reference to the `LifetimeManager` and within that I can see the `Connection` and `ConnectionId` properties.  I guess these won't always be populated if the client caller is not known, but is there any way to expose this?

**Comment by BrennanConroy** [comment]
The `LifetimeManager` may contain a list of connections for internal tracking purposes, but it's not going to be exposed.

Like @anurse said, there is no way of knowing who the current caller is from the `IHubContext`.

**Comment by anurse** [comment]
> therefore you're basically limited to sending to All

Using Groups and Users is one way to mitigate this. If you have access to the User ID of the user who initiated the action, you can use `.Users(userId)` to send a message to all of that user's connections. Similarly, you add the SignalR connections to a group and send to that group using `.Group(groupName)`

**Comment by jadjare** [comment]
@anurse, @BrennanConroy, thanks for taking the time to provide feedback.  The advise has been helpful.
