### ISSUE TITLE
signalr "connection closed with an error"

### ISSUE THREAD

**Issue by ranouf** [aspnet/SignalR#2279]
Hi,

This is the code soure:
https://github.com/ranouf/AspNetCore-SignalR/tree/master/src

csproj
```

    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="1.0.0-rc1-final" />
```

package.json

  `  "@aspnet/signalr": "^1.0.0-rc1-update1",`

I used this tutorial to update my code: [https://damienbod.com/2017/09/12/getting-started-with-signalr-using-asp-net-core-and-angular/](https://damienbod.com/2017/09/12/getting-started-with-signalr-using-asp-net-core-and-angular/)

> Each time I try to connect to the Hub, I have this error message:
> Information: WebSocket connected to ws://localhost:4053//chat?id=u9wrwlvaYiYfl1k8Jyl-yg
> Utils.js:188 Information: Using HubProtocol 'json'.
> Utils.js:188 Information: Close message received from server.
> **Utils.js:182 Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'.**

I tried to find information about that [Google: signalr "connection closed with an error"](https://www.google.ca/search?rlz=1C1CHBF_enCA784CA784&ei=kV_7WoCQH6al_QbivIyIAw&q=signalr+%22connection+closed+with+an+error%22&oq=signalr+%22connection+closed+with+an+error%22&gs_l=psy-ab.3..35i39k1.1761.2636.0.3752.2.2.0.0.0.0.83.166.2.2.0....0...1c.1.64.psy-ab..0.2.166....0.Goy_HyV9u_g)

But I didnt find any answer.

Is there someone who can help?

**Comment by BrennanConroy** [comment]
On your server you can turn on detailed errors via:
```
services.AddSignalR(o =>
{
    o.EnableDetailedErrors = true;
})
```

This will then give you a more detailed error message on the client

**Comment by peterdeme** [comment]
I got a similar one behind AWS ALB. Locally everything works fine, but behind a load balancer I got this after turning on detailed errors: 

![image](https://user-images.githubusercontent.com/19969687/40282785-861e2aee-5c74-11e8-88c0-49f10e704864.png)

WebSockets are supported and I have turned on sticky sessions. I'll update here if I figured out something.

**Comment by peterdeme** [comment]
Aaand got it. Exception thrown behind a hub are not propagated. 

```csharp
public override Task OnConnectedAsync()
{
     _logger.LogInformation("On connected: " + Context.User.Identity.Name);
     _memCache.Set(Context.User.Identity.Name, Context.ConnectionId);

     return base.OnConnectedAsync();
}
```

Looks like the Identity Name was null in my case and argument exception was thrown by `IMemoryCache`. @ranouf try enabling detailed errors, and add more logging to your hub.

**Comment by peterdeme** [comment]
David, sorry, yes I believe this is expected behaviour.

Regardless, if this helps someone, I managed to figure out my issue where the user principal is empty in the hub. So locally, I'm using AutoAuthorize middleware, and in our deployed environments we are using JwtAuthorizer one. I dunno why but with the latter one, the `Context.User` is empty, even though in our Controllers the User is very much populated. I figured I'll put `Authorize` attribute in my hub as well, so the middleware will surely run before the Hub is invoked.

Then did this on client side:

```typescript
const opts =  { accessTokenFactory: () => this.authService.getAuthToken()};

const connection = new signalr.HubConnectionBuilder()
   .withUrl(`${environment.backendAddress}progress-notifier`, opts)
   .build();
```

This `accessTokenFactory` is the best thing ever! I didn't even need any workaround to apply my header and I love that.

**Comment by anurse** [comment]
@ranouf have you been able to get any additional error information by setting the option @BrennanConroy suggested above?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by ranouf** [comment]
Hi, sorry I m working on something else currently. 
Thanks for.your help, when I will have more time I will try your suggestions ;)
