### ISSUE TITLE
Interface proxies for client hub connections

### ISSUE THREAD

**Issue by israellot** [aspnet/SignalR#2281]
Are dynamic generate typed proxies  planed for clients as well  ? ( Not clients in a hub, but clients that connect to a remote hub ) 
Similar to TypedHubClients<T> in _Microsoft.AspNetCore.SignalR.Internal_ but for _Microsoft.AspNetCore.SignalR.Client_

**Comment by anurse** [comment]
I wouldn't say it's planned, but it's something we've talked about :).

**Comment by davidfowl** [comment]
Dupe of https://github.com/aspnet/SignalR/issues/290
