### ISSUE TITLE
Specify the polyfill for Node.js

### ISSUE THREAD

**Issue by ManuelRauber** [aspnet/SignalR#2284]
* Versions of Client-Side NuGet/NPM Packages: 1.0.0-rc1-update1
* Are you using the C# client or the JavaScript client: JavaScript/Node.js
* The Operating System on the Client (Windows/Linux/macOS): macOS

In your [readme](https://github.com/aspnet/SignalR/tree/dev/clients/ts/signalr) there's an info about required polyfills for Node.js. It would be nice, if you link the polyfills you used for testing since for every stated polyfill there are several npms.

**Comment by davidfowl** [comment]
See the nodejs sample here https://github.com/aspnet/SignalR-samples/tree/master/StockTickR/NodeClient

**Comment by anurse** [comment]
We haven't been able to do the research/planning to select appropriate polyfills for 2.1, so we don't want to recommend something we haven't looked at seriously. As @davidfowl mentioned, we have a sample, but for now it's up to you to research the polyfills and select an appropriate one. We'll be looking at this for future releases. The priority for JavaScript in 2.1 was browsers, but we plan to improve NodeJS support moving forward.
