### ISSUE TITLE
Move C++ library source out of aspnet/SignalR

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2288]
Is there a way to link to all the source code from libraries that the C++ client uses?

![image](https://user-images.githubusercontent.com/303201/40144498-fd0366b6-59b2-11e8-8a95-b778c2920eee.png)

**Comment by mikaelm12** [comment]
Or at least start with moving the gtest source out of our repo

**Comment by davidfowl** [comment]
I 10000% agree

**Comment by anurse** [comment]
Even submodules would be a step in the right direction :). Or having the build script download the gtest sources (**only** when it knows for sure it's going to run the tests)

**Comment by anurse** [comment]
Propose for 2.2.0-mq
