### ISSUE TITLE
typescript connect the server will throw XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by zhaoqinghai** [aspnet/SignalR#2295]
![default](https://user-images.githubusercontent.com/26404526/40163874-8c609d92-59ea-11e8-8592-c19d9864f5fa.png)

**Comment by davidfowl** [comment]
This must be a node application. Right?

**Comment by zhaoqinghai** [comment]
No,This is just for testing

**Comment by davidfowl** [comment]
Yes but using nodejs, that’s the way you run JavaScript outside of the browser...

**Comment by BrennanConroy** [comment]
Yeah, looks like Nodejs
Read the NodeJS section of the README https://github.com/aspnet/SignalR/tree/dev/clients/ts/signalr#nodejs
