### ISSUE TITLE
"Didn’t parse the handshake" error 

### ISSUE THREAD

**Issue by ChristaPn** [aspnet/SignalR#2297]
I have a .net core 2.0 application that uses Microsoft.AspNetCore.SignalR (1.0.0-preview2-final), with Kestrel server. I can successfully send messages back and forth to the hub , while using an angular 5 app. 

I also want to use it though from a c# console app, that uses  websocketsharp.core v1.0.0 for handling web socket requests (see attachment). 
From logging info I can see that the socket can be opened successfully but when I try to send the JSON handshake request (as described in: https://github.com/aspnet/SignalR/blob/dev/specs/HubProtocol.md) I get a "Didn’t parse the handshake" error at Microsoft.AspNetCore.SignalR.HubSocketContext[0].

Windows Server 2012 is used for both client and server.

[Program.txt](https://github.com/aspnet/SignalR/files/2012929/Program.txt)

Any ideas?

**Comment by anurse** [comment]
Purely out of curiosity, why are you building your own .NET Client? I just want to understand if there's something missing or not supported in the existing client that you're trying to get working?

**Comment by ChristaPn** [comment]
I just wanted to build a showcase in .net with the minimum possible set up, so my colleagues can transfer the logic to Go lang . The client there does not work the latest SignalR version.

**Comment by anurse** [comment]
Cool, thanks for the info!

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
