### ISSUE TITLE
Javascript Client: error while call disconnect

### ISSUE THREAD

**Issue by claylaut** [aspnet/SignalR#2298]
I've migrated to the latest version and found the below issue:

When calling `hubConnection.stop()` it throws an error.
https://github.com/aspnet/SignalR/blob/846432c9ac4599cbd24ceac6e756627d3f1859c7/client-ts/signalr/src/HubConnection.ts#L158

`'Error: Websocket closed with status code: 1006 ()'.
signalr.js:1676 `

* Transport Type: WebSockets
* Versions of Server-Side NuGet Packages: 1.0.0-rc1-final
* Versions of Client-SideNPM Packages (@aspnet/signalr`): 1.0.0-rc1-update1
* Are you using the C# client or the JavaScript client: JavaScript client
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome

**Comment by BrennanConroy** [comment]
Could you try to gather client and server logs? See https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide
Otherwise there is nothing actionable here

**Comment by claylaut** [comment]
@BrennanConroy Thanks a lot for the diagnostics guide it's very useful, I will extract the requested information and I will let you know.

**Comment by claylaut** [comment]
@BrennanConroy after created a sample application for pure signalr client for a different issue i couldnt reproduce this.

I will close this for now if i will have more information will re open it. 

Thanks for the Diagnostics Guide :)
