### ISSUE TITLE
Develop a plan for a more all-inclusive NodeJS client

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2301]
Right now, `@aspnet/signalr` is usable in NodeJS, but it requires numerous global polyfills. We should come up with a plan for a more "all-inclusive" Node JS client. This may just be logic/behavior in the existing client, or we could build a new `@aspnet/signalr-node` package that bundles `@aspnet/signalr` with additional polyfills (and pre-configures them).

Things to figure out:
* [ ] What polyfills should we use?
* [ ] How should `@aspnet/signalr` allow injecting polyfills. I'd like to avoid depending upon globals, so should `IHubConnectionOptions` have a `webSocketConstructor` parameter, etc.?
* [ ] How should we package the client?
* [ ] Support for custom headers/cookies?

**Comment by davidfowl** [comment]
>  What polyfills should we use?

We shouldn't polyfill anything. Or rather, lets not call it that. We abstract things a bit more and have node implementations and browser implementations.

>  How should @aspnet/signalr allow injecting polyfills. I'd like to avoid depending upon globals, so should IHubConnectionOptions have a webSocketConstructor parameter, etc.?

You mean IHttpConnectionOptions right? I think it's fine to hang the factories off there

>  How should we package the client?

I think a separate package.

**Comment by anurse** [comment]
We should ensure that the `WebSocket` and `EventSource` abstractions we use take the `accessToken` value. NodeJS-based implementations would be able to actually encode this in a header, which would be more desirable.

**Comment by anurse** [comment]
This is also effectively a pre-req for https://github.com/aspnet/SignalR/issues/2048 since the tests run in Node

**Comment by anurse** [comment]
So socket.io just directly depends upon the `ws` WebSocket polyfill library: https://github.com/socketio/engine.io-client/blob/1cfae04a13ad43c9644231698f51f101ab1d19c7/package.json#L35

**Comment by anurse** [comment]
I did some research and thinking on ways to handle this. I listed a few approaches below. I think we should just go head-first into this and do the 4th approach before (one library that works in node and browser). It's a little more work for us, and it does mean that extra packages are downloaded on install, but I think the clean experience is worth it.

## Approach 1: Global Polyfills

We do nothing. We already have HttpClient to abstract XMLHttpRequest, and Node users can install polyfills into the global WebSocket/EventSource

### Pros: 

* No work for us to do!

## Cons: 

* It sucks hard.
* Getting WebSockets to work in Node requires installing a global which is Bad
* Unit Testing is hard because we have to install globals, which risks cross-contamination

## Approach 2: Manual, non-global polyfills

We add options to IHttpConnectionOptions to provide a WebSocket constructor function and an EventSource constructor function. Users can pass a Polyfill in to that and we'll use it instead of the global. We can provide HubConnectionBuilder methods to configure them

### Pros:

* Users can install polyfills without polluting global scope
* Our unit tests don't have to pollute global scope

### Cons:

* Users still have to find and configure polyfills

## Approach 3: `@aspnet/signalr-node` library

This is based on Approach #2. We add the options to IHttpConnectionOptions as TypeScript **@internal** fields, which means they don't show up in the docs. We build a '@aspnet/signalr-node' library that depends directly on `@aspnet/signalr`, as well as WebSocket and EventSource polyfills and stitches it all together.

### Pros:

* Users don't have to find an configure polyfills

### Cons:

* Separate library, which is confusing and seems unnecessary in JavaScript
* Users can't easily swap out Polyfills, but since we still have the undocumented options on IHttpConnectionOptions, they *could* swap them out in theory.
* Properly stitching it together is actually not trivial since we need to "override" logic in `HubConnectionBuilder`. It's doable, but a little funky and might involve exporting a different `HubConnectionBuilder` out of `@aspnet/signalr-node` that wraps the one in `@aspnet/signalr`.

## Approach 4: One band, one sounds, one library

We just have the one library. The library takes a direct dependency on the polyfills we want to use. However, we still "detect" the browser and use the browser-native versions if they are present and we only `require` the polyfill if we aren't on a browser. Also, this is what socket.io does in their [`engine.io-client`](https://github.com/socketio/engine.io-client/blob/master/package.json#L35) package (engine.io is their lower-level transport abstraction, like our Http.Connections)

### Pros:

* Everything just works in the single library.
* The world becomes a better place, one bit at a time.
* Dogs and cats live together in harmony.

### Cons:

* Again, users can't easily swap out the polyfills, but we could make them configurable, and even document it.
* More complex logic for us, but honestly, it's not much more than Approach #3
* New third-party dependencies, but we wouldn't need to bundle them for the browser version since they aren't needed there. Would need to see how WebPack and friends are affected, but I think this pattern isn't uncommon.
* Users have to download the WebSocket and EventSource polyfills when `npm install`ing, even if they don't plan to use them.

**Comment by davidfowl** [comment]
I was leaning towards 3 but then I saw this https://www.npmjs.com/package/socket.io-client, now I think 4.

**Comment by anurse** [comment]
We're going with Approach 4. Closing this out and creating specific issues for the work
