### ISSUE TITLE
Add scripts to automatically deploy test applications

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2303]
We should automatically deploy test applications on each commit. We can do this as part of our main build, or in a separate build triggered on each commit. This will help with things like testing Xamarin and multiple browsers.

**Comment by BrennanConroy** [comment]
Also, add Commit hash endpoint to both apps

**Comment by BrennanConroy** [comment]
Repo specific tasks are done for this. Now we need to work on the automated publish per commit to dev
