### ISSUE TITLE
JsonHubProtocol does not correctly count extra arguments for complex objects

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2311]
```
{'type':1,'invocationId':'42','target':'foo','arguments':[1,'',{'1':1,'2':2}]}
```

Error message says there are 8 arguments instead of 3 because the content is not correctly skipped.

**Comment by anurse** [comment]
Reopening to track as a candidate for 2.1.1 patch.

**Comment by anurse** [comment]
Re-closing, we're going to open new issues for patch work.
