### ISSUE TITLE
SignalR dotnet core authentication

### ISSUE THREAD

**Issue by amir734jj** [aspnet/SignalR#2316]
I am using [`Microsoft.AspNetCore.SignalR`][1] nuget package with [`Bazinga.AspNetCore.Authentication.Basic`][2] which adds basic authentication to dotnet core. My C# SignalR client connects when there is no authentication, but when I add `AuthorizeAttribute` it connects by http and http request header gets authenticated successfully but the Socket does not authenticate probably because there is no header in socket messages.

So I am wondering how should I pass a token or something to authenticated socket connection or is there a example code that I can follow. I think I should pass a random token to just authenticated user and the user needs to constantly pass the token in messages.

[Client project][3], [Server project][4]

**Server:**

    using System.Threading.Tasks;
    using Bazinga.AspNetCore.Authentication.Basic;
    using Domainlogic;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Cors.Infrastructure;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.Extensions.DependencyInjection;
    
    namespace API
    {
        public class Startup
        {
            public void ConfigureServices(IServiceCollection services)
            {
                services.AddCors(options => options.AddPolicy("CorsPolicy", builder =>
                {
                    builder
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                        .AllowAnyOrigin();
                }));
    
                services.AddSignalR();
                
                services.AddAuthentication(BasicAuthenticationDefaults.AuthenticationScheme)
                    .AddBasicAuthentication(credentials => Task.FromResult(
                        credentials.username == "SomeUserName"
                        && credentials.password == "SomePassword"));
            }
    
            // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
            public void Configure(IApplicationBuilder app, IHostingEnvironment env)
            {
                if (env.IsDevelopment())
                {
                    app.UseDeveloperExceptionPage();
                }
    
                app.UseCors("CorsPolicy");
    
                app.UseCors(CorsConstants.AnyOrigin);
    
                app.UseFileServer();
    
                app.UseSignalR(route => { route.MapHub<MessageHub>("/chat"); });
                
                app.UseAuthentication();
            }
        }
    }

**Server hub:**

    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.SignalR;
    
    namespace Domainlogic
    {
        public class MessagePayload
        {
            public string Name { get; set; }
            
            public string Message { get; set; }
            
            public DateTime Date { get; set; }        
        }
        
        [Authorize]
        public class MessageHub : Hub
        {   
            // connected IDs
            private static readonly HashSet<string> ConnectedIds = new HashSet<string>();
    
            public override async Task OnConnectedAsync()
            {
                ConnectedIds.Add(Context.ConnectionId);
                
                await Clients.All.SendAsync("SendAction", "joined", ConnectedIds.Count);
            }
    
            public override async Task OnDisconnectedAsync(Exception ex)
            {
                ConnectedIds.Remove(Context.ConnectionId);
                
                await Clients.All.SendAsync("SendAction", "left", ConnectedIds.Count);
            }
    
            public async Task Send(MessagePayload message)
            {
                await Clients.All.SendAsync("SendMessage", message);
            }
        }
    }

**Client:**

    using System;
    using System.Net;
    using System.Net.Http.Headers;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Http.Connections.Client;
    using Microsoft.AspNetCore.SignalR.Client;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Options;
    using Microsoft.Extensions.Logging;
    
    namespace SignalRClient
    {
        public class MessagePayload
        {
            public string Name { get; set; }
            
            public string Message { get; set; }
            
            public DateTime Date { get; set; }        
        }
        
        class Program
        {
            public static string Base64Encode(string plainText) {
                var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(plainText);
                return System.Convert.ToBase64String(plainTextBytes);
            }
            
            static void Main(string[] args)
            {
                var credential = Convert.ToBase64String(System.Text.Encoding.GetEncoding("ISO-8859-1").GetBytes("SomeUserName" + ":" + "SomePassword"));
                
                //Set connection
                var connection = new HubConnectionBuilder()
                    .WithUrl("http://localhost:5000/chat", options =>
                    {
                        options.Headers.Add("Authorization", $"Basic {credential}");
                    })
                    .AddJsonProtocol()
                    .Build();
                            
                connection.On<MessagePayload>("SendMessage", param =>
                {
                    Console.WriteLine(param.Message);
                });
    
                connection.StartAsync().Wait();
    
                var startTimeSpan = TimeSpan.Zero;
                var periodTimeSpan = TimeSpan.FromSeconds(3);
                int i = 0;
                
                var timer = new System.Threading.Timer((e) =>
                {
                    connection.InvokeAsync<MessagePayload>("Send", new MessagePayload()
                    {
                        Message = "Some message: " + i++
                    });
                }, null, startTimeSpan, periodTimeSpan);
                
    
                Console.Read();
                connection.StopAsync();
            }
        }
    }

  [1]: https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR
  [2]: https://www.nuget.org/packages/Bazinga.AspNetCore.Authentication.Basic
  [3]: https://www.dropbox.com/s/afsneajippv6vfx/SignalRClient.zip?dl=0
  [4]: https://www.dropbox.com/s/jy2wkc8x79e9ku3/SymmetricCryptoChatRoom.zip?dl=0

**Comment by davidfowl** [comment]
Move UseAuthentication above UseSignalR

**Comment by amir734jj** [comment]
@davidfowl Wow, it worked! Thank you so much!

**Comment by PSausM** [comment]
I had the same issue. It is not mentioned in the docs.

**Comment by timgabrhel** [comment]
I just ran in to this exact same issue. 

@davidfowl Any chance you could give a little insight into what's happening internally when registering `UseAuthentication`?

**Comment by davidfowl** [comment]
The middleware sets the user on the http context.
