### ISSUE TITLE
Fix not reading to end of argument JSON on binding error

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2321]
```
{'type':1,'invocationId':'42','target':'foo','arguments':[[],{'target':'foo2'}]}
```

JSON hub protocol does not correctly read to the end of arguments. In sample above "foo2" in target property that is nested in argument value would replace correct "foo".

**Comment by anurse** [comment]
Reopening to track as a candidate for 2.1.1 patch.

**Comment by anurse** [comment]
Porting Checklist:
* [x] 2.2.0 `dev`
* [ ] 2.1.1 `release/2.1`

**Comment by anurse** [comment]
Re-closing, we're going to open new issues for patch work.
