### ISSUE TITLE
Is there a way to convert/create instance of a specified type using some sort of utility that encapsulates the underlying protocol in a hub method? 

### ISSUE THREAD

**Issue by isijoc** [aspnet/SignalR#2325]
We are trying to create a `generic hub method` that can process different types of objects. If we only use the JsonHubProtocol then we can infer that opaque objects are deserialized as `JObject` and therefore take advantage of facilities provided to perform the translation from opaque objects to well-known ones. But if we use another hub protocol then the previous assumption is no longer valid. Is there a way accomplish this type of logic using a protocol agnostic approach?

Thank you very much for taking the time to read this and kudos to all of you for creating such amazing framework!

```csharp
namespace test
{
    public class MessagePayload
    {
        public string PayloadType { get; set; }
        public object Payload { get; set; }
    }

    public class PayloadTypeA 
    {
        public int Id { get; set; }
    }

    public class PayloadTypeB
    {
        public string Description { get; set; }
    }

    public class MessageBusHub : Hub
    {
        public void OnMessageArrived(MessagePayload message)
        {
            Type payloadType = Type.GetType(message.PayloadType);
            var actualPayload = ((JObject)message.Payload).ToObject(payloadType);
        }
    } 
}
```

**Comment by davidfowl** [comment]
It’s not really doable in a protocol agnostic way as there’s no universal representation for it. The only thing I can think of it using byte[] but that’s inefficient using JSON since it gets base64 encoded by default.

**Comment by davidfowl** [comment]
Are you trying to pass through a message from another system?

**Comment by isijoc** [comment]
Thank you for responding so quickly! Yes, I am trying to pass in messages between different message bus system. Is there anything you recommend looking at? I will look more into your example of using a the hub connection directly in your weather app for a possible alternative implementation. Thank you again, you are incredible talented!

**Comment by davidfowl** [comment]
I think using a hub is fine actually and byte[] would be the representation. For a text protocol like JSON it would be base64 encoded but that’s not the end of the world. It will just be more efficient as binary.

Using byte[] is better as well sice it basically tells the deserializer to treat it as opaque data.

**Comment by davidfowl** [comment]
Thanks for the kind words.

**Comment by isijoc** [comment]
You are most welcome, I deeply admire your work. Finally, how can I get the underlying protocol to get the actual deserialized object from the binary representation within the hub? 

```csharp
public class MessageBusHub : Hub
{
        public void OnMessageArrived(string payloadType, byte[] payload)
        {
            Type payloadType = Type.GetType(payloadType);
            var protocol =  Context.Proptocol; //magic protocol property?
            var actualPayload = proptocol.Deserialze(payload, payloadType);
        }
}
```

**Comment by anurse** [comment]
Can you provide an example of what your client code looks like in this scenario? @davidfowl is suggesting you serialize the message manually on the client before calling the hub method, so there is no "protocol" property to read, it's just whatever format you choose to use to serialize your message.

If you can let us know the overall goal you're trying to achieve (including details like what system is providing these messages), we can provide guidance that's more tuned for your situation :).

**Comment by isijoc** [comment]
Hi anurse, sorry it took me so long to reply but I tried to gather all the main pieces into a single file to give you an idea of what I am trying to do.  We use a flavor on NServiceBus to orchestrate the communication between multiple applications. I am trying to see if we can take advantage of the fact that signalR has built-in abstractions to isolate the logic from the transport protocol as well as the formatter used to serialize/deserialize messages to be consumed by parties on both ends of the hub. 

The overall goal is to have clients to dispatch messages to the server and then consume replied messages from the server in a sort of transport/formatter agnostic way.  Below you can see an example where a server hub is used as a message bus. It processes client messages arrived to the server through the `ProcessMsg` method and then sends back replies through the `replyMsg` event invoked on the client side. For the client implementation, we are using `redux-sagas` which creates channels to transfer messages using the `aspnet/signalr` javascript client.

I see @davidfowl idea of just ignoring the protocol used to serialize/desealize the message but I was actually wondering if I could take advantage of its benefits without much effort. If think if I could find a way to call in the message formatter specifying the actual type after being identified then it should just magically work :) 

Thank you very very much for willing to help. I really appreciate it!

## Server side
```csharp
namespace MessageBus
{
	public class IncomingMessage
	{
		public string PayloadType{ get; set; }
		public object Payload { get; set; }
	}
	
	publi c class MessageBusHub: Hub, IMessageBus
	{
		private ConcurrentQueue<IMessage> messageQueue = new ConcurrentQueue<IMessage>();
		private IServiceProvider serviceProvider;
		
		public MessageBusHub(IServiceProvider serviceProvider)
		{
			this.serviceProvider = serviceProvider;
		}
				  
		public void ProcessMsg(IncomingMessage incomingMsg)
		{
			Type payloadType = Type.GetType(incomingMsg.PayloadType);
			var msg = ((JObject)incomingMsg.Payload).ToObject(payloadType);
			Consume((IMessage)msg);
		}
		
		protected void Consume(params IMessage[] msgs)
		{
			foreach(var msg in msgs) {
				messageQueue.Enqueue(msg);
			}
			
			ProcessMsgQueue();
		}
		
		protected void ProcessMsgQueue()
		{
			var msgContext = new MessageBusContext
			{
				Bus = this
				... 
			};
			
			while(!messageQueue.IsEmpty)
			{
				if (!messageQueue.TryDequeue(out IMessage msg))
					continue;
				
				foreach (var msgHandler of FindHandlersOf(msg))
				{
					InvokeHandleMsg(msgHandler, msg, msgContext);
				}
			}
		}
		
		protected IEnumerable<object> FindHandlersOf(IMessage msg)
		{
			var handlerType = typeof(IHandleMessage<>).MakeGenericType(msg.GetType());
			return serviceProvider.GetServices(handlerType);
		}
		
		protected InvokeHandleMsg(object target, msg, context)
		{
			// reflection stuff
		}
		
		protected void Publish(IMessage msg);
		{
			SendMessageToCallerClient(msg);
			Consume(msg);
		}
		
		protected Task SendMessageToCallerClient(IMessage msg)
		{
			return Clients.Caller.SendAsync("replyMsg", msg);
		}
	}

	public class PlaceOrderHandler : IHandleMessage<PlaceOrder>
	{
		public void HandleMsg(PlaceOrder message, IMessageHandlerContext context)
		{
			var orderPlaced = new OrderPlaced
			{
				OrderId = message.Id
			};
			return context.Bus.Publish(orderPlaced);
		}
	}
	
	public class PlaceOrder: IMessage
	{
		public Id { get; set; }
	}
	
	public class OrderPlaced: IMessage
	{
		public int OrderId { get; set; }
	}
		
	public interface IHandleMessage<TMsg>
	   where TMsg: IMessage
	{
		void HandleMsg(TMsg message, IMessageContext context);		
	}

	public interface IMessageContext
	{
		IMessageBus Bus { get; set; }
		IMessageCallerContext CallerContext { get; set; }
	}

	public interface IMessageBus
	{	  
		void Publish(params IMessage[] messages);
	}

	public interface IMessage { }  

}
```
## javascript client

```javascript

import { take, put, call, actionChannel, fork, cancel, cancelled } from 'redux-saga/effects'
import { eventChannel, delay, buffers } from 'redux-saga'
import { HubConnectionBuilder } from '@aspnet/signalr'

const client = new clientBuilder()
  .withUrl('/message-bus')
  .build()

const createChannelFromServerReplyMsgEvents = (client) =>
  eventChannel(emit => {
    client.on('replyMsg', emit)
    return () => {
      client.off('replyMsg', emit)
    }
  })

const createChannelFromOnCloseEvents = (client) =>
  eventChannel(emit => {
    client.onclose(error => emit({ type: 'HUB_CONNECTION_CLOSED', error }))
    return () => {
      // teardown onclose event subscription ?
	  // not sure how to do that
    }
  })

function* sendMessageToServer (transferMessageChannel) {
  while (true) {
    const message = yield take(transferMessageChannel)
    try {
      yield call([client, 'invoke'], 'ProcessMsg', message)
    } catch (error) {
      console.error(error)
    }
  }
}

function* receiveMessageFromServer (serverReplyMsgChannel) {
  while (true) {
    const receivedMsg = yield take(serverReplyMsgChannel)
    yield put(receivedMsg)
  }
}

function* handleclientIO (transferMessageChannel, serverReplyMsgChannel) {
  yield fork(receiveMessageFromServer, serverReplyMsgChannel)
  yield fork(sendMessageToServer, transferMessageChannel)
}

export default function* messageBusHandler () {
  // we want to serially transfer messages to the server endpoint 
  const transferMessageChannel = yield actionChannel('TRANSFER_MESSSAGE_CMD', buffers.sliding(20))
  const serverReplyMsgChannel = yield call(createChannelFromServerReplyMsgEvents, client)
  const clientOnCloseEventChannel = yield call(createChannelFromOnCloseEvents, client)

  while (true) {
    try {
      console.log('initializing hub communication...')
      // initialize the client communication by calling start
      yield call([client, 'start'])
      // spawn threads for reading from and writing to the hub
      const clientIOTask = yield fork(handleclientIO, transferMessageChannel, serverReplyMsgChannel)
      // wait for onClose event
      const closeAction = yield take(clientOnCloseEventChannel)
      if (closeAction.error) {
        console.error(closeAction.error)
      }
      // cancel client I/O workers because client is in disconnected state
      // and no I/O operation is allowed
      yield cancel(clientIOTask)
    } catch (e) {
      if (yield cancelled()) {
        throw e
      }
    }

    yield call(delay, 5000) // retry after 5s
  }
}
```

**Comment by anurse** [comment]
So from this section of code, it looks like you're basically trying to send an arbitrary JavaScript object to the server:

```javascript
    const message = yield take(transferMessageChannel)
    try {
      yield call([client, 'invoke'], 'ProcessMsg', message)
    } catch (error) {
      console.error(error)
    }
```

So, if you want to be able to do that in a way that works no matter which protocol you use, I'd suggest serializing it to JSON yourself on the client and treat it as a string. Then, even if you switch the Hub Protocol in use, the payload you are trying to send will still be in JSON and you can deserialize it manually.

Of course, this incurs a performance penalty, because you are serializing the inner payload to JSON, then SignalR will wrap that in an invocation and serialize it again, but it would be a minor impact, and gives you the flexibility to do what you want.

**Comment by isijoc** [comment]
That is a great idea @anurse! Pretty clever solution!!! The only tiny concern is that I would have to include a json serializer in all clients to pre-format the message that the signalr infrastructure will deliver to the server. But still, it is pretty doable solution since a json serializer library is available in all our client's platforms. 

By going through the code, I did realize it is the job of each protocol to figure the type of the binding parameters for the target hub method and do the appropriated deserialization before invoking it. That gave me the idea of using the `IHubProtocolResolver` to identify all available protocols and then iterate through all possible translations of the opaque object after the method has been invoked such as in   

```csharp
public class IncomingMessage
{
    public string PayloadType{ get; set; }
    public object Payload { get; set; }
}
    
public class MessageBusHub: Hub, IMessageBus
{
    private string[] protocolNames;
    
    public MessageBusHub(IHubProtocolResolver protocolResolver)
    {
        protocolNames = protocolResolver.AllProtocols.Select(x=>x.GetType().Name).ToArray(); 
    }
              
    public void ProcessMsg(IncomingMessage incomingMsg)
    {
        Type payloadType = Type.GetType(incomingMsg.PayloadType);
        var msg = TryToConvertOpaqueMsgToSpecificType(incomingMsg.Payload, payloadType);
        if (msg != null) 
	{
             Consume(msg);
        }
    }
    
    public object TryToConvertOpaqueMsgToSpecificType(object msg, Type type)
    {
        foreach(var protocol in protocolNames)
        {
            case "JsonHubProtocol": 
            {
                if (msg is JObject jsonMsg)
		{
                    return jsonMsg.ToObject(messageType);
		}
                break;
            }
            case "MessagePackHubProtocol":
            {
                //do magic to convert object to type
                
            }
        }
        return null;
    }
}
 ```

Anyway, thank you very much @davidfowl  and @anurse  for being so generous with your time and knowledge and for building such amazing framework! I love it!!!

**Comment by davidfowl** [comment]
The protocol is responsible for decoding the entire invocation (including method name, arguments etc)  so you can't just use it on arguments of your deserialized object. See the hub protocol spec here https://github.com/aspnet/SignalR/blob/dev/specs/HubProtocol.md

**Comment by isijoc** [comment]
Thank you David! now I see why it was hard to accomplish what I was trying do. The spec is super useful because not only provides a lot of details but also helps to understand why things are coded on a certain way. Thank again for all your help and guidance!

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
