### ISSUE TITLE
C# client with Azure SignalR Services: Unable to connect to the server with any of the available transports.

### ISSUE THREAD

**Issue by MhAllan** [aspnet/SignalR#2329]
I had Signalr hub within asp.net core 2.0 mvc application and it was working fine. hosted it on azure and it was working. when tried to use Azure Signalr Services the client started to throw this exception 
**"Unable to connect to the server with any of the available transports."**

The weird thing is that I can see connections on azure portal.

**First question** is the bug. all what changed and made it break are these:
- services.AddSignalRCore()**.AddAzureSignalR(signalrConnectionString)**
- app.**UseAzureSignalR(router => router.MapHub<SettingsHub>("/myhub")) instead of UseSignalR** 

Notes:
- signalr resource connection string is set in configurations
- app.UseFileServer() has no effect, and I wonder why it is there without any explanation
- debuggin in iis express or hosting on azure both same result

This is the client, and I don't know where all other options have gone or how to configure logs!:
```
_hubClient = new HubConnectionBuilder()
                            .WithUrl(url, HttpTransportType.WebSockets)
                            .Build();

            await _hubClient.StartAsync();
```

no https no authentication no authorization. mvc controllers work, signalr client does not!

**Second question** is, if the client is not connected, what are these connections I see on the portal? is it my web app creating them or what? any documentation/explanation?

![image](https://user-images.githubusercontent.com/13087546/40294028-120a4914-5d17-11e8-90eb-4f8d7ff2964b.png)

**Comment by davidfowl** [comment]
You need to update to the RC1 of ASP.NET Core and .NET Core.

**Comment by MhAllan** [comment]
@davidfowl , **same issue**. Here are the updated references:

on server:
```xml
<TargetFramework>netcoreapp2.1</TargetFramework>
...
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-rc1-final" />
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-rc1-final" />
<PackageReference Include="Microsoft.Azure.SignalR" Version="1.0.0-preview1-10009" />
```
and client:
```xml
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
...
<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="1.0.0-rc1-final" />
```
