### ISSUE TITLE
WebSocket Client Can not handshake

### ISSUE THREAD

**Issue by LGinC** [aspnet/SignalR#2331]
`ClientWebSocket client = new ClientWebSocket();
                var cts = new System.Threading.CancellationToken();
                client.Options.AddSubProtocol("protocol1");
                client.ConnectAsync(new Uri("wss://myhost/signalr"), cts).Wait();
                Console.WriteLine("Connect success");
                Task.Delay(3000).Wait();
                client.SendAsync(new ArraySegment<byte>(Encoding.ASCII.GetBytes(@"{""protocol"": ""json"",""version"": 1}")), WebSocketMessageType.Text, true, cts).Wait();
                Console.WriteLine("Send success");
                var buffer = new ArraySegment<byte>(new byte[1024]);
                client.ReceiveAsync(buffer, cts).Wait();
                Console.WriteLine(Encoding.UTF8.GetString(buffer.ToArray()));`

It will disconnect When I send the handshake message  @"{""protocol"": ""json"",""version"": 1}".

Maybe encoding

server log:
.Internal.Transports.WebSocketsTransport - Socket opened.
INFO  2018-05-21 17:10:14,682 [16   ] .Internal.Transports.WebSocketsTransport - Socket closed.
ERROR 2018-05-21 17:10:14,682 [16   ] oft.AspNetCore.Sockets.ConnectionManager - Failed disposing connection 9e7c69b2-b709-469f-ae3e-8b6ce74bbce3.
System.IO.InvalidDataException: Unable to parse payload as a negotiation message.
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.NegotiationProtocol.TryParseMessage(ReadOnlySpan`1 input, NegotiationMessage& negotiationMessage)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.<NegotiateAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by BrennanConroy** [comment]
You need the payload separator https://github.com/aspnet/SignalR/blob/dev/specs/HubProtocol.md#json-payload-encoding

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.

**Comment by LGinC** [comment]
`services.AddSignalR(options =>
            {
                // Faster pings for testing
                options.KeepAliveInterval = TimeSpan.FromSeconds(5);
            }).AddJsonProtocol(options =>
            {
                //options.PayloadSerializerSettings.Converters.Add(JsonConver);
                //the next settings are important in order to serialize and deserialize date times as is and not convert time zones
                options.PayloadSerializerSettings.Converters.Add(new IsoDateTimeConverter());
                options.PayloadSerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Unspecified;
                options.PayloadSerializerSettings.DateParseHandling = DateParseHandling.DateTimeOffset;
            });`

addJsonProtocol in func ConfigureServices,  and client send 
{
    "protocol": "json",
    "version": 1
}

but server log Protocol.NegotiationProtocol.TryParseMessage failed


ERROR 2018-05-22 10:40:38,635 [3    ] oft.AspNetCore.Sockets.ConnectionManager - Failed disposing connection a4589209-d77e-408e-b54d-0efd29dc4a79.
System.IO.InvalidDataException: Unable to parse payload as a negotiation message.
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.NegotiationProtocol.TryParseMessage(ReadOnlySpan`1 input, NegotiationMessage& negotiationMessage)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.<NegotiateAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by davidfowl** [comment]
You didn’t add the payload separator

**Comment by davidfowl** [comment]
And I quote from the spec:

JSON payloads are separated with the record separator (0x1e) to ease the parsing.

**Comment by LGinC** [comment]
@davidfowl  How to add it?

**Comment by anurse** [comment]
You need to terminate all JSON messages with the "Record Separator" character (ASCII code `0x1E`). If you're writing a custom client using `ClientWebSocket` directly, you have to add that to the message yourself.

Is there a reason you aren't using the .NET Client and are using WebSockets directly?

**Comment by LGinC** [comment]
@davidfowl @anurse Thanks, I add the 0x1e,and send success.
