### ISSUE TITLE
Web Sockets Connection throws 404 connection error

### ISSUE THREAD

**Issue by claylaut** [aspnet/SignalR#2333]
I've upgraded from tech preview to rc1 signalr and I m still receiving the `404 connection error for web sockets`. 

Shouldn't stickiness are not required anymore for web socket connections? 

I m not sure if I m missing any configurations on client or server. Any ideas how to solve this issue?

## Currently we are using:
* Signalr Javascript client : `1.0.0-rc1-update1`
* Server-Side NuGet Packages: `1.0.0-rc1-final`
* Signalr Server is running on Kubernetes cluster of: `4 instances`
* Kubernetes: using `ingress with ngnix`
* Operating System on the Server: `Linux`
* Operating System on the Client: `Windows`
* Host: `AWS`
* Browser on the client: `Chrome`

## Sample Client Application for quick testing:
This sample client application connects with our signalr server
https://github.com/claylaut/signalr-websocket-connection-issue

## Server logs sample:
These server logs are for one specific user retrying to connect multiple times and after few retries, it connects successfully. 
[server-logs-sample.xlsx](https://github.com/aspnet/SignalR/files/2022755/server-logs-sample.xlsx)

## Client sample error:
![client-trace-error](https://user-images.githubusercontent.com/1999085/40311616-a77b756a-5d10-11e8-9ee0-feeb484c876c.jpg)

**Comment by davidfowl** [comment]
You need to enable sticky sessions when using SignalR behind a load balancer https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html

**Comment by davidfowl** [comment]
I guess this is also relevant https://www.nginx.com/products/nginx/load-balancing/

**Comment by claylaut** [comment]
@davidfowl Thanks a lot for your reply.

I thought it wasn't needed after I've seen the below comment, but maybe I've misunderstood it.
https://github.com/aspnet/SignalR/issues/984#issuecomment-341763390

I will set ngnix + aws load balancers and i will let you know how it goes.

**Comment by davidfowl** [comment]
Ah yes, that behavior changed in the RC, if you want to go back to direct websocket connections then you need to set the `SkipNegotiation` on WithUrl (you can pass options there).

If you disable negotiate you will not be able to use the new Azure SignalR service without extra work (that's still an option even though you're on AWS).

**Comment by claylaut** [comment]
Thanks for the clarification.
I will go for sticky sessions which sounds the proper fix for this issue.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.

**Comment by claylaut** [comment]
@davidfowl I managed to fix it.

Leaving my solution here maybe someone else will encounter this issue and it will be helpful.

We are using `Kubernetes ingress-nginx` and I only needed to add the below **annotations**:
```
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
```

**IMPORTANT NOTES**: 
* We've set the AWS ELB to use `TCP` instead `HTTP`.
* AWS LB doesn't require sticky sessions (still this is not possible when you're using TCP.)
* This works with **Signalr RC1**, with the older version `tech preview 2` it will throw an exception ( i didnt investigate it why).

**Comment by lucaswalter** [comment]
I had the same issue with ingress-nginx and ended up having to use these annotation in my Ingress instead:

```
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
```
