### ISSUE TITLE
Uncaught Error: The 'protocol' argument is required

### ISSUE THREAD

**Issue by vpaulino** [aspnet/SignalR#2334]
Hi there, 

I was trying to run a simple sample with signalr but I'm getting some errors on the dev tools ( chrome or edge ) 

try to run my sample on kestrel and iisexpress but got this error messages from the dev tools on the browsers: 
Chrome: 

Uncaught Error: The 'protocol' argument is required.
    at Function.Arg.isRequired (signalr.js:1537)
    at new HubConnection (signalr.js:1753)
    at site.js:3
Arg.isRequired @ signalr.js:1537
HubConnection @ signalr.js:1753
(anonymous) @ site.js:3
signalr.js:1537 Uncaught Error: The 'protocol' argument is required.
    at Function.Arg.isRequired (signalr.js:1537)
    at new HubConnection (signalr.js:1753)
    at site.js?v=v3PhiEz524fSM8dMzun4We38h4Udlp9uDZyube2Y4ug:3

OS: windows 10 pro 
dotnet framework installed: 2.1.300-preview1-008174
client signalR installation : @aspnet/signalr@1.0.0.0-rtm-30793
visual studio: vs1107 version 15.7.1

the csproj of the aspnet mvc application created: 
```

<PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.1.0-preview1-final" />
  </ItemGroup>

```

Here is the client code: 
```

var connection = new signalR.HubConnection('/appEvents', { logger: signalR.LogLevel.Trance });

conn.on("ReceiveEvent", (appEvent) =>
{
    console.log(appEvent);

    const li = document.createElement("li");
    li.textContent = JSON.stringify(client);
    document.getElementById("processEvents").appendChild(li);


});

document.getElementById("askForEvents").addEventListener("click", event => {
    const processId = document.getElementById("processId").value;
    conn.invoke("StartProcessMonitor", processId).catch(err => console.error(err.toString()));
    event.preventDefault();
});

conn.start().catch(err => console.error(err.toString()));
```
 the server code: 
```

 public class AppEventsHub : Hub
    {
        
        public async Task StartProcessMonitor(int processId)
        {
                   var processDetail = .... 
                   await Clients.All.SendAsync("ReceiveEvent", processDetail);
        }
  }

```

and the server startup code where I comment the call to SetCompatibilityVersion(CompatibilityVersion.Version_2_1) because I was following the sample on the aspnet site:~
 
```

  public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddMvc();//.SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services.AddSignalR();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();

            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseSignalR(routes => routes.MapHub<AppEventsHub>("/appEvents"));
            
            app.UseMvc();
        }
```
 here are the logs from the kestrel console: 
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\vitor.paulino\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: C:\Users\vitor.paulino\source\repos\AspNetSamples\FirstSignalR
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
 HttpsConnectionAdapter[1]
      Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__48_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__9.MoveNext()

looks like it is missing support to HTTPS.... Im missing any step to get a valid certificate to test this app locally? 
VisualStudio generated one for me and is correctly installed as seen in the print screen: 

![devcert](https://user-images.githubusercontent.com/859157/40315145-7c98fb90-5d12-11e8-9a88-e132730fcbd9.png)

BTW: Great job on this framework.  :)

**Comment by BrennanConroy** [comment]
Your client and server need to be the same version, looks like you're using rc1 for client and preview1 for server right now.

**Comment by anurse** [comment]
If you're using an RTM build of the client, you can't use the `HubConnection` constructor directly, you have to use `HubConnectionBuilder`. See the documentation for guidance: https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1

**Comment by vpaulino** [comment]
thks @anurse ! 

But the error is still happening... what is the correct version of the client to match with server version ? and where can I get it ?
This is what is listed from the dotnet npm dev registry; 
![image](https://user-images.githubusercontent.com/859157/40352757-9c075f54-5da7-11e8-9665-7b33188b36c1.png)

But the complete version name is truncated.

And from the public registry looks like the problem is the same: 
![image](https://user-images.githubusercontent.com/859157/40352879-f62344b2-5da7-11e8-81d1-ed78fea40a26.png)

**Comment by anurse** [comment]
The version numbers should match precisely, client and server. So if you are using `1.0.0-foobar-123` on the server you should use the same version on the client. However, remember that RTM builds are not currently on NuGet.org/NPM, so you need to use the internal registry described here: https://github.com/aspnet/SignalR#packages

**Comment by anurse** [comment]
If you are using RC1 (the latest supported version), then the versions numbers you want are `1.0.0-rc1-final` on the server and `1.0.0-rc1-update1` on the client

**Comment by vpaulino** [comment]
Hi there,

Seems to work now ! thks! 

Just some side notes that may help: 

If you just update the nuget packages and npm packages you will get an error when trying to run the project, something like this: 

![image](https://user-images.githubusercontent.com/859157/40414398-01638de6-5e70-11e8-8098-eb33975f2d57.png)

because there is no framework to support those metapackages ( those are metapackages right ?) you still need to install the framework with this  sdk :

![image](https://user-images.githubusercontent.com/859157/40414189-7d369d74-5e6f-11e8-8a48-45e046d6da2d.png)

After the installation it should appear in the dotnet sdk folder the new framework that support the new metapackages: 
![image](https://user-images.githubusercontent.com/859157/40414475-33af1180-5e70-11e8-9ecd-058497224c94.png)


at the end with the correct framework and metapackages and npm packages all should work.
