### ISSUE TITLE
[2.1.1] NegotiateProtocol doesn't handle responses with null AvailableTransports

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2342]
Consider taking https://github.com/aspnet/SignalR/issues/2133 for 2.1.1

**Comment by anurse** [comment]
As far as I can tell, this isn't really blocking a customer scenario right? This would only affect someone using the NegotiateProtocol code themselves for some other purpose.

**Comment by JamesNK** [comment]
Correct. IMO this is a low priority change. It could easily wait for 2.2

**Comment by anurse** [comment]
Withdrawing from 2.1.1
