### ISSUE TITLE
Automatically test old clients against the latest server

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2346]
Old versions of SignalR clients (C#/TS) should work with the latest server version. Need an automated way to test this.

e.g. 2.1 C# client should continue to work against 2.1.1 server.

Should be extensible so as to support as many future clients as required for the future.

e.g. 2.1 and 2.1.1 C# clients should continue to work against 2.2 SignalR server.

**Comment by davidfowl** [comment]
I'm not sure how important this is to automate if there's no protocol changes. What exactly is this test trying to verify?

**Comment by anurse** [comment]
How do we know if there's no protocol change? Also, there are definitely behavioral changes that could break older clients.

**Comment by davidfowl** [comment]
I dunno, I'm not warm to this idea because I think it won't happen, but we can measure the amount of work required to do this and the ROI

**Comment by anurse** [comment]
We don't think this is worth the cost right now. We'll react if necessary
