### ISSUE TITLE
[2.1.1 Tracking] Websocket connection closes with error code 1007

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2349]
Consider taking https://github.com/aspnet/SignalR/issues/2323 for 2.1.1

**Comment by anurse** [comment]
This is a tracking issue, we just need to track that https://github.com/dotnet/corefx/pull/29840 goes in to 2.1.1

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/corefx/pull/29853

**Comment by anurse** [comment]
The corefx issue was approved by Shiproom. Leaving this open until we confirm it's in and merged. @BrennanConroy do you have any test code you could run to verify that the fix is in 2.1.1 when we get a build?

**Comment by BrennanConroy** [comment]
Yes

**Comment by BrennanConroy** [comment]
Verified that the fix is in
