### ISSUE TITLE
Allow HubConnection to take a SynchronizationContext on which to invoke On handlers

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2350]
This is super useful in UI scenarios. Usually you want to be able to affect your UI in the `On` handler, but you need a Sync Context to get back on the UI thread.

**Comment by JamesNK** [comment]
Is this done in any other .NET library? From my experience with UWP calling to the dispatcher is fairly common and not a big deal.

**Comment by anurse** [comment]
@DamianEdwards mentioned we either did this in ASP.NET SignalR or had guidance for doing something like this. This is also something we've talked about for a while. It certainly could be the case that most users will want to do additional processing in the `On` handler before transitioning to the UI thread though. We can probably leave this until we get feedback

**Comment by davidfowl** [comment]
We didn't do this in ASP.NET SignalR but discussed it at length https://github.com/SignalR/SignalR/issues/972

**Comment by davidfowl** [comment]
We should wait for feedback, backlogging this

**Comment by anurse** [comment]
Closing this, waiting for feedback.
