### ISSUE TITLE
Why getting negotiate text in hub URL

### ISSUE THREAD

**Issue by OmprakashAmarwal** [aspnet/SignalR#2369]
### Getting negotiate text after hub name in URL
I have installed Client SignalR using.
        npm i @aspnet/signalr
And my component like this
        import { HubConnectionBuilder } from '@aspnet/signalr';

       export class SignalRComponent implements OnInit {
         _hubConnection: any;
  
       ngOnInit() {
       
       //SignalR Hub Connections
       this._hubConnection = new HubConnectionBuilder().withUrl('http://localhost:5000/message').build();
      
       this._hubConnection.start().then(() => {

       let connectionID = this._hubConnection.connection.connectionId;
       console.log('MessageHub Connected');
       console.log('Connection ID ' + connectionID);

       }); 
       }
      }

## My server is on 5000 Port with message Hub
  it's working with
     "@aspnet/signalr-client": "^1.0.0-alpha2-final",

While i'm connecting with hub then i am getting this.
![image](https://user-images.githubusercontent.com/22167026/40489989-13fc6928-5f88-11e8-9448-3db28786a9f0.png)

:5000/message/negotiate:1 Failed to load resource: the server responded with a status of 404 (Not Found)

I don't know why negotiate text is present in server url.
Please let me know if i'm making mistake.

**Comment by OmprakashAmarwal** [comment]
it means @aspnet/signalr works with Microsoft.AspNetCore.SignalR --version 1.0.0-rc1-final ??

**Comment by davidfowl** [comment]
Yes. Actually "@aspnet/signalr-client" is deprecated https://www.npmjs.com/package/@aspnet/signalr-client:

![image](https://user-images.githubusercontent.com/95136/40528155-a788e10a-5fa4-11e8-98ae-e97e641e1774.png)

**Comment by OmprakashAmarwal** [comment]
Hello @davidfowl  
I updated Client and server as well. now i can connect with hub server. but could you please let me know how can i get connection id in Client side. since we are using 
       this._hubConnection.connection.connectionId;

**Comment by anurse** [comment]
It is not possible to get the connection ID from the client, as it is not a good way to identify a connection outside of the single server on which the connection exists. If you need to be able to identify a set of clients, add the connection to a group using `Groups.AddAsync` in the Hub and then use `Clients.Groups(groupName)` to send to the group.

**Comment by davidfowl** [comment]
We don't expose the connection id on the client.

**Comment by OmprakashAmarwal** [comment]
But in case I have to send a message to a specific connection Id then how would I able to send the message.
Could you please provide private chat code ?

**Comment by anurse** [comment]
If you're using authentication, you can use `Clients.User(userName)` to send to all connections for a particular user ID.

If you aren't using authentication, we'd need to know more about how users are identified in your system to be able to provide guidance. On the server, you just need to add the connection to a named group using `Groups.AddAsync`, in whatever Hub code you use to identify a user. How were you using connection ID before? The sample code you provided above only used it for logging.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
