### ISSUE TITLE
rc1-final and update-1 not working on Azure App Service

### ISSUE THREAD

**Issue by matteo-mosca** [aspnet/SignalR#2371]
* Versions of Server-Side NuGet Packages: 1.0.0-rc1-final
* Versions of Client-Side NuGet/NPM Packages: tried both 1.0.0-rc1-final and 1.0.0-rc1-update1
* Are you using the C# client or the JavaScript client: JS client in Angular application
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Azure Web App
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):  Chrome

Since I updated my software to rc1-final it stopped working in Azure environment.

I have two distinct applications, server app with Signalr package from nuget, and client app with js client from npm, and I have CORS setup accordingly.

Prior to this version everything worked fine both locally (different ports) and on Azure Web App (2 distinct web apps on different hostnames, again with CORS setup).

Now with this version everything works locally, so I didn't notice anything was wrong until I updated my staging environment on Azure.

Now it cannot open any type of connection:
* Error during WebSocket handshake: Unexpected response code: 404
* Error: Failed to start the transport 'WebSockets': undefined
* Error: Failed to start the transport 'LongPolling': Error
* Error: Failed to start the connection: Error: Unable to initialize any of the available transports.

The same code locally with "ng serve" for the client and IIS express for the server works perfectly.

I tried to rollback to 1.0.0-preview2-final on both server and client and everything started working again.

**Comment by matteo-mosca** [comment]
ARR Affinity is already enabled on both server and client Azure Apps, so that's not the current problem.

**Comment by anurse** [comment]
Ok, that helps :). Can you get server and client-side logs as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) ?

**Comment by matteo-mosca** [comment]
I think I can, but not now. Tomorrow from the office I will be able to produce them. Thanks.

**Comment by matteo-mosca** [comment]
[steelchihuahua-client-staging.azurewebsites.net.har.txt](https://github.com/aspnet/SignalR/files/2037311/steelchihuahua-client-staging.azurewebsites.net.har.txt)
For the client side, I already managed. Server side will need to wait until tomorrow.

**Comment by matteo-mosca** [comment]
I'm still working on getting the Azure log, but for now I can produce my server side application log, which reports no errors on the hub negotiation phase:

2018-05-24T16:40:17.3511072+00:00 0HLE1IE7TKAV2:00000004 [INF] Request starting HTTP/1.1 OPTIONS http://steelchihuahua-server-staging.azurewebsites.net/companies/negotiate?jwttoken=[redacted]   (ca22a1cb)
2018-05-24T16:40:17.3512409+00:00 0HLE1IE7TKAV2:00000004 [INF] Policy execution successful. (0204925d)
2018-05-24T16:40:17.3515402+00:00 0HLE1IE7TKAV2:00000004 [INF] Request finished in 0.5992ms 204  (791a596a)

**Comment by davidfowl** [comment]
@matteo-mosca the diagnostic guide @anurse pointed you at here explains how to get much more detailed SignalR logs https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide

**Comment by matteo-mosca** [comment]
As I was saying, I was working on it. Here's the application log from Azure.
[diagnostics-20180525.txt](https://github.com/aspnet/SignalR/files/2038328/diagnostics-20180525.txt)

**Comment by anurse** [comment]
I see the WebSocket requests being sent from the client but nothing matching that in the server logs. Were these collected for the same activity?

Can you provide a code snippet illustrating how you are connecting on the client?

**Comment by matteo-mosca** [comment]
They were not collected in the same activity, but in an equivalent one, meaning a simple browser refresh on the homepage, post login, which is made with a normal WebAPI controller and does not involve SignalR in any way. SignalR is only used in the secured portion of the web application, not in the public part.

The client connection code:

`this.hubConnection = new HubConnectionBuilder()
            .withUrl(environment.serverUrl + "/" + hubPath + "?jwttoken=" + this.token.stringToken)
            .configureLogging(LogLevel.Debug)
            .build();`
`this.hubConnection
            .start()
            .then(() => {
                this.ready.next(true);
                this.ready.complete();
                console.log("Connection started!");
            })
            .catch(err => console.log("Error while establishing connection"));`

this.ready is just a Subject that I expose so the callers can wait for the hub to be connected before sending requests.

**Comment by BrennanConroy** [comment]
>but in an equivalent one, meaning a simple browser refresh on the homepage, post login, which is made with a normal WebAPI controller and does not involve SignalR in any way.

Could you clarify this part, you didn't use SignalR to create the server logs?

Do you happen to have MVC before SignalR in the middleware pipeline and do they share routes?

**Comment by matteo-mosca** [comment]
It was all done with SignalR, just in 2 different moments, but the same action was taken.

SignalR is before MVC in the middleware configuration and they do not share routes. MVC is used for a single controller and there's only one specific route mapped for it.

Anyway I upgraded to 1.0.0 today along with .Net Core 2.1 and the problem's gone, I don't really know what that was, but right now it's ok.

I think you can close this issue.

**Comment by anurse** [comment]
Ok, let us know if it comes back!
