### ISSUE TITLE
Server messages don't reset ping window

### ISSUE THREAD

**Issue by DylanDmitri** [aspnet/SignalR#2372]
Server sends keep-alive pings to the client.

Intended behavior (from [HubProtocolReadme](https://github.com/aspnet/SignalR/blob/dev/specs/HubProtocol.md))

> a Ping frame is only sent if 15 seconds elapses since the last message was sent. 

However, currently only pings reset this window. The server pings consistently every ~15 seconds, regardless of other activity.

The only current ping reset is in ```HubConectionContext.KeepAliveTick``` line 453

```
                Interlocked.Exchange(ref _lastSendTimestamp, currentTime);
```

This reset should also happen whenever any message is sent.

**Comment by DylanDmitri** [comment]
Seems like everything goes through the duplex pipe ```_connectionContext.Transport.Output```.

sometimes ```Output.Write(thing)```

sometimes ```Other.Write(message, Output)```

Can't put a reset in here. Probably need to put it in multiple ```HubConnectionContext``` methods, which feels bad.

**Comment by DylanDmitri** [comment]
nevermind, looks like putting it in both ```WriteCore``` methods will work

**Comment by DylanDmitri** [comment]
```ValueTask,ContinueWith``` isn't a thing, so can't really put it in ```WriteCore```. Going for ```_writeLock.release()``` instead...

**Comment by DylanDmitri** [comment]
Approach is successful, however this gets tangled in the ping sending changes in the ```ping catcher``` branch, so will include this fix in that branch.

**Comment by anurse** [comment]
This was done in https://github.com/aspnet/SignalR/commit/3d0f68b22c05b918c4e2637af0d879e34c0b48a2
