### ISSUE TITLE
Disable AppVeyor

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2376]
We has a Jenkins now and it is faster (usually).

* [ ] Disable AppVeyor (@pranavkm , @ryanbrandenburg and/or @natemcmaster can help here, I don't know if there's a switch we need to throw or if just deleting the YAML file will do it)
* [ ] Delete `appveyor.yml` files

**Comment by natemcmaster** [comment]
@Eilon has to throw a switch. Just deleting the file isn't enough

**Comment by anurse** [comment]
That's kinda what I thought, deleting the file would just remove all our customizations. I'll send an email.

**Comment by anurse** [comment]
Email sent

**Comment by JamesNK** [comment]
Done?

**Comment by mikaelm12** [comment]
Yup! Done
