### ISSUE TITLE
How to complete External Notification in SignalR Core

### ISSUE THREAD

**Issue by LGinC** [aspnet/SignalR#2377]
In AspNet SignalR, I can use `GlobalHost.ConnectionManager.GetHubContext<ChatHub>()` to get a Hub,

but I can not find the API in AspNetCore SignalR.

**Comment by OmprakashAmarwal** [comment]
I am working in core WebAPi and it's working fine for me please Configure route for SignalR hub in Startup.cs file in Configure method like this.

        public void Configure(IApplicationBuilder app)
        {
             app.UseSignalR(route =>
            {
                route.MapHub<ChatHub>("/message");
            });
            app.UseMvc();
        }

**Comment by blahblehblah** [comment]
Simply inject it in the constructor

**Comment by anurse** [comment]
Yeah, just inject `IHubContext<ChatHub>` into your constructor using dependency injection. `GlobalHost` only existed in ASP.NET SignalR as a workaround because we didn't have any DI system :)

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
