### ISSUE TITLE
camelCase - RC1

### ISSUE THREAD

**Issue by blahblehblah** [aspnet/SignalR#2378]
Alpha version had >
services.AddSignalR(o =>
{
    o.JsonSerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
});

Any update on the RC1?

**Comment by BrennanConroy** [comment]
RC1 enables CamelCase by default

**Comment by anurse** [comment]
If you are asking how to configure JSON options in RC1, you use the `AddJsonProtocol` method to configure JSON options:

```csharp
services.AddSignalR()
    .AddJsonProtocol(options => ...)
```

**Comment by blahblehblah** [comment]
@BrennanConroy Api return's camelCase, however not on the SignalR side, 

Result > 
`Avatar
:
"http://i.pravatar.cc/100"
ConnectionId
:
"wQad4lhPErW3tyh9q-9h8w"
Nickname
:
"sdAD4"`

I am using the MessagePack protocol.

**Comment by anurse** [comment]
MessagePack is configured using an `options => ...` lambda in `.AddMessagePackProtocol`. You configure formatter resolvers, see the [repository for the MessagePack-CSharp library we use](https://github.com/neuecc/MessagePack-CSharp/#extension-pointiformatterresolver) for more documentation on those.

Note that currently MessagePack-CSharp has a limitation that it **cannot** deserialize a `camelCase` MessagePack object into a `PascalCase` .NET object by default. This is being tracked here: https://github.com/neuecc/MessagePack-CSharp/issues/220

As a workaround, you can decorate your .NET class with attributes so MessagePack can properly deserialize them, see https://github.com/neuecc/MessagePack-CSharp/#object-serialization for details.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
