### ISSUE TITLE
Move Utf8BufferTextReader to corefx

### ISSUE THREAD

**Issue by darkl** [aspnet/SignalR#2386]
Hi,

I was wondering if it would be possible to move Utf8BufferTextReader and Utf8BufferTextWriter to corefx and make them public, so other libraries could consume them. These depend on System.Memory and System.Buffers.

Thanks!
Elad

**Comment by JamesNK** [comment]
Hi. It is not up to us to make that decision. Raise an issue on the corefx repo and the team who maintain corefx will consider whether those types would be useful for general users.

**Comment by darkl** [comment]
Will do.
BTW, How do you guys expect people to use System.IO.Pipelines in order to implement their own protocols? Given that these classes are internal and the fact the examples call the ToArray() method, it is likely that people would implement their protocols in an inefficient way.
Not criticizing you guys, just wondering.

**Comment by davidfowl** [comment]
Copying our code until we add more bcl types. Things like this take time to permiate through the ecosystem. That’s why there’s so much custom code in here.

**Comment by JamesNK** [comment]
There is nothing stopping you from copying Utf8BufferTextReader and Utf8BufferTextWriter into your own implementation.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
