### ISSUE TITLE
Connecting from JS using websocket connection fails to open connection (works from c# client)

### ISSUE THREAD

**Issue by rolfwessels** [aspnet/SignalR#2389]
## Behaviour
When connecting to local SignalR service from js client it immediately gives and error on the console.
`Error while establishing connection :( WebSocket is not in the OPEN state`
Then a few seconds later it says `Error: Server returned handshake error: Handshake was canceled.`

## Expected
Should connect. (Using the C# client connection to same service works consistently)

## Setup
* NuGet Microsoft.AspNetCore.SignalR 1.0.0-rc1-final
* NPM @aspnet/signalr: ^1.0.0-rc1-update1
* The c# client works with same service but the JS one does not
* The Server:Kestrel
* OS server & client Windows
* Browser: Chrome

## Steps to reproduce.
Checkout https://github.com/rolfwessels/CoreDocker
`src\CoreDocker.Website\dotnet run`
Checkout https://github.com/rolfwessels/CoreDocker.Website
`npm run start`

## Console logs
[server-console-output.txt](https://github.com/aspnet/SignalR/files/2041604/server-console-output.txt)
[js-client-console-output.txt](https://github.com/aspnet/SignalR/files/2041605/js-client-console-output.txt)
[localhost.har.txt](https://github.com/aspnet/SignalR/files/2041608/localhost.har.txt)

**Comment by anurse** [comment]
Can you show the code you are using to start the JavaScript client? I can't search the repository you linked because it's a fork, and the code looks very complicated so I wasn't able to find the SignalR initialization logic in there. I wasn't able to find the "chat.component.ts" file referenced by the error message in GitHub file search either.

**Comment by rolfwessels** [comment]
Sure, the code is [here ](https://github.com/rolfwessels/CoreDocker.Website/blob/coredocker/develop/src/app/pages/chat/chat.component.ts#L18)

```
ngOnInit() {
    this.connection = new HubConnectionBuilder()
      .configureLogging(LogLevel.Trace)
      .withUrl('http://localhost:5000/chat')
      .build();
    this.connection.on('send', data => {
      console.log(data);
    });
    this.connection.onclose((e) => {
      console.log('Connection closed!', e);
    });
    console.log('Trying to connect to hub!');
    this.connection.start()
      .then(() => {
        console.log('Connection started!');
        this.connection.send('send', 'csad');
      })
      .catch(err => console.log('Error while establishing connection :(', err));

  }
```

**Comment by anurse** [comment]
Hrm, not seeing anything out of the order there. The suspicious thing to me is that your client logs have

```
chat.component.ts:36 Error while establishing connection :( WebSocket is not in the OPEN state
```

Which indicates that the WebSocket failed to connect and we missed it somehow. But the server logs do show a WebSocket request (the `101` status code gives it away):

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/chat?id=plyTtsCQ_7Qc8JJEPBP4Bg
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      Policy execution successful.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 15120.5968ms 101
``` 

Can you turn up the log level for SignalR on the server? There are instructions for doing that in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#server-side-logging). Also, if you could collect a [Fiddler Trace](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#fiddler-windows-and-macos) that would also help. The HAR file from the browser dev tools is easy to get and has some information, but misses some things that Fiddler does a better job of capturing.

If you'd like, you can send the traces to me via email using `[my github username]@microsoft.com`. That might be easier for sending the fiddler traces. Make sure to reference this issue :).

**Comment by rolfwessels** [comment]
Thanks for the response. So as you can see from the settings [here](https://github.com/rolfwessels/CoreDocker/blob/develop/src/CoreDocker.Api/appsettings.json). Logging was already was set to trace already. When I set the microsoft setting to `Warning` it works but I don't see more signalR info than already presented. I will spend some time to figure out why that is.

Will send the fiddler trace.

**Comment by anurse** [comment]
I was able to run your application and something in the libraries you are using is replacing the global `WebSocket` class with something that doesn't properly implement `WebSocket.OPEN`, thus we don't recognize the socket as open and throw this error. It seems something in `zone.js` is replacing `WebSocket.OPEN` with a function, which means we can't work correctly because the WebSocket type is broken. I suggest filing an issue with `zone.js` to resolve this, since they are the ones replacing WebSockets. As a workaround, you can use a different transport on the client.

As an example, in the console window of a normal empty Chrome Tab:

![image](https://user-images.githubusercontent.com/7574/40796199-232b9f3c-64b9-11e8-8968-19e46622f287.png)

But in the console window for your site:

![image](https://user-images.githubusercontent.com/7574/40796217-32d96608-64b9-11e8-8846-188fdb493c62.png)

**Comment by rolfwessels** [comment]
Thanks. I will look into it.

**Comment by anurse** [comment]
Cool. I'm going to close this for now, but feel free to comment further with what you find out! We can re-open if there is something we can fix to make this work better.

**Comment by rolfwessels** [comment]
So after some investigation it seems `zone.js` is a required component of Angular 5. 

I'm actually not convinced that it is zone.js. 
1) I commented out the zone.js include and still had OPEN as function
2) I created a new angular cli project (it included zone) with none of the theme stuff and ran `typeof WebSocket.OPEN` and it was number .

I will try to dig a bit deeper to see if I can pin point the issue.

I found a quick work around by just adding before trying to connect. :-)
` Object.defineProperty(WebSocket, 'OPEN', {    value: 1,  });`

Thanks again for looking into it. Really appreciate it.

**Comment by anurse** [comment]
The only thing that led me to zone was that when I was running the application I added a Watch on `window.WebSocket` in the debugger and one of the properties of the function indicated `zone.js` as the place the function was "defined" but I wasn't familiar enough to figure out exactly why that was happening :). It's very possible it was `zone.js` *in combination with* some other library. It would certainly be useful to isolate down to the thing that was causing it if you have the time to try that out, but if not that's just fine. Glad you found a solution that works for you!
