### ISSUE TITLE
Issue With Typed Hubs for AzureSignalR

### ISSUE THREAD

**Issue by bsampica** [aspnet/SignalR#2390]
I believe this to be a bug in the AzureSignalR package.

To recreate:

```
public interface ITypedHub 
{
     Task HubMethod(string data);
}

public class MySuperHub<ITypedHub> :  Hub
{

}

services.AddSignalR(options => options.EnableDetailedErrors = true).AddAzureSignalR();

app.UseAzureSignalR(routes => {
      routes.MapHub<MySuperHub<ITypedHub>>("/signalr/superhub");
}

Error:  Cannot establish web socket connection.

**Comment by BrennanConroy** [comment]
Looks like an issue with the Azure SignalR Sdk, could you file the issue here: https://github.com/Azure/azure-signalr

I think the hubname needs to be url encoded like we do here: https://github.com/aspnet/SignalR/blob/9b2e48fdf20a76e25a2f35a4b60b04959f09ffa2/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionManager.cs#L105

**Comment by davidfowl** [comment]
While there’s a bug here that’s not quite how types hubs work. The signature usually looks like:

MyTypedHub : Hub\<ITypedHub\>

**Comment by bsampica** [comment]
Sorry, yes that’s correct. My psudeo code was just typed wrong.

On May 26, 2018, at 10:09 PM, David Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:


While there’s a bug here that’s not quite how types hubs work. The signature usually looks like:

MyTypedHub : Hub<ITypedHub>

**Comment by davidfowl** [comment]
Then how is it breaking?

**Comment by bsampica** [comment]
When working with a typed hub, it will break the connection. I believe someone above said because of the URL?  Needs to be URL encoded.

On May 26, 2018, at 10:26 PM, David Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:


Then how is it breaking?

**Comment by davidfowl** [comment]
Can you specify the actual code snippet? The call to MapHub should not contain generic arguments (which is likely the problem) when using types hubs.

Are you intentionally trying to use a generic hub?

**Comment by bsampica** [comment]
Yea so that’s likely the issue. If you’re using a typed hub context it’s Hub<T>

Which means we have to use MyHub<T> : Hub<T>

So the Routes.MapHub<MyHub<IMyType>>() causes the issue.

If that’s just not supported right now, no big deal.

On May 27, 2018, at 6:38 AM, David Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you specify the actual code snippet? The call to MapHub should not contain generic arguments (which is likely the problem) when using types hubs.

Are you intentionally trying to use a generic hub?

**Comment by davidfowl** [comment]
Right that’s the bug, I’m mostly asking why you hub is generic to begin with.

**Comment by bsampica** [comment]
Oh, yea...

We have a lower layer called our Real-time Provider, that sends either SMS ( push notifications through azure ), MQTT, and or SignalR.  They share an interface cause the calling code sends a “real-time” message but doesn’t care which transport, and then the layer decides how it goes out.

Then secondary, our testable surface for unit tests, though I’ve been working on converting those tests that implement the generic hub to MyHub<dynamic> : Hub<dynamic>.

On May 27, 2018, at 7:09 AM, David Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:


Right that’s the bug, I’m mostly asking why you hub is generic to begin with.

**Comment by anurse** [comment]
Ahhh gotcha, thanks for clarifying!

**Comment by davidfowl** [comment]
This issue was moved to https://github.com/Azure/azure-signalr/issues/113
