### ISSUE TITLE
Contex.User is null when not in debug session. 

### ISSUE THREAD

**Issue by KennethInfoEasy** [aspnet/SignalR#2392]
I'm using 2.1.0-rc1. I'm having an issue when not using a debugged instance of the HUB. 
Context.User is empty on connect. In debug the application works as expected.

I'm on IIS 10.0.16299.15. The error occurs just after the handshake has occured: 

Utils.ts:169 Debug: Starting HubConnection.
Utils.ts:169 Debug: Starting connection with transfer format 'Text'.
Utils.ts:169 Debug: Sending negotiation request: http://localhost/NO.Auto.EDI/print/negotiate
Utils.ts:169 Debug: Selecting transport 'WebSockets'
Utils.ts:169 Trace: (WebSockets transport) Connecting
Utils.ts:165 Information: WebSocket connected to ws://localhost/NO.Auto.EDI/print?id=YyzECr-RG6t8fEMYoDVzHA
Utils.ts:169 Debug: Sending handshake request.
Utils.ts:169 Trace: (WebSockets transport) sending data. String data of length 32.
Utils.ts:165 Information: Using HubProtocol 'json'.
Utils.ts:169 Trace: (WebSockets transport) data received. String data of length 3.
Utils.ts:169 Debug: Server handshake complete.

The error is: Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error. ArgumentNullException: Value cannot be null.
Parameter name: userName'. from Utils.ts:159

The Context.User is empty on my on
 [Authorize]
        public override async Task OnConnectedAsync()
        {
 var username = Context.User.Identity.Name;
}

Some of my services used: 
services.AddConnections();
services.AddSignalR(options => { options.EnableDetailedErrors = true; options.KeepAliveInterval = TimeSpan.FromSeconds(10); });
services.AddAuthentication()
            .AddCookie(builder => builder.Cookie.Name = "Test");
            services.AddAntiforgery();

Any Ideas?

**Comment by KennethInfoEasy** [comment]
I think i found it. It seems like the debug session where a different application pool then the web application was setup againt.. Seems to be working now after changing the apps default application pool.

**Comment by KennethInfoEasy** [comment]
It was not the application pool. does someone have a hint of why the Context.User would be null even if i'm logged in?

**Comment by KennethInfoEasy** [comment]
New info: Problem do not occure in IE 11.461.16299.0 but in chrome Versjon 66.0.3359.18. I have not tested with other browser yet

**Comment by davidfowl** [comment]
The usual error is that you don’t put the call to UseAuthentication before UseSignalR

**Comment by KennethInfoEasy** [comment]
I need to check that ,,, But i have this in my code: 

  app.UseAuthentication(); //Must be before mappings (url) and hubs

And it is before use SignalR.. But it works in Edge and IE , not in Chrome.

**Comment by davidfowl** [comment]
You don’t have a default authentication scheme specified in your configuration. Can you put a simple repro project on GitHub?

**Comment by KennethInfoEasy** [comment]
@davidfowl  Ive tried to reproduce this outside of this project . even in this project it worked for a while.  now it is persisent in this project, but only in chrome. The thing that beats me is that Context.User is null even if i'm logged in.  Standard ASP .net Identity with a slighty extended IdentityUser. (couple of extra properties).

**Comment by KennethInfoEasy** [comment]
@davidfowl  Now i see what you are saying.. I use this: 
    services.AddAuthentication()
            .AddCookie(builder => builder.Cookie.Name = "someName");
  services.AddAntiforgery(options => options.Cookie.Name = "someName");

**Comment by KennethInfoEasy** [comment]
@davidfowl: The problem is also in Firefox.

**Comment by KennethInfoEasy** [comment]
@davidfowl  I think i'm getting closer to the real issue. The error 'Error: Server returned an error on close: Connection closed with an error. ArgumentNullException: Value cannot be null.
Parameter name: userName'. from Utils.ts:159 is from UserManager which tries to load the identity of a null user name.  

The real issue is that Context.User is null.. I stripped alot of code and now i have a hub with only the onConnectedAsync. 
`'   [Authorize]
        public override async Task OnConnectedAsync()
        {
            var username = Context.User.Identity.Name;
            await base.OnConnectedAsync();
        }`

I'm connected and Context.ConnectionId is giving a connectionId. Context.IsAuthenticated is false, Context.User.Identity.Name is null. For me now it seems like HttpContec (From GetHttpContext) is not returning the logged in User context.

**Comment by davidfowl** [comment]
Ah put he attribute on the hub itself not on the OnConnectedAsync method, that doesn’t have any effect. That way unsuthenticated users won’t be able to connect (which is what I assume your goal is)

**Comment by KennethInfoEasy** [comment]
@davidfowl Thanks for the suggestion. I moved it. The result as before works on IE and Egde, Chrome and Firefox now gives error: 
`Failed to complete negotiation with the server: error: unauthorized utils.ts:159
Failed to start the connection: error: unauthorized util.ts:159`

So the issue is the authorization break in chrome and firefox, but why ?

**Comment by davidfowl** [comment]
Do you have the right auth cookie? From what I glanced at the code snippet above , it looks like you’re using cookie auth?

**Comment by KennethInfoEasy** [comment]
@davidfowl I am yes. And I should since it working IE and Edge. But I just saw something strange,, maybe it is a clue, or making it more confusing. If i start on the hub url (http://localhost/myApp/myHub/) it redirects me to the login page (which i must always use for myApp). Then i works. Could this help narrow it down?

**Comment by KennethInfoEasy** [comment]
@davidfowl Just confirmed that both in FireFox and Chrome if I first navigate to: http://localhost/myApp/myHub/negotiate which redirects me to the login page then It works.

**Comment by KennethInfoEasy** [comment]
Reproduce the error in this project. https://github.com/KennethInfoEasy/mySignalR

**Comment by KennethInfoEasy** [comment]
Hi, Any suggestions here ? I'm stuck. @davidfowl  @anurse . 
Btw thanks for all the help so far. I appreciate it

**Comment by davidfowl** [comment]
A few things before I dig into this project:

- It's using .NET Core 2.0 and attempting to use ASP.NET Core 2.0 when in reality, you need to use ASP.NET Core 2.1. I recommend switching to the ASP.NET Core 2.1 rc1. Or wait a few days for the final version of 2.1 and upgrade to that. Or if you can't wait, there's an EAP of 2.1 here https://github.com/aspnet/Home/wiki/2.1.0-Early-Access-Downloads.
- Why does your antiforgery cookie and authentication cookie have the same name? https://github.com/KennethInfoEasy/mySignalR/blob/eebab183149afc856b00b1999cabccc73a864201/SignalRAuth/Startup.cs#L44-L45
- Why do you call `AddCookie` at all, you're already using `AddIdentity`. It might be harmless though, it seems like you're not actually using it anywhere.
- Why did you change the keep alive interval? https://github.com/KennethInfoEasy/mySignalR/blob/eebab183149afc856b00b1999cabccc73a864201/SignalRAuth/Startup.cs#L34
- https://github.com/KennethInfoEasy/mySignalR/blob/eebab183149afc856b00b1999cabccc73a864201/SignalRAuth/wwwroot/Scripts/TestHub.js#L2. I see you're running on full IIS. Does the problem reproduce when using just kestrel?

**Comment by KennethInfoEasy** [comment]
@davidfowl Thank for your comments. 

- I've updated the project settings to reflect the correct SDK which was referenced.
- The AntiForgery is has now another name. 
- In the orginal project i'm using cookies to allow an external client to use an api for login. This works fines, but I included in the testproject so you could see the startup services used. 
- The keep alive interval is changed only because of debug/trace. 
- The issue seems to be in kestrel also.

**Comment by davidfowl** [comment]
> I've updated the project settings to reflect the correct SDK which was referenced.

Awesome!

> The AntiForgery is has now another name.

You also don't need to explicitly add it since MVC adds it. Did you do so to configure the cookie name?

> In the orginal project i'm using cookies to allow an external client to use an api for login. This works fines, but I included in the testproject so you could see the startup services used.

My point is that identity already configures cookies and you're doing so again. The project is using identity for cookies and this additional cookies authentication scheme you added isn't being used at all, so you can remove it.

> The issue seems to be in kestrel also.

Great, that simplifies things.

**Comment by KennethInfoEasy** [comment]
@davidfowl 

> 
You also don't need to explicitly add it since MVC adds it. Did you do so to configure the cookie name?

Yes, but only as part of the troubleshooting. 

> My point is that identity already configures cookies and you're doing so again. The project is using identity for cookies and this additional cookies authentication scheme you added isn't being used at all, so you can remove it.


I will remove it to see if this is the issue (because it feels like something like that).

**Comment by KennethInfoEasy** [comment]
@davidfowl 
It works in kestrel sorry. I had an typed url to the IIS instance of the hub. changed to relativ path and now kestrel works. Not getting the IIS instance to work though.

**Comment by KennethInfoEasy** [comment]
This is the current situastion.. All work in a running debug session.

When not running debug the only one that is not working is a full IIS : 

Failed to load resource: the server responded with a status of 401 (Unauthorized)
Utils.ts:159 Error: Failed to complete negotiation with the server: Error: Unauthorized
ConsoleLogger.log @ Utils.ts:159
Utils.ts:159 Error: Failed to start the connection: Error: Unauthorized
ConsoleLogger.log @ Utils.ts:159
Orderview.js:10 Error: Unauthorized

**Comment by KennethInfoEasy** [comment]
@davidfowl If i navigate to http://localhost/SignalRAuth/test/negotiate and then login, it works.

**Comment by davidfowl** [comment]
> @davidfowl If i navigate to http://localhost/SignalRAuth/test/negotiate and then login, it works.

Can you look at the browser cookies when you navigate to the negotiate endpoint?

Also you haven't answered, does it also fail the same way when running in visual studio using IIS Express?

**Comment by KennethInfoEasy** [comment]
@davidfowl 
Its actually different

- cookie at http://localhost/myapp/
CfDJ8LvDXR_BoUdAg7rNxNMkvDcLO3YnYYn78oPd5Vdm6My0JqPQUnD_55a7Ie5b_WCD7tNo6s1N8YNHB7WZhxBfoHcuh0FS26aRM56EwkPEa2niWTXz5xSVCmj-MUO7-Gn1ETPmRyvD64rTMr2Amr07oXYoZPu_TtfGl0OTdKkVoVEFQ2K9J3Et0DGGirmcLIAFbGlSyPI86xlKtQU_yn9-IA_EH1ymT5bs_v4a01ItZNm78ZPpWpE-aHVYUNTWvG0sCyFmDdqy1u2DtayHcXzmNUxRyRzVW2CcevWBbESsOXjAa9cN9xA2ZWrbx6TTOvZ5Z05cX5RTRw5QNiSr6zu1hP9Gb0qAJYfF8NbPlOglYW-i5hCHQohkZxnqvj3Jp74qd8tz6PHcDPYXhzv_42L2UPy19UIiDYeugK42uGvXBQaeWnnF8tQFy1ZzjQMaGrcleLeh1jaRO3Yl-9pjacO0Kurc0DKyID6KjzhVLQTYnFJuqkaGQYpN0_JF7dDuJCQ9B_SrxTlpJCkXD1O2DnSdX5lcMT_rNKM_XgWfy2H8mn2HlZOgXoQZ4VtZ3GHO7mt8y1ZCxvUWuu4IEUREOhh5og7qDBtzH9ESSSm-HwQl616DrCl3tpEo-yozF16AzG_2qPfscE-Rg9UHyc3Zll270_Dvsjt332wGtxR_rjEtlys-dEH5cPvGIZsilOaI1BF2KbzNBj_xjSnQ5j6dmOXBbpx7oxswmleWvNPiuUyDypZt_yB-h1B_nMh7O3djg-RPxRmk4tYWDu1gklSQrrrzLGh_deSjcyIlC2HZl7ZHD_Lw

- Cookie at http://localhost/myapp/myhub/negotiate
CfDJ8LvDXR_BoUdAg7rNxNMkvDcepX2IGROejYh_gBwNAXo4Q2ffH1AkDNiiT_j-Q1dZOsZH1YSIH4YYkBeRKFjWD2DUABm0yoVdpwtV5inYNG5JLP0XK_U_hol7ma8iB-wDWkp13LEkfAj1WeONHTO7qIxBr3TnSchsryJ2rmgSYjO7jPu63ZM420l_d3u07UKZMbcRG7C0mZl_b_dXtivkhURGKvIXzeDxBqpKJzj0WyXbchxytjbaQiYL8O5zLBr6vSVN461GmJgeqqSSls3r-0PBxWcw02cVQRXO5Zurhmp0HMQjq2L2OlAvrcufdSXQ8kb6iLziIoaNCY53CLPiWY3ngCzofHpwaCQ9TmmbNnqT8qHbQZgFTOZPS3UZiMbgFfBar8cCJt5rXTBA9npJ304k6-WK6qxW2R2bNXEx7kcwGtlI3T49e8T8_Jny7oP27w9gbkj3OCsHtoIhHFyOZx6YKEp3rCRyz4bNNzyW9rSv8g3GrwLe9owt29lqHVnpU00PGUqMFKHX63djYgizJdaWEqLAiZcipzTTXo5pN980hA1VkAumQCp3xaOYyRZKUzWJcvDoZARpecDHRsgDC5BPvxgiL334zdbG4pqVyzwliAlY4KXUIyXjkfv_no2cR_JuaOnqKMBOchB2hxkQhCi9KnTv2IedNlWs_P9ey1DTpZuXFdohCHa7pEgngYDNUWOAQWDUuCzFxRcxZWkMfNT3WbDEwM0CYzwk_T1EFx7szqJwwfsfEFMF7WRoCBoNCDn7iV8lbjnfkhVeTleo5mmav8TlAuM93Q1DZ_FOU2yh

**Comment by davidfowl** [comment]
So it only fails on full IIS, not IIS express and for some strange reason it's not seeing the existing cookie you do have as an authenticated user. 

If you make a new IIS site, does it just work? I'm wondering if it something to do with your IIS configuration that's special. Can you show all of the cookie details?

**Comment by KennethInfoEasy** [comment]
> So it only fails on full IIS, not IIS express and for some strange reason it's not seeing the existing cookie you do have as an authenticated user.

Your are correct. And that is consistent with the behavior. 

> If you make a new IIS site, does it just work? I'm wondering if it something to do with your IIS configuration that's special. 

I suspect this as well, but cannot prove it. I will try your suggestion. At one point it worked after first setting up the hub. I work on many projects on the same iis server but cannot see how they would be in conflict. I have the app in its own application pool.

**Comment by anurse** [comment]
> It works in EDGE and IE,, not Chrome and Firefox

Sounds like an issue in Server-Sent Events then. That transport is only supported there. Would you be able to collect network traces and server logs as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) ?

**Comment by KennethInfoEasy** [comment]
@anurse 

> Sounds like an issue in Server-Sent Events then. That transport is only supported there. Would you be able to collect network traces and server logs as described in the Diagnostics Guide ?

Yes of course,, I will do that first thing tomorrow at work.

**Comment by mjrousos** [comment]
For what it's worth, I'm seeing a similar issue (Context.User is null in Chrome but not in Edge) but I don't think it's SSE-specific because in my case everything works fine using either WebSockets or SSE when running Kestrel locally but both transports fail (only in Chrome, they work in Edge) when hosted in Azure (Kubernetes) Container Service. I'm trying to dig in more and figure out what could possibly make my hub's user null only when deployed to AKS and with the client running in Chrome. I'll report back if I find anything interesting.

**Comment by mjrousos** [comment]
One more update - it looks like my problem is cookie related. Not sure if this is the same issue @KennethInfoEasy is running into or not but it looks like Chrome is not including the auth cookie returned by the negotiate call in the request to my SignalR hub (but only when hosted in AKS, bizarrely!). Could be an issue in my app; not sure yet. Still investigating...

**Comment by KennethInfoEasy** [comment]
@mjrousos could you try to use the negotiate url of the hub eg: http://localhost/myapp/myhub/negotiate

My experiance is that after this everythings works,, untill i clear the cookies.

**Comment by mjrousos** [comment]
Figured out what was up with my app. As expected, it looks like an issue on my end. The scenario that caused problems was:

* My front-end (and general app API) was served from one domain
* My SignalR backend was from a different domain
* Everything was served over HTTP since I'm just testing things out and hadn't bothered with SSL yet

By default, the auth cookie had a "SameSite: Lax" property meaning that it could only be sent cross-domain if it was sent to as part of a 'safe' request (HTTPS or GET). Since the SignalR connection is established with a POST, the cookie was omitted.

I managed to work around this by modifying my cookie authentication registration:

```CSharp
services.
    AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).
    AddCookie(options => 
    {
        options.Cookie.SameSite = SameSiteMode.None; // The important line
    });
```

Once everything's HTTPS, I expect I shouldn't need this.

I still haven't figured out exactly why Chrome and Edge had different behavior here (still investigating that) but they both work after this work-around.

Not sure if this is the same issue you're seeing, @KennethInfoEasy, but here's hoping :)

**Comment by KennethInfoEasy** [comment]
@mjrousos Mine is all http as well but same "domain" localhost.  Adding the Samsitemode.none was not the solution for me :( But i'm happy it fixed your issue.

**Comment by KennethInfoEasy** [comment]
@davidfowl @anurse 
Hi after yet another day with testing I will try to sum up the issue and suggest a conclusion. If you agree we will just close the issue and move on. 

- It works for all browser when using debug. (Debug/Start debugging (F5))
- It works for all browser when starting from vs (Debug/Start without debugging (Ctrl+F5))
-It works for all browser When published to a webserver (also full iis, not the build from debug.

So it only fails when navigating to the full IIS site from browser it only works for IE and EDGE. Chrome and firefox fails with 401 auth error on the negotiate url. 

I credit my computer, iis setup or some other projects living on the same server with this issue. 

If you want me to investigate further (SSE,Fiddler logs or Cookies) let me know. Thank alot @davidfowl  and @anurse for the assistance.

**Comment by anurse** [comment]
Hrm, I'd still like to figure out what's up. Just so I understand fully, it fails when using Full IIS only, but if you use IIS Express through VS it works fine? Perhaps it is something in your IIS configuration.

Could you collect a Fiddler trace? You can send it to me directly at `[my github username]@microsoft.com` to avoid spamming the thread with this data.

**Comment by KennethInfoEasy** [comment]
> Could you collect a Fiddler trace? You can send it to me directly at [my github username]@microsoft.com to avoid spamming the thread with this data.

I have emailed you the cilentlog and chrome trace as well. Email is marked with subject: 
**Trace data - Contex.User is null when not in debug session. #2392**

**Comment by anurse** [comment]
The first thing I see from the trace is that the cookie has a "path" constraint of `/signalRAuth` but the SignalR request is made to `/SignalRAuth`. I think the path values in cookies are case-sensitive. Can you try ensuring the case matches when connecting to the SignalR endpoint?

**Comment by KennethInfoEasy** [comment]
@anurse @davidfowl 
And that was the whole issue.. Now it works as expected.  Problem solved
