### ISSUE TITLE
HubConnectionBuilderHttpExtensions where is  .WithMessageHandler and .WithTransport

### ISSUE THREAD

**Issue by radenkozec** [aspnet/SignalR#2398]
It seams that .WithMessageHandler and .WithTransport are removed or moved in latest version of C# client.
Even in documentation is stated that exists
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnectionbuilderhttpextensions?view=aspnetcore-2.1
In source code I cannot find it.
Can you please confirm this?

**Comment by JamesNK** [comment]
That documentation is out of date. I'll create an issue with the docs team to fix it.

Those options are now set via the `WithUrl` method. Example here - https://github.com/aspnet/SignalR/blob/e4d0f2980efa4fa4b8e6097b41b3317ff0b5a763/benchmarkapps/Crankier/Client.cs#L24

**Comment by radenkozec** [comment]
@JamesNK Changes in last minutes.
And new code for MessageHandler is not working?
https://github.com/aspnet/SignalR/issues/2226
This means that I cannot do anything before RTM right?

**Comment by JamesNK** [comment]
The overload that takes these two parameters should work

`WithUrl(Uri url, Action<HttpConnectionOptions> configureHttpConnection)`

**Comment by radenkozec** [comment]
This code is working. I can confirm it. Thanks for your help
