### ISSUE TITLE
SignalR 1.0.0 released?

### ISSUE THREAD

**Issue by WilcoBakker** [aspnet/SignalR#2399]
Dear developers of SignalR,

According to the release tags, SignalR 1.0.0 has been released 4 days ago. Is that the actual post-RC post-pre-release release?
If so, when will it be added to NuGet?

Thanking you in advance. 🤗

**Comment by Sinfulelf** [comment]
Mb this will help U
https://github.com/aspnet/Home/wiki/2.1.0-Early-Access-Downloads

**Comment by anurse** [comment]
The release tags are often prepared ahead of the official release, and before we publish to NuGet.org. See our blog for official announcements: https://blogs.msdn.microsoft.com/webdev
