### ISSUE TITLE
Server returned handshake error

### ISSUE THREAD

**Issue by yaohaixiao** [aspnet/SignalR#2400]
Server-Side: Microsoft.AspNetCore.SignalR 1.0.0-preview2-final
Client-Side: @aspnet/signalr@1.0.0-rc1-final （work with javascript client）
IIS: 10.0
OS Server: Windows Server 2016
OS Client: Windows 10 Enterprise
Browser: Chrome 59.0.3071.115

It works well on my PC, debug with VS 2017 using IIS Express. But when I publish it to the Server (Azure), It's return the error: 

> Server returned handshake error: An unexpected error occurred during connection handshake.

I enbaled the Websockets on my IIS server. 

Here is my js code

```js
const connection = new signalR.HubConnectionBuilder().withUrl('/signalr/siteHub').configureLogging(signalR.LogLevel.Information).build()

connection.on('ReceiveMessage', (response) => {
        console.log(response)
        console.log('refresh the grid')
        this.loadData()
})

connection.on('PublishErrorMessage', (response) => {
        console.log(response)
        console.log('refresh the grid')
        this.loadData()
})

connection.start().then(() => {
    console.log('connection Start!')

    if (!this.isInvoked) {
         let connectState = connection.connection.connectionState
         if (connectState === 1) {
            // for 'ReceiveMessage'
            connection.invoke('SendTest', (userId).toString(), 3).catch(err => console.error(err.toString()))
           // for 'PublishErrorMessage' 
            connection.invoke('SendTest', (userId).toString(), 3).catch(err => console.error(err.toString()))
         }
    }
}).catch((err) => {
    console.error(err.toString())
})
```

**Comment by davidfowl** [comment]
Here's your problem:

> Server-Side: Microsoft.AspNetCore.SignalR 1.0.0-preview2-final
> Client-Side: @aspnet/signalr@1.0.0-rc1-final （work with javascript client）

Update the server side to 1.0.0-rc1-final

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.

**Comment by yaohaixiao** [comment]
I just updated the server size version to 1.0.0-rc1-final, but it still not work. And I got the same error.

**Comment by davidfowl** [comment]
@yaohaixiao can you fill out the issue here again https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md, including following the diagnostic guide to get more information https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide?

**Comment by davidfowl** [comment]
If you get the same error then something isn’t updated. Also the fact that IIS expressndies work makes me think your deployment environment might be the issue or maybe you didn’t publish updated bits

**Comment by yaohaixiao** [comment]
@davidfowl I gree with you, the deployment environment might be the issue but I just can't figure out

I update the version to the 1.0.0 both server and client. still got the same error

**Comment by davidfowl** [comment]
@yaohaixiao can you try following the diagnostic guide? That'll provide more information.

**Comment by yaohaixiao** [comment]
@davidfowl

 I found the issue

> HandshakeTimeout = TimeSpan.MaxValue

I removed this setting then it works well on IIS. but Why?

**Comment by anurse** [comment]
We can't help figure out why if we don't have the logs from the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide). Setting `HandshakeTimeout` to `TimeSpan.MaxValue` is a bad idea as it means clients can hold connections open without ever performing the handshake.

**Comment by yaohaixiao** [comment]
@anurse 
thank you! I'll follow the Diagnostics Guide.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
