### ISSUE TITLE
System.Memory problem on Xamarin.iOS?

### ISSUE THREAD

**Issue by freever** [aspnet/SignalR#2401]
I am getting the following errors running a Xamarin.Forms iOS app with SignalR-1.0.0-rc1-final and Xamarin.Forms 3.0.0.482510:

> warning: Could not load signature of Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol:TryParseMessage due to: Could not resolve type with token 01000026 (from typeref, class/assembly System.Buffers.ReadOnlySequence`1, System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51) assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Buffers.ReadOnlySequence`1 member:(null) signature:<none>

> warning: Could not load signature of Microsoft.AspNetCore.SignalR.Protocol.IHubProtocol:TryParseMessage due to: Could not resolve type with token 01000034 (from typeref, class/assembly System.Buffers.ReadOnlySequence`1, System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51) assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Buffers.ReadOnlySequence`1 member:(null) signature:<none>

This is followed with this exception:

> System.TypeLoadException: Could not resolve the signature of a virtual method : "Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol"

The code throwing the exception is:

```
           _hubConnection = new HubConnectionBuilder()
                .WithUrl(Endpoint)
                .Build();
```
I'm aware that there's a problem with Xamarin.Android due to the missing System.Memory facade in Mono (#1886) - is this the reason for my iOS problems too or am I doing something wrong here?

UWP is working fine. 

My version info is as follows:

> === Visual Studio Community 2017 for Mac (Preview) ===
> 
> Version 7.6 Preview (7.6 build 711)
> Installation UUID: 60680359-6e03-485d-b0af-f7e27ea999fc
> Runtime:
> 	Mono 5.12.0.226 (2018-02/9824e260f56) (64-bit)
> 	GTK+ 2.24.23 (Raleigh theme)
> 	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)
> 
> 	Package version: 512000226
> 
> === NuGet ===
> 
> Version: 4.3.1.4445
> 
> === .NET Core ===
> 
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	2.0.5
> 	2.0.0
> SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
> SDK Versions:
> 	2.1.4
> 	2.0.0
> MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks
> 
> === Xamarin.Profiler ===
> 
> '/Applications/Xamarin Profiler.app' not found
> 
> === Xamarin.Android ===
> 
> Version: 8.3.0.19 (Visual Studio Community)
> Android SDK: /Users/adrianfrielinghaus/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		7.0 (API level 24)
> 		7.1 (API level 25)
> 		8.0 (API level 26)
> 		8.1 (API level 27)
> 
> SDK Tools Version: 25.2.5
> SDK Platform Tools Version: 27.0.1
> SDK Build Tools Version: 27.0.3
> 
> Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
> 
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> === Apple Developer Tools ===
> 
> Xcode 9.3.1 (14154.1)
> Build 9E501
> 
> === Xamarin.Mac ===
> 
> Version: 4.5.0.280 (Visual Studio Community)
> Hash: e85a7be8
> Branch: master
> Build date: 2018-05-03 11:35:01-0400
> 
> === Xamarin.iOS ===
> 
> Version: 11.11.0.280 (Visual Studio Community)
> Hash: e85a7be8
> Branch: master
> Build date: 2018-05-03 11:35:00-0400
> 
> === Xamarin Inspector ===
> 
> Version: 1.4.0
> Hash: b3f92f9
> Branch: master
> Build date: Fri, 19 Jan 2018 22:00:34 GMT
> Client compatibility: 1
> 
> === Build Information ===
> 
> Release ID: 706000711
> Git revision: 634060c6c105fd3ee36678fe547680fd258cbf45
> Build date: 2018-05-04 16:11:06-04
> Xamarin extensions: c6720450018cb69a3da7c6d0aa0715c013783595
> Build lane: monodevelop-lion-master
> 
> === Operating System ===
> 
> Mac OS X 10.13.4
> Darwin 17.5.0 Darwin Kernel Version 17.5.0
>     Mon Mar  5 22:24:32 PST 2018
>     root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
> 
> === Enabled user installed extensions ===
> 
> NuGet Package Explorer 0.2
> NuGet Package Management Extensions 0.12.6
> Internet of Things (IoT) development (Preview) 7.5
> 
>

**Comment by davidfowl** [comment]
Xamarin is currently not supported, see this issue for more details https://github.com/aspnet/SignalR/issues/1886

**Comment by cwrea** [comment]
FWIW, I filed a related Xamarin.iOS issue earlier: [iOS app build fails when referencing package (e.g. Entity Framework Core 2.1) that depends on newer System.Memory](https://github.com/xamarin/xamarin-macios/issues/4168). In my case I was interested in updating a project to use EF Core v2.1, which also referenced newer System.Memory than supported by Xamarin.iOS.

**Comment by DavePilks** [comment]
I don't understand, if Xamarin is supported, why are there Xamarin Samples available? I just downloaded them and they give the same error. But what is the point of providing samples that are known not to work?

**Comment by anurse** [comment]
> But what is the point of providing samples that are known not to work?

Good catch, that is a little confusing. I updated the readme for that sample to clarify. We use the samples to help verify scenarios as well as illustrate them. The sample doesn't work right now because of #1886 but we don't want to get rid of it right now because it should work once that issue is resolved.

**Comment by cwrea** [comment]
Relevant: https://github.com/aspnet/Announcements/issues/305
