### ISSUE TITLE
How can I get connection is disconnected ?

### ISSUE THREAD

**Issue by OmprakashAmarwal** [aspnet/SignalR#2402]
there is any way to detect connection disconnected from hub server ?
so i can notify offline to user or reconnect to server.

Please provide a full document related to all the new changes.

**Comment by davidfowl** [comment]
Something like this?

https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1#handle-events-for-a-connection

**Comment by Sinfulelf** [comment]
1) "any way to detect connection disconnected"
- As David said, You might use ' public override Task OnDisconnectedAsync (Exception exception)' in ur Hub.
2) reconnect to server
- You can "Decorators" to ur invoke functions, and call new connection, if old was closed

**Comment by OmprakashAmarwal** [comment]
it's good while i have to do some server side task, but i need to get any event on client side while a connection is disconnected.

like we are using  ##this._hubConnection.start() for notify that user is connected to SignalR but, in case connection is broken and we need to just notify to user that you have to reconnect or offline then what is the event for it?

**Comment by Sinfulelf** [comment]
Add observer to Connection state (connection->connectionState). If connectionState === 4 - grtz, U have disconnect =)

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/blob/dev/samples/SignalRSamples/wwwroot/hubs.html#L157

**Comment by davidfowl** [comment]
@Sinfulelf there's no exposed connection state in ASP.NET Core SignalR.

**Comment by Sinfulelf** [comment]
@davidfowl Oh, my bad

**Comment by OmprakashAmarwal** [comment]
@BrennanConroy The code is working fine, is this a good way to perform reconnect while 
   this._hubConnection.onclose(function (e) { 
   });
Event is called ?

**Comment by OmprakashAmarwal** [comment]
@davidfowl  you need to create document for your new changes with best approach.

**Comment by davidfowl** [comment]
Yes, the docs need some love.

https://github.com/davidfowl/UT3/blob/dac409886c1bb7aec7c150b74d4ce9a3e246f03c/UTT/wwwroot/js/utt.js#L141-L153

**Comment by mikaelm12** [comment]
Yeah, sorry if that wasn't clear. That's what I meant. It was added to dev after RTM-ing so it'll be available in our next minor release

**Comment by GFoley83** [comment]
@davidfowl if you reconnect in the manner you've shown, should you still be in the same groups you were in before the connection dropped? 

From some quick testings it seems that you have to track and rejoin all groups manually.

**Comment by davidfowl** [comment]
@GFoley83 no it's a new connection and you have to rejoin the groups.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
