### ISSUE TITLE
Error: Server returned handshake error

### ISSUE THREAD

**Issue by yaohaixiao** [aspnet/SignalR#2404]
Server-Side: Microsoft.AspNetCore.SignalR 1.0.0
Client-Side: @aspnet/signalr@1.0.0 （work with javascript client）
IIS: 10.0
OS Server: Windows Server 2016
OS Client: Windows 10 Enterprise
Browser: Chrome 66.0.3359.181

It works well when debug with VS 2017 using IIS Express. But when I publish it to the IIS server, It's return the error: 

> Server returned handshake error: An unexpected error occurred during connection handshake.

 I enabled all the features on IIS. here is the log:

> 2018-05-30 03:46:00 10.5.106.125 POST /signalr/rdcsiteHub/negotiate - 5003 - 10.5.106.125 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/66.0.3359.181+Safari/537.36 http://10.5.106.125:5003/projects/27/applications/112/deploys/daily 200 0 0 43

> 2018-05-30 03:46:00 10.5.106.125 GET /signalr/rdcsiteHub id=Ha2uZqE6tANXYATFN3gkug 5003 - 10.5.106.125 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/66.0.3359.181+Safari/537.36 - 101 0 0 166

seems like I could connect the hub, but it returns error when I call the **connection.invoke** function

Here is my javascript code

```js
import * as signalR from '@aspnet/signalr'
const connection = new signalR.HubConnectionBuilder().withUrl('/signalr/siteHub').configureLogging(signalR.LogLevel.Information).build()

connection.on('ReceiveMessage', (response) => {
        console.log(response)
        console.log('refresh the grid')
        this.loadData()
})

connection.on('PublishErrorMessage', (response) => {
        console.log(response)
        console.log('refresh the grid')
        this.loadData()
})

connection.start().then(() => {
    console.log('connection Start!')

    if (!this.isInvoked) {
         let connectState = connection.connection.connectionState
         if (connectState === 1) {
            // for 'ReceiveMessage'
            connection.invoke('SendTest', (userId).toString(), 3).catch(err => console.error(err.toString()))
           // for 'PublishErrorMessage' 
            connection.invoke('SendTest', (userId).toString(), 3).catch(err => console.error(err.toString()))
         }
    }
}).catch((err) => {
    console.error(err.toString())
})
```

**Comment by anurse** [comment]
Can you capture logs from the ASP.NET Core server (not IIS access logs) using the instructions in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)? It would also be very helpful if you could capture a network trace using [Fiddler](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#fiddler-windows-and-macos)

**Comment by davidfowl** [comment]
@yaohaixiao why did you close this bug https://github.com/aspnet/SignalR/issues/2400 and reopen a new one with the exact same description?

**Comment by davidfowl** [comment]
Ah @anurse closed it.
