### ISSUE TITLE
Enable TSLint for tests

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2407]
We should run TSLint over our unit tests. Particularly rules like [no-floating-promises](https://palantir.github.io/tslint/rules/no-floating-promises/) which ensure you properly `await` a promise. It's easy to mess that up and get weird behavior in a test.

I'd suggest doing this by adding a new script to each of `clients\ts\signalr\package.json` and `clients\ts\signalr-protocol-msgpack\package.json` that lints the tests, and then have the `test` script in `clients\ts\package.json` run those commands before running `jest`.

**Comment by anurse** [comment]
I'd also strongly suggest waiting for #2388 to land first since it will conflict hard.

**Comment by JamesNK** [comment]
#2388 done
