### ISSUE TITLE
Large data being "merged" incorrectly

### ISSUE THREAD

**Issue by aldrashan** [aspnet/SignalR#2419]
Nuget package: Microsoft.AspNetCore.SignalR (1.0.0-rc1-final)
Javascript client
Server: kestrel
Server OS: Linux
Client browser: all

I send data from my Hub to the client after serializing it like so:
`await Clients.Caller.SendAsync("ReceiveAllTables", JsonConvert.SerializeObject(tables, new JsonSerializerSettings() { ContractResolver = new CamelCasePropertyNamesContractResolver() }));`

The javascript function then parses the incoming data back to an object array and processes it.

This works fine as long as there are a few tables.
As soon as a size threshold is reached (not sure what that threshold is) the parsing to objects fails because there are unexpected characters in the json string.
An example of this would be:
[{"tableId":1,"Name":"Test1"}, ... ,{**g145**"tableId":6,"Name":"Test6"}, ...]

The "g145" is what causes the parsing to fail.
The same thing happens when you send back data without first serializing it. Random bytes get added in the javascript received data causing weird characters to appear in the object string, which causes the parsing to fail.

**Comment by davidfowl** [comment]
Are you running on .net Core 2.0 or 2.1?

**Comment by aldrashan** [comment]
@davidfowl 2.0

**Comment by davidfowl** [comment]
Use 2.1, we’ve seen issue with http client on 2.0 causing strange behavior like this

**Comment by anurse** [comment]
@aldrashan Have you been able to update to .NET Core 2.1 and reproduce the issue there?

**Comment by aldrashan** [comment]
@anurse Just upgraded today since I had to wait for a mysql package update from Pomelo and the original issue appears to be fixed. I haven't tried it with way larger amounts of data, but sending a couple of objects already threw errors before, so I'm assuming it's fixed. Will post back if it's not.
