### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by dvdmrk** [aspnet/SignalR#2421]
I've tried literally everything, I've rearranged my startup file added cors policy, seriously in a bind.
These are the errors I'm getting based off of an angular build using the latest vs code, node, core, and signalr. I've built a pretty generic chat application, and I'm not sure where to go from here.

Angular is running in the development mode. Call enableProdMode() to enable the production mode.
/home/echo/negotiate:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
Utils.js:151 Warning: Error from HTTP request. 0:
ConsoleLogger.log @ Utils.js:151
Utils.js:148 Error: Failed to complete negotiation with the server: Error
ConsoleLogger.log @ Utils.js:148
Utils.js:148 Error: Failed to start the connection: Error
ConsoleLogger.log @ Utils.js:148
core.js:1448 ERROR Error: Uncaught (in promise): Error
Error
at new HttpError (Errors.js:16)
at XMLHttpRequest.xhr.onerror [as __zone_symbol__ON_PROPERTYerror] (HttpClient.js:80)
at XMLHttpRequest.wrapFn (zone.js:1166)
at ZoneDelegate.invokeTask (zone.js:421)
at Object.onInvokeTask (core.js:4736)
at ZoneDelegate.invokeTask (zone.js:420)
at Zone.runTask (zone.js:188)
at ZoneTask.invokeTask [as invoke] (zone.js:496)
at invokeTask (zone.js:1517)
at XMLHttpRequest.globalZoneAwareCallback (zone.js:1543)
at new HttpError (Errors.js:16)
at XMLHttpRequest.xhr.onerror [as __zone_symbol__ON_PROPERTYerror] (HttpClient.js:80)
at XMLHttpRequest.wrapFn (zone.js:1166)
at ZoneDelegate.invokeTask (zone.js:421)
at Object.onInvokeTask (core.js:4736)
at ZoneDelegate.invokeTask (zone.js:420)
at Zone.runTask (zone.js:188)
at ZoneTask.invokeTask [as invoke] (zone.js:496)
at invokeTask (zone.js:1517)
at XMLHttpRequest.globalZoneAwareCallback (zone.js:1543)
at resolvePromise (zone.js:809)
at eval (zone.js:728)
at rejected (tslib.es6.js:63)
at ZoneDelegate.invoke (zone.js:388)
at Object.onInvoke (core.js:4745)
at ZoneDelegate.invoke (zone.js:387)
at Zone.run (zone.js:138)
at eval (zone.js:858)
at ZoneDelegate.invokeTask (zone.js:421)
at Object.onInvokeTask (core.js:4736)

**Comment by BrennanConroy** [comment]
Could you follow the diagnostic guide here: https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide so that we have enough information to start figuring out the issue

**Comment by dvdmrk** [comment]
@BrennanConroy I'm not really sure what other information to give you because I'm not getting any errors in vs code. I've included my har file. [har.txt](https://github.com/aspnet/SignalR/files/2066072/har.txt) 
For further reference, earlier on I had tslib issue which I resolved by reviewing other issues, and I had the issue where it was required to reference the qualified url in the connection because I'm calling the echo hub from the home component. 

Here's a copy of my home component ts file. My Startup file is pretty generic aswell, with cors, referencing app.UseSignalR before app.UseMVC as per other suggestions. My chat hub returns void. There aren't many things that can go wrong with the limited code in my practice application, but still, the connection isn't opening. 

import { Component, OnInit } from '@angular/core';
import signalR = require('@aspnet/signalr');

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
})
export class HomeComponent implements OnInit {
  message:string='';
  messages:string[]=[];

  public hubConnection : signalR.HubConnection;
  ngOnInit() {
    this.hubConnection = new signalR.HubConnectionBuilder()
      .withUrl("https://localhost/home/echo/")
      .configureLogging(signalR.LogLevel.Information)
      .build();
    this.hubConnection.on("Send", (msg) => {
      this.messages.push(msg);
    });
    this.hubConnection.start();
  }

  echo() {
    this.hubConnection.invoke("Echo", this.message);
  }
}

**Comment by davidfowl** [comment]
Where is all the version information for the OS, web sever and SignalR itself?

**Comment by dvdmrk** [comment]
"@aspnet/signalr": "^1.0.0",
dotnet --version 2.1.300
OS Windows 10
I'm not sure how to find the web server version, but I'm assuming it's kestral since I haven't changed anything.

**Comment by anurse** [comment]
The HAR trace shows all the requests going to `http://localhost:5001` **except** the SignalR one (`/negotiate`) which is going to `http://localhost` (on port `80`). On which port is you SignalR app actually listening?

**Comment by dvdmrk** [comment]
@anurse I'm not sure what port signlar is actually running, I have not specified. I am accessing the application via localhost:5001

**Comment by anurse** [comment]
So your ASP.NET Core application is running on `localhost:5001`? Then you need to use the same port when you call `withUrl`: `.withUrl("https://localhost:5001/home/echo/")`

**Comment by dvdmrk** [comment]
i have tried that and it returns a 404 on the negotiate method

**Comment by BrennanConroy** [comment]
In your `MapHub` call what is the path you specify?

**Comment by dvdmrk** [comment]
"/echo"

**Comment by BrennanConroy** [comment]
Remove "/home" from the url since that's not part of the route you specified for your hub

**Comment by dvdmrk** [comment]
I thank you for all your help, I am able to get it working now. I think it might have been an issue with installing tslib in the wrong directory. I am grateful for your patience and assistance. I am marking this resolved.

**Comment by anurse** [comment]
Is this the issue you were seeing? #2410

**Comment by rmsutton** [comment]
I am having the same exact issue. Our codebase works fine another another machine fails on mine.
