### ISSUE TITLE
JavaScript/Angular: Failed to complete negotiation with the server

### ISSUE THREAD

**Issue by kiko35** [aspnet/SignalR#2422]
Hello,

I'm trying to translate this back-end code using the signalr-client lib: https://github.com/Bittrex/beta/blob/master/samples/WebsocketSample.js to a code using yours and a browser. 

Here is the code:

     this.connection = new HubConnectionBuilder()
      .configureLogging(LogLevel.Trace)
      .withUrl("wss://beta.bittrex.com/signalr")
      .build();

    this.connection.on("send", data => {
      console.log(data);
    });

    this.connection.onclose(e => {
      console.log("Connection closed!", e);
    });

    console.log("Trying to connect to hub!");

    this.connection
      .start()
      .then(() => {
        console.log("Connection started!");
        //this.connection.send('send', 'csad');
      })
      .catch(err => console.log("Error", err));

I get some errors:

Error: Failed to complete negotiation with the server: Error

Error: Failed to start the connection: Error

Error while establishing connection :( Object { __zone_symbol__error: Error, fileName: Getter & Setter, lineNumber: Getter & Setter, columnNumber: Getter & Setter, message: Getter & Setter, name: Getter & Setter, stack: Getter & Setter, originalStack: Getter & Setter, zoneAwareStack: Getter & Setter, toString: value(), … } app.component.ts:48:20

Do you have any idea?

**Comment by dvdmrk** [comment]
I am also having a negotiation error.

**Comment by anurse** [comment]
Can you collect client and server logs, as well as network traces as specified in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) ?

**Comment by kiko35** [comment]
Here are the logs

[Archive 18-06-06 19-59-22.har.txt](https://github.com/aspnet/SignalR/files/2077584/Archive.18-06-06.19-59-22.har.txt)
[client.txt](https://github.com/aspnet/SignalR/files/2077585/client.txt)

**Comment by anurse** [comment]
> And I was also wondering if we could use the js client lib without angular?

Absolutely. The JS client has no dependency on other libraries (with the exception of MessagePack support which requires the [`msgpack5`](https://github.com/mcollina/msgpack5) library.

The logs are a bit empty. Did you set the client-side log level to `Trace` as indicated in the [JavaScript Client logging section of the Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#javascript-client-logging). We can take a look at the HAR file, that looks good, but having the detailed logs would help.

**Comment by kiko35** [comment]
I can't save them to a file but here is a screen

http://i.imgur.com/v6kQZTs.png

When i'm trying to use the library, I have this error: TypeError: signalR.HubConnectionBuilder is not a constructor even if I include <script src="signalr.js"></script>

**Comment by kiko35** [comment]
Ok, i can save logs on chrome and that's what I got:

[client.log](https://github.com/aspnet/SignalR/files/2077802/client.log)

**Comment by BrennanConroy** [comment]
Don't put "wss" as the url scheme. Put "https", SignalR will convert it if you use websockets

**Comment by kiko35** [comment]
With https, I have another error message:

Failed to load https://beta.bittrex.com/signalr/negotiate?clientProtocol=1.5&_=1528315659304: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by kiko35** [comment]
Ok guys, here is the translation of the back-end code (https://github.com/Bittrex/beta/blob/master/samples/WebsocketSample.js) It only **works** with the firefox extension CORS Everywhere extension.

`     

    <script src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js'></script>
     <script src='https://cdnjs.cloudflare.com/ajax/libs/signalr.js/2.2.3/jquery.signalR.js'></script>
     <script src='pako.js'></script>

    <script>			
		
		var connection = $.hubConnection('https://beta.bittrex.com/signalr');
		var hubProxy = connection.createHubProxy('c2');
		hubProxy.on('uE', function(message) {
			// Decode base64 (convert ascii to binary)
			var strData = atob(message);
			// Convert binary string to character-number array
			var charData = strData.split('').map(function(x){return x.charCodeAt(0);});
			// Turn number array into byte-array
			var binData = new Uint8Array(charData);
			var data = pako.inflate(binData, { raw: true });
			// Convert gunzipped byteArray back to ascii string:
			var strData = String.fromCharCode.apply(null, new Uint16Array(data));
			// Output to console
			console.log(strData);
		});
		connection.start().done(function() {
			console.log('connection started!');
			hubProxy.invoke('SubscribeToExchangeDeltas', "BTC-LTC");
		});
		
    </script>`

**Comment by anurse** [comment]
Is the issue resolved? Your post indicated that you need the "CORS Everywhere" extension in Firefox. That completely disables the Cross-Origin protections of the browser. What you should be doing is changing your server to enable CORS.

You should configure the CORS middleware on the server to make sure the appropriate CORS data is provided. As a quick solution you can use something like this in your Startup.cs file:

```csharp
app.UseCors(builder => {
    builder.AllowAnyMethod()
        .AllowAnyOrigin()
        .AllowAnyHeader()
        .AllowCredentials();
});
```

**Comment by kiko35** [comment]
Unfortunately, it is not my server, it's a crypto exchange (bittrex), but i'm going to try to modify the jquery.signalR.js file to add some headers ("Access-Control-Allow-Origin": "null", "access-control-allow-credentials": "true") to the request in order to get rid of the extension.

**Comment by BrennanConroy** [comment]
Wait, you're trying to convert a ASP.NET SignalR 2.X Client to a ASP.NET Core SignalR 1.0.0 Client which is communicating to a ASP.NET SignalR 2.X Server? That isn't supported. The server needs to also be ASP.NET Core SignalR 1.0.0, ASP.NET SignalR 2.X isn't compatible with ASP.NET Core SignalR 1.0.0

**Comment by kiko35** [comment]
I don't know what they actually use at the back-end but now it is only a matter of CORS, the handshake cannot take place because some headers are missing for the initial request.

**Comment by BrennanConroy** [comment]
> ASP.NET SignalR 2.X isn't compatible with ASP.NET Core SignalR 1.0.0

If your original code was working that means the server is using ASP.NET SignalR 2.X and your new code **will not work**

**Comment by kiko35** [comment]
This code works like the original I was trying to translate to use it into a browser


[good.html.txt](https://github.com/aspnet/SignalR/files/2081605/good.html.txt)

**Comment by anurse** [comment]
It looks like the "Bittrex" service you're connecting to uses ASP.NET SignalR to connect. This repo is for ASP.NET **Core** SignalR, which is a complete rewrite of the product and not compatible. Since the server is using ASP.NET SignalR, there's no need to convert to the code in this repository.

As to your CORS issue, that is something that can **only** be resolved on the server. I suggest you contact Bittrex for assistance. There is no way to disable this CORS protection in the JavaScript client.

**Comment by kiko35** [comment]
Ok but if an extension is able to solve this problem, you are sure it's not possible to do something in javascript to solve this problem? The error is always: " header 'Access-Control-Allow-Origin'  is missing"

**Comment by kiko35** [comment]
You are right about the CORS issue, nothing is possible in javascript for the client side except some web extensions. Thank you for the help.

**Comment by BrennanConroy** [comment]
To be 100% clear, the web extensions remove some of the security that browsers provide for you. So be careful when using them.
