### ISSUE TITLE
Breaking Changes...

### ISSUE THREAD

**Issue by samcov** [aspnet/SignalR#2423]
Upgrading to 2.1 had a lot of breaking changes, and most have been resolved. However, there are two that I'm not sure how to resolve, since the old way has been removed(see code at end)

1. While I don't seem to have an issue talking to the js client, in the C# client, I'm not sure how to force Pascal Case.

2. How do I specify Websockets or MessagePack as the transport?

.**WithHubProtocol**(new JsonHubProtocol(Options.Create(new JsonHubProtocolOptions()
{
    PayloadSerializerSettings = new JsonSerializerSettings()
    {
	// Configure as you'd like here
    }
})))
.**WithTransport**(TransportType.WebSockets)

**Comment by anurse** [comment]
For MessagePack, you use the `.AddMessagePackProtocol()` extension method on `HubConnectionBuilder`. This requires the `Microsoft.AspNetCore.SignalR.Protocols.MessagePack` package.

For specifying a specific set of transports, you configure that in the `options => {}` delegate provided to `.WithUrl()`

**Comment by samcov** [comment]
BTW, in the JS client, you guys made a change to **withCredentials**, setting it to true, is there a way to set that to false in the client, or is there a solution on the server?

Also, you **what do I do to get Pascal case in the C# client**?

**Comment by samcov** [comment]
Ok, ignore the credentials, I found out that adding ".AllowCredentials()" on the server solves that problem, so I just need to know how to get Pascal Case in the C# client.

**Comment by anurse** [comment]
For Pascal Case JSON you set the Contract Resolver as such:

```csharp
.AddJsonProtocol(options => {
    options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver();
})
```

Note, you should not use `.WithHubProtocol` in the C# client, there is a specific overload for JSON (`.AddJsonProtocol`) that does a lot more of the work for you. We're actively working on improving docs this week, so we'll make sure this gets covered (https://github.com/aspnet/Docs/issues/6599 is tracking this work)

**Comment by samcov** [comment]
AddJsonProtocol appears to not be a member of IHubConnectionBuilder

**Comment by anurse** [comment]
you need to import the `Microsoft.Extensions.DependencyInjection` namespace. Visual Studio (and VSCode) should suggest it as a quick fix when you type it in. I'll add a note to the docs to point that out.

**Comment by samcov** [comment]
Yes, Visual Studio does give me the suggestion, and everything is working properly... Thanks!

**Comment by anurse** [comment]
Awesome!
