### ISSUE TITLE
SignalR Webhost with ASP.NET Core 2.1 and UWP app as Client returns ' 405 Method not allowed'

### ISSUE THREAD

**Issue by pazcaldj** [aspnet/SignalR#2426]
I am struggling with this for a while now and I can't get it to work. I have 2 applications, both running on a Raspberry Pi 2 with Win IoT:

- ASP.NET Core 2.1 Web Api - Within this WebApi I am running a SignalR Host (published as `win10-arm`). 

- Universal Windows App - This app will be a client which should communicate with the host and all other clients (published as ARM).

When I deploy the UWP app and I try to run it, it crashes in the `hubConn.Start(...)` method of the HubConnection and returns the error:

> **HttpClientException**: StatusCode: 405, ReasonPhrase: 'Method Not
> Allowed', Version: 1.1, Content: System.Net.Http.StreamContent,
> Headers: {   Server: Kestrel   Date: Sat, 02 Jun 2018 17:04:15 GMT  
> Content-Length: 0   Content-Type: text/plain }

The testconsole and UWP are both using the `Microsoft.AspNet.SignalR.Client` (2.2.3) nuget package (which is the latest). The ASP.NET Core 2.1 Web Api is using the `Microsoft.AspNetCore.App` SDK (2.1.0).

By reading this post https://stackoverflow.com/questions/49152486/signalr-version-compatability-statuscode-405-method-not-allowed/49153217#49153217 I am familiar with the fact that SignalR is not backwards compatible for both host as client. But I would expect that as I am using the latest nuget packages and versions which are available on nuget everything would work.

Also, I am aware that ASP.NET Core 2.1 package and the SignalR Client package are 2 different packages, but I cannot add the nuget package `Microsoft.AspNetCore.App` to the UWP project as it is not compatible with any `win10-arm` platform.

If I want to work with ASP.NET Core 2.1 SignalR, which nuget package should I include in my Test Console app, as well in my UWP project?

Here some of the code; all projects are completely defaults via File - New project, plus the code below.

**ASP.NET Core 2.1 Web Api**

Startup.cs

    public class Startup
    {
        ...
        
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            ...

            services.AddMvc();
            services.AddSignalR();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
 
            ...
            
            app.UseSignalR(route =>
            {
                route.MapHub<HomeAutomationHost>("/HomeAutomationHost");
            });

            app.UseMvc();
        }
    }

**Universal Windows App**

MainPage.xaml.cs

    public class MainPage 
    {
	    ...
	
	    public async Task DoConnect()
	    {
                var hubConn = new HubConnection("http://192.168.2.49:5000/HomeAutomationHost", false);
                hubConn.EnsureReconnecting();

                var signalRHost = hubConn.CreateHubProxy("HomeAutomationHost");

                await hubConn.Start(new WebSocketTransport());
	    }
    }

**Comment by dvdmrk** [comment]
I feel like you should be using AspNetCore.SignalR which is v 1.0 right now. The version you are using has dependencies on the dotnet Framework v4.5 as per 'https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/'.

**Comment by pazcaldj** [comment]
Thank you so much for your answer! This was indeed the issue! I was using the wrong package all along. I was aware of the difference of these packages, but it slipped my mind the moment I was focusing on the issue. I am now hitting a different exception, related to System.Memory but I noticed several about this so I will dig further. Again many thanks!

**Comment by anurse** [comment]
> I am now hitting a different exception, related to System.Memory

This is a known issue and will be resolved in the first patch (there's no public ETA but we're giving it a high priority). See #2406 for more info. If you can, reducing the minimum Windows version of your UWP app to the Fall Creators Update should resolve the issue (I don't know if IoT requires a higher minimum version)
