### ISSUE TITLE
Cannot Load Dependencies from Nuget Package

### ISSUE THREAD

**Issue by DavePilks** [aspnet/SignalR#2428]
I am trying to use the AspNetCore Nuget package in a Xamarin.Forms app. But when it tries to load the ViewModel that has the reference to the .dll, I get the following message.

> Could not load file or assembly 'Microsoft.AspNetCore.SignalR.Client.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. assembly:Microsoft.AspNetCore.SignalR.Client.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type: member:(null) signature:

* Versions of Client-Side NuGet/NPM Packages: 1.0.0
* Are you using the C# client or the JavaScript client: C#
* The Operating System on the Client (Windows/Linux/macOS): Xamarin.Forms via Visual Studio for MacOS

The project that I am adding the Nuget package to is a .Net Standard 2.0 project.

**Comment by anurse** [comment]
We're tracking Xamarin issues in #1886 . SignalR 2.1.0 does not support Xamarin due to some issues we've encountered, but it's a high priority on the team to get these fixed.
