### ISSUE TITLE
Many "Failed connection handshake" errors per second

### ISSUE THREAD

**Issue by rfrancisco** [aspnet/SignalR#2430]
We have multiple servers with an average of 30-40K connections each. We connect the clients using the Typescript signalR client.
One thing that we notice in our logs is that we have many "Failed connection handshake" erros being logged. Is this normal? If so should this be being logged as an error?

We started using signalR in RC1, and we saw this behaviour, now we updated to the final version and the behaviour is still the same.

**Comment by BrennanConroy** [comment]
Could you fill out the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by Maciejszuchta** [comment]
Hello, I have a similar problem.
I've created my API with ASP CORE 2.1 and SignalR on Windows machine. Now I published the API to the server with Linux and in the chrome console I see only errors like this:

![image](https://user-images.githubusercontent.com/12434636/43004930-82cddb18-8c31-11e8-90e3-0b14c8fd5117.png)


My server reports:
![image](https://user-images.githubusercontent.com/12434636/43004986-b54f3410-8c31-11e8-9c06-efdffd77ad9a.png)

**Comment by anurse** [comment]
Can you file a new issue please? Please include details such as the exact server configuration you are using (for example, are you using a proxy like nginx or Apache?) and follow the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) to provide server and client-side logs in text format (screenshots are very difficult to work with)

**Comment by krvi** [comment]
I had this problem with SignalR behind an nginx proxy.
`proxy_set_header Connection "Upgrade";` resulted in a lot of failed handshakes per hour.
`proxy_set_header Connection "";` resulted in relatively few failed handshakes per hour.
`proxy_set_header Connection $http_connection;` fixed it entirely (over an hour).

**Comment by Maciejszuchta** [comment]
It looks like setting 
`proxy_set_header Connection $http_connection;` or
`proxy_set_header Connection "Upgrade";`

fixes the issue.

**Comment by kspearrin** [comment]
I had to specify both of the following headers on my nginx proxy location for the signalr endpoint:

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```
