### ISSUE TITLE
Send JWT bearer token from SignalR .NET Client in WPF Application

### ISSUE THREAD

**Issue by retsetman** [aspnet/SignalR#2431]
I want to apply a JWT based authentication scheme in my ASP .NET Core 2.1 SignalR hub for .NET clients that connect from a WPF application. I have read [this]( https://github.com/aspnet/SignalR/issues/1130) and this seems possible on the server side but how will I send the JWT token while connecting to the signalR hub? The HubConnectionBuilder and HubConnection classes of the SignalR .NET client don't seem to offer similar functionality to the one described in [this](https://docs.microsoft.com/en-us/aspnet/signalr/overview/security/hub-authorization#header) for .NET Framework SignalR. Are you planning to add such functionality in SignalR .NET Core client?

If it is not possible at the moment, I have thought of adding the JWT token to the connection URL. But I think the default implementation of JWT authentication in the server expects the token in the Authorization header. In this case how can I extract the token from the URL in the server? Can you show me the proper code for this?

**Comment by BrennanConroy** [comment]
Take a look at our JWT sample, specifically the `AccessTokenProvider` you can set when creating your connection

https://github.com/aspnet/SignalR/blob/948ebf34ece11918804f443b65c6a053dfc8f35c/samples/JwtClientSample/Program.cs#L38

**Comment by retsetman** [comment]
Thanks, it worked!

**Comment by retsetman** [comment]
I have another problem now. 
I wanted to apply authentication only to the hub connection request so I added the [Authorize] attribute in my server's Hub class. But I also wanted to call a Hub method from the client without further authentication so I also added the [AllowAnonymous] attribute to the Hub method but this didn't stop authentication for this method's invocations. Is there some other way to achieve this?

PS The above Hub method would do nothing and serve as a heartbeat call from the client so I wouldn't want to do an unnecessary authentication.

**Comment by BrennanConroy** [comment]
`[AllowAnonymous]` isn't supported.

So you have a client connected to a hub with `[Authorize]` and don't want it to run auth when calling a specific method? May I ask why you want to do this?

The only way this can be achieved is to put `[Authorize]` on all your hub methods except the heartbeat one.

**Comment by retsetman** [comment]
In my scenario, various Web API controller methods can call methods in the SignalR .NET Core client. The SignalR client only connects to the hub using authentication and then waits for method calls from the Hub. At the moment, the only Hub method that will be called from the client will be an empty heartbeat method. I found that I need this method so that I can detect some disconnections that the client does not detect (server-side internet connectivity loss), so that I can reconnect. So, as I said before, I want the client's initial connection to be authenticated but I don't want the subsequent frequent heartbeat empty method calls (sent over the same connection) to be authenticated (to me it seems useless - please correct me if I am wrong). 

It seems to me (after testing) that the authentication of the client's initial connection cannot be applied without adding the [Authorize] attribute to the Hub class. There is no hub function to which I can add the [Authorize] attribute for the initial connection instead. So, if I want authenticated connections, I also have to authenticate my heartbeat requests. Am I right? Is there another way to achieve both authenticated connection and non-authenticated hub method call (sent over the same connection)?

**Comment by anurse** [comment]
> So, as I said before, I want the client's initial connection to be authenticated but I don't want the subsequent frequent heartbeat empty method calls (sent over the same connection) to be authenticated (to me it seems useless - please correct me if I am wrong).

What do you mean you "don't want the subsequent frequent heartbeat empty methods calls...to be authenticated"? Authentication data must be exchanged for every request on the connection or the connection is not actually authenticated. If anyone can simply send a message to a connection without being authenticated, then the connection is insecure (the connection ID alone is **not** a sufficient authentication token). But that only applies to Long Polling and Server-Sent Events anyway. If you are using WebSockets, there is only one HTTP request, and thus only one exchange of authentication data.

Let's go back to basics. What **bug** or **problem** caused you to want to apply `AllowAnonymous` to the Heartbeat method? Were you seeing high bandwidth consumption or performance impact? If not, there's no need to do it. Hub connections aren't like MVC controllers. The _authentication_ happens once, during connection, and then each method call is _authorized_ based on that authentication data.

**Comment by retsetman** [comment]
The only reason I want to apply [AllowAnonymous] is that, based on the following log for a hub method call, I thought the token is validated again and I wanted to avoid that, since it seems useless for a heartbeat. I hadn't found any performance issues yet. I also have to say that I had the Websocket connection scenario in my mind.

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/ChatHub?id=RRNQjECpE7
EmW2pBp2az8A  73
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 45.5871ms 200 text/plain
```

**Comment by BrennanConroy** [comment]
> Authentication data must be exchanged for every request on the connection or the connection is not actually authenticated.

Auth will always run, otherwise you would allow unauthorized connections to call your hub method which is probably not what you want.

**Comment by anurse** [comment]
Yeah, it's not possible to avoid that. The layer that handles sending/receiving data is intentionally **unaware** of SignalR messages, it's just transferring bytes. So there's no way for us to know that an individual send only contains messages destined for an unauthenticated Hub method. It could even contain multiple messages, so it could have one message that is supposed to be authenticated and one that isn't.

I wouldn't worry about token validation unless you actually observe a performance problem. There are **lots** of things happening on every request and JWT token validation is a tiny part of that process. And as I said, if you have a WebSocket connection, there's only one (long-running) HTTP request, so there's only one JWT token validation.

**Comment by retsetman** [comment]
Thank you both for clarifying everything!

**Comment by grahambunce** [comment]
@anurse Not to hijack this thread, but to close off this loop? How do you want us to handle token expiry? Since the token provider is added during the Hub Builder, and this is then invoked on start, how would we ensure we get a new token before expiry and that the .NET client is using this new token?

Do we need to force a stop / start on the hub so that we get the new token?

**Comment by retsetman** [comment]
You can check client-side if the token has expired and ask the server for a new one if it is needed, like this:
```
var jwthandler = new JwtSecurityTokenHandler();
var jwttoken = jwthandler.ReadToken(lastJwt);
var expDate = jwttoken.ValidTo;
if (expDate < DateTime.UtcNow.AddMinutes(1))
     GetNewJwt();
```
I also didn't find any way to replace the expired token with a new without restarting the connection. This would be very good. Is there a way?

**Comment by anurse** [comment]
It depends a little on the transport right now. If you have your token factory check the expiration and get it's own new token though, it will likely work, but this is definitely a place that needs some work.

Your token factory is called before **every** HTTP request, so as long as you make sure the factory returns a valid token every time (by having it replace the token before it expires) it should work. In a WebSocket connection, there is only one request for the whole connection so if the token expires mid-connection the request stays active until you need to actually reconnect. In Server-Sent Events and Long Polling, each request calls your token factory again so if you give it an updated token it should just work.

**Comment by retsetman** [comment]
@anurse Can you supply an example with a token factory that checks the expiration of the token and replaces it?

**Comment by anurse** [comment]
I don't have a complete example ready at this time, it would depend on how your JWT token works. Since your token factory is called for every individual request, it's not a matter of "replacing" it, just return a different token from the factory when your token expires. Some pseudo code:

```csharp
// Somewhere outside the token provider:
private JwtToken _token = null;

var c = new HubConnectionBuilder()
    .WithUrl("...", options => {
        options.AccessTokenProvider = async () => 
        {
            if(_token == null || _token.ValidTo < DateTime.UtcNow.AddMinutes(1))
            {
                _token = await GetNewTokenAsync();
            }
            return _token.ToString();
        }
    })
    .Build();
```

**Comment by retsetman** [comment]
I just hadn't realized that a method that dynamically provides a token could be given to the `AccessTokenProvider ` and that this method is called every time a new request is made (in case of SSE or long polling). The example that @BrennanConroy provided assigned a string value to `AccessTokenProvider `, so it didn't lead me to the right direction. But this pseudo code helped and this pattern is working for me now. 
Probably also @grahambunce thought that the token cannot be replaced after the HubConnection has been built.
Thanks

**Comment by anurse** [comment]
It actually **always** has to be a function. It can just be a function that returns the same string every time 😄.

Glad to hear it seems to be working out for you! We definitely want to improve the scenarios here so please let us know if there's still a gap. We also just published docs on configuration, [including a segment on JWT tokens](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-bearer-authentication) and would definitely appreciate any feedback that would make that clearer!

I'm going to close this for now since it looks like the primary issue has been resolved. Feel free to comment further if there's any discussion and we can always file something new if there's an issue to fix.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
