### ISSUE TITLE
Consider using TryAddSingleton for services that users can override

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2432]
For our public services like `IUserIdProvider`,`IHubActivator`, `HubLifetimeManager`, and `IHubProtocolResolver` we should be using `TryAddSingleton` so that if a user adds the service before calling `AddSignalR` we don't override their setting.

https://github.com/aspnet/SignalR/blob/948ebf34ece11918804f443b65c6a053dfc8f35c/src/Microsoft.AspNetCore.SignalR.Core/SignalRDependencyInjectionExtensions.cs#L23-L30

@davidfowl Did we have a reason for using `AddSingleton` or did we just forget?

Technically this would be a breaking change, but in a good, probably acceptable, way.

**Comment by davidfowl** [comment]
We forgot, seems like a fine thing to change in 2.2. I'm not sure we need to patch it but we can if there's evidence that people are seeing problems.

**Comment by mikaelm12** [comment]
Done: e41764c161574983c49362cfb29ce23eb5941b74
