### ISSUE TITLE
Throwing HubException from server should bypass EnableDetailedErrors flag

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2439]
Just like ASP.NET SignalR

**Comment by anurse** [comment]
Yep, that makes sense. We should do it.

**Comment by MiszczProgramowania** [comment]
I have better idea... implement possibility to extend/overide some functionalities of exceptions parsing  and handling.

It will open possibility for implementation of:
Throwing HubException from server should bypass EnableDetailedErrors flag
and a at least hundred of other strategies...

**Comment by davidfowl** [comment]
I don’t think we’re going to be providing any extensibility here. We’re going to do what ASP.NEt SignalR does and see if satisfies 90% of users. We have no desire for pre-mature extensibility that a majority of users don’t need.

**Comment by mikaelm12** [comment]
Done here: c7ebae47ea3569183a27c1edd745d79da7c8f159
