### ISSUE TITLE
Typescript client efficient handling of error messages from server.

### ISSUE THREAD

**Issue by IonutArhire** [aspnet/SignalR#2445]
As per issue #2437 I enabled EnableDetailedErrors flag:

```
services.AddSignalR().AddHubOptions<MatchHub>(options => {
                options.EnableDetailedErrors = true;
});
```

I throw HubException the same way:

```
public async Task SendResources(string gameKey) {
      throw new HubException("oops");
      ...
}
```
And my typescript client handles the error the same:

```
public connected(data): void {    
  this._hubConnection.invoke('SendResources', this._gameKey).catch(this.errorHandler);
}

public errorHandler(err): void {
  console.log(err);
}
```
I get the HubException message on the client, but the problem is I can't easily get the message out without parsing:

![capture](https://user-images.githubusercontent.com/26301880/41093188-5313b168-6a53-11e8-968a-1041a5abacd7.PNG)

![1](https://user-images.githubusercontent.com/26301880/41093243-83ab4e8a-6a53-11e8-9265-899cd40a48bd.PNG)

I've tried throwing using an InnerException like this:

`throw new HubException("oops", new Exception("oops"));`

but I can't even access the inner exception on the client.

Do I need to parse it or is there another way provided by signalR? Isn't there a specialized signalR object for errors?

Versions:
.net core: 2.1
angular: 5
@aspnet/signalr: 1.0.0

**Comment by anurse** [comment]
For now you need to parse it out. The main issue here is that SignalR is not coupled to .NET, since an error could be flowing from Client to Server and the client could be written in any language. We could look at developing some kind of "protocol" for error message objects, but we'd need to design that. What kind of information would you want to be able to communicate with errors? Just a "type" value as well as the original message?

**Comment by MiszczProgramowania** [comment]
Related with:
https://github.com/aspnet/SignalR/issues/2439

There is proposal that will fix this and related issue.

**Comment by IonutArhire** [comment]
For my app, a simple error code integer would be enough. I'm building a multiplayer game and I want the client app to receive an error if the user tries to enter a full game room or a non-existent game room. I find it more intuitive to use exceptions for these kind of use cases instead of having to type check the response.

**Comment by anurse** [comment]
#3235 will track this work from here.
