### ISSUE TITLE
Clients.All.myJsfunction cannot trigger the function in js file

### ISSUE THREAD

**Issue by Kriegthor23** [aspnet/SignalR#2446]
so Here is my issue 

i might be doing something wrong but what i basicly try is im trying to connect two peers with a video chat 
and while i try that in text chat part i use 

in ChatHub.cs part 
        public void Send(string name, string message)
        {
            // Call the broadcastMessage method to update clients.
            Clients.All.broadcastMessage(name, message);
        }
and corresponding JS part of it

 chat.client.broadcastMessage = function (name, message) { //my function does is job }

and this works very well 

but for video call 
in ChatHub.cs 

some function in ChatHub calls 

        public void GetConnectionIDandSet()
        {
            var users = JsonConvert.SerializeObject(ConnectedUsers);
            Clients.All.getConnectionIDandSet(users);
        }

and corresponding JS part of it

chat.client.getConnectionIDandSet = function (users) { // do the job }

and when i try to debug it on console 
Clients.All.getConnectionIDandSet(users); does not trigger 

chat.client.getConnectionIDandSet = function (users) { // do the job }

so what am i doing wrong at here 

* Versions of Server-Side NuGet Packages: SignalR 2.2.3
* Versions of Client-Side NuGet/NPM Packages: SignalR 2.2.3
* Are you using the C# client or the JavaScript client: 
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):  IIS Express
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome 66.0.3359.181 (official) (64 bit)

The gist for full project 
https://gist.github.com/Kriegthor23/54c1a246cba6e9fb9096c161edc99a59

Thanks for helps in advance 
And if this is a dupp of an issue maybe i missed in closed sections i appologize from the members in advance

**Comment by BrennanConroy** [comment]
Your issue belongs at https://github.com/SignalR/SignalR, please move it there

**Comment by anurse** [comment]
Closing as this issue related to the ASP.NET SignalR libraries (`Microsoft.AspNet.SignalR.*`) but this repo is for tracking issues in the ASP.NET Core SignalR libraries (`Microsoft.AspNetCore.SignalR.*` and `@aspnet/signalr*` on NPM). Please re-file the issue at http://github.com/SignalR/SignalR

**Comment by Kriegthor23** [comment]
sorry for putting it into the wrong repo @anurse  @BrennanConroy  
opened the new one in https://github.com/SignalR/SignalR/issues/4130 

ty for your help
