### ISSUE TITLE
[Proposal] Consider introducing the RPC layer

### ISSUE THREAD

**Issue by mkosieradzki** [aspnet/SignalR#245]
@davidfowl Thank you very much for yesterday presentation link! It was really helpful.

I was doing a lot of thinking about the new design. And I am not convinced very much about some Hub abstraction at all.

There is some design discrepancy in hubs by inheriting them from the legacy SignalR design while changing some fundamental concepts underneath.

On the one hand hubs introduces entities like groups and users which are extremely application-specific - on the other hand without ReliableConnection abstraction it tries to allow multiple HubLifetimeManager designs.

In my opinion there is at least one layer missing between Hub and Sockets (I really love the idea of separating sockets layer!). It's the RPC layer.

This layer should allow procedurę invocation on both connection sides and should allow pluggable RPC protocols.

Just to mention: gRPC, JSON RPC...
(it complies with your idea of allowing multiple serialization formats). Maybe it's not the idea of serialization format that's worth consideration, but maybe the RPC format or both?

On top of this abstraction you can then build Hubs which will pursue the Users, Group delivery abstraction.
But maybe also a ReliableHub with reliable connections? I would definitely make the Hub-layer thinner.

OK. And now long shot. Why not to allow hub abstraction over ... message oriented RPC protocols like WAMP? :)

**Comment by davidfowl** [comment]
> There is some design discrepancy in hubs by inheriting them from the legacy SignalR design while changing some fundamental concepts underneath.

What discrepancy is that? The hub is a pretty high level, very specific RPC protocol to support the scenarios we think are important to the most people (based on our experience with previous versions of SignalR).

> on the other hand without ReliableConnection abstraction it tries to allow multiple HubLifetimeManager designs.

Can you elaborate? There are some people that use SignalR for very simple "close to the metal" websocket like scenarios. We don't want to force everyone to go through a very heavy abstraction when their scenario doesn't care about it. Furthermore, previously scale out was *very* specific and not very scalable TBH and the new design gives greater flexibility without sacrificing the ease of use.

> In my opinion there is at least one layer missing between Hub and Sockets (I really love the idea of separating sockets layer!). It's the RPC layer.

I'm not convinced there needs to be a generic RPC layer. Build a few of those and show me how they are all similar and why they need to build on top of each other. 

> This layer should allow procedurę invocation on both connection sides and should allow pluggable RPC protocols.

> Just to mention: gRPC, JSON RPC...
(it complies with your idea of allowing multiple serialization formats). Maybe it's not the idea of serialization format that's worth consideration, but maybe the RPC format or both?

We have a sorta kinda

> OK. And now long shot. Why not to allow hub abstraction over ... message oriented RPC protocols like WAMP? :)

We looked at WAMP but were unconvinced we needed to support it directly. It also is message based (which is fine) but we didn't want that to be the primitive we built the lower layers on top of. As for Hubs on top of WAMP directly? Sure, sounds like it could be interesting but it's not the directly we're currently going in.

**Comment by mkosieradzki** [comment]
> The hub is a pretty high level, very specific RPC protocol to support the scenarios we think are important to the most people (based on our experience with previous versions of SignalR).

Is Hub RPC protocol really that specific? I rather see a generic RPC protocol (method invocation).

> What discrepancy is that?

It is that on the one hand high level and on the other totally low-level as it does not understand reliable connection abstraction.

> We have a sorta kinda have an abstract RPC layer 

I would definitely excercise the classes you have mentioned by moving them to an abstract RpcLayer - those classes are definitely not-hub or SignalR specific! At the end of the day you end up with some method invocation. This is just the RPC layer.

> We looked at WAMP but were unconvinced we needed to support it directly

WAMP (as other message based protocols) specifically has one advantage which is the router abstraction. It allows to establish a reliable connection on top of multiple connections.

> Furthermore, previously scale out was very specific and not very scalable TBH and the new design gives greater flexibility without sacrificing the ease of use.

I partially agree, but by dropping the ReliableConnection abstraction you are making multiple you are offering quite different service than before.


I totally agree that default configurations should be similiar to what is currently available, but imagine following design.

Three layers:
- Socket
- RpcChannel
- Hub

Most trivial, default RpcChannel is close to the metal exactly what you have now. It is tied to the socket connection (connection breaks then channel breaks). It uses your variant your json formatter, or just standard JSON RPC (it is really similar to what you did, why not to use the standarized one?).

But one can implement for example a reliable RpcChannel that does reconnects, conducts message replies if needed, store unsent messages in some durable queue to ensure guaranteed delivery, kills duplicates.

Someone else might implement an RpcChannel using gRPC to have compatbility with Binary clients on the hub-level as well.

AFAIR You said in the presentation you don't like the formatters approach. In this design you don't need formatters at all. Formatters are the implementation detail of the RPC channel. That way you can add additional fields responsible for reliable connections and stuff!

From the typescript client perspective this is the same. You can have default RpcChannel, but you can also insert an alternative RpcChannel that handles all the missing messaging. So in the TypeScript client RpcChannel should also be pluggable.
