### ISSUE TITLE
Force all Hubs to require authentication

### ISSUE THREAD

**Issue by kofifus** [aspnet/SignalR#2452]
In older versions I would do:
	`Microsoft.AspNetCore.SignalR. GlobalHost.HubPipeline.RequireAuthentication();`
to force all hubs to require authentication even if they do not have [Authorize] 

But with latest Core 2.1 this does not compile anymore.
What is the current way to do this ?

**Comment by mikaelm12** [comment]
There's no way to require authentication on all hubs in a single call right now as there was in Classic SignalR.

**Comment by mikaelm12** [comment]
Additionally the GlobalHost type isn't in ASP.NET Core SignalR

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
