### ISSUE TITLE
Missing HubConnectionBuilderHttpExtensions methods

### ISSUE THREAD

**Issue by myrup** [aspnet/SignalR#2454]
After switching from 2.1 rc1 to release (.Net Core and SignalR C# client) some `HubConnectionBuilderHttpExtensions` methods (like `WithHeader`) are missing.

To reproduce create a 2.1 Console Project and add NuGet package `Microsoft.AspNetCore.SignalR.Client`:
![screen shot 2018-06-08 at 04 28 46](https://user-images.githubusercontent.com/1935820/41136004-774cb454-6ad4-11e8-802e-55587d8a9e26.png)

**Comment by BrennanConroy** [comment]
WithUrl takes a delegate that allows you to configure things like headers.

**Comment by myrup** [comment]
Ah ok so it has been deprecated? In that case this documentation seems to be outdated:

[HubConnectionBuilderHttpExtensions.WithAccessToken](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnectionbuilderhttpextensions.withaccesstoken?view=aspnetcore-2.1).

**Comment by BrennanConroy** [comment]
The API docs need to be updated.

@Rick-Anderson How do the API docs get updated?

**Comment by mikaelm12** [comment]
Sent and email to @Eilon to Update the docs 👍

**Comment by mikaelm12** [comment]
Going down the email rabbit hole ...

**Comment by mikaelm12** [comment]
These docs have been updated! https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnectionbuilderhttpextensions.withurl?view=aspnetcore-2.1
