### ISSUE TITLE
The AsChannelReader sample doesn't handle the case when the connection is closed

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/SignalR#2456]
I'm using the Git 1.0.0 tag, run build.cmd and then run the `samples\SignalRSamples` application.

In a Browser, I choose the streaming examples, `Connect` and then choose `From Observable`.

When the observable completes, the channel properly completes and the observable's subscription is disposed. However, when I `Disconnect` before the observable completes, the channel in turn doesn't ever complete and the subscription remains active. Unbounded channels then effectively become a memory leak.

The latter is what I'm seeing in my application, where the observables don't ever complete by design and browsers just connect and disconnect to a Hub.

**Comment by anurse** [comment]
You mean the channel leaks on the server when the client disconnects? You need to check the `ConnectionAborted` token on the `Context` to detect that and clean things up. We should update the sample to illustrate that though.

Channels don't have a way for cancellation/completion to flow from the reader to the writer, so we use a Cancellation Token for that instead.

**Comment by anurse** [comment]
For the observable case, you'd want to unsubscribe from the observable and complete the channel when the cancellation token is triggered. We should update the [`AsChannelReader`](https://github.com/aspnet/SignalR/blob/dev/samples/SignalRSamples/ObservableExtensions.cs#L12) sample to do that too.

**Comment by davidfowl** [comment]
Ah yes this sample is missing that critical piece. Good catch.

**Comment by JanEggers** [comment]
I added the ct as @anurse mentioned and then do this:

 `ct.Register(() => channel.Writer.Complete());`

seems to work but im not shure its correct, there is also an overload of subscribe that takes a ct but then it doesnt return a disposable anymore...

**Comment by anurse** [comment]
> I added the ct as @anurse mentioned and then do this:
> 
> ct.Register(() => channel.Writer.Complete());

This is what I would do. If you want to signal "cancellation" rather than just completion you can pass `OperationCancelledException` in the exception parameter to `Complete`. I don't know that SignalR does anything with that today though.
