### ISSUE TITLE
How does signalR maps ConnectionId to connection for specyfic client?

### ISSUE THREAD

**Issue by AwanesowArtem** [aspnet/SignalR#2460]
One more question:
Let's assume that there are two servers with signalR, I will connect to first server, will second server be able to invoke methods on client if it knows ConnectionId?

**Comment by BrennanConroy** [comment]
If you are using Redis for scaleout yes

**Comment by AwanesowArtem** [comment]
But how? If second server knows nothing about the client, how will it work? I think I do not have clear understanding how SignalR is mapping ConnectionId to HttpConnection

**Comment by BrennanConroy** [comment]
Because the two servers are talking to each other over Redis. So if you send a message to a specific connection id the server you're sending to first checks if it knows that connection id, if it doesn't it will send the message over Redis to the other server(s) and the server with that connection id will then send it to the correct client.

**Comment by AwanesowArtem** [comment]
@BrennanConroy , could you please explain? Thank you in advance

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-in-signalr

This is a link to the ASP.NET SignalR scaleout docs, be aware that this isn't the same as ASP.NET Core SignalR so some things wont apply, but the general idea and pictures should give you a good idea of how scaleout works.

**Comment by AwanesowArtem** [comment]
Thank you for quick answers!

**Comment by mikaelm12** [comment]
The main idea here is that even if there are clients connection to different servers that don't know anything about each other directly, they communicate with a backplane (Redis for example). The backplane is the unifying element here
![signalr-backplane](https://user-images.githubusercontent.com/4809660/41185290-a2ca50fc-6b3b-11e8-9f0f-c55e957cbf28.png)
