### ISSUE TITLE
Failed to start the connection: Error: Unable to initialize any of the available transports.

### ISSUE THREAD

**Issue by ZainElDeen** [aspnet/SignalR#2464]
I'm facing this error while trying to make a demo using 
SignalR :  * @version 1.0.0.
ASPNetCore 2.1
Vue.js

![untitled](https://user-images.githubusercontent.com/40148176/41205423-6ecb2d9e-6cf3-11e8-8a4c-7a48a5f2fbc2.jpg)
 This is the error at the console window
anyone can help?

**Comment by anurse** [comment]
Can you follow the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) and provide client and server logs as well as a network trace from Chrome? We need more detailed information to be able to diagnose your issue.

**Comment by CorrieP** [comment]
Hi there
I also had this issue. I was using Visual Studio Code and the launch.json file that VSCode creates automatically points to an old buid: *bin/Debug/netcoreapp2.1*.
Maybe try and delete all your bin/Debug or bin/Release folders and try again.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
