### ISSUE TITLE
Equivalent for HubConnectionBuilder WithConsoleLogger()

### ISSUE THREAD

**Issue by alexiordan** [aspnet/SignalR#2466]
What is the equivalent in SignalR 1.0.0 for the WithConsoleLogger() found in preview1?

**Comment by anurse** [comment]
You use `.ConfigureLogging` and configure it the same way you configure logging on the server:

```csharp
var connection = new HubConnectionBuilder()
    .WithUrl("...")
    .ConfigureLogging(logging => {
        logging.AddConsole();
    })
    .Build();
```

We have some docs on configuration (including logging) coming soon!

Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.

**Comment by alexiordan** [comment]
'ILoggingBuilder' does not contain a definition for 'AddConsole' and no extension method 'AddConsole' accepting a first argument of type 'ILoggingBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by anurse** [comment]
You need to bring in the appropriate Logging provider package. In for Console that's `Microsoft.Extensions.Logging.Console`
