### ISSUE TITLE
simplify HubConnection ctors - ILoggerFactory should not be required, IInvocationAdapter

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#247]
Previously tracked as #206

**Comment by moozzyk** [comment]
Related: https://github.com/aspnet/SignalR/issues/235

**Comment by mikaelm12** [comment]
Mainly addressed in https://github.com/aspnet/SignalR/pull/253 and https://github.com/aspnet/SignalR/pull/238
