### ISSUE TITLE
Pull up System.Threading.Tasks.Extensions and System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2474]
In order to fully fix #2406 we need to pull our transitive reference of `System.Threading.Tasks.Extensions` and `System.Runtime.CompilerServices.Unsafe` up to `4.5.1`. We get those through `System.IO.Pipelines` but corefx doesn't flow transitive dependencies up.

This is only **required** in the client, but it is a Common package that references `System.IO.Pipelines`. There's no reason we couldn't just reference these packages directly in the `Microsoft.AspNetCore.SignalR.Client.Core` package though, even though that package doesn't directly depend upon `System.IO.Pipelines`.

cc @davidfowl

**Comment by anurse** [comment]
Proposing for 2.1.3. It's unintuitive for users to have to take this dependency in order to work in UWP/Xamarin

**Comment by muratg** [comment]
Approved for 2.1.3.

**Comment by Eilon** [comment]
@anurse / @BrennanConroy / @mikaelm12 - is this still planned for 2.1.3?

**Comment by BrennanConroy** [comment]
It seems like that change made some things better and others worse. Because there is a workaround to this issue that doesn't make other scenarios worse I don't think we'll take the change until everything works.

@anurse is back in a couple days, can we wait that long?

**Comment by Eilon** [comment]
Time is kind of running out, so I'm moving this to 2.1.4 for now. When @anurse returns we will see where we are at and if we want to try to take this in 2.1.3. But the bar would be super duper ultra mega high.

**Comment by Eilon** [comment]
@anurse - do you have any thoughts on patching this?

**Comment by anurse** [comment]
Let's hold it for now. People are successfully using Xamarin, this was just a minor improvement.

**Comment by Eilon** [comment]
OK just ping me in this issue if we change our mind.

**Comment by muratg** [comment]
@anurse this is NOT in 2.1.4 right? (Please feel free to remove from the milestone.)

**Comment by anurse** [comment]
Closing this. We need to re-evaluate what the right fixes are here. Might need to gather some feedback from current Xamarin users.
