### ISSUE TITLE
Unable to connect Hub because "Missing required property 'protocol'"

### ISSUE THREAD

**Issue by Kadgiko** [aspnet/SignalR#2478]
Since upgrading from `1.0.0-preview1-update1` to `1.0.0`, I have not been able to connect to my hub with the following error. I do not understand what I have done wrong. I have read that it might be because the two version of the client and server did not match. But as mentionned below, I doubled checked to have version 1.0.0 everywhere. I tried using the withHubProtocol without success and didn't find any example using it either. Seems default to `JsonHubProtocol` in the `build()`, so again I do not understand why it would not be defined properly.

> Microsoft.AspNetCore.SignalR.HubConnectionContext:Error: Failed connection handshake.
> System.IO.InvalidDataException: Missing required property 'protocol'.
>    at Microsoft.AspNetCore.SignalR.Protocol.HandshakeProtocol.TryParseRequestMessage(ReadOnlySequence`1& buffer, HandshakeRequestMessage& requestMessage)
>    at Microsoft.AspNetCore.SignalR.HubConnectionContext.HandshakeAsync(TimeSpan timeout, IReadOnlyList`1 supportedProtocols, IHubProtocolResolver protocolResolver, IUserIdProvider userIdProvider, Boolean enableDetailedErrors)

Am I missing something important? What could I look into to troubleshoot this?

* Versions of Server-Side NuGet Packages:
    `<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0" />`
    `<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.0.0" />`
* Versions of Client-Side NuGet/NPM Packages
    "@aspnet/signalr": "1.0.0",
* Are you using the C# client or the JavaScript client:
     Javascript client (Typescript with "@types/signalr": "2.2.35")
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
     Kestrel (default with VSCode)
* The Operating System on the Server (Windows/Linux/macOS):
     Microsoft Windows 10 Pro, Version	10.0.16299 Build 16299
* The Operating System on the Client (Windows/Linux/macOS):
     Microsoft Windows 10 Pro, Version	10.0.16299 Build 16299
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
     Chrome
* Kestrel server stack
     [server.txt](https://github.com/aspnet/SignalR/files/2095757/server.txt)

* Code example:
```
class MyHub {
    public connection: signalR.HubConnection;

    constructor(url: string) {
        this.connection = new signalR.HubConnectionBuilder()
            .withUrl(url || '/signalr')
            .configureLogging(signalR.LogLevel.Trace)
            // .withHubProtocol(new signalR.JsonHubProtocol())
            .build();

        this.connection.start();
    }

    execute = (callback) => {
        return this.connection.connection.startPromise.then(() => {
            if (typeof callback === typeof (Function)) {
                callback(this.connection);
            }

            return this.connection.connection.startPromise;
        }).catch((e) => {
            LogSrv.log(LogLevel.Error, 'There was an error connecting to the hub. Please check the configuration.');
        });
    }
}
```
```
this.hub.execute((connection) => {
    connection.connection.invoke('log', logLevel, message).catch(() => {
        LogSrv.log(LogLevel.Error, 'could not log message \'' + message + '\'');
    });
});
```
```
this.hub.execute((connection) => {
    return connection.invoke('connect', instanceId).catch((error) => {
        LogSrv.log(LogLevel.Error, 'Failed to connect instance');
        LogSrv.log(LogLevel.Error, error);
    });
});
```
```
public partial class MyHub : Hub
{
    private ILogger Logger { get; set; }

    public InstanceHub(ILoggerFactory loggerFactory) =>
        (Logger) = (loggerFactory.CreateLogger<InstanceHub>());

    public async void Connect(string instanceId)
    {
        var instance = InstanceController.Get<ExcelInstance>(instanceId);

        instance.AddConnection(Context.ConnectionId);

        await Groups.AddToGroupAsync(Context.ConnectionId, instanceId);
    }

    public override Task OnConnectedAsync()
    {
        Console.WriteLine("This is not triggered.");

        return base.OnConnectedAsync();
    }

    public void Log(LogLevel level, string message)
    {
        Logger.Log(level, message);
    }
}
```
```
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();
        services.AddSignalR();
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseExceptionHandler("/Home/Error");
        }

        app.UseStaticFiles();

        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller=FileViewer}/{action=OpenFile}");
        });

        app.UseSignalR(routes =>
        {
            routes.MapHub<InstanceHub>("/signalr");
        });

        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .WriteTo.Console()
            .WriteTo.File("../temp/logs.txt", LogEventLevel.Debug)
            .CreateLogger();

        loggerFactory.AddSerilog();
    }
}
```

**Comment by BrennanConroy** [comment]
Few things:
* Gather a network trace as described https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#network-traces
* Never use `async void` for your hub methods (and most other times too)
* `this.connection.start();` returns a promise, don't use `this.connection.connection.startPromise`, those are private and the only reason you can access them is because javascript

**Comment by BrennanConroy** [comment]
Actually, you probably don't need to get the network traces. Fix your code to wait on `connection.start()` and you'll fix the issue

**Comment by Kadgiko** [comment]
Thanks, you are right, I assumed `startPromise` did the same as saving the start() promise.

**Comment by mikaelm12** [comment]
Seems like this has been resolved. Going to close this but feel free to reopen if something persists
