### ISSUE TITLE
"Message is incomplete" error

### ISSUE THREAD

**Issue by SqweeeRyan** [aspnet/SignalR#2487]
Hello! I just upgraded to 1.0.0 from 1.0.0-rc1-final on both the front-end and back-end. With no other code changes, we started getting an error being thrown in signalr.js:

"Error: Message is incomplete.
    at Function.TextMessageFormat.parse (https://localhost:44361/lib/aspnet-signalr/signalr.js:1404:19)
    at JsonHubProtocol.parseMessages (https://localhost:44361/lib/aspnet-signalr/signalr.js:3082:62)
    at HubConnection.processIncomingData (https://localhost:44361/lib/aspnet-signalr/signalr.js:1940:42)
    at WebSocketTransport.HubConnection.connection.onreceive (https://localhost:44361/lib/aspnet-signalr/signalr.js:1760:68)
    at WebSocket.webSocket.onmessage (https://localhost:44361/lib/aspnet-signalr/signalr.js:2619:47)"

I added a console.log to that TextMessageFormat.parse method to see the input, and I see that it is a C# object that is being broken into half. That is, the first message is of length 2,049 characters. Then that exception is thrown. Then I immediately get the next message that is about the same length (2,046 characters), followed by the same exception. Finally, I get the 3rd, and final message that completes the C# object...and that throws an exception of:

"Unexpected token f in JSON at position 3"

Again, this is the same code that was working for 1.0.0-rc1-final. Wondering if anybody has any insights about what might be going on? Is there a trick for how I should be passing the data to the client that has changed since rc1?

My method of passing the data to the front-end, from the hub, follows:
```csharp
await Clients.Client(Context.ConnectionId).SendAsync("FullRsvpListOfAttendees", attendees.Select(n => new
{
   AttendeeId = n.AttendeeId,
   FirstName = n.AttendeeFirstName,
   LastName = n.AttendeeLastName,
   IsMuted = n.IsMuted
}).ToList());
```
Thank you!

**Comment by MutatedBread** [comment]
Leaving tactical dot here .

**Comment by anurse** [comment]
Server and client logs (also described in the Diagnostics Guide) would also help.

**Comment by SqweeeRyan** [comment]
Attached!

It's hard to tell for sure, but it looks, to me, like the "TextMessageFormat.RecordSeparator" is missing from the end of the message that is being sent from the server to the client. 

Hopefully I properly generated these logs. Please let me know if there's anything more I can provide, or if you would like to take 5/10 minutes for a quick Zoom/screenshare to show you live.

[Server Log.txt](https://github.com/aspnet/SignalR/files/2103563/Server.Log.txt)
[Client Log.txt](https://github.com/aspnet/SignalR/files/2103564/Client.Log.txt)
[localhost.har.txt](https://github.com/aspnet/SignalR/files/2103565/localhost.har.txt)

**Comment by SqweeeRyan** [comment]
Ahhh, it appears to be a problem with the [Azure SignalR Service](https://azure.microsoft.com/en-us/services/signalr-service/) - I turned that off, and everything works great. Then I turn it back on and we get the errors back again.

Is this the right place to leave this error report? I don't see a GitHub repo for the AzureSignalR to leave issue reports.

**Comment by BrennanConroy** [comment]
You can file issues at https://github.com/Azure/azure-signalr/issues

**Comment by SqweeeRyan** [comment]
Not sure how I missed that. Thx, I'll close this and report there.
