### ISSUE TITLE
Cannot start a connection that is not in the Initial state

### ISSUE THREAD

**Issue by chauhan-saurabh** [aspnet/SignalR#2488]

**Comment by BrennanConroy** [comment]
We're gonna need more info if you want help
### Please include as much of the following as you can

* Versions of Server-Side NuGet Packages:
* Versions of Client-Side NuGet/NPM Packages:
* Are you using the C# client or the JavaScript client:
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
* The Operating System on the Server (Windows/Linux/macOS):
* The Operating System on the Client (Windows/Linux/macOS):
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
* Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please **do not** put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.

**Comment by chauhan-saurabh** [comment]
Hey @BrennanConroy,

Thanks for your response i am using signalR in my react-native app and backend server in .Net Core 2.0 i am able to successfully integrate signalR in my project but getting issue while reconnecting to hubconnection using hubConnection.start() function because i am getting automatically disconnect after 30seconds or more i am getting Error : Cannot start a connection that is not in the Initial state 

1. Versions of Server-Side NuGet Packages:  

2. Versions of Client-Side NuGet/NPM Packages: using SignalR-client in react native app "@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha2-final.min.js"

3. Are you using the C# client or the JavaScript client: using javascript client 

4. The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Kestrel

5. The Operating System on the Server (Windows/Linux/macOS): Linux

6. The Operating System on the Client (Windows/Linux/macOS): IOS/ Android (react-native)

The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please do not put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.

**Comment by anurse** [comment]
Note: On the server, you upgrade to ASP.NET Core 2.1 and then **remove** the SignalR server dependencies (as they are built in to ASP.NET Core)

**Comment by chauhan-saurabh** [comment]
Hey @BrennanConroy How can i upgrade to 1.0.0 and should it works with React Native also ?

**Comment by BrennanConroy** [comment]
Install the newest npm package https://www.npmjs.com/package/@aspnet/signalr and update your server reference to the latest https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR/

**Comment by chauhan-saurabh** [comment]
@BrennanConroy  i cant find the code compatible with react-native in newest npm package https://www.npmjs.com/package/@aspnet/signalr
i got multiple errors

**Comment by chauhan-saurabh** [comment]
i am accessing hubconnection as 

import { HubConnection } from "@aspnet/signalr/dist/browser/signalr";

**Comment by anurse** [comment]
The APIs have changed since the alpha version you used. See the [JavaScript Client Documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1) for more information.

**Comment by chauhan-saurabh** [comment]
@anurse is it compatible with React Native

**Comment by anurse** [comment]
Yes, it should be compatible. I believe others have successfully used SignalR on React Native. However, we do not provide official support for React Native at this time. We just don't have the infrastructure to test on it (and other platforms are a higher priority for us right now).

Having said that, we're happy to help make sure it works. If you encounter an issue, let us know and we'll try to help and fix what we can fix, but we don't commit to "official" support outside of a standard Web Browser at this time.

**Comment by chauhan-saurabh** [comment]
Thanks @anurse for your support and time i'll make a try and let you know if got any issue.

**Comment by anurse** [comment]
I'm going to close this issue for now, since it looks like there isn't anything for us to fix right now. Feel free to comment further or open a new issue if you encounter issues! Please take a look at the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) before opening a new issue, and collect the logs/traces requested there.
