### ISSUE TITLE
waiting in console client for received messages

### ISSUE THREAD

**Issue by kofifus** [aspnet/SignalR#2489]
Looking at the [HubSample.cs](https://github.com/aspnet/SignalR/blob/dev/samples/ClientSample/HubSample.cs)

The sample client is waiting on console input and sending it to the hub.

A more common scenario is where you want the client to send some messages and then wait for any incoming messages from the hub, and only exit when the hub disconnected.

What is the correct way to wait in the console client for messages when Console.ReadLine() etc are not relevant ?

**Comment by BrennanConroy** [comment]
Waiting is very application specific. If you really just want to sit around doing nothing and wait for messages to be received you could do something like:
```
while (some condition)
{
    // wake up every 5 seconds
    await Task.Delay(5000);
}
```
