### ISSUE TITLE
HubConnection on JsClient keep all the handler registration

### ISSUE THREAD

**Issue by ste4net** [aspnet/SignalR#2493]
I am using Js client 1.0.0 in a typescript angularX project.

In my test i ha declared an HubConnection as property of component class and initialized it during component initizialization.

HubConnection keep all the previous handler registration even creating and initializing a new HubConnection.

 
```
[…]
export class SignalRComponent implements OnInit, OnDestroy {
  public conn: HubConnection;
  ngOnInit() {
   […]
     this.conn = (new HubConnectionBuilder())
        .withUrl(`/messageHub`, options)
        .configureLogging(LogLevel.Information).build();
     this.conn.on("testMessage", (n, m) => console.log([n, m]));
      this.conn.start().then(() => {
        console.log('Hub connection started')
      }).catch(err => {
          console.log('Error while establishing connection')
        });
   }
[…]
```
 

Every time a new SignalRComponent is created a new handler to "testMessage" is register. If i create (and destroy) SignalRComponent  3 times i have 3 messages for each "testMessage".

To solve this i keep attention at manual unregistering process.
During component destruction i have to unregister event and stop connection.

```
  ngOnDestroy(): void {
    this.conn.off("testMessage");
    this.conn.stop().then(() => console.log("Hub connection stopped"));
  }
```

**Comment by mikaelm12** [comment]
This is the intended functionality. 
We were designing for the scenario in which something happens to a connection and it has to be restarted We wanted to avoid making people have to re-register all their handlers. The compromise was I added the `off` method to remove handlers for a specific name with out needing to keep an actual reference to the handlers.

**Comment by anurse** [comment]
Are there multiple `SignalRComponent` instances on a single page? If so, there's no reason to create a separate `HubConnection` for each, you could just share a single `HubConnection` among all of them.

**Comment by ste4net** [comment]
@anurse  I made the test in a Angular5 SPA . SignalRComponent in this case are only one per "page" but moving from components to another everytime SignalRComponent is recreated it keep trace of older handlers.
I think the best way here is to use it in a global shared service.

**Comment by anurse** [comment]
Yeah, in a SPA I think a single shared connection makes sense. There's no need to recreate the connection on navigation.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
