### ISSUE TITLE
Publish client to cdnjs?

### ISSUE THREAD

**Issue by los93sol** [aspnet/SignalR#2505]
With LibraryManager getting full integration into VS current previews it would be great if the client was published to cdnjs in addition to npm so I could eliminate npm from my workflow.

**Comment by anurse** [comment]
We talked about this earlier and decided we didn't really want to publish to a bunch of different CDNs. [Unpkg](https://unpkg.com/) automatically publishes NPM package content and I believe LibraryManager has support, or is adding support for unpkg.

If there's significant interest in adding more CDNs, we're certainly not opposed to the idea, but for LibMan, unpkg is the solution we're going with for now.

**Comment by los93sol** [comment]
Sounds like that effectively accomplishes what I was looking for.  Glad to hear the discussions are happening and see the consistency!  Thanks to everyone at MS and the community contributing!

**Comment by los93sol** [comment]
Sounds like that effectively accomplishes what I was looking for.  Glad to hear the discussions are happening and see the consistency!  Thanks to everyone at MS and the community contributing!
