### ISSUE TITLE
How do I get a reference to a Hub? private data

### ISSUE THREAD

**Issue by kofifus** [aspnet/SignalR#2506]
I have seen https://github.com/aspnet/SignalR/issues/182 but I'm having an issue with that solution

in https://github.com/aspnet/SignalR/issues/182 the suggestion is to "creating and injecting a class with shared logic" like this:

```
namespace SharedHubLogic
{
    class HubMethods
    {
        private IHubContext<THub> _hubContext;
        public HubMethods(IHubContext<THub> hubContext)
        {
            _hubContext = hubContext;
        }

        public Task WriteMessageAsync(string method, param object[] args)
        {
            return _hubContext.Clients.All.InvokeAsync(method, args);
        }
    }
}

class CrawlHub : Hub
{
    private HubMethods _hubMethods;
    public CrawlHub(HubMethods hubMethods)
    {
        _hubMethods = hubMethods;
    }

    public Task CrawlFailed(string reason)
    {
        return _hubMethods.WriteMessageAsync("writeStatus", reason);
    }
}

```
my problem is the management of private data... If for example I am keeping a list of connectionIDs updated in OnConnectedAsync and OnDisconnectedAsync and want a GetConnectionIDsList() method in the HubMethods class .. I suddenly need the connections dictionary to be public in that class which is ugly.

What is the best way to solve this ?

**Comment by anurse** [comment]
Why does the dictionary need to be public? Can't you just add the methods you need to access the dictionary to the `HubMethods` class? Could you show more of the code you're trying to write?

**Comment by kofifus** [comment]
Consider this:

```
namespace SharedHubLogic
{
    class HubMethods
    {
		public ConnectionData
		{
			public DateTime? connectionTime = null;
		}
        public Dictionary<string, ConnectionData> connections = new Dictionary<string, ConnectionData>();
        
        private IHubContext<THub> _hubContext;
        
        public HubMethods(IHubContext<THub> hubContext)
        {
            _hubContext = hubContext;
        }

        public Task SomeHubMethod(param object[] args)
        {
            return _hubContext.Clients.All.InvokeAsync("somemethod", args);
        }
        
        public Task GetConnectionData(string connectionID)
        {
            return connections[Context.ConnectionId];
        }
    }
}

class CrawlHub : Hub
{
    private HubMethods _hubMethods;
    public CrawlHub(HubMethods hubMethods)
    {
        _hubMethods = hubMethods;
    }

    public override async Task OnConnectedAsync()
    {
        _hubMethods.connections[Context.ConnectionId] = new ConnectionData();
        _hubMethods.connections[Context.ConnectionId].connectionTime = DateTime.Now();
        await Task.CompletedTask;
    }

    public override async Task OnDisconnectedAsync(Exception ex)
    {
        _hubMethods.connections[Context.ConnectionId].connectionTime = null;
        await Task.CompletedTask;
    }
}

```

You can see how I can either make connections public or move OnConnectedAsync/OnDisconnectedAsync to HubMethods, both not great.

It would be much more natural if I could simply get a reference to the hub instance and keep it all there.

**Comment by kofifus** [comment]
Thanks

Thew goal is twofold, first share hub method between the hub and another class (hence the need for HubMethods), and seconds keep a connections dictionary mapping connectionId to a ConnectionData.

The solution above while not having connections public has the disadvantage of having OnConnectedAsync/OnDisconnectedAsync and any method of MyHub that needs to access connections defined twice (both in SomeSingletonService and MyHub) ...
