### ISSUE TITLE
Get initial Java client in

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2508]
## Goals
* Supports JSON over WebSockets only
* HubConnection class with `.on`, `.invoke`, `.send`
* Can be single-use (not restartable) at this phase
* Can only support very limited set of types (for example, only `String` parameters, etc.)
* Should have Unit Tests.
* Very simple command line sample (can have hard-coded URL, hard-coded messages, or even been recieve-only etc.)
* Should be "production" code (tested, edge cases covered, etc.), just very **limited functionality**.

## Non-Goals
* Configuration (Headers, Cookies, Transport limitation, etc.)
* `HubConnectionBuilder`
* `HttpConnection` as a *public* API (though it would likely be good to have that abstraction for Unit Testing anyway)

**Comment by anurse** [comment]
Let's get the #2524 PR done with some unit tests and create issues to track individual work items moving forward.

**Comment by mikaelm12** [comment]
We've got an initial client in! Still a lot of work to go but I think this issue is good to be closed. I'll be filing individual issues for remaining work.

Client commits: 6b3437deb78eb1ff21bf524a7d9cf6ed3b3ecad0 and b0ce55e6c86a18d5e874456f1fd1fe49c70fac1f
