### ISSUE TITLE
Signalr works onPageLoad but does not send data to react component after Table Update

### ISSUE THREAD

**Issue by sourceship13** [aspnet/SignalR#2516]
Hello All, 

I have a Asp.Net Core 2.0 Project. I'm using IIS Express, Chrome, and Windows server 2016, and VS Studio 2017 to debug. 
When I load my project I can see my Hub being called and hitting my breakpoint before it returns to the Clients. I have setup SqlDependecyEx; When I update a row in my table I see my Hub being called and returning an array with the database objects in it, but I do not see my call back on the react component being called again. I have place console.log(pingRecords) in my callback on my component and see it get called the first time the page loads but not after I trigger a database update. I do see it hit my Hub on signalr but it does not reach my client's callback. 
Can you all help point me in the right direction. I am still new to Signalr and React so any input would help me out. Thank You all in advance and please let me know if I can provide any more info. Thanks!

**Here is my package.json :**
```
{
  "version": "1.0.0",
  "name": "dotnetify_react_template",
  "private": true,
  "scripts": {
    "webpackDev": "webpack-dev-server --hot --colors --progress --inline --config webpack.config.js"
  },
  "devDependencies": {
    "aspnet-webpack": "2.0.1",
    "aspnet-webpack-react": "3.0.0",
    "awesome-typescript-loader": "3.2.1",
    "babel-core": "6.26.0",
    "babel-loader": "7.1.2",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-0": "6.24.1",
    "chart.js": "^2.7.1",
    "css-loader": "0.28.7",
    "dotnetify": "3.0.0-pre",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "flexboxgrid": "6.3.1",
    "material-ui": "^0.19.4",
    "prop-types": "15.6.0",
    "react": "^16.4.0",
    "react-chartjs-2": "^2.6.4",
    "react-dom": "^16.4.0",
    "react-hot-loader": "3.1.1",
    "style-loader": "0.19.0",
    "url-loader": "0.6.2",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.2"
  },
  "dependencies": {
    "aspnet-webpack": "2.0.1",
    "aspnet-webpack-react": "3.0.0",
    "awesome-typescript-loader": "3.2.1",
    "babel-core": "6.26.0",
    "babel-loader": "7.1.2",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-0": "6.24.1",
    "chart.js": "^2.7.1",
    "css-loader": "0.28.7",
    "dotnetify": "3.0.0-pre",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "flexboxgrid": "6.3.1",
    "material-ui": "^0.19.4",
    "prop-types": "15.6.0",
    "react": "^16.4.0",
    "react-chartjs-2": "^2.6.4",
    "react-dom": "^16.4.0",
    "react-hot-loader": "3.1.1",
    "style-loader": "0.19.0",
    "url-loader": "0.6.2",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.2"
  }
}
```
**Here is my react component:** 
```
import React from 'react';
import dotnetify from 'dotnetify';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import globalStyles from '../styles/styles';
import ThemeDefault from '../styles/theme-default';
import auth from '../auth';
import BasePage from '../components/BasePage';
//import { Row, Card} from ''
import { pink500, grey200, grey500 } from 'material-ui/styles/colors';
import IconRemove from 'material-ui/svg-icons/content/clear';
import { log } from 'util';
import PropTypes from 'prop-types';
import { withStyles } from '@material-ui/core/styles';
import Card from '@material-ui/core/Card';
import CardActions from '@material-ui/core/CardActions';
import CardContent from '@material-ui/core/CardContent';
import Button from '@material-ui/core/Button';
import Typography from '@material-ui/core/Typography';
import Grid from '@material-ui/core/Grid';
import { ListItem } from 'material-ui';

const signalR = require("@aspnet/signalr");

var tileJson;

const styles = {
    card: {
        minWidth: 160,
        width: 180,
        margin: 20
    },
    cardTitle: {
        fontSize: 18,
        margin: 10,
    },
    cardLatency: {
    }
};
var listItems;

class DeviceMonitor extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            items: [],
            isLoading: true,
            signalrMessage: '',
            signalrHubConnection: null
        };

        
    }

    componentDidMount = () => {
        const signalrHubConnection = new signalR.HubConnectionBuilder().withUrl("/Hubs/DeviceHub").build();

        this.setState({ signalrHubConnection }, () => {
            this.state.signalrHubConnection.start()
                .then(() => signalrHubConnection.invoke("GetDeviceJson"))
                .catch((err) => console.log('Error:' + err));

            this.state.signalrHubConnection.on('DevicesFromHub', (pingRecords) => {
                console.log(pingRecords);
                const signalrMessage = pingRecords;
                this.setState({ signalrMessage });
                ;
                listItems = this.state.signalrMessage.map((d) =>
                    <Card style={styles.card} key={d.deviceName}>
                        <CardContent style={{ textAlign: 'center' }}>
                            <Typography variant="headline" style={styles.cardTitle} >
                                {this.state.DeviceList}
                            </Typography>
                            <Typography style={{ color: d.latencyColorCode, fontSize: 20 }} >
                                {d.recentLatency} ms
                        </Typography>
                            <Typography style={{ color: d.minsColorCode, fontSize: 18 }} >
                                {d.responseTimeDiff} mins ago
                        </Typography>
                        </CardContent>
                    </Card>
                );
                this.setState({ isLoading: false });
            });
        });

        //this.setState({ signalrHubConnection }, () => {
        //    this.state.signalrHubConnection.start().then(() => connection.invoke("GetDeviceJson").catch(err => console.log('SignalR Error:' + err)));

        //    this.state.signalrHubConnection.on("DevicesFromHub", (pingRecords) => {
        //        tileJson = pingRecords;
        //        const signalrmessage = pingRecords;
        //        this.setState({ signalrMessage });
        //        console.log('updated');
        //        listItems = this.state.signarMessage.map((d) =>
        //            <Card style={styles.card} key={d.deviceName}>
        //                <CardContent style={{ textAlign: 'center' }}>
        //                    <Typography variant="headline" style={styles.cardTitle} >
        //                        {d.deviceName}
        //                    </Typography>
        //                    <Typography style={{ color: d.latencyColorCode, fontSize: 20 }} >
        //                        {d.recentLatency} ms
        //                </Typography>
        //                    <Typography style={{ color: d.minsColorCode, fontSize: 18 }} >
        //                        {d.responseTimeDiff} mins ago
        //                </Typography>
        //                </CardContent>
        //            </Card>
        //        );
        //        this.setState({ isLoading: false });

        //    });

        //});
    }

    render() {
        if (this.state.isLoading == false) {
            return (
                <MuiThemeProvider muiTheme={ThemeDefault}>
                    <BasePage title="Device Monitor" navigation="Application / Device List">

                        <Grid container spacing={8}>
                            {listItems}

                        </Grid>
                    </BasePage>
                </MuiThemeProvider>
            );
        }
        else {
            return (
                <MuiThemeProvider muiTheme={ThemeDefault}>
                    <BasePage title="Device Monitor" navigation="Application / Device List">
                        <div>
                            <h1> loading </h1>
                        </div>
                    </BasePage>
                </MuiThemeProvider>
            );
        }
    }
}

export default DeviceMonitor;
```

**Comment by sourceship13** [comment]
Also Here is my SignalR Hub as well: 
'using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace Pinger
{
    public class DeviceHub : Hub
    {
        private static DeviceHub _deviceHub;

        public dynamic GetDeviceJson()
        {
            string connectionString = "Data Source=workstationsql;Initial Catalog=AsisDev;Integrated Security=True";
            List<LogRecord> pingRecords = new List<LogRecord>();

            using (var connection = new SqlConnection(connectionString))
            {
                string query = "Select [DeviceName], [RecentResponseMsg], [IPAddress], [DesiredTimeout], [RecentLatency], [LastResponseTime] From dbo.Device";
                connection.Open();
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    DataTable dt = new DataTable();
                    var listener = new SqlDependencyEx(SqlHelper.ConnectionString, "AsisDev", "Device");
                    listener.TableChanged += dependency_OnChange;
                    listener.Start();

                    if (connection.State == ConnectionState.Closed)
                    {
                        connection.Open();
                    }
                    var reader = command.ExecuteReader();
                    dt.Load(reader);
                    if (dt.Rows.Count > 0)
                    {
                        foreach (DataRow row in dt.Rows)
                        {
                            try
                            {
                                LogRecord log = new LogRecord();
                                log.DeviceName = row["DeviceName"] as string;
                                log.ResponseMessage = row["RecentResponseMsg"].ToString();
                                log.IPAddress = row["IPAddress"].ToString();
                                log.DesiredTimeout = row["DesiredTimeout"] as int?;
                                log.RecentLatency = row["RecentLatency"] as int?;
                                log.LastResponseTime = row["LastResponseTime"] as DateTime?;
                                pingRecords.Add(log);
                            }
                            catch (Exception e)
                            {
                                continue;
                            }
                        }
                    }
                }
            }

            foreach (LogRecord log in pingRecords)
            {
                //latency colors
                if (log.RecentLatency > log.DesiredTimeout)
                {
                    //red
                    log.LatencyColorCode = @"#af2139";
                }
                else if (log.RecentLatency < log.DesiredTimeout)
                {
                    //green
                    log.LatencyColorCode = @"#248232";
                }

                log.ResponseTimeDiff = Math.Round(DateTime.UtcNow.Subtract(log.LastResponseTime.GetValueOrDefault()).TotalMinutes);

                if (log.ResponseTimeDiff > 2)
                {
                    log.MinsColorCode = @"#af2139";
                }
            }

            //return Clients.All.SendAsync("DevicesFromHub", Newtonsoft.Json.JsonConvert.SerializeObject(pingRecords));
            return Clients.All.SendAsync("DevicesFromHub", pingRecords);
        }

        private void dependency_OnChange(object sender, SqlDependencyEx.TableChangedEventArgs e)
        {
            //SqlDependencyEx.NotificationTypes.Update
            Console.WriteLine("something changed");
            _deviceHub = new DeviceHub();
            _deviceHub.GetDeviceJson();
        }
    }
}'

**Comment by BrennanConroy** [comment]
Welcome to SignalR!

So there are a couple things that you should know that will help fix the issue:
* Never create a Hub instance manually, the library handles Hub creation as well as setting specific properties on the Hub that are used when calling `Clients.All` etc.
* The lifetime of a specific Hub instance is the duration of the method call. For example, when the client invokes `GetDeviceJson` a new Hub instance is created, your method is run, and then the Hub is destroyed. This means that you can't store state in the Hub.
* If you want to send to a client from the server without a Hub method being called you can get an `IHubContext<DeviceHub>` injected via DI somewhere else in your app and call `Clients.All` via that. See this doc for more details on how to do that: https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1

If you have any more questions feel free to ask!

**Comment by sourceship13** [comment]
Hi There! 

Thanks for your guidance, this is the first time for me to implement SignalR, I'm still learning the best practices. I think the last point you mentioned is what I will try to achieve. I'm reading more into the documentation you referenced, I think this is what I will try to implement. 

Just a quick question, what do you mean by "Inject via DL" ? I have heard others mention this but am, not entirely sure the meaning.

Also I am using dotnetify, I think I have a choice between implementing a web-socket call back in my or calling my Hub from my BaseVm that links to my React view with dotnetify. Do you have any two cents on the approach I should follow. 

Ultimately, I am trying to pass an array of object to my View and would like that array to update on database change event; so I have a real time view of the objects in a database table in my React View. I'm trying to achieve that using a web-socket connection. What would be the simplest way to achieve that, SignalR on my client or the Dotnetify approach with the BaseVm methods? 

Thanks in advance, You've already done a lot to point me in the right direction.

**Comment by BrennanConroy** [comment]
Unfortunately, I've never used dotnetify so I can't be of much help there.

**Comment by sourceship13** [comment]
No Problem. Thanks for the earlier Info, it helped steer me in the right direction. Have a Great Day.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
