### ISSUE TITLE
Sticky sessions when forcing WebSocket protocol

### ISSUE THREAD

**Issue by nphmuller** [aspnet/SignalR#2525]
If I understand correctly I have to force WebSocket transport to avoid the sticky sessions requirement.

I noticed however that when negotiation is enabled the connection id is still sent as a parameter when setting up the WebSockets connection (`GET /myhub?id={connectionId}`). Can this be a problem if I want to avoid sticky sessions? Do I have to disable negotiation on the client side? Because I'd rather have a server-side setting that works for all clients, if that's available.

**Comment by davidfowl** [comment]
We're currently in the process of writing a document about this but here's the PR:

https://github.com/aspnet/Docs/blob/39c125241f3911fd28596220372c69e827fc1e2a/aspnetcore/signalr/configuration.md#configure-additional-options

You want to set skipNegotiation to true to avoid the negotiation request. The caveats are also listed.

**Comment by nphmuller** [comment]
Thanks. So I take it there's no server side setting to disable negotiation, and none planned? Because it would be nice if my clients didn't have to worry about if my server supports sticky sessions or not.

**Comment by davidfowl** [comment]
> Thanks. So I take it there's no server side setting to disable negotiation, and none planned? Because it would be nice if my clients didn't have to worry about if my server supports sticky sessions or not.

No, there's no way to do it on the server and we currently don't plan to do so. You can expose an end point from your application decoupled from signalr that returned the right settings for the environment. Though I'm not sure how that would work either.

**Comment by davidfowl** [comment]
> So basically I have to make my own negotiation endpoint. I might experiment a bit with that.

Yep. I assume all it would be doing is returning a JSON payload with a bool telling the client if it should be sticky or not and that payload would be controlled by some environment settings? There's no way to detect if you're in an environment that won't work with sticky sessions so there's that.

> Or is there a way to make the negotiation endpoint not return the client id? 

No, you cannot make the existing negotiate end point *not* return a connection id.

**Comment by nphmuller** [comment]
> I assume all it would be doing is returning a JSON payload with a bool telling the client if it should be sticky or not and that payload would be controlled by some environment settings?

Probably not. The client shouldn't care if the session is sticky or not. It just needs to get the metadata describing what my server supports (which would be WebSockets transports, because I don't want to support sticky sessions on the server, and either text or binary serialization). Basically the data the current negotiation endpoint returns, without the connectionId.

Hopefully I can override the current negotiate endpoint with my own negotiate endpoint.
And the final hopeful thing would be that the SignalR clients accept a negotiate response without a connection id.

Lot's of things that can (and probably will) go wrong. But sounds fun to tinker with. :)

**Comment by davidfowl** [comment]
So let me try to see if I can summarize:

You'd like to be able to set a setting that says, never return a connection id from negotiate which would mean don't use sticky sessions right? 

That actually seems like a reasonable way to make things work. I believe it would require client changes though which means old clients won't work with this new feature. It also means that the only transport supported is websockets as the other transports require sticky sessions.

**Comment by nphmuller** [comment]
Good summary.

Just had a quick look at the source of the ts client. And you're right that it would require client changes. The connection id is required when negotiation, because it's always used to build the connect url: https://github.com/aspnet/SignalR/blob/7317762b29979b6dde7e38cc91e07561a44184ad/clients/ts/signalr/src/HttpConnection.ts#L223

**Comment by nphmuller** [comment]
Turns out the connection id is required for the .NET client. Would the PR have any chance to succeed if I removed the requirement from the .NET client?

**Comment by davidfowl** [comment]
We'd need to add versioning support to the client. If the client request doesn't container a version, it's version=1 and we can't assume that connection id can be null. If it has a version parameter then we take that into consideration and remove the connection id. We'd update the spec here with the relevant information.

/cc @anurse

**Comment by nphmuller** [comment]
That would defeat the purpose of the option: making sure the server doesn't require sticky sessions.

The spec says the connection id is only required for the Long Polling and Server-Side Events transports. So isn't it technically a bug in the .NET client implementation? Since it doesn't say its required for a Web Socket transport?

https://github.com/aspnet/SignalR/blob/6b3437deb78eb1ff21bf524a7d9cf6ed3b3ecad0/specs/TransportProtocols.md#L47

**Comment by nphmuller** [comment]
This line also makes it sound like the connectionId is optional in the response:
`A response that contains the connectionId which will be used to identify the connection on the server and the list of the transports supported by the server.`

**Comment by anurse** [comment]
> The spec says the connection id is only required for the Long Polling and Server-Side Events transports.

The spec specifies that the negotiate response contains a `connectionId` but the ID is only required to be **used** by the Long Polling and Server-Sent Events transports. So the spec still _requires_ that the server returns a connection ID (in the current version) it just doesn't require the client to use it. So it's expected that a client would rely on that behavior. Having said that, it's not unreasonable to change that in an updated spec and update the clients to expect that. We do have the versioning constraint here though, since the spec is changing mandatory behavior into optional behavior, so it needs to know if the client can handle that.

**Comment by anurse** [comment]
It wouldn't be unreasonable to have the client simply disregard the connection ID when connecting over WebSockets (thus allowing support for non-sticky sessions). The downside is that the connection created in the initial negotiation will have been created and will need to time out before those resources are released.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
