### ISSUE TITLE
Access token logged in server and ts client package

### ISSUE THREAD

**Issue by nphmuller** [aspnet/SignalR#2526]
In the Server-Side package and the TS Client-Side package (and possibly other Client-Side packages) the access token gets logged. This is because the token is sent as a query parameter.

* Versions of Server-Side NuGet Packages: 1.0.0
* Versions of Client-Side NuGet/NPM Packages: 1.0.0
* Are you using the C# client or the JavaScript client: JavaScript (TS)

**Comment by davidfowl** [comment]
> This is because the token is sent as a query parameter.

This isn't going to change in the short term see https://github.com/whatwg/html/issues/3062.

**Comment by nphmuller** [comment]
Maybe, as a workaround you could filter out the token in the log call? At least on the client side the logger is directly called from the signalr package, so it might be possible. On the server side it might be a bit harder.

**Comment by davidfowl** [comment]
Do you mean that you turned logging *on* and you want the token to be excluded from those logs? On the SignalR the token is logged by ASP.NET Core infrastructure, not from SignalR.

**Comment by nphmuller** [comment]
I didn't turn logging on for SignalR explicitly for both the Server and the TS Client package. Just using the default logging configuration for ASP.NET Core and whatever's the default for the browser.

When I connect the following is logged on the server side:
`2018-06-22 19:18:26 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost Request starting HTTP/1.1 GET http://localhost:5000/Monitor?access_token={access token here}`
And in the browser console:
`signalr.min.js:16: Information: WebSocket connected to ws://localhost:5000/Monitor?access_token={access token here}`

It'd be nice if the token could be excluded from this logs, or be replaced by `redacted` or something like that.

**Comment by davidfowl** [comment]
> I didn't turn logging on for SignalR explicitly for both the Server and the TS Client package. Just using the default logging configuration for ASP.NET Core and whatever's the default for the browser.

I'm saying that the layer that logs doesn't know that the query string is an access token so it would be difficult to do any filtering. That would be an entirely new feature to either disable all query strings or letting users disable specific query strings. I'm not sure this is realistic.

For the client, we can redact the access token (we can reuse the flag we have for logging message content).

**Comment by nphmuller** [comment]
> I'm not sure this is realistic.

Totally understandable. :)

Shall I leave this issue open to see if there's enough interest in this?

**Comment by davidfowl** [comment]
> Shall I leave this issue open to see if there's enough interest in this?

Which part of the issue?

**Comment by nphmuller** [comment]
Not sure actually. Client-side only filtering is probably less important than server side. But that one is a lot more difficult to accomplish. 

Any preference? Honestly it sounds to me that it's not realistic enough anyway.

**Comment by anurse** [comment]
Also, if you are using IIS, it will log the querystring and ASP.NET Core has no way to affect that. Unfortunately right now the only way to avoid this is to strip the token out of the relevant logs yourself. We've talked about doing #1802 to help make this cleaner.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
