### ISSUE TITLE
404 Negotiate problem in VS2017 React template

### ISSUE THREAD

**Issue by oevillegas** [aspnet/SignalR#2528]
I'm having trouble connecting to the Hub using the latest release of .Net Core 2.1 and SignalR within a React project template from Visual Studio 2017 (15.7.4).

I am seeing the 404 Negotiate error, and after a lot of searches, every answer pointed out that there was a compatibility between the server and the client, however, I have checked and made sure that I am using the latest libraries. (Project is referencing Microsoft.AspNetCore.App 2.1.0 SDK and @aspnet/signalr 1.0.0 for client)

An interesting part to this is that I followed the Getting started guide at [https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio](url) using the Razor Pages template from Visual studio and that works perfectly, but when I choose the React template and try to adapt it to it, then it fails to connect:

![image](https://user-images.githubusercontent.com/12765333/41782802-ddcfc2e8-7600-11e8-9f57-ff809f401ad0.png)

Here is the code that I'm using:

Note:  This is my first attempt at React, so the React component code below might not be best practices since I'm just learning it, I'm only posting this question so I can successfully make a connection between the signalr client and the hub.

Hub:
`
public class ChatHub:Hub
    {

        public async Task SendMessage(string user, string message)
        {
            await Clients.All.SendAsync("ReceiveMessage", user, message);
        }

        public override Task OnConnectedAsync()
        {
            Clients.All.SendAsync("ReceiveMessage", "Test", "Connected");
            return base.OnConnectedAsync();
        }
    }
`

Startup:
`public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            // In production, the React files will be served from this directory
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp/build";
            });
            services.AddCors(options => options.AddPolicy("CorsPolicy",
           builder =>
           {
               builder.AllowAnyMethod().AllowAnyHeader()
                      .AllowAnyOrigin()
                      .AllowCredentials().Build();
           }));

            services.AddSignalR();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseSpaStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action=Index}/{id?}");
            });

            app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    spa.UseReactDevelopmentServer(npmScript: "start");
                }
            });
            app.UseSignalR(routes =>
            {
                routes.MapHub<ChatHub>("/chatHub");
            });

        }
    }`
React component:
`import React, { Component } from 'react';
import { HubConnectionBuilder, LogLevel } from "@aspnet/signalr/dist/browser/signalr";

export class Ticker extends Component {
    displayName = Ticker.name

    constructor(props) {
        super(props);
        this.state = {
            last: props.last
            , vol: props.vol
            , change: props.change
            , symbol: props.symbol
        };
    }

    render() {
        return (
            <tr>
                <td>{this.state.symbol}</td>
                <td>{this.state.last}</td>
                <td>{this.state.change}</td>
                <td>{this.state.vol}</td>
            </tr>
        );
    }
}

export class TickerBoard extends Component {
    displayName = TickerBoard.name

    constructor(props) {
        super(props);
        this.state = {
            instruments: props.instruments
        };

        //this.addInstrument = this.addInstrument.bind(this);
    }

    componentWillMount() {
        let inst =
            [
                { key: 1, symbol: 'FB', last: 98.28, change: .07, vol: 500000 },
                { key: 2, symbol: 'AAPL', last: 192.35, change: .03, vol: 2200000 },
                { key: 3, symbol: 'NFLX', last: 402.27, change: .03, vol: 1300000 },
                { key: 4, symbol: 'GOOGL', last: 1157.12, change: .03, vol: 100000 },
            ];

        this.setState((prevstate, props) => {
            return { instruments: inst };
        });
    }

    componentDidMount() {
        //This is the server under /example/server published on azure.
        const connection = new HubConnectionBuilder()
            .withUrl("/chatHub")
            .configureLogging(LogLevel.Information)
            .build();
        connection.start().catch(err => console.error(err.toString()));

    }

    render() {
        return (
            <div>
                <h4>Tickers</h4>

                <table>
                    <tbody>
                        {this.state.instruments.map((instruments) => {
                            return <Ticker symbol={instruments.symbol} last={instruments.last} change={instruments.change} vol={instruments.vol} key={instruments.key} />
                        })}
                    </tbody>
                </table>
            </div>
        );
    }
}`

Since this same example works with Razor Pages, I don't know if there is an issue of compatibility with React, or if its just my code :)

Any help is really appreciated!

**Comment by BrennanConroy** [comment]
Your hub is mapped to "chathub" but you try to access "chatHub", I think we are case sensitive here.

**Comment by oevillegas** [comment]
Thanks, I corrected it in the comment above and in my code.  I rebuilt the solution and ran the app, but I still get the same error.

**Comment by BrennanConroy** [comment]
You might need to put `UseSignalR` before `UseSpa`

**Comment by oevillegas** [comment]
And that did it!  Kinda embarrassing that it was such silly mistake.  I better go read more on how .net Core works. :)

Thank you, I appreciate the help!

**Comment by wannadream** [comment]
> You might need to put `UseSignalR` before `UseSpa`

This saves me tons of time. Thanks.
