### ISSUE TITLE
Get JavaScript API docs posted

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2529]
We have JSDoc comments, but the API docs don't actually go anywhere right now :(. There are JavaScript API docs on docs.microsoft.com: https://docs.microsoft.com/en-us/javascript/api/, but I'm not sure exactly how to get them there :). We should follow up with the necessary folks to get the docs posted.

TODO:
* [ ] Review and fix errors in docs
  * [@aspnet/signalr](https://review.docs.microsoft.com/en-us/javascript/api/@aspnet/signalr/?branch=smoke-test)
  * [@aspnet/signalr-protocol-msgpack](https://review.docs.microsoft.com/en-us/javascript/api/@aspnet/signalr-protocol-msgpack/?branch=smoke-test)

**Comment by BrennanConroy** [comment]
Reopening to track merging into release/2.1

**Comment by Eilon** [comment]
## Description

TODO: Describe the bug

## Customer Impact

TODO: Describe how it affects customers. Is there a workaround? How many customers reported?

## Regression from?

TODO: Fill in when it worked, when it stopped working

## Risk

High/Medium/Low/Very Low
TODO: Fill in explanation of risk.

**Comment by Eilon** [comment]
Approved for 2.1.4.

**Comment by BrennanConroy** [comment]
Done in https://github.com/aspnet/SignalR/pull/2605
