### ISSUE TITLE
Consider re-adding the HubConnectionBuilder configuration methods

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2532]
The issues with the documentation on HubConnectionBuilder made me think about the type a little more. It seems like a misuse of the builder pattern. The whole point is being able to construct new objects with explicit methods to set specific properties. It feels like what we have now with `withUrl` is just a half step away from a complex constructor which defeats the  purpose of a builder. Just me ranting though 😄

**Comment by davidfowl** [comment]
8 overloads of a single method isn't the same as 8 ways to construct an object. You have to count *every* overloads of *every* extension methods on the builder.

**Comment by anurse** [comment]
We don't want to make this kind of breaking change to an existing type. We could consider adding a new thing, but that means defining a new thing which is difficult since we've burned the name :)
