### ISSUE TITLE
Are we supposed to implement and supply our own HttpClient in NodeJS env?

### ISSUE THREAD

**Issue by jayarjo** [aspnet/SignalR#2533]
Looking at DefaultHttpClient here, I see that it uses XMLHttpRequest implicitly. Is there a simpler workaround, than implementing own HttpClient?

**Comment by BrennanConroy** [comment]
In 1.0.0 you have to always polyfill XMLHttpRequest (or implement your own HttpClient as you pointed out). And there are two other polyfills you need for certain cases, see our npm package readme https://github.com/aspnet/SignalR/tree/dev/clients/ts/signalr#nodejs

In 1.1.0 we're looking at providing default polyfills so Node users can use the library without any extra work.

**Comment by jayarjo** [comment]
Would be great to have polyfills in place, so I vote for 1.1.0 roadmap. 

Meanwhile I should confess that never pollyfilled anything in NodeJS... is there a way to declare missing objects globally, or will I need to fork the project and add appropriate imports manually?

**Comment by BrennanConroy** [comment]
Here's an example:
https://github.com/aspnet/SignalR-samples/blob/e5daadc2443e54b7e5fab5133bff5f1bdcbd0eb7/StockTickR/NodeClient/app.js#L3-L4

Look at the full app for package.json etc.

**Comment by jayarjo** [comment]
Had to write it down as follows to avoid errors in TypeScript.

```typescript
(global as any).XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
(global as any).WebSocket = require("websocket").w3cwebsocket;
```

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
