### ISSUE TITLE
Add HubOptions

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#254]
HubOptions will contain EndPoint options.

Initial set of thoughts for the options:
- [ ] Verbose error for hub methods
- [ ] Adding/Removing supported protocols?
- [x] Negotiate Timeout?
- [X] JsonSerializerSettings

**Comment by muratg** [comment]
Needed for #261

**Comment by anurse** [comment]
We may want both a global `HubOptions` and a `HubOptions<T>` that lets you override options for a specific Hub.

**Comment by BrennanConroy** [comment]
Moving out of alpha, we did what we wanted to for alpha

**Comment by moozzyk** [comment]
https://stackoverflow.com/questions/46766516/get-detailed-error-for-exception-in-signalr-core-hub-method-execution

**Comment by muratg** [comment]
Closing per today's triage decision.

**Comment by niklr** [comment]
What happened to JsonSerializerSettings? Seems to be removed after 1.0.0-alpha2-final

**Comment by anurse** [comment]
Since the protocols are pluggable, the options were moved to a different location. Now you set them in the `.AddJsonProtocol` extension method in `ConfigureServices`, like this:

```csharp
services.AddSignalR()
    .AddJsonProtocol(options => {
        // Edit or replace 'options.PayloadSerializerSettings' here!
    });
```

**Comment by borissedov** [comment]
I want to enable custom exceptions logging for Hub actions.
But my standard approach from Startup.cs
` app.UseExceptionHandler(handler =>
            {
                handler.Run(context =>
                {
                    var exception = context.Features.Get<IExceptionHandlerFeature>()?.Error;
                    ...
               }
           });
`
doesn't work for Hub errors.
Is there any workaround?
