### ISSUE TITLE
/signalr/connect?  - Not found

### ISSUE THREAD

**Issue by imanshu15** [aspnet/SignalR#2541]
Hello ,

I am using signalr 2.2.3.0. And working on localserver works fine even in some hosting places it works fine.
I bought a new server recently and still on preview mode. Now i get this error as you can see below.

![untitled](https://user-images.githubusercontent.com/15451073/41885227-9f78260e-7914-11e8-8dfc-ec535bb66306.png)

I think the problem is signalR is trying to find the file in 'http://163.182.175.187/signalr/connect?' but it actually exists in 'http://163.182.175.187/plesk-site-preview/teamxsms.xyz.lk/signalr/connect?' . 

So can you please tell me how to inform signalR to go and look under that path to connect? Thank you

**Comment by BrennanConroy** [comment]
You can configure the url on the client using `$.connection.hub.url = "..."`, see https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#the-signalr-url

Also, this repo is for ASP.NET Core SignalR, you are using ASP.NET SignalR which is at https://github.com/SignalR/SignalR.

Closing as fixed.
