### ISSUE TITLE
How to get exception message from Hubs In the Js client?

### ISSUE THREAD

**Issue by Sinfulelf** [aspnet/SignalR#2543]
Hello. my current application looks like that
![test](https://user-images.githubusercontent.com/36459812/41898273-402c931a-7932-11e8-95d4-14c592caae19.png)
 Than I get exception like this
![test2](https://user-images.githubusercontent.com/36459812/41898344-71fe65bc-7932-11e8-8e84-ef356253c991.png)
____
**But is there any way to get exception message in the catch block**?
___
_Im grateful to you and appreciated._

**Comment by BrennanConroy** [comment]
You can set `EnableDetailedErrors = true` on the server, we just wrote a new doc that will be pushed to docs.asp.net soon, for now it's located [here](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md#configure-server-options).

For 1.1 we've added support for throwing `HubException` to bypass the flag and always give the exception message to the client, https://github.com/aspnet/SignalR/issues/2439.

Closing as answered, feel free to re-open if you have any issues.
