### ISSUE TITLE
ConnectionId as GUID?

### ISSUE THREAD

**Issue by aleha84** [aspnet/SignalR#2547]
Migrating from .netframework to .net core. And previously SignalR connection id was a guid string. Now it's not. All code and DB were tightly tied to this data type.
Found this code: https://github.com/aspnet/SignalR/blob/8d680db112a47d0df112af26afae8bef16f76278/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionManager.cs#L98

This means that there are no ways to switch it to something other? Are there any workarounds?

**Comment by anurse** [comment]
The Connection ID is not for usage outside of a single SignalR server, and it's always been designed as an opaque string, you should not depend upon the format of it.

**Comment by aleha84** [comment]
i've used connectionId in clients connections manager. And if i see it represents GUID string (hex digits with dashes) then i used Guid type in backend models code. 

Do you plan in the future to add the ability to specify custom connectionsId generator? 

What purpose of Context.Features and IConnectionIdFeature especially?

**Comment by anurse** [comment]
> And if i see it represents GUID string (hex digits with dashes) then i used Guid type in backend models code.

In general, you should avoid making these kinds of assumptions about values you don't control. The SignalR connection ID is exposed as a `string` which is the only guarantee we give about it's format. The fact that earlier it _happened_ to be a GUID is an implementation detail.

> Do you plan in the future to add the ability to specify custom connectionsId generator?

No, the connection ID is an internal identifier and is not designed to be extensible in this way.

> What purpose of Context.Features and IConnectionIdFeature especially?

Context.Features works the same way as `HttpContext.Features`, it's a way for connection middleware components to add features that other middleware can use. SignalR is built on a Connection Middleware system that is similar to (but different from) how HTTP traffic flows through Request Middleware. `IConnectionIdFeature` is the feature that SignalR puts in to report the connection ID it generated up to the rest of the system.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
