### ISSUE TITLE
OnConnectedAsync Referer is empty

### ISSUE THREAD

**Issue by aleha84** [aspnet/SignalR#2548]
In Hub OnConnectedAsync method Request header "Referer" is empty. 

```
public override async Task OnConnectedAsync()
{
    var referer = Context.GetHttpContext().Request.Headers["Referer"];

    /*...*/

    await base.OnConnectedAsync();
}
```

But what to do if i need to know from which page client is connecting to hub?

**Comment by anurse** [comment]
What transport are you using? I believe WebSockets does not send the Referer header. You could always have your client invoke an "Initialize" method when it starts up and provide the page information there.

**Comment by aleha84** [comment]
Yes, WebSocket. Invoking additional method after start is an extra work.  And it's obvious that I expect to get the initial data when connecting occurs, not after. Current workaround is to add extra query in connection url.

**Comment by BrennanConroy** [comment]
https://fetch.spec.whatwg.org/#concept-websocket-establish
> Let request be a new request, whose url is requestURL, ..., referrer is "no-referrer",

The WebSocket spec for browsers is saying there will be no referer header. There isn't anything SignalR can do here.

**Comment by anurse** [comment]
Maybe, but it's up to the browsers to decide what they send.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
