### ISSUE TITLE
Add AddHub methods

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#255]
Do this in the same PR or at the same time as #254
```c#
AddHub<THub>()
AddHub<THub, TClient>()
AddHub<THub>(HubOptions)
AddHub<THub, TClient>(HubOptions)
```

**Comment by berdon** [comment]
How do you envision this being used? Something like:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSignalR()
      .AddHub<MyHub>(o -> ...)
      .AddHub<MyOtherHub>();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
  app.UseSignalR(routes =>
  {
    routes.MapHub<MyHub>("/hub");
    routes.MapHub<MyOtherHub>("/other");
  });
}

Would `AddHub()` be optional if you didn't need to specify options?

**Comment by BrennanConroy** [comment]
That snippet looks right. It isn't necessary unless you want DI in your Hub I believe.

**Comment by grahamehorner** [comment]
I think that AddHub should be explicit, meaning that if a developer used a shared assembly that contained two SignalR hubs but only wished to publish/expose one as a service then they can do.  I think adding all SignalR hubs as services automatic is a bad idea for resource management etc. or have I misunderstood what AddHub is for an the above comments ?

**Comment by muratg** [comment]
Needed for #261

**Comment by muratg** [comment]
Closing per today's triage decision.
