### ISSUE TITLE
SignalR web sockets not work with asp.net core 2.1 with Bearer token authentication. but SSE work as expected

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [aspnet/SignalR#2555]
### Please consider the following before filing an issue

* If you are using NuGet Packages that start with `Microsoft.AspNet.SignalR`, use the issue tracker at https://github.com/SignalR/SignalR to report the issue. This 
repository is for packages that start with `Microsoft.AspNetCore.SignalR` (and NPM packages that start with `@aspnet/signalr`)

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: Microsoft.AspNetCore.SignalR (1.0.0)
* Versions of Client-Side NuGet/NPM Packages: @aspnet/signalr (1.0.0)
* Are you using the C# client or the JavaScript client: java script client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):  IIS Express/Azure Web App (web socket enabled)
* The Operating System on the Server (Windows/Linux/macOS): windows 10
* The Operating System on the Client (Windows/Linux/macOS): windows 10
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): chrome / firefox
* Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please **do not** put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.

When in doubt, feel free to file the issue, we're happy to help answer questions. We also suggest using the `asp.net-core-signalr` tag on StackOverflow to ask questions.

Everything works fine with SSE but web socket give below error (Javascript error)
Error come from : WebSocketTransport.js 
var webSocket = new WebSocket(url); - conncetion cano not initilize

Error : WebSocketTransport.js?315c:35 WebSocket connection to 'wss://localhost:44382/matcher?id=1GjG9FMUXQKZ-fHBs3sJxA' failed: Error during WebSocket handshake: Unexpected response code: 500

**Comment by LilanMadusankaSilva** [comment]
debug result 
Information: Normalizing '/matcher?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIwNUFFQzg3MzkzQzREMjhBMTAzODZCMjZBMDQzRUE3Nzg0Rjc1REYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJJRnJzaHprOFRTaWhBNGF5YWdRLXAzaFBkZDgifQ.eyJuYmYiOjE1MzAxNjY1NDEsImV4cCI6MTUzMDE3MDE0MSwiaXNzIjoiaHR0cHM6Ly9sb2dpbmRldi5hZHJhZGV2LmNvbSIsImF1ZCI6WyJodHRwczovL2xvZ2luZGV2LmFkcmFkZXYuY29tL3Jlc291cmNlcyIsIm1hdGNoZXJfYXBpIl0sImNsaWVudF9pZCI6Im1hdGNoZXIiLCJzdWIiOiI5N0tIbXBOUFdVT3RiTFpvSVZlTmxBIiwiYXV0aF90aW1lIjoxNTMwMTY2NTM5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJ0aGlsb2tnQDk5eC5sayIsInNlc3Npb25UaW1lT3V0IjoiMjAiLCJlbmdhZ2VtZW50R3VpZF9tYXRjaGVyIjoiM2MzODU2OGYtMTRmMC00NjFkLWJlYjQtYjlmOTk3Njg4NWQzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRoaWxva2dAOTl4LmxrIiwiZW5nYWdlbWVudEd1aWQiOiJqMVk0UFBBVUhVYS10TG41bDJpRjB3IiwianRpIjoiOTIwZDg5NGQ4MWUyNjEyNDQ1YmY1OWM5ZTc0ZjY4Y2UiLCJzY29wZSI6WyJvcGVuaWQiLCJhZHJhX2NsYWltcyIsIm1hdGNoZXJfYXBpLmZ1bGxfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.bGxQ7s8Kj0eiuMXEqNbSccN3wNfCkq3CR6IjQwzrnGzmuj3uTmczg-OqUaVY8BPbyfCCsTGRrsa-_IovVnxO34tcQapnuTlQE73QAmPPqGE90hVBfFpt6tJIk2UJWykVU14GVmxEw5izcQsIHe2Qg0I1Kg1cG9V-dy8QtJNj2x6WYv5rgdZ48zjEAzYXuRnRomoGwLdQB3ZLQ6uOccM019rqCqzVgwMZXAnM6POlHyTFQYnNRlsaxqKuKRqZ4ZNGzU7fZEFCMclAkp54Vq-GUBjGpUNoIGMJGCIdLsXOA86kU65RMtyLxqY1A7_m9BGCPT87Hkp_EdFCn392L11a7g' to 'https://localhost:44382/matcher?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIwNUFFQzg3MzkzQzREMjhBMTAzODZCMjZBMDQzRUE3Nzg0Rjc1REYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJJRnJzaHprOFRTaWhBNGF5YWdRLXAzaFBkZDgifQ.eyJuYmYiOjE1MzAxNjY1NDEsImV4cCI6MTUzMDE3MDE0MSwiaXNzIjoiaHR0cHM6Ly9sb2dpbmRldi5hZHJhZGV2LmNvbSIsImF1ZCI6WyJodHRwczovL2xvZ2luZGV2LmFkcmFkZXYuY29tL3Jlc291cmNlcyIsIm1hdGNoZXJfYXBpIl0sImNsaWVudF9pZCI6Im1hdGNoZXIiLCJzdWIiOiI5N0tIbXBOUFdVT3RiTFpvSVZlTmxBIiwiYXV0aF90aW1lIjoxNTMwMTY2NTM5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJ0aGlsb2tnQDk5eC5sayIsInNlc3Npb25UaW1lT3V0IjoiMjAiLCJlbmdhZ2VtZW50R3VpZF9tYXRjaGVyIjoiM2MzODU2OGYtMTRmMC00NjFkLWJlYjQtYjlmOTk3Njg4NWQzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRoaWxva2dAOTl4LmxrIiwiZW5nYWdlbWVudEd1aWQiOiJqMVk0UFBBVUhVYS10TG41bDJpRjB3IiwianRpIjoiOTIwZDg5NGQ4MWUyNjEyNDQ1YmY1OWM5ZTc0ZjY4Y2UiLCJzY29wZSI6WyJvcGVuaWQiLCJhZHJhX2NsYWltcyIsIm1hdGNoZXJfYXBpLmZ1bGxfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.bGxQ7s8Kj0eiuMXEqNbSccN3wNfCkq3CR6IjQwzrnGzmuj3uTmczg-OqUaVY8BPbyfCCsTGRrsa-_IovVnxO34tcQapnuTlQE73QAmPPqGE90hVBfFpt6tJIk2UJWykVU14GVmxEw5izcQsIHe2Qg0I1Kg1cG9V-dy8QtJNj2x6WYv5rgdZ48zjEAzYXuRnRomoGwLdQB3ZLQ6uOccM019rqCqzVgwMZXAnM6POlHyTFQYnNRlsaxqKuKRqZ4ZNGzU7fZEFCMclAkp54Vq-GUBjGpUNoIGMJGCIdLsXOA86kU65RMtyLxqY1A7_m9BGCPT87Hkp_EdFCn392L11a7g'.
Utils.js?c9f7:158 Debug: Starting HubConnection.
Utils.js?c9f7:158 Debug: Starting connection with transfer format 'Text'.
Utils.js?c9f7:158 Debug: Sending negotiation request: https://localhost:44382/matcher/negotiate?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIwNUFFQzg3MzkzQzREMjhBMTAzODZCMjZBMDQzRUE3Nzg0Rjc1REYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJJRnJzaHprOFRTaWhBNGF5YWdRLXAzaFBkZDgifQ.eyJuYmYiOjE1MzAxNjY1NDEsImV4cCI6MTUzMDE3MDE0MSwiaXNzIjoiaHR0cHM6Ly9sb2dpbmRldi5hZHJhZGV2LmNvbSIsImF1ZCI6WyJodHRwczovL2xvZ2luZGV2LmFkcmFkZXYuY29tL3Jlc291cmNlcyIsIm1hdGNoZXJfYXBpIl0sImNsaWVudF9pZCI6Im1hdGNoZXIiLCJzdWIiOiI5N0tIbXBOUFdVT3RiTFpvSVZlTmxBIiwiYXV0aF90aW1lIjoxNTMwMTY2NTM5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJ0aGlsb2tnQDk5eC5sayIsInNlc3Npb25UaW1lT3V0IjoiMjAiLCJlbmdhZ2VtZW50R3VpZF9tYXRjaGVyIjoiM2MzODU2OGYtMTRmMC00NjFkLWJlYjQtYjlmOTk3Njg4NWQzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRoaWxva2dAOTl4LmxrIiwiZW5nYWdlbWVudEd1aWQiOiJqMVk0UFBBVUhVYS10TG41bDJpRjB3IiwianRpIjoiOTIwZDg5NGQ4MWUyNjEyNDQ1YmY1OWM5ZTc0ZjY4Y2UiLCJzY29wZSI6WyJvcGVuaWQiLCJhZHJhX2NsYWltcyIsIm1hdGNoZXJfYXBpLmZ1bGxfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.bGxQ7s8Kj0eiuMXEqNbSccN3wNfCkq3CR6IjQwzrnGzmuj3uTmczg-OqUaVY8BPbyfCCsTGRrsa-_IovVnxO34tcQapnuTlQE73QAmPPqGE90hVBfFpt6tJIk2UJWykVU14GVmxEw5izcQsIHe2Qg0I1Kg1cG9V-dy8QtJNj2x6WYv5rgdZ48zjEAzYXuRnRomoGwLdQB3ZLQ6uOccM019rqCqzVgwMZXAnM6POlHyTFQYnNRlsaxqKuKRqZ4ZNGzU7fZEFCMclAkp54Vq-GUBjGpUNoIGMJGCIdLsXOA86kU65RMtyLxqY1A7_m9BGCPT87Hkp_EdFCn392L11a7g
Utils.js?c9f7:158 Debug: Selecting transport 'WebSockets'
WebSocketTransport.js?315c:35 WebSocket connection to 'wss://localhost:44382/matcher?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIwNUFFQzg3MzkzQzREMjhBMTAzODZCMjZBMDQzRUE3Nzg0Rjc1REYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJJRnJzaHprOFRTaWhBNGF5YWdRLXAzaFBkZDgifQ.eyJuYmYiOjE1MzAxNjY1NDEsImV4cCI6MTUzMDE3MDE0MSwiaXNzIjoiaHR0cHM6Ly9sb2dpbmRldi5hZHJhZGV2LmNvbSIsImF1ZCI6WyJodHRwczovL2xvZ2luZGV2LmFkcmFkZXYuY29tL3Jlc291cmNlcyIsIm1hdGNoZXJfYXBpIl0sImNsaWVudF9pZCI6Im1hdGNoZXIiLCJzdWIiOiI5N0tIbXBOUFdVT3RiTFpvSVZlTmxBIiwiYXV0aF90aW1lIjoxNTMwMTY2NTM5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJ0aGlsb2tnQDk5...IwZDg5NGQ4MWUyNjEyNDQ1YmY1OWM5ZTc0ZjY4Y2UiLCJzY29wZSI6WyJvcGVuaWQiLCJhZHJhX2NsYWltcyIsIm1hdGNoZXJfYXBpLmZ1bGxfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.bGxQ7s8Kj0eiuMXEqNbSccN3wNfCkq3CR6IjQwzrnGzmuj3uTmczg-OqUaVY8BPbyfCCsTGRrsa-_IovVnxO34tcQapnuTlQE73QAmPPqGE90hVBfFpt6tJIk2UJWykVU14GVmxEw5izcQsIHe2Qg0I1Kg1cG9V-dy8QtJNj2x6WYv5rgdZ48zjEAzYXuRnRomoGwLdQB3ZLQ6uOccM019rqCqzVgwMZXAnM6POlHyTFQYnNRlsaxqKuKRqZ4ZNGzU7fZEFCMclAkp54Vq-GUBjGpUNoIGMJGCIdLsXOA86kU65RMtyLxqY1A7_m9BGCPT87Hkp_EdFCn392L11a7g&id=v1iP_J4ZZKT3cdhT2391mw' failed: Error during WebSocket handshake: Unexpected response code: 500
(anonymous) @ WebSocketTransport.js?315c:35
(anonymous) @ WebSocketTransport.js?315c:33
step @ tslib.es6.js?9ab4:91
(anonymous) @ tslib.es6.js?9ab4:72
fulfilled @ tslib.es6.js?9ab4:62
Utils.js?c9f7:148 Error: Failed to start the transport 'WebSockets': undefined
ConsoleLogger.log @ Utils.js?c9f7:148
(anonymous) @ HttpConnection.js?8e6f:248
step @ tslib.es6.js?9ab4:91
(anonymous) @ tslib.es6.js?9ab4:72
rejected @ tslib.es6.js?9ab4:63
Promise.then (async)
step @ tslib.es6.js?9ab4:64
(anonymous) @ tslib.es6.js?9ab4:65
__awaiter @ tslib.es6.js?9ab4:61
HttpConnection.createTransport @ HttpConnection.js?8e6f:206
(anonymous) @ HttpConnection.js?8e6f:140
step @ tslib.es6.js?9ab4:91
(anonymous) @ tslib.es6.js?9ab4:72
fulfilled @ tslib.es6.js?9ab4:62
Promise.then (async)
step @ tslib.es6.js?9ab4:64
(anonymous) @ tslib.es6.js?9ab4:65
__awaiter @ tslib.es6.js?9ab4:61
HttpConnection.startInternal @ HttpConnection.js?8e6f:74
HttpConnection.start @ HttpConnection.js?8e6f:34
(anonymous) @ HubConnection.js?6cf9:52
step @ tslib.es6.js?9ab4:91
(anonymous) @ tslib.es6.js?9ab4:72
(anonymous) @ tslib.es6.js?9ab4:65
__awaiter @ tslib.es6.js?9ab4:61
HubConnection.start @ HubConnection.js?6cf9:41
(anonymous) @ signalr-service.ts?238c:44
step @ tslib.es6.js?9ab4:91
(anonymous) @ tslib.es6.js?9ab4:72
(anonymous) @ tslib.es6.js?9ab4:65
__awaiter @ tslib.es6.js?9ab4:61
SignalrService.start @ signalr-service.ts?238c:29
(anonymous) @ app.ts?19b4:81
step @ tslib.es6.js?9ab4:91
(anonymous) @ tslib.es6.js?9ab4:72
fulfilled @ tslib.es6.js?9ab4:62
Promise.then (async)
step @ tslib.es6.js?9ab4:64
(anonymous) @ tslib.es6.js?9ab4:65
__awaiter @ tslib.es6.js?9ab4:61
App.onUserChange @ app.ts?19b4:67
Promise.then (async)
handler @ oidc-state.js?1c5d:28
OidcState.subscibeUserChange @ oidc-state.js?1c5d:30
OidcService.subscribeUserChange @ oidc-service.js?6220:41
(anonymous) @ app.ts?19b4:48
step @ tslib.es6.js?9ab4:91
(anonymous) @ tslib.es6.js?9ab4:72
(anonymous) @ tslib.es6.js?9ab4:65
__awaiter @ tslib.es6.js?9ab4:61
App.activate @ app.ts?19b4:47
tryActivateViewModel @ aurelia-templating.js?8628:4478
Promise.then (async)
createController @ aurelia-templating.js?8628:4534
_createControllerAndSwap @ aurelia-templating.js?8628:4509
compose @ aurelia-templating.js?8628:4595
compose @ aurelia-templating.js?8628:4859
setRoot @ aurelia-framework.js?0682:111
(anonymous) @ boot.ts?e80d:24
step @ tslib.es6.js?9ab4:91
(anonymous) @ tslib.es6.js?9ab4:72
fulfilled @ tslib.es6.js?9ab4:62
Promise.then (async)
step @ tslib.es6.js?9ab4:64
(anonymous) @ tslib.es6.js?9ab4:65
__awaiter @ tslib.es6.js?9ab4:61
configure @ boot.ts?e80d:8
(anonymous) @ aurelia-bootstrapper.js?6fd9:124
Promise.then (async)
config @ aurelia-bootstrapper.js?6fd9:119
(anonymous) @ aurelia-bootstrapper.js?6fd9:155
Promise.then (async)
bootstrap @ aurelia-bootstrapper.js?6fd9:154
(anonymous) @ aurelia-bootstrapper.js?6fd9:141
Promise.then (async)
run @ aurelia-bootstrapper.js?6fd9:136
(anonymous) @ aurelia-bootstrapper.js?6fd9:161
(anonymous) @ aurelia-bootstrapper.js:139
./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js @ vendor.js?v=it-PcZvc5UZTcGaI2NTtTX6UhW8-egYBVQ8Goji9MIE:3730
__webpack_require__ @ vendor.js?v=it-PcZvc5UZTcGaI2NTtTX6UhW8-egYBVQ8Goji9MIE:21
(anonymous) @ aurelia-bootstrapper.js from dll-reference vendor_bundle?8d6f:1
./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js @ app.js:1199
__webpack_require__ @ app.js:717
fn @ app.js:99
0 @ app.js:1554
__webpack_require__ @ app.js:717
(anonymous) @ app.js:784
(anonymous) @ app.js:787
Utils.js?c9f7:158 Debug: Selecting transport 'ServerSentEvents'
Utils.js?c9f7:158 Debug: Sending negotiation request: https://localhost:44382/matcher/negotiate?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIwNUFFQzg3MzkzQzREMjhBMTAzODZCMjZBMDQzRUE3Nzg0Rjc1REYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJJRnJzaHprOFRTaWhBNGF5YWdRLXAzaFBkZDgifQ.eyJuYmYiOjE1MzAxNjY1NDEsImV4cCI6MTUzMDE3MDE0MSwiaXNzIjoiaHR0cHM6Ly9sb2dpbmRldi5hZHJhZGV2LmNvbSIsImF1ZCI6WyJodHRwczovL2xvZ2luZGV2LmFkcmFkZXYuY29tL3Jlc291cmNlcyIsIm1hdGNoZXJfYXBpIl0sImNsaWVudF9pZCI6Im1hdGNoZXIiLCJzdWIiOiI5N0tIbXBOUFdVT3RiTFpvSVZlTmxBIiwiYXV0aF90aW1lIjoxNTMwMTY2NTM5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJ0aGlsb2tnQDk5eC5sayIsInNlc3Npb25UaW1lT3V0IjoiMjAiLCJlbmdhZ2VtZW50R3VpZF9tYXRjaGVyIjoiM2MzODU2OGYtMTRmMC00NjFkLWJlYjQtYjlmOTk3Njg4NWQzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRoaWxva2dAOTl4LmxrIiwiZW5nYWdlbWVudEd1aWQiOiJqMVk0UFBBVUhVYS10TG41bDJpRjB3IiwianRpIjoiOTIwZDg5NGQ4MWUyNjEyNDQ1YmY1OWM5ZTc0ZjY4Y2UiLCJzY29wZSI6WyJvcGVuaWQiLCJhZHJhX2NsYWltcyIsIm1hdGNoZXJfYXBpLmZ1bGxfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.bGxQ7s8Kj0eiuMXEqNbSccN3wNfCkq3CR6IjQwzrnGzmuj3uTmczg-OqUaVY8BPbyfCCsTGRrsa-_IovVnxO34tcQapnuTlQE73QAmPPqGE90hVBfFpt6tJIk2UJWykVU14GVmxEw5izcQsIHe2Qg0I1Kg1cG9V-dy8QtJNj2x6WYv5rgdZ48zjEAzYXuRnRomoGwLdQB3ZLQ6uOccM019rqCqzVgwMZXAnM6POlHyTFQYnNRlsaxqKuKRqZ4ZNGzU7fZEFCMclAkp54Vq-GUBjGpUNoIGMJGCIdLsXOA86kU65RMtyLxqY1A7_m9BGCPT87Hkp_EdFCn392L11a7g
Utils.js?c9f7:154 Information: SSE connected to https://localhost:44382/matcher?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIwNUFFQzg3MzkzQzREMjhBMTAzODZCMjZBMDQzRUE3Nzg0Rjc1REYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJJRnJzaHprOFRTaWhBNGF5YWdRLXAzaFBkZDgifQ.eyJuYmYiOjE1MzAxNjY1NDEsImV4cCI6MTUzMDE3MDE0MSwiaXNzIjoiaHR0cHM6Ly9sb2dpbmRldi5hZHJhZGV2LmNvbSIsImF1ZCI6WyJodHRwczovL2xvZ2luZGV2LmFkcmFkZXYuY29tL3Jlc291cmNlcyIsIm1hdGNoZXJfYXBpIl0sImNsaWVudF9pZCI6Im1hdGNoZXIiLCJzdWIiOiI5N0tIbXBOUFdVT3RiTFpvSVZlTmxBIiwiYXV0aF90aW1lIjoxNTMwMTY2NTM5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJ0aGlsb2tnQDk5eC5sayIsInNlc3Npb25UaW1lT3V0IjoiMjAiLCJlbmdhZ2VtZW50R3VpZF9tYXRjaGVyIjoiM2MzODU2OGYtMTRmMC00NjFkLWJlYjQtYjlmOTk3Njg4NWQzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRoaWxva2dAOTl4LmxrIiwiZW5nYWdlbWVudEd1aWQiOiJqMVk0UFBBVUhVYS10TG41bDJpRjB3IiwianRpIjoiOTIwZDg5NGQ4MWUyNjEyNDQ1YmY1OWM5ZTc0ZjY4Y2UiLCJzY29wZSI6WyJvcGVuaWQiLCJhZHJhX2NsYWltcyIsIm1hdGNoZXJfYXBpLmZ1bGxfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.bGxQ7s8Kj0eiuMXEqNbSccN3wNfCkq3CR6IjQwzrnGzmuj3uTmczg-OqUaVY8BPbyfCCsTGRrsa-_IovVnxO34tcQapnuTlQE73QAmPPqGE90hVBfFpt6tJIk2UJWykVU14GVmxEw5izcQsIHe2Qg0I1Kg1cG9V-dy8QtJNj2x6WYv5rgdZ48zjEAzYXuRnRomoGwLdQB3ZLQ6uOccM019rqCqzVgwMZXAnM6POlHyTFQYnNRlsaxqKuKRqZ4ZNGzU7fZEFCMclAkp54Vq-GUBjGpUNoIGMJGCIdLsXOA86kU65RMtyLxqY1A7_m9BGCPT87Hkp_EdFCn392L11a7g&id=sXwQTN1wiboBAn_Tfx77wQ
Utils.js?c9f7:158 Debug: Sending handshake request.

**Comment by anurse** [comment]
> Error during WebSocket handshake: Unexpected response code: 500

This indicates that your server threw an exception while processing the WebSocket request (possibly in SignalR but also possibly in some other middleware). Is there anything in the console output from the server? Can you collect server-side logs as specified in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)?

Also, you closed this issue, have you solved the problem already or was that unintentional?

**Comment by lurumad** [comment]
Hi @anurse 

I have the same problem

[chrome.log](https://github.com/aspnet/SignalR/files/2180635/chrome.log)
[signalrserver.txt](https://github.com/aspnet/SignalR/files/2180636/signalrserver.txt)

I've attached log files. I have the same error in Azure SignalR repo samples

https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/AdvancedChatRoom

Regards!

**Comment by LilanMadusankaSilva** [comment]
In my case I was not enabled web sockets in web app. but after enabled web sockets it work as expected

**Comment by lurumad** [comment]
In my case using this piece of code:

```charp
options.Events = new JwtBearerEvents
{
    OnMessageReceived = context =>
    {
        var accessToken = context.Request.Query["access_token"];

        if (!string.IsNullOrEmpty(accessToken) &&
            (context.HttpContext.WebSockets.IsWebSocketRequest || context.Request.Headers["Accept"] == "text/event-stream"))
        {
            context.Token = context.Request.Query["access_token"];
        }
        return Task.CompletedTask;
    }
};
```

I think this should be manage by SignalR by default.

Regards

**Comment by davidfowl** [comment]
Here's the doc on auth https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1.

> I think this should be manage by SignalR by default.

Manage what exactly?
