### ISSUE TITLE
websocket closed with code 1001 with reason stream end encountered

### ISSUE THREAD

**Issue by chauhan-saurabh** [aspnet/SignalR#2556]
I am getting websocket closed with code 1001 with reason stream end encountered when using connection.stop()

**Comment by anurse** [comment]
Close code `1001` occurs because the browser is navigating away from the page and has to forcibly terminate the connection. Are you calling `.stop()` in response to some event? Can you provide a snippet of the code that calls `.stop()` (including what user action would _trigger_ the call)?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
