### ISSUE TITLE
Unable to build Xamarin Forms project with SignalR packages

### ISSUE THREAD

**Issue by reznor244** [aspnet/SignalR#2559]
I'm attempting to add AspNetCore.SignalR.Client/.Core to an existing Xamarin Forms app. I was unable to get it to build at all, even after installing all the dependencies mentioned in this [announcement](https://github.com/aspnet/Announcements/issues/305). I then tried creating a new solution to see if is because other packages in my app are dated, but the test solution doesn't build either.

```
Can not resolve reference: System.Threading.Tasks.Extensions, referenced by Microsoft.AspNetCore.Http.Connections.Client. Please add a NuGet package or assembly reference for System.Threading.Tasks.Extensions, or remove the reference to Microsoft.AspNetCore.Http.Connections.Client.
```
```
Can not resolve reference: System.Threading.Tasks.Extensions, referenced by System.IO.Pipelines. Please add a NuGet package or assembly reference for System.Threading.Tasks.Extensions, or remove the reference to System.IO.Pipelines.
```
```
Can not resolve reference: System.Threading.Tasks.Extensions, referenced by Microsoft.AspNetCore.SignalR.Client.Core. Please add a NuGet package or assembly reference for System.Threading.Tasks.Extensions, or remove the reference to Microsoft.AspNetCore.SignalR.Client.Core.
```
```
Can not resolve reference: System.Threading.Tasks.Extensions, referenced by System.Threading.Channels. Please add a NuGet package or assembly reference for System.Threading.Tasks.Extensions, or remove the reference to System.Threading.Channels.
```

Test solution:
https://github.com/reznor244/TestSignalRClient/tree/master

Steps:
1. Create Xamarin Forms app from built-in template.
2. Add Microsoft.AspNetCore.SignalR.Client and Client.Core nuget packages.
3. Add additional nuget packages from [announcement](https://github.com/aspnet/Announcements/issues/305)
4. Build Android project --- fails.

**Comment by anurse** [comment]
\*sigh\* ok, I've tracked this one down. I was able to repro the issue on my build of Xamarin but it no longer repros when I remove the System.Threading.Tasks.Extensions dependency. It looks like that package was marked as "built-in" in 4.5.1 but it's not actually built-in to Xamarin yet.

I believe you mentioned originally that you were also having issues before you added the dependencies. One other thing I did was to update all the Xamarin.* packages to the latest version (the project you posted had slightly out-of-date versions).

I just edited the announcement to remove the (erroneous) recommendation to add the new version.

So try removing those dependencies and updating the Xamarin packages and see how that does. If you're still seeing issues then, we can keep digging :)

**Comment by reznor244** [comment]
My test project builds fine now after removing those packages.

My original project does not, but it is on a much older version of Xamarin.Forms (2.3.4.270). I originally thought that shouldn't matter, but I can try updating if needed.

Error:
```
Can not resolve reference: `Microsoft.AspNetCore.SignalR.Client.Core`, referenced by `Dash.Chat.Client`. Please add a NuGet package or assembly reference for `Microsoft.AspNetCore.SignalR.Client.Core`, or remove the reference to `Dash.Chat.Client`.
```

Microsoft Visual Studio Enterprise 2017 Preview
Version 15.8.0 Preview 3.0
VisualStudio.15.Preview/15.8.0-pre.3.0+27825.0
Microsoft .NET Framework
Version 4.7.03056
Installed Version: Enterprise
Xamarin   4.11.0.669 (d15-8@3994c2e05)
Xamarin Designer   4.14.137 (1ad4c2903)
Xamarin Templates   1.1.67 (2c6e667)
Xamarin.Android SDK   8.4.0.1 (HEAD/a6ec739ce)
Xamarin.iOS and Xamarin.Mac SDK   11.14.0.4 (29d671b)

**Comment by reznor244** [comment]
I went with the "update all packages" strategy and that didn't work. Updated every Xamarin.* package I could.

After that, I realized that maybe my test project wasn't quite representative of my actual project. In my actual project, all the SignalR client code is in its own project with no reference to Xamarin. So I put the SignalR client code in the Xamarin project and added the SignalR.Client package directly. This worked. I would think I shouldn't need to do this? Or does it need some kind of reference to Xamarin?

**Comment by reznor244** [comment]
I’ll see if I can duplicate the issue in another test solution and post
that on Monday.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by reznor244** [comment]
My apologies for not responding. I tried it again at some time and it succeeded using updated packages v1.0.2. Not sure if that fixed it or something else.

**Comment by anurse** [comment]
No problem! Just wanted to update this for our tracking. Glad to hear the updated packages fixed the issue, we have done fixes to Xamarin scenarios in the last couple of patches.
