### ISSUE TITLE
Authorization for EndPoints and Hubs

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#256]
- [ ] Authorize Attribute on EndPoint
- [ ] Authorize Attribute on Hub class and methods
- [x] Use Policy name in EndPointOptions

**Comment by berdon** [comment]
@BrennanConroy Would you have a few minutes today to discuss the thoughts around this?

I'd like to help out but I want to make sure any changes I make are in line with what you guys are planning. I've done some initial work but with #254 and #255 that might change how or where Hub policies might be stored after checking TypeInfo custom attributes.

**Comment by BrennanConroy** [comment]
Closing in favor of https://github.com/aspnet/SignalR/issues/552
