### ISSUE TITLE
[2.1.3] Port TryAddSingleton for services #2432

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2561]
#2432

In 2.1.X we override user services with ours if they set them before `services.AddSignalR();`.
Can be pretty frustrating and difficult to figure out. Simple fix, low risk
@anurse

**Comment by mikaelm12** [comment]
Link to my commit: e41764c161574983c49362cfb29ce23eb5941b74
It's a fairly small code change

**Comment by muratg** [comment]
Approved for 2.1.3.

**Comment by BrennanConroy** [comment]
Done
