### ISSUE TITLE
Missing method definition in HubConnectionBuilder.d.ts

### ISSUE THREAD

**Issue by zdrsh** [aspnet/SignalR#2580]
I have the latest npm version @aspnet/signalR (1.0.0)

It seems like the method definition for 

`public configureLogging(logging: LogLevel | ILogger): HubConnectionBuilder`

is missing now in the typing dist/esm/HubConnectionBuilder.d.ts

**Comment by anurse** [comment]
Looks like the definition has two separate overloads instead:

```
public configureLogging(logging: LogLevel): HubConnectionBuilder
public configureLogging(logging: ILogger): HubConnectionBuilder
```

But that would mean that if you have a `LogLevel | ILogger` then you won't be able to just pass it straight in. Unfortunately that may have been broken by some TypeScript API clean-up and documentation we did in RTM. You can work around it using something like this:

```typescript
public function myFunc(logging: LogLevel | ILogger, builder: HubConnectionBuilder) {
    if(typeof logging === "number") {
        builder.configureLogging(logging);
    } else {
        builder.configureLogging(logging);
    }
}
```

It's a little funky, but it should work around the problem. We can probably get this fixed.

**Comment by zdrsh** [comment]
Thanks @anurse.

**Comment by BrennanConroy** [comment]
We're going to keep this open for tracking fixing the issue.
