### ISSUE TITLE
Java Client De-Serializing Custom Types

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2582]
Currently the Java client doesn't support de-serializing custom types. Gson stores the types as a `LinkedTreeMap` which we can't directly cast to arbitrary types. Need to do some investigation into how to do this in a clean way.

**Comment by anurse** [comment]
I'd expect we can use the same pattern we use in .NET here and have an "invocation binder" interface that flows into the Hub Protocol and allows the protocol to get the `Class` objects representing the destination types.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/55597adf616757aaec0bc7a611754430b9ef4fd8
