### ISSUE TITLE
Move De-serialization logic into HubProtocol layer

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2587]
Currently in the Java client the deserialization from JSON happens in the HubConnection layer via
https://github.com/aspnet/SignalR/blob/896c6692b4fdaee16e2fbbb26b86821091c32f71/clients/java/signalr/src/main/java/HubConnection.java#L32

This should be handled via the HubProtocol so that it can be done with different protocols.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/55597adf616757aaec0bc7a611754430b9ef4fd8
