### ISSUE TITLE
refactor DefaultHubDispatcher control flow

### ISSUE THREAD

**Issue by DylanDmitri** [aspnet/SignalR#2591]
Old flow effectively has 2*3=6 cases, one for each combination of (has streaming parameters / no streaming parameters) and (send async / invoke async / invoke streaming async). 

New flow will contain two splits, one split on (streaming params / no streaming params), and then the flows will rejoin, and then split again on invocation kind.

**Comment by anurse** [comment]
Sounds good! I'm not so sure it's XS though (cost needs to include time it takes to test the change, and managing the PR/code review), and I'd rather be conservative with our cost estimate :)

**Comment by DylanDmitri** [comment]
done and pushed
