### ISSUE TITLE
Life cycle after disconnecting client from internet

### ISSUE THREAD

**Issue by PedroHFranco** [aspnet/SignalR#2601]
Hello guys,

I'm gotting a strange situation in my application when my C# client got disconnected from internet:

My application is staying stuck in some method of SignalR i was trying to found what method was causing this and after alot of attempts i arrived at this situation with this HubConnectionBuilder.

I have create and Appender for log message and every log i'm sending an message to my Azure App Server.

```csharp
public async Task SendMessagedLogger(string log)
{
	try
	{
		await _hubConnection.SendAsync("MessagedLogger", log);

	}
	catch (Exception ex)
	{
		//Log.Error($"Erro ao enviar Mensagem de Log: {ex.GetFullException()}");
	}
}
```

What I've done to try to solve the problem, i changed every InvokeAsync to SendAsync, and set the KeepAliveInterval, after this i'm gotting error.

This is my Server code side:

Connected method:
```csharp
public override Task OnConnectedAsync()
{
	var httpContext = Context.GetHttpContext();
	var token = httpContext.Request.Query["Token"];
	switch (token)
	{
		case "log4net":
			AddToGroup("log4net").Wait();
			break;
		case "autoupdate":
			token = httpContext.Request.Query["Conta"];
			UpdateConnectionIdAutoUpdate(token, Context.ConnectionId);
			AddToGroup("autoupdate").Wait();
			break;
		default:
			UpdateConnectionIdConta(token, Context.ConnectionId);
			break;
	}

	return base.OnConnectedAsync();
}
```
 
Disconnected method:
```csharp
public override Task OnDisconnectedAsync(Exception exception)
{
	Clients.Groups("log4net").SendAsync("RecieveMessage", Context.ConnectionId, $"A conexão com o serviço foi perdida.\r\nDetalhes: {exception?.GetBaseException()?.Message}").Wait();
	RemoveFromGroup("log4net").Wait();
	return base.OnDisconnectedAsync(exception);
}
```

Startup:
```csharp
app.UseSignalR(routes =>
{
	routes.MapHub<MonitoringHub>("/monitoring", o => { o.TransportMaxBufferSize = 0; });
});
```

And this is my Client side:

I have created a singleton class for don't start new connection every time i need to send something.

This is my Connection method:

```csharp
public static MonitoringConnection Connection
{
	get
	{
		try
		{
			if (_connection != null)
				return _connection;

			_connection = new MonitoringConnection();
			if (_hubConnection == null)
			{
				BuildAndConnectOnHub();
				_hubConnection.Closed += HubConnectionOnClosed;
			}

			CommandUpdateComponents();
			return _connection;
		}
		catch (Exception ex)
		{
			Log.Error($"Erro ao montar connection hub: {ex.GetFullException()}");
			return null;
		}
	}

	set { _connection = value; }
}
```

```csharp
private static void BuildAndConnectOnHub()
{
	try
	{
		if (_MonitoringConnectionState != MonitoringConnectionState.Connected)
		{
			_hubConnection = new HubConnectionBuilder()
				.WithUrl($"http://localhost:5010/monitoring?token={Settings.Data.Token}", options =>
				{
					options.Transports = HttpTransportType.WebSockets;
					options.WebSocketConfiguration = (webSocketOptions) =>
						{
							webSocketOptions.KeepAliveInterval = TimeSpan.FromSeconds(3);
						};
				})
				.ConfigureLogging(logging => {
					logging.AddConsole();

					// Feel free to use other logging providers, such as Serilog or Seq!

					// Choose one of the below:

					// This will set ALL logging to Debug level
					logging.SetMinimumLevel(LogLevel.Debug);

					// Alternatively, you can set the default verbosity to something less noisy and
					// only turn up the SignalR loggers
					logging.SetMinimumLevel(LogLevel.Information);
					logging.AddFilter("Microsoft.AspNetCore.SignalR", LogLevel.Debug);
					logging.AddFilter("Microsoft.AspNetCore.Http.Connections", LogLevel.Debug);
				})
				.Build();

			_hubConnection.StartAsync().Wait();
			_MonitoringConnectionState = MonitoringConnectionState.Connected;
		}
	}
	catch (Exception e)
	{
		var type = e.GetFullTypeException();
		if ((type == typeof(SocketException) || type == typeof(WebException)) && _MonitoringConnectionState == MonitoringConnectionState.Faulted)
		{
			Thread.Sleep(30000);//30 segundos
			BuildAndConnectOnHub();
		}
		Log.Error($"Erro: {e.GetFullException()}");
	}
}
```

My method on Closed just call this Start connection above and i set the flag saying the connection has been losted.

```csharp
private static async Task HubConnectionOnClosed(Exception exception)
{
	try
	{
		_MonitoringConnectionState = MonitoringConnectionState.Faulted;
		BuildAndConnectOnHub();
	}
	catch (Exception e)
	{
		Log.Error($"Erro: {e.GetFullException()}");
	}
}
```

I'm checking in Try catch at _hubConnection according the exception i retry to connect on server again, but when i'm try to reconect its staying stuck and i'm gotting the follow error message in both side:

> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ConnectionResetException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
>    --- End of inner exception stack trace ---
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.ReadableBufferAwaitable.GetResult()
>    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvOutputConsumer.<WriteOutputAsync>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61`2.MoveNext()
>    at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61`2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport.<StartReceiving>d__8.MoveNext()
> dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[14]
>       Socket connection closed prematurely.

I don't know if i have to close Client connection on server, i have look how to do this and got no luck in search.

Any idea?
Thanks!!

**Comment by danpadua** [comment]
Same problem

**Comment by BrennanConroy** [comment]
Could you make a small app to reproduce the issue?
Also, could you gather client and server logs, see https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#server-side-logging and https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#javascript-client-logging

**Comment by PedroHFranco** [comment]
Yes i can, i will provide the application.....
This execption i have sent is already from Diagnostics..... both side log it.

**Comment by PedroHFranco** [comment]
I have created an application trying to simulate the problem, but I could not, i will let the link from application [here](https://github.com/PedroHFranco/SignalRMonitoringExample) , if some one want to see.

It's an Windows Service, schedulling Job's with no dependecies in Service.
Also a Appender to log4net to see any log in service, this log are sending to SignalR, i also provide the Server.
So this is an Motoring application to Windows Service.

I will let close this Issue. While i don't found the problem.. 

Thank's @BrennanConroy

**Comment by QtRoS** [comment]
@PedroHFranco how is it going with your problem? Did you manage to solve it? 
Seems that I've faced similar problem, SignalR's method `SendAsync` lasts forever when I'm trying to invoke method for all clients (some of them disconnected before that).
