### ISSUE TITLE
SignalR does not seem to use provided id from custom IUserIdProvider

### ISSUE THREAD

**Issue by Hypnobrew** [aspnet/SignalR#2602]
* Microsoft.Azure.SignalR 1.0.0-preview1-10015
* @aspnet/signalr 1.0.0
* Javascript client from Latest Chrome
* Kestrel
* Ubuntu 18.04 (Tried on Windows 10 as well)

Experienced issue:
I use SignalR core with the SingalR Service in Azure, and I would like to tweak how users are mapped since the default `NameIdentifier` claim in my `JWT` token is not specific enough in my case.

I have created a custom class that implements `IUserIdProvider` and added this as a dependency in my Startup as:   
```
services.AddSignalR().AddAzureSignalR("********");
services.AddSingleton<IUserIdProvider, MyCustomProvider>();
````
I can see that my custom provider is called but it looks like the default `NameIdentifier` is used anyway.
It does not matter what I return from my `GetUserId` method.
Are there any known issues regarding this or do you have any idea what is the problem here?

Thanks!

**Comment by BrennanConroy** [comment]
I am not aware of any issues here.
Could you provide more info, like how are you accessing the user id that doesn't have the expected value? Can you repro the issue without using Azure SignalR Service?

**Comment by davidfowl** [comment]
This is likely an issue with the service specifically.

**Comment by Hypnobrew** [comment]
Made some tests with a new clean project created using the tooling (`dotnet new mvc`) without the Azure SignalR Service, and it works as expected. When adding Signal R Service, I experience the same behavior as earlier where the custom user id provider is not used.

**Comment by BrennanConroy** [comment]
Yeah, that's probably a good idea. https://github.com/Azure/azure-signalr

**Comment by Hypnobrew** [comment]
Great, thanks!

**Comment by BrennanConroy** [comment]
Closing since you've filed the other issue.
