### ISSUE TITLE
How to access Context.Items out of Hub

### ISSUE THREAD

**Issue by Hawthorn2013** [aspnet/SignalR#2606]
Hi,
I know I can save some key-value pairs in **Context.Items**, and they exist when the connection is opened.
But I want to access some key-value pairs out of Hub, for example in a controller.
How can I get Context.Items **out of** Hub class?

Thank you.

**Comment by BrennanConroy** [comment]
You can't. It doesn't make sense.

`Context` in the hub is specific to that connection. When you're in a controller you aren't a SignalR connection so it wouldn't make sense to access the `Items` property since there is no connection associated with the controller method call.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
