### ISSUE TITLE
SignalR Core with Redis Backplane issues 

### ISSUE THREAD

**Issue by JakeSimmons89** [aspnet/SignalR#2607]
Hub is connecting to a local redis server but when I said messages from one hub Instance it does not make it to the 2nd hub instance. 
        

My understanding is that the hubs should be communicating through a redis subpub channel but I do not see either instance of my Hub subscribing to a channel. 

Any help would be great!

```
	public void ConfigureServices(IServiceCollection services)
        {
            services.AddSignalR().AddRedis("localhost");

        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseFileServer();

            app.UseSignalR(routes =>
            {
                routes.MapHub<ApplicationHub>("/app");
            });
        }
```

**Comment by BrennanConroy** [comment]
When you say hub instance do you mean server instance? Redis scaleout is for multiple servers running the same app to communicate between each other.

**Comment by JakeSimmons89** [comment]
Yes I mean Server instance.

I want to have a signalR app on multiple servers all of which are subscribed to a Redis channel and sending messages to clients based on what is received from the redis channel.

**Comment by BrennanConroy** [comment]
Are all your servers connected to the same redis instance?

Subscriptions are handled by SignalR and should work exactly as you described.

Could you show what you're doing and expecting?

**Comment by JakeSimmons89** [comment]
Yes they are all connected to the same Redis instance 

`services.AddSignalR().AddRedis("localhost");`

I expect that if I have 2 SignalR applications connected to the same redis and I call a method on one of them that redis should instruct the other one to call the same method.

Result being all clients connected to either server A or B receive the same data

**Comment by JakeSimmons89** [comment]
I am trying to Broadcast data from my SignalR App. I possibly need up to 5 instances of said SignalR App to handle to amounts of data/connection.What would be the best way to accomplish what I want?

Theoretically I would want all 5 SignalR instances subscribed to a Redis channel so I can publish the data to the channel once and have it received and sent out to their respective connections.

I do not need communication between clients , just broadcasting real time data.

**Comment by BrennanConroy** [comment]
> I could just send the data from a client of one of the servers and it will make it too all clients ?

Yes, that is how it works.

One client calls a hub method on one of the servers, that hub method invokes `Clients.All.SendAsync(..., ...)` and all clients across all severs will get that message.

**Comment by JakeSimmons89** [comment]
Thank you for making me see the light that is SignalR.

Below is the General workflow I see working for data Broadcasting:

3rd Party service data (Web socket server)----->My Web socket Client------> My Redis cache (throttle/massage data) ------> SignalR Client (Controlled Periodic data pushes)-------->SignalR Hub---------> All clients connected to Hub 

*Also can use a Redis backplane to scale out more SignalR servers if need be.

Your thoughts would be greatly appreciated.

**Comment by BrennanConroy** [comment]
> 3rd Party service data (Web socket server)----->My Web socket Client------> My Redis cache (throttle/massage data) 

The above part is all done on a single client? And then that client will send a hub invocation every 2 seconds and you want all connected clients across multiple servers to get that message?

If you hook redis up to your servers like you showed in your code samples above then this should be working. If not, would it be possible to make a small repro application so I could take a look?

**Comment by JakeSimmons89** [comment]
Machine 1
My Web socket Client------> My Redis cache (throttle/massage data)

Machine 2
SignalR Client (Controlled Periodic data pushes)

Machine 3 
SignalR Hub

I will work on putting together a small repo

**Comment by JakeSimmons89** [comment]
The redis backplane using subpub correct?

if so what would the channel name be so I can open up a redis cli and see if any messages are being sent.

**Comment by BrennanConroy** [comment]
`monitor` will show you messages

**Comment by JakeSimmons89** [comment]
@BrennanConroy I found my issue.

The issue appears to be a Redis connection issue.

@aauronn in what instance would you not want sticky session ? asking as I thought you always need an active connection to a single SignalR hub.

**Comment by BrennanConroy** [comment]
@JakeSimmons89 Glad you found the issue. Good to close now?

**Comment by JakeSimmons89** [comment]
@BrennanConroy Yes , thank you for all your help
