### ISSUE TITLE
Cannot Read Property 'HubConnectionBuilder' of Undefined.

### ISSUE THREAD

**Issue by MarkSky** [aspnet/SignalR#2608]
I used SignalR in my javascript file:

```
import signalR from '@aspnet/signalr';

const GameHubConnection = new signalR.HubConnectionBuilder()
    .withUrl('url')
    .build();
```

And when I ran it on Chrome, I got an error in Chrome developer tools:

> Hub.js:9 Uncaught TypeError: Cannot read property 'HubConnectionBuilder' of undefined

Webpack version: 4.15.1
@aspnet/signalr version: 1.0.0

How could I solve it?

**Comment by BrennanConroy** [comment]
We have a detailed doc on how to use SignalR and Webpack, could you check it out and see if it resolves your issue?
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.1&tabs=visual-studio

**Comment by MarkSky** [comment]
OK, I find it.
Thanks.

**Comment by BrennanConroy** [comment]
> But if it only used to ASP.NET Project?

Not sure what you mean here

**Comment by MarkSky** [comment]
@BrennanConroy I read your doc, and found Use the File > New > Project menu option and choose the ASP.NET Core Web Application template
So I want to know if it only used to ASP.NET Core Web Application?

**Comment by BrennanConroy** [comment]
Yes, this version of SignalR only works with ASP.NET Core

**Comment by MarkSky** [comment]
So, how could I use it on client web site? Only HTML and Javascript.

**Comment by BrennanConroy** [comment]
Could you put a repro app in a git repository so I can take a look?

**Comment by MarkSky** [comment]
OK.
This is my project:
[PhaserAndSignalR](https://github.com/MarkSky/PhaserAndSignalR)

**Comment by BrennanConroy** [comment]
Change your import statement to:
`import * as signalR from '@aspnet/signalr';`

Also, `createHubProxy` doesn't exist in ASP.NET Core SignalR so you'll need to remove that.

**Comment by MarkSky** [comment]
Thank you, this error is solved.
I would like to know if ASP.NET Core SignalR doesn't support proxy?

**Comment by BrennanConroy** [comment]
There is no hub proxy, each connection is to a single hub via the url endpoint.
