### ISSUE TITLE
Better Exception Handling in Java Client

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2610]
Currently the exception handling is minimal and general method signatures just declare that general exceptions could be thrown. Work needs to be done to make this more specific and catch these and fail at the right levels of the client. 

Context
https://github.com/aspnet/SignalR/pull/2583#discussion_r200011358
https://github.com/aspnet/SignalR/pull/2583#discussion_r200013217

**Comment by moozzyk** [comment]
Effective Java 70-72

**Comment by anurse** [comment]
Consider wrapping some exceptions so the throws clauses aren't so broad. For example in HubProtocol

```java
HubMessage[] parseMessages(String message, InvocationBinder binder) throws HubProtocolException;
```

or even just

```java
HubMessage[] parseMessages(String message, InvocationBinder binder) throws SignalRException;
```

**Comment by anurse** [comment]
It looks like we should just use `HubException` only for representing errors that come from `invoke` and use `RuntimeException` (and friends) for everything else.

**Comment by anurse** [comment]
Handshake response error -> `RuntimeException`
