### ISSUE TITLE
How to authenticate token from AAD in an aspnet core web api passed through signalR?

### ISSUE THREAD

**Issue by exztinct01** [aspnet/SignalR#2616]
First of all, I'm a bit new to web dev as a whole but I would like to ask this question since we''re using AAD authentication. I created an aspnet core React application and used the authentication scheme generated by aspnet core webapi on the backend and adal js on the frontend. So I added the code below in Startup.cs and `[Authorize]` in my controllers as well as my hubs.

     services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
                .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

From the client side, I attached the token to the headers of my ajax requests and they all work correctly. Below is the function I use to perform the fetch. The `adalApiFetch` function already adds the authorization inside it
        
         .......
         let response = yield adalApiFetch(axios, "api/securities", {
            method: "GET",
            headers: {
                "Content-Type": "application/json; charset=UTF-8",
                Accept: "application/json"
            }
        }).catch(function(error) {
          throw error;
        });
        .........

For the hubs, I'm using the code below

       const conn = new SignalR.HubConnectionBuilder().withUrl("/myhub", {
          accessTokenFactory: async () => {
              return await getApiToken();
          }
      }).build();

Like I said above, axios fetch and authentication works, but signalR does not. 
Chrome has the following logs

        WebSocketTransport.js:35 WebSocket connection to 'wss://localhost:5001/myhub id=................................&access_token=ey..........................
        failed: HTTP Authentication failed; no valid credentials available
        Error: Failed to start the transport 'WebSockets': undefined

And this is from Edge

        Error: Failed to start the transport 'WebSockets': undefined
        SCRIPT12008: SCRIPT12008: WebSocket Error: Incorrect HTTP response. Status code 401, Unauthorized

Can anyone please guide me on what I am missing?

**Comment by exztinct01** [comment]
I posted this issue yesterday in the aspnet/docs repo but I was pointed to here

Meanwhile, upon looking more at the application and the logs produced, as well as testing the connection itself, I found out it actually worked. However, the errors are still produced.

I decided to create a new application using the aspnet core react template. I added the AzureAD Bearer authentication (the one I showed in the post above), and put the `[Authorize]` tag in the ChatHub class. I also added `adal js` authentication on the react application using the `react-adal` library.

In connection builder, I did this

    const connection = new SignalR.HubConnectionBuilder()
      .withUrl("/chathub", {
        accessTokenFactory: async () => {
          let token = await adalGetToken(authContext, adalConfig.endpoints.api);
          return token;
        }
      })
      .build();
    // added handlers then connection.start().catch(err => console.error(err.toString()));

the connection succeeded but the errors in Chrome still occurred and the server logs below are produced

      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 POST https://localhost:5001/chathub/negotiate text/plain;charset=UTF-8 0
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 273.7414ms 200 application/json
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id={firstID}&access_token={MyToken}
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
            Authorization failed.
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
            AuthenticationScheme: AzureADJwtBearer was challenged.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 19.1657ms 401
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 POST https://localhost:5001/chathub/negotiate text/plain;charset=UTF-8 0
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 6.6534ms 200 application/json
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id={secondID}&access_token={SameTokenAsAbove}
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
            Authorization failed.
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
            AuthenticationScheme: AzureADJwtBearer was challenged.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 18.2278ms 401
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 POST https://localhost:5001/chathub/negotiate text/plain;charset=UTF-8 0
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 6.651ms 200 application/json
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id=rgUlpDdMJw8X2Hcku6VL2A&_=1531225867582
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 17.6661ms 200 application/octet-stream
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id=rgUlpDdMJw8X2Hcku6VL2A&_=1531225867604
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 POST https://localhost:5001/chathub?id=rgUlpDdMJw8X2Hcku6VL2A text/plain;charset=UTF-8 32
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 17.5539ms 200 text/plain
      info: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
            Completed connection handshake. Using HubProtocol 'json'.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 49.7215ms 200 application/octet-stream
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id=rgUlpDdMJw8X2Hcku6VL2A&_=1531225867666
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.

**Comment by exztinct01** [comment]
I can't see why the first attempt above fails

**Comment by BrennanConroy** [comment]
By default the client will try all 3 transports before failing to connect. In this case WebSockets failed, then SSE failed, but LongPolling succeeded so you got a successful connection.

I'm not familiar with how AzureADJwtBearer works, but I can tell you the main difference between the 2 failing connections and the successful one in this case is that LongPolling sends the token via the `Authorization` header and the other 2 send it via `access_token` query string.

@Tratcher for more info on Auth. Mostly, how to get `access_token` to work?

**Comment by Tratcher** [comment]
You need to customize AddAzureADBearer to read the bearer token from the query string. @BrennanConroy SignalR should already have an example for doing this with JwtBearer.

**Comment by BrennanConroy** [comment]
Oh duh... I blame my nose.

Take a look at our Jwt Sample, specifically the access_token section here: https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/samples/JwtSample/Startup.cs#L51-L61

**Comment by exztinct01** [comment]
hmmm `options.Events` does not exist for `AddAzureADBearer`.

**Comment by exztinct01** [comment]
I used `JwtBearer` instead of `AzureADBearer` to be able to customize the `AddBearer`. Below is the code for `ConfigureServices`

            services.AddAuthorization(options =>
            {
                options.AddPolicy(JwtBearerDefaults.AuthenticationScheme, policy =>
                {
                    policy.AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme);
                    policy.RequireClaim(ClaimTypes.NameIdentifier);
                });
            });

            var clientId = Configuration["AzureAd:ClientId"];
            var tenantId = Configuration["AzureAd:TenantId"];
            var issuer = $"https://sts.windows.net/{tenantId}/";

            services.AddAuthentication(options => 
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
                .AddJwtBearer(options =>
                {
                    options.RequireHttpsMetadata = false;
                    options.SaveToken = true;
                    options.Authority = "https://login.microsoftonline.com/common/";

                    options.TokenValidationParameters =
                    new TokenValidationParameters
                    {
                        LifetimeValidator = (before, expires, token, parameters) => expires > DateTime.UtcNow,
                        ValidateAudience = true,
                        ValidAudiences = new string[] { clientId },
                        ValidateIssuer = true,
                        ValidIssuer = issuer,
                        ValidateActor = false,
                        ValidateLifetime = true,
                        ValidateIssuerSigningKey = true,
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes("{myClientSecret}"));
                    };
                    
                    options.Events = new JwtBearerEvents
                    {
                        OnMessageReceived = context =>
                        {
                            var accessToken = context.Request.Query["access_token"];

                            if (!string.IsNullOrEmpty(accessToken) &&
                                (context.HttpContext.WebSockets.IsWebSocketRequest || context.Request.Headers["Accept"] == "text/event-stream"))
                            {
                                context.Token = context.Request.Query["access_token"];
                            }
                            return Task.CompletedTask;
                        }
                    };
                });

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services.AddSignalR();

Then I have this in the `Configure` method

            app.UseAuthentication();
            app.UseStaticFiles();
            app.UseSpaStaticFiles();

            app.UseSignalR(routes =>
            {
                routes.MapHub<ChatHub>("/chathub");
            });

            app.UseMvc(routes ........
            app.UseSpa(spa => .......

then in the `ChatHub`, [Authorize]`. I also tried `[Authorize(JwtBearerDefaults.AuthenticationScheme)]`
In the js client, I set the transport to only use websockets coz it's the only one I want to test right now. Btw, websockets work when I'm not using authentication/authorization for the hub. The logs are below

    info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
          Request starting HTTP/1.1 POST http://localhost:5000/chathub/negotiate text/plain;charset=UTF-8 0
    info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
          Successfully validated the token.
    info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
          Authorization was successful.
    info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
          Request finished in 14.5294ms 200 application/json
    info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
          Request starting HTTP/1.1 GET http://localhost:5000/chathub?id=8rXp28ElBL7Ueq2zjwqGFQ&access_token=eyJ...............................................
    info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
          Authorization failed.
    info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
          AuthenticationScheme: Bearer was challenged.
    info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
          Request finished in 10.2827ms 401

When I examine the token, the claims required are there. I don't know exactly which claim is referred to by `ClaimTypes.NameIdentifier` but my token has `name`, `unique_name`, and many more claims.

**Comment by exztinct01** [comment]
It does not enter this block

               if (context.HttpContext.WebSockets.IsWebSocketRequest || context.Request.Headers["Accept"] == "text/event-stream")
                                {
                                    Console.WriteLine($"Request is for WebSockets");
                                    context.Token = context.Request.Query["access_token"];
                                }

**Comment by BrennanConroy** [comment]
Put `app.UseWebSockets()` above `app.UseAuthentication`. It's an unfortunate ordering issue

**Comment by exztinct01** [comment]
oh come on, all I've been missing is the `app.UseWebSockets()`
Thanks for the help
