### ISSUE TITLE
signalr 1.0.2

### ISSUE THREAD

**Issue by randhuck-kbmax** [aspnet/SignalR#2624]
We are using ASP.NET Core 2.1 with SignalR 1.0.2. The latest version of the npm package is 1.0.0-preview1-final which appears to be incompatible with ASP.NET Core 2.1. When trying to install the server side nuget package, it fails saying ASP.NET Core 2.1 only allows 1.0.1 or greater.

This is all in spite of the documentation https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1 having ASP.NET Core 2.1 all over it.

Am I missing something? Why would there be a supported server-side version without an associated javascript client-side version?

**Comment by BrennanConroy** [comment]
> The latest version of the npm package is 1.0.0-preview1-final

Where are you getting that information?

At the very top of the docs it explains how to install the npm package `npm install @aspnet/signalr`, and going to npm and viewing that package will show the latest version as 1.0.2

**Comment by randhuck-kbmax** [comment]
My apologies. When I installed it via npm it got 1.0.0-preview1-final and when browsing the package.json in this repo, I saw the latest version was 1.1.0-preview1 and I mistakened that for the 1.0.0-preview1-final version I got. I was able to specify version 1.0.2 when installing via npm and it was able to retrieve that. You can close this.
