### ISSUE TITLE
How to read or write data in ConnectionHandler?

### ISSUE THREAD

**Issue by Caskia** [aspnet/SignalR#2629]
I use ConnectionHandler to implement my websocket server like [Social Wether Sample](https://github.com/aspnet/SignalR/blob/release/2.2/samples/SocialWeather/SocialWeatherConnectionHandler.cs). It can be seen that connection.Transport.Input or connection.Transport.Output use the pipeline, so when socket clients send message frequently Transport.Input.ReadAsync() will read 
sticky packet. Do you have some advises to separate these packages?
```
var result = await connection.Transport.Input.ReadAsync();
                var buffer = result.Buffer;
                try
                {
                    if (!buffer.IsEmpty)
                    {
                        var stream = new MemoryStream();
                        var data = buffer.ToArray();
                        await stream.WriteAsync(data, 0, data.Length);
                        stream.Position = 0;
                        var weatherReport = await formatter.ReadAsync(stream);
                        await _lifetimeManager.SendToAllAsync(weatherReport);
                    }
                    else if (result.IsCompleted)
                    {
                        break;
                    }
                }
                finally
                {
                    connection.Transport.Input.AdvanceTo(buffer.End);
                }

```

**Comment by BrennanConroy** [comment]
You need to have some kind of packet separator in your protocol.

**Comment by Caskia** [comment]
Need to add some separator in client's packets? I review signalr's code, you use 0x1e as the separator, I think it affects the content of the client. Any other clean approach?

**Comment by BrennanConroy** [comment]
You need some kind of framing, either a separator, or length prefix the packets, or something else.

**Comment by Caskia** [comment]
I think it's like netty, I need to design protocol between client and server side.

**Comment by davidfowl** [comment]
That's correct. At that level you're writing and reading raw bytes and you need to invent a protocol.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
