### ISSUE TITLE
Using Redis to store groups/connections

### ISSUE THREAD

**Issue by Biarity** [aspnet/SignalR#2631]
From my understanding, the [DefaultHubLifetimeManager](https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs) uses an [in-memory dictionary](https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/src/Microsoft.AspNetCore.SignalR.Core/Internal/HubGroupList.cs#L14) to store group info.  IMO this isn't very scalable, and since I'm already using a distributed Redis cache, I'd like to be able to also use that with SignalR.

Going through the source I found the [RedisHubLifetimeManager](https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs), but I'm not sure what the best way to use it is.

1) Do I have to manually inject all the services [here](https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/src/Microsoft.AspNetCore.SignalR.Core/SignalRDependencyInjectionExtensions.cs) just to be able to use Redis? Or is there a way of "overriding" an injected service? (So I won't have to manually update the list of core services if it changes)

2) I have the following in my startup `ConfigureServices`:
```C#
services.AddDistributedRedisCache(options => {...});
```
How do I make sure SignalR is using the same Redis instance?

**Comment by BrennanConroy** [comment]
Add a reference to `Microsoft.AspNetCore.SignalR.Redis` and add `.AddRedis(options)` to `AddSignalR()`. The options will allow you to configure redis.

**Comment by Biarity** [comment]
That sounds good. Just wondering, was this documented anywhere I missed?

**Comment by BrennanConroy** [comment]
Not really, we have an issue on the docs repo to write a doc about it. https://github.com/aspnet/Docs/issues/7204

**Comment by Biarity** [comment]
All good 👍
