### ISSUE TITLE
MessagePack serializes every DateTime to UTC. Is this expected behavior?

### ISSUE THREAD

**Issue by atresnjo** [aspnet/SignalR#2632]
Server version: 2.1.1
Client Version: 1.0.2
MessagePack: 1.0.2

The DateTime I send/receive gets always converted to UTC even if the Kind isn't UTC.  Is this expected behavior or am I missing something?

**Comment by BrennanConroy** [comment]
Unfortunately messagepack datetime spec doesn't store the kind info so this is the expected behavior, see the spec here: https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type

**Comment by atresnjo** [comment]
@BrennanConroy 

Okay, thanks. 

For anyone else that might stumble upon this, a workaround is to set the Kind property with DateTime.SpecifyKind to Utc always and then messagepack won't mess it up.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
