### ISSUE TITLE
Question: Using SignalR with Bare Websockets

### ISSUE THREAD

**Issue by crocoM4** [aspnet/SignalR#2633]
Hi,
I am trying to connect from a javascript client to a hub without using SignalR client.
For example using the [browser websocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) :
` var mSocket= new WebSocket("ws://www.example.com/myHubName") `

I tried to follow [this sample ](https://github.com/aspnet/SignalR/tree/release/2.2/samples/SignalRSamples) but I cannot connect or send messages to a hub like [this](https://github.com/aspnet/SignalR/blob/release/2.2/samples/SignalRSamples/Hubs/Chat.cs)

The only way that makes this work is by using an approach like this [ConnectionHandlers](https://github.com/aspnet/SignalR/blob/release/2.2/samples/SignalRSamples/ConnectionHandlers/MessagesConnectionHandler.cs) that doesn't seem to use SignalR but an implementation of a "custom WebSocket".

So, there is a way to connect to a SignalR server without using the dedicated client? Or I need to implement a custom ConnectionHandler like one in the example. Am I missing something?

**Comment by davidfowl** [comment]
If you want to use raw websockets with hubs then you need to implement the hub protocol. Using the ConnectionHandler requires implementing a custom protocol.

**Comment by crocoM4** [comment]
Thanks for your answer.
Another question: there is a way  to implement a server websocket with SignalR without the hub's functionalities (es. call client's functions) but just use SignalR for example to manage connections? Or i need to implement my websocket using Microsoft.AspNetCore.WebSockets package?

**Comment by davidfowl** [comment]
> Another question: there is a way to implement a server websocket with SignalR without the hub's functionalities (es. call client's functions) but just use SignalR for example to manage connections?

Yes you can use the ConnectionHandler layer for this.

**Comment by crocoM4** [comment]
So basically i need to implement a ConnectionHandler similar to [this one] (https://github.com/aspnet/SignalR/blob/release/2.2/samples/SocialWeather/SocialWeatherConnectionHandler.cs) in the sample where the connections are stored and managed with a list right?

In that case, when does SignalR come into play? I do not seem to use this library in any way

**Comment by davidfowl** [comment]
> So basically i need to implement a ConnectionHandler similar to this one in the sample where the connections are stored and managed with a list right?

Yep. Also that example is very basic. There are thread safety concerns. Transport isn't thread safe. So multiple threads can't write to it at the same time.

> In that case, when does SignalR come into play? I do not seem to use this library in any way

That's right, SignalR itself is built *on top* of the same infrastructure. For e.g. here's the [HubConnectionHandler](https://github.com/aspnet/SignalR/blob/6c28d453ee9dd05412a9dbad66336a062e20a3cf/src/Microsoft.AspNetCore.SignalR.Core/HubConnectionHandler.cs) as an example.

**Comment by crocoM4** [comment]
Ok, now I have much clearer ideas. Thank you for your patience and time
