### ISSUE TITLE
Introductory YouTube video removed?

### ISSUE THREAD

**Issue by kierenj** [aspnet/SignalR#2635]
At  - https://www.youtube.com/watch?v=u0_vkWYYXRc - I get "Video has been removed by the user".
Was just about to sit down and catch up with it!

(Linked in readme.md)

**Comment by BrennanConroy** [comment]
Thanks for pointing that out! I think it was moved and is now at https://www.youtube.com/watch?v=Lws0zOaseIM

**Comment by mikaelm12** [comment]
Thanks for the find!
Being addressed here https://github.com/aspnet/SignalR/pull/2637

**Comment by mikaelm12** [comment]
Done here: a2942ce8851c3e504ad51502bec41886df5d5733
Thanks again for point this out @kierenj!
