### ISSUE TITLE
JS Client for react native

### ISSUE THREAD

**Issue by FIVIL** [aspnet/SignalR#2636]
Hi is it possible to use signalr JS client in react native project

**Comment by BrennanConroy** [comment]
I believe other people have had success using react native.

We don't officially support it, however if you find an issue when using react native we will consider non-breaking changes in PR's to help make it work.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
