### ISSUE TITLE
Send OAuth Token inside WebSocket message and validate on server

### ISSUE THREAD

**Issue by windischb** [aspnet/SignalR#2649]
Hi!

I'm looking for a way to get better control of the OAuth token.
If i understand the current implementation correct, the token will only be sent once -> before the http connection is upgraded to websockets, or?
We use Reference Tokens for Authentication, which means that the API can check if the token on every request, if it is still valid and not expired.

For now i'm always create a JSON Object with the token and all necessary Properties
```js

let msg = {
  "Id": "59b42621-1b62-4d9f-bc40-aad031408d81",
  "AuthData": "ba2f4c04e731d4c3033dd1fef0530bc0bd0e6cbe808321495dc7c4669c7b1d9e",
  "Method": "GetItemsByCategory",
  "Arguments": ["Books"]
}

this.hubConnection.invoke("InvokeServerMethod", msg)
```

On the ServerSide there is only one Method in my Hub:
```csharp
public async Task<SignalRResponse> InvokeServerMethod(SignalRMessage message) {
    try {
        return await SignalRServerMethodManager.InvokeServerMessageAsync(this, message);
    } catch (Exception ex) {
        return new SignalRResponse(message.Id) {
            Error = ex
        };
    }         
}
```

Every `SignalRMessage` is processed by this Method.
1. Check if the Token is still valid -> cached, or if cache expired(5min), validated on IdentityServer
2. Search the Method with matching Arguments using Reflection -> `GetItemsByCategory(string category)` 
3. Invoke the Method
4. return a `SignalRResponse` with the result or error

So far it works well, but i try to find a better way.
I use this way in a few Projects, and i always have to do the heavy lifting with Reflection and so on...

It would be great if there where a `Middleware` or something similar which can be used for validating the token before the Method in the SignalRHub is invoked!
That would save me to do all that terrible stuff...

Br

**Comment by anurse** [comment]
Ok, I'm going to close this for now since it seems like you have a solution to your problem. Feel free to comment further if you have questions! We can always open a new issue if we come up with something concrete to change.
