### ISSUE TITLE
C# Client: Poll timeout causes transport to shut down

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#265]
It looks like when the client requests `/poll` and the request times out on the client, the result is an `OperationCanceledException`, which actually shuts down the whole transport. We'll need to fix this, but unfortunately we still want to properly handle `OperationCanceledException`s thrown from other places.

**Comment by mikaelm12** [comment]
I'm not seeing an OperationCanceledException, or any exception at all here actually. When the poll times out the channel complete and the Transport stops, but I'm not seeing any exceptions.

**Comment by davidfowl** [comment]
@moozzyk @anurse is this still relevant?

**Comment by muratg** [comment]
@mikaelm12 will verify the behavior.

**Comment by muratg** [comment]
We don't think this is an issue anymore.
