### ISSUE TITLE
What happened to the video about SignalR?

### ISSUE THREAD

**Issue by TheBuzzSaw** [aspnet/SignalR#2655]
This is referenced on the README page: https://www.youtube.com/watch?v=u0_vkWYYXRc

Did Microsoft withdraw all these videos? :(

**Comment by TheBuzzSaw** [comment]
Oh, did they get moved to another channel?

https://youtu.be/Lws0zOaseIM

**Comment by mikaelm12** [comment]
Yeah, who ever is in charge of managing that content moved it to be under a different channel. 
Theres an [updated link in the readme](https://www.youtube.com/watch?v=Lws0zOaseIM)
