### ISSUE TITLE
HubDescriptor Type

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2658]
Consider changing the HubInvocationBinder and HubDispatcher to use a common HubDescriptor layer to remove the coupling between the binder and the dispatcher

**Comment by anurse** [comment]
To expand upon this: Currently the Binder needs a way to get the parameter types for a method and it relies upon the Dispatcher to do this. This seems like too many responsibilities for the Dispatcher so the suggestion was to introduce a new "Descriptor" layer that gets the Method information for a Hub and provides it to both the Dispatcher (to invoke methods) and the Binder (to get parameter types).

**Comment by anurse** [comment]
Let's leave this until there's a feature motivating the work.
