### ISSUE TITLE
WebSocketTransport does not create correct url to connect to the server

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#266]
The url here: https://github.com/aspnet/SignalR/blob/dev/test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs#L117  should be just `/echo`

With the Url above the client does not get the connection id. If the WebSockets transport was replaced with LongPolling transport things wouldn't work.

**Comment by mikaelm12** [comment]
Resolved in: https://github.com/aspnet/SignalR/pull/268
