### ISSUE TITLE
JS Client Support IE8？

### ISSUE THREAD

**Issue by yun738243875** [aspnet/SignalR#2663]
same as title

**Comment by anurse** [comment]
We don't officially support IE8. See the [documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-2.1#client-system-requirements) for the specific list of supported browsers.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
