### ISSUE TITLE
MessagePackHubProtocol and unions

### ISSUE THREAD

**Issue by LucaGanio** [aspnet/SignalR#2664]
The current version of the method  MessagePackHubProtocol.WriteArgument only takes two arguments:
private void WriteArgument(object argument, Stream stream)

This is fine for regular serializations, but it is failing when an Interface marked with the Messagepack.UnionAttribute is used as an argument. This happens because the current implementation infer the type to pass to the serializer from a call to GetType(), while for the case of the union the interface type should be used.

A possible solution would be to turn the WriteArgument method into a 3 arguments method, providing the real type of the argument along with its value

**Comment by anurse** [comment]
Can you provide an example so that we can reproduce the issue?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
