### ISSUE TITLE
Wiki - Diagnostics Guide Missing Console Nuget hint for .NET Client logging

### ISSUE THREAD

**Issue by ericbrunner** [aspnet/SignalR#2667]
Hi

Just followed that [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) and got stuck when applying the [.NET Client logging](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#net-client-logging) .

The extension method `AddConsole()` wasn't found. After gooling I found that @anurse mentioned that nuget extension package [here](https://github.com/aspnet/SignalR/issues/2466#issuecomment-396425386)

`PM> install Microsoft.Extensions.Logging.Console
`

Please add the hint to the Diagnostics Guide. Thanks!
Eric

**Comment by anurse** [comment]
Done! Thanks for the suggestion!
