### ISSUE TITLE
SignalR Connection Stability - Connection Error and Connection Timeout

### ISSUE THREAD

**Issue by ericbrunner** [aspnet/SignalR#2668]
* Versions of Server-Side NuGet Packages:  `Microsoft.Azure.SignalR V. 1.0.0-preview1-10015`
* Versions of Client-Side NuGet/NPM Packages: `Microsoft.AspNetCore.SignalR.Client V. 1.0.2` / `signalr.js V. 1.0.2`
* Are you using the C# client or the JavaScript client: `Both`
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): `WebApp and ApiApp (with SignalR Hub) are hosted in Azure App Service (guess both run on KESTREL, didn't changed anything in portal). The ApiApp uses the [Azure SignalR service](https://azure.microsoft.com/en-us/services/signalr-service/).`
* The Operating System on the Server (Windows/Linux/macOS): `Azure App Service on WIndows`
* The Operating System on the Client (Windows/Linux/macOS): `Windows/Linux`
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): `Chrome/Edge/Firefox/Opera`

I did everything mentioned in the Diagnostics Guide except the Fiddler tracing.
Download my logs from 2 separate TESTRUNS here => [SignalR-TestRuns.zip](https://github.com/aspnet/SignalR/files/2216757/SignalR-TestRuns.zip)

I write down what I did and maybe it is easier to follow in context of the logs.

1. I navigated to my the [SignalR test URL](https://truckerapp360-dev.azurewebsites.net/signalrtest) of  my WebApp 
2. From that URL the SignalR Hub at [https://truckerwebapp-api-dev.azurewebsites.net/chat](https://truckerwebapp-api-dev.azurewebsites.net/chat) is contacted (CORS in truckerwebapp-api.dev enabled). 
3. All javascript code from the [SignalR test URL](https://truckerapp360-dev.azurewebsites.net/signalrtest) can be found with right-click view source.
4. I made 2 separate TESTRUNS
   **TESTRUN1:**
   Only on WIndows 10 Pro PC inside my company LAN
   **TESTRUN2:**
   On the WIndow 10 Pro PC inside my company LAN and from my private Ubuntu Linux PC at home.
   The logs are separated and I hope you can easily locate them. If not feel free to contact me 
   immediately.

**TESTRUN Descriptions:**

Test Case: Test SignalR Connection Stability

---- **TESTRUN 1** -------------------------------------------------------------------------

Duration: 12 hours
Tests Hosting Environment: Window 10 Professional 64 bit
Where: On-Premises Window LAN behind Firefall
 

Web App (Test CORS) - OUTGOING REQUESTS
URL: [https://truckerapp360-dev.azurewebsites.net/signalrtest](https://truckerapp360-dev.azurewebsites.net/signalrtest)
Host: Azure 
Type: App Service (Web App)

-	(Client Side)
	npm @aspnet/signalr 
		- `signalr.js V. 1.0.2`
	
Api App (with SignalR Hub) - INCOMING REQUESTS
SignalR Endpoint: [https://truckerwebapp-api-dev.azurewebsites.net/chat](https://truckerwebapp-api-dev.azurewebsites.net/chat) 
Host: Azure 
Type: App Service (Api App)

(Server Side)
Nuget
	- `Microsoft.Azure.SignalR V. 1.0.0-preview1-10015`

Api App utilized Azure SignalR Service (currently for Tests on Free Plan max. 100 concurrent connections)!

Code snippet:
`services.AddSignalR(hubOptions => hubOptions.EnableDetailedErrors = true).AddAzureSignalR();`
	

Tests on : 

- .NET FW 4.6.1 (Console App) - OUTGOING REQUESTS (connect, wireup, start, receive)

(Client Side) 
Nuget
	- `Microsoft.AspNetCore.SignalR.Client V. 1.0.2`

- .NET Core 2.1 (Console App) - OUTGOING REQUESTS (connect, wireup, start, receive)

(Client Side)
Nuget
	- `Microsoft.AspNetCore.SignalR.Client V. 1.0.2`

- Browser
	- `Chrome  Version 67.0.3396.99 (Official Build) (64-bit)`
	- `Opera Version 54.0.2952.60` 
	
	
Still running after 12 hours:
	- `.NET Core 2.1 (Console App)`
	- `Opera Version 54.0.2952.60`
	
	Browser that lost Connection
	- `Chrome  Version 67.0.3396.99 (Official Build) (64-bit)`

	
	App that lost connection
	`.NET FW 4.6.1 (Console App)`
	

---------------- **TESTRUN 2** -------------------------------------------------------

BROWSER:
Chrome (WIndows + Ubuntu)
Opera (WIndows + Ubuntu)
Edge

Tests Hosting Environment: Window 10 Professional 64 bit / Ubuntu Linux
Where: On-Premises Window LAN behind Firefall / Linux from external PC

Tests on : 

- .NET FW 4.6.1 (Console App) - OUTGOING REQUESTS (connect, wireup, start, receive)

(Client Side) 
Nuget
	- `Microsoft.AspNetCore.SignalR.Client V. 1.0.2`

- .NET Core 2.1 (Console App) - OUTGOING REQUESTS (connect, wireup, start, receive)

(Client Side)
Nuget
	- `Microsoft.AspNetCore.SignalR.Client V. 1.0.2`

- Browser
	- `Chrome  Version 67.0.3396.99 (Official Build) (64-bit)`
	- `Opera Version 54.0.2952.60 `
	- `Microsoft Edge Version 41.16299.371.0 (Microsoft EdgeHTML 16.16299)`

Duration: 	21 hours
Started	: 	21.07.2018 11:20 am
Ended	:	22.07.2018 08:20 am

**Sample Code:**

ApiApp containing the SignalR Hub and TruckerAppChangeTracker Service that sends every 10 seconds data to all clients 
[TruckerWebApp.RestApi.zip](https://github.com/aspnet/SignalR/files/2216789/TruckerWebApp.RestApi.zip)
[TruckerWebApp.RestApi.Samples.Net.Console.zip](https://github.com/aspnet/SignalR/files/2216790/TruckerWebApp.RestApi.Samples.Net.Console.zip)
[TruckerWebApp.RestApi.Samples.NetCore.Console.zip](https://github.com/aspnet/SignalR/files/2216791/TruckerWebApp.RestApi.Samples.NetCore.Console.zip)

**Comment by ericbrunner** [comment]
In the meanwhile I found some good [link ](https://github.com/aspnet/Docs/issues/6885#issuecomment-395124361) and set on the server side the `KeepAliveInterval ` server - to - client ping to 3 seconds.

 ```
services.AddSignalR(hubOptions => {
                hubOptions.EnableDetailedErrors = true;
                hubOptions.KeepAliveInterval = TimeSpan.FromSeconds(3);
            }).AddAzureSignalR();
```

and increased the ServerTimeout in the javascript client to 10 minutes (default 30 sec.).

**JS**
```
var connection = new signalR.HubConnectionBuilder()
                    .withUrl('/chat')
                    .configureLogging(signalR.LogLevel.Trace)
                    .build();

                connection.serverTimeoutInMilliseconds = 1000 * 60 * 10; // 1 second * 60 * 10 = 10 minutes.
```

**.NET 4.6.1 ConsoleApp / .NET Core 2.1 ConsoleApp**

`            connection.ServerTimeout = TimeSpan.FromMinutes(10);`

Will to a 3rd TESTRUN attempt and get back with my results.

**Comment by ericbrunner** [comment]
Results from **TESTRUN3** (see [my last comment](https://github.com/aspnet/SignalR/issues/2668#issuecomment-406850416))

After applying the `ServerTimeout `on the HubConnection (Client Side in JS and .NET, .NET Core)
and set the `KeepAliveInterval `to 3 seconds in the Hub (server to client pings) I started 
**TESTRUN3** with following clients. Please find the logfiles below.

Host: Windows 10 Pro x64
Duration: ~ 20 hours

Started SignalR Client Browser Connections from
- `Chrome Version 67.0.3396.99 (Official Build) (64-bit)`
- `Firefox 61.0.1 (64-Bit)`
- `Opera Version 54.0.2952.60`
 

Started SignalR Client Console App:
- `.NET FW 4.6.1 Console App`
- `.NET Core 2.1 Console App`


The following where still connected and working (send, receive)

Browser:
- `Chrome Version 67.0.3396.99 (Official Build) (64-bit)`

Console App:
- `.NET FW 4.6.1 Console App`


**Connection Errors** occured in browser `Firefox `and `Opera `. I get that **connection error** (please find the detailed log in atteched zip)

**Console Log**
```
Information: Close message received from server. Utils.ts:165:20
Error: Connection disconnected with error 'Error: Server returned an error on close: Unknown error.'. Utils.ts:159:20
Server returned an error on close: Unknown error. signalrtest:158:21 
```

In .NET Core 2.1 Console App I get that **connection error** (please find the detailed log in atteched zip):

```
[12:13:57 DBG] Message received. Type: Text, size: 36, EndOfMessage: True.
[12:13:57 VRB] Resetting keep-alive timer, received a message from the server.
[12:13:57 DBG] Processing 36 byte message from server.
[12:13:57 ERR] Received close message with an error: Unknown error.
[12:13:57 VRB] Waiting on Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:748).
[12:13:57 INF] WebSocket closed by the server. Close status NormalClosure.
[12:13:57 VRB] Releasing Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:757).
[12:13:57 DBG] Receive loop stopped.
[12:13:57 DBG] Disposing HttpConnection.
[12:13:57 INF] Transport is stopping.
[12:13:57 DBG] Send loop stopped.
[12:13:57 DBG] Transport stopped.
[12:13:57 INF] HttpConnection Disposed.
[12:13:57 DBG] Canceling all outstanding invocations.
[12:13:57 ERR] Connection is shutting down due to an error.
Microsoft.AspNetCore.SignalR.HubException: The server closed the connection with the following error: Unknown error.
```

At first look it seems that I `fixed the connection timeout` with the above code adjustments which is very good :) Still the **connection error** with message Unknown error. Hmm.... Not very helpful message. Anyway hope you can find the root cause.

Thanks in advance,
Eric 
[SignalR-TestRun3.zip](https://github.com/aspnet/SignalR/files/2218336/SignalR-TestRun3.zip)

**Comment by BrennanConroy** [comment]
Its hard to tell from your logs, but it looks like you have multiple app instances running and the connections that close are from an instance that is shut down.
> 2018-07-21 21:17:38.422 +00:00 [Information] TruckerWebApp.RestApi.Services.TruckerAppChangeTrackerService: StopAsync overload invoked for graceful shutdown. Now calling base.

The connections that don't close are on an app instance that isn't shut down. This doesn't look like a SignalR issue.

**Comment by ericbrunner** [comment]
Thats absolurly nonsrnse what you write. That ChangeTracker Service is a background service and has nothing to do with that specific SignalR issue. In fact it sends periodically messages to the SignalR Hub.
The WebApp hosting that background service and the SignalR Hub is ONE instance running and hosted in Azure.

All other logs I provided are browser SignalR javascript and .NET client logs.

I question myself what for I invested that much time and uploaded full code and diagnostic logs forvsuch poor answer!

Anyway in the meanwhile I got workarounds.

**Comment by BrennanConroy** [comment]
I'm sorry you feel that way. But from your logs and the fact that Background services are stopped on application shutdown, it points to what I said.

From the `BackgroundService` code:
> Triggered when the application host is performing a graceful shutdown.

Code for reference:
https://github.com/aspnet/Hosting/blob/09c2fe8911a3b8e9c263a4b510a0245c28c656ff/src/Microsoft.Extensions.Hosting.Abstractions/BackgroundService.cs#L45-L49

Could you explain why there are 2 separate log files for the server logs if it's only a single app instance?

**Comment by ericbrunner** [comment]
As mentioned in the initial issue

I navigated to my the SignalR test URL of my WebApp
From that URL the SignalR Hub at https://truckerwebapp-api-dev.azurewebsites.net/chat is contacted (CORS in truckerwebapp-api.dev enabled).

One Server Log is from the WebApp which acts as the Javascript SignalR client to the CORS ebabled Api App (2nd logs) where the SignalR Hub is hosted. The Background Service is hosted in the Api App where the hub resides, too. Thatvis normal behaviour and intented that StopAsync method is invoked on app shutdown. But thats not the issue.

**Comment by ericbrunner** [comment]
Try yourself

Join the chatroom https://truckerwebapp-api-dev.azurewebsites.net/signalrtest

Leave it running for 48 hours and look at your browser logs. You will see the connection errors or connection timeouts
I will remove the anonymous login after 48 hours. Thats only for investigation purposes of Microsoft.

**Comment by anurse** [comment]
There's a huge amount of data here and lot of different questions going on. Can you please simplify the data and clarify precisely what steps cause unexpected behavior and what you *expected* the behavior to be? Reviewing the logs I see a very large quantity of completely normal behavior and a request to shut down the site:

```
2018-07-21 21:17:37.839 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.1 POST http://127.0.0.1:32656/iisintegration  0
2018-07-21 21:17:37.906 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 67.9194ms 202 
```

Those log messages are sent when IIS tries to shut down the application, which would definitely cause any existing connections to be terminated. If these are irrelevant, as you claim above, can you limit the logs to only the server application on which the **Hub** is running rather than including additional server applications?

We'd like to help resolve your issue, but we need your help interpreting the data as we don't know how your application is structured. Correlating the errors you are seeing on the client with the logs on the server would help immensely as I don't see any timestamps on the client. We need to try to isolate what is being logged on the server *around the time the client errors occur*. Unfortunately, we don't include the timestamps in our log messages, which is something we should fix (https://github.com/aspnet/SignalR/issues/2750), but as an interim measure you can add timestamps yourself using a custom logger. The following example will register a custom logger that includes timestamp information:

```javascript
var connection = new HubConnectionBuilder()
    .withUrl(...)
    .configureLogging({
        log: function(logLevel, message) {
            console.log(new Date().toISOString() + ": " + message);
        }
    })
    .build();
```
