### ISSUE TITLE
SignalR connection negotiation fails

### ISSUE THREAD

**Issue by beradrian** [aspnet/SignalR#2669]
* Versions of Server-Side NuGet Packages: 2.3.0
* Versions of Client-Side NPM Packages: 1.0.2
* Are you using the C# client or the JavaScript client: TypeScript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Azure Web App
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome

I'm trying to use SignalR in an Angular application. I'm using the Typescript client `@aspnet/signalr`.

What I get in the console is 

> Information: Normalizing '/api/signalr?connectionData=%5B%7B%22name%22%3A%22myhub%22%7D%5D' to 'http://server:port/api/signalr?connectionData=%5B%7B%22name%22%3A%22myhub%22%7D%5D'.
>
> Debug: Starting HubConnection. 
> 
> Debug: Starting connection with transfer format 'Text'. 
> 
> Debug: Sending negotiation request:
> http://server:port/api/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22kanbanhub%22%7D%5D
>
> Error: Failed to start the connection: TypeError: Cannot read property 'length' of undefined

The error seems to come from the line `if (!(_i < transports_1.length)) return [3 /*break*/, 9];` in `HttpConnection`. It could be related to the fact that the negotiation response does not contain the `availableTransports` array.

    {
        "Url":"/api/signalr",
        "ConnectionToken":"XXX",
        "ConnectionId":"XXX",
        "KeepAliveTimeout":20.0,
        "DisconnectTimeout":30.0,
        "ConnectionTimeout":110.0,
        "TryWebSockets":false,
        "ProtocolVersion":"1.2",
        "TransportConnectTimeout":5.0,
        "LongPollDelay":0.0
    }

Any idea why?

I also asked this on SO: https://stackoverflow.com/questions/51449450

**Comment by davidfowl** [comment]
ASP.NET Core SignalR and ASP.NET SignalR are incompatible.

**Comment by anurse** [comment]
You need the [`signalr`](http://npmjs.com/package/signalr) package, which is developed from the github.com/SignalR/SignalR repo.
