### ISSUE TITLE
Consider adding "Spotless" to Java build

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2676]
We should use something like [Spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-to-java-source-google-java-format) to enforce and apply code style to our Java code. I think we should do similar things in C#, but at least with C# we're all quite familiar with the code style and can enforce the major ones in PRs. Plus people get a little wary when you start suggesting automated C# style enforcement 😛 

I suggest we just pick an existing Java style and go with it. [Google Java Style](https://google.github.io/styleguide/javaguide.html) seems fine and is [supported by Spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-to-java-source-google-java-format)

**Comment by mikaelm12** [comment]
Cool, I'll take a look

**Comment by mikaelm12** [comment]
Done here: 39e6c6ff2f91d41564615efdd2df04063d499250
