### ISSUE TITLE
JavaDoc Documentation

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2677]
We'll need to provide JavaDoc documentation to publish to Maven. This can just be dummy content for now, but [Maven Central requires](https://central.sonatype.org/pages/requirements.html#supply-javadoc-and-sources) that we at least produce a `-javadoc.jar` file.

**Comment by mikaelm12** [comment]
I have Java docs being generated with placeholder text as a build task

**Comment by mikaelm12** [comment]
https://github.com/aspnet/SignalR/blob/3d6e1e69fd03d0aed50f713ece482e7df65434a6/clients/java/signalr/build.gradle#L26-L29

**Comment by mikaelm12** [comment]
Working here: https://github.com/aspnet/SignalR/pull/2745
