### ISSUE TITLE
Packaging Java Client as part of build

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2678]
We need to package the Java Client appropriately as part of our build. We'll be publishing to Maven Central, which mean we need to adhere to their [requirements](https://central.sonatype.org/pages/requirements.html) for packages. That means we need to produce the following outputs from our build:

* `signalr-1.0.0.pom` - POM file manifest (like a nuspec) - Looks like Gradle can [produce this for us](https://docs.gradle.org/current/userguide/publishing_maven.html)
* `signalr-1.0.0.jar` - JAR file with compiled code - Again, Gradle should be able to produce this output
* `signalr-1.0.0-sources.jar` - JAR file with Java source code (for debugging) - Yet again [Gradle seems to support this with some configuration](https://docs.gradle.org/current/userguide/publishing_maven.html)
* `signalr-1.0.0-javadoc.jar` - JAR file containing Java Documentation produced by `javadoc` - Gradle should be able to do this too.

**Comment by anurse** [comment]
This is a fairly high priority if we want to be able to ship the Java Client in the first preview for 2.2. Let's sync up on this when you're next in @mikaelm12 .

**Comment by mikaelm12** [comment]
Working here: https://github.com/aspnet/SignalR/pull/2690

**Comment by anurse** [comment]
https://github.com/aspnet/SignalR/commit/e03166252578dca884f9b9d5c1d8a632de97754a
