### ISSUE TITLE
JsonSerializationException: A member with the name 'inactive' already exists on 'Users'.

### ISSUE THREAD

**Issue by MagicAndre1981** [aspnet/SignalR#2683]
When I try to call SignalR function from UWP Client I get a JsonSerializationException claiming that a member 'inactive' already exists. But the class only contains 1 field with this name and I have no idea how to solve this.

```
      Received hub invocation: InvocationMessage { InvocationId: "1", Target: "LogOnAsync", Arguments: [ foo, bar ] }.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[6]
      Failed writing message.
Newtonsoft.Json.JsonSerializationException: A member with the name 'inactive' already exists on 'Users'. Use the JsonPropertyAttribute to specify another name.
   bei Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonProperty property) in /_/Src/Newtonsoft.Json/Serialization/JsonPropertyCollection.cs:Zeile 118.
   bei Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:Zeile 1353.
   bei Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:Zeile 317.
   bei Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:Zeile 1226.
   bei Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver.ResolveContract(Type type) in /_/Src/Newtonsoft.Json/Serialization/CamelCasePropertyNamesContractResolver.cs:Zeile 104.
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:Zeile 70.
   bei Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:Zeile 1143.
   bei Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteCompletionMessage(CompletionMessage message, JsonTextWriter writer)
   bei Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   bei Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   bei Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message)
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[4]
      Waiting for the application to finish sending data.
OnDisconnectedAsync, 'exception':
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[2]
      Socket closed.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[6]
      OnConnectedAsync ending.
```

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: 2.1.2
* Versions of Client-Side NuGet/NPM Packages: 2.1.2
* Are you using the C# client or the JavaScript client: C#
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Microsoft.AspNetCore.Server.Kestrel 2.1.2
* The Operating System on the Server (Windows/Linux/macOS): Windows 10 v1709 x64
* The Operating System on the Client (Windows/Linux/macOS):Windows 10 v1709 x64
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): n/a

**Comment by anurse** [comment]
I notice the class is `partial`, are there other parts to the class in different files then?

**Comment by MagicAndre1981** [comment]
that's it. I only remembered that the partial class has overrides for ToString(), Equals(), GetHashCode(), but indeed there was a public property with name Disabled which is bool and return 1==disabled, because this is an old db and at at the creation time, firebird had no boolean support (added in Firebird 3.0).

**Comment by anurse** [comment]
Ok, so it sounds like you've resolved your issue. I'll close this bug, but feel free to comment further if you have questions about this or open a new issue if you encounter something else!

**Comment by MagicAndre1981** [comment]
thanks for your help. New Signalr is faster compared to old version. Why has the class worked in the old but doesn't work in new SignalR?

**Comment by anurse** [comment]
Without looking at the whole class (with all the `partial` pieces) it would be hard to tell. I believe ASP.NET SignalR did not do the automatic `camelCase` conversion, which could cause this.

**Comment by MagicAndre1981** [comment]
ok, thanks for the explanation.

**Comment by MagicAndre1981** [comment]
@anurse 1 question. Is[ this issue ](https://github.com/xamarin/xamarin-android/issues/2037)Xamarin/Android or SignalR related?

**Comment by anurse** [comment]
SignalR should work in Xamarin.Android with the 8.4.0.1 release of Xamarin.Android, which is part of Visual Studio 15.8. That version hasn't been fully released yet but is available in the public previews of VS 15.8

**Comment by MagicAndre1981** [comment]
ok, so I have to wait for 15.8 final.

**Comment by anurse** [comment]
If you aren't able to use preview releases, then yes, you will have to wait.
