### ISSUE TITLE
Blocking error doing integration testing

### ISSUE THREAD

**Issue by bdominguez** [aspnet/SignalR#2686]
I have the same problem as this user:

https://stackoverflow.com/questions/51265565/aspnet-core-integration-test-for-signalr

It can be really easy tested with this snippet:

Startup:

```csharp
 public class MyCustomStartup {

    public void ConfigureServices(IServiceCollection services) {
        services.AddSignalR();
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
        app.UseSignalR(routes => {
            routes.MapHub<MyCustomHub>("/myCustomHub");
        });
    }

}
```

Test code:

```csharp
IWebHostBuilder builder = new WebHostBuilder()
    .UseStartup<MyCustomStartup>();

using (TestServer server = new TestServer(builder)) {
    var connection = new HubConnectionBuilder()
          .WithUrl(new Uri(server.BaseAddress, "myCustomHub"))
          .Build();

    await connection.StartAsync();
}
```

Error:

`
Message: Test method MyProject.TestMethod1 threw exception: 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
`

Is there any way to get it working? Thanks.

**Comment by BrennanConroy** [comment]
Looks like `TestServer` requires you to use the `HttpMessageHandler` created by it, so change your code to
```
.WithUrl(new Uri(server.BaseAddress, "myCustomHub"), o =>
{
    o.HttpMessageHandlerFactory = _ => server.CreateHandler();
})
```

**Comment by anurse** [comment]
Note that this will not work with WebSockets. It's not possible to use the WebSocket transport to connect to a server hosted with TestServer

Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
