### ISSUE TITLE
Flaky test: CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2687]
This test [fails](http://aspnetci/viewLog.html?buildId=516007&buildTypeId=Releases_22xPublic_UbuntuUniverse) occasionally with the following error:
```
System.TimeoutException : Operation in CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser timed out at /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisEndToEnd.cs:118
   at System.Threading.Tasks.TaskExtensions.OrTimeout[T](Task`1 task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber)
   at Microsoft.AspNetCore.SignalR.Redis.Tests.RedisEndToEndTests.CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser(HttpTransportType transportType, String protocolName) in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisEndToEnd.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser-WebSockets-json at 2018-07-26T11:06:08
| [0.000s] TestLifetime Information: Starting test CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser_WebSockets_json at 2018-07-26T11:06:08
| [0.006s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: oL-lE9Q8TE1OUMdwc-KbHA - Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:34263/echo?id=oL-lE9Q8TE1OUMdwc-KbHA'.
| [0.010s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: oL-lE9Q8TE1OUMdwc-KbHA - HttpConnection Started.
| [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: oL-lE9Q8TE1OUMdwc-KbHA - Using HubProtocol 'json v1'.
| [0.013s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: oL-lE9Q8TE1OUMdwc-KbHA - HubConnection started.
| [0.016s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: UJlJgaOV48igHz9RK614vw - Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:44298/echo?id=UJlJgaOV48igHz9RK614vw'.
| [0.017s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: UJlJgaOV48igHz9RK614vw - HttpConnection Started.
| [0.018s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: UJlJgaOV48igHz9RK614vw - Using HubProtocol 'json v1'.
| [0.019s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: UJlJgaOV48igHz9RK614vw - HubConnection started.
| [5.024s] TestLifetime Information: Finished test CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser_WebSockets_json in 5.0229968s
| [5.026s] TestLifetime Information: Finished test CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser-WebSockets-json in 5.0257548s
```

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by BrennanConroy** [comment]
I'm going to up the log level on the server because the trail ran cold. There is a 5 second gap where nothing is logged and the last thing that happened was the `RedisHubLifetimeManager` being invoked.

**Comment by anurse** [comment]
What are we supposed to do with this issue @ryanbrandenburg @Eilon @muratg ? @BrennanConroy has updated the test to give us more information next time this happens, but until it does re-occur we can't really move forward. Should we be leaving this issue open?

**Comment by anurse** [comment]
Cool with me. The "More Info" label is perfect here then since our general pattern is to close out issues with that label when the last message is from a contributor and was posted more than a week ago.

**Comment by BrennanConroy** [comment]
Been a week since we "asked" for more info, closing out. Bot will make a new issue if it re-occurs.
