### ISSUE TITLE
Can anyone here help with a Signalr HubContext issue?

### ISSUE THREAD

**Issue by Carneno** [aspnet/SignalR#2688]
### Please consider the following before filing an issue

* If you are using NuGet Packages that start with `Microsoft.AspNet.SignalR`, use the issue tracker at https://github.com/SignalR/SignalR to report the issue. This 
repository is for packages that start with `Microsoft.AspNetCore.SignalR` (and NPM packages that start with `@aspnet/signalr`)

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: 1.0.2
* Versions of Client-Side NuGet/NPM Packages: 1.0.2
* Are you using the C# client or the JavaScript client: Javascript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): IIS Express 
* The Operating System on the Server (Windows/Linux/macOS): Windows 10 Home version 1803
* The Operating System on the Client (Windows/Linux/macOS): Windows 10 Home version 1803
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Firefox 61.0.1 (64-bit)
* Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please **do not** put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.  I'm sorry, I can't figure this out.

When in doubt, feel free to file the issue, we're happy to help answer questions. We also suggest using the `asp.net-core-signalr` tag on StackOverflow to ask questions.

Hello,

I tried to get help for my problem at [StackOverflow](https://stackoverflow.com/questions/51363483/how-do-i-display-signalr-messages-on-a-client-sent-from-an-asp-net-core-2-1-mvc) and got one unrelated comment and no answers.

I have an Asp.Net Core 2.1, MVC, C#, Web application in Visual Studio 2017 15.7.5 with SignalR 1.0.2.

I am having a problem with using SignalR not being able to send hub messages to a client through the controller dependency injection HubContext method.

I don't know where else to go for help except here.  I already tried StackOverflow and [Asp.Net Forums](https://forums.asp.net/t/2143825.aspx?Return+View+with+absolute+path+not+executing+from+IActionResult+controller+method)

Is there anyone here that can help to figure out why this is not working for me?

Thanks,
Tony

**Comment by anurse** [comment]
From the code on your StackOverflow post, it looks like the "Get Products" button is submitting a form, which means the browser will navigate to your MVC controller. When it does this, the SignalR connection is disconnected. SignalR connections only stay active while you're on the current page. As soon as you submit a form or click a link, the SignalR connection is broken.

Can you clarify what you're trying to achieve and what isn't working? There's a lot of extra information here that makes it difficult to understand the problem you're having.

**Comment by Carneno** [comment]
@anurse Thanks for your help.

I agree, the SignalR connection is disconnected when the form navigates to the MVC controller.  I pointed that out in both of my other requests for help.

So, if that's the case, where SignalR connections only stay active while you're on the current page, what is the sense in providing the ability to [send notifications to clients from outside a hub](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1)?

I am trying to send messages to the AccessToken.cshtml.  That's what is not working.

Thanks,
Tony

**Comment by anurse** [comment]
The general purpose for that is to send a notification to one user when **a different user** performs an action. SignalR is designed to send push notifications to users, and push notifications aren't generally needed for the client that performed the request, since they can get a notification as part of the response (depending upon how that's done).

What is your goal here? It looks like, from your description, when the user clicks "Get Products" you want to show them the available products. This isn't really something that should need SignalR, this can just be done by rendering the list of products in the view returned by your GetProducts link. SignalR is for sending push notifications *for things the user didn't directly request*.

**Comment by anurse** [comment]
If you really want to keep the user on the "AccessToken" page and render the products in-line rather than sending them to a new page, then you'd need to do AJAX requests instead of full form posts, but again you still wouldn't need SignalR for this.

**Comment by Carneno** [comment]
Yes, that is my goal.  It is the second part of my goal.  The first is to display progress messages during the processing to get the products to show to the user.

I think I'll just use a ViewComponent to display the products list on the same screen.

Thanks for your information and help.

Tony
