### ISSUE TITLE
Injecting Timer Based Hub Service in Startup.cs Not Initializing Service

### ISSUE THREAD

**Issue by budoray** [aspnet/SignalR#2689]
Nuget
Microsoft.AspNetCore.SignalR v1.0.2

This issue solved my first need where I had a timer within my hub class. I followed @spudcud 's comment.
https://github.com/aspnet/SignalR/issues/1699

I then created a ChatHubService for simple testing. I set a breakpoint in ChatHubService and execution never stops. I see no evidence that the timer is working either. 

Startup.cs
services.AddSingleton(typeof(ChatHubService), typeof(ChatHubService));
...

elswhere
...

// This works fine when invoking from a web page
public class ChatHub : Hub
    {
        public async Task SendMessage(string message)
        {
            await Clients.All.SendAsync("ReceiveMessage", message);
        }
}

// This does not appear to initialize as expected.
public class ChatHubService
    {
        private IHubContext<ChatHub> _hubContext;
        private Timer _timer;

        public ChatHubService(IHubContext<ChatHub> hubContext)
        {
            _hubContext = hubContext;

            // Do any timer initialization/setup etc or do it via method call.
            _timer = new Timer();
            _timer.Interval = 1000;
            _timer.Elapsed += new ElapsedEventHandler(_timer_Elapsed);
            _timer.AutoReset = true;
            _timer.Enabled = true;
            _timer.Start();
        }

        void _timer_Elapsed(object sender, ElapsedEventArgs e)
        {
            NotifyClients("Test");
        }

        private void NotifyClients(string message)
        {
            _hubContext.Clients.All.SendAsync("ReceiveMessage", message);
        }
    }

**Comment by anurse** [comment]
Do you activate the service at all? Registering a service in DI just makes it available to other components. A component has to actually **request** it in order to activate it. You'd need to put `ChatHubService` in a constructor somewhere.

However, if all you want is a background service that runs on a timer, you can use [`IHostedService`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1)

**Comment by budoray** [comment]
Converting this to a service solved my issue. Thank you for your quick response and the link to the documentation.
