### ISSUE TITLE
Transport spec specifies incorrect query string

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2691]
The spec says the query string should be "connectionId", however it's supposed to be "id"

**Comment by anurse** [comment]
![Sesame Street aliens saying "Derp" repeatedly](https://media.giphy.com/media/hhnpSxCjyXzHy/giphy.gif)

**Comment by davidfowl** [comment]
A PR would have been less work.

**Comment by BrennanConroy** [comment]
If you recall, I was in the middle of some important work

**Comment by mikaelm12** [comment]
> A PR would have been less work.

Was gonna write the same thing earlier but held back 🤣

**Comment by Eilon** [comment]
Does this really need to go into the patch branch? Who is looking at the patch branch for a spec?

**Comment by anurse** [comment]
I kinda agree here. It doesn't really need to be in the patch.

**Comment by anurse** [comment]
Just merge it in to `release/2.2` and up to `master`.
