### ISSUE TITLE
Introduce CompletableFuture & Async Await to the Java Client 

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2694]
Currently everything is synchronous. We can stop blocking everywhere with Java's `CompletableFuture` type and then we can make it nice with EA's async await library

CompletableFuture - https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html
EA Async Await library for Java - https://github.com/electronicarts/ea-async

**Comment by mikaelm12** [comment]
There are no milestones for previews but this is planned to go into preview2

**Comment by anurse** [comment]
Also consider [RxJava](https://github.com/ReactiveX/RxJava)

**Comment by anurse** [comment]
We should look at this now. I think it's going to be the place where we're going to need the most feedback.

**Comment by mikaelm12** [comment]
Yeah, been thinking about this for sure but I guess I'm waiting for Preview1 to go out the door first

**Comment by anurse** [comment]
Let's do futures and start by just wrapping the blocking stuff in Futures.

**Comment by mikaelm12** [comment]
Done here: f27df1d61e39d5c9995d65edd2212fa36e24ea94
