### ISSUE TITLE
LongPolling: Setting connection to inactive while there is still an active poll

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2700]
There was a race where we could set the connection state to Inactive even though there was an active poll which could cause the connection to be closed by the server.

The fix was to add a "task queue" so all new poll requests would wait until the previous poll finished all state updates before starting the new poll state updates.

Details:
Browser could abort the http request (normal timeout behavior) and then send a new poll, on the server we might start processing the poll and see that there is an active poll which we could proceed to cancel and wait for the transport task to finish. The transport task would get an operation canceled exception and see that the http request was aborted so would just return normally, Then it would proceed to wait for the state lock which the new poll is currently holding, the new poll would see the transport task is finished and set the status as active and start the new transport task and then release the lock. Now the previous poll can aquire the lock, see that the connection is active (which it assumed was from when it polled) and set it to inactive. Then our heartbeat would come along 5 seconds later and clean the connection up.

TLDR:
Poll is canceled by client, client sends new poll, race between previous poll and new poll where status could be set as inactive and heartbeat could clean up connection.

**Comment by BrennanConroy** [comment]
Done https://github.com/aspnet/SignalR/pull/2697

**Comment by davidfowl** [comment]
@BrennanConroy we should find out why IE is doing this. Are we setting up the xhr incorrectly by default? The server timeout should be less than the client timeout by default.

**Comment by BrennanConroy** [comment]
Turns out the client poll was set to timeout at 90 seconds, and the server poll timeout is also 90 seconds. We should increase the poll timeout on the client
