### ISSUE TITLE
Configurable WebSockets Transport Buffer Size

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#271]
The WebSockets transport arbitrarily uses a 1k buffer for reads. We should figure out a better value for this.

**Comment by muratg** [comment]
cc @moozzyk thoughts?

**Comment by moozzyk** [comment]
https://github.com/SignalR/SignalR/blob/1fba14fa3437e24c204dfaf8a18db3fce8acad3c/src/Microsoft.AspNet.SignalR.Core/Owin/WebSockets/WebSocketHandler.cs#L20-L21 - possibly configurable but I am not feeling strongly about this.

**Comment by muratg** [comment]
Set the buffer to 4KB.

**Comment by grahamehorner** [comment]
+1 vote for a configurable buffer value with a default value 4k

**Comment by davidfowl** [comment]
@mikaelm12 Add an option to https://github.com/aspnet/SignalR/blob/ccf6cd415e7e79896ba6b47045ecc5a5f1474460/src/Microsoft.AspNetCore.Sockets.Http/WebSocketOptions.cs. 

We may also want to consider a maximum message size https://github.com/SignalR/SignalR/blob/83726e069c2c19a32a2e57a990facad17328906b/src/Microsoft.AspNet.SignalR.Core/Configuration/IConfigurationManager.cs#L51

**Comment by davidfowl** [comment]
Closing this since we're going to just use bounded pipes

**Comment by SamBallantyne** [comment]
@davidfowl how did this end up? 

I'd like to use websocketd for a very low latency application where I am writing to stdout roughly 100 messages of about 100B every second. Websocketd seems to be buffering the input... Any thoughts?

**Comment by SamBallantyne** [comment]
What are the bounds on the pipe? Is it possible to flush?

**Comment by davidfowl** [comment]
@SamBallantyne what exactly are you trying to control? There are various buffer sizes some are configurable and some aren't configurable.
