### ISSUE TITLE
Is there any .NET4.0 client?

### ISSUE THREAD

**Issue by zlzforever** [aspnet/SignalR#2711]
I setup a asp.net core signalr service, and some machines use Microsoft.AspNetCore.SignalR.Client connect my service works well, but i have some machines only support .NET4.0, so i try to use Microsoft.AspNet.SignalR.Client to connect asp.net core signalr service, but failed.

**Comment by anurse** [comment]
No, the ASP.NET Core SignalR Client requires a platform that supports .NET Standard 2.0. The minimum version of .NET Framework supported is 4.6.1.

The `Microsoft.AspNet.SignalR.Client` package is not compatible with ASP.NET Core SignalR, as you observed.
