### ISSUE TITLE
[2.1.5] LongPolling: Setting connection to inactive while there is still an active poll

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2714]
@Eilon For 2.1.4 consideration

PR for change in release/2.2 https://github.com/aspnet/SignalR/pull/2697
Original Issue: #2700

**Comment by Eilon** [comment]
@BrennanConroy - please fill in the template:

## Description

TODO: Describe the bug

## Customer Impact

TODO: Describe how it affects customers. Is there a workaround? How many customers reported?

## Regression from?

TODO: Fill in when it worked, when it stopped working

## Risk

High/Medium/Low/Very Low
TODO: Fill in explanation of risk.

**Comment by Eilon** [comment]
@BrennanConroy can you provide info on whether there are customer reports of this?

**Comment by BrennanConroy** [comment]
This issue was hitting the bug https://github.com/aspnet/SignalR/issues/2672

**Comment by Eilon** [comment]
@BrennanConroy putting a reminder here for you to update the customer impact section.

**Comment by natemcmaster** [comment]
There was no representative in shiproom today for this one, so this bug is not yet approved for 2.1.x.

cc @muratg

**Comment by mkArtakMSFT** [comment]
Not approved for 2.1.X in Shiproom.

**Comment by muratg** [comment]
Closing this. We'll reconsider if there's customer interest.

**Comment by anurse** [comment]
We need to make sure someone from the team is at the shiproom for this since we need to understand why this is not being considered for a servicing release. It is a customer-reported issue that causes connections to be dropped randomly, as described in the impact above. My understanding has been that this meets the bar.

**Comment by vivmishra** [comment]
Approved for 2.1.5

**Comment by anurse** [comment]
@BrennanConroy please open a PR porting this change to `release/2.1` and link it here.

**Comment by natemcmaster** [comment]
Fixed in https://github.com/aspnet/SignalR/pull/2769
