### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by rashmi-carevalet** [aspnet/SignalR#2724]
I have a .Net Core 2.0 server and my client is ASP.NET Web Application.
signalR server is using Microsoft.AspNetCore.SignalR 1.0.2 and my javascript client library is jquery.signalR-2.2.2.js
I have added the javascript library manually to the project and referencing it in my code. (not using any client nuget packages).

When connecting I get a 405 Method Not Allowed error. 

In one of the posts I found that the error occurs because of signalR version compatibility issues between signalR server and signalR client. If that is the case then could you please suggest the version of signalR javascript library that is compatible with AspNetCore.SignalR 1.0.2

**Comment by BrennanConroy** [comment]
As you found in other posts those two are incompatible.

The JS client that works is on npm at https://www.npmjs.com/package/@aspnet/signalr
There is a small readme on that page with example usage. And we also have docs to show a full end-to-end https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio
