### ISSUE TITLE
facing issues while migrating from 1.0.0 alpha to 1.0.0

### ISSUE THREAD

**Issue by sarvabowmen** [aspnet/SignalR#2726]
### Please consider the following before filing an issue

* If you are using NuGet Packages that start with `Microsoft.AspNet.SignalR`, use the issue tracker at https://github.com/SignalR/SignalR to report the issue. This 
repository is for packages that start with `Microsoft.AspNetCore.SignalR` (and NPM packages that start with `@aspnet/signalr`)

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: 1.0.0
* Versions of Client-Side NuGet/NPM Packages: 1.0.0
* Are you using the C# client or the JavaScript client: javascript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):  Azure
* The Operating System on the Server (Windows/Linux/macOS): windows
* The Operating System on the Client (Windows/Linux/macOS): windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): chrome
* Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please **do not** put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.

When in doubt, feel free to file the issue, we're happy to help answer questions. We also suggest using the `asp.net-core-signalr` tag on StackOverflow to ask questions.
in version 1.0.0 alpha i was accessing the connection metadata like this
var tcs = (TaskCompletionSource<bool>)Context.Connection.Metadata["ConnectedTask"];
				//tcs?.TrySetResult(true);

But after migrating to 1.0.0 i cannot able to access the connection metadata, please help me by giving info on how to access it
https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide

**Comment by BrennanConroy** [comment]
Use `Context.Items["ConnectedTask"]`

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
