### ISSUE TITLE
Flaky WebSockets test on Travis

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#273]
We get this failure https://travis-ci.org/aspnet/SignalR/jobs/208738694#L2771 about 50% of the time on Travis. We've just been restarting Travis to this point. 
We should at least skip this until we resolve the issue.

**Comment by moozzyk** [comment]
I don't think disabling the test will fix the issue in general. I think that once we disable this test another will start failing (similarly to how these test started  failing after we disabled ping-pong tests).

**Comment by mikaelm12** [comment]
Hmm. Okay. Then we should look into this a bit further

**Comment by anurse** [comment]
I'm going to try to take a look after the work I'm currently finishing up.
