### ISSUE TITLE
signalr  modified for the miniprogram

### ISSUE THREAD

**Issue by LcFireRabbit** [aspnet/SignalR#2732]
** using the  JavaScript client (in the miniprogram ide)
* The Operating System on the Server (Windows):
* The Operating System on the Client (Windows):
[signalr_for_miniprogram.txt](https://github.com/aspnet/SignalR/files/2259136/signalr_for_miniprogram.txt)

**Comment by BrennanConroy** [comment]
What is the question?

**Comment by BrennanConroy** [comment]
I'm sure there are better places to put this.
