### ISSUE TITLE
MessagePackHubProtocol error in Angular

### ISSUE THREAD

**Issue by andreatosato** [aspnet/SignalR#2736]
* Versions of Server-Side NuGet Packages:
**_Microsoft.AspNetCore.SignalR.Core: 1.0.2
Microsoft.AspNetCore.SignalR.Protocols.MessagePack: 1.0.2_**
* Versions of Client-Side NuGet/NPM Packages:
 **_@aspnet/signalr: 1.0.2
 @aspnet/signalr-protocol-msgpack: 1.0.2_**
* Are you using the C# client or the JavaScript client:
**_Javascript_**
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
**_IIS Express_**
* The Operating System on the Server (Windows/Linux/macOS):
**_Windows_**
* The Operating System on the Client (Windows/Linux/macOS):
**_Windows_**
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
**_Chrome_**

**Angular error**:
```
Uncaught ReferenceError: global is not defined
    at Object../node_modules/buffer/index.js (index.js:43)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@aspnet/signalr-protocol-msgpack/dist/esm/MessagePackHubProtocol.js (vendor.js:61966)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@aspnet/signalr-protocol-msgpack/dist/esm/index.js (vendor.js:62173)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/services/chatHub.service.ts (chat.service.ts:10)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/home/home.component.ts (main.js:595)
    at __webpack_require__ (bootstrap:76)
```
**Client Side**
```
private connection: HubConnection;
...
this.connection = new HubConnectionBuilder()
      .withUrl(environment.baseHubs + '/chat', {
            accessTokenFactory: () => token,
            logger: LogLevel.Trace
      })
      .withHubProtocol(new MessagePackHubProtocol())
      .build();
```
**Server Side**
```
 services.AddSignalR(config => config.EnableDetailedErrors = true)
              .AddMessagePackProtocol()
              .AddAzureSignalR();
...
 app.UseAzureSignalR(map =>
        {
                map.MapHub<ChatHub>("/chat");
        });
```

When I change protocol to Json all work **fine**:
Client Side
```
this.connection = new HubConnectionBuilder()
      .withUrl(environment.baseHubs + '/chat', {
            accessTokenFactory: () => token,
            logger: LogLevel.Trace
      })
      .withHubProtocol(new JsonHubProtocol())
      .build();
```
Server Side
```
 services.AddSignalR(config => config.EnableDetailedErrors = true)
              .AddJsonProtocol(config => config.PayloadSerializerSettings.ContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver())
              .AddAzureSignalR();
...
 app.UseAzureSignalR(map =>
        {
                map.MapHub<ChatHub>("/chat");
        });
```

**Comment by anurse** [comment]
Can you provide your webpack configuration? When using SignalR as a node module (via something like WebPack) it expects to be in a Node environment (where things like `global` are defined). WebPack is supposed to [automatically shim those things](https://webpack.js.org/configuration/node/) though.

**Comment by andreatosato** [comment]
this is my project: https://github.com/andreatosato/RealTime/tree/master/ChatPWA/chat-app
Project is for conference sessions.
I tried to add in polyfill.js:
```
(window as any).global = window;
```
The introduction of the line of code indicates a new error with messagepack.

**Comment by BrennanConroy** [comment]
Could you give step-by-step instructions on how to run the app and hit the issue?

**Comment by andreatosato** [comment]
With last [commit](https://github.com/andreatosato/RealTime/commit/1ef0a9609b676da5d56b7ac01934478121b03191), I migrate from Json to MessagePack protocol.

Step to reproduce error:

1. Run client Angular App with [angular-cli running powershell command: ng serve](https://github.com/andreatosato/RealTime/tree/master/ChatPWA/chat-app#development-server)
2. Run server [ASP .NET Core app](https://github.com/andreatosato/RealTime/tree/master/ChatPWA/ChatApp.Backend)

**Comment by BrennanConroy** [comment]
Yeah, I figured out those steps, but how do you actually hit the issue? It ran fine, but there is no SignalR code running in the browser.

**Comment by andreatosato** [comment]
excuse me for the misunderstanding.
I encounter the problem at runtime when running the following line of code:
```Javascript
this.connection = new HubConnectionBuilder()
      .withUrl(environment.baseHubs + '/chat', {
            accessTokenFactory: () => token,
            logger: LogLevel.Trace
      })
      .withHubProtocol(new MessagePackHubProtocol())
      .build();
```

**Comment by BrennanConroy** [comment]
Got it running by adding more polyfill bits. Just had to follow stackoverflow for a couple more things
```
(window as any).global = window;

(window as any).process = {
    env: { DEBUG: undefined },
    version: "1",
};
global.Buffer = global.Buffer || require('buffer').Buffer;
```

https://stackoverflow.com/questions/50371593/angular-6-uncaught-referenceerror-buffer-is-not-defined

**Comment by andreatosato** [comment]
Wow, great! Thanks a lot! @BrennanConroy 

Complete resolution:
**index.html**

```HTML
<head>
 <script>
    var global = global || window;
    var Buffer = Buffer || [];
    var process = process || {
      env: { DEBUG: undefined },
      version: []
    };
  </script>
</head>
```

**polyfills.ts**
```JavaScript
(window as any).global = window;
(window as any).process = {
    env: { DEBUG: undefined },
    version: '1',
};
```
