### ISSUE TITLE
Test failure: ServerThrowsHubExceptionIfStreamingHubMethodCannotBeResolved

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2746]
This test [fails](http://aspnetci/viewLog.html?buildId=524711&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
System.Exception : 1 error(s) logged.
Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport - ErrorPolling - RVwH3zULmhl9KAICdQuEZQ - Error while polling 'http://127.0.0.1:50262/dynamic?id=RVwH3zULmhl9KAICdQuEZQ'.
===================
System.NotSupportedException: Stream does not support reading.
   at System.IO.Stream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.StreamToStreamCopy.CopyAsync(Stream source, Stream destination, Int32 bufferSize, Boolean disposeSource, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.<Poll>d__19.MoveNext()
===================
   at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose()
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose()
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<ServerThrowsHubExceptionIfStreamingHubMethodCannotBeResolved>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test ServerThrowsHubExceptionIfStreamingHubMethodCannotBeResolved-json-LongPolling-/dynamic at 2018-08-06T22:59:00
| [0.001s] TestLifetime Information: Starting test ServerThrowsHubExceptionIfStreamingHubMethodCannotBeResolved_json_LongPolling_dynamic at 2018-08-06T22:59:00
| [0.001s] ServerLogScope Information: Server log scope started.
| [0.003s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:50262/dynamic/negotiate  0
| [0.003s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.7132ms 200 application/json
| [0.003s] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: RVwH3zULmhl9KAICdQuEZQ - Starting transport. Transfer mode: Text.
| [0.011s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:50262/dynamic?id=RVwH3zULmhl9KAICdQuEZQ  
| [0.012s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 7.4695ms 200 application/octet-stream
| [0.012s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: RVwH3zULmhl9KAICdQuEZQ - HttpConnection Started.
| [0.012s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: RVwH3zULmhl9KAICdQuEZQ - Using HubProtocol 'json v1'.
| [0.012s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:50262/dynamic?id=RVwH3zULmhl9KAICdQuEZQ  
| [0.013s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:50262/dynamic?id=RVwH3zULmhl9KAICdQuEZQ  32
| [0.013s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6593ms 200 text/plain
| [0.013s] SERVER Microsoft.AspNetCore.SignalR.HubConnectionContext Information: RVwH3zULmhl9KAICdQuEZQ - Completed connection handshake. Using HubProtocol 'json'.
| [0.014s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: RVwH3zULmhl9KAICdQuEZQ - HubConnection started.
| [0.014s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.9032ms 200 application/octet-stream
| [0.014s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:50262/dynamic?id=RVwH3zULmhl9KAICdQuEZQ  
| [0.014s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:50262/dynamic?id=RVwH3zULmhl9KAICdQuEZQ  11
| [0.015s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6528ms 200 application/octet-stream
| [0.015s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.7708ms 200 text/plain
| [0.015s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:50262/dynamic?id=RVwH3zULmhl9KAICdQuEZQ  
| [0.015s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHos
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by davidfowl** [comment]
What a bizzare exception. Maybe something is copying the get request stream?

**Comment by anurse** [comment]
This is definitely an odd one. It seems to be happening within `HttpClient.SendAsync` (from `FinishSendAsyncBuffered` on the stack). We don't do anything fancy here:

https://github.com/aspnet/SignalR/blob/1874368a5caa4f562d1d693e58ae5b68a24d6166/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/LongPollingTransport.cs#L149-L170

**Comment by davidfowl** [comment]
cc @geoffkizer @davidsh @stephentoub

**Comment by geoffkizer** [comment]
I'm guessing the CancellationToken is firing here? Just a guess, but we may have a race where the connection is being closed due to cancellation, but LoadIntoBufferAsyncCore is trying to read the response body anyway, and somehow this gets manifested as "stream does not support reading".

**Comment by anurse** [comment]
Ah, that's definitely possible. We do trigger that cancellation token on shutdown. Should we just suppress that error and treat it as `OperationCanceledException`?

**Comment by geoffkizer** [comment]
Well, we still shouldn't throw the weird stream exception in this case. But assuming that cancellation is being triggered, it's less concerning than just random failures.

BTW what version of .NET is this running on?

**Comment by anurse** [comment]
Looks like the failure is on .NET Framework 4.6.1 (at least that's the build output we're running, not sure exactly which runtime is on the machine)

**Comment by ryanbrandenburg** [comment]
Yeah, if it's caused by another product I would say mark it as blocked and use this as a tracking issue for the other issue. That's what we were trying to convey in the checklist, any suggestions on how to make that more clear?

**Comment by stephentoub** [comment]
But this only repros on .NET Framework, not .NET Core?

**Comment by anurse** [comment]
Correct. Filed https://github.com/dotnet/corefx/issues/31748

**Comment by anurse** [comment]
I have a few more updates in the linked issue, but I did indeed verify that the cancellation token was triggered immediately before this exception occurred.

**Comment by anurse** [comment]
> But this only repros on .NET Framework, not .NET Core?

> Correct.

I should clarify. We've only **seen** it on .NET Framework. I have no idea if the same condition could exist in the .NET Core code :)

**Comment by ryanbrandenburg** [comment]
What's left to track is when we consume the fix they produce.

**Comment by anurse** [comment]
We've fixed the immediate test issue, and there's nothing we need to track here anymore.
