### ISSUE TITLE
Connection Can't be established

### ISSUE THREAD

**Issue by embryologist** [aspnet/SignalR#2749]
This issue seems redundunt and I apologize for posting it again but none of the solutions helped me.

I have the following config,
* asp.net core 2.1.3
* Are you using the C# client or the JavaScript client: Both
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
* The Operating System on the Server (macOS):
* The Operating System on the Client (macOS):
* The Browser on the client, if using the JavaScript client (Chrome):
* Angular 6.1.1.
* "@aspnet/signalr": "^1.0.2",

I config. my logging as following,

```C#
 public static void Main(string[] args) {
            var logger = NLogBuilder.ConfigureNLog("NLog.config").GetCurrentClassLogger();
            try {
                CreateWebHostBuilder(args)
                    .ConfigureLogging(config => {
                        // config.ClearProviders();
                        config.AddFilter("Microsoft.AspNetCore.SignalR", LogLevel.Debug);
                        config.AddFilter("Microsoft.AspNetCore.Http.Connections", LogLevel.Debug);
                        config.AddConsole();
                        config.AddDebug();
                        config.AddFilter("System", Microsoft.Extensions.Logging.LogLevel.Debug)
                            .AddFilter<DebugLoggerProvider>("Microsoft", Microsoft.Extensions.Logging.LogLevel.Trace);
                    })
                    .Build().Run();
            } catch (Exception e) {
                logger.Error(e, "Stopped program because of exception");
                throw;
            } finally {
                NLog.LogManager.Shutdown();
            }
        }
```

and my startup config,

```C#
services.AddSignalR((hubOptions) => {
                    hubOptions.EnableDetailedErrors = true;
                    // hubOptions.KeepAliveInterval = TimeSpan.FromMinutes(1);
                })
                .AddJsonProtocol(options => {
                    options.PayloadSerializerSettings.ContractResolver =
                        new DefaultContractResolver();
                }).AddHubOptions<ChatHub>(options => {
                    options.EnableDetailedErrors = true;
                });
```

```C#
app.UseCors(config =>
                config.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin().AllowCredentials());
            app.UseSignalR(routes => {
                routes.MapHub<ChatHub>("/api/CRUD");
            });
```

my front end,

 ```typescript
 public createConnection(hubEndPoit) {
    this.hubConnection = new HubConnectionBuilder()
      .withUrl(this.baseUrl + hubEndPoit, {
        transport: signalR.HttpTransportType.WebSockets,
      })
      .configureLogging(signalR.LogLevel.Information)
      .build();
  }

  private startConnection(): void {
    this.hubConnection
      .start()
      .then(() => {
        console.log('Hub connection started');
        this.connectionEstablished.next(true);
      })
      .catch(err => {
        console.log('Error while establishing connection, retrying...', err);
        setTimeout(this.startConnection(), 5000);
      });
  }
```

What I am experiencing is that when I try to initialize the connection I get the following,

![screen shot 2018-08-07 at 03 44 52 2](https://user-images.githubusercontent.com/15179986/43771514-59fe005c-99f4-11e8-90cd-d4de3773255a.png)

and this is my logging,

![screen shot 2018-08-07 at 03 45 49 2](https://user-images.githubusercontent.com/15179986/43771576-877e4a0a-99f4-11e8-81e1-4f2224d114f1.png)

What could be going wrong here?

**Comment by anurse** [comment]
Angular uses `zone.js` which seems to corrupt the WebSocket APIs, causing us to throw these errors. See https://github.com/aspnet/SignalR/issues/2389#issuecomment-393601202 for more info.

Apparently adding `Object.defineProperty(WebSocket, 'OPEN', { value: 1, });` to the start of your app can work around this issue.

**Comment by embryologist** [comment]
speaking of, at the start of my app I have this request which I don't know where it's coming from,

![screen shot 2018-08-07 at 11 29 49](https://user-images.githubusercontent.com/15179986/43795230-91b6685e-9a35-11e8-9fdc-a7c954d124ca.png)
![screen shot 2018-08-07 at 11 30 26](https://user-images.githubusercontent.com/15179986/43795251-a16c8fee-9a35-11e8-9bba-7280ab6bfb14.png)

would this be an issue?

**Comment by BrennanConroy** [comment]
That's part of how angular works, I think it talks to the `ng serve` process?

**Comment by embryologist** [comment]
oh, okay.
I still don't know how to work around this issue, from @anurse comment it seems that my problem is client side. in my app I run the subscription in ngZone like this,
```typescript
private onChanges() {
    this.signalRService.foodchanged.subscribe(value => {
      this.ngZone.run(() => {
        console.log(value);
      });
    });
  }
```
but my guess is that the issue goes even beyond that, the service that I am using does not show that the connection is established immediately, 

first I get the normalizing information and then after a minute or so I get the handshake error

**Comment by anurse** [comment]
Can you collect a client-side network trace and logs as specified in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)?

**Comment by embryologist** [comment]
@anurse, so I just changed my connection code block to the basic config. and I got this change,

```typescript
  public createConnection(hubEndPoit) {
    this.hubConnection = new HubConnectionBuilder()
      .withUrl(this.baseUrl + hubEndPoit)
      .configureLogging(signalR.LogLevel.Information)
      .build();
  }

```
![screen shot 2018-08-07 at 12 01 49](https://user-images.githubusercontent.com/15179986/43796660-b8bb206c-9a39-11e8-8dbb-f85b574b9dcd.png)

I am also attaching the log trace per the guide.

[www.artngcore.com.har.txt](https://github.com/aspnet/SignalR/files/2267716/www.artngcore.com.har.txt)

**Comment by embryologist** [comment]
something that baffles me, why the connection is being normalized first? I got it to work partially but the proper connection lasts at least a minute before it starts

**Comment by embryologist** [comment]
per the [docs](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#javascript-client-logging), everything should be outputted to the browser console. as far as I can see, this is what I am getting,

![screen shot 2018-08-07 at 14 42 25](https://user-images.githubusercontent.com/15179986/43804226-239c5ac0-9a50-11e8-804a-b43e43b6149d.png)

I am getting nothing else, should I?

my config for logging is,

```typescript
import { HubConnection, HubConnectionBuilder } from '@aspnet/signalr';
import { Subject } from 'rxjs';
import { ConfigService } from '../utils/config.service';
import * as signalR from '@aspnet/signalr';

  public createConnection(hubEndPoit) {
    this.hubConnection = new HubConnectionBuilder()
      .withUrl(this.baseUrl + hubEndPoit)
      .configureLogging(signalR.LogLevel.Information)
      .build();
  }
```

> Have you applied the workaround I suggested above?

yes, I currently have it in my app.component.ts `Constructor` but it's not solving the errors.

one more thing, I am totally new to SignalR and my code is adopted from this [repo](https://github.com/FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript). I cloned it and it is working fine there.

**Comment by anurse** [comment]
> something that baffles me, why the connection is being normalized first?

All this means is that we're resolving the URL using the Browser APIs (i.e. converting `/foo/bar` to `https://example.com/foo/bar`). This doesn't depend on being able to connect at all

> yes, I currently have it in my app.component.ts Constructor but it's not solving the errors.

And that code is definitely running **before** you try to create the SignalR connection?

If that's the case, I don't see anything obvious in your logs. Are you able to provide code that reproduces the issue? You mentioned that the sample you took this from does seem to be working. I presume it's using the same version of Angular that you are?

**Comment by embryologist** [comment]
@anurse yes, app.component.ts will run and initialize everything way before I start the connection. 
My angular version is "@angular/core": "^6.1.1", the demo version is "@angular/core": "^6.0.0".

one more interesting thing, and speaking of resolving URL, the normalization does not occur in safari. the code stuck there.

**Comment by embryologist** [comment]
So here is my problem I guess. at the begining of the connection a request is sent to `wss://www.artngcore.com:4200/api/CRUD?id=0_uGI7io5iFN1SOv5Akfxw` and this process is being stalled and provokes the handshake errors until the proper connection starts.

![screen shot 2018-08-07 at 16 56 47](https://user-images.githubusercontent.com/15179986/43808732-379254ae-9a63-11e8-9dcd-ad09b3021e85.png)

is this a normal part of the process? sending to wss://...... ?

**Comment by embryologist** [comment]
Now I see what you explained, its a `WebSocket` issue, the only way to temporary resolve the issue is by explicitly set the `transportType` to `ServerSentEvents`. 

`.withUrl(this.baseUrl + hubEndPoit, signalR.HttpTransportType.ServerSentEvents)`

I still can not resolve via `WebSocket`

**Comment by embryologist** [comment]
ok, sorted out.
for my angular I am using a proxy to differ the HTTP requests, ignorant enough not to consider it for te only reason that I haven't gotten a 404 response.

```typescript
 "/api": {
    "target": {
      "host": "localhost",
      "protocol": "https:",
      "port": 5001
    },
    "secure": false,
    "logLevel": "debug",
    "changeOrigin": true
  },

```
So I changed the route to:

```C#
 app.UseSignalR(routes => {
                routes.MapHub<ChatHub>("/hub/CRUD");
            });

```
and my client call,

```typescript
public createConnection(hubEndPoit) {
    this.hubConnection = new HubConnectionBuilder()
        .withUrl('https://localhost:5001/' + 'hub/' + hubEndPoit)
      .configureLogging(signalR.LogLevel.Information)
      .build();
  }
```
@anurse @BrennanConroy , Thank you for your great help. I am closing this issue.

**Comment by BrennanConroy** [comment]
Glad you got it resolved!
