### ISSUE TITLE
Include timestamps in console log messages

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2750]
We don't include timestamps in the console log messages we write from the client. It would make correlation with server diagnostics much easier if we did.

* [x] TypeScript
* [ ] Java

**Comment by anurse** [comment]
TypeScript and Java need this added. C# does it via the logger itself adding the timestamp.

**Comment by anurse** [comment]
Recommended format:

```
[Timestamp] [Level] Message
```

Where `Timestamp` is the ISO date format: `YYYY-MM-ddTHH:MM:ssZ` (i.e. `2018-08-07T10:10:00Z`)

**Comment by mikaelm12** [comment]
I'll assign this to myself and close it out with the Java log timestamps.

**Comment by mikaelm12** [comment]
Done here: https://github.com/aspnet/SignalR/commit/6310cffd7c7a8e9beef5d7d774f557870e08b401
