### ISSUE TITLE
ES6 Module / Class Support?

### ISSUE THREAD

**Issue by Randy-Buchholz** [aspnet/SignalR#2758]
I'm trying to used SignalR with ES6 modules and classes, but can't find the right imports. There doesn't seem to be a top level class or factory for SignalR. Basically, I'm trying to do something like the examples in the https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#call-client-methods-from-hub, but inside an ES2015 module or inside a JavaScript class. Using a script tag, the docs has:
```
<script src="~/lib/signalr/signalr.js"></script>
<script>
    const connection = new signalR.HubConnectionBuilder()
        .withUrl("/chatHub")
        .configureLogging(signalR.LogLevel.Information)
        .build();
    connection.start().catch(err => console.error(err.toString()));
</script>
```

In a ES6 module (or module script block), it seems I should be able to do something similar. I looked for an exported SignalR class, but don't see one. I couldn't find any imports to work with. Something like an exported class with a static builder method (`HubConnectionBuilder` or similar) would allow something like

```
import { SignalR } from "/js/signalR.js";
const connection = SignalR.HubConnectionBuilder... 

// or exposing properties

import { HttpConnection, HubConnection } from "/js/signalR.js";

const hubUrl = "http://localhost:5000/hub";
const httpConnection = new HttpConnection(hubUrl);
const hubConnection = new HubConnection(httpConnection)
```
Am I missing something?

**Comment by anurse** [comment]
In an ECMAScript module, the namespace prefix isn't required, the following code should work:

```javascript
import { HubConnectionBuilder } from "@aspnet/signalr";

const connection = new HubConnectionBuilder()
    .withUrl("/chatHub")
    .build();
// ... connect, invoke methods, attach handlers, etc.
```

**Comment by anurse** [comment]
The priorities for documentation have been the `<script>` tag form, but you're right, we're lacking some docs for using the library from an ECMAScript module. I'll file an issue for that. We do have some docs as part of our [WebPack documentation](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.1&tabs=visual-studio#enable-client-and-server-communication) (the code snippets also apply when using SignalR via any other ECMAScript module environment, not just WebPack)

**Comment by Randy-Buchholz** [comment]
Don't know if the `@aspnet` makes a difference (I'm just using loose files), but
```
import { HubConnectionBuilder } from "/js/signalr.js";

const hubConnection = new HubConnectionBuilder()
    .withUrl(hubUrl)
    .build();
```
gives

`Uncaught SyntaxError: The requested module '/js/signalr.js' does not provide an export named 'HubConnectionBuilder'`

**Comment by anurse** [comment]
So where did you get this `signalr.js` file? Are you using ASP.NET **Core** on your server? The ASP.NET Core SignalR client comes from the NPM package `@aspnet/signalr`.

If you're using ASP.NET (non-Core, i.e. `System.Web`) then it doesn't support ECMAScript modules.

**Comment by Randy-Buchholz** [comment]
It's core, the one from the npm package, dist directory. I just dropped it into this solution's wwwroot.

 * @overview ASP.NET Core SignalR JavaScript Client.
 * @version 1.0.2.

**Comment by anurse** [comment]
The script in `dist/browser`? That one isn't designed for use via a module loader. If you're using a module loader, is there a reason you aren't just using it out of `node_modules`? That's the main purpose for using a module loader.

The `dist/browser` script is the one designed for single-file including via a `<script>` tag. If you really need to take the scripts out of the module and put them somewhere else, you want the `dist/esm` folder, which has an ECMAScript Module version of the library. This should all be done for you though if you reference the module directly via `node_modules`.

**Comment by Randy-Buchholz** [comment]
I'm seeing that now. Found the esm folder. Thanks.
