### ISSUE TITLE
Move classes in to 'com.microsoft.aspnet.signalr' package

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2761]
Our Java classes are in the default package. We should move them into `com.microsoft.aspnet.signalr`.

We need a `package com.microsoft.aspnet.signalr;` directive at the top of each file and probably need to put them in a folder structure (`com/microsoft/aspnet/signalr`).

**Comment by mikaelm12** [comment]
Done here: c9104d4932b85ab7dfa784f3314421584a3882e1
