### ISSUE TITLE
Support hubs methods from explicit interface implementations

### ISSUE THREAD

**Issue by michalkovy** [aspnet/SignalR#2766]
We want to use nicely on server side F# with SignalR and methods implementing an interface, like this code:
```fsharp
type CustomerDisplayHub () =
    inherit Hub()
    interface ICustomerDisplay with 
        member this.SendGenericCommand (command : Domain.Command) = 
            CustomerDisplay.SendGenericCommand(command)
```
Unfortunately, HubReflectionHelper which is used by DefaultHubDispatcher doesn't include methods from explicit interfaces to hub and F# implements interfaces explicitly only. The same problem is in C# when using explicit interface implementations:
```csharp
public class CustomerDisplayHub : Hub, ICustomerDisplay
{
    bool ICustomerDisplay.SendGenericCommand(Command command)
    {
        return CustomerDisplay.SendGenericCommand(command);
    }
}
```

* Versions of Server-Side NuGet Packages: 1.0.2

**Comment by anurse** [comment]
When you use explicit interface implementation the methods are private so we aren't able to see them. Is this the only way to implement an interface in F#? It would seem a lot of other things (MVC Controller Actions, etc.) would fail in this way as well.

**Comment by anurse** [comment]
After looking at the generated code for some F#, you're going to have to make your hub methods "members" directly on the type in order for SignalR to be able to detect them. You can then define interface implementations that just forward to those methods (this is exactly what C# does for implicit implementation). For example:

```fsharp
type CustomerDisplayHub() =
    inherit Hub()
    member this.SendGenericCommand (command : Domain.Command) = 
        CustomerDisplay.SendGenericCommand(command)
    interface ICustomerDisplay with
        member this.SendGenericCommand(command) = this.SendGenericCommand(command)
```

If you don't define a separate member, then the implementation is done in a private method and SignalR won't expose it as a hub method.

**Comment by michalkovy** [comment]
You can list the interfaces which it implements and call methods using the interfaces.

Yes, it is the only nice way in F#. What you can do is to write a method manually with same name again this time within type itself and call from that method the method from interface implementation. That is our current work-around. See Calling Interface Methods here: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/interfaces

**Comment by michalkovy** [comment]
You were quicker but yes, what you wrote we use, but I see it as a work-around, like I wrote. It doesn't feel nice, also reason we use interface is to ensure the signature matches but we can't check that on those manually written methods so it becomes less useful.

**Comment by anurse** [comment]
SignalR only scans the public methods, and we don't have plans to change that behavior as it would be dramatically different from MVC and other places where we scan for methods to invoke. It would also be surprising (and possibly dangerous) for private methods (such as explicit interface implementations) to be invokable by the client. It's unfortunate that F# doesn't have a way to do implicit interface implementation via public methods like C# does but I don't think we can do much to change it without causing other problems.

**Comment by anurse** [comment]
We can certainly do whatever we want, the question is does it match the intended semantics. SignalR is intended to allow you to expose .NET classes across our transports to other clients. It's an RPC system, designed to extend method calls across a network. In general that means we want the semantics of a SignalR Hub to match the semantics of any other local .NET class. There are obviously places where this doesn't work (for example SignalR doesn't currently support overloading) but that's the general design principal.

The purpose of explicit interface implementation is to be able to implement an interface **without** exposing the implementation through the actual declaring type. For SignalR to provide different semantics here than the rest of .NET would be strange. It's unfortunate that the F# syntax for implementing an interface method and exposing that implementation on the type itself isn't very friendly, but I don't think that's a sufficient reason to break that expectation.

**Comment by michalkovy** [comment]
Makes sense, a few comments:

Advanced RPC frameworks sometimes allow you to use the object hierarchy so you are able to upcast to interface and call it remotely - that would work for us, too.

You are trying to match how class is used from .NET locally but locally it should be mostly used through interfaces.

Today SignalR has already exception to the semantics - it hides implicit implementation from IDisposable interface, cleaner towards the semantics would be if it didn't do it and hubs implemented IDisposable explicitly, but I understand that it makes life easier to C# devs.

Let me now describe our use case, maybe you will have better idea for us. We have F# server and we use it from our F# client. What I would ideally want is to ensure interface between client and server to be checked at compile time and minimize amount of manually written code. So I though we start by using interfaces and later that we would write type provider which would generate client types from the interfaces. Do you plan to write some kind of generated .net client or something like that in future? Or any other idea? Thanks.

**Comment by anurse** [comment]
> Advanced RPC frameworks sometimes allow you to use the object hierarchy so you are able to upcast to interface and call it remotely - that would work for us, too.

It's certainly something to think about. I don't think it's a goal for SignalR right now, but you are correct that it is a feature of some RPC systems.

> You are trying to match how class is used from .NET locally but locally it should be mostly used through interfaces.

Right, but at the moment we only register Hubs by their type. Perhaps if we had a way to register the Hub's interface type separate from its implementation (like DI services) this could make sense. Then the type "handle" you are remoting is the interface, and the implementation type is just the runtime value.

> Today SignalR has already exception to the semantics - it hides implicit implementation from IDisposable interface, cleaner towards the semantics would be if it didn't do it and hubs implemented IDisposable explicitly, but I understand that it makes life easier to C# devs

Yep, and I absolutely agree that this isn't an absolute situation where we always adhere directly to the semantics of the platform. Suppressing Dispose makes sense because it is a relatively minor break in the semantics that has a large benefit.

> Let me now describe our use case, maybe you will have better idea for us. We have F# server and we use it from our F# client. What I would ideally want is to ensure interface between client and server to be checked at compile time and minimize amount of manually written code. ... Do you plan to write some kind of generated .net client or something like that in future?

I actually agree that in a C# application, an interface is exactly the right way to do this. It's unfortunate that F# has different semantics here. I'm not sure the best way to accomplish this. We have talked about proxy generation (see https://github.com/aspnet/SignalR/issues/290) and it's something we're keeping on our backlog. We'd do that by exposing an object model describing the hub, so you could certainly use that to build a type provider (if we didn't provide one in the box).

Glad to hear this feedback! I'm going to close this issue because as I said I don't think we want to change our semantics here and we have issues tracking the other ideas. Feel free to comment further if you have other feedback.

**Comment by michalkovy** [comment]
Thanks. I agree with the ideas. Allowing to register a hub under an interface separate from hub feels nice. Also generated proxy would work well.
