### ISSUE TITLE
Unable to connect, No server available

### ISSUE THREAD

**Issue by DibranMulder** [aspnet/SignalR#2772]
As of a sudden my SignalR client written in JavaScript wasn't able to connect with the server anymore. This happend on dev, test, acceptance and prod. I wasn't able to pinpoint the problem and tried to restart my ASP.net core web app that connects with my Azure SignalR Service. That fixed the situation for now. However I'm anxious that this situation will occur again.
![signalr issue fixed](https://user-images.githubusercontent.com/5592416/43885185-71c65f5c-9bb8-11e8-90b7-490fe6249507.png)
Am I doing something wrong? Should I update to the latest versions? Did you guys update Azure Signal Service and broke existing connections? How should I prevent this kind of problems. Any help is appreciated. 

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages:
Microsoft.Azure.SignalR 1.0.0-preview1-10015
* Versions of Client-Side NuGet/NPM Packages:
@aspnet/signalr 1.0.0
* Are you using the C# client or the JavaScript client:
JavaScript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
Using an ASP.net core web app
```csharp
private static IWebHost BuildWebHost(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    var env = hostingContext.HostingEnvironment;
                    config.SetBasePath(env.ContentRootPath)
                            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                            .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true)
                            .AddEnvironmentVariables();
                })
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                    logging.AddConsole();
                    logging.AddAzureWebAppDiagnostics();
                    logging.AddDebug();
                    logging.AddApplicationInsights(
                        hostingContext.Configuration.GetSection("Logging"),
                        hostingContext.Configuration.GetSection("AppSettings")["InstrumentationKey"],
                        false,
                        "Allego.Cpm.RealtimeEvents.SignalR");
                })
                .UseKestrel()
                .UseStartup<Startup>()
                .UseIISIntegration()
                .Build();
        }

...

public void ConfigureServices(IServiceCollection services)
{
            string hostName = _configuration.GetSection("AppSettings")["SignalRHost"];
            string key = _configuration.GetSection("AppSettings")["SignalRKey"];
            services.AddSignalR().AddAzureSignalR($"Endpoint=https://{hostName};AccessKey={key};");
}
```
* The Operating System on the Server (Windows/Linux/macOS):
Azure Web App
* The Operating System on the Client (Windows/Linux/macOS):.
Windows 10
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
Both Chrome and Edge tested

**Comment by xscript** [comment]
@DibranMulder This looks like a bug in SignalR Service. I've created an issue at https://github.com/Azure/azure-signalr/issues/156 . Let's follow up at there.

Also, could you send your instance name to me? I want to check our backend logs.
You can send it to my email `kevinzha<at>microsoft.com` (replace `<at>` with `@`).

**Comment by DibranMulder** [comment]
You've got mail, thanks for the help.

**Comment by anurse** [comment]
I'm going to close this issue since the discussing is moving to the SignalR Service repository. Please feel free to comment further here if the investigations indicate an issue in SignalR!
