### ISSUE TITLE
Call connection.invoke() will return a 1007 from server sometimes on Linux

### ISSUE THREAD

**Issue by wangyi7099** [aspnet/SignalR#2795]
* Versions of Server-Side NuGet Packages: 
1.0.2
* Versions of Client-Side NuGet/NPM Packages:
 1.0.2
* Are you using the C# client or the JavaScript client: 
no
* The Operating System on the Server (Windows/Linux/macOS):
Linux
* The Operating System on the Client (Windows/Linux/macOS):
Linux
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
Chrome
 * AspNetCore:
 2.1.2

Work fine on Windows, but when I call connection.invoke()  on Linux, server will return a status of 1007 sometimes, not always. 

My client side code like so: 
```javascript
var connection = new signalR.HubConnectionBuilder()
      .withUrl("http://localhost:8089/MessageHint")
      .build();
   connection.on('ready', function() {
      connection.invoke("InitMessage", "88b4d7ad-de10-4af1-bbc2-35dcac4dced").catch(function(err) {
        console.error(err);
        if (opts.error) {
          opts.error(err);
        }
      });
    });
    
```

My server side code like so:
```c#
    public async Task InitMessage(string customerId)
        {
            Dictionary.Add(Context.ConnectionId, customerId);
            await Groups.AddToGroupAsync(Context.ConnectionId, customerId);
            await Clients.Caller.SendAsync("init", customerId);
        }
```
My Startup.cs
```c#
 public IServiceProvider ConfigureServices(IServiceCollection services) {
       services.AddSignalR();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
         app.UseSignalR(routes =>
            {
                routes.MapHub<PersistentMessageHint>("/MessageHint");
            });
            app.UseWebSockets();
}
```

![11111](https://user-images.githubusercontent.com/24426655/44025718-6f73c578-9f23-11e8-944a-8ed97feb635a.png)

**Comment by anurse** [comment]
Hrm, 1007 is "Invalid Payload Error" which usually indicates invalid UTF-8 data. Could you collect client and server-side logs as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)?

Also, if you can collect a network trace from the linux client machine that fails that would help as well. Please note that we need more detailed information here so the browser dev tools are not sufficient, you need to specifically use something like [tcpdump](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#tcpdump-macos-and-linux) to collect the trace.

**Comment by wangyi7099** [comment]
Sorry. My fault. It is a matter of logic problems , I initialized websocket twice on client silde, thanks for your explaination!

**Comment by anurse** [comment]
No problem, sometimes explaining the problem leads you to the solution 😄
