### ISSUE TITLE
Build failure on Ubuntu

### ISSUE THREAD

**Issue by pranavkm** [aspnet/SignalR#280]
/SignalR/client-ts/Microsoft.AspNetCore.SignalR.Test.Server/Microsoft.AspNetCore.SignalR.Test.Server.csproj(27,7): error MSB3030: Could not copy the file "/SignalR/client-ts/Microsoft.AspNetCore.SignalR.Test.Server/../dist/browser/signalr-client.js" because it was not found.

**Comment by pranavkm** [comment]
cc @moozzyk

**Comment by moozzyk** [comment]
The agent(s) had ancient versions of node and npm. After updating I was able to successfully build the project manually.

**Comment by moozzyk** [comment]
This is now fixed
