### ISSUE TITLE
Use JUnit 5 for the Java Client tests

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2802]
Should upgrade to use JUnit 5. This gives us a much cleaner way to assert exceptions and to create parameterized tests as well. Don't forget to get the new dependency approved.

**Comment by anurse** [comment]
Yep, this can wait until @Eilon is back. The usage would be internal-only with no distribution. We already use JUnit 4, but just want to update to the latest to a) stay on the latest bits and b) get access to some nice new features.

**Comment by anurse** [comment]
See if we can time-box this to a day. If it takes longer, just skip.

**Comment by Eilon** [comment]
Let me know package type (e.g. Maven?) and package ID, and I'll do the approval.

**Comment by anurse** [comment]
Apparently it's a series of package IDs since it was refactored in version 5 (kinda like xunit is now). @mikaelm12 When you've got the list of Maven groupID/artifactIDs we need to use, just add them here and ping Eilon.

**Comment by mikaelm12** [comment]
Yeah, depending on what exactly we need from JUnit 5,it'll be a couple of new dependencies instead of just 1 like with JUnit 4. I'll send you an email @Eilon when I make the PR for converting our tests. It's not the highest priority right now though.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/70ea1268a7236c3e5a2cab2a310088c10276e1e0
