### ISSUE TITLE
Support of Persistent Connection API

### ISSUE THREAD

**Issue by claudioesposito** [aspnet/SignalR#2812]
We are porting a SignalR .NET application to .NET Core. We cannot find in SignalR for .NET Core the implementation of the the Persistent Connection API, it seems only Hub are available. 
Any new or plan to implement it or alternative way to use "message based" model instead of more "RPC model" used by Hubs?

**Comment by moozzyk** [comment]
Check the HttpConnection class.

**Comment by davidfowl** [comment]
There’s no equivalent of PersistentConnections in the new model. The closest thing is a ConnectionHandler but it’s not message based, it’s just a stream of bytes. You need to implement a light protocol on top of that.

**Comment by anurse** [comment]
You can check out the [MessagesConnectionHandler](https://github.com/aspnet/SignalR/blob/release/2.2/samples/SignalRSamples/ConnectionHandlers/MessagesConnectionHandler.cs) in the SignalRSamples project for some guidance here. It's not a core scenario so we don't have documentation for it yet, but the sample should illustrate the general idea.

**Comment by claudioesposito** [comment]
OK Looks as a good starting point. Thanks for your quick support.
