### ISSUE TITLE
Update build to use `npm ci` to improve reliability

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/SignalR#2817]
https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

This is not yet available in Node 8.x (see https://github.com/nodejs/node/pull/21593).

**Comment by natemcmaster** [comment]
We have had continual problems with the reliability of `npm install` in VSTS builds. It would be nice to switch to something that is designed for CI environments.

**Comment by anurse** [comment]
We could install the latest npm as part of the build script, there's no need to be tied to the version that comes with Node.

**Comment by natemcmaster** [comment]
That would work too. 

Also, we've talked about using yarn instead. My experience with Yarn so far has been that it's fast and reliable and doesn't require a special ci mode.

**Comment by anurse** [comment]
Looks like `npm ci` is significantly faster than yarn according to the post you linked. I'm not too worried either way, but I do want the install of whatever tools we use to be simple and as automated as possible.

**Comment by BrennanConroy** [comment]
Blocked https://github.com/aspnet/SignalR/pull/2823#issuecomment-414841842

**Comment by anurse** [comment]
Blocked on moving everything to AzDO

**Comment by natemcmaster** [comment]
No longer blocked. TeamCity CI has NodeJS 10, as does AzDO.

**Comment by BrennanConroy** [comment]
Done in https://github.com/aspnet/AspNetCore/pull/4378
