### ISSUE TITLE
Implement keep-alive

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#282]
This will be at the SignalR level. A few design challenges:
- This is unneeded for long polling but SignalR doesn't know what the underlying transport is (it could sniff connection metadata)
- Do we treat it like a regular invocation message with a specific method name? Payload might be bigger than it would need to not conflict with existing Hub method names.
- Is it in both directions? In SignalR 2.0 we did server to client keep alives to stop proxies from killing the connection. We at least need to do that work but do we need client to server keep alives?
- How often is it sent?

**Comment by moozzyk** [comment]
The idea is that we introduce a new MessageType to the hub protocol for keep alive frames which will be treated the same as any other hub message by transports but SignalR will not raise OnRecevied events for these messages.

**Comment by anurse** [comment]
We have server-to-client keepalive now. We can call this done for now and see how it works in practice :)

**Comment by isaac873** [comment]
Hi @anurse, when you say it's done, is it available to use now?

**Comment by davidfowl** [comment]
It's in the myget feed.

**Comment by anurse** [comment]
See github.com/aspnet/Home#builds for guidance on how to use the nightly builds. They are unsupported and likely to have breaking changes though, so use at your own risk ;)
