### ISSUE TITLE
Class not found: "HubConnectionTest"Empty test suite.

### ISSUE THREAD

**Issue by aehyok** [aspnet/SignalR#2828]
Execute HubConnectionTest，please help me,thanks.

![image](https://user-images.githubusercontent.com/5900140/44252036-54848880-a22d-11e8-9c3e-5e8d7732f845.png)

**Comment by anurse** [comment]
cc @mikaelm12 Perhaps we need a short doc on how to build and test the Java Client.

FYI @aehyok the Java Client is in prototype form right now, and not ready for production use.

**Comment by mikaelm12** [comment]
> cc @mikaelm12 Perhaps we need a short doc on how to build and test the Java Client.

I'm writing something up for the preview1 blog post to get people started.

**Comment by mikaelm12** [comment]
@aehyok Is this a clean clone of the repo? Can you show your `build.gradle` file?

**Comment by mikaelm12** [comment]
It seems like it's most likely your java plugin not being up to date or not refreshing.
This StackOverflow post has a bunch of potential solutions - https://stackoverflow.com/questions/39282282/class-not-found-empty-test-suite-in-intellij

**Comment by aehyok** [comment]
My build.gradle is  this  'https://github.com/aspnet/SignalR' source code，no changes were made. 
Is there any problem with my environment?But my other project is no problem。 @mikaelm12 
I'm looking forward to the preview1 blog,thank you very much!!!

**Comment by mikaelm12** [comment]
Hi @aehyok, just wanted to follow up. Have you tried the newest releases of the Java client/seen the blog posts?

**Comment by mikaelm12** [comment]
Closing this as we haven't heard from you in a little while. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
