### ISSUE TITLE
SignalR on Docker - Connection ID required

### ISSUE THREAD

**Issue by mylifelineio** [aspnet/SignalR#2829]
Application works well without Docker, getting Connection ID required error when I browse to the hub. 

Is there perhaps a step-by-step guide on what configuration is required to setup Docker to work with SignalR including Redis. 

* Versions of Server-Side NuGet Packages:
Core 2.1.2

* Are you using the C# client or the JavaScript client:
Javascript

* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
Reverse Nginx proxy to kestrel

* The Operating System on the Server (Windows/Linux/macOS):
Ubuntu 16.04

* The Operating System on the Client (Windows/Linux/macOS):
Windows

* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
Chrome

**Comment by anurse** [comment]
If you use a browser you should get the "Connection ID required" error. You need to use the JavaScript or C# client library to connect. Are you seeing an error?

**Comment by mylifelineio** [comment]
Thanks Andrew for the help.

My error:

> Utils.ts:165 Information: Normalizing '/monitorhub' to 'https://myurl/monitorhub'.
> WebSocketTransport.ts:38 WebSocket connection to 'wss://myurl/monitorhub?id=RBJvk_uTZFlA5rGY4yIbBA' failed: Error during WebSocket handshake: Unexpected response code: 200
> (anonymous) @ WebSocketTransport.ts:38
> (anonymous) @ WebSocketTransport.ts:36
> step @ tslib.es6.js:91
> (anonymous) @ tslib.es6.js:72
> fulfilled @ tslib.es6.js:62
> Utils.ts:159 Error: Failed to start the transport 'WebSockets': undefined
> 

Let me give Redis a try. Is there any need to follow this Docker websockets article https://docs.docker.com/ee/ucp/interlock/usage/websockets/

Do I need to define wss somewhere in my Docker compose?

**Comment by anurse** [comment]
> Error during WebSocket handshake: Unexpected response code: 200

You mentioned you're using Nginx. Have you [configured Nginx to forward WebSockets](https://www.nginx.com/blog/websocket-nginx/)? By default, it won't properly forward them and will simply terminate the connection

> Do I need to define wss somewhere in my Docker compose?

No, that's just how the browser formats the URL when connecting to WebSockets. The actual request is a standard HTTPS request.

**Comment by mylifelineio** [comment]
Followed that Nginx article and ensured http_upgrade and alive was set but still getting the same errors

> proxy_http_version 1.1;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection keep-alive;
> proxy_set_header Host $host;
> proxy_cache_bypass $http_upgrade;

More logs:

> app    | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
> app   |       => ConnectionId:0HLG5261D7J31 => RequestId:0HLG5261D7J31:00000001 RequestPath:/monitorhub
> app    |       Request finished in 5274.1932ms 200 text/event-stream
> app    | fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]
> app    |       => ConnectionId:0HLG5261D7J2V => RequestId:0HLG5261D7J2V:00000001 RequestPath:/monitorhub => TransportConnectionId:QNGpX42F_xLPplldBjuVrg
> app    |       Failed connection handshake.

**Comment by mylifelineio** [comment]
This needs to be 

proxy_set_header Connection "upgrade";

Thanks for the help Andrew
