### ISSUE TITLE
Generate test report file for jest

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/SignalR#2830]
I'm not a JS test expert here, but it appears from a little googling that jest/jasmine can produce a jUnit test result file. Would be good to enable this so we can publish test results to VSTS. It makes it easier to see test failures (as opposed to console output) and also lets us track test history across many runs.. 

https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-test-results

**Comment by anurse** [comment]
Sounds good!
