### ISSUE TITLE
Test failure: SSEWontStartIfSuccessfulConnectionIsNotEstablished

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2832]
This test [fails](http://aspnetci/viewLog.html?buildId=534598&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
System.TimeoutException : Operation in WithConnectionAsync timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Helpers.cs:69
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__2.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.Tests.HttpConnectionTests.<WithConnectionAsync>d__9.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Helpers.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.Tests.HttpConnectionTests.ConnectionLifecycle.<SSEWontStartIfSuccessfulConnectionIsNotEstablished>d__11.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.ConnectionLifecycle.cs:line 346
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test SSEWontStartIfSuccessfulConnectionIsNotEstablished at 2018-08-18T02:20:36
| [0.015s] TestLifetime Information: Starting test SSEWontStartIfSuccessfulConnectionIsNotEstablished at 2018-08-18T02:20:36
| [10.026s] TestLifetime Information: Finished test SSEWontStartIfSuccessfulConnectionIsNotEstablished in 9.9462568s
| [10.031s] TestLifetime Information: Finished test SSEWontStartIfSuccessfulConnectionIsNotEstablished in 9.9655565s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
SSEWontStartIfSuccessfulConnectionIsNotEstablished [failed with about the same error](http://aspnetci/viewLog.html?buildId=535249&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
SSEWontStartIfSuccessfulConnectionIsNotEstablished [failed with about the same error](http://aspnetci/viewLog.html?buildId=537779&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment]
@BrennanConroy did the added logs help with this failure?

**Comment by BrennanConroy** [comment]
A little

**Comment by muratg** [comment]
What's next then?

**Comment by BrennanConroy** [comment]
More investigating, we think we've narrowed it down to either a bug in rethrowing an exception (very unlikely as that should break a lot of people), or a lock in logging that could be timing out the test.

**Comment by BrennanConroy** [comment]
We've narrowed it down and can repro after a few test runs locally. Still investigating.

**Comment by anurse** [comment]
This is caused by https://github.com/dotnet/coreclr/issues/19698 (.NET Core) / https://devdiv.visualstudio.com/DevDiv/_workitems/edit/672340 (.NET Framework)

**Comment by anurse** [comment]
@BrennanConroy is going to disable logging for these tests and file an issue in the 3.0 milestone to restore it (which is where the CLR bug is scheduled to be fixed). When logging is disabled I think this issue can be closed.

**Comment by BrennanConroy** [comment]
Fixed https://github.com/aspnet/SignalR/pull/2880
