### ISSUE TITLE
How-to: Verify if ConnectionId is still valid

### ISSUE THREAD

**Issue by cnlogistics** [aspnet/SignalR#2833]
Most of my customers connect to my SignalR service from within a Web Browser.
As you know a customer often closes the browser window without logout.
So I have little chance to gracefully logout and remove it's current ConnectionId.
I have to say I store customer with it's connectionId in my Sql database.

Is the [OnDisconnected](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1#handle-events-for-a-connection) event the right place for me to remove the user with it's current connectionId from my signalr usersession database table?

**Comment by blahblehblah** [comment]
> Is the OnDisconnected event the right place for me to remove the user with it's current connectionId from my signalr usersession database table

Yes
