### ISSUE TITLE
Failed to find handler for 'broadcastMessage' method

### ISSUE THREAD

**Issue by ericbrunner** [aspnet/SignalR#2834]
In my .NET Core 2.1 Azure Function I use the SignalR .Net Core Client v.1.0.2. I turned on full debug logging and for the first time I saw that:

![image](https://user-images.githubusercontent.com/6480047/44296330-4aaa6600-a2bd-11e8-825f-17e6b5079560.png)

Captured logs from Localhost Console UI are attached
[azure-func-signalr-localhost.log](https://github.com/aspnet/SignalR/files/2299183/azure-func-signalr-localhost.log)

Azure Function: [NotifySignalrUser](https://gist.github.com/cnlogistics/f631c20d8feb4daa0f1f69edc8a17644)
Signalr Hub: [TruckerWebAppHub](https://gist.github.com/ericbrunner/1b1b75d8593dca416ccfa6a975e26d9f)

**Comment by BrennanConroy** [comment]
You don't have "broadcastMessage" registered on your `HubConnection`.

See the docs for client methods https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1#call-client-methods-from-hub

**Comment by ericbrunner** [comment]
I only invoke the "broadcastMessage" method n the Hub

`Clients.Client(receiverConnectionId).SendAsync("broadcastMessage", senderName, message);`

In the Azure Function there is no registered "broadcastMessage" handler.

**Comment by ericbrunner** [comment]
You are correct. Currently while started the Hub and Function on localhost I had no registered clients that where connected to "broadcastMessage". I guess that is what that error message is all about.
