### ISSUE TITLE
Test failure: SSETransportStopsWithErrorIfSendingMessageFails

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2835]
This test [fails](http://aspnetci/viewLog.html?buildId=535030&buildTypeId=XPlat_Windows_Win7_Universe) occasionally with the following error:
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   typeof(System.TimeoutException): Operation in SSETransportStopsWithErrorIfSendingMessageFails timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs:211
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [0.000s] TestLifetime Information: Starting test SSETransportStopsWithErrorIfSendingMessageFails at 2018-08-19T08:21:48
| [0.009s] TestLifetime Information: Starting test SSETransportStopsWithErrorIfSendingMessageFails at 2018-08-19T08:21:48
| [0.010s] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Information: Starting transport. Transfer mode: Text.
| [4.979s] TestLifetime Information: Finished test SSETransportStopsWithErrorIfSendingMessageFails in 4.8914184s
| [4.991s] TestLifetime Information: Finished test SSETransportStopsWithErrorIfSendingMessageFails in 4.9097814s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
SSETransportStopsWithErrorIfSendingMessageFails [failed with about the same error](http://aspnetci/viewLog.html?buildId=536734&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment]
@anurse could you take a look/reroute?

**Comment by anurse** [comment]
@BrennanConroy is investigating but so far hasn't had much luck.

**Comment by aspnet-hello** [comment]
SSETransportStopsWithErrorIfSendingMessageFails [failed with about the same error](http://aspnetci/viewLog.html?buildId=537530&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
SSETransportStopsWithErrorIfSendingMessageFails [failed with about the same error](http://aspnetci/viewLog.html?buildId=538895&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by anurse** [comment]
We've now identified that both this test failure and https://github.com/aspnet/SignalR/issues/2832#issuecomment-415905393 seem to be caused by an `AccessViolationException` in `Exception.ToString()` called when logging. This **is** occurring in product code but we're not yet sure the root cause. CLR team is engaged.

**Comment by anurse** [comment]
This is caused by https://github.com/dotnet/coreclr/issues/19698 (.NET Core) / https://devdiv.visualstudio.com/DevDiv/_workitems/edit/672340 (.NET Framework)

**Comment by anurse** [comment]
@BrennanConroy is going to disable logging for these tests and file an issue in the 3.0 milestone to restore it (which is where the CLR bug is scheduled to be fixed). When logging is disabled I think this issue can be closed.

**Comment by BrennanConroy** [comment]
Fixed https://github.com/aspnet/SignalR/pull/2880
