### ISSUE TITLE
.NET Core 2.1 SignalR reconnect from .NET Client 1.0.2 Closed not called

### ISSUE THREAD

**Issue by radenkozec** [aspnet/SignalR#2845]
I am using .NET Client for SignalR 1.0.2.
I am trying to automatically reconnect when I lost connection to server.
My Connection closed method is never called even if I shutdown server completely.
The code is like this:

```
 private async Task<bool> OpenSignalRConnection()
        {
            Log.Information("Creating SignalR connection");
            SignalRConnection = new HubConnectionBuilder()
           .WithUrl(BaseUrl + "/hubs/integrationserver", options =>
           {
                options.Headers.Add("Authorization", "Basic " + Header);
           })
           .Build();

            SignalRConnection.On<string, string>("ReceiveMessage", (entityName, json) =>
            {
                var intSrvArgs = new IntSrvEventArgs
                {
                    EntityName = entityName,
                    Json = json
                };
                _entityAddedUpdated?.Invoke(this, intSrvArgs);

            });

            await SignalRConnection.StartAsync();
           // **here I am subscribing to Closed event**
            SignalRConnection.Closed += SignalRConnection_Closed;
            return true;
        }
```
And then code for closed:
```
 private async Task SignalRConnection_Closed(Exception arg)
        {
            Log.Information("Connection is closed");
            await SignalRConnection.StopAsync();
            await SignalRConnection.DisposeAsync();
            TimeSpan retryDuration = TimeSpan.FromSeconds(30);
            DateTime retryTill = DateTime.UtcNow.Add(retryDuration);

            while (DateTime.UtcNow < retryTill)
            {
                bool connected = await OpenSignalRConnection();
                if (connected)
                {
                    Log.Information("Connection Re-Created");
                    return;
                }
            }
        }

```
Connection Closed is never called.
Does someone have a example of proper way to reconnect from C# Client?

**Comment by anurse** [comment]
Can you collect client and server logs as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)? In particular, the logs from around the time you shut down the server would be best.

Also please include the following information as requested by the Issue Template:

* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
* The Operating System on the Server (Windows/Linux/macOS):
* The Operating System on the Client (Windows/Linux/macOS):

**Comment by radenkozec** [comment]
The Server: IIS 8
Operating system on server: Windows Server 2016
Operating system on client: Windows 10

Can you point us to the article what is the proper way to implement reconnect from C# client?
It seams that this is impossible to do in this version of SignalR?

**Comment by anurse** [comment]
There's no article at the moment (see https://github.com/aspnet/Docs/issues/6757). There's a sample in JavaScript available here: https://github.com/davidfowl/UT3/blob/dac409886c1bb7aec7c150b74d4ce9a3e246f03c/UTT/wwwroot/js/utt.js#L141-L153

Your logic is mostly correct, however, you should not call `DisposeAsync` until you are completely finished with the connection and **do not intend to reconnect**. Just calling `StopAsync` is sufficient to clean up per-connection resources.

**Comment by radenkozec** [comment]
@anurse I managed to implement my own version which works correctly on .NET Client.
I wrote a blog post about it https://www.radenkozec.com/net-core-signalr-automatic-reconnects/
so if someone has a similar problem it can check out the code in the blog post.
Thanks.

**Comment by BrennanConroy** [comment]
The `HubConnection` is reusable so your implementation isn't quite the recommended way. If you take a look at the link @anurse provided you'll see the `HubConnection` is created once for the client and any callbacks (`.on`, `close`, etc.) are applied once so you don't have to keep re-registering for callbacks.

The link is for the TS client, but the implementation should behavior very similarly to the .NET client.

**Comment by radenkozec** [comment]
@BrennanConroy Thanks for feedback. I will improve my code to re-use HubConnection.
