### ISSUE TITLE
Triger SignalR Core server method at specific time

### ISSUE THREAD

**Issue by Narutofox** [aspnet/SignalR#2852]
I posted this on StackOverflow but so far no answer so I am hoping to get some kind of answer here.
I am trying to create a scheduled action for signalR hub server method. In ASP.NET I used this
```
public class ChatTestsHub : Hub
{
   private static List<ChatTestData> chatTestData = new List<ChatTestData>();
   public static List<ChatTestData> Data { get => chatTestData; set => chatTestData = value; }
     public void JoinChat()
        {
           ScheduleAction(() => StartTest(""), DateTime.Now.AddHours(1));
        }

        public void StartTest(string group)
        {
            if (Data.Any(x => x.GroupName == group) && ConnectedUsers.Any(x => x.Groups.Contains(group)) && !Data.Find(x => x.GroupName == group).QuestionStart.HasValue)
            {
                ChatTestData current = Data.Find(x => x.GroupName == group);
                Clients.Group(group).beginTest("Welcome to " + current.ChatTest.TestName, group);
                Clients.Group(group).questionMessage(current.CurrentQuestion.QuestionOrder + ". " current.CurrentQuestion.QuestionText, group);
                Clients.Group(group).allowChat(group);
            }
        }

    private async System.Threading.Tasks.Task<object> ScheduleAction(Action action, DateTime ExecutionTime)
    {
        var t = System.Threading.Tasks.Task.Run(
                async () =>
            {
                await       System.Threading.Tasks.Task.Delay((int)ExecutionTime.Subtract(DateTime.Now).TotalMilliseconds);                                
                action();
            });
        return t;
    }  
}
```

Probably not the best solution but it worked. I would pass Hub method as action as well as DateTime on when to trigger the action. Now in ASP.NET Core I get error that says I can not access object that has been disposed. I need a way to trigger a Hub server method at specific time.

Thank you

**Comment by anurse** [comment]
Can you provide a full example that we can run to reproduce the problem? The snippet you posted doesn't seem to be your Hub method, so I'm not sure how it's being called or what you are accessing from the `action` delegate. The Hub class is disposed when the Hub method returns so if you try to access things on it (such as the `Context` or `Clients` properties) from a background thread you'll get this error. You should use [`IHubContext<T>`](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1) to send messages to the Hub from background processes instead.

**Comment by BrennanConroy** [comment]
Abstract your hub method out and call the method from your hub and your scheduler.

The scheduler will need to get the `IHubContext<YourHub>` via DI and use it for sending messages and your Hub method will have access to the `Context` and `Clients` properties for sending messages.

**Comment by Narutofox** [comment]
I updated the question. If I understand correctly with IHubContext<YourHub> I can now send messages to clients. But what I want is to call Hub method on server at specific time that will then do its thing among others call needed client side methods. By looking through instance IHubContext<YourHub> I don't see any way to do this.
Thank you

**Comment by BrennanConroy** [comment]
You **cannot** call a hub method manually.
Refactor your code so the hub method logic is in a shared location that your hub and scheduler can call.

```c#
public ExampleHub : Hub
{
    public async Task GenericHubMethod()
    {
        var result = await Service.DoSomeStuff();
        await Clients.All.SendAsync("ClientMethod", result);
    }
}

public class Service
{
    public static async string DoSomeStuff()
    {
        return await SomeDatabaseCallThatReturnsAString();
    }
}
```

**Comment by Narutofox** [comment]
Okay that's what I wanted to know.
Thank you for your help
