### ISSUE TITLE
Specify that this TypeScript client does not work for ASP.NET SignalR

### ISSUE THREAD

**Issue by kylenoteboom** [aspnet/SignalR#2853]
The ASP.NET SignalR repository mentions it not being compatible with ASP.NET Core SignalR: https://github.com/SignalR/SignalR

This repository, for ASP.NET SignalR Core, does not mention the reverse, which I have found somewhat confusing.

Please put a similar warning at the top of the README.md so others won't have to waste their time trying out this version when they need the other one.

**Comment by anurse** [comment]
Good catch! We just added that note to the SignalR/SignalR readme, so I'll add it now. Also moving forward we're working to have the product itself emit useful errors when you try to cross the streams (see https://github.com/aspnet/SignalR/issues/2728 and https://github.com/SignalR/SignalR/issues/4160).

I'll update the readme now!
