### ISSUE TITLE
Send message to SignalR Client with confirmation

### ISSUE THREAD

**Issue by radenkozec** [aspnet/SignalR#2855]
* The Operating System on the Server (Windows/Linux/macOS): Windows 2016
* The Operating System on the Client (Windows/Linux/macOS): Windows 10

I have injected IHubContext<IntegrationServerHub> hubcontext in my class.
After that I try to send message to specific client:
 Log.Information("Starting sending message");
 await _hubcontext.Clients.User(username).SendAsync("ReceiveMessage", entityName, json);
Log.Information("Passed even message not send and exception not fired");

Client is not connected and I try to send message and nothing happens. Exception is not thrown and I don't know if message is send to client successfully or not.

Not sure how to send message to specific client and get confirmation that message is received?

**Comment by radenkozec** [comment]
Hm I now see that SingalR don't guarantee message delivery. I will close this issue.

**Comment by anurse** [comment]
Yeah, guaranteed delivery is a very difficult thing to achieve in general and ASP.NET Core SignalR doesn't provide that functionality by default. There has been some interest in building extensions that do this, but we don't have anything built-in right now.
