### ISSUE TITLE
When using MessagePack Protocol, client never receives messages

### ISSUE THREAD

**Issue by kspearrin** [aspnet/SignalR#2857]
* Versions of Server-Side NuGet Packages: 2.1.2, 1.0.3 (msg pack)
* Versions of Client-Side NuGet/NPM Packages: 1.0.2, 1.0.3 (msg pack)
* Are you using the C# client or the JavaScript client: Javascript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Local IIS Express from VS 2017
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome

Server:

```
services.AddSignalR().AddMessagePackProtocol();
```

```
app.UseSignalR(routes => routes.MapHub<NotificationsHub>("/hub");
```

Client (Angular website in TypeScript):

    import * as signalR from '@aspnet/signalr';
    import * as signalRMsgPack from '@aspnet/signalr-protocol-msgpack';

    ...

        this.signalrConnection = new signalR.HubConnectionBuilder()
            .withUrl(this.url + '/hub', {
                accessTokenFactory: () => this.getToken(),
            })
            .withHubProtocol(new signalRMsgPack.MessagePackHubProtocol())
            .configureLogging(signalR.LogLevel.Trace)
            .build();

        this.signalrConnection.on('ReceiveMessage', (data: any) => {
            console.log(data);
        });

When using the Msg Pack protocol, my clients never receive the messages from the server.

Server log shows:

```
Microsoft.AspNetCore.SignalR.HubConnectionContext:Information: Completed connection handshake. Using HubProtocol 'messagepack'.
```

Client log shows:

```
... connected ...

Debug: Server handshake complete.
Trace: (WebSockets transport) data received. Binary data of length 3. // <== Pings?, repeated
```

I don't see any errors in the console.

Everything works fine if I comment out the `.withHubProtocol(new signalRMsgPack.MessagePackHubProtocol())` line and it uses the JSON protocol. Messages are received.

Server log shows:

```
Microsoft.AspNetCore.SignalR.HubConnectionContext:Information: Completed connection handshake. Using HubProtocol 'json'.
```

Client log shows:

```
... connected ...

Debug: Server handshake complete.
Trace: (WebSockets transport) data received. String data of length 11. // <== Ping?
Trace: (WebSockets transport) data received. String data of length 263. // <== My message
Trace: (WebSockets transport) data received. String data of length 11. // <== Pings?, repeated
```

Any idea what is going on here?

**Comment by kspearrin** [comment]
I set log level on the server to verbose and set `.AddSignalR(c => c.EnableDetailedErrors = true)`, but nothing new showed up.

Here is an example message coming into the JSON protocol `parseMessages` function:

```
"{"type":1,"target":"ReceiveMessage","arguments":[{"type":0,"payload":{"Id":"04e4706d-7f57-427d-ac9b-a93e00ce3014","UserId":"ab6fe7ee-0311-4795-aaa9-a6530051eea0","RevisionDate":"2018-08-23T21:29:28.5294727Z"},"contextId":"b5f6083d-2eca-4f24-9f01-39f1b0c75c56"}]}"
```

**Comment by BrennanConroy** [comment]
Getting the logs would be very helpful, there must be something missing like a config value. Take a look at our guide and see if there is anything helpful https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#locally-using-iis-express 

Are you passing a JObject/JArray as an argument?

**Comment by kspearrin** [comment]
Not `JObject`, but I was using `PushNotificationData<object>` . Turns out that silently breaks things. Switched from `object` to a proper type and now the message arrives. Thanks for the tip.

**Comment by BrennanConroy** [comment]
Silently broke things in SignalR or your code? If in SignalR we'd love to know how we can make it not silent.

**Comment by kspearrin** [comment]
@BrennanConroy I assume in SignalR. I did not get any type of error message on the server and things continued on like it sent the message, when for whatever reason it did not.

**Comment by kspearrin** [comment]
@BrennanConroy 

The code for this project is all open source. See here:

https://github.com/bitwarden/core/tree/master/src/Notifications
https://github.com/bitwarden/core/blob/master/src/Notifications/NotificationsHub.cs
https://github.com/bitwarden/core/blob/master/src/Notifications/AzureQueueHostedService.cs#L74
https://github.com/bitwarden/core/blob/master/src/Notifications/HubHelpers.cs#L26

Though it is not fixed not to use `<object>` anymore. Fix was here:
https://github.com/bitwarden/core/commit/68c349f72fb2a81fb232484dcc504f1c1d7103d2#diff-8037e8c57f01609139049fe9a3192322

This was the sample data from a message I observed working with JSON, but not with MsgPack when I was using `<T>` as `object`:

```
{"type":0,"payload":{"Id":"04e4706d-7f57-427d-ac9b-a93e00ce3014","UserId":"ab6fe7ee-0311-4795-aaa9-a6530051eea0","RevisionDate":"2018-08-23T21:29:28.5294727Z"},"contextId":"b5f6083d-2eca-4f24-9f01-39f1b0c75c56"}
```

**Comment by BrennanConroy** [comment]
Could you explain the simplest way to repro the issue with your project. I don't see any reference to a SignalR Client and do I just create an HTTP POST with fiddler using the sample data you posted above?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
