### ISSUE TITLE
SignalR Client should preserve query string when getting a redirect negotiation reponse

### ISSUE THREAD

**Issue by xscript** [aspnet/SignalR#2859]
Right now, when client getting a redirect response (with `url` and `accessToken` properties), the returned URL will be used and query string in the original request URL is abandoned, see [JavaScript client](https://github.com/aspnet/SignalR/blob/release/2.2/clients/ts/signalr/src/HttpConnection.ts#L153-L155) and [C# client](https://github.com/aspnet/SignalR/blob/release/2.2/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs#L318-L321).
Per offline talk with @davidfowl , SignalR client should preserve the original query strings.

**Comment by BrennanConroy** [comment]
We may want to consider taking this in a 2.1.X patch too.

**Comment by anurse** [comment]
I think this would be a breaking change though, and might cause unintentional information disclosure. Need to talk with @davidfowl about this.

**Comment by BrennanConroy** [comment]
We might punt this because of https://github.com/Azure/azure-signalr/pull/184

**Comment by anurse** [comment]
If that's the way this is being resolved, then yeah, we don't need to make a change here. Depends on if @davidfowl still believes this to be a bug in general

**Comment by BrennanConroy** [comment]
@davidfowl Thoughts?
