### ISSUE TITLE
[Question] How to emulate different connection bandwidth between Client and Server while developing with SignalR?

### ISSUE THREAD

**Issue by MelnikovIG** [aspnet/SignalR#2860]
What is the best practice during development for emulating connection bandwidth between Client and Server on single Windows machine? Any tips how you are doing this?

**Comment by anurse** [comment]
> emulating connection bandwidth

What do you mean here? Do you mean simulating low-bandwidth connections? We don't have tests that do this at this time. There are tools out there for doing network bandwidth simulation but they aren't specific to SignalR.

**Comment by MelnikovIG** [comment]
I agree it is not relative to SignalR, but maybe someone got same troubles testing connections stability. In my case helped using NetLimiter and virtual machines. Closing.
