### ISSUE TITLE
NullReferenceException in HttpConnectionManager if application has already been started

### ISSUE THREAD

**Issue by creativbox** [aspnet/SignalR#2875]
When using SignalR in a modular application like OrchardCore, the HttpConnectionManager will throw a NRE in Start() because the application has already been started (i.e. IApplicationLifeTime.ApplicationStarted is already signaled and _nextHeartbeat gets set too late). 

Microsoft.AspNetCore.SignalR version 1.0.3
https://github.com/OrchardCMS/OrchardCore/issues/2268

**Comment by BrennanConroy** [comment]
Fixed in https://github.com/aspnet/SignalR/pull/2878
