### ISSUE TITLE
LongPolling and SSE not Supported In Redis Scaleout

### ISSUE THREAD

**Issue by cgyqu** [aspnet/SignalR#2884]
We have two signalr servers after tengine.

When test LongPolling and SSE transport,I found the signalr was not working properly and return **No Connection with that ID** .And If the WebSocket transport not set `skipNegotiation = true`,signalr return **No Connection with that ID** too.

So I look at the code,and find this
```C#
private async Task<HttpConnectionContext> GetConnectionAsync(HttpContext context)
{
    var connectionId = GetConnectionId(context);

    if (StringValues.IsNullOrEmpty(connectionId))
    {
        // There's no connection ID: bad request
        context.Response.StatusCode = StatusCodes.Status400BadRequest;
        context.Response.ContentType = "text/plain";
        await context.Response.WriteAsync("Connection ID required");
        return null;
    }

    if (!_manager.TryGetConnection(connectionId, out var connection))
    {
        // No connection with that ID: Not Found
        context.Response.StatusCode = StatusCodes.Status404NotFound;
        context.Response.ContentType = "text/plain";
        await context.Response.WriteAsync("No Connection with that ID");
        return null;
    }

    return connection;
}
```
This means that the connectionid is only stored on one server and is not Shared across multiple servers.
Is that the reason？Any plan to fix this?

**Comment by davidfowl** [comment]
It's not a bug it's by design. ASP.NET Core SignalR requires sticky sessions when using scale out. This means you need to pin a connection to a particular server.

**Comment by cgyqu** [comment]
@davidfowl，do that means only one server can be deployed if I use longponging transport?

Our scenario is to use signalr on WeChat miniapp.Some lower versions of the app do not support websocket,sse also not supported, so only longpolling can be used.And Stability is not guaranteed if only one server is deployed.

Why not use the same design as the .net fromwork version？

**Comment by davidfowl** [comment]
> @davidfowl，do that means only one server can be deployed if I use longponging transport?

No, it means you need to configure your load balancer to pin connections to particular servers.

> Why not use the same design as the .net fromwork version？

Because it has scalability *and* reliability issues.
