### ISSUE TITLE
unable to initialize any of the available transports

### ISSUE THREAD

**Issue by seven1986** [aspnet/SignalR#2885]
《IphoneX safari》, 《IphoneX wechat》 will throw error “**unable to initialize any of the available transports**”

![image](https://user-images.githubusercontent.com/20808494/44780765-4a5f7400-abb5-11e8-9706-bb90f2bf6a1e.png)

### have a try for this game, please help me, thanks a lot!
https://games.ixingban.com/guessing/index.html

《Android all is OK》

**Comment by anurse** [comment]
Can you collect client-side logs as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)? That should show more detail about the error underlying that issue.

**Comment by anurse** [comment]
You haven't provided the client-side logs though, I understand what error you're seeing, but I need the logs in order to understand why the error is ocurring. The JavaScript client can produce logs to the browser console (see instructions [here](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#javascript-client-logging)). I'm not sure how WeChat exposes the browser console but I expect they have a way.

**Comment by seven1986** [comment]
System: windows10

![image](https://user-images.githubusercontent.com/20808494/45020809-8cc7fb80-b062-11e8-8dce-04a1dd22b99a.png)

![image](https://user-images.githubusercontent.com/20808494/45020758-6a35e280-b062-11e8-904e-b797fd32d742.png)

**Comment by anurse** [comment]
Are you able to connect to the server from outside the WeChat environment? It looks like the WeChat environment doesn't fully support SignalR, you'd have to follow up with WeChat support about their support for WebSockets and Server-Sent Events.

You can also try falling back to Long Polling, which should work in almost all environments. You can do that by specifying the allowed transports in the `.withUrl` call:

```javascript
let connection = new signalR.HubConnectionBuilder()
    .withUrl("/myhub", { transport: signalR.HttpTransportType.LongPolling })
    .build();
```

See the [Configuration docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-allowed-transports) for more information.

**Comment by seven1986** [comment]
I can't connect to server only **safari(whatever windows or MAC)**, they other all OK.

**Comment by seven1986** [comment]
@anurse After we tried, we may found the reson which the issues I comment here.
There are 8 people in 1 group in drawinghub. One drawing, they onthers sync.
Drawer will send base64 img data(around 30KB) to they others during each mousemove event.
It will can't connect after send too many img data. how to optimize server？
