### ISSUE TITLE
Test failure: CanSendAndReceiveUserMessagesWhenOneConnectionWithUserDisconnects

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/SignalR#2895]
This test [fails](http://aspnetci/viewLog.html?buildId=542609&buildTypeId=Releases_21Public_UbuntuUniverse) occasionally with the following error:
```
[Test Collection Cleanup Failure (RedisEndToEndTestsCollection)]: System.Exception : Command '/usr/bin/docker stop redisTestContainer' failed with exit code '1'. Output:
Error response from daemon: No such container: redisTestContainer
   at Microsoft.AspNetCore.SignalR.Redis.Tests.Docker.RunProcessAndThrowIfFailed(String fileName, String arguments, ILogger logger, TimeSpan timeout) in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/Docker.cs:line 90
   at Microsoft.AspNetCore.SignalR.Redis.Tests.Docker.Stop(ILogger logger) in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/Docker.cs:line 74
   at Microsoft.AspNetCore.SignalR.Redis.Tests.RedisServerFixture`1.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisServerFixture.cs:line 60
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.1.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
HubConnectionCanSendAndReceiveMessages [failed with about the same error](http://aspnetci/viewLog.html?buildId=542609&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by BrennanConroy** [comment]
This was the first time running on a new agent which caused the redis docker container to attempt a full build without any cache. Now that it's downloaded the image once the container is created much faster and won't hit the 20 second timeout. I'm going to close this issue.
