### ISSUE TITLE
[ts-client] get AccessTokenFactory not being called on each request? 

### ISSUE THREAD

**Issue by blahblehblah** [aspnet/SignalR#2896]
I will need to rebuild the connection in order for it to get the capture the new token

**Comment by anurse** [comment]
It should be called for each request. Can you provide a code sample that reproduces the problem when run?

**Comment by blahblehblah** [comment]
Same as the sample,
`    this._hubConnection = new signalR.HubConnectionBuilder()
      .withUrl("https://localhost:44370/hubs/main", {
        accessTokenFactory: () => this.authenticationProvider.getToken()
      })
      .configureLogging(signalR.LogLevel.Trace)
      .build();`

 try having an extra button to generate a new bearer token with different claims for testing and save it, when calling API you will get the new token, however calling a hub will still use the old token

**Comment by davidfowl** [comment]
It's probably being called for each request but websockets makes a single request. Is that what you're running into?

**Comment by blahblehblah** [comment]
exactly, thats about it, any solution? or should i always recreate the connection incase of websockets

**Comment by davidfowl** [comment]
Here’s the issue tracking this. We have no built in feature for this but he sample code in the isssu may help 
https://github.com/aspnet/SignalR/issues/1159

**Comment by blahblehblah** [comment]
Will look into it, thank you

**Comment by anurse** [comment]
Closing this as the factory is behaving as designed. This is just an issue with how the token expiry is handled which is being discussed in #1159.
