### ISSUE TITLE
Xamarin.Android regression?

### ISSUE THREAD

**Issue by freever** [aspnet/SignalR#2899]
Has there been a regression on #1886 ? iOS is still OK but my Xamarin.Android app has suddenly started throwing out the same old errors:

> Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `System.IO.Pipelines`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `System.IO.Pipelines`

> Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `Microsoft.AspNetCore.SignalR.Client.Core`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `Microsoft.AspNetCore.SignalR.Client.Core`.

> Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `System.Threading.Channels`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `System.Threading.Channels`.	

> Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `Microsoft.AspNetCore.Http.Connections.Client`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `Microsoft.AspNetCore.Http.Connections.Client`.		

I am on he latest versions of everything:

- SignalR.Client 1.0.3
- VS 15.9.0 Preview 1.0 (Xamarin.Android 9.1.0.12)
- VS Mac 7.8 Preview (Xamarin.Android 9.1.0.12)

My build server is running a few versions behind and does not have the same build error:
- VS Mac 7.6 (Xamarin.Android 9.0.0)

Locally I am running the latest betas so I might be the canary in the coal mine?

**Comment by KSemenenko** [comment]
Try to remove the app.config from the project. It helped me for Xamarin.iOS and Xamarin.Andoird

**Comment by freever** [comment]
Turns out it isn't related to the Xamarin.Android version as reverting to stable channel makes no difference. I am able to build in Release mode, just not in Debug. So I dunno.
