### ISSUE TITLE
Consider sharing a Redis connection between all hubs

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2900]
Currently we create the Redis connection in `RedisHubLifetimeManager<THub>` which means there is a connection per Hub. This is likely not necessary, and we can probably look at sharing the connection between all Hubs. We should consider sharing the connection.

**Comment by cgyqu** [comment]
Glad to see this improvement

**Comment by juepiezhongren** [comment]
for different hubs to connect client, could or do they share a single ws-connection?

**Comment by anurse** [comment]
@juepiezhongren No, each Hub uses a separate WebSocket connection. That's not related to this discussion though, as we're just talking about sharing a single Redis connection from the server to the Redis backplane.

**Comment by cgyqu** [comment]
@anurse ,I haven't tested the performance.Just found out this.

**Comment by cgyqu** [comment]
As we konw,Redis servers are typically set to 1000 connections.If the application define too many hubs,which can take up too many connections.Redis servers are generally Shared,this may cause some potential problems. This is what I worried.

On the other hand , In `ASPNet SinglR`,I noticed that there is only one global  Redis connection for  pub-sub and only one topic. But in `Core SingalR`,each connection has a topic.

On my PC，I did a quick test, `AspNetCore.SignalR` TPS is not as high as 'AspNet.SignalR'.
All use WebSockets Transport，and send message by client.

> AspNet.SignalR: over 1200/s
>AspNetCore.SignalR: about 1000/s

You can also do more tests to see if the results are correct.

I think it has something to do with this design.

**Comment by davidfowl** [comment]
We haven't seen people use that many hubs in real life. It's extremely wasteful especially since ASP.NET Core is a hub per connection. That said, we're going to look at sharing the connection regardless.

**Comment by anurse** [comment]
This can be worked around by using the [RedisOptions.ConnectionFactory](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.signalr.redis.redisoptions.connectionfactory?view=aspnetcore-2.1) to share a singleton `ConnectionMultiplexer`. We're going to close this until we see further feedback.
