### ISSUE TITLE
Javascript & Java clients mark state as connected before the handshake response has been received

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2903]
The .NET client waits for the handshake to complete before marking the connection as usable but this isn't the same for the javascript client.

https://github.com/aspnet/SignalR/blob/f42f4c56e61c5891a851907cf4639575dbbc8df4/clients/ts/signalr/src/HubConnection.ts#L123

**Comment by davidfowl** [comment]
> I agree it's wrong, but what's the actual customer impact here? Won't the user sends be queued behind the handshake messages and still work?

Not sure, I was reviewing the java client and saw this bug and noticed it was in the javascript client as well. I'm guessing it can result in more failures than necessary since we're exposing the state now in 1.1.

**Comment by anurse** [comment]
Ok cool. You're right, it's backwards and we should fix it, just wanted to understand it fully. I'll put it in 2.2 for now.

**Comment by BrennanConroy** [comment]
Fixed in #3068
