### ISSUE TITLE
Swagger support?

### ISSUE THREAD

**Issue by Kikimora** [aspnet/SignalR#2913]
How can I generate swagger documentation for SignalR API?

**Comment by anurse** [comment]
There is no way to do this as OpenAPI does not support RPC-style documentation. OpenAPI and Swagger are only for generating descriptions of REST APIs, but SignalR does not use a REST API, it has a custom protocol.

[AsyncAPI](https://www.asyncapi.com/) is a better fit here, and we're investigating systems like that for describing SignalR APIs in the future.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.

**Comment by RSuter** [comment]
Swagger/OpenAPI is not really able to describe SignalR hubs, that's why I created an experimental spec + generator: https://github.com/RSuter/SigSpec

Discussion about Swagger + SignalR: https://github.com/RSuter/NSwag/issues/691
