### ISSUE TITLE
xamarin.ios got SIGABRT while trying to re-StartAsync after call StopAsync

### ISSUE THREAD

**Issue by juepiezhongren** [aspnet/SignalR#2918]
__

**Comment by anurse** [comment]
Can you provide a sample app that can reproduce the issue? And fully describe your environment as requested in the new issue template:

* Versions of Server-Side NuGet Packages:
* Versions of Client-Side NuGet/NPM Packages:
* Are you using the C# client or the JavaScript client:
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
* The Operating System on the Server (Windows/Linux/macOS):
* The Operating System on the Client (Windows/Linux/macOS):
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):

Please also collect client-side logs as requested in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)
