### ISSUE TITLE
Syntax Error when used in a Vue project initialized with cli v3

### ISSUE THREAD

**Issue by joefazz** [aspnet/SignalR#2919]
Hi!

I'm trying to use SignalR in a Vue project that I've set up with the new CLI however I get this error whenever I use the `<script>` tag

`Uncaught SyntaxError: Unexpected token <`

I've reproduced this at [this github repo](https://github.com/joefazz/vue-cli3-signalr-error)

Any help would be appreciated

**Comment by anurse** [comment]
Does the error only reproduce when you include the SignalR script? It seems very unlikely that SignalR would be able to cause a syntax error in your application.

**Comment by joefazz** [comment]
Sorry I should've been more specific. It says the syntax error is inside the signalr.js file itself.

Yes it is only when the script is included.

**Comment by anurse** [comment]
Is your server actually serving the signalr js file properly? This kind of syntax error is very common when the server reports a 404 or other error, because it sends back HTML which starts with a `<` character and is invalid JavaScript.

**Comment by anurse** [comment]
It looks like your server only serves files out of the `public` directory, so accessing from `node_modules` like you do in your [index.html](https://github.com/joefazz/vue-cli3-signalr-error/blob/f4a69df97c951bcbeb353cd70d48c252be6319a2/public/index.html#L4) wouldn't work.

**Comment by joefazz** [comment]
Thanks it works now! Sorry for the issue clog.
