### ISSUE TITLE
Support for InvokeAsync

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2926]
We only support `SendAsync`-style invocation in the Java Client right now. We need support for waiting for the server to finish the invocation.

**Comment by anurse** [comment]
Sounds like this is the way we have to do it, so let's do it. I wonder if we should put the return type first?

```java
.invoke(String.class, "GetProductName", 123, 456);
```

vs

```java
.invoke("GetProductName", String.class, 123, 456);
```

I like the first one (return type first) because a) it looks closer to the C# and b) it keeps the method name and args together.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/4b378692a4ea350091f1101e519169e28b8662b5
