### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2927]
Probably use Rx: `streamAsObservable(...)`.

**Comment by Tragetaschen** [comment]
On my (usual) embedded platform, I'm using SignalR to communicate with web browsers (running the system's GUI or on an attached computer) and recently started using SignalR as the IPC protocol over a Bluetooth socket. I'm consuming the latter for testing purposes from a UWP, but running on Android is the actual environment.

Most of the time, the connection is used to push out current data (changing once per second) from the instrument to GUI/connected browser/Android phone and that's where I'm using streaming to a large extent. Should streaming not be supported initially, the Android side would need to continuously invoke a method on the instrument which returns when a new value is available.

**Comment by anurse** [comment]
Cool, I appreciate the context. I think we're leaning towards waiting until Streaming is available before calling it version "1.0.0" so I think that should cover what you're looking for. We don't think Streaming will be delayed much but it might not land right at 2.2 RTM so we want to make sure we can find the right versioning to communicate that. Our current thinking is that we can hit 1.0 in the Java Client shortly after ASP.NET Core 2.2 releases but well before ASP.NET Core 3.0.

**Comment by Tragetaschen** [comment]
That would pretty much line up with my "in the 2.2 time frame" from #3002, so: yay!

**Comment by mikaelm12** [comment]
Streaming added here: cdd7387159190d4e3c1755ffc0830d5b5073bb28
