### ISSUE TITLE
How to get SignalR packages to .Net Core Visual Studio 2017 project?

### ISSUE THREAD

**Issue by mne1991** [aspnet/SignalR#293]
Could anybody help me to get SignalR packages to work with .Net Core Visual Studio 2017 project?
I tried to copy NuGet.Config file to my project root but I couldn't restore SignalR packages.

**Comment by BrennanConroy** [comment]
You should just need to add `https://dotnet.myget.org/f/aspnetcore-ci-dev/api/v3/index.json` to your feeds when restoring
