### ISSUE TITLE
Make AddSignalR fully idempotent

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2931]
There are still a couple things that aren't `TryAdd`ed:

https://github.com/aspnet/SignalR/blob/db99baac354d08196a9e64790fa552eb14e932d5/src/Microsoft.AspNetCore.SignalR/SignalRDependencyInjectionExtensions.cs#L38-L39

We'll need to use `TryAddEnumerable` for the second one since we want to add it if `HubOptionsSetup` hasn't been registered yet, even if another `IConfigureOptions<HubOptions>` *has* been registered.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/8be051ce34319c9aac7cd55340c28642c25d0fbd
