### ISSUE TITLE
HttpClientHandler System.ObjectDisposedException on client side (C#)

### ISSUE THREAD

**Issue by AwsomeCode** [aspnet/SignalR#2934]
* Versions of Server-Side NuGet Packages: **Microsoft.AspNetCore.App 2.1.1**
* Versions of Client-Side NuGet/NPM Packages: **Client for ASP.NET Core SignalR 1.0.3**
* Are you using the C# client or the JavaScript client: **C# Client** 
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): **IIS Express**
* The Operating System on the Server (Windows/Linux/macOS): **Windows**
* The Operating System on the Client (Windows/Linux/macOS): **Windows**

I have simple HttpClientHandler 

```
public class WrappedHttpMessageHandler : HttpClientHandler
    {
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            //request.Headers= ;
            var response = await base.SendAsync(request, cancellationToken); //System.ObjectDisposedException
            return response;
        }
    }
```
Used in HubConnectionBuilder

```
handler = new WrappedHttpMessageHandler{};

connection = new HubConnectionBuilder().WithUrl("http://localhost:50741/ChatHub", op =>{
    op.HttpMessageHandlerFactory = h => handler;
}).Build();

```

Getting System.ObjectDisposedException at reconnecting or whenever calling below line second time.
```
await connection.StartAsync(); //System.ObjectDisposedException
```
Whitout HttpMessageHandler in HubConnectionBuilder reconnection is working fine.

**Comment by davidfowl** [comment]
Can you show the entire stack trace? Can you provide a repro project? Did you call dispose on anything?

**Comment by AwsomeCode** [comment]
Not calling any dispose anywhere.
Stacktrace [ObjectDisposedException.txt](https://github.com/aspnet/SignalR/files/2365646/ObjectDisposedException.txt)

**Comment by AwsomeCode** [comment]
Repos:
Server [AspNetCoreSignalrTest1.zip](https://github.com/aspnet/SignalR/files/2365702/AspNetCoreSignalrTest1.zip)
Client [WpfApp1.zip](https://github.com/aspnet/SignalR/files/2365703/WpfApp1.zip)

**Comment by davidfowl** [comment]
Ah good! That code is correct.


The simple fix is the create the handler in the handler factory instead of reusing it. 

```C#
connection = new HubConnectionBuilder().WithUrl("http://localhost:50741/ChatHub", op =>{
    op.HttpMessageHandlerFactory = h => new WrappedHttpMessageHandler();
}).Build();
```

Will likely work. The reason it's a handler factory instead of an instance.

**Comment by AwsomeCode** [comment]
I need an access of WrappedHttpMessageHandler object. I need to change header of httpRequest for some reason.

**Comment by davidfowl** [comment]
You can already change headers without having a custom message handler.  Your samples doesn't really show what you're trying to accomplish. Regardless, you need to create the handler during handler creation in the factory, this might mean that you have to do something more convoluted to pass state into the handler that will later read that state.

**Comment by AwsomeCode** [comment]
How can I change authentication header without creating new hubconnection object?
Currently in old signalr if my user needs to login with other account I am stopping the connection changing the authentication header and starting the connection again. Without re registering any methods or creating new hubconnection. 
How can I archive this?

**Comment by AwsomeCode** [comment]
Also we need to access httpresponse status code.

**Comment by davidfowl** [comment]
> How can I change authentication header without creating new hubconnection object?

https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1

You can use the AccessTokenProvider to set the access token for an API.

> Also we need to access httpresponse status code.

Can you write up a sample of exactly what you want to do?

**Comment by AwsomeCode** [comment]
> Can you write up a sample of exactly what you want to do?

Sure.
Our app uses Basic Authentication (ex. Username and Password) 

```
public class WrappedHttpMessageHandler : HttpClientHandler
    {
        public string UserName;
        public string Password;
        public event EventHandler<ArgsProfileInfo> AccountConflict = delegate { };

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            request.Headers.Authorization = new AuthenticationHeaderValue("Basic", "UserNameAndPassword");

            var response = await base.SendAsync(request, cancellationToken);
            if (response.StatusCode == HttpStatusCode.Conflict)
            {
                AccountConflict(this, new ArgsProfileInfo(UserName));
            }
            return response;
        }
    }
```

App has option for adding multiple accounts (ex. like Multiple email accounts). So user can switch between them.
For this we don't need to close the and hence we are not creating new hubconnection for it as well.
We just Stop() the connection and swap the AuthenticaionHeader and Start() the connection.
```
request.Headers.Authorization = new AuthenticationHeaderValue("Basic", "UserNameAndPassword");
```

Users cannot access account from multiple locations. For this at the time of authentication on server we check for other active connection or that user. If user has any active connection we set the HttpRespose StatusCode to Conflict. 
```
var response = await base.SendAsync(request, cancellationToken);
            if (response.StatusCode == HttpStatusCode.Conflict)
            {
                AccountConflict(this, new ArgsProfileInfo(UserName));
            }
```

So the problem is:

HttpClientHandler is call for first request only second request is not getting authorize. Header parameters are missing on second request.

Releated Issue https://github.com/aspnet/SignalR/issues/686 https://github.com/aspnet/SignalR/issues/1039
But it solves changing of authorization token only. Not for changing Basic Authentication and does not return HttpStatusCode

**Comment by anurse** [comment]
If you just need to update the Auth header, you can do that without wrapping the handler. The `HttpConnectionOptions` type has a [`Headers`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connections.client.httpconnectionoptions.headers?view=aspnetcore-2.1#Microsoft_AspNetCore_Http_Connections_Client_HttpConnectionOptions_Headers) list on it and you can simply update it there:

```csharp
var headers = new Dictionary<string, string>();
var connection = new HubConnectionBuilder()
    .WithUrl(url, op => {
        op.Headers = headers;
    })
    .Build();

headers["Authorization"] = $"Basic {authCredentials}"
await connection.StartAsync();

// When you need to change credentials:
await connection.StopAsync();
headers["Authorization"] = $"Basic {updatedAuthCredentials}"
await connection.StartAsync();
```

If you set your own dictionary to the `Headers` property, you can modify it it in between the `StopAsync` and `StartAsync` calls and we'll use the updated values when restarting.

If you still need to use wrapping HttpHandler, you'll need to use a factory that creates a new instance of your handler each time, but you can have that factory access a shared value to get the latest auth credentials so that when you re-start it, it gets an updated credential. Use code like this (where `AuthenticationManager.GetCurrentUserCredentials()` is code you provide in some component):

```csharp
var connection = new HubConnectionBuilder()
    .WithUrl(url, op => {
        op.HttpMessageHandlerFactory = h => new WrappedHttpMessageHandler(AuthenticationManager.GetCurrentUserCredentials(), h);
    })
    .Build();
```

**Comment by AwsomeCode** [comment]
I think this will work for me. If I get any issues I will reopen it.
Thanks @anurse @davidfowl Your great.
