### ISSUE TITLE
Flaky test on CI XPlat

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/SignalR#296]
This test occasionally fails on Ubuntu: EndToEndTests.ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport

http://aspnetci/project.html?projectId=XPlat&testNameId=2676016220103739427&tab=testDetails

**Comment by BrennanConroy** [comment]
Yeah, @moozzyk has fixed it in https://github.com/aspnet/SignalR/pull/291 I believe.

**Comment by moozzyk** [comment]
This should be fixed in 2f2d3a6f
