### ISSUE TITLE
NPM Next Version Publishing

### ISSUE THREAD

**Issue by PaitoAnderson** [aspnet/SignalR#2966]
I'm just wondering why `1.1.0-preview2-35157` was published as `latest` instead of replacing `1.1.0-preview1-35029` as `next`?

[https://www.npmjs.com/package/@aspnet/signalr?activeTab=versions](https://www.npmjs.com/package/@aspnet/signalr?activeTab=versions)

npm outdated output:
<img width="642" alt="screen shot 2018-09-17 at 11 47 50 am" src="https://user-images.githubusercontent.com/4108718/45634101-8a589f00-ba6f-11e8-8f6d-2b513d5c15b8.png">

Thanks!

**Comment by anurse** [comment]
This should be fixed now! Thanks for noticing and posting the question!
