### ISSUE TITLE
onclose is not called in JS client on server timeout

### ISSUE THREAD

**Issue by CombeeMike** [aspnet/SignalR#2969]
* Versions of Server-Side NuGet Packages: `1.0.2`
* Versions of Client-Side NuGet/NPM Packages: `1.0.2`
* Are you using the C# client or the JavaScript client: `JavaScript`
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): `Kestrel`
* The Operating System on the Server (Windows/Linux/macOS): `Win`
* The Operating System on the Client (Windows/Linux/macOS): `Win`
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): `Chrome`

I'm initializing my connection with this code:

```js
connection = new signalR.HubConnectionBuilder()
  .withUrl("/signalR", {
    transport: signalR.HttpTransportType.WebSockets,
    serverTimeoutInMilliseconds: 30 * 1000
  })
  .configureLogging(/* my custom logger */)
  .build();

connection.onclose(_handleDisconnected);
```

If I simply pause my server, `_handleDisconnected` is not called after 30 secs but after ~ 1.5 min.

I've debugged a little and found that `HubConnection.serverTimeout` is actually called after ~ 30 sec which in turn calls `this.connection.stop` but doesn't trigger the `onclose` event.

Also `this.webSocket.close();` within `WebSocketTransport.stop` is called...

**Comment by BrennanConroy** [comment]
Looks like you might be hitting https://github.com/aspnet/SignalR/issues/2557#issuecomment-402798865
This was fixed in 2.2.0-preview1. You can try out our previews by using the "next" tag when installing the client via npm, or grab one of the preview versions explicitly https://www.npmjs.com/package/@aspnet/signalr/v/1.1.0-preview2-35157

**Comment by CombeeMike** [comment]
Perfect, working as expected in the mentioned preview version!
Until this makes it into stable I can intercept `WebSocketTransport.stop` and call the close handler myself.

Thanks for the fast & helpful response!

**Comment by CombeeMike** [comment]
Out of curiosity: Is there any timeline for when those changes are released as stable?

**Comment by BrennanConroy** [comment]
Our Roadmap https://github.com/aspnet/Home/wiki/Roadmap
