### ISSUE TITLE
Should we make HubException in the Java Client a Runtime Exception

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2976]
Should we change HubException in the java client to derive from Runtime Exception. 
The main reason being 
>RuntimeException and its subclasses are unchecked exceptions. Unchecked exceptions do not need to be declared in a method or constructor's throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.

[Runtime Exception Docs](https://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html)

**Comment by anurse** [comment]
We should get this figured out ASAP. Probably as part of the review with some other Java folks.

**Comment by mikaelm12** [comment]
Looks like we wont be going this direction
