### ISSUE TITLE
Test failure: HubConnectionCanSendAndReceiveMessages

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/SignalR#2979]
This test [fails](http://aspnetci/viewLog.html?buildId=557087&buildTypeId=Releases_21Public_UbuntuUniverse) occasionally with the following error:
```
[Test Collection Cleanup Failure (RedisEndToEndTestsCollection)]: System.Exception : Command '/usr/bin/docker stop redisTestContainer' failed with exit code '1'. Output:
Error response from daemon: No such container: redisTestContainer
   at Microsoft.AspNetCore.SignalR.Redis.Tests.Docker.RunProcessAndThrowIfFailed(String fileName, String arguments, ILogger logger, TimeSpan timeout) in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/Docker.cs:line 90
   at Microsoft.AspNetCore.SignalR.Redis.Tests.Docker.Stop(ILogger logger) in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/Docker.cs:line 74
   at Microsoft.AspNetCore.SignalR.Redis.Tests.RedisServerFixture`1.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisServerFixture.cs:line 60
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.1.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
CanSendAndReceiveUserMessagesWhenOneConnectionWithUserDisconnects [failed with about the same error](http://aspnetci/viewLog.html?buildId=557087&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by anurse** [comment]
@BrennanConroy can we make the stop a little more resiliant and check if the container is even running first.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 10 failures [with about the same error](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=32141) on release/2.2 at 6:03:17 PM:
- HubConnectionCanSendAndReceiveMessages
- HubConnectionCanSendAndReceiveMessages
- HubConnectionCanSendAndReceiveMessages
- HubConnectionCanSendAndReceiveMessages
- HubConnectionCanSendAndReceiveMessages
- HubConnectionCanSendAndReceiveMessages
- HubConnectionCanSendAndReceiveMessages
- HubConnectionCanSendAndReceiveMessages
- HubConnectionCanSendAndReceiveMessages
- HubConnectionCanSendAndReceiveMessages

**Comment by BrennanConroy** [comment]
Closing as we made some changes to the redis tests, RAAS will open a new issue if there is still flakiness.
