### ISSUE TITLE
Implement Reactive Socket protocol and Reactive Streams

### ISSUE THREAD

**Issue by Horusiath** [aspnet/SignalR#298]
Since you're already rewriting websocket layer, maybe it would be a good idea to implement a [reactive socket](http://reactivesocket.io/) protocol on top of it? In short it's a network equivalent of the [Reactive Streams](http://www.reactive-streams.org/) standard, that manages to bring a common way of providing reliable asynchronous message-based streaming with backpressure build as core part.

Reactive socket already has implementations for Java, JavaScript and C++ (probably also Go and Python).

Reactive streams SPI (Service Provider Interface, don't confuse it with API) is already implemented by several libraries across different platforms, including RxJava, RxJS, but also Reactor and Akka.Streams implementations on both JVM and .NET. It will be part of JDK 9 standard library, while [.NET version](https://github.com/reactive-streams/reactive-streams-dotnet) will soon reach v1.0, and already includes a compatibility test kit (just as reactive socket).

Both standards have wide company support, including Netflix, Pivotal and Lightbend. Maybe it's a good idea for Microsoft to join as well? ;)

**Comment by moozzyk** [comment]
This is an interesting idea and I think it should be possible to implement a reactive socket server on top of the socket layer. I don't think however we would include such an implementation out of the box. It sounds like it would make a great 3rd party addition.

**Comment by Bartolomeus-649** [comment]
This is so obvious something that should be part of all versions and flavors of .NET out of the box. 
It is very problematic if this is an official Microsoft view on what .NET should support when it comes to async and reactive paterna, technology and standards.
For example, there is a huge need for something that replaces RIA services that will work across different clients, such as web(http/html/javascript), Xamarin Forms, traditional .NET desktop applications(winforms, wpf) and so on.
SignalR could be this "RIA 2.0", but it needs to be packaged and fully integrated with VisualStudio, Entity Framework and so on.
