### ISSUE TITLE
Complete Java Docs

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2982]
The current Java docs we have were a first pass for the main public types. We need to go through again and add any missing documentation before preview 3 since the API docs will be on the docs site.

**Comment by anurse** [comment]
Just waiting on API docs team to update the docs themselves.

**Comment by mikaelm12** [comment]
Docs are up now!
Main docs: https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-2.2
Api Docs: https://docs.microsoft.com/en-us/java/api/com.microsoft.signalr?view=aspnet-signalr-java
