### ISSUE TITLE
IE 11: Invalid operand to ‘instanceof’: Function expected

### ISSUE THREAD

**Issue by balkarov** [aspnet/SignalR#2986]
Hello. Thank you for your library!

I have problem in Internet Explorer 11. 
I have web application 1 which has signalR. And I have another application2 (without signalR) which has iframe with application 1. 
When I close iframe (remove from dom) in application 2 I get error: `Invalid operand to ‘instanceof’: Function expected` every ~10-15 seconds. 
After debug I saw that after close iframe ArrayBuffer is undefined in signalR. But I open iframe with app 1 ArrayBuffer is defined.
![123123123](https://user-images.githubusercontent.com/6030335/45815722-31447180-bce2-11e8-8eb9-e9f28eec68b2.png)

### Info

* "@aspnet/signalr": "1.0.3"
* Microsoft.AspNetCore.SignalR 1.0.3
* npm 6.1.0
* The JavaScript client
* IIS Express
* Windows 10
* IE 11

**Comment by anurse** [comment]
@BrennanConroy we can probably be a little more defensive here.

**Comment by BrennanConroy** [comment]
This fix will appear in the 1.1.0-preview3 release
Fixed via https://github.com/aspnet/SignalR/commit/ef3d3b1cddebf43e6f8bbfc81519a11356d2095a
