### ISSUE TITLE
Set User-Agent correctly in SignalR Clients

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#299]
We have a dummy User-Agent in the SignalR client right now, but before preview we should make our User-Agent strings consistent across C#, JavaScript (in NodeJS, we can't set it in the browser), Swift, etc.

Not a high priority right now, just something I noticed and didn't want to forget about.

/cc @moozzyk @davidfowl

**Comment by moozzyk** [comment]
We also tended to include more information in the User-Agent string: https://github.com/SignalR/SignalR/blob/ed4a08d989bf32a1abf06cd71a95571a8790df82/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L915-L952

**Comment by davidfowl** [comment]
@moozzyk moving to @mikaelm12

**Comment by mikaelm12** [comment]
Done: b60e5982777e6141c4cae0069d401c2b7f9a6342
