### ISSUE TITLE
WebSockets failing with 500 during negotiation, always falling back to SSE

### ISSUE THREAD

**Issue by oising** [aspnet/SignalR#2990]
Logs:

[aspnet_core_web_server.txt](https://github.com/aspnet/SignalR/files/2402528/aspnet_core_web_server.txt)
[signalr-client-console-trace.txt](https://github.com/aspnet/SignalR/files/2402529/signalr-client-console-trace.txt)

* Versions of Server-Side NuGet Packages:

```
PM> get-package

Id                                  Versions
--                                  --------
Microsoft.AspNetCore.App            {2.1.4}
mediatR                             {5.1.0}
MediatR.Extensions.Microsoft.Dep... {5.1.0}
Microsoft.NETCore.App               {2.1}
Microsoft.AspNetCore.SpaServices    {2.1.1}
```
* Versions of Client-Side NuGet/NPM Packages:
```
PS> yarn list --depth 0 --pattern @aspnet*
yarn list v1.9.4
└─ @aspnet/signalr@1.0.3
```
* Are you using the C# client or the JavaScript client:

JS

* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 

IIS Express 10

* The Operating System on the Server (Windows/Linux/macOS):

Windows 10/1803 (also tested on Windows 10/rs5)

* The Operating System on the Client (Windows/Linux/macOS):

As above.

* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):

Chrome 69/x64

* Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please **do not** put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.

Attached.

When in doubt, feel free to file the issue, we're happy to help answer questions. We also suggest using the `asp.net-core-signalr` tag on StackOverflow to ask questions.

**Comment by oising** [comment]
if I'll hazard a guess without too much thinking, it's the SpaServices middleware that's b0rking something: `Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.PerformProxyRequest`

My app is a SPA based on Aurelia. The app itself was generated using `aurelia-cli`.

**Comment by anurse** [comment]
Yeah, I'm noticing that too. The call stack doesn't even have SignalR in it. I'm not sure what SpaServices is doing here. It looks like the conditional proxy middleware is trying to forward the request to... somewhere? (I don't know for sure where the proxy middleware is trying to forward requests) and getting the 500 trying to read the response.

@SteveSandersonMS Do you have some additional context that can help here? What we're seeing is that a WebSocket request is coming in, but before it gets to SignalR, the SpaServices ConditionalProxyMiddleware is trying to proxy it and throwing an exception:

```
project> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
project>    at System.Net.Http.HttpConnection.FillAsync()
project>    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
project>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
project>    --- End of inner exception stack trace ---
project>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
project>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
project>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
project>    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
project>    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
project>    at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.PerformProxyRequest(HttpContext context)
project>    at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
project>    at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
project>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I think what's happening is that the `ConditionalProxyMiddleware` is trying to proxy the WebSocket request and so it copies all the incoming headers to `HttpClient` to do so, but that means it will be copying headers like `Connection: Upgrade` and `Upgrade: WebSocket` which will totally blow up when given to `HttpClient` (since WebSockets have their own client).

**Comment by oising** [comment]
I have a private repo here that contains the entire app. It should repo this issue out of the box. Shall I add you as a member so you can clone it? just need to `yarn`, `au build` then f5 in vstudio for iisexpress (`au run` will spin up a node http server, not what we want)
