### ISSUE TITLE
Insert List of SignalR Client link in docs

### ISSUE THREAD

**Issue by andreatosato** [aspnet/SignalR#2996]
Hi, I would like to suggest that you add all the links and references to SignlaR Client developments in the SignalR Core documentation.

Current list:
ASP .NET Core: 'Microsoft.AspNetCore.SignalR.Client' on NuGet (https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR/)
Java: 'com.microsoft.aspnet:signalr' on Maven (https://search.maven.org/artifact/com.microsoft.aspnet/signalr)
JavaScript (including NodeJS): '@aspnet/signalr' on NPM (https://www.npmjs.com/package/@aspnet/signalr)
C++: (Prototype) https://github.com/aspnet/SignalR/tree/master/clients/cpp (no official release planned yet)
Swift: (Unofficial) SwiftSignalRClient on CocoaPods (https://github.com/moozzyk/SignalR-Client-Swift)

Source: @anurse in gitter conversation.

Thanks a lot!

**Comment by anurse** [comment]
Moving to the Docs repo: https://github.com/aspnet/Docs/issues/8646
