### ISSUE TITLE
System.Web.HttpException: The remote host closed the connection. The error code is 0x800704CD

### ISSUE THREAD

**Issue by jinek** [aspnet/SignalR#3008]
* Versions of Server-Side NuGet Packages: 2.3.0
* Versions of Client-Side NuGet/NPM Packages: 2.3.0
* C# client
* Azure Web App
* Windows on server and client

Exception happening during server deployment
[SignalRStackTrace.txt](https://github.com/aspnet/SignalR/files/2414737/SignalRStackTrace.txt)

**Comment by davidfowl** [comment]
This issue was moved to SignalR/SignalR#4217
