### ISSUE TITLE
Getting exception from server on C# client

### ISSUE THREAD

**Issue by farlock85** [aspnet/SignalR#3009]
I have an ASP.NET SignalR server on .NET Core 2.1 and a .NET 4.6.2 C# Client on Microsoft.AspNetCore.SignalR.Client 1.0.3.

This is my hub:

```
public class MyHub : Hub
{
	public async Task<Boolean> Connect(String identifier)
	{
		if (identifier == null)
		{
			throw new Exception("Identifier null");
		}
		return true;
	}
}
```

And my client:

```
try
{
	var response = await _hubConnection.InvokeCoreAsync<boolean>("connect", new Object[] { null });
}
catch (Exception ex)
{

}
```

When I send the request the server throws a custom Exception (identifier null), but the exception on the client is `An unexpected error occurred invoking 'connect' on the server.` and the actual exception cannot be accessed.

**Comment by anurse** [comment]
By default, for security reasons, we don't expose detailed error messages to the client. There are two ways to the more detailed information:

1. Turn on [`EnableDetailedErrors`](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-server-options) to allow the server to send detailed error messages. This is **not recommended in production**
2. Check the server logs, the full exception should be logged there for you to see (this is the recommended approach in production environments).

**Comment by farlock85** [comment]
Ok makes sense. This is a fully internal app so there is a need to have the exceptions come over as is, EnableDetailedErrors works fine in this case.

**Comment by anurse** [comment]
Re-reading your example, there is a third option that may be better:

3. Leave `EnableDetailedErrors` **disabled** and throw `HubException` or exceptions derived from `HubException`. Those errors will be sent to the client regardless of your `EnableDetailedErrors` setting (as they are designed for use when you want to explicitly communicate the error to the client). This would mean that other exceptions (runtime errors, database connection problems) won't have their details sent to the client, but the exceptions you choose will.

**Comment by farlock85** [comment]
Yes that's even better, that way I can only send over intended exceptions that need to be acted on, thanks!
