### ISSUE TITLE
Throw a useful error when WebSockets are disabled on the server

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#3014]
Today the Java Client doesn't do anything with the negotiate payload other than handling redirects. The payload also contains a list of available transports though. Eventually the client will use this to do fallback, but since we only support WebSockets, it should at least check that list to see if WebSockets are available on the server and throw a useful error (`The WebSocket transport is not available on the server`) if it's not there.

**Comment by mikaelm12** [comment]
We should add logging though.
