### ISSUE TITLE
The 'protocol' argument is required error

### ISSUE THREAD

**Issue by etairi** [aspnet/SignalR#3020]
I'm trying to use SignalR, and on my backend, I installed the following NuGet packages:

> Microsoft.AspNetCore.All (2.0.6) // I can't migrate to newer version at the moment.
> Microsoft.AspNetCore.SignalR (1.0.3)
> Microsoft.Azure.SignalR (1.0.0)
> Microsoft.Azure.SignalR.Protocols (1.0.0)

And on my frontend I'm using React, and I installed the following package with npm:

> "@aspnet/signalr": "^1.0.3"

Then, in my frontend, I have a code segment like this one (please note that I'm using JS and not TS):

```
import {
    //ConsoleLogger,
    LogLevel,
    HttpTransportType,
    HubConnection,
} from '@aspnet/signalr';

import config from '../../run-config';

class WebsocketService {
    _connection;

    constructor() {
        const transport = HttpTransportType.WebSockets;

        // Apparently, ConsoleLogger is not available anymore?! 
        // What do I use for logging now?
        //const logger = new ConsoleLogger(LogLevel.Information);

        const options = {
            transport: transport,
            //logger: logger,
        };
        const url = config.hubHost;

        // Throws error here, when trying to create a HubConnection.
        this._connection = new HubConnection(url, options);
        this._connection.start().catch((err) => console.error(err));
    }
}

const MyWebsocketService = new WebsocketService();
export default MyWebsocketService;
```

What exactly is the problem? And how can I overcome it?

**Comment by BrennanConroy** [comment]
Don't create a `HubConnection` manually, use the `HubConnectionBuilder`. See an example here: https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#connect-to-a-hub

In typescript the `HubConnection` constructor is private, you're just getting away with it because there is no private in javascript.

**Comment by anurse** [comment]
Let us know if you're still seeing an issue after switching to HubConnectionBuilder!

**Comment by etairi** [comment]
I changed to using `HubConnectionBuilder` as per your request, and did something like this:
```
import * as signalR from '@aspnet/signalr';
import config from '../../run-config';

class WebsocketService {
    _connection;
    constructor() {
        const url = config.hubHost;
        this._connection = new signalR.HubConnectionBuilder()
                                      .withUrl(url)
                                      .configureLogging(signalR.LogLevel.Trace)
                                      .build();
        this._connection.start().catch((err) => console.error(err.toString()));
    }

    registerNotificationAdded = (notificationAdded) => {
        this._connection.on('NotificationAdded', (notification) => {
            notificationAdded(notification);
        });
    }

    addNotification(notification) {
        this._connection.invoke('AddNotification', notification);
    }
}

const NotificationWebsocketService = new WebsocketService();
export default NotificationWebsocketService;
```

In the console I see the following messages printed:

> Debug: Starting HubConnection.
> Debug: Starting connection with transfer format 'Text'.
> Debug: Sending negotiation request: https://localhost:44335/api/negotiate

And then it throws errors:

> POST https://localhost:44335/api/negotiate 404
> Error: Failed to complete negotiation with the server: Error
> Error: Failed to start the connection: Error

But really there is no negotiate endpoint on my server side. I didn't see anywhere online that one needs such an endpoint. How does it should look on server side?

**Comment by BrennanConroy** [comment]
Your server should have `routes.MapHub<HubName>("/api");` Which will add a /api/negotiate endpoint for you. See our docs for a working server example https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio#configure-the-project-to-use-signalr

**Comment by etairi** [comment]
I actually added it, but then was pointing to a wrong place. I updated it, and now it seems to connect nicely, but what I want to achieve does not work exactly. I have the following now:

**webSocketService.js:**
```
import * as signalR from '@aspnet/signalr';
import config from '../../run-config';

class WebsocketService {
    _connection;
    constructor(hub) {
        const url = config.hubHost;
        this._connection = new signalR.HubConnectionBuilder()
                                      .withUrl(url + hub)
                                      .configureLogging(signalR.LogLevel.Trace)
                                      .build();
        this._connection.start().catch((err) => console.error(err.toString()));
    }

    registerNotificationAdded = (notificationAdded) => {
        this._connection.on('NotificationAdded', (notification) => {
            notificationAdded(notification);
        });
    }

    addNotification(notification) {
        this._connection.invoke('AddNotification', notification);
    }
}

const NotificationWebsocketService = new WebsocketService('/notification');
export default {
    NotificationWebsocketService,
};
```

**notificationService.js:**
```
import WebSocketService from './webSocketService';

class NotificationService {
    _notificationAdded;

    constructor(notificationAdded) {
        this._notificationAdded = notificationAdded;

        WebSocketService.NotificationWebsocketService.registerNotificationAdded((notification) => {
            this._notificationAdded(notification);
        });
    }

    addNotification(notification) {
        WebSocketService.NotificationWebsocketService.addNotification(notification);
    }
}

export default NotificationService;
```

**notification.sagas.js:**

```
import { apply, put, select } from 'redux-saga/effects';
import { getTranslate } from 'react-localize-redux';
import Immutable from 'seamless-immutable';
import {
    addUserNotificationSucceeded,
    addUserNotificationFailed,
} from '../reducers/notification.reducers';
import NotificaitonService from '../services/notificationService';

function* translate(key) {
    const locale = yield select(state => state.locale);
    return (getTranslate(locale))(key);
}

export function* addUserNotification(notifApi, { payload }) {
    const fallbackErrorTranslation = yield translate('error.custom_error.add_notification_failed');

    try {
        const notificationService = new NotificaitonService((notification) => {
            handleOnSocket(notification);
        });

        function* handleOnSocket(notification) {
            const user = yield select(state => state.authentication.user);
            const userNotifications = yield select(state => state.notification.userNotifications);
            let updatedUserNotifications = userNotifications;
            console.log(notification);

            if (notification && notification.notified_user_id && notification.notified_user_id === user.id) {
                updatedUserNotifications = userNotifications ? Immutable.asMutable(userNotifications).concat(notification)
                                                             : Immutable.asMutable([]).concat(notification);
            }
            yield put(addUserNotificationSucceeded(updatedUserNotifications));
        };

        notificationService.addNotification(payload);
    } catch (err) {
        console.error(err);
        yield put(addUserNotificationFailed({
            message: fallbackErrorTranslation,
        }));
}
```

Now I tried to open my site in two browsers one in Chrome and one in Mozilla. In Chrome I make a call that calles `addUserNotification` saga, and I see trace messages coming about data sent and received. And in Mozilla, I just wait for the notification to be displayed, and I again see the trace messages about data sent and received, but the notification does not arrive I get the following warning:

> Warning: No client method with the name 'NotificationAdded' found.

What might be the problem here?

**Comment by BrennanConroy** [comment]
That means your `HubConnection` doesn't have a 'NotificationAdded' method registered.

I see that you do call `.on("NotificationAdded")` but maybe it isn't being called in Firefox? Try debugging and making sure the client callback is registered.

**Comment by etairi** [comment]
How can I check or make sure that a client callback is registered? Because in my case I'm calling it, and the request goes to my server and it is executed but then in return it cannot seem to find `NotificationAdded` method. Though, as you said I already have it.

**Comment by BrennanConroy** [comment]
>How can I check or make sure that a client callback is registered?

By debugging the javascript in the browser and making sure that `.on(...)` is actually being called.

One thing I noticed and hope is just a typo when you pasted the code, you reference "NotificaitonService" in one of the files when it should be "NotificationService".

Try minimizing the app to just a hubconnection and the .on callback so it's easier to see what is going on.

```
this._connection = new signalR.HubConnectionBuilder()
                                      .withUrl(url + hub)
                                      .configureLogging(signalR.LogLevel.Trace)
                                      .build();
this._connection.start().catch((err) => console.error(err.toString()));
this._connection.on("NotificationAdded", (s) => {});

**Comment by anurse** [comment]
Sounds like you've resolved your issue @etairi ! I'm going to close this issue but feel free to comment further if you have questions!
