### ISSUE TITLE
Difference between establishing connection to the server with connectionId and directly connecting with websocket endpoint without connectionId

### ISSUE THREAD

**Issue by sarvabowmen** [aspnet/SignalR#3024]

**Comment by davidfowl** [comment]
The difference is performance. If you know the server supports websockets and you know the client can connect via websockets you can avoid the round trip.

**Comment by mikaelm12** [comment]
In other words, you can totally avoid the negotiate back and forth process. But it's worth noting that if you're using the Azure SignalR service the negotiation process is required.
