### ISSUE TITLE
ERR_CONNECTION_REFUSED even with logging disabled

### ISSUE THREAD

**Issue by jdmichel** [aspnet/SignalR#3026]
This is within my front-end single page app. 
```javascript
...
import * as signalr from "@aspnet/signalr";
...
    this.conn = new signalr.HubConnectionBuilder()
      .configureLogging(signalr.LogLevel.None)
      .withUrl(`${Config.serviceUrl}/userHub`)
      .build();
...
private connectToHub() {
    let tmr = window.setInterval(() => {
      console.debug("Attempting to connect to notification hub.");
      this.conn
        .start()
        .then(() => {
          window.clearInterval(tmr);
          this.updateConnectionStatus(ConnectionStatus.Connected);
          console.debug("Connected to notification hub.");
        })
        .catch(err => {
          this.updateConnectionStatus(ConnectionStatus.Disconnected);
          //console.debug(`Error connecting to notification hub.`);
        });
      // Chrome always shows detailed errors in the console, so no point in logging again above.
    }, 3000);
  }
```
When I bring the REST service down, then I'm seeing an ERR_CONNECTION_REFUSED message logged every 3 seconds. I'd rather just log my own debug-level messages (or none) instead since we display the connection status and don't need the clutter in the log. 

It looks like one of your error messages is being logged even though I set LogLevel.None when building the HubConnection.

**Comment by BrennanConroy** [comment]
What is the exact message being logged?

**Comment by jdmichel** [comment]
OPTIONS https://localhost:44333/api/userHub/negotiate net::ERR_CONNECTION_REFUSED

I'm only seeing the message in Chrome (latest) and not in Edge. I think I've seen before that Chrome sends CORS messages that Edge does not. 

My app is running in http://localhost:8080 on webpack-dev-server, and communicating with asp.net core 2.1 REST service running on https://localhost:44333.

**Comment by BrennanConroy** [comment]
That error message isn't from SignalR. I think Chrome is writing it.

**Comment by jdmichel** [comment]
OK. Sorry to bother you.
