### ISSUE TITLE
[Java] Transport needs to have a callback to the connection to stop the connection on failure

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#3038]
If the transport fails for any reason the `HubConnection` will still be "connected" and all sends will fail.
We should be passing a callback to the transport so it can trigger a disconnect at the `HubConnection` layer if the transport is closed from failures etc.

See https://github.com/aspnet/SignalR/blob/release/2.2/clients/ts/signalr/src/HttpConnection.ts#L208

**Comment by anurse** [comment]
Fixed in #3054
