### ISSUE TITLE
ConnectionTests.CannotSendAfterReceiveThrewException test failure on Ubuntu

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/SignalR#304]
Didn't see an issue filed for this but I'm seeing functional test failures on Ubuntu: http://aspnetci/viewLog.html?buildId=186882&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR

The issue is that the line here times out during the test: https://github.com/aspnet/SignalR/blob/dev/test/Microsoft.AspNetCore.Sockets.Client.Tests/ConnectionTests.cs#L649. Not familiar with the code so someone should investigate.

cc @anurse @BrennanConroy  @mikaelm12 @moozzyk

**Comment by moozzyk** [comment]
I know what's happening.
