### ISSUE TITLE
Error getting negotiation connection refused both on Xamarin and Windows

### ISSUE THREAD

**Issue by dugasz1** [aspnet/SignalR#3041]
* Versions of Server-Side NuGet Packages: 1.0.3 / 1.1.0-preview2-35157
* Versions of Client-Side NuGet/NPM Packages: 1.0.3 / 1.1.0-preview2-35157
* Are you using the C# client or the JavaScript client: C# Client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Kestrel
* The Operating System on the Server (Windows/Linux/macOS): Windows 10
* The Operating System on the Client (Windows/Linux/macOS): Xamarin 4.15.9 | Xamarin.Android SDK 9.0.0.19
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): -

[wireshark.txt](https://github.com/aspnet/SignalR/files/2435387/wireshark.txt)
[clientlog.txt](https://github.com/aspnet/SignalR/files/2435388/clientlog.txt)

Dear Developers!

I'm trying to make an application on Xamarin with this library and a light back end with asp.net core. 
I always get on my Android phone: 
```
[0:] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Error: Failed to start connection. Error getting negotiation response from http://192.168.0.2/live.

System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
```

So i tried a the same simple client on Windows and i got the same problem.
I tried it with two version 1.0.3 / 1.1.0-preview2-35157. I always used the same version on client and server. ( I even double cheked it with this line of code:)

```
AssemblyName name = typeof(Microsoft.AspNetCore.SignalR.Client.HubConnection).Assembly.GetName();
            Console.WriteLine("SignalR client version" + name.Version);
```
I attached the full Xamarin output and a wireshark log.

But if i send a http request from an app from Play Store on my phone, i got Connection ID required. Which is fine i guess because i just sent an empty GET.

**Comment by BrennanConroy** [comment]
This doesn't seem like a SignalR issue, try using `HttpClient` in your application and connecting to your site.

I found a StackOverflow question that looks similar and has some possible fixes https://stackoverflow.com/questions/31131658/xamarin-connect-to-locally-hosted-web-service

**Comment by anurse** [comment]
Your Fiddler log is just a text log which doesn't include WebSocket frame content. Can you export an "SAZ" file from Fiddler and upload that instead so we can see the traffic properly?

**Comment by dugasz1** [comment]
Sorry, i'm on another machine but a few minutes and i will create it again

**Comment by dugasz1** [comment]
[fiddler-JsonReaderException.zip](https://github.com/aspnet/SignalR/files/2443059/fiddler-JsonReaderException.zip)

**Comment by anurse** [comment]
Ah, I see the problem. You are connecting to `/chat` in the SignalRSamples project which is a raw "ConnectionHandler" and doesn't speak the Hub protocol. You should be connecting to `/default` instead.

**Comment by dugasz1** [comment]
Thank you it's works fine now. I was careless sorry.
