### ISSUE TITLE
[Java] Consider rewriting tests to compose futures instead of calling 'get'

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#3048]
Currently our tests call `.get()` with a timeout when dealing with `CompletableFuture<...>`. We should probably be using `.thenCompose` `.thenAccept` etc. instead.

**Comment by anurse** [comment]
This would depend upon JUnit supporting tests that return futures :).

**Comment by anurse** [comment]
Not possible because we are using RxJava now.
