### ISSUE TITLE
Connect to multiple hubs using the same connection

### ISSUE THREAD

**Issue by joeuy** [aspnet/SignalR#3057]
Hi,
Is it possible to connect to multiple hubs using the same connection? I could not find any docs or samples on this. 
Example: Open 1 websocket to the service, receive messages from hub1, hub2, hub3, ...., hubN.

**Comment by anurse** [comment]
No, it's not possible to run multiple hubs on the same connection. If you want to split your code up into chunks you can do have a single hub and then route to other DI services for each method.

**Comment by anurse** [comment]
Duplicate of #955

**Comment by joeuy** [comment]
Read the discussion on #955, I think my motivation is different so I wanted to share it.  @davidfowl @anurse 
I want to use hubs more like groups, let me explain why:

Scenario:
- entities belong to a single category (immutable).
- several users observe a category. A user could observe multiple categories (mutable - the categories a user observe changes over time).
- every time an entity is modified, it is required to notify users observing the category.

**NOTE:** I am using SignalR azure service + server-less flavor. 

Implementation options (please feel free to comment if there is a better way):

**A**
- when an entity is modified, find out the list of users for the entity category, notify each user in the list. 

pros: 
- single connection.
- single hub (is this actually a pro? is it ok to scale a hub to thousands of connected users?)

con: 
- extra work of trying to notify users that are not even connected.

**B**
- Use a group for each category. When a user connects to signalR, figure out which categories he is observing, add the user to all the corresponding groups. 
- When an entity is modified, notify the group that represents the category. 

pros: 
- single connection.
- single hub (is this actually a pro? is it ok to scale a hub to thousands of connected users?)
- when an entity is modified, just figure out the entity category. Then broadcast on the corresponding group. 

con: 
- user/category is mutable.
- group membership is persistent, explicit need to keep it in sync with actual user/category membership

**C**
- Use hubs as groups. When a user connect to signalR, figure out which categories he is observing, for each category connect to a hub named by the category_id. 
- When an entity is modified, broadcast on the hub named category_id.

pros: 
- multi hub (users are distributed across hubs. Is this actually a pro?)
- when an entity is modified, just figure out the entity category. Then broadcast on the corresponding hub.
- every time the user connects we refresh memberships.

con: 
- right now multiple connections are required.

**Comment by anurse** [comment]
> * is it ok to scale a hub to thousands of connected users?

Absolutely, in fact more hubs is **less** scalable in this scenario because of the multi-connection problem.

I'm not clear why Groups aren't a sufficient mechanism here. Yes, the client would need to store the list of groups and "rejoin" on reconnect, but you're already storing this data and doing this routing when connecting to separate hubs. I'm not sure I understand why this persistence is a "pro" for scenario C but a "con" for scenario B.

**Comment by joeuy** [comment]
> I'm not sure I understand why this persistence is a "pro" for scenario C but a "con" for scenario B.
Its because in C memberships get "refreshed" more often, every time connection happen. 

> I'm not clear why Groups aren't a sufficient mechanism here.
They are sufficient. However, it requires replicating and maintaining my user/category membership into signalR group structure.

In azure SignalR service its even harder because I need to call APIs to join/leave groups [docs](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#add-a-user-to-a-group)

Also I don't know how it works under the hood. But likely its more efficient to broadcast a message on a hub where 1.000 users are connected, than send a message to 1.000 users when there is 1.000.000 in the hub (I am thinking about backplane here too).

**Comment by anurse** [comment]
> Its because in C memberships get "refreshed" more often, every time connection happen.

This can easily be achieved via having the clients join right away. I'm not disagreeing that it's more work on the application side, but given our history with issues surrounding multiple Hubs on a single connection (in ASP.NET SignalR) it's something we intentionally avoided and I want to understand if the benefits outweight the costs here.

> In azure SignalR service its even harder because I need to call APIs to join/leave groups [docs](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#add-a-user-to-a-group)

That's only the case when using the REST API, not when using a SignalR app. If you have a SignalR app running on the server then you do this via the `Groups` API in the Hub and you can definitely have the client send up a batch of groups to join, or even extract that information from a QueryString parameter. How is your app built, are you using the SignalR Service directly in a serverless configuration or do you have a SignalR Server app?

> But likely its more efficient to broadcast a message on a hub where 1.000 users are connected, than send a message to 1.000 users when there is 1.000.000 in the hub (I am thinking about backplane here too).

From our data that isn't the case but if you've got some data to show that it isn't as efficient, that would definitely change things! Groups are fairly well optimized, especially when using a backplane. In the design of the system Hubs generally produce more load on the server and backplane than groups/users/etc.

**Comment by joeuy** [comment]
>  in a serverless configuration

Yes its server-less configuration. 

What would you say its the best way to go?

**Comment by anurse** [comment]
> Yes its server-less configuration.

Ok, thanks for clarifying that.

I still think Groups are the way to go here. The system was designed to use them for exactly this purpose. If there are issues that are getting in the way of doing that, we should discuss those. Hubs are not designed as collections of users, they represent the endpoints to which the client connects, so having multiple hubs on a single connection breaks that pattern.

It sounds like there are some limitations in the group-management REST APIs. I'd suggest you file an issue on the Azure SignalR repo (https://github.com/azure/azure-signalr) since they own those APIs. For example, it might be reasonable to add an API to "batch join" a single user to multiple groups.

**Comment by joeuy** [comment]
Thanks for the discussion, closing the issue now.
