### ISSUE TITLE
Look into using annotation processors 

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#3071]
Using annotation processors could clean up some of the code we have, specifically around registering handlers. We should do some investigation here.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/SignalR/issues/466

**Comment by anurse** [comment]
Yeah, this would be done as part of #466

**Comment by bradygaster** [comment]
we may revisit this but closing for now. cc @mikaelm12
