### ISSUE TITLE
React to the new StackExchange.Redis v2.0 package 

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#3077]
StackExchange released a new Redis library `StackExchange.Redis` V2.0.x

We'll be creating a new package: `Microsoft.AspNetCore.SignalR.StackExchangeRedis` which uses that. 

cc @anurse @Tratcher @DamianEdwards @Eilon

**Comment by BrennanConroy** [comment]
Done in https://github.com/aspnet/SignalR/pull/3089
