### ISSUE TITLE
[Forms][iOS] Error CS1703 Multiple assemblies with equivalent identity

### ISSUE THREAD

**Issue by sidatacom** [aspnet/SignalR#3079]
I have a Xamarin cross client project which contain signalr. If i add the nuget package Microsoft.AspNetCore.SignalR.Protocols.MessagePack (all Versions) i get this error.

the package includes the reference to System.Reflection.Emit.

i found some workarounds to fix the error for example this:

```
<PackageReference Include="System.Reflection.Emit">
  <Version>4.3.0</Version>
  <ExcludeAssets>all</ExcludeAssets>
</PackageReference>

```
but it does not work i get an runtime error if i create an instance of an hub.

the nuget package is in a .net standard 2.0 Assembly which referenced.

please can someone remove the reference ?

Thx

**Comment by anurse** [comment]
We can't remove the reference because it comes from the message pack library we use (https://github.com/neuecc/MessagePack-CSharp), so they would have to remove the dependency. I believe it isn't used in our default configuration though, so it should continue to work. Can you provide a sample project that fails and describe where the failure occurs?

**Comment by sidatacom** [comment]
[SampleProject.zip](https://github.com/aspnet/SignalR/files/2461019/SampleProject.zip)

Here the sample Project if you compile the ios project the failure occurs

**Comment by sidatacom** [comment]
I opened also an issue on the massagepack project !!!

[https://github.com/neuecc/MessagePack-CSharp/issues/328](url)

**Comment by anurse** [comment]
Looks like this is going to be part of fixing https://github.com/aspnet/SignalR/issues/3122. I'm going to close this and we can move discussion there.

**Comment by sidatacom** [comment]
Now we have the same with the signalR Client but other DLL.

https://github.com/xamarin/xamarin-macios/issues/5135#issuecomment-439597542


warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.

MTOUCH : warning MT0109: The assembly 'System.Threading.Tasks.Extensions.dll' was loaded from a different path than the provided path (provided path: /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Facades/System.Threading.Tasks.Extensions.dll, actual path: /Users/macuser/src/SignalRTaskExtensions/packages/System.Threading.Tasks.Extensions.4.5.0/lib/netstandard2.0/System.Threading.Tasks.Extensions.dll).
