### ISSUE TITLE
SignalR Client Error java.lang.NoClassDefFoundError: com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I

### ISSUE THREAD

**Issue by devrajeev** [aspnet/SignalR#3081]
I am facing the below error while trying to use SignalR Client in android application 👎 
**Error java.lang.NoClassDefFoundError: com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I**

Dependency I used for SignalR Android Client in build.gradle file
implementation 'com.microsoft.aspnet:signalr:0.1.0-preview1-35029'

Here throwing that error 👎 

> hubConnection.on("ReceiveMessage", (message)-> {
> 
>         getActivity().runOnUiThread(new Runnable() {
>             @Override
>             public void run() {
>                 Log.d("MessageReceived",message);
>                 arrayAdapter.add(senderName + " : " +message);
>                 arrayAdapter.notifyDataSetChanged();
>             }
>         });
>     }, String.class);

Error Source for reference 👎 

Find below error source

> **10-07 23:24:39.425 18779-18779/com.cabieo.cabieoapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I>
> 10-07 23:24:39.425 18779-18779/com.cabieo.cabieoapp D/AndroidRuntime: Shutting down VM
> 
> --------- beginning of crash
> 10-07 23:24:39.600 18779-18779/com.cabieo.cabieoapp E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.cabieo.cabieoapp, PID: 18779
> java.lang.NoClassDefFoundError: com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I
> at com.microsoft.aspnet.signalr.CallbackMap.put(CallbackMap.java:15)
> at com.microsoft.aspnet.signalr.HubConnection.on(HubConnection.java:219)
> at com.cabieo.cabieoapp.Fragments.ChatHomeFragment.onCreateView(ChatHomeFragment.java:70)
> at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
> at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
> at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
> at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
> at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
> at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
> at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
> at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
> at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
> at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
> at android.os.Handler.handleCallback(Handler.java:742)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:157)
> at android.app.ActivityThread.main(ActivityThread.java:5571)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
> 10-07 23:24:39.607 5240-5310/? I/octvm_klo: klo lock**

**Comment by anurse** [comment]
Can you try again with the latest version `0.1.0-preview2-35174` ? If it continues to repro in the latest version can you let us know your Android API level?

Also, would you be able to post a project that reproduces the issue? That would help us identify what is different about your scenario from our tests so we can identify the problem :).

**Comment by devrajeev** [comment]
> Can you try again with the latest version `0.1.0-preview2-35174` ? If it continues to repro in the latest version can you let us know your Android API level?
> 
> Also, would you be able to post a project that reproduces the issue? That would help us identify what is different about your scenario from our tests so we can identify the problem :).

I have tried with  'com.microsoft.aspnet:signalr:0.1.0-preview2-35174' this also found same issue

I am using API level - 26


```
0-08 23:54:24.375 3044-3044/? W/Binder:1475_3: type=1400 audit(0.0:32866): avc: denied { ioctl } for path="socket:[5763791]" dev="sockfs" ino=5763791 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
10-08 23:54:24.375 3044-3044/? W/Binder:1475_3: type=1400 audit(0.0:32867): avc: denied { ioctl } for path="socket:[5763791]" dev="sockfs" ino=5763791 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
10-08 23:54:24.398 31668-31668/com.cabieo.cabieoapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I>
10-08 23:54:24.398 31668-31668/com.cabieo.cabieoapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I>
10-08 23:54:24.403 31668-31668/com.cabieo.cabieoapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I>
10-08 23:54:24.412 31668-31668/com.cabieo.cabieoapp D/AndroidRuntime: Shutting down VM
10-08 23:54:24.609 31668-31745/com.cabieo.cabieoapp D/FA: Logging event (FE): app_exception(_ae), Bundle[{firebase_event_origin(_o)=clx, _r=1, firebase_screen_class(_sc)=Dashboard, firebase_screen_id(_si)=-7937857469536167886, timestamp=1539023064416, fatal=1}]
    
    --------- beginning of crash
10-08 23:54:24.617 31668-31668/com.cabieo.cabieoapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cabieo.cabieoapp, PID: 31668
    java.lang.NoClassDefFoundError: com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I
        at com.microsoft.aspnet.signalr.CallbackMap.put(CallbackMap.java:15)
        at com.microsoft.aspnet.signalr.HubConnection.on(HubConnection.java:281)
        at com.cabieo.cabieoapp.Fragments.ChatHomeFragment$1.run(ChatHomeFragment.java:101)
        at java.lang.Thread.run(Thread.java:818)
        at com.cabieo.cabieoapp.Fragments.ChatHomeFragment.onCreateView(ChatHomeFragment.java:125)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5571)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
```

**Comment by mikaelm12** [comment]
I'll investigate!

**Comment by devrajeev** [comment]
> I'll investigate!

Sure Thanks!

I tried with API Version 28 same issue is there.

**Comment by devrajeev** [comment]
Just checked, It's working fine with Emulator but not working on real device, which is having Android OS Version 6.1.

If you need my help in reproduce the issue, please let me know, can have screen share.

My Emulator configuration where it is running fine.

> Name: Nexus_6_API_25
> 
> CPU/ABI: Google APIs Intel Atom (x86)
> 
> Path: /Users/rajeev/.android/avd/Nexus_6_API_25.avd
> 
> Target: google_apis [Google APIs] (API level 25)
> 
> Skin: nexus_6
> 
> SD Card: 100M
> 
> hw.dPad: no
> 
> hw.lcd.height: 2560
> 
> runtime.network.speed: full
> 
> hw.accelerometer: yes
> 
> hw.device.name: Nexus 6
> 
> vm.heapSize: 256
> 
> skin.dynamic: yes
> 
> hw.device.manufacturer: Google
> 
> hw.lcd.width: 1440
> 
> hw.gps: yes
> 
> hw.initialOrientation: Portrait
> 
> image.androidVersion.api: 25
> 
> hw.audioInput: yes
> 
> image.sysdir.1: system-images/android-25/google_apis/x86/
> 
> tag.id: google_apis
> 
> showDeviceFrame: yes
> 
> hw.camera.back: virtualscene
> 
> hw.mainKeys: no
> 
> AvdId: Nexus_6_API_25
> 
> hw.camera.front: emulated
> 
> hw.lcd.density: 560
> 
> avd.ini.displayname: Nexus 6 API 25
> 
> hw.arc: false
> 
> hw.gpu.mode: auto
> 
> hw.device.hash2: MD5:984dbf66b1aaafcdb7e89573ffb74b46
> 
> hw.ramSize: 1536
> 
> hw.trackBall: no
> 
> PlayStore.enabled: false
> 
> fastboot.forceColdBoot: no
> 
> hw.battery: yes
> 
> hw.cpu.ncore: 2
> 
> hw.sdCard: yes
> 
> tag.display: Google APIs
> 
> runtime.network.latency: none
> 
> hw.keyboard: yes
> 
> hw.sensors.proximity: yes
> 
> disk.dataPartition.size: 800M
> 
> hw.sensors.orientation: yes
> 
> avd.ini.encoding: UTF-8
> 
> hw.gpu.enabled: yes

**Comment by devrajeev** [comment]
> I'll investigate!

Hey, It's crashing/throwing exception on Android Version 6 (marshmallow).
Kindly provide fixes or work around, I am in little hurry.

Thanks

**Comment by bradygaster** [comment]
cc @mikaelm12

**Comment by mikaelm12** [comment]
The Preview 3 version of the Java client, version 1.0.0-preview3-35501, should work with Android API level 26 and higher. (The RTM version should work with levels 16 and higher fyi). Let us know if you have issues with the preview 3 client

**Comment by anurse** [comment]
We believe this is fixed in the RTM version of the Java client. We now support as low as API level 16 (though API Level 21 or later is required for TLS 1.2 support). Please feel free to comment/re-open if this issue still occurs in the final release (coming before the end of the year) and we can investigate further.
