### ISSUE TITLE
Ensure an EndPoint can properly time-out waiting for Client to close

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#31]
If an EndPoint closes its output Channel, it needs to be able to time-out waiting for the Client to close the input channel. I think this should work, but I want to write a few tests of it, and make sure the transports behave properly.

**Comment by davidfowl** [comment]
What does it do today?

**Comment by anurse** [comment]
The main ungraceful case is if the server app fails, we send a close frame and stop processing input. If the client socket stays alive but never actually sends it's close frame, we should probably time out. It's a very edge case though.

Most of the other disgraceful shutdown cases are covered in #35 now.

**Comment by anurse** [comment]
I've updated this issue, edited the description in place. @muratg I think we should look at this in Preview. I have some thoughts.

**Comment by anurse** [comment]
Moving back to 1.0.0. It does appear that we signal the Channels appropriately, which is what I wanted to verify in this milestone. We'll want a good battery of end-to-end tests that verify these connection behaviors, but we're not there yet.
