### ISSUE TITLE
asp.net core 2.1 signlar js client doesn't work in Safari

### ISSUE THREAD

**Issue by NGancevich** [aspnet/SignalR#3106]
Hi. I have trouble with connecting to signalr using safari browser. I'm getting error:
WebSocket handshake: 'Connection' header is missing . It's working in other browsers. I don't specify protocol directly. 

connection = new signalR.HubConnectionBuilder()
            .withUrl("/atsHub")
            .configureLogging(signalR.LogLevel.Information)
            .build();

connection.start().catch(function(err) {
            console.error(err.toString());
        });

Please advice.

**Comment by anurse** [comment]
Can you collect client-side logs as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) ? Also, what OS is your server running on?

**Comment by NGancevich** [comment]
>           Also, are you hosting the server behind a proxy?

No. I don't use

**Comment by NGancevich** [comment]
I'm using Safari 5.1.7 on windows 10.  Server: windows 2012R2 , IIs 8.5.9600

**Comment by anurse** [comment]
> I'm using Safari 5.1.7 on windows 10

Safari for **Windows**? That's not really a supported browser any more (Apple no longer updates it) and Safari 5 is very out of date. We support recent versions of the "evergreen browsers" (Safari, Chrome, Firefox, Edge) and IE 11. Old versions of Safari and other browsers are not supported.

**Comment by NGancevich** [comment]
I used Safari 5 because wanted to emulate my iPad. It has been working on my iPad when I used classic signalR

**Comment by NGancevich** [comment]
Ok for closing.

**Comment by anurse** [comment]
> I used Safari 5 because wanted to emulate my iPad

Safari for Windows is not a good way to emulate an iPad. It's very out of date

> If I understood correctly it won't work on my old iPad

SignalR should work just fine on most iPads as long as you're running the latest Apple-supported version of iOS for the device.

**Comment by stroumphs** [comment]
I got the same issue with this.
After debug a little bit. The long polling transport type is working for Safari 5.x on windows and not working for Websocket type.
Have problem on handsake. But I cannot find the way to handle onclose event of websocket implement in WebsocketTransport class.
In my case, if I detect websocket not working i will change the transport type to long polling and init the new connection.

Are there any hints for this way ?
