### ISSUE TITLE
Invoking while in a On response function will cause deadlock (?)

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#3125]
_From @farlock85 on Friday, 12 October 2018 22:59:16_

Consider this code:

`
    public class S
    {
        private readonly HubConnection _hubConnection;

        public S()
        {
            _hubConnection = new HubConnectionBuilder()
                             .WithUrl("")
                             .ConfigureLogging(logging => {
                                 logging.AddConsole();
                                 logging.SetMinimumLevel(LogLevel.Trace);
                             })
                             .Build();

            _hubConnection.On<DataRequest>("DataFetch", DataFetch);
        }

        private void DataFetch(DataRequest dataRequest)
        {
            var response = new DataResponse
            {
                RequestId = dataRequest.RequestId
            };

            var dataResponse = Send<DataResponseResult>("DataResponse", response)
                .Result;
        }
        
        public async Task<T> Send<T>(String methodName, params Object[] parameters)
        {
            Log.Information("Sending {methodName} request", methodName);

            try
            {
                var response = await _hubConnection.InvokeCoreAsync<T>(methodName, parameters, new CancellationTokenSource(30000).Token);

                Log.Information("Received {methodName}", methodName);

                return response;
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Error sending {methodName}", methodName);
            }

            return default(T);
        }
    }
`

the Send is called from the DataFetch which comes from _hubConnection.On. 

The trace logger doesn't mention anything special, but you will see that it hangs on InvokeCoreAsync until it times out.

When I wrap the Send method in a Task.Factory.StartNew it works fine.

_Copied from original issue: SignalR/SignalR#4246_

**Comment by anurse** [comment]
_From @anurse on Saturday, 13 October 2018 00:00:11_

The `HubConnectionBuilder` API is for ASP.NET Core SignalR. This repo is for ASP.NET SignalR. I'll move the issue to the appropriate repo for you.

**Comment by davidfowl** [comment]
Yes, this a know issue, we should document it for now until we come up with a fix.

**Comment by BrennanConroy** [comment]
Same issue basically: https://github.com/aspnet/SignalR/issues/3159
