### ISSUE TITLE
Samples need serious work

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#313]
Our samples needs a lot of work. The UIs are bad and the chat sample has very little functionality. The chat sample in particular needs some love.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/issues/1

**Comment by moozzyk** [comment]
+ the C# sample cannot connect to the chat app due to auth

**Comment by RichiCoder1** [comment]
@BrennanConroy I feel like this may be a silly question, but is this something ya'll are taking contributions on?

**Comment by seriouz** [comment]
@RichiCoder1 they'll take on everything contributions 😄

**Comment by muratg** [comment]
@RichiCoder1 Yup, we do :)

**Comment by TheGatsby81** [comment]
As a complete newbie to typescript, I found I couldn't generate the signalr-client.js script with the download. I followed the instructions on the website to no avail.

**Comment by moozzyk** [comment]
@TheGatsby81 - have you tried the npm package - once you run `npm install` you will be able to find signalr-client.js in node_modules? Or if you need to build yourself try this: https://github.com/aspnet/SignalR/issues/165#issuecomment-275930704.

**Comment by TheGatsby81** [comment]
Simple, thanks!

**Comment by hanvyj** [comment]
Are there any samples for using the client? I've installed the npm but I can't find any client samples in the samples directory in git.

**Comment by moozzyk** [comment]
@hanvyj - if you are looking for the js client sample here are the samples:
- https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/Views/Home/Index.cshtml#L17-L39
- https://github.com/aspnet/SignalR/blob/dev/samples/SocketsSample/wwwroot/hubs.html#L100
- https://github.com/moozzyk/SignalR-Client-Swift/blob/master/TestServer/wwwroot/index.html#L26

**Comment by hanvyj** [comment]
Great, thanks, I was just being dumb.

**Comment by davidfowl** [comment]
Use the https://github.com/aspnet/SignalR-samples/ repository
