### ISSUE TITLE
Duration requires android api level 26 or higher

### ISSUE THREAD

**Issue by DHosseiny** [aspnet/SignalR#3141]
Duration class used here added in java 8 and android not support java 8 completely in api level lower than 26. Please use other way to implement duration. here is exception line [HubConnection.java:50](https://github.com/aspnet/SignalR/blob/defbadb26b4224d5025549992fc5ae4e95e0d288/clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java#L50)
Here is first exception lines:
`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
        at com.microsoft.signalr.HubConnection.<init>(HubConnection.java:50)`
to produce this issue just create a HubConnection in android app with api lower than 26.
version: 99.99.99-dev

**Comment by anurse** [comment]
FYI for other maintainers: Android API Level 26 corresponds to Android Oreo (8.0)

I think it makes sense to avoid `Duration` given this. Thanks for the report!

**Comment by anurse** [comment]
Duration will be removed in the RTM build of the Java Client. We are continuing to evaluate Android API level in #3143
