### ISSUE TITLE
Verify and document minimum Android API Level

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#3143]
Currently, because of #3141, the minimum [Android API Level](https://source.android.com/setup/start/build-numbers) we supports is API Level 26 (Android 8.0.0 "Oreo").

We should try to move this down as far as we reasonably can. If anyone is using the Java Client in an Android app, it would be great to hear from your what your minimum API Level is so we know what level would reach the most users! Please comment on this thread with the minimum API Level you require for your application.

Once we've decided on a minimum level, we should investigate options for validating that our library sticks with that API level, and we should publish the minimum level in the [docs for the Java Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-2.2)

**Comment by rvlajcev** [comment]
minSdkVersion 25 here
SignalR: 0.1.0-preview2-35174
No issues at all.

You have to include
```
compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
}
```

in build.gradle (app)

**Comment by mikaelm12** [comment]
I'm starting to investigate this issue and came across this
![androidapicompat](https://user-images.githubusercontent.com/4809660/47122532-0808f980-d22c-11e8-9e6d-9f1055b1a084.png)

**Comment by mikaelm12** [comment]
This means for getting to 23 we'll have to remove the `FunctionalInterface` tags and the references to `Consumer<T>` that we have

**Comment by Tragetaschen** [comment]
My project is currently targeting Android 7.0 - API level 24

**Comment by vahidarr** [comment]
Android 4.4.2 with api 17 is best option because android developer that write app for all group of people or lets say with general purpose need api level 17

**Comment by dradoicic** [comment]
Hi all,
In our project, the minimum API level is 19 so 17-19 would be excellent. The tricky part is to migrate our project to a higher API level just to be able to continue development while we are waiting for lower API level compatibility. Can you share timeline, when we can expect this API change?

**Comment by anurse** [comment]
> Can you share timeline, when we can expect this API change?

We're evaluating this for the ASP.NET Core 2.2 release, which is planned to be released by the end of the year.

**Comment by dradoicic** [comment]
@anurse Clear. Thank you for the info.

**Comment by Tooto** [comment]
Hi!  I work in big mobile outsource company.
We have a lot of projects.
New project supports api level 19.
Old projects - api level 17.

**Comment by anurse** [comment]
We've gotten our testing mostly complete and can say the following:

* The SignalR Java Client will run on Android **API Level 16 and above**.
* Connecting through the Azure SignalR Service will require Android **API Level 20 and above** because the Azure SignalR Service requires **TLS 1.2** and does not support **SHA-1**-based cipher suites. Android added support for SHA-1 cipher suites in API Level 20.

**Comment by anurse** [comment]
Our testing here is complete and the docs issue is filed to update the docs when RTM is ready. I'm going to close this issue now.
