### ISSUE TITLE
(.NetCore2.1, angular5) : Error: Failed to complete negotiation with the server: Error: Not Found

### ISSUE THREAD

**Issue by ad-el** [aspnet/SignalR#3150]
Errors:
POST http://localhost:4200/streamHub/negotiate 404 (Not Found)
Error: Failed to complete negotiation with the server: Error: Not Found

** Versions of Server-Side NuGet Packages:**
Microsoft.AspNetCore.App (2.1.5) 
Microsoft.AspNetCore.SignalR.Core (1.0.4)
*** Versions of Client-Side NuGet/NPM Packages:**
"@aspnet/signalr": { "version": "1.0.4", }
*** Are you using the C# client or the JavaScript client:**
JavaScript
*** The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):** 
II Express
*** The Operating System on the Server and Client (Windows/Linux/macOS):**
Windows 7 Home Premium
*** The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):**
Chrome

Using signalR with angular5 I can't establish connection between client and server: Here are my files:
Startup.cs:
```
public void ConfigureServices(IServiceCollection services)
        {
            // (...)
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAllPolicy",
                      builder =>
                      {
                          builder.AllowAnyOrigin()
                                 .AllowAnyHeader()
                                 .AllowAnyMethod()
                                 .AllowCredentials()
                                 .WithOrigins("http://localhost:4200")
                                 ;
                      });
            });

            services.AddSignalR();
            services.AddAutoMapper();
            services.AddMvc()
                .AddJsonOptions(options =>
                {
                    options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
                } 
            );
            // (...)
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseCors("AllowAllPolicy");

            app.UseSignalR(route =>
            {
                route.MapHub<StreamHub>("/streamHub");
            });
            app.UseAuthentication();
            app.UseMvc();
        }
```
StreamHub.cs :
```
using Microsoft.AspNetCore.SignalR;
using System.Threading.Channels;
using System.Threading.Tasks;

namespace GST.Api.Hubs
{
    public class StreamHub : Hub
    {
        public ChannelReader<int> Counter(int count, int delay)
        {
            var channel = Channel.CreateUnbounded<int>();
            _ = WriteItems(channel.Writer, count, delay);
            return channel.Reader;
        }

        private async Task WriteItems(ChannelWriter<int> writer, int count, int delay)
        {
            for (var i = 0; i < count; i++)
            {
                await writer.WriteAsync(i);
                await Task.Delay(delay);
            }
            writer.TryComplete();
        }
    }
}
```
signalr.service.ts : 
```
import { Injectable, EventEmitter } from '@angular/core';
import { HubConnection, HubConnectionBuilder } from '@aspnet/signalr';
//import * as signalR from '@aspnet/signalr';

@Injectable()
export class SignalrService {

  connectionEstablished = new EventEmitter<Boolean>();

  private connectionIsEstablished = false;
  private streamHubConnection: HubConnection;

  constructor() {
    this.createConnection();
    this.registerOnServerEvents();
    this.startConnection();
  }

  private createConnection() {
    this.streamHubConnection = new HubConnectionBuilder()
      .withUrl('/streamHub')
      .build();
  }

  private registerOnServerEvents() {
    this.streamHubConnection.on("eventFromServer", () => {
      console.log('eventFromServer received');
    });
  }

  private startConnection() {
    this.streamHubConnection
      .start()
      .then(() => {
        this.connectionIsEstablished = true;
        console.log('stream connection started');
        this.connectionEstablished.emit(true);
      }).catch(err => { console.log(err); });
  }

  public startStreaming() {
    this.streamHubConnection.stream("Counter", 10, 500)
      .subscribe({
        next: (item) => { console.log(item); },
        complete: () => { console.log('streaming completed'); },
        error: (err) => { console.log(err); },
      });
  }
}
```

**Comment by anurse** [comment]
If you're getting a 404 from `/negotiate` it's likely that you either have a routing configuration problem or are hitting the wrong URL. I presume your angular app is on the same server (i.e. you aren't using Angular's dev server?).

**Comment by ad-el** [comment]
I run angular site using ng serve angular-cli command. WebApi project runs on VS2017 IIS Expres. Both run on the same machine. Url which is hit: POST http://localhost:4200/streamHub/negotiate. Configuration shortly: 
services.AddSignalR();
app.UseSignalR(route =>
            {
                route.MapHub<StreamHub>("/streamHub");
            });
as it is described here: https://docs.microsoft.com/pl-pl/aspnet/core/signalr/hubs?view=aspnetcore-2.1

Client configuration is shown inside SignalrService.createConnection() method. Url POST http://localhost:4200/streamHub/negotiate is hit if this.streamHubConnection.start() is reached.

I created new clean angular5 site using angular-cli 'ng new testsite' command and new WebAPI .net core 2.1 application. Then I installed signalr for WebAPI project and for the angular5 site project and the issue exists also here.

**Comment by anurse** [comment]
> I run angular site using 'ng serve' angular-cli command.

So that would be a different server then. Your HTML/JavaScript content (served by `ng serve`) is at `http://localhost:4200` but your ASP.NET Core app is running on a different port number. You can't just use `/streamHub` because that means it will try to use `http://localhost:4200/streamHub` as the URL but the server is actually running on a different port. You need to look at what port your ASP.NET Core site is running on and use the full URL for the hub when creating your HubConnection on the client.
