### ISSUE TITLE
Microsoft.AspNetCore.SignalR.HubConnectionContext[5] and Failed connection handshake.

### ISSUE THREAD

**Issue by clintnetwork** [aspnet/SignalR#3151]
Hello,

NPM SignalR version :  "@aspnet/signalr": "^1.0.4"
It's running on ArchLinux
Using the default Kestrel server*
Using Firefox but the issue is everywhere, it's a server side issue

I'm running a SignalR project with **Microsoft.AspNetCore.SignalR** (https://github.com/clintnetwork/stratis-guru-v2) and i have a lot of this errors :
```fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]
      Failed connection handshake.
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]
      Failed connection handshake.
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]
      Failed connection handshake.
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]
      Failed connection handshake.
```

I have commented this:
app.UseHsts();
app.UseHttpsRedirection();

Thank you !

**Comment by BrennanConroy** [comment]
Could you please follow the [issue template](https://github.com/aspnet/SignalR/blob/release/2.2/.github/ISSUE_TEMPLATE.md) and [diagnostics guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) so we can help solve your issue.

**Comment by clintnetwork** [comment]
I will try yes, thank you

**Comment by clintnetwork** [comment]
Ok so i've updated to @aspnet/signalr@next but the problem is the same, apparently all works on localhost:7777 but with the problem appear when i use with nginx

**Comment by anurse** [comment]
Can you provide the network trace requested above? Also, can you post your nginx config? If it only fails behind nginx, it's likely there's something wrong with the config there.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by clintnetwork** [comment]
This nginx rules has fix the problem :
    proxy_set_header Connection $http_connection;
