### ISSUE TITLE
Non-browser client fails to create secure connection "1.1.0-preview3-35497"

### ISSUE THREAD

**Issue by Havunen** [aspnet/SignalR#3168]
Hi

There seems to be bug in preview version of npm `"@aspnet/signalr": "^1.1.0-preview3-35497"` when using SSL connection ( https / secure socket ). Our SignalR server is not accepting non secure connections and defining secure url does not use secure connection on non browser environment. 

Tested in
`Windows 10 + NodeJS  v10.11.0`

If you look into source code, it hard coded to use `"http"` client when using nodeJS. See here:

https://github.com/aspnet/SignalR/blob/a51eec7a1d76272721da7437a273b3c6c74c581a/clients/ts/signalr/src/DefaultHttpClient.ts#L10-L13

https://github.com/aspnet/SignalR/blob/a51eec7a1d76272721da7437a273b3c6c74c581a/clients/ts/signalr/src/NodeHttpClient.ts#L4

In NodeJS to open secure http connection it needs `https` client

Steps to reproduce:

index.js
```js
const signalR = require('@aspnet/signalr');

connection = global._conn = new signalR.HubConnectionBuilder().withUrl(
  'https://URL'
).build();

// Add connection listeners....

connection.start().catch(err => {console.error(err);});
```

Server responds http https redirection answer: `Error: Moved Permanently: 301 `

If I change source code to use `require("https");` instead of `require("http");`  it goes through.
But fails to Websocket connection `Error: Failed to start the transport 'WebSockets': null`

EDIT: This is probably non relevant
to fix that I changed:
https://github.com/aspnet/SignalR/blob/a51eec7a1d76272721da7437a273b3c6c74c581a/clients/ts/signalr/src/WebSocketTransport.ts#L46

`http => https` and `ws => wss`

Without secure connection all works as expected

**Comment by anurse** [comment]
Good catch. We should import both modules in `NodeHttpClient` and select the appropriate one based on the URL.

**Comment by anurse** [comment]
Your later change to the `url.replace` shouldn't actually be necessary since we intentional don't put the `:` in the regex, so if the URL is `https://foo`, the regex will replace `http` with `ws` and you'll end up with `wss://foo` (because the `s` from `https` was left behind). Is this not working for you? It works in our tests so I want to make sure that if there's an issue we update our tests.

**Comment by anurse** [comment]
> If I change source code to use `require("https");` instead of `require("http");` it goes through.
> But fails to Websocket connection `Error: Failed to start the transport 'WebSockets': null`

Can you enable client-side logging and collect a network trace from the client so we can see how the server is responding to the WebSocket request? There are some tips on how to do this in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)

**Comment by Havunen** [comment]
Awesome, thank you :+1:

**Comment by Havunen** [comment]
Hey,

I compiled latest code from 2.2 branch, and the fix here is not working:

In my machine, Mac osx and Ubuntu url is object with following properties:
```
URL {
  href:
   'https://orangutan.service.signalr.net/client/negotiate?hub=gorillahub&asrs.op=%2FgorillaHub',
  origin: 'https://orangutan.service.signalr.net',
  protocol: 'https:', // NOTICE THE COLON
  username: '',
  password: '',
  host: 'orangutan.service.signalr.net',
  hostname: 'orangutan.service.signalr.net',
  port: '',
  pathname: '/client/negotiate',
  search: '?hub=gorillahub&asrs.op=%2FgorillaHub',
  searchParams:
   URLSearchParams { 'hub' => 'gorillahub', 'asrs.op' => '/gorillaHub' },
  hash: '' }
```


https://github.com/aspnet/SignalR/blob/release/2.2/clients/ts/signalr/src/NodeHttpClient.ts#L37-L41
