### ISSUE TITLE
How to map userId to connectionId?

### ISSUE THREAD

**Issue by AwanesowArtem** [aspnet/SignalR#3176]
Hi all,
How to map userId to conenctionId in SignalR core?

In previous version there was PrincipalUserIdProvider with it i was able to map userId to connectionId.
What is the way to do it in SignalR Core?

**Comment by anurse** [comment]
Do you want to change how the user ID is assigned? Our docs has a section on [Users in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1#users-in-signalr) that explains how you can do this. ASP.NET Core SignalR has an `IUserIdProvider` as well and you can provide your own implementation of that interface to customize how the user ID is assigned.

**Comment by AwanesowArtem** [comment]
> Do you want to change how the user ID is assigned? Our docs have a section on [Users in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1#users-in-signalr) that explains how you can do this. ASP.NET Core SignalR has an `IUserIdProvider` as well and you can provide your own implementation of that interface to customize how the user ID is assigned.

Thank you. But how 

public class NameUserIdProvider : IUserIdProvider
{
    public string GetUserId(HubConnectionContext connection)
    {
        return connection.User?.FindFirst(ClaimTypes.Name)?.Value;
    }
}

**Comment by AwanesowArtem** [comment]
> Do you want to change how the user ID is assigned? Our docs have a section on [Users in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1#users-in-signalr) that explains how you can do this. ASP.NET Core SignalR has an `IUserIdProvider` as well and you can provide your own implementation of that interface to customize how the user ID is assigned.

Thank you!
