### ISSUE TITLE
Build failing :(

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#318]
Fresh clone of dev fails to build

`Starting test execution, please wait...
[xUnit.net 00:00:00.7905770]   Discovering: Microsoft.AspNetCore.SignalR.Tests
[xUnit.net 00:00:01.5402407]   Discovered:  Microsoft.AspNetCore.SignalR.Tests
[xUnit.net 00:00:01.8044987]   Starting:    Microsoft.AspNetCore.SignalR.Tests
Starting test server...
[xUnit.net 00:00:02.9269007]     Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.ConnectionCanSendAndReceiveMessages(transportFactory: Func`2 { Method = Microsoft.AspNetCore.Sockets.Client.ITransport <get_Transports>b__5_1(Microsoft.Extensions.Logging.ILoggerFactory), Target = <>c { } }) [FAIL]
[xUnit.net 00:00:02.9282311]       System.TypeLoadException : Could not load type 'System.IO.Pipelines.IBufferPool' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
[xUnit.net 00:00:02.9296568]       Stack Trace:
[xUnit.net 00:00:02.9308239]            at System.IO.Pipelines.StreamExtensions.AsPipelineWriter(Stream stream)
[xUnit.net 00:00:02.9309223]         /Users/mikaelm/Desktop/PrinceDev/AspNet/signalr-dev/src/Microsoft.AspNetCore.Sockets.Client/LongPollingTransport.cs(209,0): at Microsoft.AspNetCore.Sockets.Client.LongPollingTransport.<SendMessages>d__19.MoveNext()
[xUnit.net 00:00:02.9309871]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.9310351]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.9310835]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.9311824]            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[xUnit.net 00:00:02.9312747]         /Users/mikaelm/Desktop/PrinceDev/AspNet/signalr-dev/src/Microsoft.AspNetCore.Sockets.Client/Connection.cs(298,0): at Microsoft.AspNetCore.Sockets.Client.Connection.<SendAsync>d__36.MoveNext()`

**Comment by mikaelm12** [comment]
@BrennanConroy @anurse @moozzyk @davidfowl

**Comment by davidfowl** [comment]
Looking

**Comment by davidfowl** [comment]
It's fixed now
