### ISSUE TITLE
How to use Windows Authentication on version 1.0.4?

### ISSUE THREAD

**Issue by DannyBoyNg** [aspnet/SignalR#3188]
### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: 1.0.4
* Versions of Client-Side NPM Packages: 1.0.4
* Are you using the C# client or the JavaScript client: JavaScript/Typescript Client
* The Server you are using: IIS Express 
* The Operating System on the Server: Windows
* The Operating System on the Client: Windows
* The Browser on the client, if using the JavaScript client: Chrome

How to use Windows Authentication on version 1.0.4?

On previous versions you could use: 
```
    var connection = new HubConnectionBuilder()
    .WithUrl("https://example.com/myhub", options => {
        options.UseDefaultCredentials = true;
    })
    .Build();
```

That does not seem to be available on version 1.0.4. The message I get from the server is 401 unauthorized. The regular AspNetCore Web Api requests work fine with Windows Authentication. Only the SignalR requests I cannot get working with WIndows Authentication.

**Comment by DannyBoyNg** [comment]
I just wanted to add some more info. It is the OPTIONS pre-flight request that is not getting through. Even though CORS is set to allow any method. The response is 401 unauthorized.

This is the endpoint: https://localhost:44300/myHub/negotiate

```
           services
                .AddCors(options =>
                {
                    options.AddPolicy("CorsPolicy", builder => 
                        builder.AllowAnyOrigin()
                            .AllowAnyMethod()
                            .AllowAnyHeader()
                            .AllowCredentials());
                });
            services
                .AddAuthentication(IISDefaults.AuthenticationScheme);
            services
                .AddSignalR();
            services
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
                .AddJsonOptions(options =>
                {
                    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                });
-------------------------------------------------------
            app.UseCors("CorsPolicy");
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseSignalR(routes =>
            {
                routes.MapHub<MyHub>("/myHub");
            });
            app.UseMvc();
```

**Comment by BrennanConroy** [comment]
There is a nice blog post explaining exactly how to handle CORS + Windows Auth in IIS!
https://blogs.iis.net/iisteam/getting-started-with-the-iis-cors-module

**Comment by DannyBoyNg** [comment]
Thanks Brennan for the blog post but the blog post was written for Asp.Net not Asp.Net Core. It did not contain the information needed to solve the problem.

**Comment by BrennanConroy** [comment]
The blog post is written for hosting an app in IIS, nothing specific to ASP.NET or ASP.NET Core. The same configuration will apply for both.

What information are you missing?

**Comment by anurse** [comment]
Unfortunately because IIS's Windows Auth happens before ASP.NET Core runs, the ASP.NET Core CORS implementation isn't able to process the `OPTIONS` request (because the browser won't send your Windows credentials with it). The only real solution here is to use the IIS CORS module since it runs **before** Windows Authentication and can process the unauthenticated CORS request.

**Comment by DannyBoyNg** [comment]
My bad. This is my first project doing windows authentication. I'll give the blog post another try. I'll report back my findings.

**Comment by DannyBoyNg** [comment]
Just a quick question. Do you know how to make it work on IIS express. The blog post works great for IIS but my development environment uses IIS express. I can't figure out how to make it work for IIS express.

**Comment by anurse** [comment]
Not off hand. I believe you can do the same, you'll just have to find the appropriate config files. @shirhatti, are there any docs about enabling the IIS CORS module *on IIS Express* specifically?

@DannyBoyNg Another option you can use is to configure IIS to allow anonymous users, then add middleware *after* the `UseCors` middleware that blocks anonymous users. Then, anonymous `OPTIONS` requests would go through and get to `UseCors` (where they would be handled) but if a non-`OPTIONS` request came in, it would pass through `UseCors` and hit your middleware that blocks it. It's a bit of a hack, but it would let you continue to use ASP.NET Core CORS with Windows Auth.

**Comment by DannyBoyNg** [comment]
@anurse Thank you for your solution. It solves the problem of the anonymous OPTIONS request. There doesn't seem to be another solution, at least that I could find.

Case closed.
