### ISSUE TITLE
Azure SignalR chrome issue

### ISSUE THREAD

**Issue by sandipbhavsar** [aspnet/SignalR#3219]
I am working on asp.net core 2.1 API application with azure signalR service. When I open application in chrome, It is trying to connect again and again in loop.

**Comment by BrennanConroy** [comment]
Could you collect a network trace with the issue? https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#network-traces

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
