### ISSUE TITLE
What is the proper way to use raw ConnectionHandler for WebSockets to process individual messages?

### ISSUE THREAD

**Issue by slipdef** [aspnet/SignalR#3220]
The below code worked fine for SignalR 1.0.0 alpha 1:
```
class MyConnectionHandler : ConnectionHandler
        {
            public override async Task OnConnectedAsync(ConnectionContext connection)
            {
                while (true)
                {
                    var result = await connection.Transport.Input.ReadAsync();

                    var buffer = result.Buffer;
                    if (result.IsCompleted)
                        break;

                    var data = buffer.ToArray();
                    var jsonMessage = Encoding.Default.GetString(data);
                   // process message here

                    connection.Transport.Input.AdvanceTo(result.Buffer.End);
                }
            }
        }
```

But after abstracting to pipes I don't get full individual messages here, instead ReadAsync returns me partial message if it's greater than 2048 bytes, on the next iteration it returns remaining part of the message. 
I would be OK to aggregate on my side but I don't have any access to WebSocketReceiveResult.EndOfMessage here to figure out when a message ends. I see HubConnectionHandler handles that by using RecordSeparator. Is there anyway to handle that without introducing custom separator between messages?

The more of an issue is when a message is less than 2048 byte. I'm receiving a combined output from ReadAsync. Like sending "1" and "2" as individual messages results in receiving "12" sometimes (can be easily reproduced by adding some artificial delay before ReadAsync invocation).

**Comment by davidfowl** [comment]
You need to invent your own protocol. The ConnectionHandler only handles streaming data and as a result, there's no way to access the EndOfMessage property.

You need to use raw [websockets](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.1) if you want the full fidelity of the protocol.

**Comment by anurse** [comment]
We don't plan to separate them, but we do fully intend to allow ConnectionHandlers to be used outside of SignalR. It's a layering thing, we want SignalR to be able to run indepdently from the `Http.Connections` layer.

**Comment by slipdef** [comment]
Clear, thanks.
