### ISSUE TITLE
Where can I download com.microsoft.signalr(for Java)?

### ISSUE THREAD

**Issue by akira32** [aspnet/SignalR#3228]
I download Java client. But I lose the definition of com.microsoft.signalr. Does somebody know where I download com.microsoft.signalr?

**Comment by anurse** [comment]
It's available from the Maven Central repository. You can add a dependency to your Maven POM file or Gradle build file. See the documentation on the [SignalR Java Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-2.2) for more information.

**Comment by akira32** [comment]
anurse, Thank you. I have another confuse the persistent connection disappears in asp.net core?

**Comment by anurse** [comment]
Correct, ASP.NET Core SignalR does not currently include an equivalent for PersistentConnection.

**Comment by akira32** [comment]
I write a pom.xml in root fo JavaFX(Intellij). Is the pom.xml correct?

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>jpademo</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <dependencies>

        <dependency>
            <groupId>com.microsoft.signalr</groupId>
            <artifactId>signalr</artifactId>
            <version>1.0.0-preview3-35501</version>
        </dependency>
        <dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
            <version>2.2.2</version>
        </dependency>

    </dependencies>
</project>
```

**Comment by anurse** [comment]
It looks fine to me, what error are you getting?

**Comment by akira32** [comment]
This pom.xml I used is correct. This thread can be closed.
