### ISSUE TITLE
what's the difference signalr core vs signalr framework?

### ISSUE THREAD

**Issue by jasonliaocn** [aspnet/SignalR#3273]
I cannot find any document on this topic can you give some link tell the difference or on the wiki?
thanks.

**Comment by gfontorbe** [comment]
I think a good place to start would be on [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.1)

**Comment by anurse** [comment]
Closing as the document @gfontorbe linked has the comparison information you are looking for. If you have questions about the content in the doc, please post your feedback in the document itself by clicking the "Content Feedback" button in the "Feedback" section at the bottom of the document. We can clarify any questions you have and add them to the doc to help others.

**Comment by bradygaster** [comment]
Also added to the [FAQ](https://github.com/aspnet/SignalR/wiki/Frequently-Asked-Questions)
