### ISSUE TITLE
Windows Form for Core SignalR Client

### ISSUE THREAD

**Issue by akira32chen** [aspnet/SignalR#3287]
I created a Windows Form with Core SignalR Client.
In TcpConnection.cs appears three errors. I had download System.IO.Pipelines by Nuget. I cannot install System.IO, Visual Studio 2017 display that it does not find the System.IO.dll.

Does somebody know how to solve this problem?

```
'DuplexPipe' is inaccessible due to its protection level
'DuplexPipe.DuplexPipePair.Transport' is inaccessible due to its protection level
'DuplexPipe.DuplexPipePair.Application' is inaccessible due to its protection level
```

        public async Task<ConnectionContext> StartAsync()
        {
            await _socket.ConnectAsync(_endPoint);

            var pair = **DuplexPipe**.CreateConnectionPair(PipeOptions.Default, PipeOptions.Default);

            Transport = pair.**Transport**;
            _application = pair.**Application**;

            _ = ExecuteAsync();

            return this;
        }

_Originally posted by @akira32 in https://github.com/aspnet/SignalR/issues/3259#issuecomment-437272538_

**Comment by anurse** [comment]
TcpConnection is not officially supported, it is a sample. DuplexPipe is a helper type we produce, you can copy it from [the source](https://github.com/aspnet/SignalR/blob/release/2.2/src/Common/DuplexPipe.cs).

**Comment by akira32chen** [comment]
@anurse , Thank you! My problem is solved.
