### ISSUE TITLE
Replace Auth code when security helper is created

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#329]
Our Auth code is copied from Mvc AuthFilter, the code will be put in a common place that we can both use.
This is to track the replacement.
See: https://github.com/aspnet/Security/pull/1148

**Comment by davidfowl** [comment]
@BrennanConroy This is done right?

**Comment by BrennanConroy** [comment]
Not really, we have https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Http/Internal/AuthorizeHelper.cs and MVC has https://github.com/aspnet/Mvc/blob/c27b07ef3f8b07dfe1d1de38a8d7bf2d6a9298f4/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L107 they look very similar.

**Comment by davidfowl** [comment]
What is the plan? Is there one?

**Comment by BrennanConroy** [comment]
I don't know of any @HaoK

**Comment by davidfowl** [comment]
Ok I'm closing this.

**Comment by HaoK** [comment]
Yeah the policyEvaluator was the new shared helper, which SignalR is using now
