### ISSUE TITLE
Cannot send data if the connection is not in the 'Connected' State.

### ISSUE THREAD

**Issue by akousmata** [aspnet/SignalR#3294]
Doing a really simple call from the client to the server following [this article's](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#call-hub-methods-from-client) example.  When I originally set it up, I had the following code:

```
const transactionConnection =
    new signalR.HubConnectionBuilder()
           .withUrl("https://localhost:44313//TransactionHub")
           .configureLogging(signalR.LogLevel.Trace)
           .build();        

transactionConnection.on('ReceiveMessage', function (evt, transactionNotification) {
    if (!transactionNotification)
        return;
            
    // Do stuff
});

transactionConnection.start().catch(err => console.error(err.toString()));
transactionConnection.invoke('JoinGroup', 'ClientAccountTransaction').catch(err => console.error(err.toString()));
```
If I launch the page this way, I get the error in the title (client debug is attached).
[signalrdebug.txt](https://github.com/aspnet/SignalR/files/2573126/signalrdebug.txt)

It seemed like based on the order of the log messages, that the connection needed time to get established, so I added a button to the page with an on click event that calls:

`transactionConnection.invoke('JoinGroup', 'ClientAccountTransaction').catch(err => console.error(err.toString()));`

And that worked.  Unfortunately, there's no way I can present that to the client, this is all supposed to work under the hood.  Is my assumption correct about the timing of the calls and if so what do you recommend we do to work around this?

* Versions of Server-Side NuGet Packages:  1.0.1
* Versions of Client-Side NuGet/NPM Packages: 1.0.4
* Are you using the C# client or the JavaScript client: Javascript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): IIS Express
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome

**Comment by BrennanConroy** [comment]
This is fixed in the 1.1.0 preview builds, you can try them out, or if that isn't possible add a small delay between `start` and `invoke`.

**Comment by akousmata** [comment]
When do you anticipate releasing 1.1.0?

**Comment by BrennanConroy** [comment]
Soon is all I can say, https://github.com/aspnet/AspNetCore/wiki/Roadmap#schedule

**Comment by akousmata** [comment]
so the fix is in the server side code?

**Comment by BrennanConroy** [comment]
No, it's on the client side. It wasn't waiting for the handshake response before returning from start.

**Comment by akousmata** [comment]
I see, but you're going to time the release with .Net Core 2.2.

**Comment by davidfowl** [comment]
Looking at the above code though there's a bug where you're invoking after calling start without waiting on start to complete.

```JS
transactionConnection.start().catch(err => console.error(err.toString()));
transactionConnection.invoke('JoinGroup', 'ClientAccountTransaction').catch(err => console.error(err.toString()));
```

This is incorrect, it should be:

```JS
transactionConnection.start().then(() => {
    transactionConnection.invoke('JoinGroup', 'ClientAccountTransaction').catch(err => console.error(err.toString()));
});
```

**Comment by akousmata** [comment]
@BrennanConroy David's answer worked on my end.

**Comment by BrennanConroy** [comment]
Yeah, I missed that you weren't waiting for start to finish. Although you might see the issue occasionally still because of the bug I was referring to.
