### ISSUE TITLE
.NET Core SignalR - close connection logic

### ISSUE THREAD

**Issue by alex-user** [aspnet/SignalR#3297]
Hello all,

I use SignalR v1.0.3 for ASP.NET Core 2.1 and I have question about close connection logic.
For example consider small example step by step:
1 - Client opened connection
2 - After that, server started produce items to client
3 - Over time client close connection

What happens to the messages that were in the queue for sending?
1 - They be lost 
2 - The connection will be closed as soon as the remaining messages are sent

**Comment by anurse** [comment]
> They be lost

This is what will happen. Once the client closes the connection, any messages which have not been completely received by the client will be lost (even if we waited to ensure they were sent, that's no guarantee that they will arrive in time).

**Comment by alex-user** [comment]
@anurse thank you for your answer. 
We can implement additional logic in our application. But it would be great  do not closing the channel immediately. For example, using a timeout. Or detecting messages on the internal bus. In any case, the client can always forcibly break the connection.
