### ISSUE TITLE
Restarting TypeScript client does not resubscribe to subscriptions

### ISSUE THREAD

**Issue by twsouthwick** [aspnet/SignalR#3305]
### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: 1.0.3
* Versions of Client-Side NuGet/NPM Packages: 1.1.0-preview3-35497. We need a fix that's not in the latest released version for the JS client and reconnects
* Are you using the C# client or the JavaScript client: JavaScript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): Kestrel
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows/iOS/Android
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Edge/Chrome

We are seeing issues with subscriptions after a disconnect. We are handling disconnects by calling `HubConnection.start()` every 5 seconds or so. After we are reconnected, we are fine calling any method, but do not receive any messages. We are looking at handling resubscribing as part of the reconnection, but wanted to see if there are plans to handle resubscribing the client so that the observables can keep working.

Logs:
[server.log](https://github.com/aspnet/SignalR/files/2582705/server.log)
[client.log](https://github.com/aspnet/SignalR/files/2582706/client.log)
[network.har.txt](https://github.com/aspnet/SignalR/files/2582707/network.har.txt)

**Comment by mikaelm12** [comment]
> to handle resubscribing the client so that the observables can keep working

I'm assuming you're talking specifically about streaming invocations? Or are you seeing this behavior for setting up handlers for normal invocations? This is the expected behavior for the streaming scenario.

**Comment by twsouthwick** [comment]
Just to make sure I understand, for streaming scenario, it's expected that the client manually tracks what streams it is connected to and reconnect to each after restarting the connection.

**Comment by anurse** [comment]
Correct, if you are streaming (`.stream` method) and get disconnected, the stream should end (the `complete` method on your subscriber will be called). You have to re-start streams when you reconnect.

**Comment by twsouthwick** [comment]
hmm seems like I'm not using the right terms. We aren't using `.stream` - we're using `HubConnection.on(eventName)` and using rxjs to pipe it into an observable. Is that still expected?

**Comment by anurse** [comment]
Ok, that's different. Those should be reconnected. I was talking specifically about streaming method calls.
