### ISSUE TITLE
After update today to VS 15.9 iOS not working

### ISSUE THREAD

**Issue by sidatacom** [aspnet/SignalR#3307]
![unbenanntes bild](https://user-images.githubusercontent.com/43718498/48561951-6db2d900-e8f1-11e8-8f09-348e2505355e.png)

`[0:] Method not found: void System.Threading.Tasks.ValueTask`1..ctor(System.Threading.Tasks.Sources.IValueTaskSource`1<!0>,int16)`

On connecting to the hub this error show's

ex = {System.MissingMethodException: Method not found: void System.Threading.Tasks.ValueTask`1..ctor(System.Threading.Tasks.Sources.IValueTaskSource`1<!0>,int16)
  at System.IO.Pipelines.Pipe+DefaultPipeWriter.FlushAsync (System.Threading.CancellationToken cance...

The exception raised after : await _hubConnection.StartAsync(cancellationToken);

In the update the MONO VERSION and Xamarin Version will be updated.

**Comment by sidatacom** [comment]
So i downgrade to 15.8.9 old mono version and xamarin and same code run very well !!!

Did nobody test the iOS implementation here with the preview versions ???

**Comment by sidatacom** [comment]
Nobody from Microsoft have a look to this project ???

**Comment by bradygaster** [comment]
To which version did you upgrade? Also, have you seen [this note about Xamarin development](https://github.com/aspnet/Announcements/issues/305) from our team?

**Comment by bradygaster** [comment]
Thank you for the information, apologies for linking you to an old doc, as it has helped some other Xamarin devs in their journey. The SignalR team members will be engaging some of our friends in the Xamarin team to work on this. I'll keep this thread updated.

**Comment by bradygaster** [comment]
I spoke with our colleagues in the Xamarin team and this feels like an issue with a recent Xamarin update, and unrelated to the SignalR package. The team has asked that you use the VS Feedback tool to submit an issue, as the Xamarin team highly prioritizes issues that come in via that tool. For now I will close this GitHub issue as it seems to be specific to this Xamarin update and not to SignalR. If we ascertain through internal issue resolution that this is a SignalR issue I'll re-open it here. Expect to hear a response once you submit the vs-feedback item, as the team frequently triages issues coming in from that channel.

**Comment by sidatacom** [comment]
No response from vs team !!!

**Comment by bradygaster** [comment]
I can't articulate with predictability how long it will take the feedback team to reply, but I'm confident they'll get to you.

**Comment by sidatacom** [comment]
They did an made a [link ](https://github.com/xamarin/xamarin-macios/issues/5133)to github :)

**Comment by dalexsoto** [comment]
We are now tracking this bug here https://github.com/mono/mono/issues/11731

**Comment by Aguilex** [comment]
@sidatacom as you can see from the mono bug referenced here, we have a proposed fix for this issue. We're going through the validation and packaging activities for this and expect to include this fix in the next servicing release for 15.9. Thanks for your patience!

**Comment by bradygaster** [comment]
thanks for the update, @Aguilex and team!
