### ISSUE TITLE
Rename Protocols.Json package to Protocols.NewtonsoftJson

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#3308]
As well as changing the namespaces and `AddJsonProtocol` -> `AddNewtonsoftJsonProtocol`

**Comment by Eilon** [comment]
Let's make sure we have @DamianEdwards sign off on the new names first.

**Comment by anurse** [comment]
Make sure to post an announcement (being very clear that this is for **3.0**) to aspnet/Announcements once this change is in.

**Comment by BrennanConroy** [comment]
This has been approved

**Comment by Eilon** [comment]
Breaking change, right?

**Comment by BrennanConroy** [comment]
Yes
