### ISSUE TITLE
SignalR not supported on Android 8.0.0 and higher

### ISSUE THREAD

**Issue by Buli1212** [aspnet/SignalR#3328]
Error while installing on Android 8 device or higher. I've tried Android 8.0.0 and Android 9.0.0:

> Installation failed with message INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res =-113.

It looks like an issue with native libraries used by SignalR. 
With Android 9 already out there is there any chance to add support for the latest architectures ?

I've tried 'com.microsoft.signalr:signalr:1.0.0-preview3-35501' and implementation 'com.microsoft.aspnet:signalr:0.1.0-preview2-35174' using gradle implementation on Samsung S7 and Google Pixel 1

**Comment by anurse** [comment]
> It looks like an issue with native libraries used by SignalR.

We don't use any native libraries directly. It's possible that one of our dependencies does though (GSON, okhttp, and RxJava).

**Comment by Buli1212** [comment]
I was doing calls
```
    microsoft.aspnet.signalr.client.hubs.HubConnection
    microsoft.aspnet.signalr.client.hubs.HubProxy
```
which made me exclude gson library. After I've started using microsoft.signalr.signalr class I didn't have to exclude gson and everything works as expected. The problem I have now is that there is no 
HubProxy class. I will create a new issue/question for that. This one can be closed. Thank you for the quick response.
