### ISSUE TITLE
[JAVA] Concurrency and hub connection state

### ISSUE THREAD

**Issue by ncthbrt** [aspnet/SignalR#3329]
The latest version of the Java client on the `/release/2.2` branch does not have measures in place to ensure that the hub connection state is synchronized across threads (with the naked variable being read without concurrency control), this leads to invoke calls failing even when the connection status is `Connected` on other threads. 

A possible fix might be to mark this variable as volatile (though can at times be a fragile solution), or switch to using the accessor at all times, along with some form of locking.

**Comment by mikaelm12** [comment]
Hmm, interesting. We only update the actual `HubConnectionState` inside a lock in the client but I can do some investigation on this. Do you have any more information on a repro? 
Thanks!

**Comment by ncthbrt** [comment]
Apologies, I'm not at a computer right now, but from the source it may be
because you're using a rentrant lock rather than a reentrant read write
lock, which as far as I understand means that reads much also be
synchronised.


I'm not a professional android developer however (work mainly in F#/C#),
soy understanding of Java threading semantics may be poor.

**Comment by mikaelm12** [comment]
Hmm, well maybe would could transition to using a ReadWriteLock since it seems that we're not currently acquiring a lock on reads

**Comment by ncthbrt** [comment]
If need be, could take a look at this on Monday, and maybe make a PR?

**Comment by mikaelm12** [comment]
@ncthbrt I'll take this on. We are considering back porting this change as well.
Thanks for your help!

**Comment by ncthbrt** [comment]
Of course. :)
Btw don't know if you saw the PR above.

**Comment by mikaelm12** [comment]
This issue is being addressed in this PR https://github.com/aspnet/AspNetCore/pull/4400 and will be going into the 2.2.2 patch of the Java client. That issue is being tracked here:https://github.com/aspnet/AspNetCore/issues/4393. Thank you for the contribution @ncthbrt!
