### ISSUE TITLE
Inheritance in Hubs

### ISSUE THREAD

**Issue by Lukino2000** [aspnet/SignalR#333]
Hi,
for my understanding at the moment it is not possible using inheritance in hub declaration.

I suppose this is cause of HubEndPoint.DiscoverHubMethods where you use TypeInfo.DeclaredMethods.

is there any way to use a BaseHub with public methods?

thanks in advance and sorry for any misunderstanding

**Comment by davidfowl** [comment]
Sure, that's just an oversight. @BrennanConroy can you take a look at this?

**Comment by BrennanConroy** [comment]
Closed via #334
