### ISSUE TITLE
 OnDisconnectedAsync(Exception exception) not fired (LongPooling)

### ISSUE THREAD

**Issue by NightAngell** [aspnet/SignalR#3334]
**Server NuGets:** _Microsoft.AspNetCore.App (2.1.1) include Microsoft.AspNetCore.SignalR (1.0.1)_
**Client NPM Packages:** _"@aspnet/signalr": "^1.0.4"_
**Client:** _TypeScript (Angular7)_
**Server:** _IIS Express_
**Operating System (Client and Server):** _Windows 7_
**Browser:** _Chrome_

**Problem:** Hub method  OnDisconnectedAsync(**Exception** _exception_) not fired when:
1. User close Browser (or Tab)
2. User lost connection with internet (Chrome: F12->Network->Offline)
3. User refresh page

**Expected behaviour:** _OnDisconnectedAsync(Exception exception) fired_
**Actual behaviour:** _OnDisconnectedAsync(Exception exception) not fired_

> Code to reproduct error (Front Agnular7) https://github.com/NightAngell/SignalRErrorReproductionFront

> Code to reproduct error (Backend Asp.NET Core 2.1): https://github.com/NightAngell/SignalRErrorReporductionBackend

**Steps to reproduction:**
_**Backend**_
1. Create new Asp.Net core 2.1 project
2. In `Startup.cs` add `services.AddSignalR();` and  
```
app.UseSignalR(options =>
            {
                options.MapHub<YourHub>("/yourHub");
            });
```
3. Create `YourHub : Hub` 
4. In YourHub override `Task OnDisconnectedAsync(Exception exception)`
5. Make breakpoint in `OnDisconnectedAsync ` (For Debugging purpose)

_**Frontend**_
1. Connect to server (transport:  LongPolling)
2. `.then(()=>{ console.log("Connected!") });`
3. Close browser or close tab or or refresh page or (Chrome) F12->Network->Offline

> *Resolve CORS problem if required

Logs:
[Chrome.log](https://github.com/aspnet/SignalR/files/2613759/Chrome.log)
[ChromeNetwork.har.log](https://github.com/aspnet/SignalR/files/2613762/ChromeNetwork.har.log)
[ASPNETCOREBUG.log](https://github.com/aspnet/SignalR/files/2613773/ASPNETCOREBUG.log)

> All logs from "Code to reproduct error"

**Comment by BrennanConroy** [comment]
We changed how some of this worked in 2.2 which will most likely resolve the issues you're seeing. Can you try out the nightly bits on the client and server?

**Comment by NightAngell** [comment]
I use WebSockets instead of LongPooling (on Windows 10 instead of 7 [WebSockets transport not available on win7 IIS Express]) and it work (Chrome: F12->Network->Offline don`t work, but this is probably bug related to chrome tools and localhost (client and server are on localhost)*, I test it better when I deploy project to external hosting in the future [For now i write project for studies and I don`t plan deploy]). I just want notify about problem, but I see this problem is known and probably resolved, then I think this issue can be closed.

*Because when is set Client as offline using chrome tools, client still can send and receive messages from server
