### ISSUE TITLE
Is it possible to change Response cookies inside OnConnectedAsync? 

### ISSUE THREAD

**Issue by komarovalexander** [aspnet/SignalR#3340]
Hi!
```
public override Task OnConnectedAsync() {
    Context.GetHttpContext().Response.Cookies.Append("key", "value");  // here I have error
    return base.OnConnectedAsync();
}
```
"Headers are read-only, response has already started." error is thrown
Are there any ways to change cookie before base.OnConnectedAsync() is happen?

Btw. in classical .net it is possible to set cookie in OnConnected method

**Comment by analogrelay** [comment]
No, it's not possible to set cookies in a Hub event or method. Consider the WebSockets transport: When using that transport, there is only a single HTTP request (the one establishing the socket) and the response is in-progress by the time your application runs. So there's no HTTP response that can be used to set the cookie.

Why do you need to set a cookie? If you need to track state on the client, you can send that state down to the client and store it somewhere there (local storage, for example). Or, you can store the data in `Context.Items` and it will be there for all requests made by that connection.

**Comment by komarovalexander** [comment]
>Why do you need to set a cookie?

I create application for demonstration purposes only. 
Here is an explanation:
I use hubs with webapi. Webapi stores temporary data in the session storage and sends notification about changes using groups of signalR hub context. I need to send notification inside one browser (because I use session storage in webapi) so I save signalR groupId into cookie.

> No, it's not possible to set cookies in a Hub event or method.

I see
I think the best solution for me it's generate groupId and save it into cookie on the client side.

Thank you for explanation!
