### ISSUE TITLE
[Android&Java] on network change

### ISSUE THREAD

**Issue by xiazunyang** [aspnet/SignalR#3341]
https://github.com/aspnet/SignalR/blob/master/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java#L98
should change to  ```onClose.invoke(0, t.getMessage());```
Otherwise NullPointerException will occur when the network state changes.

**Comment by BrennanConroy** [comment]
Dupe of https://github.com/aspnet/SignalR/issues/3336
We've fixed it in the RTM version, which should be out before the end of the year
