### ISSUE TITLE
Java Streaming Support

### ISSUE THREAD

**Issue by bradygaster** [aspnet/SignalR#3343]
Adding Java streaming to our backlog so we can begin the discussion of when it might be realistic to consider. Probably after we wrap up #2699? As requested via docs in [this doc issue](https://github.com/aspnet/Docs/issues/9771#issuecomment-443964393).

**Comment by BrennanConroy** [comment]
Is this for server -> client streaming https://github.com/aspnet/SignalR/issues/2927? We've already done it for 3.0 😄

**Comment by mikaelm12** [comment]
Yeah, the feature work for this is done here https://github.com/aspnet/SignalR/commit/cdd7387159190d4e3c1755ffc0830d5b5073bb28. We just need to add the docs section for streaming but we have to be sure to only add it to the 3.0.0 and later docs. I don't think we have those up yet?

**Comment by bradygaster** [comment]
Closing this since it's mainly a doc issue. Also created a single issue we can use to keep track of things we'll need to make sure we doc - or update the docs - during 3.0. #3345
