### ISSUE TITLE
[Issue] Benchmarking - Concurrent client messages

### ISSUE THREAD

**Issue by saibaskaran57** [aspnet/SignalR#3344]
Hi,

I'm in midst of benchmarking our application on ASP NET Core SignalR 2.1 and found something that would want to check with the team here.

**Use-case:**
I have a Real-Time application that requires a client to send/stream down high volume(approximated 1 million request per hour) data asynchronously. SignalR Web-sockets was a preferred option as it only creates one connection which can send/stream multiple messages to server side.

**Issue:**
I noticed the execution of request is synchronous on the server-side where it only accepts a new request after it completes one request although its `async Task`.

**e.g. A simple-sample app** 
Server-side code
```
public sealed class RealTimeApp : Hub
{
    public async Task SendMessage(string message)
    {
           await Task.Delay(5000); // to simulate long running tasks(e.g. service/database calls)
           await Clients.Caller.SendAsync("ReceiveMessage", message);
    }
}
```

 .NET client-side code(burst performance mode):

```
var tasks = new List<Task>()

tasks.Add(connection.Invoke<string>("SendMessage", "sample1"));
tasks.Add(connection.Invoke<string>("SendMessage", "sample2"));
tasks.Add(connection.Invoke<string>("SendMessage", "sample3"));
tasks.Add(connection.Invoke<string>("SendMessage", "sample4"));
tasks.Add(connection.Invoke<string>("SendMessage", "sample5"));

await Task.WhenAll(tasks.ToArray());
```

**Server Execution:**
"sample1" data
"sample2" data(only executes after first message complete)
"sample3" data(only executes after second message complete)
......

**Questions:**
1) Is this the intended behavior on SignalR? 
2) If it's the intended behavior, are there any solution on how we could achieve the use-case?
3) Can we achieve this with using Streaming option given that a user should have a bounded data?

**Comment by muratg** [comment]
This is by design in current release. 

We'll consider https://github.com/aspnet/SignalR/issues/3133 in 3.0.

**Comment by muratg** [comment]
@BrennanConroy could you add the workaround here?

**Comment by BrennanConroy** [comment]
You can achieve long running tasks by using the `IHubContext<Hub>` class. See https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.2 for some reference on the usage.

**Comment by saibaskaran57** [comment]
Thanks for the confirmation.

As mentioned by @BrennanConroy, the workaround is to send via Middleware, Controllers. Our clients would be expected to use SignalR Hub to stream down their messages.

I have a thought in mind as below:

Assume the long-running task which is a service call(can be in milliseconds/seconds) and can be concurrent messages sent in.

Does the below workaround recommended to be applied since Websocket is Full-duplex?

**Server-side code :**
```
public Task SendMessage(string message)
{
      this.HandleMessageAsync(message).ConfigureAwait(false);

      return Task.CompletedTask;
}
```
```
private async Task HandleMessageAsync(string message)
{
     await Task.Delay(5000); // to simulate long running tasks(e.g. service/database calls/processing)
     await Clients.Caller.SendAsync("ReceiveMessage", message);
}
```

The above does not block each message and can be sent concurrently. 

Please give a shout-out, if this is a terrible idea.

**Comment by BrennanConroy** [comment]
>Client-side code :

I'm assuming that is still server side code, and you just meant it is the code that communicates with the client.

That approach would most likely fail because you are possibly using properties of the Hub class after the Hub method has exited and the Hub will be disposed of after each method call.

**Comment by saibaskaran57** [comment]
@BrennanConroy 

Yes, you are right. That is still the server side code. Corrected the comment.

The current design seems to be a show-stopper for our use case. Are there any other workaround on this?

**Comment by BrennanConroy** [comment]
Yeah, I have a different workaround for you:

```c#
public class MyHub : Hub
{
    private readonly IHubContext<MyHub> _context;
    public MyHub(IHubContext<MyHub> context)
    {
        // capture an IHubContext<> that isn't tied to the Hub lifetime
        _context = context;
    }

    public Task SendMessage(string message)
    {
        // Capture the connectionId of the client so we can use Clients.Caller from outside the Hub
        var connectionId = Context.ConnectionId;
        Task.Run(async () =>
        {
            await Task.Delay(5000);
            // The IHubContext<THub> doesn't have Clients.Caller because it isn't associated with a connection
            // So we use Clients.Client(connectionId) to do the exact same thing
            await _context.Clients.Client(connectionId).SendAsync("Send", "testing");
        });

        return Task.CompletedTask;
    }
```

**Comment by saibaskaran57** [comment]
Thanks for your quick response & workaround. I'll give it a try and let you know how that went.

**Comment by saibaskaran57** [comment]
Hi @BrennanConroy ,

Thanks for your assistance.

I have tried the workaround and it's working great.

Hopefully, it will get considered to have it supported on SignalR instead.

**Comment by samcov** [comment]
Very good information guys... Thanks!
