### ISSUE TITLE
Invalid negotiation response received

### ISSUE THREAD

**Issue by ryancole** [aspnet/SignalR#3346]
Hi folks,

I'm trying to make use of Azure's SignalR Service. I'm not using the "Serverless" mode, meaning I have a local ASP.NET Core web server with the `Microsoft.Azure.SignalR` library. That local SignalR server just hands off the connection to Azure, as far as I understand it. Next, I have an Azure Functions v1 application that targets .NET Framework 4.6.1. I intend for these Functions to behave like a SignalR client and broadcast "progress" messages. I've got the `Microsoft.AspNetCore.SignalR.Client` package installed in the Functions application.

Whenever I try to connect to my local hub server, I get an error saying `Invalid negotiation response received`. The full error is below ...

```
Microsoft.AspNetCore.Http.Connections.Common: Invalid negotiation response received.
Microsoft.AspNetCore.Http.Connections.Common: The type initializer for 'JsonArrayPool`1' threw an exception.
Microsoft.AspNetCore.Http.Connections.Common: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

The error is kind of confusing, as it's a mix of two different problems. The first is an invalid negotiation response, and the second is a more sinister missing file. I'm unsure which error is the true error - perhaps the missing file error is cause by some prior error (perhaps the invalid negotiation response).

Anyway, I'm unsure how to proceed. I can't seem to get this client to connect to my hub server.

Any ideas?

**Comment by ryancole** [comment]
[FunctionApp4.zip](https://github.com/aspnet/SignalR/files/2651398/FunctionApp4.zip)

Here is a sample project of my client code that fails. It's a blank Azure Function HTTP Trigger function project, into which I pasted a few lines of code that tries to connect to my local hub server.

My hub server seems to work when being connected to from the browser. I have some javascript that is using the `@aspnet/signalr` package and it connects to my hub just fine.

**Comment by BrennanConroy** [comment]
I'm pretty sure Azure Functions are short lived "functions", so you can't have a traditional C# SignalR client running in them since they last for a single Http request basically.

Have you checked out the docs we have for the SignalR Service and Functions? https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service

**Comment by ryancole** [comment]
@BrennanConroy thank you for the quick reply!

I have checked those bindings out and they look super handy, but unfortunately we're currently targeting azure functions v1 because we need the .net framework support. I believe those bindings only work within a .net standard / core project, or possibly only on azure functions v2. I tried installing the package and got a whole host of compatibility errors. (Trust me, I put some serious thought into re-writing the whole thing to target Functions v2 and use .NET Core, but that involves finding replacements for some Windows-only third party libraries we use / pay for)

Alternatively, I tried directly accessing Azure SignalR Service, from my Functions code, via the REST API. I basically copy + pasted code from the [serverless sample code](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Serverless) on github that [generates the JWT](https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/Serverless/ServiceUtils.cs#L26-L54) and puts together the HTTP request.  This request seems to "go through", as I receive the "Accepted" HTTP response, but the message is never broadcast back out to other connected clients, it seems. I was having a difficult time debugging the REST API approach, so I attempted to revert back to the `Microsoft.AspNetCore.SignalR.Client` package approach.

You're right that the functions are short lived. Is that not acceptable for SignalR? These functions don't need to receive anything, I'm just trying to broadcast-only some messages intended to be read by other connected signalr clients.

**Comment by bradygaster** [comment]
What @BrennanConroy says is true, that the Function is short-lived and really, the only way to use SignalR with Functions is the bindings. This short-lived*ness* isn't really an applicable SignalR scenario; you could use the client to connect to a hub and send a message, but you'd be connecting/disconnecting quickly (which could lead to other issues). The idea of SignalR is *always connected*. 

You are correct that these are for .NET Core only, I'm 99% sure. Adding @anthonychu to validate these are only for Core but I'm pretty sure they are. 

Here's an idea - you could create a second function that responds to incoming HTTP requests, then effectively turns around and pumps those back into the service. Then, you could use the binding to pump the messages into the service, and your existing V1 function could simply make HTTP requests to your "realtime proxy function." That would also give you more ability to reuse the "realtime proxy" in other scenarios later if you need.

**Comment by ryancole** [comment]
Thanks, @bradygaster.

I went ahead and introduced a second Functions application that target .NET Core and uses Functions V2. In that project I have a Service Bus-triggered Function that uses the SignalR output binding to dispatch messages to Azure SignalR service. That aspect of everything seems to be working now, as I can use Fiddler to log the HTTP requests and can see that the binding is indeed making the `POST` request to Azure and is getting an `Accepted` response.

I'm on to a whole new bit of confusion now though, as my browser-based `@aspnet/signalr` clients are not receiving the messages that I'm invoking from the Azure Functions application via the SignalR binding. I go into detail about my setup and that issue in #3349 though.
