### ISSUE TITLE
Feature: option to disable URL rewriting

### ISSUE THREAD

**Issue by IlCallo** [aspnet/SignalR#3348]
### Please include as much of the following as you can in your bug report

* Versions of Client-Side NPM Packages: 1.0.4
* Are you using the C# client or the JavaScript client: TS/JS
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome

### Brief description
Currently SignalR client automatically normalizes the URL if full domain is not specified.
It could be useful to be able to disable that behaviour.

### Use case
In my Angular project I have an HttpInterceptor which already manages URL normalization for all API calls (both for realtime and rest ones) and I prefer to manage URL normalization in a single place (passing the HttpClient implementation to the HubConnectionBuilder) instead of doint it in every communication-related service

**Comment by analogrelay** [comment]
If you pass an absolute URL to the `HubConnectionBuilder`, we won't normalize the URL.

Note that SignalR uses the `WebSocket` and and `EventSource` browser APIs which make HTTP requests **without using XHR or `fetch`** so it's very likely that Angular's `HttpInterceptor` does not receive those requests and any rewriting you perform there **would not apply** to those requests. I'd suggest that you do not rely on `HttpInterceptor` receiving all SignalR-related requests.

**Comment by IlCallo** [comment]
I see... I saw there was the possibility to provide an HttpClient and thought it was using it for requests, but I guess it's using it only for the initial connection, right?
Ty for the answer anyway
