### ISSUE TITLE
ITransportHeatbeat?

### ISSUE THREAD

**Issue by mb2140** [aspnet/SignalR#341]
I'm attempting to build a sort of presence monitor where I can monitor connect/disconnects to a particular hub.  Using earlier versions of SignalR I was able to tap into ITransportMonitor and use "GenConnections" like this:

https://patdunn.net/2015/05/05/building-a-simple-presence-manager-for-signalr/

Is there a something similar to ITransportHeartbeat in this library?

**Comment by davidfowl** [comment]
No it's gone, we don't currently have an equivalent as yet. We'll bring something similar back but it's not there yet.

**Comment by davidfowl** [comment]
Its possible to use the events on the hub to build the connection list now
