### ISSUE TITLE
Build error: Failed to retrieve information about 'Internal.AspNetCore.BuildTools.Tasks' 

### ISSUE THREAD

**Issue by klaus-liebler** [aspnet/SignalR#344]
After having checked out the current master and having called the build script I get this error . For more details, have a look in the attachment, please.
[output.txt](https://github.com/aspnet/SignalR/files/876597/output.txt)

Hint "Das Zeitlimit fr den Vorgang wurde erreicht" means "time limit has been reached"

**Comment by moozzyk** [comment]
Looks like a timeout when trying to restore packages. Is it persistent? (I was able to build the repo earlier today without any problems)

**Comment by klaus-liebler** [comment]
I just tried to compile it one minute ago. The problem is still there.

**Comment by klaus-liebler** [comment]
I tried to execute the build script on my second development  pc - the error remains the same.

**Comment by moozzyk** [comment]
I just tried from my home pc and things work just fine:

```
dotnet-install: .NET SDK version 2.0.0-preview1-005418 is already installed.
Adding C:\Users\moozz_000\AppData\Local\Microsoft\dotnet\ to PATH
> dotnet msbuild /nologo  /t:Restore /p:PreflightRestore=true C:\source\SignalR-Core\.build/KoreBuild.proj
  Restoring packages for C:\source\SignalR-Core\.build\KoreBuild.proj...
  Restoring packages for C:\source\SignalR-Core\.build\shared\sharedsources.csproj...
  Lock file has not changed. Skipping lock file write. Path: C:\source\SignalR-Core\.build\shared\obj\project.assets.jso
n
  Restore completed in 159.68 ms for C:\source\SignalR-Core\.build\shared\sharedsources.csproj.
  Installing NuGetPackageVerifier 1.0.2-rc2-15220.
  Installing Internal.AspNetCore.BuildTools.Tasks 1.0.0-rc2-15220.
  Generating MSBuild file C:\source\SignalR-Core\.build\obj\KoreBuild.proj.nuget.g.props.
  Generating MSBuild file C:\source\SignalR-Core\.build\obj\KoreBuild.proj.nuget.g.targets.
  Writing lock file to disk. Path: C:\source\SignalR-Core\.build\obj\project.assets.json
  Restore completed in 21.36 sec for C:\source\SignalR-Core\.build\KoreBuild.proj.

  NuGet Config files used:
      C:\source\SignalR-Core\.build\NuGet.Config
      C:\source\SignalR-Core\NuGet.Config
      C:\Users\moozz_000\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json
      https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json
      https://api.nuget.org/v3/index.json
      C:\LocalFeed
      https://www.myget.org/F/aspnetvnext/
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

  Installed:
      2 package(s) to C:\source\SignalR-Core\.build\KoreBuild.proj
...
```

@natemcmaster - do you have any idea what it can be or how to get more details why restore is failing like that:

```
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/internal.aspnetcore.buildtools.tasks/index.json'.
  An error occurred while sending the request.
    Das Zeitlimit fuer den Vorgang wurde erreicht (means timeout)
```

**Comment by natemcmaster** [comment]
Sometimes NuGet's HTTP cache can be corrupted. Try running `nuget.exe locals http-cache --clear` to reset it.

**Comment by klaus-liebler** [comment]
@natemcmaster I tried your call using the nuget.exe (v 4.8.8.2275) in the .build directory

Btw, the correct call is `nuget.exe locals http-cache -clear` (only one hyphen before clear).

The error remains the same...

**Comment by moozzyk** [comment]
@natemcmaster - is this url https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/internal.aspnetcore.buildtools.tasks/index.json correct? When I try to check this I see: **The specified blob does not exist.** RequestId:a99e3346-0001-0089-4185-a9dfa1000000 Time:2017-03-30T18:46:10.4826349Z which I don't think is expected

@klaus-liebler - can you do `git clean -xdf` and `git pull origin dev` before building? If you cloned the code some time ago you might have old build scripts...

**Comment by BrennanConroy** [comment]
No, that package is on https://dotnet.myget.org/gallery/aspnetcore-tools but restore should be using all feeds in the nuget.config

**Comment by moozzyk** [comment]
In that case there might some settings in the global NuGet.config that interfere with ours - e.g. the global NuGet.config has already a key called "AspNetCoreTools". @klaus-liebler - can you check post your global NuGet.config?

**Comment by klaus-liebler** [comment]
@moozzyk I use an absolutely fresh cloned repository

File content of C:\Users\<my user name>\AppData\Roaming\NuGet\NuGet.Config is

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
</configuration>`

**Comment by moozzyk** [comment]
@klaus-liebler - I guess you need to figure out where the `https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3` feed is coming from. We are not using it so it must be somewhere in your environment.

**Comment by klaus-liebler** [comment]
@moozzyk I tryed to do this by searching the URL in all files, but this was not successful. I tried to open the server https://dotnetmyget.blob.core.windows.net/ on my browser, but I get the well known error message.

Sorry, but I do not know how to figure out this?

Maybe, somebody can just provide the compiled artifacts so that I can use them without having to compile them on my system?

**Comment by moozzyk** [comment]
We push packages to myget after each build. Here is the feed https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json (gallery: https://dotnet.myget.org/gallery/aspnetcore-ci-dev
