### ISSUE TITLE
Fix JsonTextWriter usage if necessary

### ISSUE THREAD

**Issue by kichalla** [aspnet/SignalR#346]
MVC had the following issue filed:
https://github.com/aspnet/Mvc/issues/5413

Json.Net 10.0.1 has a property on JsonTextWriter which fixes this
http://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonWriter_AutoCompleteOnClose.htm

SignalR currently uses text writer in the following locations, check if these locations need to be fixed too:

- https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Common/JsonNetInvocationAdapter.cs#L49
- https://github.com/aspnet/SignalR-Server/blob/dev/src/Microsoft.AspNetCore.SignalR.Server/Transports/PersistentResponse.cs#L93

**Comment by moozzyk** [comment]
We don't expect partial writes. This code is actually being rewritten so this no longer applies.
