### ISSUE TITLE
Server needs perf counters 

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#349]

**Comment by DamianEdwards** [comment]
We can look at `EventCounter` again. @kichalla even wrote a prototype cmd line viewer for them.

**Comment by muratg** [comment]
The goal is to design and implement the infrastructure in preview1 and implement a few of the perf counters as well.

We'll finish up the rest of the perf counters in later releases.

**Comment by muratg** [comment]
cc @anurse

**Comment by anurse** [comment]
Using this to track adding EventSource/EventCounter to SignalR. See https://gist.github.com/anurse/af1859663ac91c6cf69c820cebe92303 for some guidance on adding EventSources and EventCounters to ASP.NET projects.

**Comment by BrennanConroy** [comment]
Compiling list of Counters/Events we may want:

**Microsoft-AspNetCore-Sockets EventSource**
- [x] ConnectionsStarted - Counts started connections
- [x] ConnectionsStopped - Counts connections that stopped gracefully
- [x] ConnectionsTimedOut - Counts connections that timed out
- [ ] ConnectionsAborted - Counts connections that aborted abnormally
- [x] ConnectionDuration (EventCounter)
- [ ] BytesRead - Counts bytes read from connections
- [ ] BytesWritten - Counts bytes written to connections
- [ ] Connection counters per transport?

**Microsoft-AspNetCore-SignalR EventSource**
- [ ] MessagesReceived - Counts all messages received
- [ ] MessagesSent - Counts all messages sent
- [ ] InvocationsReceived - Counts invocation messages received
- [ ] CompletionsReceived - Counts all completion messages received
- [ ] ErrorsReceived - Counts completion messages received containing an error
- [ ] StreamItemsReceived - Counts stream items messages received
- [ ] InvocationsSent - Counts invocation messages sent
- [ ] CompletionsSent - Counts completion messages sent
- [ ] ErrorsSent - Counts completion messages sent containing an error
- [ ] StreamItemsSent - Counts stream items messages sent

Error counters: We need to review a little bit about where they belong in our system

Scale-out counters? Redis messages sent, received, groups etc.

**Comment by anurse** [comment]
> Scale-out counters? Redis messages sent, received, groups etc.

Yep, sounds good :).

**Comment by BrennanConroy** [comment]
Redis messages sent and received would probably be unnecessary since it would be counted in Microsoft-AspNetCore-SignalR

**Comment by anurse** [comment]
Well, yeah, but tracking Redis sends/receives in general might be useful.

**Comment by anurse** [comment]
Perf counters aren't going to fit our scope for 2.1.0
