### ISSUE TITLE
Test TypeScript user experience in a Node app

### ISSUE THREAD

**Issue by sSeewald** [aspnet/SignalR#350]
It is intended that the TS client is designed for browser only?

**Comment by moozzyk** [comment]
No. The TS client is specifically designed to not be tight to the browser however you will need to use polyfills for missing functionality (e.g. XHR)

**Comment by sSeewald** [comment]
Hm Ok. But this would fail especially in nodejs. Because there is a Socket in "net" but WebSocket is not available.

`class WebSocketTransport {
...
let webSocket = new WebSocket(connectUrl);
...
}`

**Comment by moozzyk** [comment]
Incidentally I was thinking about this yesterday when sending this PR: https://github.com/aspnet/SignalR/pull/348. Namely whether to take only `TransportType` or `TransportType | ITransport`. The only thing is that implementing ITransport is not always trivial.

**Comment by moozzyk** [comment]
This is now almost possible with some polyfilling: https://twitter.com/moozzyk/status/898650110468292608 and hacking. 
https://github.com/aspnet/SignalR/pull/744 removes the hacking part - with these changes I was able to get the client working with websockets and longpolling transports.

**Comment by moozzyk** [comment]
cddc5f8a75b48f08b33e2b9cbf3d5005b573ac1b
