### ISSUE TITLE
What is the alternative for CreateHubProxy()

### ISSUE THREAD

**Issue by Liero** [aspnet/SignalR#351]
I see that IHubProxy was removed implementation targeting .NET Standard.

What is current alternative for this code:

```
HubConnection signalRConnection = new HubConnection(config.ServerUrl + "/signalr/hubs");
IHubProxy hubProxy = signalRConnection.CreateHubProxy("MyHub");
hubProxy.On("SendNotification", handler);
```

**Comment by moozzyk** [comment]
```C#
HubConnection signalRConnection = new HubConnection(config.ServerUrl + "/signalr/hubs");
signalRConnection .On("SendNotification", new Type[] {/*argument types*/}, handler);
```

We will have generic versions of the `On` method to not require the array with argument types (https://github.com/aspnet/SignalR/issues/311).

**Comment by Liero** [comment]
Yes, but on which hub is the code listening?

**Comment by moozzyk** [comment]
You need configure the hub on the server side like this: https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/Startup.cs#L86 and then you access using `serverUrl + "/{configured path}"`
