### ISSUE TITLE
Can't create UWP or WPF apps that use SignalR

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#364]
When trying to write a UWP or WPF sample I get missing assembly errors for System.Net.Http and Logging.

**Comment by muratg** [comment]
Targeting .NET Core?

**Comment by davidfowl** [comment]
No, this is a regular WPF application using the new SignalR client.

**Comment by muratg** [comment]
@mikaelm12 sync up with @davidfowl and @anurse before starting investigating this.

**Comment by pellea** [comment]
I have no issue using the latest SignalR client package in a WPF app (.net 4.7).

**Comment by moozzyk** [comment]
I can't repro this. Closing.

**Comment by moozzyk** [comment]
Note: for WPF you currently [need to add a reference to the NETStandard.Library.NETFramework package](https://github.com/dotnet/sdk/issues/1220#issuecomment-302188132).
