### ISSUE TITLE
Clean up server side logging

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#368]
We need to make some adjustments to logging on the server:

- There needs to be an easy way to look at the logs for a single connection id. Today we don't consistently specify the connection id as a structured logging argument, and we should be doing that.

- We should also be using pre-compiled templates (see https://github.com/aspnet/KestrelHttpServer/blob/6a66323a99f92c3e4a926d362e55542193a3ed44/src/Microsoft.AspNetCore.Server.Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs).

**Comment by BrennanConroy** [comment]
Related https://github.com/aspnet/SignalR/issues/553

**Comment by muratg** [comment]
We have some amount of logging for alpha1. We'll revisit the levels and the amount of logging in preview1.

**Comment by muratg** [comment]
We'll have another review of logging at a later time.
