### ISSUE TITLE
Create mechanism for transforming InvocationMessages outside of Hub protocol

### ISSUE THREAD

**Issue by berdon** [aspnet/SignalR#375]
Related to #374 
> @anurse:
> The Invocation Adapter was only intended as a way to serialize/deserialize the hub messages, hence the changes in this PR. However, having a component that allows you to intercept and rewrite those messages does seem like it might be useful and worth discussing, for exactly those scenarios.
>
>Can I suggest moving this discussion to a new Issue? This seems like something we'll want to discuss in depth to figure out the best way to do it, but I don't want to overload this discussion thread with it.
> [Thread here](https://github.com/aspnet/SignalR/pull/374#issuecomment-292266572)

**Comment by davidfowl** [comment]
Why not just use a JSON converter?

**Comment by berdon** [comment]
@davidfowl 
Did my example/use-case in the linked PR provide any clarity?

I like the suggestion for JSON Converters and think they will work. However, how would that work given the lack of guarantee that the protocol type is unknown? Ie. BinaryHubProtocol might become a thing, replace the JsonHubProtocol, and now suddenly the types aren't converted using the custom JSON Converters.

**Comment by anurse** [comment]
Would it not also be feasible to simply do this in the Hub logic itself? Make the Hubs just facades in front of a common implementation and they just transform the inputs from different-version clients and call the common implementation? That way you are isolated from protocol changes, and not coupled to specific extension points in SignalR.

**Comment by muratg** [comment]
We do not plan on doing this.
