### ISSUE TITLE
Change JavaScript to use new Transport protocol for send

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#383]
Right now, the JavaScript client is just relying on the legacy behavior here in HttpConnectionDispatcher: https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets/HttpConnectionDispatcher.cs#L354

I'd like to remove that code soon, so we should update the JavaScript client. We'll need to write a Text message formatter in JavaScript, but we've already got the parser so it shouldn't be too hard.

/cc @mikaelm12 @moozzyk @davidfowl

**Comment by anurse** [comment]
Sorry if there's already a bug tracking this, but I didn't see it. I wanted to have a bug tracking it so we know to remove the legacy code in HttpConnectionDispatcher when the bug is closed.

**Comment by moozzyk** [comment]
I will do that

**Comment by moozzyk** [comment]
Fixed in e691e1cff83cce9ab1fd294ee787aba822ff0e7b
