### ISSUE TITLE
Decouple Sockets from Http

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#389]
We want to be able to run Sockets on non-HTTP servers (Raw TCP, etc.). So we should split the Sockets package into a Sockets library and a Sockets.Http library which binds to HTTP. Then SignalR would run on top of Sockets only and be decoupled from HTTP. We can have a SignalR.Http that adds additional HTTP-related stuff if needed.

/cc @davidfowl

**Comment by davidfowl** [comment]
Lets do this ASAP. Lets just do Sockets and Sockets.Abstractions?

**Comment by anurse** [comment]
Yep, I'll do it next, after #390 . I guess Abstractions makes sense, though there will likely be more than just abstract things in there

**Comment by davidfowl** [comment]
Done
