### ISSUE TITLE
Should the Sockets and SignalR protocol be subprotocols in WebSockets

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#402]
Should we set the subprotocol when talking over websockets?

/cc @anurse

**Comment by anurse** [comment]
Yes, I think we should, just to make sure we're clear.

**Comment by davidfowl** [comment]
Related to https://github.com/aspnet/SignalR/issues/520

**Comment by moozzyk** [comment]
- The client should send a versioned subprotocol name for SignalR.
- Endpoint should be able to read the subprotocol from metadata

**Comment by davidfowl** [comment]
@moozzyk how do you feel about this? This requires some back and forth between the endpoint and the transport.

**Comment by moozzyk** [comment]
I think it depends on how much of _back and forth_ is required. Not required but would be nice. I wonder if it could be useful at the http connection level for IoT scenarios.

**Comment by anurse** [comment]
What if this was just an EndPoint option and `.MapHub` configured it?

**Comment by davidfowl** [comment]
I'm not sure you want to do it that globally instead of per connection.

**Comment by anurse** [comment]
My thought is you'd have a list of subprotocols on the Endpoint options that are allowed, and the transport would negotiate it against the list that the client presents in it's request. The actual subprotocol decision is per-connection.

Also, we could take a page out of the Auth Handlers and provide events on the Endpoint options for custom subprotocol negotiation.
