### ISSUE TITLE
Is there a way to use SignalR in asp.net core and Xamarin.forms ?

### ISSUE THREAD

**Issue by paradisehuman** [aspnet/SignalR#411]
Hi. I used to try to use SignalR in Asp.net core and Xamarin but unfortunately didn't success.
I couldn't communicate with the client side in Xamarin. 
Is there a plan to come out the newer version of SignalR .net core  ?

**Comment by moozzyk** [comment]
The client for SignalR Core targets netstandard1.3 so it should be possible to use it in Xamarin. If it does not work please provide more details.

**Comment by paradisehuman** [comment]
@moozzyk The server side (asp.net core )was alpha version, and couldn't communicate with the client side version 2 (Xamarin). connection didn't started and It gave me error.

**Comment by davidfowl** [comment]
@paradisehuman Do you have an application that you can put on github so we can take a look?

**Comment by paradisehuman** [comment]
@davidfowl To be honest, I tried one month ago . but please wait to put my code here .

**Comment by moozzyk** [comment]
You can't use SignalR2.x client with SignalR core. You need to use SignalR Core client.

**Comment by paradisehuman** [comment]
@moozzyk Ok. I will test it and come back again.

**Comment by paradisehuman** [comment]
@moozzyk Is there any signalR client package for .net core ? I can't find anything !

**Comment by moozzyk** [comment]
https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.AspNetCore.SignalR.Client

**Comment by berdon** [comment]
For what it's worth, we were leveraging SignalR core with Xamarin but ended up dropping it because of net standard / pcl issues specific to Android. I've asked @ryanwersal to comment when he has time.

**Comment by paradisehuman** [comment]
OK.I installed the client packages . 
I configure the server side same as this link : 
http://radu-matei.github.io/blog/signalr-core/

And this my client side : 

```
public class App : Application
    {
         
        public App()
        {
            MainPage = new ContentPage { Content=new Label{Text="OK"}};
        }
        protected override async void OnStart()
        {
            base.OnStart();
            var url = new Uri("http://localhost:54801");
            var connection = new HubConnection(url);
            await connection.StartAsync().ContinueWith(task =>
            {
                if (task.IsFaulted)
                    MainPage.DisplayAlert("Error", "An error occurred when trying to connect to SignalR: " + task.Exception.InnerExceptions[0].Message, "OK");
            });
        }
    }
```
I got the 

> "Unable to connect to the remote server"

 Error.
I'm using UWP.

**Comment by moozzyk** [comment]
What is the stacktrace? I don't think this exception is coming from SignalR client and I don't think the server even receives the request. Are you sure your application allows making HTTP requests?

**Comment by paradisehuman** [comment]
@moozzyk `at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport.<Connect>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport.<StartAsync>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Sockets.Client.Connection.<StartTransport>d__36.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Sockets.Client.Connection.<StartAsyncInternal>d__33.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__24.MoveNext()`

**Comment by paradisehuman** [comment]
In Android I got this error : 

> "The server returned status code '200' when status code '101' was expected"
I'm using 10.0.2.2:54801 , instead of localhost.

**Comment by paradisehuman** [comment]
My server version is 0.2.0-preview2-22683 and the client version is 1.0.0-preview1-24571 .
Is it influence this problem ?

**Comment by BrennanConroy** [comment]
Thats the wrong server package. Use Microsoft.AspNetCore.SignalR 1.0.0-preview1-24574

**Comment by moozzyk** [comment]
0.2.0 server is quite ancient. Use the same version as the client. When you are running from a device emulator you can't use localhost because SignalR would try to connect to the server running on the device and not on your machine.

**Comment by paradisehuman** [comment]
@moozzyk There is no Microsoft.AspNetCore.SignalR.Server 1.0.0-preview1-24574!
Yes,I'm using 10.0.2.2 in Android.
I'm using localhost In UWP.

**Comment by paradisehuman** [comment]
@BrennanConroy When I install Microsoft.AspNetCore.SignalR 1.0.0-preview1-24574 instead of Microsoft.AspNetCore.SignalR.Server 0.2.0-preview2-22683 in my Web project, I got this error when I start the server : 

> System.TypeLoadException: 'Method 'ConfigureAppConfiguration' in type 'Microsoft.AspNetCore.Hosting.WebHostBuilder' from assembly 'Microsoft.AspNetCore.Hosting, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'

**Comment by BrennanConroy** [comment]
You need to reference the latest pre-release packages for AspNetCore, so 2.0.0-* for Hosting etc.

**Comment by paradisehuman** [comment]
@BrennanConroy  Ok. It seems the error disappear. If I face a new problem, I will ask. Thank you

**Comment by moozzyk** [comment]
24574 was more than 6 builds ago :) There is a reason why we use * in versions. Because we have multiple builds a day versions change frequently (we had 6 builds in the last 5 hours - https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.AspNetCore.SignalR).  You want to use `1.0.0-*` version for SignalR and `2.0.0-*` for other Asp.Net Core packages.
