### ISSUE TITLE
Add tests for SSE transport

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#413]
Add more unit tests and make sure existing tests run across all available transports if applicable (e.g. https://github.com/aspnet/SignalR/blob/dev/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs#L59)

**Comment by davidfowl** [comment]
What is this? Is it for the JS client?

**Comment by moozzyk** [comment]
No, for C# client. Still needs to be done.

**Comment by davidfowl** [comment]
We don't have any SSE transport tests?

**Comment by moozzyk** [comment]
No. You pushed to push the change without these tests.

**Comment by davidfowl** [comment]
Yea but it's been a while 😄

**Comment by moozzyk** [comment]
Fixed in 2854e868eca4fea078d9833a501fb56e2ae151a8
