### ISSUE TITLE
Consider renaming Microsoft.AspNetCore.SignalR.AuthorizeAttribute

### ISSUE THREAD

**Issue by mskurnik** [aspnet/SignalR#42]
When calling a hub from a MVC controller that `Authorize` decorated on the class or method/view for example, there is an ambiguous reference between  `Microsoft.AspNetCore.SignalR.AuthorizeAttribute` and `Microsoft.AspNetCore.Authorization.AuthorizeAttribute`.  If you rename `Microsoft.AspNetCore.SignalR.AuthorizeAttribute` to `Microsoft.AspNetCore.SignalR.Authentication.AuthorizeAttribute`, you would remove this ambiguity.

**Comment by BrennanConroy** [comment]
This is the wrong repo, look at https://github.com/aspnet/SignalR-Server which is the old repo for SignalR

**Comment by moozzyk** [comment]
This issue does not apply to this version of SignalR.
