### ISSUE TITLE
Exception/error handling

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#420]
We need to manifest errors from the server to the client properly. This includes:

* ~~Errors parsing Hub protocol messages, which should manifest as `Error` frames in the underlying transport (followed by closing the connection)~~ - done
* Errors that occur during Hub method invocation should not include exception message bodies by default (enabled in development mode), like we do with exceptions in the HTTP pipeline (for security).

**Comment by muratg** [comment]
We'll need to add a configuration option to enable verbose errors which include stacktrace.

**Comment by davidfowl** [comment]
Related to #254
