### ISSUE TITLE
Could you tell me how to fix it.

### ISSUE THREAD

**Issue by WestFive** [aspnet/SignalR#421]
i use the   AspNetCore.signalR.Server 0.2.0-a  
```
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An unhandled exception has occurred: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.AspNetCore.SignalR.Server.Resources.resources" was correctly embedded or linked into assembly "Gray.Microsoft.AspNetCore.SignalR.Server" at compile time, or that all the satellite assemblies required are loadable and fully signed. Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.AspNetCore.SignalR.Server.Resources.resources" was correctly embedded or linked into assembly "Gray.Microsoft.AspNetCore.SignalR.Server" at compile time, or that all the satellite assemblies required are loadable and fully signed.
```
I feel puzzled at this err.
![image](https://cloud.githubusercontent.com/assets/20624447/25426174/df38e9f4-2aa0-11e7-951c-1902a05a25d4.png)
This problem occurs when the program can still work.

**Comment by BrennanConroy** [comment]
First off you're using an old deprecated pre-release version of SignalR Core. The correct one is https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.AspNetCore.SignalR

Secondly your error message talks about Gray.Microsoft.AspNetCore.SignalR.Server which is some random persons version

**Comment by jagathprasanga** [comment]
I'm also getting same error. The latest Microsoft.AspNetCore.SignalR (https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client) is not having java client (for Android). Have you found any option.
Thanks.

**Comment by moozzyk** [comment]
If the error is mentioning "Gray.Microsoft.AspNetCore.SignalR.Server" see @BrennanConroy's response. Gray.Microsoft.AspNetCore.SignalR.Server is not something that was shipped by Microsoft or is supported by Microsoft.

**Comment by jagathprasanga** [comment]
Is there any way to connect with Microsoft.AspNetCore.SignalR (https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR/1.0.0-alpha2-final) from Java(Android). signalr-client-sdk-android.jar is not supporting with latest SignalR as I knew.

**Comment by moozzyk** [comment]
As per my [comment](https://github.com/aspnet/SignalR/issues/883#issuecomment-336499189) - there is no Java client at the moment for this version of SignalR.

**Comment by perumalsamya** [comment]
@jagathprasanga Have you found the solution for your problem? I am also facing the same issue

**Comment by jagathprasanga** [comment]
@perumalsamya No options found so, I decided to go with Gray.Microsoft.AspNetCore.SignalR.Server 
 (https://www.nuget.org/packages/Gray.Microsoft.AspNetCore.SignalR.Server/0.2.0-alpha1 )
