### ISSUE TITLE
Handle back pressure from slow clients when application complete

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#426]
If an application is complete but the transport is currently writing to a slow connection, it's possible we'll miss the notification that the application is complete for an indeterminate amount of time, leaking resources. We need to handle this situation by checking the channel's task and completing the outgoing send after some timeout.

This needs to be handled in all 3 transports:
- LP - https://github.com/aspnet/SignalR/blob/d19ed0070c25478c6ed23c2490e700f1452e8a68/src/Microsoft.AspNetCore.Sockets/Transports/LongPollingTransport.cs#L69
- SSE - https://github.com/aspnet/SignalR/blob/d19ed0070c25478c6ed23c2490e700f1452e8a68/src/Microsoft.AspNetCore.Sockets/Transports/ServerSentEventsTransport.cs#L65
- WS - https://github.com/aspnet/SignalR/blob/d19ed0070c25478c6ed23c2490e700f1452e8a68/src/Microsoft.AspNetCore.Sockets/Transports/WebSocketsTransport.cs#L194

/cc @anurse

**Comment by anurse** [comment]
Closing in favor of #820

**Comment by davidfowl** [comment]
@halter73 Kestrel's drain timeout will cover this right?

**Comment by davidfowl** [comment]
Re-opening this one separately, I need to do some investigation.

**Comment by davidfowl** [comment]
Turns out we don't need to handle this!
