### ISSUE TITLE
Production use of SignalR for Asp.Net Core

### ISSUE THREAD

**Issue by Jenan** [aspnet/SignalR#429]
Hello, 

I would like to ask about production use of SignalR. I want to use the SignalR in the production and is it possible use the latest version of SignalR for Asp.Net Core or is necessary use the version for full .NET framework?

Thank you.

**Comment by davidfowl** [comment]
1. SignalR on ASP.NET Core isn't production ready
2. It requires the latest ASP.NET Core (2.x) to function properly (which isn't released yet)
3. There's 2 versions of SignalR on our myget feed today, a deprecated one https://github.com/aspnet/SignalR-Server and this one (the one that will ship). Running the other deprecated one in production is also unsupported (though I know of people using it). 
4. Some people have hacked SignalR 2.x to make to run on ASP.NET Core but it's also not supported and has lots of strange quirks.
5. The .NET Framework version required to use SignalR on ASP.NET core will be .NET Framework 4.6 since we target netstandard 1.3

**Comment by Jenan** [comment]
OK, then is it necesarry or recommended waiting for new version of Asp.Net Core 2.0 and install latest version of SignalR (Microsoft.AspNetCore.SignalR)?

**Comment by shaggygi** [comment]
Yup, I would wait until the release later this year.   You can hear more about updates Tuesday at https://live.asp.net/.  There will also be a session at [Build 2017](https://build.microsoft.com/) in less than 2 weeks.

**Comment by Jenan** [comment]
Or is it possible and stable use the following case?
`ASP.NET Core Web Application (.NET Framework)` and `Microsoft.ApplicationInsights.AspNetCore Version="2.0.0"`

Thanks.

**Comment by davidfowl** [comment]
There is no supported "as soon as possible" scenario. It's not done yet. You can grab packages and deal with issues or feature gaps as you encounter them (hack it until it works), but it's use at your own risk.

**Comment by grahamehorner** [comment]
@davidfowl really looking forward to watching //build on Channel9 any hints on what sessions to watch for #SignalR, #kestrel. .netstandard 2.0 etc aka the 😎 stuff

**Comment by HelloKitty** [comment]
Does the closing of this issue signal anything significant in changes towards the project? I realize it's still unreleased, and not ready for production, but is it ready for use at all? Will their be significant API churn in the upcoming months?

**Comment by davidfowl** [comment]
> but is it ready for use at all?

Sure, it works but there will be API changes, especially client side. Probably not big ones but you can expect lots of churn. As for the server side hub API, it's pretty solid and there will be tweaks. Most of the other work will be in protocol changes, missing features (like scale out) and making the product stable (scale testing, browser testing).

You can follow this issue to see a big picture of the current state https://github.com/aspnet/SignalR/issues/394.

**Comment by joeangry** [comment]
@davidfowl what if I've got an old SignalR 2.2.2 project which is self hosted. Will I be able to call that from SignalR Core? Or are they not compatible?

**Comment by davidfowl** [comment]
@joeangry they aren't compatible. Though I'm not 100% sure what you mean by being able to "call it from signalr core".

**Comment by joeangry** [comment]
So I've got a SignalR host in v2.2.2. Then I've got a website that uses SignalR Core. Does that make more sense?

**Comment by davidfowl** [comment]
Not really. Are you asking if the SignalR Core Client is compatible with the 2.2.2 server? It's not.

**Comment by Jenan** [comment]
@davidfowl  The .NET Core 2.0 is released - is it ready SignalR too for production use or will be in the future? Thx.

**Comment by davidfowl** [comment]
> is it ready SignalR for .NET Core too for production use or will be in the future? Thx.

No, SignalR hasn't been released as part of .NET Core 2.0. It's part of ASP.NET Core 2.1

**Comment by Spiralis** [comment]
@davidfowl How can I start implementing usage of SignalR now for an ASP.Net Core 2 project, if at all possible? I know that it will not be released until 2.1 is out. And I understand that it probably will have bugs and potentially miss some features. But, it might be that I can get away with the limitations early on. And - I guess it would be good for you guys to potentially get some feedback on issues too? The project I am thinking about using this for will probably not be released until early next year anyway.

**Comment by davidfowl** [comment]
We're going to be releasing an alpha on top of 2.0.0 in a few weeks, but using it in production will not be recommended (as with all pre-release software). It's an early release to get feedback. All future previews will be on top of 2.1.

**Comment by rasheedalsheikh** [comment]
is the client library gonna be bound to typescript?

**Comment by moozzyk** [comment]
@rasheedalsheikh - what do you mean by "bound to typescript"?

**Comment by bangonkali** [comment]
Has the alpha been released?

**Comment by davidfowl** [comment]
nope

**Comment by maniphanh** [comment]
David, 
Is there a place to check or subscribe to when Alpha is out?

**Comment by davidfowl** [comment]
https://blogs.msdn.microsoft.com/webdev/

**Comment by shelland** [comment]
What about SignalR for Java? Is it completely dead?

**Comment by davidfowl** [comment]
There will be a new Java client.

**Comment by MattHartz** [comment]
@davidfowl,
Is Alpha considered production ready? We just need basic signalr functionality without jquery dependency 
 (our frontend is written in reactjs) while our product is in it's infancy (small user base).

**Comment by davidfowl** [comment]
No, it is not. If you have an internal facing site, it's probably fine. External facing, it's really not.

**Comment by MattHartz** [comment]
@davidfowl Okay thanks for the update.

**Comment by coultonluke** [comment]
How about now?

**Comment by davidfowl** [comment]
Still no

**Comment by coultonluke** [comment]
Thanks.  Really sad to hear this cause I was excited to write a new project in Core.  I notice that the Nuget package says final, does that mean that it's nearly there? :)

**Comment by davidfowl** [comment]
When the preview moniker is removed

**Comment by anurse** [comment]
> I notice that the Nuget package says final, does that mean that it's nearly there? :)

The only purpose for the word `-final` in there is to distinguish between our nightly builds (in the form `1.0.0-alpha2-12345`). Because of how NuGet and Semantic Versions work, we have to put the `-final` in there (`1.0.0-alpha2-final`) so that NuGet sees it as a **higher** version than the nightly builds. So the `-final` suffix simply refers to it being the last build of the **alpha** release, which is definitely not production ready.

As @davidfowl points out, generally only RTM versions (i.e. `1.0.0` with no suffix) are fully supported production-ready releases.

SignalR will be part of the ASP.NET Core 2.1 release, which is currently aiming for Q1/Q2 2018 as per the Roadmap: https://github.com/aspnet/Home/wiki/Roadmap, at which point it will be production-ready.

**Comment by davenewza** [comment]
> There will be a new Java client.

@davidfowl are you able to confirm if this would this be released along with RTM?

**Comment by davidfowl** [comment]
> @davidfowl are you able to confirm if this would this be released along with RTM?

It won't. RTM clients are typescript/javascript and the .NET Standard client. We're starting the c++ client https://github.com/aspnet/SignalR/pull/1703 and the java client will be the next after we ship the RTM.

**Comment by anurse** [comment]
> We're starting the c++ client

And to be extra clear, even though we're starting the C++ client now, it **is not shipping in 2.1 RTM**. We aren't yet sure exactly when it will ship, it's just experimental at the moment.

**Comment by Bloodday** [comment]
the communication will be backward compatible? if i make a gameserver on top of  ASP.net core 2.1 SignalR the client that is out for Unity 3d (https://github.com/NVentimiglia/SignalR-Unity3d) will work?

**Comment by skoruba** [comment]
How about now? :)

**Comment by davidfowl** [comment]
SignalR 1.0.0 was released on nuget yesterday

**Comment by davidfowl** [comment]
Yes

**Comment by crowz4k** [comment]
Actually, we are working on a new project (.net core 2.1 with tag-helpers) and we were wondering if we can use SignalR, so I am wondering how hard is to do that can you recommend any good book or place to learn and is there any additional discord or place to chat

**Comment by BrennanConroy** [comment]
Docs is always a good start https://docs.microsoft.com/en-us/aspnet/core/signalr/?view=aspnetcore-2.1

**Comment by Jayant369963** [comment]
Hi there, can I use the Asp.NET core SignalR client library for my Asp.NET SignalR backend?

**Comment by davidfowl** [comment]
@Jayant369963 nope.
