### ISSUE TITLE
How upgrade my project from SignalR-Server to new SignalR package

### ISSUE THREAD

**Issue by Jenan** [aspnet/SignalR#430]
I have use the package `SignalR-Server` and I have tried to upgrade my code to new version of `SignalR` and I get some error because is missing following:

I have a combination the `SignalR` hub with `Web Api`:

```
public abstract class ApiHubController<T> : Controller
        where T : Hub
    {
        private readonly IHubContext _hub;
        public IHubConnectionContext<dynamic> Clients { get; private set; }
        public IGroupManager Groups { get; private set; }
        protected ApiHubController(IConnectionManager signalRConnectionManager)
        {
            var _hub = signalRConnectionManager.GetHubContext<T>();
            Clients = _hub.Clients;
            Groups = _hub.Groups;
        }
    }

```
There is missing the `IConnectionManager`.

In my Web Api controller I use the property `Clients` from ApiHubController like this:

`Clients.All.MethodName("test");`

And finally I can't create the custom authorize attribute like this:

```
public class AuthorizeHub : AuthorizeAttribute
	{
		public override bool AuthorizeHubConnection(HubDescriptor hubDescriptor, HttpRequest request)
		{
			var token = request.Query["token"];

			if (token.Count == 0) return false;

			var accessToken = token[0];

			//Validate token

			return true;
		}

		public override bool AuthorizeHubMethodInvocation(IHubIncomingInvokerContext hubIncomingInvokerContext, bool appliesToMethod)
		{
			var args = hubIncomingInvokerContext.Args.ToList();

			if (args.Count == 0) return false;

			var accessToken = args[0];

			//Validate token

			return true;
		}		
	}
```

How can I fix my code?

Thanks for any suggestions.

**Comment by davidfowl** [comment]
There's no longer a custom authorize attribute, SignalR uses the ASP.NET Core auth system and attribute doesn't work quite as yet.

**Comment by Jenan** [comment]
OK, I see but how can I catch action like in this method: AuthorizeHubConnection?

**Comment by davidfowl** [comment]
> OK, I see but how can I catch action like in this method: AuthorizeHubConnection?

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies
