### ISSUE TITLE
Switch to using shared-source ObjectMethodExecutor

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#432]
See https://github.com/aspnet/Common/pull/217

We should use this instead of our copy. Should be a simple swap.

**Comment by BrennanConroy** [comment]
So one small problem possibly is our ObjectMethodExecutor supports `static` methods, and it doesn't look like the common one does :/

**Comment by anurse** [comment]
Send a PR then :)

**Comment by anurse** [comment]
If we're supporting `static` methods in Hubs, then Controllers should probably support them too.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/1da4e07fff263c39edb6382d448fac65f358020b
