### ISSUE TITLE
SignalR does not use WebSockets

### ISSUE THREAD

**Issue by izverev-aexsoft** [aspnet/SignalR#435]
I'm running into problem trying to use WebSockets. Always falls back to long polling.
What is my implementation about:
- Project uses net461 framework
- Using package Microsoft.AspNet.SignalR.Core 2.2.1
- Using OWIN integration, so AppBuilder.MapSignalR(), not AddSignalR() call
- Windows 8.1 Enterprise
- VS 2015, IIS Express, also tried at AWS server IIS with same result
- Latest Chrome browser

What I did:
- Enabled Websockets as IIS component
- Added reference to Microsoft.AspNetCore.WebSockets 1.0.1 and call to UseWebSockets() extension
- Client specifies webSockets as required protocol

What I do not have:
- httpRuntime targetFramework="4.5" - not sure if I need this line in Web.config, once trying to add, application can not start, seen it in some recommendations on the web

Sidenote:
- websockets work well in another sample app (not SignalR)

Do I miss anything?

**Comment by moozzyk** [comment]
Are you by any chance trying to run SignalR 2.2.1 in an Asp.NET Core project?

**Comment by izverev-aexsoft** [comment]
We use full framework (net461), and SignalR works fine except of this issue.

**Comment by moozzyk** [comment]
In that case this _Added reference to Microsoft.AspNetCore.WebSockets 1.0.1 and call to UseWebSockets() extension_ is not needed and in the best case will do nothing.
What do you get if you try to request: `http://{your-server}/signalr/negotiate`?
Turn on logging and check what the client logs. 
It is weird that the client falls back to long polling if you only want to use webSockets transport. Can you show your code?

**Comment by izverev-aexsoft** [comment]
I request longPolling along with webSockets. Here is the error which I get leaving webSockets alone:
"No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization."
I'd like to trace transport selection process more detailed, but only doc I found on this matter is https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#server_text, it requires to modify system.diagnostics section of Web.config which seem does not work with ASP.NET Core.

**Comment by moozzyk** [comment]
Again: What do you get if you try to request: http://{your-server}/signalr/negotiate?

**Comment by izverev-aexsoft** [comment]
`{"Url":"/signalr","ConnectionToken":"98eff824-cf37-45fc-aafa-92cdc6585306:","ConnectionId":"98eff824-cf37-45fc-aafa-92cdc6585306","KeepAliveTimeout":6.0,"DisconnectTimeout":10.0,"ConnectionTimeout":10.0,"TryWebSockets":false,"ProtocolVersion":"1.2","TransportConnectTimeout":5.0,"LongPollDelay":0.0}`

**Comment by moozzyk** [comment]
"TryWebSockets":false, - indicates that webSockets were not turned on the server side so the client does not even try starting the webSockets transport.

**Comment by izverev-aexsoft** [comment]
Websockets feature is installed in system. Websocket-only app (no SignalR) works (on IIS express).
Is there SignalR-specific setting?

**Comment by moozzyk** [comment]
If you are running this in ASP.NET Core then probably [context.Environment.SupportsWebSockets()](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Core/PersistentConnection.cs#L515) returns false. I don't know how this is being set.

**Comment by jkells** [comment]
SignalR 2 isn't supported on ASP.NET Core and SignalR 3 isn't ready yet.

As you've discovered you can get it running but WebSockets doesn't work. You can get WebSockets to work with a few hacks to SignalR. See here: https://github.com/jkells/SignalR/commit/58e6b9a3c01349f09b7d5e198cd673684e64b3ae

And here is a sample: https://github.com/jkells/signalr2-netcore-websockets-sample

We've been running this hack in production since January with no issues but YMMV, some features of SignalR might not work.

**Comment by moozzyk** [comment]
As per @jkells comment we don't support running SignalR 2 in ASP.NET Core apps and there are no plans to support this scenario.

**Comment by ondravondra** [comment]
@jkells I made the original signalr2 nuget package work with core using this hack:

```
private void HackInWebsockets(IAppBuilder app)
{
    app.Use((c, n) =>
    {
        c.Environment.Add("server.Capabilities", new Dictionary<string, object>
        {
            { "websocket.Version", "1.0" }
        });

        var accept = c.Get<Action<IDictionary<string, object>, Func<IDictionary<string, object>, Task>>>("websocket.Accept");
        if (accept != null)
        {
            c.Set<Action<IDictionary<string, object>, Func<IDictionary<string, object>, Task>>>("websocket.Accept", (_, hcb) =>
            {
                accept(_, aenv =>
                {
                    aenv.Add(typeof(WebSocketContext).FullName, new HackedWebSocketContext((WebSocket)aenv[typeof(WebSocket).FullName]));
                    return hcb(aenv);
                });
            });
        }

        return n();
    });
}

private class HackedWebSocketContext : WebSocketContext
{
    private readonly WebSocket webSocket;

    public override Uri RequestUri => throw new NotImplementedException();

    public override NameValueCollection Headers => throw new NotImplementedException();

    public override string Origin => throw new NotImplementedException();

    public override IEnumerable<string> SecWebSocketProtocols => throw new NotImplementedException();

    public override string SecWebSocketVersion => throw new NotImplementedException();

    public override string SecWebSocketKey => throw new NotImplementedException();

    public override CookieCollection CookieCollection => throw new NotImplementedException();

    public override IPrincipal User => throw new NotImplementedException();

    public override bool IsAuthenticated => throw new NotImplementedException();

    public override bool IsLocal => throw new NotImplementedException();

    public override bool IsSecureConnection => throw new NotImplementedException();

    public override WebSocket WebSocket => webSocket;

    public HackedWebSocketContext(WebSocket webSocket)
    {
        this.webSocket = webSocket;
    }
}
```

SignalR code only uses `WebSocket` property of `WebSocketContext` so I did not implement the others.
`IAppBuilder` is from `Owin.dll`

**Comment by izverev-aexsoft** [comment]
@jkells thank you, it worked for us!

**Comment by izverev-aexsoft** [comment]
@ondravondra but your hack was better, because keeping modified SignalR sources along with the main project is a pain. Thank you!

**Comment by Spiti** [comment]
I tried the approach above, it upgrades to websockets, but it also upgrades to sse and connects to it, so websockets is not used. Any ideas? @izverev-aexsoft can you share you solution?

**Comment by izverev-aexsoft** [comment]
@Spiti our clients are set up to use only long polling and websockets, so the server have to choose websockets.

**Comment by Spiti** [comment]
I did the hack, but it does not succeed to connect using web sockets. Please see attached.
![image](https://user-images.githubusercontent.com/8936434/38096313-3c0018f4-337b-11e8-9520-7413139b1188.png)
