### ISSUE TITLE
Unable to resolve netcoreapp2.0

### ISSUE THREAD

**Issue by vany0114** [aspnet/SignalR#455]
Hi guys, 

I've been trying to compile this project or even use the nuget Microsoft.AspNetCore.SignalR (from here https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json) but didn't work, because it depends on .netcore 2.0. I installed manually the SDK from here (https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview1-download.md), but it not appear in VS2017 as a framework version available. Anybody can help me about that?

Thanks a lot.

**Comment by davidfowl** [comment]
You need to install Visual Studio 15.3 preview

**Comment by vany0114** [comment]
Thanks @davidfowl I skiped that step because I had already installed VS2017, but I realized is another version...do you know why Microsoft released another Visual Studio version and don't an update or something like that?

**Comment by grahamehorner** [comment]
@vany0114 VS2017 & VS15 are one in the same VS15.3 or VS2017.3 preview is a preview of an upcome update to VS to support new Windows 10 & .NET features check #Build for more information
