### ISSUE TITLE
Question: Multiple Hubs

### ISSUE THREAD

**Issue by harisbotic** [aspnet/SignalR#456]
Is it better design to have two separate hubs (ex. MainHub, ChatHub) so if client doesn't want to use chat he simply doesn't connect to ChatHub
or
to still have two separate hubs, but on the same link
```csharp
app.UseSignalR(routes =>
{
      routes.MapHub<MainHub>("/signalr");
      routes.MapHub<ChatHub>("/signalr");
});
```

Would the second way even work as in old SignalR?

**Comment by ondravondra** [comment]
We have hubs separated by the app feature they handle and the second way (multiple separate hubs on single connection) is a must have for us.

**Comment by anurse** [comment]
You'd need to have separate URLs for each Hub. Part of the reason for simplifying to one-hub-per-endpoint is to make it clear which connections are associated with which Hubs. This is much simpler and clearer in SignalR Core.

One consideration to make is that if you **are not** using WebSockets or HTTP/2, browsers tend to have a relatively low limit on the number of outstanding connections that can be made to a single domain. In most browsers, that number is 6. When using Long Polling or Server-Sent Events, each Hub would occupy one of these 6 allowed connections to do the polling/event streaming. You still need a free connection for sending to the Hub (as that's done via a separate AJAX call), so you have a hard maximum of 5 Hubs before you'd start seeing problems with polling (and even with 5 you are only leaving one free connection for sending and other AJAX calls).

**NOTE**: HTTP/2 removes this limitation by sharing a single connection for all traffic, so you wouldn't have this limit (currently only [HttpSysServer](https://github.com/aspnet/HttpSysServer) supports HTTP/2 though). Also the limits for WebSockets are generally much higher. I believe it's about 30 per host in Chrome, for example.

**Comment by davidfowl** [comment]
@harisbotic How many hubs do you have in your application?

**Comment by harisbotic** [comment]
One for now, but I am about to create a second

**Comment by anurse** [comment]
> One consideration to make is that if you are not using WebSockets or HTTP/2, browsers tend to have a relatively low limit on the number of outstanding connections that can be made to a single domain.

To be clear, this would not limit the number of Hubs you can have in your application. Only the number of Hubs a single user can connect to **from a single page**

**Comment by harisbotic** [comment]
Yeah I see, thank you for clarifying it.
So to simplify it, you are saying that there shouldn't be any problems in having more hubs (unless in situations you specified), and that its better to have one-hub-per-endpoint for concept separation.
