### ISSUE TITLE
Enable EndPoints and Hubs to "require HTTPS"

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#457]
We have the `RequireHttps` attribute in MVC. SignalR will likely need something similar for EndPoints and Hubs. This attribute would ensure that only WebSocket connections made over `wss://` and HTTP Poll/SSE/Send requests made over `https://` are accepted at that EndPoint/Hub

**Comment by anurse** [comment]
This can be done using middleware or an Authorization policy for now, so it doesn't need to be done right now.

**Comment by davidfowl** [comment]
Or ever 😄

**Comment by davidfowl** [comment]
@anurse I'm closing this. The https middleware should handle this. Though it probably shouldn't redirect...
