### ISSUE TITLE
How do I use the npm client or a js client?

### ISSUE THREAD

**Issue by vany0114** [aspnet/SignalR#458]
Hi there,

I'm trying to use the npm signalr-client, any example to use in VS2017? I don't see the way to connect to the server from javascript client, the Microsoft.AspNetCore.SignalR.Client.TS project example doesn't generate the signalr-client.js, so I don't know how to I could connected to the server with this new version of SignalR.

Thanks.

**Comment by moozzyk** [comment]
One way is to use npm to install the module and then copy the signalr-client.js file to the folder with scripts. You can use MSBuild Copy task to do that in one of the targets invoked during build (e.g. AfterBuild) - https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/ChatSample.csproj#L47-L49

**Comment by vany0114** [comment]
Thanks @moozzyk I already did that (use npm to install the module) but this client is for node js server right?...if I use it doesn't work because it's not able to resolve its dependencies.

By the other hand, I achieved compile de js client from this project, so meanwhile I'm working with it.

**Comment by moozzyk** [comment]
This client is a browser agnostic signalr js client. The npm package is one of the way of distributing it.  The idea was that it should be possible to run it with node but the user needs to provide functionality that is missing via polyfills. 

> if I use it doesn't work because it's not able to resolve its dependencies

Not sure what you meant here - the module has no dependencies. If this was about xhr or websockets not present - as I said they are supposed to be provided by the user. (Admittedly, I have not tried it yet so there might be some work required if it is too hard),

**Comment by vany0114** [comment]
I mean, when I tried to use this client, the error was about these lines:

```
var url = require('url'),
    querystring = require('querystring'),
    http = require('http'),
    https = require('https'),
    WebSocketClient = require('websocket').client; // https://github.com/Worlize/WebSocket-Node
```

I took the usage example:

```
var signalR = require('./signalr.js');
var client  = new signalR.client(
	"http://localhost:8080/signalR",  //signalR service URL
	['TestHub'],                      // array of hubs to be supported in the connection
    2,                                //optional: retry timeout in seconds (default: 10)
    true                              //optional: doNotStart default false
);
```
I imagine I have to configure the "url", "querystring" and the other modules in require, but I don't know, the truth is I'm a little confused. 

In order to use the signalR module, I installed require js and I configured the path for signalr module pointing to "npm modules" folder.

So I think that I'm doing something wrong...you can give some example to use this client, please?
