### ISSUE TITLE
Publish the signalr-client

### ISSUE THREAD

**Issue by fazouane-marouane** [aspnet/SignalR#459]
Hi,

There are some issues in the way the new signalr client is published:
1. There's already a package named "signalr-client" in the npm registry. So it's better to pick another one.
2. Installing the client from myget, with the current naming convention, is not realistic. You should use npm scopes (myget is compatible with this).

So I suggest that either you rename the package and publish it to the official npm registry, or you carry on using myget but change the package name to `@signalr/client` or something similar.

I'm open to discussion and don't hesitate to ask me to clarify specific points.

**Comment by anurse** [comment]
We're publishing to MyGet because there hasn't been an official release yet. When there's an official release, it will be published to the NPM official feed. As to using NPM scopes, we can consider that before a final release is made.

**Comment by fazouane-marouane** [comment]
@anurse
That's great news! In fact, the expected workflow is to have a .npmrc file with the following content (assuming the final package is `@aspnet/signalr`

@aspnet:registry="https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/"

So when we build through a CI system all our packages will go through the official npm registry expect for packages with scope @aspnet.

**Comment by fazouane-marouane** [comment]
Hi

So what's your stance on changing the package's name before the final release? 
If this is not the right place to discuss such issues, please let me know.

**Comment by odannyboy000** [comment]
@anurse Would you be willing to publish the signalr-client package with an npm scope before release?

It's difficult to share npm packages with teammates right now because they have to manually install the signalr client rather that allowing us to specify them in an .npmrc file.

**Comment by anurse** [comment]
I think we could consider doing so. @moozzyk, @davidfowl, we should consider how we're going to publish our NPM packages soon, so we can get people on-board with dogfooding.

**Comment by moozzyk** [comment]
signalr-client is now @aspnet/signalr-client (cdbb13de66b068015d068e5fab67e4e6ab42d3da). You can install it from myget using the following command:
```
 npm install @aspnet/signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/
```
We will remove the non-scoped version of the client from myget soon.
