### ISSUE TITLE
npm WARN deprecated

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#467]
please consider update npm deprecated packages

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by moozzyk** [comment]
We don't have direct dependencies on these packages and the last time I looked at packages that depend those were not updated to depend non-deprecated versions.

**Comment by davidfowl** [comment]
@anurse we fixed these warnings (at least I don't see them in the build anymore)

**Comment by anurse** [comment]
Closing the issue then :)
