### ISSUE TITLE
The server does not terminate long polling connection cleanly 

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#469]
If the user send a message and immediately leaves the OnConnectedAsync method like this: https://github.com/aspnet/SignalR/blob/8f18ff44234e038c6728f9798faf970df3244fad/test/Microsoft.AspNetCore.SignalR.Tests/EchoEndPoint.cs#L11-L14 the connection always closes with 404 error on the client. The problem is that when the user leaves the OnConnectedAsync we immediately clean up the connection but since we just sent data to the client there is no pending poll. As a result when the poll request arrives from the client the connection has already been cleaned up and the poll request is rejected with 404.

**Comment by davidfowl** [comment]
Good catch.
