### ISSUE TITLE
samples not working

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#472]
An error occurred while starting the application.
NullReferenceException: Object reference not set to an instance of an object.
System.Diagnostics.DiagnosticListener..ctor(string name)
TypeInitializationException: The type initializer for 'System.Diagnostics.HttpHandlerDiagnosticListener' threw an exception.
System.Diagnostics.DiagnosticListener.get_AllListeners()
NullReferenceException: Object reference not set to an instance of an object.
System.Diagnostics.DiagnosticListener..ctor(string name)
System.Diagnostics.HttpHandlerDiagnosticListener..cctor()

Show raw exception details 
System.NullReferenceException: Object reference not set to an instance of an object.

   at System.Diagnostics.DiagnosticListener..ctor(String name)

   at System.Diagnostics.HttpHandlerDiagnosticListener..cctor()
TypeInitializationException: The type initializer for 'System.Diagnostics.HttpHandlerDiagnosticListener' threw an exception.
System.Diagnostics.DiagnosticListener.get_AllListeners()
Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsInitializer.Start()
Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Show raw exception details 
System.TypeInitializationException: The type initializer for 'System.Diagnostics.HttpHandlerDiagnosticListener' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at System.Diagnostics.DiagnosticListener..ctor(String name)

   at System.Diagnostics.HttpHandlerDiagnosticListener..cctor()

   --- End of inner exception stack trace ---

   at System.Diagnostics.DiagnosticListener.get_AllListeners()

   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsInitializer.Start()

   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)

   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
.NET Core X64 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.0.0-preview2-25138    |    Microsoft Windows 10.0.15063    |   Need help?

**Comment by moozzyk** [comment]
which sample is that?

**Comment by davidfowl** [comment]
It's the new light up feature wreaking havoc on our projects. There's an issue where it blindly injects an incompatible app insights into the application.

**Comment by grahamehorner** [comment]
@davidfowl any advice on how/if to stop it so I can try the samples?

**Comment by grahamehorner** [comment]
@moozzyk all samples impacted 😭

**Comment by davidfowl** [comment]
I'll fix the samples.

**Comment by davidfowl** [comment]
Fixed in https://github.com/aspnet/SignalR/commit/87c4da41e8440554119a8331b76c21ba2065e952

**Comment by grahamehorner** [comment]
Please consider adding check to unit tests for this type of situation

**Comment by davidfowl** [comment]
This isn't a unit test type situation. This is actually a very special case. The tooling needs to be fixed. It's not a SignalR issue, it's a problem with how VS in injecting incompatible code into *any* ASP.NET Core application and breaking them. My "fix" is temporary.

**Comment by grahamehorner** [comment]
@davidfowl please forgive my ignorance, and just to make sure I fully understand, when you say tooling, VS is this only an IDE issue for VS2017 (including update 3) and/or VSCODE, dotnet run ... etc.  is there any links to the issue? (again for my understanding only)

keep up the great work guys, loving the road map for SignalR, etc ...  and have some interesting project that I'm excited to use SignalR for ;)
