### ISSUE TITLE
How can i use aspnetcore Signalr? 

### ISSUE THREAD

**Issue by safakseyrek** [aspnet/SignalR#480]
Hi,
I need aspentcore signalr server nuget links or need aspnetcore SignalR server document.

**Comment by BrennanConroy** [comment]
Since this hasn't been released yet there is no nuget link. I can give you the link to our nightly dev feeds for the latest bits: https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.AspNetCore.SignalR
As for using it, try looking at the samples in this repo https://github.com/aspnet/SignalR/tree/dev/samples/ChatSample

**Comment by safakseyrek** [comment]
thanks . i want to use with xamarin forms and aspnetcore signalr. Do you have a document that you know
?

**Comment by grahamehorner** [comment]
@BrennanConroy is there a bower equivalent for the TypeScript client as I'm not able to find to Microsoft.AspNetCore.SignalR.Client.TS using the myget feed?

**Comment by Ibro** [comment]
`npm install signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/`

**Comment by grahamehorner** [comment]
I've created a npm package.json file

{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "devDependencies": {
    "signalr-client" : "https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/"
  }
}

but get the following ?

49 verbose stack Error: ENOENT: no such file or directory, open 'C:\..\package.json'
49 verbose stack     at Error (native)
50 verbose cwd C:\DEV\..\ProjectFolder
51 error Windows_NT 10.0.15063
52 error argv "C:\..\Node.exe" "C:\..\node_modules\\npm\\bin\\npm-cli.js" "install"
53 error node v5.4.1
54 error npm  v3.3.4
55 error path C:\..\package.json
56 error code ENOENT
57 error errno -4058
58 error syscall open
59 error enoent ENOENT: no such file or directory, open 'C:\...\package.json'
59 error enoent This is most likely not a problem with npm itself
59 error enoent and is related to npm not being able to find a file.
60 verbose exit [ -4058, true ]

sorry if this a numpty issue, I'm new to the world of npm ;)  I was hoping that this would download the package when using CI/CD with the docker VSTS-agent?

**Comment by grahamehorner** [comment]
end when running npm I get 

"C:\..\Preview\Enterprise\Web\External\npm" install signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/
npm ERR! fetch failed https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/~0.0.17
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/~0.0.17
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

**Comment by moozzyk** [comment]
@grahamehorner - the package.json needs to look something like this: https://github.com/moozzyk/SignalR-Client-Swift/blob/master/TestServer/package.json. You will probably need to update the version to something that is available here: https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/npm/signalr-client (I did not have luck with wildcards after `preview2` to not have to provide exact version but have not spend too much time on it yet)

**Comment by moozzyk** [comment]
@safakseyrek - the C# client targets netstandard1.3 so you should be able to use it in xamarin. If you can't please open a new issue with error details and repro steps.

**Comment by weitzhandler** [comment]
Where did `IHubProxy` go?
