### ISSUE TITLE
Cancellation in Streamed results

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#481]
We need to review how cancellation works in Streamed results. If the connection terminates, we need to be able to stop enumerating the sequence the user gave us, and ideally signal cancellation back to it in order to cancel any other async operations.

On a similar note, we may want to add support for passing a `CancellationToken` in to a Hub method.

**Comment by grahamehorner** [comment]
@anurse +1 for passing a CancellationToken into a hub method.   question would this be a token from a client or a server side token?  could this be used by an administrator to terminate badly behaved SignalR hub streaming methods? or place a upper limit on time of execution etc.

**Comment by moozzyk** [comment]
Need to expose a CancellationToken to the hub in some way. Needs some design/discussion.

**Comment by davidfowl** [comment]
> On a similar note, we may want to add support for passing a CancellationToken in to a Hub method.

I think we should just expose it as a property on the Context instead of being a parameter.

**Comment by anurse** [comment]
Agreed. If we were going to put it as an argument it would be confused with something the client could control.
