### ISSUE TITLE
Observables returned by the client when streaming may drop events

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#482]
Currently, the implementation of IObservable **on the client** for streaming fires events to all subscribed observers, but does not buffer or store any events for replaying. That means that there is a race between when the Invocation is sent to the server and when the Observer subscribes to the Observable. Any items streamed down before the user code subscribes to the IObservable will be lost. We may want to consider adding some replay/buffering. Alternatively we could have `Stream` simply return an `IObservable` that sends the request when `Subscribe` is called, rather than having `Stream` send the request directly.

**Comment by moozzyk** [comment]
This idea sounds a lot like ring buffer from the old SignalR. I wonder if it is possible not to stream to users who subscribed after streaming started or potentially give the user the option between not streaming and streaming partial results. If you think about stock ticker why would it be useful to stream old results? Also, in this case streaming may never end so storing and replaying all this data is going to be costly while newly joined clients need only the latest data.

**Comment by grahamehorner** [comment]
IMHO these should be separated into hot/cold streams similar to hot/cold observable in RX

**Comment by grahamehorner** [comment]
also wondering if Bart De Smet's work on rx cloud streaming services may be useful 😎

**Comment by anurse** [comment]
@grahamehorner Yep, this is a traditional Hot/Cold Observable problem. I think that SignalR Hubs would always be Cold Observables, in that the Client is structured such that they receive every item sent by the server, without races. If the server wishes to allow Clients to subscribe to Hot Observables via a Hub method, that Hub method would return a new Cold Observable over that Hot Observable that closes over the desired stream. Trying to build a primitive to distinguish between the two gets complicated and is one of those things where we can't easily do it in a default way that any app would want, so it's up to the App to determine the lifetime of a Client's subscription by building an Observable that represents exactly what will be sent to that Client when they request a stream.

@moozzyk The buffering I'm talking about is on the Client, to ensure that any events received in between the Invocation being sent and the Subscribe method being called on the IObservable returned by the client can be replayed. I definitely don't want to add any server buffering.

**Comment by moozzyk** [comment]
@anurse - thanks for clarification - it now makes sense.

**Comment by anurse** [comment]
We're going to use `ReadableChannel<T>` for now, which should resolve this. Channel has an `AsObservable` which can produce an observable.
