### ISSUE TITLE
Consistent, configurable logging in the JavaScript client

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#485]
The JavaScript client (and indeed all the clients) needs to have configurable logging rather than just relying on `console.log` as it does right now.

**Comment by moozzyk** [comment]
This was originally being tracked here: https://github.com/aspnet/SignalR/issues/3 but a separate issue makes it more visible.

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR/pull/484#issuecomment-303706786

**Comment by muratg** [comment]
For alpha1: add ability to turn off console.log lines (for node.js usage). 

In the next milestone we'll design/implement the right abstraction for client side logging.

**Comment by muratg** [comment]
@moozzyk will also look into adding an options object at the HubConnection class.  We want to have a bool value for logging, a logger object and hub protocol.

**Comment by moozzyk** [comment]
Fixed in: e4c1b888ca65045e8ecde700c8289192e6eb5fc0 and 7db480b23e8d11a384b88a34704468341429c562
