### ISSUE TITLE
npm signalr-client issues

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#488]
I'm having issues when trying to use npm to get the signalr-client ?

**npm install signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/**

pm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "signalr-client" "--registry" "https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ETARGET

npm ERR! notarget **No compatible version found: signalr-client@^0.0.17**
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0-preview2-25158, 0.1.0-preview2-25159, 0.1.0-preview2-25160, 0.1.0-preview2-25161, 0.1.0-preview2-25164, 0.1.0-preview2-25165, 0.1.0-preview2-25176, 0.1.0-preview2-25177, 0.1.0-preview2-25178, 0.1.0-preview2-25179
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\...\npm-cache\_logs\2017-05-24T12_17_36_266Z-debug.log

**Comment by dandax** [comment]
Try this:
```
npm install signalr-client@0.1.0-preview2-25179 --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/
```

**Comment by moozzyk** [comment]
Also, see my comment here: https://github.com/aspnet/SignalR/issues/480#issuecomment-303800070

In general the TS client needs some work to improve the user experience but this work will be done after we move some big rocks.

**Comment by grahamehorner** [comment]
I cloned the https://github.com/moozzyk/SignalR-Client-Swift suggested, updated the package.json in (VS2017 update 3) with the current version; saved it the bower/npm output windows shows 

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\npm.CMD" install
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Enterprise\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Enterprise\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! No compatible version found: signalr-client@0.1.0-preview2-25179
npm ERR! Valid install targets:
npm ERR! ["0.0.17","0.0.16","0.0.15","0.0.14","0.0.13","0.0.12","0.0.11","0.0.10","0.0.9","0.0.8","0.0.7","0.0.6","0.0.5","0.0.4","0.0.3","0.0.2","0.0.1"]
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\DEV\github\moozzyk\signalr\TestServer\npm-debug.log

with the npm-debug.log containing

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Enterprise\\Web\\External\\Node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Enterprise\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.4
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData signalr-client
20 silly mapToRegistry name signalr-client
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/signalr-client
24 verbose request uri https://registry.npmjs.org/signalr-client
25 verbose request no auth needed
26 info attempt registry request try #1 at 9:14:09 PM
27 verbose request id 349504e1a18c760e
28 verbose etag W/"57d61f6f-5a9d"
29 verbose lastModified Mon, 12 Sep 2016 03:22:23 GMT
30 http request GET https://registry.npmjs.org/signalr-client
31 http 304 https://registry.npmjs.org/signalr-client
32 verbose headers { date: 'Wed, 24 May 2017 20:14:11 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   'cache-control': 'max-age=300',
32 verbose headers   etag: 'W/"57d61f6f-5a9d"',
32 verbose headers   age: '21',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-lhr6331-LHR',
32 verbose headers   'x-cache': 'HIT',
32 verbose headers   'x-cache-hits': '1',
32 verbose headers   'x-timer': 'S1495656852.669772,VS0,VE0',
32 verbose headers   vary: 'Accept-Encoding' }
33 silly get cb [ 304,
33 silly get   { date: 'Wed, 24 May 2017 20:14:11 GMT',
33 silly get     via: '1.1 varnish',
33 silly get     'cache-control': 'max-age=300',
33 silly get     etag: 'W/"57d61f6f-5a9d"',
33 silly get     age: '21',
33 silly get     connection: 'keep-alive',
33 silly get     'x-served-by': 'cache-lhr6331-LHR',
33 silly get     'x-cache': 'HIT',
33 silly get     'x-cache-hits': '1',
33 silly get     'x-timer': 'S1495656852.669772,VS0,VE0',
33 silly get     vary: 'Accept-Encoding' } ]
34 verbose etag https://registry.npmjs.org/signalr-client from cache
35 verbose get saving signalr-client to C:\Users\GrahameHorner\AppData\Roaming\npm-cache\registry.npmjs.org\signalr-client\.cache.json
36 silly fetchPackageMetaData Error: No compatible version found: signalr-client@0.1.0-preview2-25179
36 silly fetchPackageMetaData Valid install targets:
36 silly fetchPackageMetaData ["0.0.17","0.0.16","0.0.15","0.0.14","0.0.13","0.0.12","0.0.11","0.0.10","0.0.9","0.0.8","0.0.7","0.0.6","0.0.5","0.0.4","0.0.3","0.0.2","0.0.1"]
36 silly fetchPackageMetaData
36 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\npm\lib\fetch-package-metadata.js:146:16)
36 silly fetchPackageMetaData     at C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\iferr\index.js:13:50
36 silly fetchPackageMetaData     at C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\npm\lib\utils\pulse-till-done.js:19:8
36 silly fetchPackageMetaData     at saved (C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\npm\lib\cache\caching-client.js:168:7)
36 silly fetchPackageMetaData     at C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
36 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:82:15)
36 silly fetchPackageMetaData  error for signalr-client@0.1.0-preview2-25179 [Error: No compatible version found: signalr-client@0.1.0-preview2-25179
36 silly fetchPackageMetaData Valid install targets:
36 silly fetchPackageMetaData ["0.0.17","0.0.16","0.0.15","0.0.14","0.0.13","0.0.12","0.0.11","0.0.10","0.0.9","0.0.8","0.0.7","0.0.6","0.0.5","0.0.4","0.0.3","0.0.2","0.0.1"]
36 silly fetchPackageMetaData ]
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: No compatible version found: signalr-client@0.1.0-preview2-25179
42 verbose stack Valid install targets:
42 verbose stack ["0.0.17","0.0.16","0.0.15","0.0.14","0.0.13","0.0.12","0.0.11","0.0.10","0.0.9","0.0.8","0.0.7","0.0.6","0.0.5","0.0.4","0.0.3","0.0.2","0.0.1"]
42 verbose stack
42 verbose stack     at pickVersionFromRegistryDocument (C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\npm\lib\fetch-package-metadata.js:146:16)
42 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\iferr\index.js:13:50
42 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\npm\lib\utils\pulse-till-done.js:19:8
42 verbose stack     at saved (C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\npm\lib\cache\caching-client.js:168:7)
42 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Web\External\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
42 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
43 verbose cwd C:\DEV\github\moozzyk\signalr\TestServer
44 error Windows_NT 10.0.15063
45 error argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Enterprise\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Enterprise\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
46 error node v5.4.1
47 error npm  v3.3.4
48 error No compatible version found: signalr-client@0.1.0-preview2-25179
48 error Valid install targets:
48 error ["0.0.17","0.0.16","0.0.15","0.0.14","0.0.13","0.0.12","0.0.11","0.0.10","0.0.9","0.0.8","0.0.7","0.0.6","0.0.5","0.0.4","0.0.3","0.0.2","0.0.1"]
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by moozzyk** [comment]
Did you use the right `--registry`?

```
PS C:\source\SignalR-Client-Swift\TestServer> npm install --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/
test-server-dev@1.0.0 C:\source\SignalR-Client-Swift\TestServer
`-- signalr-client@0.1.0-preview2-25179

npm WARN test-server-dev@1.0.0 No description
npm WARN test-server-dev@1.0.0 No repository field.
PS C:\source\SignalR-Client-Swift\TestServer>
```

**Comment by grahamehorner** [comment]
Yeah, did that using cmd with administrative permissions

**Comment by moozzyk** [comment]
Admin rights should not be needed - I ran my command from a regular command prompt.

**Comment by grahamehorner** [comment]
Ok, thanks will try again in morning

**Comment by grahamehorner** [comment]
Ok, still no joy; running in a PS command window as a normal user :'(

PS C:\DEV\github\moozzyk\signalr\TestServer> npm install --registry https://dotnet.my
get.org/f/aspnetcore-ci-dev/npm/ test-server-dev@1.0.0 C:\DEV\github\moozzyk\signalr\
TestServer -- signalr-client@0.1.0-preview2-25179
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--registry" "https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/" "test-server-dev@1.0.0" "C:\\DEV\\github\\moozzyk\\signalr\\TestServer" "--" "signalr-client@0.1.0-preview2-25179"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Not Found

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\GrahameHorner\AppData\Roaming\npm-cache\_logs\2017-05-25T09_02_39_401Z-debug.log
PS C:\DEV\github\moozzyk\signalr\TestServer>


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--registry',
1 verbose cli   'https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/',
1 verbose cli   'test-server-dev@1.0.0',
1 verbose cli   'C:\\DEV\\github\\moozzyk\\signalr\\TestServer',
1 verbose cli   '--',
1 verbose cli   'signalr-client@0.1.0-preview2-25179' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData test-server-dev@1.0.0
8 silly fetchPackageMetaData signalr-client@0.1.0-preview2-25179
9 silly fetchNamedPackageData test-server-dev
10 silly mapToRegistry name test-server-dev
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'test-server-dev',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'test-server-dev',
13 silly mapToRegistry   name: 'test-server-dev',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/test-server-dev
15 silly fetchNamedPackageData signalr-client
16 silly mapToRegistry name signalr-client
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry **https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/**
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'signalr-client',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'signalr-client',
19 silly mapToRegistry   name: 'signalr-client',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/signalr-client
21 verbose request uri https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/test-server-dev
22 verbose request no auth needed
23 info attempt registry request try #1 at 10:02:38 AM
24 verbose request id fdfa1ee478b729e6
25 http request GET https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/test-server-dev
26 verbose request uri https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/signalr-client
27 verbose request no auth needed
28 info attempt registry request try #1 at 10:02:38 AM
29 http request GET https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/signalr-client
30 http 200 https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/signalr-client
31 verbose headers { 'cache-control': 'private, s-maxage=0',
31 verbose headers   'transfer-encoding': 'chunked',
31 verbose headers   'content-type': 'application/json',
31 verbose headers   server: 'Microsoft-IIS/10.0',
31 verbose headers   'request-context': 'appId=cid-v1:745096cd-dd19-46b9-b5a5-9f51fe240388',
31 verbose headers   'x-frame-options': 'deny',
31 verbose headers   'x-xss-protection': '1; mode=block',
31 verbose headers   'x-content-type-options': 'nosniff',
31 verbose headers   date: 'Thu, 25 May 2017 09:02:40 GMT' }
32 silly get cb [ 200,
32 silly get   { 'cache-control': 'private, s-maxage=0',
32 silly get     'transfer-encoding': 'chunked',
32 silly get     'content-type': 'application/json',
32 silly get     server: 'Microsoft-IIS/10.0',
32 silly get     'request-context': 'appId=cid-v1:745096cd-dd19-46b9-b5a5-9f51fe240388',
32 silly get     'x-frame-options': 'deny',
32 silly get     'x-xss-protection': '1; mode=block',
32 silly get     'x-content-type-options': 'nosniff',
32 silly get     date: 'Thu, 25 May 2017 09:02:40 GMT' } ]
33 verbose get saving signalr-client to C:\Users\GrahameHorner\AppData\Roaming\npm-cache\**dotnet.myget.org\f\aspnetcore-ci-dev\npm\signalr-client\**.cache.json
34 verbose correctMkdir C:\Users\GrahameHorner\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
35 silly pickManifestFromRegistryMetadata spec 0.1.0-preview2-25179 tag latest versions [ '0.1.0-preview2-25177',
35 silly pickManifestFromRegistryMetadata   '0.1.0-preview2-25178',
35 silly pickManifestFromRegistryMetadata   '0.1.0-preview2-25179',
35 silly pickManifestFromRegistryMetadata   '0.1.0-preview2-25219',
35 silly pickManifestFromRegistryMetadata   '0.1.0-preview2-25220',
35 silly pickManifestFromRegistryMetadata   '0.1.0-preview2-25223',
35 silly pickManifestFromRegistryMetadata   '0.1.0-preview2-25226',
35 silly pickManifestFromRegistryMetadata   '0.1.0-preview2-25227',
35 silly pickManifestFromRegistryMetadata   '0.1.0-preview2-25228',
35 silly pickManifestFromRegistryMetadata   '0.1.0-preview2-25229' ]
36 **http 404 https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/test-server-dev**
37 verbose headers { 'cache-control': 'private, s-maxage=0',
37 verbose headers   server: 'Microsoft-IIS/10.0',
37 verbose headers   'request-context': 'appId=cid-v1:745096cd-dd19-46b9-b5a5-9f51fe240388',
37 verbose headers   'x-frame-options': 'deny',
37 verbose headers   'x-xss-protection': '1; mode=block',
37 verbose headers   'x-content-type-options': 'nosniff',
37 verbose headers   date: 'Thu, 25 May 2017 09:02:41 GMT',
37 verbose headers   'content-length': '0' }
38 silly get cb [ 404,
38 silly get   { 'cache-control': 'private, s-maxage=0',
38 silly get     server: 'Microsoft-IIS/10.0',
38 silly get     'request-context': 'appId=cid-v1:745096cd-dd19-46b9-b5a5-9f51fe240388',
38 silly get     'x-frame-options': 'deny',
38 silly get     'x-xss-protection': '1; mode=block',
38 silly get     'x-content-type-options': 'nosniff',
38 silly get     date: 'Thu, 25 May 2017 09:02:41 GMT',
38 silly get     'content-length': '0' } ]
39 silly fetchPackageMetaData Error: 404 Not Found
39 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:304:12)
39 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:255:9)
39 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
39 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:186:22)
39 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
39 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
39 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1081:10)
39 silly fetchPackageMetaData     at emitOne (events.js:96:13)
39 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
39 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1001:12)
39 silly fetchPackageMetaData  error for test-server-dev@1.0.0 { Error: 404 Not Found
39 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:304:12)
39 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:255:9)
39 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
39 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:186:22)
39 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
39 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
39 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1081:10)
39 silly fetchPackageMetaData     at emitOne (events.js:96:13)
39 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
39 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1001:12) statusCode: 404, code: 'E404' }
40 silly rollbackFailedOptional Starting
41 silly rollbackFailedOptional Finishing
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: 404 Not Found
44 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:304:12)
44 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:255:9)
44 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
44 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:186:22)
44 verbose stack     at emitTwo (events.js:106:13)
44 verbose stack     at Request.emit (events.js:194:7)
44 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1081:10)
44 verbose stack     at emitOne (events.js:96:13)
44 verbose stack     at Request.emit (events.js:191:7)
44 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1001:12)
45 verbose statusCode 404
46 verbose cwd C:\DEV\github\moozzyk\signalr\TestServer
47 error Windows_NT 10.0.15063
48 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--registry" "https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/" "test-server-dev@1.0.0" "C:\\DEV\\github\\moozzyk\\signalr\\TestServer" "--" "signalr-client@0.1.0-preview2-25179"
49 error node v7.10.0
50 error npm  v4.2.0
51 error code E404
52 error 404 Not Found
53 verbose exit [ 1, true ]

**Comment by moozzyk** [comment]
You got 404 (http 404 https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/test-server-dev) because you are trying to install this package:  test-server-dev@1.0.0 C:\DEV\github\moozzyk\signalr. Why do you do this? test-server-dev is the name of the current project created just to bring the client. The command you need is just `npm install --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/` (given that you updated the version of signalr-client in the `package.json`)

**Comment by grahamehorner** [comment]
@moozzyk I copied the PS commandline you used above verbatim ? 

I've also tried npm install --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/ as discussed above?  and a lot more including creating an .npmrc without success the project simply never get
anything therefore has no signalr-client.js etc. ?

**Comment by moozzyk** [comment]
Did you check here: `.\node_modules\signalr-client\dist\browser\signalr-client.js`? The file won't be added to your project automatically. You need to copy it to your project.

**Comment by grahamehorner** [comment]
@moozzyk yes, I've check that folder the .\node_modules\ ... exists but no signalr-client folder? even the TestServer project seems to have the same issue for me :'( guess as a quickfix I'll just download/extract/copy manually  until the 'BIG ROCKS' are moved ;)

**Comment by moozzyk** [comment]
npm should work. I have a few machines and it works everywhere. I am not sure why it does not work in your case. If you run build.cmd repo it will build the client (note that one of the gulp dependencies produces this warning: _npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree._ and you seem to be running node 7)

**Comment by ssougnez** [comment]
Hi,

I have a weird issue when I try to install the npm package. When I run 

`npm view signalr-client versions --registry http://dotnet.myget.org/f/aspnetcore-ci-dev/npm/`

I get

> [ '0.1.0-alpha1-26542',
>   '0.1.0-alpha1-26543',
>   '0.1.0-alpha1-26546',
>   '0.1.0-alpha1-26547',
>   '0.1.0-alpha1-26548',
>   '0.1.0-alpha1-26549',
>   '0.1.0-alpha1-26550',
>   '0.1.0-alpha1-26551',
>   '0.1.0-alpha1-26552',
>   '0.1.0-alpha1-26553' ]

But when I do:

`npm install signalr-client --registry http://dotnet.myget.org/f/aspnetcore-ci-dev/npm/`

I get

> npm ERR! code E404
> npm ERR! 404 Feed does not exist.: signalr-client@latest

Am I doing something wrong here or is it the proxy/firewall of the location where I am that could block this? It seems pretty weird to me that npm is able to see that there is a "0.1.0-alpha1-26553" version on the repository but is not able to download it. 

Is there something special to do?

**Comment by TAGC** [comment]
I was having issues with this too. Took me a while to figure it out. First I downgraded from npm 5 to 4.6.1 and then ran:

```
npm install msgpack5
npm install @aspnet/signalr-client@1.0.0-alpha1-26931 --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/
```

**Comment by TAGC** [comment]
Aha, I just spotted that in the README anyway. I was wondering how I missed it, until I realised all this time that I've been browsing a snapshot of this repo at some random commit (66876aa2f8) when the README looked like this:

![image](https://user-images.githubusercontent.com/1588951/30154362-9b83cbe6-93b1-11e7-8442-416c684a5991.png)
