### ISSUE TITLE
How to debug "Server negotiation failed." ?

### ISSUE THREAD

**Issue by xperiandri** [aspnet/SignalR#49]
How can I find why this happens?

Request starting HTTP/1.1 GET http://localhost:1965/1/Driver/negotiate?clientProtocol=1.4&connectionData=[%7B%22Name%22:%22DriverHub%22%7D]

``` C#
            app.UseSignalR(routes =>
            {
                routes.MapHub<PassengerHub>(Routes.PassengerArea1); // PassengerArea1 = "/1/Passenger";
                routes.MapHub<DriverHub>(Routes.DriverArea1); // DriverArea1 = "/1/Driver";
            });
```

`Microsoft.AspNet.SignalR.Client`
``` C#
        static void Main(string[] args)
        {
            var connection = new HubConnection("http://localhost:1965/1/Driver", false);
            var proxy = connection.CreateHubProxy("DriverHub");
            connection.Start().Wait();
        }
```

**Comment by davidfowl** [comment]
The old SignalR client is incompatible with new SignalR.

**Comment by xperiandri** [comment]
Ah, how can I connect from Android and .NET to it?

**Comment by davidfowl** [comment]
You can't at this point. The .NET client is being worked on in a branch. It should be possible to direct connect using a websocket client as well. You'd need to parse the invocation messages though

**Comment by xperiandri** [comment]
Is there exist a description of protocol?

**Comment by davidfowl** [comment]
It's too early at this point. We're still getting the basic functional working. This isn't stable enough to use for anything real as yet. The first client targets will be JavaScript and .NET

**Comment by xperiandri** [comment]
So do you suggest to use `Microsoft.AspNetCore.SignalR.Server": "0.2.0-*`?

**Comment by davidfowl** [comment]
I don't really have a recommendation for using SignalR on ASP.NET Core at the moment, this stuff just isn't ready yet. Some people have been using `Microsoft.AspNetCore.SignalR.Server` with some success though don't bother filing bugs on it because we're not fixing them. Some people have been using SignalR 2.x with Owin on ASP.NET Core on .NET Framework.
