### ISSUE TITLE
Remove IDisposable from Hub

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#493]
It's not needed.

**Comment by izverev-aexsoft** [comment]
Just for the case, we use it for offloading some work. So hub method may return result to the client immediately and complete work on disposal.

**Comment by davidfowl** [comment]
Your specific Hub can be disposable but the base class doesn't need to be.

**Comment by grahamehorner** [comment]
This is causing issues for me when I have an Observable.Interval subscription on a hub; as the base is checking the dispose and throwing exceptions when the OnNext method of the subscription is fired.  I haven't as yet been able to trace why the hub believes that it has been disposed ?

**Comment by davidfowl** [comment]
Not needed anymore
