### ISSUE TITLE
OnDisconnected behind load balancer

### ISSUE THREAD

**Issue by izverev-aexsoft** [aspnet/SignalR#494]
I run two identical SignalR servers locally (at 81 and 82 ports) and nginx as a load balancer at port 80.
I use Redis as a backplane. Messages are delivered properly between server instances.
Using long polling protocol.

So internally each request is routed to either server and it causes strange behavior. OnDisconnected server event is called each time server is changed and timeout reached and it happens very often. OnConnected is never called (except initial connection). OnReconnected also never called. Client events are also fine (and I do not get client-side "disconnected" event once OnDisconnected happen at the server).

The issue doesn't happen when one server is behind LB. It is reproduced at Amazon EC2 instance with ALB.

Is it something expected that under LB server will face lots of OnDisconnected events? If so, how should I handle it - to distinct from real connection loss?
If not, what could be an issue?
Thanks a lot!

**Comment by davidfowl** [comment]
This should be filed on http://github.com/SignalR/SignalR/, this repository is for SignalR on ASP.NET Core which is extremely different

**Comment by izverev-aexsoft** [comment]
OK, sorry! And what is the project status? Our project is on ASP.NET Core and AspNet.SignalR is one of artifacts. Should we move to this implementation?

**Comment by davidfowl** [comment]
Not sure what you mean. If you're already using SignalR on asp.net Core then you're using some old unsupported version. SignalR is still in progress. You can watch https://channel9.msdn.com/Events/Build/2017/B8078 for an update

**Comment by izverev-aexsoft** [comment]
Thanks! We use Microsoft.AspNet.SignalR.Core v2.2.2 and so have to use net461 full framework. Had no choice and will be happy to upgrade.
