### ISSUE TITLE
Unable to resolve Microsoft.AspNetCore.SignalR.Server for .NETCoreApp, Version=v1.1

### ISSUE THREAD

**Issue by Bogatinovski** [aspnet/SignalR#497]
I have been using the Microsoft.AspNetCore.SignalR.Server assembly for the last 3 months very successfully and today all of I sudden I started getting this error when I do dotnet restore. What has changed and how to fix this issue ?
I am pulling the dependency from https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json

**Comment by BrennanConroy** [comment]
`Microsoft.AspNetCore.SignalR.Server` is an old deprecated package. It was from this repo https://github.com/aspnet/SignalR-Server/blob/dev/README.md

Looks like it has been deleted from that feed or was never on that feed.
