### ISSUE TITLE
Nuget package unavailable - failed build?

### ISSUE THREAD

**Issue by JamesReate** [aspnet/SignalR#498]
Hi, at this moment the aspnet core signalr package has become unavailable. The only difference I'm noticing is that the current branch build is showing as "Failing" which I'm guessing may have something to do with this. 
Copying image directly from our Continuous build server:
![image](https://cloud.githubusercontent.com/assets/2886324/26563653/bb5c631c-449a-11e7-8655-3e63362c25dd.png)

**Comment by davidfowl** [comment]
https://github.com/aspnet/SignalR/issues/497

**Comment by JamesReate** [comment]
So, is there a new nuget package we should install for aspnetcore? Or is the current way to build and package locally?

**Comment by JamesReate** [comment]
found it:
Install-Package Microsoft.AspNetCore.SignalR -Version 1.0.0-preview1-24937 -Source https://dotnet.myget.org/F/aspnetcore-release/api/v3/index.json

**Comment by moozzyk** [comment]
To make it clear - Microsoft.AspNetCore.SignalR package is deprecated and will never ship.

**Comment by davidfowl** [comment]
You mean SignalR.Server

**Comment by moozzyk** [comment]
Yes - copy/paste error. Updated.

**Comment by nbickel** [comment]
do you know of an alternative for Microsoft.AspNetCore.SignalR.Server?

**Comment by davidfowl** [comment]
Microsoft.AspNetCore.SignalR (which requires the latest CI bits)
