### ISSUE TITLE
Groups.Exists(groupName) and Public Access to ConnectionList

### ISSUE THREAD

**Issue by harisbotic** [aspnet/SignalR#50]
I started to implement these two options in my project and I saw that currently there is no way of doing it without some hacking.

My idea was to have a property in Connection.Metadata called "LastSeen" or "UserStatus", and generally, I could access ConnectionList then I could access their Metadata and get a list of all online users.

I think Groups.Exists is also mandatory to have to see if the group exists, especially if someone wants to use Single-user groups.

Did you plan to add these features, and when approximately? :)

**Comment by davidfowl** [comment]
Accessing the connection list might be leaky from a hubs POV. If you look at the redis implementation of the HubLifetimeManager, you'll see it uses that list in a completely different way. Heck, the backing implementation might not even need a connection list. For those reasons, it can't be exposed. If you want a list of connections, you'll need to track it yourself. 

> I think Groups.Exists is also mandatory to have to see if the group exists, especially if someone wants to use Single-user groups.

I'm not sure how you'd implement that if you were running on more than a single server. We generally avoid things like this that drastically change behavior on single server vs multi server scenarios (or things that are extremely hard to implement multi server we just leave as an exercise for application developers).

> Did you plan to add these features, and when approximately? :)

The specific features you are asking for no. We *do* want to enable user presence tracking in some form but we're not that far along as yet. We're working on making the low level details work reliably at this point. 

That said, if you want to hack together something, feel free to do so. We've been taking the approach of not building any into the box but low level primitives and then writing samples to understand where the boiler plate code comes in, then if it makes sense, we'll bring it back into the framework (or an extension if it makes more sense there).

**Comment by harisbotic** [comment]
Thanks a lot man, I did plan to have multiple server, do you suggest than to have persisten storage (ex. Azure Table) where it would store userId and connectionId in one entity. In that case, we would not use SingalR groups at all, but we would do a query on Azure to get all connectionIds for particual user.

OnDisconnect event would go to azure and delete that particual connectionId.

This is the design that I have in my mind atm, but I feel that its kinda heavy. Please, if you could provide your opinion on this I would be amazing :)
