### ISSUE TITLE
Adding javascript client to bower

### ISSUE THREAD

**Issue by ciband** [aspnet/SignalR#502]
Hello, could you please make the javascript client available via bower?  Thank you.

**Comment by Ibro** [comment]
I think npm should be enough. 

Also, bower has been deprecataed - https://github.com/bower/bower/issues/2298

> ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

**Comment by grahamehorner** [comment]
while I agree NPM is a good package manager bower is simply not going away as it is used by a large number of front end developers and has a large amount of library/items in both public and private repository.  The tooling for bower already exists in VS so why not simple publish the client package in both repositories?   + current experience of npm for SignalR is poor and has issues

**Comment by Ibro** [comment]
Why bother with both npm and bower when it can be done properly with npm and enable same usage?

**Comment by grahamehorner** [comment]
@Ibro user base many frontend dev don't use npm and use bower exclusively both using and publishing to bower and tooling in vs exists

**Comment by Ibro** [comment]
Fair point, even tho switching to bower from npm shouldn't be a big deal at all. And afaik VS has support for both npm and bower, no?

**Comment by ciband** [comment]
I appreciate the information and the discussion.  As a background on my perspective, I am a C++ developer that hasn't touch web stuff since about 1999 with Frontpage...and now I'm getting back into things for a new project.  For an ASP.NET Core project, bower seemed like the "correct choice" in Visual Studio for client side package management.  It does seem easier to deal with vs. npm since I don't have to write any additional gulp/taskrunner stuff to extract the js file I actually need and put it in wwwroot.

That being said, I'm a newbie, i'm probably missing something to make my life easier, and not opposed to a strictly npm solution if that is the way forward as an industry.  Thanks again for the discussion.

**Comment by vlear** [comment]
I can't run the code, it like java

**Comment by los93sol** [comment]
I agree it would be nice to be distributed via Bower.  I had to install npm just to get the client...plus the OOTB asp.net templates are configured for nuget/bower so getting the client from npm for .net devs doesn't really make a lot of sense.

**Comment by ciband** [comment]
Just to close the loop for our usage, due to other reasons we've moved our project to use npm instead of bower so it is no longer a need for us.  Feel free to close unless there is a greater need in the community.

**Comment by moozzyk** [comment]
There are no plans to make the client available on bower at this point.
