### ISSUE TITLE
Observable Hub

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#509]
I've written a simple SignalR Heartbeat hub that sends a 'PING' message along with a GUID to all clients connected; the Hub uses the ReactiveExtensions Observable.Interval(TimeSpan.FromSeconds(90)) with a lambda expression that computes a simple text string message and sends to all clients;  the hub seems to freeze randomly without error ?

**Comment by moozzyk** [comment]
Please provide a repro - ideally as a github repo.

**Comment by grahamehorner** [comment]
using the Chat sample add the following lines below to the hub, this is now consistently failing when the observable fires the OnNext method ?


        private IDisposable _heart;

        public override async Task OnConnectedAsync()
        {        
            if (_heart == null)
                _heart = Observable.Interval(TimeSpan.FromSeconds(15))
                     .Subscribe(
                         async (i) =>
                         {
                             await Clients.All.InvokeAsync("Send", "System", $"PING: {Guid.NewGuid().ToString()}");
                         },
                         async (ex) =>
                         {
                                 await Clients.All.InvokeAsync("Send", "System", $"PONG: {Guid.NewGuid().ToString()}");
                         },
                         async () =>
                         {
                                 await Clients.All.InvokeAsync("Send", "System", $"GAME, SET, MATCH");
                         }
                     );
        }

**Comment by davidfowl** [comment]
@grahamehorner That code is broken. That's not allowed in new SignalR. The Hub is transient and terminated after invocations. If you want a background process, then you need to either keep the hub alive by calling a method with an async task or by moving that code into a background process.

**Comment by grahamehorner** [comment]
hmm, interesting so this is a breaking change; shame seems to work the fine if the Hub<TClient> : IDisposable CheckDispose doesn't throw an exception ?

**Comment by davidfowl** [comment]
> hmm, interesting so this is a breaking change; 

Yes an intentional one to stop you from leaking hubs (a very common problem caused by the coding pattern you're using). Capturing hub state in a closure is bad and causes leaks.

Why are you kicking of a per connection timer that broadcasts to all connections? How is that not a background task? You don't need any state but the `IHubContext` which can be injected into your background task. Add an `IHostedService` to the DI container and inject the `IHubContext` and do your processing in Start.

**Comment by grahamehorner** [comment]
@davidfowl ok, thanks any points or examples, or is it a have a play at present ;) BTW was initially using an  external IObservable which was DI into the hub constructir, but opted to simplify to try and getting this working.

**Comment by grahamehorner** [comment]
@davidfowl Q: should I be using DI registering a custom HubLifetimeManager<> for this use case ?

**Comment by grahamehorner** [comment]
I got this work after @davidfowl pointed me in the correct direction; thanks @davidfowl

**Comment by SuperJMN** [comment]
Could you please paste the relevant code? I want to do exactly the same!

**Comment by davidfowl** [comment]
Something like this https://github.com/davidfowl/UT3/blob/fb12e182d42d2a5a902c1979ea0e91b66fe60607/UTT/Scavenger.cs

And the wire up.
https://github.com/davidfowl/UT3/blob/fb12e182d42d2a5a902c1979ea0e91b66fe60607/UTT/Startup.cs#L46
