### ISSUE TITLE
Microsoft.AspNetCore.SignalR.Server disappear ??

### ISSUE THREAD

**Issue by one0410** [aspnet/SignalR#512]
I could find Microsoft.AspNetCore.SignalR.Server 0.2.0-* on https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json before last week.
But this week, when I wanna auto build my project on azure. It told me unable to resolve this package.
Did you remove package from https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json ???

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/issues/498
