### ISSUE TITLE
Add endpoint base classes to support JSON over websockets for ReadableChannel<T> and IObservable<T>

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#515]
The basic idea here is that in the most common use case for websockets is streaming data over the socket using JSON. The reason there's no need for dispatch in this case is because that's already handled by the route itself (urls dispatch vs message dispatch). In these simple cases, we provide all of the plumbing and connection tracking so that websockets are efficient and connection tracking is good. These 2 derived endpoints are just samples of what it could look like (the below is hacked together). Obviously we'd need serializer extensibility and we could consider supporting non JSON but here's that's the gist.

```C#
app.UseSockets(routes =>
{
    routes.MapEndPoint<Stocks>("stocks");
});
```

### IObservable implementation

```C#
public class Stocks : ObservableEndPoint<long>
{
    public override IObservable<long> Subscribe(ConnectionContext connection)
    {
        return Observable.Interval(TimeSpan.FromSeconds(1));
    }
}
```

### Channels implementation

```C#
public class Stocks : ChannelEndPoint<long>
{
    public override ReadableChannel<long> Subscribe(ConnectionContext connection)
    {
        var channel = Channel.CreateUnbounded<long>();

        async Task Produce()
        {
            long number = 0;
            while (!connection.Transport.Input.Completion.IsCompleted)
            {
                await channel.Out.WriteAsync(number++);

                await Task.Delay(1000);
            }
        }

        _ = Produce();

        return channel.In;
    }
}
```

### Implementations

```C#
public abstract class ChannelEndPoint<T> : EndPoint
{
    public abstract ReadableChannel<T> Subscribe(ConnectionContext connection);

    public override async Task OnConnectedAsync(ConnectionContext connection)
    {
        var input = Subscribe(connection);

        while (await input.WaitToReadAsync())
        {
            while (input.TryRead(out var item))
            {
                // Inefficient, don't do this in real life
                var data = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(item));

                connection.Transport.Output.TryWrite(new Message(data, MessageType.Text));
            }
        }
    }
}

public abstract class ObservableEndPoint<T> : EndPoint
{
    public abstract IObservable<T> Subscribe(ConnectionContext connection);

    public override Task OnConnectedAsync(ConnectionContext connection)
    {
        var tcs = new TaskCompletionSource<object>();
        var disposable = Subscribe(connection).Subscribe(item =>
        {
            // Inefficient, don't do this in real life
            var data = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(item));

            connection.Transport.Output.TryWrite(new Message(data, MessageType.Text));
        },
        () =>
        {
            tcs.TrySetResult(null);
        });

        connection.Transport.Input.Completion.ContinueWith((task, state) =>
        {
            ((IDisposable)state).Dispose();
        },
        disposable);

        return tcs.Task;
    }
}
```

**Comment by hubert-associates** [comment]
Thanks, an IObservable-over-the-network is something we have been looking for. The closest we have found to date was the Refit framework. We are on .NET-Core.

**Comment by PtwHub** [comment]
Any news on this cool feature? Thanks!

**Comment by anurse** [comment]
This issue is specifically discussing a lower-level use of Observables over WebSockets and we don't have an ETA for adding it (it isn't one of our high priorities for 2.1)

However, in ASP.NET Core 2.1, SignalR will provide support for producing Observables that stream over the network using it's higher-level Hubs API, see https://github.com/aspnet/SignalR-samples/tree/master/StockTickR for some examples using the currently-released Alpha versions

**Comment by davidfowl** [comment]
This won't work well without framing. We can make this work for the websocket transport to only accept messages that are not split then we can re-consider.

**Comment by davidfowl** [comment]
Moving to backlog because it isn't critical for 2.1.0 and can be built easily on top of the existing layers.

**Comment by davidfowl** [comment]
In order to make this work without a thin protocol layer, we'd need to support buffering the incoming message. This would be a flag on HttpConnectionOptions.
