### ISSUE TITLE
Remove ITransportFactory and HttpClient from IConnection.StartAsync

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#518]
Thinking forward to the future of non-http, we should decouple `IConnection` from http as well. That way Hubs can be used on top of any arbitrary `IConnection` as well.

https://github.com/aspnet/SignalR/blob/831fa7289319b890122161ad02dd17222dfbbca4/src/Microsoft.AspNetCore.Sockets.Client/IConnection.cs#L13

**Comment by davidfowl** [comment]
Notes:
- `IConnection.StartAsync` shouldn't take any arguments and should be moved to Sockets.Abstractions
- `Connection` should be renamed to `HttpConnection`
- `HttpConnection` should let you replace the `HttpMessageHandler` but possibly not the HttpClient itself. This solves a bunch of the ownership issues around disposing the `HttpClient`. We always own the `HttpClient` and you get pluggability via the message handler.

Some design issues with this:
- Should `HubConnection` be tied to Http? Do we need an `HttpHubConnection`?
- How do we pick the transport in the `HttpConnection` case? Is it a constructor argument instead of an argument to StartAsync? That would be much cleaner layering wise.

/cc @moozzyk

**Comment by moozzyk** [comment]
Done.
