### ISSUE TITLE
Determine how metadata flows from the HttpContext to ConnectionContext.Metadata

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#520]
After https://github.com/aspnet/SignalR/pull/517 there's no longer a concept of text/binary messages but SignalR needs a way to determine what protocol to use json/protobuf etc. We'd like to flow transport specific data to do this so we need a way to flow say query string information to connection metadata.

**Comment by grahamehorner** [comment]
IMHO I'd like to follow the HTTP accept: header with an optional $format parameter similar to odata

**Comment by anurse** [comment]
Yeah, `Accept` headers are the best case, but unfortunately they don't work in all cases. WebSocket clients (the browser in particular) don't generally give you the ability to specify headers on the incoming request, and SSE requires a specific `Accept` header that doesn't distinguish between our sub-protocols (JSON and ProtoBuf).

**Comment by davidfowl** [comment]
We'll likely use the query string.

**Comment by davidfowl** [comment]
Proposal:

For http based transports, metadata can be passed through http requests via headers or query string:

- **Query string** - `?sockets-{key}={value}` e.g.  `?sockets-format=json&sockets-name=foo`
- **Headers** - `X-Sockets-{key}={value}` e.g. `X-Sockets-format=json`


These will manifest as keys in connection metadata with entries mapping to the key value pairs specified. There should be no conflict with reserved keys since we'll be using objects for those internally (even though we're not doing this today).

**Comment by davidfowl** [comment]
It's actually a bit more complicated than this. We need to go deeper and figure out how this maps to APIs on the client side as well.

**Comment by davidfowl** [comment]
Actually, the more I think about this, the more I think we need to negotiate based on a message rather than relying on the underlying transport. The problem is that TCP has nothing so we can't rely on this for those transport types. The `HubEndPoint` could look at the underlying transport metadata directly (e.g. like pull out the http context or specific features) in order to light up behavior based on the transport.

**Comment by anurse** [comment]
Something that's really important in this: We **cannot** allow internally-used metadata (like transport name, etc.) be overridden by this function for security reasons. For those, we should use Features anyway, in the new model.

In fact, I think "metadata" is the wrong term from this because we don't want customers putting things in here that could be overridden by client-provided parameters. Perhaps something like "Parameters"?

**Comment by davidfowl** [comment]
I think we can punt this. We added a negotiate message so there's no need to support flowing arbitrary data from the http request through the protocol. We offer access to the `HttpContext` directly so the user code can get at it.
