### ISSUE TITLE
HubLifetimeManager<THub> Helpers

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#521]
Please consider adding optional tasks for OnFirstConnectionAsync & OnLastDisconnectionAsync so that resources may be initialise/released/disposed when the first/last connection is established/disposed.

**Comment by davidfowl** [comment]
I don't think these should be helpers, it's easy enough to implement that yourself.

**Comment by grahamehorner** [comment]
Ok, as alternative could we add a property on HubLifetimeManager<THub> so implementation expose the number of connections via something like ConnectionCount instead of having to do Clients.All.Count everytime ?

**Comment by davidfowl** [comment]
Nope. That would break scale out scenarios.

**Comment by moozzyk** [comment]
You can count connections yourself if you need. As per @davidfowl response this will not work in scale out scenarios without custom code.
