### ISSUE TITLE
InvokeGroupUserAsync

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#529]
please consider adding a method to allow sending a message to a user connected to a given group; a user can have multiple connection each connection can have different groups; more then one connection can be connected to the same group.

currently you can send a message to all connection, all users in a group, a connection or a user; but if you wish to send a message to a user in a given group this is missing; IMHO this would be a common use case for chat services.

example method signature 

> public override Task InvokeGroupUserAsync(string groupName, string userId, string methodName, object[] args)

**Comment by davidfowl** [comment]
Why do you need this? Just make a group that has the users you care about and send to that group.

**Comment by grahamehorner** [comment]
if I a user can have many connection each connection can be part of many groups a user.  user case a user need to send a message to another user in a given group
chat room moderator telling user some non public/group info

We'd need to find all the connections for that user, and check if the connection has been linked to the group, then a message would be sent to the resulting connections.

The above could be a one use operation, or there maybe a need to send more messages, in which case creating a group with the and adding the connection to it would work, expect when the user established a new connection and joined the original group this wouldn't be included in the one he moderator was sending messages too

**Comment by davidfowl** [comment]
I don't see why this can't be solved with another group. I'd rather not push these "nice to have" things so deep into the stack if it can be done in other ways. LINQ expressions don't scale well past an in memory collection and designing APIs that can work against systems that aren't queryable is important.

**Comment by grahamehorner** [comment]
@davidfowl ok, I'll defer to your expertise; example of a non optimised example (quick & dirty)
otherwise I'm going to be creating groups that concatenate the groupName + userId for every user that joins a group; as well as adding groupName; seems a little wasteful ?

```
public override Task InvokeGroupUserAsync(string groupName,string userId, string methodName, object[] args)
        {
            return InvokeAllWhere(methodName, args, connection =>
            {
                if (!string.Equals(connection.User.Identity.Name, userId, StringComparison.Ordinal))
                    return false;

                var groups = connection.Metadata.Get<HashSet<string>>(HubConnectionMetadataNames.Groups);
                return groups?.Contains(groupName) == true;
            });
}
```

**Comment by davidfowl** [comment]
What does the redis implementation look like?
