### ISSUE TITLE
HttpConnectionDispatcher.ExecuteAsync failing with error 400 and no logs 

### ISSUE THREAD

**Issue by fuocor** [aspnet/SignalR#530]
I have a routing handler that maps query strings to socket endpoints that was working fine  up to 1.0.0-preview3-25476. No it is failing with no logging out put with a 400. The code I have is pretty straight forward.

```
    public class SocketRouteBuilder
    {
        private readonly HttpConnectionDispatcher _dispatcher;
        private readonly RouteBuilder _routes;

        public SocketRouteBuilder(RouteBuilder routes, HttpConnectionDispatcher dispatcher)
        {
            _routes = routes;
            _dispatcher = dispatcher;
        }

        public void MapSocket(string path, Action<ISocketBuilder> socketConfig) =>
            MapSocket(path, new HttpSocketOptions(), socketConfig);

        public void MapSocket(string path, HttpSocketOptions options, Action<ISocketBuilder> socketConfig)
        {
            var socketBuilder = new SocketBuilder(_routes.ServiceProvider);
            socketConfig(socketBuilder);
            var socket = socketBuilder.Build();
            _routes.AddPrefixRoute(path, new RouteHandler(c => _dispatcher.ExecuteAsync(c, options, socket)));
        }

        public void MapEndPoint<TResolver, TEndPoint>(string path)
            where TResolver : EndPointResolver<TEndPoint>
            where TEndPoint : EndPoint
        {
            _routes.AddPrefixRoute(path, new RouteHandler(context =>
            {
                var endpointResolver = context.RequestServices.GetService<TResolver>();
                var endpoint = endpointResolver.Resolve(path, context);
                return _dispatcher.ExecuteAsync(context, new HttpSocketOptions(), endpoint.OnConnectedAsync);
            }));
        }
    }
```

The endpoints resolve and are valid, but something is failing and I have nothing to go by except for the 400 going back to the client.

rich

**Comment by davidfowl** [comment]
Lots of code changed recently so it's likely that you're making the wrong requests from the client. It's hard to know without seeing more data.

**Comment by fuocor** [comment]
the culprit seems to be 

`   public static class HttpDispatcherAppBuilderExtensions
    {
        public static IApplicationBuilder UseSocketsEx(this IApplicationBuilder app, Action<SocketRouteBuilder> callback)
        {
            var dispatcher = app.ApplicationServices.GetRequiredService<HttpConnectionDispatcher>();

            var routes = new RouteBuilder(app);

            callback(new SocketRouteBuilder(routes, dispatcher));

            app.UseWebSocketConnections();
            app.UseRouter(routes.Build());
            return app;
        }
`
UseWebSocketConnections lingered and should be UseWebSockets

rich
