### ISSUE TITLE
ReadInvocationDescriptorAsync doesn't handle multiple requests (maybe Json only)

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#54]
If 2 or more requests come in from the same connection before reading starts then our `JsonNetInvocationAdapter` may read multiple requests and create an `InvocationDescriptor` from just the first one and throw away the other requests.

I know Json is affected by this, but other `InvocationAdapters` should be checked as well.

@davidfowl @moozzyk

**Comment by moozzyk** [comment]
Looks like the StreamReader has the default buffer of 1024 bytes (https://msdn.microsoft.com/en-us/library/yhfzs7at(v=vs.110).aspx). Since we create a new one each time we are discarding buffered characters. This can  also result in corrupt messages.

**Comment by moozzyk** [comment]
Feels like passing pipelines instead of streams to InvocationAdapters will allow fixing this since we would be able to "return" unconsumed bytes.

**Comment by davidfowl** [comment]
Yes! Let's change these APIs to take the pipeline directly.

**Comment by davidfowl** [comment]
Good catch @BrennanConroy

**Comment by anurse** [comment]
This should be fixed when we convert Hubs to use MessagingEndpoint. I'll assign this to me.

**Comment by anurse** [comment]
No longer an issue, @davidfowl switched us to use messaging so the adapter always gets a payload of exactly one message.
