### ISSUE TITLE
Switch to msgpack for binary instead of protobuf

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#543]
We're going to switch to msgpack for our binary protocol.

- [x] - Add msgpack to the spec (optionally removing protobuf)
- [x] - Investigate msgpack C# libraries

**Comment by neuecc** [comment]
This is an interesting story.
Which library are you going to use? MsgPack-Cli or MessagePack-CSharp or built your own?
https://github.com/msgpack/msgpack-cli
https://github.com/neuecc/MessagePack-CSharp/

**Comment by grahamehorner** [comment]
IMHO BSON could be a good option

**Comment by davidfowl** [comment]
@neuecc I'd like to start with your library since it seems to have lots of performance work done. We should try both though.

**Comment by neuecc** [comment]
@davidfowl Thank you. If you encounts blocking point, I can help it.

**Comment by quanterion** [comment]
@davidfowl It is very intersting to know why do you switch to msgpack! Can you explain a little bit?

**Comment by davidfowl** [comment]
@quanterion 
- It's compact
- It's a binary protocol
- It doesn't require an IDL for the types you want to serialize
- It has a library for every major language we want to support

This blurb from MessagePack-CSharp also has some convincing arguments (handling null/empty etc)
https://github.com/neuecc/MessagePack-CSharp/#compare-with-protobuf-json-zeroformatter

**Comment by davidfowl** [comment]
@moozzyk plz update

**Comment by alexvaluyskiy** [comment]
@moozzyk It is very interesting to know why MessagePack-CLI was chosen instead of MessagePack-CSharp? Did you do any perf tests?

**Comment by moozzyk** [comment]
@alexvaluyskiy: https://github.com/neuecc/MessagePack-CSharp/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20author%3Amoozzyk 
These are now resolved but at that time they were not and were blocking.
