### ISSUE TITLE
Add ConfigureAwait(false) to all of the .NET Client code

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#545]
The .NET Clients will run in Xamarin, WPF, WinForms, System.Web apps that all have a sync context. We need to get off it while doing work.

**Comment by muratg** [comment]
Moved to preview1 milestone, @mikaelm12

**Comment by davidfowl** [comment]
Is the alpha the same?

**Comment by muratg** [comment]
@mikaelm12, @davidfowl has a cleaner way to do this, so please sync up with him.

**Comment by davidfowl** [comment]
This custom awaiter https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/System/Threading/Tasks/ForceAsyncAwaiter.cs#L18. Can be used on each of our top level methods on the client side:

```C#
public async Task StartAsync() => await StartAsyncInternal().ForceAsync();

private Task StartAsyncInternal()
{
   ...
}
```

**Comment by mikaelm12** [comment]
Added in a200cd46b19d101e2c445a356af9ff4318bdf432
