### ISSUE TITLE
Consider making .NET Client .On callbacks and Receive callbacks async

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#546]
If you want to write async logic in a callback then it'll be async void and events will fire in an overlapping way. We should consider async overloads to the On methods.

**Comment by moozzyk** [comment]
This is already biting us [here](https://github.com/aspnet/SignalR/blob/59a8f5f3b58f3f3c7b33898bc3fbe8158a0ddf9b/src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs#L209).

**Comment by davidfowl** [comment]
We'd also need to make the Received callback async too.

**Comment by mikaelm12** [comment]
Addressed in: https://github.com/aspnet/SignalR/pull/578
