### ISSUE TITLE
We don't set X-Requested-With in our XHR requests

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#547]
We don't set the `X-Requested-With` in our XHR requests. As a result, the `OPTIONS` request we do for negotiate on an authenticated Endpoint tries to do a 302 redirect to the login page, which blows up hard.

We can fix this by explicitly calling `xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest")` in our `HttpClient` code in the TypeScript client

Also, the `HttpClient` currently rejects its Promises with a custom object rather than an `Error` object. We should fix that.

/cc @moozzyk

**Comment by davidfowl** [comment]
So you're basically saying we can keep `OPTIONS` 😄

**Comment by moozzyk** [comment]
Yes

**Comment by anurse** [comment]
![https://media.tenor.com/images/a3c06d4e50bf02b2ba66240dc4938703/tenor.gif](https://media.tenor.com/images/a3c06d4e50bf02b2ba66240dc4938703/tenor.gif)

**Comment by davidfowl** [comment]
Moving this to you @mikaelm12

**Comment by mikaelm12** [comment]
Done: ed6badbabeb876592f2fbe3919b5831292c7da05
