### ISSUE TITLE
message is incomplete

### ISSUE THREAD

**Issue by sweetwxh** [aspnet/SignalR#550]
The sever called the client with a complex object,and the browser's console log the data received correct. However, an error throws after the log:uncaught error:message is incomplete.

**Comment by sweetwxh** [comment]
Ive already found out the issue which is the Chinese en code triggered

**Comment by davidfowl** [comment]
@sweetwxh are you sure you're using this SignalR and not github.com/SignalR/SignalR?

**Comment by sweetwxh** [comment]
@davidfowl yes,I'm using asp.net core 2.0 preview with this signalr. The library was installed with nuget（https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json"), I'm trying encode Chinese characters for transporting now.

**Comment by moozzyk** [comment]
@sweetwxh - can you provide a repro (ideally as a github repo)?

**Comment by sweetwxh** [comment]
@moozzyk 
On the server side, just a simply call with an object that one of it's field has Chinese characters:
```
var message  = new Message{
   UserName="Fred",IsPrivate=true,Msg="测试消息"
};
await realtime.Clients.All.InvokeAsync("SendNotify",message);
```
The client throws an exception:
![error1](https://user-images.githubusercontent.com/1302701/27016799-db3159a2-4f55-11e7-95e0-a4893eaf6455.png)
![error2](https://user-images.githubusercontent.com/1302701/27016803-e1fc4314-4f55-11e7-9ac4-98c2f02e6754.jpg)

**Comment by davidfowl** [comment]
I can reproduce this. It's an encoding problem both ways. The length is being encoded in javascript incorrectly and we're assuming utf8 on the server side. On the client side it's the same problem, we send back the utf8 length of the string payload and the client expects utf16.
