### ISSUE TITLE
Reset version numbers to 0.x.x until we're ready to release

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#557]

**Comment by davidfowl** [comment]
Won't that mess literally everything up? What's the actual plan here?

**Comment by muratg** [comment]
@DamianEdwards Are we OK having the first preview release version of SignalR be 1.0.0-preview3 or 1.0.0-preview4?  

Otherwise, we'll need to downgrade the version, clean all the feeds up, and ask everyone to clean their local caches.

**Comment by muratg** [comment]
This is done.
