### ISSUE TITLE
Delegate invoking CAN be simplified with thread safety.

### ISSUE THREAD

**Issue by huww98** [aspnet/SignalR#561]
From https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs#L143 and https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs#L174 I read the comments saying `Do not "simplify" - events can be removed from a different thread`.

I think these can be simplified using new "null conditional operator" actually. From https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators, these new operators are thread-safe.

**Comment by BrennanConroy** [comment]
Thats pretty cool, did not realize those operators were thread-safe
cc @moozzyk

**Comment by moozzyk** [comment]
Me neither. Thanks @huww98!

**Comment by davidfowl** [comment]
@huww98 care to send a PR?

**Comment by huww98** [comment]
@davidfowl I have created a PR #565

**Comment by davidfowl** [comment]
Merged!
