### ISSUE TITLE
Support relative paths for JS HubConnection and Connection 

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#564]
Today we do use `document.location.host` for all of our samples https://github.com/aspnet/SignalR/blob/6576bb0ea46354823b4668d8d82a047a8efdff56/samples/SocketsSample/wwwroot/streaming.html#L44. We need to bake this into the client if the path is relative.

**Comment by moozzyk** [comment]
One of the reasons it is not baked in now is that it only works in a browser. We will probably have to throw for relative paths if `document` is not defined.

**Comment by davidfowl** [comment]
Do we need a browser friendly API?

**Comment by moozzyk** [comment]
... or make the parameter optional and throw if full url cannot be resolved because window/document is missing

**Comment by moozzyk** [comment]
This is now implemented.
