### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by boukenka** [aspnet/SignalR#570]
Hello,

I have installed VS 2017 Update 2. Then I have downloaded the project. Then I have tried to compile without success. I have tried after VS2017 Update 3 preview. Then I have downloaded the project. Then I have tried to compile without success. Then I have tried to update the project via the NUGET Manager with no success. There were always many errors during that operation.

Maybe this is obvious that I am doing something wrong or that the project is not ready.
Just could you please provide a list of clear steps how it can be tested/compiled and what are the full dates/roadmap for the SignalR project. I have some deadlines in front of me in my company and I would like to know if it will be feasible to use this new version in the delay I got.

Thanks

**Comment by davidfowl** [comment]
> I have installed VS 2017 Update 2. Then I have downloaded the project. Then I have tried to compile without success. I have tried after VS2017 Update 3 preview. Then I have downloaded the project. Then I have tried to compile without success. Then I have tried to update the project via the NUGET Manager with no success. There were always many errors during that operation.

What does download the project mean? Some more details would help.

> Maybe this is obvious that I am doing something wrong or that the project is not ready.

SignalR for ASP.NET Core ships later this year (Q4).

> Just could you please provide a list of clear steps how it can be tested/compiled and what are the full dates/roadmap for the SignalR project.

If you're trying to build the project, then clone the repository and run `build.cmd\build.sh`.

> I have some deadlines in front of me in my company and I would like to know if it will be feasible to use this new version in the delay I got.

The library is still under heavy development so I wouldn't recommend shipping anything to production with it.

**Comment by boukenka** [comment]
Thanks for the quick response and for the help. I have tried the different 'build' files without success present in the ZIP file of the repository (I have unzipped the repository on my computer). There were errors that packages could not be restored or that there were approximate matches. 

I will wait for Q4 to try again.

PS: For project, I was meaning the ZIP of the SignalR repository.

**Comment by grahamehorner** [comment]
@boukenka have you installed the .net core 2.0 preview build ? and or the asp.net core 2.0 packages?

**Comment by davidfowl** [comment]
@boukenka build.cmd should work (regardless of warnings),  to use it in VS you the .NET Core preview tooling as @grahamehorner suggests.

**Comment by boukenka** [comment]
The dotnet-dev-win-x64.2.0.0-preview1 has been installed on my computer.
Please see in the attachment the errors during the Build process.
[Logs.txt](https://github.com/aspnet/SignalR/files/1082727/Logs.txt)

**Comment by davidfowl** [comment]
```
C:\Users\marcb\Downloads\SignalR-dev\SignalR-dev\build\repo.targets(4,5): error MSB3073: The command "npm install --no-optional" exited with code 9009. [C:\Users\marcb\Downloads\SignalR-dev\SignalR-dev\.build\KoreBuild.proj]
```

Seems like you're missing `npm`. You need npm and the typescript compiler (tsc)

/cc @moozzyk We need a list of requirements to build this repo.

**Comment by boukenka** [comment]
TypeScript_SDK and node-v8.1.2-x64 have been installed. There is an error at the Build process.
[Uploading MoreLogs.txt…]()

**Comment by moozzyk** [comment]
node and npm are required. Install node from https://nodejs.org/en/download/. We are using LTS (6.x) currently but @natemcmaster tried 8.x and it worked. Also install npm. Once you do that build.cmd/build.sh will take care of other dependencies.

**Comment by boukenka** [comment]
Unfortunately it didn't work. node-v8.1.2-x64 has been uninstalled and node-v6.11.0-x64 has been installed (including NPM). There was an error during the Build process.
[LastLogs.txt]()

**Comment by davidfowl** [comment]
@boukenka the LastLogs link needs to be fixed

**Comment by boukenka** [comment]
LastLogs link has been fixed.

**Comment by davidfowl** [comment]
You need to install git:

```
e.SignalR.Client.TS.csproj(46,5): error MSB3073: The command "git checkout HEAD -- C:\Users\marcb\Downloads\SignalR-dev\SignalR-dev\client-ts\Microsoft.AspNetCore.SignalR.Client.TS\../package.json" exited with code 128.
```

**Comment by boukenka** [comment]
Git-2.13.1.2-64-bit has been installed. I think there is still the same error during Build process.
[AnotherLogs.txt](https://github.com/aspnet/SignalR/files/1083145/AnotherLogs.txt)

**Comment by davidfowl** [comment]
It's failing because you downloaded the source zip instead of cloning the git repository. Try closing it as a git repository and building it.

**Comment by boukenka** [comment]
GitHubDesktopSetup.exe has been installed. Repository has been cloned with that software. Build was Ok (please see the logs file: [BuildLogs.txt](https://github.com/aspnet/SignalR/files/1083166/BuildLogs.txt)
After I have opened the project (SignalR.sln) with VS2017 Update 3 preview and I have tried to compile/run the 'ClientSample' project. There were many errors.

**Comment by davidfowl** [comment]
Did you say the build was ok? I see errors in your build log.

**Comment by boukenka** [comment]
The first time, I just launch the command and it was looking OK. The second time, the output was re-directed to a logs file (present in the previous comment). I didn't check the content this time.

**Comment by boukenka** [comment]
I really appreciate all the help which has been provided. I guess I didn't previously detect that there were errors. For that issue, do you have any final advice/possible solution? Is it possible to have in a ZIP file a full project where there would not be the need to do any build and to have a direct compilation without error?

**Comment by davidfowl** [comment]
You can either use the nuget packages on the myget feed or build it yourself.

**Comment by grahamehorner** [comment]
@boukenka remember to update to framework & tooling from nightly builds #dogfooding
