### ISSUE TITLE
TransportType.WebSockets Causing Failure

### ISSUE THREAD

**Issue by HelloKitty** [aspnet/SignalR#573]
When trying to set up the most basic ASP Core Web API application and a .NET Core console application I encountered an issue with the default HttpConnection's TransportType. However connection can be established with ServerSentEvents.

```
HubConnection connection = new HubConnection(new HttpConnection(new Uri(@"http://localhost:5001/test"), TransportType.WebSockets));

connection.StartAsync().Wait();
```

Results in:
```
+ InnerException	{System.InvalidOperationException: No requested transports available on the server.
   at Microsoft.AspNetCore.Sockets.Client.DefaultTransportFactory.CreateTransport(TransportType availableServerTransports)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<StartAsyncInternal>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__19.MoveNext()}	System.Exception {System.InvalidOperationException}
```

Is there something that must be done to enable websockets on the ASP Core app? I don't see anything that explicitly enables or configures it in the samples.

**Comment by moozzyk** [comment]
What OS are you running and are you using IIS or HttpSysServer?

**Comment by HelloKitty** [comment]
@moozzyk using Kestrel only on Win7 testing locally at the moment.

**Comment by HelloKitty** [comment]
Also this related issue does not help resolve this. I'm probably doing something wrong but it doesn't seem obvious.

https://github.com/aspnet/KestrelHttpServer/issues/114

**Comment by moozzyk** [comment]
WebSockets are not natively supported on Windows 7 and the client explicitly [removes](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Client.Http/DefaultTransportFactory.cs#L44) webSockets from valid transports if they are not supported. Since you explicitly requested WebSockets as the only transport there is no transport to start. Try specifying Transport.All - the client should use WebSockets if they are available and ServerSentEvents if webSockets are not available. HttpConnection should default to .All but I just noticed that it does not.

**Comment by HelloKitty** [comment]
Oh I see, this sounds familiar. I think I've read that Websockets weren't supported yet on Win7 but that was a long while back. I'll use TransportType.All for now then but as for the default I guess All would be better than WebSockets then as you said.

**Comment by moozzyk** [comment]
I opened issue #574 to change the default in C# client and verify the behavior in the TS client.

**Comment by davidfowl** [comment]
We might be able to get around the Win7 thing by using the managed websocket client on windows 7. We should look into that.

**Comment by muratg** [comment]
Issue is tracked in #574. Closing this one.
