### ISSUE TITLE
.NET Core Signalr C# Client - Make overload for specifying an HttpClientHandler more convenient

### ISSUE THREAD

**Issue by pwen090** [aspnet/SignalR#588]
Hello I have a C# asp.net core (full framework) SignalR server; using SSL and requiring TLS 1.2. I have an existing C# (full framework) console application using SignalR client. This works fine without any issues. I have a new client in C# (.net core) but the same code is returning an exception when I call my hubconnection.Start() method.

`A security error occurred
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
`
The "only" difference between the code for the .NET Core and .NET Full client is in the .NET Full client we have:

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            ServicePointManager.ServerCertificateValidationCallback += (sender, certx, chain, sslPolicyErrors) => true;`

This is obviously a big difference and most likely the cause for the .NET Core client failing given our server enforces TLS 1.2 and also returns a cert that might look invalid to default cert validation methods. 

What I am unclear on is how with the .NET Core SignalR Client do we perform the same configuration like we have done in the past with ServicePointManager? thank you

**Comment by pwen090** [comment]
Using version 2.2.2 off standard nuget feed for Microsoft.AspNet.SignalR.Client. Is there a newer version I should try to give you better feedback? 

I saw those constructor options and gave it a good try but was not sure what/how it should really be setup. Do you have any more information on that so i can try to maybe get something working to share with people? Even if it is a high level note of what should be chained together. Is the top most piece the actual hubconnection.Start(httpclient or clientransport) and then what from there? thank you for any advice.

I had to do some tweaks for autorest and ssl under .net core but it was more a matter of changing my existing WebRequestHandler to be a HttpClientHandler. And since HttpClientHandler lets you specify SslProtocols and ServerCertificateCustomValidationCallback there was nothing else to do to overcome the previous usage of ServicePointManager.

**Comment by davidfowl** [comment]
Sounds like you're using the non ASP.NET Core version of SignalR. This isn't the right repository for that project. You should file this issue at github.com/SignalR/SignalR

**Comment by pwen090** [comment]
My bad... Ok now on latest visual studio 2017 preview with .NET Core 2.0 preview and using this nuget feed: https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json
with Microsoft.AspNetCore.SignalR.Client (1.0.0-preview3-25919)
and Microsoft.AspNetCore.Sockets.Client.Http (1.0.0-preview3-25919)

I look to have been able to fix the SSL issues fine now. I create my HttpConnection as such:
`var httpConnection = new HttpConnection(baseuri, TransportType.All, loggerFactory, secureHandler);`

Where secureHandler is a HttpClientHandler with the proper SSL and certificate validation settings in place. 

This connects to my server (.NET full framework signalr server) from a TCP/SSL perspective but it looks as though the new .net core client code is perform an OPTIONS call against the signalr url I gave it:
`OPTIONS https://192.168.242.1:5050/signalr`
whereas the old client code was starting off with:
`GET https://192.168.242.1:5050/signalr/negotiate?clientProtocol=1.4`

Before I try to track down if I am giving it the wrong endpoint (given no more hubproxy that seemed to sort out the url) - I just wanted to make sure in general should a client using the new .net core signalr client work with the old full .net signalr server?

**Comment by davidfowl** [comment]
Everything looks good. 

> I just wanted to make sure in general should a client using the new .net core signalr client work with the old full .net signalr server?

The 2 versions of SignalR are completely incompatible so you need to use the new client.

**Comment by davidfowl** [comment]
Updated the title.

**Comment by mikaelm12** [comment]
Addressed in: https://github.com/aspnet/SignalR/pull/609
