### ISSUE TITLE
SignalR.Http throws System.MissingMethodException

### ISSUE THREAD

**Issue by dzoech** [aspnet/SignalR#591]
I tried to setup a new project from scratch using 1.0.0-preview3-25879. 

It seems that in order to use `app.UseSignalR` I have to include the package `Microsoft.AspNetCore.SignalR.Http`. But when I add this package the following exception is thrown in `WebHost.CreateDefaultBuilder` during startup:

`System.MissingMethodException: 'Method not found: 'Microsoft.AspNetCore.Hosting.IWebHostBuilder Microsoft.AspNetCore.Hosting.IWebHostBuilder.ConfigureLogging(System.Action2<Microsoft.AspNetCore.Hosting.WebHostBuilderContext,!!0>)'.'`

**Comment by davidfowl** [comment]
You're probably mixing preview1 and preview3 bits, you can't. Update everything else.

**Comment by dzoech** [comment]
Thank you, this was the issue. I upgraded `Microsoft.AspNetCore.All` to `2.0.0-preview3-25879` and now it works. I was just a little irritated, because in your MSBuild talk you mixed preview1 and preview2...

While I try to get your demo from the MSBuild running, I'd like to ask a follow-up question:
On the client side i do the following:
`    <script src="signalr-client.js"></script>

    <script>
        var conn = new signalR.HubConnection('http://localhost:31100/livetable'); // separate service

        conn.on('Send', data => {
            // process...
        });

        conn.start()
            .then(() => {
                console.log('Started');
            })
            .catch(error => {
                console.log('Error');
            });`

But I get the error 
`Uncaught TypeError: Cannot create property 'onDataReceived' on string 'http://localhost:31100/livetable'
    at new HubConnection (signalr-client.js:282)
    at index.html:17`

Has the way of creating clients changed or am I missing something? 
Thank you in advance.

**Comment by dzoech** [comment]
I'm sorry, after asking the question I found out, how to use it properly:

`var conn = new signalR.HubConnection(new signalR.HttpConnection('http://localhost:31100/livetable'));`

**Comment by davidfowl** [comment]
👍
