### ISSUE TITLE
Hard to find packages for preview3-25892

### ISSUE THREAD

**Issue by pellea** [aspnet/SignalR#592]
Hello,

I updated the old SignalR **preview2** packages I was using to the new **preview3**-25892 and I wasn't able to instantiate an `HttpConnection` used by the `HubConnection`.

Then I found the right package (or I think it is).

Here are all the packages I added:
```

    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="1.0.0-preview3-25892" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-preview3-25892" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="1.0.0-preview3-25892" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Http" Version="1.0.0-preview3-25892" />
    <PackageReference Include="Microsoft.AspNetCore.Sockets" Version="1.0.0-preview3-25892" />
    <PackageReference Include="Microsoft.AspNetCore.Sockets.Client.Http" Version="1.0.0-preview3-25892" />
    <PackageReference Include="Microsoft.AspNetCore.Sockets.Common.Http" Version="1.0.0-preview3-25892" />
    <PackageReference Include="Microsoft.AspNetCore.Sockets.Http" Version="1.0.0-preview3-25892" />
```

It's hard to find the required packages between the **xxx.Sockets.xxx** and **xxx.SignalR.xxx** packages. Is it not possible to pack everything with the Microsoft.AspNetCore.SignalR.Http ?

Regards,
Adrien.

**Comment by davidfowl** [comment]
For the client side right now, you need:

- Microsoft.AspNetCore.SignalR.Client (**HubConnection**)
- Microsoft.AspNetCore.Sockets.Client.Http (**HttpConnection**)

**Comment by pellea** [comment]
I cleaned up a little bit my references. With only those two the client works.

On the server I have a new exception
![image](https://user-images.githubusercontent.com/395982/27547468-69e0e9ec-5a96-11e7-9f96-19e423b15e62.png)

Is there somewhere an updated sample that link the nuget packages and not the project directly?

**Comment by davidfowl** [comment]
@pellea No. The sample project in here should be good enough. Did you call AddSignalR?

**Comment by pellea** [comment]
Yes I did.

**Comment by davidfowl** [comment]
Can you show your startup class

**Comment by pellea** [comment]
Here is my startup.cs class:

```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;

namespace iNUI.FlyFolder.SignalR
{
    public class Startup
    {
        public IConfiguration Configuration { get; }

        public Startup(IConfiguration config)
        {
            this.Configuration = config;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<SiteServerDbContext>(options => options.UseSqlServer(this.Configuration.GetConnectionString("AzureSqlDatabaseConnectionString")));
            
            services.AddSingleton<IConfiguration>(this.Configuration);

            services.AddSignalRCore();
            services.AddMvcCore();

            services.AddSingleton<MessageProcessor>();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IApplicationLifetime appLifetime)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            
            app.UseFileServer();

            app.UseSignalR(routes =>
            {
                routes.MapHub<SystemManagerHub>("/mgmt");
            });

            app.UseMvc();

            appLifetime.ApplicationStarted.Register(() =>
            {
                var messageProcessor = app.ApplicationServices.GetService<MessageProcessor>();
                messageProcessor.Start();
            });

            appLifetime.ApplicationStopping.Register(() =>
            {
                var messageProcessor = app.ApplicationServices.GetService<MessageProcessor>();
                messageProcessor.Stop();
            });
        }
    }
}

```

**Comment by davidfowl** [comment]
You need to change `AddSignalRCore` to `AddSignalR` in `ConfigureServices`

**Comment by davidfowl** [comment]
Also some unrelated improvements you can make to your code in general:
- You don't need to add the `IConfiguration` to the DI container, it's already been added. It's new in 2.0.
- You can use the new primitive `IHostedService` to start your message processor instead of wiring it up in Configure. Here's an example https://github.com/aspnet/SignalR/blob/47ac4e5bf964c6275a3acbbfec31e33e1ff323e7/src/Microsoft.AspNetCore.Sockets/SocketsApplicationLifetimeService.cs#L10. You can call `services.AddSingleton<IHostedService, YourHostedService>()` in `ConfigureServices`

**Comment by pellea** [comment]
It's working now.

When upgrading to new packages, `AddSignalR` was not available while `AddSignalRCore `was. That confused me. 

Thanks for the tips about the `IHostedService`. My code is a lot cleaner now.
