### ISSUE TITLE
Review usages of Try* methods in protocol parsers

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#602]
Some of these [methods](https://github.com/aspnet/SignalR/blob/13ef35fa79f3e52453868ef7421e46d58b5c5242/src/Microsoft.AspNetCore.SignalR.Common/Internal/Formatters/TextMessageFormatter.cs#L43) never return false. 
Also, review what we are doing if the methods that can return false actually return false and if this is correct.

**Comment by davidfowl** [comment]
I'll take this one.
