### ISSUE TITLE
Add support for IUserIdProvider

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#604]
This allows users to plug in how 
 to convert from the incoming connection to the user id that SignalR uses for Clients.User(userId)

https://github.com/SignalR/SignalR/blob/b73cbabe69bc48c4cb8d768148e157712a264ce9/src/Microsoft.AspNet.SignalR.Core/IUserIdProvider.cs

**Comment by BrennanConroy** [comment]
Milestone?

**Comment by BrennanConroy** [comment]
Done via https://github.com/aspnet/SignalR/commit/665f166d67bedb6df53499ab59b618e8a72cf2c0
