### ISSUE TITLE
Uncaught TypeError: Cannot create property onDataReceived on string

### ISSUE THREAD

**Issue by romanov** [aspnet/SignalR#612]
Decided to play with a core version and got this:

I took client js from 
`npm install signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/`

![error](https://user-images.githubusercontent.com/644179/27669540-e1cfc50e-5c8f-11e7-9cce-0e5aac7ed76e.png)

![error2](https://user-images.githubusercontent.com/644179/27669567-126b2dc0-5c90-11e7-8cd2-d90db5681b52.png)

ok, looks like api has changed,
got a solution from here
`https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/Views/Home/Index.cshtml`

closed

**Comment by moozzyk** [comment]
Yeah, you no longer pass url to hubConnection but you need to create an HttpConnection and pass it when creating HttpConnection.
