### ISSUE TITLE
Change HubProtocol specification to use variable size int for length prefix

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#613]
Today we waste 8 bytes of space for the length prefix. We should use a more compact integer encoding (like what protobuf or msgpack uses)

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR/blob/6332e98d03daae8aeb42d826ca346ff5f2b5bd3d/src/Microsoft.AspNetCore.SignalR.Common/Internal/Formatters/BinaryMessageFormatter.cs#L15

**Comment by davidfowl** [comment]
Yep, this bug is just a follow up.

**Comment by moozzyk** [comment]
Also maybe we should not support messages bigger that int.MaxValue. It will make life easier since Javascript bitwise operators only support 32-bit integers and it does not feel that sending messages over 2GB is a real scenario.

**Comment by davidfowl** [comment]
It would be fine starting with that. I don't know that we want to block > 2GB though.

**Comment by moozzyk** [comment]
It's done now.
