### ISSUE TITLE
Q: SignalR ServiceFabric

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#621]
I'm wondering if SignalR could be hosted from inside a Stateless Service ?
and if so how could/is this done ?

**Comment by davidfowl** [comment]
Like any other regular ASP.NET Core service that runs in service fabric.

**Comment by grahamehorner** [comment]
but what about StatelessService can SignalR be used outside of ASP.NET Core service ? or has it a dependency of kestrel etc. in ASP.NET Core.  sorry I'm not fully up todate with channels/pipline etc. and this may be a numpty question ;) loz

**Comment by davidfowl** [comment]
> but what about StatelessService can SignalR be used outside of ASP.NET Core service

That's not a thing. SignalR runs on ASP.NET Core.

**Comment by grahamehorner** [comment]
Ok, that's interesting

I'm trying to use ASP.NET Core 2.0 Preview-3 within ServiceFabric;  I'm getting the following error installing nugget packages ? do I need to target a different framework, other than 4.6.1 which the ServiceFabric templates use as default ?

**Comment by grahamehorner** [comment]
I'm using VS2017 v15.3.0 Preview 3.0 to create a ServiceFabric project using Stateless ASP.NET Core - Web Application targeting ASP.NET 2.0; this template produces a project which targets the .NET Framework 4.6.1 which is .NET Standard 2.0 compliant? however when attempting to reference ASP.NET Core nuget components marked as .NETStandard 2.0 these fail and rollback ?

any ideas ?

**Comment by grahamehorner** [comment]
in fact this is happening for any ASP.NET Core 2.0 - (.NET Framework) application ?

**Comment by grahamehorner** [comment]
@davidfowl ok got more info the nuget package of SignalR 1..0.0-preview3-25967 seams to work ok, but the 1.0.0-preview3-25972 and above are giving me issues? and rolls back? 

Restoring packages for ...\Web2\Web2.csproj...
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/index.json 475ms
  GET https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-dev/nuget/v3/flatcontainer/system.runtime.compilerservices.unsafe/index.json
  OK https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-dev/nuget/v3/flatcontainer/system.runtime.compilerservices.unsafe/index.json 688ms
Package restore failed. Rolling back package changes for 'Web2'.
Time Elapsed: 00:00:02.0552791
========== Finished ==========

BTW I'm using the https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json nuget feed ?

**Comment by davidfowl** [comment]
Closing as this was resolved

**Comment by grahamehorner** [comment]
@davidfowl thanks to all the team, great work, beers on me 😁
