### ISSUE TITLE
REST endpoint Vs SignalR

### ISSUE THREAD

**Issue by varghesep** [aspnet/SignalR#626]
I have an **Angular Mobile App** that uses a **.NET Core REST endpoint** which is hosted in Azure. This app is a mobile application for a user group. I will have a real-time functionality in the future where one of the person in the group modifies the data in the **MS SQL** database, the other people in the group should be notified and then update their mobile apps. But how often the data is changed is very minimum, so **push** feature to the mobile app is a luxury feature.

Is SignalR appropriate for this app by considering:

1. The push feature is used rarely.
2. Keep the resource usage of the Azure less compared to the REST endpoint.
3. Get hundreds of images from Azure Blob storage on request from the Angular client.
4. Get data for hundreds of people when the app starts.
5. Retrieve user data from the MS SQL on request.
 
 Is SignalR useful compared to [Angular HTTP](https://angular.io/guide/http) or [XMLHttpRequest ](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest)or [Fetch ](https://angular.io/guide/http)or [JSONP](https://en.wikipedia.org/wiki/JSONP)?

**Comment by moozzyk** [comment]
Can you afford keeping the connection open on the client all the time?

**Comment by varghesep** [comment]
@moozzyk I don't know whether that is expensive or in other words resource intensive. I want to keep the cloud resource usage to minimum.

**Comment by moozzyk** [comment]
I am saying that with XmlHttpRequest etc. you control when you start a new request while SignalR will try to keep the connection always open creating requests if necessary even though there is no data to send/receive (e.g. with long polling transport there will be a new request every two minutes if the server has no data to send).
