### ISSUE TITLE
No serialization

### ISSUE THREAD

**Issue by romanov** [aspnet/SignalR#630]
I'm sending some message with javascript like:

` connection.send("Hello", 1, 25, 254);`

if my hub method is 

`public async Task Hello(string id, string num1, string num2)`

everything is okay, but if i'm changing it to:

`public async Task Hello(int id, int num1, int num2)`

my javascript client throws some websocket errors and disconnects

Am i doing something wrong?

**Comment by moozzyk** [comment]
What errors are you getting on the server side? The reason why the client disconnects is the server closing the connection due to an error.

**Comment by davidfowl** [comment]
@romanov Can you paste all of the code instead of those small snippets? Paste the entire hub class and the entire client side code wire up.

**Comment by romanov** [comment]
> The reason why the client disconnects is the server closing the connection due to an error.
Looks like. I've checked again my hub methods with try/catch.
