### ISSUE TITLE
How to create a .net standard client?

### ISSUE THREAD

**Issue by malichishti** [aspnet/SignalR#633]
Hi,

I have a **.net standard class library** which needs to connect to **ASP Core Signal r Hub**. Is this achievable? If yes how?

Is there a nuget package i can use?

Regards,
Ali

**Comment by moozzyk** [comment]
What version of SignalR are you using?

**Comment by malichishti** [comment]
I do not have a server yet, I need to create both server and client while the Server will be ASP.NET Core and client will be .Net Standard

I can use any version which will allow me to do this. Hoping for a nuget package or something similar to achieve this.

**Comment by moozzyk** [comment]
The packages for SignalR ASP.NET Core are available on the https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json feed. Your server will need to use Asp.NET Core 2.0

**Comment by malichishti** [comment]
@moozzyk I get following error the moment i add **Microsoft.AspNetCore.SignalR.Http** package to my server.
![image](https://user-images.githubusercontent.com/17155996/28552093-ae470ca6-712f-11e7-8825-4e117f028b96.png)

**Comment by moozzyk** [comment]
Most likely you are mixing versions.

**Comment by malichishti** [comment]
Following is all that i have installed in an empty ASP.NET Core Web application, the moment it is installed i get above error.
![image](https://user-images.githubusercontent.com/17155996/28559468-07ed5fa6-715a-11e7-8a23-858ade61a620.png)

**Comment by moozzyk** [comment]
@malichishti - you also need 2.0 runtime and matching libraries.

**Comment by malichishti** [comment]
@moozzyk - Its already added:
![image](https://user-images.githubusercontent.com/17155996/28598457-07fe137c-71e7-11e7-945d-c5731e5cd290.png)
the project works fine if i uninstall **Microsoft.AspNetCore.SignalR.Http**

**Comment by BrennanConroy** [comment]
You need newer bits than 2.0.0 to use **AspNetCore.SignalR**, i.e. use **2.1.0-preview1-26462** of **Microsoft.AspNetCore.All**

**Comment by malichishti** [comment]
Thank you that solved it.
