### ISSUE TITLE
Microsoft.AspNet.SignalR.Core references & Newtonsoft 6.0 

### ISSUE THREAD

**Issue by advapiIT** [aspnet/SignalR#635]
I've got a strange behavior.
I'm referencing Microsoft.AspNet.SignalR.Core in a web app application and also referencing Newtonsoft.Json 10.0.0 in a web application. Sometime when I build a reference to Newtonsoft 6.0 is copied to the output folder... the only reference I've found is 

![image](https://user-images.githubusercontent.com/4690086/27865842-6fbb06c2-6194-11e7-8bca-1dfd1649c5c4.png)

What can be the reason of such a behavior?

**Comment by davidfowl** [comment]
@advapiIT This is the wrong repository for this issue, it should be filed on github.com/SignalR/SignalR.
