### ISSUE TITLE
can i add the package to my project using NuGet ?

### ISSUE THREAD

**Issue by ScriptiZer** [aspnet/SignalR#640]
can i add the package to my project using NuGet ?

**Comment by mikaelm12** [comment]
SignalR Core is currently available through our MyGet feed:  https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json

**Comment by romanov** [comment]
When you are using VS 2017.3 with a blank ASP.NET CORE (v2) templates: it says `method not found`.
But if you are trying to fetch the latest `Microsoft.AspNetCore.All` rtm from NuGet - it fails.

**Comment by davidfowl** [comment]
> When you are using VS 2017.3 with a blank ASP.NET CORE (v2) template: it says method not found.

By design. You can't use the latest SignalR builds with preview2.

> But if you are trying to fetch the latest Microsoft.AspNetCore.All rtm from NuGet - it fails with Package restore failed

Because you didn't configure the right feeds.

**Comment by romanov** [comment]
`https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json` - this one?

**Comment by davidfowl** [comment]
Yep.

**Comment by romanov** [comment]
Can somebody confirm that it's impossible to get the latest asp.net core build from NuGet in VS 2017.3
I've tested on 2 machines. `Package restore failed`

**Comment by beatsm** [comment]
See #646


________________________________

**Comment by harisbotic** [comment]
For those who might still look at this issue, I believe the feed has been changed to this one:
https://dotnet.myget.org/F/aspnetcore-ci-release/api/v3/index.json

in this commit d830fc1

**Comment by moozzyk** [comment]
@harisbotic - this is not correct - dev branch should be ([and is](https://github.com/aspnet/SignalR/blob/90a6d8fdf709f13538c810ffb553e4c14a7cd720/NuGet.config#L5)) on the aspnetcore-ci-dev feed.

**Comment by jbarber2016** [comment]
What if my .net is 4.5.2?  If I add these packages it's not compatible.

**Comment by moozzyk** [comment]
@jbarber2016 - It still should work as soon as you are using ASP.Net Core 2.0

**Comment by ssougnez** [comment]
Hi,

I read all comments but the solution is not really clear to me. I created this SO question : https://stackoverflow.com/questions/45495548/what-is-the-correct-package-to-use-for-signalr-with-asp-net-core as I can't install SignalR whatever I do... what's the correct way to install the package ?

Thanks
