### ISSUE TITLE
Old SDK version installed when running Build

### ISSUE THREAD

**Issue by beatsm** [aspnet/SignalR#646]
When I run build.cmd an old sdk version is installed 

![image](https://user-images.githubusercontent.com/3408087/27956344-5392ef5e-6311-11e7-8d99-5dce3159be06.png)

This results in this error

![image](https://user-images.githubusercontent.com/3408087/27956450-cefc0e46-6311-11e7-96ba-0bd353b1f717.png)

I had to install the latest from here before it would work

https://github.com/dotnet/cli

Which was a little confusing as I would not necessarily think that a CLI also included the SDK. 

Suggest either fixing the build scripts or mentioning this in the installation notes.

Thanks

**Comment by davidfowl** [comment]
This is something we need to do AspNetCore wide.

**Comment by moozzyk** [comment]
@beatsm - if you do `git clean -xdf` you will get the right version. VS errors are probably a result of a SDK/runitme mismatch - build.cmd is using runtime/sdk from ~\.dotnet\x64 while VS is using the one from `C:\Program Files\dotnet` this is why after you installed the latest from https://github.com/dotnet/cli things started to work.

**Comment by moozzyk** [comment]
Seems resolved.
