### ISSUE TITLE
Signing Powershell scripts

### ISSUE THREAD

**Issue by beatsm** [aspnet/SignalR#647]
Working in a paranoid corporate environment we are no longer able to run unsigned powershell scripts. I have been advised by my Sys Admins that this is an effective attack vector and is also now best practice.

This means that I am no longer able to build this repo in work (Or install many features of VS 2017 but that's not this repos problem). 

Would you consider signing your powershell scripts?

Thanks

**Comment by davidfowl** [comment]
I'm like 96% sure that we aren't going to sign our build scripts. I can't think of any open source project that does. 

This isn't a SignalR specific issue though, all of our repositories build the same under the asp.net org. File an issue under aspnet/Home but I'm pretty sure it's s non starter.

**Comment by moozzyk** [comment]
@beatsm - do you need to build the repo at all? Why not just use NuGet packages?

**Comment by beatsm** [comment]
I was just trying to figure out why I couldn't install the nuget packages and didn't know the cli included the sdk.

Thanks
________________________________
