### ISSUE TITLE
Don't allow WebSocketsTransport to be half-closed

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#65]
(via @anurse in person)

The WebSockets transport currently allows a half-close situation, where one party has closed but the other can still send. That's technically valid per the spec, but I don't think it's a valuable scenario and it causes confusion.

**Comment by anurse** [comment]
I actually think, now, that we should keep this behavior in place for the low-level EndPoints API. Definitely don't want it for the Hubs API though.

**Comment by anurse** [comment]
Closing, since as mentioned we do want to allow this at the low level API.
