### ISSUE TITLE
SignalR Groups

### ISSUE THREAD

**Issue by Sourabh721992** [aspnet/SignalR#653]
Is there some limitation on the maximum number of groups created in signalr at a particular time?

**Comment by davidfowl** [comment]
No, there's no limit

**Comment by Sourabh721992** [comment]
Thanks. Please clarify the below points:
1. Can we know how many groups got created  in signalr 
2. If there are no active users in the group. Will the group remains in signalr or not.

**Comment by grahamehorner** [comment]
It's worth noting that be be no limit, but memory & performance may be a limiting factor; @davidfowl I appreciate no optimisation has been performed yet and this would possibly correct what I've seen when having a large number of users 2,000 sending to a group scans the metadata of the connection to see of that is in a group, even if no user is in the group your sending too

**Comment by Sourabh721992** [comment]
Can we remove the group if there is no user in the group?

**Comment by davidfowl** [comment]
@grahamehorner Yep, we're aware of the current performance issues with groups. But no performance work has been done at all and there's tons of low hanging fruit. We're still working through all of the big rocks so it's not the most important thing at the moment. 

> Can we know how many groups got created in signalr

No, there's currently no way to query the group. We're still designing this, so depending on where we land we might let you query the groups but you can't at the moment.
