### ISSUE TITLE
Connect Self Hosted SignalR

### ISSUE THREAD

**Issue by Sourabh721992** [aspnet/SignalR#654]
Hi, 

I have self hosted signalr at my localhost. 
Now, I want my colleague to connect to the signalr server from his machine. I have tried numerous method but was not able to connect from different machine in the LAN network.

I request you to guide me.

**Comment by Sourabh721992** [comment]
I am getting the below error: 

Cannot be connected to the URL

**Comment by davidfowl** [comment]
1. Is this SignalR on ASP.NET Core, or is it SignalR 2.x? If it's the latter then you're on the wrong repository.
2. Can you provide a sample on github that shows the issue?

**Comment by moozzyk** [comment]
Looks like a dupe of https://github.com/SignalR/SignalR/issues/3965
