### ISSUE TITLE
Questions: UWP client options?

### ISSUE THREAD

**Issue by drchilds** [aspnet/SignalR#673]
So now that the client is netstandard 2.0 based, are there any options for testing with a UWP based client?  The current Windows Insider SDK doesn't appear to support netstandard 2.0 UWP apps yet.  Is there another build available that does?  The 2.2.2 client doesn't support connecting to core SignalR hubs, correct?

Sorry for the barrage of questions.  Inquiring minds want to know.  :)

**Comment by moozzyk** [comment]
Not at the moment. See: https://github.com/aspnet/SignalR/issues/423#issuecomment-309109706

**Comment by davidfowl** [comment]
The client will support netstandard 2.0 which will work with the latest UWP

**Comment by mikaelm12** [comment]
Make sure you make your minimum version Win 10 Fall Creators Update. Details in the blog post below

https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/
