### ISSUE TITLE
Adding Query String/Headers in Javascript Client

### ISSUE THREAD

**Issue by ggiebel** [aspnet/SignalR#680]
I want to use a token for authentication when clients connect to a hub.  I had been doing this with the old ASP.NET signalR and the jquery signalr client by adding a query string in the client and a server middleware that parsed the query string into a header. However, I cannot figure out how to set a query string or headers with the new signalr-client.js for .NET Core 2.0. Is this doable or has support been removed?

**Comment by moozzyk** [comment]
It has not been plumbed yet. The HttpClient [supports](https://github.com/aspnet/SignalR/blob/dev/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpClient.ts#L4-L6) headers but none of the transports are passing or taking headers. Also, LongPolling does not use the HttpClient. Note that the headers cannot be set when using websockets from javascript.

**Comment by Havret** [comment]
Any estimate when this will be implemented?

**Comment by moozzyk** [comment]
This issue is about JavaScript client and you point to the documentation on C# client. Which are you asking about?

**Comment by Havret** [comment]
Sorry. I just wanted to make my point. :) I am asking about JS client, to be precise I would like to know how can I set my bearer token before establishing connection using HubConnection.

**Comment by moozzyk** [comment]
If you are using JavaScript you need to pass tokens using query string and this is already possible. Some of the underlying APIs SignalR is using (most notably WebSockets and EventSource) don't allow setting headers and there is not much SignalR can do about that. See also: https://github.com/aspnet/SignalR/issues/875#issuecomment-333390304, #888, #686

**Comment by Havret** [comment]
Ok, everything is perfectly clear. Cheers!

**Comment by Eric-Larson** [comment]
After attaching a query string on the client, I can't seem to find where I can retrieve the value on the server. I see ConnectionId within 'hub context', but no additional query strings.

**Comment by moozzyk** [comment]
You need to use https://github.com/aspnet/SignalR/blob/595f783857598c56056305d627b969b856367454/src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionContextExtensions.cs#L14

**Comment by Eric-Larson** [comment]
Thanks @moozzyk! You posted the function signature from the socket namespace, here's the one for SignalR.

https://github.com/aspnet/SignalR/blob/64b3cf5339abf59e6dc327d450cc24fd5c21bf68/src/Microsoft.AspNetCore.SignalR/HttpConnectionContextExtensions.cs#L11

Here's what I used to retrieve the query string:

        private string getQueryString(HubCallerContext context)
        {
            HttpContext httpContext = HttpConnectionContextExtensions.GetHttpContext(context.Connection);
            return httpContext.Request.Query["token"];;
        }

**Comment by moozzyk** [comment]
this is an extension method so you can call it just like this:

`var httpContext = context.Connection.GetHttpContext()`

**Comment by bigswede74** [comment]
Is there a way to send data from the client in the query string like in previous versions?

$.connection.hub.qs = { 'MyKey' : 'MyValue' };

**Comment by moozzyk** [comment]
yes - just use the full url with querystring when creating the connection (e.g. `new signalR.HubConnection("/chat?mykey=myvalue"`);

**Comment by bigswede74** [comment]
@moozzyk thanks that works great.

**Comment by craigdmckenna** [comment]
@moozzyk, would you consider of the following API implementation for this issue?:
```
const conn = new signalR.HubConnection('/signalr', {
    headers: {
        'Accept-Language': 'en-US'
    }
});
```

If so, I'd be willing to work on a PR.

**Comment by moozzyk** [comment]
@craigdmckenna - I had something similar (except I used `Map<string, string>` for headers) "working" on Friday and removed for now. The reason is that this is misleading - as explained above the browser does not allow setting headers for webSockets and eventSource, so users will be setting headers and expecting to see the values on the server side but in many cases they won't.

**Comment by craigdmckenna** [comment]
How about adding a constructor to `HttpClient` to be able to initialize it with the `headers` option which could then be passed to `HttpConnection`? `HttpConnection` has an existing `httpClient` option. This would be round-about but would isolate the `headers` option.

**Comment by moozzyk** [comment]
You can do it already (you can [pass](https://github.com/aspnet/SignalR/blob/dev/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IHttpConnectionOptions.ts#L9) your own implementation of IHttpClient where you can set headers) but it does not solve the problem. The problem is:
- webSockets is a different API that does not allow setting the headers
- eventSource is a different API that does not allow setting the headers
- long polling is not using this client because it has more specific requirements (it was noted here: https://github.com/aspnet/SignalR/issues/3 but was done)

**Comment by craigdmckenna** [comment]
My bad, I didn't look closely enough to see that webSockets and eventSource use HttpClient and just assumed otherwise. Thanks moozzyk.

**Comment by LGinC** [comment]
How to add auth query string?  
I use this  "?Abp.TenantId=2&Authorization=Bearer " + myAccessToken".

but AbpSession.GetUserId() not work

**Comment by anurse** [comment]
You shouldn't need to put it in the query string manually at all. Just specify an `accessTokenFactory` in the options object for `.withUrl`. Note, you'll need to manually configure JWT bearer auth to read from the query string. See the sample for more information: https://github.com/aspnet/SignalR/tree/dev/samples/JwtSample
