### ISSUE TITLE
Replace ConnectionManager.MakeNewConnectionId() with a pluggable id generator (and a discussion about SignalR Cluster)

### ISSUE THREAD

**Issue by KPixel** [aspnet/SignalR#684]
The general idea is to make the ConnectionId into a vessel of useful information (think: JWT).

This suggestion goes with #683 to improve the following scenario (and many others):

Currently, a SignalR cluster using RedisHubLifetimeManager looks like this:

![signalr-redis](https://user-images.githubusercontent.com/26368333/28791165-ce24dad4-762b-11e7-87b9-7273fc39b197.png)

When S1 (server 1) wants to send a message to C2 (client 2), it sends the message to Redis, which broadcasts it to all servers, and S4 is the only one to use that message and send it to C2.

If we can include a server id inside the ConnectionId, then S1 can know (without a lookup to a central database) which server to route the message to. We get something like this:

![signalr-cluster](https://user-images.githubusercontent.com/26368333/28791435-be44d26c-762c-11e7-90d6-ece0579466e7.png)

By the way, Redis itself has a similar mesh topology in Cluster mode. So, the message actually goes through more hops in that case. You can read more about the [Redis Cluster Bus](https://redis.io/topics/cluster-spec#the-cluster-bus).
Edit: A [Microsoft Orleans cluster](https://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Cluster-Management.html) is also similar to this design.

With this feature, we can implement #683 by grouping the connectionIds by server, and forwarding a single message to each server for its connections.

Practically, this new HubLifetimeManager could be built on top of something like Azure Service Fabric or containers. And I even thought about using SignalR for the communication intra-server...

But the whole point of this issue is to enable this scenario, not to actually build it.

**Comment by davidfowl** [comment]
Sounds like a fine addition. Connection ids can't be reused but making it pluggable seems completely reasonable.

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/aspnet/SignalR/issues/604

**Comment by KPixel** [comment]
For anyone who is interested in the cluster scenario, please read #961 (just a starting point solving the need for a custom ConnectionId).
