### ISSUE TITLE
Will the TS client work with a standard .NET application?

### ISSUE THREAD

**Issue by AnimaMundi** [aspnet/SignalR#685]
I was literally just about to start investigating how to go about implementing a TypeScript SignalR client for standard .NET applications (I really don't want to use JQuery) when I came across this. Is there any chance of the .NET Core client working with standard .NET applications?

**Comment by davidfowl** [comment]
This version of SignalR is incompatible with 2.x if that's what you're asking.

**Comment by AnimaMundi** [comment]
Okay, thank you!
