### ISSUE TITLE
Deserialize int into Int32 instead of Int64

### ISSUE THREAD

**Issue by ssougnez** [aspnet/SignalR#693]
Hi,

when using the method `invoke` of the client library to send data to my Hub, numbers are deserialized in "Int64". Shouldn't they be deserialized in "Int32" instead (as with ASP.NET Core Web API for example) ? It seems pretty weird to me to have "Int64" parameter for all my methods.

**Comment by moozzyk** [comment]
I am not sure I understand this. Where do you see Int64? Can you elaborate?

**Comment by ssougnez** [comment]
After some investigation, I'm starting to wonder if SignalR is really the culprit. I have this method in my Hub:

```
public Task Command(Command command)
{

}
```

The `Command` class is the following:

```
 public class Command
{
    [JsonProperty(PropertyName = "name")]
    public string Name { get; set; }

    [JsonProperty(PropertyName = "arguments")]
    public List<object> Arguments { get; set; } = new List<object>();

    [JsonProperty(PropertyName = "scope")]
    public string Scope { get; set; }
}
```

From my code JavaScript, I do the following:

`this.hub.invoke("Command", <ICommand>{ name: command, scope: "global", arguments: [ 1 ]});`

When I put a break point in the `Command` method and do `command.Arguments[0].GetType`, I get `Int64` and not `Int32`.

**Comment by moozzyk** [comment]
There is only one type for numbers in JSON which is Number. Because Arguments is List<object> JSON.Net does not know your target type and probably plays it safe and use Int64. No one can now whether your number is supposed to be Int32 or Int64 if you deserialize it from a string to object. The information is just not there.

**Comment by ssougnez** [comment]
Yeah, I was kind of thinking that but you confirmed it. Thanks and sorry for the useless post ;-)

**Comment by moozzyk** [comment]
No worries!
