### ISSUE TITLE
Deploy in Azure failed

### ISSUE THREAD

**Issue by pellea** [aspnet/SignalR#698]
Hello,

I updated the packages version of SignalR from 1.0.0-preview3-25939 to one available now (1.0.0-alpha1-26583 or 1.0.0-alpha1-26423 or 1.0.0-alpha1-26381). But I can't deploy it again on Azure.

The packages 1.0.0-preview3-25939 are not available anymore.

What can I do?

Thanks,
Adrien.

**Comment by davidfowl** [comment]
Update your package to ones that exist. Or mirror packages that you depend on. SignalR isn't finished yet so there's no stable version at the moment

**Comment by pellea** [comment]
I think the problem is that SignalR is way too much ahead of the Azure aspnetcore runtime. If I run the SignalR project on my local machine with the latest prerelease of the runtime, it works just fine. But if I deploy it on Azure it's not working.

I can understand SignalR is not finished yet but it would be great if the prerelease could be usable/deployable too or we wouldn't be able to test/provide feedbacks :)

I don't mind "mirroring" the packages but where can I find the specific version of a package. The 1.0.0-preview3-25939 package doesn't exists in [myget.org](https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR).

**Comment by davidfowl** [comment]
> I think the problem is that SignalR is way too much ahead of the Azure aspnetcore runtime. If I run the SignalR project on my local machine with the latest prerelease of the runtime, it works just fine. But if I deploy it on Azure it's not working.

That's because it's slated for 2.1 not 2.0.

> I can understand SignalR is not finished yet but it would be great if the prerelease could be usable/deployable too or we wouldn't be able to test/provide feedbacks :)

There will be one, it's just not the builds you are using right now. 

> I don't mind "mirroring" the packages but where can I find the specific version of a package. The 1.0.0-preview3-25939 package doesn't exists in myget.org.

It probably got deleted.

**Comment by pellea** [comment]
None of the version on myget.org work on Azure.

I "my" usable version got deleted what can I do?

**Comment by moozzyk** [comment]
Try publishing your application as a standalone app. It will be bigger because it will carry the runtime but it will be self-contained.

**Comment by davidfowl** [comment]
@pellea are you using a local nuget.config? Is it working locally because you have it on disk?

**Comment by pellea** [comment]
@moozzyk I successfully deployed the app as a standalone app. Thanks.

@davidfowl Yes I use a local nuget.config. It's working locally because I updated the SignalR packages and I have the latest .net core preview SDK installed. If I use the same runtime than in Azure Web app (via global.json) it's not working either.

**Comment by moozzyk** [comment]
Basically preview runtimes are never installed on Azure so if you want to use bits that run on preview runtimes you need to publish standalone (so that the runtime is included) or dotnet won't be able to find the runtime application requires and the application won't start.
