### ISSUE TITLE
.NET Client - Correct way to Start SignalR in a .NET Winforms app.

### ISSUE THREAD

**Issue by simonpbond** [aspnet/SignalR#707]
I'm wanting to know the correct way to start the SignalR .NET client on a winforms app.
I noticed the following in your "client sample" (which is console based)

You call:

`await connection.StartAsync(); `

you use a loop:

`while (!cts.Token.IsCancellationRequested)`

When i tried removing the while loop, I noticed the client connects and then immediately disconnects.
I guess I was expecting .StartAsync(); to keep the SignalR client running indefinitely in the background.

It seems to work if I keep the above while loop running (after having removed the sample console code from within the loop).  However, I feel I'm of-course not doing this the correct way.

I'm starting the client from the Program.cs of my application, with the idea of having the SignalR client always running, even as forms are being opened and closed, is this the correct approach? Seems to work.

`Task.Run(() => WarehouseManagement.Client.Networking.ClientSignalRManager.ExecuteAsync(SignalRServerURL));`

Lastly, how can I check if the client is connected or disconnected? (on the client side)?

Apologies for my ignorance, any advice as to whether I'm on the right path would be appreciated. 

Thanks.

**Comment by davidfowl** [comment]
> When i tried removing the while loop, I noticed the client connects and then immediately disconnects.

It shouldn't disconnect unless your windows form application quits or there was a failure on connection.

> I guess I was expecting .StartAsync(); to keep the SignalR client running indefinitely in the background.

It does. The only reason the application does a loop is to stop console app from ending prematurely. 

> I'm starting the client from the Program.cs of my application, with the idea of having the SignalR client always running, even as forms are being opened and closed, is this the correct approach? Seems to work.

Yep.

> Lastly, how can I check if the client is connected or disconnected? (on the client side)?

There's no bool right now. See https://github.com/aspnet/SignalR/issues/212. You can register for the Disconnected event on the client side to know if you're connected or not.

**Comment by simonpbond** [comment]
Hi David,

Do you see anything wrong here? Strangely the only way to keep it running is to retain the cancellationtoken / while loop code. As mentioned above, it's being started in Program.CS of a winforms app using Task.Run (as shown above).

With the while condition it works great, without it..  it does not. The application is not exiting, and I assume program.cs remains running for the lifetime of the winforms app? I'm using build 26462, could that be the issue?

```
    public class ClientSignalRManager
    {

        public static HttpConnection httpConnection;
        public static HubConnection connection;
        public static CancellationTokenSource cts;

        public static void Disconnect()
        {
            Log.Logger.Information(DateTime.Now.ToString("ss:mm:hh - dd/MM/yyyy") + " : " + "Disconnected from Server (At the Server's Request)");
            cts.Cancel();
            connection.DisposeAsync();
        }


        public static async void sendMessage(string message)
        {

            Log.Logger.Information("Client Sending Message: " + message);
            try
            {
                await connection.InvokeAsync<object>("Send", cts.Token, message);
            }
            catch (System.InvalidOperationException)
            {
                if (connection != null) { Log.Logger.Information("(Debugging) Connection object seems to still exist, message not sent."); }
            }
        }



        public static void displayMessage(string message)
        {
            Log.Logger.Information("Client Received a Message: " + message);
        }

        private static string _baseUrl;

        public static async Task<int> ExecuteAsync(string baseUrl)
        {

            baseUrl = string.IsNullOrEmpty(baseUrl) ? "http://localhost:5000/hubs" : baseUrl;
            _baseUrl = baseUrl;

            var loggerFactory = new LoggerFactory();

            Log.Logger.Information(DateTime.Now.ToString("ss:mm:hh - dd/MM/yyyy") + " : " + "Connecting to Server : {0}", baseUrl, baseUrl);
            httpConnection = new HttpConnection(new Uri(baseUrl));
            connection = new HubConnection(httpConnection, loggerFactory);
            connection.Connected += () => Task.Run(() => onConnected());
            connection.Closed += (Exception e) => Task.Run(() => onClosed());
            connection.On<string>("Send", message => { displayMessage(message); });
            connection.On<string>("Disconnect", message => { Disconnect(); });
            try
            {
                await connection.StartAsync();
                Log.Logger.Information(DateTime.Now.ToString("ss:mm:hh - dd/MM/yyyy") + " : " + "Connected to Server.", baseUrl);

                cts = new CancellationTokenSource();

                while (!cts.Token.IsCancellationRequested)
                { 
                    // Loop.... to keep SignalR running.
                }

            }
            catch (AggregateException aex) when (aex.InnerExceptions.All(e => e is OperationCanceledException))
            {
            }
            catch (OperationCanceledException)
            {
            }
            finally
            {
                await connection.DisposeAsync();
            }
            return 0;
        }


        public static async Task onClosed()
        {
            Log.Logger.Information(DateTime.Now.ToString("ss:mm:hh - dd/MM/yyyy") + " : " + "Lost Connection with Server.");
            await ExecuteAsync(_baseUrl);
        }

        public static void onConnected()
        {
            Log.Logger.Information(DateTime.Now.ToString("ss:mm:hh - dd/MM/yyyy") + " : " + "Established connection to Server.");
        }

    }

```

**Comment by davidfowl** [comment]
Remove the while loop and remove DisposeAsync from the finally (that's probably what's causing it to close).

**Comment by simonpbond** [comment]
Kicking myself ! Thank you !

Can I also ask (before I leave you alone), is the correct way to close the connection gracefully with the server:

hubConnection.DisposeAsync(); 

I can't seem to find a hubConnection.Stop(); or something similar.

as the server always logs "The remote party closed the WebSocket connection without completing the close handshake.". So I'm guessing dispose is just to clean up the hubConnection for garbage collection?

**Comment by davidfowl** [comment]
`DisposeAsync` is the way to stop the connection gracefully. If you close the application without disposing then that error message is expected.

**Comment by simonpbond** [comment]
Thanks for taking the time to help me David, really appreciated :)
