### ISSUE TITLE
hubProxy.Invoke(...) fails with System.InvalidOperationException

### ISSUE THREAD

**Issue by maltium** [aspnet/SignalR#709]
Using .NET Core 2 Preview 2, when calling hubProxy.Invoke(...), a System.InvalidOperationException is sometimes raised. The InnerException is null.

The same exact code runs fine without fail on .NET Framework 4.5

**Comment by BrennanConroy** [comment]
Looks like you are using old SignalR
See https://github.com/SignalR/SignalR/issues

**Comment by moozzyk** [comment]
@maltium - How do you run you app? Signalr 2.x client is not compatible with Asp.NET Core server and running SignalR 2.x server on Asp.NET Core is not supported.

**Comment by maltium** [comment]
@BrennanConroy  I'm using 2.2.2 stable

@moozzyk I'm running the client as a dotnet core console app. I don't own the server, but for sure it's not running dotnet core.

**Comment by moozzyk** [comment]
What is the stack trace? What is the transport? Can you post traces?

**Comment by maltium** [comment]
I'm using websockets over https. To me the stacktrace is looking useless. Here's a small snippet that reproduces the issue.

```
using Microsoft.AspNet.SignalR.Client;
using System.Threading;

namespace SignalRBug
{
    class Program
    {
        static void Main(string[] args)
        {
            StartSocket();

            new ManualResetEvent(false).WaitOne();
        }

        static async void StartSocket()
        {
            HubConnection hubConnection = new HubConnection("https://bittrex.com/signalr/hubs");
            IHubProxy coreHubProxy = hubConnection.CreateHubProxy("corehub");

            await hubConnection.Start();
            await coreHubProxy.Invoke("SubscribeToExchangeDeltas", "BTC-BCC");
        }
    }
}
```

**Comment by maltium** [comment]
For reference here's the exception details I'm getting:

`System.InvalidOperationException occurred
  HResult=0x80131509
  Message=There was an error invoking Hub method 'corehub.SubscribeToExchangeDeltas'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SignalRBug.Program.<StartSocket>d__1.MoveNext() in C:\Users\dev\Source\Repos\SignalRBug\SignalRBug\Program.cs:line 21
`

**Comment by maltium** [comment]
@BrennanConroy Seems I am using the old SignalR

**Comment by geminilyss** [comment]
@maltium I also met this problem, how did you solve it? I tried to use the new version of the signalR(Microsoft.AspNetCore.SignalR.Client), but it can't not connect to the server.

**Comment by BrennanConroy** [comment]
> Signalr 2.x client is not compatible with Asp.NET Core server and running SignalR 2.x server on Asp.NET Core is not supported.

**Comment by geminilyss** [comment]
@BrennanConroy The server is .NET Framework but I don't own the server.My client has to be .NET Core,when I use signalR with .NET Core，the problems occurs.If I use signalR with .NET Framework,it runs fine.Is there any way to make signalR compatible with .NET Core?

**Comment by anurse** [comment]
You can use the ASP.NET SignalR Client ([`Microsoft.AspNet.SignalR.Client`](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/) in a .NET Core application.

You have to use the form of the client that matches your server (so in this case, the ASP.NET SignalR client because your server application is ASP.NET) but the clients work fine in any .NET Standard environment (including .NET Core).
