### ISSUE TITLE
Longer messages get split into chunks of 1024 characters

### ISSUE THREAD

**Issue by charlieamer** [aspnet/SignalR#71]
I was trying to call a function from server to a JS client with parameter string which is around 5000 characters long. The message, however, was split into chunks of 1024 bytes and sent multiple times (that is, firstly, chunk 0-1024 is sent, then 1024-2048, etc). This resulted in a corrupt JSON, as you can imagine, library is trying to read message by message, and it gets chunks instead. This happens on WebSocket transport and ServerSideEvents transport (long polling transport works).
Is there a way to change the max length of text that I can send, or will you upgrade the client that he knows how to receive these multipart messages.

**Comment by davidfowl** [comment]
This library is still under heavy development and isn't ready for real usage yet.

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR/issues/6
