### ISSUE TITLE
/signalr return a 404 error 

### ISSUE THREAD

**Issue by ghost** [aspnet/SignalR#713]
Hi,

I try to implement SignalR Core within my Asp.Net Core 2 project, however, i cannot join my hubs with my Wpf client (2.2.2, protocol 1.4), /signar/negotiate returning a 404 error code.

Versions:
- Vs 2017 15.3.0 (Preview)
- dotnet --version => 2.0.1-servicing-006924
- Microsoft.AspNetCore.All 2.1.0-preview1-26627
- Microsoft.AspNetCore.SignalR 1.0.0-alpha1-26627
- Microsoft.AspNetCore.SignalR.Http 1.0.0-alpha1-26627

Startup.cs

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSignalR();
    ...
    services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    ...
    app.UseSignalR(routes =>
    {
        routes.MapHub<SignalRHub>("myhub");
    });

    app.UseMvc();
}
```

Strange thing, if i hit http://ip:port/myhub, i do have an answer ("Connection ID required"), but still /myhub/negotiate do not answer either.

Any clue ?

**Comment by BrennanConroy** [comment]
SignalR Core requires the new SignalR Core client, the old SignalR 2 clients wont work.

**Comment by souchprod** [comment]
Thanks for the fast answer, however it seems that i can't install SignalR Core client nuyget package in a WPF app, does it mean that it is impossible to achieve my objective ?

**Comment by moozzyk** [comment]
I think you may need to wait until .NET Framework supports NetStandard 2.0. As per this [blog post](https://blogs.msdn.microsoft.com/dotnet/2017/04/05/announcing-the-net-framework-4-7/) it is supposed to happen later this year. 
If you really need it you can try hacking it by downloading packages extracting dlls, and referencing them directly. Not an ideal solution but may unblock you until things converge.

**Comment by souchprod** [comment]
Ok, thanks a lot, i will evaluate both options.

**Comment by davidfowl** [comment]
We'll look into this. We want clients to be as compatible as possible so we'll re-evaluate before we ship.

**Comment by souchprod** [comment]
Hi, according to [this post ](https://blogs.msdn.microsoft.com/dotnet/2017/08/07/welcome-to-the-net-framework-4-7-1-early-access/) the .Net Fw 4.7.1 preview embeds the .Net standard 2.0. I will give it a try.
