### ISSUE TITLE
Dependencies missing on node

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#716]
We use a number of things in the TS client which are not available by default on nodejs and currently needs to be polyfilled:
- XmlHttpRequest
- WebSockets
- EventSource
- atob()/btoa

We need to decide what to do with these dependencies. As per https://github.com/aspnet/SignalR/pull/699#discussion_r132612557 we could:
- continue to require polyfilling on nodejs 
- implement dependency injection
- build a nodejs version with different sources
- not support some these features (mostly about atob/btoa - used for sending binary protocol over text tansports).

**Comment by ssougnez** [comment]
Hi,

I'm currently facing the issue that XMLHttpRequest is not defined under NodeJs. As I read this post, I notice that you plan on doing something to fix this, but I was wondering if you had a temporary solution that I could use to polyfill XMLHttpRequest until you fix this issue ?

Btw, I don't know if it's correct, but so far, I'm using SignalR this way:

`const SignalR = require("@aspnet/signalr-client/dist/src/index"); `

I'm using it in a Azure app function.

Thanks a lot

**Comment by davidfowl** [comment]
https://github.com/davidfowl/SignalRCoreAlphaSample/blob/ee0760d8ad0efb00d89874e9887f8fe41e6d9bc8/nodesample/app.js

https://github.com/davidfowl/SignalRCoreAlphaSample/blob/ee0760d8ad0efb00d89874e9887f8fe41e6d9bc8/nodesample/package.json#L7-L8

You need those 2 packages (you can ignore the non final version of the signalr alpha).

**Comment by ssougnez** [comment]
Hehe, works like a charm, thanks a lot ! 

I'm using signalR Core for some weeks now and I can really see all the work you're putting out in it and it's pretty awesome. Keep up the good work, it's really becoming awesome and easy to use ;-)

**Comment by anurse** [comment]
Some other issues will improve the NodeJS behavior: #1317 , #1212 . We're going to close this issue because we don't plan to implement WebSocket/EventSource polyfills for node.
