### ISSUE TITLE
UWP .netstandard2 question

### ISSUE THREAD

**Issue by bjamesdev** [aspnet/SignalR#718]
I am a user who is waiting on compatibility between SignalR & UWP compiled in .net native (release mode). As I understand from this comment [#423 (comment)](https://github.com/aspnet/SignalR/issues/423#issuecomment-309109706). SignalR is now .netstandard2 compatible,  therefore when UWP is also .netstandard2 compatible, scheduled in this coming Fall Creators Update (as I have read), they should work together. Is this correct?
Will there need to be a new nugget package for this?
Thanks

**Comment by moozzyk** [comment]
There won't be a separate NuGet package. Because SignalR client targets netstandard2.0 the package we have should work with UWP.
