### ISSUE TITLE
Handle cancellation in SSE on the client

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#719]
When the SSE transport is started and immediately stopped the OpenConnection method may throw OperationCanceledException [here](https://github.com/aspnet/SignalR/blob/4898c0d3dfe5516c7e4285f76a5dcea102d48600/src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs#L80-L82). We should catch these exceptions and ignore.

**Comment by davidfowl** [comment]
The exception would be caught by Task.WhenAll so it *should* be fine. The only problem is that we'll see an exception in the application on close
