### ISSUE TITLE
Issue when arguments response is a real array in the TS client

### ISSUE THREAD

**Issue by ssougnez** [aspnet/SignalR#721]
Hello,

Say I have this:

`return Clients.Client(Context.ConnectionId).InvokeAsync("response", returnedCommands);`

Where `returnedCommands` is an array with two object in it. When I listen for the message "response" in my TS client, I see this in the console:

`(WebSockets transport) data received: 500:{"invocationId":"4","type":1,"target":"response","nonBlocking":true,"arguments":[{"name":"discussionById","arguments":[{"id":1,"title":"BOT_MESSAGE::ENROLLMENT_TITLE","fromBot":true,"messages":[{"id":1,"from":null,"date":"2017-08-12T22:42:16.0442334","content":"BOT_MESSAGE::ENROLLMENT_CONTENT","unreadForPlayers":[]}],"players":[],"messagesUnreadFor":[]}],"scope":"939a8fa4-d61b-4627-84ac-c979d1308896"},{"name":"unreadMessageCount","arguments":[17],"scope":"939a8fa4-d61b-4627-84ac-c979d1308896"}]};`

```JSON
{
  "invocationId": "4",
  "type": 1,
  "target": "response",
  "nonBlocking": true,
  "arguments": [
    {
      "name": "discussionById",
      "arguments": [
        {
          "id": 1,
          "title": "BOT_MESSAGE::ENROLLMENT_TITLE",
          "fromBot": true,
          "messages": [
            {
              "id": 1,
              "from": null,
              "date": "2017-08-12T22:42:16.0442334",
              "content": "BOT_MESSAGE::ENROLLMENT_CONTENT",
              "unreadForPlayers": [
                
              ]
            }
          ],
          "players": [
            
          ],
          "messagesUnreadFor": [
            
          ]
        }
      ],
      "scope": "939a8fa4-d61b-4627-84ac-c979d1308896"
    },
    {
      "name": "unreadMessageCount",
      "arguments": [
        17
      ],
      "scope": "939a8fa4-d61b-4627-84ac-c979d1308896"
    }
  ]
}
```

As we can see, the "arguments" array contains the two value I returned, so no issue. However, if I do this:

`this.hub.on("response", (command: ICommand) => { console.log(command); });`

I also tried with `ICommand[]` but as you can guess, it does not change anything. The value displayed in the console is:

`{name: "discussionById", arguments: Array(1), scope: "939a8fa4-d61b-4627-84ac-c979d1308896"}`

I only get the first item of the "arguments" array.

I'm using "signalr-client-0.1.0-alpha1-26627" and "Microsoft.AspNetCore.SignalR.1.0.0-alpha1-26462"

I might be wrong but it should be possible to return an array of arguments.

**Comment by davidfowl** [comment]
If you want to return an array try doing this:

```
return Clients.Client(Context.ConnectionId).InvokeAsync("response", new object[]
 { returnedCommands });
```

This is typical problem when using params arguments in C#. The arguments you specify in the array become ordinal positions in the call. If you do this:

var args = new object[] { "data1", "data2" };

```
Clients.Client(Context.ConnectionId).Invoke("method",  args);
```

That will call a method with 2 arguments.

var data = new object[] { "data1", "data2" };

```
Clients.Client(Context.ConnectionId).Invoke("method",  new object[] { args });
```

That will call a method with a single argument where that single argument is an array. 

Hope that helps.

**Comment by ssougnez** [comment]
As I receive the array from another method, I couldn't do it like that but out of curiosity, I just tried to call `ToList()` on the array and now it works.

I understand the problem, however, it's a tricky one because it seems reasonable that someone would try such a thing :-)

**Comment by muratg** [comment]
👍

**Comment by davidfowl** [comment]
@ssougnez FWIW we recently fixed this problem.
