### ISSUE TITLE
System.Reflection.Emit and netstandard2.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/SignalR#735]
.NET Standard 2.0 does not support System.Reflection.Emit, yet Microsoft.AspNetCore.SignalR is currently using it. It looks like we've jerry-rigged System.Ref.Emit into netstandard2.0 by using the 4.3.0 package reference. This will cause SignalR to blow up with nasty runtime errors on platforms that support ns2.0 but not refemit (uwp, xamarin, and others).

https://github.com/aspnet/SignalR/blob/a359da0c447b303d0c6f7b6f50ceabfd4e3d0794/src/Microsoft.AspNetCore.SignalR/Microsoft.AspNetCore.SignalR.csproj#L22

cc @davidfowl

**Comment by davidfowl** [comment]
> This will cause SignalR to blow up with nasty runtime errors on platforms that support ns2.0 but not refemit (uwp, xamarin, and others).

That's ok for a few reasons:

- This is a server component.
- It's an optional feature.

We don't hit any real issues but we should verify that restore works. Eventually we'll want to run the server on an uwp app but it's not a mainline scenario right now.

**Comment by muratg** [comment]
@davidfowl Do you mean we should verify that restore works on UWP, Xamarin etc?

**Comment by davidfowl** [comment]
No I don't think we care about this bug until asp.net Core runs on uwp and xamarin which is questionable right now.

**Comment by moozzyk** [comment]
Also, if we remove dynamic hubs this will no longer be an issue.

**Comment by natemcmaster** [comment]
> No I don't think we care about this bug until asp.net Core runs on uwp and xamarin which is questionable right now.

Just to be clear - does the SignalR .NET **client** need System.Reflection.Emit? I get that the **server** wouldn't run from uwp/xamarin, but IMO a client on these platforms is a valuable scenario.

**Comment by moozzyk** [comment]
The client does not need System.Reflection.Emit.
