### ISSUE TITLE
The client should send requested transfer mode to the server in the negotiation request

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#742]
Currently, the server assumes it knows what transfer modes a transport supports and decides whether to base64 encode messages for binary transport. This assumption may not be correct. One example is an [XmlHttpRequest polyfill](https://www.npmjs.com/package/xmlhttprequest) which does not support XmlHttpRequest Level 2 features. Trying to use a binary transport with this polyfill fails - the client (after teaching it to use non-level-2 xhr) will base64 encode binary messages but the server assumes it is fine to send binary data over longpolling transport does not encode the message which causes failures on the client. 
One way of solving this problem would be to send transfer mode along with protocol in the negotiation message

**Comment by davidfowl** [comment]
This has been resolved.

**Comment by davidfowl** [comment]
This actually isn't resolved. I also discussed this with @anurse recently. There are other scenarios where this could be useful information to have in the handshake.
