### ISSUE TITLE
[WebSocket Client] When connection is closed during SendAsync, consider throwing a more descriptive exception

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#748]
We had a flaky test that threw OperationCancelledException occasionally, and it revealed a case where a user may be confused. The scenario was the following

1. WebSocket client sends to server, completes the send but the thread is paused BEFORE the SendAsync call in `WebSocket` returns.
2. Server, in response to the message, closes the Socket
3. The transport wakes up and aborts the WebSocket connection, triggering the cancellation token that the transport gave to `SendAsync`
4. The WebSocket client wakes up, sees the cancelled token and throws `OperationCancelledException`.

The result is that the user sees an `OperationCancelledException` but never actually requested Cancellation. In my mind, `OperationCancelledException` is specifically for cases where the user requested cancellation. We should consider catching the exception in this case and throwing another exception that is more specific, indicating that the transport was closed by the server while attempting to send a message.

/cc @BrennanConroy @moozzyk 

Definitely not a priority for alpha.

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR/pull/745
