### ISSUE TITLE
During sending data through SignalR it should be possible to somehow CamelCasePropertyNamesContractResolver

### ISSUE THREAD

**Issue by ivankarpey** [aspnet/SignalR#761]
In dotnet core there is a nice things exist by default currently -  applying `CamelCasePropertyNamesContractResolver` to json data which helps to have seamless conversion from .NET world naming guidelines to java-script basics.

Well, understanding that signalr isn't the same as plain json data sending it's still nice to have a way to configure that data send through signalr still have a possibility to adopt naming case from .NET to JavaScript principles.

**Comment by moozzyk** [comment]
978f5cebc089dc26e2ecb65fd60701e4307edfa7 ?

**Comment by ivankarpey** [comment]
Yep, that's probably it. Thanks.
