### ISSUE TITLE
Version in the user-agent header should be generated automatically

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#763]
We should use https://github.com/aspnet/SignalR/blob/7b0be52c545bc20f7402ed1b58c5ff8f99c2030f/version.xml#L6 to generate the User-Agent header. Currently the version is hardcoded - it is fragile and will very likely be missed when we move to a newer version/version suffix.

(We already use this to generate version for the npm module for the client: https://github.com/aspnet/SignalR/blob/cdbb13de66b068015d068e5fab67e4e6ab42d3da/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Microsoft.AspNetCore.SignalR.Client.TS.csproj#L42)

**Comment by anurse** [comment]
All we need to do here is make sure the AssemblyInformationalVersion ends up in the User Agent from the client.
