### ISSUE TITLE
Consider testing compatibility with event-source-polyfill

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/SignalR#766]
After seeing #760, it might be a good idea to test SSE when provided by a polyfill. I've been using https://github.com/Yaffle/EventSource (`event-source-polyfill` in npm) for some time now with SignalR 2.2 (on ASP.NET Core). It provided a working SSE connection in IE and Edge to the server without me ever noticing it as polyfill.

**Comment by moozzyk** [comment]
What such tests would test? The polyfill? People are free to use polyfills to make up for missing browser features but I think this is out of scope for SignalR. If it becomes an issue we can revisit but I think even SignalR 2.2.2  did not use polyfills when running tests on IE and it has never been a problem (granted, SignalR 2.x falls back to a different transport if connection with a given transport could not be established).
