### ISSUE TITLE
Try adding headers to the Request from a HubConnection in C# client

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#769]
We need to see how hard this is to do, and decide if we need to make it easier. 

Assigning to @BrennanConroy for investigation.

**Comment by BrennanConroy** [comment]
Did a little bit of this when doing C# Client for ShootR
```c#
var httpHandler = new WrappedHttpMessageHandler();
var connection = new HubConnectionBuilder()
.WithUrl("https://site.name.com")
.WithTransport(TransportType.ServerSentEvents)
.WithMessageHandler(httpHandler)
.Build();

private class WrappedHttpMessageHandler : HttpClientHandler
{
    private IEnumerable<string> Cookies { get; set; }
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        if (Cookies.Any())
        {
            request.Headers.Add("Set-Cookie", Cookies);
        }
        var response = await base.SendAsync(request, cancellationToken);

        if (!Cookies.Any())
        {
            response.Headers.TryGetValues("Set-Cookie", out var values);
            Cookies = values;
        }
        return response;
    }
}
```

**Comment by moozzyk** [comment]
I think we should expose an API (something similar to the CookieContainer exposed in the previous version) to make it first class and to make it work in all scenarios (e.g. I don't think the HttpHandler method will work for the WebSockets transport)

**Comment by SGStino** [comment]
Correct, the HttpHandler works only for the initial negotiate, but not for the socket itself. Ran into this yesterday (#994). I had to copy the WebSocketTransport code over, comment out all the logging (_**internal** static class SocketClientLoggerExtensions_) and add the cookie in the connect method.

**Comment by moozzyk** [comment]
This is the same as #686 - Closing as a duplicate.
