### ISSUE TITLE
Verify 1.0.0-alpha1

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#770]
## Negative scenarios
  - Call server/client methods where (@moozzyk)
    - [ ] The method doesn't exist
    - [ ] Method exists but invalid number of params are passed
    - [ ] ... invalid types of parameters are passed

## Port samples
   - Stock Ticker using Streaming
   - Move Shape
   - Chat

## Triage SignalR 2 samples and decide what to port (@davidfowl)
   - https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/tutorial-getting-started-with-signalr 

## Redis
  - Chat app deployed to Azure, with two+ server instances 
    - With groups
    - Direct messages

## Authentication
  - Chat app with (@BrennanConroy)
    - Cookie auth
    - With or without Identity 
    - JWT bearer Auth with C# client 

## Clients:
  - C# 
    - .NET Core & .NET Framework (@moozzyk)
    - Xamarin (@Moozzyk)
  - TS - browser & node (@BrennanConroy))
  - JS  - browser & node  (@moozzyk)

## Dimensions:
  - Transports
  - Protocols
  - Hub types
  - Browsers

**Comment by muratg** [comment]
cc @davidfowl (1.0.0-alpha1 tester), @moozzyk, @BrennanConroy, @mikaelm12

**Comment by moozzyk** [comment]
alpha1 has shipped.
