### ISSUE TITLE
Asp.Net Core 2.0 Compability?

### ISSUE THREAD

**Issue by lugrugzo** [aspnet/SignalR#773]
Hello

Is SignalR compatible with 2.0 version of Asp.Net Core? I run `dotnet add package Microsoft.AspNetCore.SignalR.Server` from command line and got this error:

`Unable to find a stable package Microsoft.AspNetCore.SignalR.Server with version 
error:   - Found 1 version(s) in nuget.org [ Nearest version: 0.0.1-alpha ]`

**Comment by moozzyk** [comment]
The version in dev needs Asp.NET Core 2.1. However, we want to ship alpha1 that runs on Asp.NET Core 2.0.

**Comment by BrennanConroy** [comment]
Also, Microsoft.AspNetCore.SignalR.Server<http://Microsoft.AspNetCore.SignalR.Server> is not the correct package for SignalR Core
________________________________

**Comment by lugrugzo** [comment]
@BrennanConroy What is the correct package? A few tutorial I tried follow mentions it's package is `Microsoft.AspNetCore.SignalR.Server`

Example: 
https://radu-matei.com/blog/signalr-core/

**Comment by moozzyk** [comment]
Search for 1.0.0-alpha1 SignalR packages on the myget [aspnetcore-dev](https://dotnet.myget.org/Gallery/aspnetcore-dev) feed.

**Comment by lugrugzo** [comment]
I will integrate it once it reaches to production. Thanks for your efforts.
