### ISSUE TITLE
Cors isse with signalr2x

### ISSUE THREAD

**Issue by bhasker412** [aspnet/SignalR#774]
I had a working signalR hosted in godaddy. But now am facing cors issue as mentioned below.

Tried in Firefox: 56 and Edge 40 facing the same issue.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://<mysite>/signalr/negotiate?clientProtocol=1.5&group=<mygroup>&connectionData=%5B%7B%22name%22%3A%22imageshub%22%7D%5D&_=1503813812427. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I have tried all the CORS configurations mentioned in tutorial nothing worked.

Here is my startup.cs which i am using now.

`    public class Startup
    {

        public void Configuration(IAppBuilder app)
        {
            app.UseCors(CorsOptions.AllowAll);
            app.Map("/signalr", map =>
            {
                // Setup the CORS middleware to run before SignalR.
                // By default this will allow all origins. You can 
                // configure the set of origins and/or http verbs by
                // providing a cors options with a different policy.
                
                //map.UseCors(CorsOptions.AllowAll);                

                HubConfiguration hubConfiguration = new HubConfiguration();
                //hubConfiguration.EnableDetailedErrors = true;
                //hubConfiguration.EnableJavaScriptProxies = true;
                
                map.RunSignalR(hubConfiguration);

            });

            **
           //app.Map("/cors", map =>
            //{
            //    map.UseCors(CorsOptions.AllowAll);
            //    map.MapSignalR();
            //});**

        }
    }
}`

**Comment by davidfowl** [comment]
This issue should be filed on github.com/SignalR/SignalR
