### ISSUE TITLE
Port to dotnet core 2.0 and alpha1 26799 

### ISSUE THREAD

**Issue by JanEggers** [aspnet/SignalR#775]
i tried to upgrade my playground project but i have several issues:

my inital playaround was with preview1 24401 where i had one hub and a working js client.

after updating to dotnetcore 2.0 i use alpha1 26799.

1. i cannot get the js client, when executing the command 
npm install @aspnet/signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/
like you say in your readme.md i get a 404

2. the samples are not uptodate or im missing something. in my code AddSignalr does no longer exist but AddSignalrCore and UseSignalr is gone and i didnt find alternatives. both methods are still used in the samples.

are there fixes for the issue or should i wait for a final alpha1 until i try to plaay around with signalr again.

**Comment by mikaelm12** [comment]
We're aiming to release an official Alpha of SignalR this week. I'd suggest just waiting for that 😄

**Comment by moozzyk** [comment]
@JanEggers 
1. Is it actually complaining about @aspnet/signalr-client or msgpack5? Does it work if you `npm install msgpack5` and then `npm install @aspnet/signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/`?
2. AddSignalR is here: https://github.com/aspnet/SignalR/blob/978f5cebc089dc26e2ecb65fd60701e4307edfa7/src/Microsoft.AspNetCore.SignalR.Http/SignalRDependencyInjectionExtensions.cs#L11 - maybe you are missing a reference to the `Microsoft.AspNetCore.SignalR.Http` package?

**Comment by JanEggers** [comment]
@moozzyk  thx for the info.

1. looking closer at the message it is msgpack5, i installed it then it works. as sidenote: id prefere a signalr-client without dependencies and a signalr-client-msgpack and signalr-client-whatevertransport. 

2. you may add a note somewhere when releasing official alpha1 that devs no should replace  Microsoft.AspNetCore.SignalR with Microsoft.AspNetCore.SignalR.Http

**Comment by davidfowl** [comment]
> you may add a note somewhere when releasing official alpha1 that devs no should replace Microsoft.AspNetCore.SignalR with Microsoft.AspNetCore.SignalR.Http

We're working on the packaging problem before alpha1.

**Comment by moozzyk** [comment]
@JanEggers - the issue is that msgpack is on npmjs.org while signalr-client on myget. Adding an .npmrc like this: https://github.com/moozzyk/SignalR-Client-Swift/blob/6c8d713c1bb69497ab2f6a370f103726d7499a52/TestServer/.npmrc should fix it. I think for alpha1 we will have just one npm module with all the code.
