### ISSUE TITLE
Implement Authentication redirect for cookies

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#776]
Today when we issue the challenge from SignalR a 401 is correctly returned with a `Location` response header with the redirect URI. We should issue a client side redirect to get to the login page. Here's what this looks like:

```
HTTP/1.1 401 Unauthorized
Location: http://localhost:57562/Account/Login?ReturnUrl=%2Fchat
Server: Kestrel
X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNcZGZvd2xlclxEb2N1bWVudHNcR2l0SHViXFNpZ25hbFJcc2FtcGxlc1xDaGF0U2FtcGxlXGNoYXQ=?=
X-Powered-By: ASP.NET
Date: Sun, 27 Aug 2017 21:50:30 GMT
Content-Length: 0
```

We should also consider adding a client side hook to allow the client to handle this (maybe the client wants to pop up a client side UI to login rather than redirecting).

**Comment by NtFreX** [comment]
> We should also consider adding a client side hook to allow the client to handle this (maybe the client wants to pop up a client side UI to login rather than redirecting).

I wouldn't like it if signalr would redirect me without having the chance to change that.

**Comment by BrennanConroy** [comment]
Websockets connections need to be let through when unauthorized and then immediately closed with some kind of error code (4401?)/message to let us tell the client that they need some authorization. This is because if we challenge during the websockets handshake it will error without any usable information.

**Comment by muratg** [comment]
No plans to do this per the triage decision
