### ISSUE TITLE
signalr-client javascript error on ie

### ISSUE THREAD

**Issue by leehavin** [aspnet/SignalR#777]
When I quote client js
npm install @aspnet/signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/

There is no error in chrome, but there is a syntax error in Internet explorer 

![image](https://user-images.githubusercontent.com/12468518/29772397-30b8e022-8c2b-11e7-8c02-57bdb925e1d5.png)

I hope to get your help soon

**Comment by moozzyk** [comment]
IE does not support any ES6 features. I am [working](It's in the works https://github.com/aspnet/SignalR/pull/772 ) on transpiling the client to ES5.

**Comment by moozzyk** [comment]
Fixed in ff2bf5ad7598c221b67d017d93726f01ca051143 and 2a36aa141d90bf8b4112e720986d525b9ac45c11
Samples are being updated in https://github.com/aspnet/SignalR/pull/784
