### ISSUE TITLE
npm install error 404

### ISSUE THREAD

**Issue by leehavin** [aspnet/SignalR#785]
![image](https://user-images.githubusercontent.com/12468518/29802417-957f9a24-8ca7-11e7-937b-48022c312506.png)

Part of ES5 does not support ie8, do you test it in ie8?

**Comment by davidfowl** [comment]
ie8 will very likely not be a supported browser.

**Comment by leehavin** [comment]
@davidfowl In aspnet signalr, support IE8 +, including IE8.This might not have anything to do with the service, it's the signalr-client relationship.I still want to support IE8 +

**Comment by moozzyk** [comment]
Install msgpack5 first or add .npmrc with the following line:
```
@aspnet:registry=https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/
```

**Comment by davidfowl** [comment]
@leehavin original SignalR was built ~5 years ago when IE8 support was more important. If it *just works* I think that's fine but I wouldn't state it as something we test (it's too old at this point).

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR/pull/786

**Comment by leehavin** [comment]
@davidfowl Thank you.I believe the community will be improved. In China, many enterprises still stay in older versions.But thank you very much.
