### ISSUE TITLE
SignalR Core over Https Problems

### ISSUE THREAD

**Issue by simonpbond** [aspnet/SignalR#789]
Locally on my development machine I can connect fine from the client to the server using: 

`httpConnection = new HttpConnection(new Uri("https://localhost:44324/settings"));`

However, when hosting on Windows Server 2016 using IIS and binding to port 443 with a local certificate, I can't seem to make a SignalR connection from my development machine (client) to the server unless I use only **http**.

The server is also hosting MVC (together with SignalR) and I can connect fine to both http and https for viewign the MVC site, which makes me rule out a firewall issue.

Is there anything else I need to be doing to enable https with SignalR on a remote server?

**Comment by davidfowl** [comment]
There's nothing special no. Can you make a regular https request using another client to verify it works?

**Comment by simonpbond** [comment]
Javascript worked fine. About to re-test the .NET client and will post how I go.

**Comment by muratg** [comment]
@simonpbond any luck?

**Comment by simonpbond** [comment]
@muratg Will be working on this today and post my result's tonight, have been stuck trying to resolve 2 other issues that have shown up in my project at the same time.

**Comment by simonpbond** [comment]
Placed together a small project to test again and the problem no longer exists. 
Json works http / https 
.NET works http / https

However this leaves me to my last issue , posting now 😄
