### ISSUE TITLE
Copyright and license headers for TS files?

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#797]
Do we need Copyright and license headers for the TS files? If yes, then we should do this before Alpha

**Comment by mikaelm12** [comment]
@muratg @moozzyk

**Comment by muratg** [comment]
Yes, we'll need these. Thanks for catching these!

**Comment by mikaelm12** [comment]
Cool, I'll get right on it

**Comment by mikaelm12** [comment]
Added: 7dcbf25069c09096a2c8a1b9de1eacf61c013ef7
