### ISSUE TITLE
-4077 causing server to stop accepting requests

### ISSUE THREAD

**Issue by jrote1** [aspnet/SignalR#804]
There was an issue in the older signalr where when a client disconnected whilst being written to Write would cause the server does not to respond to requests until restarted.  The code I issued as a pull request is here https://github.com/LiquidThinking/SignalR-Server/commits/4077-fix. Could I confirm if this is fixed in the new version?

Thanks

**Comment by BrennanConroy** [comment]
Considering we rewrote basically everything in this repo we can't do a 1:1 comparison of the old and new code. If you had a reliable way to cause the issue before you could try it again to see the behavior.

**Comment by moozzyk** [comment]
This code no longer exists so there is no action for us to take.
