### ISSUE TITLE
JS client only supports one subscribed event per method

### ISSUE THREAD

**Issue by billbogaiv** [aspnet/SignalR#807]
When using the JS client, the last event registered with `.on` overrides any previous registration for the same method:

```js
conn.on('method', () => { console.log('never executed') });
conn.on('method', () => { console.log('executed') });
```

Internal construct uses `Map.set`: https://github.com/aspnet/SignalR/blob/7db480b23e8d11a384b88a34704468341429c562/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts#L24 and https://github.com/aspnet/SignalR/blob/7db480b23e8d11a384b88a34704468341429c562/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts#L202

Any reason `Array` is not being used? My current workaround is to construct multiple connections.

This may also be a problem with the .NET client: https://twitter.com/davidfowl/status/903348037514272768

This should be addressed in the managed client when we do https://github.com/aspnet/SignalR/issues/900

**Comment by davidfowl** [comment]
We also need a way to remove subscriptions.

**Comment by moozzyk** [comment]
I investigated one of the issues and ended up fixing this. I propose we take it for alpha2.

**Comment by davidfowl** [comment]
Agreed
