### ISSUE TITLE
Hubs can be stateful and bad things will happen

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#81]
If a Hub is registered in the DI container as a Singleton it will be stateful. Each connection will get the same instance and we will try to set it up from multiple threads causing crashes and unexpected behavior.

**Comment by davidfowl** [comment]
We shouldn't block this. It's pretty much the same as an mvc controller

**Comment by BrennanConroy** [comment]
Let me direct you to a piece of code that would cause issues https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs#L152-L154

**Comment by moozzyk** [comment]
That's all right. I am just filing this issue for visibility. I think we should at least document it somewhere.

**Comment by davidfowl** [comment]
Closing this out, we can document it.
