### ISSUE TITLE
aspnetcore MVC Sample

### ISSUE THREAD

**Issue by willthiswork89** [aspnet/SignalR#814]
I have been trying for about 14 hours now to get MVC working with the signalR library in a core 2.0 app. I know its fairly new but i was wondering if anyone has found a sample or example of a simple chat app with core 2.0. 

Thanks!

**Comment by BrennanConroy** [comment]
You could take a look at the ChatSample in this repo https://github.com/aspnet/SignalR/tree/dev/samples/ChatSample

Although you will probably run into issues when using 2.0 because the dev branch of SignalR uses 2.1.0-*. If you want to use 2.0 you will need to use the rel/1.0.0-alpha1 branch. Unfortunately we don't have any nuget packages yet, but we will soon.

**Comment by willthiswork89** [comment]
I have managed to get a paired down version working within a .net CORE RestAPI for a basic "chat" that shows events as they are POST'ed to a controller. I believe I may be the first person to actually get this working since I could not find any documentation haha

**Comment by ByronAP** [comment]
did you post it anywhere...

**Comment by willthiswork89** [comment]
Hey Byron, i did not yet because its written with some pretty specific IP that my company owns. I plan on making a little cleaner example directly from a clean .net core 2.0 template so i can share or possibly merge into the examples here.

**Comment by jadjare** [comment]
In case anyone's interested I've created a Basic Demo App using .NET Core 2.0 and SignalR.  It can be found here..
https://github.com/jadjare/SignalR-AspNetCore2-Demo

Instructions to get started on in the ReadMe file.

**Comment by ajtowf** [comment]
So how do I get the hubcontext from a controller given I inject IServiceProvder? I noticed there is no IConnectionManager. I'd like to do something similar to:

    _connectionManager.GetHubContext<MyHub>().Clients.All.doSomethingOnClients();

where _connectionManager is something similar to IConnectionManager.

**Comment by ajtowf** [comment]
I posted a separate issue in form of a question if somebody else is interested here: https://github.com/aspnet/SignalR/issues/884

**Comment by moozzyk** [comment]
The alpha1 has been shipped on NuGet and npm. There are some samples in the https://github.com/aspnet/SignalR-Samples repo. I am closing this issue for now. Feel free to open a new issue if you encounter problems.

**Comment by ajtowf** [comment]
In this screencast I setup an mvc controller, when posted to, we broadcast to all connected clients, in our specific case, it's angular apps running on a seperate host, so it involves CORS as well.

https://www.towfeek.se/2017/09/16/consuming-signalr-for-aspnet-core-from-angular/ 

Hope it helps, cheers!
