### ISSUE TITLE
The server closes connection if number of arguments for a hub method is incorrect or the argument cannot serialized for a given type

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#815]
If a client provides an incorrect number of parameters for a hub method or the value of an argument cannot be converted to the expected type the server will close the connection. It would be better to return Error for a given invocation to the user similarly to what we do if we cannot find a hub method requested by the client.

In general any exception thrown from an IHubProtocol implementation will shutdown the connection.

**Comment by muratg** [comment]
Not valid anymore.
