### ISSUE TITLE
Ability to open a binary WebSocket connection

### ISSUE THREAD

**Issue by KPixel** [aspnet/SignalR#817]
Currently, it seems to be impossible to create an `HttpConnection` with a binary WebSocket transport. It defaults to text.

The solution in my fork is to make `SetTransferMode()` public so that I can call it before `StartAsync()`.

**Comment by moozzyk** [comment]
You need to set the transferModeFeature to `TransferMode.Binary`. See: https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs#L88-L100

**Comment by davidfowl** [comment]
@KPixel why are you changing the mode manually?

**Comment by KPixel** [comment]
I am not using SignalR, just the Sockets layer.

Regarding setting the `transferModeFeature`, that's exactly what `SetTransferMode()` does, so I don't want to duplicate it.

**Comment by davidfowl** [comment]
Ah cool!

**Comment by moozzyk** [comment]
SetTransferMode is not part of the interface. We could possibly expose it as an extension method on IConnection.

**Comment by KPixel** [comment]
That's fine with me.

And `HubConnection` can re-use it as well.
