### ISSUE TITLE
Exceptions from user HttpConnection event handlers should be caught and logged

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#818]
Currently exceptions thrown from user's code handling Connected/Received/Closed events are not handled. For the Connected and Closed events they are ignored. For the Received event they are returned as the result of the queued task in the task queue and make it impossible to enqueue another task. This results in not raising the Received event anymore for new data received by the client. 

We should catch exceptions from user's event handlers and log. They should not affect the client.

Related #816

**Comment by moozzyk** [comment]
@muratg @davidfowl - I think we should do this in alpha. Just sent a PR for this.

**Comment by muratg** [comment]
Sounds reasonable to me.

**Comment by moozzyk** [comment]
Fixed in 18f770e
