### ISSUE TITLE
Default log output of SignalR js client is too much

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#821]
Seems like we log a bunch of things by default:

![image](https://user-images.githubusercontent.com/95136/30100893-384addc0-929f-11e7-840a-7147f9cad803.png)

We shouldn't log the received messages as information that could be super noisy.

**Comment by davidfowl** [comment]
This should be fixed for the alpha.

/cc @moozzyk @muratg

**Comment by moozzyk** [comment]
I will add Trace level and will log these as Trace.
