### ISSUE TITLE
If processing a message from a (long polling) batch fails the client won't process remaining messages

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#828]
Related to:  #816 

LongPolling can batch messages. If there are multiple messages in a batch and processing a message fails the remaining messages in the batch are not processed. This can lead to hangs on the client:
1. The client is invoking a hub method which invokes a client method (note the client is the same)
2. The server batches client side invocation and hub method completion/result together
3. On the client invoking the client side method fails (e.g. parameter binding fails)
4. The hub method completion message is not processed and the client hangs awaiting for the completion which came but was not processed.

**Comment by davidfowl** [comment]
This will be fixed as part of the client refactoring.

**Comment by davidfowl** [comment]
Closed in favor of https://github.com/aspnet/SignalR/issues/1450
