### ISSUE TITLE
Cannot build SignalR-rel-2.0.0

### ISSUE THREAD

**Issue by gabor182** [aspnet/SignalR#833]
This is my first comment here, so first of all let me thank you all the hard work you put into this library!

The problem I encountered is that the version labeled with SignalR-rel-2.0.0 can not be built. I ran the build.cmd /t:Restore command, and it gave me the following output: 

[Output](https://gist.github.com/gabor182/d3279703f442cd23a5ceb2bbac46cbbf)

Where can these missing packages be found? If some additional package feeder is needed, then it would be wise to put its url into the readme file (or the build script could automatically update the package source list if a nuget.exe location is given in a command arg)
Is there any way to have a .NET Core 2.0 compatible version of SignalR?

**Comment by davidfowl** [comment]
SignalR rel/2.0.0 isn't a thing. In fact the branch should be deleted as it means nothing (since nothing shipped).

We're preparing for an alpha of SignalR Core (1.0.0-alpha1) on top of ASP.NET Core 2.0 (the only version that will run on ASP.NET Core 2.0) next week. Here's a sample on how to run it today https://github.com/davidfowl/SignalRCoreAlphaSample.

**Comment by KPixel** [comment]
@davidfowl By the way, what is your versioning strategy for SignalR?
I would hope that it would match the version of ASP.NET Core that it is running on top of.

So, v2.0.0-alpha1 would be the first release.

I understand that it is weird from an engineering point of view, but it would make a lot more sense for end-users (I remember the whole confusing with the versions for .NET Core 1.x, .NET Standard 1.x, etc).

Actually, considering that this library lives in the `Microsoft.AspNetCore` namespace, I think it also makes sense from an engineering point of view.

**Comment by OpenSpacesAndPlaces** [comment]
@davidfowl 

Will there by MSSQL support in the alpha? e.g.
https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-sql-server

In your sample app it looks like only a redis package is available at the moment.

Thanks!

**Comment by KPixel** [comment]
@OpenSpacesAndPlaces In an ASP.NET Community Standup, Damian said that it will only be Redis for now.

**Comment by davidfowl** [comment]
@KPixel as for versioning the product as 2.0.0 or 2.1.0 instead of 1.0.0, we'll discuss it after the alpha since it won't align with the ASP.NET core version right now anyways.

**Comment by gabor182** [comment]
@davidfowl Thank you for your answer. Can't wait for the release.
