### ISSUE TITLE
Issue with IConnection events returning a Task

### ISSUE THREAD

**Issue by KPixel** [aspnet/SignalR#836]
I noticed that `IConnection` has three events that return a `Task`: `Connected`, `Received` and `Closed`.

Oddly, `Connected` and `Closed` don't use that returned value.
And for `Received`, the task is added to a `TaskQueue`.

However, event delegates are multicast (many "subscribers"), so only the `Task` of the last subscriber is used.
As such, it is not typically recommended for events to have return types. But, in the case, a possible solution could be to explicitly invoke & await each subscriber, like this:

```
if (receivedHandler != null)
{
    foreach (var d in receivedHandler.GetInvocationList().OfType<Func<byte[], Task>>())
    {
        await d(buffer);
    }
}
```

Based on [this answer on StackOverflow](https://stackoverflow.com/a/41765701).

**Comment by davidfowl** [comment]
Good catch! We'll fix this post alpha.

**Comment by moozzyk** [comment]
@KPixel - Good catch!

**Comment by davidfowl** [comment]
Moved this to alpha2

**Comment by moozzyk** [comment]
@davidfowl - I think we should skip this for alpha2 - It will be superseded by https://github.com/aspnet/SignalR/issues/900

**Comment by davidfowl** [comment]
Yep closing
