### ISSUE TITLE
No easy way to get the HttpContext from a HubConnectionContext

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#837]
We added GetHttpContext on ConnectionContext but then we changed the Hub to expose HubConnectionContext instead of ConnectionContext:

https://github.com/aspnet/SignalR/blob/eec4b33cff09382285766844b8054d3e65fa1131/src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionContextExtensions.cs

This makes it harder to get at the HttpContext from inside of the hub. We should expose GetHttpContext on HubConnectionContext.

**Comment by davidfowl** [comment]
We should fix this for the alpha /cc @moozzyk @muratg

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/393ab6a4f03b68d2a55336fc7ccf8c89f7c546ae
