### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by codetian** [aspnet/SignalR#841]
where can i find RoadMap about SignalR?

**Comment by codetian** [comment]
you donot update RoadMap long time

**Comment by davidfowl** [comment]
What are you looking for? Not much as changed. ASP.NET Core SignalR ships with 2.1

**Comment by codetian** [comment]
I' d like to know when SignalR can use . I know  it now ,ASP.NET Core SignalR ships with 2.1.

**Comment by moozzyk** [comment]
There will be alpha1 soon and then we will merge with Asp.Net Core  2.1
