### ISSUE TITLE
JS/TS client HubConnection.onClosed should be a method instead of a property

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#842]
It should be possible to wire up multiple handlers to the closed event. We could even consider using on instead of having special events. That *does* mean we would need reserved names but it would be less concepts.

Today:

```TS
let http = new signalR.HttpConnection(document.location.protocol + '//' + document.location.host + '/chat');
let connection = new signalR.HubConnection(http);

connection.onClosed = e => {
        
};
```

Proposal:

```TS
let http = new signalR.HttpConnection(document.location.protocol + '//' + document.location.host + '/chat');
let connection = new signalR.HubConnection(http);

connection.on('close', e => {
        
});
```

We could also change the nomenclature and use connect/disconnect like the server side does.

/cc @moozzyk

**Comment by moozzyk** [comment]
I am not a fan of `on('close'` - it will get confused with regular hub methods.

**Comment by davidfowl** [comment]
Yea, I get it. socket.io does something similar for disconnect.

**Comment by davidfowl** [comment]
I think we should do the method change for all events in the .NET client as well. It's just a better API in general.

**Comment by moozzyk** [comment]
I don't like using the string for the name of the method for close if we can have just a strongly typed method. I also don't think we are reducing the number of concepts, rather we are conflating concepts. We could do:
```
connection.onClose(e => {
});
```
if we wanted to. One thing that is not clear from this signature is what happens if invoke this method multiple times. With the property it was clear that you are replacing the handler with the method it is not clear if you are adding or replacing.

**Comment by davidfowl** [comment]
It should match the on overload and it should be possible to subscribe multiple handlers. I think we should do the same for the .NET client as well.

**Comment by moozzyk** [comment]
I am opposed to changing `connection.onClose` to `connection.on('close'...)`. In my mind this is similar to changing `connection.start()` to `connection.invoke('start'...)` which we hopefully are not doing.

**Comment by davidfowl** [comment]
@moozzyk yea I think that's fine. Lets go with:

```JS
connection.closed(e => {
});
```
