### ISSUE TITLE
async api generator support

### ISSUE THREAD

**Issue by JanEggers** [aspnet/SignalR#847]
hi there,

i really like openapi spec aka swagger aka swashbuckle. so i wonder if there are any planns to support an api explorer thing so a generator for this (https://www.asyncapi.com) can be build

**Comment by davidfowl** [comment]
We don't plan to do any runtime generation or API explorer model. The current idea is that it'll just be a very simple reflection friendly api

**Comment by JanEggers** [comment]
oki thx
