### ISSUE TITLE
Use message formatters defined by host

### ISSUE THREAD

**Issue by xperiandri** [aspnet/SignalR#85]
I set default enum serialization as string

``` C#
            services.AddMvc()
                    .AddJsonOptions(opt =>
                    {
                        var settings = opt.SerializerSettings;
                        settings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
                    });
```
But old one SignalR did not use that.

**Comment by davidfowl** [comment]
Those are MVC options, SignalR doesn't know about MVC.

**Comment by xperiandri** [comment]
What about aligning this together?
Anyway MVC is required if you want to use SignalR with ASP.NET

**Comment by davidfowl** [comment]
Having a way to set both things would good but not via mvc. Also mvc isn't required to use SignalR with asp.net.

**Comment by moozzyk** [comment]
Kind of related: https://github.com/aspnet/SignalR/issues/73

**Comment by xperiandri** [comment]
@davidfowl, so as I understand from your presentations it is implemented, isn't it?

**Comment by davidfowl** [comment]
It's tracked here https://github.com/aspnet/SignalR/issues/261
