### ISSUE TITLE
.NET Client logs every single message as information

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#853]
Similar to https://github.com/aspnet/SignalR/issues/821 we need to change the .NET client to reduce the default amount of spam. There's also no overload that lets you specify the log level. Ideally you would do this:

```C#
var connection = new HubConnectionBuilder()
    .WithUrl("http://localhost:5000/cache")
    .WithMessagePackProtocol()
    .WithConsoleLogger(LogLevel.Debug)
    .WithTransportType(TransportType.WebSockets)
    .Build();
```

The current overload taking `ILoggerFactory` doesn't make much sense.

> info: Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport[0]
      09/12/2017 00:59:09: Connection Id ec09831d-efcb-4bc4-8b89-34800a6e0912: Starting transport. Transfer mode: Text.
info: Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport[6]
      09/12/2017 00:59:09: Connection Id ec09831d-efcb-4bc4-8b89-34800a6e0912: Starting the send loop.
info: Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport[2]
      09/12/2017 00:59:09: Connection Id ec09831d-efcb-4bc4-8b89-34800a6e0912: Starting receive loop.
Connected!
hey
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[4]
      Sending Invocation '1'.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[5]
      Sending Invocation '1' completed.
info: Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport[11]
      09/12/2017 00:59:12: Connection Id ec09831d-efcb-4bc4-8b89-34800a6e0912: Passing message to application. Payload s
ize: 44.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[4]
      Sending Invocation '2'.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[5]
      Sending Invocation '2' completed.
info: Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport[11]
      09/12/2017 00:59:12: Connection Id ec09831d-efcb-4bc4-8b89-34800a6e0912: Passing message to application. Payload s
ize: 47.
1

/cc @moozzyk @muratg

**Comment by BrennanConroy** [comment]
Close it when https://github.com/aspnet/SignalR/pull/869 goes in

**Comment by moozzyk** [comment]
2e695c935ec0fe8271f9ea618892c40c835160f9

**Comment by davidfowl** [comment]
This is fixed now
