### ISSUE TITLE
Look at supporting msgpack-RPC 

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#855]
After reading this it seems like we're pretty close to supporting msgpack-rpc for the message pack flavor of our protocol:

https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md

I haven't dug in but it might be possible to support this directly as a subset of our msg pack protocol or have it be another protocol.

/cc @moozzyk @anurse

**Comment by muratg** [comment]
JSON-RPC?

**Comment by ccic** [comment]
Look forward to see msgpack-rpc for CSharp. I found the current RPC library is gRPC in CSharp field. But msgpack's performance looks better.
