### ISSUE TITLE
Add CancellationToken representing the lifetime of the IConnection

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#858]
Today since we only have an event for Disconnect, it makes it hard to write linear code that does something until the client disconnects. It should be possible to write a reconnect loop like this:

```C#
while (true)
{
    // Create a new connection    
    var connection = new HubConnectionBuilder()
                    .WithUrl("http://localhost:5000/cache")
                    .WithMessagePackProtocol()
                    .WithConsoleLogger()
                    .WithTransportType(TransportType.WebSockets)
                    .Build();

    // Start it
    await connection.StartAsync(); 
   
    // Do things while the connection is alive and wait for it to finish

    await connection.Lifetime.AsTask();

    // Dispose when it's done
    await connection.DisposeAsync();
}
```

**Comment by moozzyk** [comment]
@davidfowl - we should move it out of alpha2 given that we are going to overhaul the API as described in #900 and this will be addressed there. Otherwise we will have both the Closed event and the token which can be a bit confusing.

**Comment by davidfowl** [comment]
Closing
