### ISSUE TITLE
Issue with disposing the HttpConnection

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#860]
```
Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CheckFixedMessage(protocol: JsonHubProtocol { Name = "json", Type = Text }, transportType: ServerSentEvents, path: "/dynamic")
Error Message:
 System.ObjectDisposedException : The CancellationTokenSource has been disposed.
Stack Trace:
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at System.Net.Http.HttpClient.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<DisposeAsyncCore>d__53.MoveNext() in 
```

**Comment by BrennanConroy** [comment]
Looks like this can happen when `HttpClient.Dispose` is called more than once at the same time. In `HttpConnection` we have two spots we dispose the `HttpClient` we should refactor it to only have 1.

**Comment by moozzyk** [comment]
Some notes before we remove one of these. The Dispose in the DisposeAsync is for the cases when the connection did not start successfully (e.g. failure during negotiation) or if the user called `DisposeAsync` between negotiation and starting the transport. In these cases we won't have the continuation on channel completion. The dispose in the channel completion continuation is for cases when the connection was closed abruptly and the user did not call DisposeAsync.

**Comment by BrennanConroy** [comment]
This was fixed when we made the HttpConnection reusable
