### ISSUE TITLE
Exceptions thrown from Protocols on the Server-Side hang

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#861]
The exception is observed when the connection closes.

https://github.com/aspnet/SignalR/blob/30f16fcf4be46d118d34645a77afc31143525250/src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs#L110
This line observes the exception. But only happens when the connection closes.

Related to https://github.com/aspnet/SignalR/issues/816

**Comment by moozzyk** [comment]
Fixed with 02676956565e85d806c85e1235cb2998fd5a5caa
