### ISSUE TITLE
A little doubt about signalr core

### ISSUE THREAD

**Issue by uopeydel** [aspnet/SignalR#866]
1. How can i set a [Context.User.Identity.Name] in https://github.com/aspnet/SignalR/tree/dev/samples/ChatSample
in this sample when i open connection properties Name alway null ,or i must to map client id and name by self in other var?
2. How can i use signalr send notification netframework to this signalr  netcore ,this imposible?

```
 public void SendNotificationToCoreX()
 {
            var CoreDomain = "http://localhost:58141/chat";
            var hubConnection = new HubConnection(CoreDomain);
            var chatHubProxy = hubConnection.CreateHubProxy("chat");
            hubConnection.Start().Wait();
            chatHubProxy.Invoke("Send", "testMess").Wait();
}
```

this code in net 4.6 doesn't work
have error [JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.]

Thank for answer to much.
Sorry to bother.

**Comment by davidfowl** [comment]
> How can i set a [Context.User.Identity.Name] in https://github.com/aspnet/SignalR/tree/dev/samples/ChatSample
in this sample when i open connection properties Name alway null ,or i must to map client id and name by self in other var?

In general, SignalR Core is built on top of ASP.NET Core, you can use a middleware to set the user.

> How can i use signalr send notification netframework to this signalr netcore ,this imposible?

Nope. The 2 frameworks are incompatible. You can use the new ASP.NET Core SignalR Core client to talk to ASP.NET Core SignalR servers.

**Comment by uopeydel** [comment]
> In general, SignalR Core is built on top of ASP.NET Core, you can use a middleware to set the user.
Have some example to set it in this git?

**Comment by davidfowl** [comment]
@uopeydel What exactly are you trying to do? The chat sample uses ASP.NET Core identity for user management.

**Comment by uopeydel** [comment]
@davidfowl Now i try chat sample in 

https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/Views/Home/Index.cshtml

user.Name is alway null ,i think if i can pass user name to store in  _connections list (PresenceHubLifetimeManager) it will have more benefit to me when i fillter user list.

**Comment by davidfowl** [comment]
I'm not sure the chat sample is a good one to follow for the most basic understanding of SignalR Core. There is a bunch of experimental code in there.
