### ISSUE TITLE
Rationale behind supporting Server-Sent Events and Long Polling

### ISSUE THREAD

**Issue by KPixel** [aspnet/SignalR#868]
Considering the amount of work that goes into supporting these transports, I am curious why that is needed.

From what I can see [online](http://caniuse.com/websockets/embed/), all major browsers/platforms support WebSockets which is a better transport in every way (correct?).

I'm probably missing something obvious :)

**Comment by davidfowl** [comment]
It's a fair question this day in age since all the newer browsers do support websockets. The original SignalR was made ~4 years ago when that wasn't the case and websocktes weren't as ubiquitous as they are now. There's also a case for supporting older browsers and older OSes, we still support Windows 7 / Window Server 200 R2 which doesn't have built in support for WebSockets with IIS or http.sys (though with raw kestrel there's no restriction). 

The other thing to consider is the fact that SignalR runs in more environments that just browsers. That might be a case to *only* support websockets but we have the flexibility to decide since we have these 3 transports implemented anyways.

One other scenario I can think of is using signalr to do polling (by setting a short poll timeout) but keeping the benefits of the programming model.

We did drop forever frame though which has been a source of security problems and bugs in the past.

All of that to say it's not *that* much more effort and it's mostly historical. We've removed automatic fallback so we'll see how much the other transports are used.

**Comment by KPixel** [comment]
I understand the historical reasons behind supporting them years ago.
On the server-side, I doubt many devs will be deploying their shinny new ASP.NET Core projects on Windows Server 2008 R2. But who knows? :)

Ultimately, I agree with relying on telemetry to confirm whether they are still needed or not.
By the way, do you have a mechanism to collect such information (client & server sides)?
It seems like it wouldn't be automated...

By the way, I still like the idea of abstracting the transports. For example, a TCP transport could make sense at the Sockets layer in some scenarios.

**Comment by davidfowl** [comment]
> Ultimately, I agree with relying on telemetry to confirm whether they are still needed or not.
By the way, do you have a mechanism to collect such information (client & server sides)?
It seems like it wouldn't be automated...

We have none today.

> I still like the idea of abstracting the transports. For example, a TCP transport could make sense at the Sockets layer in some scenarios.

I'll refer you to https://github.com/aspnet/KestrelHttpServer/issues/1980 again just in case you haven't read it. We're basically building an transport + connection abstraction so higher level frameworks like SignalR can run on TCP or WebSockets without knowing the difference. Take a look at the examples spelled out in that doc.

Over all, it doesn't hurt to have these 2 transports there (LP and SSE). We'll see how much trouble they give but ultimately the new design is so much simpler than what we had before, I don't anticipate many problems.

**Comment by KPixel** [comment]
@davidfowl I was part of the Bedrock discussion, mostly arguing about its name :)

Thanks for the quick replies.

**Comment by moozzyk** [comment]
One more datapoint - some corporate proxies block websockets.

**Comment by KPixel** [comment]
I think a related issue is that proxies can mess with websocket connections, and a common workaround is to just use https/wss.

**Comment by davidfowl** [comment]
https fixes it.

**Comment by tanichols** [comment]
There are some (unfortunate) situations where the browser and server support web sockets, but the web socket protocol has been disabled in the gateway. I'm currently in this situation, though trying to enact change.

**Comment by KPixel** [comment]
@tanichols Doesn't HTTPS resolve this issue? Or do you not have the control to make that switch?

**Comment by tanichols** [comment]
@KPixel The client makes requests over HTTPS which get converted to wss by the  `signalr-client` js library, which are blocked by the gateway.

**Comment by tanichols** [comment]
I thought so, but the js client converts the HTTPS request to a WSS request before establishing the connection.

**Comment by tanichols** [comment]
![image](https://user-images.githubusercontent.com/5770965/30711813-9100c448-9ecf-11e7-94bb-d13ed490ee87.png)

**Comment by papaytl185** [comment]
I am running my mvc aspnetcore app in a server farm with Redis and am having similar issues with a 404 error. I'm not sure where to look, we are running pfsense as the load balancer with iis servers. Its pretty consistent that every other refresh successfully connects and the other times I get the 404. If I take 1 server offline, leaving just one, it always works. And vice versa if i take the other server offline it works, so both servers work fine when running through the load balancer 1 at a time. 

Any help would be greatly appreciated.

WebSocket connection to 'wss://mywebsite.com/notification?id=d0fc384a-14f0-4436-aaaf-e5d50502399f' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by tanichols** [comment]
@papaytl185 Sounds like a sticky sessions issue. You'll need sticky sessions in order to handle the handshake, and you'll need redis to synchronize the updates to the clients. Sounds like you have redis, but are missing the sticky sessions aspect. 

https://doc.pfsense.org/index.php/Inbound_Load_Balancing#Sticky_connections

**Comment by papaytl185** [comment]
Thanks for the quick response, I was under the impression sticky sessions weren't required due to scaling out with Redis? Is there a way to apply sticky sessions just for websockets?

**Comment by tanichols** [comment]
I'm not sure about that, I don't use pfsense. You'll have to look into pfsense docs. I was also bit by this. O thought I just needed redis, but the sticky sessions are required for the initial handshake and the client to communicate with a server. Redis simply makes sure that subscribers on the other servers get the notifications when a client invokes on one server. 

1. Client 1 connects to server (maintains connection to this server for the remainder of the connection.)
2. Client 2 connects to server 2 (maintains connection)
3. Client 1 invokes an update method on server 1
4. Redis distributes this to the other servers
5. Both servers push out the update to the clients

Without sticky sessions, you can't complete the handshake. Without redis, some of your clients don't receive the updates.

**Comment by papaytl185** [comment]
I wonder why it cant complete the handshake on the other server the request is coming into. Is it due to needing to create a new connectionId or something.. It doesn't seem like a good design forcing sticky sessions on a server farm. With the old signalr i have no issues and don't need sticky sessions.

**Comment by tanichols** [comment]
I assume it's something to do with the connection IDs. I agree that it's odd to force sticky sessions. Any word from the team?

**Comment by davidfowl** [comment]
Old SignalR and new SignalR designs are completely different https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/. 

> It doesn't seem like a good design forcing sticky sessions on a server farm.

It only seems that way right now, it dramatically simplifies dealing with persistent connections in general and simplifies the programming model for developers. 

One thing we will do is *NOT* require sticky sessions if you specifically choose the websockets transport (see https://github.com/aspnet/SignalR/issues/932), but it will be required for the other 2 transports (server sent evens and long polling).

**Comment by papaytl185** [comment]
I turned on sticky sessions and am still getting the error. I really dont understand it :/
Maybe it has something to do with my groups in my hub `OnConnectedAsync.`

`        public override async Task OnConnectedAsync()
        {
            await Groups.AddAsync(Context.ConnectionId, DealerGroup(Context.User.Claims.FirstOrDefault(x => x.Type.Equals(ABClaimTypes.DealerId))?.Value));
            await Groups.AddAsync(Context.ConnectionId, UserGroup(Context.User.Claims.FirstOrDefault(x => x.Type.Equals(ABClaimTypes.UserId))?.Value));
            await Groups.AddAsync(Context.ConnectionId, UserNameGroup(Context.User.Identity.Name));
            await Groups.AddAsync(Context.ConnectionId, SessionGroup(Context.User.Claims.FirstOrDefault(x => x.Type.Equals(ABClaimTypes.SessionId))?.Value));
            
            await base.OnConnectedAsync();
        }`

**Comment by davidfowl** [comment]
The 404 means the connection id doesn't exist

**Comment by papaytl185** [comment]
That's what I figured, its weird sticky sessions still is not working for me. Is there a way to force a new connection or create a new connection id when returning a 404?

**Comment by davidfowl** [comment]
Not with the alpha no. The client always make 2 requests with websockets today.

**Comment by tanichols** [comment]
@davidfowl thanks for clarifying the rational a d sharing an enhancement! Much appreciated!

**Comment by almazik** [comment]
Just to add to the rationale of supporting server-sent events. 
We are actually looking at the option to switch _from_ WebSockets to server-sent events. The main reason is that we have a complex website with multiple loosely-coupled components with corresponding backend services, each of them expecting a flow of push notifications from the backend. SSE should allow us to independently subscribe to push notifications from each component (and evolve each protocol independently), while on a transport level it is still a single connection to the backend gateway thanks to the HTTP2 request multiplexing. 
Implementing the same logic using WebSockets would either require multiple open connections to different backend endpoints or having a central backend push notifications hub which knows about all the services and messages (our current setup). 

@davidfowl, what would you choose?

**Comment by anurse** [comment]
If you're using HTTP/2, WebSockets definitely doesn't have all the same advantages. Having said that, there is [work underway](https://tools.ietf.org/html/draft-ietf-httpbis-h2-websockets-00) to provide a way to upgrade an individual HTTP/2 stream into a WebSocket which helps here.

Your reasoning for choosing SSE over WebSockets certainly seems sound. When most of your traffic is from Server to Client, SSE is not much different from WebSockets. The main benefit WebSockets gives over SSE is around sending from Client to Server.

One thing to note is that SSE is a text-based protocol which makes it very difficult to support binary protocols without heavy encoding burdens (for example, SignalR's Message Pack protocol does not work over SSE)
