### ISSUE TITLE
Pipeline modules for cross-cutting concerns 

### ISSUE THREAD

**Issue by bromanko** [aspnet/SignalR#871]
Is a capability similar to [current SignalR's pipeline modules](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#how-to-customize-the-hubs-pipeline) planned? Right now I'm using DyanmicProxy implementations for cross-cutting concerns but that requires my invocation methods to be virtual which is bound to get forgotten.

**Comment by davidfowl** [comment]
Not sure if we want to bring these back yet. Why do you need them? What sorts of cross cutting things are you doing in your hubs?

**Comment by bromanko** [comment]
Right now this is being used to log all invocations. Another use case I'm exploring is for input parameter validation. I can see it being useful for many of the typical ASP.NET middleware use cases.

**Comment by davidfowl** [comment]
@bromanko logging invocations isn't a good enough reason. That'll be there by default in the new version. 

> Another use case I'm exploring is for input parameter validation

Maybe. What sort of validation do you have in mind? There's no model binding, validation or anything like that (or plans for anything like that currently).

I'd prefer if this version of SignalR is extremely light weight and inflexible by default with minimal extension points. 

> I can see it being useful for many of the typical ASP.NET middleware use cases.

I need more examples, ASP.NET middleware is specific to the http domain. These are specifically RPC invocations. We need more scenarios to make sure what we build works.

As you can tell, I'm not a fan of the existing hub pipeline so I'm not keen to bring anything like it back until there are a bunch of scenarios that require it.

**Comment by bromanko** [comment]
No major complaints from me. I am more interested in understanding the roadmap than trying to convince you to add this feature. Logging has been the only thing I immediately needed and as you mentioned, this is being included. 

For parameter validation, I was considering adding DataAnnotation validation at a cross-cutting level. 

Another potential use-case could be adding per-invocation authorization. From the best I can tell, right now authorization is handled only at the hub level.

**Comment by davidfowl** [comment]
> For parameter validation, I was considering adding DataAnnotation validation at a cross-cutting level.

What sort of application data are you posting to your hubs? 

> Another potential use-case could be adding per-invocation authorization.

Already works per invocation and per hub connection.

> I am more interested in understanding the roadmap than trying to convince you to add this feature

Yes that's great! I have no doubt this feature is generally useful (thats why we did it initially) but I want to see some concrete examples before we add anything else.

**Comment by muratg** [comment]
We're looking related topics here: https://github.com/aspnet/SignalR/issues/924

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
