### ISSUE TITLE
Question about js client vs server version

### ISSUE THREAD

**Issue by valeriob** [aspnet/SignalR#873]
Hi,
i'm lost in versioning hell :D
npm signalr-client is versioned 0.0.17, server is versioned like 1.0.0-alpha1-26873 then there are rel/2.0.0  rel/2.0.0-preview1 rel/2.0.0-preview2.
signalr-client 0.0.17 works with 1.0.0-alpha1-26699, but no longer with 1.0.0-alpha1-26873.
I downloaded rel/2.0.0 and it began download netcore sdk 2.0.0 preview 3 😄.
Can you explain a bit how it works ? thanks

**Comment by moozzyk** [comment]
As per [README](https://github.com/aspnet/SignalR/tree/30f16fcf4be46d118d34645a77afc31143525250) for ASP.NET SignalR Core you need to use the @aspnet/signalr-client. We are preparing the alpha release and will publish the package on npm. rel/2.0.0 branches should not be used - they were created when we branched ASP.NET Core 2.0 but SignalR was not part of it. If you want to build from source either use the dev branch or rel/1.0.0-alpha1 which will be used to cut the release.

**Comment by valeriob** [comment]
Thanks !
