### ISSUE TITLE
IHttpConnectionOptions and IHubConnectionOptions aren't exposed

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#875]
There is no way to new up a class that implements either `IHttpConnectionOptions` or `IHubConnectionOptions` because they aren't exported. Looks like we just need to add them to the index.ts file.

In general we need to rethink our exporting strategy. At the moment it is quite inconsistent. In some cases we export all types from a file/module while in other cases we re-export. We re-export if there are types in the file/module which should not exposed publicly but we should review if this is consistent and if there is a better way of doing this.

**Comment by BrennanConroy** [comment]
Also `IConnection` and `IHubProtocol` aren't exposed.

**Comment by moozzyk** [comment]
I am not sure if IConnection and IHubProtocol need to be exposed.

**Comment by BrennanConroy** [comment]
How do you write your own `BetterMessagePack` protocol then? Or implement `SuperFastUDP` connection?

**Comment by moozzyk** [comment]
For now we treat protocols as an internal thing (that's why IHubProtocol is in the Internal namespace)

**Comment by moozzyk** [comment]
In general we need to rethink our exporting strategy. At the moment it is quite inconsistent. In some cases we export all types from a file/module while in other cases we re-export. We re-export if there are types in the file/module which should not exposed publicly but we should review if this is consistent and if there is a better way of doing this.

**Comment by andreimcristof** [comment]
+1, need this as well

**Comment by moozzyk** [comment]
@andreimcristof - I don't think this issue is related to headers too much. Even if you created a custom IHttpClient it won't really  - it would basically work only for the OPTIONS request. Keep in mind the neither WebSocket nor EventSource allow passing headers. I think you will need to use querystring for passing authorization header. Also, see: #888 and #686

**Comment by andreimcristof** [comment]
@moozzyk thank you for the detailed explanation. cheers

**Comment by BrennanConroy** [comment]
This was done in @anurse's refactor
