### ISSUE TITLE
possible System.* v 4.0.1 and v4.2 dependency issue upon adding signalr v1.* to project.json

### ISSUE THREAD

**Issue by MarcAir** [aspnet/SignalR#88]
using 1.2.0-* netcoreapp1.2 adding "Microsoft.AspNetCore.SignalR": "1.0.0-*" causes dependency ambiguity issues with type 
`Task<TResult>`
```csharp
Error	CS0433	The type 'Task<TResult>' exists in both 'System.Threading.Tasks, Version=4.0.10.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.2.0.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	ds.air..NETCoreApp,Version=v1.2
```
I have tried digging for this issue for about a week, and have narrowed down to possible package dependencies (although this is speculation here)
[Newtonsoft.json <9.0.1](https://www.nuget.org/packages/Newtonsoft.Json/)

**Comment by davidfowl** [comment]
It's because you need to use the specific version of the toolchain that asp.nst is currently using. Newer packages depend on a new dotnet CLI sdk.

**Comment by MarcAir** [comment]
Oh I see yes you are correct. That pointer reminded me of the preview 3 migration for msbuild to preview 4 (*but as of now preview 5 is the current build).
I have some work todo here.
thanks again
