### ISSUE TITLE
Investigate polly for retries/reconnects

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#882]
We might be able to farm out reconnect logic to an external library if we have the right extension points. Polly is one of the common libraries used for resiliency https://github.com/App-vNext/Polly#retry we should investigate to see if this can be plugged in client side.

**Comment by grahamehorner** [comment]
that sound an interesting and compelling story, is there any concept of transient errors in SignalR ?

**Comment by davidfowl** [comment]
Nope. Once the connection is dead, it's dead.

**Comment by LarsKemmann** [comment]
So you would use Polly to try handling reconnects on the client side, is that right?
In that case, yes, you could probably use the `Policy` interface and either provide a default one or allow the caller to pass in a custom policy (`ISyncPolicy` or `IAsyncPolicy`, or expose a `PolicyBuilder` perhaps).
That might make for interesting solutions such as the caller providing a circuit breaker policy.

**Comment by muratg** [comment]
We won't be implementing this.
