### ISSUE TITLE
Question: Getting the hubcontext from a controller

### ISSUE THREAD

**Issue by ajtowf** [aspnet/SignalR#884]
Hi, this is more of a question, couldn't find anything in the docs or samples, so here it goes:

Given a HomeController that I post to, how do I get the hubcontext to publish something to the clients? Let's say I inject IServiceProvider and IHttpContextAccessor (just in case there is an extension).

    [Route("api/chat")]
    public class HomeController : Controller {

        private ISomething _something;

        public HomeController(IServiceProvider serviceProvider, IHttpContextAccessor accessor) {
            _something = accessor.HttpContext.Features.Get<ISomething>();
        }
        public IActionResult Post() {
            _something.Clients.All.send("Hello");
            return Ok();
        }
    }

I guess I expect ISomething to be something similar to IConnectionManager.

**Comment by BrennanConroy** [comment]
This should help https://github.com/aspnet/SignalR/issues/182

**Comment by ajtowf** [comment]
Ah ofc, worked like a charm, I even looked at the IHubContext interface but didn't realize that I needed to invoke InvokeAsync,  expected a dynamic object:

    [Route("api/chat")]
    public class HomeController : Controller {

        IHubContext<Chat> _something;

        public HomeController(IHubContext<Chat> chathubContext) {
            _something = chathubContext;
        }
        public IActionResult Post() {
            // I tried this earlier (expected dynamic), my bad: _something.Clients.All.send("Hello") 
            _something.Clients.All.InvokeAsync("send", "Hello");
            return Ok();
        }
    }

Thanks!

**Comment by moozzyk** [comment]
@ajtowf - there is a PR for this.

**Comment by ajtowf** [comment]
@moozzyk not sure I follow, it works as is? Didn't realize I just needed to resolve IHubContext<Chat>.
