### ISSUE TITLE
Standalone client and server

### ISSUE THREAD

**Issue by hemm1** [aspnet/SignalR#89]
I was thinking of using this across two separate applications, where the server is an API without any frontend whatsoever, and the frontend is a pure javascript app served via nodejs. Is this usage recommended, or even supported?

I suppose I can use nuget to get the package in my backend application, and use something like `npm install --save https://github.com/aspnet/SignalR` to get a hold of it in my frontend and then compile it myself using webpack, but then I will have unneeded `.cs` files in my `node_modules`, and unneeded `.ts`-files in my server (I will probably also need the typescript compiler in my server without any frontend). It feels like I am doing something wrong or misunderstanding something. Is there an easier way to split up the client and server code, or is this use case maybe not supported at this time?

**Comment by moozzyk** [comment]
Can't you compile on your dev box and deploy a compiled version to your frontend server instead of trying to compile it directly on the server? 

Eventually we will want to have a better experience for this kind of scenarios but we are in the early stages here and have not yet gotten to the point where we started thinking about this.

**Comment by hemm1** [comment]
Yeah, I suppose that would help a bit. I'll try it if I get the time. I might as well close this issue then, if some kind of support for this use case is in the pipeline anyway.

Thank you for your reply, and keep up the great work! 👍

**Comment by moozzyk** [comment]
We are now publishing the client as npm module. The module contains a browserified version of the client. You can install it using the following command:

`npm install signalr-client --registry https://dotnet.myget.org/f/aspnetcore-ci-dev/npm/`
