### ISSUE TITLE
Support cancelling Streaming results without client disconnection

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#898]
Today cancelling streaming results requires the connection to go away or the server side to sever the close it. There's no way for the client to independently cancel a stream without closing the connection. Support this requires a protocol change and a new message type to indicate a cancelled stream.

/cc @anurse @moozzyk

**Comment by BrennanConroy** [comment]
Our current observable implementation on the TS client has a closed bool that is unused.
https://github.com/aspnet/SignalR/blob/e42f6980b643f6474c144fc7fdd36aedb0bac19f/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Observable.ts#L6-L11

I hacked together using it and clients can locally unsubscribe by setting close to true.
We could combine that with sending a new message type to the server that will unsubscribe it from the server side.

**Comment by davidfowl** [comment]
@BrennanConroy look at RxJS to see how un subscription is done there.

**Comment by BrennanConroy** [comment]
Looks like they check the closed value like I was. As well as splicing the subscribers array to remove the closed subscription.

**Comment by muratg** [comment]
We should probably consider supporting non-streaming stops as well, perhaps via CancellationTokens.

**Comment by davidfowl** [comment]
@BrennanConroy I assigned this to you

**Comment by BrennanConroy** [comment]
When you call stream get back an observable
When you call unsubscribe on the observable send "complete" to server
When you call unsubscribe on the observer, remove from observable
When all observers unsubscribe, send "complete" to server
When server completes stream, complete all observers and clean up observable

```
var subject = connection.stream("streamMethod");
var subscriber = subject.subscribe({ next: x => console.log(x) });

// will cause subject to tell server to complete
subscriber.unsubscribe();
// or
// will complete subscriptions and send complete to server
subject.close();
```

@davidfowl @anurse @moozzyk 
Did I miss anything, or misinterpret anything?

**Comment by anurse** [comment]
> When you call unsubscribe on the observable send "complete" to server

You can call unsubscribe on an observable? I'm not sure I understand what that means...

**Comment by davidfowl** [comment]
Yea that doesn't look right. I think the code looks like this:

```
var observable = connection.stream("streamMethod");
var subscription = observable.subscribe({ next: x => console.log(x) });

// will cause subject to tell server to complete
subscription.unsubscribe();
```

**Comment by BrennanConroy** [comment]
Done for C# client https://github.com/aspnet/SignalR/commit/de2e0967c3da60e9af91a2985b90c7572c9c3322
TS/JS needs work

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/a86295956685f4c3600189ffcda0241e24786635
