### ISSUE TITLE
Stream Method is asynchronous but without Async suffix 

### ISSUE THREAD

**Issue by A7medRamadan** [aspnet/SignalR#899]
Stream Method is asynchronous but without Async suffix in its name, it should be StreamAsync

**Comment by davidfowl** [comment]
Which Stream method?

**Comment by A7medRamadan** [comment]
HubConnection connection = hubConnectionBuilder.WithUrl(url).Build();

await connection.**Stream**<>("", "");
I think it should be 
await connection.**StreamAsync**<>("", "");

**Comment by davidfowl** [comment]
It's not async though. It returns a ReadableChannel\<T\>.

**Comment by A7medRamadan** [comment]
Yes, it would make more sense to be async
