### ISSUE TITLE
Can't send message directly to a connectionId

### ISSUE THREAD

**Issue by FailHair** [aspnet/SignalR#901]
I'm trying to send a specific message to a specific user using its `connectionId`. But the message never arrives at the client. The JS code is never called. I do this with the following code:
```
// message.ConnectionId = the connectionId of the "user" I want to send the message to.
await Clients.User(message.ConnectionId).InvokeAsync("DirectChat", new[] { message.Text });
```
note: I've been sure, with a breakpoint, that `message.ConnectionId` contains the correct value.

When I change that line to this:

```
await Clients.All.InvokeAsync("DirectChat", new[] { message.Text });
```

Then it all works. But obviously then everyone receives the message, which I don't want.

So I'm either doing something wrong or there exists a bug when trying to send a message directly to a `connectionId`. Is there a way to solve this issue?

I'm currently using `SignalR 1.0.0-alpha2-27024`.

**Comment by BrennanConroy** [comment]
Use `await Clients.Client(message.ConnectionId)...`

**Comment by davidfowl** [comment]
Right , user is for user names, not connection ids.

**Comment by FailHair** [comment]
Thanks a lot, that works!
