### ISSUE TITLE
Add SignalR specific build information to the README.md

### ISSUE THREAD

**Issue by jkotalik** [aspnet/SignalR#906]
@BrennanConroy @moozzyk @mikaelm12 we are updating build/contributing information across all of our repos. Would it be possible to add SignalR specific build requirements (like typescript and npm) to the README?

**Comment by moozzyk** [comment]
typescript is not required it is being brought by npm. npm and nodejs are required.

**Comment by willthiswork89** [comment]
i was failing because i didnt have gulp either so that should be noted as well i would think.

**Comment by moozzyk** [comment]
@willthiswork89 - need to check this. I thought it should be fine because we bring it as a [dependency](https://github.com/aspnet/SignalR/blob/2efbd6a95ae16b18f1432abacc3931374618617d/client-ts/package.json#L34).

**Comment by willthiswork89** [comment]
on my machine where i traditionally have not done front end dev i was getting an error "Failed to run command gulp " when i would try to build the front end client library from a clean visual studio 2017 solution. I can try to replicate by uninstalling gulp for you

**Comment by willthiswork89** [comment]
ah yes this is it 

  
  <Target Name="BuildTSClient" Inputs="@(Inputs)" Outputs="@(Outputs)" BeforeTargets="Build">
    <Exec Command='npm run gulp -- --gulpfile "$(MSBuildThisFileDirectory)gulpfile.js" build-ts-client' />
  </Target>

**Comment by moozzyk** [comment]
Thanks @willthiswork89 - I will check this.

**Comment by moozzyk** [comment]
@willthiswork89 - I cannot repro this. I uninstalled the gulp that was installed globally and ran the BuildTSClient target and it worked just fine. Note that gulp is in invoked via npm so as long as you run npm install (see the comment above the target) gulp should be found in the project node_modules folder. I run the global gulp often times at development time when I just want to build the client but it is not a requirement for build.cmd to run and succeed. We also don't install gulp on our CI servers (see [.travis.yml](https://github.com/aspnet/SignalR/blob/80bf6951817409e978939c75fbdf5adbf2445b0d/.travis.yml) or [.appveyor.yml](https://github.com/aspnet/SignalR/blob/80bf6951817409e978939c75fbdf5adbf2445b0d/.appveyor.yml)) and the builds pass.

```
PS C:\source\SignalR> gulp
gulp : The term 'gulp' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ gulp
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (gulp:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\source\SignalR> cd .\client-ts\
PS C:\source\SignalR\client-ts> cd .\Microsoft.AspNetCore.SignalR.Client.TS\
PS C:\source\SignalR\client-ts\Microsoft.AspNetCore.SignalR.Client.TS> dotnet build /t:BuildTSClient
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft.AspNetCore.SignalR.Client.TS -> C:\source\SignalR\client-ts\Microsoft.AspNetCore.SignalR.Client.TS\bin\Debug\netstandard2.0\Microsoft.AspNetCore.Sig
nalR.Client.TS.dll

  > @aspnet/signalr-client@1.0.0 gulp C:\source\SignalR\client-ts
  > gulp "--gulpfile" "C:\source\SignalR\client-ts\Microsoft.AspNetCore.SignalR.Client.TS\gulpfile.js" "build-ts-client"

  [12:12:21] Working directory changed to C:\source\SignalR\client-ts\Microsoft.AspNetCore.SignalR.Client.TS
  [12:12:21] Using gulpfile C:\source\SignalR\client-ts\Microsoft.AspNetCore.SignalR.Client.TS\gulpfile.js
  [12:12:21] Starting 'clean'...
  [12:12:22] Starting 'compile-ts-client'...
  [12:12:22] Finished 'clean' after 86 ms
  [12:12:24] Finished 'compile-ts-client' after 2.33 s
  [12:12:24] Starting 'browserify-client'...
  [12:12:24] Starting 'browserify-msgpackprotocol'...
  [12:12:24] Starting 'browserify-clientES5'...
  [12:12:24] Starting 'browserify-msgpackprotocolES5'...
  [12:12:26] Finished 'browserify-client' after 2.21 s
  [12:12:32] Finished 'browserify-msgpackprotocol' after 7.82 s
  [12:12:38] Finished 'browserify-msgpackprotocolES5' after 14 s
  [12:12:38] Finished 'browserify-clientES5' after 14 s
  [12:12:38] Starting 'browserify'...
  [12:12:38] Finished 'browserify' after 80 ╬╝s
  [12:12:38] Starting 'build-ts-client'...
  [12:12:38] Finished 'build-ts-client' after 26 ms

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:22.04
PS C:\source\SignalR\client-ts\Microsoft.AspNetCore.SignalR.Client.TS>
```
