### ISSUE TITLE
Connection Establishment Semantics

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#91]
Rename `/getid` to `/negotiate` and have it establish the connection metadata and state (including allocating the Channel/Pipeline). We will **still** support a raw WebSocket connection, which will lazily initialize the connection state, but Server-sent Events and Long Polling will require that the connection be established before working. This should eliminate the Send/Poll race referred to in #82.

**Comment by anurse** [comment]
When this is done, fix the weirdness in Microsoft.AspNetCore.Sockets.Client.LongPollingTransport where we wait for Poll to start before sending.

**Comment by mikaelm12** [comment]
Cant wait to get the `Task.Delay` calls out of our tests 😄
