### ISSUE TITLE
Dependency Injection with SignalR

### ISSUE THREAD

**Issue by nguyenquocquan** [aspnet/SignalR#910]
Hi all,
I have a issue with SignalR, my source using DI into Chat : Hub file, but didn't use Dependency Injection.
Please help me with this issue!
Thanks

**Comment by davidfowl** [comment]
@nguyenquocquan Can you put a sample project on github with steps to reproduce the problem?

**Comment by nguyenquocquan** [comment]
@davidfowl 

![app_start](https://user-images.githubusercontent.com/24238292/30581056-064aacec-9d49-11e7-95ed-f99e9f753995.PNG)

`My application_Start`

![startup](https://user-images.githubusercontent.com/24238292/30581083-1a55997c-9d49-11e7-9a57-b24863224a6a.PNG)

`Startup.cs`

![dependency](https://user-images.githubusercontent.com/24238292/30581098-258384e4-9d49-11e7-9b6e-673d0875d4ec.PNG)

'Register Dependency'

![chathub](https://user-images.githubusercontent.com/24238292/30581118-379ffe5a-9d49-11e7-9434-7fdfe9f8d9b0.PNG)

`And ChatHub file` connect with client

**Comment by nguyenquocquan** [comment]
And this is error when i run app

![error](https://user-images.githubusercontent.com/24238292/30581407-3120cca2-9d4a-11e7-9006-b4acd48994c0.PNG)

**Comment by davidfowl** [comment]
@nguyenquocquan This belongs on http://github.com/SignalR/SignalR. This is the repository for the ASP.NET Core version of SignalR. Please move the issue over there.
