### ISSUE TITLE
IIS Reverse Proxy

### ISSUE THREAD

**Issue by RassK** [aspnet/SignalR#911]
How do you reverse proxy ws channel ?

I have a standalone kestrel running aspnetcore webapi + IIS in front, doing reverse proxy. With the old signalr there was an outbound rule to rewrite, but what's the case with new signalr ?

JS console is clean for a while. Saying it's connected, but no single frame is moving. After a while you can notice: 
WebSocket connection to 'ws://endpoint/virtual-dir/myhub?id=942b7d3c-64ed-461c-b59c-1d4912c11b6e' failed: Invalid frame header

```
            <rules>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://localhost:5000/{R:1}" />
                </rule>
            </rules>
```

Removing reverse proxy and everything works nicely.

**Comment by moozzyk** [comment]
By default SignlaR should work behind IIS without having to add any url rewrite rules.

**Comment by RassK** [comment]
yes, by the default case. I'm hosting kestrel server locally and it's seen to the outside only via IIS reverse proxy. So in this case rules are needed to proxy requests.

**Comment by davidfowl** [comment]
> So in this case rules are needed to proxy requests.

Nope. Sounds like it isn't the default case. Hosting Kestrel behind IIS via ANCM (the ASP.NET Core IIS Module) just works without rewrite rules.

**Comment by RassK** [comment]
Exactly, thats what im telling, the default case works okay. But lets consider the option, when ANCM is not used and IIS app is just a proxy containing only web.config file for reverse proxying. In simple words, proxy and app are separated.

**Comment by davidfowl** [comment]
Great now we're on the same page, I didn't realize that you weren't using ANCM. What are you using to proxy requests to the back end? ARR, that's the only other thing that would work. I don't see how rewrite rules would help.

**Comment by davidfowl** [comment]
Searching for url rewrite reverse proxy websockets yields some interesting results on the interwebz https://stackoverflow.com/questions/34316825/websockets-reverse-proxy-in-iis-8. In general though, I would try to get it working with pure websockets without SignalR and see if you hit any problems with that. 

> WebSocket connection to 'ws://endpoint/virtual-dir/myhub?id=942b7d3c-64ed-461c-b59c-1d4912c11b6e' failed: Invalid frame header

This looks like a pretty low level bug somewhere.

**Comment by RassK** [comment]
Yeap, should be ARR3 IIS module.

Before the aspnetcore signalr version i had a signalr specific outbound rule. But as the endpoints are now changed, it wouldn't work. So it's probably the negoation part what breaks.

`
<outboundRules>
	<rule name="Update Url property" preCondition="JSON" enabled="true" stopProcessing="true">
		<match filterByTags="None" pattern="\&quot;Url\&quot;:\&quot;(.+?)\&quot;" />
		<conditions>
			<add input="{URL}" pattern="(.*)/signalr/" />
		</conditions>
		<action type="Rewrite" value="&quot;Url&quot;:&quot;{C:1}{R:1}&quot;" />
	</rule>
	<preConditions>
		<preCondition name="JSON">
			<add input="{URL}" pattern="/signalr/negotiate" />
			<add input="{RESPONSE_CONTENT_TYPE}" pattern="application/json" />
		</preCondition>
	</preConditions>
</outboundRules>
`

**Comment by muratg** [comment]
This is external to SignalR. ANCM bug tracking this issue: https://github.com/aspnet/AspNetCoreModule/issues/163

**Comment by shirhatti** [comment]
Just want to point out that @RassK reported a ARR bug. I want to ack that we're looking into ARR but can't share the tracking information since ARR is private.

Given that ANCM and ARR share design aspects, it is likely that ANCM suffers from the same issue which is what is being tracked in the linked issue.

**Comment by onlyann** [comment]
@shirhatti
Is it still an issue today to use IIS ARR as a reverse proxy to relay SignalR websocket communications?
