### ISSUE TITLE
.then(...) Exception

### ISSUE THREAD

**Issue by harveytriana** [aspnet/SignalR#912]
Hello -
About Getting Started. I worked this basic guide. 

hubConnection.start(); 
             .then(() => connection.invoke('Send', 'Hello'));

Shows this exception: Uncaught (in promise) ReferenceError: connection is not defined at  hubConnection.start.then 

Then, I removed: .then(), that is:

hubConnection.start();

After that works fine.

One minor thing. I did not see clear how to use npm from Visual Studio. I did it manually.

Bye.
P.S Excellent. I have long worked with SignalR as an inherent part of my software development.

**Comment by moozzyk** [comment]
What is `connection` in your code? I don't see it being declared so the error seems to be that you are referring to a non-declared variable. Try:
```
hubConnection.start()
    .then(() => hubConnection.invoke('Send', 'Hello'));
```

I am not sure if there is npm related tooling in VS. Using npm directly is fine (I do it all the time).

**Comment by harveytriana** [comment]
Right - Sorry - Closed.


________________________________
De: Pawel Kadluczka <notifications@github.com>
Enviado: martes, 19 de septiembre de 2017 11:24 a. m.
Para: aspnet/SignalR
Cc: Luis Harvey Triana Vega; Author
Asunto: Re: [aspnet/SignalR] .then(...) Exception (#912)


What is connection in your code? I don't see it being declared so the error seems to be that you are referring to a non-declared variable. Try:

hubConnection.start()
    .then(() => hubConnection.invoke('Send', 'Hello'));


I am not sure if there is npm related tooling in VS. Using npm directly is fine (I do it all the time).
