### ISSUE TITLE
SignalR TypeScript Library doesn't compile in basic scenario after importing from npm

### ISSUE THREAD

**Issue by QuinntyneBrown** [aspnet/SignalR#923]
I would like to make a basic (no frameworks) client implementation of SignalR Core TypeScript library to test my server implementation.

The library does not compile using tsc. I receive the error, "Can not find Map". I believe it is a Typings issue.

The following is repo that demonstrates the issue.

https://github.com/QuinntyneBrown/signalr-core-client-getting-started

**Comment by moozzyk** [comment]
No, it is not typings. You are trying to compile to `"target": "es2015",` and Map and some other types are not supported in ES5. You can try adding `"lib": ["es2015", "dom"]` to your compilerOptions but I am not sure if it fixes it. If it doesn't the options are: 
- target es6
- if you need es5 compatible version - target es6 and transpile to es5

**Comment by QuinntyneBrown** [comment]
The project is targeting es (es2015) and the lib configuration you have described is in the tsconfig.

https://raw.githubusercontent.com/QuinntyneBrown/signalr-core-client-getting-started/master/tsconfig.json

When you import the SignalR TypeScript with Angular, it works fine. PeerDependecy issue? Not sure. 

I would love to see a standalone sample, importing the lib from npm, tsc compile and used in a vanilla html page.

**Comment by moozzyk** [comment]
The config seems to have [`es2016`](https://github.com/QuinntyneBrown/signalr-core-client-getting-started/blob/master/tsconfig.json#L14) and not `es2015` though.

**Comment by moozzyk** [comment]
I tried to repro this without any changes (i.e. with `es2016` in the config) and I was not able to:
```
PS C:\temp\signalr-core-client-getting-started> npm install

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\temp\signalr-core-client-getting-started\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

added 539 packages in 24.128s
PS C:\temp\signalr-core-client-getting-started> tsc
PS C:\temp\signalr-core-client-getting-started> ls .\src\


    Directory: C:\temp\signalr-core-client-getting-started\src


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/21/2017   4:02 PM            292 main.js
-a----        9/21/2017   4:02 PM            400 main.js.map
-a----        9/21/2017   3:59 PM            267 main.ts


PS C:\temp\signalr-core-client-getting-started> node .\node_modules\webpack\bin\webpack.js

[at-loader] Using typescript@2.5.2 from typescript and "tsconfig.json" from C:\temp\signalr-core-client-getting-started/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.287 sec.
Hash: f0d5b0133e6f9464d5f1
Version: webpack 3.6.0
Time: 2309ms
 Asset    Size  Chunks                    Chunk Names
app.js  267 kB       0  [emitted]  [big]  app
   [0] (webpack)/buildin/global.js 509 bytes {0} [built]
  [26] ./src/main.ts 260 bytes {0} [built]
    + 47 hidden modules
```

`tsc` compiled the main.ts without any errors. 
I ran webpack and it created a script in the dist folder that was running just fine:

![image](https://user-images.githubusercontent.com/1438884/30722621-1e6e2fe8-9ee7-11e7-8c6a-faf940ead1b7.png)

(The errors in the browser is because the script does not start the connection before it is trying to send (there is no server anyways so starting the connection would not work either) but it is thrown from the client itself so the compilation did complete successfully and the client can be created and methods can be invoked). 

I am closing it for now since I can't repro the issue with the code you provided.
