### ISSUE TITLE
Add support to HubLifetimeManager for handling incoming invocations before the hub method is called

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#924]
This is basically slowly bringing back the hub pipeline. We'll eventually end up with a decorator pattern again for wrapping all hub incoming and outgoing invocations

**Comment by anurse** [comment]
@muratg I'm going to bump this to preview2 for now, just because it'll be public API and it would be good to get it into a preview and not just cram it in right before RTM :). We can always reschedule it as needed.

**Comment by RefaeloGanesh** [comment]
Is there an estimate when an updated version will come out?

**Comment by anurse** [comment]
SignalR Core is due in the first half of 2018 (see the Roadmap: https://github.com/aspnet/Home/wiki/Roadmap). We're hoping to have a first preview out in early 2018 (no guarantees), but this fix is targeted at the second preview (date TBD).
