### ISSUE TITLE
camelCase JSON contract resolve is not picked up

### ISSUE THREAD

**Issue by Arash-Sabet** [aspnet/SignalR#925]
We want to have signalR core library version **1.0.0-alpha1-final** return us camelCase properties when serializing objects but our approach was not conclusive despite it worked for the non-core version of signalR. We simply followed [this thread](https://stackoverflow.com/questions/37832165/signalr-net-core-camelcase-json-contract-resolver) as a guideline but our attempt for the core version was not conclusive.

Is there an issue in the signalr core library in terms of bringing such a custom serializer into account?

**Comment by BrennanConroy** [comment]
```c#
services.AddSignalR(o =>
{
    o.JsonSerializerSettings = new JsonSerializerSettings
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver()
    };
});
```

**Comment by Arash-Sabet** [comment]
@BrennanConroy Worked. thanks!
