### ISSUE TITLE
When is the project going to target netstandard2.1

### ISSUE THREAD

**Issue by NtFreX** [aspnet/SignalR#929]
Why is the target at the moment still netstandard 2.0 when it will be released for netstandard2.1?

I would like to take a look how I can implement an sql server backpane and the SqlDependecy class has only been added to netstandard2.1.

By the way: Is there any interesst in adding support for sql server as an backpane?

**Comment by grahamehorner** [comment]
@NtFreX SignalR doesn't need to target the netstandard 2.1 as you can use libraries developed lower versions of the standard can be used with applications that use high versions of the standard @DamianEdwards @davidfowl can you confirm my understanding?

**Comment by davidfowl** [comment]
You are correct, we don't need to target 2.1 for your applications or libraries to use 2.1. It just means your backplane implementation requires 2.1.

We're not sure about the sql server backplane just yet. We'll base on it the demand which is pretty low at the moment.

**Comment by NtFreX** [comment]
@grahamehorner @davidfowl Thanks for the info. You do not coincidentally have a source where I can read up what happens under the hood when I use an 2.1 library from 2.0?

**Comment by davidfowl** [comment]
Conceptually it's the same as asking if a library targeting .net 4.5 can run on .net 4.6. The answer is yes , it's backwards compatible
