### ISSUE TITLE
sample compilation vs2017 rc1 client/etc. TS not compiled

### ISSUE THREAD

**Issue by MarcAir** [aspnet/SignalR#93]
using signalr 1 preview 1 in vs 2017 rc1 projects the ts compilation does not occur. 
where is the location of the files for msbuild to reference?
```xml
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish" Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
    <Exec Command="bower install" />
    <Exec Command="dotnet bundle" />
    <Exec Command="npm run gulp -- --gulpfile %project:Directory%/../../src/Microsoft.AspNetCore.SignalR.Client.TS/gulpfile.js bundle-client --bundleOutDir %project:Directory%/wwwroot/lib/signalr-client/" />
  </Target>
```

**Comment by moozzyk** [comment]
Were there any errors?

**Comment by MarcAir** [comment]
none, it completely ignores the command.
whats interesting is that also the source is not located in the relative path - I am trying to get an error out of it to point me in the right direction.

How does TS work with signalr in vs 2017 for building out the client scripts?

**Comment by moozzyk** [comment]
Maybe the target is not invoked at all?

I have not tried using VS2017 yet but we are planning to convert this repo to VS2017 in the coming days. Looks like this will be one of the issues we will have to understand and fix.

**Comment by MarcAir** [comment]
Thanks for the quick response :) at least your comments have saved me hours of hunting - ill see if I can go back to vs 2015 and get her working.
thanks

**Comment by moozzyk** [comment]
The repo has been converted to csproj and things seem to work fine. Closing this for now. Feel free to reopen and provide more details if it does not work for you.
