### ISSUE TITLE
Allow direct connect to the HubEndPoint without negotiation

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#932]
We should be able to expose a model where everything is fully specified via configuration on both server and client that would avoid any negotiation and would just directly connect using the specified transport and protocol.

This includes:
- [x] - Direct websocket connection without http negotiation for a connection id (#1035)
- [ ] - Specific protocol selection which avoids hub protocol negotiation.

Related to #854  

/cc @anurse @moozzyk

**Comment by anurse** [comment]
To write down my thoughts from earlier in-person discussions:

I think a good way to represent this, architecturally, is to change our Hub Protocol abstraction to be a little more stateful and move negotiation into that layer. We'd build a `NegotiatedHubProtocol` which contains a list of Hub Protocols to negotiate. That component handles the first negotiation frame and then just proxies all data through to the appropriate Hub Protocol. Then, every Hub endpoint has one and only one instance of Hub Protocol associated with it (a `NegotiatedHubProtocol` containing the JSON and MsgPack Hub Protocols, by default), and users can reconfigure as needed. I think this would be better than a first-class "disable negotiation" feature.

Having said all that, we should consider making a simpler configuration model available (extension methods or something). A TCP endpoint that only wanted to speak MsgPack would simply change the Hub Protocol in the HubOptions from it's default value to `MsgPackHubProtocol`.

**Comment by moozzyk** [comment]
We decided not to do the second part. Everything can work fine if things are aligned but if anything is misconfigured - and getting to this state is quite easy - it's a pit of failure because there is not a good way to detect this state and close the connection with a clear message. See comments in https://github.com/aspnet/SignalR/pull/1095 for more details.
