### ISSUE TITLE
How scalable is SignalR?

### ISSUE THREAD

**Issue by fragilethoughts** [aspnet/SignalR#936]
How SignalR can deal with many concurrent connections like 100 000+ ? If userbase grows how can this be achieved? I was thinking of using it in my social media like project for live feeds, chatting and so on. I could as well use some pre-existing solution and go easy way with services like Firebase or Pusher and it would be handled for me. But what if I wrote my own infrastructure based on SignalR, WebSockets? I'm also looking for the most affordable solution. I think first of making a limit of 10 000 connections. Will I need multiple servers for that, and most importantly what server could handle so many connections, and what would be the CPU, RAM usage. Was SignalR tested in highly scalable applications? What is more cost-effective (financially)? (Sockets, Long polling?, third party service like Pusher, Firebase). WebSockets seem like a modern solution to me and I would like to try go this way.

https://deepstreamhub.com/blog/load-balancing-websocket-connections/

**Comment by davidfowl** [comment]
We haven't done that level of scale testing yet but as always it will be dependent on your app, your hardware etc

> What is more cost-effective (financially)? (Sockets, Long polling?, third party service like Pusher, Firebase). WebSockets seem like a modern solution to me and I would like to try go this way.

Are you counting the cost of maintenance?

**Comment by fmj02** [comment]
Yes counting the cost of maintenance.

**Comment by willthiswork89** [comment]
Try not to pre-optimize. Keep the design in mind for growth but do not go out of your way to handle an eventuality that may never happen. 

With SignalR and Redis it should not be that hard to scale through a microservice or something.

**Comment by markrendle** [comment]
This is always going to be one of those "it depends" situations.

If you hop onto Azure or similar and set yourself up a nice big cluster of medium-sized servers (something like D2v3 or D4v3) behind a load-balancer with sticky websocket support, and a big fat Redis cache as a backplane, you should be able to run some load tests and (as long as you delete the resource group when you're finished) it will only cost you a few bucks. Experiment with different topologies, but bear in mind that in production you're going to want at least 3 servers so just running a single D64v3 is not an option.

**Comment by davidfowl** [comment]
As we get closer and closer to the release, we're working on getting more numbers. I'll update this thread with our results.

**Comment by Dewaldf** [comment]
Hi, do we have some numbers yet ? Is there anywhere we can see what has been achieved so far ?

thanks

**Comment by davidfowl** [comment]
This is our only load test run
https://twitter.com/anurse/status/983406560880701440

/cc @anurse

**Comment by Dewaldf** [comment]
Looks very good, thanks

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
