### ISSUE TITLE
Update README with status of the project and future roadmap/timeline

### ISSUE THREAD

**Issue by ryanwalls** [aspnet/SignalR#937]
Without a lot of digging through issues and PRs, it is not possible to get an idea of whether this project is ready for production or not.  What the latest status is.  What the future timeline or roadmap is.  

It would be ideal to have this all available in the README.

**Comment by davidfowl** [comment]
https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/

SignalR is currently released as an alpha1 with an alpha2 coming in the next week or so on top of ASP.NET Core 2.0. Subsequent releases will align with the ASP.NET Core 2.1 timeline. We'll be posting the ASP.NET Core 2.1 roadmap any day now.

/cc @DamianEdwards @glennc

**Comment by moozzyk** [comment]
Typically you would use NuGet to get the packages. NuGet shows available versions of a package and it makes it clear what the last version is e.g.: https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR

**Comment by ryanwalls** [comment]
@moozzyk Yep, that is helpful, but doesn't give much context about release notes, what is working/what isn't, coming features, etc.

**Comment by moozzyk** [comment]
I suppose we will have documentation once we ship the final version. The NuGet page makes it clear whether it is ready for production - the newest package is alpha1 and there is a message saying it's a prerelease version. My experience with putting road maps, planned features etc. in the README is that it is hard to keep the information up-to-date and therefore is can be more confusing than not having anything at all.
