### ISSUE TITLE
Except functionality

### ISSUE THREAD

**Issue by Gurgen** [aspnet/SignalR#939]
1. I want to send message to all authorized users
2. I want to send message to specified user except some connection ids

I mean, it will be excellent to add except clients to all clients filter, we have AllExcept() but can't add except to groups and other filters

Like this

T Group(string groupName, IReadOnlyList<string> excludedIds = null);
T User(string userId, IReadOnlyList<string> excludedIds = null);

**Comment by BrennanConroy** [comment]
`User(string userId)` is to a single user so an except list doesn't make sense.
Groups one is questionable, since you could manage your groups differently so the exclude list is automatically there.

**Comment by davidfowl** [comment]
Right the goal is to provide very basic building blocks so you can do more complex groupings using add/remove to group.

**Comment by Gurgen** [comment]
Look. Client User-X connected to hub and I want to inform all other connected clients of User-X except connected user

**Comment by Gurgen** [comment]
`public override Task OnConnectedAsync()
        {
            Clients.Client(Context.ConnectionId).InvokeAsync($"Hello {Context.User.Identity.Name}, you are connected!");
            Clients.User(Context.User.Identity.Name).InvokeAsync($"You are connected from another device!", except: Context.ConnectionId);
            return base.OnConnectedAsync();
        }`

**Comment by KPixel** [comment]
@Gurgen This is not possible yes, but eventually, I think you should be able to find the connection ids of the other connected clients to send the second message, so the code could look like this:

```C#
public override async Task OnConnectedAsync()
{
    await Clients.Client(Context.ConnectionId).InvokeAsync($"Hello {Context.User.Identity.Name}, you are connected!");

    var otherClients = Connections.Where(c => c.User.Identity.Name == Context.User.Identity.Name
        && c.ConnectionId != Context.ConnectionId).Select(c => c.ConnectionId);

    await Clients.Clients(otherClients).InvokeAsync($"You are connected from another device!");
    await base.OnConnectedAsync();
}
```

I discussed an API for that here #683.

And note that this code would have to be written very differently if you need to scale out...

**Comment by Gurgen** [comment]
OK, I understand that we can implement a Base class derived from Hub and implement there functionality as we want. I mean with this issue/improvement will be more simple working with hubs if we have except list of connections to every sub collection of connections.

**Comment by Gurgen** [comment]
Also I created library to work with .net core signal r hubs from android, if you interested.
The repository is here, and at the moment supports only connections via websockets
[https://github.com/Gurgen/SignalR-.net-core-android-client](https://github.com/Gurgen/SignalR-.net-core-android-client)

**Comment by Gurgen** [comment]
[https://github.com/Gurgen/SignalR/commit/84ed23c83bf587aaccc6118701c9082b28fc54fd](https://github.com/Gurgen/SignalR/commit/84ed23c83bf587aaccc6118701c9082b28fc54fd)

Please look at this commit

**Comment by Gurgen** [comment]
I implemented [InvokeFilter](https://github.com/Gurgen/SignalR/commits/gurgen/invokeBuilder) with exclude feature and not only.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
