### ISSUE TITLE
Is there any QueryString equivalent ?

### ISSUE THREAD

**Issue by Pictar** [aspnet/SignalR#942]
Hello,

Before switching to the .NET Core version of SignalR, I used to be able to send parameters before starting the connection using QueryString such as

`var connection = $.hubConnection();`
`connection.qs = { 'version' : '1.0' };`

and get them in the C# back with `var version = Context.QueryString['version'];`

However I can't find anything like that in .NET Core. How can I achieve the same result, or is there even a way to do that now ?

Thanks

**Comment by moozzyk** [comment]
When you create a hubConnection you need to pass an url which can contain parameters e.g. 
```
var hubConnection = new signalR.HubConnection('/chat?p1=42');
```

**Comment by bogatykh** [comment]
Question was not answered.
How to read query parameters inside Hub?

**Comment by anurse** [comment]
Reading query string parameters in the hub is not recommended as SignalR is generally not directly tied to a single HTTP request (there are multiple requests going on throughout the connection). However, if it's essential to your scenario and can't be done any other way, you can access the entire HTTP context (including the query string) via `Context.GetHttpContext()` in the Hub.
