### ISSUE TITLE
Expose IHttpConnectionFeature Properties 

### ISSUE THREAD

**Issue by zAfLu** [aspnet/SignalR#944]
Hello my friends,

I'm currently struggling a bit with "how to get the caller ip". I thought the connection information’s where In _hub.Context.Connection_ but I cannot find any IPs in the whole Hub class. So maybe you can give me a hint :)

**Comment by davidfowl** [comment]
We need to hoist this to a first class feature on the hub.Context.Connection but this should work:

```
Context.Connection.GetHttpContext().Connection.LocalIpAddress
```

**Comment by zAfLu** [comment]
oh well ... i think i need to open my eyes next time. thanks mate :)
And yes hosting this as a first class feature would be nice.

**Comment by mikaelm12** [comment]
Done in: 40e906f23a311d745230b8a3b48c919b25231f7c
