### ISSUE TITLE
Publish signalr-client typings to the @types scope

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#951]

**Comment by arshadhammad** [comment]
Is there any way around till they publish signalr-client typings to the @types scope?

**Comment by anurse** [comment]
The `.d.ts` files are present in the `src` directory and linked via the package.json, so if you're using NPM, you should be able to access the definitions already. In fact, I'm not even sure that publishing to `@types` is going to be necessary if we continue shipping `.d.ts` files in the main package. The `@types` packages are only needed when the types are maintained by someone other than the upstream, and since we write the client in TypeScript, we'll be maintaining the typings ourselves.

**Comment by moozzyk** [comment]
@anurse - there is a scenario when people want to use the transpiled .js in a ts project. See: https://github.com/aspnet/SignalR/issues/239#issuecomment-332223928 and https://github.com/aspnet/SignalR/issues/239#issuecomment-332469678

**Comment by anurse** [comment]
Yes, I've been looking at figuring out how best to rework our TypeScript build to build a unified `.d.ts` file as well. I still think we won't end up needing a separate `@types` package though.

**Comment by valeriob** [comment]
Thanks !
It's not so important where you put it, but the fact that it exists 😄 I do not know what side effect it will have by placing it inside browser folder side by side with signalr-client .js files.

**Comment by anurse** [comment]
> I do not know what side effect it will have by placing it inside browser folder side by side with signalr-client .js files.

As as you don't add a `script` tag for it, it'll have no effect in the browser ;)

**Comment by mnmr** [comment]
@anurse Please see my comment on [#239](https://github.com/aspnet/SignalR/issues/239) for suggestion on how to fix the typings for people that do not use modules.

**Comment by valeriob** [comment]
@anurse as long as you configure tsconfig.json to esclude "node_modules" and include just the files needed (or the complilation will be very slow).

**Comment by anurse** [comment]
We'll likely be using the [`export as namespace`](https://github.com/zspitz/TypeScript-Handbook/blob/release-2.0/pages/Modules.md#umd-modules) functionality for UMD support since we need to support both scenarios (CommonJS modules and Browser globals)

**Comment by anurse** [comment]
SignalR includes typings for both ESM/CJS and UMD usage, so a `@types` package is not required and the work here is done.

**Comment by valeriob** [comment]
I'm sorry but i do not find the type definition without modules in here https://www.npmjs.com/package/@aspnet/signalr-client , where is it ?

**Comment by anurse** [comment]
It'll be in the next release, you can use the instructions in the README to download it from our nightly feed.

**Comment by valeriob** [comment]
Ok, just to be sure, 1.0.0-preview2-30169 still does not contains them.

**Comment by anurse** [comment]
They're working on my end. What issue are you seeing? How are you referencing the package?

**Comment by mnmr** [comment]
@valeriob It looks like the client was moved (back?) to @aspnet/signalr - I'm guessing that is your problem with not seeing the changes.

**Comment by valeriob** [comment]
Thanks, i was looking for a single definition file, instead you made the code namespace compatible via export as namespace signalR;
Very good thanks !
