### ISSUE TITLE
signalR server crashes after deploying to IIS server

### ISSUE THREAD

**Issue by Arash-Sabet** [aspnet/SignalR#952]
We deployed our signalR server which works well in Visual Studio 2017 environment. When we publish the server it to an IIS server, we see the error message below. We are not using any performance counter or application telemetry in our code.

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AI.PerfCounterCollector, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
>    at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetry(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.ApplicationInsightsWebHostBuilderExtensions.<>c.<UseApplicationInsights>b__0_0(IServiceCollection collection)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext _, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at MyNamespace.Program.Main(String[] args)

**Comment by davidfowl** [comment]
It's an assembly load failure for application insights. Are you using app insights?

**Comment by Arash-Sabet** [comment]
@davidfowl No we are not using insights.

**Comment by Arash-Sabet** [comment]
@davidfowl Regardless of having or not having insights in our application, this issue should not happen. Here is our code:

```
public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
```

Here is the startup class:

```
public class Startup
	{
		private const string CorsPolicy = MyCorsPolicy";
		private IHostingEnvironment _env;

		public Startup(IHostingEnvironment env)
		{
			_env = env;
			var builder = new ConfigurationBuilder()
				.SetBasePath(env.ContentRootPath)
				.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
				.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
				.AddEnvironmentVariables();
			Configuration = builder.Build();	
		}

		public IConfigurationRoot Configuration { get; }

		// This method gets called by the runtime. Use this method to add services to the container.
		public void ConfigureServices(IServiceCollection services)
		{            
			services.AddOptions();
			services.AddCors(setupAction =>
				setupAction.AddPolicy(CorsPolicy,
					builder => builder
					.AllowAnyOrigin()
					.AllowAnyMethod()
					.AllowAnyHeader()
					.AllowCredentials())
			);
			services.AddBusinessServices();
			services.AddConfigurations(Configuration);
			services.AddSignalR(options => options.JsonSerializerSettings.ContractResolver = new SignalRContractResolver());
			services.AddMvc();
		}

		// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
		public void Configure(IApplicationBuilder app, 
			IHostingEnvironment env, 
			ILoggerFactory loggerFactory,
			IApplicationLifetime appLifetime)
		{
			loggerFactory
				.AddConsole(Configuration.GetSection("Logging"))
				.AddDebug()
				.AddSerilog();

			app.
				UseCors(CorsPolicy).
				UseSignalR(routes =>
			{
				routes.MapHub<MyHub>(Constants.MyHubName);
			});
		}
	}
```

Here are the dependencies:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha1-final" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0" />
    <PackageReference Include="Serilog" Version="2.6.0-dev-00894" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.2" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.1-dev-00771" />
  </ItemGroup>
```

**Comment by Gurgen** [comment]
Try to remove UseSignalR and run, I think it's not a problem on Signal R part, exception was thrown from Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetry method

**Comment by Arash-Sabet** [comment]
@Gurgen @davidfowl Obviously including application insights causes issues with signalR. Removing it from the code helped us proceed. However, you guys need to address this. So, I'm going to keep this issue open until it's addressed. You can let me know to have it verified.

**Comment by davidfowl** [comment]
My guess is that it isn't a SignalR issue but a more general ASP.NET Core issue. Since you can't reproduce the problem anywhere but your IIS server it means it's something environmental. If you can help narrow it down that would be great but as of right now we have nothing to go on.

Can you dump the environment variables in the broken process to disk? I'd like to know what's causing app insights to be activated at all. Just adding a package shouldn't be enough to cause anything to happen.

**Comment by Arash-Sabet** [comment]
@davidfowl would you please give me your email address and I will forward you that info? Thanks.

**Comment by Arash-Sabet** [comment]
@davidfowl Let's put it in this way as a corrected explanation: we have explicitly removed app insights and the signalR worked. We put it back and the signalR app no longer worked due to that exception. So, I think the issue is that signalR and insights together cannot work when deployed to an IIS server.

**Comment by BrennanConroy** [comment]
And if you kept app insights in and removed signalr then your app would probably continue failing. There is no interaction between signalr and app insights that would cause this issue.

**Comment by Gurgen** [comment]
@Arash-Sabet I deployed my app to IIS with insights and SignalR and it works perfectly.

Remove from your app completely SignalR and check, is working your app on IIS?

**Comment by moozzyk** [comment]
Does not seem to be a SignalR issue and no follow up.
