### ISSUE TITLE
SignalR in embedded web browser control

### ISSUE THREAD

**Issue by budcribar** [aspnet/SignalR#953]
I have an embedded web-browser control and an embedded Kestrel server in a Windows application. The embedded control uses an older version of IE.  IE throws a syntax error when it hits "class Base64EncodedHubProtocol" when it loads Base64EncodedHubProtocol.js What do I need to do to fix this?
change  Base64EncodedHubProtocol.js  to  Base64EncodedHubProtocol.ts and re-compile targeting ES5?

**Comment by moozzyk** [comment]
Yes, IE does not support ES6 so you need to compile to ES5 (or use the ES5 version included in the dist/browser folder).

**Comment by budcribar** [comment]
I am also using Angular 4, so I tried setting the .angular-cli.json to:
"scripts": [
        "../node_modules/@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha1-final.js",
        "js/odometer.min.js",
        "js/scroller.min.js"
      ],

but somehow it gets mapped to loading Base64EncodedHubProtocol.js  from the src directory which is not ES5. I have no idea how "ng build" does this but the downloaded file (vendor.js) using the embedded web browser control or Internet Explorer 11 is different than if I download it using Edge or Chrome. Any suggestions?

**Comment by moozzyk** [comment]
Take a look at:
https://github.com/aspnet/SignalR/issues/729
https://github.com/angular/angular-cli/issues/7532
https://github.com/aspnet/SignalR/issues/867
and let me know if this helps.

**Comment by budcribar** [comment]
I included the client sources in my project so they would compile down to ES5 and it seems to work. Haven't tried to do "ng build --prod" yet. Not a great solution for those trying to support old browsers...

**Comment by moozzyk** [comment]
As per https://github.com/aspnet/SignalR/issues/867#issuecomment-331803584 it might be fixed soon in the Angular-cli
