### ISSUE TITLE
SignalR stops working when deploying the working app to Azure

### ISSUE THREAD

**Issue by Rishabh-V** [aspnet/SignalR#954]
Hey folks,

I wrote a simple SignalR demo app, which works fine in my dev box. But when published to Azure app, I get the following error. Any guidance to fix it ?
![errorsignalr](https://user-images.githubusercontent.com/15943060/30900446-a695453e-a381-11e7-8f31-0adf61ff0ea4.JPG)

signalr-client-1.0.0-alpha1-final.js:662 WebSocket connection to 'wss://testdecompression.azurewebsites.net/gameHub?id=1e90719e-8749-4805-b100-28a943ee6724' failed: Error during WebSocket handshake: Unexpected response code: 503
Promise @ signalr-client-1.0.0-alpha1-final.js:662

**Comment by moozzyk** [comment]
Did you enable webSockets in you Azure app service? As far as I remember webSockets are disabled by default.

**Comment by Rishabh-V** [comment]
@moozzyk 👍 That was indeed what I had missed. Thanks for the help. This issue was a false alarm, hence marking it as closed.

**Comment by fmonroe** [comment]
Took me a while to find this! That was indeed my problem. The client was getting 503. This fixed the issue.

**Comment by johnkwaters** [comment]
I have the same issue. Works locally, but not on Azure. 503.
I have enabled web sockets, as well as ARR and Always On.
Using 1.0.0-preview2-final for both server and angular client.
