### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by SSkovboiSS** [aspnet/SignalR#957]
Hi there

I'm developing a React Native mobile app and need a simple chat for it.  So i am interested in a way @aspnet/signalr-client can be integrated with React Native applications. And if not maybe, is there any workarounds? E. g. without using @aspnet/signalr-client.

**Comment by davidfowl** [comment]
What exactly is the problem?

**Comment by SSkovboiSS** [comment]
I've just setup sample project.

First thing is that msgpack5 depends on core node modules so seems like it's compatible with react-native only through special shim.

Secondly, when I've setup shim I ran into exception when trying to start connection:

Error
    at new HttpError (D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\@aspnet\signalr-client\dist\src\HttpError.js:6)
    at XMLHttpRequest.xhr.onerror (D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\@aspnet\signalr-client\dist\src\HttpClient.js:34)
    at XMLHttpRequest.dispatchEvent (D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\event-target-shim\lib\event-target.js:172)
    at XMLHttpRequest.setReadyState (D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\react-native\Libraries\Network\XMLHttpRequest.js:546)
    at XMLHttpRequest.__didCompleteResponse (D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\react-native\Libraries\Network\XMLHttpRequest.js:381)
    at D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\react-native\Libraries\Network\XMLHttpRequest.js:485
    at RCTDeviceEventEmitter.emit (D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\react-native\Libraries\EventEmitter\EventEmitter.js:181)
    at MessageQueue.__callFunction (D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:260)
    at D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:101
    at MessageQueue.__guard (D:\Programs\VSProjects\Empeek\kidscareapp-mobileapp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:228)

**Comment by SSkovboiSS** [comment]
Well I used http protocol for url, so got that error, but when I changed it anyway failed with "Cannot read property 'createElement' of undefined" in HttpConnection.resolveUrl.

**Comment by moozzyk** [comment]
I don't think msgpack5 does not depend on core node modules. It has its own Buffer implementation used when not running on node. 
You showed the stacktrace but did not show error message so hard to tell why you get the error.
If the url provided does not start with http:// or https:// the client is trying to [resolve](https://github.com/aspnet/SignalR/blob/9ecb6d1d583dc90e1c979488a73f8686b26522e3/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpConnection.ts#L169) it using `window.document` (after checking that document is defined)

**Comment by davidfowl** [comment]
@moozzyk maybe we should be detecting `window` and `window.document`

**Comment by SSkovboiSS** [comment]
Actually there is nothing quite useful in full error message:

err: Error at new HttpError (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:123814:124) at XMLHttpRequest.xhr.onerror (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:123883:28) at XMLHttpRequest.dispatchEvent (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:12244:35) at XMLHttpRequest.setReadyState (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:14016:18) at XMLHttpRequest.__didCompleteResponse (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13872:14) at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13967:45 at RCTDeviceEventEmitter.emit (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:11575:35) at MessageQueue.__callFunction (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:3813:42) at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:3654:15 at MessageQueue.__guard (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:3787:9)
    statusCode: 0
    stack: "Error↵    at new HttpError (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:123814:124)↵    at XMLHttpRequest.xhr.onerror (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:123883:28)↵    at XMLHttpRequest.dispatchEvent (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:12244:35)↵    at XMLHttpRequest.setReadyState (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:14016:18)↵    at XMLHttpRequest.__didCompleteResponse (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13872:14)↵    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13967:45↵    at RCTDeviceEventEmitter.emit (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:11575:35)↵    at MessageQueue.__callFunction (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:3813:42)↵    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:3654:15↵    at MessageQueue.__guard (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:3787:9)"
    __proto__:
        constructor: ƒ Error()
        message: ""
        name: "Error"
        toString: ƒ toString()
        __proto__: Object
__proto__: Object

**Comment by moozzyk** [comment]
@SSkovboiSS - can you post a repro?

**Comment by SSkovboiSS** [comment]
@moozzyk, excuse me I don't exactly understand, what do you need.

**Comment by moozzyk** [comment]
The problem is that the code you provided does not reproduce the issue by itself. I think there is a react native part to it (like a custom XHR if they have one). So, if you provided a minimal but complete repro it would speed up the investigation.

**Comment by muratg** [comment]
@SSkovboiSS A GitHub repo with the minimal app that reproduces this issue would be ideal I think.

**Comment by SSkovboiSS** [comment]
https://github.com/SSkovboiSS/SignalRReactNativeChat

**Comment by moozzyk** [comment]
I found a couple of issues that are causing the problem. First, you configured the client to connect to localhost. This won't work - the client runs on the device and localhost means the server on the device. But the server is not running on the device. If you debug the code where the error happens you will see: 

![image](https://user-images.githubusercontent.com/1438884/31097005-b43895b6-a772-11e7-9c4b-2e58d1a07967.png)

The problem with the client is that since the connection could not be made both `status` and `statusText` are `undefined` there is no useful error message. 

The second problem is that when you start your server you used `localhost` as the host name. This way the server only accepts requests from clients running locally. However, the emulator is basically a VM and is not running locally so, it can't connect to the server. After I changed the application url in [launchSettings.json](https://github.com/SSkovboiSS/SignalRReactNativeChat/blob/40dd50f682ac1933f203d0298e428cb50ffd8669/SignalRReactNativeChat/SignalRReactNativeChat/Properties/launchSettings.json#L24) to ` "applicationUrl": "http://*:10923/"` and changed the [URL](https://github.com/SSkovboiSS/SignalRReactNativeChat/blob/master/App.js#L17) in your client to `http://{ip}:10923/chat` I was able to talk to the server:
![image](https://user-images.githubusercontent.com/1438884/31097402-0b04c378-a774-11e7-853a-f1f6a6b7e42b.png)

**Comment by SSkovboiSS** [comment]
1.0.0-preview1-update1 not working with this repro.
I just updated SignalR packages on both .NET and RN projects. Also I followed your instructions on how to properly connect to API from simulator.

Unfortunately error is not quite helpfull.
https://i.imgur.com/w9qRmD7.png

**Comment by SSkovboiSS** [comment]
I was able to get more details while debugging:
https://i.imgur.com/OykP7tM.png

I tried to fix it by adding setRequestHeader call to DefaultHttpClient in signalr.js, like this:
`xhr.setRequestHeader('Content-Type', header);`

I used 'application/json' and 'text/html', but in both cases requests failed on timeout.
https://i.imgur.com/gwYXyDK.png

**Comment by Shhzdmrz** [comment]
This is my simple configuration for the chat app using React Native as a client and its working fine. ES5 code working with react native (not with simple javascript). Also an important thing is connection should be persistent when the app is in background and with ES5 code its also working for this case.

> My question is: **will it be (ES5 version of client) available in the released build of the SignalR?** Because I tried with the preview and it doesn't have the ES5 client code and simple javascript is not working with the React Native.

Here is my code: (In case if anyone needed for the basic configuration)
```JS
import React, { Component } from 'react';
import {
  Text,
  View
} from 'react-native';
import { HubConnection } from '@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha2-final.min.js';

const conn = new HubConnection('http://192.168.1.2:34078/Chat');

export default class App extends Component {
  componentDidMount(){
    conn.start()
        .then(() => { console.log("Connection Started"); conn.invoke("Send", "Some Message") })
        .catch(err => console.log("Unable to start Connection: " + err));
    conn.on("Send", message) =>  console.log(message);
  }

  render() {
    return (
      <View>  
        <Text>
          Welcome to React Native!
        </Text>
        <Text>
          To get started, edit App.js
        </Text>
      </View>
    );
  }
}
```

**Comment by anurse** [comment]
In the next release, all builds of the script will use ES5.
