### ISSUE TITLE
Manually disconnect clients from server

### ISSUE THREAD

**Issue by BirkOFH** [aspnet/SignalR#958]
Hi. Tell me how to proceed if I need to close the old connection from the server side.
This situation occurs when the user is authorized from another device. I need to close the old connection and use a new one.
This is a websocket connection.

**Comment by davidfowl** [comment]
With alpha1 you might be able to do it using:

```C#
Context.Connection.GetHttpContext().Abort();
```

This isn't very first class but in alpha2 you'll be able to do this:

```C#
Context.Connection.Abort();
```

**Comment by BirkOFH** [comment]
Thank you. The problem is different.
I need to close the first connection, and leave the last to work.
`Context.Connection.GetHttpContext().Abort();`
will close the current connection but I need an older one.

**Comment by davidfowl** [comment]
@BirkOFH are you storing connections server side? What code do you want to write?

**Comment by BirkOFH** [comment]
@davidfowl, I only store connectionId but it looks like this is not enough

**Comment by davidfowl** [comment]
Nope

**Comment by davidfowl** [comment]
Closing this
