### ISSUE TITLE
When can we expect the update in nuget?

### ISSUE THREAD

**Issue by Gurgen** [aspnet/SignalR#959]

**Comment by muratg** [comment]
What update are you referring to? 

An alpha version ASP.NET Core SignalR is up on NuGet for a couple of weeks: https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR/1.0.0-alpha1-final

**Comment by Gurgen** [comment]
I know about alpha1 update and use it in my projects. I mean, after that pre-release version update there are many good changes here (in git), but not updated nuget package.

**Comment by muratg** [comment]
Got it. We don't have an exact release date planned yet, but we hope to release an alpha2 relatively soon.

**Comment by Gurgen** [comment]
OK, thank you.
