### ISSUE TITLE
Add a public HttpConnection.ConnectionId

### ISSUE THREAD

**Issue by KPixel** [aspnet/SignalR#963]
Would it be ok to make the `ConnectionId` visible outside of `HttpConnection`?
Something like:
```C#
public string ConnectionId => _connectionId;
```

It could also be exposed through the `Features` property if you don't want to expose it directly like that.

Reason: When using the Sockets library, the client has no way of knowing its own ConnectionId.
I am working on a scenario where the client needs to send it to a notification service (think of it as a decentralized presence system).

**Comment by davidfowl** [comment]
No because the client will not always have the connection id. See https://github.com/aspnet/SignalR/issues/788#issuecomment-330796319 (and generally the overall thread about this)

**Comment by KPixel** [comment]
My bad. I didn't expect this issue to have already been discussed, so I didn't search for it.

I am going to continue this discussion here: #961.
