### ISSUE TITLE
nexpected token: name (Subject) UglifyJs

### ISSUE THREAD

**Issue by pieterlouw1974** [aspnet/SignalR#964]
When building production Angular app with 
node --max_old_space_size=5120 "node_modules\@angular\cli\bin\ng" b --prod

and this
this._hubConnection = new HubConnection('http://localhost:5000/somehub');
in my signalR Service i get the error:

ERROR in vendor.a57f00d9a885473089c7.bundle.js from UglifyJs
Unexpected token: name (Subject) [vendor.a57f00d9a885473089c7.bundle.js:53900,6]

without the line
 this._hubConnection = new HubConnection('http://localhost:5000/somehub');
It Build 100%

**Comment by davidfowl** [comment]
See https://github.com/aspnet/SignalR/issues/867#issuecomment-329114305

**Comment by pieterlouw1974** [comment]
What i did to get it working
tsconfig.app.json
{
"compilerOptions": {
"sourceMap": true,
"declaration": false,
"moduleResolution": "node",
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"lib": [
"es2017",
"dom"
],
"outDir": "../out-tsc/app",
"target": "es6",
"module": "es2015",
"baseUrl": "",
"types": []
},
"exclude": [
"test.ts",
"**/*.spec.ts"
]
}

tsconfig.jason
{
"compileOnSave": false,
"compilerOptions": {
"outDir": "./dist/out-tsc",
"baseUrl": "src",
"sourceMap": true,
"declaration": false,
"moduleResolution": "node",
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"target": "es6",
"typeRoots": [
"node_modules/@types"
],
"lib": [
"es2017",
"dom"
]
}
}

package,jason
"devDependencies": {
"": "1.5.0-beta.1",
"": "4.4.4",

angular 4.4.4
