### ISSUE TITLE
Thounds of threads call System.Threading.WaitHandle.WaitOne

### ISSUE THREAD

**Issue by karelz** [aspnet/SignalR#965]
_From @anthonywanted on September 27, 2017 3:14_

Our application running a signalR server and thrift server. While it runs 2 days or more, it use cpu 100% and threads count up to thounds, just suddenly. 
I dump a core dump, and run sos EEStack, thounds of threads stack looks like this
![image](https://user-images.githubusercontent.com/26265122/30893942-66942e36-a373-11e7-80db-83aef70e0e2e.png)

Here is the zabbix graphs
![image](https://user-images.githubusercontent.com/26265122/30894354-e4bbbf84-a375-11e7-8bd6-f928eb3069c8.png)
![image](https://user-images.githubusercontent.com/26265122/30894370-fae14f4a-a375-11e7-9ecb-a5dd4f719d9c.png)

Here is the code, core dump is showing some problem in 
`cancelTokenSource.Token.WaitHandle.WaitOne();`

    public class AccessServer
    {
        private ILogUtility logger = LogFactory.Create(typeof(AccessServer));

        private CancellationTokenSource cancelTokenSource = new CancellationTokenSource();

        protected IWebHost webHost;

        public void Run()
        {
            try
            {
                var settings = ConfigurationUtility.GetSettings<Settings>("appsettings");
                var commonSettings = ConfigurationUtility.GetSettings<CommonSettings>("commonsettings");
                string serviceName = typeof(IAccessService).GetThriftServiceName();
                int port = settings.ThriftPorts[serviceName];

                StartupService.Current
                .LoadAllAssemblyInBaseDirectory()
                .UseAutofac()
                .RegisterMapper()
                .InitStartupTask()
                .InitUpstreamMessageManager()
                .Start();

                webHost = new WebHostBuilder()
                    .UseKestrel(o => { })
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseStartup<Startup>()
                    .UseUrls(settings.LocalServer)
                    .Build();

                webHost.Start();
                $"SignalR running on {settings.LocalServer}".WriteInfoLog();
                StartupService.Current.StartThriftServices(commonSettings.LocalServerIP, port, cancelTokenSource,
                   new List<(Type Type, string ServiceName, string ServiceNameConfig)>() { (typeof(IAccessService), $"{serviceName}-{commonSettings.LocalServerIP.Replace(".", "-")}-{port}", serviceName) });

                cancelTokenSource.Token.WaitHandle.WaitOne();
            }
            catch (Exception ex)
            {
                logger.Error($"Access run error：{ex.Message}", ex);
            }
        }
    }

environment is docker(17.06.0-ce, build 02c1d87) using dotnet image (dotnet:v1.1 runtime) running on centos 7.2(kernel 3.10.0-327.el7.x86_64)

_Copied from original issue: dotnet/corefx#24278_

**Comment by karelz** [comment]
_From @danmosemsft on September 27, 2017 17:23_

@anthonywanted I'm not familiar with SignalR (this is the CoreFX repo, not the SignalR repo) but if you are seeing many callstacks with Main->Run then that would mean your Main() is calling Run() on many threads.  (Each thread is then launching this service, then waiting on it.) Is that what you expect?

**Comment by moozzyk** [comment]
What version of SignalR is that? I don't see any SignalR related code in the provided code fragment.

**Comment by anthonywanted** [comment]
@karelz 
I just call Run in Program.cs
![image](https://user-images.githubusercontent.com/26265122/30998023-59d9c2be-a4fe-11e7-888e-3b53b3ce67da.png)
![image](https://user-images.githubusercontent.com/26265122/30998026-61d1e280-a4fe-11e7-807d-5845bf394cbe.png)

@moozzyk 
https://github.com/aspnet/SignalR-Server.git
https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR.Server
this version, but it seems like be removed..

I changed my code like this and i hope it can help
public class AccessServer
    {
        private ILogUtility logger = LogFactory.Create(typeof(AccessServer));

        private CancellationTokenSource cancelTokenSource = new CancellationTokenSource();

        protected IWebHost webHost;

        public void Run()
        {
            try
            {
                var settings = ConfigurationUtility.GetSettings<Settings>("appsettings");
                var commonSettings = ConfigurationUtility.GetSettings<CommonSettings>("commonsettings");
                string serviceName = typeof(IAccessService).GetThriftServiceName();
                int port = settings.ThriftPorts[serviceName];

                StartupService.Current
                .LoadAllAssemblyInBaseDirectory()
                .UseAutofac()
                .RegisterMapper()
                .InitStartupTask()
                .InitUpstreamMessageManager()
                .StartThriftServices(commonSettings.LocalServerIP, port, cancelTokenSource,
                   new List<(Type Type, string ServiceName, string ServiceNameConfig)>() { (typeof(IAccessService), $"{serviceName}-{commonSettings.LocalServerIP.Replace(".", "-")}-{port}", serviceName) })
                .Start();

                webHost = new WebHostBuilder()
                    .UseKestrel(o => { })
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseStartup<Startup>()
                    .UseUrls(settings.LocalServer)
                    .Build();

                if (!cancelTokenSource.IsCancellationRequested)
                {
                    $"SignalR running on {settings.LocalServer}".WriteInfoLog();
                    webHost.Run();
                }

                #region core dump
                // so many thread see this so stop using WaitOne()
                //Thread   1
                //TEB information is not available so a stack size of 0xFFFF is assumed
                //Current frame: libpthread.so.0!__pthread_cond_wait + 0xbf
                //Child - SP         RetAddr Caller, Callee
                //00007FFD47F6FC70 00007ffd47f701a0 00007ffd47f701a0
                //00007FFD47F6FC98 00007f49b011894d(MethodDesc 00007f49afd5ab90 + 0x1d System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean)), calling 00007f4a298a77d0(stub for System.Threading.WaitHandle.WaitOneNative(System.Runtime.InteropServices.SafeHandle, UInt32, Boolean, Boolean))
                //                    00007FFD47F6FCA8 00007ffd47f6fc70 00007ffd47f6fc70
                //00007FFD47F6FD90 00007f49b011894d(MethodDesc 00007f49afd5ab90 + 0x1d System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean)), calling 00007f4a298a77d0(stub for System.Threading.WaitHandle.WaitOneNative(System.Runtime.InteropServices.SafeHandle, UInt32, Boolean, Boolean))
                //                    00007FFD47F6FDB0 00007f49b011881f(MethodDesc 00007f49afd5ab58 + 0x2f System.Threading.WaitHandle.WaitOne(Int32, Boolean)), calling(MethodDesc 00007f49afd5ab90 + 0 System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean))
                //00007FFD47F6FDE0 00007f49b06206b8(MethodDesc 00007f49afb66640 + 0x5a8 VIP.OA.IM.AccessServer.AccessServer.Run())
                //00007FFD47F6FEE0 00007f49b05ea4aa(MethodDesc 00007f49afb65b28 + 0x2a VIP.OA.IM.AccessServer.Application.Program.Main(System.String[])), calling 00007f49b05ea0a0(stub for VIP.OA.IM.AccessServer.AccessServer.Run())
                //                    00007FFD47F700D0 00007ffd47f701a0 00007ffd47f701a0
                //00007FFD47F70178 00007ffd47f705b0 00007ffd47f705b0
                //00007FFD47F701A0 00007ffd47f705b0 00007ffd47f705b0
                //00007FFD47F70540 00007ffd47f705b0 00007ffd47f705b0
                #endregion
                // 
                //cancelTokenSource.Token.WaitHandle.WaitOne();
            }
            catch (Exception ex)
            {
                logger.Error($"access server run with error：{ex.Message}", ex);
            }
        }
    }

**Comment by davidfowl** [comment]
Sorry, that version of SignalR isn't supported.

**Comment by moozzyk** [comment]
SignalR-Server was never officially released and is not supported. We[ released an alpha version of SignalR for Asp.NET Core](https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/) a couple weeks ago and if you see similar problems with the new version we will investigate.

**Comment by anthonywanted** [comment]
Dose this version of SignalR support Android(java)/iOS(object-c)? My client is Android/iOS app.
The reason I use this version is that it use old interfaces such as dotnet framework version support and it is running in dotnet core. 

Thanks!

**Comment by davidfowl** [comment]
No it doesn't support the existing clients. This version has a newer protocol and we don't have new versions of the Java and iOS client. 

There are no plans to support the version of SignalR you are running.

**Comment by anthonywanted** [comment]
@davidfowl 
Is there any plans to support Java/iOS client with the latest version of SignalR?

**Comment by davidfowl** [comment]
> Is there any plans to support Android/iOS client with the latest version of SignalR?

Yes we plan to write a swift and android compatible clients. We're still alpha right now but the plan is to have clients for:

- C# (.NET Standard 2.0 platforms including xamarin etc)
- Android (either written in Kotlin or java)
- iOS (swift client)
- Typescript/javascript/nodejs

> If it needs a long time to support, is there any way to implement real-time communication with Android/iOS simply like SignalR?

I'm not sure what you're asking

**Comment by anthonywanted** [comment]
@davidfowl 
Thanks a lot!
