### ISSUE TITLE
Self-JS Client On Remote IIS

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [aspnet/SignalR#967]
It's probably something dumb, but I've seem to hit some sort of strange block.

Cross Application:
localhost C# client to localhost C# server - Good
localhost C# to remote C# server - Good

Self-Host/View (e.g. I'm viewing the currently connected user list across all applications connected)
localhost JS client to localhost C# server (self - view on localmachine)- Good
remote JS client to remote C# server (self - view on server)- Good
**remote JS client to remote C# server (self - view on another machine on the network)- Bad**

Hosting on IIS 7.5.

The part I'm not understanding is the the same code works in all cases except one.

In console I get like:
"Information: SSE connected to http://**mylocaldns**l/v1/sync?id=4abb1002-9f56-492d-9a8c-433a707b0a3a"  signalr-client-1.0.0-alpha1-final.min.js:1:11373
Closed  connections.js:44:3
Error: Error occurred
Stack trace:
connect/</c.onerror@http://**mylocaldns**/js/signalr/signalr-client-1.0.0-alpha1-final.min.js:1:14017
  connections.js:45:9
XML Parsing Error: syntax error
Location: http://**mylocaldns**/v1/sync?id=4abb1002-9f56-492d-9a8c-433a707b0a3a
Line Number 1, Column 1:  sync:1:1
Error: Not Found

200 for options to /v1/sync
200 for get to /v1/sync?id=4abb1002-9f56-492d-9a8c-433a707b0a3a
404 for post to /v1/sync?id=4abb1002-9f56-492d-9a8c-433a707b0a3a (sending {"protocol":"json"})

Then it's dead.

The code is pretty basic:

```
    var options = {
        transport: signalR.TransportType.ServerSentEvents,
        protocol: "json",
        logging: signalR.LogLevel.Trace
    };
    var http = new signalR.HttpConnection('http://**mylocaldns**/v1/sync', options);
    var connection = new signalR.HubConnection(http);
...

    connection.onClosed = (e) => {
        console.log("Closed");
        console.log(e);
    };

connection.start().then(() => {
      //does stuff
    });
```

Any help is appreciated - thanks!

**Comment by moozzyk** [comment]
Can you try using unminified version of the client? Can you turn on logging on the server and check if you see any exceptions?

**Comment by moozzyk** [comment]
I did not see 404 for the message with the protocol - do you do anything special between get and post (e.g. debug your code)? I think the server will remove the connection when there is no {protocol:"json"} message within 5 seconds after sending OPTIONS and 404 means that the connection is not there. Or, if you are using load balancing the request went to a different server than the one OPTIONS request was sent to.

**Comment by OpenSpacesAndPlaces** [comment]
@moozzyk 

Unminified js is the same result - dying and throwing to 'eventSource.onerror'.
Otherwise I don't seem to get a server exception (request trace below).

Nothing special about the setup that I'm aware - fairly boilerplate single server.

What makes no sense to me, unless console/net is lying, is that the first couple requests connect and It explicitly says:

`"Information: SSE connected to http://mydns/v1/sync?id=4f79b147-de02-471b-9c72-209e076f6118`



```
  eventSource.onerror = (e) => {
                    reject();
                    // don't report an error if the transport did not start successfully
                    if (this.eventSource && this.onClosed) {
                        this.onClosed(new Error(e.message || "Error occurred"));
                    }
                };
```


```

          "Information: SSE connected to http://mydns/v1/sync?id=4f79b147-de02-471b-9c72-209e076f6118"  signalr-client-1.0.0-alpha1-final.min.js:1:11373
Closed  connections.js:44:9
Error: Error occurred
Stack trace:
connect/</c.onerror@http://mydns/js/signalr/signalr-client-1.0.0-alpha1-final.min.js:1:14017
  connections.js:45:9
XML Parsing Error: syntax error
Location: http://mydns/v1/sync?id=4f79b147-de02-471b-9c72-209e076f6118
Line Number 1, Column 1:  sync:1:1
Error: Not Found

```

```
infoinfo: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 OPTIONS http://mydns/v1/sync  
: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 OPTIONS http://mydns/v1/sync  
infoinfo: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3666ms 200 application/json
: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3666ms 200 application/json
infoinfo: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://mydns/v1/sync?id=4f79b147-de02-471b-9c72-209e076f6118  
: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://mydns/v1/sync?id=4f79b147-de02-471b-9c72-209e076f6118  
infoinfo: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 5002.7529ms 200 text/event-stream
: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 5002.7529ms 200 text/event-stream
infoinfo: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://mydns/v1/sync?id=4f79b147-de02-471b-9c72-209e076f6118 text/plain;charset=UTF-8 20
: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://mydns/v1/sync?id=4f79b147-de02-471b-9c72-209e076f6118 text/plain;charset=UTF-8 20
infoinfo: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.2834ms 404 
: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.2834ms 404 
```

**Comment by moozzyk** [comment]
It seems that the connection was closed:
```
: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 5002.7529ms 200 text/event-stream
```
and then the client tried to send a message:
```
: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://mydns/v1/sync?id=4f79b147-de02-471b-9c72-209e076f6118 text/plain;charset=UTF-8 20
```
This failed since the client closed the connection the connection was not there so the server returned 404. 

Can you show your client code - the snippets you provided don't show full picture (e.g. I don't see any place where the connection is being stopped)? If you are not stopping the connection anywhere - can you try using https? Also, setting log level to Trace on the server side might give some additional details.

btw. you have duplicate console logging so you likely are hitting this issue: https://github.com/aspnet/MetaPackages/issues/162. Remove extraneous `.AddConsole()` call from your `Main()` (or wherever you build the host)

**Comment by OpenSpacesAndPlaces** [comment]
The full code of this is fairly short/simple  - not much more then I posted already:

```
var fStart = function () {
    var options = {
        transport: signalR.TransportType.ServerSentEvents
        ,protocol: "json"
        //,logging: signalR.LogLevel.Trace
    };
    var http = new signalR.HttpConnection(document.location.protocol + '//' + document.location.host + '/v1/sync', options);
    var connection = new signalR.HubConnection(http);

    connection.on('Connections',
        (message) => {

        //append current list of connections to page

        });

    connection.onClosed = (e) => {
        console.log("Closed");
        console.log(e);
    };


    connection.start().then(() => {

  //Join the group the connection list is publishing too
        connection.invoke('Join', "Dashboard");
    });
}
fStart();
```

> If you are not stopping the connection anywhere - can you try using https?

There's no code to do a  forced stop - when/where it's dying is as it happens.
Currently don't have a location with a cert I can deploy to at the moment (just on local dev server)


Thanks for the tip on the logger - here is the slightly cleaner more verbose output:

```
: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL893V4M3UVG" completed keep alive response.
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL893V4M3UVH" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 16.4496ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 18.5525ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 OPTIONS http://mydns/v1/sync  
dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name '(null)' and template 'v1/sync'.
dbug: Microsoft.AspNetCore.Sockets.ConnectionManager[0]
      10/01/2017 18:57:28: ConnectionId f76a3b7e-99b0-4262-87d4-765f69729ec5: New connection created.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://mydns/favicon.ico  
dbug: Microsoft.AspNetCore.Builder.RouterMiddleware[1]
      Request did not match any routes.
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[5]
      The request path /favicon.ico does not match an existing file
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL893V4M3UVG" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.2881ms 200 
dbug: Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher[8]
      10/01/2017 18:57:28: Connection Id f76a3b7e-99b0-4262-87d4-765f69729ec5: Sending negotiation response.
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL893V4M3UVH" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 351.8545ms 200 application/json
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://mydns/v1/sync?id=f76a3b7e-99b0-4262-87d4-765f69729ec5  
dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name '(null)' and template 'v1/sync'.
dbug: Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher[3]
      10/01/2017 18:57:28: Connection Id f76a3b7e-99b0-4262-87d4-765f69729ec5, Request Id 0HL893V4M3UVG:00000005: Establishing new connection.
dbug: Microsoft.AspNetCore.SignalR.HubEndPoint[0]
      Negotiate was canceled.
dbug: Microsoft.AspNetCore.Sockets.ConnectionManager[1]
      10/01/2017 18:57:34: ConnectionId f76a3b7e-99b0-4262-87d4-765f69729ec5: Removing connection from the list of connections.
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL893V4M3UVG" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 5356.7185ms 200 text/event-stream
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://mydns/v1/sync?id=f76a3b7e-99b0-4262-87d4-765f69729ec5 text/plain;charset=UTF-8 20
dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name '(null)' and template 'v1/sync'.
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL893V4M3UVH" completed keep alive response.
dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      Connection id "0HL893V4M3UVH", Request id "0HL893V4M3UVH:00000003": started reading request body.
dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      Connection id "0HL893V4M3UVH", Request id "0HL893V4M3UVH:00000003": done reading request body.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 12.3773ms 404 
```

**Comment by moozzyk** [comment]
It seems that the client never sent the initial negotiation message. 

```
dbug: Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher[8]
      10/01/2017 18:57:28: Connection Id f76a3b7e-99b0-4262-87d4-765f69729ec5: Sending negotiation response.
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL893V4M3UVH" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 351.8545ms 200 application/json
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://mydns/v1/sync?id=f76a3b7e-99b0-4262-87d4-765f69729ec5  
dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name '(null)' and template 'v1/sync'.
dbug: Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher[3]
      10/01/2017 18:57:28: Connection Id f76a3b7e-99b0-4262-87d4-765f69729ec5, Request Id 0HL893V4M3UVG:00000005: Establishing new connection.
dbug: Microsoft.AspNetCore.SignalR.HubEndPoint[0]
      Negotiate was canceled.
dbug: Microsoft.AspNetCore.Sockets.ConnectionManager[1]
      10/01/2017 18:57:34: ConnectionId f76a3b7e-99b0-4262-87d4-765f69729ec5: Removing connection from the list of connections.
```

`Establishing new connection` tells me that the client opened connection for (what I assume) event-stream but then `Negotiate was canceled` means that either the connection was closed before the client was able to send this message, or the client did not send the message within 5 seconds (this should not happen in general unless there is a network related issue - the client sends this message immediately after the transport was able to open the connection to the server).

I tried your code and could not repro the issue. The problem might be some network device between the client and the server. Can you try a different transport and see if this code still fails the same way? Can you try using https to make sure nothing is interfering with the request?

**Comment by OpenSpacesAndPlaces** [comment]
> The problem might be some network device between the client and the server.

What's weird is I have no problems in the C# client case. 
e.g. C# SSE localhost to/from http://mydns/v1/sync 

From the same machine I can't use the JS SSE client on http://mydns to/from http://mydns/v1/sync.

From a network topology standpoint, maybe I'm incorrect in that assertion - it should be the same thing.

> Can you try a different transport and see if this code still fails the same way?

To make this more confusing if I change the JS Client Transport, It works fine:
`signalR.TransportType.LongPolling`

I'm unable to try websockets since this is hosted on II7.5 at the moment.

--

Worst case I can use LongPolling and move on, but I was hoping there was a way to track down what was causing the JS SSE Client to fail.

Would there be any specific spots in "signalr-client-1.0.0-alpha1-final.js" to add some breaks/console logs that might tickle more useful information out?

Thankss for your continued help.

**Comment by moozzyk** [comment]
Someone is [seeing](https://github.com/aspnet/SignalR/issues/986#issuecomment-334644638) a similar issue. I wonder if you are using any kind of authentication on the server side? Also, have you tried skipping IIS (i.e. connecting directly to Kestrel), have you tried different browsers and you had the same behavior regardless of the browser?

**Comment by OpenSpacesAndPlaces** [comment]
>  I wonder if you are using any kind of authentication on the server side? 

The code doesn't utilize any authentication at the moment.

> Also, have you tried skipping IIS (i.e. connecting directly to Kestrel), 

I have not tried direct to Kestrel - though I'm not sure I'd have a way to-do that in the current test environment that would be mimic the IIS configuration/server location unless you know of a way to bind a local DNS record to a kestrel instance directly.

> have you tried different browsers and you had the same behavior regardless of the browser?

I had tried Edge, Chrome, FireFox - same result in each using SSE.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
