### ISSUE TITLE
Manually Resolved IHubContext<T> is not functioning correctly.

### ISSUE THREAD

**Issue by csafg2** [aspnet/SignalR#972]
i have scenario where i need to access Hub clients from a static class so i tried resolving an instance of HubContext this way:

    `public class Startup
     {
        public static ServiceProvider Provider { get; private set; }

        public void ConfigureServices(IServiceCollection services)
        {
            // other stuff
            services.AddSignalR();

            Provider = services.BuildServiceProvider();
        }
    }`

**and in the static class:**

` var chatHub = Startup.Provider.GetService<IHubContext<Chat>>();
chatHub.Clients.All.InvokeAsync("Send", "Hellow folks").Wait();`

chatHub instance is correctly instantiated but calling InvokeAsync dose not really do anything with the clients. (note that asking to inject  to IHubContext<THub> to controller or similar objects works just fine).

asp.net Core 2.0
sdk version: 2.0
signalr version: 1.0.0-alpha1-final

Thanks in advance

**Comment by dangshui** [comment]
I have the same problem. and i found the IHubContext<T> _connections count is 0, so when i invoke a client method in server, client will not receive this invoke command.
What is the recommended way to push data to clients?

**Comment by davidfowl** [comment]
That code is incorrect. You can't build the service provider yourself if you don't return it to the system. You essentially have 2 service providers, your own world and the world that ASP.NET Core knows about. If you *must* use a static then I'd recommend storing the `ApplicationServices` on the `IApplicationBuilder`. 

```C#
public class Startup
 {
    public static ServiceProvider Provider { get; private set; }

    public void ConfigureServices(IServiceCollection services)
    {
        // other stuff
        services.AddSignalR();
    }
    
    public void Configure(IApplicationBuilder app)
    {
          Provider = app.ApplicationServices;
    }
}
```

Re-evaluate if you truly need to use a static or if you can just inject the `IHubContext<THub>` into the appropriate class.

**Comment by csafg2** [comment]
@davidfowl Thanks, it`s working now.

i guess it`s the only way to access hub clients from a background service that is not part of asp.net. 
(i have a back ground service that generates notifications)

**Comment by davidfowl** [comment]
> i guess it`s the only way to access hub clients from a background service that is not part of asp.net.
(i have a back ground service that generates notifications)

It really just depends on where things start up. If it's outside of the ASP.NET Core universe then sure, if the background service is part of the DI container and it starts up as part of the ASP.NET Core application then there's probably a better way.
