### ISSUE TITLE
NodeInvocationException: Uncaught (in promise): ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by Yatajga** [aspnet/SignalR#973]
Hello,

I'm using the standard ASP.NET Core 2.0 Angular Project in VS 2017 (Version 15.3.5) with ASP.NET Core SignalrR 1.0.0-alpha1-final. When I try to start connection, I'm getting the following error: NodeInvocationException: Uncaught (in promise): ReferenceError: XMLHttpRequest is not defined
ReferenceError: XMLHttpRequest is not defined, When I comment this.start() ( in startConnection() )method, everything works fine. An I'm able to start connection. Please see this video for more details.

https://1drv.ms/v/s!AvVA6SUKWG9zkb0uwaP81fbUPnamsQ

```
import { Inject, Injectable} from '@angular/core';
import { HubConnection } from '@aspnet/signalr-client'
import { Observable } from 'rxjs/Observable';
import { ReplaySubject } from 'rxjs/ReplaySubject';
import { Product } from './product'

//declare var $: any;

@Injectable()
export class ProductsSignalRService {

    //private proxy: any;
    //private connection: any;
    //public connectionExists: Boolean;

    private productMessageHub: HubConnection;

    private addObservable: ReplaySubject<Product>;
    private removeObservable: ReplaySubject<number>;

    public productAddedEvent = ()=> this.addObservable.asObservable();

    constructor( @Inject('BASE_URL') private baseUrl: string) {
        console.log(baseUrl);

        let url = baseUrl + 'ProductMessageHub';

        this.productMessageHub = new HubConnection(url);
        this.removeObservable = new ReplaySubject<number>();
        this.addObservable = new ReplaySubject<Product>();
    }

    public startConnection(): void {
        this.start();
    }

    private start() {
        this.productMessageHub.start().then(
            () => {
                console.log('Connected !!!');

                this.productMessageHub.on('ProductRemoved',
                    (data: any): void => {
                        let productId = data as number;
                        this.productRemoved(productId);
                    });

                this.productMessageHub.on('ProductAdded',
                    (data: any): void => {
                        let product = data as Product;
                        this.productAdded(product);
                    });
            }
        );
    }

    public addProduct(product: Product) {
        this.productMessageHub.invoke('addProduct', product);
    }

    public saveProduct(product: Product) {
        this.productMessageHub.invoke('saveProduct', product);
    }

    public removeProduct(productId: number): Observable<number> {
        this.productMessageHub.invoke('removeProduct', productId);

        return this.removeObservable.asObservable();
    }

    private productAdded(product: Product): void {
        this.addObservable.next(product);
    }

    public productRemoved(productId: number): void {
        this.removeObservable.next(productId);
    }
}
```

**Comment by moozzyk** [comment]
You need to provide an XmlHttpRequest polyfill. I happened to write a [post](https://blog.3d-logic.com/2017/10/01/the-signalr-for-asp-net-core-javascript-client-part-2-outside-the-browser/) on using the JavaScript client in NodeJS which shows how to do that.

**Comment by davidfowl** [comment]
@moozzyk I'm not sure it's that simple. This looks like its failing because of the pre-rendering support in JavascriptServices.

/cc @SteveSandersonMS

**Comment by Yatajga** [comment]
Thank you for the comments. 

> You need to provide an XmlHttpRequest polyfill - ok will try, but why it works the second time in case when I didn't add anything?

If mentioned polyfills is required for the SignalR package why it doesn't include in the npm package?

**Comment by SteveSandersonMS** [comment]
@Yatajga Do you definitely want to be using the SignalR client during server-side prerendering? What do you want it to do during prerendering?

I would have thought that it only makes sense to use the SignalR client when the application is running on the client. If that is the case, you should avoid making calls into SignalR during prerendering.

To distinguish between running in a browser versus in a Node environment (e.g., during prerendering), you can use logic like this:

```
if (typeof window !== 'undefined') {
    // code that only runs in the browser
} else {
    // code that only runs in Node (e.g., during prerendering)
}
```

**Comment by Yatajga** [comment]
@SteveSandersonMS Thank you for the response! 

No, I do not need to run SignalR client during the prerendering process. 

> I would have thought that it only makes sense to use the SignalR client when the application is running on the client. If that is the case, you should avoid making calls into SignalR during prerendering.

You are completely right, that is what I want (run application on the client). At the same time I try to understand where/when/why prerending process call this method. As I know ngOnInit() is called at runtime, am I wrong? 

> What do you want it to do during prerendering?

This is the simple application to investigate all new features of the new version of SignaR. I do not trying to do extra steps. I just included the SignalR package and try to try it.  In the real application I want to have small footprint of all client assets.

**Comment by SteveSandersonMS** [comment]
> As I know ngOnInit() is called at runtime, am I wrong?

It is called at runtime, which includes prerendering. Prerendering is just starting up your app, running it until it stops doing anything, then rendering its UI as an HTML string from that state.

**Comment by Yatajga** [comment]
Ok, Thank you!

**Comment by SteveSandersonMS** [comment]
Great, closing as resolved (unless @davidfowl you think something needs to be changed to make the SignalR client automatically skip execution when running in Node).

**Comment by moozzyk** [comment]
@SteveSandersonMS - signalr client [can run in Node](https://blog.3d-logic.com/2017/10/01/the-signalr-for-asp-net-core-javascript-client-part-2-outside-the-browser/) in general so we don't want to skip execution.

**Comment by RGVGreatCoder** [comment]
I also get the error "NodeInvocationException: Uncaught (in promise): ReferenceError: XMLHttpRequest is not defined" even after removing all the signalr code in my Angular application and just leaving the library installed (that is, still in my package.json file), After uninstalling the library, my Angular app ran well again.

Where is the best place to create the HubConnection() object and run On(), Start() and Invoke() methods if not on the OnInit Angular method? Is there any Angular sample code? :-\

**Comment by Yatajga** [comment]
@RGVGreatCoder you can use [this example](https://code.msdn.microsoft.com/The-ASPNET-vNext-Real-Time-b1d27fe4?redir=0).
