### ISSUE TITLE
HubConnection onClosed event not fired on JS client

### ISSUE THREAD

**Issue by pacodp** [aspnet/SignalR#974]
I'm writing a reconnect code to keep alive the hub connection. I was using @aspnet/signalr-client 1.0.0-alpha2-27049 and it was working. Somehow the HubConnection onClosed event was called several times (once every minute 4 times) and then the connection seemed to get stable.

With the new versions of the js client (1.0.0-alpha2-27146 to 1.0.0-alpha2-27174) onClosed event is not being fired. I keep the browser inactive for some minutes, then when I try to make an invoke on the HubConnection I get the next error:

```
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State
    at HttpConnection.send (HttpConnection.js:98)
    at Promise (HubConnection.js:168)
    at new Promise (<anonymous>)
    at HubConnection.invoke (HubConnection.js:152)
    at Channel.componentDidUpdate (Channel.js:432)
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponent.js:726
    at CallbackQueue.notifyAll (CallbackQueue.js:74)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:78)
    at ReactReconcileTransaction.closeAll (Transaction.js:207)
```

The hub was connected previously as I can see the websocket connected log:
```
Information: WebSocket connected to wss://...
```

The connected state changed to 3 (disconnected) but the onClosed event didn't get called.

**Comment by pacodp** [comment]
I've found the signalr-client 1.0.0-alpha1-final on npm feed (https://www.npmjs.com/package/@aspnet/signalr-client) and it works.

**Comment by moozzyk** [comment]
I think this is because event names were [renamed](https://github.com/aspnet/SignalR/commit/20d4d70cc7ceaae976c478cde0c6ae59946dce3d) in alpha2. It is now `onclose`. When we ship alpha2 we will describe changes to API.
