### ISSUE TITLE
JS client may not give an error if sending an HTTP request fails

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#976]
See: https://github.com/aspnet/SignalR/issues/957#issuecomment-333652247

In ReactNative the client was not able to connect to the server at all and the Error message was empty because both `status` and `statusCode` were `undefined`. It appears however that XmlHttpRequest contains a useful error message which we should include in the Error.

**Comment by muratg** [comment]
We'll reopen if someone still observes.

**Comment by moozzyk** [comment]
It was just observed: https://github.com/aspnet/SignalR/issues/957#issuecomment-371947683

**Comment by anurse** [comment]
I'm a little confused. In the linked example, the error message is in the `response` property. I don't think we should be expecting to read an error out of that field, particularly if `statusCode` isn't defined. This seems like a bug in the implementation of XHR.
