### ISSUE TITLE
Remove ProtoBuf from SignalR Hub Protocol spec

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#978]
We're not doing it for v1 (doing MsgPack for binary instead). We can always get it back from older versions when we are ready to add it and I want to make sure the spec is clear.

/cc @davidfowl @BrennanConroy @moozzyk 

(The only reason this is an issue and not just a PR is that @BrennanConroy has a PR out for spec updates and I don't want to conflict)

**Comment by moozzyk** [comment]
It was not removed because we were thinking about creating ProtoBuf HubProtocole as a sample.

**Comment by anurse** [comment]
But would it be part of the official set of protocols? I just want to make sure it stays clear that it is not officially supported at the moment. And we can always pull it from source control history ;)

**Comment by davidfowl** [comment]
Lets not remove it just yet

**Comment by Suvarnnan** [comment]
when Protobuff HubProtocol will become available .Right now , we could see a sample SocialWeather and it has protobuff protocol usage .Is this a right sample about Protobuff usage in SignalR??

**Comment by anurse** [comment]
There are no plans for Protobuf in SignalR, we decided to use MsgPack instead because Protobuf requires that the application developer provide a schema for every Hub call. The API is extensible (via `IHubProtocol`) though so it would be possible to implement it yourself.

The SocialWeather sample provides an example of how to use a custom protocol with the lower-level Endpoints API, it isn't using the higher level SignalR Hub API.
