### ISSUE TITLE
Client transport exception handling

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#98]
We need robust testing of exceptions in the client transports. There are a background tasks running and we need to make sure that exceptions properly shut down the background tasks **and** report the error to user code.

**Comment by anurse** [comment]
Has this been taken care of?

**Comment by muratg** [comment]
@anurse we thought it was, but perhaps not :)

**Comment by moozzyk** [comment]
I added coverage for the LongPollingTransport (the only one we currently have).

**Comment by anurse** [comment]
Ok, that sounds good then. I'm fine to close it, I just saw that the only PR it was associated with was unrelated and wanted to make sure we didn't miss it :).
