### ISSUE TITLE
Likely stable release date for 1.0.0

### ISSUE THREAD

**Issue by dubs999** [aspnet/SignalR#982]
Hey there

We're really interested in integrating with the aspnet core version of Signal R. Unfortunately due to company politics we wont be able to build the alpha release into our product.

Does the team have a release date/milestone in mind? Would be great to know if a build would likely be ready by the end of this year.

Many thanks

**Comment by moozzyk** [comment]
The stable release will be released with ASP.NET Core 2.1 which is [planned](https://github.com/aspnet/Home/wiki/Roadmap) for Q1/Q2 next year.

**Comment by KANekT** [comment]
@moozzyk you planed Next PreRelease 2.1.0-preview1 or 1.0.0-alpha3?

**Comment by moozzyk** [comment]
We are planning to ship the next preview as part of ASP.NET Core 2.1.0 preview1
