### ISSUE TITLE
SignalR Scaleout with Redis

### ISSUE THREAD

**Issue by tanichols** [aspnet/SignalR#991]
In the original SignalR, scale out was as simple as saying "UseRedis()" and passing in a 4 part configuration. While I have seen that redis is available as a scale out option, I haven't had much luck finding documentation on how to configure the connection. Any advice? My startup.cs has the following:
```
// Add SignalR
services.AddSignalR();
```
```
// Enable SignalR on `rpc' endpoint
app.UseSignalR(routes =>
{
    routes.MapHub<ChatHub>("rpc");
});
```

**Comment by BrennanConroy** [comment]
This is how you add it.
```
services.AddSignalR().AddRedis(redisOptions =>
{
    redisOptions.Options.EndPoints.Add("connectionId");
});
```

The chatsample can use redis
https://github.com/aspnet/SignalR/blob/72514f39436951ae70649ecfe754a0f365d3b7ff/samples/ChatSample/Startup.cs#L58-L60
But doesn't show any options

**Comment by tanichols** [comment]
Perfect! I kept seeing `EndPoints` in my intellisense, but I thought it was meaning my signalr endpoints, not the endpoint of my redis instance. Perhaps `Server` or `Connection` would be more intuitive.

**Comment by BrennanConroy** [comment]
Well the StackExchange API uses this for its options
https://github.com/StackExchange/StackExchange.Redis/blob/8c94c7b41b231b27d8a9367d8e942bb72b87d81e/StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs#L847

**Comment by moozzyk** [comment]
Looks like this is resolved.

**Comment by HelmuthWcs** [comment]
I tried the proposed solution but I am unable to connect. I am trying this:
`services.AddSignalR().AddRedis(redisOptions =>
{
	redisOptions.Options.EndPoints.Add("xxxxx.redis.cache.windows.net", 6380);
}`
Error is:
> Connection to redis failed

As it fails I also tried to add password with:
`redisOptions.Options.Password = AzureConfig.RedisPassword;`
Error is:
> Connection to redis failed

Also inserting full connection like specified by azure is not working: 
> Message	"Value does not fall within the expected range."	string

I also checked that my credentials are valid with a independent connection 
`services.AddDistributedRedisCache(...)`

Is there no way signalr can get the redis cache from dependency injection?

**Comment by BrennanConroy** [comment]
`AddDistributedRedisCache` and `SignalR.AddRedis` basically use the same connection logic so there is no reason one would work and the other wouldn't. When you say you checked your credentials did you actually use the cache? Because just creating the cache with `AddDistributedRedisCache` doesn't actually start a connection to redis.

**Comment by HelmuthWcs** [comment]
Yes I did test it, here is my test code which works as expected:
`public IActionResult CacheTest()
		{
			string value = _cache.GetString("CacheTime");

			if (value == null)
			{
				value = DateTime.Now.ToString();

				var options = new DistributedCacheEntryOptions();
				options.SetSlidingExpiration(TimeSpan.FromMinutes(1));
				_cache.SetString("CacheTime", value, options);
			}

			string result = "cacheTime: " + value + "\n" + " currentTime: " + DateTime.Now.ToString();

			return Content(result);
		}`
