### ISSUE TITLE
Review  ## HTTP Post (Client-to-Server only) of the spec and make necessary fixes

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#993]
See: https://github.com/aspnet/SignalR/pull/992#issuecomment-334827109

**Comment by AwsomeCode** [comment]
Is it useful for uploading large files? Then it might be required.

**Comment by moozzyk** [comment]
@AwsomeCode - Why would you choose SignalR to upload large files over uploading them with just a POST request? Note that SSE and Long Polling already use POST to send messages so you can just start use the LongPolling or SSE transport to achieve this functionality. This section was about a half transport which kind of optimizes LongPolling for one way connection - i.e. does not create poll requests. Neither of our clients support it and I don't think the server supports either.
