### ISSUE TITLE
Exposing connections list?

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#995]
Should we expose the list of connection to make it easier to be aware of all connected clients? 
Right now someone would have to do something like write their own HubEndpoint and override the OnConnected method and create their own ConnectionList property they would then expose.

**Comment by BrennanConroy** [comment]
The whole point of the presence sample was to show that people can do this if they want.
https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/PresenceHubLifetimeManager.cs

**Comment by mikaelm12** [comment]
Yeah, I get that. I was discussing it with @moozzyk and we were discussing the possibility of making it easier than that.

**Comment by davidfowl** [comment]
Expose it where?

**Comment by moozzyk** [comment]
I think the question here is: "How do I get a list of connections in my hub?". People has been asking this a lot for the old SignalR. The caveat is that I don't think it can work with scaleout.

**Comment by grahamehorner** [comment]
I've been experimenting with scale out where the SignalR hub(s) talk to each other using SignalR itself so in essence a hub becomes a node in a mesh network of hubs and they exchange messages and information there current state/connections etc.
