### ISSUE TITLE
SignalR Documentation

### ISSUE THREAD

**Issue by tanichols** [aspnet/SignalR#996]
I'd like to start working on SignalR documentation. Since SignalR is still in alpha, I don't believe the docs belong in the aspnet/Docs repo. Can I get some guidance on how the team would like to handle documentation? I can do simple .MD pages in root, .MD pages in a docs directory, a gh-pages branch with github pages or something else entirely. Let me know what format the team would like and I'll get started.

**Comment by moozzyk** [comment]
@danroth27 @Rick-Anderson - what is the best place to get started on documentation for SignalR for ASP.NET Core?
@tanichols - I think it would be good to agree on some outline/topics you would like to cover.

**Comment by Rick-Anderson** [comment]
I'll make a SignalR node in https://docs.microsoft.com/en-us/aspnet/core/
@moozzyk  can we use https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr for the intro? @tanichols  could copy that MD then update it for the current version. Ditto for https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/tutorial-getting-started-with-signalr

**Comment by moozzyk** [comment]
https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr will need to be modified quite significantly to be applicable to the new SignalR

**Comment by tanichols** [comment]
I think we should start simple on github. The "announcing SignalR..." Page had great getting started content, I just wanted to add what I've learned working with groups, injecting hubcontext into an API controller, and adding a redis backplane.

**Comment by Rick-Anderson** [comment]
> https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr will need to be modified quite significantly to be applicable to the new SignalR

Yes, but is there anything useful in it to start with? Or should we start totally from scratch? It's usually easier to update an article rather than starting from scratch. 

>The "announcing SignalR..." Page had great getting started content, I just wanted to add what I've learned working with groups, injecting hubcontext into an API controller, and adding a redis backplane.

Work with @moozzyk  on that. I can do a copy/edit/cleanup.

**Comment by moozzyk** [comment]
@Rick-Anderson - Yes, I think https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr could be used as a starting point.

**Comment by tanaka-takayoshi** [comment]
I'd like to focus on a document about backplane. If I should create a new issue, please let me know. As far, Redis is only available for backplane of SignalR, I mean brand-new SignalR for ASP.NET Core), and it's available from NuGet.
https://github.com/aspnet/SignalR/tree/dev/src/Microsoft.AspNetCore.SignalR.Redis

However, there is no documentation for backplane, so I should look into the source code when I want to use it. Is it correct?

**Comment by moozzyk** [comment]
@tanaka-takayoshi - yes, currently there is just source code.

**Comment by moozzyk** [comment]
@Rick-Anderson 

> I'll make a SignalR node in https://docs.microsoft.com/en-us/aspnet/core/

Have you had a chance to do this?

**Comment by Rick-Anderson** [comment]
@moozzyk  done #4732

**Comment by moozzyk** [comment]
Thanks!

**Comment by SamBartlettXOM** [comment]
Hey! I'm looking for documentation on the JS client for SignalR core - has that been worked on yet? I couldn't find anything on it at https://docs.microsoft.com/en-us/aspnet/core/ (or really any documentation on SignalR core at all) - am I looking in the wrong place?

**Comment by anurse** [comment]
> am I looking in the wrong place?

No, you're looking in the right place! We've been busy working on getting Preview 1 ready, so we don't have any docs available there yet. As @moozzyk mentioned, there are blog posts with some documentation. There are also samples in this repo and in https://github.com/aspnet/SignalR-Samples .

**Comment by davidfowl** [comment]
Doc issues are here https://github.com/aspnet/Docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+signalr
